### ISSUE TITLE
CLI fails when project lives in a path that contains spaces

### ISSUE THREAD

**Issue by IndrakumarR** [microsoft/react-native-windows#10001]
![image](https://user-images.githubusercontent.com/78961533/170284910-d26b257e-dfa9-47a4-bd2a-bb121a6a1b37.png)
I got this error , any give me a solution.

_Originally posted by @IndrakumarR in https://github.com/microsoft/react-native-windows/issues/3263#issuecomment-1137320523_

**Comment by asklar** [comment]
you have a space in the root folder "Window app", which is tripping the script. Can you rename that folder to remove the space?

**Comment by jonthysell** [comment]
It looks like there may be something wrong with how we invoke that PS script. @chiaramooney can you look at this?

**Comment by chiaramooney** [comment]
When I test this scenario, my `run-windows` command fails even sooner stating that `run-windows` does not exist. When I remove the ' ' character contained in my path, then `run-windows` is able to be found again. With this, it seems like at large the RNW CLI doesn't support path names with spaces not just within the WindowsStoreAppUtils script. If we want to enable this behavior, we'll have to make changes across all our scripts. @asklar @jonthysell @chrisglein 

Is this still work we want to go after?
