### ISSUE TITLE
Style inheritance for Text components

### ISSUE THREAD

**Issue by twvdb** [microsoft/react-native-windows#1002]
React Native for iOS and Android both have the concept of style inheritance for Text subtrees. However, on Windows this is (currently) not the case.

Example:
```
<Text style={{color: 'red'}}>
    I am red
    <Text>
        I should be red by inheritance
    </Text>
</Text>
```

**Comment by ndbroadbent** [comment]
Yep, I'm also running into this. The workaround is not so bad though, you just need to extend the existing styles with overrides.

```
const mainStyle = {
  // ...
}

const innerStyle = {
  ...mainStyle,
  // override styles
}
```

**Comment by zenVentzi** [comment]
I'm having the same issue without using react-native-windows, so I guess that's coming from the core logic of react-native.
