### ISSUE TITLE
Style TextInput

### ISSUE THREAD

**Issue by alixeb** [Microsoft/react-native-windows#1004]
Hello,

#### Placeholder
At the moment it is not possible to give a color to placeholder. It is always black.
1. Is there a plan to support `placeholderTextColor`?

#### Focus style
Also it looks like when an input receives focus, it always has a white background and black text even when the default style for the input is background transparent with a given color

2. Is there a way to control focus style?

**Comment by meddyrainzo** [comment]
Please can some update be made on this issue. It's been open for most of the year now and nothing has been said about it. Especially the focus styling
