### ISSUE TITLE
how to make a taskbar app? any example?

### ISSUE THREAD

**Issue by cinder92** [Microsoft/react-native-windows#1006]
Is there any example about how to build a task bar app? those right clock.

thanks!

**Comment by rozele** [comment]
I'm not sure I know what you mean by a task bar app, do you have a pointer to documentation?

**Comment by rozele** [comment]
@cinder92 if you mean adding a tray icon for your React Native app, react-native-windows is build for UWP, and I don't think UWP apps support tray icons.  However, this repo also supports a WPF, perhaps @matthargett could comment on if it would be possible to build an app with a tray icon using react-native-wpf.

**Comment by cinder92** [comment]
@rozele  thanks for answering, yep i mean try icon, thanks!

**Comment by Xapphire13** [comment]
Any update on this?

**Comment by rozele** [comment]
Out of scope for this repo - its theoretically possible to embed a react-native app in any XAML app, so assuming you can write a UWP / WPF app that becomes a tray app, then there is no limitation here. Closing.

**Comment by thatsofia** [comment]
>its theoretically possible to embed a react-native app in any XAML app

So that must be what the Xbox app is then? 

Odd that I couldn't find a guide on getting a tray icon... One that has a context menu that supports HiDPI at that too.
