### ISSUE TITLE
Getting "Invalid response for blob" on simple fetch() request.

### ISSUE THREAD

**Issue by fahrulseptiana** [microsoft/react-native-windows#10098]
### Problem Description

I have new boilerplate which is generated by following [this](https://microsoft.github.io/react-native-windows/docs/getting-started) guide, but when I'm trying to make simple fetch data using get "fetch()" error with warning "Invalid response for blob" happened. Well it just a simple fetch.

### Steps To Reproduce

1. Make a new project with [this](https://microsoft.github.io/react-native-windows/docs/getting-started) guide
2. Build a fetch() get request on useEffect react hooks
3. Error happened

### Expected Results

I expect the results is Promise from fetch().

### CLI version

7.0.3

### Environment

```markdown
System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 20.89 GB / 31.87 GB
  Binaries:
    Node: 14.19.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.14.16 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 30, 31, 32
      Build Tools: 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0
      System Images: android-29 | Google Play Intel x86 Atom_64, android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: AI-212.5712.43.2112.8609683
    Visual Studio: 16.11.32510.428 (Visual Studio Community 2019), 17.3.32519.111 (Visual Studio Community 2022)     
  Languages:
    Java: 11.0.12 - C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.0 => 0.68.0
    react-native-windows: 0.68.5 => 0.68.5
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2019

### Build Configuration

Debug

### Snack, code example, screenshot, or link to a repository

![err2](https://user-images.githubusercontent.com/10472373/173202339-7275e68f-a344-4989-90f5-ddad0009f2c5.png)

![err1](https://user-images.githubusercontent.com/10472373/173202311-5c49ac5c-bb04-4524-9c4a-d1510b97254d.png)

**Comment by tero-paananen** [comment]
I have this error now on 0.69.11. Issue did not exist on 0.69.7.
