### ISSUE TITLE
how to use mac

### ISSUE THREAD

**Issue by nextmvp** [microsoft/react-native-windows#10128]

**Comment by nextmvp** [comment]
how to use Mac to develop app when I want to test my app in windows environment?

**Comment by nextmvp** [comment]
should I install a dual system or use some app like parallels?

**Comment by asklar** [comment]
@nextmvp You will need a Windows environment to build a RNW app. You can find some options here: https://microsoft.github.io/react-native-windows/docs/win10-vm

**Comment by nextmvp** [comment]
thanks a lot
