### ISSUE TITLE
Sketch Community Module broken on 0.69

### ISSUE THREAD

**Issue by TatianaKapos** [microsoft/react-native-windows#10122]
### Problem Description

While validating the Gallery app on .69, Sketch Community Module gave this error since React removed ViewPropTypes in 18.0.0.

![image](https://user-images.githubusercontent.com/42554868/173889453-86bc00f7-ec66-45ce-b813-5f9119cc4d44.png)

Should just have to go into the [CM](https://github.com/creambyemute/react-native-sketch-canvas/blob/master/src/SketchCanvas.js#L12) and export the property from a different package

### Steps To Reproduce

1. Bump react-native-gallery to 0.69-preview
2. Run App

### Expected Results

Gallery to run fine.

### CLI version

npx react-native --version

### Environment

```markdown
npx react-native info
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2019

### Build Configuration

Debug

**Comment by creambyemute** [comment]
@asklar Wasn't on my radar because we're still using RN and RNW 0.65.

It looks like a general React/ReactNative related problem and not related to RNW itself. 

There's also a lifecCycle method that should be refactored. I'll have a look into it in the next few days.

**Comment by TatianaKapos** [comment]
@creambyemute Validated with Gallery, issue is fixed with the PR! :)

**Comment by asklar** [comment]
Thanks @creambyemute for the quick fix!

**Comment by creambyemute** [comment]
@TatianaKapos @asklar I've moved the repo to the organization account: https://github.com/wwimmo

**Comment by asklar** [comment]
thanks for the heads up!

**Comment by creambyemute** [comment]
@asklar @TatianaKapos This module is now available via npm (https://www.npmjs.com/package/@wwimmo/react-native-sketch-canvas). I also adapted the README.

Cheers.
