### ISSUE TITLE
cannot run from cmd or through VS Code launch.json (when building on CPU that identifies as ia32)

### ISSUE THREAD

**Issue by fmiskuly-eastman** [microsoft/react-native-windows#10136]
### Problem Description

I have been trying to get my react windows project to build in VS Code for a few days now to no avail. 

I have followed all steps in this tutorial: https://microsoft.github.io/react-native-windows/docs/getting-started but have been matched with many different error messages:

Running the dependency script im told I have all dependencies required, although before manually fixing the visual studio install components, I was receiving an error that my windows was not in the specified range [6.1,6.3] to install some Microsoft packages, not sure if this is the issue. I upgraded my windows to the latest and that specific error went away

![image](https://user-images.githubusercontent.com/83961524/174327797-ded0824c-7209-49ee-b9db-4a5f28f4eda2.png)

In my visual studio installer I have all required components installed: 

![image](https://user-images.githubusercontent.com/83961524/174328202-645dbbaa-3817-4b61-87e6-c2d49a666825.png)

Currently, when launching either through the command line 'npx react-native run-windows' or the launch.json file, Im met with the following error. 

![image](https://user-images.githubusercontent.com/83961524/174329508-ee44aae2-81b5-429e-917b-ca0e73105e22.png)

I am able to run the application by running 'npm start' from a powershell window, and using the [Debug | x64] configuration in Visual Studio, but not being able to run this through the command line indicates to me that something is wrong with the configuration that I would like to fix.

![image](https://user-images.githubusercontent.com/83961524/174336213-eea89bc4-7662-475d-ae03-b214ec02412a.png)

### Steps To Reproduce

1. follow steps in react native tutorial
2. attempt to run in VS Code using launch.json file
3. error
following the react native tutorial on both my personal desktop and work laptop have produced the same errors. 

### Expected Results

ability to run the application using 'npx react-native run-windows'

### CLI version

7.0.3

### Environment

```markdown
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19044
    CPU: (8) ia32 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 7.19 GB / 15.69 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files (x86)\nodejs\node.EXE      
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD    
    npm: 8.11.0 - C:\Program Files (x86)\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.32106.194 (Visual Studio Professional 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.2 => 0.68.2
    react-native-windows: 0.68.5 => 0.68.5
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2019

### Build Configuration

Debug

**Comment by chrisglein** [comment]
Error:
```The specified solution configuration "Debug|ia32" is invalid```

That's not a configuration we'd expect to see. A guess is that you're running the 32 bit version of node, where you should be running the 64 bit version of node. This hypothesis is matched by your environment output above. 
```
Node: 16.15.1 - C:\Program Files (x86)\nodejs\node.EXE  
```
And you can see that node output the architecture as `ia32` here:
```
CPU: (8) ia32 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
```

Your Visual Studio 2019 version also seems to be 32 bit.

The 32 bit version of Node is taking precedence. As a workaround you can try uninstalling Node and then use the dependency script referenced by the getting started walkthrough which will ensure the 64 bit version of Node is installed.

@jonthysell @asklar Can you resolve whether we can support 32 bit node?

**Comment by NickGerleman** [comment]
The ".metaproj" bit points to the issue happening specifically in this script, which was recently added. 

https://github.com/microsoft/react-native-windows/blob/ca34a4691a57fe3bba679ac5786d6302aecd6cd5/packages/%40react-native-windows/cli/powershell/Eval-MsBuildProperties.ps1

**Comment by NickGerleman** [comment]
Bug is this line. Will set arch to ia32 instead of x86. https://github.com/microsoft/react-native-windows/blob/3857727addf3adb0962b3970d91976ee866ee75b/packages/%40react-native-windows/cli/src/runWindows/runWindowsOptions.ts#L75

Can workaround by manually passing "--arch".
