### ISSUE TITLE
Create initial queries to extract raw CLI telemetry data

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#10143]
### Summary

Once the CLI telemetry is enabled and pushing data, it'll exist in an unprocessed form. We need to write some queries to extract that data and transform it into the correct schema, so it can be used to build reports.

### Motivation

The raw data will be available but we'll want a more uniform data set.

**Comment by jonthysell** [comment]
I already have the queries I wrote against the test back-end, so this task should be rather small.

**Comment by jonthysell** [comment]
As we explore 1DS onboarding, the details of this task may change slightly.

**Comment by jonthysell** [comment]
Removing references to AI/Kusto/KQL - the exact technology used for 1DS may be different. (Though I do have some test KQL queries ready for the AI implementation).

**Comment by danielayala94** [comment]
For now, I'm not expecting the need of writing Kusto queries to populate charts, as most stuff can be achieved via UI. I'll close this for now, we can reactivate if we find out there is a need for Kusto stuff.
