### ISSUE TITLE
ScrollEnabled with horizontal=true doesn't disable scroll

### ISSUE THREAD

**Issue by dmbrowne** [microsoft/react-native-windows#1016]
ReactNative 0.37
ReactNativeWindows 0.37

I am trying to disable scrolling for a `ListView` that is using the `horizantal={true}` property, but the `scrollEnabled={false}` prop does not seem to work. However when i remove the horizontal prop and keep the scrollenabled=false prop; it disables the scrolling correctly.

I'm guessing this is a bug not a feature?

**Comment by alixeb** [comment]
@rozele could you please help on this issue.

We have a `ListView` which is using `horizantal={true}`.
The `ListView` displays some cards. The cards are draggable.

When the list has many many cards, the scroll of the list stops the drag event of the card.
This is blocking us for our first release of our app. Any help suggested much appreciated.

**Comment by alixeb** [comment]
Also logged a new issue of react-native repo
https://github.com/facebook/react-native/issues/14057

**Comment by andandandandrew** [comment]
@dmbrowne  @alixeb 

Maybe this is just a typo, but `horizontal` is spelled incorrectly in your message. Good luck!
