### ISSUE TITLE
tintColor Style not supporting PlatformColor

### ISSUE THREAD

**Issue by ayush1397** [microsoft/react-native-windows#10177]
### Problem Description

I am not able to use UWP ResourceDictionary brushes using PlatformColor as a value for tintColor style for images

### Steps To Reproduce

Assign a style of tintStyle to an image with a value as PlatformColor, the app crashes

### Expected Results

The app should not crash and proper color brush mentioned in PlatformColor should be applied

### CLI version

4.14.0

### Environment

```markdown
PS D:\to-do-windows\xplatform> npx react-native info
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz
    Memory: 46.93 GB / 63.66 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.32602.291 (Visual Studio Enterprise 2019)
  Languages:
    Java: Not Found
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^16.13.1 => 16.14.0
    react-native: ^0.63.4 => 0.63.4
    react-native-windows: ^0.63.41 => 0.63.41
  npmGlobalPackages:
    *react-native*: Not Found
```

### Visual Studio Version

Visual Studio 2019

### Build Configuration

DebugBundle

**Comment by chrisglein** [comment]
Crash does not repro on recent-ish versions (verified so far on 0.68). Definitely upgrade off of 0.63 - that's out of our support window. But `tintColor` is not correctly supporting `PlatformColor` still on the newer versions. That's a gap.
