### ISSUE TITLE
WPF animations currently no-op

### ISSUE THREAD

**Issue by GantMan** [Microsoft/react-native-windows#1019]
Glad to have WPF in place, but alas animations are a must!  Performing simple animations (in JavaScript - NOT native drivers) do not work in WPF.

From a 10,000ft view, Animations are provided via shared lib:  https://github.com/ReactWindows/react-native-windows/tree/master/ReactWindows/ReactNative.Shared

So it's likely some small difference in WPF that is causing these to fail.

**Comment by matthargett** [comment]
Fixed bt #1036
