### ISSUE TITLE
Crash when hovering over a Switch component in high contrast mode

### ISSUE THREAD

**Issue by paperbackdragon** [microsoft/react-native-windows#10205]
### Problem Description

When a high contrast theme is active on Windows, if I hover over a Switch component, our React Native Windows app crashes. I've also sometimes noticed a similar (or the same) crash if I have our app open when I enable a high contrast theme.

I also notice that the Switch components don't seem to honor the colors that I have set in our app (which are all hex/rgb, not brushes). Sometimes with the Switch components do this, hovering over them fixes it, but in this case it crashes instead.

Screenshot of the line that's crashing, with local variables and call stack (sometimes it crashes on ToggleSwitchFillOn, sometimes ToggleSwitchFillOff):

<img width="1378" alt="Screen Shot 2022-06-24 at 10 24 36 AM" src="https://user-images.githubusercontent.com/899430/176012979-014c8f71-a28e-4d8e-a7d2-9db3b4576e0d.png">
<img width="1403" alt="Screen Shot 2022-06-24 at 10 30 19 AM" src="https://user-images.githubusercontent.com/899430/176013121-81afb6ec-87c0-4992-a6f0-f1a8fff0382a.png">

### Steps To Reproduce

1. In Windows 11, enable a high contrast theme, such as "Aquatic"
2. Open a React Native Windows app that has a Switch component
3. Hover your mouse over the Switch component
4. App will crash

### Expected Results

Instead, when hovering over a Switch in high contrast, I expect any hover-related styles to be applied to the Switch component.

### CLI version

0.66.0

### Environment

```markdown
System:
    OS: Windows 10 10.0.25131
    CPU: (20) x64 Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz
    Memory: 106.19 GB / 127.71 GB
  Binaries:
    Node: 16.9.1 - D:\CxCache\OneDrive.NodeJS.Windows.1.0.0\tools\nodejs\node.EXE
    Yarn: 1.22.11 - D:\CxCache\OneDrive.NodeJS.Windows.1.0.0\tools\nodejs\yarn.CMD
    npm: 7.21.1 - D:\CxCache\OneDrive.NodeJS.Windows.1.0.0\tools\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.17134.0, 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.32602.291 (Visual Studio Enterprise 2019), 17.2.32602.215 (Visual Studio Enterprise 2022)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.66.0 => 0.66.0
    react-native-windows: 0.66.0 => 0.66.0
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2019

### Build Configuration

Debug

**Comment by paperbackdragon** [comment]
Note that this is a ship-blocking bug for us since we need to have high contrast mode working in order to ship to customers.

**Comment by paperbackdragon** [comment]
Link to crash dump and relevant pdb files: https://microsoft-my.sharepoint-df.com/:u:/p/heath/EabeziIrxYRLs-N975XgBDYBerC7pascu1dI8NRap56n0A?e=5x5yia

**Comment by asklar** [comment]
we have a Teams thread on this, possible fix in PR #10219

**Comment by chiaramooney** [comment]
@paperbackdragon Circling back to this bug specifically. Was Alex's patch able to work for you?

**Comment by chiaramooney** [comment]
Removing assignee as work is now on the backlog and I will most likely not get to in the near future. In addition, migration to Fabric means this may not be work that is fixed on Paper.

**Comment by chiaramooney** [comment]
Closing issue now that new arch is in experimental phase.
