### ISSUE TITLE
pagingEnabled missing in ScrollView

### ISSUE THREAD

**Issue by mroswald** [microsoft/react-native-windows#1020]
The native implementation lacks the property/mechanism [`pagingEnabled`](https://facebook.github.io/react-native/docs/scrollview.html#pagingenabled) on windows side. Is it possible to implement it?

Btw it's mentioned in the javascript interface: https://github.com/ReactWindows/react-native-windows/blob/master/Libraries/Components/ScrollView/ScrollView.windows.js#L241

**Comment by kevinvangelder** [comment]
@mroswald Are you trying to use UWP (Windows 10), WPF (Windows 7/8), or both?

**Comment by mroswald** [comment]
UWP Windows 10
