### ISSUE TITLE
Support react-native-app-auth

### ISSUE THREAD

**Issue by mattyancheksonos** [microsoft/react-native-windows#10220]
### Module

react-native-app-auth

### Module repo url

https://github.com/FormidableLabs/react-native-app-auth

### Target Version

0.63+

### Existing issue url

https://github.com/FormidableLabs/react-native-app-auth/issues/740

### Existing windows implementation?

- [ ] Legacy/C# implementation

### Which app/customer is requesting this module?

Sonos

### In what scenarios will this module be used?

Authentication via OAuth 2.0 Specifications as well as OpenID Connect Specifications.  Provides support for a wide variety of OAuth providers.

### Essential Features

Authorization (Authorization Code),
Token Refresh,
Token Revoke,
Logout

**Comment by asklar** [comment]
thanks for filing @mattyancheksonos. Putting this in the backlog for now. Feel free to send a PR to that repo.

**Comment by chrisglein** [comment]
Closing this module request as not in plan. Not that this module _shouldn't_ receive a Windows implementation, but it makes more sense to track that request on the module's repo rather this repo.
