### ISSUE TITLE
winrt/Microsoft.ReactNative.h no such file

### ISSUE THREAD

**Issue by atikulbd** [microsoft/react-native-windows#10258]
### Problem Description

I'm new to React Native Windows development.
My development OS: **Windows 10 Edu x64bit** (Up-to-date)
Visual Studio version: 2019
I've installed the development dependencies using rnw-dependencies.ps1 script successfully with all OK.
I've tested with Win SDK versions both 10.0.18362.0 and 10.0.19041.0 + React Native Win versions 0.67 and 0.69.
I've created a fresh RNW project following all procedures in React Native Windows official doc.
**Here's my commands:**

`npx react-native init TestWin --template react-native@^0.67.0`
`cd TestWin`
`npx react-native-windows-init --overwrite`
`npx react-native run-windows`

But my build fails and it generates error that **winrt/Microsoft.ReactNative.h** header file is not found. I looked inside **C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\winrt** and **C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\winrt** folders but there's no such file named **Microsoft.ReactNative.h**.
Please help. My OS is updated to latest updates (Win 10 Edu).

### Steps To Reproduce

Please read the description.

### CLI version

6.4.0

### Environment

```markdown
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i5 CPU         650  @ 3.20GHz
    Memory: 4.55 GB / 7.80 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0, 10.0.20348.0
  IDEs:
    Android Studio: AI-212.5712.43.2112.8609683
    Visual Studio: 16.11.32602.291 (Visual Studio Community 2019)
  Languages:
    Java: 11.0.15.1 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.67.0 => 0.67.0
    react-native-windows: 0.67.13 => 0.67.13
  npmGlobalPackages:
    *react-native*: Not Found
info React Native v0.69.1 is now available (your project is running on v0.67.0).
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2019

### Build Configuration

Debug

**Comment by asklar** [comment]
There is likely a build error happening before we even get to trying to include that header.
can you run `npx react-native run-windows --logging` and share the build output?
