### ISSUE TITLE
Need backport for "Fix floating point conversions in non en-US locales"

### ISSUE THREAD

**Issue by paperbackdragon** [microsoft/react-native-windows#10272]
### Problem Description

We're looking for this PR fix to be ported to 0.68: https://github.com/microsoft/react-native-windows/pull/10058

It's unlikely we'll upgrade to 0.70 anytime soon so having this in 0.68 (which we're upgrading to soon) will make development easier.

Original discussion on Teams before the fix was written: https://teams.microsoft.com/l/message/19:ea7692fed931434db524836878adf9df@thread.skype/1654124763305?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=8034415f-bc0a-4b5d-9453-78ee27e16b22&parentMessageId=1654124763305&teamName=React%20Native%20%40Microsoft&channelName=React%20Native%20Windows&createdTime=1654124763305

### Steps To Reproduce

Note we were on RNW 0.66.0 when we first saw this issue, using Hermes and XAML islands.

1. Turn on React Native dev/debug mode
2. Change app language to German (or other language that uses commas as decimal notation)
3. Run app
4. See this error in the UI:
<img width="682" alt="MicrosoftTeams-image (21)" src="https://user-images.githubusercontent.com/899430/179613350-d7488ba3-75c5-4fef-b0ed-38c4552cf900.png">

### Expected Results

App runs normally, with our translated strings visible 

### CLI version

6.4.0

### Environment

```markdown
System:
    OS: Windows 10 10.0.25158
    CPU: (20) x64 Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz
    Memory: 108.80 GB / 127.71 GB
  Binaries:
    Node: 16.9.1 - D:\CxCache\OneDrive.NodeJS.Windows.1.0.0\tools\nodejs\node.EXE
    Yarn: 1.22.11 - D:\CxCache\OneDrive.NodeJS.Windows.1.0.0\tools\nodejs\yarn.CMD
    npm: 7.21.1 - D:\CxCache\OneDrive.NodeJS.Windows.1.0.0\tools\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.17134.0, 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.32602.291 (Visual Studio Enterprise 2019), 17.2.32602.215 (Visual Studio Enterprise 2022)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.66.0 => 0.66.0
    react-native-windows: 0.66.0 => 0.66.0
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2019

### Build Configuration

Debug

**Comment by asklar** [comment]
@TatianaKapos will backport this

**Comment by TatianaKapos** [comment]
backported into .69 and .68 :)
