### ISSUE TITLE
Move CoreApp sample to a new sample package

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#10283]
> I don't think you should just dump this CoreApp sample in a subfolder of playground. If you want to prove that it works/builds, Either convert an existing app package to CoreApp (I don't see any likely candidates), or create a new private sample app package.

_Originally posted by @jonthysell in https://github.com/microsoft/react-native-windows/pull/9936#discussion_r891511568_

**Comment by chrisglein** [comment]
CoreApp is being used as inspiration for how our new Fabric app templates will work. But it won't carry forward in the same form. So the correct action here (for Paper) is to delete this rather than move it, and the Fabric app template will supersede it.

**Comment by jonthysell** [comment]
CoreApp is gone.
