### ISSUE TITLE
Getting error: The command npx react-native autolink-windows exited with code 9009

### ISSUE THREAD

**Issue by marek8623** [microsoft/react-native-windows#10286]
### Problem Description

I am following the steps based on this manual:
https://microsoft.github.io/react-native-windows/docs/getting-started#building-a-standalone-react-native-windows-app

But I am getting the following error:
_The command "npx react-native autolink-windows --check --sln "windows\projectName.sln" --proj "windows\projectName\projectName.vcxproj"" exited with code 9009._

### Steps To Reproduce

1. npx react-native-windows-init --overwrite
2. opening solution in visual studio code
3. Project > Publish > Create App Packages

### Expected Results

Builded a standalone React Native Windows App that I can install on Windows tablet.

### CLI version

7.0.4

### Environment

```markdown
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz
    Memory: 5.84 GB / 15.39 GB
  Binaries:
    Node: 14.17.0 - ~\.nvm\versions\node\v14.17.0\bin\node.EXE
    Yarn: 1.22.19 - ~\.nvm\versions\node\v14.17.0\bin\yarn.CMD
    npm: 6.14.13 - ~\.nvm\versions\node\v14.17.0\bin\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.32602.291 (Visual Studio Community 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.1 => 0.68.1
    react-native-windows: 0.68.9 => 0.68.9
  npmGlobalPackages:
    *react-native*: Not Found
```

### Visual Studio Version

Visual Studio 2019

**Comment by asklar** [comment]
Is your project named `projectName`?
Error 9009 means something (likely the "npx" command) was not able to be executed.
If you open a developer command prompt and try to run that command, do you get an error? 
> `npx react-native autolink-windows --check --sln "windows\projectName.sln" --proj "windows\projectName\projectName.vcxproj`
