### ISSUE TITLE
UIExplorer on WPF

### ISSUE THREAD

**Issue by kevinvangelder** [Microsoft/react-native-windows#1030]
I'm adding WPF support to UIExplorer but I'm getting `Unable to get property "Constants" of undefined or null reference` and I can't track down it's source. It's entirely possible that it's because the javascript is trying to use modules that don't exist in RNW WPF (yet) but it's odd I can't definitively point to any section of code.

**Comment by rozele** [comment]
@kevinvangelder do you have a branch, if I get some time I could try to repro / help debug

**Comment by kevinvangelder** [comment]
I don't currently have a branch since I'm working on the submodule and I'm not confident in my ability to do so without screwing things up. Here is the redbox I'm getting.

![constants crash](https://cloud.githubusercontent.com/assets/1771152/23272575/9911fe46-f9b0-11e6-99c5-f392fd5661bb.PNG)

**Comment by rozele** [comment]
@kevinvangelder you can commit to the submodule and push that branch to your personal GitHub repo.  To roll back that commit, you just need to reset the Example submodule pointer from the main repo:
```
git reset Examples
git checkout Examples
git submodule update
```

**Comment by sayar** [comment]
@kevinvangelder has this issue been resolved?

**Comment by kevinvangelder** [comment]
I think the particular example project I was having this problem with went away in a recent RN update.
