### ISSUE TITLE
Different behavior for `borderRadius` on Windows than other platforms

### ISSUE THREAD

**Issue by rozele** [microsoft/react-native-windows#10335]
### Problem Description

On all other RN platforms, `borderRadius` is clamped to 50% of the minimum dimension of the view (width or height).

On Windows, `borderRadius` will produce an oval shape.

### Steps To Reproduce

1. In any test app, add the following view:
```
<View style={{width: 20, height: 50, borderRadius: 100, backgroundColor: 'blue"}} />
```
2. Notice that on Windows, this produces an oval shape:
![image](https://user-images.githubusercontent.com/1106239/181568622-3228a9e6-4f3a-41d6-a34c-d4aeee33e4f2.png)

### Expected Results

Here is what the same code looks like on other platforms:
|macOS|Android|Web|
|-|-|-|
|![image](https://user-images.githubusercontent.com/1106239/181568870-d1c50a1c-2504-4ef0-a6bb-9ce6d4a2de35.png)|![image](https://user-images.githubusercontent.com/1106239/181569522-daba8d02-a180-4fe0-a3f8-9bb9ad715472.png)|![image](https://user-images.githubusercontent.com/1106239/181569102-e3fc6d8e-9f19-4eae-97ff-e9cf1741ac1c.png)|

### CLI version

npx react-native --version

### Environment

```markdown
npx react-native info
```

**Comment by PPatBoyd** [comment]
Happened to stumble on this issue, curiously enough the clamping is only done on web when using pixel values; when using percent values for borderRadius (which RN does not currently support) it does not clamp and creates an oval:

<img width="177" alt="image" src="https://user-images.githubusercontent.com/41588892/184428203-4ac3bd2f-0481-401b-8d72-fb39eb56dc64.png">


Noting it here cause it's interesting and just in case supporting % units for borderRadius is in RN's future :)

HTML: 
`<!DOCTYPE html><html><head><style> 
h2 { margin-top: 50px; }
#example1 {
  border: 2px solid red;
  width: 20px;
  height: 50px;
  border-radius: 50%; }
#example2 {
  border: 2px solid red;
  width:20px;
  height:50px;
  border-radius: 100px; }
</style></head>
<body>
<h2>border-radius: 50%:</h2>
<div id="example1" />
<h2>border-radius: 50px:</h2>
<div id="example2" />
</body></html>
`
