### ISSUE TITLE
PR checks allow changelists with invalid comment field

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#10333]
### Problem Description

The PR #10306 made some small changes to RNW, and included a changelog file with type: none and an invalid comment. This is causing errors to be reported when creating new changelog files with `yarn change`.

```
C:\code\rnw>yarn change
yarn run v1.22.18
$ beachball change
Checking for changes against "upstream/main"
fetching latest from remotes "upstream/main"
Found changes in the following packages:
  react-native-windows
Error transforming C:\code\rnw\change\react-native-windows-dd0c144f-9d1d-455c-b871-a45c09942d29.json: TypeError: comment.match is not a function
fetching latest from remotes "upstream/main"
```

Source JSON: 
```json
{
  "type": "none",
  "comment": {
    "title": "",
    "value": ""
  },
  "packageName": "react-native-windows",
  "email": "hpratt@microsoft.com",
  "dependentChangeType": "none"
}
```

1. We should make sure (if possible) that you can't select `None` as a change type.
2. If we can't prevent "none" from being selected, maybe our checks should reject `none` as a change.
3. We should make sure our checks validate that changelogs are acceptable (not blank or the wrong type).

### Steps To Reproduce

1. Run `yarn change`

### CLI version

npx react-native --version

### Environment

```markdown
npx react-native info
```

**Comment by chrisglein** [comment]
Feedback from triage: None is valid here, but the PR can absolutely check the other fields, and we can try to figure out how this being used incorrectly.
