### ISSUE TITLE
WPF requires run in x86 before x64 will run

### ISSUE THREAD

**Issue by kevinvangelder** [Microsoft/react-native-windows#1033]
If you completely clean a project (delete everything in `windows/packages`, `windows/mywpfproj/bin`, and `windows/mywpfproj/obj`) and try to run the application in x64, you'll get a `BadSystemImageFormat` exception. Running the app in x86 and then in x64 resolves this issue. Something in the x86 build process doesn't happen in the x64 build process.

**Comment by rozele** [comment]
@kevinvangelder is this something wrong with the .csproj configuration again?  Did you ever get to the bottom of this?

**Comment by kevinvangelder** [comment]
I don't know. Unfortunately I haven't had a chance to try to debug it yet, but I might get a chance in the next few weeks.

**Comment by sayar** [comment]
@kevinvangelder has this issue been resolved?

**Comment by kevinvangelder** [comment]
I haven't run in to this in a long time, so it's probably okay to close until someone hits it again.
