### ISSUE TITLE
How can we make popup view scrollable in react native windows?

### ISSUE THREAD

**Issue by aykejriw** [microsoft/react-native-windows#10399]
I am trying to use pop-up as a modal for react-native windows. I have a use case where my modal/pop-up should be scollable. 

Is there a way I can acheive this in react-native windows?

**Comment by chrisglein** [comment]
What have you tried? You should be able to include a scroll view in a popup just fine. Do you have some sample code you've tried?

**Comment by aykejriw** [comment]
@chrisglein I used scrollview, but I am getting below erros.

`error: ..\..\node_modules\react-native-reanimated\src\index.ts: C:\work\XS.SDX.Settings\node_modules\react-native-reanimated\src\index.ts: Export namespace should be first transformed by `@babel/plugin-proposal-export-namespace-from`.
  5 | export * from './reanimated1';
  6 | export * from './reanimated2';
> 7 | export * as default from './Animated';`

**Comment by aykejriw** [comment]
ScrollView from react-native-windows working. I was importing scrollview from react-native previously. Closing the issue
