### ISSUE TITLE
Implement native mechanism for invoking the yellowbox (console.warn)

### ISSUE THREAD

**Issue by pre10der89** [microsoft/react-native-windows#1039]
There is currently no way to invoke a yellow box (console.warn) from native code... This will allow a developer to issue a warning from the native code when something is not supported... That warning will show in DEBUG, but will be ignored in RELEASE mode...  This is in place of throwing an exception and/or adding DEBUG vs. RELEASE conditionals...

**Comment by rozele** [comment]
I've changed my mind on this. Generally speaking, it should always be possible to trigger the warning from JavaScript.  We could easily implement the YellowBox warning for https://github.com/ReactWindows/react-native-windows/issues/1040 if we just know what version of the OS is being used in the JavaScript module, e.g., from the Platform.windows.js module.
