### ISSUE TITLE
How to set background blur for popMenu?

### ISSUE THREAD

**Issue by aykejriw** [microsoft/react-native-windows#10401]
I have a case where i want to set some controls on pop-up. I want to set the focus on pop-up and darkened the area outside of it.

Is there a way I can achieve this in pop-up for react native windows?

**Comment by chrisglein** [comment]
For questions we recommend either our [Discussions](https://github.com/microsoft/react-native-windows/discussions) board or StackOverflow. As this doesn't seem to be a seem to be an issue that matches our issue templates, I'm going to close this out and direct you there.
