### ISSUE TITLE
Show yellowbox warning when UWP TextInput placeholderTextColor is used

### ISSUE THREAD

**Issue by pre10der89** [Microsoft/react-native-windows#1040]
The placeholderTextColor property is not supported in the UWP TextInput control... Setting this property is a no-op with no warning to the developer that the property is not supported... 

When #1039 is implemented a warning should be emitted from the placeholder color property setters for TextInput and PasswordBox

**Comment by rozele** [comment]
We either need:
a) the *.wpf.js moniker
b) something in Platform.windows.js that lets us know what version of the OS is being used.

If we have the version of the OS, we can emit the console.warning from JavaScript directly.

**Comment by sayar** [comment]
@rozele can you confirm if this has been resolved?

**Comment by rozele** [comment]
This has not been resolved. We still have issues where we should warn for props that people might expect to work but don't (yet they still want confirmation that it not working is "expected" behavior)

**Comment by rozele** [comment]
Fixing placeholder text color on UWP.
