### ISSUE TITLE
Getting Build error even after installing tool kit

### ISSUE THREAD

**Issue by chzappsinc** [microsoft/react-native-windows#10465]
### Problem Description

I am getting error
buildd failed with message C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(460,5): error MSB8020: The build tools for Visual Studio 2015 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, please install Visual Studio 2015 build tools. Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".`

But i have installed 2015 Build Tools

![Screenshot 2022-08-28 025230](https://user-images.githubusercontent.com/65512279/187048720-bc8650af-9ac8-4328-8f67-45e721e81f5c.png)

### Steps To Reproduce

-

### CLI version

8.0.6

### Environment

```markdown
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 6.43 GB / 15.73 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.13.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 25, 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.0, 29.0.2, 30.0.2, 30.0.3, 31.0.0
      System Images: android-30 | Google APIs Intel x86 Atom, android-Tiramisu | Google APIs Intel x86 Atom_64
      Android NDK: 22.1.7171670
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.16299.0, 10.0.17134.0, 10.0.17763.0, 10.0.18362.0, 10.0.19041.0, 10.0.20348.0, 10.0.22000.0, 10.0.22621.0
  IDEs:
    Android Studio: AI-212.5712.43.2112.8815526
    Visual Studio: 16.11.32802.440 (Visual Studio Community 2019), 17.3.32819.101 (Visual Studio Community 2022)
  Languages:
    Java: 11.0.15 - C:\Program Files\Eclipse Adoptium\jdk-11.0.15.10-hotspot\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: 0.69.5 => 0.69.5
    react-native-windows: 0.69.6 => 0.69.6
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Platform Version

10.0.15063

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

Debug

**Comment by chzappsinc** [comment]
@chrisglein Any solution? 

Build success when i manually re targeted solution

**Comment by chrisglein** [comment]
The error message is misleading. It was unable to find your toll set and it went looking elsewhere. The error is much later down the chain. We predict that you're missing the 142 UWP tool set. Can you run the dependency script and see what you get?
https://microsoft.github.io/react-native-windows/docs/rnw-dependencies#install-the-development-dependencies

**Comment by chzappsinc** [comment]
@chrisglein 

```
Checking Free space on C: > 15 GB                            OK
Checking Installed memory >= 16 GB                           OK
Checking Windows version > 10.0.16299.0                      OK
Checking Developer mode is on                                OK
Checking Long path support is enabled                        OK
Checking Choco                                               OK
Checking git                                                 OK
Checking Compilers, build tools, SDKs and Visual Studio      OK
Checking NodeJS LTS                                          OK
Checking Chrome                                              OK
Checking Yarn                                                OK
Checking .net core 3.1                                       OK
All mandatory requirements met
```

**Comment by chrisglein** [comment]
With multiple side by side VS installs it's possible that the dependency script is finding one but the build is finding another.
Is it at all possible to reduce down to one VS install (2019 or 2022) for you? Not ideal as that should work, but as a workaround maybe that unblocks you?

You can also check in the VS installer for each if the dependency is installed for one but not the other.
