### ISSUE TITLE
Is possible to react-native to communicate c# side with REST?

### ISSUE THREAD

**Issue by MongkonEiadon** [Microsoft/react-native-windows#1048]
Could I connect react part (View) to the existing c# (Models) with REST service inside same application, I plan to run in-app background as Server and use react to render the view from that models

**Comment by rozele** [comment]
@MongkonEiadon There are a number of ways you can do this. 

You can create a custom component type (View) in C# from the [ViewManager abstraction](https://github.com/ReactWindows/react-native-windows/blob/master/docs/NativeComponentsWindows.md). From the custom component you can do whatever you want to integrate with your in-app background server. However, the custom component logic typically is triggered on the UI thread, and communication with the background server would be asynchronous, so you may want to avoid this.

I think the "React Native way" to do this is to create a [native module in C#](https://github.com/ReactWindows/react-native-windows/blob/master/docs/NativeModulesWindows.md). You can make the native methods on the module asynchronous by appending an `IPromise` argument as the last function parameter, and then consume the API as a promise in JavaScript. From JavaScript, you would just make the native method calls, await the promise result, and update your components props.
