### ISSUE TITLE
Changing pointerEvents from "none" back to "box-none" doesn't restore pointer events

### ISSUE THREAD

**Issue by juhasuni** [microsoft/react-native-windows#10493]
### Problem Description

If you set the `pointerEvents` prop to "none" this effectively blocks all pointer events for view and its descendants. Setting it back to "box-none" should restore the events to descendants but instead it keeps blocking the events for the entire view tree.

As a result for instance back button in popular navigation library `react-navigation` stops working after you've navigated to another screen and used the back button once. This is because react-navigation blocks all pointer events for the previous screen's header and tries to restore them when you come back to the screen, but because of the bug mentioned the events are never restored.

### Steps To Reproduce

You can try this simple example to reproduce the issue:

```ts
import React, { useState } from 'react';
import { Button, View } from 'react-native';

const HitTest = () => {
  const [value, setValue] = useState<'none' | 'box-none'>('box-none');

  console.log('Value:', value);

  return (<View style={{
    flex: 1, alignItems: 'center', justifyContent: 'center'
  }}>
    <View pointerEvents={value}><Button title='Test' onPress={() => console.log('Success!')} /></View>
    <Button title='Toggle' onPress={() => setValue((prev) => prev === 'box-none' ? 'none' : 'box-none')} />
  </View >);
};

export default HitTest;
```

Restoring from "none" to "auto" seems to work flawlessly.

### Expected Results

The view's descendants should receive pointer events.

### CLI version

7.0.4

### Environment

```markdown
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 20.39 GB / 31.90 GB
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.32802.440 (Visual Studio Community 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: 0.69.4 => 0.69.4
    react-native-windows: 0.69.2 => 0.69.2
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2019

### Build Configuration

Debug

**Comment by juhasuni** [comment]
Looking at the code I'd say that the bug is in this `if` clause, or better, the lack of `else` clause:
https://github.com/microsoft/react-native-windows/blob/0512b19c41d76e618411f3503a79d9ebebe5ccae/vnext/Microsoft.ReactNative/Views/ViewManagerBase.cpp#L274

The `IsHitTestVisible` is never set back to `true`, so the fix could be something like:
```c++
if (iter != pointerEventsMap.end()) {
  nodeToUpdate->m_pointerEvents = iter->second;
  if (nodeToUpdate->m_pointerEvents == PointerEventsKind::None) {
    if (const auto uiElement = nodeToUpdate->GetView().try_as<xaml::UIElement>()) {
      uiElement.IsHitTestVisible(false);
    }
  } else {
    if (const auto uiElement = nodeToUpdate->GetView().try_as<xaml::UIElement>()) {
      uiElement.IsHitTestVisible(true);
    }
  }
}
```

This can be written in a simpler form, but at least it is easy to see the fix when written like this.

**Comment by rozele** [comment]
Yup. Good catch :)
