### ISSUE TITLE
Implement AccessibilityInfo module

### ISSUE THREAD

**Issue by rozele** [Microsoft/react-native-windows#1051]
React Native iOS and Android have an AccessibilityInfo native module:
* https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/modules/accessibilityinfo/AccessibilityInfoModule.java
* https://github.com/facebook/react-native/blob/643925b41d02c67c14d3f24032bfc3d3c9ee3bfb/Libraries/Components/AccessibilityInfo/AccessibilityInfo.ios.js
* https://github.com/facebook/react-native/blob/643925b41d02c67c14d3f24032bfc3d3c9ee3bfb/Libraries/Components/AccessibilityInfo/AccessibilityInfo.android.js

We'll need something similar for Windows.

**Comment by abhivijay96** [comment]
There are multiple accessibility featutres here 
https://docs.microsoft.com/en-us/windows/uwp/accessibility/accessibility
I couldn't find the touch exploration in UWP like in android.
Can you please let me know which specific feature to implement.
Thank you

**Comment by abhivijay96** [comment]
can you please let me know if anybody could find touch exploration in UWP.
Thanks.

**Comment by rozele** [comment]
Useful pointer to docs from dupe issue - http://facebook.github.io/react-native/releases/0.43/docs/accessibilityinfo.html#accessibilityinfo.

**Comment by rozele** [comment]
Closed by #1443 (I think).
