### ISSUE TITLE
Z-Index example on UIExplorer <View> example fails

### ISSUE THREAD

**Issue by rozele** [Microsoft/react-native-windows#1052]
```
Unable to get property 'onStartShouldSetResponderCapture' on undefined or null reference
```

Additionally, the stack trace is not converted to the actual line numbers.

**Comment by rozele** [comment]
From debugging, it looks like it may be a bug in react@16.0.0-alpha. The bug only occurs when you click on the Z-Index "number", as the virtual text element should have type "string" (as referenced [here](https://github.com/facebook/react-native/blob/fd4ad6ca82676e4f63bad26eb0869981439ba106/Libraries/Renderer/src/renderers/shared/shared/event/EventPluginHub.js#L141)), but it actually has type "number".

**Comment by rozele** [comment]
Filed two issues against `react-native`, where I think the origin of the bugs is:
https://github.com/facebook/react-native/issues/12749
https://github.com/facebook/react-native/issues/12750

**Comment by IanVS** [comment]
I'm not using `react-native-windows`, but I came across what seems to be this same issue in my own app.  FWIW, upgrading to `react-native@0.45.0-rc.2` and `react@16.0.0-alpha.12` seems to have resolved it for me.

**Comment by rozele** [comment]
Closing as dupe of #1131
