### ISSUE TITLE
Nuget restore is not working on or after 0.68

### ISSUE THREAD

**Issue by sakthivel-servicemax** [microsoft/react-native-windows#10538]
### Problem Description

Getting below error during nuget restore which was working fine in 0.67.

 NU1201: Project ReactNativePicker is not compatible with uap10.0.17763 (UAP,Version=v10.0.17763). Project ReactNativePicker supports: native (native,Version=v0.0)
    NU1201: Project ReactNativeBlobUtil is not compatible with uap10.0.17763 (UAP,Version=v10.0.17763). Project ReactNativeBlobUtil supports: native (native,Version=v0.0)
    NU1201: Project ReactNativeCameraCPP is not compatible with uap10.0.17763 (UAP,Version=v10.0.17763). Project ReactNativeCameraCPP supports: native (native,Version=v0.0)
    NU1201: Project RNLocalize is not compatible with uap10.0.17763 (UAP,Version=v10.0.17763). Project RNLocalize supports: native (native,Version=v0.0)
    NU1201: Project RCTPdf is not compatible with uap10.0.17763 (UAP,Version=v10.0.17763). Project RCTPdf supports: native (native,Version=v0.0)
    NU1201: Project Microsoft.ReactNative is not compatible with uap10.0.17763 (UAP,Version=v10.0.17763). Project Microsoft.ReactNative supports: native (native,Version=v0.0)

Please help us to sort out this issue.

### Steps To Reproduce

Our App is in live. Currently we have react native windows version 0.67.4.

Now upgrading it to 0.69. Getting the error on nuget restore as mentioned in problem description.

### CLI version

8.0.6

### Environment

```markdown
System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 2.82 GB / 5.98 GB
  Binaries:
    Node: 14.19.3 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.10.2 - ~\AppData\Roaming\npm\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.32802.440 (Visual Studio Community 2019)
  Languages:
    Java: 1.8.0_302 - C:\Program Files\Eclipse Foundation\jdk-8.0.302.8-hotspot\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.69.4 => 0.69.4
    react-native-windows: 0.69.6 => 0.69.6
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2019

### Build Configuration

Release

**Comment by asklar** [comment]
@JunielKatarn FYI

**Comment by JunielKatarn** [comment]
Hi @sakthivel-servicemax.
This seems like a configuration issue (MSBuild properties).

Is your app open-source?
If so, can you point us to the branch you are working on for the upgrade?

**Comment by jonthysell** [comment]
Is your app C# or C++?

**Comment by JunielKatarn** [comment]
> Hi @JunielKatarn, Sorry, ours is not open-source. If i change the react-native-windows version to 0.67, nuget restore is working fine. But changing it to 0.68/0.69, it is not working.

Noted. If your app has C++ dependencies, have you tried the steps documented here?
https://microsoft.github.io/react-native-windows/docs/managing-cpp-deps

**Comment by sakthivel-servicemax** [comment]
@JunielKatarn Thanks for the reference. I collected all packages.config, added to main project and installed through command. Even though it throws errors on nuget restore, we ignore it and Project building is fine now.
