### ISSUE TITLE
SpeechRecognizer.RecognizeAsync() crashes app

### ISSUE THREAD

**Issue by ClaudiuHBann** [microsoft/react-native-windows#10540]
### Problem Description

I am trying to do some speech recognition in react native for desktop and hololens 2 using the SpeechRecognition API provided in C++, but the same code (I will provide the code below) works in a winui and uwp projects but not in a react native one. (crashes the app)

### Steps To Reproduce

1. create the default react-native-windows project (https://microsoft.github.io/react-native-windows/docs/getting-started)
2. create a simple module and use the SpeechRecognition API

### Expected Results

Like in a UWP to listen the input for microphone and output the words I am saying.

### CLI version

8.0.6

### Environment

```markdown
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 AMD Ryzen 7 4800H with Radeon Graphics
    Memory: 9.78 GB / 15.36 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0, 10.0.20348.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 17.3.32825.248 (Visual Studio Community 2022)
  Languages:
    Java: 11.0.12 - C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop, HoloLens

### Visual Studio Version

Visual Studio 2022

### Build Configuration

Debug

### Snack, code example, screenshot, or link to a repository

I use the module:

```
#pragma once

#include "pch.h"

#include <winrt/Windows.Media.SpeechRecognition.h>
#include <winrt/Windows.Media.Capture.h>
using namespace winrt;

#include <functional>
#include <string>
using namespace std;

#include "NativeModules.h"

namespace NativeModuleSample
{
  REACT_MODULE(FancyMath);
  struct FancyMath
  {
    REACT_METHOD(Listen);
    ::winrt::fire_and_forget Listen(::std::function<void(::std::string)> callback) noexcept {
      co_await ::winrt::resume_background();

      static ::winrt::Windows::Media::SpeechRecognition::SpeechRecognizer speechRecognizer = nullptr;
      if (!speechRecognizer) {
        speechRecognizer = ::winrt::Windows::Media::SpeechRecognition::SpeechRecognizer();
        co_await speechRecognizer.CompileConstraintsAsync();
      }

      auto speechRecognitionResult = co_await speechRecognizer.RecognizeAsync();
      callback("You said: " + to_string(speechRecognitionResult.Text()));
    }
  };
}
```

I call the Listen method from the react native, and then the call to speechRecognizer.RecognizeAsync() crashes the app with the following output:

![image](https://user-images.githubusercontent.com/78564392/189497812-cc48ec74-2d53-41ed-972a-ec70941f2673.png)

**Comment by asklar** [comment]
the issue here is that the methods you are calling are async, I think co_await works inside of REACT_METHOD only when you have a ReactPromise as a callback param, see: https://microsoft.github.io/react-native-windows/docs/native-modules-async#simplehttpmodule-in-cwinrt

**Comment by ClaudiuHBann** [comment]
Ok so I tried what you said like:

Module in C++
```
REACT_METHOD(ExplicitPromiseMethod);
    winrt::fire_and_forget ExplicitPromiseMethod(winrt::Microsoft::ReactNative::ReactPromise<std::string> const result) noexcept {
      try {
        static ::winrt::Windows::Media::SpeechRecognition::SpeechRecognizer speechRecognizer = nullptr;
        if (!speechRecognizer) {
          speechRecognizer = ::winrt::Windows::Media::SpeechRecognition::SpeechRecognizer();
          co_await speechRecognizer.CompileConstraintsAsync();
        }

        auto speechRecognitionResult = co_await speechRecognizer.RecognizeAsync();
        result.Resolve("You said: " + to_string(speechRecognitionResult.Text()));
      } catch (const std::exception& ex) {
        result.Reject(ex.what());
      }
    }
```

Module in JS:
```
+ExplicitPromiseMethod: () => Promise<string>;
```

Using the module in JS:
```
FancyMath.ExplicitPromiseMethod()
  .then(result => console.log(result))
  .catch(error => console.log(error));
```

And still the same thing:
![image](https://user-images.githubusercontent.com/78564392/189600262-090f6e8c-1696-41ab-a5cf-c91435cd6095.png)

**Comment by ClaudiuHBann** [comment]
Wow, I am so stupid, the code was not the problem, I needed to enable the microphone capability from the appx manifest like in here : https://stackoverflow.com/questions/45008609/uwp-speech-recognition

I apologize for the inconvenience. :)
