### ISSUE TITLE
Hermes.exe is not supporting for Windows Server 2016

### ISSUE THREAD

**Issue by sakthivel-servicemax** [microsoft/react-native-windows#10571]
### Problem Description

We have a dedicated Windows Server Machine for build generation 
Below is the machine configuration.

<img width="535" alt="image" src="https://user-images.githubusercontent.com/23378397/190046817-66a48c73-2f0f-4bca-97df-9fccc6696038.png">

We have react-native-windows version 0.69.6 for our project. On build creation, Hermes.exe is generating binary file. This is working fine in our local machine. But the same is not working in our server machine. 

Will the above configuration mentioned support hermes.exe?

If not, what is the requirement to make it?

### Steps To Reproduce

Hermes.exe is not running if i open it. Getting the error like below in Windows Server os
![image](https://user-images.githubusercontent.com/23378397/190047470-2f24f7ef-cba7-4c5b-beb5-9a2c4df4804c.png)

### CLI version

npx react-native --version

### Environment

```markdown
npx react-native info
```

**Comment by asklar** [comment]
Windows Server 2016 (1607, version 10.0.14393.5066) won't have the required system components like the ICU library.
Release 1703 seems to be the first Window release with ICU, see https://docs.microsoft.com/en-us/windows/win32/intl/international-components-for-unicode--icu-#history-of-changes-to-the-icu-library-in-windows

Windows Server 2019 is 17763 / 1709, so that should be the minimum Windows Server release that can support it.

**Comment by chrisglein** [comment]
If the components aren't there, I assume the relevant recommendation is to [Disable Hermes](https://microsoft.github.io/react-native-windows/docs/hermes#disabling-hermes) and use Chakra?

Do we need to capture our stance on Windows Server supported versions [here](https://microsoft.github.io/react-native-windows/docs/rnw-dependencies)?

**Comment by asklar** [comment]
that page lists 16299 as the min version (which IIRC is already not working based on WinUI 2.x requirements)
the Windows Server version mentioned here (14393) is much older than even the minimum supported version (16299 or 17734)
