### ISSUE TITLE
react-native-swiper doesn't work

### ISSUE THREAD

**Issue by nuthinking** [Microsoft/react-native-windows#1058]
It's a JS based plugin and it doesn't seem to use particular ScrollView features. Could this be the lack of paging? Thanks!
This is happening in UWP Windows 10 with RN v.0.42 and RNW v.0.42.0-rc.5

**Comment by Warpenguin** [comment]
react-native-swiper has platform specified checks and does not cater for windows: 
https://github.com/leecade/react-native-swiper/blob/master/src/index.js#L548.

If you just need a wrapper for a swiping control, the ported f8app has a useful alternative:
https://github.com/ReactWindows/f8app/blob/master/js/common/ViewPager.js

**Comment by nuthinking** [comment]
@Warpenguin thanks a lot for the tip!

Looks like FlipViewWindows doesn't have anything similar to the onScroll event of RN core (Xaml FlipView has a PointerMoved?). Something I would need.

**Comment by Warpenguin** [comment]
Does onSelectionChange not suffice? You can use that to determine when the selected index changed (content swiped). Since the iOS implementation is using the standard react-native ScrollView component, you could try replace FlipViewWindows with the ScrollView and use pagingEnabled={true} but I'm not sure if its possible to get the desired behaviour. I've yet to try it.

**Comment by nuthinking** [comment]
@Warpenguin as paging is not supported by ScrollView on Windows, I am trying to implementing the logic myself. I would love to be able to detect the on touchEnd event of the drag but looks like the only event I can get besides onScroll is onScrollEndDrag and this is triggered only after the momentum animation ended. I can't even find a way to disable the momentum animation.

**Comment by Warpenguin** [comment]
What exactly do you need the ScrollView to do?

Come join the reactiflux discord and ask for help in the react-native-platforms channel: https://discordapp.com/invite/0ZcbPKXt5bWJVmUY

**Comment by rozele** [comment]
Please file on the react-native-swiper repo.
