### ISSUE TITLE
Unable to build the RNW app with version 0.69.6

### ISSUE THREAD

**Issue by Manjunatha123** [microsoft/react-native-windows#10609]
### Problem Description

Hi,
We were getting issue with header button in the navigation not clickable with react-native-windows version 0.68.9.
saw that there an open issue which said the issue will be fixed on RNW 0.69.6. [Issue link](https://github.com/react-navigation/react-navigation/issues/10719#issuecomment-1239402085) 

When I try to run the app with RNW 0.69.6, I am unable to build the app in VS 2019.
I get the following error.

Could not write lines to file "build\x64\Debug\Microsoft.ReactNative.Managed.CodeGen\netcoreapp3.1\win-x64\Microsoft.ReactNative.Managed.CodeGen.GeneratedMSBuildEditorConfig.editorconfig". Could not find a part of the path 'C:\Users\user\AppName\WinRebuild\AppName\node_modules\react-native-windows\Microsoft.ReactNative.Managed.CodeGen\build\x64\Debug\Microsoft.ReactNative.Managed.CodeGen\netcoreapp3.1\win-x64\Microsoft.ReactNative.Managed.CodeGen.GeneratedMSBuildEditorConfig.editorconfig'.				

### Steps To Reproduce

1. npx react-native init MyApp  --template react-native@^0.69.0
2. cd MyApp
3. npx react-native-windows-init --overwrite --version 0.69.6 --language cs
4. npx react-native autolink-windows --sln windows\MyApp.sln.
5. open the MyApp.sln in VS2019 enterprise and try to build.
6. We get error mentioned in the description.
7. To make sure no dev dependencies are missing we ran the below command as well
```
Set-ExecutionPolicy Unrestricted -Scope Process -Force;
iex (New-Object System.Net.WebClient).DownloadString('https://aka.ms/rnw-deps.ps1')
```
The output is as follows
Checking Free space on C: > 15 GB                                        OK
Checking Installed memory >= 16 GB                                    OK
Checking Windows version > 10.0.16299.0                            OK
Checking Developer mode is on                                             OK
Checking Long path support is enabled                                 OK
Checking git                                                                            OK
Checking Compilers, build tools, SDKs and Visual Studio      OK
Checking NodeJS LTS                                                             OK
Checking Chrome                                                                   OK
Checking .net core 3.1                                                            OK

Even though long path is enabled we are unable to build the app.

### Expected Results

App builds successfully and we are able to run the app.

### CLI version

npx react-native --version

### Environment

```markdown
npx react-native info
Unable to run command
npx react-native info
error: unknown command 'info'
(Did you mean init?)
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2019

### Build Configuration

Debug

**Comment by tero-paananen** [comment]
Maybe this helps somehow https://github.com/microsoft/react-native-windows/issues/10236#issuecomment-1240577791

**Comment by tero-paananen** [comment]
Create React Native app near C root to prevent filepaths to grow too long (more than 256). There may still be sometimes errors with too long filenames.

**Comment by tero-paananen** [comment]
Reboot Windows and keep only one Visual Studio open....try close Visual Studio Code while building to prevent some file locks...

**Comment by chrisglein** [comment]
> open the MyApp.sln in VS2019 enterprise and try to build.

Does your build succeed if you use the command-line and `run-windows`?

There may be some VS component here that isn't long-path aware.

**Comment by Manjunatha123** [comment]
Build does works on `run-windows`. Any changes that needs to be done for NuGet updates could not be done in VSCode.
Also if we somehow manage to get the app running using `run-windows` we get the below error in the debugger console and the application screen goes blank.
```
Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native
```
We have we have app.windows.js that has code that wraps App component within `<MenuProvider>` for the pop-up to work.

The code works fine with version 0.68.9 with some tweaks in node_modules. We wanted to avoid that so tried with 0.69.6 but could not run the app successfully.

Thanks.

**Comment by jonthysell** [comment]
Where are you getting `<MenuProvider>`? Another module?

Can you provide a small repro repo that reproduces this build break?

**Comment by Manjunatha123** [comment]
The code is as below
```
import * as React from 'react';
import App from './App.js';
import { MenuProvider } from 'react-native-popup-menu';  // for the popup menu

export default class AppWindows extends React.Component {
  render(){
    return <MenuProvider><App /></MenuProvider>;
  }
}
```
Even without this as well I was not able to build solution in VS2019.

**Comment by jonthysell** [comment]
Can you provide a cloneable repo repro? We really need to see all the files to see why it only repos in VS and not when using `run-windows`.
