### ISSUE TITLE
[WPF] onLayout.nativeEvent.layout reports relative position instead of absolute position

### ISSUE THREAD

**Issue by kevinvangelder** [microsoft/react-native-windows#1061]
On iOS and UWP `onLayout.nativeEvent.layout` reports the absolute position of the element. In WPF it reports the relative position of the element.

**Comment by rozele** [comment]
@kevinvangelder any updates on this?

**Comment by kevinvangelder** [comment]
I think we found a workaround, though I don't recall what it was. The important thing is that it's unexpected behavior, so we might want to find a way to document it.
