### ISSUE TITLE
rnpm-plugin-windows not working

### ISSUE THREAD

**Issue by bmeverett** [Microsoft/react-native-windows#1062]
I tried setting up a new react native windows project based on the Getting Started Guides and can't get it working. Here is what I did:

```
react-native init ReactWindows
cd ReactWindows
npm install --save-dev rnpm-plugin-windows
react-native windows
```
I get an error saying `could not find react-native-windows@0.42.*`

So I tried to install react-native-windows manually
```
npm install --save-dev react-native-windows@0.42.0
react-native windows
```
I am still receiving the same error `could not find react-native-windows@0.42.*`

Running ` npm ls react-native react-native-windows` shows 
```
+-- react-native@0.42.0
`-- react-native-windows@0.42.0
```

**Comment by rozele** [comment]
@bmeverett which version of rnpm-plugin-windows was installed?

**Comment by matthargett** [comment]
Did you change into the ReactWindows directory? That step is missing in your commands above.

**Comment by bmeverett** [comment]
@rozele 0.2.4

@matthargett yes that is a typo but I did changed the directory.

**Comment by rozele** [comment]
@bmeverett sadly I can't repro.  Can you verify that you also have the problem for other versions of `react-native`?  Try running:

```
react-native init v41 --version 0.41.2
cd v41
npm i --save-dev rnpm-plugin-windows
react-native windows
```

Do you get the same error related to v0.41 of `react-native-windows?

**Comment by bmeverett** [comment]
@rozele yes I still got the same error with the steps you described

**Comment by jerinjohnk** [comment]
@bmeverett I got the same error today. Along with this mine specified checksum error so probably it was a result of connection dropping. So kept running `npm install --save-dev rnpm-plugin-windows` again and again and on third trial it was successful

**Comment by sayar** [comment]
@bmeverett and @jerinjohnk was this resolved?

**Comment by jerinjohnk** [comment]
@sayar running npm install --save-dev rnpm-plugin-windows untill successful completion was the one that worked for me. Havent tried it recently though.

**Comment by sayar** [comment]
It is working in the most recent releases. I'm going to close this issue. Thanks!
