### ISSUE TITLE
Unable to manually link native module

### ISSUE THREAD

**Issue by jihoobyeon** [microsoft/react-native-windows#10684]
### Problem Description

I [made a native module](https://github.com/jihoobyeon/react-native-file-panel) and it doesn't worked.
I found that my module didn't auto-linked, so I tried [manually linking](https://microsoft.github.io/react-native-windows/docs/native-modules-using) and now this error appears:
```
Build failed with message 4:7>C:\Users\jihoobyeon\Desktop\foo\node_modules\react-native-file-panel\windows\FilePicker\ReactPackagePr
ovider.idl(3): error MIDL2025: [msg]syntax error [context]: expecting . near "]" [C:\Users\jihoobyeon\Desktop\foo\node_modules\react-na
tive-file-panel\windows\FilePicker\FilePicker.vcxproj]. Check your build configuration.
```

I tried deleting `[webhosthidden]` in `ReactPackageProvider.idl`, and this calls another error:
```
Build failed with message 7:7>C:\Users\jihoobyeon\Desktop\foo\node_modules\react-native-file-panel\windows\FilePicker\ReactPackagePr
ovider.idl(5): error MIDL2011: [msg]unresolved type declaration [context]: Microsoft.ReactNative.IReactPackageProvider [ RuntimeClass '
FilePicker.ReactPackageProvider'  ] [C:\Users\jihoobyeon\Desktop\foo\node_modules\react-native-file-panel\windows\FilePicker\FilePicker
.vcxproj]. Check your build configuration.
```

It seems to MIDL(which comes with SDK) is being problem,
so I also tried upgrading SDK to 10.0.22000.0 and downgrading to 10.0.18362.0
both of them didn't worked.

### Steps To Reproduce

1. do `yarn add https://github.com/jihoobyeon/react-native-file-panel.git` at your project
2. run `npx react-native run-windows --arch=x64`

### Expected Results

module has resigtered with no error.

### CLI version

7.0.4

### Environment

System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 AMD Ryzen 3 2200U with Radeon Vega Mobile Gfx
    Memory: 21.43 GB / 31.63 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0, 10.0.22000.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.32901.82 (Visual Studio Community 2019)
 WebStorm 2022.1.4
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.2 => 0.68.2
    react-native-windows: 0.68.18 => 0.68.18

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2019

### Build Configuration

Debug

### Snack, code example, screenshot, or link to a repository

this is my `App.tsx`:

```
import React from 'react';
import { Button, View } from 'react-native';
import { open, save } from 'react-native-file-panel';

export default class App extends React.Component {
  render() {
    return (
      <View>
        <Button title='SAVE' onPress={ () => save('txt', '가나다라마1') } />
        <Button title='OPEN' onPress={ () => open('txt') } />
      </View>
    );
  }
}
```

**Comment by jonthysell** [comment]
It looks like you've created the native project on your own, so you're not referencing any of the Microsoft.ReactNative dependencies you need to build a native module.

Please read https://microsoft.github.io/react-native-windows/docs/native-modules-setup#creating-a-new-native-module-library-project to see how you can use `react-native-windows-init` to set up your project with the correct dependencies.

**Comment by jihoobyeon** [comment]
@jonthysell OK, that worked. It was my mistake. Thanks!
