### ISSUE TITLE
FocusManager returns null when TextBox is focused in XAML Islands

### ISSUE THREAD

**Issue by rozele** [microsoft/react-native-windows#10690]
### Problem Description

In a XAML Islands app, FocusManager returns null when a TextBox has focus. It appears to also return null for arbitrary controls, including ViewControl. This means that calling `.blur()` on a TextInput ref (or any ref for that matter) never blurs the TextInput.

### Steps To Reproduce

1. Attempt to blur a TextInput in a XAML Islands app - it will not :(

### Expected Results

Calling `.blur()` on a `<TextInput>` ref should blur the control.

### CLI version

npx react-native --version

### Environment

```markdown
npx react-native info
```

**Comment by jonthysell** [comment]
Are we trying to call `GetFocusedElement()` without a XAML root to the method? Possibly related: https://github.com/microsoft/microsoft-ui-xaml/issues/3484

**Comment by rozele** [comment]
Thanks @jonthysell - updated https://github.com/microsoft/react-native-windows/pull/10691 to use the GetFocusedElement(XamlRoot) overload.
