### ISSUE TITLE
Remove VirtualizedListProps Patch

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-windows#10694]
### Problem Description

<>

### Steps To Reproduce

N/A

### CLI version

npx react-native --version

### Environment

```markdown
npx react-native info
```

**Comment by NickGerleman** [comment]
You can remove @react-native-windows/virtualizedlist in general. It is identical to the one in core at this point.

**Comment by chiaramooney** [comment]
VirutalizedList has been removed.
