### ISSUE TITLE
Remove AttributedString and LayoutableShadowNode patch

### ISSUE THREAD

**Issue by TatianaKapos** [microsoft/react-native-windows#10722]
### Problem Description

Tracking removal of overrided files from latest [integration](https://github.com/microsoft/react-native-windows/pull/10479/files#diff-c14f3a9383607a661977aa577c75bbc547827502950e0244721ef021f549fbe2). Once these PRs are merged in https://github.com/facebook/react-native/pull/34947 and https://github.com/facebook/react-native/pull/34889, it should fix complier warning treated as errors

### Steps To Reproduce

1. Remove both override files
2. Build react-native-windows
3. You'll see the compiler errors

### CLI version

npx react-native --version

### Environment

```markdown
npx react-native info
```

**Comment by jonthysell** [comment]
@TatianaKapos Putting this on 0.71 for now, but if we don't get integrated fast enough for 0.71, move this to 0.72.

**Comment by TatianaKapos** [comment]
Removed as of this integration: https://github.com/microsoft/react-native-windows/pull/10883
