### ISSUE TITLE
ReactPromise's should provide better error information when used from incorrect thread

### ISSUE THREAD

**Issue by acoates-ms** [microsoft/react-native-windows#10730]
ReactPromise requires that it's resolved from the JS thread.  We should, at least in debug, provide better error information when a user resolves/rejects the promise from a non-JS thread.

See #10707 as an example.

**Comment by vmoroz** [comment]
@acoates-ms, no, we do not have such requirements. ReactPromise can be resolved from any thread. See: https://github.com/microsoft/react-native-windows/blob/9b33ee7e69645d3eba7edb90d4d945128970e12f/vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.cpp#L423
I had provided a fix for it a few months ago. In which version/language do you see the issue?

**Comment by vmoroz** [comment]
`ReactPromise` was enabled to complete from any thread in this PR: https://github.com/microsoft/react-native-windows/pull/9595 and then backported to 0.65 and up. I am closing this issue and going to look into the original issue #10707.
