### ISSUE TITLE
NativeAnimatedModule missing implementation of updateAnimatedNodeConfig

### ISSUE THREAD

**Issue by acoates-ms** [microsoft/react-native-windows#10731]
NativeAnimatedModule implementation is incomplete and is missing the `updateAnimatedNodeConfig` method.  This prevents the module from being able to turn on using the codegen'd Spec.

**Comment by rozele** [comment]
Looks like this is only being used in AnimatedColor.js, so we can probably coalesce this issue with https://github.com/microsoft/react-native-windows/issues/9493

**Comment by chrisglein** [comment]
Duplicate of #9493
