### ISSUE TITLE
SendReceiveSsl Desktop.IntegrationTests fails with `[0x80072f7d] An error occurred in the secure channel support` on Windows Server 2022 with Visual Studio 2022

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#10732]
### Problem Description

As part of PR #9916 I'm building/testing RNW with Visual Studio 2022 on Windows Server 2022.

```
Failed SendReceiveSsl [1 s]
  Error Message:
   Assert failed. Expected:<> Actual:<[0x80072f7d] An error occurred in the secure channel support>
  Stack Trace:
  	at WebSocketIntegrationTest::SendReceiveCloseBase() in D:\a\_work\1\s\vnext\Desktop.IntegrationTests\WebSocketIntegrationTest.cpp:line 77
```

FYI PRs only run this test as part of Release x64.

This does not repro locally with VS 2022 in Windows 11 on Debug or Release.

### Steps To Reproduce

See PR.

### CLI version

npx react-native --version

### Environment

```markdown
npx react-native info
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

Release

**Comment by jonthysell** [comment]
As best as I can discern, this may be because Windows Server 2022 has higher requirements for TLS than what we use in our code.

**Comment by chrisglein** [comment]
Currently disabled in the PR, but ideally we can figure this out.

**Comment by chrisglein** [comment]
@asklar can you link the issue tracking inability to enable/disable TLS 1.3?

**Comment by asklar** [comment]
tracked internally by https://task.ms/39781302

**Comment by TatianaKapos** [comment]
internal issue is marked as solved but issue is still present when the testcase is renabled: [pipeline](https://dev.azure.com/ms/react-native-windows/_build/results?buildId=488456&view=logs&jobId=04732b5a-7694-5542-a0f7-38d45f6d282d&j=04732b5a-7694-5542-a0f7-38d45f6d282d&t=b42938fe-57a2-5b5d-dbd0-519303d5bf40)
