### ISSUE TITLE
[WPF] Transforms not working

### ISSUE THREAD

**Issue by leonskim** [Microsoft/react-native-windows#1076]
It seems transform style props except for `translateX` and `translateY` are not implemented.

Working:
- translateX
- translateY

Not working:
- perspective
- rotate, rotateX, rotateY, rotateZ
- scale, scaleX, scaleY
- skewX, skewY

Test code:
```
<View style={{transform: [{ scale: 0.5 }]}}>
   ...
</View>
 ```

Exception:
```
Exception thrown: 'System.InvalidOperationException' in ReactNative.Net46.dll
```

**Comment by matthargett** [comment]
@pre10der89 can this be closed now?
