### ISSUE TITLE
Share Api

### ISSUE THREAD

**Issue by KalKhera** [Microsoft/react-native-windows#1077]
A general question. Has anyone given thought on doing this in windows?

https://facebook.github.io/react-native/docs/share.html

**Comment by ndbroadbent** [comment]
+1, I'm getting:

```
[JS Warn] Possible Unhandled Promise Rejection (id: 0):
Unsupported platform
Error: Unsupported platform
   at share (http://172.16.80.1:8081/index.windows.bundle?platform=windows&dev=true&hot=false:48639:9)
```

[react-native-share](https://github.com/EstebanFuentealba/react-native-share#how-it-looks) supports Windows. It would be great if that code could be imported into `react-native-windows`, but I'll use that for now.

**Comment by ndbroadbent** [comment]
Update: I haven't had a good experience with the react-native-share library. It seems to fail silently on the Windows Phone emulator, and I'm getting this error on the local machine: ["There was a problem with the data"](https://github.com/EstebanFuentealba/react-native-share/issues/126)

It would be awesome if this feature could be officially supported.

**Comment by rozele** [comment]
I believe this is a dupe of #567
