### ISSUE TITLE
Inconsistent Facebook.Yoga packages between ReactNative UWP project and App UWP project causes redbox

### ISSUE THREAD

**Issue by Warpenguin** [Microsoft/react-native-windows#1079]
Redbox message: 

> Exception has been thrown by the target of invocation

Exception: 

> System.MissingMethodException: "Method not found: 'Facebook.Yoga.YogaValue Facebook.Yoga.YogaValue.Point(Single)'."

Consolidating the Facebook.Yoga package between the 2 projects fixes this.

**Comment by saas-plat** [comment]
+1

**Comment by rozele** [comment]
This should have been resolved as of https://github.com/Microsoft/react-native-windows/pull/1049.
