### ISSUE TITLE
Building 0.69.9 from source fails when injecting net5.0 dependency into CppWinRT project

### ISSUE THREAD

**Issue by slobo80** [microsoft/react-native-windows#10792]
### Problem Description

We build from source. We include Codegen.csproj as a ProjectReference to ReactNativeXaml.vcxproj via the experimental features props. This works up to 0.69.8. 

Project properties were consolidated in https://github.com/microsoft/react-native-windows/commit/61a16cd809b8ee02cc4098493bcde61eca518466 which broke our build.

### Steps To Reproduce

1. Inject Codegen.csproj as a ProjectReference to ReactNativeXaml.vcxproj via the experimental features props.
2. Build solution.

### Expected Results

Build to succeed.

### CLI version

8.0.6

### Environment

```markdown
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 1.63 GB / 15.92 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.32929.386 (Visual Studio Enterprise 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Platform Version

10.0.22000.0

### Target Device(s)

Desktop

### Visual Studio Version

2019

### Build Configuration

Debug

![image](https://user-images.githubusercontent.com/1782771/197890924-2f07c8a5-47fe-4b1f-8a5a-cb648fab1ddd.jpg)

**Comment by jonthysell** [comment]
The probable solution for this will be to remove the need for this hacky workaround that never should have worked in the first place. The RNX Codegen should just be runnable as a target, not depended on by the RNX C++ project.

**Comment by slobo80** [comment]
This is a major issue for us, preventing us to upgrade. How can we prioritize this? @chrisglein

**Comment by chrisglein** [comment]
@jonthysell What's your take on the scope of this fix? Sounds like removing some workaround, but is that going to introduce some other problem?

**Comment by jonthysell** [comment]
I will make try to make a fix in RNX that will run the Codegen as a target as part of the RNX C++ build.

@slobo80 , you can either wait for that fix and consume a newer version of react-native-xaml, or you can remove the hack and just run the codegen exe by yourself as a step before building RNX.

**Comment by jonthysell** [comment]
Please upgrade to the latest RNX and remove the injected dependency workaround. If you have issues getting the new RNX to run codegen at build time, please open a new bug in the RNX repo.
