### ISSUE TITLE
Positioning popup/flyout vertically by fixed amount changes relative horizontal positioning

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#10813]
### Discussed in https://github.com/microsoft/react-native-windows/discussions/10812

<div type='discussions-op-text'>

<sup>Originally posted by **lcherukuri** October 30, 2022</sup>
```
import React, {useState} from 'react';
import {Pressable, StyleSheet, Text, View} from 'react-native';
import {Flyout} from 'react-native-windows';

export const FlyoutScreen = () => {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <View style={styles.container}>
      <Pressable onPress={() => setIsOpen(true)}>
        <Text>Open</Text>
      </Pressable>

      <Flyout
        style={styles.flyout}
        isOpen={isOpen}
        isLightDismissEnabled={true}
        onDismiss={() => setIsOpen(false)}>
        <View style={styles.flyoutContent}>
          <Text>Some Content inside Flyout</Text>
          <Text>More Content inside Flyout</Text>
        </View>
      </Flyout>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  flyout: {
    width: '50%',
  },
  flyoutContent: {
    backgroundColor: 'grey',
    justifyContent: 'center',
    alignItems: 'center',
  },
});
```

Given a flyout of width X%, I want to horizontally align it to the center of the screen and 100px from the top of the screen. By default, it looks like this

![1](https://user-images.githubusercontent.com/9434550/198904920-ff23f25c-25b4-4f35-9c15-9ee86c7bd2fa.png)

If I give it a vertical offset of 100px, it looks like this

![image](https://user-images.githubusercontent.com/9434550/198904732-750674a3-8284-4c10-9a8e-5a46f9e34ed5.png)

Is there a way to horizontally center the flyout without using a fixed horizontal offset number? 
In web CSS, something like `width: 50%, margin: auto`
</div>

**Comment by TatianaKapos** [comment]
You can position a Flyout relative to the screen by using [useWindowsDimensions API](https://reactnative.dev/docs/usewindowdimensions) ie setting the horizontal Offset to  `horizontalOffset={useWindowDimensions().width / 2}`.
