### ISSUE TITLE
UWP non-xaml app dispatcher support

### ISSUE THREAD

**Issue by mikebev-ik** [Microsoft/react-native-windows#1081]
We have a non-XAML UWP app we're trying to use ReactNative in - it's a Direct3D app. Within this app we're getting an exception in MessageQueueThread.cs wherein it's trying to access the Main Window's CoreDispatcher; but of course, since we're non-XAML, there is no Main Window, so it crashes. 

![dispatcher_exception](https://cloud.githubusercontent.com/assets/20999326/24764974/f41057aa-1aaa-11e7-9655-179cd37aecd1.png)

**Comment by rozele** [comment]
Unfortunately this isn't really a supported scenario for react-native-windows. Closing due to this and inactivity.
