### ISSUE TITLE
RNW stable releases needs to update to latest RN core versions

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#10839]
### Problem Description

We should update our stable branches of RNW to require the latest matching version of RN.

TLDR: In publishing RN 0.71-RC0, all older versions of RN were broken for Android builds. See https://github.com/facebook/react-native/issues/35210 for details.

RN Core has pushed patches back to RN 0.63.

### Steps To Reproduce

See https://github.com/facebook/react-native/issues/35210

### CLI version

npx react-native --version

### Environment

```markdown
npx react-native info
```

**Comment by chrisglein** [comment]
Definitely worth highlighting this problem (see the linked issue).
Our dependency doesn't specify a sub version. If we do nothing no one is blocked from updating the version for app's builds. Giving a specific version would cause problems in the future.

There's a question about whether we're integrating dot releases on old branches (in case updating the dependency version isn't enough). That hasn't been in our workflow. The dot releases are infrequent so it shouldn't be too much to keep up with.

We should do an audit of the dot releases in our support window right now.
And we should add this to the integration workflow to catch any source changes in the future (these are covered in the weekly releases meeting, so this should be possible to do as we go).

But for this specific issue, no change seems to be required.

**Comment by chiaramooney** [comment]
Closing issue for now. Conclusion is action items for the future in investigating integrating dot releases.
