### ISSUE TITLE
support for c++ native modules

### ISSUE THREAD

**Issue by mahantesh19** [Microsoft/react-native-windows#1086]
does "react-native-windows" java script files interact with "c++" native library ?

**Comment by matthargett** [comment]
Yes, you can expose C++/CX (aka Managed C++ or C++/CLI) code to JavaScript by transliterating the C# examples in our documentation into that language. In default React Native Windows though, all JavaScript is calling into C#.

Feel free to re-open if you have other questions, I hope this helps!
