### ISSUE TITLE
Uncaught error on "Network request not found"

### ISSUE THREAD

**Issue by jbcullis** [microsoft/react-native-windows#10876]
### 404 unhandled

![image](https://user-images.githubusercontent.com/27532334/201347306-1e3943aa-9f02-4398-ac34-26ae1c7f7fbb.png)

### Steps To Reproduce

New project
Fetch to a bad address (eg. http://localhost/api/null)

### CLI version

70.4

### Environment

```markdown
OS: Windows 10 10.0.22621    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz    Memory: 18.84 GB / 31.73 GB  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE    Yarn: 1.22.15 - C:\Program Files\nodejs\yarn.CMD    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0, 10.0.22000.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 17.0.32126.317 (Visual Studio Professional 2022)     
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.4 => 0.70.4
    react-native-windows: 0.70.4 => 0.70.4
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

Debug

**Comment by chrisglein** [comment]
@jbcullis Can you include the exception callstack and any other context from the debugger? Also the line of code where you're making your request so we can see your exact repro?

**Comment by Arthurmtro** [comment]
I got same error here, when I fetch ip with a port it crashes
