### ISSUE TITLE
How to forbid the screen orientation by coding

### ISSUE THREAD

**Issue by gangli66** [microsoft/react-native-windows#10903]
### Problem Description

I finished my react-native-windows project and generated an appx. It worked on Surface10 well. When I turned the tablet to portrait, the screen also turned, although I selected only Landscape in the Package.appxmanifest. How can I control the screen only turn to Landscape? I have already use react-native-orientation-locker package in RN and DisplayOrientations.Landscape in C++, but they worked badly. Although I can control it by Windows Settings, it can only lock the screen(can't orient to the opposite landscape).

### Steps To Reproduce

1. Prepare a react-native-windows project.
2. Select "Landscape" in Package.appxmanifest.
3. Generate an appx.
4. Install the appx to a Surface tablet.
5. Run the app.
6. Orient the tablet to portrait.

### Expected Results

When orient to portrait, the screen doesn't orient.
When orient to the opposite landsacpe, the screen orients.

### CLI version

7.0.4

### Environment

```markdown
npx react-native info
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2019

### Build Configuration

Release

### Snack, code example, screenshot, or link to a repository

react-native-windows: 0.68.15

**Comment by jonthysell** [comment]
@chiaramooney This sounds like a UWP tablet-mode issue (not necessarily RNW-specific). Can you look into this?
