### ISSUE TITLE
How to keep the focus on a TextInput

### ISSUE THREAD

**Issue by gangli66** [microsoft/react-native-windows#10904]
### Problem Description

In my RNW app, there is a page only made up of a `<WebView>` and a `<TextInput>`. In the `<TextInput>` I set following properties:
onBlur={onBlur}
onKeyDown={onKeyDown}
ref={inputRef}  (it is defined as const inputRef = useRef())
and in the function onBlur:
inputRef.current.focus()

Normally it works well. I can input any key and the function onKeyDown triggers. However, after I clicked the content of WebView, the TextInput lost its focus. Although the function onBlur triggered, the TextInput didn't gain focus. But after I clicked the content of WebView again, the TextInput gained focus. The issue that the TextInput lost focus happens as random.
This issue only happens in Release build.

In Debug mode, it works well.

How can I keep the focus only on the TextInput, so that I can trigger keyevent every time?

### Steps To Reproduce

1. Prepare a project as my problem description.
2. Generate an appx by Release mode and install it to a Surface tablet or Win10 PC.
3. Run it and work as my problem description.

### Expected Results

When the TextInput lost its focus, it can gain focus immediately every time.

### CLI version

7.0.4

### Environment

```markdown
react 17.0.2
react-native: 0.68.3
reaact-native-windows: 0.68.15
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2019

### Build Configuration

Release

**Comment by jonthysell** [comment]
Also can you confirm if this repros on at least RNW 0.69?

**Comment by gangli66** [comment]
> This sounds like an async timing issue where the webview is grabbing focus _after_ the text input's onblur tries to grab focus back. Something like, when clicking on the webview:
> 
> 1. Text input loses focus, webivew doesn't have focus yet
> 2. Onblur fires, text input re-grabs focus for itself
> 3. Webview finally grabs focus for itself
> 
> Does webview have an onfocus event? Could you maybe make the webview's event give up focus the text-view automatically?

Thans for reply.
However, I set <Webview>'s attribute fosusable={true} and onFocus={onWebviewFocus}, and then create a function onWebviewFocus to print something. But it seems that the webview can't gain focus because the something has been not printed.
I will try to use 0.69 to see it.

**Comment by gangli66** [comment]
> > This sounds like an async timing issue where the webview is grabbing focus _after_ the text input's onblur tries to grab focus back. Something like, when clicking on the webview:
> > 
> > 1. Text input loses focus, webivew doesn't have focus yet
> > 2. Onblur fires, text input re-grabs focus for itself
> > 3. Webview finally grabs focus for itself
> > 
> > Does webview have an onfocus event? Could you maybe make the webview's event give up focus the text-view automatically?
> 
> Thans for reply. However, I set 's attribute fosusable={true} and onFocus={onWebviewFocus}, and then create a function onWebviewFocus to print something. But it seems that the webview can't gain focus because the something has been not printed. I will try to use 0.69 to see it.



> Also can you confirm if this repros on at least RNW 0.69?
> 
> https://microsoft.github.io/react-native-windows/support

When I used rn0.69, it showed the same issue.


> Also can you confirm if this repros on at least RNW 0.69?
> 
> https://microsoft.github.io/react-native-windows/support

I have tried it on 0.69, but it showed me the same issue.

**Comment by gangli66** [comment]
> > > This sounds like an async timing issue where the webview is grabbing focus _after_ the text input's onblur tries to grab focus back. Something like, when clicking on the webview:
> > > 
> > > 1. Text input loses focus, webivew doesn't have focus yet
> > > 2. Onblur fires, text input re-grabs focus for itself
> > > 3. Webview finally grabs focus for itself
> > > 
> > > Does webview have an onfocus event? Could you maybe make the webview's event give up focus the text-view automatically?
> > 
> > 
> > Thans for reply. However, I set 's attribute fosusable={true} and onFocus={onWebviewFocus}, and then create a function onWebviewFocus to print something. But it seems that the webview can't gain focus because the something has been not printed. I will try to use 0.69 to see it.
> 
> > Also can you confirm if this repros on at least RNW 0.69?
> > https://microsoft.github.io/react-native-windows/support
> 
> When I used rn0.69, it showed the same issue.
> 
> > Also can you confirm if this repros on at least RNW 0.69?
> > https://microsoft.github.io/react-native-windows/support
> 
> I have tried it on 0.69, but it showed me the same issue.

Does it refer to the content of my Webview source?

**Comment by chrisglein** [comment]
It might help if you could provide a standalone repo of a repro.

It's not surprising that there are timing differences between Debug and Release here, and you're attempting to make strong assumptions about the timing of focus events. My guess is you need to delve in deeper to WebView's internal focus events if you really want to make this reliable. Hard to say without seeing your exact code for how you're attempting this.
