### ISSUE TITLE
Windows 7

### ISSUE THREAD

**Issue by fabdelgado** [Microsoft/react-native-windows#1091]
Hi, how to support Windows 7 ?

**Comment by matthargett** [comment]
See the documentation for initializing and running the WPF variant of React Native Windows in the documentation here:
https://github.com/Microsoft/react-native-windows/blob/master/local-cli/rnpm/wpf/README.md

I can attest the WPF support is working really well, and Windows 7 support is critical to the product I work on -- more than 66% of our 20+ million desktop app use per month comes from Windows 7. Your end users will need to have Win7 SP1 and .NET 4.6.x installed.

**Comment by fabdelgado** [comment]
@matthargett thankyou
