### ISSUE TITLE
Improve Debug Target Name when using Hermes

### ISSUE THREAD

**Issue by aeulitz** [microsoft/react-native-windows#10915]
### Summary

Unless a RNW dev sets the 'debuggerRuntimeName' property in the DevSettings, we advertise the debug target for the React Instance via the hardcoded string "Hermes React Native". We should provide more info to enable the RNW dev to connect to the instance s/he wants to debug.  

### Motivation

On a platform like Windows, it's conceivable that multiple RN host apps are running simultaneously (including multiple instances of the same app). It's also conceivable that within one app multiple RNW instances are running simultaneously. Therefore, the debug target name should convey bundle identity as well as information about the host app.

### Open Questions

The same issue probably applies to V8. We should probably track this with a separate bug.

**Comment by aeulitz** [comment]
Related to Office work item [VSO:6558665](https://office.visualstudio.com/OC/_workitems/edit/6558665)

**Comment by acoates-ms** [comment]
We already have the https://microsoft.github.io/react-native-windows/docs/native-api/ReactInstanceSettings#debuggerruntimename property that should do this.  -- We should double check that that is hooked up with Hermes.

I don't think it makes sense to try to use the bundle name or other things instead. -- The bundle name is probably just index for most users which isn't any more descriptive than the default.

As for Office, we should probably just pass through the sdx identity as `DebuggerRuntimeName` on the office side. -- I dont think it makes sense to try to do more in RNW.
