### ISSUE TITLE
Camera support

### ISSUE THREAD

**Issue by datkinson** [Microsoft/react-native-windows#1093]
Is there camera support or if not are there any packages that can provide that functionality?

**Comment by jmcginty** [comment]
I have written a camera module implementation. I'll see if I can wrap it up as a module

**Comment by matthargett** [comment]
I know someone had a fork of react-native-camera that added Windows support, but not sure what happened to that. Maybe @rozele or @kevinvangelder or @GantMan would remember?

**Comment by rozele** [comment]
Closing as dupe of #183. We've needed to add the CameraRollModule (and other camera related APIs) for some time. @jmcginty if you have an implementation that covers most of the behaviors for the core camera functionality in RN, a PR would be greatly appreciated.
