### ISSUE TITLE
Unable to build on macOS using Parallels (ERROR: The system was unable to find the specified registry key or value)

### ISSUE THREAD

**Issue by alexzobi** [microsoft/react-native-windows#10943]
### Problem Description

I'm trying to use [Parallels](https://www.parallels.com/pd/general/) to run a windows vm to develop a RNW app. My laptop has an M1, so I don't know if that has something to do with it, but I cannot get around this issue. When I started seeing it in our app (which had previously run in v0.69 from vscode 2022 preview a few months back), I decided to spin up a new app. The fresh app has the same issue. I try to autolink and it throws this error, but then says `autolink successful`. However, when I try to build, I get the same error and it tells me to run the linking command with the `--check --sln` flags as i have below. Doesn't seem to help. I've tried building for arm64 and x86 and I get the same error.

```bash
npx react-native autolink-windows --check --sln "windows\rnw.sln" --proj "windows\rnw\rnw.vcxproj"
ERROR: The system was unable to find the specified registry key or value.
 √ Checking auto-linked files...
Success: No auto-linking changes necessary.
```
A couple of things i've noticed, even after running the dependency script, it still says .NET 3.1 isn't installed. if i agree to install it, it says installed successful, but if i run the command again (after closing and restarting the shell session) it again says not installed. i tried manually installing .net 3.1 which changed nothing. I also noticed that the output of `npx react-native info` says `ia32` but obviously that is not the architecture. I've tried retargeting my solution for 10.0.19 and 10.0.22. same error regardless. 

It's unfortunate because we had the app running before and all but one of my team have Apple Silicon, so it has brought our RNW development to a halt and caused us to stop support (hopefully temporarily) for windows. Any thoughts would be greatly appreciated.

![Screen Shot 2022-11-28 at 2 33 05 PM](https://user-images.githubusercontent.com/35748903/204395000-bbb440d5-4dde-48d2-93cd-1e2fa85834dc.png)

### Steps To Reproduce

1. `npx react-native init <projectName> --template react-native@^0.70.0`
2. `cd projectName`
3. `npx react-native-windows-init --overwrite`
4. `npx react-native autolink-windows`
5. `npx react-native run-windows`
 -or-
5. Open VS2022, build for `x86` or `ARM64`

### Expected Results

successfully builds clean app

### CLI version

0.70.6

### Environment

```markdown
System:
    OS: Windows 10 10.0.22621
    CPU: (4) ia32 Apple Silicon
    Memory: 2.49 GB / 7.99 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files (x86)\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.2 - C:\Program Files (x86)\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: 17.4.33110.190 (Visual Studio Community 2022)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.6 => 0.70.6
    react-native-windows: 0.70.7 => 0.70.7
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

Debug

**Comment by chrisglein** [comment]
> It's unfortunate because we had the app running before 

Do you know when this started breaking for you?
Our official support for VS2022 is rather new, and being rolled out for the first time in the soon-to-be-in-preview 0.71. Were you on VS2019 before or always on VS2022? Is it possible to use VS2019 and/or update to 0.71 preview (when that is released)?

Which emulation mode are you using for Parallels?

It may help to get additional logging. Not sure why there's a registry error in autolinking. Add `--logging`.

**Comment by chrisglein** [comment]
@jonthysell if there are some more diagnostic options / environment variables that'd help here, comment with them here.

**Comment by AlexSobiloffSonos** [comment]
> > It's unfortunate because we had the app running before
> 
> Do you know when this started breaking for you? Our official support for VS2022 is rather new, and being rolled out for the first time in the soon-to-be-in-preview 0.71. Were you on VS2019 before or always on VS2022? Is it possible to use VS2019 and/or update to 0.71 preview (when that is released)?
> 
> Which emulation mode are you using for Parallels?
> 
> It may help to get additional logging. Not sure why there's a registry error in autolinking. Add `--logging`.
> 
> Is it an option to disable autolinking?

I was using VS2022 Preview alongside RN0.68. It was when upgrading to regular VS2022 that this started happening.

**Comment by alexzobi** [comment]
> > It's unfortunate because we had the app running before
> 
> Do you know when this started breaking for you? Our official support for VS2022 is rather new, and being rolled out for the first time in the soon-to-be-in-preview 0.71. Were you on VS2019 before or always on VS2022? Is it possible to use VS2019 and/or update to 0.71 preview (when that is released)?
> 
> Which emulation mode are you using for Parallels?
> 
> It may help to get additional logging. Not sure why there's a registry error in autolinking. Add `--logging`.
> 
> Is it an option to disable autolinking?

Sorry for the delayed response. I was using VS2022 Preview alongside RN0.68. It was after upgrading to regular VS2022 that this started happening.

**Comment by k1mmm** [comment]
@alexzobi I was having the same issue, in my case it turned out nodejs 32bit was installed by default by react-native-windows installer instead of 64bit. https://github.com/microsoft/react-native-windows/discussions/10932

**Comment by jonthysell** [comment]
Good to know that you need to install 64bit Node.

I have checked and using the `rnw-dependencies.ps1` script should install the 64-bit version of NodeJS, as it calls `choco install -y nodejs-lts`, which detects and installs the proper version.
