### ISSUE TITLE
Flatlist support ?

### ISSUE THREAD

**Issue by zerglingno1** [Microsoft/react-native-windows#1094]

**Comment by lznt** [comment]
Any news on this?

**Comment by matthargett** [comment]
I think we'll have to implement this to cut a 44 release, so we'll update this issue once we get around to that next week.

**Comment by rozele** [comment]
The only thing preventing us from having FlatList is the lack of a RefreshControl (#190).

**Comment by rozele** [comment]
I don't see anything actually blocking FlatList from working at this point. We still don't have RefreshControl, but the RNTester example works (except for a few quirks with TextInput).
