### ISSUE TITLE
Update pipelines to test Node 18

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#11003]
### Summary

We run Node Tests on LTS versions of Node, currently against 14 and 16. We should expand that matrix to include the latest Node LTS 18.

### Motivation

We test Node 14 because the minimum Node we support is 14 to align with RN core. We test on Node 16 because our images have used Node 16 for a while now. With the latest Node LTS 18, we should be running our tests on it at least.

**Comment by TatianaKapos** [comment]
as of https://github.com/microsoft/react-native-windows/pull/11858, we switched to use node18 in our pipeline images. Closing this issue but feel free to reopen if it missed a test.
