### ISSUE TITLE
ScrollView: contentOffset doesnt seem to have any effect

### ISSUE THREAD

**Issue by rachmcnamara** [Microsoft/react-native-windows#1107]
I  would like to start my horizontal scroll view on the second item in the list.  I have set a contentOffset but the scrollView does not start at the new position.   Below is the snippet of the ScrollView tag...

render()
{
       var {height, width} = Dimensions.get('window');
        console.log("window width "+width)

        return (
                <ScrollView horizontal={true} contentOffset={{x:width, y:0}} pagingEnabled={true}  contentContainerStyle={{width:width*3, height:height}} ref={(a)=>this.scrollView = a} >

**Comment by adi1133** [comment]
Looks like the underlying UWP api [ChangeView](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.scrollviewer#Windows_UI_Xaml_Controls_ScrollViewer_ChangeView_Windows_Foundation_IReference_System_Double__Windows_Foundation_IReference_System_Double__Windows_Foundation_IReference_System_Single__) is broken.

There is more info at:
 - [social.msdn.microsoft.com](https://social.msdn.microsoft.com/Forums/en-US/8e81da67-949a-4206-855e-1dad60299841/scrollviewerchangeview-not-working-on-my-vertically-scrolling-gridview?forum=winappswithcsharp)
- [stackoverflow.com](https://stackoverflow.com/questions/22535838/windows-store-app-scrollviewer-changeview-not-working)

**Comment by rozele** [comment]
I think there's a category of issues with the way props are set. Many props are set on the view before a layout pass with dimensions. We may have to add in an architecture that at least waits for the first layout pass before setting these properties.

@rachmcnamara - a good way to test out this theory would be to tie the `contentOffset` property to a state variable, and then set the `contentOffset` to the expected `width` value after a short timeout.

**Comment by rozele** [comment]
@rachmcnamara please update if this is still an issue, otherwise we'll close.
