### ISSUE TITLE
LayoutAnimation still causes app to crash

### ISSUE THREAD

**Issue by scott108** [Microsoft/react-native-windows#1108]
#884 did not resolve root cause

It still crash when using LayoutAnimation in UWP App

![image](https://cloud.githubusercontent.com/assets/7892590/25835052/6e7795f4-34ae-11e7-8394-a17f293e77fd.png)

**Comment by matthargett** [comment]
Can you provide some code we can paste into Playground and reproduce?

We are using animation in our app and not seeing this problem, but that may be due to some changes on the 42-stable branch that haven't been published on the public feed yet.
