### ISSUE TITLE
AccessibilityInfo.isScreenReaderEnabled always returns true

### ISSUE THREAD

**Issue by rozele** [microsoft/react-native-windows#11089]
### Problem Description

From the RN docs:

**isScreenReaderEnabled()**
> Query whether a screen reader is currently enabled. Returns a promise which resolves to a boolean. The result is true when a screen reader is enabled and false otherwise.

The value always returns true for me (others have reported that it switches back and forth between true and false) when a screen reader (e.g., Narrator) is not enabled.

### Steps To Reproduce

Set up this example in simple.tsx:
```
/**
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 * @format
 */
import React, {useEffect, useState} from 'react';
import {AccessibilityInfo, AppRegistry, Text, View} from 'react-native';

export function Bootstrap() {
  const [isEnabled, setIsEnabled] = useState(false);
  useEffect(() => {
    const id = setInterval(async () => {
      const enabled = await AccessibilityInfo.isScreenReaderEnabled();
      setIsEnabled(enabled);
    }, 1000);
    return () => clearInterval(id);
  }, []);
  return <Text>isScreenReaderEnabled: {isEnabled ? 'true' : 'false'}</Text>;
}

AppRegistry.registerComponent('Bootstrap', () => Bootstrap);
```
![image](https://user-images.githubusercontent.com/1106239/212403015-17c3ae03-2263-4f5a-ad78-71a172656866.png)

### Expected Results

I would expect the screen to show `isScreenReaderEnabled: false` as long as I don't have any screen reader tool (e.g., Narrator) running.

### CLI version

npx react-native --version

### Environment

```markdown
npx react-native info
```

### Target Platform Version

None

### Visual Studio Version

None

### Build Configuration

None

**Comment by rozele** [comment]
This is implemented here: https://github.com/microsoft/react-native-windows/blob/main/vnext/Microsoft.ReactNative/Modules/AccessibilityInfoModule.cpp#L34

Is there a more reliable API than UiaClientsAreListening to call?

**Comment by chrisglein** [comment]
@AgneLukoseviciute tested this maybe a month ago and it was working. Maybe there was a recent regression? Needs some eyeballs to try the repro and see what's changed.

**Comment by chrisglein** [comment]
Also, it's possible it's your configuration @rozele ? Can you share your environment information?

**Comment by rozele** [comment]
> Also, it's possible it's your configuration @rozele ? Can you share your environment information?

I tested on both UWP and XAML Islands, but I'll definitely test again and update the environment info section.

**Comment by chrisglein** [comment]
Confirmed this repro's on 0.71.
