### ISSUE TITLE
Undesired re-renders in react-navigation

### ISSUE THREAD

**Issue by MacKenzieHnC** [microsoft/react-native-windows#11094]
### Problem Description

I already posted this in [`react-navigation`](https://github.com/react-navigation/react-navigation/issues/11146) and [`react-native-screens`](https://github.com/software-mansion/react-native-screens/issues/1684), but the more I dig, the less I think it is directly because of code in those repos. Admittedly, this is all extremely over-my-head, so be skeptical of my assessment.

The core issue is screens unmounting/remounting on every `blur` event in `react-navigation`, fully ignoring `unmountOnBlur`, which causes any local states associated with that screen to be lost. This most-frustratingly includes even opening and closing drawers.

I'm still digging, but so far all I've managed to figure out is that the root issue is probably in this repo. It is similar to [this issue](https://github.com/microsoft/react-native-windows/issues/10484), but the associated [fix](https://github.com/microsoft/react-native-windows/issues/10484#issuecomment-1232785185) has no effect.

I have confirmed that the issue affects `drawer`, `stack`, and `native-stack` implementations of `react-navigation`, so I suspect it affects all of them.

EDIT: Oh wait, is this a full duplicate? I sincerely cannot tell.

Maybe this is a new clue: drawers opening gets added to the `navigation` history the same as when you are changing screens. So the core *could* be that when the `navigation` prop changes, RNW thinks that that counts as a root change, and updates the whole tree as a result. But if that was all it is, then using
```js
const history = useNavigationState(state => state.history);
history.push({key: 'route', name: 'someName''});
```
would trigger it and it doesn't. So it might have something to do with `emit`.

### Steps To Reproduce

1. New react native project
2. install RNW and navigation
3. Create a screen with a `useState` and `blur` events (`navigation.push()`, `navigation.openDrawer`, etc.)
4. Watch your local state disappear

### Expected Results

State should be maintained the same way it is on Android

### CLI version

9.3.2

### Environment

```markdown
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 7.25 GB / 15.93 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 9.2.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.17763.0, 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: AI-221.6008.13.2211.9477386
    Visual Studio: 16.11.33214.272 (Visual Studio Community 2019)
  Languages:
    Java: 19.0.1 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.6 => 0.70.6
    react-native-windows: 0.70.10 => 0.70.10
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2019

### Build Configuration

Debug

### Snack, code example, screenshot, or link to a repository

https://github.com/MacKenzieHnC/ReactNavigationWindows (Note: there is a hack required to even run Gesture Handler on my machine. Clearly labeled in git commit history, unrelated to this issue, but `drawer` shows this issue most glaringly)

**Comment by chrisglein** [comment]
@AgneLukoseviciute @chiaramooney is this related to the accessibility tree noHideDescendents/screens issues that have been looked at? This may be part of what can only be fixed by a native implementation and doesn't work with the JS implementation. Can you link or duplicate this issue as appropriate?

**Comment by MacKenzieHnC** [comment]
Possibly related, I just tried [this drawer example](https://github.com/AgneLukoseviciute/RNW-DrawerNavigator) and absolutely none of the text inputs persist data for even a moment (without even opening the drawer). If that's not true for everyone, there might be something weird about my setup.

**Comment by MacKenzieHnC** [comment]
I understand this isn't anyone's priority, and that's fair, but could I just get an update:

On a scale from baby's first programming project to journey through the Forest of the Nightmare King, how hard is this to solve?

**Comment by MacKenzieHnC** [comment]
> I am having this same issue in RNW .71 Is there a solution or workaround for this?

None that I could find, and I don't think one's coming soon. I ended up having to build navigation myself.

**Comment by acaininet** [comment]
> > I am having this same issue in RNW .71 Is there a solution or workaround for this?
> 
> None that I could find, and I don't think one's coming soon. I ended up having to build navigation myself.

How deep was the well to re-write navigation? How does it avoid the re-rendering issues?

**Comment by MacKenzieHnC** [comment]
> > > I am having this same issue in RNW .71 Is there a solution or workaround for this?
> > 
> > 
> > None that I could find, and I don't think one's coming soon. I ended up having to build navigation myself.
> 
> How deep was the well to re-write navigation? How does it avoid the re-rendering issues?

I went with really minimal functionality so not awful. Had to get good at `forwardRef`s for my version of `onNavigateAway`, but that was the worst of it.

Getting the header bar to look right was pretty annoying, I guess.

I also made no attempt to implement any kind of history, which I'm sure would be an absolute nightmare, and I suspect that's where the bad interaction with RNW is. I don't know, but I think the problem is that the history object changes on every navigation event, which makes RNW re-render the tree. I have no idea why it's only RNW tho

**Comment by chiaramooney** [comment]
Closing issue for now. This is related to the Paper implementation on no-hide-descendants. The team is currently focused on implementing Fabric (the new architecture). Fabric will bring a re-write to this functionality. If issue persists on new architecture, new issue can be created.
