### ISSUE TITLE
Can't upload file with axios

### ISSUE THREAD

**Issue by letieu** [microsoft/react-native-windows#11095]
### Problem Description

can't upload file with axios

### Steps To Reproduce

The code still works fine on ios and android 
![image](https://user-images.githubusercontent.com/53562817/212873341-e4f021d2-f57f-4961-9c08-930688560596.png)
But on window axios return: 
![image](https://user-images.githubusercontent.com/53562817/212875426-eeb51b38-d434-41ea-b857-ca4fa800dd1a.png)

cannot upload image 

### CLI version

npx react-native --version

### Environment

```markdown
npx react-native info
```

### Target Platform Version

None

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2019

### Build Configuration

None

**Comment by chrisglein** [comment]
This might have required some features in the networking implementation like incremental http updates. Can you provide your version information as described above?

May be related to #9534 and #2460

**Comment by letieu** [comment]
I use
 "axios": "^0.26.0",
"react-native-windows": "0.67.13",
I have tried all ways to downgrade and upgrade versions of axios and react native windows but it still doesn't work

**Comment by jonthysell** [comment]
It looks like the underlying HTTP feature was implemented last November and only backported as far back as RNW 0.68. So you'll need at least RNW 0.68.24.

But as of now the minimum supported version of RNW is 0.70, so I'd really recommend moving to that. See https://microsoft.github.io/react-native-windows/support
