### ISSUE TITLE
Failed to Restore the NuGet Packages

### ISSUE THREAD

**Issue by anuragvijayvergia** [Microsoft/react-native-windows#1112]
Hi I am trying to run a react native windows project, but when I am doing react-native run-windows I am getting error as Failed to restore the NuGet Packages. 

This what I have done till now 
react-native init newProject --version 0.41.2
cd newProject
npm i --save-dev rnpm-plugin-windows
react-native windows
react-native run-windows

**Comment by chsrlnd** [comment]
Are you running Visual Studio 2015 instead of 2017?

**Comment by matthargett** [comment]
Just tested this and I can reproduce the error if I run those commands on a fresh VM that has nodejs installed, but not Visual Studio. I'm updating the README to be clearer and update the link to VS2015 since its moved.

**Comment by anuragvijayvergia** [comment]
@chsrlnd @matthargett  Yes I didn't noticed the link was taking me to visual studio 2017, thanks for the info. 

Its working now.

**Comment by juanitogan** [comment]
@matthargett  Note that the "Windows 10 SDK" link also led me to install VS17 instead of VS15, so maybe note stronger that VS17 and later SDKs are not supported yet, and maybe point that link somewhere else too.  None of this is obvious to us new to VS where newer version are, apparently, a problem.

**Comment by juanitogan** [comment]
Oh, yeah, to maybe help anyone else lost on this save some time.  The other error message related to this, if trying to run from VS instead of the command line (assuming you got past the ChakraBridge default StartUp Project problem) is:

`... ReactNative.dll could not be found`

**Comment by juanitogan** [comment]
And, finally, after much ado, VS15 can only be downloaded (at the moment) by jumping through the hoops here:

https://www.visualstudio.com/vs/older-downloads/

**Comment by cdevroe** [comment]
@juanitogan @matthargett @chsrlnd Is it still required that I download VS15 rather than VS17?

**Comment by rozele** [comment]
@cdevroe - everything works on VS 2017 now.

**Comment by cdevroe** [comment]
@rozele Thanks. I've managed to get pretty far in the process. Having an issue with "Yoga" related files not being found at the `react-windows run-windows` step. After toying with it for half a day I'm moving on for now. But I do hope to get it all working so I can build a Windows app.

**Comment by rozele** [comment]
@cdevroe - you may be missing a VS 2017 plugin for desktop or C++ development.
