### ISSUE TITLE
ScrollView component parity for Fabric

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#11152]
This task captures the work to reach parity between Paper and Fabric for the native code for the `<ScrollView>` component.

# ComponentView

1. [x] Create the ScrollViewComponentView (SVCV)
2. [x] Register the ComponentView in the ComponentViewRegistry

# APIs

See latest spec at https://reactnative.dev/docs/scrollview.

## ScrollView Props

API | Platform | RNW Paper | RNW Fabric | Notes 
--:|:--:|:--:|:--:|:--
| <ul><li>[x] StickyHeaderComponent</li></ul> |  | JS | JS | 
| <ul><li>[x] alwaysBounceHorizontal</li></ul> | iOS | No | No? | 
| <ul><li>[x] alwaysBounceVertical</li></ul> | iOS | No | No? | 
| <ul><li>[x] automaticallyAdjustContentInsets</li></ul> | iOS | No | No? | 
| <ul><li>[x] automaticallyAdjustKeyboardInsets</li></ul> | iOS | No | No? | 
| <ul><li>[x] automaticallyAdjustsScrollIndicatorInsets</li></ul> | iOS | No | No? | 
| <ul><li>[x] bounces</li></ul> | iOS | No | No? | 
| <ul><li>[x] bouncesZoom</li></ul> | iOS | No | No? | 
| <ul><li>[x] canCancelContentTouches</li></ul> | iOS | No | No? | 
| <ul><li>[x] centerContent</li></ul> | iOS | No | No? | 
| <ul><li>[x] contentContainerStyle</li></ul> |  | See View style | See View style | Supports View Style Props, Layout Props, Shadow Props
| <ul><li>[x] contentInset</li></ul> | iOS | No | No? | 
| <ul><li>[x] contentInsetAdjustmentBehavior</li></ul> | iOS | No | No? | 
| <ul><li>[x] contentOffset</li></ul> |  | No | SVCV | 
| <ul><li>[x] decelerationRate</li></ul> |  | No | No? | 
| <ul><li>[x] directionalLockEnabled</li></ul> | iOS | No | No? | 
| <ul><li>[x] disableIntervalMomentum</li></ul> |  | No | No? | 
| <ul><li>[x] disableScrollViewPanResponder</li></ul> |  | JS | JS | 
| <ul><li>[x] endFillColor</li></ul> | Android | No | No? | 
| <ul><li>[x] fadingEdgeLength</li></ul> | Android | No | No? | 
| <ul><li>[ ] horizontal</li></ul> |  | SVM | Pri 1 | 
| <ul><li>[x] indicatorStyle</li></ul> | iOS | No | No? | 
| <ul><li>[x] invertStickyHeaders</li></ul> |  | JS | JS | 
| <ul><li>[ ] keyboardDismissMode</li></ul> |  | SVM | Pri 1 | 
| <ul><li>[x] keyboardShouldPersistTaps</li></ul> |  | JS | JS | 
| <ul><li>[x] maintainVisibleContentPosition</li></ul> | iOS | No | No? | 
| <ul><li>[ ] maximumZoomScale</li></ul> | iOS | SVM | Pri 1 | 
| <ul><li>[ ] minimumZoomScale</li></ul> | iOS | SVM | Pri 1 | 
| <ul><li>[x] nestedScrollEnabled</li></ul> | Android | No | No? | 
| <ul><li>[ ] onContentSizeChange</li></ul> |  | SVM | Pri 1 | 
| <ul><li>[ ] onMomentumScrollBegin</li></ul> |  | SVM | Pri 1 | Event is topScrollBeginMomentum, Fabric: Code present but commented out?
| <ul><li>[ ] onMomentumScrollEnd</li></ul> |  | SVM | Pri 1 | Event is topScrollEndMomentum, Fabric: Code present but commented out?
| <ul><li>[x] onScroll</li></ul> |  | SVM | SVCV | 
| <ul><li>[ ] onScrollBeginDrag</li></ul> |  | SVM | Pri 1 | Fabric: Code present but commented out?
| <ul><li>[ ] onScrollEndDrag</li></ul> |  | SVM | Pri 1 | Fabric: Code present but commented out?
| <ul><li>[x] onScrollToTop</li></ul> | iOS | No | No? | 
| <ul><li>[x] overScrollMode</li></ul> | Android | No | No? | 
| <ul><li>[ ] pagingEnabled</li></ul> |  | SVM | Pri 1 | 
| <ul><li>[x] persistentScrollbar</li></ul> | Android | No | No? | 
| <ul><li>[x] pinchGestureEnabled</li></ul> | iOS | No | No? | 
| <ul><li>[x] refreshControl</li></ul> |  | No | No? | 
| <ul><li>[x] removeClippedSubviews</li></ul> |  | No | No? | 
| <ul><li>[ ] scrollEnabled</li></ul> |  | SVM | Pri 1 | 
| <ul><li>[x] scrollEventThrottle</li></ul> | iOS | No | No? | 
| <ul><li>[x] scrollIndicatorInsets</li></ul> | iOS | No | No? | 
| <ul><li>[x] scrollPerfTag</li></ul> | Android | No | No? | 
| <ul><li>[x] scrollToOverflowEnabled</li></ul> | iOS | No | No? | 
| <ul><li>[x] scrollsToTop</li></ul> | iOS | No | No? | 
| <ul><li>[ ] showsHorizontalScrollIndicator</li></ul> |  | SVM | Pri 1 | 
| <ul><li>[ ] showsVerticalScrollIndicator</li></ul> |  | SVM | Pri 1 | 
| <ul><li>[ ] snapToAlignment</li></ul> | iOS | SVM | Pri 1 | 
| <ul><li>[ ] snapToEnd</li></ul> |  | SVM | Pri 1 | 
| <ul><li>[ ] snapToInterval</li></ul> |  | SVM | Pri 1 | 
| <ul><li>[ ] snapToOffsets</li></ul> |  | SVM | Pri 1 | 
| <ul><li>[ ] snapToStart</li></ul> |  | SVM | Pri 1 | 
| <ul><li>[x] stickyHeaderHiddenOnScroll</li></ul> |  | JS | JS | Mapped to ScrollViewStickyHeader's hiddenOnScroll
| <ul><li>[x] stickyHeaderIndices</li></ul> |  | JS | JS | 
| <ul><li>[ ] zoomScale</li></ul> | iOS | SVM | Pri 1 | 

## ScrollView Methods

API | Platform | RNW Paper | RNW Fabric | Notes 
--:|:--:|:--:|:--:|:--
| <ul><li>[x] flashScrollIndicators()</li></ul> | iOS | No | No? | 
| <ul><li>[x] scrollTo()</li></ul> |  | SVM | SVCV | Fabric: #11344
| <ul><li>[x] [scrollToEnd()](https://github.com/microsoft/react-native-windows/issues/12074) </li></ul> |  | SVM | SVCV | Fabric: #12190
| <ul><li>[x] zoomToRect()</li></ul> |   | No | No? | 

## View Props

API | Platform | RNW Paper | RNW Fabric | Notes 
--:|:--:|:--:|:--:|:--
| <ul><li>[ ] accessibilityActions</li></ul> |  | FEVM | Pri 2 | 
| <ul><li>[x] accessibilityElementsHidden</li></ul> | iOS | No | No? | 
| <ul><li>[x] accessibilityHint</li></ul> |  | FEVM | CBCV+CDAP | Fabric: #12036
| <ul><li>[x] accessibilityIgnoresInvertColors</li></ul> | iOS | No | No? | 
| <ul><li>[x] accessibilityLabel</li></ul> |  | FEVM | CBCV+CDAP | Fabric: #11674
| <ul><li>[x] accessibilityLanguage</li></ul> | iOS | No | No? | 
| <ul><li>[ ] accessibilityLiveRegion</li></ul> | Android | FEVM | Pri 2 | 
| <ul><li>[x] accessibilityRole</li></ul> |  | FEVM | CDAP | Fabric: #11412
| <ul><li>[ ] accessibilityState</li></ul> |  | FEVM | CBCV+CDAP | Fabric: Partial impl in #11674
| <ul><li>[x] accessibilityValue</li></ul> |  | FEVM | CBCV+CDAP | Fabric: #12287
| <ul><li>[x] accessibilityViewIsModal</li></ul> | iOS | No | No? | 
| <ul><li>[x] accessible</li></ul> |  | CVM+FEVM | CBCV+CDAP | Fabric: #11719
| <ul><li>[x] collapsable</li></ul> | Android | No | No? | 
| <ul><li>[x] focusable</li></ul> | Android | CVM | CBCV+CDAP | Fabric: #11674
| <ul><li>[x] hitSlop</li></ul> |  | JS | JS | 
| <ul><li>[x] importantForAccessibility</li></ul> | Android | No | No? | 
| <ul><li>[x] nativeID</li></ul> |  | No | No? | 
| <ul><li>[x] needsOffscreenAlphaCompositing</li></ul> |  | No | No? | 
| <ul><li>[x] nextFocusDown</li></ul> | Android | No | No? | 
| <ul><li>[x] nextFocusForward</li></ul> | Android | No | No? | 
| <ul><li>[x] nextFocusLeft</li></ul> | Android | No | No? | 
| <ul><li>[x] nextFocusRight</li></ul> | Android | No | No? | 
| <ul><li>[x] nextFocusUp</li></ul> | Android | No | No? | 
| <ul><li>[ ] onAccessibilityAction</li></ul> |  | VMB | Pri 2 | 
| <ul><li>[x] onAccessibilityEscape</li></ul> | iOS | No | No? | 
| <ul><li>[x] onAccessibilityTap</li></ul> |  | No | CDAP | Fabric: #11874
| <ul><li>[x] onLayout</li></ul> |  | VMB | Pri 1 | 
| <ul><li>[x] onMagicTap</li></ul> | iOS | No | No? | 
| <ul><li>[x] onMoveShouldSetResponder</li></ul> |  | JS | JS | 
| <ul><li>[x] onMoveShouldSetResponderCapture</li></ul> |  | JS | JS | 
| <ul><li>[x] onResponderGrant</li></ul> |  | JS | JS | 
| <ul><li>[x] onResponderMove</li></ul> |  | JS | JS | 
| <ul><li>[x] onResponderReject</li></ul> |  | JS | JS | 
| <ul><li>[x] onResponderRelease</li></ul> |  | JS | JS | 
| <ul><li>[x] onResponderTerminate</li></ul> |  | JS | JS | 
| <ul><li>[x] onResponderTerminationRequest</li></ul> |  | JS | JS | 
| <ul><li>[x] onStartShouldSetResponder</li></ul> |  | JS | JS | 
| <ul><li>[x] onStartShouldSetResponderCapture</li></ul> |  | JS | JS | 
| <ul><li>[x] pointerEvents</li></ul> |  | VMB | SVCV | 
| <ul><li>[x] removeClippedSubviews</li></ul> |  | No | No? | 
| <ul><li>[x] renderToHardwareTextureAndroid</li></ul> | Android | No | No? | 
| <ul><li>[x] shouldRasterizeIOS</li></ul> | iOS | No | No? | 
| <ul><li>[x] style</li></ul> |  | See Below | See Below | Supports View Style Props, Layout Props, Shadow Props
| <ul><li>[x] testID</li></ul> |  | FEVM | CDAP | Fabric: #11412
| <ul><li>[ ] accessibilityPosInSet</li></ul> | Windows | FEVM | Pri 2 | 
| <ul><li>[ ] accessibilitySetSize</li></ul> | Windows | FEVM | Pri 2 | 
| <ul><li>[x] enableFocusRing</li></ul> | Windows | JS | CBCV+SVCV | Fabric: #11323, Focus ring impl in CBCV and CV must call updateBorderProps / updateBorderLayoutMetrics
| <ul><li>[x] keyDownEvents</li></ul> | Windows | VMB | CBCV | Fabric: #12146
| <ul><li>[x] keyUpEvents</li></ul> | Windows | VMB | CBCV | Fabric: #12146
| <ul><li>[x] onBlur</li></ul> | Windows | VMB | CBCV | Paper: Event is registered, but maybe never fired?, Fabric: #11279
| <ul><li>[x] onFocus</li></ul> | Windows | VMB | CBCV | Paper: Event is registered, but maybe never fired?, Fabric: #11279
| <ul><li>[x] onKeyDown</li></ul> | Windows | VMB | CBCV+CEH | Fabric: #12146
| <ul><li>[x] onKeyDownCapture</li></ul> | Windows | VMB | Pri 1 | 
| <ul><li>[x] onKeyUp</li></ul> | Windows | VMB | CBCV+CEH | Fabric: #12146
| <ul><li>[x] onKeyUpCapture</li></ul> | Windows | VMB | Pri 1 | 
| <ul><li>[x] onMouseEnter</li></ul> | Windows | VMB | CEH | 
| <ul><li>[x] onMouseLeave</li></ul> | Windows | VMB | CEH | 
| <ul><li>[ ] tabIndex</li></ul> | Windows | CVM | Pri 1 | 
| <ul><li>[ ] tooltip</li></ul> | Windows | FEVM | Pri 1 | 

## View Style Props

API | Platform | RNW Paper | RNW Fabric | Notes 
--:|:--:|:--:|:--:|:--
| <ul><li>[x] backfaceVisibility</li></ul> |  | No | CBCV+SVCV | Fabric: #12115 Impl in CBCV and CV must call updateTransformProps
| <ul><li>[x] backgroundColor</li></ul> |  | CVM | SVCV | 
| <ul><li>[x] borderBottomColor</li></ul> |  | No | CBCV+SVCV | Fabric:#11323, Border impl in CBCV and CV must call updateBorderProps / updateBorderLayoutMetrics
| <ul><li>[x] borderBottomEndRadius</li></ul> |  | CVM | CBCV+SVCV | Fabric:#11323, Border impl in CBCV and CV must call updateBorderProps / updateBorderLayoutMetrics
| <ul><li>[x] borderBottomLeftRadius</li></ul> |  | CVM | CBCV+SVCV | Fabric:#11323, Border impl in CBCV and CV must call updateBorderProps / updateBorderLayoutMetrics
| <ul><li>[x] borderBottomRightRadius</li></ul> |  | CVM | CBCV+SVCV | Fabric:#11323, Border impl in CBCV and CV must call updateBorderProps / updateBorderLayoutMetrics
| <ul><li>[x] borderBottomStartRadius</li></ul> |  | CVM | CBCV+SVCV | Fabric:#11323, Border impl in CBCV and CV must call updateBorderProps / updateBorderLayoutMetrics
| <ul><li>[x] borderBottomWidth</li></ul> |  | CVM+NUIM | CBCV+SVCV | Fabric:#11323, RN Core resolves LayoutMetrics, but border impl in CBCV and CV must call updateBorderProps / updateBorderLayoutMetrics
| <ul><li>[x] borderColor</li></ul> |  | CVM | CBCV+SVCV | Fabric:#11323, Border impl in CBCV and CV must call updateBorderProps / updateBorderLayoutMetrics
| <ul><li>[x] borderEndColor</li></ul> |  | No | CBCV+SVCV | Fabric:#11323, Border impl in CBCV and CV must call updateBorderProps / updateBorderLayoutMetrics
| <ul><li>[x] borderEndWidth</li></ul> |  | CVM+NUIM | CBCV+SVCV | Fabric:#11323, RN Core resolves LayoutMetrics, but border impl in CBCV and CV must call updateBorderProps / updateBorderLayoutMetrics
| <ul><li>[x] borderLeftColor</li></ul> |  | No | CBCV+SVCV | Fabric:#11323, Border impl in CBCV and CV must call updateBorderProps / updateBorderLayoutMetrics
| <ul><li>[x] borderLeftWidth</li></ul> |  | CVM+NUIM | CBCV+SVCV | Fabric:#11323, RN Core resolves LayoutMetrics, but border impl in CBCV and CV must call updateBorderProps / updateBorderLayoutMetrics
| <ul><li>[x] borderRadius</li></ul> |  | CVM | CBCV+SVCV | Fabric:#11323, Border impl in CBCV and CV must call updateBorderProps / updateBorderLayoutMetrics
| <ul><li>[x] borderRightColor</li></ul> |  | No | CBCV+SVCV | Fabric:#11323, Border impl in CBCV and CV must call updateBorderProps / updateBorderLayoutMetrics
| <ul><li>[x] borderRightWidth</li></ul> |  | CVM+NUIM | CBCV+SVCV | Fabric:#11323, RN Core resolves LayoutMetrics, but border impl in CBCV and CV must call updateBorderProps / updateBorderLayoutMetrics
| <ul><li>[x] borderStartColor</li></ul> |  | No | CBCV+SVCV | Fabric:#11323, Border impl in CBCV and CV must call updateBorderProps / updateBorderLayoutMetrics
| <ul><li>[x] borderStartWidth</li></ul> |  | CVM+NUIM | CBCV+SVCV | Fabric:#11323, RN Core resolves LayoutMetrics, but border impl in CBCV and CV must call updateBorderProps / updateBorderLayoutMetrics
| <ul><li>[x] [borderStyle](https://github.com/microsoft/react-native-windows/issues/3078)</li></ul> |  | No | CBCV | Fabric: Border impl in CBCV and CV must call updateBorderProps / updateBorderLayoutMetrics
| <ul><li>[x] borderTopColor</li></ul> |  | No | CBCV+SVCV | Fabric:#11323, Border impl in CBCV and CV must call updateBorderProps / updateBorderLayoutMetrics
| <ul><li>[x] borderTopEndRadius</li></ul> |  | CVM | CBCV+SVCV | Fabric:#11323, Border impl in CBCV and CV must call updateBorderProps / updateBorderLayoutMetrics
| <ul><li>[x] borderTopLeftRadius</li></ul> |  | CVM | CBCV+SVCV | Fabric:#11323, Border impl in CBCV and CV must call updateBorderProps / updateBorderLayoutMetrics
| <ul><li>[x] borderTopRightRadius</li></ul> |  | CVM | CBCV+SVCV | Fabric:#11323, Border impl in CBCV and CV must call updateBorderProps / updateBorderLayoutMetrics
| <ul><li>[x] borderTopStartRadius</li></ul> |  | CVM | CBCV+SVCV | Fabric:#11323, Border impl in CBCV and CV must call updateBorderProps / updateBorderLayoutMetrics
| <ul><li>[x] borderTopWidth</li></ul> |  | CVM+NUIM | CBCV+SVCV | Fabric:#11323, RN Core resolves LayoutMetrics, but border impl in CBCV and CV must call updateBorderProps / updateBorderLayoutMetrics
| <ul><li>[x] borderWidth</li></ul> |  | CVM+NUIM | CBCV+SVCV | Fabric:#11323, RN Core resolves LayoutMetrics, but border impl in CBCV and CV must call updateBorderProps / updateBorderLayoutMetrics
| <ul><li>[x] elevation</li></ul> | Android | No | No? | 
| <ul><li>[ ] opacity</li></ul> |  | FEVM | Pri 1 | 
| <ul><li>[x] transform</li></ul> |  | FEVM | CBCV+SVCV | Fabric: #12115 Impl in CBCV and CV must call updateTransformProps

## Layout Props

API | Platform | RNW Paper | RNW Fabric | Notes 
--:|:--:|:--:|:--:|:--
| <ul><li>[x] alignContent</li></ul> |  | NUIM | CBCV+SVCV | Fabric: RN Core resolves LayoutMetrics
| <ul><li>[x] alignItems</li></ul> |  | NUIM | CBCV+SVCV | Fabric: RN Core resolves LayoutMetrics
| <ul><li>[x] alignSelf</li></ul> |  | NUIM | CBCV+SVCV | Fabric: RN Core resolves LayoutMetrics
| <ul><li>[x] aspectRatio</li></ul> |  | NUIM | CBCV+SVCV | Fabric: RN Core resolves LayoutMetrics
| <ul><li>[x] borderBottomWidth</li></ul> |  | CVM+NUIM | CBCV+SVCV | Fabric:#11323, RN Core resolves LayoutMetrics, but border impl in CBCV and CV must call updateBorderProps / updateBorderLayoutMetrics
| <ul><li>[x] borderEndWidth</li></ul> |  | CVM+NUIM | CBCV+SVCV | Fabric:#11323, RN Core resolves LayoutMetrics, but border impl in CBCV and CV must call updateBorderProps / updateBorderLayoutMetrics
| <ul><li>[x] borderLeftWidth</li></ul> |  | CVM+NUIM | CBCV+SVCV | Fabric:#11323, RN Core resolves LayoutMetrics, but border impl in CBCV and CV must call updateBorderProps / updateBorderLayoutMetrics
| <ul><li>[x] borderRightWidth</li></ul> |  | CVM+NUIM | CBCV+SVCV | Fabric:#11323, RN Core resolves LayoutMetrics, but border impl in CBCV and CV must call updateBorderProps / updateBorderLayoutMetrics
| <ul><li>[x] borderStartWidth</li></ul> |  | CVM+NUIM | CBCV+SVCV | Fabric:#11323, RN Core resolves LayoutMetrics, but border impl in CBCV and CV must call updateBorderProps / updateBorderLayoutMetrics
| <ul><li>[x] borderTopWidth</li></ul> |  | CVM+NUIM | CBCV+SVCV | Fabric:#11323, RN Core resolves LayoutMetrics, but border impl in CBCV and CV must call updateBorderProps / updateBorderLayoutMetrics
| <ul><li>[x] borderWidth</li></ul> |  | CVM+NUIM | CBCV+SVCV | Fabric:#11323, RN Core resolves LayoutMetrics, but border impl in CBCV and CV must call updateBorderProps / updateBorderLayoutMetrics
| <ul><li>[x] bottom</li></ul> |  | NUIM | CBCV+SVCV | Fabric: RN Core resolves LayoutMetrics
| <ul><li>[x] direction</li></ul> |  | FEVM+NUIM | CBCV+SVCV | Fabric: RN Core resolves LayoutMetrics
| <ul><li>[x] display</li></ul> |  | FEVM+NUIM | SVCV | 
| <ul><li>[x] end</li></ul> |  | NUIM | CBCV+SVCV | Fabric: RN Core resolves LayoutMetrics
| <ul><li>[x] flex</li></ul> |  | NUIM | CBCV+SVCV | Fabric: RN Core resolves LayoutMetrics
| <ul><li>[x] flexBasis</li></ul> |  | NUIM | CBCV+SVCV | Fabric: RN Core resolves LayoutMetrics
| <ul><li>[x] flexDirection</li></ul> |  | NUIM | CBCV+SVCV | Fabric: RN Core resolves LayoutMetrics
| <ul><li>[x] flexGrow</li></ul> |  | NUIM | CBCV+SVCV | Fabric: RN Core resolves LayoutMetrics
| <ul><li>[x] flexShrink</li></ul> |  | NUIM | CBCV+SVCV | Fabric: RN Core resolves LayoutMetrics
| <ul><li>[x] flexWrap</li></ul> |  | NUIM | CBCV+SVCV | Fabric: RN Core resolves LayoutMetrics
| <ul><li>[x] height</li></ul> |  | VMB+NUIM | CBCV+SVCV | Fabric: RN Core resolves LayoutMetrics
| <ul><li>[x] justifyContent</li></ul> |  | NUIM | CBCV+SVCV | Fabric: RN Core resolves LayoutMetrics
| <ul><li>[x] left</li></ul> |  | VMB+NUIM | CBCV+SVCV | Fabric: RN Core resolves LayoutMetrics
| <ul><li>[x] margin</li></ul> |  | NUIM | CBCV+SVCV | Fabric: RN Core resolves LayoutMetrics
| <ul><li>[x] marginBottom</li></ul> |  | NUIM | CBCV+SVCV | Fabric: RN Core resolves LayoutMetrics
| <ul><li>[x] marginEnd</li></ul> |  | NUIM | CBCV+SVCV | Fabric: RN Core resolves LayoutMetrics
| <ul><li>[x] marginHorizontal</li></ul> |  | NUIM | CBCV+SVCV | Fabric: RN Core resolves LayoutMetrics
| <ul><li>[x] marginLeft</li></ul> |  | NUIM | CBCV+SVCV | Fabric: RN Core resolves LayoutMetrics
| <ul><li>[x] marginRight</li></ul> |  | NUIM | CBCV+SVCV | Fabric: RN Core resolves LayoutMetrics
| <ul><li>[x] marginStart</li></ul> |  | NUIM | CBCV+SVCV | Fabric: RN Core resolves LayoutMetrics
| <ul><li>[x] marginTop</li></ul> |  | NUIM | CBCV+SVCV | Fabric: RN Core resolves LayoutMetrics
| <ul><li>[x] marginVertical</li></ul> |  | NUIM | CBCV+SVCV | Fabric: RN Core resolves LayoutMetrics
| <ul><li>[x] maxHeight</li></ul> |  | NUIM | CBCV+SVCV | Fabric: RN Core resolves LayoutMetrics
| <ul><li>[x] maxWidth</li></ul> |  | NUIM | CBCV+SVCV | Fabric: RN Core resolves LayoutMetrics
| <ul><li>[x] minHeight</li></ul> |  | NUIM | CBCV+SVCV | Fabric: RN Core resolves LayoutMetrics
| <ul><li>[x] minWidth</li></ul> |  | NUIM | CBCV+SVCV | Fabric: RN Core resolves LayoutMetrics
| <ul><li>[ ] overflow</li></ul> |  | NUIM | Pri 1 | 
| <ul><li>[x] padding</li></ul> |  | CVM+NUIM | CBCV+SVCV | Fabric: RN Core resolves LayoutMetrics
| <ul><li>[x] paddingBottom</li></ul> |  | CVM+NUIM | CBCV+SVCV | Fabric: RN Core resolves LayoutMetrics
| <ul><li>[x] paddingEnd</li></ul> |  | CVM+NUIM | CBCV+SVCV | Fabric: RN Core resolves LayoutMetrics
| <ul><li>[x] paddingHorizontal</li></ul> |  | CVM+NUIM | CBCV+SVCV | Fabric: RN Core resolves LayoutMetrics
| <ul><li>[x] paddingLeft</li></ul> |  | CVM+NUIM | CBCV+SVCV | Fabric: RN Core resolves LayoutMetrics
| <ul><li>[x] paddingRight</li></ul> |  | CVM+NUIM | CBCV+SVCV | Fabric: RN Core resolves LayoutMetrics
| <ul><li>[x] paddingStart</li></ul> |  | CVM+NUIM | CBCV+SVCV | Fabric: RN Core resolves LayoutMetrics
| <ul><li>[x] paddingTop</li></ul> |  | CVM+NUIM | CBCV+SVCV | Fabric: RN Core resolves LayoutMetrics
| <ul><li>[x] paddingVertical</li></ul> |  | CVM+NUIM | CBCV+SVCV | Fabric: RN Core resolves LayoutMetrics
| <ul><li>[x] position</li></ul> |  | NUIM | CBCV+SVCV | Fabric: RN Core resolves LayoutMetrics
| <ul><li>[x] right</li></ul> |  | NUIM | CBCV+SVCV | Fabric: RN Core resolves LayoutMetrics
| <ul><li>[x] start</li></ul> |  | NUIM | CBCV+SVCV | Fabric: RN Core resolves LayoutMetrics
| <ul><li>[x] top</li></ul> |  | VMB+NUIM | CBCV+SVCV | Fabric: RN Core resolves LayoutMetrics
| <ul><li>[x] width</li></ul> |  | VMB+NUIM | CBCV+SVCV | Fabric: RN Core resolves LayoutMetrics
| <ul><li>[ ] zIndex</li></ul> |  | FEVM | Pri 1 | 

## Shadow Props

API | Platform | RNW Paper | RNW Fabric | Notes 
--:|:--:|:--:|:--:|:--
| <ul><li>[x] shadowColor</li></ul> |  | No | CBCV+SVCV | Fabric: #12108, Shadow props impl in CBCV and CV must call updateShadowProps
| <ul><li>[x] shadowOffset</li></ul> | iOS | No | CBCV+SVCV | Fabric: #12108, Shadow props impl in CBCV and CV must call updateShadowProps
| <ul><li>[x] shadowOpacity</li></ul> | iOS | No | CBCV+SVCV | Fabric: #12108, Shadow props impl in CBCV and CV must call updateShadowProps
| <ul><li>[x] shadowRadius</li></ul> | iOS | No | CBCV+SVCV | Fabric: #12108, Shadow props impl in CBCV and CV must call updateShadowProps

## Native Component Methods

API | Platform | RNW Paper | RNW Fabric | Notes 
--:|:--:|:--:|:--:|:--
| <ul><li>[x] blur()</li></ul> | Windows | VMB | CBCV | Fabric: #11323
| <ul><li>[x] focus()</li></ul> | Windows | VMB | CBCV | Fabric: #11323

# Glossary

See the [Glossary](https://github.com/microsoft/react-native-windows/issues/11135#glossary) to decode the abbreviations above and/or the [RNW Fabric Inventory.xlsx](https://microsoft.sharepoint-df.com/:x:/t/ReactNativeMicrosoft/EZvd2544Yn9PgmfDQyhq1xYBNcngo3_nNZvR6h_67IjP8w?e=UQz0jQ).

**Comment by rozele** [comment]
Not captured in props and events, but the scroll wheel functionality is a bit choppy. Is there an easy way to animate WM_MOUSEWHEEL events?

**Comment by jonthysell** [comment]
Closing this deliverable, all remaining component properties required for parity are now being tracked by individual issues.
