### ISSUE TITLE
Dependency script fails: Cannot index into a null array.

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#11165]
### Problem Description

When I run the dependency script I get the following error:

```
C:\Users\asdf> Set-ExecutionPolicy Unrestricted -Scope Process -Force;PS
C:\Users\asdf> iex (New-Object System.Net.WebClient).DownloadString('[https://aka.ms/rnw-vs2022-deps.ps1')](https://aka.ms/rnw-vs2022-deps.ps1%27))
Cannot index into a null array.
At line:15 char:1
+ $Verbose = $PSCmdlet.MyInvocation.BoundParameters["Verbose"].IsPresen ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException    + FullyQualifiedErrorId : NullArray
```

Alex sez:
sounds like this line needs a null check on BoundParameters
```$Verbose = $PSCmdlet.MyInvocation.BoundParameters["Verbose"].IsPresent;```

### Steps To Reproduce

1. Copy and run dependency script per website instructions

### Expected Results

No errors

### CLI version

error: unknown option '--version'

### Environment

```markdown
error: unknown command 'info'
(Did you mean init?)
```

### Target Platform Version

None

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

None

**Comment by jonthysell** [comment]
I just pushed a quick fix for this, too big of a blocker IMO: https://github.com/microsoft/react-native-windows/commit/4228abcf11a3df2aa1f9e3a3fd398faa3b27eead
