### ISSUE TITLE
Make Windows 10 10.0.10586 the minimum version

### ISSUE THREAD

**Issue by matthargett** [Microsoft/react-native-windows#1116]
I noticed that ChakraBridge cannot target any OS less than 10586, probably due to UWP C++ targeting being incomplete in Windows 10 retail release.

Additionally, original retail release of Windows 10 (10.0.10240) has had its [support ended](https://support.microsoft.com/en-us/help/13853/windows-lifecycle-fact-sheet).

Also, it looks like the 10586 version of the SDK doesn't quite work correctly on Windows 7 any more, due to this error: 
```
error APPX0002: Task 'GenerateAppxPackageRecipe' failed. 0x7F - Failed to load MRM support library.
```

For early adopters of Windows retail build who never connect to the network and never get updates, they are probably unlikely to be active users of the Store and therefore unlikely to be "shut out" of apps via this new requirement.

Thoughts, question, concerns?

**Comment by matthargett** [comment]
It's also worth noting that there was never a 10240 build for Mobile -- the first Windows 10 Mobile build appears to be 10586. Not sure about Xbox One.

**Comment by allanrsmith** [comment]
https://en.wikipedia.org/wiki/Xbox_One_system_software#Version_history
 ```The Shared Partition contained the Windows 8 Core at launch until November 2015, where via a system update known as the "New Xbox One Experience", it was upgraded to the Windows 10 Core``` Looks like Xbox One was also first on Windows 10 Core at 10586

**Comment by tim-soft** [comment]
So which SDK should be installed to use react-native-windows?

The readme lists Windows 10 SDK Build 14393, which seems pretty old at this point

**Comment by matthargett** [comment]
@tim-soft 14393 is the minimum one that I tested and found to work in a clean Windows 7 VM. Newer ones may work, but installing the 14393 (Windows 10 Anniversary Edition)  SDK is a good way to make sure you're not using newer APIs that would preclude Anniversary Edition users from running your RNW app.

**Comment by rozele** [comment]
No real reason to do this, but we'll likely set RS1 (14393) to the minimum version soon given there has not been much attempt to verify which APIs used are still compatible with TH1/2.
