### ISSUE TITLE
Animating transform properties with Animated API doesn't work properly with useNativeDriver set to true

### ISSUE THREAD

**Issue by Qurishe** [microsoft/react-native-windows#11181]
### Problem Description

I have used Animated API to define screen entrance and exit animations as well as creating a Modal animation which kind of scales and translates on X or Y axis to the screen but when the useNativeDriver is true the animation just stucks halfway and doesn't complete.

you can see in the video below the first time with useNativeDriver set to false it works fine but the second time set the useNativeDriver to true and the animation doesn't work properly.

https://user-images.githubusercontent.com/32069358/217607299-b51ad1a4-758a-4939-9006-e47262d1dbe5.mp4

### Steps To Reproduce

animate transform properties like any other property

### CLI version

0.70.0

### Environment

```markdown
System:
    OS: Windows 10 10.0.22000
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 2.59 GB / 9.90 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.32901.82 (Visual Studio Enterprise 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.0 => 0.70.0
    react-native-windows: 0.70.11 => 0.70.11
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Platform Version

None

### Visual Studio Version

None

### Build Configuration

None

**Comment by chrisglein** [comment]
Can you provide the code snippet in question where you applied the animation?
There a number of bugs with `useNativeDriver`, and this may or may not be one of the known ones (see [here](https://github.com/microsoft/react-native-windows/labels/Area%3A%20Animation)). Some more details would help narrow this down.
