### ISSUE TITLE
Is this project still being developed?

### ISSUE THREAD

**Issue by jsp3536** [Microsoft/react-native-windows#1120]
What is Microsoft commitment in supporting this?  I notice there hasn't been much activity with this Repo lately.  I would like to know Microsoft's commitment level before I invest a lot of time making an UWP app with this.

**Comment by matthargett** [comment]
Hi! There are multiple companies with deep investment in the project -- not just Microsoft. While we all work together to respond to issues reported in GitHub and on Discord (like my recent pull requests), and give feedback to/merge submitted pull requests, we do sometimes fall behind for a few weeks. Is there some specific activity you were looking for and not seeing?

**Comment by jsp3536** [comment]
Thanks for your response. I have been prototyping  an UWP app with react-native for windows and I have been excited by the results. I just wanted to confirm I was not going to paint myself in a corner going down this path. I appreciate all you guys  hard work on this.
