### ISSUE TITLE
Secure Supply Chain Analysis warnings because of incorrect NuGet.config

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#11209]
### Problem Description

From [this compliance run](https://dev.azure.com/microsoft/ReactNative/_build/results?buildId=64338597&view=logs&j=27307724-e5a4-5138-9d40-a20492a83fb9&t=627bd5ed-c745-5927-bcf8-24960fc147f0):

```
> Starting Multifeed Nuget Security Analysis:
##[warning]packages/playground/windows/NuGet.Config - Multiple feeds declared.
> Starting Multifeed Corext Analysis:
> Starting Multifeed Python Security Analysis:
> Starting CFS NuGet Analysis:
##[warning]packages/playground/windows/NuGet.Config - CFS0013: package source has value that is not an Azure Artifacts feed.
##[warning]NuGet.Config - CFS0012: missing declared or inherited <clear /> element.
##[warning]packages/e2e-test-app/windows/NuGet.Config - CFS0012: missing declared or inherited <clear /> element.
##[warning]packages/integration-test-app/windows/NuGet.Config - CFS0012: missing declared or inherited <clear /> element.
##[warning]packages/sample-apps/windows/NuGet.Config - CFS0012: missing declared or inherited <clear /> element.
##[warning]vnext/NuGet.Config - CFS0012: missing declared or inherited <clear /> element.
```

### Steps To Reproduce

See compliance pipeline: https://dev.azure.com/microsoft/ReactNative/_build?definitionId=79546&_a=summary

### CLI version

npx react-native --version

### Environment

```markdown
npx react-native info
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

None

**Comment by jonthysell** [comment]
It seems the following PRs are at least partially to blame:

* 0.69: #10766
* 0.70: #10770
* main: #11027

However it seems that we might also need to hardcode NuGet.org as the only source in the root NuGet.config.

**Comment by chrisglein** [comment]
Rename needs to happen first, then this config can be cleaned up.
