### ISSUE TITLE
[0.71.1] --useWinUI3, it cannot be debugged normally.

### ISSUE THREAD

**Issue by SF-Simon** [microsoft/react-native-windows#11221]
### Problem Description

> Restore:
>   X.509 certificate chain validation will use the default trust store selected by .NET.
>   ..\testCS\windows\testCS\testCS.csproj 的包...
>     GET https://api.nuget.org/v3-flatcontainer/microsoft.reactnative.windowsappsdk/index.json
>     OK https://api.nuget.org/v3-flatcontainer/microsoft.reactnative.windowsappsdk/index.json 913 毫秒
> ..\testCS\windows\testCS\testCS.csproj : error NU1102: 找不到版本为 (>= 0.71.1) 的包 Microsoft.ReactNative.WindowsAppSDK
> [..\testCS\windows\testCS.sln]
> ..\testCS\windows\testCS\testCS.csproj : error NU1102:   - 在 Nuget.org 中找到 40 个版本[ 最接近版本: 0.71.0 ] 
> [..\testCS\windows\testCS.sln]
> 

It seems that Nuget.org lacks version 0.71.1.

When I manually corrected version 0.71.0, this kind of problem occurred again.

> Command failed with error NoAppxManifest: Unable to find AppxManifest from "...\testCS", using search path: "windows/{*/bin/x64/Debug,x64/Debug/*,target/x64/Debug}/AppxManifest.xml"
> Your telemetry sessionId was 5a22fa9c0bb932888a7f9821ad4dfaac
> 

### Steps To Reproduce

npx react-native init testCS --template react-native
cd testCS 
npx react-native-windows-init --useWinUI3 --overwrite --language cs
npx react-native run-windows --logging

### CLI version

0.71.1

### Environment

```markdown
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.22621
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
  IDEs:
    Android Studio: Not Found
    Visual Studio: 17.4.33213.308 (Visual Studio Professional 2022)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.0 => 0.71.0
    react-native-windows: 0.71.1 => 0.71.1
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Platform Version

None

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

Debug

**Comment by chrisglein** [comment]
There was a publish issue that is the cause of the missing package. That's been resolved. Can you try again now that that's resolved?

**Comment by SF-Simon** [comment]
This problem has been fixed.  Previously, I manually lowered the version
number of the dependency, and it can also run normally.

Chris Glein ***@***.***>于2023年2月24日 周五03:22写道：

**Comment by smasinde** [comment]
I getting this issue again

**Comment by raeitan** [comment]
Getting this issue on 0.72.8
