### ISSUE TITLE
[0.71] Publishing stable releases fails on "Create GitHub Release"

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#11250]
### Problem Description

See: https://dev.azure.com/microsoft/ReactNative/_build/results?buildId=64464120&view=logs&j=bd0c9a5d-cce5-5ddc-8479-a97ca35bf82d&t=8479e205-8af0-5268-99d0-683d34bec7b7

This was hit both on RNW 0.71.0 and 0.71.1 publish and prevents the nugets from being built and published (even though NPM is published).

It looks like it might be a problem with trying to (re-)create `react-native-windows 0.71.0-preview.4` which already exists?

### Steps To Reproduce

See: https://dev.azure.com/microsoft/ReactNative/_build/results?buildId=64464120&view=logs&j=bd0c9a5d-cce5-5ddc-8479-a97ca35bf82d&t=8479e205-8af0-5268-99d0-683d34bec7b7

### CLI version

npx react-native --version

### Environment

```markdown
npx react-native info
```

### Target Platform Version

None

### Visual Studio Version

None

### Build Configuration

None

**Comment by jonthysell** [comment]
It looks like the tag and release were created for 0.71.0-preview.4, but GH was in a weird state where the release wasn't appearing in the list of releases. I've poked it so it appears and hopefully that fixes this.

**Comment by chrisglein** [comment]
We'll find out on Monday 🤞

**Comment by jonthysell** [comment]
Confirmed this is fixed.
