### ISSUE TITLE
Help Wanted: Can i build WPF apps targeted for Win 7 using react native windows?

### ISSUE THREAD

**Issue by himanshubakshi** [Microsoft/react-native-windows#1125]
I am exploring react native windows and want to understand what it means when we say that this supports WPF? 
Can i only develop WPF apps targeted for Win 10? Or can i do it for regular Win32 WPF apps as well. 

Any guidance on this would be helpful.

**Comment by matthargett** [comment]
Yes, you can use React Native Windows to target WPF on Windows 7 (and 8 and 10) desktops that have .NET 4.6 (or later) installed. We are doing exactly this on my project at work and it's been fantastic to reach desktop Windows users with the same JavaScript and React development skills we already had in our web team.
