### ISSUE TITLE
Add E2E Tests for ScrollView

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-windows#11297]
Add E2E Jest Snapshot Tests for FlatList. Tests should exist as samples within RNTester.

**STATUS TYPES**
| Status | Description |
| -- | --
| Not Implemented | Prop is not implemented for given architecture.
| Not Completed | No test or sample exists for the prop.
| Sample Completed | Sample exists for the prop, but sample is not run in a Jest Snapshot Test.
| Completed | Sample and Snapshot test exists for the prop.

**PROPS STATUS FOR FLATLIST**
| Test Description | Status (Paper) | Status (Fabric) | Notes
| -- | -- | -- | --
| Default | <ul><li>[x] Completed   – RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| AccessibilityHint | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| AccessibilityLabel | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| AccessibilityActions | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| AccessibilityRole | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| AccessibilityValue | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| ImportantforAccessibility   – no-hide-descendants | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| testID | <ul><li>[x] Completed - RN Tester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| Style –   backgroundColor | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| Style –   borderBottomColor | Not Implemented | <ul><li>[ ] Not Completed</li></ul>
| Style –   borderBottomEndRadius | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| Style   –borderBottomLeftRadius | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| Style –   borderBottomRightRadius | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| Style –   borderBottomStartRadius | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| Style –   borderBottomWidth | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| Style –   borderColor | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| Style –   borderEndColor | Not Implemented | <ul><li>[ ] Not Completed</li></ul>
| Style –   borderLeftColor | Not Implemented | <ul><li>[ ] Not Completed</li></ul>
| Style –   borderLeftWidth | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| Style –   borderRadius | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| Style –   borderRightColor | Not Implemented | <ul><li>[ ] Not Completed</li></ul>
| Style –   borderStartColor | Not Implemented | <ul><li>[ ] Not Completed</li></ul>
| Style –   borderStyle | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| Style –   borderTopColor | Not Implemented | <ul><li>[ ] Not Completed</li></ul>
| Style –  borderTopEndRadius | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| Style –  borderTopLeftRadius | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| Style –  borderTopRightRadius | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| Style –  borderTopStartRadius | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| Style –  borderTopWidth | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| Style –  borderWidth | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| Style –  elevation | Not Implemented | <ul><li>[ ] Not Completed</li></ul>
| Style – opacity | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| Style – height | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| Style – width | <ul><li>[x] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| Style – overflow | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| Accessible | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| Focusable | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| HitSlop | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| NativeID | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| NextFocus* | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| onAccessibilityAction | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| onAccessibilityTab | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| onAccessibilityEscape | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| onLayout | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| onMoveShoudlSetResponder | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| onMoveShouldSetResponderCapture | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| onResponderGrant | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| onResponderMove | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| onResponserReject| <ul><li>[ ] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| onResponderRelease | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| onResponderTerminate | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| onResponderTerminationRequest | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| onStartShouldSetResponder | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| onStartShouldSetResponderCatpure | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| pointerEvents | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| needsOffscreenAlphaCompositioning | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| toolTip | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| StickyHeaderComponent | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| contentContainerStyle | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| contentOffset | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| DecelerationRate | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| disableIntervalMomentum| <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| disabledScrollViewPanResponder | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| Horizontal | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| invertStickyHeaders | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| keyboardDismissMode | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| keyboardShouldPersistTaps | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| onContentSizeChanged | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| onMomentumScrollBegin | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| onMomentumScrollEnd | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| onScroll | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| onScrollBeginDrag | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| onScrollEndDrag | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| pagingEnabled | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| refreshControl | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| removeClippedSubviews | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| scrollEnabled | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| showsHorizontalScrollIndicator | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| showsVerticalScrollIndicator | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| snapToEnd | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| snapToAlignment | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| snapToInterval | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| snapToOffsets | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| snapToStart | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| stickHeaderHiddenOnScroll | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| stickyHeaderIndices | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| flashScrollIndicators() | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| scrollTo() | <ul><li>[ ] Not Completed</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| nestedScrollEnabled | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| automaticallyAdjustsScrollIndicatorInsets | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| automaticallyAdjustsContentInsets | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| maintainVisibleContentPosition | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| centerContent | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| scrollEventThrottle | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| persistentScrollbar | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| endFillColor | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| fadingEdgeLength | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| scrollToOverflowEnabled | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| scrollsToTop | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| contentInset | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| scrollIndicatorInsets | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| onScrollToTop | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| overScrollMode | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| pinchGestureEnabled | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| maximumZoomScale | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| minimumZoomScale | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| indicatorStyle | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| directionalLockEnabled | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| canCancelContentTouches | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| contentContainerStyle | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| contentInsetAdjustmentBehavior | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| Bounces | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| BouncesZoom | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| alwaysBounceHorizontal | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>
| alwaysBounceVertical | <ul><li>[x] Completed - RNTester</li></ul> | <ul><li>[ ] Not Completed</li></ul>

**Comment by chrisglein** [comment]
@chiaramooney Same title as #11296, and text above says `FlatList`.

**Comment by chiaramooney** [comment]
Duplicate.
