### ISSUE TITLE
Event bubble / capture broken for raw text nodes.

### ISSUE THREAD

**Issue by rozele** [Microsoft/react-native-windows#1131]
### Description

I'm getting an undefined reference exception due to the kind of node that is encountered in the event bubble / capture system:

![error](https://cloud.githubusercontent.com/assets/1106239/23633214/da8364ec-0292-11e7-84f6-69fb6237176e.png)

The reason seems to be related to 

### Reproduction

Run the `<View>` example in UIExplorer. In the `Z-Index` example, click one of the number text in one of the boxes. I.e.:

![example](https://cloud.githubusercontent.com/assets/1106239/23633230/e2608ea6-0292-11e7-80b0-2549f8d561e1.png)

### Solution

Still investigating:
1) determine why the raw text node for the number has type number (seems related to recent React upgrade)
2) Figure out if we need to expand the types of raw text nodes here to skip over:
https://github.com/facebook/react-native/blob/master/Libraries/Renderer/src/renderers/shared/shared/event/EventPluginHub.js#L141

### Additional Information

* React Native version: 0.43.0-rc.1
* Platform: UWP
* Operating System: Windows

Replaces https://github.com/facebook/react-native/issues/12750

**Comment by ndbroadbent** [comment]
@rozele Could you recommend a place where I could add a quick fix for this? Even just a `try-catch` block would be good, to ignore the error and fail silently instead of crashing. 

(It's just becoming difficult to switch between versions when testing and submitting/rebasing PRs.)

**Comment by rozele** [comment]
@ndbroadbent I think this is an issue in react@16.0.0-alpha.6, rather than an issue with react-native or react-native-windows. Which versions of react, react-native, and react-native-windows are you using? I think we'd have to patch react, or get the react-native team to upgrade 0.43 / 0.44...

**Comment by matthargett** [comment]
@ndbroadbent does this reproduce with 45-stable RNW 46-stable RN Android?

**Comment by rozele** [comment]
Closing as this issue was specific to react@16.0.0-alpha.6
