### ISSUE TITLE
Get all tests running for UWP

### ISSUE THREAD

**Issue by rozele** [Microsoft/react-native-windows#1134]
The NUnit tests are currently not running for UWP from Visual Studio. If we can't get all the UWP unit tests running from Test Explorer with MSTest and NUnit, we may just have to maintain copies of the unit tests, one using NUnit and the other using MSTest. cc @matthargett (sorry, I know we've been over this a bunch of times).

**Comment by matthargett** [comment]
This was working before across multiple machines, but it does appear to be touchy depending on the environment somehow. I'd like to try two things that would hopefully make it work more consistently before taking drastic measures:
* Update to latest NUnit 3.x and NUNit3TestAdapter
* Convert to VS2017

**Comment by rozele** [comment]
Closing for now, as this generally works in VS (assuming the NUnit plugin is cooperating)
