### ISSUE TITLE
File system in UWP

### ISSUE THREAD

**Issue by GurtejSafaltek** [Microsoft/react-native-windows#1135]
Hi,How can i use file system functions like read file, write file ,create folder etc,  It's urgent for me because i'm developing app for android, ios and UWP using react native, react-native-fs (https://github.com/itinance/react-native-fs)  is only available for android and ios

**Comment by zerglingno1** [comment]
i just write a simple code here : https://github.com/hnq90/react-native-filesystem

**Comment by GurtejSafaltek** [comment]
@zerglingno1  Thanks for the response,It looks like that your code is only for android and ios not for the UWP app

**Comment by GurtejSafaltek** [comment]
@zerglingno1  Thanks for your response ,will check it and let you know if it is working for me or not

**Comment by rozele** [comment]
It's been added.
