### ISSUE TITLE
Reanimated 3 "The native part of Reanimated doesn't seem to be initialized"

### ISSUE THREAD

**Issue by JakeHedman** [microsoft/react-native-windows#11368]
### Problem Description

Running an app with reanimated 3 installed and hermes enabled causes the following error:

```
 ERROR  [Reanimated] The native part of Reanimated doesn't seem to be initialized. This could be caused by
  - not rebuilding the app after installing or upgrading Reanimated
  - trying to run Reanimated on an unsupported platform
```

### Steps To Reproduce

1. Enable hermes
2. Install react-native-reanimated
3. Start app

### CLI version

10.0.0

### Environment

```markdown
System:
    OS: Windows 10 10.0.22621
    CPU: (4) x64 Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz
    Memory: 10.55 GB / 19.52 GB
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowAllTrustedApps: Enabled
      AllowDevelopmentWithoutDevLicense: Enabled
      Versions: 10.0.19041.0, 10.0.22000.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 17.5.33414.496 (Visual Studio Community 2022)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.0 => 0.71.0
    react-native-windows: 0.71.3 => 0.71.3
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Platform Version

None

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

Debug

**Comment by chrisglein** [comment]
Reanimated is partially implemented: https://github.com/microsoft/react-native-windows/issues/4151
Specifically the native parts aren't implemented. And won't be on Paper. But is something that can be considered with Fabric.
So for now, this is working as intended, which is to say this module isn't fully supported on Windows at the moment.

**Comment by exotexot** [comment]
Having the same issue, and opened an issue here: https://github.com/software-mansion/react-native-reanimated/issues/4402

@chrisglein but previous versions of reanimated were working with react-native-windows. I dont know excatly when it started to break - I will test if I can go back to unblock it. 
However, reanimated is needed for the Drawer Navigation from  react-navigation ...

**Comment by HunainHumail** [comment]
We developers need support of react native reanimated on react native windows.. React Native Reanimated is a very big library, used in almost every project! I just separated my react native windows code base from my main project just because it was crashing on reanimated and my android and ios apps were using that for some classy animations. So there must be support for React Native Windows. Waiting for that, Please add that to the plans..
