### ISSUE TITLE
Remove override of PerformanceApiExample.js

### ISSUE THREAD

**Issue by TatianaKapos** [microsoft/react-native-windows#11373]
### Problem Description

Recent [Integration](https://github.com/microsoft/react-native-windows/pull/11353/commits/968651f20e11d91ee90bc5c3d55483f24a36bb55) creates an example in rn-tester that uses [relative pathing](https://github.com/facebook/react-native/blob/main/packages/rn-tester/js/examples/Performance/PerformanceApiExample.js#L19) instead of module pathing which cause us to override the file.

Fix is to make upstream PR and remove override in future integration.

### Steps To Reproduce

1. Set PerformanceApiExample.js to copy in override file

### Expected Results

Playground should build fine

### CLI version

npx react-native --version

### Environment

```markdown
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Memory: 40.95 GB / 63.85 GB
  Binaries:
    Node: 16.12.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  Managers:
    RubyGems: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.17763.0, 10.0.18362.0, 10.0.19041.0, 10.0.22000.0
  IDEs:
    Android Studio: AI-213.7172.25.2113.9014738
    Visual Studio: 16.11.33328.57 (Visual Studio Enterprise 2019), 17.4.33403.182 (Visual Studio Enterprise 2022)
  Languages:
    Java: 11.0.16.1 - C:\Program Files\Eclipse Adoptium\jdk-11.0.16.101-hotspot\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

Debug

**Comment by chrisglein** [comment]
PR is merged upstream. Need to take with the next integration.
