### ISSUE TITLE
Native module in app fails to find constants with web debugging disabled (release)

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#11385]
### Problem Description

I have some native code in my app that I'm surfacing. Not via an external module (those are all working fine). This works fine in debug builds but not in release, and after debugging through it seems to be that that's because in release web debugging is disabled the module is treated as a turbo module. And for some reason it's not discovered as a turbo module.

I followed the documentation as closely as I could. What am I missing?

The module is registered, but in release mode it's going to go down this turbo module path per here:
```cpp
void ReactPackageBuilder::AddTurboModule(
    hstring const &moduleName,
    ReactModuleProvider const &moduleProvider) noexcept {
  if (m_isWebDebugging)
    m_modulesProvider->AddModuleProvider(moduleName, moduleProvider);
  else
    m_turboModulesProvider->AddModuleProvider(moduleName, moduleProvider, true);
}
```

When I debug through `TurboModulesProvider` and it gets here:

`facebook::jsi::Value get(facebook::jsi::Runtime &runtime, const facebook::jsi::PropNameID &propName)`
https://github.com/microsoft/react-native-windows/blob/main/vnext/Microsoft.ReactNative/TurboModulesProvider.cpp#L145

The `propName` here is "appVersion" (the constant on my module). But the code seems to expect "getConstants".

```cpp
    if (key == "getConstants" && !m_moduleBuilder->ConstantProviders().empty()) {
      // try to find getConstants if there is any constant
      return facebook::jsi::Function::createFromHostFunction(
          runtime,
          propName,
          0,
          [moduleBuilder = m_moduleBuilder](
              facebook::jsi::Runtime &rt,
              const facebook::jsi::Value & /*thisVal*/,
              const facebook::jsi::Value * /*args*/,
              size_t /*count*/) {
            // collect all constants to an object
            auto writer = winrt::make<JsiWriter>(rt);
            writer.WriteObjectBegin();
            for (auto const &constantProvider : moduleBuilder->ConstantProviders()) {
              constantProvider(writer);
            }
            writer.WriteObjectEnd();
            return writer.as<JsiWriter>()->MoveResult();
          });
    }
```

### Steps To Reproduce

Consuming app code:
```tsx
import VersionInfo from './NativeVersionInfo'
...
<Text>{VersionInfo.appVersion}</Text>
```

NativeVersionInfo.ts
```ts
import type { TurboModule } from 'react-native/Libraries/TurboModule/RCTExport';
import { TurboModuleRegistry } from 'react-native';

export interface Spec extends TurboModule {

  getConstants: () => {
    appVersion: string,
    buildVersion: string,
  };
}

export default TurboModuleRegistry.get<Spec>(
  'VersionInfo'
) as Spec | null;
```

VersionInfo.h
```cpp
#pragma once

#include "pch.h"

#include "NativeModules.h"
#include "../../codegen/NativeVersionInfoSpec.g.h"

#include <winrt/Windows.ApplicationModel.h>
#include <strsafe.h>

namespace ArtificialChatModules
{
    REACT_MODULE(VersionInfo);
    struct VersionInfo
    {
        using ModuleSpec = VersionInfoSpec;

        REACT_GET_CONSTANTS(GetConstants)
        VersionInfoSpec_Constants GetConstants() noexcept
        {
            winrt::Windows::ApplicationModel::PackageVersion version = winrt::Windows::ApplicationModel::Package::Current().Id().Version();

            VersionInfoSpec_Constants constants;
            char buffer[256];
            StringCchPrintfA(buffer, _countof(buffer), "%d.%d.%d", version.Major, version.Minor, version.Build);
            constants.appVersion = std::string(buffer);
            constants.buildVersion = std::to_string(version.Revision);
            return constants;
        }
    };
}
```

And yes I realize that [there's a module for this](https://github.com/tessus/react-native-version-info), but it's on the old modules infrastructure and I thought I'd implement it in my app before committing a PR back to that module to update it. Plus I need the ability to drop into native code without always having to go to an external module.

### Expected Results

Module works in release because it worked in debug

### CLI version

10.0.0

### Environment

```markdown
System:
    OS: Windows 10 10.0.25319
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 763.84 MB / 15.92 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.19041.0, 10.0.22000.0, 10.0.22621.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 17.5.33424.131 (Visual Studio Community 2022), 16.11.33328.57 (Visual Studio Community 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.0 => 0.71.0
    react-native-windows: 0.71.1 => 0.71.1
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

Release

**Comment by acoates-ms** [comment]
What does the JS using these constants look like?

If you look at say the AppState module in RN when it moved to TurboModules, you'll see that from the JS side, if you want code that is compatible with both NativeModules and TurboModules you need to change the JS to call getConstants(), which should work in the old NativeModule too.
https://github.com/facebook/react-native/commit/d9930897a8ab80fb49628efb2a08d1e0c4d4fee6#diff-3402d8d0082acba7a28c141bf8ca9aa3ae63c4dd9dfcf210c3d4b5bea739bdc1

**Comment by chrisglein** [comment]
Docs need to be updated to have the right instructions that are compatible with TurboModules. Need to dupe to doc issue.
