### ISSUE TITLE
when using onMouseEnter/onMouseLeave and an animated scale transform the component does not respond

### ISSUE THREAD

**Issue by Victor0814gui** [microsoft/react-native-windows#11392]
### Problem Description

when using onMouseEnter/onMouseLeave and the Animated api of react-native to control scale, height and width transformations the component does not respond, unless it is removed and created again, but if I use some height and width change the component simply breaks the entire application, even if the component no component recalculation hook

### Steps To Reproduce

1- follow the example steps https://reactnative.dev/docs/animated changing opacity by height and width
2 - use the View component's onMouseEnter and onMouseLeave properties

### Expected Results

change smoothly just like on IOS and Android

### CLI version

0.69-0.70.10

### Environment

```markdown
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i5 CPU         650  @ 3.20GHz
    Memory: 896.22 MB / 7.93 GB
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30, 31, 32, 33
      Build Tools: 30.0.3, 31.0.0, 33.0.0
      System Images: android-26 | Google Play Intel x86 Atom, android-28 | Wear OS Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-31 | Intel x86 Atom_64, android-31 | Google TV Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0, 10.0.22000.0
  IDEs:
    Android Studio: AI-213.7172.25.2113.9123335
    Visual Studio: 17.4.33213.308 (Visual Studio Enterprise 2022)
  Languages:
    Java: 11.0.15 - C:\Program Files\OpenJDK\openjdk-11.0.15_10\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: 0.69.0 => 0.69.0
    react-native-windows: 0.69.21 => 0.69.21
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Platform Version

None

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

Debug

**Comment by Victor0814gui** [comment]
@chrisglein  Simples example https://github.com/Victor0814gui/animationsample

**Comment by chrisglein** [comment]
Adding the key bits here for reference:
```jsx
const Box = () => {
  const boxRef = React.useRef(new Animated.Value(1)).current

  const onMouseEnter = () => {
    Animated.spring(boxRef,{
      useNativeDriver: true,
      toValue: 1.3
    }).start()
  }
  const onMouseLeave = () => {
    Animated.spring(boxRef,{
      useNativeDriver: true,
      toValue: 1
    }).start()
  }

  return (
    <Animated.View 
      //@ts-ignore
      onMouseEnter={onMouseEnter}
      onMouseLeave={onMouseLeave}
      style={[
        styles.box,
        {
          transform:[{scale: boxRef}]
        }
      ]}
    />
  )
}
```

Not sure if a problem with the partial `useNativeDriver` implementation (lots of issues [here](https://github.com/microsoft/react-native-windows/labels/Area%3A%20Animation))

**Comment by Victor0814gui** [comment]
somehow in version 0.71.6 it works perfectly with useNativeDriver: false, the solution I found was to update the project to the latest version.
