### ISSUE TITLE
Create Microsoft.ReactNative.Win32.CppApp.props 

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-windows#11416]
Proposal from https://github.com/microsoft/react-native-windows/pull/11407.

We should consider making a Microsoft.ReactNative.Win32.CppApp.props (or something else instead of Win32) so we can start to diverge from the UWP requirements without overcomplicating the existing file.

**Comment by chiaramooney** [comment]
Agree that this should be work for 0.73 milestone instead of v0.72. Not immediately pressing work. Functionality works fine for now, but will be good to do this work in future. Tagging with needs attention so it can be assigned to the right dev.

**Comment by TatianaKapos** [comment]
This didn't get done is v73, is this work required for v74 or should it be moved to backlog?

**Comment by chrisglein** [comment]
@jonthysell how does this align with your app template work? Part of #11920 or no?

**Comment by jonthysell** [comment]
This works is already done with the Composition.CppApp.props file
