### ISSUE TITLE
Overflow doesn't work

### ISSUE THREAD

**Issue by AkshatSharda** [Microsoft/react-native-windows#1142]
Overflow doesn't works on windows. Similar issue is on android but it works for ios properly.
style={{overflow: 'hidden'}}

**Comment by pranavrajsinghchauhan** [comment]
We also facing the same concern. Is overflow supported on RN-Windows?

**Comment by rozele** [comment]
Overflow should be working, however it can only handle rectangular clipping: https://github.com/Microsoft/react-native-windows/blob/master/ReactWindows/ReactNative/UIManager/BaseViewManager.cs#L61-L72
