### ISSUE TITLE
ellipsizeMode property of Text is not working as expected

### ISSUE THREAD

**Issue by Abhishe08k** [microsoft/react-native-windows#11434]
### Problem Description

Problem : In react native Windows, we have a pill which contains text(user name) and a close button. If user name is too large, close button is not seen. We are observing this when text size is increased to 200% [ control panel->settings->Accessibility->Text size]. Further we are able to repro this with normal text size as well when user name is too large to get fit into the container.
 

- We have tried using flex box and the issue gets resolved but even if the user name is small, the close button appears at extreme right which makes sense as well. But, we do not want this.

- **Ideal Scenario** This is what we want.  close button should be next to the user name(Nilay Sanghvi). If size of the user name increases, the size of the pill should increase. And, if the entire name can not be accommodated, at the tail ellipses should appear and then the close button.

![image](https://user-images.githubusercontent.com/109737224/228423907-405bbf5f-0393-41d1-a53a-7c1ffc53a94e.png)

- **Problematic scenario:** This is what is happening as of now. We tried using ellipsizeMode. But. its not getting honored (see below). We tried using ellipsizeMode in conjunction with numberOfLines but this is not giving the desired result.

![image](https://user-images.githubusercontent.com/109737224/228423994-cafc0152-23d0-4e41-bee8-597b3f7674be.png)

**<Text** style={getThemeStyles(styleKeys.personaPillText, theme)} **ellipsizeMode='tail' numberOfLines={1}**>
                        {"abhishek abhishek abhishek abhishek abhishek abhishek abhishek abhishek abhishek abhishek abhishek abhishek" }
**</Text>**
	

- **Other scenario**: If we use flex box, its working as expected for the long names. But for shorter name as well, close button is at the extreme right which we don't want.

![image](https://user-images.githubusercontent.com/109737224/228424056-ddfa0212-5cae-4bb0-b3eb-4411190c54fe.png)

![image](https://user-images.githubusercontent.com/109737224/228424116-182c9d5d-2e13-43d2-8630-955296474b56.png)

Is ellipsizeMode not supported on Windows? Is there any other property that we can use here? can you please help us in getting this resolved? 

### Expected Results

Close button should always be visible. And it should appear just after the text. If text is too large, ellipses should appear at the tail of the text and then, close button should appear. 
Close button should always be visible next to the text irrespective of the size of the text.

If text is too large and cannot be fit into the container, ellipses should always appear as per ellipsizeMode property.

### CLI version

9.3.2

### Environment

```markdown
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz
    Memory: 44.65 GB / 63.59 GB
  Binaries:
    Node: 14.21.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.18 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.17763.0, 10.0.19041.0, 10.0.22000.0, 10.0.22621.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 17.5.33516.290 (Visual Studio Enterprise 2022)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.1 => 0.70.1
    react-native-windows: 0.70.2 => 0.70.2
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

ReleaseBundle

**Comment by Abhishe08k** [comment]
Further, using flex i was able to bring the cross button closer to the text if its smaller.
![image](https://user-images.githubusercontent.com/109737224/228537969-fab1a0a7-8ec2-4f99-a294-8fb1ee959346.png)

For longer text,
![image](https://user-images.githubusercontent.com/109737224/228541040-40b6d4c3-43d1-4706-af7e-e938a9f91b26.png)


But the issue is : the background color is taking the size of the entire container. And it is visible in case text is small.

**Comment by chrisglein** [comment]
The background size taking the size of the entire container is likely due to your alignment settings on the parent container. I was able to get the sort of behavior you're looking for with this markup (adapted from your snack):

```
      <View style={{
          backgroundColor: 'pink',
          flexGrow: 0,
          alignItems: 'flex-start',
          padding: 24}}>
        <View style={{
          flexGrow: 0,
          backgroundColor: 'aliceblue',
          flexDirection: 'row',
          alignItems: 'center',
          marginRight: 80}}>
          <Text style={{
              flexGrow: 0,
              flexShrink: 1,
              marginHorizontal: 5}}
            numberOfLines={1}>ABhishek ABhishek ABhishek ABhishek ABhishek ABhishek ABhishek ABhishek ABhishek ABhishek ABhishek ABhishek ABhishek ABhishek
          </Text>
          <Button
            title="Press me"
            onPress={() => {}}/>
        </View>
      </View>
```

![image](https://user-images.githubusercontent.com/26607885/229606837-81c0d39c-f477-4dab-bbc7-cf8585a0b9b2.png)
![image](https://user-images.githubusercontent.com/26607885/229606910-e76422e6-f0c5-4962-801f-19fc5675f6b4.png)

**Comment by Abhishe08k** [comment]
Thank you @chrisglein for your time. I will definitely try this.
I was also able to do this by defining the max width of the text i term of percentage of the container.

![Image (2)](https://user-images.githubusercontent.com/109737224/229980611-7f479d56-df1a-4ea9-b9a6-8d15c9919698.png)
