### ISSUE TITLE
`gap` incorrectly applies space after last item, not just between items

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#11442]
### Problem Description

The entire point of the `gap` style property is to apply space between items rather than after each item. If you want space after each item, use a margin.

https://reactnative.dev/docs/flexbox#row-gap-column-gap-and-gap

### Windows
![image](https://user-images.githubusercontent.com/26607885/229585892-8e0d0c60-0bc1-4cf2-89ba-41c4b932c05c.png)

### Web (via Snack below)
![image](https://user-images.githubusercontent.com/26607885/229586323-2ad9099d-c5b8-44e3-b5ff-a5930139aa31.png)

### Steps To Reproduce

```js
<View style={{flexDirection: 'column', gap: 8, backgroundColor: 'green'}}>
  <Text style={{backgroundColor: 'red'}}>Hello</Text>
  <Text style={{backgroundColor: 'blue'}}>World</Text>
</View>
```

### Expected Results

![image](https://user-images.githubusercontent.com/26607885/229586323-2ad9099d-c5b8-44e3-b5ff-a5930139aa31.png)

### CLI version

10.0.0

### Environment

```markdown
System:
    OS: Windows 10 10.0.23431
    CPU: (24) x64 AMD Ryzen Threadripper PRO 3945WX 12-Cores
    Memory: 44.37 GB / 63.86 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 9.4.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0, 10.0.22000.0, 10.0.22621.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 17.5.33516.290 (Visual Studio Community 2022), 16.11.33423.256 (Visual Studio Community 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.0 => 0.71.0
    react-native-windows: 0.71.1 => 0.71.1
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

Debug

### Snack, code example, screenshot, or link to a repository

https://snack.expo.dev/3JaAmzz_j

**Comment by chrisglein** [comment]
Another example of a horizontal gap. Red background on the parent container with an 8 pixel gap, some dialog buttons as the children:
![image](https://user-images.githubusercontent.com/26607885/229590731-a35d6439-63c1-4d72-91dc-300caeb06a4e.png)

**Comment by chrisglein** [comment]
This should be implemented by Yoga. I have this app ported to Fabric, I'll do a comparison there. And then see if there's any upstream issue. Unless Windows is mapping to the wrong property somehow, this should work.

**Comment by NickGerleman** [comment]
This was fixed in Yoga with https://github.com/facebook/yoga/commit/ba27f9d1ecfa7518019845b84b035d3d4a2a665, backported to RN 0.71.0-rc.5 with  https://github.com/facebook/react-native/commit/a0ee98dfeec1a75e649a935b733c70ae2cc1628d before we released.

Looks like RNW is missing the change.
