### ISSUE TITLE
Remove TurboModule.h Override

### ISSUE THREAD

**Issue by TatianaKapos** [microsoft/react-native-windows#11453]
### Problem Description

In [recent integration](https://github.com/microsoft/react-native-windows/pull/11450), RN calls a function with an unreferenced formal parameter which we treat as an error. Make PR upstream to get rid of this error.

`node_modules\react-native\ReactCommon\react\nativemodule\core\ReactCommon\TurboModule.h(123,33): Error C4100: 'thisVal': unreferenced formal parameter
`

### Steps To Reproduce

1. Remove override
2. Try to build playground

### Expected Results

playground runs without errors

### CLI version

npx react-native -v

### Environment

```markdown
npx react-native info
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

Debug

**Comment by chrisglein** [comment]
@TatianaKapos Can you link the upstream PR you have to fix this?

**Comment by TatianaKapos** [comment]
PR that fixes the issue: https://github.com/facebook/react-native/pull/36853
