### ISSUE TITLE
Popup autoFocus implementation change to automatically focus on component

### ISSUE THREAD

**Issue by YajurG** [microsoft/react-native-windows#11454]
### Summary

Currently, the `autoFocus` property for the Popup component does not automatically shift focus to the component when opened, but only adds it to the tabIndex. This does not do anything different than the `accessible` and `focusable` properties do. In order to automatically shift focus to a popup when opened, we currently have to use `setAccessibilityFocus` method.

### Motivation

This will be a QOL change for using Popups, as the expected behavior, particularly from an accessibility point of view, is that focus will shift to the popup automatically when it is opened. Instead of having to use the setAccessibilityFocus method and account for re-rendering and synchronous changes within React Native components, we can simply set the `autoFocus` property to be true.

### Basic Example

Example popup with the autoFocus property
```
<Popup accessible={true}
       focusable={true}
       accessibilityHint={'this is the popup'}
       autoFocus={true}
       isOpen={showPopup1}>
```

**Comment by chrisglein** [comment]
Related: https://github.com/microsoft/react-native-windows/issues/3372
What's the implementation state for this across all components?

Core only has `autoFocus` for TextInput: https://reactnative.dev/docs/textinput#autofocus
Popup is a RNW-only component. So how it handles autoFocus probably folds into whether we support in other components.
