### ISSUE TITLE
Implement TextInput.onChangeText for Fabric

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#11462]
Part of https://github.com/microsoft/react-native-windows/issues/11145

This one is particularly egregious because without this working you can't actually get the text out of a TextInput.

**Comment by chrisglein** [comment]
Seems to be working fine? Not sure why it's not marked in the table. @jonthysell why was this one unchecked?

<html>
<body>


 onChangeText | TIVM | Pri 1 | Event is topTextInputChangeText
-- | -- | -- | --



</body>
</html>

**Comment by chrisglein** [comment]
This works as far as I can tell. Not sure why it wasn't set in the table. @jonthysell @TatianaKapos  do you know?

**Comment by TatianaKapos** [comment]
Tested on rntester, this works in fabric today so I'm going to close this issue and update the table :)
