### ISSUE TITLE
Update Community Modules to `WindowsTargetPlatformMinVersion` v10.0.17763.0

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-windows#11494]
With the upgrade of RNW to WinUI 2.8 in https://github.com/microsoft/react-native-windows/pull/11493, all modules must now set their `WindowsTargetPlatformMinVersion` to at least v10.0.17763.0. We should take a pass through all of the community modules we support and check if they need an upgrade. 

Note: We'll want this work completed before v0.72 is released, since the bump to Win2.8 will be in v0.72 and we don't want to release the new version while some of our main community modules are not compatible with it. Will also block gallery.

**Comment by chiaramooney** [comment]
@TatianaKapos is now handling this. Tatiana this issue may be a duplicate at this point; I think you might have a seperate issue to track this work. Either way feel free to close when the work is done!

**Comment by TatianaKapos** [comment]
closing, tracking here: https://github.com/microsoft/react-native-gallery/issues/324
