### ISSUE TITLE
Add Node 18 to Pipeline Options for Node

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-windows#11521]
In https://github.com/microsoft/react-native-windows/pull/11500 we upgrade the node version in the repository to Node 16. However, since Node 18 is released we would also like this version of node to run in our pipelines. 

See https://github.com/microsoft/react-native-windows/blob/6a15837a441c23df1e2fb4c1257bc835a49539f2/.ado/jobs/node-tests.yml#L14. This should also include Node 18. However, currently there are errors that throw when we enable Node 18 because there is an API that has been deprecated in Node 18 that we make use of in our code.  This API must be updated as well.

**Comment by chrisglein** [comment]
@TatianaKapos Is this resolved?

**Comment by TatianaKapos** [comment]
resolved via https://github.com/microsoft/react-native-windows/pull/11858
