### ISSUE TITLE
@tanstack/query needs Object.fromEntries and Array.flatMap polyfills to work on react-native-windows. 

### ISSUE THREAD

**Issue by exotexot** [microsoft/react-native-windows#11526]
### Problem Description

Hello,

I'm using https://github.com/TanStack/query.
On Windows I cannot run  https://tanstack.com/query/v4/docs/react/reference/useQueries

It requires polyfills for Object.fromEntries and Array.flatMap.
I wonder if this is an react-native-windows issue - as it works on ios/android - or if this is an TanStack/query issue? If its the latter I will try and make a PR.

### Steps To Reproduce

1. create new rn-windows app
2. install tanstack/query
3. use useQueries hook
4. => crash

### Expected Results

Not crashing application

### CLI version

10.2.0

### Environment

```markdown
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Memory: 8.64 GB / 15.97 GB
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0, 10.0.22000.0, 10.0.22621.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 17.5.33516.290 (Visual Studio Community 2022)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.4 => 0.71.4
    react-native-windows: 0.71.6 => 0.71.6
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

Debug

**Comment by chrisglein** [comment]
@exotexot By default you'll be using Chakra. But you can [opt into Hermes](https://microsoft.github.io/react-native-windows/docs/hermes). The behavior you see here will very much depend on the JS engine. Did you change the JS engine? And do you have more source you can share with us?
