### ISSUE TITLE
Blank screen when deployed to hockeyapp

### ISSUE THREAD

**Issue by metalmalte** [Microsoft/react-native-windows#1152]
Hi,

after I deployed my app to hockeyapp, the view of the app is white. It seems like the JS is not loaded. This only happens when I upload the app. When I run it locally, the app runs as expected.

Tell me if you need additionally information!

I changed my the package name to a domain xx.yyyy.zzzzz
Could that be somehow related to the problem?

Also I had to create the ReactAssets folder myself. It is now bundled with the app.

**Comment by matthargett** [comment]
When you say "run it locally", are you launching the appx package locally? Or starting it from a non-packages (Debug) build?

**Comment by metalmalte** [comment]
With locally I mean the debug build with the React Native server running. This works perfect. It seems to me like the release version is not looking for the js bundle in the right directory. But I am just a Windows development noob.

**Comment by rozele** [comment]
@metalmalte is this just a problem for the HockeyApp build, or can you reproduce locally by producing a Release build?

**Comment by sayar** [comment]
@metalmalte were you able to resolve this issue?

**Comment by sayar** [comment]
@metalmalte It seems as though your issue has been resolved. If you don’t mind, I will close this issue in 1 day unless I get an update from you.
