### ISSUE TITLE
Switch bounding box is not centered

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#11558]
Screenshot taken from React Native Gallery and using Accessibility Insights:
![image](https://user-images.githubusercontent.com/26607885/236301576-6e3ed721-1afd-4d2a-a6b4-d69c9f9f03cc.png)

Contrast with this screenshot from WinUI 2 Gallery:
![image](https://user-images.githubusercontent.com/26607885/236301723-b86244ef-5800-488e-bc03-5c433ad8a132.png)

I'm guessing this is related from using that switch but not in the usual Windows style of including a label?

Originally reported here:
              ![react-native switch paddingLeft not working cursor](https://user-images.githubusercontent.com/92716081/236297856-0698a06d-2922-48e7-8bb4-7cb6f486621b.png)

@chrisglein , You can see the difference between Switch placeholders in the above screen.

_Originally posted by @bahri-dev in https://github.com/microsoft/react-native-windows/issues/11554#issuecomment-1535233609_

**Comment by acoates-ms** [comment]
> I'm guessing this is related from using that switch but not in the usual Windows style of including a label?

I think the answer is worse than that.

https://github.com/facebook/react-native/blob/80ecbdf2b28f3ee6c80a183a09c32482caa36134/packages/react-native/Libraries/Components/Switch/Switch.js#L226

Switch has a hard coded size in core/iOS, and we are not using anything different for windows.

**Comment by bahri-dev** [comment]
> I think the answer is worse than that.
> 
> Switch has a hard coded size in core/iOS, and we are not using anything different for windows.

I tried to change width, height, paddingLeft in the above file. width and height work fine, but paddingLeft doesn't work.
That's why I'm asking how I can fix the placeholder issue of Switch component.

**Comment by chrisglein** [comment]
I'm a bit worried about changing the alignment for Switch on Paper and breaking an unknown number of RNW apps' look and feel in a subtle way. We're working on moving to Fabric and it has its own Switch control that at least now shares no lineage with the XAML ToggleSwitch this time around.

Question is, what size _should_ it be? That probably depends on what the Fluent standards are?

Action here: double check that we have good sizing/centering in Fabric.
For Paper, I'm proposing we won't fix this.

**Comment by bahri-dev** [comment]
@chrisglein , the size of Slider can be changed by using width, height styles. That's why it's okay. I wish to add paddingLeft too. Then, we can change the position as similar as size. Then it's okay even though it's not center align.

**Comment by marlenecota** [comment]
I can confirm that Switch is centered on Fabric:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/1422161/236914187-a0fe92a2-9a28-4d9a-be63-80725fc142e8.png">

**Comment by bahri-dev** [comment]
@marlenecota , how can I check out the above screen? Could you share the git repo?

**Comment by marlenecota** [comment]
@bahri-dev it's the [playground app](https://github.com/microsoft/react-native-windows/blob/main/packages/playground) that is part of this repo. Be sure to use the [composition (fabric) solution](https://github.com/microsoft/react-native-windows/blob/main/packages/playground/windows/playground-composition.sln).

**Comment by bahri-dev** [comment]
@marlenecota , I tried to build playground app in Win 11, but it's failed.
![react-native-windows playground build error](https://github.com/microsoft/react-native-windows/assets/92716081/17803fe9-d90d-4a93-86ce-3b6faa4379c8)
Could you let me know how I can fix it?

**Comment by bahri-dev** [comment]
@marlenecota , I tried to use react-native-windows@0.70.19, but it's still same issue.
I compared the following files between RNW@0.70.19 & [playground app](https://github.com/microsoft/react-native-windows/blob/main/packages/playground/package.json)
node_modules\react-native-windows\Libraries\Components\Switch\Switch.js,
node_modules\react-native-windows\Libraries\Components\Switch\SwitchNativeComponent.js,
node_modules\react-native-windows\Microsoft.ReactNative\Views\SwitchViewManager.h,
node_modules\react-native-windows\Microsoft.ReactNative\Views\SwitchViewManager.cpp.
But there is no differences between them.
That's why I can't understand why RNW@0.70.19 Switch doesn't work as expectedly.

**Comment by marlenecota** [comment]
> @marlenecota , I tried to use react-native-windows@0.70.19, but it's still same issue. I compared the following files between RNW@0.70.19 & [playground app](https://github.com/microsoft/react-native-windows/blob/main/packages/playground/package.json) node_modules\react-native-windows\Libraries\Components\Switch\Switch.js, node_modules\react-native-windows\Libraries\Components\Switch\SwitchNativeComponent.js, node_modules\react-native-windows\Microsoft.ReactNative\Views\SwitchViewManager.h, node_modules\react-native-windows\Microsoft.ReactNative\Views\SwitchViewManager.cpp. But there is no differences between them. That's why I can't understand why RNW@0.70.19 Switch doesn't work as expectedly.

Those files are for the Paper implementation which we're not changing per Chris' comment. 

The Fabric code (which has centering fixed and will eventually be the default implementation) can be found [here](https://github.com/microsoft/react-native-windows/blob/main/vnext/Microsoft.ReactNative/Fabric/Composition/SwitchComponentView.cpp).

**Comment by bahri-dev** [comment]
@marlenecota , My UWP project is based on react-native-windows@0.70.19. How can I use the above Fabric code for Switch component?

**Comment by chrisglein** [comment]
> @marlenecota , My UWP project is based on react-native-windows@0.70.19. How can I use the above Fabric code for Switch component?

Fabric support for RNW is still in [active development](https://github.com/microsoft/react-native-windows/issues/12042). To try it out now you need to be on canary releases to get the latest and greatest, but at a minimum on version 0.72. That said, we're not recommending anyone make the migration quite yet. There's still a bunch of work to do, including getting automation around default app templates and all the support you'd need to get started.

As per my comment above, we are not going to change the placement of the existing Switch control on the mainline (Paper) versions of RNW. You'll have to work around the alignment within your app.

What we have done is confirm that this is fixed in the new version of Switch. However that will be only for Fabric, which is in an opt-in experimental state, and that'll be the case until likely 0.74+.
