### ISSUE TITLE
Remove NuGet.org from NuGet.Config

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#11557]
### Problem Description

To be compliant, this repo must rely on exactly one ADO feed for NuGet packages. However our feed isn't set up yet to upstream NuGet.org, so this is a tracking issue to remove that feed (as inserted in PR #11548).

### Steps To Reproduce

See NuGet.Config

### CLI version

npx react-native -v

### Environment

```markdown
npx react-native info
```

### Target Platform Version

None

### Visual Studio Version

None

### Build Configuration

None

**Comment by chrisglein** [comment]
@jonthysell and @dannyvv are working on what the right solution is here to satisfy compliance requirements.
