### ISSUE TITLE
Integration Test Failures in CI

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-windows#11556]
### Problem Description

Looks like some of the integration test configurations have been failing in CI for a bit. In PR we only run one configuration of the integration tests, but in CI 3 more configurations are run and two of these are failing consistently. In cutting the v072 branch the tests are now failing for this branch as well. We should investigate the culprit.

### Steps To Reproduce

See CI pipeline for main.

### CLI version

npx react-native -v

### Environment

```markdown
npx react-native info
```

### Target Platform Version

None

### Visual Studio Version

None

### Build Configuration

None

**Comment by chrisglein** [comment]
Example failure:
https://dev.azure.com/ms/react-native-windows/_build/results?buildId=455740&view=logs&j=8349fc81-5ad4-5774-5bc5-64ac6c4a4913&t=b6af2c94-5184-50c5-c804-22efdc8fed1d
Configurations shared: Web and Debug
Next step: run it in debug mode locally in the matching configuration (and hope it fails locally)
