### ISSUE TITLE
Please update the compatibility with latest version of react-native. Still requires old versions  showing errors and warnings

### ISSUE THREAD

**Issue by RohitLuthra19** [Microsoft/react-native-windows#1156]
npm WARN react-native-windows@0.33.4 requires a peer of react-native@~0.33.0 but
 none was installed.
npm WARN react-native-windows@0.33.4 requires a peer of react@~15.3.1 but none w
as installed.

**Comment by rozele** [comment]
@RohitLuthra19 can you elaborate here? It looks like you're trying to install react-native-windows to react-native@0.33.*. Is this correct?

**Comment by RohitLuthra19** [comment]
I tried to run the following command 
react-native windows
it gets failed by showing following error message

```
Rohits-MBP:vAdmin rohitluthra$ react-native windows
Scanning 751 folders for symlinks in /Users/rohitluthra/Desktop/vAdmin/node_modules (60ms)
Reading application name from package.json...
Reading react-native version from node_modules...
Checking for react-native-windows version matching 0.42.*...
Installing react-native-windows@0.42.0...
npm WARN react-native@0.42.3 requires a peer of react@~15.4.1 but none was installed.
npm WARN react-native-windows@0.42.0 requires a peer of react@~15.4.1 but none was installed.
npm WARN reactxp@0.42.0-rc.3 requires a peer of react-addons-perf@^15.4.1 but none was installed.
npm WARN reactxp@0.42.0-rc.3 requires a peer of react-native-windows@^0.33.0 but none was installed.
npm ERR! code 1
Command failed: npm install --save react-native-windows@0.42.0
npm WARN react-native@0.42.3 requires a peer of react@~15.4.1 but none was installed.
npm WARN react-native-windows@0.42.0 requires a peer of react@~15.4.1 but none was installed.
npm WARN reactxp@0.42.0-rc.3 requires a peer of react-addons-perf@^15.4.1 but none was installed.
npm WARN reactxp@0.42.0-rc.3 requires a peer of react-native-windows@^0.33.0 but none was installed.
npm ERR! code 1
```

**Comment by tim-soft** [comment]
Do I need to specify a version for react-native-windows?

I'm trying to test the waters with a react-native 0.45.1 project and get similar errors to above^^^

As of this posting react-native 0.45.1 is the latest build

**Comment by rozele** [comment]
I have the following version of `react-native-cli` installed:
```
> react-native --version
react-native-cli: 2.0.1
```
I ran the following steps:
```
# use --npm flag to force NPM instead of yarn
> react-native init myproj --npm --version 0.42.3
> cd myproj
> npm i --save-dev rnpm-plugin-windows
+ rnpm-plugin-windows@0.2.6
> react-native windows
# no NPM warnings produced
```

Are you attempting to add react-native-windows to an existing react-native project or creating one from scratch?

**Comment by RohitLuthra19** [comment]
Attempting to add react-native-windows to an existing react-native.

**Comment by rozele** [comment]
@RohitLuthra19 can you file this issue against http://github.com/Microsoft/reactxp? It looks like they need to update their react-native-windows dependency version.
