### ISSUE TITLE
Upgrade lage to 2.x

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#11580]
### Summary

Upgrade the repo from lage 1.9.6 to >= 2.0. This sounds like it may include some breaking changes.

### Motivation

We use lage 1.9.6 in our repo, but that's 5 months old and the latest version is 2.6. It depends on a lot of older dependencies that risk having security issues (see xml2js in#11575).

### Basic Example

Lage 1.x to 2.x migration guide: https://microsoft.github.io/lage/docs/Cookbook/migration/

**Comment by chrisglein** [comment]
Nothing too concerning from looking at the breaking change list. May be a smooth transition.
