### ISSUE TITLE
accessibilityLabel doesn't perform as expected

### ISSUE THREAD

**Issue by cj3699xiao** [microsoft/react-native-windows#11630]
### Problem Description

`accessibilityLabel` should override what narrator read out. But instead of override, it concatenates the read out content.

For instance, for the code below:
` <Text accessibilityLabel="Test Test Test">ABCDE</Text>`

When we open narrator scan mode, we expected this text component to be read as "Test Test Test". But in reality, it reads out "Test Test Test ABCDE".

### Steps To Reproduce

1. Create example component. 
2. Open narrator scan mode and locate focus to the component.

### Expected Results

we expected this text component to be read as "Test Test Test".

### CLI version

8.0.6

### Environment

```markdown
System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 Intel(R) Core(TM) i9-10900 CPU @ 2.80GHz
    Memory: 4.11 GB / 31.71 GB
  IDEs:
    Android Studio: AI-213.7172.25.2113.9014738
    Visual Studio: 16.11.33529.622 (Visual Studio Enterprise 2019), 17.5.33530.505 (Visual Studio Enterprise 2022)
  Languages:
    Java: javac 19 - C:\Program Files\OpenJDK\jdk-19\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Platform Version

None

### Target Device(s)

Desktop

### Visual Studio Version

None

### Build Configuration

None

**Comment by chrisglein** [comment]
This was regressed during a recent release (71.12, we believe), and fixed since (will be in 72 release, currently in preview). Can you provide your version information per the template so we can confirm?

**Comment by cj3699xiao** [comment]
The current version we have is 0.69.20 if not mistaken.

├─┬ @wsx/app-settings@0.0.1 -> .\packages\app-settings
│ ├─┬ @cspayments/pidl-react-native-windows@0.0.1-alpha.12
│ │ └── react-native-windows@0.69.20 deduped
│ └── react-native-windows@0.69.20 deduped

Thanks

**Comment by chrisglein** [comment]
Here's the change I was referring to: https://github.com/microsoft/react-native-windows/pull/11605
Can you upgrade to a more current version? 0.69 is outside of our active support window as of the end of 2022.
https://microsoft.github.io/react-native-windows/support

Let us know how that affects the behavior you're seeing.
