### ISSUE TITLE
RNW App throwing Unauthorized Access Exception

### ISSUE THREAD

**Issue by Qurishe** [microsoft/react-native-windows#11647]
### Problem Description

RNW app throws unauthorized access exception when trying to access folders in desktop or documents or anywhere else.
i have done the follwing things but nothing works:
1. broadFileSystemAccess: added this in project's Package.appxmanifiest and declared   "xmlns:rescap="http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities"
at the top and turned the permission on in windows settings file system:
![broadFileSystemAccess](https://github.com/microsoft/react-native-windows/assets/32069358/db7301c7-4c51-4ad8-866e-8d3bf709a745)

2. Used FolderPicker: used Windows.Storage api to select a folder and add it to the FutureAccessList with a token and later on retrieve that directory using the same token as in following picture:
**setting the file access list**
![FileAccessList](https://github.com/microsoft/react-native-windows/assets/32069358/d123d7df-1ac0-4d46-9692-ad0e4a5a74af)

**getting file access list path**
![GetFutureAccessList](https://github.com/microsoft/react-native-windows/assets/32069358/4839e175-cadc-401b-bcad-333aa7725f72)

but with all these i still get the follwing error:
![Access to the path denied](https://github.com/microsoft/react-native-windows/assets/32069358/a0dd474e-2ab8-468d-9196-b36e0980b2cb)

### Steps To Reproduce

1. Pick a folder using the FolderPicker api and add it to the FutureAccessList.
2. Use path from FutureAccessList to create, read or update files in the same directory

### Expected Results

save generated pdf file in the selected directory.

### CLI version

0.71.0

### Environment

```markdown
...
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

Debug

**Comment by Qurishe** [comment]
@chrisglein any idea about this issue?

**Comment by chrisglein** [comment]
If I'm reading this right, your problem isn't really with RNW, but with getting the underlying UWP app to use [broadFileSystemAccess](https://learn.microsoft.com/en-us/windows/uwp/files/file-access-permissions#capabilities-for-accessing-other-locations). As in I would guess that you'd hit the same access denied error if there were no RNW usage in the app. You may be able to get help by poking around a bit on stackoverflow looking for caveats about that permission. When you attach a debugger does it fail on the line that gets the folder or the part after you add the PDF to the path and do whatever's in that `try` block?

**Comment by Qurishe** [comment]
Yes, the error is from the UWP side not the RNW itself.
When i attach the debugger it stops at the line where pdf is going to be generated and when i use try catch it throws error of access denied to the path.
However i tried to select LocalState folder and it just works fine and generates the pdf without any problem. But i cannot depend on localstate folder because i want to generate documents to the directory which user has selected.

--info wasn't working and yes i am using react-native-windows 71.13

**Comment by Qurishe** [comment]
I just figured out how Windows.Storage APIs work and solved saving files anywhere i want.
i am closing this for now and if anyone faces similar issue can comment on this issue and i will provide the information and steps.

**Comment by AhmedMustafa505** [comment]
Hello @Qurishe Can you tell how could you use Windows.Storage APIs to allow access to Filesystem automatically without having to access it manually from app settings ?

**Comment by Qurishe** [comment]
Hi @AhmedMustafa505 you have to add the directory to the FutureAccessList that way you only have to select a directory and then you can carry on operations on that directory
