### ISSUE TITLE
Databases

### ISSUE THREAD

**Issue by sm2017** [Microsoft/react-native-windows#1172]
1. How can I have a database??
2. Is realm supported??
3. Is sqlite suppoted??

**Comment by zerglingno1** [comment]
This plugin provides a WebSQL-compatible API to store data in a react native app, by using a SQLite database on the native side. Can you check it we write a simple bridge here :
https://github.com/craftzdog/react-native-sqlite-2

**Comment by sm2017** [comment]
Is there any other alternative way?

**Comment by amorenew** [comment]
Yes, there should be different alternatives

**Comment by amorenew** [comment]
@sayar 
I tested another database and it worked
https://github.com/antoniopresto/react-native-local-mongodb/issues/1

**Comment by amorenew** [comment]
So now we have two database
**CouchDB** 'PouchDB' https://github.com/craftzdog/react-native-sqlite-2
 and 
**MongoDB**
https://github.com/antoniopresto/react-native-local-mongodb

**Comment by lekerning** [comment]
@amorenew 
Hi,  I want to know is realm supported yet?

**Comment by amorenew** [comment]
@lekerning 
in https://github.com/realm/realm-dotnet/issues/509#issuecomment-268197932
>>"I'm hopeful we can get a release out before Feb"
>>"We released Windows Desktop (i.e. WPF/Console app) support. We're actively working on UWP and hope to have an alpha release in several weeks."

milestone:https://github.com/realm/realm-dotnet/milestone/4
https://github.com/realm/realm-core/issues/2059

**Comment by lekerning** [comment]
@amorenew 
Good news, thanks a lot!

**Comment by amorenew** [comment]
Welcome

**Comment by amorenew** [comment]
@lbochenek Maybe it's in alpha or beta not final release but anyway it will take time to support React Native

**Comment by amorenew** [comment]
here they asking for beta testers
https://github.com/realm/realm-dotnet/issues/509#issuecomment-268197932

**Comment by rozele** [comment]
@amorenew @lekerning unfortunately, realm for native platforms (iOS, Android, and UWP) is totally separate from realm for react-native. realm for react-native is more like realm for JavaScriptCore, with a bit of native functionality to ensure that the realm hooks are installed. What we need to get realm working on react-native-windows is realm for Chakra(Core).

**Comment by billbarsch** [comment]
Hello, what good offline DB options we have now in 2020 to use with react-native-windows and android too?
NeDB have this on github:
`Deprecated. When I started this project, there were no off-line storage options for react-native besides AsyncStorage. Today there are many better options, which receive PRs and have entire teams working on. For these reasons, this project is archived.`
