### ISSUE TITLE
ESlint config should include `microsoft/eslint-plugin-sdl` for compliance

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#11743]
### Summary

To be compliant we should add the `@icrosoft/eslint-plugin-sdl` plugin to our eslint config.

See: https://github.com/microsoft/eslint-plugin-sdl

### Motivation

The Microsoft ESlint compliance tasks expect certain rules to be followed so we should include the plugin so we can fix the issues and pass those tasks.

**Comment by jonthysell** [comment]
We may also need to extend the proper `@microsoft/sdl/required` config.

**Comment by chrisglein** [comment]
Will this have a problem with the Flow code?
We should run this and see what happens though.
