### ISSUE TITLE
Getting white screen some of the time also in few system not on all systems

### ISSUE THREAD

**Issue by rohitgaidhane** [microsoft/react-native-windows#11740]
### Problem Description

`{
  "dependencies": {
    "@react-native-community/masked-view": "^0.1.5",
    "@react-native-community/netinfo": "^5.9.7",
    "axios": "^0.19.0",
    "axios-token-interceptor": "^0.2.0",
    "i18n-js": "3.5.1",
    "lodash": "^4.17.15",
    "moment": "^2.24.0",
    "moment-timezone": "^0.5.31",
    "prop-types": "^15.7.2",
    "react": "16.8.3",
    "react-native": "0.59.10",
    "react-native-base64": "0.0.2",
    "react-native-checkbox": "^2.0.0",
    "react-native-config": "0.12.0",
    "react-native-debugger": "^1.1.0",
    "react-native-device-info": "^5.6.3",
    "react-native-elements": "^1.2.7",
    "react-native-extended-stylesheet": "^0.12.0",
    "react-native-file-viewer": "^2.0.2",
    "react-native-fs": "^2.16.6",
    "react-native-htmlview": "^0.15.0",
    "react-native-pdf-view": "^0.3.2",
    "react-native-popup-menu": "^0.15.7",
    "react-native-sensitive-info": "^5.5.5",
    "react-native-testing-library": "^1.12.0",
    "react-native-vector-icons": "^6.6.0",
    "react-native-windows": "0.59.0-legacy.2",
    "react-navigation": "^2.18.3",
    "react-redux": "^6.0.1",
    "redux": "^4.0.1",
    "redux-logger": "^3.0.6",
    "redux-persist": "^5.10.0",
    "redux-saga": "^1.0.2",
    "reduxsauce": "^1.0.1"
  },
  "devDependencies": {
    "@babel/core": "^7.7.7",
    "@babel/runtime": "^7.7.7",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "babel-preset-react-native": "^4.0.1",
    "enzyme": "^3.11.0",
    "enzyme-adapter-react-16": "^1.15.2",
    "enzyme-to-json": "^3.4.4",
    "eslint": "^6.5.1",
    "eslint-config-prettier": "^4.1.0",
    "eslint-config-standard": "^12.0.0",
    "eslint-plugin-import": "^2.16.0",
    "eslint-plugin-node": "^8.0.1",
    "eslint-plugin-prettier": "^3.0.1",
    "eslint-plugin-promise": "^4.0.1",
    "eslint-plugin-react": "^7.12.4",
    "eslint-plugin-react-native": "^3.6.0",
    "eslint-plugin-standard": "^4.0.0",
    "jest": "^24.9.0",
    "jest-react-native": "^18.0.0",
    "metro-react-native-babel-preset": "^0.57.0",
    "prettier": "^1.16.4",
    "react-dom": "^16.12.0",
    "react-native-rename": "^2.4.1",
    "react-test-renderer": "^16.13.0",
    "rnpm-plugin-windows": "^0.6.1"
  },
  "jest": {
    "preset": "react-native",
    "transform": {
      "^.+\\.js$": "<rootDir>/node_modules/react-native/jest/preprocessor.js"
    },
    "setupFiles": [
      "./jest/setup.js"
    ],
    "collectCoverage": true,
    "moduleDirectories": [
      "node_modules",
      "src"
    ],
    "testEnvironment": "node",
    "testEnvironmentOptions": {
      "enzymeAdapter": "react16"
    },
    "cacheDirectory": "./cache",
    "coveragePathIgnorePatterns": [
      "/node_modules/",
      "/jest"
    ],
    "coverageThreshold": {
      "global": {
        "statements": 80
      }
    },
    "transformIgnorePatterns": [
      "node_modules/(?!(jest-)?react-native)"
    ],
    "snapshotSerializers": [
      "enzyme-to-json/serializer"
    ]
  }
}
`

package.json

this is old react native version 
I also implemented error boundaries if any code error but I didn't got any code issue.
as Getting white screen some of the time also in few system not on all systems

### Steps To Reproduce

Lunch app on debug mode / lunch exe file on some system it will cause issue sometimes not always

### Expected Results

what could be issue and please suggest fix for that

### CLI version

    "react-native-windows": "0.59.0-legacy.2",

### Environment

```markdown
npx react-native info
```

### Target Platform Version

None

### Visual Studio Version

None

### Build Configuration

None

**Comment by rohitgaidhane** [comment]
some time it build worked fine and after some break when i reopen app it show white screen

**Comment by chrisglein** [comment]
0.59 is well outside of our [support window](https://microsoft.github.io/react-native-windows/support). We'll need you to upgrade in order to help investigate this.
