### ISSUE TITLE
Fabric Text renders emojis in monochrome

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#11764]
### Problem Description

Emojis render in Fabric's Text, but without any color:

![image](https://github.com/microsoft/react-native-windows/assets/26607885/0c6853f8-c9b7-499e-92d6-3f22693f8a63)

### Steps To Reproduce

```js
<Text>👍</Text>
```

Or for an interactive app that hits this all the time:
https://github.com/chrisglein/artificial-chat/issues/119

### Expected Results

![image](https://github.com/microsoft/react-native-windows/assets/26607885/0df7e505-07d2-4762-831e-44238c986ccd)

### CLI version

12.0.0-alpha.3

### Environment

```markdown
info Fetching system and libraries information...
System:
  OS: Windows 10 10.0.25880
  CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
  Memory: 43.87 GB / 63.85 GB
Binaries:
  Node:
    version: 18.15.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.19
    path: C:\Program Files (x86)\Yarn\bin\yarn.CMD
  npm:
    version: 9.5.0
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Enabled
    AllowAllTrustedApps: Enabled
    Versions:
      - 10.0.19041.0
      - 10.0.22000.0
      - 10.0.22621.0
IDEs:
  Android Studio: Not Found
  Visual Studio:
    - 17.5.33530.505 (Visual Studio Community 2022)
Languages:
  Java: Not Found
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.0-nightly-20230601-d9b3339ef
    wanted: 0.73.0-nightly-20230601-d9b3339ef
  react-native-windows:
    installed: 0.0.0-canary.665
    wanted: 0.0.0-canary.665
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Target Platform Version

10.0.19041

### Visual Studio Version

Visual Studio 2022

### Build Configuration

None

### Snack, code example, screenshot, or link to a repository

https://github.com/chrisglein/artificial-chat/issues/119

**Comment by chrisglein** [comment]
Probably a one line fix setting some rich edit option... just don't know what that is.

**Comment by acoates-ms** [comment]
For windowless controls, color fonts aren’t enabled by default. To enable them, send the message [EM_SETTYPOGRAPHYOPTIONS](https://docs.microsoft.com/en-us/windows/win32/controls/em-settypographyoptions) with wparam = lparam = TO_DEFAULTCOLOREMOJI | TO_DISPLAYFONTCOLOR, where TO_DEFAULTCOLOREMOJI = 0x1000 and TO_DISPLAYFONTCOLOR = 0x2000. In a windowless control, you can do this by calling

ITextServices::TxSendMessage(EM_SETTYPOGRAPHYOPTIONS,
   TO_DEFAULTCOLOREMOJI | TO_DISPLAYFONTCOLOR,
   TO_DEFAULTCOLOREMOJI | TO_DISPLAYFONTCOLOR, nullptr);

Source: https://devblogs.microsoft.com/math-in-office/richeditd2d-window-controls/
