### ISSUE TITLE
How can I call functions like WinExec，ShellExecute ，CreateProcess in react-native-windows context

### ISSUE THREAD

**Issue by Hakunata** [microsoft/react-native-windows#11793]
### Summary

I need do some work in background and need call other process.So how to implements this in react-native-windows app?

### Motivation

I need do some work in background and need call other process.So how to implements this in react-native-windows app?

**Comment by jonthysell** [comment]
There's no easy or built-in way to do this. You can check out the [AppServiceDemo sample](https://github.com/microsoft/react-native-windows-samples/tree/main/samples/AppServiceDemo) for an example of an RNW app that contains a secondary app for calling old Win32 APIs. However the specific APIs you're calling may still not work due to the limitations of UWP (particularly to invoke other processes not included in your app package).

**Comment by Hakunata** [comment]
> There's no easy or built-in way to do this. You can check out the [AppServiceDemo sample](https://github.com/microsoft/react-native-windows-samples/tree/main/samples/AppServiceDemo) for an example of an RNW app that contains a secondary app for calling old Win32 APIs. However the specific APIs you're calling may still not work due to the limitations of UWP (particularly to invoke other processes not included in your app package).

Could c++/winrt execute windows command line ?

**Comment by Hakunata** [comment]
Was there any entry in c++/winrt that can launch sub process?  I need call win32-exe from react-native-windows or native code

**Comment by chrisglein** [comment]
We have some coverage of this general topic on our website [here](https://microsoft.github.io/react-native-windows/docs/native-code). Hopefully that article is useful?

The short answer is that an RNW app is by default a UWP app, and a UWP can't out of the box do what you're asking about. A Win32 app can, but that's a different app model and requires different setup.

**Comment by AlmTalal** [comment]
> We have some coverage of this general topic on our website [here](https://microsoft.github.io/react-native-windows/docs/native-code). Hopefully that article is useful?
> 
> The short answer is that an RNW app is by default a UWP app, and a UWP can't out of the box do what you're asking about. A Win32 app can, but that's a different app model and requires different setup.

@chrisglein What is the different settup that it may require, is there any documentation about that ? @Hakunata you were able to solve the problem ? Please give me a hint
