### ISSUE TITLE
What's the easist way to call windows-device-scanner and get result image with react-native-windows

### ISSUE THREAD

**Issue by Hakunata** [microsoft/react-native-windows#11803]
### Summary

What's the easist way to call windows-device-scanner and get result image with react-native-windows

### Motivation

What's the easist way to call windows-device-scanner and get result image with react-native-windows

**Comment by chrisglein** [comment]
Can you give a bit more detail? What do you mean by "windows-device-scanner"? Do you mean the UWP scanner APIs?
https://learn.microsoft.com/en-us/windows/uwp/devices-sensors/scan-from-your-app
I don't know if there's a RN module that does scanners that supports windows ([you could check](https://reactnative.directory/?windows=true)). Assuming there isn't, you would wrap your call to the UWP APIs using [native modules](https://microsoft.github.io/react-native-windows/docs/native-modules).
