### ISSUE TITLE
Add different heading level announcements for Narrator for different types of Headings

### ISSUE THREAD

**Issue by YajurG** [microsoft/react-native-windows#11847]
### Summary

Currently, there is only support for one type of 'header' announcement within narrator, as the `accessibilityLabel` prop only takes one type of 'header' property. Because of this, we are announing 'heading, level 2' for any Text component that has `accessibilityLabel = 'header'`. Ideally, we will have a different heading announcement in Narrator for different types of headings e.g the title of a page would have a different announcement than the sub-headings of sections on the same page.

### Motivation

There is currently an issue on Gallery where different header announcements are needed for different types of headings. In the below example, 'Button' would be a different heading announcement from 'A simple button' or 'A colored button'. 
![image](https://github.com/microsoft/react-native-windows/assets/30995198/0ab39a6f-69cb-44eb-a624-dc3b73937795)
Currently all headings have the same announcement - 'heading, level 2'.

**Comment by AgneLukoseviciute** [comment]
One option would be to add a windows-specific `accessibilityLevel: number` prop that would allow for customizing the value. This would be aligned with: https://github.com/react-native-community/discussions-and-proposals/blob/fd64774e8161973b87b8f0a27587fa039eb7b43b/proposals/0000-accessibility-apis.md

**Comment by Yajur-Grover** [comment]
This is no longer an accessibility issue, so marking as closed.
