### ISSUE TITLE
Multiple windows

### ISSUE THREAD

**Issue by k1mmm** [microsoft/react-native-windows#11887]
### Summary

Hello, I'm trying to create an application in react-native-windows that needs to have multiple windows opened. In react-native-macos I've achieved this by sharing a react native bridge between my windows. How ever accessing the react native bridge in windows seems to be allot harder.

I've seen an answer where you could use ApplicationView API to create a new window, but it was not fully clear in the answer if it always was going to need a new react native instance or not.

If there is no way to share a react native instance between two windows, what would be the recommended way to communicate between them?

### Motivation

Desktop applications have different needs than mobile, and handling windows is one of them

**Comment by chrisglein** [comment]
> If there is no way to share a react native instance between two windows,

Yes. You can share the same react host and thus the same instance. I don't think we have any samples that demonstrate this. Look in MainPage.cpp where we assign the host from the application. You'd need to assign the shared host instead. But knowing it's possible do you have what you need? Let us know.

**Comment by vmoroz** [comment]
In C++: https://github.com/microsoft/react-native-windows/blob/main/packages/sample-apps/windows/SampleAppCPP/MainPage.cpp
```C++
MainPage::MainPage() {
  InitializeComponent();
  ReactRootView().ReactNativeHost(Application::Current().as<App>()->Host());
}
```

In C#: https://github.com/microsoft/react-native-windows/blob/main/packages/sample-apps/windows/SampleAppCS/MainPage.xaml.cs
```C#
public MainPage()
{
  InitializeComponent();
  ReactRootView.ReactNativeHost = ((App)Application.Current).Host;
}
```

**Comment by k1mmm** [comment]
Awesome! thank you both very much!

**Comment by k1mmm** [comment]
It worked perfectly, thank you!
