### ISSUE TITLE
Implement 'role' with native implentation

### ISSUE THREAD

**Issue by TatianaKapos** [microsoft/react-native-windows#11886]
### Problem Description

Latest integration brought in [Native ARIA Roles: Remove JS Shim](https://github.com/facebook/react-native/commit/19699ab3b529af747223b7e470ad1e84be264b86) which removes the JS shimming of `role` to `accessibilityRole`. Not sure if we already have a native implementation of role or not but their PR states "_This will require any out of tree platforms to add their own native implementation for `role` to continue to work."._ This needs further investigation!

### Steps To Reproduce

1. Launch playground and test 'role' 

### CLI version

12.0.0-alpha.3

### Environment

```markdown
System:
  OS: Windows 10 10.0.22621
  CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
  Memory: 52.40 GB / 63.85 GB
Binaries:
  Node:
    version: 18.5.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.5
    path: C:\Program Files (x86)\Yarn\bin\yarn.CMD
  npm:
    version: 8.18.0
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Enabled
    AllowAllTrustedApps: Enabled
    Versions:
      - 10.0.17763.0
      - 10.0.18362.0
      - 10.0.19041.0
      - 10.0.22000.0
IDEs:
  Android Studio: AI-213.7172.25.2113.9014738
  Visual Studio:
    - 16.11.33801.447 (Visual Studio Enterprise 2019)
    - 17.6.33801.468 (Visual Studio Enterprise 2022)
Languages:
  Java:
    version: 11.0.16.1
    path: C:\Program Files\Eclipse Adoptium\jdk-11.0.16.101-hotspot\bin\javac.EXE
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

Debug

**Comment by chrisglein** [comment]
Generally these xplat React changes are only targeting Fabric, but this is one that also affects Paper. So we'll need to figure out for both here.
