### ISSUE TITLE
Initialising a new project starts with three yellow box errors

### ISSUE THREAD

**Issue by jmcginty** [Microsoft/react-native-windows#1189]
Steps to replicate: 

Do a standard init project, and run: 

react-native init AwesomeProject
cd .\AwesomeProject\
yarn add rnpm-plugin-windows
react-native windows
react-native run-windows

![yellow box](https://user-images.githubusercontent.com/1586538/28003862-fcd184d0-6583-11e7-9489-1e6ce94f3dd1.png)

The use of React.PropTypes is deprecated, as is using react.createClass() which seems to be the root of these problems. 

Using React Native 46.1, 
React Native Windows 0.46.0-rc.0

```
{
	"name": "AwesomeProject",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"start": "node node_modules/react-native/local-cli/cli.js start",
		"test": "jest"
	},
	"dependencies": {
		"react": "16.0.0-alpha.12",
		"react-native": "0.46.1",
		"react-native-windows": "0.46.0-rc.0",
		"rnpm-plugin-windows": "^0.2.6"
	},
	"devDependencies": {
		"babel-jest": "20.0.3",
		"babel-preset-react-native": "2.1.0",
		"jest": "20.0.4",
		"react-test-renderer": "16.0.0-alpha.12"
	},
	"jest": {
		"preset": "react-native"
	}
}

```

**Comment by rozele** [comment]
Thanks @jmcginty we need to update our init project templates

**Comment by jmcginty** [comment]
Isn't the problem in the component definitions? 
It seems some components e.g. 

> Picker.windows.js

 has been updated to include `PropTypes` from `'prop-types'` and create classes by Extending the React.Component. 

> Text.windows.js

 still uses the deprecated `React.PropTypes` & `const Text = React.createClass({`

**Comment by rozele** [comment]
@jmcginty are you going to submit PRs for the other warnings as well?

**Comment by jmcginty** [comment]
@rozele Hi, I have submitted a PR for the View.propTypes warning. The React.createClass one is trickier. I will create a pull request, but it will be incomplete. I'll need some help with that.

**Comment by rozele** [comment]
@jmcginty it looks like the react-native project applied a mixture of `create-react-class` (https://github.com/facebook/react-native/commit/9afb71fde8199156ed683dca6aa59826f9fb9279) and transforming the React.createClass calls into an ES6 type (https://github.com/facebook/react-native/commit/a2fb703bbb988038323c55b29b40e8f5ff52966d).  We should try to keep consistent with those files.

**Comment by jmcginty** [comment]
Yes - simple classes can be converted to es6, which is the preferred method, and others can use the  `create-react-class` method.
I have been using https://github.com/reactjs/react-codemod to help me do the conversions. 
It has done a bunch of classes, but there are about 18 files it could auto convert due to "inconvertible mixins.". I am going to tidy up the ones that the tool and I can convert and pull request that. After that, I'll list the ones I couldn't do and we can discuss tactics.

**Comment by rozele** [comment]
Closing as this is quite out of date.
