### ISSUE TITLE
If http is unresponsive, the app crashes

### ISSUE THREAD

**Issue by 1280103995** [microsoft/react-native-windows#11910]
### Problem Description

Use fetch or axios to initiate an http request. If the server does not respond, the App will crash.

<img src="https://github.com/microsoft/react-native-windows/assets/17424486/9dcbf0f9-7155-49a4-b028-f8d6ac0cd083" width="50%" height="50%"/>
<img src="https://github.com/microsoft/react-native-windows/assets/17424486/d08870f0-7062-4cf4-9e6d-f6fd72148396" width="50%" height="50%"/>

### Steps To Reproduce

1. create a new App according to the official documentation
2. Use ```fetch``` or ```axios``` in ```App.tsx``` to initiate an http request to an unknown server, for example ```http://localhost:8080```. Our goal is just to make the request unresponsive.
3. Enter the project root directory and execute ```yarn start```
4. Open the project with VS2022 and run it in debug mode

### Expected Results

Even if the http server is unresponsive, the App cannot crash

### CLI version

11.3.2

### Environment

```markdown
info Fetching system and libraries information...
System:
  OS: Windows 10 10.0.22621
  CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1260P
  Memory: 5.27 GB / 15.68 GB
Binaries:
  Node:
    version: 18.16.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.19
    path: ~\AppData\Roaming\npm\yarn.CMD
  npm:
    version: 9.5.1
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Enabled
    AllowAllTrustedApps: Enabled
    Versions:
      - 10.0.18362.0
      - 10.0.19041.0
      - 10.0.22000.0
      - 10.0.22621.0
IDEs:
  Android Studio: Not Found
  Visual Studio:
    - 17.6.33815.320 (Visual Studio Community 2022)
Languages:
  Java: Not Found
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.0
    wanted: 0.72.0
  react-native-windows:
    installed: 0.72.1
    wanted: 0.72.1
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Target Platform Version

None

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

Debug

### Snack, code example, screenshot, or link to a repository

```
"dependencies": {
    "react": "18.2.0",
    "react-native": "0.72.0",
    "react-native-windows": "0.72.1"
  }
```
```
import React, {useEffect} from 'react';
import {View, Text} from 'react-native';

function App() {
  useEffect(() => {
    fetch('http://localhost:8080')
      .then(date => date.json())
      .then(res => {
        console.log('<< Response >>', res);
      });
  }, []);

  return (
    <View
      style={{
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'black',
      }}>
      <Text style={{color: 'white', fontSize: 28}}>Hello</Text>
    </View>
  );
}

export default App;
```

**Comment by chrisglein** [comment]
Certainly the expectation from [the docs](https://reactnative.dev/docs/network#handling-the-response) seems clear:
> Don't forget to catch any errors that may be thrown by fetch, otherwise they will be dropped silently.

To me that implies that you should add a `.catch()`, but that if you don't the error is expected to be silent. And that seems to be the behavior on web/iOS/etc.. So Windows would be behaving as an outlier here.

**Comment by chrisglein** [comment]
@JunielKatarn Does this match your expectation?

**Comment by YajurG** [comment]
Recommending as closed as there doesn't seem to be additionaly follow up
