### ISSUE TITLE
App is closing instantly when click on the top right cross icon without completing the process.

### ISSUE THREAD

**Issue by rahulmishra1991** [microsoft/react-native-windows#11927]
### Problem Description

I am using react native windows app where I am calling another exe. With the exe we are communicating through the websocket. When the windows app will be close same time I need to pass SHUTDOWN event to the exe through Websocket.
But when I am closing the app instantly app is closed instead of complete the process app is closed.

Here is some code which i am using currently:

```
import { AppState, BackHandler } from "react-native";

async componentDidMount() {
AppState.addEventListener('change', this.handleAppStateChange);
    BackHandler.addEventListener('hardwareBackPress', this.handleBackPress);
}

handleAppStateChange = (nextAppState) => {
    console.log('App state changed:', this.state.appState, '→', nextAppState);
    this.closeWebsocket('Close')
    if (
      this.state.appState.match(/active|foreground/) &&
      nextAppState === 'inactive'
    ) {
      console.log('App is going to close.');
      // Perform your actions or cleanup logic here before the app is closed
    }
    this.setState({ appState: nextAppState });
  };
  handleBackPress = async () => {
    // Perform actions before the app is closed
    this.closeWebsocket('Back')
  };

closeWebsocket(type) {
    let websocketFn = new WebSocket(AppConstants.WEBSOCKET_DETAILS.url);
    
    // websocket onopen event listener
    websocketFn.onopen = async () => {
      websocketFn.send(JSON.stringify({
          "event": AppConstants.WebsocketEvents.STATUS,
          "timestamp": "",
          "publisher": "MY_APP",
      }));
    };
    websocketFn.addEventListener('message', (event) => {
      const dataFromServer = JSON.parse(event.data);
      if(dataFromServer.event === AppConstants.WebsocketEvents.STARTED){
        websocketFn.send(JSON.stringify({
          "event": AppConstants.WebsocketEvents.SHUTDOWN,
          "timestamp": "",
          "publisher": "MY_APP",
          "reason": ""  
        }));
        if(type === "Back") {
          BackHandler.exitApp()
          return true;
        }
      }
    });
  }
```

In the above code what i need to do is when app is closing or crashing I just need to call the closewebsocket() and once connected with the websocket just send the SHUTDOWN message to server. But app is closing before that.

### Steps To Reproduce

When closing the app, App instantly closed without process completetion.

### Expected Results

Closesocket function should be completed before closing the app.

### CLI version

npx react-native -v 6.14.11

### Environment

```markdown
Here are the environment info:

react-native -v: 6.14.11
npm ls rnpm-plugin-windows: rnpm-plugin-windows@0.6.1
npm ls react-native-windows: react-native-windows@0.59.0-legacy.2
node -v: v14.16.0
npm -v: 6.14.11
yarn -version: 1.22.19
```

### Target Platform Version

None

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2017

### Build Configuration

Debug

**Comment by rahulmishra1991** [comment]
This is not related to any specific version i have tried the same in latest version.

**Comment by rahulmishra1991** [comment]
Is there any update on this?

**Comment by chrisglein** [comment]
> This is not related to any specific version i have tried the same in latest version.

Can you confirm by running the environment commands above? Version 0.59 is very very old, and was on an old implementation of RNW. Updating the number in your package.json isn't going to be enough - you'd need to refresh your app template from the CLI in order to get all the fixes from the past years.
