### ISSUE TITLE
No MapView parity from AirBnB's react-native-maps for UWP

### ISSUE THREAD

**Issue by Noitidart** [Microsoft/react-native-windows#1193]
A AirBnB maps dev closed a topic and say AirBnB package will never be providing support for UWP - https://github.com/airbnb/react-native-maps/issues/1456#issuecomment-314575465

This disagrees with the docs on react-native windows as it says that their `MapView` was deprecated in favor of AirBnB's package - https://github.com/Microsoft/react-native-windows/blob/master/docs/CoreParityStatus.md

![](http://i.imgur.com/yGg1wIZ.png)

**Comment by rozele** [comment]
Closing since airbnb/react-native-maps#1456 has been re-opened.
