### ISSUE TITLE
React native tab view(v3.5.2) doesn't work with react native windows version(v0.70.19)

### ISSUE THREAD

**Issue by pankshar611** [microsoft/react-native-windows#11936]
### Problem Description

On React native windows (UWP) app, React native tab view doesn't work with react native windows version(v0.70.19). However, it works with older version (v0.67.14).

Problem:
It doesn't support multiple routes. If we pass more than one route, It gives below error.
For single route, it works fine.

![image](https://github.com/microsoft/react-native-windows/assets/107645371/8e67f49e-5fb6-4afb-8a1a-f60be3f0e10d)

### Steps To Reproduce

Create React native windows UWP app
Use react native tab view
Pass more than one route to Tabview component
It fails.

### Expected Results

React native tab view should work with more than one route.

### CLI version

npx react-native -v

### Environment

```markdown
npx react-native info
```

### Target Platform Version

None

### Visual Studio Version

Visual Studio 2019

### Build Configuration

Debug

**Comment by pankshar611** [comment]
@pradeepgsd

**Comment by pankshar611** [comment]
@satya164

**Comment by chrisglein** [comment]
Just to be clear do you mean the [tab view](https://reactnavigation.org/docs/tab-view/) from the [react navigation](https://github.com/react-navigation/react-navigation) module? If this is a bug in a module's Windows implementation, the issue should be opened on that repo.

**Comment by pradeepgsd** [comment]
> Just to be clear do you mean the [tab view](https://reactnavigation.org/docs/tab-view/) from the [react navigation](https://github.com/react-navigation/react-navigation) module? If this is a bug in a module's Windows implementation, the issue should be opened on that repo.

@chrisglein Its already raised on react-navigation https://github.com/react-navigation/react-navigation/issues/11497

**Comment by pankshar611** [comment]
@chrisglein - Here is the reproducible example.

Please find below sample repository for react native windows (UWP) app and the package versioning I used.

"react": "18.1.0",
"react-native": "0.70.0",
"react-native-tab-view": "^3.5.2",
"react-native-windows": "0.70.20"

Repository where issue is reproducible - https://github.com/pankshar611/sample-uwp-app 
Please follow these steps to run app - https://microsoft.github.io/react-native-windows/docs/getting-started

**Comment by chrisglein** [comment]
Thanks for making sure there's an issue on the module's repo and for letting us know about this! Since the issue and fix would be in that module, I'm closing out this issue to singularly track over there.
