### ISSUE TITLE
Flyout doesn't use borderRadius style property

### ISSUE THREAD

**Issue by MaxBen93** [microsoft/react-native-windows#11943]
### Problem Description

When using `Flyout`, I am unable to set the borderRadius of the `Flyout` itself which is resulting in a misalignment between the shadow (projected by a XAML `<Border />` that is part of XAML's `FlyoutPresenter` default template) and content within the `Flyout` which may have `borderRadius` set on it.

This problem is most apparent when **not** specifying a `backgroundColor` for any of the content within the `Flyout`. Take note, in the following screenshot, of the lack of rounding around the corners of the shadow for the `Flyout`:

<img width="781" alt="screenshot of a basic Flyout showing the missing corner radius" src="https://github.com/microsoft/react-native-windows/assets/89095633/8b052f18-82b1-4ca7-9e91-83f9cf3a7cb1">

The TSX for the above is simply:
```tsx
<Flyout isOpen={showFlyout} isLightDismissEnabled={false} isOverlayEnabled={true} autoFocus={true} verticalOffset={100} horizontalOffset={400}>
  <View style={{ minHeight: 100, minWidth: 300 }}>
    <Text>Look at me</Text>
    <Button
      title="Click to close Flyout"
      onPress={() => {
        setShowFlyout(false);
      }}
    />
  </View>
</Flyout>
```

Adding `style={{ borderRadius: 20 }}` (or any value) to the `<Flyout />` has no effect.

### Steps To Reproduce

1. Add the following to a sample app:
```tsx
const [showFlyout, setShowFlyout] = useState(false);
...
return (
  ...
  <Button
    title="Click to open Flyout"
    onPress={() => {
      setShowFlyout(true);
    }}
  />
  <Flyout isOpen={showFlyout} isLightDismissEnabled={false} isOverlayEnabled={true} autoFocus={true} verticalOffset={100} horizontalOffset={400} style={{ borderRadius: 20 }}>
    <View style={{ minHeight: 100, minWidth: 300 }}>
      <Text>Look at me</Text>
      <Button
        title="Click to close Flyout"
        onPress={() => {
          setShowFlyout(false);
        }}
      />
    </View>
  </Flyout>
);
```
2. Launch the app and click the button

### Expected Results

The `Flyout` should present with a rounded "shadow" corresponding to the `borderRadius` value that was in the `style` of the `<Flyout />`

### CLI version

8.0.6

### Environment

```markdown
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.23509
    CPU: (24) x64 AMD Ryzen Threadripper PRO 3945WX 12-Cores
    Memory: 32.32 GB / 63.86 GB
  Binaries:
    Node: 16.19.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.17763.0, 10.0.18362.0, 10.0.19041.0, 10.0.22000.0, 10.0.22621.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 17.6.33815.320 (Visual Studio Enterprise 2022), 16.11.33801.447 (Visual Studio Enterprise 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
info React Native v0.72.3 is now available (your project is running on v0.69.6).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.72.3.
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.69.6.
info To upgrade, run "react-native upgrade".
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

Debug

**Comment by chrisglein** [comment]
The styling props aren't applied to the `Flyout` itself but to the contents of the Flyout (the `View` below it). There's an example of a rounded radius in the Gallery sample:
https://github.com/microsoft/react-native-gallery/blob/main/src/examples/FlyoutExamplePage.tsx#L178
(the snippets in the app aren't showing the full style props, but they are in the source)

There's a slight rounding to that:
![image](https://github.com/microsoft/react-native-windows/assets/26607885/454388d7-1f5d-4383-9fe2-1c71e8933c0f)

Can you try applying your styling to the node below the `Flyout` and see if that gets the effect you want?

**Comment by daaanigm** [comment]
> The styling props aren't applied to the `Flyout` itself but to the contents of the Flyout (the `View` below it). There's an example of a rounded radius in the Gallery sample: https://github.com/microsoft/react-native-gallery/blob/main/src/examples/FlyoutExamplePage.tsx#L178 (the snippets in the app aren't showing the full style props, but they are in the source)
> 
> There's a slight rounding to that: ![image](https://private-user-images.githubusercontent.com/26607885/256630270-454388d7-1f5d-4383-9fe2-1c71e8933c0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0NTk1MDcsIm5iZiI6MTcwMTQ1OTIwNywicGF0aCI6Ii8yNjYwNzg4NS8yNTY2MzAyNzAtNDU0Mzg4ZDctMWY1ZC00MzgzLTlmZTItMWM3MWU4OTMzYzBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDE5MzMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyNTllZWQ1ZmZhMmVmOTU0NWZiYThlNGZkMmZlMTdhMThlOWU3NmI4OWQ0NDRhOGNjYWU1ZDY4OGY5YzhkNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L4GhDrHvZhtFM3qFnUAN451c7xobKPR2zTvj_vxKCJA)
> 
> Can you try applying your styling to the node below the `Flyout` and see if that gets the effect you want?

It doesn't work. If you put borderRadious: 3, it seems to work because it is very little radius. If you try it with 12 you can see how it doesn't work.
