### ISSUE TITLE
Upgrade to the latest version of CppWinRT

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#11955]
### Summary

We currently target a minimum of Microsoft.Windows.CppWinRT [2.0.211028.7](https://www.nuget.org/packages/Microsoft.Windows.CppWinRT/2.0.211028.7) released in 2021.

The latest version as of opening this issue is [2.0.230706.1](https://www.nuget.org/packages/Microsoft.Windows.CppWinRT/2.0.230706.1) and was released just a few weeks ago.

We should upgrade to the latest version if possible.

### Motivation

We've stuck with an old version for so long because at that point the library didn't seem to have any active development. However there have been lots of changes and 24 releases since then, so it's probably worth updating.

**Comment by jonthysell** [comment]
This change will at minimum require PR #11953 to get checked in first. And while I haven't tested very scenario, as part of the PR I did verify locally that upgrading to [2.0.230706.1](https://www.nuget.org/packages/Microsoft.Windows.CppWinRT/2.0.230706.1) worked to successfully build the e2e-test-app.

**Comment by YajurG** [comment]
This looks like something that is still planned so marking for backlog - @jonthysell is that still the case?

**Comment by TatianaKapos** [comment]
Moving this to 0.74, doesn't seem like it's needed in 0.73-stable branch but we can backport if needed :)

**Comment by jonthysell** [comment]
The upgrade to this version of CppWinRT was done in https://github.com/microsoft/react-native-windows/pull/12798
