### ISSUE TITLE
React Native windows release build is not working.

### ISSUE THREAD

**Issue by AhmedMustafa505** [microsoft/react-native-windows#11957]
### Discussed in https://github.com/microsoft/react-native-windows/discussions/11956

<div type='discussions-op-text'>

<sup>Originally posted by **AhmedMustafa505** July 29, 2023</sup>
Hello, I'm implementing a new desktop application and I'm newly using react native windows, when I build the app in a debug mode it works fine, but when I tried to build a release build and create AppPackages to install on other devices it doesn't work at all, it shows a black screen. even when I ran the release build on my local machine. 
any solutions ?
</div>

**Comment by k1mmm** [comment]
I hade the same experience untill I generated a certificate when publishing through Visual Studio

**Comment by chrisglein** [comment]
Can you chime in with the environment information as described above? We need to know version and config.

**Comment by AhmedMustafa505** [comment]
> 1. npx react-native -version : 11.3.5
> 2. npx react-native run-windows --info : System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 4.71 GB / 15.76 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 9.7.1 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 18.2.0 => 18.2.0
    react-native: 0.72.3 => 0.72.3
    react-native-windows: 0.72.4 => 0.72.4
  Installed UWP SDKs:
    10.0.18362.0
    10.0.19041.0
    10.0.20348.0
    10.0.22000.0
    10.0.22621.0

**Comment by jonthysell** [comment]
Are you using any community modules?

**Comment by acoates-ms** [comment]
Try setting `InstanceSettings().UseDeveloperSupport(true);` in App::App in App.cpp.

This will enable some addition developer features such as redbox and the devbug menu, which may show additional errors.  Just make sure to turn if back off before you actually ship your application.

**Comment by siri025** [comment]
Encountered the same. I turned on `InstanceSettings().UseDeveloperSupport(true)`; and this is the error I get.

![image](https://github.com/microsoft/react-native-windows/assets/132692484/f0988be7-3516-455f-a448-ca9bbdfcdacd)
![image](https://github.com/microsoft/react-native-windows/assets/132692484/53bebe8b-8aeb-4413-8044-0f37bb2e1a3b)

react-native -v
11.3.3
npm ls rnpm-plugin-windows
└── (empty)
npm ls react-native-windows
└── react-native-windows@0.72.1
node -v
v18.17.0
npm -v
9.8.1

**Comment by chrisglein** [comment]
It's hard to see what that callstack is that's using `globalThis` (which is a Node 12+ addition, but you're on version 18). Can you try this again after turning off minifying your callstack? See [this](https://github.com/microsoft/react-native-windows/wiki/Getting-a-JS-callstack-in-the-debugger#un-minifying-the-callstack) to see how to do that.

**Comment by jcooem** [comment]
Hi, I have a similar problem it looks like. I've turned off minifying the callstack, this is what it looks like:
![image](https://github.com/microsoft/react-native-windows/assets/47226622/e78b0178-1e52-4531-91f6-347c9dd92b2d)

When I dismiss this error, I get:
![image](https://github.com/microsoft/react-native-windows/assets/47226622/9cfff9fe-62ed-405b-8baf-cafaae51b9cf)

I've found if I remove my call to <Provider /> from react-redux (8.1.1), the error goes away.

**Comment by chrisglein** [comment]
@siri025 This may be a more actionable callstack if you're using the Hermes JavaScript engine. Can you try with that enabled? Instructions here: https://microsoft.github.io/react-native-windows/docs/hermes
