### ISSUE TITLE
Visual Studio 17.6.5 Issue

### ISSUE THREAD

**Issue by jbcullis** [microsoft/react-native-windows#11962]
### Problem Description

Visual Studio 17.6.5 not building with dependencies, 
17/6.5 will build as a empty project, but as soon as you add a dependency we get errors.
17.4 is fine.

### Steps To Reproduce

1. Start new project
2. npm install react-nativew-webview
3. build

### Expected Results

Project should build

### CLI version

npx react-native -v

### Environment

```markdown
npx react-native info
```

### Target Platform Version

None

### Visual Studio Version

None

### Build Configuration

None

### Snack, code example, screenshot, or link to a repository

![VS 17 6 error](https://github.com/microsoft/react-native-windows/assets/27532334/cb42dee6-69cf-42eb-985c-ddd1df0c6185)

**Comment by jonthysell** [comment]
What version of RNW are you using? Also, have you opened an issue on `react-native-webview`?

**Comment by jbcullis** [comment]
@jonthysell fresh windows install, latest win rn following the getting started instructions.

The issue seems to be related to nuget as it arises on SQLite, and buffer as well.

I found the distribution for 17.4 and everything works as expected in the new machine.
On the old machine, I rolled back and everything started working.
Guessing an issue with build tools version.

**Comment by jonthysell** [comment]
@chiaramooney Can you look and see if there's some issue with RNW 0.72, VS 17.6.5+, and RN Web View?

**Comment by chiaramooney** [comment]
Adding a packages.config file to the windows/<appname> directory with the following contents:

```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Microsoft.UI.Xaml" version="2.8.0" targetFramework="native"/>
</packages>
```

resolved the issue when I reproed the problem locally. 

@JunielKatarn I know with the PackageReference work there were some scenarios where this packages.config change was necessary. Confirming that this case should be one of them (i.e. a fresh 72 app but the module was built before package reference). 

Once we get confirmation from Julio, I'll make an adjust to the WebView getting started documentation to make this more clear.
