### ISSUE TITLE
onResizeWindowsSize

### ISSUE THREAD

**Issue by sm2017** [Microsoft/react-native-windows#1197]
I see that `View::onLayout()` is not triggered on windows resizing

1- How can I detect windows resizing ??
2- How can I detect orientation change?

**Comment by rozele** [comment]
Perhaps you haven't set the onLayout callback on the correct view? The event should fire. Orientation change detection is handled the same as in other platforms, I think by registering the `namedOrientationDidChange` event

**Comment by sm2017** [comment]
@rozele I set `onLayout` callback to the root view m it works on android but not windows

**Comment by rozele** [comment]
@sm2017 is this still an issue?

**Comment by sm2017** [comment]
@rozele No
