### ISSUE TITLE
Project examples elusive for newbies

### ISSUE THREAD

**Issue by achipa** [Microsoft/react-native-windows#1199]
The README.md states:

- If you're looking for sample code, just browse the Examples folder in the GitHub web UI
- From your recursive clone of the react-native-windows repo, run git pull --recurse-submodules to make sure you're up to date with latest code
- Open Examples.sln from the Examples submodule folder in Visual Studio.

Current behavior: There is no Example folder, no Examples.sln and the only apparent submodule is RNTester

Expected behavior: Find an Examples folder or submodule, and/or have the README.md point to the right location(s)

**Comment by rozele** [comment]
@achipa sorry about this, the examples has recently migrated from UIExplorer to RNTester, we need to update our documentation.
