### ISSUE TITLE
Build failed with message LINK : fatal error LNK1104: cannot open file 'msvcprtd.lib'

### ISSUE THREAD

**Issue by AstrOOnauta** [microsoft/react-native-windows#12009]
### Problem Description

I run my first project with react-native-windows with the command "yarn run react-native run-windows" ando show the follow error:
`Build failed with message LINK : fatal error LNK1104: cannot open file 'msvcprtd.lib'`

Please, anyone can help me?

### Steps To Reproduce

1.  Create a ew project usying: 'npx react-native init PROJECTNAME --version "latest"';
2. Add react-native-windows with "npx react-native-windows-init --overwrite";
3. I follow the RNW system requirements: https://microsoft.github.io/react-native-windows/docs/rnw-dependencies;
4. I run "yarn run react-native run-windows"  and build process failed/

### Expected Results

Run the project debug.

### CLI version

npx react-native -v0.72.3

### Environment

```markdown
npx react-native info results:
System:
  OS: Windows 10 10.0.22621
  CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
  Memory: 7.48 GB / 15.82 GB
Binaries:
  Node:
    version: 18.16.0
    path: D:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.19
    path: ~\AppData\Roaming\npm\yarn.CMD
  npm:
    version: 9.5.1
    path: D:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Enabled
IDEs:
  Android Studio: Not Found
  Visual Studio:
    - 17.7.34003.232 (Visual Studio Community 2022)
Languages:
  Java:
    version: 11.0.16
    path: C:\Program Files\OpenJDK\openjdk-11.0.16_8\bin\javac.EXE
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.3
    wanted: 0.72.3
  react-native-windows:
    installed: 0.72.5
    wanted: 0.72.5
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Target Platform Version

None

### Visual Studio Version

None

### Build Configuration

None

**Comment by acoates-ms** [comment]
Did you run the dependency requirement script? - and let it install all the requirements?

**Comment by AstrOOnauta** [comment]
Yes @acoates-ms, I run the script rnw-dependencies.ps1 and all pass:
![image](https://github.com/microsoft/react-native-windows/assets/81580470/7ad84669-ae60-4150-bc1f-7923201719ac)

**Comment by chrisglein** [comment]
Can you run your build with `--logging` to see if there's more context before that error?

`yarn run react-native run-windows --logging`

Then attach the msbuild.binlog file so we can take a look.
