### ISSUE TITLE
Occasional crash during app suspension due to incorrect threading assumption

### ISSUE THREAD

**Issue by rigdern** [microsoft/react-native-windows#1200]
The App.xaml.cs template seems to assume that UWP's `Suspending` event will fire on the dispatcher thread. When this event fires, it leads to a call to `ReactInstanceManager`'s `OnSuspend` method which asserts that it's running on the dispatcher thread. However, it appears that UWP's `Suspending` event doesn't necessarily fire on the dispatcher thread.

Here's the exception I'm seeing:

    System.InvalidOperationException: Thread does not have dispatcher access.

And here's the call stack:

    at ReactNative.Bridge.DispatcherHelpers.AssertOnDispatcher() in ReactWindows\\ReactNative\\Bridge\\DispatcherHelpers.cs:line 16
    at ReactNative.ReactInstanceManager.OnSuspend() in ReactWindows\\ReactNative\\ReactInstanceManager.cs:line 231
    at ReactNative.ReactPage.OnSuspend() in ReactWindows\\ReactNative\\ReactPage.cs:line 110
    at App.OnSuspending(Object sender, SuspendingEventArgs e) in App.xaml.cs:line 290

During a quick internet search, the closest documentation I could find regarding the threading contract of UWP's `Spusending` event is a note at the bottom of this section: https://docs.microsoft.com/en-us/windows/uwp/launch-resume/resume-an-app#refresh-displayed-content-and-reacquire-resources

    "Note Because the Resuming event is not raised from the UI thread, a dispatcher must be used in your handler to dispatch any calls to your UI."

Based on this, I'm guessing that neither UWP's `Suspending` event nor its `Resuming` event are guaranteed to run on the dispatcher thread.

**Comment by rozele** [comment]
Thanks @rigdern, would love a PR if you have a fix.

**Comment by rigdern** [comment]
@rozele I don't have a fix and unfortunately don't have time to work on a fix right now. A complete fix may be more challenging than it initially appears because the dispatcher thread isn't always guaranteed to exist (for example, when the app launches from the terminated state into a background task via `OnBackgroundActivated`).

**Comment by rozele** [comment]
@rigdern I think this is related to the discussion in #1268, where the CoreWindow dispatcher is not available, but the CoreApplication dispatcher is.

**Comment by rozele** [comment]
Closing, as I think we've removed all references to the CoreWindow.

**Comment by rigdern** [comment]
@rozele 

> Closing, as I think we've removed all references to the CoreWindow.

I just want to double check that the issue is fixed. The issue was that the OS could invoke `Suspending`/`Resuming` off of the UI thread but React Native expected `_host.OnResume` and `_host.OnSuspend` to be invoked on the UI thread.

Are `_host.OnSuspend` and `_host.OnResume` no longer required to be invoked on the UI thread?

**Comment by rigdern** [comment]
@rozele can you reopen this?

**Comment by rozele** [comment]
Were you unable to re-open?

**Comment by rigdern** [comment]
@rozele I thought I couldn't but looking at closed issues now, I see a reopen button. Maybe I overlooked it.

**Comment by rozele** [comment]
@rigdern any updates on this?
