### ISSUE TITLE
Problems publishing app into Microsoft market

### ISSUE THREAD

**Issue by pablomaestri** [Microsoft/react-native-windows#1201]
I'm having this issue when I upload the .appxupload file into the app that I want to publish for Windows Phone:

Error Found: The supported APIs test detected the following errors:
API FormatMessage in api-ms-win-core-localization-l1-2-0.dll is not supported for this application type. System.Diagnostics.Tracing.dll calls this API.
This is from the certification.

I followed the steps from https://docs.microsoft.com/en-us/windows/uwp/packaging/packaging-uwp-apps#create-an-app-package but the problem persists.
What I'm doing wrong?
Thanks!

**Comment by rozele** [comment]
@pablomaestri what was the issue? Did you find something in the core framework using System.Diagnostics.Tracing that is blocking publishing?

**Comment by pablomaestri** [comment]
Hello! I generated again the file and the problem dissapear, but I have another problem with the ReleaseBundle and DebugBundle in the Solution Configuration. Some elements are not visible (for example some TextInput).
