### ISSUE TITLE
Migrate Supported Community Modules to Fabric

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-windows#12027]
Issue to track the work to migrate community modules with Window support to Fabric. 

- [x] Decide on set of communities modules that we will be making the investment to migrate to Fabric.
- [x] Create sub-tasks to track migrating each of those modules to the new architecture.

**Comment by chrisglein** [comment]
Modules are being tracked individually. Don't need this tracking issue at this point.
