### ISSUE TITLE
[Fabric] `run-windows` Script Should Work By Default on Fabric

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-windows#12026]
Currently when you try to build a Fabric app using the CLI the script will fail with an error message that the app cannot be deployed. This makes sense because Win32 apps do not bundle and are not deployed. We should make a design decision here if Fabric apps should have to explicitly specify `--no-deploy` in order for `run-windows` to succeed, or should the script be adjusted to detect if the app is on the old or new architecture and adjust its behavior accordingly. There are other behavior options here; these are just some examples.

**Comment by chrisglein** [comment]
For Fabric apps they're going to be plain old EXEs that need to be run, not deployed.
As we decide what is the golden path for the default Fabric app (**packaged**/unpackaged, **Win32**/UWP, **C++**/C#), the CLI should work.

Related #11564.

**Comment by chrisglein** [comment]
This works now
