### ISSUE TITLE
Release mode has run-time errors - works fine in Debug

### ISSUE THREAD

**Issue by jcooem** [microsoft/react-native-windows#12053]
### Problem Description

Trying to add react-native-windows to my existing RN app. It works fine in debug. But after building in release and running and gives the following error:
![image](https://github.com/microsoft/react-native-windows/assets/47226622/1e971883-1e99-4f85-9967-cd0594264fae)
After dismissing the previous error shows the next error:
![image](https://github.com/microsoft/react-native-windows/assets/47226622/e3ef0b3a-ea7d-4e4e-9510-a9576aab41f6)
This looks to be the Provider component from the react-redux library.

This is in relation it seems to this issue: https://github.com/microsoft/react-native-windows/issues/11957

Please help!

### Steps To Reproduce

1. Create a simple react native app using react-redux and the Provider component
2. Build in debug should work
3. Build in release and it should show error

### Expected Results

Release build should work as expected.

### CLI version

11.3.5

### Environment

```markdown
System:
  OS: Windows 10 10.0.19045
  CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
  Memory: 12.54 GB / 31.81 GB
Binaries:
  Node:
    version: 16.17.0
    path: D:\localapps\nodejs\node.EXE
  Yarn:
    version: 1.22.19
    path: C:\Program Files (x86)\Yarn\bin\yarn.CMD
  npm:
    version: 8.15.0
    path: D:\localapps\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Enabled
    AllowAllTrustedApps: Enabled
    Versions:
      - 10.0.18362.0
      - 10.0.19041.0
      - 10.0.22000.0
      - 10.0.22621.0
IDEs:
  Android Studio: Not Found
  Visual Studio:
    - 16.4.29709.97 (Visual Studio Professional 2019)
    - 17.6.33829.357 (Visual Studio Community 2022)
Languages:
  Java: 11.0.1
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.3
    wanted: 0.72.3
  react-native-windows:
    installed: 0.72.2
    wanted: 0.72.2
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Target Platform Version

None

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

Release

**Comment by chrisglein** [comment]
This will actually be a bit easier to diagnose if you're using the Hermes JavaScript engine. Which is pretty easy to toggle to. Can you try that and see what you get from the callstack then?
https://microsoft.github.io/react-native-windows/docs/hermes
