### ISSUE TITLE
I need to use Child-process on React Native 

### ISSUE THREAD

**Issue by AlmTalal** [microsoft/react-native-windows#12060]
### Summary

Hello ! I need to use the Child-Process module to be able to manipulate a .exe file that is crucial for my app. In Javascript I send commands to the file.exe with child process. But in react native for windows I'm not being able to do it  

### Motivation

I need to get access to the terminal.

**Comment by chrisglein** [comment]
> I need to use the Child-Process module

Can you link the module you're trying to use?
If one exists, it likely doesn't have a Windows implementation.
If one doesn't, you'd need to write the native code yourself. Which would look much like what the module would need too.

**Comment by AlmTalal** [comment]
Hello Chris ! I did not try to link the module because it is not available for react at all. I don't know if it is possible to do it. Anyway,if it is possible, can you help me find the right documentation for creating a new module or for linking the existing one. I tried by myself but I'm not able to create the module. The documentation that i followed is this : https://github.com/microsoft/react-native-windows-samples/blob/main/docs/native-modules.md

**Comment by AlmTalal** [comment]
Im having this error after following the intructions for linking a package: 

Metro has encountered an error: While trying to resolve module `child_process` from file `C:\Users\almta\terminal\App.tsx`, the package `C:\Users\almta\terminal\node_modules\child_process\package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`C:\Users\almta\terminal\node_modules\child_process\index.js`. Indeed, none of these files exist:

  * C:\Users\almta\terminal\node_modules\child_process\index.js(.native|.windows.js|.native.js|.js|.windows.jsx|.native.jsx|.jsx|.windows.json|.native.json|.json|.windows.ts|.native.ts|.ts|.windows.tsx|.native.tsx|.tsx)
  * C:\Users\almta\terminal\node_modules\child_process\index.js\index(.native|.windows.js|.native.js|.js|.windows.jsx|.native.jsx|.jsx|.windows.json|.native.json|.json|.windows.ts|.native.ts|.ts|.windows.tsx|.native.tsx|.tsx): C:\Users\almta\terminal\node_modules\metro\src\node-haste\DependencyGraph.js (289:17)
  
  Any recomendations ?

**Comment by chrisglein** [comment]
The documentation I recommend you get started with is this: https://microsoft.github.io/react-native-windows/docs/native-modules
That should walk you through the steps of writing native code and hooking it up to JavaScript. Make sure you're following along with the version that matches your RN version.
Take note that things are easier if you're just drilling into some native code from your app, not trying to package that as a module for others. Information on that here: https://microsoft.github.io/react-native-windows/docs/native-modules-setup#choose-your-own-adventure

There are also multiple samples you can look over here: https://github.com/microsoft/react-native-windows-samples/tree/main/samples

If any of that is unclear, let us know.

**Comment by AlmTalal** [comment]
I just got access by using the documentation to access [WinRT AP's](https://github.com/microsoft/react-native-winrt/blob/main/docs/USAGE.md). Now I'm having an issue of access denied But Im gonna open a new Issue for that
