### ISSUE TITLE
[0.71] Requests failing due to BlobModule checking for HttpModule.Proxy before WinRTHttpResource has added it

### ISSUE THREAD

**Issue by gozhou** [microsoft/react-native-windows#12071]
### Problem Description

In the **_release_** build of my app using RNW v0.69, requests are failing to complete due to the `response` getter in `XMLHttpRequest.js` throwing an error because `this._response` is a string rather than a blob object. Debugging further I noticed in the native code that `addNetworkingHandler` in `BlobModule.cpp` was not finding `HttpModule.Proxy` in the property bag due to being executed before `WinRTHttpResource.cpp` had added it to the prop bag. This is similar to these two earlier bugs https://github.com/microsoft/react-native-windows/issues/10036 and https://github.com/microsoft/react-native-windows/issues/11439.

In commit https://github.com/microsoft/react-native-windows/pull/11926, a snippet of code was added to `WinRTHttpResource.cpp` that would attempt to mitigate the issue by having `WinRTHttpResource` call `addNetworkingHandler` in the blob module but it or a similar solution was never backported.

### Steps To Reproduce

Unfortunately, I can't seem to get it a minimal repro so hopefully the issues and commits mentioned about is enough context.

### CLI version

8.0.7

### Environment

```markdown
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz
    Memory: 16.61 GB / 31.66 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30, 31, 33
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0
      System Images: android-29 | Google Play Intel x86 Atom, android-R | Google Play Intel x86 Atom
      Android NDK: 22.1.7171670
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.16299.0, 10.0.17763.0, 10.0.19041.0, 10.0.22000.0, 10.0.22621.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.33927.289 (Visual Studio Enterprise 2019), 17.7.34003.232 (Visual Studio Enterprise 2022), 15.9.33926.519 (Visual Studio Enterprise 2017)
  Languages:
    Java: 11.0.1 - C:\android\jdk-11.0.1\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^18.2.0 => 18.2.0
    react-native: ^0.69.12 => 0.69.12
    react-native-windows: ^0.69.27 => 0.69.27
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

Release

**Comment by acoates-ms** [comment]
@JunielKatarn
I'm guessing there have been numerous Http fixes since 0.69.  You might have more luck on a newer version.

**Comment by chrisglein** [comment]
Julio thinks this is #11439, and that we could potentially cleanly backport this back to 0.69. Needs evaluation.
Is upgrading an option? 0.71 I believe is the oldest release with this fix.

**Comment by JunielKatarn** [comment]
Backport out for review #12087.

**Comment by JunielKatarn** [comment]
The requesting party has moved their app to RNW 0.72.

This backport is not currently needed.
