### ISSUE TITLE
Remove Patch in YogaLayoutableShadowNode.cpp (8/11 Integration)

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-windows#12136]
Remove patch in YogaLayoutableShadowNode.cpp to fix bug in type conversion after change has been upstreamed.

**Comment by TatianaKapos** [comment]
Removed in: https://github.com/microsoft/react-native-windows/pull/12571/files#diff-d14b6cd6519ebb0ae82bb5eb64eab59cf48591e608f34a9228fa4c756d7731dd
