### ISSUE TITLE
Inline views with implied 0x0 size crash the app

### ISSUE THREAD

**Issue by antonkh** [Microsoft/react-native-windows#1216]
`MeasureText` should allow the following construct:

```tsx
                <Text>
                    <View style={{width: 18, height: 18, backgroundColor: '#fc0203' }}>
                        <View />
                    </View>
                </Text>
```

The inner `View` has implied 0x0 size, but because it doesn't have that size set explicitly, `MeasureText` throws an exception. This usually happens when some child nodes evaluate to `null`:

```tsx
                <Text>
                    <View style={{width: 18, height: 18, backgroundColor: '#fc0203' }}>
                        { null }
                    </View>
                </Text>
```

That `null` becomes an `RCTView` with no dimensions.

Perhaps `MeasureText` in such cases should stop at the 18x18 `View` since it already knows its dimensions.

**Comment by rozele** [comment]
Are you sure this is a problem with MeasureText and not a more general problem with not running layout calculations recursively?

**Comment by rozele** [comment]
It looks like the inline shadow node visitor is just recursing too far. I'll have a fix for this soon.
