### ISSUE TITLE
Current fabric template includes references to playground / RNTester

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#12179]
### Problem Description

Up until now, all composition/fabric apps have been derivations from the original Playground (Composition) app, and still include hardcoded references to that. This has extended to the new app template from #12172.

### Steps To Reproduce

1. Look at the `pch.h` or `resource.h` files

### CLI version

npx react-native -v

### Environment

```markdown
npx react-native info
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

None

**Comment by chrisglein** [comment]
Potentially should be written with WinAppSDK in mind and its modern assumptions about Win32 authorship.
