### ISSUE TITLE
Fabric template app source is hard to navigate / customize

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#12180]
### Problem Description

There is a giant blob of bootstrapping code in the MyApp.cpp template file, burying important things like how to change both common RN InstanceSettings but also classic Win32 things like app titles.

It would be much preferable if that app were similar to a minimal source like CoreApp, maybe with a config file (or just separate header) loaded at build time.

### Steps To Reproduce

Look at MyApp.cpp

### CLI version

npx react-native -v

### Environment

```markdown
npx react-native info
```

### Target Platform Version

None

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

None

```[tasklist]
### Tasks
- [x] Cleanup the bootstrapping code in the sample-app-fabric app
- [ ] https://github.com/microsoft/react-native-windows/pull/13875
```

**Comment by chrisglein** [comment]
@jonthysell Seems improved with the move to the WinAppSDK wrappers. Did you want to repurpose this for CoreApp-style macro improvements to this? As is it feels "good enough for now".
