### ISSUE TITLE
How to get a CI build working on my react native windows project?

### ISSUE THREAD

**Issue by lovettchris** [microsoft/react-native-windows#12184]
### Problem Description

My ci pipeline installs node.js, runs npm install in my source folder, then tries to compile using:
```
msbuild windows\SmartReplayBar.sln /p:Configuration=Release /p:Platform=x64
```
But it fails with:

> F:\git\athens\uxprototypes\SmartReplayBar\node_modules\.folly\folly-2022.11.28.00\folly\functional\Invoke.h(22,10): fat
al  error C1083: Cannot open include file: 'boost/preprocessor/control/expr_iif.hpp': No such file or directory [F:\git
\athens\uxprototypes\SmartReplayBar\node_modules\react-native-windows\Folly\Folly.vcxproj]

But `npx react-native run-windows ` works fine, so it means this command is something something additionally that npm install is not doing, and obviously I don't want to actually run the app in a CI machine.  So how do I just "build" the app to make sure it's buildable?  I don't see any "build" script in the package.json file, should we add one?

Is there some other command line I can use instead?

### Steps To Reproduce

1. On Windows 11
2.  npx react-native init SmartReplayBar --version "latest"
3. cd SmartReplayBar 
4. npx react-native-windows-init --overwrite
5. npm install
6. msbuild windows\SmartReplayBar.sln /p:Configuration=Release /p:Platform=x64

### Expected Results

Find a command line that works...

### CLI version

11.3.8

### Environment

```markdown
info Fetching system and libraries information...
System:
  OS: Windows 10 10.0.22621
  CPU: "(24) x64 AMD Ryzen 9 3900XT 12-Core Processor           "
  Memory: 48.95 GB / 63.93 GB
Binaries:
  Node:
    version: 18.17.1
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.5
    path: C:\Program Files (x86)\Yarn\bin\yarn.CMD
  npm:
    version: 9.6.7
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Enabled
    AllowAllTrustedApps: Enabled
    Versions:
      - 10.0.19041.0
      - 10.0.22621.0
IDEs:
  Android Studio: Not Found
  Visual Studio:
    - 17.7.34031.279 (Visual Studio Enterprise 2022)
    - 17.8.34112.27 (Visual Studio Enterprise 2022)
Languages:
  Java: Not Found
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli":
    installed: 11.3.8
    wanted: ^11.3.8
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-windows:
    installed: 0.72.9
    wanted: 0.72.9
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

Release

**Comment by lovettchris** [comment]
Never mind, I think I found it:
> npx react-native run-windows --no-launch --no-deploy

**Comment by jonthysell** [comment]
There are some (slightly outdated) sample CI workflows here: https://github.com/microsoft/react-native-windows-samples/tree/main/samples/ContinuousIntegration/GitHubActions
