### ISSUE TITLE
Remove C++20 Patches from ReactCommon Files

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-windows#12195]
Remove patches needed because RN is on C++20 and we use a lower version. Patches were made to ShadowTree.cpp, NumericBitfield.cpp, Config.h, LayoutResults.h, UIMangerBinding.cpp, and Node.h.

**Comment by chrisglein** [comment]
Related:
- https://github.com/microsoft/react-native-windows/issues/7748
- https://github.com/microsoft/react-native-windows/issues/7774

**Comment by TatianaKapos** [comment]
Added RawPropsParser.cpp and propsConversion.h from the PR https://github.com/facebook/react-native/pull/41149/files

**Comment by chrisglein** [comment]
@chiaramooney Can you check the forking status of these files given the integration payload for the past couple months?

**Comment by TatianaKapos** [comment]
Closing, check with main and these files are unforked :)

- ShadowTree.cpp 
- NumericBitfield.cpp
- Config.h
- LayoutResults.h
- UIMangerBinding.cpp
- Node.h
- RawPropsParser.cpp
- propsConversion.h
