### ISSUE TITLE
Fabric's Switch hitting an exception on playground

### ISSUE THREAD

**Issue by TatianaKapos** [microsoft/react-native-windows#12197]
### Problem Description

Trying to open the Switch page on composition-playground hits this callstack and exception, I haven't done much digging here but it looks like this might have to do with pointer events.

![image](https://github.com/microsoft/react-native-windows/assets/42554868/6aef89e8-499d-47df-98db-933d746178a1)

CallStack
`>	Microsoft.ReactNative.dll!facebook::react::EventTarget::retain(facebook::jsi::Runtime & runtime)	C++
 	Microsoft.ReactNative.dll!facebook::react::PointerEventsProcessor::interceptPointerEvent(facebook::jsi::Runtime & runtime, const facebook::react::EventTarget * target, const std::string & type, facebook::react::ReactEventPriority priority, const facebook::react::PointerEvent & event, const std::function<...> & eventDispatcher, const facebook::react::UIManager & uiManager)	C++
 	Microsoft.ReactNative.dll!facebook::react::UIManagerBinding::dispatchEvent(facebook::jsi::Runtime & runtime, const facebook::react::EventTarget * eventTarget, const std::string & type, facebook::react::ReactEventPriority priority, const facebook::react::EventPayload & eventPayload)	C++
 	Microsoft.ReactNative.dll!facebook::react::Scheduler::{ctor}::__l2::<lambda_1>::()::__l2::<lambda_1>::operator()(const facebook::react::UIManagerBinding & uiManagerBinding)	C++
 	[External Code]	
 	Microsoft.ReactNative.dll!facebook::react::UIManager::visitBinding(const std::function<...> & callback, facebook::jsi::Runtime & runtime)	C++
 	Microsoft.ReactNative.dll!facebook::react::Scheduler::{ctor}::__l2::<lambda_1>::operator()(facebook::jsi::Runtime & runtime, const facebook::react::EventTarget * eventTarget, const std::string & type, facebook::react::ReactEventPriority priority, const facebook::react::EventPayload & payload)	C++
 	[External Code]	
 	Microsoft.ReactNative.dll!facebook::react::EventQueueProcessor::flushEvents(facebook::jsi::Runtime & runtime, std::vector<...> && events)	C++
 	Microsoft.ReactNative.dll!facebook::react::EventQueue::flushEvents(facebook::jsi::Runtime & runtime)	C++
 	Microsoft.ReactNative.dll!facebook::react::EventQueue::onBeat(facebook::jsi::Runtime & runtime)	C++
 	Microsoft.ReactNative.dll!facebook::react::EventQueue::{ctor}::__l2::<lambda_1>::operator()(facebook::jsi::Runtime & runtime)	C++
 	[External Code]	
 	Microsoft.ReactNative.dll!Microsoft::ReactNative::AsyncEventBeat::induce::__l2::<lambda_1>::operator()(facebook::jsi::Runtime & runtime)	C++
 	[External Code]	
 	Microsoft.ReactNative.dll!facebook::react::Instance::getRuntimeExecutor::__l2::<lambda_1>::()::__l5::<lambda_1>::operator()(facebook::react::JSExecutor * executor)	C++
 	[External Code]	
 	Microsoft.ReactNative.dll!facebook::react::NativeToJsBridge::runOnExecutorQueue::__l2::<lambda_1>::operator()()	C++
 	[External Code]	
 	Microsoft.ReactNative.dll!Mso::React::MessageDispatchQueue::tryFunc(const std::function<...> & func)	C++
 	Microsoft.ReactNative.dll!Mso::React::MessageDispatchQueue::runOnQueue::__l2::<lambda_1>::operator()()	C++
 	Microsoft.ReactNative.dll!Mso::Details::FunctionObjectWrapper<...>::Invoke()	C++
 	Microsoft.ReactNative.dll!Mso::QueueService::InvokeTask(Mso::Functor<...> && task, std::optional<...> endTime)	C++
 	Microsoft.ReactNative.dll!Mso::LooperScheduler::RunLoop(const Mso::WeakPtr<...> & weakSelf)	C++
 	Microsoft.ReactNative.dll!Mso::LooperScheduler::{ctor}::__l1::<lambda_242_>::operator()()	C++
 	[External Code]	
`

### Steps To Reproduce

1. Open Switch page on playground-composition
2. It will hit this exception 

### Expected Results

Switch page should show without problems

### CLI version

npx react-native -v

### Environment

```markdown
npx react-native info
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

Debug

**Comment by YajurG** [comment]
Ran into this when trying to debug a similar error I was getting trying to load ActivityIndicator - tried to repro but wasn't able to hit this issue locally.

**Comment by TatianaKapos** [comment]
@YajurG Found out that to replicate this, you need to double click on a page to open it! It opens fine on the first click but fails ona double click

**Comment by TatianaKapos** [comment]
closing, error isn't hit in Switch page anymore
