### ISSUE TITLE
MODULE_NOT_FOUND with npx react-native init foo --version "latest"

### ISSUE THREAD

**Issue by lovettchris** [microsoft/react-native-windows#12191]
### Problem Description

node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module 'D:\temp\foo\node_modules\react-native\package.json'
Require stack:
- C:\Users\clovett.REDMOND\AppData\Roaming\npm\node_modules\react-native-cli\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at checkNodeVersion (C:\Users\clovett.REDMOND\AppData\Roaming\npm\node_modules\react-native-cli\index.js:306:21)
    at run (C:\Users\clovett.REDMOND\AppData\Roaming\npm\node_modules\react-native-cli\index.js:300:3)
    at createProject (C:\Users\clovett.REDMOND\AppData\Roaming\npm\node_modules\react-native-cli\index.js:249:3)
    at init (C:\Users\clovett.REDMOND\AppData\Roaming\npm\node_modules\react-native-cli\index.js:200:5)
    at Object.<anonymous> (C:\Users\clovett.REDMOND\AppData\Roaming\npm\node_modules\react-native-cli\index.js:153:7)
    at Module._compile (node:internal/modules/cjs/loader:1256:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\clovett.REDMOND\\AppData\\Roaming\\npm\\node_modules\\react-native-cli\\index.js'
  ]

### Steps To Reproduce

```shell
npm uninstall -g react-native-cli @react-native-windows/cli
npm install -g react-native-cli @react-native-windows/cli
npx react-native init foo --version "latest"
```

### Expected Results

should work, or update docs to use `npx react-native@latest init foo` because this seems to work.

### CLI version

11.3.7

### Environment

```markdown
info Fetching system and libraries information...
System:
  OS: Windows 10 10.0.22621
  CPU: (20) x64 Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz
  Memory: 39.87 GB / 63.78 GB
Binaries:
  Node:
    version: 18.17.1
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.19
    path: C:\Program Files (x86)\Yarn\bin\yarn.CMD
  npm:
    version: 9.8.0
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Enabled
    AllowAllTrustedApps: Enabled
    Versions:
      - 10.0.18362.0
      - 10.0.19041.0
      - 10.0.22000.0
      - 10.0.22621.0
IDEs:
  Android Studio: Not Found
  Visual Studio:
    - 17.7.34031.279 (Visual Studio Enterprise 2022)
Languages:
  Java: Not Found
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.5
    wanted: 0.72.5
  react-native-windows:
    installed: 0.72.10
    wanted: 0.72.10
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

None

**Comment by jonthysell** [comment]
The react-native CLI does give a clear warning to always run `npx react-native@latest`. Where are you seeing instructions to install packages globally? I only see instructions to stop doing that: https://reactnative.dev/docs/environment-setup

PR to update our steps to say latest: https://github.com/microsoft/react-native-windows-samples/pull/879

**Comment by lovettchris** [comment]
Oh, I see my problem was I should not be installing globally, thanks.
