### ISSUE TITLE
Remove Patches for Invalid Comparison Warnings

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-windows#12194]
Remove patch in conversions.h. 
- https://github.com/facebook/react-native/blob/ebcd1ab1ab743f2b0d4b3df16a822f7bc170d58c/packages/react-native/ReactCommon/react/renderer/components/view/conversions.h#L885

Remove patches in Node.cpp. 
- https://github.com/facebook/react-native/blob/aa8caf06415950a9aa5338bfbe7371b579a6f02a/packages/react-native/ReactCommon/yoga/yoga/node/Node.cpp#L305
- https://github.com/facebook/react-native/blob/aa8caf06415950a9aa5338bfbe7371b579a6f02a/packages/react-native/ReactCommon/yoga/yoga/node/Node.cpp#L311
- https://github.com/facebook/react-native/blob/aa8caf06415950a9aa5338bfbe7371b579a6f02a/packages/react-native/ReactCommon/yoga/yoga/node/Node.cpp#L317
- https://github.com/facebook/react-native/blob/aa8caf06415950a9aa5338bfbe7371b579a6f02a/packages/react-native/ReactCommon/yoga/yoga/node/Node.cpp#L331

**Comment by TatianaKapos** [comment]
conversions.h was removed in: https://github.com/microsoft/react-native-windows/pull/12571/files and node.cpp is no longer overriden :)
