### ISSUE TITLE
[Fabric] ActivityIndicator missing transform prop

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#12204]
### Problem Description

In #12115, the code for the transform prop was moved in into `CompositionBaseComponentView` to be used by all components, but the call to `updateTransformProps()` was not added to `ActivityIndicatorComponentView`.

### Steps To Reproduce

1. Set a `transform` style prop on an ActivityIndicator

### Expected Results

Transform is applied

### CLI version

npx react-native -v

### Environment

```markdown
npx react-native info
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

None

**Comment by YajurG** [comment]
I tried to repro this issue locally but the transform prop seemed to be working when I tested it on the ActivityIndicatorExample.js file:

Code sample (from ActivityIndicatorExample):
```
title: 'Default (small, white)',
render(): Node {
  return (
    <ActivityIndicator
      style={[styles.centering, styles.gray, {transform: [{scaleX: 1}]}]}
      color="white"
    />
  );
},
```
Screenshot with `scaleX:1`: 
![image](https://github.com/microsoft/react-native-windows/assets/30995198/5d8ef15c-0c99-43e5-b435-cdccd7e52030)

Screenshot with `scaleX:0.5`:
![image](https://github.com/microsoft/react-native-windows/assets/30995198/e8032fe4-a89f-4b45-ae82-610794b95e38)

Screenshot with `scaleX:2`:
![image](https://github.com/microsoft/react-native-windows/assets/30995198/dd446c39-c860-4e74-9b3e-1857080d0a60)

@jonthysell how did you repro the issue? For reference, the example file I used was in @react-native-windows/tester/js/examples.

**Comment by jonthysell** [comment]
@YajurG I just saw that the fabric ActivityIndicatorComponentView doesn't call `updateTransformProps()`.

**Comment by TatianaKapos** [comment]
Unassigning, not a priority since Activity Indicator is still working with transform props, more of a question is why it's working without calling the method directly
