### ISSUE TITLE
Exception thrown when opening ActivityIndicator example page

### ISSUE THREAD

**Issue by YajurG** [microsoft/react-native-windows#12212]
### Problem Description

When trying to open the ActivityIndicator example page on playground, the following exception is thrown:
![image](https://github.com/microsoft/react-native-windows/assets/30995198/0b64efed-04a6-4c38-bb69-e926d9829492)

When looking at the Call Stack below, it looks like the error originates from the call of `SetReferenceParameter()` on line 1265 in `CompositionBaseComponentView`, which was a change included in #12170. Based on looking at the local variable values, the `centerPointPropSet` being passed to `SetReferenceParameter()` is `null`.
 
### Call Stack
`>Microsoft.ReactNative.dll!winrt::impl::consume_Microsoft_UI_Composition_ICompositionAnimation<winrt::Microsoft::UI::Composition::ExpressionAnimation>::SetReferenceParameter(const winrt::param::hstring & key, const winrt::Microsoft::UI::Composition::CompositionObject & compositionObject) Line 262	
C++
 	Microsoft.ReactNative.dll!Microsoft::ReactNative::CompositionBaseComponentView::EnsureTransformMatrixFacade() Line 1265	C++
 	Microsoft.ReactNative.dll!Microsoft::ReactNative::CompositionBaseComponentView::updateTransformProps(const facebook::react::HostPlatformViewProps & oldViewProps, const facebook::react::HostPlatformViewProps & newViewProps, winrt::Microsoft::ReactNative::Composition::ISpriteVisual m_visual) Line 1121	C++
 	Microsoft.ReactNative.dll!Microsoft::ReactNative::CompositionViewComponentView::updateProps(const std::shared_ptr<facebook::react::Props const> & props, const std::shared_ptr<facebook::react::Props const> & oldProps) Line 1357	C++
 	Microsoft.ReactNative.dll!Microsoft::ReactNative::FabricUIManager::RCTPerformMountInstructions(const std::vector<facebook::react::ShadowViewMutation,std::allocator<facebook::react::ShadowViewMutation>> & mutations, int surfaceId) Line 257	C++
 	Microsoft.ReactNative.dll!Microsoft::ReactNative::FabricUIManager::performTransaction::__l2::<lambda_2>::operator()(const facebook::react::MountingTransaction & transaction, const facebook::react::SurfaceTelemetry & surfaceTelemetry) Line 327	C++
 	[External Code]	
 	Microsoft.ReactNative.dll!facebook::react::TelemetryController::pullTransaction(const std::function<void __cdecl(facebook::react::MountingTransaction const &,facebook::react::SurfaceTelemetry const &)> & willMount, const std::function<void __cdecl(facebook::react::MountingTransaction const &,facebook::react::SurfaceTelemetry const &)> & doMount, const std::function<void __cdecl(facebook::react::MountingTransaction const &,facebook::react::SurfaceTelemetry const &)> & didMount) Line 40	C++
 	Microsoft.ReactNative.dll!Microsoft::ReactNative::FabricUIManager::performTransaction(const std::shared_ptr<facebook::react::MountingCoordinator const> & mountingCoordinator) Line 317	C++
 	Microsoft.ReactNative.dll!Microsoft::ReactNative::FabricUIManager::initiateTransaction(std::shared_ptr<facebook::react::MountingCoordinator const> mountingCoordinator) Line 346	C++
 	Microsoft.ReactNative.dll!Microsoft::ReactNative::FabricUIManager::schedulerDidFinishTransaction::__l7::<lambda_1>::operator()() Line 358	C++
 	Microsoft.ReactNative.dll!winrt::impl::delegate<winrt::Microsoft::ReactNative::ReactDispatcherCallback,`Microsoft::ReactNative::FabricUIManager::schedulerDidFinishTransaction'::`7'::<lambda_1>>::Invoke() Line 2665	C++
 	Microsoft.ReactNative.dll!winrt::Microsoft::ReactNative::ReactDispatcherCallback::operator()() Line 6897	C++
 	Microsoft.ReactNative.dll!winrt::Microsoft::ReactNative::implementation::CreateLoggingCallback::__l2::<lambda_1>::operator()() Line 45	C++
 	Microsoft.ReactNative.dll!winrt::impl::delegate<winrt::Microsoft::ReactNative::ReactDispatcherCallback,`winrt::Microsoft::ReactNative::implementation::CreateLoggingCallback'::`2'::<lambda_1>>::Invoke() Line 2665	C++
 	Microsoft.ReactNative.dll!winrt::Microsoft::ReactNative::ReactDispatcherCallback::operator()() Line 6897	C++
 	Microsoft.ReactNative.dll!winrt::Microsoft::ReactNative::implementation::ReactDispatcher::Post::__l2::<lambda_1>::operator()() Line 56	C++
 	Microsoft.ReactNative.dll!Mso::Details::FunctionObjectWrapper<`winrt::Microsoft::ReactNative::implementation::ReactDispatcher::Post'::`2'::<lambda_1>,void>::Invoke() Line 166	C++
 	Microsoft.ReactNative.dll!Mso::QueueService::InvokeTask(Mso::Functor<void __cdecl(void)> && task, std::optional<std::chrono::time_point<std::chrono::steady_clock,std::chrono::duration<__int64,std::ratio<1,1000000000>>>> endTime) Line 208	C++
 	Microsoft.ReactNative.dll!Mso::TaskDispatcherHandler<Mso::DispatcherTraits<Mso::MicrosoftTypeTag>>::Invoke() Line 216	C++
 	[External Code]	
 	Playground-composition.exe!RunPlayground(int showCmd, bool useWebDebugger) Line 542	C++
 	Playground-composition.exe!WinMain(HINSTANCE__ * instance, HINSTANCE__ * __formal, char * __formal, int showCmd) Line 588	C++
 	[External Code]	
`

### Steps To Reproduce

1. Launch playground-composition.
2. Open the ActivityIndicator example page.

### Expected Results

ActivityIndicator example page should open.

### CLI version

12.0.0-alpha.7

### Environment

```markdown
WARNING: You should run npx react-native@latest to ensure you're always using the most current version of the CLI. NPX has cached version (0.73.0-nightly-20230811-68c7cfe62) != current release (0.72.5)

info Fetching system and libraries information...
System:
  OS: Windows 10 10.0.22621
  CPU: "(24) x64 AMD Ryzen Threadripper PRO 3945WX 12-Cores     "
  Memory: 43.09 GB / 63.86 GB
Binaries:
  Node:
    version: 18.12.1
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.19
    path: C:\Program Files (x86)\Yarn\bin\yarn.CMD
  npm:
    version: 8.19.2
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Enabled
    AllowAllTrustedApps: Enabled
    Versions:
      - 10.0.18362.0
      - 10.0.19041.0
      - 10.0.22000.0
      - 10.0.22621.0
IDEs:
  Android Studio: AI-213.7172.25.2113.9123335
  Visual Studio:
    - 17.7.34031.279 (Visual Studio Enterprise 2022)
    - 16.11.34031.81 (Visual Studio Enterprise 2019)
Languages:
  Java:
    version: 18.0.2.1
    path: C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Target Platform Version

None

### Visual Studio Version

Visual Studio 2022

### Build Configuration

Debug

**Comment by chrisglein** [comment]
Animation module and composition need to be the same, but there's a mix happening here of system composition and lifted composition. @acoates-ms will change the playground app to use lifted composition so this is consistent.

**Comment by TatianaKapos** [comment]
closing, ActivityIndicator page is running fine now :)
