### ISSUE TITLE
npx react-native run-windows not getting completed

### ISSUE THREAD

**Issue by divyanshgarg96-6** [microsoft/react-native-windows#12225]
### Problem Description

I had set up a new project in the Windows system and tried to run the application but it's not getting started and also not giving any error.

### Steps To Reproduce

1. npx react-native init windowsApp
2. cd windowsApp
3. npx react-native-windows-init --overwrite
4. npx react-native run-windows

### CLI version

11.3.7

### Environment

```markdown
System:
  OS: Windows 10 10.0.18363
  CPU: (6) x64 Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
  Memory: 3.26 GB / 7.94 GB
Binaries:
  Node:
    version: 18.18.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.19
    path: C:\Program Files (x86)\Yarn\bin\yarn.CMD
  npm:
    version: 10.2.0
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Enabled
    Versions:
      - 10.0.18362.0
      - 10.0.19041.0
      - 10.0.20348.0
      - 10.0.22000.0
      - 10.0.22621.0
IDEs:
  Android Studio: AI-223.8836.35.2231.10811636
  Visual Studio:
    - 17.7.34031.279 (Visual Studio Enterprise 2022)
Languages:
  Java:
    version: 11.0.20
    path: C:\Program Files\Microsoft\jdk-11.0.20.8-hotspot\bin\javac.EXE
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.5
    wanted: 0.72.5
  react-native-windows:
    installed: 0.72.10
    wanted: 0.72.10
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Target Platform Version

None

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

Debug

### Snack, code example, screenshot, or link to a repository

<img width="1440" alt="Screenshot 2023-10-11 at 12 49 56 PM" src="https://github.com/microsoft/react-native-windows/assets/142501291/12f1ddf0-ae8e-4330-b10d-c50c6e5888bd">

**Comment by chrisglein** [comment]
From your screenshot there it looks like it's still building. Did it continue for some time after that? Can you try again with `--logging` to see if there's something that stalls and doesn't complete?

**Comment by divyanshgarg96-6** [comment]
With --logging it was running for 3 hours and stuck on XamlTypeInof as you can see on PowerShell terminal, and with the normal one it was running for about an hour.

**Comment by chrisglein** [comment]
> With --logging it was running for 3 hours and stuck on XamlTypeInof as you can see on PowerShell terminal, and with the normal one it was running for about an hour.

Can you share the logs with us?

From the screenshot you had it said "select npm", and I don't know if that was just for you to take the screenshot or that was the state before. When you select text on a command-line window it will eventually pause execution as the text buffer fills up. Or at least that's true for classic cmd. The more modern Terminal client might not have that quirk.

> with the normal one it was running for about an hour.

Which normal one are you referring to?

**Comment by divyanshgarg96-6** [comment]
It's working fine now. Thank you
