### ISSUE TITLE
ReactRootView do not unmount on navigation

### ISSUE THREAD

**Issue by k1mmm** [microsoft/react-native-windows#12247]
### Problem Description

I have a second window that hosts a ReactRootView, but this root view is not uninitialized or unmounted when the window is being closed (on navigation). Is there anyway to manually unmount a react root view? Maybe I'm missing something since I'm pretty new to UWP.

### Steps To Reproduce

1) Create a new window with a ReactRootView
2) Close that window
3) ReactRootView is still active and handling events

### CLI version

11.3.7

### Environment

```markdown
System:
  OS: Windows 10 10.0.22621
  CPU: (20) x64 13th Gen Intel(R) Core(TM) i5-13600KF
  Memory: 15.06 GB / 31.82 GB
Binaries:
  Node:
    version: 18.16.1
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.19
    path: C:\Program Files (x86)\Yarn\bin\yarn.CMD
  npm:
    version: 9.5.1
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Enabled
    AllowAllTrustedApps: Enabled
    Versions:
      - 10.0.18362.0
      - 10.0.19041.0
      - 10.0.22000.0
      - 10.0.22621.0
IDEs:
  Android Studio: Not Found
  Visual Studio:
    - 17.6.33829.357 (Visual Studio Community 2022)
Languages:
  Java: Not Found
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.5
    wanted: 0.72.5
  react-native-windows:
    installed: 0.72.10
    wanted: 0.72.10
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Target Platform Version

None

### Visual Studio Version

None

### Build Configuration

None

**Comment by chrisglein** [comment]
> and handling events

Which events are you seeing still flow to the (closed) ReactRootView?

It's possible for RN to keep rolling without a window because headless RN is a useful scenario for some. There's enough variability here in behavior that people want that there's no automatic unload. You may need to manually call unload instance, although arguably there should be clear eventing for handling that for you on Window close. @vmoroz to comment.

**Comment by acoates-ms** [comment]
You can force unload the instance by calling `UnloadInstance` on your `ReactNativeHost`.  If you want the JS instance to stay alive, and just shut down the `ReactRootView`, you can either just ensure that you have no `refrences` to the `ReactRootView`, and it is not in any UI tree. -- Or you could force the `ReactRootView` to shut down by setting its `ReactNativeHost` to null.

**Comment by k1mmm** [comment]
Thank you, nulling ReactNativeHost worked perfectly!
