### ISSUE TITLE
Remove patches for fixes to prevent 4018, 4244 warnings

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#12300]
In order to pass the new BinSkim requirements for the 1ES template (see PR #12295) we had to remove some of the previously suppressed compiler warnings, specifically 4018 and 4244.

In order to build I had to patch the following files:

* `vnext\ReactCommon\TEMP_UntilReactCommonUpdate\react\renderer\core\ShadowNode.cpp`
* `vnext\ReactCommon\TEMP_UntilReactCommonUpdate\react\renderer\core\RawPropsParser.cpp`

**Comment by TatianaKapos** [comment]
closed via https://github.com/microsoft/react-native-windows/pull/12679
