### ISSUE TITLE
Updating the new app template to use WinAppSDK

### ISSUE THREAD

**Issue by acoates-ms** [microsoft/react-native-windows#12303]
> Is there an issue/tracking updating the new app template to use WinAppSDK?

_Originally posted by @jonthysell in https://github.com/microsoft/react-native-windows/issues/12242#issuecomment-1782083799_

There is now.

**Comment by chrisglein** [comment]
@jonthysell we've taken some changes now to take on WinAppSDK 1.4. So we can resolve this now?

**Comment by jonthysell** [comment]
This was resolved by #12481
