### ISSUE TITLE
FormData seems to be array not object

### ISSUE THREAD

**Issue by tero-paananen** [microsoft/react-native-windows#12392]
### Problem Description

`FormData` seems to be array not object in: https://github.com/microsoft/react-native-windows/blob/6450dc820659eaf1e5811300021625fa135b3d85/vnext/Shared/Networking/WinRTHttpResource.cpp#L205

Code above causes that form data is empty Object.

I tried to handle form data as array and managed to get requests work (with string params) with form data:

```
      auto& formData = data["formData"].AsArray(); // as array !

      for (auto& formDataPart : formData) {
        IHttpContent formContent{ nullptr };
        auto& data = formDataPart.AsObject();
        for (auto& formDataPart : data) {
          auto& key = formDataPart.first;
          auto& value = formDataPart.second;
          if (key == "string" && !value.IsNull()) {
            formContent = HttpStringContent{ to_hstring(value.AsString()) };
          }
          else if (key == "uri" && !value.IsNull()) {
            auto filePath = to_hstring(value.AsString());
            auto file = co_await StorageFile::GetFileFromPathAsync(filePath);
            auto stream = co_await file.OpenReadAsync();
            formContent = HttpStreamContent{ stream };
          }

          if (formContent) {
            auto fieldName = data["fieldName"].AsString();
            auto& headers = data["headers"].AsObject();
            AttachMultipartHeaders(formContent, headers);
            multiPartContent.Add(formContent, to_hstring(fieldName));
          }
        }
      }
````

### Steps To Reproduce

1. Create HelloWord for example like
```
npx react-native init Hello071 --template react-native@0.71
cd Hello071
yarn install
npx react-native-windows-init --overwrite --language cs --version 0.71
```
2. Make some fetch request with some form data 
```
 useEffect(() => {
    const formData = new FormData();
    formData.append('username', 'test'); // string param example
    fetch('https://www.google.com', {body: formData, method: 'POST'}).then(
      response => {
        console.log('response);
      },
    );
  }, []);
```

3. You will get `TypeError: Network request failed` because invalid form data handling

### CLI version

10.2.4

### Environment

```markdown
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 15.97 GB / 31.90 GB
  Binaries:
    Node: 16.20.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.19.4 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0, 10.0.22000.0, 10.0.22621.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 17.7.34221.43 (Visual Studio Community 2022), 16.11.31829.152 (Visual Studio Community 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.14 => 0.71.14
    react-native-windows: 0.71.43 => 0.71.43
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Platform Version

None

### Visual Studio Version

Visual Studio 2022

### Build Configuration

Debug

**Comment by tero-paananen** [comment]
Also array in iOS and Android

https://github.com/facebook/react-native/blob/caed1dc2303e8156fcc06c26770d4bb1d0f22788/packages/react-native/Libraries/Network/RCTNetworking.mm#L446


https://github.com/facebook/react-native/blob/caed1dc2303e8156fcc06c26770d4bb1d0f22788/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/modules/network/NetworkingModule.java#L441C6-L441C70

**Comment by gtRfnkN** [comment]
Thank you! I just realized that you've provided a fix for the issue as well - this is fantastic!

It works just as well for version 0.72.20. 
Here is a patch for that version to use with `patch-package`:

```
diff --git a/node_modules/react-native-windows/Shared/Networking/WinRTHttpResource.cpp b/node_modules/react-native-windows/Shared/Networking/WinRTHttpResource.cpp
index 15e28ba..386b90a 100644
--- a/node_modules/react-native-windows/Shared/Networking/WinRTHttpResource.cpp
+++ b/node_modules/react-native-windows/Shared/Networking/WinRTHttpResource.cpp
@@ -202,26 +202,33 @@ IAsyncOperation<HttpRequestMessage> WinRTHttpResource::CreateRequest(
       content = HttpStreamContent{std::move(stream)};
     } else if (data.find("formData") != data.cend()) {
       winrt::Windows::Web::Http::HttpMultipartFormDataContent multiPartContent;
-      auto &formData = data["formData"].AsObject();
+      auto &formData = data["formData"].AsArray();
 
       // #6046 -  Overwriting WinRT's HttpMultipartFormDataContent implicit Content-Type clears the generated boundary
       contentType = nullptr;
 
       for (auto &formDataPart : formData) {
         IHttpContent formContent{nullptr};
-        auto &itr = formDataPart.second["string"];
-        if (!formDataPart.second["string"].IsNull()) {
-          formContent = HttpStringContent{to_hstring(formDataPart.second["string"].AsString())};
-        } else if (!formDataPart.second["uri"].IsNull()) {
-          auto filePath = to_hstring(formDataPart.second["uri"].AsString());
-          auto file = co_await StorageFile::GetFileFromPathAsync(filePath);
-          auto stream = co_await file.OpenReadAsync();
-          formContent = HttpStreamContent{stream};
-        }
+        auto &data = formDataPart.AsObject();
+        for (auto &formDataPart : data) {
+          auto &key = formDataPart.first;
+          auto &value = formDataPart.second;
+          if (key == "string" && !value.IsNull()) {
+            formContent = HttpStringContent{ to_hstring(value.AsString()) };
+          }
+          else if (key == "uri" && !value.IsNull()) {
+            auto filePath = to_hstring(value.AsString());
+            auto file = co_await StorageFile::GetFileFromPathAsync(filePath);
+            auto stream = co_await file.OpenReadAsync();
+            formContent = HttpStreamContent{ stream };
+          }
 
-        if (formContent) {
-          AttachMultipartHeaders(formContent, formDataPart.second["headers"].AsObject());
-          multiPartContent.Add(formContent, to_hstring(formDataPart.second["fieldName"].AsString()));
+          if (formContent) {
+            auto fieldName = data["fieldName"].AsString();
+            auto &headers = data["headers"].AsObject();
+            AttachMultipartHeaders(formContent, headers);
+            multiPartContent.Add(formContent, to_hstring(fieldName));
+          }
         }
       } // foreach form data part
```

**Comment by AhmedMustafa505** [comment]
> .then(
>       response => {
>         console.log('response);
>       },
>     );

I tried to modify WinRTHttpResource.cpp, with this patch as described above, but nothing changed still getting Request Network failed error.

I'm using these versions:
    "react-native": "0.72.7",
    "react-native-windows": "0.72.20" 

and RN- DocumentPicker for selecting file to upload:
    "react-native-document-picker": "^9.0.1",

**Comment by tero-paananen** [comment]
> > .then(
> > response => {
> > console.log('response);
> > },
> > );
> 
> I tried to modify WinRTHttpResource.cpp, with this patch as described above, but nothing changed still getting Request Network failed error.
> 
> I'm using these versions: "react-native": "0.72.7", "react-native-windows": "0.72.20"
> 
> and RN- DocumentPicker for selecting file to upload: "react-native-document-picker": "^9.0.1",

I have not tested `url` case yet. Only `string` is in use currently in our app. This code above is only my proposal and i hoped that someone else could give final code.  Try to fix that if possible?

**Comment by gtRfnkN** [comment]
We are using it as a file upload with `uri` and this change resolved the issue. But we're writing the file ourselves and don't use `react-native-document-picker`. Maybe it does something differently?

**Comment by AhmedMustafa505** [comment]
also react-native-document-picker returns a file data including uri 

`content
: 
""
fileCopyUri
: 
"C:\\Users\\Ahmed\\Downloads\\1_4.png"
name
: 
"1_4.png"
size
: 
1750993
type
: 
"image/png"
uri
: 
"C:\\Users\\Ahmed\\Downloads\\1_4.png"`


this is the changed part of the WinRTHTTPResource.cpp files that I've made following your patch:
`
 auto& formData = data["formData"].AsArray();

      // #6046 -  Overwriting WinRT's HttpMultipartFormDataContent implicit Content-Type clears the generated boundary
      contentType = nullptr;

       for (auto& formDataPart : formData) {
        IHttpContent formContent{ nullptr };
        auto& data = formDataPart.AsObject();
        for (auto& formDataPart : data) {
          auto& key = formDataPart.first;
          auto& value = formDataPart.second;
          if (key == "string" && !value.IsNull()) {
            formContent = HttpStringContent{ to_hstring(value.AsString()) };
          }
          else if (key == "uri" && !value.IsNull()) {
            auto filePath = to_hstring(value.AsString());
            auto file = co_await StorageFile::GetFileFromPathAsync(filePath);
            auto stream = co_await file.OpenReadAsync();
            formContent = HttpStreamContent{ stream };
          }

          if (formContent) {
            auto fieldName = data["fieldName"].AsString();
            auto& headers = data["headers"].AsObject();
            AttachMultipartHeaders(formContent, headers);
            multiPartContent.Add(formContent, to_hstring(fieldName));
          }
        }
      }

      content = multiPartContent;
    }
  }
`

Are there any more changes that needs to added?

**Comment by AhmedMustafa505** [comment]
It worked fine with me now thank you ! =)

**Comment by JunielKatarn** [comment]
I have successfully reproduced the issue and validated the suggested fix.
PR will be published shortly.
