### ISSUE TITLE
× Building Solution: Utilization:          100.0    Average Utilization: 100.0...  × Build failed with message undefined. Check your build configuration.

### ISSUE THREAD

**Issue by miteshdevg** [microsoft/react-native-windows#12409]
### Problem Description

× Building Solution: Utilization:          100.0    Average Utilization: 100.0...
 × Build failed with message undefined. Check your build configuration.
 i am getting above error when try to run  npx react-native run-windows 
 

### Steps To Reproduce

i am getting 4 error in visual studio 

### CLI version

npx react-native -v

### Environment

```markdown
npx react-native info
```

### Target Platform Version

10.0.15063

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2019

### Build Configuration

Debug

**Comment by miteshdevg** [comment]
@asklar Please help me

**Comment by asklar** [comment]
I don't work on this project anymore, sorry. @chrisglein or @jonthysell can help though.

**Comment by chrisglein** [comment]
This issue lacks the environment info requested in the bug template. Please edit your issue report to add this information.

```
npx react-native info
```

**Comment by miteshdevg** [comment]
@chrisglein 

PS E:\project\MealManagePOSApp-git> npx react-native info  

info Fetching system and libraries information...
(node:9636) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9636) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency   
(node:9636) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:9636) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency   
(node:9636) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency 
(node:9636) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:9636) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:9636) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:9636) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
(node:9636) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
(node:9636) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
(node:9636) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
(node:9636) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
(node:9636) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
(node:9636) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
(node:9636) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
(node:9636) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
(node:9636) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
(node:9636) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
(node:9636) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
(node:9636) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
(node:9636) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
(node:9636) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
(node:9636) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
(node:9636) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
(node:9636) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
(node:9636) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
(node:9636) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
(node:9636) Warning: Accessing non-existent property 'which' of module exports inside circular dependency
System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
    Memory: 2.29 GB / 7.80 GB
  Binaries:
    Node: 20.6.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 10.2.1 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
  npmGlobalPackages:
    react-native-cli: 2.0.1
    
    
    
    and window information is 
    
    PS E:\project\MealManagePOSApp-git> npx react-native info  
info Fetching system and libraries information...
(node:9636) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9636) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency   
(node:9636) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:9636) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency   
(node:9636) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency 
(node:9636) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:9636) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:9636) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:9636) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
PS E:\project\MealManagePOSApp-git> npx react-native run-windows --info
(node:15192) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15192) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency     
(node:15192) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency  
(node:15192) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency     
(node:15192) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency   
(node:15192) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency  
(node:15192) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency   
(node:15192) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency   
(node:15192) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
(node:15192) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency    
(node:15192) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency   
(node:15192) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency   
(node:15192) Warning: Accessing non-existent property 'find' of module exports inside circular dependency 
(node:15192) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency 
(node:15192) Warning: Accessing non-existent property 'head' of module exports inside circular dependency 
(node:15192) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency   
(node:15192) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
(node:15192) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency   
(node:15192) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency   
(node:15192) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency  
(node:15192) Warning: Accessing non-existent property 'set' of module exports inside circular dependency  
(node:15192) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency 
(node:15192) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency 
(node:15192) Warning: Accessing non-existent property 'test' of module exports inside circular dependency 
(node:15192) Warning: Accessing non-existent property 'to' of module exports inside circular dependency   
(node:15192) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
(node:15192) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
(node:15192) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency 
(node:15192) Warning: Accessing non-existent property 'which' of module exports inside circular dependency

  System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
    Memory: 2.36 GB / 7.80 GB
  Binaries:
    Node: 20.6.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 10.2.1 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
    react-native-windows: 0.61.16 => 0.61.16
  Installed UWP SDKs:
    10.0.18362.0
    10.0.19041.0
    10.0.22621.0

**Comment by miteshdevg** [comment]
@jonthysell and @chrisglein 
below is error while i am trying to run 

`npx react-native run-windows       `

PS E:\project\MealManagePOSApp-git> npx react-native run-windows       
- Downloading NuGet Binary(node:12312) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:12312) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:12312) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:12312) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:12312) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:12312) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:12312) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:12312) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:12312) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
(node:12312) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
(node:12312) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
(node:12312) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
(node:12312) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
(node:12312) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
(node:12312) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
(node:12312) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
(node:12312) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
(node:12312) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
(node:12312) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
(node:12312) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
(node:12312) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
(node:12312) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
(node:12312) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
(node:12312) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
(node:12312) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
(node:12312) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
(node:12312) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
(node:12312) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
(node:12312) Warning: Accessing non-existent property 'which' of module exports inside circular dependency
 √ Found NuGet Binary
 √ Found MSBuild v16.0 at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin (16.11.34301.259)
- Restoring NuGetsC:\Users\Planet\AppData\Local\Temp\nuget.4.9.2.exe
 √ Restoring NuGets
 √ Found MSBuild v16.0 at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin (16.11.34301.259)
 √ Found Solution: E:/project/MealManagePOSApp-git/windows/MealManage.sln
 i Build configuration: Debug
 i Build platform: x86
Running MSBuild with args /clp:NoSummary;NoItemAndPropertyList;Verbosity=normal /nologo /p:Configuration=Debug /p:Platform=x86 /p:AppxBundle=Never /p:PlatformToolset=v141 /p:VisualStudioVersion=16.0 /bl
 × Building Solution: Utilization:          100.0    Average Utilization: 100.0...
 × Build failed with message undefined. Check your build configuration.

**Comment by miteshdevg** [comment]
@asklar do you have any idea about my issue.

**Comment by jonthysell** [comment]
Hi, how did you create your project? According to your info you're on a an extremely old version. Please create a project with a supported version (RN >= 0.72 at the time of me writing this). See https://microsoft.github.io/react-native-windows/docs/getting-started for details on creating a new project.

**Comment by miteshdevg** [comment]
Thank you so much i will do it if i am facing ajny issue then i will info you

**Comment by miteshdevg** [comment]
![demo](https://github.com/microsoft/react-native-windows/assets/124264146/f30b1267-af10-469f-9b51-e65c64417723)

i am facing above type issue now 


PS E:\project\MealManagePOSApp-git>    npx react-native run-windows
warn Package react-native-sqlite-storage contains invalid configuration: "dependency.platforms.ios.project" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
warn Package rn-fetch-blob contains invalid configuration: "dependency.hooks" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
 ‼ No public VS release found
 i Trying pre-release VS
 × Could not find MSBuild with VCTools for Visual Studio 17.0 or later. Make sure all required components have been installed
Command failed. Re-run the command with --logging for more information.

**Comment by miteshdevg** [comment]
now i am facing 
![image](https://github.com/microsoft/react-native-windows/assets/124264146/c2df2c10-4715-4481-8524-dd90277b5d23)

 × Building Solution: E:\project\MealManagePOSApp-git\node_modules\react-native-windows\PropertySheets\External\M...
 × Build failed with message C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.Cpp.WindowsSDK.targets(46,5): error MSB8036: The Windows SDK version 10.0.19041.0 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [E:\project\MealManagePOSApp-git\node_modules\react-native-windows\Common\Common.vcxproj]. Check your build configuration.
 
 @asklar do you have any idea about my below issue.
@AgneLukoseviciute
@NickGerleman
@JunielKatarn

**Comment by chrisglein** [comment]
No need to keep @ mentioning folks, we have this on our triage query :).

Can you run the dependency script to ensure you have all the VS and SDK dependencies installed. Give us the output of that command:
https://microsoft.github.io/react-native-windows/docs/rnw-dependencies

If that runs clean, next up make extra sure you are following all the steps in the Getting Started walkthrough: https://microsoft.github.io/react-native-windows/docs/getting-started
Make a clean new project with no added project dependencies just to make sure that works first.

Are you still hitting all the warnings from node that you pasted above? That indicates something else may be wrong with your config.
