### ISSUE TITLE
Remove patches for invalid type errors

### ISSUE THREAD

**Issue by YajurG** [microsoft/react-native-windows#12404]
Linked to: https://github.com/microsoft/react-native-windows/issues/12429

Remove patch in FloatOptional.h (`constexpr` declaration in lines 32, 39, 43, 47, 50, 54, 57, 61, 65, 69, 73, 77, 81): 
- https://github.com/facebook/react-native/blob/44660019ea9a8cae3e9199e687ba6033bca732f9/packages/react-native/ReactCommon/yoga/yoga/numeric/FloatOptional.h#L32
- https://github.com/facebook/react-native/blob/44660019ea9a8cae3e9199e687ba6033bca732f9/packages/react-native/ReactCommon/yoga/yoga/numeric/FloatOptional.h#L39
- https://github.com/facebook/react-native/blob/44660019ea9a8cae3e9199e687ba6033bca732f9/packages/react-native/ReactCommon/yoga/yoga/numeric/FloatOptional.h#L43
- https://github.com/facebook/react-native/blob/44660019ea9a8cae3e9199e687ba6033bca732f9/packages/react-native/ReactCommon/yoga/yoga/numeric/FloatOptional.h#L47
- https://github.com/facebook/react-native/blob/44660019ea9a8cae3e9199e687ba6033bca732f9/packages/react-native/ReactCommon/yoga/yoga/numeric/FloatOptional.h#L50
- https://github.com/facebook/react-native/blob/44660019ea9a8cae3e9199e687ba6033bca732f9/packages/react-native/ReactCommon/yoga/yoga/numeric/FloatOptional.h#L54
- https://github.com/facebook/react-native/blob/44660019ea9a8cae3e9199e687ba6033bca732f9/packages/react-native/ReactCommon/yoga/yoga/numeric/FloatOptional.h#L57
- https://github.com/facebook/react-native/blob/44660019ea9a8cae3e9199e687ba6033bca732f9/packages/react-native/ReactCommon/yoga/yoga/numeric/FloatOptional.h#L61
- https://github.com/facebook/react-native/blob/44660019ea9a8cae3e9199e687ba6033bca732f9/packages/react-native/ReactCommon/yoga/yoga/numeric/FloatOptional.h#L65
- https://github.com/facebook/react-native/blob/44660019ea9a8cae3e9199e687ba6033bca732f9/packages/react-native/ReactCommon/yoga/yoga/numeric/FloatOptional.h#L69
- https://github.com/facebook/react-native/blob/44660019ea9a8cae3e9199e687ba6033bca732f9/packages/react-native/ReactCommon/yoga/yoga/numeric/FloatOptional.h#L73
- https://github.com/facebook/react-native/blob/44660019ea9a8cae3e9199e687ba6033bca732f9/packages/react-native/ReactCommon/yoga/yoga/numeric/FloatOptional.h#L77
- https://github.com/facebook/react-native/blob/44660019ea9a8cae3e9199e687ba6033bca732f9/packages/react-native/ReactCommon/yoga/yoga/numeric/FloatOptional.h#L81

Remove patch in Comparison.h:
- https://github.com/facebook/react-native/blob/44660019ea9a8cae3e9199e687ba6033bca732f9/packages/react-native/ReactCommon/yoga/yoga/numeric/Comparison.h#L18
- https://github.com/facebook/react-native/blob/44660019ea9a8cae3e9199e687ba6033bca732f9/packages/react-native/ReactCommon/yoga/yoga/numeric/Comparison.h#L22
- https://github.com/facebook/react-native/blob/44660019ea9a8cae3e9199e687ba6033bca732f9/packages/react-native/ReactCommon/yoga/yoga/numeric/Comparison.h#L29

**Comment by chrisglein** [comment]
@YajurG can you link this to the general C++20 issue. We'll want to remove these as part of those.

**Comment by NickGerleman** [comment]
FYI that there are more, and more invasive usages of C++ 20 coming in future changes.

I left some context in https://github.com/microsoft/react-native-windows/pull/12331, but most of the fixes neded for C++ 20 are already merged. There are just a few left, where `std::future` needs to get replaced with an alternative like `IAsyncOperation`.

**Comment by chrisglein** [comment]
Possible these were deleted. @marlenecota were these removed?

**Comment by marlenecota** [comment]
Removed by #12679
