### ISSUE TITLE
Multiple test apps unable to build and run - producing error MSB3021

### ISSUE THREAD

**Issue by YajurG** [microsoft/react-native-windows#12508]
### Problem Description

When trying to build the solution files of both the integration-test-app and the e2e-test-app in main, I am facing the following build error: 
![image](https://github.com/microsoft/react-native-windows/assets/30995198/f95fc675-83c5-4e87-9d57-1b4b208a8ecf)

### Steps To Reproduce

1. Navigate to the e2e-test-app or integration-test-app directory
2. Run `yarn windows`

### Expected Results

Solution files should build successfully and open the respective applications

### CLI version

12.0.0-alpha.15

### Environment

```markdown
System:
  OS: Windows 11 10.0.22631
  CPU: "(24) x64 AMD Ryzen Threadripper PRO 3945WX 12-Cores     "
  Memory: 43.36 GB / 63.86 GB
Binaries:
  Node:
    version: 18.12.1
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.19
    path: C:\Program Files (x86)\Yarn\bin\yarn.CMD
  npm:
    version: 8.19.2
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Enabled
    AllowAllTrustedApps: Enabled
    Versions:
      - 10.0.18362.0
      - 10.0.19041.0
      - 10.0.22000.0
      - 10.0.22621.0
IDEs:
  Android Studio: AI-213.7172.25.2113.9123335
  Visual Studio:
    - 17.8.34309.116 (Visual Studio Enterprise 2022)
    - 16.11.34301.259 (Visual Studio Enterprise 2019)
Languages:
  Java:
    version: 18.0.2.1
    path: C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Target Platform Version

None

### Visual Studio Version

Visual Studio 2022

### Build Configuration

Debug

**Comment by chrisglein** [comment]
Happening in people's dev machines but not reproing in CI.
However repro is consistent.
Should check if this being caused by a new VS version, as that is a consistent aspect for folks hitting this.

**Comment by chrisglein** [comment]
Seems to be resolved. Not impacting folks today.
