### ISSUE TITLE
react native windows application : react native webview : NuGet packages errors

### ISSUE THREAD

**Issue by vinaykumardetrix** [microsoft/react-native-windows#12537]
### Problem Description

PS C:\Users\XXX\Desktop_Test_Win> npx react-native run-windows
MSBuild version 17.7.2+d6990bcfa for .NET Framework
Build started 12/14/2023 7:26:21 PM.

Project "C:\Users\XXX\Desktop_Test_Win\windows\TestWindows.sln" on node 1 (Restore target(s)).
ValidateSolutionConfiguration:
Building solution configuration "Debug|x64".
C:\Users\XXX\Desktop_Test_Win\node_modules\react-native-windows\PropertySheets\External\Microsoft.ReactNative.Cpp.ProjectReferences.props(12,5): warning MSB4011: "C:\Users\XXX\Desktop_Test_Win\node_mo
dules\react-native-windows\Microsoft.ReactNative.Cxx\Microsoft.ReactNative.Cxx.vcxitems" cannot be imported again. It was already imported at "C:\Users\XXX\Desktop_Test_Win\node_modules\react-native-webview\windo
ws\ReactNativeWebView\ReactNativeWebView.vcxproj (72,5)". This is most likely a build authoring error. This subsequent import will be ignored.
_GetAllRestoreProjectPathItems:
Determining projects to restore...
Restore:
X.509 certificate chain validation will use the default trust store selected by .NET for code signing.
X.509 certificate chain validation will use the default trust store selected by .NET for timestamping.
Done Building Project "C:\Users\XXX\Desktop_Test_Win\windows\TestWindows.sln" (Restore target(s)).

Build succeeded.

C:\Users\XXX\Desktop_Test_Win\node_modules\react-native-windows\PropertySheets\External\Microsoft.ReactNative.Cpp.ProjectReferences.props(12,5): warning MSB4011: "C:\Users\XXX\Desktop_Test_Win\node_
modules\react-native-windows\Microsoft.ReactNative.Cxx\Microsoft.ReactNative.Cxx.vcxitems" cannot be imported again. It was already imported at "C:\Users\XXX\Desktop_Test_Win\node_modules\react-native-webview\win
dows\ReactNativeWebView\ReactNativeWebView.vcxproj (72,5)". This is most likely a build authoring error. This subsequent import will be ignored.

1 Warning(s)
0 Error(s)
Time Elapsed 00:00:00.51
√ Restoring NuGet packages
√ Auto-linking...
Success: No auto-linking changes necessary. (849ms)
√ Found Solution: C:\Users\XXX\Desktop_Test_Win\windows\TestWindows.sln
i Build configuration: Debug
i Build platform: x64
× Building Solution: C:\Users\XXX\Desktop_Test_Win\node_modules\react-native-webview\windows\ReactNa...
× Build failed with message C:\Users\XXX\Desktop_Test_Win\node_modules\react-native-webview\windows\ReactNativeWebView\ReactNativeWebView.vcxproj(194,5): error : This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them. For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is C:\Users\XXX\Desktop_Test_Win\windows\packages\Microsoft.UI.Xaml.2.8.0\build\native\Microsoft.UI.Xaml.targets.. Check your build configuration.
Command failed. Re-run the command with --logging for more information.

Environment:

OS: windows
OS version: windows 11
react-native version: 0.72.7
react-native-webview version:13.6.3
react-native-windows version : 0.72.22

### Steps To Reproduce

1. Install react native @ 0.72.7 project along with react native windows @ 0.72.22 with latest versions and react native webview@ 13.6.3
2. Run npx react-native run-windows 

### Expected Results

need to execute the webview in react native windows application without the above issue that i posted

### CLI version

npx react-native -v got ( 11.3.10 version)

### Environment

```markdown
npx react-native info


PS C:\Users\XXX\Desktop\_Test_Win> npx react-native info
info Fetching system and libraries information...
System:
  OS: Windows 11 10.0.22000
  CPU: "(16) x64 AMD Ryzen 7 5800X 8-Core Processor             "
  Memory: 9.79 GB / 15.91 GB
Binaries:
  Node:
    version: 18.12.1
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.19
    path: C:\Program Files (x86)\Yarn\bin\yarn.CMD
  npm:
    version: 9.3.1
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK:
    API Levels:
      - "29"
      - "33"
    Build Tools:
      - 29.0.2
      - 30.0.3
      - 33.0.1
    System Images:
      - android-29 | Intel x86 Atom_64
      - android-29 | Google APIs Intel x86 Atom
      - android-29 | Google Play Intel x86 Atom
      - android-33 | Google APIs Intel x86 Atom_64
    Android NDK: Not Found
  Windows SDK:
    AllowAllTrustedApps: Enabled
    AllowDevelopmentWithoutDevLicense: Enabled
    Versions:
      - 10.0.17763.0
      - 10.0.18362.0
      - 10.0.19041.0
      - 10.0.20348.0
      - 10.0.22000.0
      - 10.0.22621.0
IDEs:
  Android Studio: AI-213.7172.25.2113.9123335
  Visual Studio:
    - 17.7.34202.233 (Visual Studio Community 2022)
Languages:
  Java: 11.0.16.1
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.7
    wanted: ^0.72.7
  react-native-windows:
    installed: 0.72.22
    wanted: 0.72.22
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Target Platform Version

None

### Visual Studio Version

None

### Build Configuration

None

**Comment by chrisglein** [comment]
Does your project have a `packages.config`? Older app templates didn't have that and newer ones do. Information here:
https://microsoft.github.io/react-native-windows/docs/managing-cpp-deps
Although it looks like you're on version 72 this might have impacted you if you're transitioning from something else. Let us know what you have.

**Comment by chrisglein** [comment]
Also you might have luck poking around for similar issues. For example: https://github.com/microsoft/react-native-windows/issues/11668

**Comment by vinaykumardetrix** [comment]
@chrisglein  i have managed using https://microsoft.github.io/react-native-windows/docs/managing-cpp-deps with the adding package.config file and adding targetmin platform as shown in error report and issue got solved for ehich i used version react-native-windows@12.0.2 so its working fine 

thanks for that kudos to great community we have in react native
