### ISSUE TITLE
@react-native-windows/fs: Unable to resolve module fs

### ISSUE THREAD

**Issue by chayka-wbw** [microsoft/react-native-windows#12542]
### Problem Description

My App.tsx is just the template plus the following lines in the beginning:
```
import fs from '@react-native-windows/fs';
fs.writeFileSync("./test.txt", "text");
```

The error:

Unable to resolve module fs from path\to\project\node_modules\graceful-fs\graceful-fs.js: fs could not be found within the project or in these directories:
  node_modules
  ..\..\node_modules
> 1 | var fs = require('fs')
    |                   ^
  2 | var polyfills = require('./polyfills.js')
  3 | var legacy = require('./legacy-streams.js')
  4 | var clone = require('./clone.js')

  at ModuleResolver.resolveDependency (path\to\project\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:150:15)
    at DependencyGraph.resolveDependency (path\to\project\node_modules\metro\src\node-haste\DependencyGraph.js:282:43)
    at Object.resolve (path\to\project\node_modules\metro\src\lib\transformHelpers.js:176:21)
    at Graph._resolveDependencies (path\to\project\node_modules\metro\src\DeltaBundler\Graph.js:476:35)
    at Graph._processModule (path\to\project\node_modules\metro\src\DeltaBundler\Graph.js:261:38)
    at async Graph._addDependency (path\to\project\node_modules\metro\src\DeltaBundler\Graph.js:372:20)
    at async Promise.all (index 2)
    at async Graph._processModule (path\to\project\node_modules\metro\src\DeltaBundler\Graph.js:322:5)
    at async Graph._addDependency (path\to\project\node_modules\metro\src\DeltaBundler\Graph.js:372:20)
    at async Promise.all (index 1)

### Steps To Reproduce

1. Create a new react-native-windows project, following the getting started guide
2. import the @react-native-windows/fs module and try using a method from there

### Expected Results

Expecting text.txt to be created in the root folder of the project

### CLI version

0.73.1

### Environment

```markdown
info Fetching system and libraries information...
(node:15664) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
System:
  OS: Windows 10 10.0.19045
  CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
  Memory: 2.30 GB / 7.89 GB
Binaries:
  Node:
    version: 21.4.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.19
    path: C:\Program Files (x86)\Yarn\bin\yarn.CMD
  npm:
    version: 10.2.4
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK:
    AllowAllTrustedApps: Enabled
    AllowDevelopmentWithoutDevLicense: Enabled
    Versions:
      - 10.0.19041.0
      - 10.0.22621.0
IDEs:
  Android Studio: Not Found
  Visual Studio:
    - 17.8.34330.188 (Visual Studio Community 2022)
Languages:
  Java:
    version: 20.0.2
    path: C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.1
    wanted: ^0.73.1
  react-native-windows:
    installed: 0.73.2
    wanted: 0.73.2
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

Debug

**Comment by Victor0814gui** [comment]
Based on the initial aspects of React Native, this module should only be there if it were an internal module necessary for React Native Windows to function correctly. If you look at the code, you'll notice they are solely JavaScript files and types 🤔. Perhaps this is the case. The right approach would be to use `react-native-fs`, which provides these necessary methods and more 😎. Moreover, for this module to work, the app would require special permissions to access directories and files 😕.

**Comment by chrisglein** [comment]
Correct, this is an external module and you'd need that to get the native Windows code. The issue tracking that module is here: https://github.com/microsoft/react-native-windows/issues/2829

If I recall, it has a draft implementation but that hasn't been merged. But that's the issue to follow.
