### ISSUE TITLE
*.windows.js files overriding *.ios.js files?

### ISSUE THREAD

**Issue by kevinvangelder** [Microsoft/react-native-windows#1255]
@asgvard says:

> causes RN Windows to override normal RN .js files, which results in for example error on iOS about wrong props for StatusBar like "light-content", because for RN Windows it's only "default" or "dark-content". Which means it actually server RN windows .js files instead of normal ones even for iOS.

There is a possibility this could be an issue with [Metro Bundler](http://github.com/facebook/metro-bundler), but we want to verify that it's not our problem.

**Comment by asgvard** [comment]
Hi,

Some additional info and another possible reproducing case is similar to this issue:
https://github.com/facebook/react-native/issues/13925
(there are also some related issues opened in the comments to this issue)

I've seen exactly the same error, which means it tries to use Text.windows.js, which requires non-existent RCTVirtualText for iOS. Tried to clear react-native packager cache, doesn't help unfortunately.
This happened to me when I used react-native-video above 1.0.0, it had react-native-windows as a dependency.
When I rolled back to react-native-video 1.0.0 - it became fine again. So the rough idea is that adding react-native-windows causes iOS platform to use .windows.js files for some reason.

**Comment by sayar** [comment]
I haven't been able to reproduce this at all neither with the Text or the Video components. Can you share the steps you took to get this error or other reproducible steps? What version of react-native are you using?

**Comment by RyanMitchellWilson** [comment]
I'm getting the exact same error as @asgvard
Using:
react-native: 0.44
react-native-video: 1.2 which uses react-native-windows: 0.41.0-rc.0

**Comment by RyanMitchellWilson** [comment]
I am using a Mac as well as watchman. I've run `watchman watch-del-all` and still get the problem. Did you also build the app to the simulator? I don't have the problem until try to run the app in the simulator then I get the errors.

I'm not sure if this could make a difference but I am using npm 4.4.1 and not yarn.

**Comment by kevinvangelder** [comment]
Watchman isn't supported on Windows, so that could be the major difference between your workflow and ours. It might be worthwhile to try disabling or (temporarily) uninstalling watchman to see if the issue persists.

**Comment by RyanMitchellWilson** [comment]
From what I can see, watchman is pretty much required to run react-native on mac. Unless anyone else has found a way to run without it, I have not.

**Comment by kevinvangelder** [comment]
Hmm, I thought it only enabled live/hot reload.

**Comment by rozele** [comment]
@RyanMitchellWilson if watchman is not installed, won't the packager just default to the node file watcher? It's a bit slower, but it's what's used when developing on Windows.

**Comment by rozele** [comment]
Also, I proposed a change to react-native-video - https://github.com/react-native-community/react-native-video/pull/733 - there's no reason that dependency ever should have been there.

**Comment by RyanMitchellWilson** [comment]
@rozele Ya people have been trying to get that dependency removed for months without much luck, I actually ended up just forking that project and removing the dependency myself so I'm no longer experiencing this problem.

**Comment by negativetwelve** [comment]
this was merged https://github.com/react-native-community/react-native-video/pull/730 but a new release hasn't been pushed out yet :/

**Comment by rozele** [comment]
Closing - much has changed in metro, please advise if this needs reopening.
