### ISSUE TITLE
[Fabric] ShadowProps handling were put behind a feature flag, but now no ComponentViews implement that flag

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#12577]
### Problem Description

Looking at the RN docs, most of the core components support both border and shadow props.

The change in PR #12287 added `CompositionComponentViewFeatures` flags to control whether the `CompositionBase ComponentView` processes border/shadow props for the subclassed ComponentView. The change also set all components to use `CompositionComponentViewFeatures::Default`, which is Borders only, which was fine, because each individual ComponentView sublclass processed shadows themselves.

However PR #12474 removed all these manual calls to process shadow props in the subclasses, without updating their feature flags to include the shadow props.

### Steps To Reproduce

This was seen through static analysis.

### CLI version

npx react-native -v

### Environment

```markdown
npx react-native info
```

### Target Platform Version

None

### Target Device(s)

Desktop

### Visual Studio Version

None

### Build Configuration

None

**Comment by chrisglein** [comment]
Worth seeing how tests could have caught this. It's possible that snapshots didn't include the shadows, which would explain it. But we want this to break a test.
