### ISSUE TITLE
Add support for bordered elements

### ISSUE THREAD

**Issue by Foxman13** [Microsoft/react-native-windows#126]

**Comment by rozele** [comment]
I think we're tabling this issue for now, XAML doesn't really support multi-colored borders so we're taking a simple approach.

**Comment by rozele** [comment]
At the very least, we need to support dashed and dotted borders, we can still table the multi-colored borders.

**Comment by kevinvangelder** [comment]
@rozele If I were to implement this feature, preferably in a way that would support doing css-style border shapes (https://css-tricks.com/examples/ShapesOfCSS/), what method would you suggest?

**Comment by rozele** [comment]
I think we're going to want to abandon the current approach for borders and use a drawing API instead. The current approach creates a XAML tree that is 2x deep because of the use of the XAML border element.

**Comment by rozele** [comment]
At some point someone can investigate using a drawing API (similar to how things are done on Android) rather than the Border component, but for now closing this issue until there is a community need.
