### ISSUE TITLE
Deprecate CoreApp

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#12617]
### Summary

Deprecate and delete the CoreApp projects and APIs.

### Motivation

CoreApp was an experiment in creating a different, minimal RNW app project that builds very quickly. While it has many good ideas that we may want to incorporate into the upcoming new arch template app, by itself it's technically an unsupported chunk of code awkwardly attached to the Playground projects, and its APIs expose us to compliance issues (see #12569) even though no one is using it.

**Comment by chrisglein** [comment]
Let's incorporate the best ideas into our future-looking Fabric templates. But as this was experimental, safe to remove from what we have.
