### ISSUE TITLE
0.72.20 Narrator announcing 'Collapsed' on Pressable components

### ISSUE THREAD

**Issue by cj3699xiao** [microsoft/react-native-windows#12629]
### Problem Description

When focused on a pressable component with Narrator on, Narrator announces it's state as collapsed as part of the accessibility description.
However, the pressable is not relative to property expandable/collapsible. Which was added automatically, and this behavior is not expected. 

I think this problem is associated with this issue. https://github.com/microsoft/react-native-windows/issues/11734

### Steps To Reproduce

1.Load RNTester in Playground
2.Turn Narrator on
3. Navigate to the Pressable component page
4. Focus on any of the Pressable and wait for the Narrator announcement

### Expected Results

Narrator announces 'Collapsed' at the end of the announcement for a Button (acceesbilityRole) component.

### CLI version

11.3.7

### Environment

```markdown
System:
  OS: Windows 11 10.0.23620
  CPU: (20) x64 Intel(R) Core(TM) i9-10900 CPU @ 2.80GHz
  Memory: 4.03 GB / 31.71 GB
Binaries:
  Node:
    version: 18.17.1
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.19
    path: ~\AppData\Roaming\npm\yarn.CMD
  npm:
    version: 9.1.2
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Enabled
    AllowAllTrustedApps: Enabled
    Versions:
      - 10.0.18362.0
      - 10.0.19041.0
      - 10.0.22000.0
      - 10.0.22621.0
IDEs:
  Android Studio: Not Found
  Visual Studio:
    - 17.8.34408.163 (Visual Studio Enterprise 2022)
Languages:
  Java:
    version: javac 19
    path: C:\Program Files\OpenJDK\jdk-19\bin\javac.EXE
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Target Platform Version

None

### Visual Studio Version

None

### Build Configuration

None

**Comment by Yajur-Grover** [comment]
@cj3699xiao Change has been backported to 0.72 in mentioned PR - let me know if this has resolved the issue for you.
