### ISSUE TITLE
Deprecate Web Debugging

### ISSUE THREAD

**Issue by vmoroz** [microsoft/react-native-windows#12719]
### Problem Description

RN docs say that the Web Debugging is deprecated starting with version 0.73:
- https://github.com/react-native-community/discussions-and-proposals/discussions/734
- https://reactnative.dev/docs/next/other-debugging-methods#remote-javascript-debugging-deprecated

Some of our partners continue to rely on Web Debugging since RNW docs do not say that it is deprecated.

### Steps To Reproduce

See the RNW for debugging where the Web Debugging is described as the first way to debug RNW apps:
https://microsoft.github.io/react-native-windows/docs/debugging-javascript

### Expected Results

We must move the Web Debugging section to the end of the debugging docs and clearly state that it is deprecated.
We must remove the Web Debugging section as soon as RN removes Web Debugging or we stop supporting it.

**Comment by chrisglein** [comment]
In core this is deprecated in 0.73 and completely removed in 0.74. So we will need to completely remove by 0.74.
