### ISSUE TITLE
In VS2015, run error: DEP0700 : 应用程序注册失败。错误 0xC000003A: 程序包 部署被 AppLocker 阻止。 (0x80073cf9)

### ISSUE THREAD

**Issue by Leadrive** [Microsoft/react-native-windows#1271]
Win10 LTSB
I followed the Getting Started, 
In VS2015, run error: DEP0700 : 应用程序注册失败。错误 0xC000003A: 程序包 部署被 AppLocker 阻止。 (0x80073cf9)

If use react-native run-windows, report error:
Failed to deploy: Command failed: CheckNetIsolation LoopbackExempt -a -n=

**Comment by sayar** [comment]
@Leadrive can you please share what version of react-native-windows you are running?

**Comment by Leadrive** [comment]
Is the latest version.






At 2017-08-08 22:29:01, "Rami Sayar" <notifications@github.com> wrote:


@Leadrive can you please share what version of react-native-windows you are running?

**Comment by rozele** [comment]
Closing as dupe of #1042.
