### ISSUE TITLE
Remove fork in TurboModuleBinding.cpp

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-windows#12731]
Following the removal of TurboModuleBindingMode in commit https://github.com/facebook/react-native/pull/38220/files, RN now defaults to the prototype code flow.  This source now runs https://github.com/facebook/react-native/blob/f7f9250f6e90a41e798a8f62738925a2859a751a/packages/react-native/ReactCommon/react/nativemodule/core/ReactCommon/TurboModuleBinding.cpp#L198-L202 in replace of `return jsi::Object::createFromHostObject(runtime, std::move(module));`. The new source causes app to render blank when you attempt to load a JS page. 

We are encountering this issue now because we are finally able to defork some code in the TurboModuleBinding/LongLivedObject files which were held at a fixed version for 1-2 years. 

Solution for now is to keep this one line forked and continue to return the hostobject. Ultimately we should figure out how to support the scenario upstream is running.

**Comment by jonthysell** [comment]
@acoates-ms It looks like a lot of the reasons we had for forking this file are now gone (fixed upstream), can you see why this last line still needs to be forked and it the fork can be removed?
