### ISSUE TITLE
Upgrade @react-native non-nightly packages to v0.74.0

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-windows#12733]
All react native monorepo packages were update to v0.74 in this commit https://github.com/facebook/react-native/commit/f40bb9331cd7f3838db92d45a2a2d7b4c23ccc00. This change was missed in the integration in October. 

When attempting to upgrade the packages to v74 now, apps throw an error when trying to load their JS saying the "NodePath type has been removed". We should figure out the culprit of this issue an upgrade the packages to match upstream. Will not be able to cut 74 until this is fixed.

**Comment by acoates-ms** [comment]
I think https://github.com/microsoft/react-native-windows/pull/12740 helps with this.
