### ISSUE TITLE
Failed to restore the NuGet packages

### ISSUE THREAD

**Issue by sm2017** [Microsoft/react-native-windows#1276]
Today I install fresh react native and react native windows (both last version)

When I run `react-native run-wpf` , The following error is occurred
>Failed to restore the NuGet packages

But when I open project using visual studio , It run successfully

**Comment by sayar** [comment]
@sm2017 Are you running VS2017? We've fixed that issue with PR #1262, can you give that branch a try? We haven't merged it back into master and published yet.

**Comment by sm2017** [comment]
@sayar no I use VS2015

**Comment by sm2017** [comment]
How to solve it?

**Comment by rozele** [comment]
@sm2017 can you run:
```
./node_modules/react-native-windows/local-cli/runWpf/.nuget/nuget.exe restore windows/<yourAppName>.sln
```

**Comment by lafka** [comment]
There's no folder called `windows` in the project directory only one named `wpf`. Calling `nuget.exe restore wpf\....` gives the following result:
```
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
All packages listed in packages.config are already installed.
```

Running `react-native run-wpf --verbose` gives:

```
Scanning 945 folders ....
Restoring NuGet packages
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
All packages listed in packages.config are already installed.
Failed to restore the NuGet packages
```

Relevant Dependencies:
* react-native-scripts 1.2.1
* rnpm-plugin-windows 0.2.7
* rnpm-plugin.wpf 0.1.2
* react-native 0.47.0-rc.5
* react-native-windows 0.47.0-rc.5

Don't know if this has any relevance but I have two f# projects located in the `wpf` folder (in addition to the c# app for react-native-windows)

**Comment by lafka** [comment]
Introduced in 16452c56a0e54cf28b33178d2175025129644924 where adding explicitly using parent stdout/err execSync returns null.

This if fixed again in bb100ac8a02be2361dfb0802710af750e920e3b3 which is in master

**Comment by sm2017** [comment]
@lafka I have output as same as you

How can I fix this ? and update my local project to fixed version ?

**Comment by lafka** [comment]
@sm2017 

You can use the git repo as a dependency. In your package.json change:

```
  "react-native-windows": "^0.47.0-rc.5",
  to
  "react-native-windows": "git://github.com/Microsoft/react-native-windows.git#master",
```

and the run `yarn` or `npm install` depending on which pkg manager you use.

**Comment by sm2017** [comment]
@lafka what about updating existing visual studio project . I need something like `react-native-git-upgrade`

**Comment by rozele** [comment]
@sm2017 please update if this is still an issue.
