### ISSUE TITLE
ERROR: The system was unable to find the specified registry key or value.

### ISSUE THREAD

**Issue by lakano** [Microsoft/react-native-windows#1277]
Hi,

I'm trying to get a luck to support Windows 10 mobile phones, but it's doesn't works for me.

I've followed your guide, create a new project, added rnpm-plugin-windows, installed / launched VS2015, initialized windows, but when I try the run-windows command, this failed.

In VS2015, it's impossible to update the Debug/ARM value from the top combo box (disabled).  
But I can give theses informations by command line, I've tried many options. 
I have a real device too (Lumia XL 750)  

> C:\apps\Test4>react-native run-windows --arch arm --device
> Scanning 902 folders for symlinks in C:\apps\Test4\node_modules (31ms)
> Restoring NuGet packages
> MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
> Restoring packages for C:\apps\Test4\node_modules\react-native-windows\ReactWindows\ReactNative\project.json...
> Restoring packages for C:\apps\Test4\windows\Test4\project.json...
> Committing restore...
> Committing restore...
> C:\apps\Test4\node_modules\react-native-windows\ReactWindows\ReactNative\ReactNative.csproj
> Restore completed in 2616ms.
> C:\apps\Test4\windows\Test4\Test4.csproj
> Restore completed in 2617ms.
> 
> NuGet Config files used:
>     C:\Users\Guillaume\AppData\Roaming\NuGet\NuGet.Config
>     C:\ProgramData\nuget\Config\Microsoft.VisualStudio.Offline.config
> 
> Feeds used:
>     https://api.nuget.org/v3/index.json
>     C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
> 
> Building C:/apps/Test4/windows/Test4.sln
> Erreur�: Erreur�: le syst�me n'a pas trouv� la cl� ou la valeur de Registre sp�cifi�e.
> Found MSBuild v14.0 at C:\Program Files (x86)\MSBuild\14.0\bin
> Erreur�: Erreur�: le syst�me n'a pas trouv� la cl� ou la valeur de Registre sp�cifi�e.
> Found MSBuild v4.0 at C:\Windows\Microsoft.NET\Framework64\v4.0.30319\
> Building Solution: C:/apps/Test4/windows/Test4.sln
> Build configuration: Debug
> Build platform: arm
> Build failed with message Error: Command failed: "C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe" "C:/apps/Test4/windows/Test4.sln" /clp:NoSummary;NoItemAndPropertyList;Verbosity=minimal /nologo /p:Configuration=Debug /p:Platform=arm /p:AppxBundle=Never
> . Check your build configuration.

The error is in french, but the translation is: ERROR: The system was unable to find the specified registry key or value.

Any help will be appreciated :)

**Comment by sayar** [comment]
Hi @lakano, can you please verify if msbuild.exe is in "C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe" ? Thanks!

**Comment by lakano** [comment]
Hi @sayar !
Thanks for your quick answer.
Yes, the field is present (not the same upper/lower cases, but under windows I suppose it's not a problem)

> C:\Program Files (x86)\MSBuild\14.0\Bin>MSBuild.exe
>
> Microsoft (R) Build Engine, version 14.0.25420.1
> Copyright (C) Microsoft Corporation. Tous droits réservés.
> 
> MSBUILD : error MSB1003: Spécifiez un fichier projet ou solution. Le répertoire de travail actif n'en contient aucun.
>

**Comment by NivethithaRR** [comment]
Getting the same error. Have you resolved this error? If yes means,kindly let me know the solution for this issue. @lakano

**Comment by lakano** [comment]
Hi @NivethithaRR !
No sorry, and so, we've decided to remove the support of Windows 10 Mobile for our application.
Best regards,
