### ISSUE TITLE
non-windows developers and Expo

### ISSUE THREAD

**Issue by lakano** [Microsoft/react-native-windows#1278]
Hi !

I have currently some bugs to test your react-native-windows module, but I would like to known if it's possible to support windows 10 mobile platform when our development OS is not Windows (I'm under GNU/Linux) ?

Is is possible to init the project (opening VS2015 the first time), compile the project under the windows 10 mobile device, and then to continue to code under GNU/Linux with the server generated by Expo ?

BTW, the Expo team doesn't have the time to add support for UWP, but may be some developers from react-native-windows could create pull request to Expo to support Windows 10 mobile easily ?

Regards

**Comment by rozele** [comment]
@lakano presumably you could use a CI like Visual Studio Mobile Center, VSTS, or AppVeyor to produce Windows binary, so nothing specifically would be blocking the development on other platforms (Linux, MacOS).

I haven't looked into what it would take to enable react-native-windows on Expo, but I think it would be very useful. I'll definitely leave this issue open and keep Expo support on the backlog.

**Comment by lakano** [comment]
Hi @rozele 

Thanks for your answer, I don't known these programs, I'll search informations about this.

Good news about your interest to make react-native-windows inside Expo ! 👍

**Comment by 3a4oT** [comment]
@rozele would be nice to have few words about it in a Readme. Can I give a try to *visual-studio-mac*?

**Comment by joeblew99** [comment]
Is there any more news on this ?

I use visual studio for Mac. I actually find it much easier than visual studio for Windows.

My wish is a way to build in a vagrant version of Windows 10 on my MacBook.

**Comment by kaflan** [comment]
https://expo.io/
Hello, any updates?

**Comment by rozele** [comment]
Please file issues on the Expo repo - more likely to garner support there.
