### ISSUE TITLE
Add react-native-gesture-handler compatibility for UWP

### ISSUE THREAD

**Issue by rozele** [Microsoft/react-native-windows#1283]
We should probably keep an eye on https://github.com/kmagiera/react-native-gesture-handler. Ideally, we'd do more than keep an eye on it and implement react-native-windows support.

**Comment by rozele** [comment]
Will re-open if there is more demand or the lib gets merged into core react-native repo

**Comment by Epicurean** [comment]
Hi, a bit new here but I'm having an issue with react-navigation support for the windows plugin. It appears that the latest version of react-navigation has an unavoidable dependency on this library. Therefore currently react-navigation is not usable for UWP apps.
Thanks!

**Comment by JulianAssmann** [comment]
I'm having the same problem. An implementation of the library for UWP therefore is important.

**Comment by cavasinf** [comment]
@rozele Any news about **react-navigation** and *react-native-windows* compatibility ?

**Comment by erksch** [comment]
This issue should be reopened. *react-navigation* and therefore *react-native-gesture-handler* too is used by every second react native app!
