### ISSUE TITLE
Unfork ScrollViewProps.cpp

### ISSUE THREAD

**Issue by TatianaKapos** [microsoft/react-native-windows#12879]
### Problem Description

When integrating react-native 0.74-rc0, they brought in https://github.com/facebook/react-native/commit/45b1aef291d26c5749ad8391582d3eb1146dcdda which has an unsafe conversion from int to float. We should make a PR upstream to fix this

### Steps To Reproduce

1. Remove override
2. Try to build playground

### CLI version

npx react-native -v

### Environment

```markdown
npx react-native info
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

Debug

**Comment by TatianaKapos** [comment]
Closing: looks like they removed the commit a week later: https://github.com/facebook/react-native/pull/43554 and next integration goes past that commit. Will still need the fork in 74.0 branch unless we cherry pick the commit

**Comment by Yajur-Grover** [comment]
This fork is present in the current integration up to 2/21: https://github.com/microsoft/react-native-windows/pull/12880. Will close the issue once main is integrated past.

**Comment by TatianaKapos** [comment]
Seems like they only reverted one of the methods, will still need to make a PR upstream to correctly cast the other method

**Comment by TatianaKapos** [comment]
PR upstream: https://github.com/facebook/react-native/pull/44603
