### ISSUE TITLE
Paper in 0.74 should default to direct debugging instead of web debugging

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#12928]
### Summary

Web debugging gives a bunch of warnings and while it may "work" still in 74 (needs confirmation) we really should bite the bullet and set the default in the (Paper) app templates to direct debugging and get that change backported to 74. This requires that Hermes direct debugging is in a known good state. There will also be work to update the docs to reflect this change (and perhaps completely delete web debugging instructions).

- [x] Change direct debugging to be the default
- [ ] Update [debugging documentation](https://microsoft.github.io/react-native-windows/docs/debugging-javascript)
- [ ] Update [CLI documentation](https://microsoft.github.io/react-native-windows/docs/run-windows-cli)
- [ ] Remove web debugging support

### Motivation

See the rationale for the deprecation here: https://github.com/react-native-community/discussions-and-proposals/discussions/734

**Comment by chrisglein** [comment]
Many of these changes addressed with #12724, but need documentation changes too.

**Comment by Yajur-Grover** [comment]
Looks like the debugging documentation was updated here to show that Web Debugging was officially deprecated in 0.73: https://github.com/microsoft/react-native-windows-samples/pull/930/files. With regards to deleting web debugging documentation, with Hermes direct debugging not yet in a good state, should we leave that section as is? Just opened a PR updating the CLI docs with a web debugging deprecated message.
