### ISSUE TITLE
Beachball bug caused release of react-native-windows@0.0.1-0 from main

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#12979]
### Problem Description

It looks like dependabot bumped beachball right before today's publish, and the new beacball decided to bump us to and publish a `react-native-windows@0.0.1-0` (instead of `react-native-windows@0.0.0-canary.805`).

I'm not sure but I believe there's places where we rely on the 0.0.0-canary.XYZ format to identify canary builds and this may have downstream consequences.

Upstream bug: https://github.com/microsoft/beachball/issues/964

### Steps To Reproduce

N/A

### CLI version

npx react-native -v

### Environment

```markdown
npx react-native info
```

### Target Platform Version

None

### Visual Studio Version

None

### Build Configuration

None

**Comment by chrisglein** [comment]
@acoates-ms has a relevant PR: https://github.com/microsoft/react-native-windows/pull/12980
