### ISSUE TITLE
Create React Native Fabric Island core functionality

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#12988]
The basic infrastructure and APIs so app developers can create a React Native Fabric Island and put it into their Win32 host window. This includes connecting input, output, and UIA for the Win32 side, as well as setting up the RN side so a hosted JS app can ask the Fabric renderer to render WinAppSDK scene graph (composition) visuals. Without this, there’s no entry point for RN app developers to create React Native Fabric experiences which render using WinAppSDK.
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/react-native-windows/issues/13308
```

**Comment by sharath2727** [comment]
Completed.
