### ISSUE TITLE
Narrator in scan mode will escape region of Popup when moving around

### ISSUE THREAD

**Issue by matlop1342** [microsoft/react-native-windows#12981]
When putting Narrator into scan mode, the narrator focus is able to escape the Popup region as the user moves narrator focus around. This behavior doesn't appear to repro with Flyouts, where focus is intentionally trapped in the region (in a Flyout, trying to push up/down at the edges of the region caues the talkback to announce there are no more items correctly).

In addition, it seems that if I set the 'isLightDismissEnabled' property on the Popup to true, the issue goes away and narrator can't escape the Popup. However, setting this property breaks using the Popup as a modal and causes other issues with our app. It is not clear to me why setting this property appears to fix the issue.

Observing this on Xbox console using RNW version 0.72.32. Can this be fixed in a later RNW version, or is there something we can set on the Popup or in the XAML to work around this issue (since it is causing accessibility problems)?

https://github.com/microsoft/react-native-gallery/assets/73371242/b39124da-6b39-4567-8a07-a474b0d4e9a5

**Comment by matlop1342** [comment]
This issue was directly raised by our Accessibility team on console. The expectation is that narrator mode should not be able to wander beyond the popup, since that can cause confusion to visually impaired individuals.

In addition, Popup does not behave the same as Flyout here. With Flyout, narrator mode stays within the bounds properly, but narrator focus leaves the Popup (unless the isLightDismissEnabled property is set for some reason).

**Comment by Yajur-Grover** [comment]
From testing the available Popup-style controls on WinUI 3 Gallery, it looks like the behavior shown above was also shown on the TeachingTip example, but not on the Flyout or ContentDialog examples, which shows it is also present within the platform. Will connect with someone on the Controls team and forward this issue to them for further insight.

**Comment by chiaramooney** [comment]
@Yajur-Grover Can I close since this is a WinUI issue?
