### ISSUE TITLE
Create public OSS new app templates for React Native Fabric

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#12991]
The tooling and templates necessary for end developers to create their own Win32 app which hosts a React Native Fabric Island. This will need to conform to the expectations and norms of the existing RN app development ecosystem. Without this we will not be able to keep or attract external developers to React Native for Windows after the Paper renderer is deprecated.
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/react-native-windows/pull/13875
```

**Comment by chrisglein** [comment]
Builds upon what is done in #12990 to then bake this into the template for new apps, replacing the boiler plate code there today with use of the new `ReactNativeIsland` type (or uses that as an implementation detail of `ReactApplication`, if simple form). Sample lays out a more manual way, where this is the clean easy mode that produces a tiny WinMain for the end app developer. Sample = clarifying advanced mode (built and validated in repo), New App = simple easy to understand mode.
