### ISSUE TITLE
Implement accessibilityActions property for Image for fabric

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#13017]
Implement the accessibilityActions property for the fabric implementation of Image.

This property was available in RNW Paper via FrameworkElementViewManager.

See #13316 for implementation details.

See https://reactnative.dev/docs/accessibility#accessibility-actions for details.

**Comment by chiaramooney** [comment]
Can close this issue. Infrastructure for accessibilityActions is in place for all core components. See https://github.com/microsoft/react-native-windows/issues/13316 for current list of supported actions. This list will grow over time as more accessibility behavior is implemented.
