### ISSUE TITLE
Implement clearTextOnFocus property for TextInput for fabric

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#13122]
Implement the clearTextOnFocus property for the fabric implementation of TextInput.

This property was available in RNW Paper via TextInputViewManager.

See https://reactnative.dev/docs/textinput#cleartextonfocus-ios for details.

**Comment by TatianaKapos** [comment]
clearTextOnSubmit: https://github.com/microsoft/react-native-windows/pull/12746, not everything will be similar but a good starting point on where to implement the code!

First Steps will be to see what IOS/Android/Web does for this property on Expo Snack and then look and see what we implemented on Paper
