### ISSUE TITLE
Extending React Native

### ISSUE THREAD

**Issue by sm2017** [Microsoft/react-native-windows#1316]
I read https://github.com/Microsoft/react-native-windows/blob/master/docs/NativeModulesWindows.md

But what about WPF? Must I create separate module for UWP and WPF ?

**Comment by rozele** [comment]
@sm2017 you can architect the UWP and WPF native module in a similar way to how ReactNative.csproj and ReactNative.Net46.csproj are architected, using a C# shared project.

E.g., react-native-code-push is implemented with a shared project:
https://github.com/Microsoft/react-native-code-push/tree/master/windows
