### ISSUE TITLE
Microsoft.JavaScript.Hermes 0.1.20 is out, we're still on 0.1.18

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#13195]
### Problem Description

I know we're waiting for a bigger update with #13182, but if that's going to take a while, we should at least get the OOM fixes that were released in Hermes 0.1.20 into main and our supported stable branches (back to 0.72?)

### Steps To Reproduce

1. Create a new app (with Hermes enabled)
2. Look at version of Hermes used at the top.

### CLI version

npx react-native -v

### Environment

```markdown
npx react-native info
```

### Target Platform Version

None

### Visual Studio Version

None

### Build Configuration

None

**Comment by vmoroz** [comment]
I am going to send PRs today to switch to 0.1.21 where the debugger supposed to be fixed.

**Comment by chrisglein** [comment]
Resolved with #13207
