### ISSUE TITLE
Current installation Documentation pulls incompatible React native version

### ISSUE THREAD

**Issue by freercurse** [microsoft/react-native-windows#13201]
### Problem Description

When following the included DOCS to get started and configure ENV - https://microsoft.github.io/react-native-windows/docs/getting-started

React-native nightly is suggested, however when trying to install react-native-windows, the install process errors out due to a version error

### Steps To Reproduce

1. Open IDE to new Folder
2. npx --yes react-native@nightly init <projectName> --version "nightly"
3. cd projectName
4. npx --yes react-native-windows-init --overwrite  (ERROR HERE)

### Expected Results

Successful installation.

For now removing the nightly version specification works when trying to install react native.

### CLI version

13.6.6

### Environment

```markdown
(node:21292) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
System:
  OS: Windows 11 10.0.22631
  CPU: "(12) x64 AMD Ryzen 5 5600X 6-Core Processor             "
  Memory: 17.93 GB / 31.91 GB
Binaries:
  Node:
    version: 22.1.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn: Not Found
  npm:
    version: 10.7.0
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Enabled
    AllowAllTrustedApps: Enabled
    Versions:
      - 10.0.19041.0
      - 10.0.22621.0
IDEs:
  Android Studio: Not Found
  Visual Studio:
    - 17.9.34728.123 (Visual Studio Community 2022)
Languages:
  Java: 11.0.16.1
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.1
    wanted: 0.74.1
  react-native-windows:
    installed: 0.74.2
    wanted: 0.74.2
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Target Platform Version

None

### Target Device(s)

Desktop

### Visual Studio Version

None

### Build Configuration

None

### Snack, code example, screenshot, or link to a repository

No-code-yet

**Comment by chrisglein** [comment]
I believe that should be
`npx --yes react-native@latest init <projectName> --version "latest"`

@TatianaKapos, do we have the right instructions from this? https://github.com/microsoft/react-native-windows-samples/pull/936
