### ISSUE TITLE
Click coordinate issues when hosting in XAML Frame or ContentPresenter

### ISSUE THREAD

**Issue by Colengc** [Microsoft/react-native-windows#1320]
I'd like to use a XAML Frame or ContentPresenter, to add React content to an existing UWP/XAML application.  However, if the Frame or ContentPresentor is not at 0,0 of the Window, the offset is not handled, resulting in incorrect click coordinates.

It's fairly straight forward to modify AwesomeProject to demonstrate the issue.  Add a Page (i.e. BlankPage1) to the project, and add the following:

    <Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
        <Grid.RowDefinitions>
            <RowDefinition Height="50"/>
            <RowDefinition Height="*"/>
            <RowDefinition Height="100"/>
        </Grid.RowDefinitions>
        <TextBlock Grid.Row="0" Height="50">X</TextBlock>
            <ContentPresenter Grid.Row="1" Name="TestFrame" ></ContentPresenter>
            <TextBlock Grid.Row="2">Y</TextBlock>
    </Grid>

Add the following to the backing CS file (i.e.BlankPage1.xaml.cs) :

        ReactPage _reactPage;

(in constructor)
            _reactPage = new MainPage();
            this.TestFrame.Content = _reactPage; 

Then, remove all reference to "_reactPage" from App.xaml.cs, and replace the call to:

           rootFrame.Content = _reactPage;

With:

         rootFrame.Navigate(typeof(BlankPage1), arguments);

With these changes, if you enable the Inspector and attempt to click on a text block, you will need to click 50 vpixels below to hit it.

I suspect the fix would be to EnqueueFindTargetForTouch in UIViewOperationQueue.cs or Measure in NativeViewHierachyManager.cs.

Please let me know if there is a better way to do what I'm trying to do.  Thanks.  :)

 - Colen

**Comment by Colengc** [comment]
I have a hack.  I have no idea what I might be breaking, but am providing my hack here in case it's useful to someone who might try to address the issue properly.

In ReactWindows\ReactNative\Touch\TouchHandler.cs, I've update OnPointerPressed() to walk the UI tree all the way up to the top, in order to establish the rootPoint.

Was:

	var rootPoint = e.GetCurrentPoint(_view);

Changed to:

	DependencyObject tmp = _view;
	DependencyObject topParent = null;
	while (tmp != null)
	{
		topParent = tmp;
		tmp = VisualTreeHelper.GetParent(tmp);
	}
	var rootPoint = e.GetCurrentPoint(topParent as UIElement);

And, in ReactWindows\ReactNative.Shared\UIManager\UIViewOperationQueue.cs, I've updated EnqueueFindTargetForTouch() to offset targetY and targetX based on the position of the React view in the window:

Was:

	_nativeViewHierarchyManager.Measure(reactTag, _measureBuffer);

Changed to:

	_nativeViewHierarchyManager.MeasureInWindow(reactTag, _measureBuffer);
	targetX += (double)_measureBuffer[0];
	targetY += (double)_measureBuffer[1];
	_nativeViewHierarchyManager.Measure(reactTag, _measureBuffer);

**Comment by rozele** [comment]
I believe this is closed by #1556
