### ISSUE TITLE
ClipboardModule could throw exception if clipboard is already opened by another process

### ISSUE THREAD

**Issue by pre10der89** [microsoft/react-native-windows#1321]
The WPF ClipboardModule will throw the following COMException if the clipboard is already opened by another process:

"OpenClipboard Failed (Exception from HRESULT: 0x800401D0 (CLIPBRD_E_CANT_OPEN)"

**Comment by rozele** [comment]
@pre10der89 is this still an issue?

**Comment by pre10der89** [comment]
@rozele I'm sure its still an issue... I long ago submitted a PR that fixes this issue... We've had it patched for over a year without a seeing this issue again.
https://github.com/Microsoft/react-native-windows/pull/1325
