### ISSUE TITLE
[Fabric] Pipe through ImageLoadError and ImageErrorInfo data

### ISSUE THREAD

**Issue by marlenecota** [microsoft/react-native-windows#13262]
### Summary

Integration #13261 brings in this change https://github.com/facebook/react-native/commit/78ab5f4b836d64b71760754c7cce1315630640c7 which now passes ImageLoadError and ImageErrorInfo objects to Image events. Currently we're passing in blank values. 

### Motivation

Parity with upstream

**Comment by chrisglein** [comment]
Look for TODOs with this issue number where the data is being passed as blank.
