### ISSUE TITLE
VSCode warns about project.json files being deprecated 

### ISSUE THREAD

**Issue by jmcginty** [Microsoft/react-native-windows#1329]
There are a few project.json files in the project which seem to be redundant
```

C:\Git\react-native-windows\ReactWindows\Playground\project.json
C:\Git\react-native-windows\ReactWindows\ReactNative\project.json
C:\Git\react-native-windows\ReactWindows\ReactNative.Tests\project.json
```

Can we delete these to remove the warnings from VSCode?

**Comment by jmcginty** [comment]
It looks like these are needed until we get rid of the dependency on 2015. Closing the issue.

**Comment by rozele** [comment]
Re-opening now that we have deprecated VS 2015 support.
