### ISSUE TITLE
Increase method effective parameters limit to more than 7

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#13307]
### Discussed in https://github.com/microsoft/react-native-windows/discussions/13295

<div type='discussions-op-text'>

<sup>Originally posted by **AgusAzar** June  4, 2024</sup>
Hi i'm doing an implementation for windows of an existing library and have some problems with a method.
The method should recieve 8 params to fit the android and ios implementation but when i try to compile it i have an error of type IndexOutOfRangeException.
After look at the implementation of CodeGenerator in Microsoft.ReactNative.Managed.CodeGen, found that a method can only have 7 named parameters.

    public static readonly SyntaxToken[] ArgLocalNames = new SyntaxToken[] {
      Arg0LocalName, Arg1LocalName, Arg2LocalName, Arg3LocalName,
      Arg4LocalName, Arg5LocalName, Arg6LocalName,
    };

Is there a reason for this limitation?</div>

**Comment by acoates-ms** [comment]
Looks like maybe this array just needs extending:
https://github.com/microsoft/react-native-windows/blob/568faad22c14f6408654d1aa18935c4f25a527c6/vnext/Microsoft.ReactNative.Managed.CodeGen/ReactNativeNames.cs#L90
