### ISSUE TITLE
0.74.8 Broke Native Module Creation

### ISSUE THREAD

**Issue by cheymonty** [microsoft/react-native-windows#13330]
### Problem Description

react-native-windows update `0.74.8` broke native module creation

### Steps To Reproduce

1. Create project following these steps https://microsoft.github.io/react-native-windows/docs/getting-started
2. When you do `npx --yes react-native-windows-init --overwrite --language cs` and go to create a native module, none of the attributes can be found (ex: `[ReactModule]`)

### Expected Results

The attributes should be found. I made a new project with `0.74.7` and everything works fine

### CLI version

13.6.6

### Environment

```markdown
System:
  OS: Windows 11 10.0.22631
  CPU: "(16) x64 AMD EPYC 7763 64-Core Processor                "
  Memory: 34.52 GB / 63.95 GB
Binaries:
  Node:
    version: 20.11.1
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 3.6.4
    path: C:\.tools\.npm-global\yarn.CMD
  npm:
    version: 10.2.4
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Enabled
    AllowAllTrustedApps: Enabled
    Versions:
      - 10.0.19041.0
      - 10.0.22621.0
IDEs:
  Android Studio: Not Found
  Visual Studio:
    - 17.10.34928.147 (Visual Studio Enterprise 2022)
Languages:
  Java: 11.0.22
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.2
    wanted: 0.74.2
  react-native-windows:
    installed: 0.74.8
    wanted: 0.74.8
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Visual Studio Version

17.10.1

### Build Configuration

None

**Comment by jonthysell** [comment]
IF you look on this page, you'll see you need to specify `--projectType lib`: https://microsoft.github.io/react-native-windows/docs/native-modules-setup
