### ISSUE TITLE
ChakraBridge: The application which this project type is based on was not found

### ISSUE THREAD

**Issue by macgriffiths** [Microsoft/react-native-windows#1334]
### Master

Hi I can't ChakraBridge to load on VS 17, it seems like the migration fails. 

- Target Platform: UWP

- Target Platform Version(s): 10.0.15063

- Target Device(s): Desktop, Mobile, Mobile Emulator

- Development Operating System: Windows 10 (Build 10.0.15063)

- Visual Studio Version: Visual Studio Enterprise 2017 (Version 15.2 (26430.13))

### Steps to Reproduce

1. Complete the getting started steps 
2. Open the solution on visual studio
3. ChakraBridge project does not load and it say incompatible. 

### Expected Behavior

The Chakrabridge should open

### Actual Behavior

Migration report: 

  | Message
-- | --
  | **..\node_modules\react-native-windows\ReactWindows\ChakraBridge\ChakraBridge.vcxproj**:         The application which this project type is based on was not found. Please try this link for further information: https://go.microsoft.com/fwlink/?LinkId=660342&projecttype=8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942

I can't get to the retarget bit since the project could not load
> Note: If you are using Visual Studio 2017, you will need to retarget the ChakraBridge project by right clicking on the project in the Solution Explorer and selecting "Retarget Projects" and pressing okay on the popup dialog (Platform Toolset should say "Upgrade to v141" in the dialog).

1. Launching the solution
![image](https://user-images.githubusercontent.com/460851/29867365-9f40770c-8d7b-11e7-83e6-8c096d798af9.png)

2. Solution Explorer
![image](https://user-images.githubusercontent.com/460851/29867461-f7532746-8d7b-11e7-99fd-b02bbb382dbe.png)

**Comment by rozele** [comment]
@macgriffiths perhaps you need to install C++ tools for VS 2017? Might need to update the docs on what versions of the UWP framework are required plus what extensions for VS 2017...

**Comment by macgriffiths** [comment]
Thank you @rozele, Turns out I only installed C++ tool for VS 15 and not 17. Issue has been resolved
