### ISSUE TITLE
Header image not loading for new app (old arch, C++ UWP)

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#13363]
### Problem Description

When creating a new C++ app (using the old arch uwp template) in canary.830, the top banner image isn't loaded.

![image](https://github.com/microsoft/react-native-windows/assets/10852185/187001c4-a7b7-4416-a7f0-d2e02c8050ab)

### Steps To Reproduce

1. Create a new app using RNW canary 830
2. Run the app

### Expected Results

The top banner image is loaded correctly

### CLI version

14.0.0-alpha.2

### Environment

```markdown
info Fetching system and libraries information...
System:
  OS: Windows 11 10.0.26100
  CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  Memory: 7.17 GB / 15.84 GB
Binaries:
  Node:
    version: 18.18.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.22
    path: C:\Program Files (x86)\Yarn\bin\yarn.CMD
  npm:
    version: 9.8.1
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Enabled
    AllowAllTrustedApps: Enabled
    Versions:
      - 10.0.19041.0
      - 10.0.22000.0
      - 10.0.22621.0
IDEs:
  Android Studio: Not Found
  Visual Studio:
    - 17.9.34902.65 (Visual Studio Enterprise 2022)
Languages:
  Java: Not Found
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.75.0-nightly-20240610-ced076210
    wanted: 0.75.0-nightly-20240610-ced076210
  react-native-windows:
    installed: 0.0.0-canary.830
    wanted: 0.0.0-canary.830
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Target Platform Version

10.0.22621

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

Debug

**Comment by chrisglein** [comment]
First step would be to look at recent changes to image and see if this break coincides with that timing and is related.
https://github.com/microsoft/react-native-windows/pull/13285

**Comment by sharath2727** [comment]
Followed the below instructions to repro, but could not repro the error:

npm show react-native-windows@0.0.0-canary.830 peerDependencies.react-native
npx --yes react-native@0.75.0-nightly-20240610-ced076210 init MyApp --template react-native@0.75.0-nightly-20240610-ced076210
yarn add react-native-windows@0.0.0-canary.830
npx --yes react-native-windows-init --overwrite --version 0.0.0-canary.830

![image](https://github.com/microsoft/react-native-windows/assets/10109130/ba62b605-16df-40ad-989d-134f1e5c667c)
