### ISSUE TITLE
Switch CI to use @react-native-community/cli

### ISSUE THREAD

**Issue by TatianaKapos** [microsoft/react-native-windows#13410]
### Summary

react-native init is being deprecated :(

![image](https://github.com/microsoft/react-native-windows/assets/42554868/813e7cb4-66dd-4519-b5f1-34bcc5eaeeb1)

### Motivation

Update our CI before it breaks

**Comment by chrisglein** [comment]
@jonthysell Any concerns here with your plans for init?
