### ISSUE TITLE
react-native-windows-init generates invalid namespace names in idl files when app has - in name

### ISSUE THREAD

**Issue by acoates-ms** [microsoft/react-native-windows#13426]
Hit this while starting from a default expo app, which is named: my-app.

**Comment by acoates-ms** [comment]
We should also look at making react-native-windows-init handle expo apps.  The steps are relatively minor:

Add a separate package.json script for `"start-windows": "react-native start"`  (Runs the normal non-expo bundler)

Add a devDependency for:  (Exact version to use will depend on RN version)
`"@react-native/metro-config": "0.74.85"`

Ensure the ComponentName in MainPage.xaml gets set to something (it ended up blank in my experiements)

Create a index.windows.tsx file at the root with something like (use same component name as used in MainPage.xaml:
```tsx
import React from 'react';
import {AppRegistry, Text, View} from 'react-native';
 
const App = () => {
    return (<View><Text style={{color:"red"}}>Hello world</Text></View>);
}
 
AppRegistry.registerComponent('MyApp', () => App);
```

**Comment by jonthysell** [comment]
react-native-windows-init is going to be deprecated - does it repro with `init-windows`?

**Comment by jonthysell** [comment]
Re-activating this as I think my PR will actually fix it.
