### ISSUE TITLE
Flyout no longer launches

### ISSUE THREAD

**Issue by TatianaKapos** [microsoft/react-native-windows#13475]
### Problem Description

Seen on both main and 0.75-branch, Flyout gives an error message when trying to launch.
![image](https://github.com/user-attachments/assets/2b3382c8-7162-4fd8-a685-f761469a4ba0)
![image](https://github.com/user-attachments/assets/baa98141-3c51-4db8-a40e-7b3a4c64e860)

### Steps To Reproduce

1. Run playground on main or the 0.75-stable branch
2. Open rntester and navigate to Flyout Page

### Expected Results

Flyout should launch

### CLI version

npx react-native -v

### Environment

```markdown
npx react-native info
```

### Target Platform Version

10.0.22621

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

Debug

**Comment by Yajur-Grover** [comment]
This is the issue tracking adding tests for launching a Flyout/Popup which would capture this scenario in the future: https://github.com/microsoft/react-native-windows/issues/11102.
