### ISSUE TITLE
Application crashes when reading directory existance 

### ISSUE THREAD

**Issue by anacardix** [microsoft/react-native-windows#13473]
### Problem Description

I'm developing an application that checks for the existence of Citrix at startup. Initially, I was reading a registry key to check for Citrix, and if it wasn't present, the application would crash. I changed the logic to check for the presence of a file on disk instead, but the application still crashes if the file doesn't exist.

Here is the relevant code:

```csharp
private static bool GetCitrixInstalled()
{
	try
	{
		string[] citrixDirectories = new string[]
		{
			@"C:\Program Files (x86)\Citrix",
			@"C:\Program Files\Citrix"
		};

		foreach (string directory in citrixDirectories)
		{
			if (Directory.Exists(directory))
			{
				return true;
			}
		}

		return false;
	}
	catch (Exception ex)
	{
		return false;
	}
}
```

This is the error displayed:

> Application name that caused the error: SIRConnector.exe, version: 1.0.0.0, timestamp: 0x666aaa94
> Module name that caused the error: ucrtbase.dll, version: 10.0.19041.3636, timestamp: 0x81cf5d89
> Exception code: 0xc0000409
> Error offset: 0x000000000007286e
> Process ID that caused the error: 0x204c
> Application start time that caused the error: 0x01dad135f9239a24
> Application path that caused the error: C:\Program Files\WindowsApps\SIRConnector_1.0.0.0_x64__kyfrjt9gd3t0w\SIRConnector.exe
> Module path that caused the error: C:\WINDOWS\System32\ucrtbase.dll
> Report ID: 25e6d215-06c8-445c-8764-4876f5567173
> Full package name that caused the error: SIRConnector_1.0.0.0_x64__kyfrjt9gd3t0w
> Application ID relative to the package that caused the error: App

Can someone help me figure out why the application is crashing and how to resolve this issue? Thank you!

### Steps To Reproduce

Start the application
Application checks for Citrix installation
Application crashes if Citrix is not installed

### CLI version

12.3.2

### Environment

```markdown
System:
  OS: Windows 10 10.0.19045
  CPU: (4) x64 Intel(R) Xeon(R) Gold 6238 CPU @ 2.10GHz
  Memory: 7.05 GB / 16.00 GB
Binaries:
  Node:
    version: 20.11.1
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.21
    path: ~\AppData\Roaming\npm\yarn.CMD
  npm:
    version: 10.4.0
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Enabled
    AllowAllTrustedApps: Enabled
    Versions:
      - 10.0.10586.0
      - 10.0.18362.0
      - 10.0.19041.0
      - 10.0.20348.0
      - 10.0.22621.0
IDEs:
  Android Studio: Not Found
  Visual Studio:
    - 17.10.35013.160 (Visual Studio Enterprise 2022)
Languages:
  Java: 11.0.20.1
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.4
    wanted: 0.73.4
  react-native-windows:
    installed: 0.73.5
    wanted: 0.73.5
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Community Modules

    "@react-native-async-storage/async-storage": "^1.23.1",
    "@tanstack/react-query": "^5.22.2",
    "axios": "^1.6.8",
    "lodash": "^4.17.21",
    "react": "18.2.0",
    "react-native": "0.73.4",
    "react-native-macos": "^0.73.15",
    "react-native-vector-icons": "^10.0.3",
    "react-native-webview": "13.8.1",
    "react-native-windows": "0.73.5"

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

Release

**Comment by chrisglein** [comment]
What permissions does your app have? By default a UWP app will not have access to the general file system, just the contents of your app's sandbox. More information here:
- https://microsoft.github.io/react-native-windows/docs/native-code#win32-desktop-apps-vs-rnw-apps
- https://learn.microsoft.com/en-us/windows/uwp/files/file-access-permissions
- You may even need to be full trust to do that: https://learn.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations

Hopefully those links are helpful, let us know if not.
