### ISSUE TITLE
How to creat an application for wpf?

### ISSUE THREAD

**Issue by jianguangyu** [Microsoft/react-native-windows#1349]
Hey,friends.
I have done things follow the tutorial but only create an application for uwp. Then I find a document here https://github.com/Microsoft/react-native-windows/tree/master/local-cli/rnpm/wpf, and I tried to create an app follow it but failed.
I was just wondering if anyone could tell me how to create an application for wpf since I really wanna create  one that can run on window 7.
Thanks!

**Comment by flyingxu** [comment]
Just in case some others are looking for the answer:

`npm install --save-dev rnpm-plugin-wpf`
`react-native wpf` or  `react-native wpf --windowsVersion 0.49.0-rc.2`
