### ISSUE TITLE
ComponentView::updateAccessibilityProps always return without triggering UpdateUiaProperty

### ISSUE THREAD

**Issue by sharath2727** [microsoft/react-native-windows#13525]
### Problem Description

m_uiaProvider is always null which results in updateAccessibilityProps always returning without raising UiaRaiseAutomationPropertyChangedEvent for accessible, accessibilityRole, accessibilityState props through UpdateUiaProperty 

### Steps To Reproduce

1. Launch playground-composition.sln
2. Update simple.tsx to show a switch:
<switch accessible={true} style={...}>
3. Add a breakpoint to notice updateAccessibilityProps being triggered but m_uiaproperty being null.

Even if accessible={false} doesn't change the behavior.

### Expected Results

UiaRaiseAutomationPropertyChangedEvent being triggered through UpdateUiaProperty for the properties: accessible, accessibilityRole, accessibilityState

### CLI version

14.0.0-alpha.2

### Environment

```markdown
info Fetching system and libraries information...
System:
  OS: Windows 11 10.0.26258
  CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
  Memory: 11.74 GB / 31.85 GB
Binaries:
  Node:
    version: 18.18.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.19
    path: C:\Program Files (x86)\Yarn\bin\yarn.CMD
  npm:
    version: 9.8.1
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Enabled
    AllowAllTrustedApps: Enabled
    Versions:
      - 10.0.17763.0
      - 10.0.18362.0
      - 10.0.19041.0
      - 10.0.22000.0
      - 10.0.22621.0
IDEs:
  Android Studio: Not Found
  Visual Studio:
    - 17.10.35027.167 (Visual Studio Enterprise 2022)
Languages:
  Java: Not Found
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Target Platform Version

10.0.22000

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

Debug

**Comment by acoates-ms** [comment]
I think this is by design.  We don't create the m_uiaProvider unless an accessibility tool requests it.  If we haven't created it, it means no-one is listening, so there is no need to raise property change events.
