### ISSUE TITLE
[0.75] [Web Debugging] Unable to fully debug a new 0.75 app

### ISSUE THREAD

**Issue by TatianaKapos** [microsoft/react-native-windows#13550]
### Problem Description
Web Debugging doesn't seem to work anymore on a 0.75 app. leaving customers to use Direct Debugging which is also not great (and we directed to use web debugging in 0.74).

Possibly related to https://github.com/facebook/metro/issues/731 

Web Debugging: 
Shows an empty app and gives the following error but will hit breakpoints before the app displays
![image](https://github.com/user-attachments/assets/cfafb4ce-bea1-4d42-a7df-111119da685c)

Direct Debugging:
Can set breakpoints but you need to reload the app and edge://inspect/ for breakpoints to hit and after while they stop working (seems to be in the same shape as 0.74)

Weirdly playground on 0.75 can use web debugging?

### Steps To Reproduce

1. Create a new 0.75 app
2. Try to Direct or Web Debug

### Expected Results

We should be able to debug something

**Comment by marlenecota** [comment]
@Yajur-Grover can you see if you get a repro, thanks.
