### ISSUE TITLE
React native: Unable to install metro, sdk or jdk

### ISSUE THREAD

**Issue by JulianHSC** [microsoft/react-native-windows#13588]
### Problem Description

I spent my time uninstalling android studio, java sdk, jdk and restarting my computer multiple times. I just removed and reinstalled the virtual device (emulator) and my metro has passed the checklist of npx react-native doctor. Is this the normal behaviour of react native? I hope this is the correct place for this problem.
![react native problem](https://github.com/user-attachments/assets/29cc12ff-364f-4c42-b2f1-2650944ff3fd)
![react native sdk problem](https://github.com/user-attachments/assets/440cf04c-ee19-40ec-9c5b-fdfbb0f0c0fa)

### Steps To Reproduce

npx react-native run-android
then you can see the screenshot.
![react native problem](https://github.com/user-attachments/assets/812f8bf1-3852-4651-82a8-c9c71acdfa00)
![react native sdk problem](https://github.com/user-attachments/assets/e0ef5e82-1d21-4b87-b938-9a5fb05feaca)

### Expected Results

It should run correctly in the android studio IDE.

### CLI version

npx @react-native-community/cli -v

### Environment

```markdown
npx @react-native-community/cli info
```

### Target Platform Version

10.0.15063

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

Release

**Comment by chiaramooney** [comment]
Looks like this issue is for Android. Please file an issue on the facebook/react-native repo instead.
