### ISSUE TITLE
Running `npx react-native init-windows` inside a project without `react-native-windows` installed gives unintuitive error messages

### ISSUE THREAD

**Issue by shirakaba** [microsoft/react-native-windows#13589]
### Problem Description

If you run `npx react-native init-windows` inside a project in which `react-native-windows` hasn't been installed yet, the error messages are unintuitive, not indicating you that `react-native-windows` needs to be installed first.

```sh
$ npx react-native@0.75.1 init-windows --help
Usage: cli [command] [options]

Options:
  -v                            Output the current version
  -h, --help                    display help for command

Commands:
  init [options] [projectName]  New app will be initialized in the directory of the same name. Android and iOS projects will use this name for publishing setup.
  doctor [options]              Diagnose and fix common Node.js, iOS, Android & React Native issues.
  help [command]                display help for command

$ npx react-native@latest init-windows
error: unknown command 'init-windows'
```

### Steps To Reproduce

Run `npx react-native@latest init-windows` inside a project that doesn't include `react-native-windows`.

### Expected Results

The error messages should indicate that `react-native-windows` needs to be installed for the command to work.

### CLI version

N/A

### Environment

N/A

### Target Platform Version

None

### Visual Studio Version

None

### Build Configuration

None

**Comment by shirakaba** [comment]
Actually, it seems `init-windows` isn't supported at all:

```sh
$ npx react-native@latest init-windows
error: unknown command 'init-windows'
```

The `@next` [docs](https://microsoft.github.io/react-native-windows/docs/next/init-windows-cli) suggest this is the correct way to invoke the command, however.

**Comment by chiaramooney** [comment]
@jonthysell Can you take a look at this? New init command may need an update.

**Comment by jonthysell** [comment]
This is not an issue that RNW can solve. You're running Meta's `react-native` package script, and it has no idea that `react-native-windows` provides an `init-windows` command unless `react-native-windows` is installed.

If you want something like this, I recommend making a request to the `@react-native-community\cli` package that their command provides better messaging when an unknown command identifier is given to their script. Furthermore, you *could* request them to identify the `init-windows` string and, if the command isn't present, message the user that they could install `react-native-windows` to get it, but that would be at their prerogative.
