### ISSUE TITLE
.net framework standard 2.0 

### ISSUE THREAD

**Issue by joeblew99** [Microsoft/react-native-windows#1361]
I have been using the new .net framework standard 2.0 

Since c' is used to make custom native components and native Ui components, then it seems plausible that we can create apps for OSX, and even android and ios using this architecture ?

**Comment by rozele** [comment]
@joeblew99 this is something we're very interested in, and I can certainly see using the C# React Native bridge with a Xamarin UIManager implementation for iOS and Android, or whatever-ui-framework for the UIManager for Linux / OSX. It's definitely something we're thinking about but not in the near term.

**Comment by joeblew99** [comment]
@rozele 
At the moment i use the c# code for android, ios and desktop frontends with a GRPC communications layer to services installed on the desktop and mobile. These proxy services have storage and also sync with the servers over grpc.

**Comment by joeblew99** [comment]
close this if you want !

**Comment by rozele** [comment]
Thanks @joeblew99! I'll re-open if we start looking into the .NET Standard library.
