### ISSUE TITLE
TextInput and clearButtonMode

### ISSUE THREAD

**Issue by sm2017** [microsoft/react-native-windows#1368]
It seems `clearButtonMode` of `TextInput` component is not implemented , I set to `'never'` but don't affected

**Comment by rozele** [comment]
@sm2017 unfortunately there is no API in UWP to disable the delete button. I'll leave this issue open.  There are some other tricks you can do to "disable" the delete button, but they would be app-specific. E.g., You could set `TextWrapping` to `Wrap` (in native code) and set the `MaxHeight` of the control if you didn't want it to span multiple lines.

**Comment by rozele** [comment]
See #1874
