### ISSUE TITLE
Can't compile a new project because nuget package is not updated to 0.75.2

### ISSUE THREAD

**Issue by tux2nicolae** [microsoft/react-native-windows#13688]
### Problem Description

We get the following error when trying to build a new project

`error NU1102: Unable to find package Microsoft.ReactNative with version (>= 0.75.2)`

### Steps To Reproduce

1. Init a new windows project
2. Try to run `npm run windows`

### CLI version

npx @react-native-community/cli -v

### Environment

```markdown
SDKs:
  Android SDK: Not Found
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Enabled
    Versions:
      - 10.0.19041.0
      - 10.0.22000.0
      - 10.0.22621.0
IDEs:
  Android Studio: AI-232.10300.40.2321.11668458
  Visual Studio:
    - 17.11.35219.272 (Visual Studio Professional 2022)
Languages:
  Java: 17.0.10
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.75.2
    wanted: 0.75.2
  react-native-windows:
    installed: 0.75.2
    wanted: ^0.75.2
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Target Platform Version

None

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

Debug

**Comment by chrisglein** [comment]
May just be a matter of bad timing. There were issues with our publish pipelines failing this week. We may need to re-run the pipeline to get the latest nugets. @jonthysell FYI. With that re-run this should it resolve itself when it completes.

**Comment by tux2nicolae** [comment]
The initial problem with nuget package was partially solved but we are still having some problems when compiling with 

```
    <UseExperimentalNuget>true</UseExperimentalNuget>
    <ReactExperimentalFeaturesSet>true</ReactExperimentalFeaturesSet>
```
    
The build log:
    
```
- Build failed with message 2:10>C:\Program Files\Microsoft Visual Studio\2022\Profession × Build failed with message 2:10>C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5321,5): error MSB3030: Could not copy the file "C:\Users\Nicu\.nuget\packages\microsoft.reactnative\0.75.2\runtimes\win10-x64\native\Microsoft.ReactNative\DevMenuControl.xbf" because it was not found.
```

**Comment by jonthysell** [comment]
Can you provide more details and/or a repro repo? Are you trying to build a library? An app?

**Comment by tux2nicolae** [comment]
When compiling an a native c++ turbo module

**Comment by jonthysell** [comment]
We're unable to repro this ourselves, can you please provide a repro in a stand-alone repo? There's no reason your build should require that file (that it's complaining about). Seeing what your code looks like (with the build files) would help.

**Comment by jonthysell** [comment]
I actually finally found a repro for this. I can only repro it by:

* Create a new RN library project with example app
* Add windows support
* Build the app as Debug x64

Then I get this error. Even on Fabric, where the xbf file shouldn't be necessary at all. VS seems to want it. If I build Debug x86 though, it works fine without the file. If l look at our CI, Debug x64 works absolutely fine as well. So I suspect it's a VS 2022 problem, as this code hasn't changed in 4 years and it's been fine the whole time for nuget consumers.

**Comment by jonthysell** [comment]
Hi @tux2nicolae.

I was able to repro your issue, then it went away after I upgraded to VS 2022 v17.11.5 and did a clean windows build.

I find the easiest way to do a clean build is to make sure all the windows stuff is commited to your git repo, and doing a git clean like `git clean -f -d -e node_modules/ -e *.pfx -e Package.StoreAssociation.xml -x`.

Can you confirm if that works for you?
