### ISSUE TITLE
Implement accessibilityActions property for View in Fabric

### ISSUE THREAD

**Issue by danielayala94** [microsoft/react-native-windows#13706]
Implement the accessibilityActions property for View in RNW Fabric. 

This property was available in RNW Paper via FrameworkElementViewManager.

For reference, check the public API documentation: https://reactnative.dev/docs/view#accessibilityactions

**Comment by chiaramooney** [comment]
Can close this issue. Infrastructure for accessibilityActions is in place for all core components. See https://github.com/microsoft/react-native-windows/issues/13316 for current list of supported actions. This list will grow over time as more accessibility behavior is implemented.
