### ISSUE TITLE
VS2015 Issues

### ISSUE THREAD

**Issue by jpshelley** [Microsoft/react-native-windows#1379]
### Environment
1. `react-native -v`: 0.48.x
2. `npm ls rnpm-plugin-windows`: 0.2.7
3. `npm ls react-native-windows`: 0.48.0-rc.x
4. `node -v`: 8.4.0
5. `npm -v`: 5.3.0

Then, specify:

- Target Platform: UWP

- Target Platform Version(s): 10.0.10586

- Target Device(s): Desktop

- Development Operating System: Windows 10

- Visual Studio Version: VS 2015

### Steps to Reproduce

After upgraded to react-native 0.48.x and react-native-windows 0.48.x Visual Studio 2015 no longer works for me. The ChakraBridge has some errors as well as other warnings about missing dll. It works for VS 2017.

(Write your steps here:)

1. react-native init AwesomeProject
2. open the solution in VS 2015
3. See the build errors

### Expected Behavior

the project builds and can run fine.

### Actual Behavior

![screenshot 1](https://user-images.githubusercontent.com/2798846/30459190-d120112e-9974-11e7-8aaf-445c6c46ab65.png)

### Reproducible Demo

`react-native init AwesomeProject` <-- that is it. Easier then cloning a project from github in my opinion.

**Comment by pulkitkkr** [comment]
I'm facing the same issue, any resolution ?

**Comment by jpshelley** [comment]
@pulkitkkr no I'm pretty sure VS 2015 just isn't supported above v0.48 I just won't be able to upgrade until we get a 2017 license.

**Comment by rozele** [comment]
VS 2015 is no longer being used for react-native-windows.
