### ISSUE TITLE
Unable to download JS bundle

### ISSUE THREAD

**Issue by jonathanhuang13** [Microsoft/react-native-windows#1387]
### Environment
1. `react-native -v`: 0.48.3
2. `npm ls rnpm-plugin-windows`: 0.2.7
3. `npm ls react-native-windows`: 0.48.0-rc.4
4. `node -v`: 8.3.0
5. `npm -v`: 5.3.0

- Target Platform: UWP
- Target Platform Version(s): 10.0.14393
- Target Device(s): Xbox
- Development Operating System: Windows
- Visual Studio Version: Visual Studio 2017

### Issue

I'm trying to access the development server on my Windows from my Xbox. I changed `DevServerHelper.cs` to the appropriate IP address and port (`x.x.x.x:8081`) and I know the two devices are on the same network. However, I'm still getting the "Unable to download JS Bundle" error. I started `react-native start` on my Windows Surface and I can access the IP address + port in my browser.

![cannotconnect](https://user-images.githubusercontent.com/6477471/30703981-18f6901e-9ea6-11e7-8262-f62acba9f470.png)

**Comment by rozele** [comment]
Can you access the service from the browser on your Xbox?

**Comment by jonathanhuang13** [comment]
Yes, I can access the service on Xbox's Edge. The interesting thing is that even if I type the appropriate IP address on my Surface and try to run the app locally, I get the same error. If I type `localhost:80811 or `127.0.0.1:8081` and deeply locally, it works as well.

**Comment by rozele** [comment]
@jonathanhuang13 please advise if this is still an issue on newer versions of react-native-windows.
