### ISSUE TITLE
[0.76] `NU1004: The package references have changed for native` with New Arch enabled

### ISSUE THREAD

**Issue by tido64** [microsoft/react-native-windows#13914]
### Problem Description

Building RNW with New Architecture enabled, I get this error:

` × Build failed with message 1>D:\react-native-test-app\node_modules\react-native-windows\Microsoft.ReactNative\Microsoft.ReactNative.vcxproj : error NU1004: The package references have changed for native. Lock file's package references: boost:[1.83.0, ), Microsoft.JavaScript.Hermes:[0.1.23, ), Microsoft.SourceLink.GitHub:[1.1.1, ), Microsoft.Windows.CppWinRT:[2.0.230706.1, ), Microsoft.WindowsAppSDK:[1.5.240227000, ), project's package references: boost:[1.83.0, ), Microsoft.JavaScript.Hermes:[0.1.23, ), Microsoft.Windows.CppWinRT:[2.0.230706.1, ), Microsoft.WindowsAppSDK:[1.5.240227000, ).The packages lock file is inconsistent with the project dependencies so restore can't be run in locked mode. Disable the RestoreLockedMode MSBuild property or pass an explicit --force-evaluate option to run restore to update the lock file. [D:\react-native-test-app\example\windows\Example.sln]. Check your build configuration.`

Where `Microsoft.SourceLink.GitHub` is no longer present. Removing `node_modules/react-native-windows/Microsoft.ReactNative/packages.fabric.lock.json` gets me further.

Looking in the npm package, I see `packages.fabric.lock.json` and `packages.lock.json` are present. Should they be included in the package?

### Steps To Reproduce

n/a

### CLI version

14.1.1

### Environment

```markdown
n/a
```

### Target Platform Version

10.0.22621

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

Debug

**Comment by jonthysell** [comment]
Two issues:

1. Yes, the lock files shouldn't be present in the npm package.
2. Building new arch against source out of this repo is not officially supported, please use the nugets as per the cpp-app template
