### ISSUE TITLE
NetworkingModule::sendRequest

### ISSUE THREAD

**Issue by sm2017** [Microsoft/react-native-windows#1391]
As both `XMLHttpRequest` and `fetch` is using `NetworkingModule::sendRequest` , so `sendRequest` is missed a feature 

The following codes
```js
fetch('https://mywebsite.com/endpoint/', {
  method: 'POST',
  body: new Uint8Array([1,2,3,4,5,6,7,8,9])
})
```

```js
var request = new XMLHttpRequest();
request.onreadystatechange = (e) => {
  if (request.readyState !== 4) {
    return;
  }

  if (request.status === 200) {
    console.log('success', request.responseText);
  } else {
    console.warn('error');
  }
};

request.open('GET', 'https://mywebsite.com/endpoint/');
request.send(new Uint8Array([1,2,3,4,5,6,7,8,9]));
```

is correct according to

https://github.com/facebook/react-native/blob/master/Libraries/Network/XMLHttpRequest.js#L508

https://github.com/Microsoft/react-native-windows/blob/97172a831bac620c4b5667792df552dfc02bd71e/Libraries/Network/RCTNetworking.windows.js#L55

Type of `data` is `RequestBody` and can be
```js
type RequestBody =
    string
  | FormData
  | {uri: string}
  | ArrayBuffer
  | $ArrayBufferView
;
```

according to 

https://github.com/facebook/react-native/blob/master/Libraries/Network/convertRequestBody.js#L35 

for my codes it is `{base64: binaryToBase64(body)}` that is not implemented in https://github.com/Microsoft/react-native-windows/blob/master/ReactWindows/ReactNative.Shared/Modules/Network/NetworkingModule.cs

Please add support for `{base64: binaryToBase64(body)}` data

**Comment by rozele** [comment]
Thanks @sm2017! Will look into it.
