### ISSUE TITLE
Kiosk Assigned Access Not Working

### ISSUE THREAD

**Issue by jayfar** [microsoft/react-native-windows#1393]
### Environment

1. `react-native -v`: 0.48.4
2. `npm ls rnpm-plugin-windows`: 0.2.7
3. `npm ls react-native-windows`: 0.48.0-rc.4
4. `node -v`: v7.4.0
5. `npm -v`: 4.0.5

- Target Platform: UWP
- Target Platform Version(s): 10.0.15063
- Target Device(s): Desktop
- Development Operating System: Windows
- Visual Studio Version: 2017

### Issue
I created a basic AwesomeProject react-native-windows UWP app, added the windows.aboveLockScreen Extension and setup this AwesomeProject app as an Assigned Access "Kiosk" app for a user. I get this error message when logging in with that user:

"We weren't able to start your app. Press Ctrl + Alt + Del to sign out or contact your system admin. For more info, search online for error code: 0x8027025a."

This error code means, "took too long to load", which does not seem too helpful. 

My exact steps were:

Added this to the Package.appxmanifest's Application section:

      <Extensions>
        <uap:Extension Category="windows.aboveLockScreen" />
      </Extensions>

Setup Assigned Access for a user as described here 
https://docs.microsoft.com/en-us/windows/configuration/set-up-a-kiosk-for-windows-10-for-desktop-editions#assigned-access-method-for-universal-windows-apps

Restarted as that user and after a bit of time, the above error message appears.
  
To confirm it is not a problem with my setup/PC, I created a very basic "Blank App (Universal Windows)" app in Visual Studio (no React Native) and I was able to set this app us as assigned access.	  

Has anyone else been able to get a react-native-windows app to run as an "Assigned Access" app?

The link below seems to have some Assigned Access best practices and trouble shooting tips. Before I dig in deeper just wondering if anybody already knows a reason why react-native-windows cannot be run as assigned access.

https://docs.microsoft.com/en-us/windows-hardware/drivers/partnerapps/create-a-kiosk-app-for-assigned-access

**Comment by stefanwuest** [comment]
@jayfar Have you been able to find a solution to this problem? I am facing the same issue.
The problem also exists with a blank app.

**Comment by jayfar** [comment]
Hi @stefanwuest   I never did figure it out and ended up using a react native WPF application and not a react native Windows (UWP) app. I used the old fashioned way of creating a Windows Kiosk by replacing Explorer.exe as the shell in the registry with my WPF react native app.

    Key: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Winlogon\Shell
    Type: REG_SZ
    Value: Explorer.exe (change this to a different default application)

Beware, the WPF version of react native has **a lot** of GUI quirks and many 3rd party GUI packages don't work well with it. Fortunately in my project, the GUI was pretty simple and I was able to work around the quirks.

It is strange even a blank UWP app (non react native) did not work for you. I was able to get a blank UWP single page app to run in Kiosk Mode, just not a blank one created by react native.

**Comment by stefanwuest** [comment]
@jayfar Thanks for your response! Just to clarify, I also tried a blank RN app, not a blank UWP app. So it seems to be a RN issue. Would be interesting to know what could actually cause the problem.

**Comment by ejoebstl** [comment]
What solved this issue for us was installing the app using `Add-ProvisionedAppPackage`. 

In an elevated powershell:
```
Add-ProvisionedAppPackage -Online -PackagePath bundle.msixbundle -SkipLicense
```

Furthermore, using the `windows.aboveLockScreen` extension caused a crash as well. We found that by basically bisecting all of our app code and settings.

**Comment by harinikmsft** [comment]
@ejoebstl - thanks for the update. Are you sufficiently unblocked at this time? It does seem strange that this occurs only within a RN environment. Adding @chrisglein , @kmelmon  to see if they have any ideas and if this will likely be an issue even in the vnext implementation.

**Comment by ejoebstl** [comment]
> Are you sufficiently unblocked at this time?
Yes, thank you. It would be good to have a way to debug such issues more easily. I guess that's a UWP issue though.

**Comment by matthewaptaylor** [comment]
I think this might be causing the issue. Any ideas?

```
Faulting application name: <AppName>.exe, version: 0.0.0.0, time stamp: 0x6886e168
Faulting module name: ucrtbase.dll, version: 10.0.26100.4652, time stamp: 0xbaffbd59
Exception code: 0xc0000409
Fault offset: 0x00000000000a4ace
Faulting process id: 0x5574
Faulting application start time: 0x1DBFF70374D7BD1
Faulting application path: C:\Program Files\WindowsApps\941ca622-9242-4aba-947d-9748e09ef62f_1.0.2.0_x64__vbrzzkxpq9pg8\<AppName>.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report Id: 75d45e2d-e4ba-4aab-a7db-3ec301ea25c8
Faulting package full name: 941ca622-9242-4aba-947d-9748e09ef62f_1.0.2.0_x64__vbrzzkxpq9pg8
Faulting package-relative application ID: App
```
