### ISSUE TITLE
Feature request : FlatList 

### ISSUE THREAD

**Issue by sm2017** [microsoft/react-native-windows#1394]
React native has an awesome `FlastList`  component , it is very useful

https://facebook.github.io/react-native/docs/flatlist.html

I am requesting `FlastList` implementation

**Comment by TomVanBoghout** [comment]
I implemented a `FlatList` on a UWP app. However the scrolling was not working. As a workaround I've put the flatlist in a `ScrollView`. Clearly this should not be the way to do this.

**Comment by whimsicaldreamer** [comment]
+1 Really need this implementation. :fingers_crossed:

**Comment by whimsicaldreamer** [comment]
+1 It would be great to have this implemented 👍 🤞

**Comment by erwan-lcs** [comment]
@TomVanBoghout do you have a code sample please? This workaround is not working for me:

```
        return (
            <ScrollView>
                <FlatList
                    refreshControl={
                        <RefreshControl
                            refreshing={this.state.refreshing}
                            onRefresh={this.onRefresh.bind(this)}
                        />
                    }
                    data={this.props.user_data.events}
                    renderItem={({ item }) => this.renderEventItem(item)}
                    keyExtractor={item => item.id}
                />
            </ScrollView>
        );
```
![No Scroll either View nor ScrollView](https://i.imgur.com/SYc1bCF.png)

**Comment by TomVanBoghout** [comment]
@erwan-lcs could you add the scrollview in a view itself, I believe that was necessary.
