### ISSUE TITLE
When Using New App Template (with ReactNativeAppBuilder) In-App Defined Native Modules Are Not Automatically Registered

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-windows#13946]
When working on my AI x RN sample app which uses the new app template for Fabric with ReactNativeAppBuilder, the code I used previously to defined a native module within my app's code no longer works. The module returns as null in my JS. When I switch my app back to the old app template the native module is registered and can be accessed from my JS.

Is it still expected behavior for app's using ReactNativeAppBuilder to have in-app defined native module be automatically registered? If so, it looks like there is a bug here. If not, we should document the change in behavior somewhere.

**Comment by jonthysell** [comment]
I think it's worse than that, I don't think any turbo modules from any external package providers are getting registered:

![Image](https://github.com/user-attachments/assets/fa60cd94-a513-465e-98d9-e3606f592b18)

**Comment by jonthysell** [comment]
I've figured it out - the new app template registers the package providers, which puts them into the host's instance settings, then, we set the instance settings, which replaces those providers.
