### ISSUE TITLE
View - Image - TouchableOpacity elements are not visible for UI inspect tools (Inspect.exe or AccScope etc.) and Automation drivers (WinAppDriver or appium etc.)

### ISSUE THREAD

**Issue by anumang** [Microsoft/react-native-windows#1396]
Environment

react-native -v:
react-native-cli: 2.0.1
react-native: 0.48.3
npm ls rnpm-plugin-windows:
rnpm-plugin-windows@0.2.7
npm ls react-native-windows:
react-native-windows@0.48.0-rc.4
node -v:
v6.11.3
npm -v:
3.10.10

Then, specify:

Target Platform: UWP
Target Platform Version(s):10.0.10586
Target Device(s):Desktop
Development Operating System:Windows 10
Visual Studio Version:2017
Steps to Reproduce

Run the following code

        <View style={{flex: 1}} testID={'menu_view'} accessibilityLabel={'menu_view'}>
           <TouchableOpacity
                testID={'menu_button'}
                accessibilityLabel={'menu_button'}
                onPress={() => {}}>
             <Image testID={'menu_icon'}  accessibilityLabel={'menu_icon'} source={Images.menu_icon} />
           </TouchableOpacity>
        </View>
Expected Behavior

If we inspect with UI inspector tools: Inspect.exe , AccScope, etc. , View, TouchableOpacity, Image elements should be visible so that we can use automation scripts with Automation drivers such as Appium - WinAppDriver

Actual Behavior

None of these elements are visible with inspector tool like Inspect.exe or AccScope, so UI test automation is not possible because of unreachable elements.

My Test Results

Non  Visible Elements with UI Inspect tools:
  - View
  - Image
  - Button
  - Touchable*

Visible Elements with UI Inspect tools
  - Text
  - TextInput
  - ScrollView

  Non-Visible elements are mapping to Decorator type elements such as Border - Canvas so they are not visible with UI inspect tools.

N/A

**Comment by atheeq** [comment]
facing the same issue. Any update on this?

**Comment by anumang** [comment]
By commit https://github.com/anumang/react-native-windows/commit/d1abf2114cb72f7a8f205d34e5440b03ae423a74 , we can solve on our local but it's not enough to PR.

**Comment by kevinvangelder** [comment]
You can find elements with automated tests by looking for the AccessibilityID (`testID` in JS).

**Comment by rozele** [comment]
@anumang please update if this is still an issue when using accessibility props like `testID`
