### ISSUE TITLE
Padding will not be set on TextInput component

### ISSUE THREAD

**Issue by furkee** [Microsoft/react-native-windows#1400]
Environment

react-native -v:
react-native-cli: 2.0.1
react-native: 0.48.3
npm ls rnpm-plugin-windows:
rnpm-plugin-windows@0.2.7
npm ls react-native-windows:
react-native-windows@0.48.0-rc.4
node -v:
v6.11.3
npm -v:
3.10.10

Then, specify:

Target Platform: UWP
Target Platform Version(s):10.0.10586
Target Device(s):Desktop
Development Operating System:Windows 10
Visual Studio Version:2017
Steps to Reproduce

Run the following code

    <TextInput
       style={{ padding: 25 }}
    />
Expected Behavior

Should apply padding inside text box

Actual Behavior

nothing changes

N/A

**Comment by sm2017** [comment]
I think related to https://github.com/Microsoft/react-native-windows/issues/1369
