### ISSUE TITLE
npx react-native run-windows

### ISSUE THREAD

**Issue by minesunny** [microsoft/react-native-windows#14012]
### Problem Description

![Image](https://github.com/user-attachments/assets/e59660d5-70ea-49a1-be20-968cd4a942cf)

### Steps To Reproduce

1. npx --yes @react-native-community/cli@next init <projectName> --version "latest"
2. cd <projectName>
3. yarn add react-native-windows@^0.75.0
4. npx react-native init-windows --overwrite
5. Set-ExecutionPolicy Unrestricted -Scope Process -Force;
iex (New-Object System.Net.WebClient).DownloadString('https://aka.ms/rnw-vs2022-deps.ps1');
6.npx react-native run-windows

### CLI version

npx @react-native-community/cli -v

### Environment

System:
  OS: Windows 11 10.0.22631
  CPU: (16) x64 AMD Ryzen 7 8845HS w/ Radeon 780M Graphics
  Memory: 48.40 GB / 59.79 GB
Binaries:
  Node:
    version: 20.18.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.22
    path: C:\Program Files (x86)\Yarn\bin\yarn.CMD
  npm:
    version: 10.8.2
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Enabled
    Versions:
      - 10.0.19041.0
      - 10.0.22621.0
IDEs:
  Android Studio: Not Found
  Visual Studio:
    - 17.11.35327.3 (Visual Studio Professional 2022)
Languages:
  Java: Not Found
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli":
    installed: 14.1.1
    wanted: ^14.1.1
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.75.4
    wanted: 0.75.4
  react-native-windows:
    installed: 0.75.0
    wanted: 0.75.0
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

### Target Platform Version

None

### Visual Studio Version

None

### Build Configuration

None

**Comment by chrisglein** [comment]
When you ran the dependency script (https://microsoft.github.io/react-native-windows/docs/rnw-dependencies) did it complete without errors? You can run it again now to validate. That should have enabled developer mode. The error showing here indicates that there was a problem entering developer mode.

**Comment by minesunny** [comment]
> When you ran the dependency script (https://microsoft.github.io/react-native-windows/docs/rnw-dependencies) did it complete without errors? You can run it again now to validate. That should have enabled developer mode. The error showing here indicates that there was a problem entering developer mode.

in step 5, I ran the script. but the problem seems that using pnpm command to install dependency, the some package's path is odd, tit;s path start with //?/, so I create a new project, and install dependency using yarn, it work fine.

**Comment by chrisglein** [comment]
> in step 5, I ran the script. but the problem seems that using pnpm command to install dependency

@minesunny Do you have the error message from the dependency script?

> so I create a new project, and install dependency using yarn, it work fine.

Works fine as in you don't see the error reported in this issue? Or works fine as yarn dependencies install fine (but unsure about general Windows dependencies)?

Can you provide the error log text for the error you saw above? The screenshot only gets us so far. A verbose build log may have more detail on the error you can copy over here.
