### ISSUE TITLE
Running Multiple Solutions via run-windows

### ISSUE THREAD

**Issue by jpshelley** [microsoft/react-native-windows#1402]
### Environment
1. `react-native -v`: 0.47.2
2. `npm ls rnpm-plugin-windows`: 0.2.7
3. `npm ls react-native-windows`: 0.47.0-rc.6
4. `node -v`: 8.4.0
5. `npm -v`: 5.3.0

Then, specify:

- Target Platform: UWP

- Target Platform Version(s): 10.0.10586

- Target Device(s): Desktop

- Development Operating System: Microsoft

- Visual Studio Version: VS 2015

### Steps to Reproduce

Our project has added a new solution for running tests in the native windows C# side of things. Via the buildSolution method --> https://github.com/Microsoft/react-native-windows/blob/16452c56a0e54cf28b33178d2175025129644924/local-cli/runWindows/utils/build.js#L34 it appears it gets the first solution from the list.

This means when we run `react-native run-windows` it picks up our tests instead of our application. My suggestion is to add a flag for solution to use.

(Write your steps here:)

1. react-native run-windows
2. Tests get run instead of the main application

### Expected Behavior

I expect the command to launch the main application or give me the option to specify the solution

### Actual Behavior

It ends up launching the tests solution instead. No way to target the correct one

### Reproducible Demo

Sadly I cannot create a demo but I hope the behavior is straightforward especially with the github link included.

**Comment by rozele** [comment]
Semi-related - https://github.com/Microsoft/react-native-windows/issues/520

**Comment by jpshelley** [comment]
@rozele is there anything I can do to help move this along? It seems that line I mentioned in the description would be a good place to look for resolving it and 520?
