### ISSUE TITLE
Support the Microsoft Fluent Design System

### ISSUE THREAD

**Issue by rigdern** [microsoft/react-native-windows#1404]
Here are the particular Fluent features I'm interested in:
  - [Acrylic](https://docs.microsoft.com/en-us/windows/uwp/style/acrylic)
  - [Connected Animations](https://docs.microsoft.com/en-us/windows/uwp/style/connected-animation)
  - [Reveal Highlight](https://docs.microsoft.com/en-us/windows/uwp/style/reveal)

**Comment by Losses** [comment]
Strongly agree.

**Comment by Losses** [comment]
@antonkh @rigdern @rozele Anyone still working on this? It's really important.

**Comment by rigdern** [comment]
@Losses I'm not aware of anybody that is currently working on this. You can see references to the [acrylic](https://github.com/Microsoft/react-native-windows/pull/1467) and [reveal highlight](https://github.com/antonkh/react-native-windows/pull/2) branches above. However, we set them aside to focus on higher priority work for our app and haven't gotten back to the Fluent work. If somebody from the community is sufficiently motivated, they could use those branches as a starting point for their own PRs and drive the acrylic and/or reveal highlight features to completion.

**Comment by Losses** [comment]
@chrisglein Hey, what happened to this issue? should I open a new issue about this?

**Comment by chrisglein** [comment]
> @chrisglein Hey, what happened to this issue? should I open a new issue about this?

@Losses A bulk close of stale issues opened against the vCurrent implementation (determined by label and age).
Some of this is already handled in vNext, like acrylic. Reveal should similarly happen for free on standard controls. As for connected animations... that's likely trickier. Rather than a multi-issue create a single proposal for that?
