### ISSUE TITLE
[Modal] Add feature for setting the X/Y pos of Modal on the screen

### ISSUE THREAD

**Issue by TatianaKapos** [microsoft/react-native-windows#14068]
### Summary

Currently Modal just open on the top-left of the users screen. Upstream's modal is defaulted to the middle of the application.

First step is to default our Modal to popup in the middle of the application.

### Motivation

Implementation of Modal

### Open Questions

Second step of this is to figure out if we want to add windows-specific properties to allow the Modal to pop/up anywhere on the screen (may be outside of the application boundaries which is not a use-case upstream has)

**Comment by chrisglein** [comment]
Some overlap with https://reactnative.dev/docs/modal#presentationstyle-ios, which is currently iOS only. That has some alignment options.

But as far as a default, centered would match expectation.

**Comment by TatianaKapos** [comment]
closing as not planned for Modal
