### ISSUE TITLE
Launch packager

### ISSUE THREAD

**Issue by sm2017** [Microsoft/react-native-windows#1407]
Today I update my react-native-windows to v0.48.0-rc.6

When I run `react-native run-windows` , It cannot launch packager , Why?

![image](https://user-images.githubusercontent.com/19644997/31175667-e50bd7ba-a91c-11e7-8b23-69c2764f1f81.png)

**Comment by rozele** [comment]
@sm2017 you must not have the correct react-native-windows version installed - v0.48.* has the updated path for `launchPackager.bat` (see [here](https://github.com/Microsoft/react-native-windows/blob/0.48-stable/local-cli/runWindows/utils/deploy.js#L126)). Prior to this commit - https://github.com/Microsoft/react-native-windows/commit/ededb4dcf4e2336317bdd124938450c46376a042 - the packager path was out of sync with `facebook/react-native`.
