### ISSUE TITLE
Microsoft.Windows.UI.Xaml.CSharp.targets was not found

### ISSUE THREAD

**Issue by sm2017** [Microsoft/react-native-windows#1408]
I update react-native-windows from 0.47.0-rc.5 to 0.48.0-rc.7
When I run `react-native run-windows` the following error is occurred

> C:\projects\app\windows\app\app.csproj(313,3): error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v11.0\Microsoft.Windows.UI.Xaml.CSharp.targets" was not found. 
> Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
> C:\projects\app\node_modules\react-native-windows\ReactWindows\ReactNative\ReactNative.csproj(214,3): error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v11.0\Microsoft.Wi
> ndows.UI.Xaml.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
> C:\projects\app\node_modules\react-native-windows\ReactWindows\ChakraBridge\ChakraBridge.vcxproj(41,3): error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.Cpp.
> Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
> C:\projects\app\node_modules\react-native-file-system\windows\RNFileSystem\RNFileSystem.csproj(176,3): error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v11.0\Microsoft.W
> indows.UI.Xaml.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
> Build failed with message Error: Command failed: "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild.exe" "C:/projects/app/windows/app.sln" /clp:NoSummary;NoItemAndPropertyList;Verbosity=quiet /nologo
> /p:Configuration=Debug /p:Platform=x86 /p:AppxBundle=Never. Check your build configuration.
> 

But from visual studio 2015 , I can run application

I see that I have `C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v14.0` folder not `C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v11.0`

In the app.csproj , I have

```
<PropertyGroup Condition=" '$(VisualStudioVersion)' == '' or '$(VisualStudioVersion)' &lt; '14.0' ">
    <VisualStudioVersion>14.0</VisualStudioVersion>
  </PropertyGroup>
```

and

```
<Import Project="$(MSBuildExtensionsPath)\Microsoft\WindowsXaml\v$(VisualStudioVersion)\Microsoft.Windows.UI.Xaml.CSharp.targets" />
```

**Comment by sm2017** [comment]
I try to create new project from zero

```
react-native init test
cd test
yarn add rnpm-plugin-windows --dev
react-native windows
```

I test it more than 10 time but I dont know why each time I have this error

``` react-native windows```

> Scanning folders for symlinks in C:\projects\test\node_modules (31ms)
> Reading application name from package.json...
> Reading react-native version from node_modules...
> Checking for react-native-windows version matching 0.49.*...
> C:\projects\test\node_modules\rnpm-plugin-windows\src\common.js:59
>         resolve(release.version)
>                        ^
> 
> TypeError: Cannot read property 'version' of undefined
>     at npm.packages.range (C:\projects\test\node_modules\rnpm-plugin-windows\src\common.js:59:24)
>     at releases (C:\projects\test\node_modules\npm-registry\endpoints\packages.js:182:5)
>     at each (C:\projects\test\node_modules\mana\index.js:314:7)
>     at Array.forEach (native)
>     at child.all (C:\projects\test\node_modules\mana\index.js:313:11)
>     at child.<anonymous> (C:\projects\test\node_modules\mana\index.js:620:13)
>     at finished (C:\projects\test\node_modules\assign\index.js:331:17)
>     at next (C:\projects\test\node_modules\assign\index.js:378:7)
>     at iterators (C:\projects\test\node_modules\assign\index.js:386:7)
>     at emits (C:\projects\test\node_modules\assign\index.js:243:14)

**Comment by sm2017** [comment]
As v0.49.0-rc.0 is released , I run the following command again

```
react-native init test
cd test
yarn add rnpm-plugin-windows --dev
react-native windows
react-native run-windows
```


### output

> $ react-native run-windows
> Scanning folders for symlinks in C:\Users\PC\Desktop\test\node_modules (31ms)
> Restoring NuGet packages
> Building C:/Users/SM/Desktop/test/windows/test.sln
> ERROR: The system was unable to find the specified registry key or value.
> ERROR: The system was unable to find the specified registry key or value.
> Found MSBuild v4.0 at C:\Windows\Microsoft.NET\Framework64\v4.0.30319\
> Building Solution: C:/Users/SM/Desktop/test/windows/test.sln
> Build configuration: Debug
> Build platform: x86
> Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
> C:\Users\PC\Desktop\test\windows\test.sln.metaproj : warning MSB4121: The project configuration for project "ReactNative.Shared" was not specified in the solution file for the solution configuration "Debug|x86". [C:\Users\PC\Desktop\test\windows\test.sln]
> C:\Users\PC\Desktop\test\windows\test\test.csproj(219,3): error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v11.0\Microsoft.Windows.UI.Xaml.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
> C:\Users\PC\Desktop\test\node_modules\react-native-windows\ReactWindows\ReactNative\ReactNative.csproj(215,3): error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v11.0\Microsoft.Windows.UI.Xaml.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
> C:\Users\PC\Desktop\test\node_modules\react-native-windows\ReactWindows\ChakraBridge\ChakraBridge.vcxproj(41,3): error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
> C:\Users\PC\Desktop\test\node_modules\react-native-windows\ReactWindows\ReactNativeWebViewBridge\ReactNativeWebViewBridge.csproj(99,3): error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v11.0\Microsoft.Windows.UI.Xaml.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
> Build failed with message Error: Command failed: "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild.exe" "C:/Users/SM/Desktop/test/windows/test.sln" /clp:NoSummary;NoItemAndPropertyList;Verbosity=quiet /nologo /p:Configuration=Debug /p:Platform=x86 /p:AppxBundle=Never. Check your build configuration.
>

**Comment by sm2017** [comment]
I install visual studio 2017 and test it again

```
react-native init AwesomeProject
cd AwesomeProject
yarn add rnpm-plugin-windows --dev
react-native windows
react-native run-windows
```


> Scanning folders for symlinks in C:\Users\PC\Desktop\AwesomeProject\node_modules (31ms)
> Restoring NuGet packages
> Building C:/Users/PC/Desktop/AwesomeProject/windows/AwesomeProject.sln
> ERROR: The system was unable to find the specified registry key or value.
> ERROR: The system was unable to find the specified registry key or value.
> Found MSBuild v4.0 at C:\Windows\Microsoft.NET\Framework64\v4.0.30319\
> Building Solution: C:/Users/PC/Desktop/AwesomeProject/windows/AwesomeProject.sln
> Build configuration: Debug
> Build platform: x86
> Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
> C:\Users\PC\Desktop\AwesomeProject\windows\AwesomeProject.sln.metaproj : warning MSB4121: The project configuration for project "ReactNative.Shared" was not specified in the solution file for the solution configuration "Debug
> |x86". [C:\Users\PC\Desktop\AwesomeProject\windows\AwesomeProject.sln]
> C:\Users\PC\Desktop\AwesomeProject\windows\AwesomeProject\AwesomeProject.csproj(219,3): error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v11.0\Microsoft.Windows.UI.Xaml.CSharp.targets"
>  was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
> C:\Users\PC\Desktop\AwesomeProject\node_modules\react-native-windows\ReactWindows\ReactNative\ReactNative.csproj(215,3): error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v11.0\Microsof
> t.Windows.UI.Xaml.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
> C:\Users\PC\Desktop\AwesomeProject\node_modules\react-native-windows\ReactWindows\ChakraBridge\ChakraBridge.vcxproj(41,3): error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.
> Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
> C:\Users\PC\Desktop\AwesomeProject\node_modules\react-native-windows\ReactWindows\ReactNativeWebViewBridge\ReactNativeWebViewBridge.csproj(99,3): error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft\W
> indowsXaml\v11.0\Microsoft.Windows.UI.Xaml.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
> Build failed with message Error: Command failed: "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild.exe" "C:/Users/PC/Desktop/AwesomeProject/windows/AwesomeProject.sln" /clp:NoSummary;NoItemAndPropertyList;Verbosity=quie
> t /nologo /p:Configuration=Debug /p:Platform=x86 /p:AppxBundle=Never. Check your build configuration.

From visual studio

![image](https://user-images.githubusercontent.com/19644997/31315528-529c564e-ac27-11e7-9912-7fe5187b71d8.png)

**Comment by rozele** [comment]
@sm2017 Not sure why it's pointing at  "C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\**v11.0**". The v11.0 seems suspicious.

**Comment by rozele** [comment]
@sm2017 The running from Visual Studio problem is because you don't have the correct project set as the startup project. You can change the startup project by right-clicking your app project and selecting "Set as Startup Project":
![vsexample](https://user-images.githubusercontent.com/1106239/31354985-7bcc51c4-ad06-11e7-81cf-f4c12b37d2f6.png)

**Comment by rozele** [comment]
Can you debug the process in node to find out why **v11.0** is being set by `run-windows`?

**Comment by sm2017** [comment]
"Set as Startup Project" , Works well 👍 

> Can you debug the process in node to find out why v11.0 is being set by run-windows?

@rozele How exactly? can you explain more? How can I do ?

**Comment by sm2017** [comment]
@rozele Can you please help me , How can I debug the process in node ?

**Comment by sm2017** [comment]
@rozele Help please to solve `v11.0` issue

**Comment by sm2017** [comment]
@rozele I still have this issue

**Comment by christophermohammed** [comment]
Has this been resolved?

**Comment by rozele** [comment]
@sm2017 please advise if this is still an issue.
