### ISSUE TITLE
Fabric e2etests fail locally and in certain PRs

### ISSUE THREAD

**Issue by TatianaKapos** [microsoft/react-native-windows#14193]
### Problem Description

When trying to run the fabric e2etests locally with these instructions: https://github.com/microsoft/react-native-windows/wiki/E2E-Testing-(Fabric) I get the following error :
![Image](https://github.com/user-attachments/assets/8fa92a8d-5264-4628-b9ac-18bf09e2d1bf)

and then on certain PRs in ADO they fails with

![Image](https://github.com/user-attachments/assets/a64027ed-ee16-443c-88bd-041acd990a1b)

I am still able to run the Paper e2etests locally which means I do have Webdriver set up correctly. I've tried on both my devbox and laptop. Not sure why Fabric fails but it means I can't debug these test for integrations

### Steps To Reproduce

1. Follow the steps here: https://github.com/microsoft/react-native-windows/wiki/E2E-Testing-(Fabric)
2. Run the tests

### Expected Results

They should run

**Comment by jonthysell** [comment]
I had no problem running the tests locally on my machine with the latest main, and all tests passed (when I set the display scaling to 100%).

**Comment by TatianaKapos** [comment]
closing! Updating wiki docs with correct instructions, thanks jon!
