### ISSUE TITLE
Move to a single index.js entry point 

### ISSUE THREAD

**Issue by whimsicaldreamer** [Microsoft/react-native-windows#1421]
React-native has moved the entry points for android and ios to a single `index.js` entry point. But using the extension for react-native-windows I am still getting `index.windows.js` in my project folder. Any views on it?

The changes to react-native are here: https://github.com/facebook/react-native/pull/15312

**Comment by rozele** [comment]
Thanks @whimsicaldreamer. I'll take a look at this.

**Comment by whimsicaldreamer** [comment]
Thanks for the speedy changes. How do I update my project to use the changes?

**Comment by rozele** [comment]
@whimsicaldreamer easiest way to do this would be to just trash your current react-native-windows project.
```
cd myapp
rd /s /q windows
del index.windows.js
```
And then re-run `react-native windows` to regenerate the project template. Unfortunately this means you'll have to re-link your native plugins if you've done any of that. We need to support something like react-native-git-upgrade better https://github.com/Microsoft/react-native-windows/issues/1358

**Comment by whimsicaldreamer** [comment]
Ok. Just a thought, `react-native windows-upgrade` sounds better. :)

**Comment by whimsicaldreamer** [comment]
@rozele, I re-ran `react-native windows` and it produced the single entry point perfectly but can we remove the `App.windows.js` file so that we can use the `App.js` file for all three platforms. Looking at the current `index.js`, it isn't importing `App.windows.js' but only `App.js`. Pardon me if my question is naive as I am new to react-native.

**Comment by jpshelley** [comment]
Should this issue be re-opened? I just created a fresh project and there is still a `App.windows.js` file along with a `App.js` file? I understand that is different from the index - but would it make sense to consolidate the App file too?
