### ISSUE TITLE
Exception when using ms-appdata uri with Image component.

### ISSUE THREAD

**Issue by opi-smccoole** [Microsoft/react-native-windows#1427]
### Environment

1. `react-native -v`: react-native: 0.48.4
2. `npm ls rnpm-plugin-windows`: rnpm-plugin-windows@0.2.7
3. `npm ls react-native-windows`: react-native-windows@0.48.0-rc.8
4. `node -v`: v8.4.0
5. `npm -v`: 5.3.0
6. `yarn --version`: not using yarn

- Target Platform: UWP

- Target Platform Version(s): 10.0.14393

- Target Device(s): Desktop, Surface Pro

- Development Operating System: Windows 10

- Visual Studio Version: 2017

### Steps to Reproduce

I'm using react-native-windows 0.48.0-rc.8 which uses version 0.0.6 of image-pipeline-windows and I am getting a cast exception when trying to display an image file with an ms-appdata URI.

(Write your steps here:)

1. Use ms-appdata uri as source for Image component.
2. Confirmed that image does exist at the specified uri location on the local file system.

### Expected Behavior

Image should display if image exists at specified URI.  

### Actual Behavior

Exception is thrown by the underlying image-pipeline-windows package.  The exception is:

System.InvalidCastException: 'Unable to cast object of type 'System.IO.DirectoryInfo' to type 'System.IO.FileInfo'.'

Submitted an issue at:

https://github.com/phongcao/image-pipeline-windows/issues/6

There is a pending PR that resolves the issue locally for me (tested by building the image-pipeline-windows package and manually copying the .dll files into my app's Debug directory) but the submitter is not sure if there are unwanted side effects.  It would also be very helpful if, once fixed, that there could be a 0.48 release that references it.  I'm not ready to handle the bundler breaking changes in 0.49 that force string-literal use in require() statements.

### Reproducible Demo

Github project that shows the error is available at:

https://github.com/objectpartners/LocalImageBugExample

**Comment by rozele** [comment]
cc @phongcao

**Comment by opi-smccoole** [comment]
@phongcao also just merged support for file URIs into image-pipeline-windows.  It'd be great to roll this update in when he releases the nuget package again.
