### ISSUE TITLE
Empty content in <Text> causes crash with marginVertical

### ISSUE THREAD

**Issue by lznt** [Microsoft/react-native-windows#1429]
### Environment

1. `react-native -v`: 0.48.4
2. `npm ls rnpm-plugin-windows`: 0.2.8
3. `npm ls react-native-windows`: 0.48.0-rc.6
4. `node -v`: 6.11.0
5. `npm -v`: 3.10.10

- Target Platform: UWP

- Target Platform Version(s): 10.0.10586

- Target Device(s): Mobile, Desktop

- Development Operating System: Windows 10 PRO

- Visual Studio Version: 2017

### Steps to Reproduce

(Write your steps here:)

1. Create text element and give it null as content
2. Add some marginVertical.
3. Crash in MeasureText because height is negative.

Probably not tied to only MarginVertical but it seems that Text elements go to negative height/width if they have margin and you dont submit them any content.

We had text element with props.exampleText, which was sometimes null, as API returned this. Caused crash which was rather pain in the ass to locate.

### Expected Behavior

I would expect the element to be insivible as it has no width or height determined and content is null or undefined, as iOS and Android behave.

### Reproducible Demo

```
<Text
    allowFontScaling={false}
    style={[styles.errorText]}>
{this.props.error}
</Text>
```

```
errorText: {
	color: colorSX,
	fontFamily: fontTitle,
	fontSize: sizeExtraSmall,
	textAlign: 'center',
	marginVertical: constants.marginSmall, <-- this causes crash when this.props.error is null.
	letterSpacing: 0.7,
},
```

In ReactTextShadowNode.cs on line 204:
private static YogaSize MeasureText(ReactTextShadowNode textNode, YogaNode node, float width, YogaMeasureMode widthMode, float height, YogaMeasureMode heightMode)

height is negative, and is not accepted, causing crash.

Hopefully this helps.

**Comment by rozele** [comment]
@lznt thanks! Looks like there might be a bug in Yoga that causes the measurement constraints to be negative (see https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/text/ReactTextShadowNode.java#L66). I'll add similar checks to make sure this exception doesn't occur.

**Comment by lznt** [comment]
Good find!

**Comment by rozele** [comment]
@lznt can you post a component with styles that reproduces this in isolation? I just did this:
```
class Playground extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.errorText}>{null}</Text>
      </View>
    );
  }
}
```
And filled in some values and can't repro.

**Comment by NunoMiguelVeloso** [comment]
Same problem where.

**Comment by lznt** [comment]
I am currently working on a different project but I checked the sourcecode and it seems we wrap the View in my example to another container, when errorText is null that has height: 0.

The problem still persists. On 0.43 React Native Windows, the error does not repro, but in 0.48 it does.

Could this help repro?

**Comment by matthargett** [comment]
@rozele any update on this? I don't think the checks from RN Android were ported over yet.

**Comment by rozele** [comment]
No repro.
