### ISSUE TITLE
Fetch issue

### ISSUE THREAD

**Issue by sm2017** [Microsoft/react-native-windows#1440]
### Environment

1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.49.3

2. `npm ls rnpm-plugin-windows`:
rnpm-plugin-windows@0.2.8

3. `npm ls react-native-windows`:
react-native-windows@0.49.0-rc.2

4. `node -v`:
v8.1.3

5. `npm -v`:
5.0.3

6. `yarn --version`:
1.2.0

Then, specify:

- Target Platform:
UWP

- Target Platform Version(s):
10.0.14393

- Target Device(s):
Desktop

- Development Operating System:
Windows 10

- Visual Studio Version:
 Visual Studio 2017 

### Steps to Reproduce

```js
fetch('https://facebook.github.io/react-native/movies.json')
        .then((response) => response.json())
        .then((responseJson) => {
          console.log('responseJson', responseJson);
        })
        .catch((error) => {
          console.log('error', error);
        });
```

### Expected Behavior

Fetch json and log it

### Actual Behavior

> TypeError: Failed to execute 'readAsText' on 'FileReader': parameter 1 is not of type 'Blob'.
>     at readBlobAsText (node_modules\whatwg-fetch\fetch.js:185)
>     at Response.Body.text (node_modules\whatwg-fetch\fetch.js:279)
>     at Response.Body.json (node_modules\whatwg-fetch\fetch.js:296)
>     at src\screens\SecondaryInitialScreen.js:31
>     at tryCallOne (node_modules\promise\setimmediate\core.js:37)
>     at node_modules\promise\setimmediate\core.js:123
>     at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:295
>     at _callTimer (node_modules\react-native\Libraries\Core\Timers\JSTimers.js:148)
>     at _callImmediatesPass (node_modules\react-native\Libraries\Core\Timers\JSTimers.js:196)
>     at Object.callImmediates (node_modules\react-native\Libraries\Core\Timers\JSTimers.js:464)

**Comment by rozele** [comment]
Thanks @sm2017 I think this is because react-native recently added the blob module. We'll have to add something similar. In the meantime, I think we can just add a Blob.windows.js implementation that throws an exception so whatwg-fetch doesn't assume it's available.

**Comment by rozele** [comment]
@sm2017 I actually can't reproduce this -
```
class Playground extends Component {

  componentWillMount() {
    fetch('https://facebook.github.io/react-native/movies.json')
      .then((response) => response.json())
      .then((responseJson) => {
        console.log('responseJson', responseJson);
      })
      .catch((error) => {
        console.log('error', error);
      });
  }

  render() {
    return (
      <View />
    );
  }
}
```
This does not throw any errors for me.

**Comment by sm2017** [comment]
@rozele , In my project I have error , But I cannot reproduce error when I create fresh project

I will try to reproduce error
