### ISSUE TITLE
Problem drawing with Win2D native module

### ISSUE THREAD

**Issue by JulienNoble** [Microsoft/react-native-windows#1442]
### Environment

1. `react-native -v`:
```
react-native-cli: 2.0.1
react-native: 0.49.3
```
2. `npm ls rnpm-plugin-windows`: `rnpm-plugin-windows@0.2.8`
3. `npm ls react-native-windows`: `react-native-windows@0.49.0-rc.2`
4. `node -v`: v6.9.4
5. `npm -v`: 3.10.10
6. `yarn --version`: 1.2.0

Then, specify:

- Target Platform: UWP
- Target Platform Version(s): 10.0.14393
- Target Device(s): Desktop (x86-x64)
- Development Operating System: Windows 10 Creators Update
- Visual Studio Version: 2017

### Steps to Reproduce

1. Launch RN app with a reference to Win2D `CanvasControl` native module
2. Check VS console to see the output

### Expected Behavior

It should show these 2 output lines in the VS console:

```
[Win2DImageView] Canvas Create Resources
[Win2DImageView] Canvas Draw
```

### Actual Behavior

The canvas create resources is called, but never the draw. The `Draw` event never seems to be called.

### Reproducible Demo

I've created a [sample project with instructions](https://github.com/JulienNoble/Win2DTest). It's the minimum setup with which I can reproduce this bug. This actually worked this morning, no update was done to the code, it just stopped working. I've checked if it's due to my computer's graphics card, but it's reproducible on other devices.

I've also created [an issue on the Win2D repo](https://github.com/Microsoft/Win2D/issues/567).

**Comment by rozele** [comment]
Thanks @JulienNoble I'm hoping the Win2D team will have more insight on this issue.

**Comment by rozele** [comment]
@JulienNoble I don't know if this is a bug in Yoga, but for some reason, you need to set explicit dimensions on the Win2D control.

**Comment by rozele** [comment]
@JulienNoble this is not a Yoga bug, you're not giving your app enough style guidance to know how wide the Win2D control should be, and Win2D optimizes the draw calls by not calling Draw on 0 width / height controls.  Do something like:
```
      <View style={styles.container}>
        <Win2dImageView style={{flex: 1, minWidth: 50}}/>
      </View>
```
