### ISSUE TITLE
Scroll Programmatically - FlatList - Not working

### ISSUE THREAD

**Issue by victorileaf** [Microsoft/react-native-windows#1446]
```

  <FlatList
                contentContainerStyle={styles.contentContainerStyle}
                ref={(c) => { this.flReadingView = c; }}
                horizontal
                scrollEnabled={true}
                removeClippedSubviews={false}
                onContentSizeChange={(width) => {
                    this.props.onContentSizeChange(width);
                }}
                keyExtractor={item => item}
                data={data}
                renderItem={({item}) => this.renderItem(item)}

            />
```

`        this.flReadingView.scrollToOffset({offset:value,animated: false});
`
This is working perfectly in ios and andoird but not in react native windows.

How to programmatically scroll a flatlist using slider ?

Is there any alternate methods available?
```

```

**Comment by chai41104** [comment]
Hi,
I have the same problem with ScrollToOffset in FlatList on react-native-windows.

Could someone explain briefly how the calculation works?

Best Wishes,

Thongchai
