### ISSUE TITLE
react-native-windows not working

### ISSUE THREAD

**Issue by CabuxaMapache** [Microsoft/react-native-windows#1456]
### Environment

1. `react-native -v`:0.49.3
2. `npm ls rnpm-plugin-windows`:-- rnpm-plugin-windows@0.2.8
3. `npm ls react-native-windows`:-- react-native-windows@0.49.0-rc.2
4. `node -v`:v7.8.0
5. `npm -v`:3.10.8
6. `yarn --version`:0.27.5

Then, specify:

- Target Platform:UWP

- Target Platform Version(s):10.0.14393

- Target Device(s):Desktop

- Development Operating System:Windows

- Visual Studio Version:Visual Studio 2017

### Steps to Reproduce

(Write your steps here:)

1. react-native init AwesomeProject
2. cd awe*
3. yarn add rnpm-plugin-windows --dev
4. react-native windows

### Expected Behavior

Configure project

### Actual Behavior

Could not find react-native-windows@0.49.*.

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by CabuxaMapache** [comment]
It seems like a proxy problem to access npm repository, sorry!

**Comment by CabuxaMapache** [comment]
Seems like a problem accessing repository, sorry!

**Comment by 378740021** [comment]
@CabuxaMapache  could you advise how to solve the issue, I am experienced on a similar problem Could not find react-native-windows@0.52.*.

**Comment by CabuxaMapache** [comment]
@378740021 For me the problem was related to the url of our npm repository. The url must end in "/" for some dependencies to work. To be more specific: the param "registry" in your ".npmrc" must end in "/".

**Comment by 378740021** [comment]
thanks for yourkindly help！it works！
