### ISSUE TITLE
Revert native modules queue to use LimitedConcurrencyTaskScheduler

### ISSUE THREAD

**Issue by rigdern** [Microsoft/react-native-windows#1466]
With the new implementation of the native modules queue, code that `awaits` introduces parallelism because the await's continuation can run on another thread in the thread pool. This means that developers of NativeModules need to think about thread-safety, locks, etc. if they`await`.

If we switch the native modules queue to an `IActionQueue` based on `new LimitedConcurrencyTaskScheduler(1)`, `await` will not introduce parallelism. Instead, the continuation will be queued to the `LimitedConcurrencyTaskScheduler` which has a max concurrency of 1. This results in a programming model similar to the experience of programming on the UI thread or in JavaScript.

**Comment by rigdern** [comment]
It looks like there's a `TaskScheduler` like `LimitedConcurrencyTaskScheduler` that is built into Windows. We can create a [`ConcurrentExclusiveSchedulerPair`](https://msdn.microsoft.com/en-us/library/system.threading.tasks.concurrentexclusiveschedulerpair(v=vs.110).aspx) and then use the `ExclusiveScheduler` that it exposes.

**Comment by rozele** [comment]
Does it work with Rx.NET or do you need to implement `IActionQueue` directly.

**Comment by rigdern** [comment]
@rozele I don't know. I never investigated why `LimitedConcurrencyTaskScheduler` hung when wrapping it with RX.NET and I haven't tried to do this with ` ConcurrentExclusiveSchedulerPair`.
