### ISSUE TITLE
Disable Potrait Orientaion for UWP React Native App

### ISSUE THREAD

**Issue by victorileaf** [Microsoft/react-native-windows#1469]
Hi,

How can i disable portrait mode for my UWP app in react-native-windows?
I have already selected 'Landscape' and 'Landscape-flipped'  in visual studio package manifest. But the app is changing its orientation when screen rotates. I need to disable portrait mode.

Any ways to fix this? Please help. Thanks in advance

**Comment by rozele** [comment]
What was the fix?

**Comment by victorileaf** [comment]
@rozele  I couldn't :(

**Comment by rozele** [comment]
Closing again due to inactivity. Seems like a general issue for UWP.
