### ISSUE TITLE
Background process for wpf app is never killed even after packaging server, wpf app, and command line processes are closed

### ISSUE THREAD

**Issue by lbochenek** [microsoft/react-native-windows#1470]
### Environment

1. `npm install --save-dev rnpm-plugin-windows`
2. `react-native wpf`

Then, specify:

- Target Platform: WPF

- Target Platform Version(s): ?

- Target Device(s): Desktop

- Development Operating System: Windows

- Visual Studio Version: VS 2017

### Steps to Reproduce

1. `react-native run-wpf`:
*wpf app spins up*
2. close wpf app
3. close packaging server
4. if process still running on commandline, ctrl+c the process

Will see a background process for the wpf app on task manager

### Expected Behavior

There shouldn't be a background process for the wpf app

### Actual Behavior

After closing wpf app, the task for that app transitions in the task manager from Apps to Background Processes.

Even after closing the packaging server and ctrl+c the process in commandline, the background process is still there

**Comment by rozele** [comment]
cc @pre10der89 @kevinvangelder, I imagine this is because some threads / dispatchers are not being destroyed properly.

**Comment by pre10der89** [comment]
@rozele Possible (https://github.com/Microsoft/react-native-windows/issues/1148)?

**Comment by piyush965** [comment]
@matthargett @rozele I am also facing the exactly same issue. The app process remain in Taskmanager even it is closed. Any workaround or plan to fix this issue?

**Comment by digitalinfinity** [comment]
The symbols are not correct in that screen shot. Can you capture a process dump and share that? You can use https://docs.microsoft.com/en-us/sysinternals/downloads/procdump to do this- run procdump -ma to capture all of the memory in the dump file.

**Comment by piyush965** [comment]
@digitalinfinity I created dump file but its quite huge around 250 MB. Is there any way to share that? This issue is easily reproducible on any RN WPF application.

**Comment by digitalinfinity** [comment]
Easiest is to probably just post it to OneDrive/Dropbox and share the link

**Comment by rozele** [comment]
The problem is with not calling `ReactPage.DisposeAsync` when the App exits. However, I recently tried to add this to Playground.Net46 and there seems to be a deadlock in the cleanup process. Still investigating.

**Comment by piyush965** [comment]
For now my workaround is to override onExit method and call Environment.Exit(0) to kill all opened threads and process.

**Comment by piyush965** [comment]
@rozele any luck on this?

**Comment by tdzl2003** [comment]
This is because `ShutdownMode` of application is default `OnLastWindowClose`, which close main thread too fast to shutdown react native thread.

on ReactInstanceManager.DetachViewFromInstanceAsync, last line

```
await rootViewRemovedTask;
```

will never continue executing.

Fix:

We can manually shutdown react native bridge gracefully after main window closed, then shutdown application explicitly.

In App.xaml: add `ShutdownMode="OnExplicitShutdown"` on <Application /> tag.

In App.xaml.cs:

```
 private void OnCreate(string[] arguments)
{
...
Application.Current.MainWindow = shellWindow;
// add this line: 
shellWindow.Closed += this.OnShellWindowClosed;
...
}

// Add this function:
private async void OnShellWindowClosed(object sender, EventArgs e)
{
    await _reactPage.DisposeAsync();
    Shutdown();
}
```

**Comment by tdzl2003** [comment]
Maybe it's better to provide a method 'Dispose()' which shutdown react native without waiting for it's completion.

**Comment by faxioman** [comment]
tdzl2003 proposed fix works for me

**Comment by pre10der89** [comment]
@tdzl2003 I'd be in favor of having a blocking Dispose option in addition to the DisposeAsync method specifically for the shutdown case. 

We use ShutdownMode.OnMainWindowClose and override the App.OnExit as follows

protected override async void OnExit(ExitEventArgs e)
{
    this.logger.Info("Application is disposing the react page...);");
     await this.reactPage.DisposeAsync().ConfigureAwait(true);
     this.logger.Info("Application has disposed the react page...");

     base.OnExit(e);
}

This does seem to shutdown all the react modules properly, but execution never seems reach the last two statements in the OnExit method shown above.   So we'll never see the "Application has disposed the react page". I tried to figure this out eons ago, but gave up. Didn't understand why execution didn't continued after the await...

**Comment by pre10der89** [comment]
@Reseul Any thoughts on this issue? I believe that the deadlock on WPF may be related to some work you did with Issue #1737. Note, that #1470 is over nine months old and may have been another cause (e.g. Not calling DisposeAsync), but now it seems to have transitioned into a deadlock as I describe above...

Any thoughts or help would be appreciated

**Comment by tdzl2003** [comment]
@pre10der89 I think the async context was lost. I break the program on Visual Studio, the main thread was exited already.

**Comment by reseul** [comment]
@pre10der89 I'll try to debug/take a look when I have a chance. I couldn't answer earlier since I was on vacation.
It's true that WPF Playground never exited for me, so whatever changes I made didn't make any difference.
I don't think I have any blocking on tasks in the code (if by that we mean <task>.Wait() ), but there could be some other issue. I'll debug.
