### ISSUE TITLE
Missing feature : BlobModule

### ISSUE THREAD

**Issue by sm2017** [microsoft/react-native-windows#1471]
### Environment

1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.49.5

2. `npm ls rnpm-plugin-windows`:
rnpm-plugin-windows@0.2.8

3. `npm ls react-native-windows`:
react-native-windows@0.49.0-rc.2

4. `node -v`:
v8.1.3

5. `npm -v`:
5.0.3

6. `yarn --version`:
1.2.0

Then, specify:

- Target Platform:
UWP

- Target Platform Version(s):
10.0.14393

- Target Device(s):
Desktop

- Development Operating System:
Windows 10

- Visual Studio Version:
 Visual Studio 2017 

### Steps to Reproduce

First see https://github.com/facebook/react-native/pull/16585

After fixing Blob issue , in windows I get new error

> TypeError: Cannot read property 'createFromParts' of undefined
>     at new Blob (node_modules\react-native\Libraries\Blob\Blob.js:99)

BlobModule is not implemented

### Expected Behavior

see https://github.com/facebook/react-native/pull/16585

### Actual Behavior

As BlobModule is not implemented . fetch API is missing arraybuffer function for response

**Comment by rozele** [comment]
@sm2017 I plan to help with this, but it looks like there's a coming change to the Blob module - https://github.com/facebook/react-native/pull/11573 - and I want to wait until that lands to make it work.  I understand that not having a `Blob` module blocks from a performance perspective, but is the missing feature actually causing exceptions? The framework should fallback to base64 blobs (which should work fine on react-native-windows) if the native BlobModule is missing. Can you confirm and provide a repro if any exceptions are thrown?

**Comment by sm2017** [comment]
Actually there is no exception in react-native-windows and in this line catch exception https://github.com/github/fetch/blob/master/fetch.js#L16 . But according to https://developer.mozilla.org/en-US/docs/Web/API/Response 

> 
> Response implements Body, so it also has the following methods available to it:
> 
> **Body.arrayBuffer()**
> Takes a Response stream and reads it to completion. It returns a promise that resolves with an ArrayBuffer.
> **Body.blob()**
> Takes a Response stream and reads it to completion. It returns a promise that resolves with a Blob.
> **Body.formData()**
> Takes a Response stream and reads it to completion. It returns a promise that resolves with a FormData object.
> **Body.json()**
> Takes a Response stream and reads it to completion. It returns a promise that resolves with the result of parsing the body text as JSON.
> **Body.text()**
> Takes a Response stream and reads it to completion. It returns a promise that resolves with a USVString (text).
> 

And according to https://github.com/github/fetch/blob/master/fetch.js#L240-L265 , here we just missing `Body.arrayBuffer()` and `Body.blob()` . and there is no alternative `base64` method
 
So if you use it `arrayBuffer` method we have `TypeError: undefined is not a function`

I will provide a repo asap

**Comment by rozele** [comment]
@sm2017 can you write up a simple component that repro's this so I can use it to see what we can do in the meantime until https://github.com/facebook/react-native/pull/11573 lands?

**Comment by sm2017** [comment]
Here is a simple component that repro's this

```js

import React, { Component } from 'react';
import {
  Text,
} from 'react-native';


export default class App extends Component {

  async componentDidMount() {
    const fetchResponse = await fetch('https://postman-echo.com/post', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/octet-stream',
      },
     body: new Uint8Array([1,2,3,4,5,6,7,8,9,0]),
    });

   const fetchResponseBody = await fetchResponse.arrayBuffer();
  }

  render() {
    return (
        <Text>
          Open console and see logs
        </Text>
    );
  }
}
```

If you see https://github.com/facebook/react-native/pull/16585/files I add a `=[]` to constructor , But for current component we have another new issue , Please see https://github.com/facebook/react-native/issues/16670

**Comment by sm2017** [comment]
@rozele What must we do?
