### ISSUE TITLE
Invoke JsSerializeScript in background

### ISSUE THREAD

**Issue by antonkh** [Microsoft/react-native-windows#1477]
Loading the JS bundle from a bytecode file makes the startup much faster. However on the 1st startup RNW spends quite a bit of time to generate the bytecode file. On a low end device like HP Stream 11 this takes 8-15s.

**Comment by rozele** [comment]
@antonkh I totally agree with this one and had made this request when the feature was initially implemented. I think we actually don't even need to use the same JavaScript thread to do the work, we can spin up a separate thread and separate JavaScriptRuntime object to do the serialization.

**Comment by rozele** [comment]
I think this was closed by #1560
