### ISSUE TITLE
Image Prefetch is slower than non-prefetched

### ISSUE THREAD

**Issue by rozele** [Microsoft/react-native-windows#1496]
### Environment

1. `react-native -v`: 0.50.*
2. `npm ls rnpm-plugin-windows`: n/a
3. `npm ls react-native-windows`: GH master
4. `node -v`: *
5. `npm -v`: *
6. `yarn --version`: n/a

Then, specify:

- Target Platform: UWP

- Target Platform Version(s): UWP *

- Target Device(s): Desktop

- Development Operating System: Windows

- Visual Studio Version: 2017

### Steps to Reproduce

(Write your steps here:)

1. Run RNTester
2. Navigate to Image Example
3. See preformance counters in 3rd example, pre-fetch is slower

### Expected Behavior

Prefetched images should load much faster than non-prefetched.

### Actual Behavior

Prefetched image loads much slower.
![prefetch](https://user-images.githubusercontent.com/1106239/32471233-4028cc62-c32a-11e7-97e9-989beec18cc4.png)

cc @phongcao

**Comment by phongcao** [comment]
Not sure if I can reproduce this issue on my side. Does it happen randomly? Btw, I've just made some changes so can you try again with this one?
https://github.com/phongcao/react-native-windows/tree/encoded-local-image

**Comment by rozele** [comment]
Thanks @phongcao, I can't reproduce now either. I think it was a one off due to poor performance on my machine in general.
