### ISSUE TITLE
Animations lagging when theres an Animated gif in the view.

### ISSUE THREAD

**Issue by KinanKazmi** [microsoft/react-native-windows#1515]
Windows 10 x64 15063

1. `react-native -v`: react-native-cli: 1.0.0 react-native: 0.50.3
2. `npm ls rnpm-plugin-windows`: rnpm-plugin-windows@0.2.8
3. `npm ls react-native-windows`: react-native-windows@0.50.0-rc.2
4. `node -v`: v8.9.0
5. `npm -v`: 5.5.1
6. `yarn --version`:

Then, specify:

UWP
- Target Platform: x86, x64

- Target Platform Version(s): 10.0.14393

- Target Device(s): Desktop

- Development Operating System: Windows 10 x64 15063

- Visual Studio Version: Visual Studio 2017

### Steps to Reproduce

1. Use this code
```
constructor(props) {
  super(props);
  this.ft = new Animated.Value(0);
}
componentDidMount() {
  this.animate(this.ft, 15000);
}	
animate(img, time) {
  img.setValue(0);
  Animated.timing(img, {toValue: 1, duration: time, easing: Easing.linear, useNativeDriver: true}).start(()=> this.animate(img, time));
}
render() {
const spin = this.ft.interpolate({
  inputRange: [0, 1],
  outputRange: ['0deg', '360deg']
})
return(
<View style={{flex:1}}>
<Image source={require('../assets/city.gif')} style={{position: 'absolute', width: screenWidth, height: screenHeight}/>
  <View pointerEvents={'none'} style = {{position: 'absolute'}}>
    <Animated.Image source={somePNGsource} style={{resizeMode: 'contain',
		alignSelf: 'center', width: 300, height: 300, transform:
      [{rotate: spin}]}]}/>
  </View>
</View>
}
```
### Expected Behavior

Smooth Animation. ( Like it was with the same code, on RN0.49.5 with RNW@0.49.0-rc.2 version)

### Actual Behavior

Animations play for about 1.5 sec then gets stuck for multiple seconds then play again and then lag and so on. Its like watching a 1080p video on a 256k modem connection.
UNLESS, you put your Animated.Image in a TouchableOpacity and keep it pressed/clicked/tapped while moving your finger/mouse. Its like constant inputs keeps it playing.
Without that, everything keeps laggnig UNTIL eventually, the gif stops playing and THEN the animation becomes smooth.
( btw my PNGs being animated are 2k+ in resolution and animated gifs are 50mb+ in size )

**Comment by kmelmon** [comment]
This issue is only relevant to the older legacy implementation of react-native-windows, which is no longer supported.
