### ISSUE TITLE
Unable to package for WPF using generated command.

### ISSUE THREAD

**Issue by JohnCIT** [Microsoft/react-native-windows#1519]
### Environment

1. `react-native -v`: 0.49.3
2. `npm ls rnpm-plugin-windows`:0.2.8
3. `npm ls react-native-windows`:0.49.0.-rc.2
4. `node -v`:6.11.3
5. `npm -v`:3.10.10

Then, specify:

- Target Platform: WPF

- Target Platform Version(s):.NET 4.6.1

- Target Device(s):Desktop

- Development Operating System:Windows 10/7

- Visual Studio Version:Visual Studio 2017

### Steps to Reproduce

(Write your steps here:)

1. Run react-native wpf
2. The generated command in react assets/index.wpf.bundle specifys use 
"react-native bundle --platform wpf"

### Expected Behavior

The bundle should be built correctly

### Actual Behavior

I get an error. Unrecognized platform wpf

**Comment by rozele** [comment]
@JohnCIT unfortunately due to limitations with the metro-bundler project, we can't create a "sub-platform" like WPF that shares code with UWP. Thus, both UWP and WPF use the `windows` platform moniker for the bundle command. cc @GantMan - are there any updates on the sub-platform work?

**Comment by GantMan** [comment]
It seems like advancements happen each day, but I haven't had a moment to step back and re-attack.   Might be a holidays hackathon project for me.  We'll see!

**Comment by Javis1205** [comment]
i try but it not working @rozele  can you help me
