### ISSUE TITLE
Use the same version of Yoga as the corresponding React Native release

### ISSUE THREAD

**Issue by rigdern** [Microsoft/react-native-windows#1522]
For a given release (e.g. 0.45.0), React Native Windows should use the same exact version of Yoga as React Native. This is important so that apps which are targeting multiple platforms (e.g. UWP, iOS, Android) will have identical layouts across platforms.

Adam Comella
Microsoft Corp.

**Comment by rozele** [comment]
Totally agree. It would be great if the Yoga team owned publishing the NuGet package. cc @axemclion any idea who we could reach out to about this?
