### ISSUE TITLE
'process' is undefined

### ISSUE THREAD

**Issue by ipy** [Microsoft/react-native-windows#1523]
### Environment

1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.50.3
2. `npm ls rnpm-plugin-windows`:
rnpm-plugin-windows@0.2.8
3. `npm ls react-native-windows`:
react-native-windows@0.50.0-rc.2
4. `node -v`:
v8.5.0
5. `npm -v`:
5.3.0
6. `yarn --version`:
1.3.2

Then, specify:

- Target Platform:
UWP

- Target Platform Version(s):
10.0.14393

- Target Device(s):
Desktop

- Development Operating System:
Windows

- Visual Studio Version:
Visual Studio 2017

### Steps to Reproduce

(Write your steps here:)

1. Create a new project: 
```
react-native init rnw 
cd rnw 
yarn add rnpm-plugin-windows --dev
react-native windows
```
2. Rename `index.js` to `registerApp.js`;
3. Create a new `index.js` with content `import './registerApp'`;
4. Run `react-native run-windows`

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

![image](https://user-images.githubusercontent.com/2088040/32897993-eafe95be-cb21-11e7-943c-1d1091bc9c0d.png)

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by rozele** [comment]
@ipy can you try upgrading to `metro-bundler@0.20.3`? I ran into this problem before and upgrading `metro-bundler` solved the issue.

**Comment by rozele** [comment]
Please re-open if there is still an issue after upgrading.

**Comment by ipy** [comment]
The issue occurs when I put `AppRegistry.registerComponent` in another file and `import` it from index.js. Solved by moving the  `AppRegistry.registerComponent` call back to index.js.
Still have no idea why it happens...

**Comment by rozele** [comment]
@ipy which version of `metro-bundler` are you using?

**Comment by rozele** [comment]
I'll re-open and re-investigate if you're using the latest `metro-bundler`.

**Comment by rozele** [comment]
@ipy - let me know if this is still an issue, I haven't seen this come up in a while.
