### ISSUE TITLE
document AppxManifest.xml error that happens when building from network drive

### ISSUE THREAD

**Issue by matthargett** [Microsoft/react-native-windows#1534]
### Environment

- Target Platform: UWP

- Target Platform Version(s): any

- Target Device(s): any

- Development Operating System: MacOS 10.12 host, Windows 10 Fall Creators Update guest.

- Visual Studio Version: VS 2017 15.4.3.

### Steps to Reproduce
1. try to build+run the UWP Playground or ReactNative.Tests projects for any build configuration or target platform

### Expected Behavior

Should build, deploy, and run UWP app.

### Actual Behavior

You get a deploy error saying the AppxManifest.xml could not be found. This is a documented issue when building UWP apps over a network share due to a weird necessity for the SYSTEM account to have full control of the build output directory during a UWP deploy and the Windows OS not being able to expose the same filesystem access over a network drive.

### Reproducible Demo

Steps are above. We just need to document the case in our common issues page. Here's a screenshot I took showing where to change the build output to a directory within the VM:
[
![rnw-appxmanifestxml-error-workaround](https://user-images.githubusercontent.com/1550766/32969559-6ffd6948-cb9a-11e7-9fa3-12cc461b0708.PNG)
](url)

**Comment by tpsands** [comment]
I'll second this issue. I work on a Mac using Parallels. I map the Mac drive into Windows and keep all files there. When I try to debug, it builds the app fine but can't then register and run the app.

**Comment by rozele** [comment]
Closing this for now, I've run into a variety of issues when working from a network drive. The recommended solution is to re-clone to the Windows machine.

**Comment by tpsands** [comment]
Another solution (instead of just re-cloning to the Windows machine) is to change the path for build output to an absolute path on the Windows machine instead of a relative path to the solution on the network drive. This has worked for me.
