### ISSUE TITLE
document error/workaround when a program (like McAfee) is occupying port 8081

### ISSUE THREAD

**Issue by matthargett** [Microsoft/react-native-windows#1538]
This has come up in the Reactiflux channel, on StackOverflow, and on my project. I thought we had documented it in the Troubleshooting document, but I was wrong.

```“The development server returned response error code: 403 Forbidden” in red screen. ```

**Comment by rozele** [comment]
Seems like a general issue for react-native development (i.e., this would be a problem for Android development on Windows). Closing.
