### ISSUE TITLE
How to create a wpf project?

### ISSUE THREAD

**Issue by wyshmily** [Microsoft/react-native-windows#1539]
Seems that the document mentioned wpf, but no words on how to target wpf.

**Comment by lunfardo** [comment]
did you make it work? I'm with the same problem, starting to think it's not posible with sdk 10 :/

**Comment by lunfardo** [comment]
npm install --save-dev rnpm-plugin-wpf
react-native wpf
react-native start -----> to start the server
react-native run-wpf --> in my case, this didnt work. Had to build from visual studio and run it. If you have the same problem, you can do this too by opening the file "Project Directory/wpf/yourproject.sln" and build (the wpf folder is made after running react-native wpf)

**Comment by ncomo11** [comment]
>react-native init samplewpfapp
npm install --save-dev rnpm-plugin-windows
npm install --save-dev rnpm-plugin-wpf
react-native wpf /* creates wpf VS project*/
react-native run-wpf 

For me run-wpf doesn't work so manually 
1. react-native start  /* to start the server */
2. Build & Run samplewpfapp.sln in visual studio

**Comment by rozele** [comment]
@ncomo11's suggestion looks right.
