### ISSUE TITLE
The remote procedure call failed.

### ISSUE THREAD

**Issue by ravirupareliya** [Microsoft/react-native-windows#1540]
After following all the steps when i try `react-native run-windows` it gives me following error.

    Exception calling "ActivateApplication" with "4" argument(s): "The remote procedure call failed. (Exception from
    HRESULT: 0x800706BE)"
    At <path>\node_modules\react-native-windows\local-cli\runWindows\utils\WindowsStoreAppUtil
    s.ps1:168 char:5
    +     $appActivator.ActivateApplication($applicationUserModelId,$args,[ ...
    +   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : COMException

**Comment by jurcello** [comment]
I have exactly the same problem. I downloaded the newest version of visual studio. Could that be the problem?

**Comment by jurcello** [comment]
I solved the problem by installing the latest version of windows 10. What version do of windows do you run now?

**Comment by rozele** [comment]
@ravirupareliya can you confirm if this is still an issue and re-open, filling out the template with version info, etc.?

**Comment by jdgalani** [comment]
I also have exactly the same problem. Does anyone found correct solution ?
