### ISSUE TITLE
Unable to call AWS from js due to an issue with 'authorization' header containing invalid format

### ISSUE THREAD

**Issue by prajithkb** [Microsoft/react-native-windows#1542]
https://github.com/Microsoft/react-native-windows/blob/4483d33ab2283abda24e981de22733f1627bfff8/ReactWindows/ReactNative.Shared/Modules/Network/NetworkingModule.cs#L469.

The Method checks for the format of the the authorization header and it is invalid, But unfortunately that is the format for calling AWS, 

According to https://stackoverflow.com/questions/19039450/adding-authorization-to-the-headers/24575721#24575721 If you change the method from Add() -> TryAddWithoutValidation() it works, I am wondering if this is something you can fix?

**Comment by rozele** [comment]
@prajithkb can you post a sample header that we can use as a regression test?

**Comment by ongk** [comment]
I'm also seeing an invalid HTTP headers error when using a SAS token in the Authorization header. The SAS token is generated by following this tutorial: https://docs.microsoft.com/en-us/rest/api/eventhub/generate-sas-token

Here is an example format for Authorization header:
SharedAccessSignature sr=someresourceuri&sig=XXXX&se=12344&skn=somekeyname

**Comment by rozele** [comment]
Closed by #2041
