### ISSUE TITLE
Background task scenarios don't work on Windows 10 Anniversary Update

### ISSUE THREAD

**Issue by rigdern** [Microsoft/react-native-windows#1548]
When the app is launched into the background from the terminated state, the background task scenarios only appear to work on the Windows 10 Fall Creators Update. My app needs them to work starting with the Windows 10 Anniversary Update.

The problem is that the UI thread's `SynchronizationContext` isn't properly setup when the app is launched from the terminated state into the background. One solution to explore is for the app to initialize the UI thread's `SynchronizationContext` in this case since Windows isn't doing it.

@rozele and I chatted in #1589. The right solution is probably for the app to initialize the dispatcher's `SynchronizationContext` when it is launched directly into the background. Here's a prototype: https://github.com/rozele/react-native-windows/commit/716f0a3d023bc0e28e2601d870366220b9d66182.

**Comment by rozele** [comment]
@rigdern - what version of Microsoft.UWP.NETCore do you need to use?

**Comment by rozele** [comment]
@rigdern can this be closed?

**Comment by rigdern** [comment]
@rozele

@reseul wired this up in our app. I asked him to share the pattern we used with you. I think it should be documented. We should also document the `SynchronizationContext` workaround.

**Comment by rozele** [comment]
@rigdern please document in this issue. Closing for now.
