### ISSUE TITLE
After updating Visual studio to version 15.5.2 existing react-native-windows .sln does not load. 

### ISSUE THREAD

**Issue by rajnishc8** [Microsoft/react-native-windows#1554]
### Environment

1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.51.0

2. `npm ls rnpm-plugin-windows`:
-- rnpm-plugin-windows@0.2.8

3. `npm ls react-native-windows`:
-- react-native-windows@0.50.0-rc.2

4. `node -v`:
v6.11.2

5. `npm -v`:
3.10.10

6. `yarn --version`:
1.3.2

- Target Platform: UWP

- Target Platform Version(s): 10.0.14393

- Target Device(s): Desktop

- Development Operating System: Windows

- Visual Studio Version:

### Steps to Reproduce

1. Open *.sln from windows folder.
2.
3.

### Expected Behavior
Solution should load all 5 project successfully.

### Actual Behavior
ChakraBridge and ReactNative.Shared did not load properly.
Reload of the ChakraBridge and ReactNative.Shared also errors out.

### Reproducible Demo
Try loading .sln of existing react-native-windows project after today's update of Visual stution to 15.2.2

Some error logs:
**********************************************************************************************************
Unsupported
This version of Visual Studio is unable to open the following projects. The project types may not be installed or this version of Visual Studio may not support them. 
For more information on enabling these project types or otherwise migrating your assets, please see the details in the "Migration Report" displayed after clicking OK.
	 - ReactNative.Shared, "C:\proj\reactJs\w1App\node_modules\react-native-windows\ReactWindows\ReactNative.Shared\ReactNative.Shared.shproj"

Non-functional changes required
Visual Studio will automatically make non-functional changes to the following projects in order to enable them to open in Visual Studio 2015, Visual Studio 2013, Visual Studio 2012, and Visual Studio 2010 SP1. Project behavior will not be impacted.
	 - w1App, "C:\proj\reactJs\w1App\windows\w1App.sln"
**************************************************************************************************************

Thanks,
--Rajnish

**Comment by rozele** [comment]
@rajnishc8 - I just upgraded to VS 2017 15.5.2 and I'm not able to reproduce the issue loading the solution in Visual Studio. I am, however, having issues executing `react-native run-windows`.
