### ISSUE TITLE
Unable to create react-native-windows app after update of visual studio 2017

### ISSUE THREAD

**Issue by rajnishc8** [Microsoft/react-native-windows#1555]
### Environment

1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.51.0

2. `npm ls rnpm-plugin-windows`:
-- rnpm-plugin-windows@0.2.8

3. `npm ls react-native-windows`:
-- react-native-windows@0.50.0-rc.2

4. `node -v`:
v6.11.2

5. `npm -v`:
3.10.10

6. `yarn --version`:
1.3.2

- Development Operating System: Windows

- Visual Studio Version: Visual Studio 2017 version 15.2.2

### Steps to Reproduce

1. react-native init w1pp
2. cd w1pp
3. npm install --save-dev rnpm-plugin-windows
4. npm install react-native@0.50
5. react-native windows
6. npm install
7. react-native run-windows
8. Error

### Expected Behavior
w1App should build and load and run on windows 10. 

### Actual Behavior
react-native run-windows gives error. Please see the error log below:
**********************************************************************************8
c:\proj\w1pp>react-native run-windows
Scanning folders for symlinks in C:\proj\w1pp\node_modules (41ms)
Restoring NuGet packages
Building C:/proj/w1pp/windows/w1pp.sln
Found MSBuild v15.0 at C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin
Building Solution: C:/proj/w1pp/windows/w1pp.sln
Build configuration: Debug
Build platform: x86
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\WindowsXaml\v15.0\8.2\Microsoft.Windows
.UI.Xaml.Common.targets(266,5): error MSB4062: The "Microsoft.Windows.UI.Xaml.Build.Tasks.CompileXaml" task could not b
e loaded from the assembly C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\WindowsXaml\
v15.0\8.2\Microsoft.Windows.UI.Xaml.Build.Tasks.dll. Could not load file or assembly 'file:///C:\Program Files (x86)\Mi
crosoft Visual Studio\2017\Community\MSBuild\Microsoft\WindowsXaml\v15.0\8.2\Microsoft.Windows.UI.Xaml.Build.Tasks.dll'
 or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is cor
rect, that the assembly and all its dependencies are available, and that the task contains a public class that implemen
ts Microsoft.Build.Framework.ITask. [C:\proj\reactJs\w1pptest\node_modules\react-native-windows\ReactWindows\ReactNativ
e\ReactNative.csproj]
Build failed with message Error: Command failed: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\msbuild.exe" "C:/proj/w1pp/windows/w1pp.sln" /clp:NoSummary;NoItemAndPropertyList;Verbosity=quiet /nologo /p:Configuration=Debug /p:Platform=x86 /p:AppxBundle=Never /p:PlatformToolset=v141 /p:VisualStudioVersion=15.0. Check your build configuration.
***********************************************************************************************************

Thanks,
--Rajnish
Note: This started happening today(12/18/2017)  from the time I updated Visual Studio 2017. Before the update of Visual Studion 2017. It used to successfully create project and load and run it on windows 10 laptop.

**Comment by rozele** [comment]
I can't repro this - I was able to successfully run an app with the latest VS 2017 and the 0.51.0-rc.0 release (15.4.3), can you update VS again, install 0.51.0-rc.0 and check again?

**Comment by rozele** [comment]
I was able to repro this - investigating.

**Comment by rozele** [comment]
I haven't seen this issue lately and I'm on Visual Studio 15.5.6. Closing.
