### ISSUE TITLE
Setting importantForAccessibility and accessibilityTraits on a view does not notify UI Automation infrastructure about the change.

### ISSUE THREAD

**Issue by zholobov** [microsoft/react-native-windows#1562]
### Environment

1. `react-native -v`: react-native-cli: 2.0.1; react-native: 0.46.4
2. `npm ls rnpm-plugin-windows`: rnpm-plugin-windows@0.2.0
3. `npm ls react-native-windows`: (empty)
4. `node -v`: v8.6.0
5. `npm -v`: 5.5.1
6. `yarn --version`: 1.2.0

Then, specify:

- Target Platform: UWP

- Target Platform Version(s): 10.0.14393

- Target Device(s): Desktop

- Development Operating System: Windows

- Visual Studio Version: 2017

### Steps to Reproduce

(Write your steps here:)

1. Create a react-native-windows app with  timer and a view with subviews. 
2. Make the view have importantForAccessibility=No and its subviews importantForAccessibilty=Yes.
3. Make the timer fire 10 seconds after app is started and when fired toggle view's importantForAccessibility between No and Yes.
4. Run Narrator.
5. Run app.
6. Before 10 seconds from start expire put narration focus on a subview.
7. Wait for 10 seconds from app start to expire, so that timer fires and changes importantForAccessibility of view to Yes.

### Expected Behavior

Narrator focus on the subview is lost since the subview is no longer in the tree - only view is.

### Actual Behavior

Narrator does not see any change. This is due to change to importantForAccessibility and accessibilityTraits properties on a view not firing proper events to Windows UI Automation as described in UIA specs.

### Reproducible Demo

n/a

**Comment by rozele** [comment]
@zholobov is this still an issue?

**Comment by zholobov** [comment]
@rozele yes it is. But it seems like not a common scenario. So maybe it can be a low-priority issue?
