### ISSUE TITLE
track performance-improving changes from Android

### ISSUE THREAD

**Issue by matthargett** [Microsoft/react-native-windows#1566]
RN Android added a CallSerializableNativeHook and SetFlushQueueImmediate on their JavaScriptExecutor equivalent:
https://github.com/facebook/react-native/search?utf8=%E2%9C%93&q=callSerializableNativeHook&type=
https://github.com/facebook/react-native/search?utf8=%E2%9C%93&q=flushQueueImmediate&type=

We should add these methods to stay in sync with upstream and give users who write RNW modules the same optimization opportunities.

**Comment by rozele** [comment]
Should bundle deltas belong here (https://github.com/facebook/react-native/commit/231c7a03043b9fb3c4bf81251ad099bab0ba05c2) or is this strictly app performance (and not dev experience performance)?

**Comment by matthargett** [comment]
Strictly app performance, let's create a separate PR for the bundle deltas.

**Comment by rozele** [comment]
I think both of these are fixed now.
