### ISSUE TITLE
Add keyboard focus related properties to PasswordBoxWindows

### ISSUE THREAD

**Issue by reseul** [Microsoft/react-native-windows#1569]
Current implementation of TextInput renders PasswordBoxWindows when secureTextEntry property is true.
The properties added by https://github.com/Microsoft/react-native-windows/pull/1546 (tabIndex, etc.) are not carried over to PasswordBoxWindows since I first had one clarifying question (@rozele ):
What's the reason for PasswordBoxWindows to exist, compared to TextInput? Why a different control? It seems to have same preoperties (including "ios", etc.), though I didn't do a thorough check.

Need some advice on how to proceed.

**Comment by rozele** [comment]
@reseul - we need the separate component because UWP TextBox does not support secure text entry.

**Comment by rozele** [comment]
#1663 should cover this.
