### ISSUE TITLE
react-native link: Error: ENOENT: no such file or directory, open <path>\MainPage.cs

### ISSUE THREAD

**Issue by non-standard** [Microsoft/react-native-windows#1578]
### Environment

1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.50.0

2. `npm ls rnpm-plugin-windows`:
`-- rnpm-plugin-windows@0.2.8

3. `npm ls react-native-windows`:
`-- react-native-windows@0.50.0

4. `node -v`:
v6.11.4

5. `npm -v`:
5.6.0

6. `yarn --version`:

- Target Platform: 
UWP

- Target Platform Version(s): 
10.0.14393

- Target Device(s): 
Desktop

- Development Operating System: 
Windows

- Visual Studio Version:  
Visual Studio 2017

### Steps to Reproduce

(Write your steps here:)

1. npm install --save react-native-video
2. react-native link

### Expected Behavior
rnpm-install info Linking react-native-video android dependency
rnpm-install info Android module react-native-video has been successfully linked
rnpm-install info Linking react-native-video ios dependency
rnpm-install info iOS module react-native-video has been successfully linked
rnpm-install info Linking react-native-video windows dependency
rnpm-install info Windows module react-native-video has been successfully linked

### Actual Behavior
`rnpm-install info Linking react-native-video android dependency
`rnpm-install info Android module react-native-video has been successfully linked
`rnpm-install info Linking react-native-video ios dependency
`rnpm-install info iOS module react-native-video has been successfully linked
`rnpm-install ERR! Something went wrong while linking. Error: ENOENT: no such file or directory, open '<project path>\windows\<project_name>\MainPage.cs'
Please file an issue here: https://github.com/facebook/react-native/issues

### Reproducible Demo

package.json dependencies section should do it:

"dependencies": {
    "react": "16.0.0",
    "react-native": "0.50.0",
    "react-native-video": "^2.0.0",
    "react-native-windows": "^0.50.0"
}

**Comment by rozele** [comment]
This will be resolved once https://github.com/facebook/react-native/pull/17745 is merged and cherry-picked onto v0.50, v0.51, and v0.52. We'll also have to cherry-pick #1601 to react-native-windows versions.

**Comment by rozele** [comment]
This will be resolved in react-native-windows@0.54.* - hopefully we'll also cherry-pick back to v0.50-v0.53
