### ISSUE TITLE
[Android parity] showPopupMenu shouldn't crash when the tag isn't found

### ISSUE THREAD

**Issue by rigdern** [microsoft/react-native-windows#1579]
Currently, `UIManager's showPopupMenu ` throws an exception when it can't find the tag. The Android implementation was changed such that the error is reported back to JavaScript rather than throwing a native exception.

Here's the Android PR that needs to be ported to RNW: https://github.com/facebook/react-native/pull/17550

**Comment by rozele** [comment]
We don't have any support for showPopupMenu, but this is being added in #1876. @rigdern can you advise if you need this feature?
