### ISSUE TITLE
WebSocket module throws an exception every 5 seconds when you're not using the react-devtools

### ISSUE THREAD

**Issue by rigdern** [microsoft/react-native-windows#1580]
[This line](https://github.com/Microsoft/react-native-windows/blob/fa85c5778f52d7ed8aae26e37dca97e611b8057a/ReactWindows/ReactNative/Modules/WebSocket/WebSocketModule.cs#L145) in the WebSocket module throws an exception once every 5 seconds.
 
The exception is:

```
WinRT information: A connection with the server could not be established
 
'System.Runtime.InteropServices.COMException' in System.Private.CoreLib.ni.dll
```

This contributes a lot of noise to Visual Studio's debug output window because it gets logged once every five seconds.

@rozele said:

> We can and should definitely do something about it. I forgot about the issue because I have a local copy of the JS module that connects to the react-devtools and I made it a no-op.

**Comment by fatfatson** [comment]
confirmed!
websocket is broken in UWP, could not connect to local server

**Comment by kgstew** [comment]
Any update on this? Just ran into the same issue seemingly at random. This was working for our app.

```
#package.json
{
  "react-native": "0.55.4",
  "rnpm-plugin-windows": "0.2.8",
  "react-native-windows": "0.55.0-rc.0",
}

**Comment by rigdern** [comment]
The particular issue I was reporting is just a debug annoyance. Our debug output ends up having a bunch of log lines about an error that is actually expected and handled.

I wasn't reporting any kind of functionality issues.

Does my description match the issue you are experiencing? If not, please open a new issue and describe in detail what unexpected behavior you are seeing.

Adam Comella
Microsoft Corp.
