### ISSUE TITLE
TypeError: Unable to get property 'scales' of undefined or null reference

### ISSUE THREAD

**Issue by cbarkerms** [Microsoft/react-native-windows#1581]
### Environment

1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.52.0

2. `npm ls rnpm-plugin-windows`:
APPNAMEREMOVED@0.0.1 C:\Projects\Partners\APPNAMEREMOVED
`-- (empty)

3. `npm ls react-native-windows`:
APPNAMEREMOVED@0.0.1 C:\Projects\Partners\APPNAMEREMOVED
`-- UNMET DEPENDENCY react-native-windows@0.50.0

npm ERR! missing: react-native-windows@0.50.0, required by APPNAMEREMOVED@0.0.1

4. `node -v` :v9.3.0
5. `npm -v`: 5.5.1
6. `yarn --version`:

Then, specify: 1.3.2

- Target Platform: UWP

- Target Platform Version(s): 10.0.14393 (UWP)

- Target Device(s): Desktop

- Development Operating System: Windows

- Visual Studio Version: 2017

### Steps to Reproduce

I am requesting an image like this:  require('../images/journey-background-00.png')

This eventually routes through to:

http://localhost:8081/C:\Projects\APP_NAME\node_modules\react-native-windows\Libraries\Image\resolveAssetSource.windows.js 
const resolver = new AssetSourceResolver(getDevServerURL(), getBundleSourceURL(), asset);

‘asset’ is defined and populated.  However, when it calls into the AssetSourceResolver constructor, it is received as ‘undefined’:

http://localhost:8081/C:\Projects\APP_NAME\node_modules\react-native\Libraries\Image\AssetSourceResolver.js 
  constructor(serverUrl: ?string,
    jsbundleUrl: ?string,
    embeddedBundleUrl: ?string,
    asset: PackagerAsset
  ) {
    this.serverUrl = serverUrl;
    this.jsbundleUrl = jsbundleUrl;
    this.embeddedBundleUrl = embeddedBundleUrl;
    this.asset = asset;
  }

Why?  Note that we are initializing AssetSourceResolver with 3 parameters, but it is expecting 4.  This seems related to https://github.com/facebook/react-native/commit/489b98bf1006818ba985e93478a088c0e1e1aae7.

I don’t have time to understand what the proper fix is, but for now I am hacking resolveAssetSource.windows.js from:

const resolver = new AssetSourceResolver(getDevServerURL(), getBundleSourceURL(), asset);

To:

const resolver = new AssetSourceResolver(getDevServerURL(), getBundleSourceURL(), null, asset);

This helps me move past.

### Expected Behavior

The image should be resolved correctly and no exception thrown.

### Actual Behavior

It broke - all details above.

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by rozele** [comment]
Thanks @cbarkerms - we need to update the `resolveAssetSource.windows.js` overload.

**Comment by rozele** [comment]
@cbarkerms - the reason we haven't fixed this yet is because we haven't upgraded to 0.52.* of react-native. It looks like there was an API change in `resolveAssetSource` that we need to accommodate in react-native-windows 0.52.*. I should have a fix this week.

**Comment by rozele** [comment]
@cbarkerms the solution we'll be publishing in `react-native-windows@0.52.*` is to remove `resolveAssetSource.windows.js`. Recent changes to the file have fixed an issue with appending `file://` too eagerly (e.g., for URLs starting with `ms-appx://` or `ms-appdata://`
