### ISSUE TITLE
Build app and export it as .exe or other format to sideload in windows 10 desktop

### ISSUE THREAD

**Issue by MikeDabrowski** [Microsoft/react-native-windows#1582]
I'd like to build and app and use it on my dektop window10. I dont want to publish it to store. The only way of installing it on win10 is to build it on that device and run it in release bundle configuration. I did it a year ago. However build process requires having visualstudio which is huge and I dont want it on my laptop, because I use it on my PC. 

How can I build an app so it could be moved and installed from single file (like .apk for android)
I've already read [this](https://docs.microsoft.com/en-us/windows/uwp/packaging/packaging-uwp-apps) article. 

I've also read somewhere on stack that win10 anniversary update can install appx files - if true it would suffice.

**Comment by rozele** [comment]
You should be able to do this with VSTS.  If you publish your git repository to VSTS, you can configure a build to produce your .appxpackage that you can sideload. See https://docs.microsoft.com/en-us/windows/uwp/packaging/auto-build-package-uwp-apps. This document says you can only target UWP 10.0.10586, I'll double check and see if that's been updated (you'll need to target 10.0.14393).

**Comment by rozele** [comment]
FYI - it looks like VSTS now supports builds with Visual Studio 2017, so I assume they have also updated to support Anniversary Update (10.0.14393) and probably later.

**Comment by zholobov** [comment]
@MikeDabrowski in that article you linked, if you choose No in the "Do you want to build packages to upload to Windows Store" dialog, you'll get a set of files in a directory, including .appx file, some dependencies and a .ps1 installation script. You can copy this whole directory on any machine and install the app using the script. Doesn't it work for you?

**Comment by MikeDabrowski** [comment]
I was just doing research, got no time to try it right now, but I want to try it in few weeks.
Perhaps there is some way to use continous integration like gitlab has to generate appx or other installable file from such project?

**Comment by MikeDabrowski** [comment]
Actually creating 'store config' and selecting no will create .appxbundle which can be installed on compatibile systems. This is what I wanted. Installing it works fine. I do have problem with actually running my app on windows devices but thats for another issue.
