### ISSUE TITLE
TouchHandler is unable to find React components based on MediaPlayerElement

### ISSUE THREAD

**Issue by btpnlsl** [microsoft/react-native-windows#1591]
I am building for UWP.

TouchHandler.OnPointerPressed will call GetReactViewTarget in order to find the React component to receive the pointer pressed event.  This is calling RootViewHelper.IsReactSubview which then tries to walk up the DependencyObject chain looking at successive Parent's until it finds a React component.

When using React component based on MediaPlayerElement, the control will contain a Grid whose FrameworkElement has a parent set to null.  When the control is clicked on, the RootViewHelper will be unable to get to the React / MediaPlayerElement control. 

![image](https://user-images.githubusercontent.com/7227778/35129273-b1485ed4-fc6f-11e7-81bb-3b3ea7f450f9.png)

If I modify react-native to use the VisualTreeHelper to find the parent element, then it will be able to find the React / MediaPlayerElement control.

@rozele and I talked about this off-line.

**Comment by zholobov** [comment]
As @rigdern showed me, always doing VisualTreeHelper.GetParent would break overlay dismissal in SplitView as described in this [comment](https://github.com/Microsoft/react-native-windows/blob/f7156d0ade1c75c9892c892e1c305f602e9db57c/ReactWindows/ReactNative.Shared/UIManager/RootViewHelper.cs#L87-L97). I also have suspicion that if it breaks SplitView it would also break parts of MediaPlayerElement or any other control that processes mouse events for internal logic.

**Comment by gmangov** [comment]
@zholobov @rigdern Did we find from XAML team why this is the case? VisualTreeHelper.GetParent doesn't appear to be subject to limitations like this one (at least not documented).

**Comment by zholobov** [comment]
@gmangov As far as I was able to understand, MediaPlayerElement behaves sort of like a ContentControl by having some of its visual children have Parent==null. I do not see anything abnormal in this.
