### ISSUE TITLE
React-Navigation not working with WPF apps

### ISSUE THREAD

**Issue by devlinb** [Microsoft/react-native-windows#1592]
### Environment

1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.52.0

2. `npm ls rnpm-plugin-windows`: `-- rnpm-plugin-windows@0.2.8
3. `npm ls react-native-windows`: `-- react-native-windows@0.52.0-rc.0
4. `node -v`: v8.9.0
5. `npm -v`: 5.5.1
Then, specify:

- Target Platform: WPF

- Target Platform Version(s): 10.0.14393

- Target Device(s): Desktop

- Development Operating System: Win10 1607 build 14393.2007

- Visual Studio Version: VS 2017

### Steps to Reproduce

(Write your steps here:)

1. Create a new react native WPF project
2.  Install react-navigation through NPM
3. add

    import { TabNavigator } from 'react-navigation';

to app.windows.js
 
4. Create a dummy test component that returns `<Text>Test</Text>`

In app.windows.js import the test component, replace the render function with

`const MainNavigator = TabNavigator({
    Home: { screen: TestScreen } });
    return (
      <View>
        <MainNavigator />
      </View>
    );
`

### Expected Behavior

TestScreen is navigated to

### Actual Behavior

![image](https://user-images.githubusercontent.com/11895351/35130484-f22bbe2c-fc75-11e7-9245-664a85938b73.png)

Identical code works fine if I run it in the Android emulator.

**Comment by faxioman** [comment]
Until it isn’t officialy merged, you can merge this by yourself:
https://github.com/Microsoft/react-native-windows/pull/1192

**Comment by machour** [comment]
#1192 was merged on Feb 8

**Comment by rozele** [comment]
Sounds like this is fixed by #1192 - closing.
