### ISSUE TITLE
release mode error: Module HMRClient is not a registered callable module

### ISSUE THREAD

**Issue by fatfatson** [Microsoft/react-native-windows#1594]
![image](https://user-images.githubusercontent.com/5842874/35203424-17d6972e-ff63-11e7-8d71-2ac3147c22db.png)

only happen in release
it's ok in debug.

**Comment by rozele** [comment]
You’ll need to make sure DEV=true for your bundle - https://github.com/facebook/react-native/blob/3c2bb3e90a26a441b78eab5051f98d6d19623b56/Libraries/Core/InitializeCore.js#L232

HMRClient is disabled for release bundles in React Native for all platforms. JS bundle and Native build are separate though, so you could enable by using dev bundle for release configuration.

**Comment by ManigandanRaamanathan** [comment]
Disable hot reloading, it will work fine

**Comment by afilp** [comment]
@ManigandanRaamanathan But we need hot reloading, why is this happening and how can it solved otherwise? Thanks!
