### ISSUE TITLE
[Question] How to enable JS Debugging without user interaction

### ISSUE THREAD

**Issue by iTOYS** [Microsoft/react-native-windows#1596]
Hi guys!

I'm working on support `react-native-windows` in [vscode-react-native](https://github.com/Microsoft/vscode-react-native/issues/614) extension.

Is it possible to enable JS Debugging and restart JS through `cmd.exe` or/and from app JS code?

We can do it on iOS and Android, so I thought that it's shoud be possible.

Thanks!

**Comment by rozele** [comment]
@iTOYS That's awesome!  To start an app in remote debugging mode, I believe you can just use the `--proxy` option, as in `react-native run-windows --proxy`. See here: https://github.com/Microsoft/react-native-windows/blob/master/local-cli/runWindows/runWindows.js#L96-L99

I think Android supports kicking off an activity at any time, do you need that as well (e.g., for attach debugger scenarios)? In theory, we can create a protocol activation URI that would enable the remote debugging.

**Comment by iTOYS** [comment]
Thanks @rozele  `react-native run-windows --proxy` exactly what I need!
Yes, on Android I can reload application in debug mode at any time with `adb` and do some another stuff. 
It would be great to have something similar.

On iOS we don't have `adb`, but we have `require('NativeModules').DevMenu` for our purposes.
I can make PR with it when I have time)
