### ISSUE TITLE
display: none not hiding view

### ISSUE THREAD

**Issue by martinbooth** [Microsoft/react-native-windows#1602]
### Environment

1. `react-native -v`: 
`react-native-cli: 2.0.1
react-native: 0.52.1`
2. `npm ls rnpm-plugin-windows`:
`+-- rnpm-plugin-windows@0.2.8`
3. `npm ls react-native-windows`:
`react-native-windows@0.52.0-rc.0`
4. `node -v`:
`v9.4.0`
5. `npm -v`:
`3.10.5`

6. `yarn --version`:

Then, specify:

- Target Platform:
UWP

- Target Platform Version(s): 10.0.14393, UWP

- Target Device(s): Desktop

- Development Operating System: Windows 10

- Visual Studio Version: Visual Studio 2017

### Steps to Reproduce

(Write your steps here:)

1. Apply the style display: none to an element
2.
3.

### Expected Behavior

(Write what you thought would happen.)
Element should be hidden
### Actual Behavior
Element is not hidden
 (though after a resize it does disappear)

(Write what happened. Add screenshots!)

### Reproducible Demo
`      <View style={{ display: 'none' }}>
        <Text>This shouldn't display</Text>
      </View>`

(Paste the link to an example project and exact instructions to reproduce the issue.)

![image](https://user-images.githubusercontent.com/4383362/35467823-917d924a-02c8-11e8-9a57-135a66058bd3.png)

**Comment by rozele** [comment]
Thanks for filing! We need to upgrade to the latest version of Yoga, then we should be able to add support for this prop!
