### ISSUE TITLE
UPF realease not load js have stopped

### ISSUE THREAD

**Issue by Javis1205** [Microsoft/react-native-windows#1607]
### Environment

1. `react-native -v`: 0.51.0
2. `npm ls rnpm-plugin-wpfs`:  ^0.1.2
3. `npm ls react-native-windows`: ^0.51.0-rc.1
4. `node -v`:
5. `npm -v`:
6. `yarn --version`:

Then, specify:

- Target Platform:

- Target Platform Version(s):
WPF

- Target Device(s):

- Development Operating System:

- Visual Studio Version:

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

I create offline bundle for WPF but it not working!
can you help me please!!! thank you so much

**Comment by rozele** [comment]
@Javis1205 please provide more detail about the specific error that is occurring, or zip up an example project that is failing so someone can try to repro.
