### ISSUE TITLE
Timing module should pause timers when entering the background

### ISSUE THREAD

**Issue by rigdern** [microsoft/react-native-windows#1610]
Currently, the timers are only paused/resumed when the app suspends/resumes:

https://github.com/Microsoft/react-native-windows/blob/81e5cc6929bfebc645cae62f6780b203da5b845d/ReactWindows/ReactNative.Shared/Modules/Core/Timing.cs#L67-L96

To be consistent with the iOS/Android React Native implementations, we should also pause/resume the timers based on the EnteredBackground/LeavingBackground events. As you can see on iOS, the timers are paused when the app enters the background:

https://github.com/facebook/react-native/blob/a63fd378a47173cc9f750e9980f18dc12dd7ea51/React/Modules/RCTTiming.m#L117

We can solve this with `IBackgroundEventListener`. I discussed this with @rozele.

**Comment by rozele** [comment]
@rigdern - to clarify, you only want timers paused when the app is suspended, correct? I can foresee the need for timers executing on apps running in a background process mode.

**Comment by rozele** [comment]
Honestly then I think we should eliminate the stub behavior that lets the `ReactChoreographer` run in the background off a dispatcher timer. Doing this will effectively "pause" timers. Not sure if there's anything else that depends on the ReactChoreographer that would be needed for background mode.
