### ISSUE TITLE
Support drop shadow properties for UWP views

### ISSUE THREAD

**Issue by keatongreve** [microsoft/react-native-windows#1614]
Similar to https://github.com/Microsoft/react-native-windows/issues/953, but that was closed after drop shadows were implemented for WPF.

**Comment by rozele** [comment]
Turns out this is pretty challenging for UWP - there was a failed attempt here: https://github.com/Microsoft/react-native-windows/pull/1633

Would be great if you want to run with this to get a robust solution.

**Comment by rozele** [comment]
Related to #2059
