### ISSUE TITLE
fontStyle style crash with wpf app

### ISSUE THREAD

**Issue by faxioman** [Microsoft/react-native-windows#1624]
Try to set the style fontStyle to ‘normal’ in a <Text/> component when targetting a wpf app.
You can see the app crashing.
With this bug, apps like react-native-vector-icons are unusable.

**Comment by rozele** [comment]
Thanks - can you see if #1191 fixes the issue?

**Comment by faxioman** [comment]
@rozele sorry for the loooong delay :(
Yes, #1191 fixes the issue!
