### ISSUE TITLE
Windows 8 will it run?

### ISSUE THREAD

**Issue by killinit** [Microsoft/react-native-windows#1640]
Hello
this is more like question then issue itself.

Can I build using React Native Windows application that will run on Windows 8 too ?

What are the limitations and/or why?

Have anybody try it?

Best Wishes Too You all
Maciej

**Comment by matthargett** [comment]
Yes, you can use the WPF version of React Native Windows to run on WIndows 7/8 if you have .NET 4.6 (minimum) installed. (Vista may also work if .NET 4.6 + IE11 is installed, but not tested and not officially supported.) Several companies are shipping RN Windows apps using the WPF variant, including BlueJeans' video collaboration app.
