### ISSUE TITLE
React native bundler error

### ISSUE THREAD

**Issue by pgodha** [microsoft/react-native-windows#1641]
### Environment

1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.44.3

2. `npm ls rnpm-plugin-windows`:

3. `npm ls react-native-windows`:
 react-native-windows@0.44.0-rc.3
4. `node -v`:
v8.9.4

5. `npm -v`:
5.3.0

6. `yarn --version`:
1.3.2
Then, specify:

- Target Platform:
WPF

- Target Platform Version(s):
.NER 4.5

- Target Device(s):
Desktop

- Development Operating System:
Win10

- Visual Studio Version:
VS 2015

### Steps to Reproduce

I have been using react-native 0.42 version, and everything was working fine, and then I changed to 0.44, and tried to create release bundle for my windows app using Command

react-native bundle --platform windows --dev false --entry-file index.windows.js --bundle-output windows/app/ReactAssets/index.windows.bundle --assets-dest windows/app/ ReactAssets/

and I get following error:-

Unable to resolve module `AccessibilityInfo` from `C:\Users\<username>\<project>\node_modules\react-native\Libraries\react-native\react-native-implementation.js`: Module does not exist in the module map

This might be related to https://github.com/facebook/react-native/issues/4968

To resolve try the following:

  1. Clear watchman watches: `watchman watch-del-all`.

  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.

  3. Reset Metro Bundler cache: `rm -rf $TMPDIR/react-*` or `npm start -- --reset-cache`.  4. Remove haste cache: `rm -rf $TMPDIR/haste-map-react-native-packager-*`.

because of some reason packager is not able to find `AccessibilityInfo` component present in RNW libraries, but I can see component is present at `project\node_modules\react-native-windows\Libraries\Components\AccessibilityInfo`

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by rozele** [comment]
RN 0.44 is quite old - any chance you can upgrade to a newer release of react-native?

**Comment by rozele** [comment]
Also - in general watchman has never really been supported for React Native Windows development - can you try disabling watchman and see if its still an issue?

**Comment by pgodha** [comment]
@rozele We are currently using RN 0.42, and trying to upgrade to RN 0.55, but getting the same error.
