### ISSUE TITLE
Unable to resolve 'ChakraBridge' for UAP,Version=v10.0.10240 when running "react-native run-windows"

### ISSUE THREAD

**Issue by rickbutton** [Microsoft/react-native-windows#1666]
### Environment

1. `react-native -v`: 2.0.1, 0.52.3
2. `npm ls rnpm-plugin-windows`: 0.2.8
3. `npm ls react-native-windows`: 0.52.0-rc.3
4. `node -v`: v9.4.0
5. `npm -v`: 5.6.0

Then, specify:

- Target Platform: UWP

- Target Platform Version(s): 10.0.14393

- Target Device(s): Desktop

- Development Operating System: Windows 10, 16299

- Visual Studio Version: 2017

### Steps to Reproduce

1. setup blank react-native app with "react-native init"
2. install rnpm-plugin-windows
3. run "react-native windows"
4. run "react-native run-windows"

### Expected Behavior

It should start the application.

### Actual Behavior

The following error:

```
Errors in C:\git\demo\node_modules\react-native-windows\ReactWindows\ReactNative\ReactNative.csproj
    Unable to resolve 'C:\git\demo\node_modules\react-native-windows\ReactWindows\ChakraBridge\ChakraBridge.vcxproj' for 'UAP,Version=v10.0.10240'.

Errors in C:\git\demo\windows\demo\demo.csproj
    Unable to resolve 'C:\git\demo\node_modules\react-native-windows\ReactWindows\ChakraBridge\ChakraBridge.vcxproj' for 'UAP,Version=v10.0.10240'.
Failed to restore the NuGet packages
```

### Reproducible Demo

Just create a blank app using react-native init. This error also occurs for me when I use version 0.53 of react-native and react-native-windows. The application starts perfectly when I use "react-native start" and VS2017 to start the UWP app.

**Comment by AdamLuciano** [comment]
Hi, I know it's been a while, did you ever find a fix?

**Comment by lironsher** [comment]
I have the same issue

**Comment by sushruth** [comment]
This is no longer an option to install in VS2019. I understand I could still install those tools but time to consider upgrade.

**Comment by Antoine-Mace** [comment]
agree with @sushruth I am fairly new to react-native-windows project, will be mentioning in doc that you must use VS2017 in order to use the correct SDK
