### ISSUE TITLE
Network errors are not properly propagated to the final response 

### ISSUE THREAD

**Issue by chadjriddle** [microsoft/react-native-windows#1667]
### Environment
react-native-cli: 2.0.1
react-native: 0.53.3
reactUWP@0.0.1 c:\ReactNative\reactUWP
`-- rnpm-plugin-windows@0.2.8
reactUWP@0.0.1 c:\ReactNative\reactUWP
`-- react-native-windows@0.53.0-rc.1
node: v9.4.0
npm: 5.6.0
yarn: 1.3.2

- Target Platform: UWP
- Target Platform Version(s): UWP 10.0.16299
- Target Device(s): Desktop
- Development Operating System: Windows 10
- Visual Studio Version: VS2017

### Problem Statement

Using fetch or superagent to retrieve simple JSON data via a HTTP Get request on the local network fails with a non-helpful generic error message.

The error returned in the response is (generic):
"Request has terminated Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc"

However, the real error thrown by the .Net code is (very helpful):
"Access is denied. A network capability is required to access this network resource"

I would expect that the .Net error message would be propagated all the way up the stack and not translated into a generic error message.  

Once I was able to debug into the .Net code and see the error message the solution was a simple fix.  Adding the "Private Network" capability to the Package.appxmanifest file solved the issue.

Looking at the code further I can see that in XMLHttpRequest.js:__didCompleteResponse() the error is reported correctly from .Net.  However, by the time the message gets to the actual fetch/superagent response it is translated to the generic error message.  

Is there a way to propagate the actual error message up through the fetch/superagent response?

This problem cost me almost a full day of trouble shooting.

As an additional note, attempting to watch the network traffic via Fiddler or the Chrome debugger masked this issue completely and allowed the request to succeed against a local server even without the "Private Network" capability enabled.

### Reproducible Demo
This issue is easy to reproduce simply use the following code to attempt to reach a network resource on the local network:

          fetch("http://198.168.1.???")  <-Update with your local network service
          .then((response) => response.json())
          .then((responseData) => {
             this.setState({data: responseData.name});
           })
           .catch((e) => {
             this.setState({data: e.message}); <- Message here is simply "Network Error"
           })
           .done()

Using superagent you get a different error message:

          request
          .get("http://192.168.1.???") <- Update with your local network service
          .end((e,r) => 
          {
            if (e) {
              this.setState({data:e.message});  <- Message here is "Request has been terminated..."
            } else{
              this.setState({data:JSON.stringify(r.body)});
            }
          });

**Comment by rozele** [comment]
This might be related to #1895
