### ISSUE TITLE
Is there a forum allow us discuss some problem about this project

### ISSUE THREAD

**Issue by XQDD** [Microsoft/react-native-windows#1692]
what I do recently is developing a sticky note app like win10's witch has few functions.

The first problem  I meet with is multi-window which is developing.

The second is how  to control the window's size( the [min/max]width and the [min/max]height of the window , what the picture show is the minimum size , it can't be smaller )
![image](https://user-images.githubusercontent.com/20871761/36947383-c8094872-2005-11e8-9cdb-7f459a194f11.png)

The third is how to custom the title bar ( not just the Three King Kong button- minimize，maximize , close , I need something else ).

I  already google it and find it in the issues , but just find some information about multi-window on the commit histories (or because of the poor English)

Desktop app is  different with the mobile's which is single page , I can't find any help in the react-native document witch just some api and component.

So I ( a rookie ) or We need a forum or other place to find some answer witch we can't easy gain

At the last , thanks for do so awesome project and forgive my poor English

**Comment by XQDD** [comment]
I found it is a disaster to build a sticky note use react-native-windows at present..I'm better to use native technology

**Comment by rozele** [comment]
It may not be a good use case for react-native-windows. Thanks for filing @XQDD.
