### ISSUE TITLE
Track pending JS calls to delay Instance being destroyed

### ISSUE THREAD

**Issue by matthargett** [microsoft/react-native-windows#1694]
There can be a race when some async (or sync) calls to Native Modules happen, an app shutdown is requested, the Bridge is destroyed, but then the JS calls return. This was noticed and fixed upstream in RN Android Java:
https://github.com/facebook/react-native/search?utf8=%E2%9C%93&q=incrementPendingJSCalls&type=

The Java implementation was transliterated/replicated in an RN Windows fork to successfully fix and prevent this class of issues.

**Comment by kmelmon** [comment]
We have this fix in the latest C++ implementation of react-native-windows.
