### ISSUE TITLE
Failed to deploy: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by MarceloEmmerich** [Microsoft/react-native-windows#1706]
### Environment

1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.52.0

2. `npm ls rnpm-plugin-windows`:
`-- rnpm-plugin-windows@0.2.8

3. `npm ls react-native-windows`:
-- react-native-windows@0.52.0-rc.3

4. `node -v`:
v6.10.3

5. `npm -v`:
3.10.10

6. `yarn --version`:
no yarn used

Building on Windows 10 x64, VS 2017 community, latest SDK, for windows 10 x64 with:

### Steps to Reproduce

* react-native run-windows --arch x64 --release

### Expected Behavior

App is built and executed as 64bit.

### Actual Behavior

```
react-native run-windows --arch x64 --release
Scanning folders for symlinks in --snip-- (31ms)
Restoring NuGet packages
Building --snip--.sln
Found MSBuild v15.0 at C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin
Building Solution: --snip--.sln
Build configuration: Release
Build platform: x64
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Sie den Schalter "/m" hinzufügen.
Starting the React-Native Server
Failed to deploy: Path must be a string. Received undefined
```

**Comment by rozele** [comment]
Need more details here. Can you try debugging with `react-native run-windows --verbose` to see if there are any glaring errors or issues that are being swallowed?

**Comment by abhisri2090** [comment]
Hey, I am still getting the same issue, any idea how to fix this?
![Screenshot (267)](https://user-images.githubusercontent.com/31709161/66595213-217f2000-ebb8-11e9-95e9-ec447aa28344.png)
