### ISSUE TITLE
Release Notes (Changelog)

### ISSUE THREAD

**Issue by jpshelley** [Microsoft/react-native-windows#1708]
I noticed around the October release that Release Notes were added, but since then there haven't been any.

Is there a way to get a Changelog for new features, breaking changes, and performance enhancements?

Release Notes help give motivation for upgrading to newer releases when showing the value to a project manager as well.

If there is a way the community can help out with this at all, let me know and I'll try to help!

**Comment by rozele** [comment]
Thanks for bringing this up @jpshelley - we're way overdue for release notes on 0.51.0 - no other releases have a "stable" version yet (0.52 and later). I'll work on getting release notes up for 0.51, and also we should consider having something like https://github.com/react-native-community/react-native-releases for RNW.

**Comment by jpshelley** [comment]
If there is anyway community members can help out, let me know! I know that type of task can be tedious.

**Comment by rozele** [comment]
Published stable versions of 0.51 - 0.54 and added release notes. Will try to keep this more up-to-date (and also will keep thinking about how we can engage the community on release notes).
