### ISSUE TITLE
Upgrading from VS 2015 to VS 2017 

### ISSUE THREAD

**Issue by jpshelley** [Microsoft/react-native-windows#1712]
As the title suggests:

Currently on `react-native` and `react-native-windows` **v47** using **_Visual Studio 2015_**

We would like to upgrade to `react-native` and `react-native-windows` **v48** which requires **_Visual Studio 2017_** it appears.

However, there are no upgrade steps. What is the preferred approach? Scanning through github issues and wasn't able to find exactly what I'm looking for.

**Comment by rozele** [comment]
I think in general we have a glaring gap in upgrade support. Closing this as we have a plethora of issues related to missing tooling for upgrading, e.g., #674

**Comment by jpshelley** [comment]
Since this is now closed, I did want to share we finally managed to upgrade from **v0.47** to **v0.51**

We ended up creating fresh _react-native-windows_ projects and manually scanning the files for changes to the `.sln` and `.proj` and other relevant `.cs` files. Taking it one upgrade at a time. It was very tedious and not ideal but we did get it completed finally.
