### ISSUE TITLE
Relax version requirements

### ISSUE THREAD

**Issue by pronebird** [Microsoft/react-native-windows#1731]
Hi,

I experience some peer dependency requirements crisis here. Is it possible to relax the version requirements?

This is the excerpt from `package.json`:

```
  "peerDependencies": {
    "react": "16.3.0-alpha.1",
    "react-native": "0.54.0"
  },
```

It's impossible to line up all of the dependencies to use the exact same version of React or react-native. I imagine there are reasons behind that I am not aware of, but if there is a way to give a little runway for the library consumers maybe that would decrease chances of running into incompatibility issues.

This also affects ReactXP, see: https://github.com/Microsoft/reactxp/issues/562

**Comment by rozele** [comment]
@pronebird good catch, this should be `^16.3.0-alpha.1` and `~0.54.0`
