### ISSUE TITLE
RFC: Remove ReactContext parameter from CreateNativeModules interface?

### ISSUE THREAD

**Issue by matthargett** [Microsoft/react-native-windows#1734]
Someone noticed that the ReactContext parameter isn't actually used most of the time. Can we eliminate this concrete type from the parameter list? Is it cruft from a bygone era, or plans for the future yet to come?

**Comment by matthargett** [comment]
@rigdern @pre10der89

**Comment by rigdern** [comment]
@matthargett Can you elaborate on how one would get access to the `ReactContext` if we removed it? A number of the modules in `MainReactPackage` use it: https://github.com/Microsoft/react-native-windows/blob/c8ef244b91b7c3f2b7d01df44fb638439f3479a2/ReactWindows/ReactNative.Net46/Shell/MainReactPackage.cs#L49

**Comment by matthargett** [comment]
It gets passed in, but a few don't end up using it directly. Several use the Context just for a dynamic lookup to get the RCTDeviceEventEmitter, and I wonder if those could be passed in directly. Some others listen for lifecycle events, and just need the delegate so they can add their handlers.

It does look like there's a few places it's used for more than one or two things, so maybe it doesn't make sense to remove the visibility entirely. Looking at the actual usage of the parameter more deeply, what do you think?

**Comment by rozele** [comment]
I'd actually prefer `ReactContext` -> `IReactContext`.

**Comment by matthargett** [comment]
That’s what I did in the netstandard branch ;) will recreate that in the Interfaces PR.

**Comment by rozele** [comment]
I agree that there should be a more standard way of using ReactContext.  Some view managers pass it through the constructor, others require that the context get pulled from the view itself.  For native modules, we need to have the option to construct the instance with the ReactContext to send events. I'm not sure that the RCTDeviceEventEmitter is really the only API we want to expose to native modules for now.
