### ISSUE TITLE
Requiring unknown module "undefined"

### ISSUE THREAD

**Issue by hashithkarunarathne** [Microsoft/react-native-windows#1736]
### Environment

  "dependencies": {
    "patwoz/react-navigation-is-focused-hoc": "^1.2.1",
    "ptomasroos/react-native-multi-slider": "0.0.11",
    "arty-charty": "^1.0.4",
    "create-react-class": "^15.6.2",
    "d3-shape": "^1.2.0",
    "lodash": "^4.17.4",
    "react": "16.3.0-alpha.1",
    "react-charts": "^0.1.0",
    "react-localize-redux": "^2.13.7",
    "react-native": "0.54.2",
    "react-native-audio-streaming": "^2.3.2",
    "react-native-audio-toolkit": "^1.0.6",
    "react-native-auto-height-image": "^0.3.4",
    "react-native-calendar-events": "^1.4.3",
    "react-native-check-box": "^2.0.2",
    "react-native-collapsible": "^0.10.0",
    "react-native-context-menu-strip": "0.0.2",
    "react-native-convert-image-to-base64": "^0.1.0",
    "react-native-datepicker": "^1.6.0",
    "react-native-device-info": "^0.13.0",
    "react-native-fcm": "^11.3.0",
    "react-native-fetch-blob": "^0.10.8",
    "react-native-firebase-analytics": "^4.0.1",
    "react-native-image-picker": "^0.26.7",
    "react-native-keyboard-aware-scroll-view": "^0.4.4",
    "react-native-lazyload": "^1.1.0",
    "react-native-lazyload-deux": "^2.0.4",
    "react-native-linear-gradient": "^2.4.0",
    "react-native-looped-carousel": "^0.1.7",
    "react-native-maps": "^0.19.0",
    "react-native-maps-super-cluster": "^1.3.1",
    "react-native-material-dropdown": "^0.6.1",
    "react-native-material-textfield": "^0.11.0",
    "react-native-modal": "^4.1.1",
    "react-native-modalbox": "^1.4.2",
    "react-native-pdf": "^3.0.3",
    "react-native-permissions": "^1.0.6",
    "react-native-popup-menu": "^0.11.0",
    "react-native-progress": "^3.4.0",
    "react-native-scrollable-tab-view": "^0.8.0",
    "react-native-snap-slider": "^0.3.0",
    "react-native-spinkit": "^1.1.1",
    "react-native-svg": "^6.0.1-rc.1",
    "react-native-svg-charts": "^1.6.1",
    "react-native-swipe-gestures": "^1.0.2",
    "react-native-swiper": "^1.5.13",
    "react-native-trackjs": "^0.1.2",
    "react-native-video": "^2.0.0",
    "react-native-view-shot": "^2.3.0",
    "react-native-windows": "^0.54.0-rc.1",
    "react-navigation": "1.5.8",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-logger": "^3.0.6",
    "redux-persist": "^5.4.0",
    "redux-thunk": "^2.2.0"
  },

1. `react-native -v`: 0.54.2
2. `npm ls rnpm-plugin-windows`: ^0.2.8
3. `npm ls react-native-windows`: ^0.54.0-rc.1
4. `node -v`: v6.11.3
5. `npm -v`: 3.10.10
6. `yarn --version`:

Then, specify:

- Target Platform: UWP

- Target Platform Version(s): 10.0.14393

- Target Device(s): Desktop, Mobile (ARM), Mobile Emulator

- Development Operating System: Windows

- Visual Studio Version: Visual Studio 2017

After updating react-native and react-native-windows this issue occurred
![issue](https://user-images.githubusercontent.com/9252251/37907285-412a165a-3122-11e8-8a34-6a1c85d6a36f.png)

**Comment by npmun** [comment]
This I believe is related to this...
github.com/react-community/react-native-maps/issues/2051

**Comment by rozele** [comment]
@npmun curious what require call is in your project at `.\app\components\index.js:7:0`

**Comment by npmun** [comment]
@hashithkarunarathne please provide information that @rozele looking for from your project.

**Comment by rozele** [comment]
Ah, thanks for redirecting @npmun

**Comment by hashithkarunarathne** [comment]
I removed react-native-maps and tried but issue is still exists

**Comment by hashithkarunarathne** [comment]
> curious what require call is in your project at .\app\components\index.js:7:0 
Thanks @rozele after removing .\app\components\index.js:7:0 component it's worked
