### ISSUE TITLE
Helvetica font in TextInput 

### ISSUE THREAD

**Issue by nomartin** [microsoft/react-native-windows#1746]
_We have been testing different fonts for UX._

The bottom of the letters:  **g  y  p  q  j**  are cut off for **Helvetica**
The placeholder works great but as soon as text is entered, the bottom of the letters are not drawn (see the SS below).

![image](https://user-images.githubusercontent.com/6379020/38121776-e973ad8c-3396-11e8-9913-1c2b31181459.png)

Code:
```javascript
import * as React from 'react';
import { TextInput, Text, View } from 'react-native';

class FontTest extends React.Component {
  public render() {
    return (
      <View>
        <View>
          <TextInput style={{ fontFamily: 'Helvetica' }}
           autoCorrect={false}
           placeholder="Helvetica : g y p q j"
          />
        </View>
        <View>
          <TextInput style={{ fontFamily: 'Helvetica' }}
           autoCorrect={false}
           placeholder="Helvetica : g y p q j"
          />
        </View>
      </View>
    );
  }
}

export default FontTest;

**Comment by rozele** [comment]
@nomartin can you confirm if this is still an issue in the latest version of react-native-windows? We've updated Yoga, so presumably we may not have this layout problem anymore.
