### ISSUE TITLE
Playground.Net46 is broken on master (at least)

### ISSUE THREAD

**Issue by matthargett** [Microsoft/react-native-windows#1751]
### Environment

1. `react-native -v`:
2. `npm ls rnpm-plugin-windows`:
3. `npm ls react-native-windows`:
4. `node -v`:
5. `npm -v`:
6. `yarn --version`:

Then, specify:

- Target Platform: WPF

- Target Platform Version(s): .NET 4.6

- Target Device(s): Desktop

- Development Operating System: Windows 10 RS4

- Visual Studio Version: VS2017 15.6.4

### Steps to Reproduce

(Write your steps here:)

1. checkout master, open ReactNative.sln
2. set Playground.Net46 as startup project, target Debug/x86
3. run (control+F5)

### Expected Behavior

Should display "Welcome to React Native" text.

(Write what you thought would happen.)

### Actual Behavior

Redbox crash, even before trying to load the bundle.

![image](https://user-images.githubusercontent.com/1550766/38242712-562091b0-36ea-11e8-94b5-bfeaef4c74ed.png)

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by reseul** [comment]
Fixed. This was a typo on some unused method, it seems some recent update added a check for this case. Nice.
