### ISSUE TITLE
  Unrecognized command 'run-windows'

### ISSUE THREAD

**Issue by leaphawk** [Microsoft/react-native-windows#1760]
### Environment

1. `react-native-cli: 2.0.1
react-native: 0.54.0`:
2. `npm ls rnpm-plugin-windows`:
3. `rnpm-plugin-windows@0.2.8`:
4. node `v8.11.1`:
5. npm `5.6.0`:
no yarn 

Then, specify:

platform:Both

framework: UWP & UWF

Desktop

Windows 10

- Visual Studio Version: communtiy 2017

### Steps to Reproduce

1. react-native init demo
2. npm install rnpm-plugin-windows 
3. react-native windows //works!
4. react-native run-windows //doesn't work ( Unrecognized command 'run-windows' )

### Expected Behavior

It's shown in docs to run the project with react-native run-android
(Write what you thought would happen.)

### Actual Behavior

  Unrecognized command 'run-windows'

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by rozele** [comment]
@leaphawk can you run `react-native --help` and see if the `run-windows` command pops up? If it does, can you also confirm that you have successfully installed `react-native-windows` via NPM with `npm ls react-native-windows`.

**Comment by leaphawk** [comment]
no I can't see `run-windows` there but `windows is there`.
<img width="564" alt="screen shot 2018-04-10 at 12 00 44 am" src="https://user-images.githubusercontent.com/32162075/38515849-11841b62-3c53-11e8-8360-7d2dbb8e79c6.png">
<img width="858" alt="screen shot 2018-04-10 at 12 06 01 am" src="https://user-images.githubusercontent.com/32162075/38515854-1925dedc-3c53-11e8-918e-7af2b3b33c39.png">

**Comment by rozele** [comment]
So it seems like the `react-native windows` command may have failed. That is responsible for installing the `react-native-windows` NPM package that matches the current installed version of `react-native`. Can you run it again?

**Comment by leaphawk** [comment]
Yeah now!

**Comment by rozele** [comment]
The `react-native` CLI uses `package.json` as a source for CLI plugins (like the `react-native run-windows` command), so if `react-native-windows` isn't showing up in `package.json` or the `node_modules` folder, then the CLI won't recognize the command.

Also, the CLI isn't the only way to run the UWP app. You can also open the solution file in Visual Studio 2017 and run from there, you'll just need to start the packager in the background (either with `npm start` or `react-native start`)

**Comment by leaphawk** [comment]
@rozele Thanks for the help. It worked this time. However, I tried multiple times before. Even done reinstalls. Maybe missed something on the terminal. Anyways thanks.
