### ISSUE TITLE
Control camera in react native window

### ISSUE THREAD

**Issue by hoangtuandinh77** [Microsoft/react-native-windows#1761]
I need to add a library to control the camera, I try many librarys for native and it fail, some body can help me???

**Comment by hoangtuandinh77** [comment]
![image](https://user-images.githubusercontent.com/25733576/39285093-bb848922-4940-11e8-9cde-24fced9ceaea.png)
 I'm try.....

**Comment by rozele** [comment]
@hoangtuandinh77 - I've updated this branch recently, but that work is _very_ experimental and not likely to be merged any time soon. If it's something you're interested in supporting, by all means take over the PR and try to get things stable enough for merge in react-native-camera.
