### ISSUE TITLE
Add Initial Props to ReactNativeHost

### ISSUE THREAD

**Issue by jpshelley** [Microsoft/react-native-windows#1774]
### Environment

1. `react-native -v`: 0.55.2
2. `npm ls rnpm-plugin-windows`:
3. `npm ls react-native-windows`: 0.55.0-rc.0
4. `node -v`:
5. `npm -v`:
6. `yarn --version`:

Then, specify:

- Target Platform: UWP

- Target Platform Version(s): UWP

- Target Device(s): Surface

- Development Operating System: Windows

- Visual Studio Version: 2017

### Steps to Reproduce

There is not longer a way to pass initial props to React Native - we would pass some hardware specific values from C# on load, so we didn't need a bridge to access them.

### Expected Behavior

Initial Props are able to be passed to `ReactNativeHost` like ReactNativePage use to allow

### Actual Behavior

There is no method for passing initial props

Is this a chosen approach? Or can we add that back into the source code for ReactNativeHost?

**Comment by jpshelley** [comment]
It appears possible due to here: https://github.com/Microsoft/react-native-windows/blob/c8ef244b91b7c3f2b7d01df44fb638439f3479a2/ReactWindows/ReactNative.Shared/ReactNativeHostExtensions.cs#L28

But because this method is private, I'm afraid that its not supported: https://github.com/Microsoft/react-native-windows/blob/master/ReactWindows/ReactNative/ReactApplication.cs#L119

**Comment by rozele** [comment]
Thanks for notifying @jpshelley - can you find the rough equivalent in Android and drop a pointer? The UWP surface is roughly symmetric.

**Comment by jpshelley** [comment]
@rozele good point:
1. When the view is created its passed its init props here --> https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/ReactActivityDelegate.java#L90
2. Those are grabbed from the overriden abstract method here - https://github.com/facebook/react-native/blob/master/RNTester/android/app/src/main/java/com/facebook/react/uiapp/RNTesterActivity.java#L46

I assume this would be similar then too
1. When the view is created its passed its init props here --> https://github.com/Microsoft/react-native-windows/blob/master/ReactWindows/ReactNative.Shared/ReactNativeHostExtensions.cs#L46
2. So the `ReactNativeHost` could have an abstract method to read from to populate

See #1775 if that makes sense
