### ISSUE TITLE
blurOnSubmit - Not Yet Implemented

### ISSUE THREAD

**Issue by jpshelley** [microsoft/react-native-windows#1779]
### Environment
1. `react-native -v`: 0.55.2
2. `npm ls rnpm-plugin-windows`: 0.2.8
3. `npm ls react-native-windows`: 0.55.0-rc.0
4. `node -v`:
5. `npm -v`:
6. `yarn --version`:

Then, specify:

- Target Platform: UWP

- Target Platform Version(s): UWP

- Target Device(s): Surface

- Development Operating System: Windows

- Visual Studio Version: 2017

### Steps to Reproduce

Create a Multiline TextInput component with blurOnSubmit and onSubmitEnter

1. Create a TextInput component like the following:
```jsx
<TextInput
   autoGrow
   multiline
   blurOnSubmit
   onSubmitEditing={() => ... }
   />
```

### Expected Behavior

Expect `onSubmitEditing` to get called
See: https://facebook.github.io/react-native/docs/textinput.html#bluronsubmit
See: https://facebook.github.io/react-native/docs/textinput.html#onsubmitediting

### Actual Behavior

Pressing Enter in a multiline textinput field just enters a new line every time.

The change would be to add the prop to --> https://github.com/Microsoft/react-native-windows/blob/master/ReactWindows/ReactNative/Views/TextInput/ReactTextInputManager.cs

**Comment by jpshelley** [comment]
for functionality reference, we've done some work on this --> https://github.com/Microsoft/react-native-windows/commit/102764698aa0b12d1c3691b9a53345e9d43d4cd3

We'll be likely to submit a PR in the coming days, but not sure about styling changes, just functionality.

**Comment by Hirurgo** [comment]
@jpshelley thanks for your work, but i have problems to reproduce your results, i apply changes and nothing happens, maybe you know some reason for this?

**Comment by Hirurgo** [comment]
@jpshelley I found the reason,  multiline  blurOnSubmit props contradict each other.
In SetMultiline function we have -    view.AcceptsReturn = multiline;
In SetBlurOnSubmit function we have -  view.AcceptsReturn = !blurOnSubmit;

Еhat is, what property is the **last** one will determine the result
