### ISSUE TITLE
ReactInstanceManager.ProcessPackage() stalls the main thread on startup

### ISSUE THREAD

**Issue by matthargett** [Microsoft/react-native-windows#1781]
We observed in profiling that the main thread stalls for quite a few frames while ProcessPackage is running during app startup. 

A possible fix would be:
* Having ProcessPackage() return a Task.Run()
* add all the Tasks to a list
* await Task.WhenAll() on the list

This may require using some concurrency-safe Dictionaries and collections in the NativeModuleRegistry.Builder and JavaScriptModuleRegistry.Builder.

**Comment by rozele** [comment]
Do you have more granular details about what's going on in `ProcessPackage` that causes the delay? @antonkh has done some investigation into this, and I believe this is related to `ViewManager` constants and collecting reflection info on `ReactMethod` and `ReactProp` methods. That was part of the inspiration for #1744.

**Comment by rozele** [comment]
@matthargett can you try out ae7e37f62b10385d168b6afc8bc0262424180f73 and lazy view manager constants in a05cfce29cdfbe917cff0679e2746063a1fe95c2 and see if it has reduced the `ProcessPackage` call?
