### ISSUE TITLE
performanceNow timer has poor resolution

### ISSUE THREAD

**Issue by matthargett** [Microsoft/react-native-windows#1782]
### Environment

1. `react-native -v`: 2.0.1 / 0.54.0
2. `npm ls rnpm-plugin-windows`:
3. `npm ls react-native-windows`: 0.54.0
4. `node -v`: 8.9.3
5. `npm -v`: 5.6

Then, specify:

- Target Platform: UWP and WPF

- Target Platform Version(s): .NET 4.6 on Windows 10 RS4

- Target Device(s): Desktop and Xbox

- Development Operating System:
Windows 10 RS4

- Visual Studio Version:
VS2017 15.6.6

### Steps to Reproduce

(Write your steps here:)

1. use performanceNow API to try and measure timings in your app without resorting to remote JS debugging

### Expected Behavior
It should provide a reasonably accurate timer such that two invocations separated by tens of milliseconds don't produce the same value.

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

Redcued in Playground's index.windows.js:
```

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
} from 'react-native';

import performanceNow from 'fbjs/lib/performanceNow';

class Playground extends Component {
  constructor(props) {
    var now = performanceNow();
    super(props);
    this.state = {performanceDotNow: now, originalPerformanceNow: now};
    setInterval(() => {
      this.setState(previousState => {
        var now = performanceNow();
        return {performanceDotNow: now};
      });
    }, 1000);
  }

  render() {
    var performanceDotNow2 = performanceNow();
    return (
      <View style={styles.container}>
        <Text style={styles.welcome} testID="WelcomeText">
          performanceNow in ctor: {this.state.originalPerformanceDotNow}
        </Text>
        <Text style={styles.instructions}>
          performanceNow in render before alert: {performanceDotNow2}
        </Text>
        <Text style={styles.instructions}>
          diff between performance now in ctor and several seconds later: {this.state.performanceDotNow - this.state.ori
ginalPerformanceNow}
        </Text>
      </View>
    );
  }
}
```

**Comment by rozele** [comment]
FYI - I looked into the `nativePerformanceNow` hook a while ago and found that it wasn't as performant as just using the built in Chakra date time behavior. As far as I knew, it has millisecond level resolution...

**Comment by rozele** [comment]
Can you add a gif of the faulty behavior in your repro? I'm not seeing any issues? In my app, I basically see a counter that ticks every second...

**Comment by rozele** [comment]
@matthargett - please update with a valid repro.

**Comment by matthargett** [comment]
1 second resolution is not sufficient for performanceNow. It needs to be at least 33ms, but preferably 16.6ms, so a user can determine even something is taking longer than a single 69hz animation frame.

**Comment by rozele** [comment]
@matthargett - please provide a screenshot or something else that demonstrates the error. What hardware are you testing this on? If I use your sample code above in a Windows 10 Parallels VM and set the `setInterval` to 17ms, I get a pretty good indication that there is nothing wrong with the resolution of `performanceNow`.

**Comment by rozele** [comment]
Closing until repro confirmed.
