### ISSUE TITLE
Race condition when multiple apps load from debug server simultaneously

### ISSUE THREAD

**Issue by matthargett** [microsoft/react-native-windows#1783]
### Environment

1. `react-native -v`: 2.0.1 / master (pre-0.55)
4. `node -v`: 8.9.4
5. `npm -v`: 5.6

Then, specify:

- Target Platform: UWP

- Target Platform Version(s): RS4

- Target Device(s): Desktop and Xbox

- Development Operating System: Windows 10 RS4

- Visual Studio Version: VS2017 15.6.6

### Steps to Reproduce

The DevSupportManager interface does not support the multi-window/app use case. When multiple apps are loading from the debug server simultaneously, they all attempt write the bundle to ReactNativeDevBundle.js concurrently. Generally, only the last application to attempt to write to the file wins.
The suggested fix is for DevSupportManager to load the bundle from the debug server directly into memory (instead of writing to disk at a hardcoded path), to avoid this race condition.

cc @rigdern @reseul

**Comment by rozele** [comment]
Oops. Yeah, this isn't a good thing. I wonder if there is some window ID we can use to name the cached bundle.

**Comment by reseul** [comment]
Is this for UWP? 
Windows enforces a single app instance, at least for the desktop case (well, we caught it not fully enforcing that due to some race conditions, but just for hundred of milliseconds), and the multi-window case shouldn't matter since we load the bundle just once.
@matthargett can you clarify the scenario?

**Comment by matthargett** [comment]
When you have multiple apps/windows sharing the same ReactInstance, but also the race conditions you mention. Even though its only for ~100ms here and there, developers have lost days and days chasing ghosts trying to figure this out.

**Comment by reseul** [comment]
This is what I don't get.
1. Multiple apps are not really possible in UWP. The race condition is something we've seen, but it's not something affecting the devs usually (long story here)
2. Multiple windows case shares same instance, so same bundle. There's no race condition, bundle is loaded just once, and there's serialization.

Anyway, this may help WPF scenarios, I guess.

**Comment by NickGerleman** [comment]
Closing since we've stopped active development on the legacy react-native-windows stack.
