### ISSUE TITLE
Incorrect use of cached bundle when dev server is no longer running

### ISSUE THREAD

**Issue by matthargett** [microsoft/react-native-windows#1784]
### Environment

1. `react-native -v`: 2.0.1 / 0.54.0
4. `node -v`: 8.9.4
5. `npm -v`: 5.6

Then, specify:

- Target Platform: WPF

- Target Platform Version(s): .NET 4.6 on Windows 10 RS4

- Target Device(s): Desktop

- Development Operating System: WIndows 10 RS4

- Visual Studio Version: VS2017 15.6.6

### Steps to Reproduce

I was reproducing an issue on a branch using Playground.Net46 and had modified its index.windows.js. I used `react-native start` and pressed the Start button in VS2017 for Playground.Net46 project's Debug/x86 configuration.

After reproducing and filing that issue, I stopped Playground.Net46 in VS2017 with the red square stop button in the toolbar. I found a new issue, broke out of the `react-native start` to stop the dev server, and did a `git checkout -b newbranch`. VS2017 noticed the project file changes and asked if it should reload the solution. I selected yes. 

I made the changes in my branch, which did *not* include the changes to Playground.Net46's index.windows.js. When I started Playground.Net46 in this new branch, with *no* dev server running, it showed me the *old* index.windows.js with my previous modifications! I pressed control+R and it showed the correct redbox saying the dev server wasn't running. I started the dev server, pressed control+R again, and it correctly loaded the new (unmodified in the branch).

I feel like I've seen this before on UWP as well, maybe 6 months ago. Apologies if there's a duplicate issue.

**Comment by rozele** [comment]
Is this actually an issue? I thought Android had the same behavior for the cached bundle.

**Comment by rozele** [comment]
@matthargett I believe this is consistent on other react-native platforms. @pre10der89 wrote a PR to try to address this (#1906). Still not convinced this is really an "issue".

**Comment by pre10der89** [comment]
@rozele  @matthargett 

The behavior is also seen on Android, but is not seen on iOS.  When the JavaScript of an iOS application is changed when the application is not running, that change will be reflected when the iOS application is launched after the changes.

I feel that this is either a mistake, oversight, or this is a statement that you must only operate with hot reloading turned on.  That is assuming there is a way to start the development server with hot reloading without the application.   If the packager is always listening for changes when the application is not running it theoretically could incrementally update the bundle on each save.

I cannot imagine that the behavior we are seeing is what is intended.
