### ISSUE TITLE
Add fontVariant support to match upstream

### ISSUE THREAD

**Issue by matthargett** [Microsoft/react-native-windows#1790]
Upstream supports passing a JSON Array of fontVariant values for the fontVariant prop on text shadow nodes. This missing prop makes sharing RN components between iOS and Windows difficult.

From the RN docs at https://facebook.github.io/react-native/docs/text.html :
`
fontVariant: array of enum('small-caps', 'oldstyle-nums', 'lining-nums', 'tabular-nums', 'proportional-nums') (iOS)
`

Upstream code (note the prop is NSArray -- not a string/enum):
https://github.com/facebook/react-native/search?utf8=%E2%9C%93&q=fontVariant&type=

**Comment by rozele** [comment]
Looks like this is only supported on iOS, if there's no UWP API equivalent, I'd argue it doesn't belong in core.

**Comment by rozele** [comment]
Closing based on previous comment. 5 minutes of searching turned up no comparable APIs for UWP.
