### ISSUE TITLE
Expose baseline value for alignItems prop to match upstream RN Android

### ISSUE THREAD

**Issue by matthargett** [microsoft/react-native-windows#1793]
Reference:
https://github.com/facebook/react-native/search?utf8=%E2%9C%93&q=baselineFunction&type=

* Add BaselineFunction property to ReactShadowNode

* Implement MeasureBaseline static function in ReactTextShadowNode

**Comment by rozele** [comment]
What are those functions used for? I haven't seen them used in any core react-native views. Do you have an example of where it's used in a community module?
