### ISSUE TITLE
Text inline views break `pointerEvents` behavior

### ISSUE THREAD

**Issue by rozele** [microsoft/react-native-windows#1817]
### Environment

1. `react-native -v`: *
2. `npm ls rnpm-plugin-windows`: *
3. `npm ls react-native-windows`: *
4. `node -v`: *
5. `npm -v`: *
6. `yarn --version`: *

Then, specify:

- Target Platform: *

- Target Platform Version(s): *

- Target Device(s): *

- Development Operating System: *

- Visual Studio Version: *

### Steps to Reproduce

(Write your steps here:)

1. Create a `<Text>` component with a nested `<View>` component
2. Add the `<Text/>` component to parent `<View pointerEvents='none'>` component
3. Wrap the whole thing in a `<TouchableWithoutFeedback>` component and add an `onPress` handler.
4. Click the text inline view.

### Expected Behavior

When you click the text inline view, the Touchable should not fire the `onPress` handler.

### Actual Behavior

The `onPress` handler fires.

### Reproducible Demo

Here's a sample you can paste into the Playground app to reproduce:
```
class Playground extends Component {
  render() {
    return (
      <TouchableWithoutFeedback onPress={() => alert('Error!')}>
        <View 
          pointerEvents='none'
          style={styles.container}>
          <Text style={styles.welcome}>
            Click the inner view, hope you don't get an alert!
            <View style={{width: 10, height: 10, backgroundColor: 'red'}} />
          </Text>
        </View>
      </TouchableWithoutFeedback>
    );
  }
}
```

When you click the inline view (the red box), the alert fires even though the click occurred inside the context of `pointerEvents: none`.

**Comment by kmelmon** [comment]
This bug only applies to the legacy implementation of react-native-windows, which is no longer supported.
