### ISSUE TITLE
in-app products support?

### ISSUE THREAD

**Issue by emretekince** [Microsoft/react-native-windows#1818]
Hi, is there any in app products/purchases support for Windows Store?

**Comment by rozele** [comment]
Here is some documentation on how to enable this with UWP: https://docs.microsoft.com/en-us/windows/uwp/monetize/enable-in-app-product-purchases. This is not a core feature of React Native, please consider making a contribution to https://github.com/dooboolab/react-native-iap if you come up with any UWP solutions.

**Comment by UsamaDaood** [comment]
Hi there.
Any support for in-app purchases for the react-native-macos ??

Have you guys any idea about this?
@rozele @emretekince @alloy @Thristhart
