### ISSUE TITLE
ReactNative.Net46 project cannot be compiled with Release mode

### ISSUE THREAD

**Issue by exKAZUu** [Microsoft/react-native-windows#1819]
### Environment

1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.55.3

2. `npm ls rnpm-plugin-windows`:
`-- rnpm-plugin-windows@0.2.8

3. `npm ls react-native-windows`:
`-- react-native-windows@0.55.0-rc.0

4. `node -v`:
v9.11.1

5. `npm -v`:
5.6.0

6. `yarn --version`:
1.6.0

Then, specify:

- Target Platform: WPF

- Target Platform Version(s): .NET 4.6

- Target Device(s): Desktop (Win 10)

- Development Operating System: Windows

- Visual Studio Version: Visual Studio 2017

### Steps to Reproduce

1. `react-native init react_native_windows_failed_build_wpf --version=0.55.3`
1. `yarn add rnpm-plugin-windows --dev`
1. `react-native wpf`
1. Open `wpf\react_native_windows_failed_build_wpf.sln` with VS 2017
1. Confirm all the projects can be compiled with the `Debug` mode
1. Confirm all the projects CANNOT be compiled with the `Release` mode

### Expected Behavior

- The `ReactNative.Net46` project can be compiled with the `Release` mode

### Actual Behavior

- The `ReactNative.Net46` project CANNOT be compiled with the `Release` mode because some NuGet dependencies cannot be resolved as follows.

```
Error	CS0234	The type or namespace name 'Reactive' does not exist in the namespace 'System' (are you missing an assembly reference?)	ReactNative.Net46	`C:\Users\exKAZUu\Projects\react_native_windows_failed_build_wpf\node_modules\react-native-windows\ReactWindows\ReactNative.Net46\Bridge\Queue\DispatcherActionQueue.cs	5	Active
```

### Reproducible Demo

https://github.com/exKAZUu/react_native_windows_failed_build_wpf.git

**Comment by AnandMM** [comment]
rozele thanks for your help. I am not able to run the exe set up on wind 8.1 device. it works on windows 7. It shows me the error, application stopped working when i run the app.
