### ISSUE TITLE
`react-native run-wpf` starts a WPF app before starting Metro Bundler and an error is shown

### ISSUE THREAD

**Issue by exKAZUu** [microsoft/react-native-windows#1824]
### Environment

1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.55.3

2. `npm ls rnpm-plugin-windows`:
`-- rnpm-plugin-windows@0.2.8

3. `npm ls react-native-windows`:
`-- react-native-windows@0.55.0-rc.0

4. `node -v`:
v9.11.1

5. `npm -v`:
5.6.0

6. `yarn --version`:
1.6.0

Then, specify:

- Target Platform: WPF

- Target Platform Version(s): .NET 4.6

- Target Device(s): Desktop (Win 10)

- Development Operating System: Windows

- Visual Studio Version: Visual Studio 2017

### Steps to Reproduce

1. `react-native init react_native_windows_failed_build_wpf --version=0.55.3`
1. `yarn add rnpm-plugin-windows --dev`
1. `react-native wpf`
1. Open `wpf\react_native_windows_failed_build_wpf.sln` with VS 2017 (this step is needed to make `react-native run-wpf` work well)
1. `react-native run-wpf`

### Expected Behavior

- A WPF app starts after Metro Bundler starts and no error is shown.

### Actual Behavior

- A WPF app starts __*BEFORE*__ Metro Bundler starts and the following error is shown.

![image](https://user-images.githubusercontent.com/436237/39731216-39d8fbf0-52a1-11e8-9c2d-71265d9582ff.png)

### Reproducible Demo

https://github.com/exKAZUu/react_native_windows_failed_build_wpf.git

**Comment by rozele** [comment]
This isn't a problem in UWP - should be trivial to look at what's being done there to reproduce for WPF. That being said, we should merge the logic for the two solutions :-/
