### ISSUE TITLE
Element has no automation peer

### ISSUE THREAD

**Issue by amereii** [Microsoft/react-native-windows#1828]
### Environment

1. `react-native -v`:
>react-native-cli: 2.0.1
react-native: 0.55.2

2. `npm ls rnpm-plugin-windows`:
rnpm-plugin-windows@0.2.8

3. `npm ls react-native-windows`:
0.55.0-rc.0

4. `node -v`:
v8.1.3

5. `npm -v`:
5.0.3

6. `yarn --version`:
1.2.0

Then, specify:

- Target Platform:
UWP

- Target Platform Version(s):
 10.0.14393

- Target Device(s):
Desktop

- Development Operating System:
 Windows 10

- Visual Studio Version:
 Visual Studio 2017

### Steps to Reproduce

Sorry , As I don't know what is the error can how it is reproduced , I cannot provide a simplified demo , So please do the following 
```
git clone https://github.com/RooyeKhat-Media/iGap-Plus -b issue-windows-1825
cd iGap-Plus
yarn install
```

Then rename `node_modules/react-native-scrollable-tab-view/Button.ios.js` to `Button.windows.js` to skip packager error

then open project with Visual studio and run it , Register in app and in **Home** and **Call list** tab you have the error (If the list is not empty)

You can open https://web.igap.net/ and register in the web version and click my cloud icon at top
![image](https://user-images.githubusercontent.com/16239920/39813271-fefe2f1e-53a4-11e8-825c-a623516e26a2.png)
Then send a message to have non-empty room list in home tab

### Expected Behavior

In android and iOS version I have no issue , But in windows version `Element has no automation peer` error is occurred [recyclerlistview](https://github.com/Flipkart/recyclerlistview) component and [my custom component](https://github.com/RooyeKhat-Media/iGap-Plus/blob/master/src/components/BaseUI/FlatList/index.windows.js)

We have always error for **recyclerlistview** but sometimes for **my custom component**

See source of **my custom component** https://github.com/RooyeKhat-Media/iGap-Plus/blob/master/src/components/BaseUI/FlatList/index.windows.js it is too simple and we must not have error

@rozele What is **Element has no automation peer** exactly?

### Actual Behavior

![image](https://user-images.githubusercontent.com/16239920/39812863-85f15944-53a3-11e8-9107-c58dbfd767db.png)

### Reproducible Demo

https://github.com/RooyeKhat-Media/iGap-Plus

**Comment by reseul** [comment]
@gmangov A case where perhaps our consistency checks are too strong.
@amereii I was able to build and run the app, but can't get to register to the web app (site not found), etc.

**Comment by amereii** [comment]
@reseul We have a DNS issue , Please try again

**Comment by amereii** [comment]
@reseul @rozele Can you fix the issue?
How can I temporarily bypass this consistency check?

**Comment by reseul** [comment]
@amereii Ok, I tested and I think I found the issue. There's a bad interaction between the accessibility code and the "display: none" style, introduced with a fix in March.

We'll think of a fix (well, we know the solution, but it may take a little to fix). In between, of you have control over what's included in your project, you may patch the ```throw new InvalidOperationException("Element has no automation peer")``` from ReactWindows\ReactNative\Accessibility\AccessibilityHelper.cs into a simple ```return;```.

**Comment by rozele** [comment]
@reseul - If, while you think of a fix, you also think of a way to regression test, that would we super :-)

**Comment by reseul** [comment]
Should be fixed now.
