### ISSUE TITLE
React-Navigation's navigate  not working with WPF apps 

### ISSUE THREAD

**Issue by peterfei** [Microsoft/react-native-windows#1835]
Hi folks,
    when i used react-navigation's navigate in wpf,   e.g.
```
<Button title={'goto Details'} onPress={()=>{
   this.props.navigation.navigate('DetailScreen');
 }}/>
```
then an ERROR throw 

![error](https://t1.picb.cc/uploads/2018/05/17/2N2SZc.png)

Plz help me how to fix it ,thanks a lot!

**Comment by rozele** [comment]
Fixed by #1822
