### ISSUE TITLE
Exception: Unable to remove the file to be replaced

### ISSUE THREAD

**Issue by ecspress** [Microsoft/react-native-windows#1836]
It happens several times a day, Currently using react-native-storage ver 0.2.2. Any help in diagnosing this would be helpful. Should there be catch clause at the following line, or its left out for some specific reason?
https://github.com/Microsoft/react-native-windows/blob/c8ef244b91b7c3f2b7d01df44fb638439f3479a2/ReactWindows/ReactNative.Net46/Modules/Storage/AsyncStorageModule.cs#L103

--Update--
Adding the missing catch and initializing the error which is send with the callback seems to take care of the crash.

**Comment by rozele** [comment]
@ecspress can you paste the JavaScript code that is the source of the error? I suspect you may be missing a step in your app, like waiting for the promise to complete before trying another AsyncStorage operation.

**Comment by rozele** [comment]
Perhaps this issue should be filed against react-native-storage.
