### ISSUE TITLE
Exception when tearing down root view before it has finished being initialized

### ISSUE THREAD

**Issue by rigdern** [microsoft/react-native-windows#1837]
We have some scenarios where a RootView is torn down shortly after it's created. Code like this will probably repro the issue:

```c#
// Initialize new RootView
_reactHost.OnCreate(RootViewKey, initialProps);

// Tear down RootView
rootView.StopReactApplicationAsync();
```

We end up with an exception like this: `InvalidOperationException("Could not get tag for view.")`

The exception is in [`UIManagerModule.DetachRootViewAsync`](https://github.com/Microsoft/react-native-windows/blob/4cc252b2fc2ec223f4debfed8d90a1984a646494/ReactWindows/ReactNative.Shared/UIManager/UIManagerModule.cs#L186). `GetTag` throws because the initialization process hasn't added the tag to the map yet.

**Comment by kmelmon** [comment]
This bug only applies to the legacy implementation of react-native-windows which is no longer supported
