### ISSUE TITLE
onMouseOver fires on touch interactions as well

### ISSUE THREAD

**Issue by UsmanAli-10p** [microsoft/react-native-windows#1843]
On a `View`, the `onMouseOver` event fires for Touch Events as well. Is there a way to identify from the event arguments what the pointer type was (mouse, pen, touch)? I need to perform different actions on mouse and touch interaction.

**Comment by rozele** [comment]
In RNTester, we have an example for getting the pointer device type from the `onMouseOver` event:
https://github.com/Microsoft/react-native-windows/blob/dff981781f10c806c5b8846042da4ad116fde6e2/js/TouchableExample.js#L290-L307

We may want to consider limiting the scope of the `onMouseOver` event to non-touch for now though. Thoughts @reseul?

**Comment by UsmanAli-10p** [comment]
@rozele Thanks for the example but there are no `onMouseOver` events in that code. I tried it out on my code but the `event.nativeEvent` received in the event handler only contains the `target` property.
I agree that the scope of this method should be limited to mouse interactions only as the name implies.

**Comment by rozele** [comment]
This is really a general issue with react-native in that much of the cross-platform API has been designed around touch. I'm not sure there's much we can do here, as there probably isn't a one-size-fits-all solution to this.  My theory is that if UWP fires the event even for touch, then we should probably fire them to JavaScript and ask the end user to filter. It's really a question of what 80% of apps would expect.

I'm not sure why the nativeEvent does not include pointerType in your case.
