### ISSUE TITLE
Is yoman used in production?

### ISSUE THREAD

**Issue by pronebird** [Microsoft/react-native-windows#1845]
Hi,

I may be wrong but it seems that `yeoman-*` related stuff is only used in CLI tools so wouldn't it be wiser to move it to devDependencies? 

That should shrink the production builds and remove unused packages from production.

Cheers,
Andrej

**Comment by rozele** [comment]
React Native uses [metro](https://github.com/facebook/metro) to create the JavaScript bundle. metro uses a dependency graph to only grab necessary modules to include in the bundle that is packaged with the app, so yeoman should not be included in the release bundle.

**Comment by rozele** [comment]
#979 will remove yeoman anyway.
