### ISSUE TITLE
a white screen comes for a while after the splash screen

### ISSUE THREAD

**Issue by abhinashkumarjha** [Microsoft/react-native-windows#1851]
### Environment

1. `react-native -v`: 0.55.3/ cli: 2.0.1
2. `npm ls rnpm-plugin-windows`:  0.2.8
3. `npm ls react-native-windows`: 0.55.0-rc.0
4. `node -v`: 8.11.1
5. `npm -v`: 5.6.0

- Target Platform: UWP

- Target Platform Version(s): 4.6.11

- Target Device(s): Desktop

- Development Operating System: windows 10

- Visual Studio Version: 2017

### Steps to Reproduce

 Getting a white screen before the splashscreen. 

(Write your steps here:)
1. Compiled the app as per https://github.com/Microsoft/react-native-windows/blob/master/docs/GettingStarted.md
2. Changed default image in Assets and updated package.manifest as  <uap:SplashScreen Image="Assets\SplashScreen.png" /> (ref:  https://docs.microsoft.com/en-us/windows/uwp/launch-resume/add-a-splash-screen )

### Expected Behavior
SplashScreen should be shown and the next expected screen is the app homescreen.

### Actual Behavior
 i am getting a whitescreen for a while **after** the splashscreen image shows up and then the home screen of app appears.

**Comment by rozele** [comment]
@abhinashkumarjha - release or debug build?

**Comment by abhinashkumarjha** [comment]
debug build

**Comment by rozele** [comment]
Can you try building in Release configuration to see if that makes things better?

**Comment by reseul** [comment]
I think this is more or less expected. 
Currently the template-based app activates the main window after host.OnCreate returns. That method though is heavily asynchronous, and during the time JS engine is initialized, bundle is loaded and run, etc., the default background (white) of the panel backing the root view is seen.

A workaround is to set a background on that panel similar to whatever color is set for splash in the manifest.

**Comment by rozele** [comment]
Closing given @reseul's workaround.
