### ISSUE TITLE
Issue with webview two way communication bridge on WPF platform

### ISSUE THREAD

**Issue by ncomo11** [microsoft/react-native-windows#1858]
### Environment
react-native -v:
react-native-cli: 2.0.1
react-native: 0.55.4

npm ls rnpm-plugin-windows:
rnpm-plugin-windows@0.2.8

npm ls react-native-windows:
react-native-windows@0.55.0-rc.0

node -v:
v6.11.1

npm -v:
3.10.10

yarn --version:

Then, specify:

Target Platform: WPF
Target Platform Version(s): .NET 4.6.0 WPF
Target Device(s): Desktop
Development Operating System: Windows 10 Pro version: 1709
Visual Studio Version: 2017

### Steps to Reproduce

(Write your steps here:)

1. react-native init test
2. cd test
3. npm install --save-dev rnpm-plugin-windows
4. npm install react-native
5. react-native wpf
6. react-native run-wpf 
7. Modify code to include webview and communicate using webview bridge  to establish two way communication betqween react-native and webview [code attached]

### Expected Behavior

Code under Webview's 'onMessage' should get called when message send from webview using 'postMessage'

### Actual Behavior
When message sent from react-native to webview it works fine but when message sent from webview to react-native it doesn't work  i.e. technically Webview component's 'injectedJavaScript' attribute works but 'onMessage' never gets called

<WebView
            source = {testFile}
            injectedJavaScript={'messageFromRN()'}
            onNavigationStateChange={(navEvent)=> console.log(navEvent.jsEvaluationValue)}
            onMessage={(event)=> console.log(event.nativeEvent.data)}
            style={{flex: 1}}
         />

### Reproducible Demo
Code with important files attached which can be added to any wpf based sample project.
Instructions:

1. replace App.windows.js and 
2. copy src folder 

[code.zip](https://github.com/Microsoft/react-native-windows/files/2069590/code.zip)

**Comment by ncomo11** [comment]
@matthargett Any comment on this issues like its a known issue, it is in plan something like that?

FYI UWP also has an issue below is my observation:
1. UWP: WebView's 'injectedJavaScript' doesn't work but 'onMessage' is working fine
2. WPF: 'injectedJavaScript' is working but 'onMessage' doesn't work

Let me know if I am not clear any need more details about this issue.

**Comment by nagisetty1** [comment]
> @matthargett Any comment on this issues like its a known issue, it is in plan something like that?
> 
> FYI UWP also has an issue below is my observation:
> 
> 1. UWP: WebView's 'injectedJavaScript' doesn't work but 'onMessage' is working fine
> 2. WPF: 'injectedJavaScript' is working but 'onMessage' doesn't work
> 
> Let me know if I am not clear any need more details about this issue.

please may i know how to inject in WPF? any sample great help?
 WPF: 'injectedJavaScript' is working but 'onMessage' doesn't work
