### ISSUE TITLE
WPF: Wrapping <TouchableHighlight> inside a <TouchableWithoutFeedback>does not respond to touch event.

### ISSUE THREAD

**Issue by piyush965** [microsoft/react-native-windows#1861]
### Environment

1. `react-native -v`: 0.55
2. `npm ls rnpm-plugin-windows`:
3. `npm ls react-native-windows`:
4. `node -v`:
5. `npm -v`:
6. `yarn --version`:

Then, specify:

- Target Platform:
WPF

- Target Platform Version(s):
4.6

- Target Device(s):
Surface Pro

- Development Operating System:
Windows

- Visual Studio Version:
2017

- Build Configuration:
Debug
### Steps to Reproduce

(Write your steps here:)
On touching "Press me!" button, alert does not appeared but when clicking from mouse - it appeared. 
`<TouchableWithoutFeedback>
	<View style={{flex:1}}>
		<TouchableHightlight
		onPress = {()=>alert("Button touched"}>
			<Text>Press me! </Text>
		</TouchableHightlight>
	</View>
</TouchableWithoutFeedback>`

### Expected Behavior

(Write what you thought would happen.)
I expect it should respond to touch event and Alert should appear. This way it works in UWP, iOS and Android.

### Actual Behavior

Alert doesn't appeared on touch event when parent view is wrapped by TouchableWithoutFeedback in WPF application.

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by piyush965** [comment]
@rozele Any clue why this is not working in WPF?

**Comment by matthargett** [comment]
I think @pre10der89 had an issue like this. Maybe they fixed it in the @blujeans fork and it hasn't been upstreamed?

**Comment by piyush965** [comment]
@matthargett I just tried on @bluejeans fork and able to reproduce issue there also.
