### ISSUE TITLE
error CS0433: The type 'ReactNativeHost' exists in both 'ReactNative.Net46, Version=1.0.0 .0, Culture=neutral, PublicKeyToken=null' and 'ReactNative, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' [D:\ React\ReactClicProject\windows\ReactClicProject\ReactClicProject.csproj]

### ISSUE THREAD

**Issue by tamajitchakraborty** [Microsoft/react-native-windows#1865]
### Environment

1. `react-native -v`: 
    react-native-cli: 2.0.1
    react-native: 0.55.4
2. `npm ls rnpm-plugin-windows`:
    -- rnpm-plugin-windows@0.2.8
3. `npm ls react-native-windows`:
    -- react-native-windows@0.55.0-rc.0
4. `node -v`: v10.4.0
5. `npm -v`: 6.1.0
6. `yarn --version`:
react-native run-windows

React log
`Scanning folders for symlinks in D:\React\ReactClicProject\node_modules (90ms)
Restoring NuGet packages
Building D:/React/ReactClicProject/windows/ReactClicProject.sln
Found MSBuild v15.0 at C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin
Building Solution: D:/React/ReactClicProject/windows/ReactClicProject.sln
Build configuration: Debug
Build platform: x86
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Micro
soft.AppXPackage.Targets(5552,5): warning APPX1901: The DefaultLanguage property is either missing from the project fil
e or does not have a value. The fallback language is set to the Visual Studio language: en-US. [D:\React\ReactClicProje
ct\node_modules\react-native-windows\Yoga\csharp\Yoga\Yoga.Universal.vcxproj]
MainReactNativeHost.cs(9,33): error CS0433: The type 'ReactNativeHost' exists in both 'ReactNative.Net46, Version=1.0.0
.0, Culture=neutral, PublicKeyToken=null' and 'ReactNative, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' [D:\
React\ReactClicProject\windows\ReactClicProject\ReactClicProject.csproj]
App.xaml.cs(24,25): error CS0433: The type 'ReactNativeHost' exists in both 'ReactNative.Net46, Version=1.0.0.0, Cultur
e=neutral, PublicKeyToken=null' and 'ReactNative, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' [D:\React\Reac
tClicProject\windows\ReactClicProject\ReactClicProject.csproj]
MainReactNativeHost.cs(25,33): error CS0433: The type 'IReactPackage' exists in both 'ReactNative.Net46, Version=1.0.0.
0, Culture=neutral, PublicKeyToken=null' and 'ReactNative, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' [D:\R
eact\ReactClicProject\windows\ReactClicProject\ReactClicProject.csproj]
MainReactNativeHost.cs(11,32): error CS0115: 'MainReactNativeHost.MainComponentName': no suitable method found to overr
ide [D:\React\ReactClicProject\windows\ReactClicProject\ReactClicProject.csproj]
MainReactNativeHost.cs(14,30): error CS0115: 'MainReactNativeHost.UseDeveloperSupport': no suitable method found to ove
rride [D:\React\ReactClicProject\windows\ReactClicProject\ReactClicProject.csproj]
MainReactNativeHost.cs(19,35): error CS0115: 'MainReactNativeHost.JavaScriptMainModuleName': no suitable method found t
o override [D:\React\ReactClicProject\windows\ReactClicProject\ReactClicProject.csproj]
MainReactNativeHost.cs(25,48): error CS0115: 'MainReactNativeHost.Packages': no suitable method found to override [D:\R
eact\ReactClicProject\windows\ReactClicProject\ReactClicProject.csproj]
App.xaml.cs(24,41): error CS1715: 'App.Host': type must be 'ReactNativeHost' to match overridden member 'ReactApplicati
on.Host' [D:\React\ReactClicProject\windows\ReactClicProject\ReactClicProject.csproj]
App.xaml.cs(8,26): error CS0534: 'App' does not implement inherited abstract member 'ReactApplication.Host.get' [D:\Rea
ct\ReactClicProject\windows\ReactClicProject\ReactClicProject.csproj]
App.xaml.cs(10,26): error CS0433: The type 'ReactNativeHost' exists in both 'ReactNative.Net46, Version=1.0.0.0, Cultur
e=neutral, PublicKeyToken=null' and 'ReactNative, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' [D:\React\Reac
tClicProject\windows\ReactClicProject\ReactClicProject.csproj]
Build failed with message Error: Command failed: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\msbuild.exe" "D:/React/ReactClicProject/windows/ReactClicProject.sln" /clp:NoSummary;NoItemAndPropertyList;Verbosity=quiet /nologo /p:Configuration=Debug /p:Platform=x86 /p:AppxBundle=Never /p:PlatformToolset=v141 /p:VisualStudioVersion=15.0. Check your build configuration.`

**Comment by tamajitchakraborty** [comment]
it was build problem.

**Comment by clarodanesh** [comment]
I went to the csproj file for my project, located at `window/projectName/projectName.csproj` and removed the ProjectReference for ReactNative.Net64.csproj but now Im getting a totally different error

Now it compiles and loads the package but im getting the error `An item with the same key has already been added. Key: RCTSimpleText`
