### ISSUE TITLE
Children management overrides for virtual shadow node

### ISSUE THREAD

**Issue by tdzl2003** [microsoft/react-native-windows#1870]
### Environment

1. `react-native -v`: 0.55.4
2. `npm ls rnpm-plugin-windows`: 0.2.8
3. `npm ls react-native-windows`: 0.55.0-rc.0
4. `node -v`: 10.4.0
5. `npm -v`:6.1.0
6. `yarn --version`: 1.7.0

Then, specify:

- Target Platform: WPF

- Target Platform Version(s): .NET 4.6.1

- Target Device(s):Desktop

- Development Operating System: Windows

- Visual Studio Version: Visual Studio 2017 Community

- Build Configuration: Debug

### Steps to Reproduce

What I'm doing is try to bridge wpf Menu to react-native-windows. The root view `Menu` is a virtual anchor node with full flex styles, and children view `MenuItem` is virtual node without any flex styles. I would like to add them to native Menu.Items/MenuItem.Items when a children was rendered in jsx.

Currently, UIManager will not create & update native view for a virtual shadow node. And there's no methods for that shadow node to override when a child was added or removed from it.

I thought overriding `AddChildAt` `RemoveChildAt` method for `ReactShadowNode` may be best option but they are not virtual methods.

Any suggesstion for doing this? Or making these two methods virtual is the best idea?

**Comment by rozele** [comment]
@tdzl2003 - in theory you don't need to override the `AddChildAt` or `RemoveChildAt` behaviors. In fact, it is not safe to update from these methods. Is it not possible to just create a view manager for the MenuItems? Are they not derived from DependencyObject?
