### ISSUE TITLE
Non-negative number required. Parameter name: width

### ISSUE THREAD

**Issue by Hirurgo** [microsoft/react-native-windows#1875]
### Environment
1. `react-native 0.55.2`:
2. `rnpm-plugin-windows 0.2.8 `:
3. `react-native-windows 0.52.0`:
4. `node 9.8.0`:
5. `npm -v 5.6.0`:

Then, specify:
- Target Platform: UWP
- Target Platform Version(s): 10.0.14393
- Target Device: Desktop
- Development Operating System: Windows 10
- Build Configuration: Debug

### Steps to Reproduce

1. Set alignItems: 'center' on parent component 
2. Put to parent component View  without any width

### Expected Behavior

Child View fill 100% of width

### Actual Behavior

Crash with error
![capture](https://user-images.githubusercontent.com/24648180/42026069-d9fba3e4-7ace-11e8-8c52-e1f9374b8d77.PNG)

**Comment by rozele** [comment]
Thanks @Hirurgo - can you paste a sample React component that includes the bug (or point to a repo with this behavior)?

**Comment by rozele** [comment]
@Hirurgo - have you updated to react-native@0.57? In react-native-windows@0.57 we've updated Yoga for the first time in some time, hoping that may have solved the issue.

**Comment by Hirurgo** [comment]
not reproduced on rn-windows 0.57.0-rc5
