### ISSUE TITLE
Documentation: Add how to hide Performance stats black boxes

### ISSUE THREAD

**Issue by creambyemute** [Microsoft/react-native-windows#1878]
It's not a problem with code so I'll just provide the screenshot of which black boxes I'm talking about:

I haven't found out how to hide the black boxes in the upper left and right corner when running uwp in dev mode, so I'd like to document it so everybody can find it but I don't know what has to be done in order to hide them.

![uwp_black_boxes](https://user-images.githubusercontent.com/3519121/42164442-4ecbdd76-7e06-11e8-83d7-27a02df78a5b.png)

**Comment by rozele** [comment]
Thanks @creambyemute - with the recent addition of the `ReactApplication` base class it became more opaque how this would be done. Previously, you would just remove this from your `App.xaml.cs` file. I think [these lines](https://github.com/Microsoft/react-native-windows/blob/master/ReactWindows/ReactNative/ReactApplication.cs#L85-L88) should be removed from the `ReactApplication` base class and make it opt-in by overriding a lifecycle method on the XAML Application base class.

**Comment by creambyemute** [comment]
@rozele Thanks for the explanation, and indeed setting `EnableFrameRateCounter` to false in `ReactApplication` disables those two boxes.

I think we could add this to the documentation until it's configurable in the UserProject again.
