### ISSUE TITLE
TextInput in ScrollView wrong focus behavior

### ISSUE THREAD

**Issue by Hirurgo** [microsoft/react-native-windows#1882]
### Environment
react-native 0.55.2:
rnpm-plugin-windows 0.2.8:
react-native-windows 0.52.0:
node 9.8.0:
npm -v 5.6.0:
Then, specify:

Target Platform: UWP
Target Platform Version(s): 10.0.14393
Target Device: Desktop
Development Operating System: Windows 10
Build Configuration: Debug

### Steps to Reproduce
put TextInput in ScrollView components

### Expected Behavior

 1.Tap to ScrollView area **don't** set focus on TextInput
 2.Tap to ScrollView area **don't**  drop focus from TextInput if it set

### Actual Behavior

 1.Tap to ScrollView area set focus on TextInput
 2.Tap to ScrollView area drop focus from TextInput if it set

    <ScrollView  style={{ backgroundColor: 'pink' }}  >
      <TextInput placeholder="Input" />
    </ScrollView>

![screen](https://user-images.githubusercontent.com/24648180/42318711-90ada2ac-8058-11e8-96f2-b134dd6001ad.gif)

**Comment by Hirurgo** [comment]
focus sets only on first child, and the obvious solution is put invisible TextInput on first position in ScrollView like this: 
`    <ScrollView>
     <TextInput style={{ width: 0,  height: 0,  margin: 0,  padding: 0,  borderWidth: 0  } } />
     <TextInput placeholder="Name" />
    </ScrollView>
`

**Comment by Hirurgo** [comment]
<ScrollView  style={{ backgroundColor: 'pink' }}  >
  <TextInput placeholder="Input" />
</ScrollView>

**Comment by rozele** [comment]
What is the basis for the expected behavior:
* Consistency with iOS / Android
* Consistency with native UWP behavior
* something else?

**Comment by Hirurgo** [comment]
@rozele In our project we work with IOS, Andoroid and UWP platforms, and i expect that same code constructions have same behavior on all platforms.

**Comment by rozele** [comment]
cc @reseul - any thoughts on why TextInput would auto-focus here?

**Comment by Hirurgo** [comment]
maybe it help, find another inconsistency with focus behavior

```
      <View style={{ height: '100%', backgroundColor: 'green' }} >
        <TextInput />
      </View>
```

**Steps reproduce:**
- Tap to TextIput
- Tap on View outside TextInput

**Expected result:**
- Nothing happened (like in Android and iOS)

**Actual result:**
- The focus disappears from TextIput
