### ISSUE TITLE
Exceptions from a JS call to a native sync hook aren't propagated back to JS

### ISSUE THREAD

**Issue by matthargett** [Microsoft/react-native-windows#1883]
A TODO item, with a PR coming soon. This is a reminder.

Right now, if a native exception is thrown by a synchronous call into a native module, that exception/error is not propagated back to the JS. This is a big blind spot for crash analytics, but also retry/recovery mechanisms.

**Comment by piyush965** [comment]
@matthargett  Not sure if this is the same I faced. **Scenario is** - In JS "fetch" GET method if I provide invalid URI (ex - !@#$) I got an exception but it was not reported to JS fetch catch block (Instead red screen appeared). Exception occurred at IReflectionReactDelegateFactory.cs file Line no 135 - NativeArgumentsParseException.

**Comment by rozele** [comment]
@piyush965 - that sounds like a different bug. Can you file another issue with a repro?

**Comment by piyush965** [comment]
@rozele Filed an issue - https://github.com/Microsoft/react-native-windows/issues/1895

**Comment by matthargett** [comment]
yes, that's a different issue. this is a more general problem not specific to network requests.

**Comment by rozele** [comment]
Hrm - seems like this is an actual bug now for react-native 0.58, as all view managers potentially call the sync method UIManager.getConstantsForViewManager, so view managers like Touchable* should throw an exception back to JS.
