### ISSUE TITLE
Menubar support

### ISSUE THREAD

**Issue by bukharim96** [Microsoft/react-native-windows#1891]
Hi,

I notice that RNW does not have an API to create app menubars. Any solutions?

Example:
<p align="center" ><img src="https://www.isunshare.com/images/article/windows-10/show-or-hide-menu-bar-favorites-bar-command-bar-status-bar-in-ie/select-an-ie-toolbar.png"></p>

**Comment by rozele** [comment]
It should be possible to create a custom view manager that adds this menu bar, but it's not a feature that is likely to be added to this repo. Please refer to the [custom native components doc](https://github.com/Microsoft/react-native-windows/blob/master/docs/NativeComponentsWindows.md) for more details on how to implement.

**Comment by bukharim96** [comment]
Thanks for the info. It's been helpful.
