### ISSUE TITLE
Updating from 0.52.0 to newer versions (master or 0.55.0-rc.0)

### ISSUE THREAD

**Issue by andreizhukv** [Microsoft/react-native-windows#1898]
### Environment

1. `react-native -v`: 0.55.2
2. `npm ls rnpm-plugin-windows`: 0.2.8
3. `npm ls react-native-windows`: master
4. `node -v`: 8.11.1
5. `npm -v`: 5.6.0

- Target Platform: UWP

- Target Platform Version(s): 10.0.14393

- Target Device(s): Desktop

- Development Operating System: Windows

- Visual Studio Version: 2017

- Build Configuration: Debug

### Steps to Reproduce

1. I have a working application using react-native-windows 0.52.0
2. Update rnw to current master
3. npm install
4. Open sln using visual studio
5. Build debug or release
6. Create appx file using visual studio

### Actual Behavior
For debug I have an the same issue as in issue 1846
For release my application is closing on start

**Comment by rozele** [comment]
Can you please provide additional details about the source of the crash (e.g., stack trace)?

**Comment by andreizhukv** [comment]
in Microsoft-Windows-TWinUI/Operational log I see:
pplications and Services Logs\Microsoft\Windows\Apps\Microsoft-Windows-TWinUI/Operational event log

**Comment by andreizhukv** [comment]
I have removed old solution and generated a new one from scratch using updated react-native-windows version and it works fine. MainPage.cs was changed to MainReactNativeHost.cs, App.xaml was updated and etc. So it is not simply update version in package.json. It would be good to add FAQ or update WIKI with information how to update react-native-windows version.
