### ISSUE TITLE
Native Views Frame doesn't allow to goBack

### ISSUE THREAD

**Issue by Noralina** [Microsoft/react-native-windows#1912]
### Environment
1. `react-native -v`: 0.55.0
2. `npm ls rnpm-plugin-windows`: 0.2.8
3. `npm ls react-native-windows`: 0.55.0-rc.0
4. `node -v`: 8.11.3
5. `npm -v`: 5.6.0
6. `yarn --version`: 1.7.0

- Target Platform: UWP
- Target Platform Version(s):10.0.14393.0
- Target Device(s): Desktop
- Development Operating System: Windows 10 Desktop
- Visual Studio Version: 2017
- Build Configuration: Debug (but all the same for this issue)

### Steps to Reproduce
1. Install a fresh react-native app
2. Install react-native-windows (like in the Get Started)
3. then, open the solution in VS and create a new native module in ReactNative/Views/Radaee/RadaeeManager.cs
4. Import an external lib RadaeePdf (it's a library to edit pdf in a native app, you can find it on their website)
5. reference Radaee to your app

RadaeeManager.cs

        class RadaeeManager : SimpleViewManager<MainPage>
        {
            public MainPage _mainPage;
            public override string Name
            {
                get
                {
                    return "RCTRadaeeView";
                }
            }

            public RadaeeManager()
            {
                _mainPage = new MainPage();
            }

            protected override MainPage CreateViewInstance(ThemedReactContext reactContext)
            {
                return _mainPage;
            }
        }

MainPage.xaml.cs

        public sealed partial class MainPage : Page
        {
            public MainPage()
            {
                this.InitializeComponent();
            }

            async private void BrowsFile(Object sender, RoutedEventArgs e)
            {
                FileOpenPicker filePicker;
                filePicker = new FileOpenPicker();
                filePicker.ViewMode = PickerViewMode.List;
                filePicker.SuggestedStartLocation = PickerLocationId.DocumentsLibrary;
                filePicker.FileTypeFilter.Add(".PDF");
                filePicker.FileTypeFilter.Add(".pdf");
                StorageFile file = await filePicker.PickSingleFileAsync();
                if (file != null)
                {
                    IRandomAccessStream stream = await file.OpenAsync(FileAccessMode.ReadWrite);
                    if (stream != null)
                    {
                        Frame rootFrame = Window.Current.Content as Frame;
                        rootFrame.Navigate(typeof(PDFReaderPage), stream);
                    }
                }
            }
        }

PDFReaderPage.xaml.cs

        public sealed partial class PDFReaderPage : Page, PDFView.PDFViewListener
        {
            IRandomAccessStream m_stream;

            public PDFReaderPage()
            {
                this.InitializeComponent();
                Windows.UI.Core.CoreWindow rcWindow = Window.Current.CoreWindow;
                Rect rcScreen = rcWindow.Bounds;
                mPDFView.Width = rcScreen.Width;
                mPDFView.Height = rcScreen.Height;
            }

            protected override void OnNavigatedTo(NavigationEventArgs e)
            {
                m_stream = (IRandomAccessStream)e.Parameter;
                m_doc = new PDFDoc();
                PDF_ERROR err = m_doc.Open(m_stream, "");
                switch (err)
                {
                    case PDF_ERROR.err_ok:
                        m_view = new PDFViewVert(mPDFView);
                        m_view.vOpen(m_doc, 4, 0xFFCCCCCC, this);
                        initOptionPanels();
                        break;
                    case PDF_ERROR.err_password:
                        break;
                    default:
                        break;
                }
            }
         }

With this code, I can't go back to my react app.
But if I don't use the Frame.Navigate, I can go back but the interaction with the pdf is broken. see below
RadaeeManager.cs

        class RadaeeManager : SimpleViewManager<PDFReaderPage>
        {
            public PDFReaderPage _mainPage;
            public override string Name
            {
                get
                {
                    return "RCTRadaeeView";
                }
            }

            public RadaeeManager()
            {
                _mainPage = new PDFReaderPage();
            }

            protected override PDFReaderPage CreateViewInstance(ThemedReactContext reactContext)
            {
                return _mainPage;
            }
        }

PDFReaderPage.xaml.cs

        public sealed partial class PDFReaderPage : Page, PDFView.PDFViewListener
        {
            IRandomAccessStream m_stream;

            public PDFReaderPage()
            {
                this.InitializeComponent();
                Windows.UI.Core.CoreWindow rcWindow = Window.Current.CoreWindow;
                Rect rcScreen = rcWindow.Bounds;
                mPDFView.Width = rcScreen.Width;
                mPDFView.Height = rcScreen.Height;
                openFile();
            }

            protected override void openFile(NavigationEventArgs e)
            {
                ApplicationData data = ApplicationData.Current;
                StorageFile file = await data.LocalCacheFolder.GetFileAsync("pdf.pdf");
                m_stream = await file.OpenAsync(FileAccessMode.ReadWrite); m_doc = new PDFDoc();
                m_stream = (IRandomAccessStream)e.Parameter;
                m_doc = new PDFDoc();
                PDF_ERROR err = m_doc.Open(m_stream, "");
                switch (err)
                {
                    case PDF_ERROR.err_ok:
                        m_view = new PDFViewVert(mPDFView);
                        m_view.vOpen(m_doc, 4, 0xFFCCCCCC, this);
                        initOptionPanels();
                        break;
                    case PDF_ERROR.err_password:
                        break;
                    default:
                        break;
                }
            }
         }

This is the way I can make Radaee that work great but I can't go back to my app.

### Expected Behavior
I need to open a native view to edit a pdf and then I need to go back to my app

### Actual Behavior
If I open my radaee page with a Frame.Navigate, I can't go back to my react app.
But if I open my radaee page with a simple return, I can't use the plugin correctly.

Thanks for your help!

**Comment by rozele** [comment]
@Noralina - I think the problem here is modeling your PDF component as a page - I think instead you want to model it as a basic FrameworkElement and move your initialization logic from the `OnNavigatedTo` method to the `SimpleViewManager` implementation.

**Comment by Noralina** [comment]
@rozele thank you for your response. I will try these two component.

**Comment by Noralina** [comment]
find a solution by opening a new window like this

        var currentAV = ApplicationView.GetForCurrentView();
        var newAV = CoreApplication.CreateNewView();
        await newAV.Dispatcher.RunAsync(CoreDispatcherPriority.Normal, async () => {
          var newWindow = Window.Current;
          var newAppView = ApplicationView.GetForCurrentView();
          newAppView.Title = file.Name;
          var frame = new Frame();
          frame.Navigate(typeof(PDFReaderPage), parameters);
          newWindow.Content = frame;
          newWindow.Activate();
          await ApplicationViewSwitcher.TryShowAsStandaloneAsync(newAppView.Id, ViewSizePreference.Default, currentAV.Id, ViewSizePreference.Default);
        });
