### ISSUE TITLE
react-native windows not working

### ISSUE THREAD

**Issue by prabhumanoharan** [Microsoft/react-native-windows#1920]
### Environment

1. `react-native -v`: 0.55.0-rc.0
2. `npm ls rnpm-plugin-windows`: rnpm-plugin-windows@0.2.8
3. `npm ls react-native-windows`: react-native-windows@0.55.0-rc.0
4. `node -v`: v10.7.0
5. `npm -v`: 6.2.0
6. `yarn --version`:

Then, specify:

- Target Platform: UWP

- Target Platform Version(s): 10.0.14393

- Target Device(s): Desktop

- Development Operating System: Windows

- Visual Studio Version: Visual Studio 2017

- Build Configuration:

### Steps to Reproduce

(Write your steps here:)

1. react-native init --version="0.55.0-rc.0" MyProject
2. npm i --save-dev rnpm-plugin-windows
3. npm i --save-dev react-native-windows
4. react-native windows

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

Could not find react-native-windows@0.55.*.

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by cdevroe** [comment]
I'm having the same error, except I'm on React Native 0.56.0.

**Comment by prabhumanoharan** [comment]
The fix is must specify the windows version. Now its works.
```
react-native windows --windowsVersion 0.55.0-rc.0
```

**Comment by cdevroe** [comment]
Thank you.
