### ISSUE TITLE
I can't do react-native run-windows after react-native link

### ISSUE THREAD

**Issue by paulbx81** [microsoft/react-native-windows#1924]
### Environment

1. `react-native -v`: 0.55.4
2. `npm ls rnpm-plugin-windows`: 0.2.8
3. `npm ls react-native-windows`: 0.55.0-rc.0
4. `node -v`: 9.11.1
5. `npm -v`: 6.1.0
6. `yarn --version`: 1.6.0

Then, specify:

- Target Platform: UWP

- Target Platform Version(s): 17134.165 UWP

- Target Device(s): Windows Surface Pro 3

- Development Operating System: Windows 10 17134.165

- Visual Studio Version: VS 2017

- Build Configuration: Debug

### Steps to Reproduce

1. do "react-native link" command
2. try to react-native run-windows

### Expected Behavior

react-native link shouldn't break my react-native run-windows

(Write what you thought would happen.)

### Actual Behavior

I can't build my app after react-native link : 

![link1](https://user-images.githubusercontent.com/40029591/43716067-f9e530da-9982-11e8-9686-b59059013d16.PNG)

![error](https://user-images.githubusercontent.com/40029591/43716069-fbe30196-9982-11e8-93e9-b1127d64fd09.PNG)

If i want **run-windows** again, i have to do **react-native windows** first and create news .sln.

But if i do react-native link again i have error again.

**Comment by paulbx81** [comment]
I tried to do : 

> .\node_modules\react-native-windows\local-cli\runWindows\.nuget\nuget.exe restore .\Windows\TabCom.sln

and i have this error : 

![error2](https://user-images.githubusercontent.com/40029591/43717613-61bc7f06-9988-11e8-8bc9-c8c700366e29.PNG)

**Comment by rozele** [comment]
Thanks @paulbx81 - can you open the solution in Visual Studio 2017 and see if there are any more details there?

**Comment by paulbx81** [comment]
@rozele No more details if i open the solution in visual studio 2017.

But if i try to deploy in debug and x86 : 

![error3](https://user-images.githubusercontent.com/40029591/43905952-6b6950d0-9bf2-11e8-8324-0cfbf3a768d4.PNG)

**Comment by rozele** [comment]
I'm confused why there is a ReactNative.Net46 dependency in your solution if you are targeting UWP. Can you remove that project from your solution and see if that fixes the issue?

**Comment by chrisglein** [comment]
No response in over a year, closing.
