### ISSUE TITLE
`react-native run-windows` build error

### ISSUE THREAD

**Issue by cdevroe** [Microsoft/react-native-windows#1925]
I'm having an issue building a vanilla React Native app using `react-native run-windows` command that isn't listed on the [Setup Troubleshooting](https://github.com/Microsoft/react-native-windows/blob/master/docs/SetupTroubleshooting.md) document.

I'm very likely not doing something right in Visual Studio 2017 as I'm not seeing the same screens as the documentation shows. Perhaps VS has been updated and looks different.

See details below.

### Environment

1. `react-native -v`:

react-native-cli: 2.0.1
react-native: 0.56.0

2. `npm ls rnpm-plugin-windows`: rnpm-plugin-windows@0.2.8 
3. `npm ls react-native-windows`: react-native-windows@0.55.0-rc.0 
4. `node -v`: v10.7.0 
5. `npm -v`: 6.1.0

- Target Platform: UWP
- Target Platform Version(s): 10.0.14393
- Target Device(s): Desktop
- Development Operating System: Windows 10 - 1803 - 17134.191
- Visual Studio Version: 2017 CE
- Build Configuration: Debug

### Steps to Reproduce

1. Follow [Getting Started](https://github.com/Microsoft/react-native-windows/blob/master/docs/GettingStarted.md) guide step-by-step
2. At `react-native run-windows` get error

### Expected Behavior

I would expect a native Windows 10 app to open and run.

### Actual Behavior

Build errors. (see image) 
![capture](https://user-images.githubusercontent.com/19237/43734764-c58ea484-9986-11e8-89b0-edb0e8404866.JPG)

**Comment by piyush965** [comment]
@cdevroe Go to this path - node_modules/react-native-windows/Yoga/csharp/Yoga , open up the solution in VS2017 and compile the build. This should work, in case if you are unable to find any files inside Yoga folder - Copy if from Github source project and place it at the same path in your project directory.

**Comment by rozele** [comment]
Closing, and opening a new issue to reflect that we need a document that covers the compatibility matrix.
