### ISSUE TITLE
WPF: onChangeText of TextInput resets text cursor and sometimes looses typed characters

### ISSUE THREAD

**Issue by acuntex** [microsoft/react-native-windows#1936]
### Environment
1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.55.4
2. `npm ls rnpm-plugin-windows`:
`-- rnpm-plugin-windows@0.2.8
3. `npm ls react-native-windows`:
`-- react-native-windows@1000.0.0  (github:Microsoft/react-native-windows)
4. `node -v`:
v10.3.0
5. `npm -v`:
6.1.0

Then, specify:

- Target Platform:
WPF

- Target Platform Version(s):
.NET 4.6.1

- Target Device(s):
Desktop

- Development Operating System:
Windows

- Visual Studio Version:
Visual Studio 2017

- Build Configuration:
Debug, DebugBundle, Release, ReleaseBundle

### Steps to Reproduce

Create a TextInput field which fires the onChangeText-event and sets state in this handler.
```
                    <View style={{height: 100}}>
                        <TextInput style={{height: 50, color: "black"}} value={this.state.myValue}
                                   onChangeText={(value) => this.setState({myValue: value})}
                        />
                        <Text>{this.state.myValue}</Text>
                    </View>
```

### Expected Behavior

When typing (even when typing fast) the text cursor should not change to the position of the text cursor. No typed character should be lost.

### Actual Behavior

When typing (mostly when typing fast) the text cursor gets reset, e.g. after the first typed character. Sometimes even characters in between get lost, as if you didn't type them.
This also happens, when something else is setting the state (even unrelated values).

**Comment by acuntex** [comment]
Happens btw. also on a Secure TextInput (password field)

**Comment by rolodex** [comment]
Known issue with react native core. See 21'40" https://youtu.be/plTTFqbEiEE

**Comment by sadiqkhoja** [comment]
@rozele any way around this?
