### ISSUE TITLE
Running react-native on windows via react-native run-windows gives error "cannot read documentDir" of null 

### ISSUE THREAD

**Issue by mahmoodFcis** [Microsoft/react-native-windows#1937]
### Environment

1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.49.3
2. `npm ls rnpm-plugin-windows`:
MyProject@2.1.0 E:\MyProject
`-- rnpm-plugin-windows@0.2.8
3. `npm ls react-native-windows`:
MyProject@2.1.0 E:\MyProject
`-- react-native-windows@0.49.0-rc.2
4. `node -v`:
v6.11.5
5. `npm -v`:
6.3.0
6. `yarn --version`:

Then, specify:

- Target Platform:

- Target Platform Version(s):
UWP,  10.0.10586

- Target Device(s):
LocalMachine

- Development Operating System:
Windows

- Visual Studio Version:
Visual Studio 2017

- Build Configuration:
DebugBundle
### Steps to Reproduce

(Write your steps here:)

1. I run react-native run-windows, the app is deployed and started
2. I receive an error, "Unable to get property 'DocumentDir' of undefined or null reference"
3. Opening the bundle file , I see reactNative.NativeModules.RNFetchBlob is null
4. I try to run react-native link
5. It links Android and IOS and gives error rnpm-install ERR! Something went wrong while linking. Error: spawn UNKNOWN

### Expected Behavior

(Write what you thought would happen.)
I expected the app to run with similar functionality of Android
### Actual Behavior

(Write what happened. Add screenshots!)

![react native error](https://user-images.githubusercontent.com/5434643/43992452-8c6c655a-9d7e-11e8-857f-624de505429e.gif)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by acuntex** [comment]
react-native-fetch-blob apparently has no native Windows implementation.

You would have to create a native implementation for the "react-native-fetch-blob api".

**Comment by rozele** [comment]
Indeed - please file an issue here: https://github.com/joltup/rn-fetch-blob/issues
