### ISSUE TITLE
Print page with react-native-print library 

### ISSUE THREAD

**Issue by irsalfirdaus** [Microsoft/react-native-windows#1952]
### Environment

1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.54.4
2. `npm ls rnpm-plugin-windows`:
rnpm-plugin-windows@0.2.8
3. `npm ls react-native-windows`:
react-native-windows@0.54.0
4. `node -v`:
v8.11.1
5. `npm -v`:
4.6.1
6. `yarn --version`:
1.5.1

Then, specify:

- Target Platform: WPF

- Target Platform Version(s): 10.0.14393

- Target Device(s): Desktop

- Development Operating System: Windows

- Visual Studio Version: VS2017 Community

- Build Configuration: Debug

### Steps to Reproduce

i used react-native-print library and when i execute react-native link this project become error 

(Write your steps here:)

1. Take a dependency on https://github.com/christopherdro/react-native-print
2. Execute: react-native link 
3. Execute: react-native run-windows

### Expected Behavior
Native library to link for Windows.

(Write what you thought would happen.)

### Actual Behavior
It failed 

MainReactNativeHost.cs(9,33): error CS0433: The type 'ReactNativeHost' exists in both 'ReactNative.Net46, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and
 'ReactNative, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' [D:\Asclar\Majapait\appdesk\windows\appdesk\appdesk.csproj]
MainReactNativeHost.cs(25,33): error CS0433: The type 'IReactPackage' exists in both 'ReactNative.Net46, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and
'ReactNative, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' [D:\Asclar\Majapait\appdesk\windows\appdesk\appdesk.csproj]
MainReactNativeHost.cs(11,32): error CS0115: 'MainReactNativeHost.MainComponentName': no suitable method found to override [D:\Asclar\Majapait\appdesk\windows\appde
sk\appdesk.csproj]
MainReactNativeHost.cs(14,30): error CS0115: 'MainReactNativeHost.UseDeveloperSupport': no suitable method found to override [D:\Asclar\Majapait\appdesk\windows\app
desk\appdesk.csproj]
MainReactNativeHost.cs(19,35): error CS0115: 'MainReactNativeHost.JavaScriptMainModuleName': no suitable method found to override [D:\Asclar\Majapait\appdesk\window
s\appdesk\appdesk.csproj]
MainReactNativeHost.cs(25,48): error CS0115: 'MainReactNativeHost.Packages': no suitable method found to override [D:\Asclar\Majapait\appdesk\windows\appdesk\appdes
k.csproj]
App.xaml.cs(18,26): error CS0433: The type 'ReactNativeHost' exists in both 'ReactNative.Net46, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'ReactNat
ive, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' [D:\Asclar\Majapait\appdesk\windows\appdesk\appdesk.csproj]
Build failed with message Error: Command failed: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\msbuild.exe" "D:/Asclar/Majapait/appdesk/windows/appdesk.sln" /clp:NoSummary;NoItemAndPropertyList;Verbosity=quiet /nologo /p:Configuration=Debug /p:Platform=x86 /p:AppxBundle=Never /p:PlatformToolset=v141 /p:VisualStudioVersion=15.0. Check your build configuration.

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by rozele** [comment]
The project is not "dead", but it is not currently as actively maintained as React Native for iOS and Android. Also, the community is smaller for UWP than for iOS and Android, so it makes sense that many 3rd party modules, such as react-native-print, do not have native implementations for UWP.

Closing, as this issue should be filed on:
https://github.com/christopherdro/react-native-print

I'm also not sure if WPF has support for the `react-native link` command (only UWP does as far as I know).

**Comment by 9sarang9** [comment]
@irsalfirdaus I am trying to connect POS ticket printer to application, can you please help me how i can use this npm for printing?
