### ISSUE TITLE
As of now this repository is not useful... How would anyone do anything with this? 

### ISSUE THREAD

**Issue by xtianus79** [Microsoft/react-native-windows#1960]
this doesn't work with React v.56  

what is a solution until these updates occur

**Comment by rozele** [comment]
The repository is still useful, especially for the majority of React Native apps that don't currently target 0.56. We are in a holding pattern as there is a lot of churn in the way platforms such as UWP and WPF plugin to React Native.

In the meantime, I recommend waiting to upgrade any react-native apps that target UWP via react-native-windows. For new apps that need to target UWP, use the `--version` option to specify version 0.55 when creating a new app with `react-native init`.  We will be releasing an RC for 0.57 ASAP.
