### ISSUE TITLE
ReactNative.dll not found

### ISSUE THREAD

**Issue by pirminb97** [Microsoft/react-native-windows#1967]
### Environment

1. react-native-cli: 2.0.1
2. react-native: 0.57.0
3. rnpm-plugin-windows@0.2.8
4. react-native-windows": 0.50.0
5. node: v8.12.0
6. npm: 6.4.1
7. yarn: 1.9.4

- Target Platform Version(s):
10.017134, .Net v4.5.2

- Target Device(s):

Windows UWP

- Development Operating System:

 Windows 10

- Visual Studio Version:

 Visual Studio 2017

- Build Configuration:

ReleaseBundle

### Steps to Reproduce

1. react-native init test2 --version 0.50.0-rc.2
2. cd test2
3. yarn add rnpm-plugin-windows --dev
4. react-native windows
5. open in VisualStudio
6. open test2.sln
7. right click test2 > Build

### Expected Behavior

RelaseBundle for test2 project starts building.

### Actual Behavior

  Error CS0006	Metadata file 'C:\Users\admin\DEV\test\test2\node_modules\react-native-windows\ReactWindows\ReactNative\bin\ARM\Debug\ReactNative.dll' could not be found

All the time i want to build, wether my real project or a test i always receive this error.

**Comment by MarvinErnst** [comment]
I get the same error

**Comment by pirminb97** [comment]
fixed the problem myself by updating project to newest RN-Version and resetting up Visual Studio with  Windows SDK 10.0.14393.0
