### ISSUE TITLE
Crash if React instance is destroyed while an async storage operation is in progress

### ISSUE THREAD

**Issue by zholobov** [microsoft/react-native-windows#1968]
https://github.com/Microsoft/react-native-windows/blob/8bc676281c3f8a2bc8e783654e608c0e489ed5b1/ReactWindows/ReactNative/Modules/Storage/AsyncStorageModule.cs#L322

Any `_mutex.Release()` (or any other code using `_mutex`) will crash with `ObjectDisposedException` if React instance was disposed meanwhile and `_mutex.Dispose()` was called. This is possible since `_mutex.Release()` calls are done in continuations that can be executed after the disposal.

**Comment by reseul** [comment]
@zholobov I think @psivaram is fixing this these days

**Comment by zholobov** [comment]
@reseul oh, checked with him, thanks! Cool - he may want to use this work item to justify a PR here.

**Comment by matthargett** [comment]
I have PR #1888 that I believe resolves this issue. I need to respond to the existing feedback, but please let me know if there's something else I need to do there.
