### ISSUE TITLE
Is this project dead? As of now there is no path forward to using this repository... When or will it not be fixed?

### ISSUE THREAD

**Issue by xtianus79** [Microsoft/react-native-windows#1969]
Can  the owners of this repository please speak to it's current state...

**Comment by rozele** [comment]
The project is still being maintained, but is in a lower priority maintenance mode until there is more clarity on the impact of the Fabric changes being made to react-native for iOS and Android. We don't want to invest heavily in the current architecture if much of it will change to support Fabric.

**Comment by xtianus79** [comment]
@rozele  i appreciate your responses.  what is fabric and why is that impacting the plugin?
