### ISSUE TITLE
Moving Exposed Xaml Control in React-Native-Windows from Windows.UI.XAML.Controls

### ISSUE THREAD

**Issue by adam-bratin** [Microsoft/react-native-windows#1970]
As part of Microsoft's Initiative the break the dependency between UWP controls and Windows SDK versions it was announced the creation of the [Microsoft.UI.Xaml](https://www.nuget.org/packages/Microsoft.UI.Xaml/) nuget package to replace using the UWP controls that were shipped in earlier SDKs. I was wondering if there has been any thought to moving to using these versions of the controls as it gives the ability for developers to use newer controls that previously required SDK versions > 14393 (RS1) which is the current targeting?

**Comment by rozele** [comment]
Great idea!

**Comment by rozele** [comment]
I'm going to close this out for now. It's likely that the view manager architecture will radically change given React Native Fabric and the move towards the rnwcpp-preview branch. These changes will likely take place before the Microsoft.UI.Xaml package has enough coverage to integrate.

**Comment by hmheng** [comment]
@rozele can the team create some open source RN control with uwp features? says inkcanvas, fluent design ui etc, which is not available in RN generally.
