### ISSUE TITLE
stucks at "fetching javascript bundle" dialog

### ISSUE THREAD

**Issue by MichalKrakow** [microsoft/react-native-windows#1980]
### Environment

1. `react-native -v`: 0.57.1
2. `npm ls rnpm-plugin-windows`: rnpm-plugin-windows@0.2.8
3. `npm ls react-native-windows`:
4. `node -v`: 8.11.3
5. `npm -v`: 5,6
6. `yarn --version` 1.9.4

Then, specify:

- Target Platform: UWP

- Target Platform Version(s): 10.0.14393

- Target Device(s): Mobile Emulator

- Development Operating System: Windows 10

- Visual Studio Version: 2017

- Build Configuration: Debug

(Write your steps here:)

1. follow instructions : https://github.com/Microsoft/react-native-windows/blob/master/docs/GettingStarted.md
2. alter DevServerHelper.cs line :
```
private const string DeviceLocalhost = "192.168.0.110:8081";
```
3. run 
```
react-native start --host 192.168.0.110 --port 8081
```
4. run from visual studio 2017 solution file targeting device emulator

### Expected Behavior

React native welcome screen

### Actual Behavior

Stuck on "fetching javascript bundle " dialog

Console shows :
```
 BUNDLE  [windows, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (541/541), done.

 BUNDLE  [windows, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (541/541)192.168.0.110 - - [25/Sep/2018:08:42:13 +0000] "GET /index.bundle?platform=windows&dev=true&hot=false HTTP/1.1" 200 2961578 "-" "-"
```
so i guess emulator can access metro bundler host but still it freezes at "fetching" dialog.

I've tried "local machine" target and it works as expected.

**Comment by rozele** [comment]
Does this still repro with react-native-windows@0.57.0-rc.5?

**Comment by Alex-Rose** [comment]
I'm facing the same behavior with 0.57.0-rc5

* `react-native -v`: react-native-cli: 2.0.1 \ react-native: 0.57.8
* `npm ls rnpm-plugin-windows`: rnpm-plugin-windows@0.2.8
* `npm ls react-native-windows`: react-native-windows@0.57.0-rc.5
* `node -v`: v11.10.0
* `npm -v`: 6.8.0
* `yarn --version` 0.19.1

* Target Platform: UWP
* Target Platform Version(s): 10.0.14393
* Target Device(s): Win10 Desktop local machine
* Development Operating System: Windows 10
* Visual Studio Version: 2017
* Build Configuration: Debug x64

In my case Metro Bundler is running and accessible from a browser, but this is the only output it gives me:

```
Looking for JS files in
   U:\react\test5

Loading dependency graph, done.
```
