### ISSUE TITLE
Could not find react-native-windows@0.57.*. / react-native-windows package not installed

### ISSUE THREAD

**Issue by assurancetourix** [microsoft/react-native-windows#2003]
### Environment

1. `react-native -v`:0.57
2. `npm ls rnpm-plugin-windows`: rnpm-plugin-windows@0.2.8
3. `npm ls react-native-windows`:  first "empty" then react-native-windows@0.57.0-rc.0 after ran npm install react-native-windows
4. `node -v`:
5. `npm -v`:

Then, specify:

- Target Platform: UWP

- Target Platform Version(s): Not known

- Target Device(s): Desktop

- Development Operating System: Windows

- Visual Studio Version: 2017

- Build Configuration: Not known

### Steps to Reproduce

I have run the command react-native windows. And get "Could not find react-native-windows@0.57.*."
I have tried with differentversion of react-native (0.56, 0.54) but still gets the issue. 

After running the command npm install --save-dev rnpm-plugin-windows, I realized that the package react-native-windows was not installed....And I manually installed it with npm install react-native-windows. Still the same error...

Would you have hints ?

Thanks.

**Comment by assurancetourix** [comment]
I managed to get it working by modifying the method getInstallPackage in node_modules\rnpm-plugin-windows\src\common.js to stg like:

const getInstallPackage = function (version) {
return Promise.resolve('react-native-windows');
};

Then the script has continued by installing react-native-windows and created the solution successfully.
However I am curious to known why this happened ?
Would you have hints ?

Thanks.

**Comment by rozele** [comment]
Please confirm if you are still able to reproduce this issue. It may have been due to a mismatched version of react-native (e.g., we could not ship react-native-windows@0.56 due to incompatibility of the react-native version)

**Comment by Alex-Rose** [comment]
I can repro this as of today

```
PS > react-native windows
Reading application name from package.json...
Reading react-native version from node_modules...
Checking for react-native-windows version matching 0.58.*...
Could not find react-native-windows@0.58.*. Latest version of react-native-windows is 0.57.0-rc.5, try switching to react-native@0.57.*.
```

I followed the instructions on the getting started page and this version got installed:
```
PS > npm v react-native-windows
react-native-windows@0.57.0-rc.5
```
Which does correspond to the latest available package on npm.

**Comment by rozele** [comment]
@Alex-Rose - we haven't updated react-native-windows to react-native@0.58 yet.

**Comment by atrauzzi** [comment]
@rozele - React native is moving pretty quickly these days, 0.59 is just around the corner.  Is this likely to continue being an issue or is there a plan in place to keep up?

**Comment by ntvinhit** [comment]
My project is using RN 0.59.*
I cannot revert it to RN 0.57 because I'm using RN hooks for almost my project.
Is there any plan to upgrade this repo for supporting RN 0.59?

**Comment by omissis** [comment]
this PR here should update to 0.58: https://github.com/Microsoft/react-native-windows/pull/2293
