### ISSUE TITLE
Release New React-Native-Windows .57

### ISSUE THREAD

**Issue by adam-bratin** [Microsoft/react-native-windows#2008]
@reseul @rozele  Is there any way that we could create a new rc for .57. There are changes for both RTL support as well as some of the fixes for background execution that are necessary to ship our product. It is currently very hard to run tests without having a public release with these changes.

Thanks.

**Comment by adam-bratin** [comment]
Any update on this?

**Comment by rozele** [comment]
Current RC has the latest from master. I have a few more fixes and a Yoga update to follow (before the stable release)
