### ISSUE TITLE
DisplayMetrics reporting size of main window and no the size of root view for 'window'

### ISSUE THREAD

**Issue by attilah** [Microsoft/react-native-windows#2010]
### Environment

1. `react-native -v`: 2.0.1
2. `npm ls rnpm-plugin-windows`: empty
3. `npm ls react-native-windows`: empty (we're using an external host)
4. `node -v`: 11.0.0
5. `npm -v`: 6.4.1

Then, specify:

- Target Platform: UWP
- Target Platform Version(s): 10.0.16299
- Target Device(s): Desktop
- Development Operating System: Windows 10 RS4
- Visual Studio Version: 15.8.7
- Build Configuration: Release/Debug depends

### Steps to Reproduce

- Make RootView to be a fixed size children inside the main window.
- Observe the Dimensions.get('window') from RN app

### Expected Behavior

- RN should not report size change
- RN should report the size of the rootView for the given RN App instance

### Actual Behavior

- RN reporting dimensions change when the main window is getting resized
- RN is reporting the dimensions of ```ApplicationView.GetForCurrentView().VisibleBounds```

**Comment by rozele** [comment]
@attilah - I agree that it would probably make sense to use root view dimensions for `window` and `screen` dimensions for the entire window, but honestly the current behavior is consistent with iOS (which only supports screen dimensions) and even the window dimensions for Android are deprecated. If you want to get the dimensions of a specific view in your app, you can always use the `onLayout` event.

I'll close this for now.
