### ISSUE TITLE
Layout issue on child views when parent view uses alignItems: 'center'

### ISSUE THREAD

**Issue by EdwardNickson** [Microsoft/react-native-windows#2012]
### Environment

react-native-cli: 2.0.1
react-native: 0.57.3
rnpm-plugin-windows@0.2.8
react-native-windows@0.57.0-rc.0
node v8.12.0
npm 6.4.1

Target Platform: UWP
Target Platform Version: 10.0.14393
Target Device: Desktop

Development Operating System: Windows 10 Enterprise
Visual Studio Version: 2017
Build Configuration: Debug & ReleaseBundle (Replicated issue on both)

### Steps to Reproduce

1. Render the following JSX Fragment

```
<View>
    <View style={{width: 80, height: 80, borderWidth: 1, flexDirection: 'row', alignItems: 'center'}}>
        <View style={{flex: 1, flexDirection: 'column'}}>
            <View style={{flex: 1, backgroundColor: 'lightgreen'}}>
                <Text>A</Text>
            </View>
        </View>
    </View>
    <View style={{width: 80, height: 80, borderWidth: 1, flexDirection: 'row'}}>
        <View style={{flex: 1, flexDirection: 'column'}}>
            <View style={{flex: 1, backgroundColor: 'lightgreen'}}>
                <Text>A</Text>
            </View>
        </View>
    </View>
</View>
```

This fragment renders two squares stacked vertically. The only difference between the two squares is that the top one has alignItems: 'center' on the outer view while the bottom square does not have the alignItems property.

### Expected Behavior
It should render two squares. Both with the letter A in the top left hand corner and both should be filled in with the light green color.
This is how it renders on Android:
![image](https://user-images.githubusercontent.com/26862861/47467167-968b0580-d840-11e8-9dc8-b194e9156139.png)

### Actual Behavior

The first square is empty. The letter A is not visible and there is no fill color.
The second square renders correctly. The letter A is in the top left hand corner and it is filled with the light green color.
This is how it renders on Windows:
![image](https://user-images.githubusercontent.com/26862861/47467153-81ae7200-d840-11e8-8f06-f08eda1a49c8.png)

It looks like the alignItems: 'center' on the outer square view is causing a bug in the flex layout calculations.
When viewed in VS the visual tree shows that the elements are getting created, but the height of the Canvas and RichTextBlock in the empty square are both 0.
![image](https://user-images.githubusercontent.com/26862861/47467359-bcfd7080-d841-11e8-8e89-88dbfb5967d7.png) ![image](https://user-images.githubusercontent.com/26862861/47467456-20879e00-d842-11e8-92bd-e85ff1e2273e.png)

### Reproducible Demo

The following sample app shows how the alignItems properties causes issues for all values except 'stretch'
```
import React, { Component } from 'react'
import {Text, View} from 'react-native'

export default class App extends Component {

  renderBox = (alignItems) => {
    return (
        <View style={{height: 80, width: 200, borderWidth: 1, flexDirection: 'row', alignItems: alignItems }}>
          <Text style={{width: 80}}>{alignItems ? alignItems : 'null'}</Text>
          <View style={{flex: 1, flexDirection: 'column'}}>
            <View style={{flex: 1, backgroundColor: 'lightgreen'}}>
              <Text>A</Text>
            </View>
            <Text>B</Text>
          </View>
        </View>
      )
  }

  render() {
    return (
      <View style={{flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: '#FFFFFF'}}>
        <Text style={{fontSize: 20, textAlign: 'center', margin: 10}}>alignItems example</Text>
        {this.renderBox(null)}
        {this.renderBox('center')}
        {this.renderBox('flex-start')}
        {this.renderBox('flex-end')}
        {this.renderBox('baseline')}
        {this.renderBox('stretch')}
      </View>
    )
  }
}

```
 The above renders as per below:
![image](https://user-images.githubusercontent.com/26862861/47467624-1a45f180-d843-11e8-92b2-542fed9d17cc.png) ![image](https://user-images.githubusercontent.com/26862861/47467673-5416f800-d843-11e8-89d4-1fa1821d62c4.png)

**Comment by rozele** [comment]
I'd like to think this is a bug in Yoga, we are way out of date (haven't updated Yoga in almost a year).

**Comment by rozele** [comment]
What's the result for iOS?

**Comment by rozele** [comment]
Unfortunately, this is not an issue with the Yoga version. I've tried updating to both the version of Yoga in 0.57 and 0.58-rc, and I can repro on each. I'll leave this open, let me know if you are able to find the fix. I'd suggest simplifying down to the minimal repro and running side-by-side debugging of the Android and Windows app.

**Comment by rozele** [comment]
I found the fix - we need to use `YGSetUseLegacyStretchBehaviour` to ensure the (incorrect) behavior of an implied stretch for containers matches currently present on iOS and Android is also the default on Windows.
