### ISSUE TITLE
react-native-maps is not supported in UWP

### ISSUE THREAD

**Issue by Ash-faq** [Microsoft/react-native-windows#2017]
### Environment
1. `react-native ^0.55.0`:
4. `node v8.10.0`:
5. `npm 5.6.0`:
6. `yarn 1.9.4:

Then, specify:

- UWP:

- Desktop, Mobile (ARM), Mobile Emulator, Xbox

- Windows Operating System:

- Visual Studio 2017

### Steps to Reproduce

(Write your steps here:)

1. installed react-native-maps 

### Expected Behavior
Need simple map with marker

### Actual Behavior

react-native-maps is not supported in UWP

**Comment by Ash-faq** [comment]
@rozele can you help me on this...

**Comment by creambyemute** [comment]
@Ash-faq As you said, it's not supported by either rn-windows nor is react-native-maps supporting rn-windows. You'll have to find a different solution or contribute to react-native-maps for windows support

**Comment by rozele** [comment]
See [this doc](https://github.com/Microsoft/react-native-windows/blob/master/docs/NativeComponentsWindows.md) for creating custom native components, should be possible to interpolate that information for creating a native map component.

**Comment by rozele** [comment]
Closing as this is out of scope for the core repo. Any maps component would have to be added in a third-party native extension.
