### ISSUE TITLE
StyleSheet.hairlineWidth not working anymore after update to RN 0.57.4 and  RNW 0.57.0-rc4

### ISSUE THREAD

**Issue by creambyemute** [Microsoft/react-native-windows#2020]
Hey there, I upgraded from RN 0.55.4 and RNW 0.55.4 to RN 0.57.4 and  RNW 0.57.0-rc4 some days ago and noticed that wherever I used `StyleSheet.hairlineWidth` it's not working anymore.

I'm pretty darn sure that it was working before the upgrade as otherwise I wouldn't have used StyleSheet.hairlineWidth

Not sure if this got "lost" due to the React-Native upgrade or the React-Native-Windows upgrade.

### Environment
1. `react-native -v`: cli 2.0.1 and react-native 0.57.4
2. `npm ls rnpm-plugin-windows`: 0.2.8
3. `npm ls react-native-windows`: 0.57.0-rc.0
4. `node -v`: v8.10.0
5. `npm -v`: 5.6.0
6. `yarn --version`: 1.12.1

- Target Platform: UWP
- Target Platform Version(s): 10.0.14393
- Target Device(s): Desktop
- Development Operating System: Windows 10 Pro 1709 (16299.726)
- Visual Studio Version: VS2017
- Build Configuration: Debug X64

### Steps to Reproduce

1. Apply a borderWidth of `StyleSheet.hairlineWidth`
2. Inspect applied css because no border is visible
3. borderWidth with `StyleSheet.hairlineWidth` was not applied

### Expected Behavior

The borderWidth is applied.

### Actual Behavior

No borderWidth is applied when using `StyleSheet.hairlineWidth`
BorderWidth is applied when using a value of for example 1 instead of StyleSheet.hairlineWidth.

### Reproducible Demo

I think it's pretty self-explanatory and it's already reproducible on a newly inited project when trying to use `StyleSheet.hairlineWidth`.

**Comment by rozele** [comment]
Indeed. I think I have a fix, but need to check with @reseul
