### ISSUE TITLE
BackHandler connection to app-level software "Back button"

### ISSUE THREAD

**Issue by achipa** [microsoft/react-native-windows#2021]
### Environment

1. `react-native -v`: 0.55.4
2. `npm ls rnpm-plugin-windows`: 0.2.8
3. `npm ls react-native-windows`: 0.55.0-rc.0
4. `node -v`: v10.13.0
5. `npm -v`: 6.4.1
6. `yarn --version` 1.12.3

Then, specify:

- Target Platform: UWP

- Target Platform Version(s): 10.0.14393

- Target Device(s): Desktop

- Development Operating System: Windows 10

- Visual Studio Version: 2017

- Build Configuration: All

### Steps to Reproduce

componentDidMount() {
    BackHandler.addEventListener("hardwareBackPress", this.handleBackPress);
}

### Expected Behavior

BackHandler gets invoked on a hardware or software button press

### Actual Behavior

This works for the hardware button, but there is no easy/apparent way to hook this up to the software buttons. 

https://docs.microsoft.com/en-us/windows/uwp/design/basics/navigation-history-and-backwards-navigation

is quite detailed on handling this, but it's unclear how that would fit the RN Windows BackHandler story. There is apparently two ways of doing this:

 - an older, no-longer-recommended app-level way, via https://docs.microsoft.com/en-us/uwp/api/windows.ui.core.systemnavigationmanager.appviewbackbuttonvisibility#Windows_UI_Core_SystemNavigationManager_AppViewBackButtonVisibility
- the current recommendation of each page/app doing it separately

In either case, I would expect this to be handled (even if optionally) on the framework level, as it is on Android, so if there were subscribers to backhandler (BackHandler.addEventListener...) the Back arrow would show. I don't really care if that's done via AppViewBackButton or some other means, what I want to avoid is extensive (Windows-only) plumbing that enables this (as then it gets even more complicated, with RTL considerations to boot).

My current workaround is to wrap BackHandler and toggle AppViewBackButtonVisibility if I have subscribers, but as said, I'd like to avoid per-platform components especially if there is a precedent in RN proper. If this *is* in line with the RNW team, I'm happy to upstream.

![image](https://user-images.githubusercontent.com/822934/48431249-7c04c780-e72e-11e8-80cd-63eb20372141.png)

**Comment by rozele** [comment]
@achipa - would be happy to look at a PR if you have a solution for this.

**Comment by achipa** [comment]
@rozele How about I open a PR for the code I currently have, more for RFC purposes? I have no problem molding it more into how RN4W is structured (in another branch/PR), but don't want to spend time doing that only to discover the concept is wrong. Is that OK?
