### ISSUE TITLE
Release Bundle x64 shows white screen after installation

### ISSUE THREAD

**Issue by pirminb97** [Microsoft/react-native-windows#2024]
### Environment

1.   react-native : 0.57.5:
2.  rnpm-plugin-windows: 0.2.8 
3.  react-native-windows: 0.57.0-rc.0
4.  node: v10.13.0
5.  npm: 6.4.1
6.  yarn: 1.12.1

- Target Platform:

* windows UWP x64

- Target Platform Version(s):

- 10.0.14393

- Target Device(s):

* Desktop

- Development Operating System:

* Windows 10

- Visual Studio Version:

* Visual Studio 17

- Build Configuration:

* Release Bundle x64

### Steps to Reproduce

1. Right click on Solution > retarget solution > Windows SDK Version: 10.0.14393.0 
2. Right click "AppName" in solution > Store > Create App Packages... > Create App packages for 
    sideloading
3. Version is incrementing automatically / Generate app bundle "Always" / x64 ReleaseBundle > create
4. Install certification on target device > install bundle script on target device 
5. App ist installed successful
6. App launches with white screen

### Expected behavior

I expect the the App UI to show up now.
If there is an error i want the app to crash.

### Actual behavior

* Blank screen appears
* no error - not even an app crash
![app_ui](https://user-images.githubusercontent.com/30226769/48766065-de704180-ecb3-11e8-89ec-fca9fe4e0df2.png)

### How i tested it

 If i run react-native run-windows the app works perfectly.

After my app UI did not show up in release build , i removed all links from index.js and just rendered a red view.
Got the same screen as before and nothing was shown.

**Comment by pirminb97** [comment]
Now this also happens to me with a blank react-native project...

**Comment by pirminb97** [comment]
fixed it. Problem was pretty embarassing... Git Bash didnt recognize \ and just ignored them, by pasting in the bundle comand

**Comment by jensonstack** [comment]
Getting same white screen in release mode. @pirminb97 Can you please explain the solution.

**Comment by softdew** [comment]
Its the same problem for me also. Please help

**Comment by asklar** [comment]
@softdew can you please file a new issue with your environment info and repro steps/if you've customized anything?

**Comment by taduyde** [comment]
the same issue

**Comment by asklar** [comment]
@taduyde please file a new bug rather than this very old bug :)

**Comment by taduyde** [comment]
@asklar
I already create a new bug on this link: https://github.com/microsoft/react-native-windows/issues/10300

**Comment by taduyde** [comment]
Hi @pirminb97 , How can you resolve it?
