### ISSUE TITLE
Exception calling "ActivateApplication" with "4" argument(s)

### ISSUE THREAD

**Issue by IrvanAhmadPrasetya** [Microsoft/react-native-windows#2026]
### Environment

1. `react-native -v`:
-react-native-cli: 2.0.1
-react-native: 0.57.7
2. `npm ls rnpm-plugin-windows`: rnpm-plugin-windows@0.2.8
3. `npm ls react-native-windows`: react-native-windows@0.57.0-rc.0
4. `node -v`: v10.6.0
5. `npm -v`: 6.1.0
6. `yarn --version`: 1.12.3

Then, specify:

- Target Platform:

- Target Platform Version(s): 10.0.17763.0

- Target Device(s):Deskop

- Development Operating System: Windows 10

- Visual Studio Version: Visual Studio 17

- Build Configuration: Debug x64

### Steps to Reproduce

(Write your steps here:)

1. react-native init TestApp
2. cd TestApp
3. yarn add rnpm-plugin-windows --dev
4. react-native windows
5. Right click on Solution > retarget solution > Windows SDK Version: 10.0.17763.0
6. react-native run-windows

### Expected Behavior

I hope the writing will appear
"Welcome to React Native!
To get started, edit App.windows.js
Press Ctrl + R to reload,
Shift + F10 or shake for dev menu ", according to the initial display in the App.windows.js file

### Actual Behavior

- Text does not appear
![capture pic rnw 2](https://user-images.githubusercontent.com/16983323/49199461-88458180-f3ca-11e8-9179-bc73a0c9d585.PNG)
-Exception calling "ActivateApplication" with "4" argument(s): "The text associated with this error code could not be
found.
```
Exception calling "ActivateApplication" with "4" argument(s): "The text associated with this error code could not be
found.
The text associated with this error code could not be found.
"
At D:\Project\Windows\test\TestApp\node_modules\react-native-windows\local-cli\runWindows\utils\WindowsStoreAppUtils.ps
1:168 char:5
+     $appActivator.ActivateApplication($applicationUserModelId,$args,[ ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : COMException
```
![capture pic rnw](https://user-images.githubusercontent.com/16983323/49199507-b034e500-f3ca-11e8-906f-196773df32a5.PNG)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by zolotyx** [comment]
Facing the same issue

**Comment by ShadyBoshra2012** [comment]
I was facing the same issue, I reinstall react-native-windows in the same project, and it works fine after it.

It's not a solution, but it just may help anyone.

**Comment by rozele** [comment]
Do you have Developer Mode enabled in Windows Settings?
<img width="1002" alt="screen shot 2019-01-22 at 9 21 03 pm" src="https://user-images.githubusercontent.com/1106239/51578488-bbb50180-1e8b-11e9-9565-77c0872637c5.png">

**Comment by rozele** [comment]
Closing for now given lack of activity.
