### ISSUE TITLE
WebView blocks gesture responder system

### ISSUE THREAD

**Issue by aikewoody** [microsoft/react-native-windows#2027]
### Environment

1. `react-native -v`:
```
react-native-cli: 2.0.1
react-native: 0.55.4
```
2. `npm ls rnpm-plugin-windows`:
```
-- rnpm-plugin-windows@0.2.8
```
3. `npm ls react-native-windows`:
```
-- react-native-windows@0.55.0-rc.0
```
4. `node -v`:
```
v10.13.0
```
5. `npm -v`:
```
6.4.1
```
6. `yarn --version`:
```
1.12.3
```

- Target Platform: UWP

- Target Platform Version(s): 10.0.14393.0

- Target Device(s): Desktop

- Development Operating System: Windows 10 Enterprise Evaluation

- Visual Studio Version: Visual Studio 2017

- Build Configuration: Debug

### Steps to Reproduce

1. Create a View component that listens to the responder system gestures.
2. Give this View as a child a WebView.
3. Make sure the View and WebView have the same dimensions.
4. Run the project on a device and try to touch/drag the views.

### Expected Behavior

The onResponder* functions of the View should fire when the user touches or drags the screen where the views are displayed.

### Actual Behavior

None of the `onResponder*` functions or `on*ShouldSetResponder*` functions fire.

### Reproducible Demo

  ```
import { View, WebView } from 'react-native';

  ...

  returnTrue = () => true;

  returnFalse = () => false;

  startDrag = () => {
    console.warn('startDrag');
    ...
    return true;
  };

  dragging = () => {
    console.warn('dragging');
    ...
    return true;
  };

  render() {
    const { width, height } = this.props;

    return (
      <View
        onMoveShouldSetResponder={this.returnTrue}
        onMoveShouldSetResponderCapture={this.returnTrue}
        onResponderGrant={this.startDrag}
        onResponderMove={this.dragging}
        onResponderReject={this.returnTrue}
        onResponderRelease={this.returnTrue}
        onResponderTerminate={this.returnTrue}
        onResponderTerminationRequest={this.returnFalse}
        onStartShouldSetResponder={this.returnTrue}
        onStartShouldSetResponderCapture={this.returnTrue}
        style={{ width, height }}
      >
        <WebView
          originWhitelist={['*']}
          scalesPageToFit
          scrollEnabled={false}
          javaScriptEnabled={false}
          style={{ width, height }}
        />
      </View>
    );
  }

...

```

This code works on Android (iOS not tested yet).

**Comment by juhasuni** [comment]
If you take a look at `ReactWebViewManager.cs` and its `CreateViewInstance` method, you can see that the WebView is setup to run in a separate thread (`var view = new WebView(WebViewExecutionMode.SeparateThread);`).

And the Microsoft's [documentation](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/web-view) states that:

> A web view that hosts content off the UI thread is not compatible with parent controls that require gestures to propagate up from the web view control to the parent, such as FlipView, ScrollViewer, and other related controls. These controls will not be able to receive gestures initiated in the off-thread web view.

So the question is, can we afford to run the WebView in the UI thread? Should we make this configurable? We've faced the same issue and as a workaround injected some JavaScript that captures the events and passes them back to RN environment using `postMessage`.

**Comment by aikewoody** [comment]
@juhasuni Thank you for the explanation! Making it configurable seems like a good solution with default behavior to run in a separate thread.

**Comment by rozele** [comment]
There's really no reason to use the SeparateThread option. I'm open to using the default constructor for WebView (which I believe defaults to SameThread).

**Comment by juhasuni** [comment]
Great, it certainly helps with gesture responders. It also brings back some other features, such as Printing. @rozele, do you want PR for this?

**Comment by rozele** [comment]
@juhasuni - if you file a PR, I'd be happy to approve / merge.

**Comment by juhasuni** [comment]
@rozele How do you feel, if we introduce a new prop that defines the execution mode?

There are couple of reasons for this:
1. Currently WebViews can be used to offload some work from the JS thread (e.g. we are using WebView to serve a headless PDF.js). For this we need `SeparateThread`.
2. WebGL support seems to require execution mode `SeparateThread`
3. Proper UI gesture propagation requires `SameThread`

Proposal: new prop that can be used to define the executionMode, with default value of `"sameThread"`. I'm not sure if `'separateProcess'` should be supported at all.

`executionMode={'sameThread' | 'separateThread' | 'separateProcess'}`
