### ISSUE TITLE
VS2017 stored a sideload app,and then I installed it in another win10 PC, notice that: unable to download JS bundle?

### ISSUE THREAD

**Issue by amicotin** [microsoft/react-native-windows#2032]
I already packaged it, so this app could be run by itself.

**Comment by rozele** [comment]
It was built with `ReleaseBundle` or `DebugBundle` target? Can you post the specific stack trace of the exception? RNW shouldn't be trying to download a bundle if you built with BUNDLE constant defined.

**Comment by amicotin** [comment]
@rozele I think it's release bundle.In VS I am go to solution, click right button-> choose store->create side load app package.Then I used another PC install this app will show that message, like in debug model.
