### ISSUE TITLE
react-navigation is no longer supported

### ISSUE THREAD

**Issue by Epicurean** [microsoft/react-native-windows#2033]
### Environment

1. `react-native -v`: 0.57.5
2. `npm ls rnpm-plugin-windows`:  0.2.8
3. `npm ls react-native-windows`: 0.57.0-rc.0
4. `node -v`: 10.9.0
5. `npm -v`: 6.2.0

- Target Platform: UWP

- Target Platform Version(s): UWP - 10.0.14393, .NET 4.6.1

- Target Device(s): Desktop

- Development Operating System: Windows 10

- Visual Studio Version: VS 2017

- Build Configuration: Debug

### Steps to Reproduce

1. install fresh react-native proj
2. install windows plugin
3. npm install react-navigation
4. run app

### Expected Behavior
Application should load without problems

### Actual Behavior
Error when loading package: Unable to resolve module gestureHandlerRootHOC. There seems to be a dependency on react-native-gesture-handler which does not support UWP.

### Reproducible Demo
![image](https://user-images.githubusercontent.com/3212505/49523511-f5985d00-f877-11e8-9b29-9283288338a0.png)

**Comment by JulianAssmann** [comment]
I'm encountering the same problem. Does someone know an alternative that works with windows too?

**Comment by phamngocduy98** [comment]
I got the problem too, which navigation is now working for react-native-windows?
![image](https://user-images.githubusercontent.com/13348656/50000783-35281d00-ffcd-11e8-9a6e-5c380a4a2ed8.png)

**Comment by creambyemute** [comment]
V2 of React-Navigation should work.

Not sure if V3 will ever work :/

**Comment by phamngocduy98** [comment]
> V2 of React-Navigation should work.
> 
> Not sure if V3 will ever work :/

I've tried to downgrade to v2.18.3 use `yarn add react-navigation@2.18.3` but not work

**Comment by rozele** [comment]
@Epicurean may also be worth a try to post an issue to the react-navigation repo. I recall chatting with the gesture-handler folks a long time ago and the plan at hat time was to create some backward compatibility, e.g., by falling back to JS-based gesture handling.

**Comment by hmheng** [comment]
I tried react-navigation 3..5.1, it works provided the react-native-gesture-handler@1.1.0 is installed. but 1.1.0 will break android as it can't support RN0.57 which RNW needs. So would be good if RNW is upgraded to 0.58 or 0.59

**Comment by hmheng** [comment]
Somehow I got it works with following packages:
    "@babel/runtime": "^7.4.2",
    "react": "^16.8.6",
    "react-native": "^0.57.8",
    "react-native-gesture-handler": "^1.1.0",
    "react-native-windows": "^0.57.0-rc.5",
    "react-navigation": "^3.5.1"

    "schedule": "^0.4.0"

**Comment by YajanaRao** [comment]
I tried with react navigation 4 and it is not working.

**Comment by khanzzirfan** [comment]
current work around is documented here. 
https://github.com/software-mansion/react-native-gesture-handler/issues/1081

**Comment by phamngocduy98** [comment]
Just use the lastest version of react navigation with lastest version of react-native-windows, and it should works as expected.
Here is my package.json
```
"dependencies": {
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/native": "^5.7.3",
    "@react-navigation/stack": "^5.9.0",
    "react": "16.13.1",
    "react-native": "0.63.2",
    "react-native-windows": "^0.63.0-0",
    "react-native-gesture-handler": "^1.7.0",
    "react-native-reanimated": "^1.13.0",
    "react-native-safe-area-context": "^3.1.4",
    "react-native-screens": "^2.10.1",
  },
```
But you need to create a index.windows.js which DON'T import react-native-gesture-handler like this:
```
import {AppRegistry} from "react-native";
import App from "./src/components/app/App";
import {name as appName} from "./src/app.json";
// import "react-native-gesture-handler";
// import {enableScreens} from "react-native-screens";
// enableScreens();

AppRegistry.registerComponent(appName, () => App);
```

Here is official document page of react-native-windows which declared supported community modules:
And you should see react-navigation there :D
https://microsoft.github.io/react-native-windows/docs/supported-community-modules
![image](https://user-images.githubusercontent.com/13348656/94133370-c3138600-fe8a-11ea-8cf6-a36cf4e6260e.png)
