### ISSUE TITLE
Building Bridges

### ISSUE THREAD

**Issue by pbahr97** [microsoft/react-native-windows#2034]
### Bridge buidling

Hello, 
since i need some C# applications to run with my own react-native-windows application i want to be able to build bridges between them. I found this quick introduction on how to develop bridges (https://github.com/Microsoft/react-native-windows/blob/master/docs/NativeModulesWindows.md), but i completely overwhelms me. As i don`t have experience in developing with C#, i even have trouble with how to get started. So i would like to know where in the project to create these files which will run as bridge or if i need to make a module how to get that included into the project. To my disappointment the tutorial did not explain all of this.
I hope theres someone out there who can help me, or even give me reference of an example how to do it properly.

Thanks
Pirmin

**Comment by Epicurean** [comment]
I don't think the intent of react native is to allow you to write native applications with the native stack. The whole premise is that you are building native apps with web tools. If you do need functionality in your React app that you would like to write in C#, I would suggest a separate C# web api project that provides functionality for your react app to consume. This is a project that may help you tremendously, as it did me http://dotnetify.net/core

**Comment by rozele** [comment]
@pirminb97 There are many ways to transfer data between UWP apps, without having more details on your specific scenarios, here are a few options to consider:
1) The Launcher API can be used to send data to another app and even wait for a result: https://docs.microsoft.com/en-us/windows/uwp/launch-resume/how-to-launch-an-app-for-results
2) There is also the option to support drag-and-drop in react-native-windows, it's not merged into master, but there was a PR that was proposed for setting RN views as drop targets: https://github.com/Microsoft/react-native-windows/pull/1549
