### ISSUE TITLE
Authorization Header get modified for RFC  2617 type header

### ISSUE THREAD

**Issue by ShrinathGupta** [Microsoft/react-native-windows#2040]
### Authorization header getting modified in final request object.

- Target Platform: UWP

In the app, we are making REST API call, and  sending Authorization Header in RFC-2617 format.  which belongs to strictly match authorization header.

`Authorization: Myapp id="xxx", ts="xxxx", nonce="4YDs1Y", mac="Gs8i3GEpoCcFzSxm5I4NZdfREIHgBreSrdfgdfgfgq76biLsuQY"`

### Finding, where it get updated

But the final request object get modified in below mention piece of code in which double quotes has been removed, because of which I am getting Invalid credentials from server. 
[In NetworkModule.cs
](https://github.com/Microsoft/react-native-windows/blob/master/ReactWindows/ReactNative.Shared/Modules/Network/NetworkingModule.cs)
```
await ProcessRequestAsync(
                    requestId,
                    useIncrementalUpdates,
                    timeout,
                    request,  //here all the double quotes from Authorization Hedaer get removed.
                    responseType,
                    token).ConfigureAwait(false);
            }
```

### What i tried,
I tried to manipulate Authorization header inside ApplyHeader method in [In NetworkingModule.cs
](https://github.com/Microsoft/react-native-windows/blob/master/ReactWindows/ReactNative.Shared/Modules/Network/NetworkingModule.cs) by
 adding backward slashes in the string like this 

``Authorization: Myapp id=\"xxx\", ts=\"xxxx\", nonce=\"4YDs1Y\"........`  but this also not worked. 
Then i tried to modify filter by making defaultAuthorizationValidation  false, Unfortunately this also not worked.

We can't modify server code, because same server is working fine for other platforms(android, ios app and web app) only it's getting failed for React-Native Windows. 

Can you please guide me, how i can modify networking module to get rid off this problem.
any sample code will be appreciated.
@rozele , @reseul , @howlettt , @pducolin .

I'm stuck, Any help will be appreciated. 
Thanks !

**Comment by ShrinathGupta** [comment]
@rozele I found that if i added value with space then double quotes remains as it is.

**Comment by ShrinathGupta** [comment]
@rozele I found that if i added value with space then double quotes remains as it is. 

`Authorization: Myapp id="xxx ", ts="xxxx ", nonce="4YDs1Y`
But server doesn't accept spaces in the value of Authorization.
Please tell me what else i can do to get rid of this.

**Comment by pducolin** [comment]
Have you tried to debug in https://github.com/Microsoft/react-native-windows/blob/master/ReactWindows/ReactNative.Shared/Modules/Network/NetworkingModule.cs#L125 ? Looks like it could be the header extraction

**Comment by ShrinathGupta** [comment]
Thanks @pducolin. i debugged that as well. Even i am modifying  header inside ApplyHeader method in switch case statement. 

https://github.com/Microsoft/react-native-windows/blob/b672036c6e118a47e8c509e3f29624547ea6c0fe/ReactWindows/ReactNative.Shared/Modules/Network/NetworkingModule.cs#L486 
                
Below is the snippet

```
StringBuilder sb = new StringBuilder();
sb.Append(" myapp CustomerId=");
sb.Append(@"""123""");
sb.Append(" ,SessionToken=");
sb.Append(" \"1235466fdfddc3\" ");

request.Headers.Add("Authorization", sb.ToString() );
```

above code brings double quotes if put space in  value like this `sb.Append(@"""123 """);` If we remove space from value then double quotes disappear. Which is strange, looks like dictionary Tvalue issue. Not sure.

any help will be appreciated. :(

**Comment by ShrinathGupta** [comment]
@rozele Please review my pull request. Thanks.

**Comment by rozele** [comment]
Thanks @ShrinathGupta - I added a review.
