### ISSUE TITLE
File Picker for desktop app.

### ISSUE THREAD

**Issue by warkann** [Microsoft/react-native-windows#2043]
### Environment

1. `react-native -v`: 
* react-native-cli: 2.0.1
* react-native: 0.57.7
2. `npm ls rnpm-plugin-windows`:
* rnpm-plugin-windows@0.2.8
3. `npm ls react-native-windows`:
* react-native-windows@0.57.0-rc.0
4. `node -v`:
* v11.3.0
5. `npm -v`:
* 6.4.1

### Target  Platform:
* UWP

### Target Platform Version:
* 10.0.14393

### Target Device(s):
* Desktop

### Development Operating System:
* Windows

I use react-native-windows for creating app for desktop windows 10.
I faced next task : to realize file download from the system with modal explorer (like <input type="file" /> in web),  BUT none of the available libraries  in the Internet is working.
I've also tried to create input in webview - there was a problem that webview.postMessage was not working. 
Maybe someone has already solved similar problems? 
I will be very grateful for some help.

**Comment by npmun** [comment]
Have you tried this?
https://github.com/Elyx0/react-native-document-picker/tree/v3?files=1

**Comment by warkann** [comment]
> Have you tried this?
> https://github.com/Elyx0/react-native-document-picker/tree/v3?files=1

Thanks a lot! This worked for me! :)

**Comment by hfdsu** [comment]
FolderPicker picker = new FolderPicker (); 
picker.FileTypeFilter.Add("*"); 
picker.ViewMode = PickerViewMode.Thumbnail; 
picker.SuggestedStartLocation = PickerLocationId.ComputerFolder; 
picker.CommitButtonText = "Select a Folder"; 
StorageFolder picked_Folder = await [url=https://chiltanpure.com/]picker.PickSingleFolderAsync()[/url]; 
so picker.SuggestedStartLocation is not a string to a path, but only a selection of libraries. does microsoft really believe that users and developers accept that lowest budget setup? 
now after the great Windows 10 Fall Creators Update it is still a joke to switch and develop to UWP. 
suggestion or question: 
does anybody at MS have an idea how to propose an path in an UWP application?

**Comment by rozele** [comment]
Closing given apparent resolution from comments.

**Comment by mohdravish** [comment]
Hi all i am also facing a problem in my window app with react native 
i wanted to open file explorer in my app and any npm packages are not supported so any please help me out from this ..
thanks in advance.

**Comment by OmerAhmedSiddiqui** [comment]
> Have you tried this? https://github.com/Elyx0/react-native-document-picker/tree/v3?files=1

its been removed

**Comment by ClaudiuHBann** [comment]
> > Have you tried this? https://github.com/Elyx0/react-native-document-picker/tree/v3?files=1
> 
> its been removed

This might help: [Support react-native-windows picker](https://github.com/react-native-documents/document-picker/issues/759#issuecomment-2642412457)
