### ISSUE TITLE
Add `swapLeftAndRightInRTL` Method to 18NModule

### ISSUE THREAD

**Issue by rozele** [microsoft/react-native-windows#2047]
Title is self-explanatory, see Android implementation for more details.

**Comment by rozele** [comment]
@reseul - when you worked on the I18N module a few months back, did you look into this at all? I'm not sure it's something we can implement with the current approach for RTL.

**Comment by reseul** [comment]
@rozele Nope, I didn't even know this one existed, I noticed it later when working on some other projects. I guess it landed post 0.46...
What's it supposed to do?

**Comment by rozele** [comment]
I think under normal conditions if you set, e.g., `paddingLeft` it applies to the left side regardless of RTL state. When `swapLeftAndRightInRTL` is set to true, I believe it swaps these kinds of properties.

**Comment by reseul** [comment]
Well, perhaps we'd have to test padding thoroughly first, to see where we landed, in order to decide what to do. Sometimes the padding is applied by Xaml, sometimes it's a result of yoga calculations triggering some positions, etc. We'd have to see them all.
Visually our app looked "fine" in RTL mode, but yeah, we didn't go through a more formal investigation.

**Comment by rozele** [comment]
Check out https://github.com/facebook/react-native/blob/6b0512c8196da5356272cbdfc1f16f23891d4f9e/ReactAndroid/src/main/java/com/facebook/react/uimanager/LayoutShadowNode.java `maybeTransformLeftRightToStartEnd`. That's where this is primarily used (in addition to a few other cases like border radius).

**Comment by rozele** [comment]
Basically I think it's a "safety" flag that let's you try to force your app to be RTL-friendly even if you use left/right as opposed to start/end.

**Comment by reseul** [comment]
Yeah, I was going to ask, what is the scenario that's being addressed.
I don't have time to go deeper at this moment, I may do it when I allocate a "working in Windows" slot...

**Comment by rozele** [comment]
No worries, I plan to address today, just wanted to make sure it wasn't something you saw and purposely didn't add because of potential conflicts with XAML FlowDirection.
