### ISSUE TITLE
Debugging the app ? Shift+F10 not working

### ISSUE THREAD

**Issue by Taerarenai** [Microsoft/react-native-windows#2053]
### Environment

1. `react-native -v`: - `0.57.8
2. `npm ls rnpm-plugin-windows`: - `0.2.8`
3. `npm ls react-native-windows`: - `0.57.0-rc.3`
4. `node -v`: - `v11.3.0`
5. `npm -v`: - `6.4.1`

Then, specify:

- Target Platform: UWP

- Target Platform Version(s): 10.0.14393 (default, for testing purposes)

- Target Device(s): Desktop

- Development Operating System: Windows 10

- Visual Studio Version: VS 2017

- Build Configuration: Debug

### Steps to Reproduce
1.Create a new app following the steps from getting started.
2.Try to debug the app by pressing SHIFT +F10

### Expected Behavior
The developer menu should pop up and it should allow me to enable "debug js" so i can use Redux Dev Tools and other such tools.
### Actual Behavior

Nothing happens....
The Dev menu does not open, its like i'm not pressing anything.

CTRL+R does work tho'.
### Reproducible Demo

The above should be more than enough since its a clean project.

**Comment by rozele** [comment]
We just need to integrate the latest into 0.57, this was resolved by #2046

**Comment by Taerarenai** [comment]
Got it, meanhwile the workaround would be to run with ``--proxy`` to enable debugging but that throws us into the problem of having to delete ``Debug`` folder because of an error (posted here in issues, but can't remember the number).

I moved away from react-native until further development is done since i can't yet contribute. 

Thanks!
