### ISSUE TITLE
Does React-Native Windows support RAM bundle?

### ISSUE THREAD

**Issue by adam-bratin** [microsoft/react-native-windows#2058]
As reading the release notes for react-native it is becoming apparent that the bundling strategy in the future is changing. [React-Native Release Notes](https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md#057) state that there is in the upcoming releases the optional adoption of RAM bundles and inline requires. Now I do know that React-Native-Windows supports unbundling, but I am unsure if specifically handles RAM bundle format. It seems this will eventually become the default option and it might be something to start looking into now.

**Comment by rozele** [comment]
@adam-bratin  - I believe we do support this in the C++ ChakraBridge project:
https://github.com/Microsoft/react-native-windows/blob/master/ReactWindows/ChakraBridge/JsIndexedModulesUnbundle.cpp

However, for many projects, even up to relatively large numbers of modules, we've found that there is better performance using the byte code serialization for Chakra. Currently, we don't have any combined approach that does both RAM bundle and byte code serialization, so unfortunately it's one or the other. 

I wouldn't take my word for it though that byte code serialization is better, it's probably best to try both on your app and evaluate the difference.

**Comment by licanhua** [comment]
Re-activate this for vNext

**Comment by chrisglein** [comment]
@licanhua It sounds like this was a question that was posed and answered 9 months ago. You just reactivated it against vnext. Can you give some background on why? Do you think there's work we must do here? Or is it okay to not support this?

**Comment by acoates-ms** [comment]
@Khalef1 I think your team probably has more info on what we should be looking at for bundle support.
