### ISSUE TITLE
Add support for textShadow* attributes

### ISSUE THREAD

**Issue by achipa** [microsoft/react-native-windows#2059]
### Environment

1. `react-native -v`: react-native-cli: 2.0.1 react-native: 0.55.4
2. `npm ls rnpm-plugin-windows`:
3. `npm ls react-native-windows`: react-native-windows@0.55.0-rc.0
4. `node -v`: v10.15.0
5. `npm -v`: 6.4.1
6. `yarn --version`:

Then, specify:

- Target Platform: UWP

- Target Platform Version(s): 10.0.16299+

- Target Device(s): Desktop

- Development Operating System: Windows

- Visual Studio Version: VS2017 

- Build Configuration: NA

### Steps to Reproduce

Define style with textShadow* properties, use in <Text> element.

textShadowOffset: { width: 5, height: 5 },
textShadowColor: "#000000",
textShadowRadius: 10,

### Expected Behavior

Text rendered with specified shadow. List at compatibility notes does not list textShadow* as missing.

### Actual Behavior

shadow properties accepted, but ignored

### Reproducible Demo

https://snack.expo.io/rJSTvmz4V

**Comment by chrisglein** [comment]
We're not investing in new features on current. If this issue is still relevant feel free to re-open against vnext.
In this case, we're already tracking as #2800
