### ISSUE TITLE
[Releases] "Get Clean" and stop requiring a dependency on our RN fork

### ISSUE THREAD

**Issue by rozele** [Microsoft/react-native-windows#2062]
We have a well defined way of "overriding" the behavior of JavaScript dependencies, namely the haste module mechanism, which allows us to provide platform-specific overrides of core react-native modules.

We want to ensure end-users that add a Windows option to their React Native apps have a single dependency on an unforked version of React Native for cross-platform JS, however we don't need to have any such guarantees on where the native "bridge" code comes from (i.e., it's fine to take a native-only dependency on a forked version of react-native, e.g., through a submodule).

**Comment by rozele** [comment]
A key consideration here for why this needs to be unblocked ASAP is there are constraints in the CLI tooling that require us to not fork if we want a good developer experience. See #2108.

**Comment by acoates-ms** [comment]
Renaming this issue to define it as work on making RNW not require our forked version of react-native.

**Comment by kmelmon** [comment]
#2264 is tracking this.  Closing
