### ISSUE TITLE
Suggest me, How to show PDF offline on UWP

### ISSUE THREAD

**Issue by nikjohns** [microsoft/react-native-windows#2067]
I am developing an application of showing PDF offline in app (windows 10) using react-native-windows and get stuck,
so can you suggest me any lib for showing PDF offline in the application?

React-native: 0.57
"react-native-doc-viewer": "^2.7.8",
"react-native-fs": "^2.13.3",
"react-native-windows": "^0.57.0-rc.5"

Win10 SDK(UWP): win10 SDK-17134, 
min-target SDK-15063.

Lib i have tried:
react-native-doc-viewer: [facing this issue]( https://github.com/philipphecht/react-native-doc-viewer/issues/127#issue-410648876)

**Comment by juhasuni** [comment]
There are commercial options, such as PSPDFKit and Foxit PDF SDK that officially support UWP. Both support React Native also.

For simple use cases, it is possible to use the classes in `Windows.Data.Pdf` namespace and specifically `PDFPage` to render the PDF as an image:
https://docs.microsoft.com/en-us/uwp/api/windows.data.pdf.pdfpage.rendertostreamasync

Another option is to load [PDF.js](https://mozilla.github.io/pdf.js/) into WebView and use it as a PDF viewer. The rendering performance of the web-only viewers is not very good.

**Comment by nikjohns** [comment]
@juhasuni Thank you for your suggestions, i have convert PDF into images and load images in view solved my problem temporary.

**Comment by SelvaraniAlagumuthu** [comment]
@nikjohns, I am also trying to show pdf file in react-native-windows. Could you please tell how to do this ?.. Because i am very new in react-native and react-native-windows.
