### ISSUE TITLE
Modal Component is not working after updating Windows SDK (10.0.17763.0)

### ISSUE THREAD

**Issue by ShrinathGupta** [microsoft/react-native-windows#2068]
**When I am trying to inject Modal, Unhand-led exception occurred.**

After updating Windows SDK from **Windows 10 SDK (10.0.14393.0)** to **Windows 10 SDK (10.0.17763.0)** OR **Windows 10 SDK (10.0.17134.0).**

Above both versions are not working for Modal component of react-native.
Installed Dependencies:
```
 "react": "^16.8.1",
 "react-native": "0.57.5",
 "react-native-windows": "^0.57.0-rc.5",
```
**Getting error at {Windows.UI.Xaml.UnhandledExceptionEventArgs}.**
Please refer attached screenshot.

@rozele Can you please check. 

![error](https://user-images.githubusercontent.com/12642711/52853525-deac9b80-3141-11e9-877c-9da7fe425c1a.jpg)

**Comment by HerrDikov** [comment]
Hi, I had the same issue. What fixed it for me was setting the max width and height of the contendDialog in ReactModalHostView from NaN to the maximum values of the window.

**Comment by kmelmon** [comment]
vnext doesn't have Modal yet.  This must be an old issue from current.
