### ISSUE TITLE
[Module] Alert not hooked up to ContentDialog

### ISSUE THREAD

**Issue by kikisaints** [microsoft/react-native-windows#2071]
Setting up an Alerts does not trigger a ContentDialog. 

**This is a platform gap.**

| Name | Status | Notes |
|------|--------|-------------|
| Alert | Partial Implementation | See [Source](../ReactWindows/ReactNative/Modules/Dialog/DialogModule.cs) |

## Details
According to [RN Alert documentation](https://facebook.github.io/react-native/docs/alert.html), this component has one method.
```js
static alert(title, message?, buttons?, options? type?)
```
This maps fairly well to ContentDialog's properties.

| RN parameter | Xaml property |
|---|---|
title | `Title`
message | `Content`
buttons | *see discussion below*
options | *ignore if parameter is specified* (the only example option I've seen is `cancelable: false`, which already maps to Xaml's behavior)
type | *ignore if parameter is specified* (some helpful discussion about this on [SO](https://stackoverflow.com/questions/50619829/react-native-what-does-type-mean-on-alert-component-method))|

### Buttons parameter
The example in RN docs specifies the buttons using
```js
    {text: 'Ask me later', onPress: () => console.log('Ask me later pressed')},
    {
      text: 'Cancel',
      onPress: () => console.log('Cancel Pressed'),
      style: 'cancel',
    },
    {text: 'OK', onPress: () => console.log('OK Pressed')},
```
We'll need to map this text to ContentDialog's `PrimaryButtonText`, `PrimaryButtonCommand`, `SecondaryButtonText`, `SecondaryButtonCommand`, `CloseButtonText`, `CloseButtonCommand`, and `DefaultButton` properties.

The last ('OK' in the sample) button in RN appears to map to Xaml's primary button. Because a dialog can show one, two, or three buttons, RNW will need to make some decisions about the buttons when initializing ContentDialog. If more than three buttons are specified in this parameter, RNW should ignore all buttons before the last three. When no styles are specified, map the last button to Primary, the second-to-last to Close, and the third-to-last button to Secondary. (This order corresponds to Android's 'neutral', 'negative', 'positive' order.)

If a parameter specifies `style: 'cancel'`, RNW should treat that as the Close button. Because multiple buttons can specify this style, only the last button to specify this style will become the Close button. **Note**: While the above examples shows the buttons in an order consistent with what I described above, it's possible for the cancel style to force a change to the order in which button parameters map to Xaml button properties. 

The `style: 'default'` parameter maps to Xaml's [DefaultButton](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.contentdialog.defaultbutton) property, which accepts values of None, Primary, Secondary, Close. Unlike the cancel style, the default style won't change the order in which the buttons will get laid out inside ContentDialog.

Xaml does not have a mapping for the iOS `destructive` style, so RNW will ignore that value of the `style` parameter.

**Comment by chrisglein** [comment]
@t-wihatz this is what you've been working on, right? Can we consider this issue done?

**Comment by harinikmsft** [comment]
@YuliKl - can you update the [parity status](https://github.com/microsoft/react-native-windows/blob/master/vnext/docs/ParityStatus.md) for the Alert line item to "Completed".
