### ISSUE TITLE
How to send HTML body or attached PDF to mail in react-native-windows

### ISSUE THREAD

**Issue by nikjohns** [microsoft/react-native-windows#2075]
I am using react native for my application development and want to send mail which contains HTML body (for good look and feel) or attached PDF.
[Linking](https://facebook.github.io/react-native/docs/linking) of react native simply send text message which is not enough while sending mail.

I have tried [react-native-share](https://github.com/react-native-community/react-native-share) however for windows it can share plane text message only which is possible by Linking also.

So, is there any way to send mail which contains HTML body or with attached PDF for windows mobile (may be base64)

**Comment by chrisglein** [comment]
Is this an issue with the react-native-share module, or the RNW specific implementation within? I don't believe the functionality you're describing is expected to be available on lean core.
