### ISSUE TITLE
PlatformConstants should provide Windows-specific information (e.g. OS version)

### ISSUE THREAD

**Issue by rozele** [microsoft/react-native-windows#2077]
The `PlatformConstants` module is used on iOS and Android to match the native bridge implementation with the current JavaScript bundle. It is also used to send platform-specific information to JavaScript. 

I can see us using the `PlatformConstants` module to include:
1. Information about the current API version for UWP, e.g., how [Android](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/modules/systeminfo/AndroidInfoModule.java#L71-L72) exposes SDK info
2. Information about the current device family, e.g., how [Android](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/modules/systeminfo/AndroidInfoModule.java#L45-L61) exposes UI mode.
3. React Native version info for ensuring JavaScript bundles are created for the correct native version.

**Comment by NickGerleman** [comment]
This can also help with deforking work. We currently patch files internal to React Native to skip platform checks if the Native module isn't available. Providing this Native module could let us skip that. For now we haven't merged in updates for new paltform checking APIs that the rest of the world will likely use.

**Comment by NickGerleman** [comment]
We will also need to update Platform.wnidows.js and Platform.win32.js when this happens

**Comment by NickGerleman** [comment]
We have a really basic implementation now, mostly just providing React Native version. What to do for OS Version needs some design, since it fights against the APIs exposed for universal contract checking right now.

**Comment by NickGerleman** [comment]
Starting with https://github.com/microsoft/react-native-windows/pull/6074 we provide UniversalApiContract for Version and document that on our site. Going to close this unless there are other constants we think we want to add.
