### ISSUE TITLE
[Releases] Set up release script for ReactNativeVersion.js module

### ISSUE THREAD

**Issue by rozele** [microsoft/react-native-windows#2078]
In order to ensure that a particular bundle is built for a specific release of native code for React Native, the OSS project has a [JavaScript module](https://github.com/facebook/react-native/blob/master/Libraries/Core/ReactNativeVersion.js) with version info and a corresponding native module for [iOS](https://github.com/facebook/react-native/blob/master/React/Base/RCTVersion.m) and [Android](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/modules/systeminfo/ReactNativeVersion.java).

Before cutting a release, react-native runs a script called [`bump-oss-versions.js`](https://github.com/facebook/react-native/blob/master/scripts/bump-oss-version.js#L60-L97), which synchronizes the iOS, Android, and JavaScript files with the correct version information.

We currently have this implemented in the C# repo [here](https://github.com/Microsoft/react-native-windows/blob/master/scripts/bump-oss-version.js#L59-L71). We'll need something similar for C++.

This feature depends on the `PlatformConstants` module, which is not currently implemented in the C++ repo. See #2077.

**Comment by acoates-ms** [comment]
We pick up ReactNativeVersion.js from react-native so it has this information already
