### ISSUE TITLE
[Releases] Set up Azure DevOps to release to NPM

### ISSUE THREAD

**Issue by rozele** [microsoft/react-native-windows#2079]
We need an automated process for publishing a release to NPM from a branch. We can use Azure DevOps release pipelines for this, where we can allow many users to kick off a release, or have automated triggers for kicking off a release, and have a few maintainers that sign off on releases.

If we start publishing native code through other package management services, e.g., NuGet or vcpkg, we will want to include those in the release pipeline as well.

**Comment by harinikmsft** [comment]
The work here is to make sure the npm module is published to the external feed.

**Comment by acoates-ms** [comment]
Part of this will be to update the dependency on RN to be a peer dependency.

**Comment by kmelmon** [comment]
It also looks like we'll need to update the permissions on the npm package to allow the build lab to publish after a successful build.  I went to npmjs.com and I see eric and harini are both listed as contributors, so one of them may be able to add the necessary permissions.  @rozele would you happen to know what's required?

**Comment by harinikmsft** [comment]
Scope for Milestone 1 - 
- publish one version manually to unblock CLI
- review the current RNWCPP against RNTester  and publish an update if needed

For Milestone 2 - tackle the automation part.

**Comment by kmelmon** [comment]
This task should include publishing the CLI as well

**Comment by marlenecota** [comment]
#2323 adds publishing of react-native-windows

Left to do:
- [ ] cli publishing

**Comment by kmelmon** [comment]
The remaining task to publish the CLI isn't critical for Milestone 2.  Moving to Milestone 3.

**Comment by chrisglein** [comment]
@marlenecota You indicated there isn't any more work to do here. Can you confirm and close the issue out if that's the case?

**Comment by marlenecota** [comment]
Yes, I mistakenly thought we had a separate npm package for our cli, but we don't.
