### ISSUE TITLE
[Component] RefreshControl not hooked up to PullToRefresh

### ISSUE THREAD

**Issue by kikisaints** [microsoft/react-native-windows#2081]
The RefreshControl for ReactNative operates very similarly to the UWP PullToRefresh control. However, when set up with RNWCPP it does nothing. App loads, but no PTR behavior - from a UX perspective.

**Comment by rozele** [comment]
Longstanding related issue: #190 - we do not have a solution for this in the master branch at this time either.

**Comment by chrisglein** [comment]
Moving this issue over to you @ddalp because you were looking into PullToRefresh. Back in March Harini thought we might need some PM attention on this so feel free to loop her in.

**Comment by ddalp** [comment]
Assign the issue to @kikisaints since I need some clarifications.
Is this the same issue as #3069? If so, I just added the support for ScrollView.RefreshControl and this issue can be resolved.

**Comment by kikisaints** [comment]
@ddalp was the work that you did fo #3069 to make the RefreshControl map to our pulltorefresh behavior when used on windows? If so, then I can close this issue :smile:

**Comment by ddalp** [comment]
@kikisaints Yes, specifically RN's refreshControl to XAML's RefreshContainer control.

**Comment by kikisaints** [comment]
Then this issue is closed, as far I am I concerned!
