### ISSUE TITLE
[Gamepad PC] Gamepad stuck on ScrollViewer in RNTesterApp

### ISSUE THREAD

**Issue by kikisaints** [Microsoft/react-native-windows#2083]
Gamepad navigation gets stuck on the ScrollViewer that's wrapping focus-able content. Once I click on an item within the ScrollViewer the gamepad focus appears to operate correctly (provided the controls within are full UWP). However, once I leave that "inside" focus, I cannot get back to it.

### Additional Info
Below is a small demo of this behavior. Ideally I would trigger the scrolling behavior by focusing on elements within the scrollviewer and when a focused element is outside of my view, the content within is scrolled to show that in view.

As you'll see below, I cannot get "into" the content displayed in the ScrollViewer without first clicking.
![gamepadscrollviewerissues](https://user-images.githubusercontent.com/6964369/53441638-175b3900-39bc-11e9-8829-9944dc09d166.gif)

**Comment by rozele** [comment]
Seems like you might need to set [KeyboardNavigationMode](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.input.keyboardnavigationmode) to "cycle". In the master branch, we created added a `tabNavigation` prop to `<ScrollView/>` allow you to customize this:
https://github.com/Microsoft/react-native-windows/blob/9a9cfeaf574a5505e767cf3afe187e6da74c1b96/ReactWindows/ReactNative.Shared/Views/Control/ReactControlManager.cs#L108-L112

As far as I can tell, this isn't available in the `rnwcpp-preview` branch. It should be trivial to implement though.

**Comment by kmelmon** [comment]
Note this may be more than just changing options to fix the bug - need to enable this in a general way

**Comment by jonthysell** [comment]
This doesn't look like it repros the same. I can get in and out of the inner content without needing to click.

**Comment by ahimberg** [comment]
ScrollView used to default to being a tabstop which was probably causing this problem.

**Comment by jonthysell** [comment]
Closing as fixed. We can re-open if it comes back.
