### ISSUE TITLE
ReleaseBundle Windows 8.1 not working

### ISSUE THREAD

**Issue by Dolu89** [microsoft/react-native-windows#2084]
### Environment

1. `react-native -v`: react-native-cli: 2.0.1
react-native: 0.57.0
2. `npm ls rnpm-plugin-windows`: -- rnpm-plugin-windows@0.2.8
3. `npm ls react-native-windows`: -- react-native-windows@0.57.0-rc.5
4. `node -v`: v10.15.1
5. `npm -v`: 6.4.1

Then, specify:

- Target Platform: WPF

- Target Platform Version(s): 10.0.14393 

- Target Device(s): Desktop 8.1 Enterprise 64bits (.NET 4.6 installed)

- Development Operating System: Windows 10 Pro

- Visual Studio Version: Visual Studio 2017 Professional

- Build Configuration: ReleaseBundle 

### Steps to Reproduce

(Write your steps here:)
With a new react native project (Hello world)
1. react-native wpf
2. react-native bundle --platform windows --entry-file index.js --bundle-output wpf\rn57\ReactAssets\index.wpf.bundle --assets-dest wpf\rn57\ReactAsset
3. Open WPF solution in visual studio
4. Retarget solution with SDK 10.0.14393
5. Select ReleaseBundle 
6. Publish
7. Launch myApp.application

### Expected Behavior

Basic Hello world of react native should be rendered

### Actual Behavior

Application crash with no error.
![rnwindows](https://user-images.githubusercontent.com/4184590/53477938-0bcc4880-3a76-11e9-851a-498366c715ff.gif)

But work in Debug mode
![capture](https://user-images.githubusercontent.com/4184590/53478919-3cad7d00-3a78-11e9-9603-e57a1dcc9896.PNG)

### Reproducible Demo

https://github.com/Dolu89/reactnativewindowstest

Clone the repo
npm install
Open wpf sln in VS2017
react-native bundle --platform windows --entry-file index.js --bundle-output wpf\rn57\ReactAssets\index.wpf.bundle --assets-dest wpf\rn57\ReactAsset
Target ReleaseBundle and x64
Publish rn57 project

**Comment by Dolu89** [comment]
I found it's a bundle problem...

The problem is on this command
`react-native bundle --platform windows --entry-file index.js --bundle-output wpf\rn57\ReactAssets\index.wpf.bundle --assets-dest wpf\rn57\ReactAsset`

The folder ReactAsset is not copied in the final package because in the file AppReactPage.cs from the VS project, contains : `AppDomain.CurrentDomain.BaseDirectory + "ReactAssets/index.wpf.bundle";` who is translated by `C:\...\myProject\wpf\myProject\bin\x64\DebugBundle\ReactAssets\index.wpf.bundle`

So I think I have to find how to remove \bin\x64\DebugBundle from the path or I have to understand why my bundle file is not in the good folder. 

Any advice?

**Comment by ChronSyn** [comment]
I don't suppose you have found any solution to this since your last reply, @Dolu89 ?

**Comment by Dolu89** [comment]
> I don't suppose you have found any solution to this since your last reply, @Dolu89 ?

No. I'm not on this project at the moment

**Comment by mskwon** [comment]
Just a heads up for anybody else with this problem - a quick workaround is to change the relative path of the bundle to “../../../ReactAssets/index.wpf.bundle”

**Comment by chrisglein** [comment]
Given there's a workaround closing this issue as we're trying to invest in vnext instead of WPF.
