### ISSUE TITLE
Add automatic accessibilityPeer for rnwcpp

### ISSUE THREAD

**Issue by ahimberg** [microsoft/react-native-windows#2089]
this overlaps a bit with adding support for onaccessibility tap, but add the similar support that c# already has for support a few basic role types

Narrator needs to announce the correct UIA control type.
- [ ] Button as Button
- [ ] TouchableHighlight as Button
- [ ] TouchableOpacity as Button
- [ ] FlatList items need x of n count announced
- [ ] SectionList items need x of n count
- [ ] SectionList sections (headers) need to be announced differently from regular items

**Comment by harinikmsft** [comment]
This is tracking just the support for current JS APIs to be plumbed through RNWCPP.

**Comment by kmelmon** [comment]
Consolidating accessibility work - Jon will take this.

**Comment by jonthysell** [comment]
This work is now split out over #2565, #2566, #2568.
