### ISSUE TITLE
Support react-native-video on RNW vNext

### ISSUE THREAD

**Issue by stecrain** [microsoft/react-native-windows#2095]
@harinikmsft Here's the issue

I want to start experimenting with video support in a React Native Windows project.
To stream play all of the content I'm interested in the video player would need to support mpeg dash and Microsoft smooth streaming.

There is an existing project that adds support for video to the C# React Native Windows implementation. I'm not sure if it makes more sense to update the existing [react-native-video](https://github.com/react-native-community/react-native-video) to work with RNWCPP or if it should live in this repo. Just wanted to point out that it exists :)

**Comment by rozele** [comment]
I would recommend that we fork [react-native-video](https://github.com/react-native-community/react-native-video) and use this work item as an opportunity to flesh out the native component extensions model.

**Comment by ahimberg** [comment]
Latest rnwcpp-preview has initial support for adding custom view managers, more work to do things nicely but its possible now.

**Comment by stecrain** [comment]
Excellent!
So with the latest changes I should be able to just add a custom ViewManager for Video and map it to MediaPlayerElement? (for example)

**Comment by ahimberg** [comment]
I believe that should be possible but I haven't actually confirmed I can use the custom viewmanager headers/types from outside the repo, we'll be trying that soon in our codebase and fixing up if there are any minor issues.  Look at CustomViewManager and replace winrt::checkbox with the xaml control you are wrapping

**Comment by harinikmsft** [comment]
This should cover adding support to a community module

**Comment by jonthysell** [comment]
Removing ready to dev until we have the proper model for native modules.

**Comment by chrisglein** [comment]
Moving back to M3 as we'll want to use this as a test case for view managers.

**Comment by chrisglein** [comment]
Camera has view manager coverage, so this can move to M4.

**Comment by kmelmon** [comment]
@ddalp do you have a topic branch you can share?  I'm looking into the versioning story and would like to see a working viewmanager.

**Comment by feechin** [comment]
I am looking to incorporate a video player in my app.  So far linking react-native-video still generates an error.  Does anyone know how to embed and play a video with the current vnext release?  Or point me to a sample react native windows app that has video embedded in it?  Thanks.

**Comment by ddalp** [comment]
@feechin Our current plan is to release a Video native module soon after MVP release.

**Comment by ddalp** [comment]
React-Native-Video community module for windows Cpp/WinRT is now checked in, remaining issue #4157 (keyboard touch events not firing when in full window mode)will be addressed in RNW.

**Comment by chrisglein** [comment]
Providing link to PR to help people looking back over the process of adding Windows support to existing native modules: https://github.com/react-native-community/react-native-video/pull/1893
