### ISSUE TITLE
[Releases] Document approach for shared JavaScript dependencies

### ISSUE THREAD

**Issue by rozele** [microsoft/react-native-windows#2097]
Most of the JavaScript dependencies we'll want to take should be taken through NPM. E.g.:
- [react-native](https://www.npmjs.com/package/react-native)
- [@react-native-community/cli](https://www.npmjs.com/package/@react-native-community/cli)

There are some other JavaScript dependencies that we may need to take through a submodule dependency as they are not currently published on NPM, namely:
- [RNTester](https://github.com/facebook/react-native/tree/master/RNTester/js)

Alternatively, we should work to get these dependencies published to NPM.

**Comment by harinikmsft** [comment]
I am not entirely sure what needs to be documented here and who the audience is for this. Pinging @chrisglein , @acoates-ms, @kmelmon  to see if there is anything specific to document/change about the consumption infrastructure?

**Comment by acoates-ms** [comment]
@NickGerleman - This is handled primarily by the override tooling at this point.
The one called out in the original description, RNTester is done using the override tooling right now.  But there is finally work being done in the community to publish this as a separate NPM package as suggested.  But we have some other packages from core that we are copying into our repo.

**Comment by NickGerleman** [comment]
For the category of "things not published from core because they're not ready to be consumed", I wonder if there are alternative methods to discourage usage.

Not sure what the intent of this specific issue is though. Is it aimed to explain how we acquire our dependencies to RNW developers?

**Comment by chrisglein** [comment]
This issue predates the 'vnext' implementation of RNW. While there's still interest in RNTester being published differently that's discussed elsewhere. If there's no clear call to action here I say we close this.
