### ISSUE TITLE
Investigate moving <View /> to use XamlDirect for better performance

### ISSUE THREAD

**Issue by harinikmsft** [microsoft/react-native-windows#2098]

**Comment by rozele** [comment]
For reference, we have an internal prototype on the C# repo for this:
https://ericroz.visualstudio.com/_git/react-native-windows?path=%2FReactWindows%2FReactNative%2FUIManager&version=GBxamldirect

**Comment by jonthysell** [comment]
I've gotten RNWCPP to consume the published C++/Cx MUXCD component, looking at @rozele's implementation for ideas on how to proceed.
