### ISSUE TITLE
[Releases] Document `react-native-windows` versioning strategy

### ISSUE THREAD

**Issue by rozele** [Microsoft/react-native-windows#2101]
There are a few questions we need to address:

1. How do we want to manage our version compatibility matrix with `react-native`?

Today, we release a minor version of `react-native-windows` for every minor version of `react-native`. Our compatibility matrix is thus very simple. If you upgrade to or use a particular version of `react-native`, find the version of `react-native-windows` with the same major and minor version and use that.

The downside to this is that if we have new features we want to add and would like to bump the version to acknowledge this, we can't because we are locked into the versioning for `react-native`. The reality is that `react-native` does not yet do a good job of obeying semantic versioning (breaking changes in minor version updates, etc.), so iterating on new features in a given minor version within the patch version band is not a big deal to the community.

2. How do we want to manage branching strategy and patches for releases?

Today, we follow the same approach that `react-native` uses:
- Cut a release branch for every version release and publish from this branch.
- All bug fixes occur on the master branch.
- Bug fixes are cherry-picked onto the release branch and published.

**Comment by rozele** [comment]
Here is my suggestion:

Continue to publish a version of `react-native-windows` for each minor of `react-native` and use the `minor` version matching as our compatibility matrix.

While we are developing the RNWCPP solution and keeping it in "preview", we'll use a prerelease tag. E.g., if we have a version of RNWCPP that is compatible with `react-native@0.57.*`, we'd publish it as `react-native-windows@0.57.0-vnext.0`, where `vnext` can be replaced with whatever prerelease moniker we choose.

**Comment by acoates-ms** [comment]
I think this can be closed?  
The react-native-windows version is currently something like: 0.57.0-vnext.21 -- Which means its compatible with RN 0.57

**Comment by harinikmsft** [comment]
Completed with #2225
