### ISSUE TITLE
[ThirdParty] Document interface for creating C++ view managers

### ISSUE THREAD

**Issue by rozele** [microsoft/react-native-windows#2102]
Many apps need to create and use custom native components. We should create a doc with sample code for how to do this with RNWCPP. For reference, we have a doc of this nature in the master branch:
https://github.com/Microsoft/react-native-windows/blob/master/docs/NativeComponentsWindows.md

**Comment by kmelmon** [comment]
We've moved the work for custom view managers out to Milestone 3, moving this as well.

**Comment by kmelmon** [comment]
Moving back to Milestone 2 to cover documenting the story that exists today.

**Comment by chrisglein** [comment]
Document in place, content is missing for C++ View Manager: https://github.com/microsoft/react-native-windows/blob/master/vnext/docs/ViewManagers.md#sample-viewmanager-c-1

**Comment by stmoy** [comment]
Document now has C++ View Manager example. https://github.com/microsoft/react-native-windows/blob/master/vnext/docs/ViewManagers.md#sample-viewmanager-c-1

Closing.
