### ISSUE TITLE
[ThirdParty] Document example for creating C++ native modules

### ISSUE THREAD

**Issue by rozele** [microsoft/react-native-windows#2103]
Many apps need to create and use custom native modules to expose native behaviors. We should create a doc with sample code for how to do this with RNWCPP. For reference, we have a doc of this nature in the master branch:
https://github.com/Microsoft/react-native-windows/blob/master/docs/NativeModulesWindows.md

**Comment by ahimberg** [comment]
native modules are written using the standard react-native interfaces from react-native/ReactCommon/cxxReact, so the base code is not different to write a C++ native module for windows, mac, android if using C++ - maybe we can find some existing reference doc (though most docs show objc or java so maybe not)

We do have a simple example in the windows sample app that could be expanded (fire events, show all the callback types).

what is unique in uwp is how you register your extra native modules.

also we should make sure to document how callbacks & firing events work, its been very common for people to try to call a callback multiple times, which isn't allowed.

**Comment by ahimberg** [comment]
Oh and we should warn that native modules are expected to be replaced by turbo modules soon

**Comment by rozele** [comment]
Thanks @ahimberg. I still think it is worth while to put together a short doc with an example of exposing UWP APIs through a native module. Analogous to the one listed in the issue description.

**Comment by chrisglein** [comment]
https://github.com/microsoft/react-native-windows/blob/master/vnext/docs/NativeModules.md#sample-native-module-c-1
