### ISSUE TITLE
[Component] TextInput's default style is clipping its bottom border

### ISSUE THREAD

**Issue by YuliKl** [microsoft/react-native-windows#2106]
The bottom border of TextInput is not being rendered because its default style sets a height of 30px. The correct value is 32.

Sample code from WindowsSampleApp:
````js
            <TextInput
              ref={c => (this._input = c)}
              defaultValue={"Test"}
              placeholderTextColor={"hotpink"}
              onChangeText={this.changeTextHandler}
              onFocus={this.focusTextInputHandler}
              onBlur={this.blurTextInputHandler}
              onSelectionChange={this.selectionChangeTextInputHandler}
              onEndEditing={this.endEditingTextInputHandler}
              onContentSizeChange={this.contentSizeChangeTextInputHandler}
              selectionColor={"red"}
              clearTextOnFocus={false}
              selectTextOnFocus={true}
            />
````
Rest state:
![image](https://user-images.githubusercontent.com/13142665/53604543-a063a300-3b69-11e9-9104-cc07e0819f79.png)

Focused state:
![image](https://user-images.githubusercontent.com/13142665/53604573-b2dddc80-3b69-11e9-97f2-aed066cdd18c.png)

Xaml TextBox (for reference):
![image](https://user-images.githubusercontent.com/13142665/53604412-495dce00-3b69-11e9-917b-da696b8bf449.png)

**Comment by kikisaints** [comment]
This is actually just a bug in the markup. That particular TextInput's style is set to 30, which is cutting off the bottom. Setting it to 35 or removing the height specification in the style altogether shows the bottom:

![image](https://user-images.githubusercontent.com/6964369/53607669-8bd8d800-3b74-11e9-8bd6-4acb0f52bcf5.png)

**Comment by YuliKl** [comment]
@kikisaints Thank you. I thought I had tried removing the height, but clearly I was doing something wrong. Probably removing the style altogether.

**Comment by kmelmon** [comment]
re-test - this may now be fixed

**Comment by harinikmsft** [comment]
This no longer repros, closing as fixed.
