### ISSUE TITLE
Improved keyboarding behaviors for lists 

### ISSUE THREAD

**Issue by YuliKl** [microsoft/react-native-windows#2107]
Some components don't have appropriate focus visuals and keyboarding behaviors when they receive keyboard focus. This issue is tracking using the `onKeyDown`, `onKeyUp` events to implement the right behaviors for lists and popups based on [Keyboarding interactions](https://docs.microsoft.com/en-us/windows/uwp/design/input/keyboard-interactions) guidance document for Windows. 

- [x] FlatList - Focus rect is drawn around the entire component
- [ ] FlatList - User can't move focus to a specific item using arrow keys

Related to #3006

**Comment by ahimberg** [comment]
The outer focus rect is coming from the scrollview which currently defaults to being a tabstop (that was to workaround an issue where clicking on anything in a scrollview would move focus to the first keyfocusable child).  should revisit that

since flatlist is just a scrollview with random children it is not getting any list item behaviors

**Comment by rectified95** [comment]
Starting to verify the scenarios. 
Testing this now in Playground now, I don't the rectangle drawn around the entire Flatlist.
@YuliKl what was the exact scenario in which this occurred? I am pressing Tab a few times until I enter the first element in the list, and I don'tsee the outer rect before that.

**Comment by YuliKl** [comment]
Given how long ago I had created this issue, I'm not surprised that you're unable to repro.

**Comment by rectified95** [comment]
Extracting the SectionList portion of the issue out to #6566

**Comment by mjfusa** [comment]
@rectified95 I checkout out your PR #6826 as I need this for navigation on XBox. The D-Pad Left and Right work great for moving between controls in the FlatList. Any ideas on how Enter can be mapped to the Pressed event? The XBox control 'A' will map to Enter.

**Comment by rectified95** [comment]
We rely on XAML for native events. I think that if you had a FlatList of \<Pressable> then pressing Space would trigger onPress. I think Enter might do the same, but I haven't been able to observe that consistently. 
Other than that, you could register a handler for the KeyDown event on the underlying ScrollView, and check if the Enter has been pressed.

**Comment by rectified95** [comment]
@mjfusa Check this out: https://github.com/microsoft/react-native-windows/blob/master/vnext/src/Libraries/Pressability/Pressability.windows.js#L642-L669
It seems like we have special-cased GamePadA

**Comment by rectified95** [comment]
To be resolved by https://github.com/microsoft/react-native-windows/pull/6826
