### ISSUE TITLE
[Onboarding] Simple CLI for RNWCPP 

### ISSUE THREAD

**Issue by harinikmsft** [Microsoft/react-native-windows#2108]
Developers can create a new React native application for Windows 10 through RNWCPP using a simple CLI with a sample template - like the experience we have today for RNW C# onboarding. This is only one scenario and the first step towards enabling it.

**Comment by rozele** [comment]
Let's treat this issue as phase 1 for the CLI project generation experience. In future phases, we can rethink the multi-step install process (i.e., _rnpm-plugin-windows_) and attempt to provide React Native CLI templates that have Windows pre-configured.

**Comment by rozele** [comment]
Here are notes for building the CLI assuming we are **not** working from a fork of `react-native`:

1. Add a flag option to the `react-native windows` command installed with `rnpm-plugin-windows`, e.g., `--cpp` to signal that we want to generate a new project for C++. [Here]( https://github.com/Microsoft/react-native-windows/blob/master/local-cli/rnpm/windows/index.js#L5-L15) is where the CLI options are configured. React Native CLI extensions are based on [commander](https://www.npmjs.com/package/commander).

2. Update the [logic](https://github.com/Microsoft/react-native-windows/blob/master/local-cli/rnpm/windows/src/windows.js#L22) for `rnpm-plugin-windows` to detect the `--cpp` flag and install the C++ version of `react-native-windows`. We have a few options for this. I tested out options for using specific pre-release names (e.g., @0.60.0-cpp.*) and dist-tags, but the semver resolution mechanisms are not sufficient to resolve by both version number and tag name (which we would need). Instead, we could publish temporarily to an alternative NPM package name (e.g., `react-native-win`), or we could publish in a scoped package (e.g., `@microsoft/react-native-windows`)

3. Add a script to our `react-native-windows` package to generate "hello world" project, similar to what we have [here](https://github.com/Microsoft/react-native-windows/tree/master/local-cli/generator-windows). The reason we don't publish the project generation code in `rnpm-plugin-windows` is so we can more tightly integrate the release of correct project templates with a release of a version of `react-native-windows`.

4. From our script in `rnpm-plugin-windows` that installs the correct version of `react-native-windows` for C++, add something similar to [this logic](https://github.com/Microsoft/react-native-windows/blob/master/local-cli/rnpm/windows/src/windows.js#L36-L37), which calls the script created in step 3 after it was installed.

**Comment by MikeHillberg** [comment]
We need some other name than "-cpp", because we're going to support C#.

**Comment by rozele** [comment]
@MikeHillberg - indeed that's a terrible name for the flag. I believe that @harinikmsft was not in favor of `vnext` or `experimental`, hence that suggestion for now.

**Comment by rozele** [comment]
While we are working from a fork of `react-native`, there's no limit to the options that we have to generate a RNWCPP project. However, I would suggest that we leverage `commander` and implement something analogous to 3. and 4. above (a generator that ships with each version of `react-native-windows` on NPM and a script that calls into that generator from our CLI after installing `react-native-windows`) so that we can easily leverage that code once we're no longer working from a fork.

**Comment by rozele** [comment]
Blocked on #2062, #2080, #2096, and #2101. We need to figure out how we will publish the code before we can invest time in an out of the box experience that downloads dependencies and generates a new project.

**Comment by rozele** [comment]
We can work around the blocker of #2062 and #2094 by publishing our `react-native` fork outside of NPM and not publishing it as a scoped package (i.e., `@microsoft/react-native`)

**Comment by rozele** [comment]
#2096 is not a blocker if the result of #2080 is that we're publishing code as binaries in our `react-native-windows` package. Even if we're shipping as source code, it's not a major blocker, we just need to document where all the native code dependencies are coming from (e.g., are Folly and Yoga coming from our `react-native` fork or are they going to be inlined in our `react-native-windows` package?)

**Comment by rozele** [comment]
Given todays discussion, the remaining blockers are:
- #2094: publish a tarball for `react-native` fork 
- #2101: publish a first version of `react-native-windows` under the new versioning scheme
- #2125: create a minimal "hello world" app for a RNWCPP project

**Comment by harinikmsft** [comment]
Work remaining here is to update the CLI to use the npm published to the public feed.

**Comment by harinikmsft** [comment]
Completed with #2302
