### ISSUE TITLE
Document Image API completion

### ISSUE THREAD

**Issue by kikisaints** [microsoft/react-native-windows#2111]
The following unchecked properties are needed to complete the **Image** control integration into RNWCPP.

## P1
- [x] [**resizeMode - partial**](https://facebook.github.io/react-native/docs/image#resizemode)
Partially supported by Image.  This guy is an Enum:
-cover:  Maps to Image.Stretch.UniformToFill
-contain:  Maps to Image.Stretch.Uniform
-stretch:  Maps to Image.Stretch.Fill
-repeat:  Not directly supported by Image.  Would need to manually repeat, either by creating multiple XAML elements (eg a Grid of Images), or by dropping down to Composition (say, by using XCBB and creating a tiling Composition EffectBrush with a LoadedImageSurface as the input)
-center:  Not directly supported by Image.  Would need to manually center/scale to fit, either in XAML (say, by computing a Brush transform) or by dropping down to Composition (similar to repeat)
- [x] **onError**
Maps to Image.ImageFailed
- [x] **onLoadEnd**
Not directly supported by Image, hook up to Image.ImageOpened/ImageFailed
- [x] **onLoadStart**
Not directly supported by Image, hook up underlying BitmapImage.DownloadProgress

## P2
- [x] **blurRadius** #2631 
Not directly supported by Image element.  Would need to drop down the Composition for this.  One possible proposal (using RS2 APIs):
-Create a XamlCompositionBrushBbase and use this to fill the background of a Panel (eg Canvas)
-The XCBB would create a Composition EffectBrush for the blur, and a LoadedImageSurface as the input.
- [ ] [**defaultSource**](https://facebook.github.io/react-native/docs/image#defaultsource) #2632
*A static image to display while loading the image source.*
Not directly supported by Image.  Would need to manually load/display this, similar to loadingIndicatorSource.
- [ ] **loadingIndicatorSource** #2633
*Similarly to source, this property represents the resource used to render the loading indicator for the image, displayed until image is ready to be displayed, typically after when it got downloaded from network.*
Not directly supported by Image.  Would need to manually load/display the loading indicator image and switch to the real image when it's ready.  There is likely open-source code for this that could be borrowed.
- [ ]  **fadeDuration** #2634

## P3
- [ ] **progressiveRenderingEnabled** #2635
*Typically Android only. When true, enables progressive jpeg streaming. [See here](https://frescolib.org/docs/progressive-jpegs.html).*
Not supported by XAML.  Would need to do the decoding ourselves and render ourselves.
- [ ] **overflow** #2636
https://facebook.github.io/react-native/docs/layout-props#overflow

## Already Completed
- [x] **source**
- [x] **onLayout**
- [x] **onLoad**

| Future |
|:--|
| <ul><li>resizeMethod *Android Only*</li> <li>accessible *iOS Only*</li><li>capInsets *iOS Only*</li><li>onPartialLoad *iOS Only*</li><li>onProgress *iOS Only*</li></ul>|

**Comment by chrisglein** [comment]
Tracking progress in this is now handled in this project board: https://github.com/microsoft/react-native-windows/projects/18
@kikisaints can you move the API status of this to markdown, similar to #2113?

**Comment by kikisaints** [comment]
@chrisglein what parts were you thinking needed to be documented?

**Comment by chrisglein** [comment]
Status of implementation, vnext vs. current, issue tracking for pending implementations, justification for anything "won't fix".
Sync with @SavoySchuler and @harinikmsft as we have a couple of these we want to go after. Savoy was going to take a crack at establishing the pattern.

**Comment by chrisglein** [comment]
All missing APIs are tracked with issues or on the board. We have no immediate plans to create formal per-method API parity documentation, so closing this issue.
