### ISSUE TITLE
[Component] Picker - Property Completion

### ISSUE THREAD

**Issue by kikisaints** [Microsoft/react-native-windows#2112]
The following unchecked properties are needed to complete the **Picker** control integration into RNWCPP.

- [x] **onValueChange**
- [x] **selectedValue**
- [x] **enabled**
*If set to false, the picker will be disabled, i.e. the user will not be able to make a selection.*

| Future |
|:--|
| <ul><li>mode *Android Only* </li><li>prompt *Android Only* </li><li>itemStyle *iOS Only* </li></ul>|

**Comment by MikeHillberg** [comment]
Can we provide some explanations with these?

**Comment by ahimberg** [comment]
This control does have an enabled property already

**Comment by kikisaints** [comment]
> This control does have an enabled property already

I was not able to get it working, but I'd trust your word of my inability to do it - so in that case we can just check off that property and close the issue 😄 !
