### ISSUE TITLE
Document ScrollView API completion

### ISSUE THREAD

**Issue by kikisaints** [microsoft/react-native-windows#2113]
The following unchecked properties are needed to complete the **ScrollView** control integration into RNWCPP.

## P1
- [x] [**snapToInterval**](https://facebook.github.io/react-native/docs/scrollview#snaptointerval)
*When set, causes the scroll view to stop at multiples of the value of ```snapToInterval```.*
Not directly supported by ScrollViewer.  Can be implemented as snap points (Win 8) on the child of the ScrollViewer.
- [x] [**snapToOffsets**](https://facebook.github.io/react-native/docs/scrollview#snaptooffsets)
*When set, causes the scroll view to stop at the defined offsets.*
Not directly supported by ScrollViewer.  Can be implemented as snap points (Win 8) on the child of the ScrollViewer.
- [ ] **snapToStart** #3065
*Use in conjunction with ```snapToOffsets```. By default, the beginning of the list counts as a snap offset. Set ```snapToStart``` to false to disable this behavior and allow the list to scroll freely between its start and the first ```snapToOffsets``` offset. The default value is true.*
Not directly supported by ScrollViewer.  Can be implemented in conjunction with adding snap points (Win 8) to the child of the ScrollViewer.
- [ ] **snapToEnd** #3066
*Use in conjuction with ```snapToOffsets```. By default, the end of the list counts as a snap offset. Set ```snapToEnd``` to false to disable this behavior and allow the list to scroll freely between its end and the last ```snapToOffsets``` offset. The default value is true.*
Not directly supported by ScrollViewer.  Can be implemented in conjunction with adding snap points (Win 8) to the child of the ScrollViewer.
- [x] [**snapToAlignment**](https://facebook.github.io/react-native/docs/scrollview#snaptoalignment)
*When ```snapToInterval``` is set, ```snapToAlignment``` will define the relationship of the snapping to the scroll view.*
Not directly supported by ScrollViewer.  Can be implemented in conjunction with adding snap points (Win 8) to the child of the ScrollViewer.
- [ ] **removeClippedSubviews** #3067
*Experimental: When true, offscreen child views (whose overflow value is hidden) are removed from their native backing superview when offscreen. This can improve scrolling performance on long lists. The default value is true.*
Not directly supported by ScrollViewer.  Seems difficult.  Needs deep dive.
- [ ] [**keyboardDismissMode**](https://facebook.github.io/react-native/docs/scrollview#keyboarddismissmode) #3068
*Determines whether the keyboard gets dismissed in response to a drag.*
Not directly supported by ScrollViewer.  Mobile-specific.  Could be difficult, needs deep dive.
- [x] **scrollEnabled**
*When false, the view cannot be scrolled via touch interaction. The default value is true. Note that the view can always be scrolled by calling ```scrollTo```.*
Maps to ScrollViewer.VerticalScrollMode/HorizontalScrollMode (Win 8)
- [x] **showsHorizontalScrollIndicator**
*When true, shows a horizontal scroll indicator. The default value is true.*
Maps to ScrollViewer.HorizontalScrollBarVisibility (Win 8)
- [x] **showsVerticalScrollIndicator**
*When true, shows a vertical scroll indicator. The default value is true.*
Maps to ScrollViewer.VerticalScrollBarVisibility (Win 8)

## P2
- [ ] **refreshControl** #3069
*A RefreshControl component, used to provide pull-to-refresh functionality for the ScrollView. Only works for vertical ScrollViews (```horizontal``` prop must be ```false```).*
Not directly supported by ScrollViewer.  Could maybe use RefreshContainer from MUX (RS4), or drop down to InteractionTracker (RS1) and build one from scratch.
- [x] **onMomentumScrollBegin**
*Called when the momentum scroll starts (scroll which occurs as the ScrollView glides to a stop).*
Not directly supported by ScrollViewer.  Could hook up to ViewChanging and look at ScrollViewerChangingEventArgs.IsInertial.
- [x] **onMomentumScrollEnd**
*Called when the momentum scroll ends (scroll which occurs as the ScrollView glides to a stop).*
Not directly supported by ScrollViewer.  Could hook up to ViewChanging/ViewChanged and look at ScrollViewerChangingEventArgs.IsInertial.
- [ ] **stickyHeaderIndices** #3070
*An array of child indices determining which children get docked to the top of the screen when scrolling. For example, passing ```stickyHeaderIndices={[0]}``` will cause the first child to be fixed to the top of the scroll view. This property is not supported in conjunction with ```horizontal={true}```.*
Not directly supported by ScrollViewer.  Seems difficult.  Needs deep dive.

## P3
- [ ] [**decelerationRate**](https://facebook.github.io/react-native/docs/scrollview#decelerationrate) #3071
*A floating-point number that determines how quickly the scroll view decelerates after the user lifts their finger.*
Not supported by ScrollViewer.
- [ ] **pagingEnabled** #3072
*When true, the scroll view stops on multiples of the scroll view's size when scrolling. This can be used for horizontal pagination. The default value is false.*
Not directly supported by ScrollViewer.  Can be implemented by adding snap points (Win 8) to the child of the ScrollViewer
- [ ] [**keyboardShouldPersistTaps**](https://facebook.github.io/react-native/docs/scrollview#keyboardshouldpersisttaps) #3073
*Determines when the keyboard should stay visible after a tap.*
Not directly supported by ScrollViewer.  Mobile-specific.  Could be difficult, needs deep dive.

## Already Completed
- [x] **horizontal**
- [x] **onScroll**
- [x] **onScrollBeginDrag**
- [x] **onScrollEndDrag**
- [x] **onContentSizeChange**
- [x] **contentContainerStyle**

| Future|
|:--|
| <ul><li>alwaysBounceVertical *iOS Only*</li><li>endfillColor *Android Only*</li><li>overScrollMode *Android Only*</li><li>scrollPerfTag *Android Only*</li><li>alwaysBounceHorizontal *iOS Only*</li><li>automactiallyAdjustcontentInsets *iOS Only*</li><li>bounces *iOS Only*</li><li>bouncesZoom *iOS Only*</li><li>canCancelContentTouches *iOS Only*</li><li>centerContent *iOS Only*</li><li>contentInset *iOS Only*</li><li>contentInsetAdjustmentBehavior *iOS Only*</li><li>contentOffset *iOS Only*</li><li>directionalLockEnabled *iOS Only*</li><li>indicatorStyle *iOS Only*</li><li>maximumZoomScale *iOS Only*</li><li>minimumZoomScale *iOS Only*</li><li>pinchGestureEnabled *iOS Only*</li><li>scrollEventThrottle *iOS Only*</li><li>scrollIndicatorInsets *iOS Only*</li><li>scrollsToTop *iOS Only*</li><li>zoomScale *iOS Only*</li><li>nestedScrollEnabled *Android Only*</li></ul>|

**Comment by christophermussack** [comment]
I have a pull request to implement just the snapToInterval and the snapToAlignment to be used by the Universal outlook team.
Besides the code change itself this is also for me to learn the process to check this in.

**Comment by chrisglein** [comment]
@kikisaints I've broken all the individual items of pending work here out into a Project board: https://github.com/microsoft/react-native-windows/projects/17
We want to move this type of "index of completion" to exist in the repo as markdown files. Coordinate with @SavoySchuler on how to do that for `ScrollView` as well. I'm assigning this over to you to track that documentation work.

**Comment by chrisglein** [comment]
All missing APIs are tracked with issues or on the board. We have no immediate plans to create formal per-method API parity documentation, so closing this issue.
