### ISSUE TITLE
Investigate hosting RNWCPP component in a Win32 app

### ISSUE THREAD

**Issue by harinikmsft** [Microsoft/react-native-windows#2115]
This work item is meant to track an investigation for hosting RNWCPP component inside a Win32 app using XamlIslands. 

This covers creating a minimal sample Win32 app that does this:
-Prerequisite:  Use the 19H1 SDK and run the app on 19H1
-Create a DesktopWindowXamlSource
-Create a “HostingPane” as the XAML content for the island and borrow all the code from today’s sample HostingPane.  This would give you the same experience you have with today’s sample app (you get the edit boxes and ability to load samples like RNTester).  

With a little more work (1 – 2 days) we could make this more polished.  Note that this doesn’t cover “productizing” the sample into a reusable control, as this isn't required for //build, but it wouldn't hurt to start thinking about an API.

**Comment by rozele** [comment]
Do we need a separate work item to track hosting RNWCPP in a UWP app as well, or is this issue a superset of that?

**Comment by harinikmsft** [comment]
We don't need to investigate hosting in UWP since we know that works today (the samples are doing that). This issue is to just investigate if hosting via XamlIslands in a Win32 app even works. 

We would need to track 2 separate issues to productize hosting components in UWP apps and in Win32 apps. Perhaps as separate controls we ship as nuget packages. This will need deeper design.

**Comment by harinikmsft** [comment]
Moving this to Milestone 2 since we completed the investigation needed for Milestone 1 (using Islands against 19H1+).

**Comment by kmelmon** [comment]
This task was primarily to investigate using XamlPresenter as a short term option for supporting Office downlevel.  After meeting with Office, they are fine waiting for lifted XAML.  Closing.
