### ISSUE TITLE
Optimize SolidColorBrush usage

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#2116]
When setting solid color brushes, a new SolidColorBrush is always created.  

See ValueUtils.cpp => SolidColorBrushFrom() utility function

Can we optimize this?  Ideas:
1) Share SolidColorBrushes that have the same color
2) Only create SolidColorBrush if we haven't already created one, otherwise set the color on the existing brush

**Comment by MikeHillberg** [comment]
Similarly, Image re-creates a new BitmapImage every time you change the source.  We want it to modify the BitmapImage's source instead.
