### ISSUE TITLE
Add ETW instrumentation

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#2119]
Instrument the code with ETW (or other) events so that we can profile the implementation/add debugging info.

What instrumentation/infrastructure already exists here, and can we get a view of perf that is inclusive of both the native code and javascript?  Looking at one of the Facebook videos, it suggests there's already instrumentation available.

- [ ] Make sure the internal logging ETW stuff is manifest based.
- [ ] Verify that console is hookable for UWP impl.

**Comment by harinikmsft** [comment]
Per @mganandraj and @acoates-ms - we should be able to leverage the hook for InitializeTracing and log to ETW.

**Comment by mganandraj** [comment]
The log/error APIs in https://github.com/microsoft/react-native-windows/blob/6cd806bb2486db76195edd47e949f6a9424fc6cb/vnext/Shared/tracing/tracing.h#L16 can be used to send ETW events. The traces can be analyzed following https://github.com/microsoft/react-native-windows/blob/main/docs/tracing.md. Hence i would consider this issue to be closed.

@chrisglein
