### ISSUE TITLE
Convert std:map usage to vector_map

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#2120]
XAML (windows.ui.xaml.dll) has a vector_map implementation that was profiled and shown to outperform std::map.  The API works identical to std::map so converting is purely mechanical/trivial.

This work item is to port vector_map into the codebase and replace usage of std::map

**Comment by edgargonzalez2020** [comment]
I'm interesting in pursuing this. I just wanted to clarify, this would be to change every occurrence of std::map to vector_map in vnext?

**Comment by kmelmon** [comment]
Sorry about the delay, I was on vacation then at a couple offsites this week.

I just chatted with @DefaultRyan who wrote vector_map and is an area expert on data structures.  

Ryan had a couple suggestions as alternatives to copying the vector_map implementation from XAML:
1) boost has something similar to vector_map called flat_map, and we're already using boost so we wouldn't have to copy any code.  However flat_map might not be a suitable replacement for all uses of std::map.  flat_map is faster if you're doing many reads and not a lot of writes.  So we'd have to do some case-by-case analysis on which to convert.

2) Google Abseil's flat_hash_map is a more general purpose map, and Ryan highly recommends it.  See:
https://abseil.io/docs/cpp/guides/container
However this would involve taking a dependency on the absl library.

I think it makes sense to evaluate absl as the first choice, and fall back to flat_map if we don't want to pull in a new dependency for some reason.

@edgargonzalez2020 can you look into these options?

**Comment by BartoszKlonowski** [comment]
As this is nice to have I can work on this in my spare time.
@chrisglein  Please assign me to this issue.

**Comment by vmoroz** [comment]
I wonder if we have any data that shows that std::map slows down RNW code. I would be more concerned with the binary sizes. Any additional library that we add to our code has a risk to increase the size of binaries. With many current scenarios the size of the RN code is often one of the biggest questions we usually must answer, especially on mobile platforms and entry-level laptops.
@BartoszKlonowski, it would be nice if we do not add dependency on the Google Abseil's library.
In many cases std::map can be used unchanged or simply replaced with std::unordered_map.
