### ISSUE TITLE
Add accessibilityRole support in rnwcpp

### ISSUE THREAD

**Issue by ahimberg** [microsoft/react-native-windows#2122]
this is related to automationPeers issue

**Comment by ahimberg** [comment]
This is partially done, we have accessibilityRole=button but should fill in the rest to map to UIA equivalents

**Comment by kmelmon** [comment]
Consolidating accessibility work - Jon will take this.

**Comment by jonthysell** [comment]
This work is now split out over #2565, #2566, #2568.
