### ISSUE TITLE
Implement accessibilityLiveRegion property, and "announce" the change in rnwcpp

### ISSUE THREAD

**Issue by ahimberg** [microsoft/react-native-windows#2124]
Android docs: https://facebook.github.io/react-native/docs/accessibility#accessibilityliveregion-android

RNW Current implementation: https://github.com/microsoft/react-native-windows/blob/master/current/ReactWindows/ReactNative/UIManager/BaseViewManager.cs#L172

`accessibilityLiveRegion` is just a simple accessibility property that needs be set in FrameworkElementViewManager.

The "announce" is just raising the right event, which we should do with something similar to the rnw current: https://github.com/microsoft/react-native-windows/blob/master/current/ReactWindows/ReactNative/Accessibility/AccessibilityHelper.cs#L370

**Comment by kmelmon** [comment]
We may able to copy the C# implementation for this

**Comment by jonthysell** [comment]
This seems pretty straight-forward, updating the description with what the C# implementation does.
