### ISSUE TITLE
[Onboarding] Minimal "Hello World" demo

### ISSUE THREAD

**Issue by rozele** [Microsoft/react-native-windows#2125]
The [Universal.SampleApp](https://github.com/Microsoft/react-native-windows/tree/rnwcpp-preview/RNWCPP/Universal.SampleApp) is a good starting point for a react-native-windows app, but we need a minimal Hello World app that we can convert into a template for generating new `react-native-windows` projects.

This would be analogous to the project that gets generated by the `react-native windows` command for C#. For reference, the [Playground](https://github.com/Microsoft/react-native-windows/tree/master/ReactWindows/Playground) project is roughly equivalent to the template.

**Comment by harinikmsft** [comment]
Added a Playground C# sample app. See [commit](https://github.com/Microsoft/react-native-windows/commit/4a9c025d91855fe517ea4371bc4e26a92dd2b12e)

**Comment by harinikmsft** [comment]
Move to separate solution, add debug option for web debugging

**Comment by akrantz** [comment]
It would be great to also have direct debugging work here.

**Comment by harinikmsft** [comment]
Completed - [Playground](https://github.com/Microsoft/react-native-windows/tree/rnwcpp-preview/RNWCPP/Playground)
