### ISSUE TITLE
Animation perf analysis

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#2126]
Animations in RN are all "dependent" as they tick on the UI thread.  Need to do some perf analysis to determine if this will result in glitchy animations, particularly for those that could potentially be done as "independent" animations (eg translation/opacity).

**Comment by rozele** [comment]
We have non-dependent animations using Storyboard for the `LayoutAnimation` feature in React Native. Here: https://github.com/Microsoft/react-native-windows/tree/master/ReactWindows/ReactNative.Shared/UIManager/LayoutAnimation

As far as the JS Animations module goes, there is a `NativeAnimated` module, which works with a subset of features from `Animations`. As far as I know, the RNWCPP solution has not implemented the `NativeAnimated` module. We implemented it in C# [here](https://github.com/Microsoft/react-native-windows/tree/master/ReactWindows/ReactNative.Shared/Animated). The `NativeAnimated` module constructs the animation "graph" in native code, and I image we could analyze the leaf nodes of the animation graph and determine if they must be dependent animations (i.e., impact layout).
