### ISSUE TITLE
Establish perf baseline comparison (C# vs C++)

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#2127]
Gather some baseline perf numbers for both C++ and C# implementation and compare.  C++ should outperform C#.

**Comment by rozele** [comment]
FYI - we have some ETW events sprinkled throughout the C# repo. They are based on the Systrace events used on Android.

E.g., if you're measuring startup, we have e.g.:
- an event that measures time to create view managers: https://github.com/Microsoft/react-native-windows/blob/master/ReactWindows/ReactNative.Shared/ReactInstanceManager.cs#L474
- an event that measures time to invoke a JS function: https://github.com/Microsoft/react-native-windows/blob/master/ReactWindows/ReactNative.Shared/Bridge/ReactInstance.cs#L154
- an event that measures time to invoke a native module: https://github.com/Microsoft/react-native-windows/blob/master/ReactWindows/ReactNative.Shared/Bridge/NativeModuleRegistry.cs#L253

**Comment by stecrain** [comment]
Any interest in comparing performance to a regular XAML UWP (C++ or C#)? Ideally this would be even faster 🔥🔥

**Comment by jonthysell** [comment]
Ideally we should have one "app" with a lot of UI that gets implemented in multiple ways:

1. RNWCS
2. RNWCPP
3. C# XAML Markup
4. C# Xaml APIs
5. C# XamlDirect

Then we do a bunch of perf  tests.

**Comment by jonthysell** [comment]
This work currently in [jonthysell:perfcompare](/jonthysell/react-native-windows/tree/perfcompare).
