### ISSUE TITLE
[ThirdParty] Document example for creating C# view managers

### ISSUE THREAD

**Issue by rozele** [microsoft/react-native-windows#2131]
Ultimately, we want to provide an interface for view managers in C# that is similar to our [existing interface](https://github.com/Microsoft/react-native-windows/blob/master/RNWCS/ReactWindows/ReactNative.Shared/UIManager/IViewManager.cs) as possible, so we can provide a simple migration story for existing apps with custom view managers.

**Comment by chrisglein** [comment]
https://github.com/microsoft/react-native-windows/blob/master/vnext/docs/ViewManagers.md#sample-viewmanager-c
