### ISSUE TITLE
[Onboarding] Create template for 'react-native init'

### ISSUE THREAD

**Issue by rozele** [microsoft/react-native-windows#2133]
The `react-native init` tool allows a user to specify a template that swaps out the typical Hello World app that the CLI tool produces with some custom template. A nice example of this is the Typescript starter template, which you would use by running:
```
react-native init MyApp --template typescript
```

We should smooth out the onboarding experience for `react-native-windows` by creating a template, so you would only need to run:
```
react-native init MyApp --template windows
```
Rather than:
```
react-native init MyApp
yarn add rnpm-plugin-windows
react-native windows
```

**Comment by rozele** [comment]
Realistically, while we're working from a fork, the `init` command will look more like:
```
react-native init MyApp --template windows --version https://github.com/Microsoft/react-native/archive/v0.57.0.tar.gz
```

**Comment by harinikmsft** [comment]
@in4margaret - can you investigate what is needed here from a CLI standpoint?

**Comment by chrisglein** [comment]
We now have a prompt in `react-native init` that points developers to how to add windows support. This seems good enough. Closing out this issue.
