### ISSUE TITLE
Document TextInput API completion

### ISSUE THREAD

**Issue by kikisaints** [microsoft/react-native-windows#2136]
The following unchecked properties are needed to complete the **TextInput** control integration into RNWCPP.

## P1
- [x] **autoFocus**

## P2
- [x] **secureTextEntry** #3081
Not directly supported by TextBox.  PasswordBox has this functionality.  Can we hot-swap between TextBox/PasswordBox?
- [x] **keyboardType** #3080
Maps to TextBox.InputScope (Win8/Win8.1)
- [ ] **autoComplete** #3079
Maps to TextBox.IsSpellCheckEnabled (Win8)

## P3
- [x] **contextMenuHidden** #3088
Not supported by XAML
- [x] **caretHidden** #3087
Not supported by TextBox.  Is supported by RichEditBox.TextDocument.CaretType.  We could maybe hack this to work in TextBox by using VisualTreeHelper.
- [ ] **autoCorrect** #3086
- [ ] **autoCapitalize** #3085
Incomplete support in XAML.  This guy is an enum:
-characters:  Maps to TextBox.CharacterCasing.Upper (RS3)
-words: Not supported
-sentences: Not directly supported.  TextBox.IsSpellCheckEnabled (Win8) turns on auto-capitalizing first word in a sentence (which maps to autoCapitalize.sentences) but this also turns on spell-checking.  Also, MikeHill says:  Some of the auto capitalization functionality in TextBox is behind the InputScope API.
-none: Supported by default
- [ ] **blurOnSubmit** #3084
Not supported in XAML
- [x] **onSubmitEditing** #3083
Needs more investigation.   Mobile specific feature, is this needed?
- [ ] **returnKeyType** #3082
Needs more investigation.  Mobile specific feature, is this needed?

## Already Completed
- [x] **clearTextOnFocus**
- [x] **defaultValue**
- [x] **editable**
- [x] **maxLength**
- [x] **multiline**
- [x] **onBlur**
- [x] **onChange**
- [x] **onChangeText**
- [x] **onContentSizeChange**
- [x] **onEndEditing**
- [x] **onFocus**
- [x] **onKeyPress**
- [x] **onLayout**
- [x] **onScroll**
- [x] **onSelectionChange**
- [x] **selection**
- [x] **selectionColor**
- [x] **selectTextOnFocus**
- [x] **value**
- [x] **allowFontScaling**
Maps to Control.IsTextScaleFactorEnabled (Phone 8.1)
- [x] **placeholder**
- [x] **placeholderTextColor**

| Future|
|:--|
| <ul><li>clearButtonMode *iOS Only*</li><li>dataDetectorTypes *iOS Only*</li><li>disabledFullscreenUI *Android Only*</li><li>enablesReturnKeyAtuomatically *iOS Only*</li><li>inlineImageLeft *Android Only*</li><li>inlineImagePadding *Android Only*</li><li>keyboardAppearance *iOS Only*</li><li>maxFontSizeMultiplier *iOS Only*</li><li>numberOfLines *Android Only*</li><li>returnKeyLabel *Android Only*</li><li>scrollEnabled *iOS Only*</li><li>selectionState *iOS Only*</li><li>spellCheck *iOS Only*</li><li>textContentType *iOS Only*</li><li>textBreakStrategy *Android Only*</li><li>underlineColorAndroid *Android Only*</li></ul> |

**Comment by ahimberg** [comment]
We have code for selection, onScroll, onBlur, are those not working?

**Comment by kikisaints** [comment]
I wasn't able to get them working, but again I'm no expert at Javascript or React Native development. So I'll check those ones off. Thanks!

**Comment by MikeHillberg** [comment]
Some of the auto capitalization functionality in TextBox is behind the InputScope API.

**Comment by kmelmon** [comment]
@licanhua can you start the process of figuring out priority/cost for the remaining properties on this list?
Just glancing at the list, IMO secureTextEntry is pretty important as this is the equivalent of PasswordBox.

**Comment by chrisglein** [comment]
@ddalp I've split all the items here into individual issues under this project board: https://github.com/microsoft/react-native-windows/projects/20

@harinikmsft as with the other issues I'm converting this to a doc issue to track API completion (like scrolling, image, etc.)

**Comment by harinikmsft** [comment]
We have moved away from documenting specific APIs for completion and instead tracking through the label [API:Completion](https://github.com/microsoft/react-native-windows/labels/API%3A%20Completion) since the total number of such issues has now reached a small enough number to not warrant specific documentation. 

I am closing this issue now since each individual item is being tracked with the right priorities independently.
