### ISSUE TITLE
Incorrect react-native dependency in preview branch

### ISSUE THREAD

**Issue by stecrain** [Microsoft/react-native-windows#2137]
package.json currently checked into the rnw-cpp branch  specifies dependency on react-native version 0.0.1

Running npm install fails to install the dependency. Seems like an accidental change with the recent updates.

**Comment by stecrain** [comment]
To unblock myself for prototyping with latest changes i had to revert start.js, and rn-cli.config.js as well.

**Comment by ahimberg** [comment]
sorry about that, I've just updated rnwcpp-preview to fix this
