### ISSUE TITLE
[Infrastructure] Validate OSS contributions can be taken through repo

### ISSUE THREAD

**Issue by harinikmsft** [Microsoft/react-native-windows#2139]
We need to validate that external contributions to the RNWCPP_Preview branch can be taken and unblock this work flow.

**Comment by faisalil** [comment]
Hey, what is RNWCPP? I see this flag being added to a lot of issues and I looked to try to understand what is happening but I couldn't.

**Comment by stephenheron** [comment]
@faisalil A little bit more info on RNWCPP can be found here: https://github.com/Microsoft/react-native-windows/blob/rnwcpp-preview/RNWCPP/README.md

**Comment by faisalil** [comment]
thanks for the info @stephenheron, what is the timeline for this to be ready and usable? I am assuming one of the goals is to keep more in sync with main react native and get updates more frequently. I really think this is important and will help with the adoption of this project.

**Comment by harinikmsft** [comment]
We just added a note on the status in the main landing page of the repo - [Status](https://github.com/Microsoft/react-native-windows#status). Stay tuned, we will publish more details and timelines shortly.

**Comment by harinikmsft** [comment]
This has been validated, contributions can be taken through the repo.
