### ISSUE TITLE
[Component] Switch - Property Completion

### ISSUE THREAD

**Issue by kikisaints** [microsoft/react-native-windows#2140]
The following unchecked properties are needed to complete the **Switch** control integration into RNWCPP.

## P1
- [x] trackColor
- [x] thumbColor
- [x] tintColor

## Already Completed
- [x] disabled
- [x] onValueChanged
- [x] value

**Comment by ddalp** [comment]
Done.

**Comment by harinikmsft** [comment]
@kikisaints - can you update [parity status](https://github.com/microsoft/react-native-windows/blob/master/vnext/docs/ParityStatus.md) with Switch as completed?
