### ISSUE TITLE
[Module] Layout Props - Property Completion

### ISSUE THREAD

**Issue by kikisaints** [Microsoft/react-native-windows#2143]
The following unchecked properties are needed to complete the **LayoutProps** module integration into RNWCPP.

## Already Completed
- [x] alignContent
- [x] alignItems
- [x] alignSelf
- [x] aspectRatio
- [x] borderBottomWidth
- [x] borderEndWidth
- [x] borderLeftWidth
- [x] borderRightWidth
- [x] borderStartWidth
- [x] borderTopWidth
- [x] borderWidth
- [x] bottom
- [x] display
- [x] end (implemented, but doesn't work without RTL #2109)
- [x] flex
- [x] flexBasis
- [x] flexDirection
- [x] flexGrow
- [x] flexShrink
- [x] flexWrap
- [x] height
- [x] justifyContent
- [x] left
- [x] margin
- [x] marginBottom
- [x] marginEnd
- [x] marginHorizontal
- [x] marginLeft
- [x] marginRight
- [x] marginTop
- [x] marginVertical
- [x] maxHeight
- [x] maxWidth
- [x] minHeight
- [x] minWidth
- [x] overflow
- [x] padding
- [x] paddingBottom
- [x] paddingEnd
- [x] paddingHorizontal
- [x] paddingLeft
- [x] paddingRight
- [x] paddingStart
- [x] paddingTop
- [x] paddingVertical
- [x] position
- [x] right
- [x] start (implemented, but doesn't work without RTL #2109)
- [x] top
- [x] width
- [x] borderColor
- [x] zIndex

| Future |
|:--|
| <ul><li>direction *iOS only*</li></ul>|

**Comment by ahimberg** [comment]
We're missing thumbColor and trackColor also (and may need to define more props to over all the possible states on windows (hover/pressed/disabled) - which are shown in RNTester's SwitchExample

**Comment by jonthysell** [comment]
P1s implemented by #2359.

Though until we implement RTL in #2109, technically some of these implemeted properties (like start and end) do not function as expected.

@harinikmsft / @kikisaints, do we want to close this now and just track the functionality in the RTL issue?

**Comment by harinikmsft** [comment]
@jonthysell closing this and tracking RTL separately sounds good to me. @kikisaints  - do we need to bring the RTL issue to Milestone 2 (was it needed for key initial scenarios?)

**Comment by ahimberg** [comment]
as long as RTL works when the default direction is RTL in the app (running when OS UI language is RTL) that may be sufficient for Milestone 2.  -- and in testing our shipping scenario in RTL, things do seem to behave correctly for the basics

**Comment by jonthysell** [comment]
Ok, I'm going to close this as complete, and add a comment to #2109. If RTL becomes an issue, we can pull this into milestone 2.
