### ISSUE TITLE
TextInput sends change notification when setting value

### ISSUE THREAD

**Issue by ahimberg** [microsoft/react-native-windows#2148]
We ran into this when using TextInput in a redux scenario where we would set textinput.value to the most recent text changed event text.  When doing that you can get into an infinite updating loop.

We do attempt to not send change notifications while updating the Text property on the textinput xaml control, but timing or multiple updates are an issue.  Android and iOS do something with an event counter maybe to avoid this problem.

**Comment by kmelmon** [comment]
Andy says that the app code has been changed to avoid this issue.  The previous code was doing something dangerous - saving the text in onChangeText and then setting it after an async event fires.  

There are a couple things we should still consider doing.  I looked at the Android implementation, it does a couple things we don't do:
1) It raises onChange which has an additional monotonically increasing event counter which could maybe be useful for this type of pattern.
2) It checks to see if the text has actually changed before raising the event.  XAML TextBox may already provide this guarantee, but if not we should guard against it.
