### ISSUE TITLE
Components need to respect High Contrast colors

### ISSUE THREAD

**Issue by YuliKl** [microsoft/react-native-windows#2151]
- [ ] Button
- [ ] TouchableHighlight
- [ ] TouchableOpacity
- [ ] FlatList
- [ ] SectionList

**Comment by jonthysell** [comment]
Currently verifying if this needs to happen in Milestone 2.

**Comment by kmelmon** [comment]
The high contrast event and colors are now complete.  This item is tracking applying those colors to js components.  Moving this to Milestone 3.
