### ISSUE TITLE
RNWCPP needs to support AcessibilityView Raw

### ISSUE THREAD

**Issue by YuliKl** [microsoft/react-native-windows#2161]
Currently, there is no way to set a component to Raw [AccessibilityView](https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.xaml.automation.automationproperties.accessibilityview.aspx). As a result, specifying a label for CheckBox requires inserting a Text component, and Narrator is able to move focus to the Text.

- [ ] CheckBox
- [ ] Switch

Re-reading the [documentation about the accessible prop](https://facebook.github.io/react-native/docs/accessibility.html#accessible-ios-android), I wonder if setting accessible="true" on the Text's parent actually results in the correct behavior.

**Comment by ahimberg** [comment]
actually our current implementation of FrameworkElementViewManger does this when you set accessible="false" but that is not quite right, we had that getting polyester buttons minimally functional and need to revisit this

**Comment by chrisglein** [comment]
Not something we plan to address on the Paper renderer as we move towards Fabric.
Fabric API completion is tracked here: https://github.com/microsoft/react-native-windows/issues/11898
