### ISSUE TITLE
Text component in rnwcpp shouldn't clip at 200% 

### ISSUE THREAD

**Issue by YuliKl** [microsoft/react-native-windows#2162]
When users choose to make text bigger in their Ease of Access display settings on Windows, the size of the characters increases but the line height does not. Text quickly becomes completely illegible because it's clipped.

This issue is related to the allowFontScaling prop mentioned in #2121

**Comment by ahimberg** [comment]
I think this is just a measure bug, but we were realizing also that our implementation of the DeviceInfo module has not implementing firing events when things change

**Comment by ddalp** [comment]
This issue does not repro any more, likely fixed by Jon's change to hook up CoreWindow bounds in DeviceInfo.

**Comment by harinikmsft** [comment]
@kikisaints - can you update [parity status](https://github.com/microsoft/react-native-windows/blob/master/vnext/docs/ParityStatus.md) so this issue is removed from Text's open issues and marked as Complete.

**Comment by kikisaints** [comment]
@harinikmsft made a PR here https://github.com/microsoft/react-native-windows/pull/3651
