### ISSUE TITLE
Remove dependency on OpenSSL.Windows-1.0.2n nuget

### ISSUE THREAD

**Issue by acoates-ms** [Microsoft/react-native-windows#2170]
The OpenSSL.Windows-1.0.2n nuget isn't published in the public feed. We need to remove this dependency to allow 3rd party developers to be able to build RNWCPP.

**Comment by JunielKatarn** [comment]
As per offline discussion, the first approach will be to promote a change in OpenSSL to allow explicitly setting the calling convention in their public headers through a macro.

**Comment by kmelmon** [comment]
Solved for now by creating 2 solutions, one for opensource, one for Office.  Closing
