### ISSUE TITLE
CalendarView control should be removed from RNWCPP

### ISSUE THREAD

**Issue by sasha-gil** [Microsoft/react-native-windows#2179]
In case if we need a generic CalendarView control in RNWCPP we will re-create it but for now it's not of production quality so it should better be removed.

**Comment by kikisaints** [comment]
Can you be a bit more specific around what's not of production quality? I believe we translate the ReactNative version to XAML's CalendarView, which means it has all the same functionality and features that UWP XAML supports today as a publicly released control.

**Comment by sasha-gil** [comment]
The current implementation that I am up to removing is somewhat naïve: it exposed almost all (but not all) properties of XAML's CalendarView as properties of the correspondent RN control - but that is not enough. For example, there are properties for styling CalendarItem, DayItem, MonthYearItem, FirstOfMonthLabel, FirstOfYearDecadeLabel - plus elements of styling for Selected, Today. But, styling for Month / Year / Decade text at the header of the control is not provided (same for up / down chevron buttons). XAML documentation recommends to use a control template for that and this is not a good choice for RN (yes, there are ways to cope with that but that requires more experimentation). Overall the control was placed here as a part of an experiment on reusing a larger XAML building block, it was only partially successful and thus has to be pulled out for now.

**Comment by sasha-gil** [comment]
The issue is resolved by commit [#778bae1](https://github.com/Microsoft/react-native-windows/commit/778bae1637ef32aa3974b123aee7abe9bd2e4212#diff-cb8b5f70552f61e819f735f8afcd2d66).
