### ISSUE TITLE
[Gamepad] Cannot invoke TouchableHighlight or TouchableOpacity content

### ISSUE THREAD

**Issue by kikisaints** [microsoft/react-native-windows#2182]
Using the Xbox controller (gamepad), I cannot invoke any content wrapped with TouchableHighlight or TouchableOpacity using the A button.

**Comment by ahimberg** [comment]
How does xbox A button event come in?  We currently only support click via mouse/pointer events, keyboard input looking at space/enter, and accessibility invoke.  There must be some additional event to hook in ViewViewManager::CreateViewControl that should be simple

**Comment by micahl** [comment]
This issue seems like a dupe of #2085.

**Comment by harinikmsft** [comment]
Using #2085 to track this work in addition to keyboard.
