### ISSUE TITLE
Enable XYFocus behavior

### ISSUE THREAD

**Issue by kikisaints** [microsoft/react-native-windows#2197]
Xbox needs the ability to specify where focus should go when using the gamepad. Today, in XAML, this is done through setting the XYFocus properties on a UIElement. A similar behavior is needed in RNWCPP (or one that yields the same run time result).

**Comment by kmelmon** [comment]
can maybe get info from Matt Haggert on how this was done for Playstation

**Comment by jonthysell** [comment]
Looking here for documentation: https://docs.microsoft.com/en-us/windows/uwp/design/input/gamepad-and-remote-interactions#xy-focus-navigation-and-interaction

Looks like we need to expose the XYFocus properties to Views, where you specify a specific element when a direction is pressed, but we'll need to provide some kind of identifier (tag?) to the target View:

**P1:**
- [ ] [Control.XYFocusUp](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.control.xyfocusup)
- [ ] [Control.XYFocusDown](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.control.xyfocusdown)
- [ ] [Control.XYFocusLeft](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.control.xyfocusleft)
- [ ] [Control.XYFocusRight](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.control.xyfocusright)

Do we need to expose the [XYFocusNavigationStrategy](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.input.xyfocusnavigationstrategy)-based properties? If so, I think they'd be P2.

**P2:**
- [ ] [UIElement.XYFocusUpNavigationStrategy](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.xyfocusupnavigationstrategy)
- [ ] [UIElement.XYFocusDownNavigationStrategy](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.xyfocusdownnavigationstrategy)
- [ ] [UIElement.XYFocusLeftNavigationStrategy](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.xyfocusleftnavigationstrategy)
- [ ] [UIElement.XYFocusRightNavigationStrategy](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.xyfocusrightnavigationstrategy)

**Comment by jonthysell** [comment]
Currently verifying if we need this for Milestone 2.

**Comment by chrisglein** [comment]
@harinikmsft Is there any design work still needed here or is this dev ready?

**Comment by harinikmsft** [comment]
Verified with Xbox customers that the built-in XY focus behaviors are adequate for scenarios at this time. We can revisit this later once we are done with pressing issues.

**Comment by harinikmsft** [comment]
The default built-in behavours for XY focus have been sufficient for Xbox scenarios. Closing this as no longer needed in the RN layer.
