### ISSUE TITLE
autoFocus for TextInput should automatically open virtual keyboard

### ISSUE THREAD

**Issue by kikisaints** [microsoft/react-native-windows#2198]
This is a request/would like to have from Xbox. When you enable the autoFocus property on TextInput it should also open up the virtual keyboard once focus has been placed into the input box.

**Comment by kmelmon** [comment]
This is supposed to "just work" for certain ways of getting focus (apparently, through keybaord focus (?)).  Need to determine if those automatic mechanisms are sufficient for this.

**Comment by kmelmon** [comment]
This isn't critical for Milestone 2.  Moving to Milestone 3.
