### ISSUE TITLE
[Theming] Ensure Light/Dark themes respond correctly in React Native created apps

### ISSUE THREAD

**Issue by kikisaints** [microsoft/react-native-windows#2206]
# Theming In RNWCPP
We need to make sure that the theme switching that we have today works correctly with all the resources in an RNWCPP app.
This is most important for high contrast, but light and dark theme switching is a close second.

## What if we did nothing?
There are a few things we get for "free" without having to do any changes/hookups.

- Components interop-ing directly with XAML controls will get light/dark theme changes "for free", as there's nothing on the JS layer that needs to know about it
- Text and any "default" colors (i.e. colors not specified at the JS layer) also get the theme changes for free, as they're translated to use the corresponding theme brushes once they reach the XAML layer.

Unfortunately, doing nothing still isn't really an option. Because Text and directly/fully native controls will **do honor the theme**, you'll get a whole different breed of Zebra UI if nothing is done:

From this:
![image](https://user-images.githubusercontent.com/6964369/58272597-be453c00-7d43-11e9-98fd-80523cb74ad1.png)
 
To this
![image](https://user-images.githubusercontent.com/6964369/58272603-c0a79600-7d43-11e9-958c-ba9077afcdec.png)

In addition, many app developers wish to "blend" more with the native platform, and would not only want to honor theme changes, but actually know about it to theme around those changes.

# Requirements/Scope
There are a few core things that need to be available to the RN app developer if we want a well-themed system.

|# |Feature | Priority |
|:-|:-|:-|
| 1 | Ability to detect when the theme has changed |Must |
| 2 | Have a method of accessing our theme brushes through the RN CSS layer so custom components can apply them | Should |

## Important Notes
The Dark/Light theming issues really mirror the same "surface level" coloring and theming issues that XAML has today, even when writing natively.

- If you set a color property directly on a native XAML control, you'll be overwriting the theming of that brush, thus breaking the Requested Theme changes
- The same thing is happening at the JS layer with React Native and the CSS-like color/brush style definitions - defining any CSS properties on a component will overwrite any theme automation that was previously there

# Open Questions

- What does RN do today on iOS and Android for the Light/Dark and High Contrast themes for the JS components?
- Is there a pre-existing RN JS API that we could re-purpose to also handle/target our Requested Theme change events?
- Do we need to provide a mapping system or separate RN CSS plugin that allows app developers to access our theme brushes at the RN CSS layer?
- Could we provide a RN CSS theme that maps to our theme brushes depending on the type of component (or it's parts) that the app developer is trying to make?

**Comment by harinikmsft** [comment]
Issue #2151 is tracking high contrast. This issue is to track light/dark theme in JS components

**Comment by kmelmon** [comment]
Load balancing this over to Marlene

**Comment by harinikmsft** [comment]
Fixed by #2684

**Comment by marlenecota** [comment]
#2705 - Part 1 of implementing windowsbrush
