### ISSUE TITLE
Ensure properties and colors set through React Native styling map to native controls reasonably

### ISSUE THREAD

**Issue by kikisaints** [microsoft/react-native-windows#2207]
This issue covers the work we'll need to do to ensure that the styling set on components at the Javascript React Native level translate as nicely as possible to the native controls.

# Theming in React Native for windows
There are many easy ways to color and theme JavaScript components in RN through CSS, but the reverse (targeting brushes or colors of native controls) is a bit trickier.

## Levels of styling to be exposed
We will be introducing two different levels of styling, one being what we'll be pushing into lean core React Native, and only we will be implementing for the Windows module only (Windows "extended" if you will).

### [P0] Styling native lean core components in React Native
In this case, the table defined above is the extent of the customization capabilities available to the RN app-developer at the JS layer. They will have to live with the native's choice for hover and other state colors/styles unless they choose to consume the Windows extended module (defined in next section).

> **Open Issue:** Currently looking for feedback from community around introducing a "pressedColor". This property would be mapped to the native control's corresponding "main" color, and in the XAML-case would override the VSM property for that color on the pressed state.

#### If pressed events were added to lean core
If the above open issue were to be closed, proposed, and implemented into vanilla React Native, we could expect one extra layer of component state customization, that could look something like this:

``` JavaScript
const styles = StyleSheet.create({
  myPickerStyle: {
    width: 200,
    height: 45,
    backgroundColor: 'red',
    pressedColor: 'dark gray',
    pressedBackgroundColor: 'white',
  },
});
```

### [P1] Styling native lean core components in RN Windows extended
In this case we will be exposing all of the properties, in every state, that exist on each lean core component.

For example, we would have enough properties exposed on our lean core components in Windows extended to enable scenarios such as this:

``` JavaScript
const styles = StyleSheet.create({
  myPickerStyle: {
    width: 200,
    height: 45,
    backgroundColor: 'red',
    Platform.select({
        windows: {
          backgroundColorHover: 'dark red',
          borderColorHover: 'grey',
        },
     }),
  },
});
```

Where the `backgroundColorHover` and `borderColorHover` in the `Picker` control case would map to the XAML lightweight styling resources `ComboBoxBackgroundPointerOver` and `ComboBoxBorderBrushPointerOver`, respectively.

## [P2] Expand the windowsBrush capabilities
Currently, the ``windowsBrush`` API in the React Native Windows implementation handles system colors only. This proposal asks to expand that API's capabilities to handle:

```
const styles = StyleSheet.create({
  someViewStyle: {
    width: 200,
    height: 45,
    backgroundColor: {windowsBrush: 'ButtonBackground'},
  },
  someOtherViewStyle: {
    alignItems: center;
    backgroundColor: {windowsBrush: 'SystemControlBackgroundBaseMediumBrush'},
  }
});
```

## [P0] Stylesheet properties align with XAML native properties
The general approach to control customization in React Native is to build your own control from primitives, and therefore be able to easily access any and all parts to color them accordingly.

However, in the case where you want to color or theme a native control - i.e. want to access it's native properties to set the colors yourself without building it out of primitives - we should look at how we can do this by mapping the css-like properties specified in the JS stylesheets to the native control properties, should they exists.

>The following are modified tables from [this open source readme](https://github.com/vhpoet/react-native-styling-cheat-sheet/blob/master/README.md).

This list looks at what React Native properties exist in the stylesheets that could be mapped to the **lean core** controls on the XAML side.

>This will not take into account how these set of properties could/do apply to container controls in XAML, like View -> Canvas/Grid etc. This is **not** looking at XAML primitives, only UIElements in general.

| RN CSS Property | RN Default | XAML Control Property Equivalent |
|------|---------|-------------|
| alignContent | | `HorizontalAlignment`<br>`VertcialAlignment` |
| aspectRatio | [number](#number) | `MinHeight`?<br>`MinWidth` ? |
| borderBottomWidth | [number](#number) |`BorderThickness(0, 0, 0, value)` |
| borderLeftWidth | [number](#number) | `BorderThickness(value, 0, 0, 0)`|
| borderRightWidth | [number](#number) | `BorderThickness()<br>0, 0, value, 0)`|
| borderTopWidth | [number](#number) | `BorderThickness(0, value, 0, 0)`|
| borderEndWidth | [number](#number)<br>*When direction is ltr, `borderEndWidth` is equivalent to `borderRightWidth`. <br>When direction is rtl, `borderEndWidth` is equivalent to `borderLeftWidth`.* | `BorderThickness(0, 0, value, 0)`<br>OR<br>`BorderThickness(value, 0, 0, 0)`<br>Depending |
| borderStartWidth | [number](#number)<br>*When direction is ltr, ``borderStartWidth`` is equivalent to ``borderLeftWidth``. <br>When direction is rtl, ``borderStartWidth`` is equivalent to ``borderRightWidth``.* | `BorderThickness(value, 0, 0, 0)`<br>OR<br>`BorderThickness(0, 0, value, 0)`<br>Depending |
| borderWidth | [number](#number) | `BorderThickness(value, value, value, value)`<br>If set to **thin**:<br>`BorderThickness(1, 1, 1, 1)`<br>If set to **medium**:<br>`BorderThickness(3, 3, 3, 3)`<br>If set to **thick**:<br>`BorderThickness(5, 5, 5, 5)` |
| direction | [oneOf](#oneof) `inherit`, `ltr`, `rtl` | `FlowDirection`|
| height | [number](#number) |`Height`|
| margin | [number](#number) | `Margin(value, value, value, value)` |
| marginBottom | [number](#number) | `Margin(0, 0, 0, value)` |
| marginHorizontal | [number](#number) | `Margin(value, 0, value, 0)` |
| marginLeft | [number](#number) | `Margin(value, 0, 0, 0)` |
| marginRight | [number](#number) | `Margin(0, 0, value, 0)` |
| marginTop | [number](#number) | `Margin(0, value, 0, 0)` |
| marginVertical | [number](#number) | `Margin(0, value, 0, value)` |
| marginEnd | [number](#number)<br>*When direction is `ltr`, `marginEnd` is equivalent to `marginRight`. <br>When direction is `rtl`, `marginEnd` is equivalent to `marginLeft`.* | `Margin(0, 0, value, 0)`<br>OR<br>`Margin(value, 0, 0, 0)`|
| marginStart | [number](#number)<br>*When direction is `ltr`, `marginStart` is equivalent to `marginLeft`. <br>When direction is `rtl`, `marginStart` is equivalent to `marginRight`.* | `Margin(value, 0, 0, 0)`<br>OR<br>`Margin(0, 0, value, 0)` |
| maxHeight | [number](#number) | `MaxHeight` |
| maxWidth | [number](#number) | `MaxWidth` |
| minHeight | [number](#number) | `MinHeight` |
| minWidth | [number](#number) | `MinWidth` |
| padding | [number](#number), [string](#string) | `Padding(value, value, value, value)`|
| paddingBottom | [number](#number), [string](#string) | `Padding(0, 0, 0, value)` |
| paddingHorizontal | [number](#number), [string](#string) | `Padding(value, 0, value, 0)`|
| paddingLeft | [number](#number), [string](#string) |`Padding(value, 0, 0, 0)` |
| paddingRight | [number](#number), [string](#string) | `Padding(0, 0, value, 0)`|
| paddingTop | [number](#number), [string](#string) | `Padding(0, value, 0, 0)`|
| paddingVertical | [number](#number), [string](#string) | `Padding(0, value, 0, value)` |
| paddingEnd | [number](#number), [string](#string)<br>*When direction is `ltr`, `paddingEnd` is equivalent to `paddingRight`.<br> When direction is `rtl`, `paddingEnd` is equivalent to `paddingLeft`.* | `Padding(0, 0, value, 0)`<br>OR<br>`Padding(value, 0, 0, 0)` |
| paddingStart | [number](#number), [string](#string)<br>*When direction is `ltr`, `paddingStart` is equivalent to `paddingLeft`. <br>When direction is `rtl`, `paddingStart` is equivalent to `paddingRight`.* | `Padding(value, 0, 0, 0)`<br>OR<br>`Padding(0, 0, value, 0)` |
| width | [number](#number) | `Width` |
| color| `ColorPropType` | `Foreground` *(If natively text, else do nothing)* |
| fontFamily | [string](#string) | `FontFamily` *(where applicable, else do nothing)* |
| fontSize | [number](#number) | `FontSize` *(where applicable, else do nothing)*  |
| fontStyle | [oneOf](#oneof) `normal`, `italic` <br>**TO BE ADDED** Windows only: `oblique` | `FontStyle` |
| fontVariant | [arrayOf](#arrayof)([oneOf](#oneof)`small-caps`, `oldstyle-nums`, `lining-nums`, `tabular-nums`, `proportional-nums`) | No equivalent |
| textTransform | [oneOf](#oneof) `none`, `uppercase`, `lowercase`, `capitalize` | No equivalent |
| fontWeight | [oneOf](#oneof) `normal`, `bold`, `100`, `200`, `300`, `400`, `500`, `600`, `700`, `800`, `900` | `FontWeight` *(where applicable, else do nothing)* |
| includeFontPadding | [bool](#bool) | No equivalent |
| lineHeight | [number](#number) | `LineHeight` *(where applicable, else do nothing)* |
| textAlign | [oneOf](#oneof) `auto`, `left`, `right`, `center`, `justify`<br>**TO BE ADDED** Windows only: `DetectFromCenter`, `Start`, `End` | `TextAlignment` *(where applicable, else do nothing)*|
| textDecorationLine | [oneOf](#oneof) `none`, `underline`, `line-through` | `TextDecoration` *(where applicable, else do nothing)* |
| backfaceVisibility | [oneOf](#oneof) `visible`, `hidden` | `Visibility="Collapsed/Visible"` |
| backgroundColor | `ColorPropType` | `Background` |
| borderBottomEndRadius | [number](#number) | ? |
| borderBottomStartRadius | [number](#number) | ? |
| borderBottomLeftRadius | [number](#number) | 'CornerRadius(0, 0, 0, value)' |
| borderBottomRightRadius | [number](#number) | 'CornerRadius(0, 0, value, 0)' |
| borderColor | `ColorPropType` | `BorderBrush` |
| borderRadius | [number](#number) | `CornerRadius(value, value, value, value)` |
| borderStyle | [oneOf](#oneof) `solid`, `dotted`, `dashed` | No equivalent |
| borderTopEndRadius | [number](#number) | ? |
| borderTopStartRadius | [number](#number) | ? |
| borderTopLeftRadius | [number](#number) | `CornerRadius(value, 0, 0, 0)` |
| borderTopRightRadius | [number](#number) | `CornerRadius(0, value, 0, 0)` |
| opacity | [number](#number) | `Opacity` |

**To be added**

| RN CSS Property | RN Default | XAML Control Property Equivalent |
|------|---------|-------------|
| pressedColor | `ColorPropType` |  XAML control lightweight styling *foreground* color equivalent  |
| pressedBackgroundColor | `ColorPropType` |  XAML control lightweight styling *background/"main"* color equivalent  |

* properties with default value `auto` marked with asterisk are do not actually have `auto` as their default value, they just behave like if they would in *css* if they had `auto` as their value. `auto` is not valid value for those properties in react-native

**Comment by khetanashita** [comment]
The Universal Calendar team needs this support to be able to control the styling of the core Xaml controls (Picker, flyout, TextInput, Switch, etc). I understand this is part of M3, but I'm not certain when the work is scheduled to start given M3 finishes by EOY. Our team is working on polishing the app to improve user experience at the moment and this qualifies as a beta blocker for us. Is there a way this can be bumped up to be worked on in July? 
@randy-flynn @JeffOtano @ahimberg please feel free to add more details/comments.
Thanks!

**Comment by khetanashita** [comment]
@kikisaints @harinikmsft 
Has there been any progress on this item? We are still blocked on styling for those items. Thanks

**Comment by chrisglein** [comment]
@kikisaints What's the status on this? We're tight on resources through the end of the year so my default is to move this to M5, but I'm not sure what work remains and how blocked the customer is.

**Comment by kikisaints** [comment]
@chrisglein with the windowbrush api in, I don't think any developers are terribly blocked when creating app thru RN on windows.
That being said, developers coming from windows to RN will be mildly inconvenienced and in some cases forced to write JS-only components to enable more flexible style-ability.

I'll go through and add priorities to the sections in this proposal. Then we can review for M4 feasibility.

**Comment by chrisglein** [comment]
@kikisaints definitely go through and prioritize. The bar for M4 is anything that blocks switching from vCurrent to vNext. This shouldn't get in the way for that, so I'm moving to M5 (starts beginning of 2020).

**Comment by RobMeyer** [comment]
I'm curious, why are pressed states are being called out specifically as a special-case? If we're trying to switch the color model in RN so that the js client can set all the colors for all the visual states to avoid js-native interop, then why not also include colors for hover and focused? (Disabled and selected could be pulled in too, but those concepts currently require re-render to set other props, so may as well just use backgroundColor for those cases.)
