### ISSUE TITLE
Get current and de-fork folly

### ISSUE THREAD

**Issue by acoates-ms** [microsoft/react-native-windows#2216]
We currently depend on a forked version of folly which is included in our RN fork.

We need to submit back any changes we require in folly, and start consuming folly directly as a submodule, or some other non-forked method.

**Comment by rozele** [comment]
Related to #2096.

**Comment by marlenecota** [comment]
Interim step:
- [ ] Move Folly fork to its own repo and consume as submodule

**Comment by chrisglein** [comment]
@acoates-ms says this is done. Closing.
