### ISSUE TITLE
Open an app in full screen only

### ISSUE THREAD

**Issue by AarshApple** [Microsoft/react-native-windows#2218]
I have developed an app and want only to open in full screen mode with user not able to resize it again. Can anyone please help me with this.

**Comment by AarshApple** [comment]
I solved this issue myself and commenting for anyone facing same issue

To launch application in full screen mode, try setting **ApplicationView.PreferredLaunchWindowingMode** as early as in App.xaml.cs's constructor found in your 'appname' project. Add this line.

**ApplicationView.PreferredLaunchWindowingMode = ApplicationViewWindowingMode.FullScreen;**

If you get the error **Cannot find ApplicationView**
Add the line: **using Windows.UI.ViewManagement;** just below the line **using systems**

Because ApplicationView ìs defined in the Windows.UI.ViewManagement namespace in uwp

**Comment by yaraht17** [comment]
Thank you, you save my day :D

**Comment by sahilvicesoftware** [comment]
> I solved this issue myself and commenting for anyone facing same issue
> 
> To launch application in full screen mode, try setting **ApplicationView.PreferredLaunchWindowingMode** as early as in App.xaml.cs's constructor found in your 'appname' project. Add this line.
> 
> **ApplicationView.PreferredLaunchWindowingMode = ApplicationViewWindowingMode.FullScreen;**
> 
> If you get the error **Cannot find ApplicationView**
> Add the line: **using Windows.UI.ViewManagement;** just below the line **using systems**
> 
> Because ApplicationView ìs defined in the Windows.UI.ViewManagement namespace in uwp

@AarshOza the user can still resize the app.
is there any solution to stop that?
Thanks in advance.
