### ISSUE TITLE
Figure out the packaging story for bundling assets to appx

### ISSUE THREAD

**Issue by harinikmsft** [microsoft/react-native-windows#2220]

**Comment by rozele** [comment]
For quick reference and context, we assume that all assets (images, JS bundle, fonts, etc.) are in the Assets/ReactAssets folder in the .appx for C#.

The easiest thing to do is to ensure the assets are stored relative to the JavaScript bundle in the .appx in the same way they are stored relative to the entry-point JS file in the source code. E.g., if you had:
```
./
- index.js
./images
  - foo.png
```
In your .appx, you'd want something like:
```
./Assets
- index.windows.bundle
./Assets/images
  - foo.png
```
This is driven by the way `resolveAssetSource.js` works in `react-native`, which resolves assets relative to your "bundle" URI (i.e., either from the dev server or from your assets path):
https://github.com/facebook/react-native/blob/master/Libraries/Image/resolveAssetSource.js#L88

It's also fine to override the `resolveAssetSource.js` module (we had done this in a previous version of `react-native-windows`), if you want something a bit more customized to UWP / Windows asset resolution that the default behavior doesn't give you.

Another thing to note, the `react-native link` command has a feature that places assets like fonts in the assets directory automatically. It's something we never implemented for `react-native-windows`, but we should definitely do it. Here is the open issue related to that:
https://github.com/Microsoft/react-native-windows/issues/1415

**Comment by chrisglein** [comment]
@harinikmsft This has been sitting around awhile. Assigning to you to sanity check if we need to bulk up any documentation here for MVP. As is I'm assuming this can wait until after.

**Comment by harinikmsft** [comment]
Unfortunately, I dont have enough context here for an update. @jonthysell / @acoates-ms - can you take a look at Eric's comment at the top and see if there is anything really actionable on this for our RNW version or is there some documentation we would need to do?

**Comment by acoates-ms** [comment]
I think this all works today. Assets get put in Bundle\Assets, and all files under Bundle get included in the appx.
