### ISSUE TITLE
Document approach and design for styling/APIs of JS components

### ISSUE THREAD

**Issue by harinikmsft** [microsoft/react-native-windows#2222]
This is tracking an uber spec that will outline the principles to be followed for solving the styling aspects of #2163 , #2155 etc., Things to outline here include:

1. Should the JS component "look like" an equivalent Windows component? Will that match what the JS component does on iOS/Android to retain cross-platform expectations of react-native developers?
2. If yes, then how are the JS styles translated to native RDs? How should we deal with impedance mismatches on styling APIs?

**Comment by kmelmon** [comment]
@kikisaints I've assigned a ZenHub estimate of 5 story points for this.  Feel free to update.

**Comment by harinikmsft** [comment]
Not needed anymore
