### ISSUE TITLE
Building React.Windows.Universal.UnitTests on x86 causes linker errors

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#2224]
By default, React.Windows.Universal.UnitTests is not set to build in the ReactWindows.sln for any configuration.

If you actually try it, it succeeds in x64, but fails on x86:

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "public: __thiscall facebook::react::AppStateModule::AppStateModule(class std::shared_ptr<class facebook::react::AppState> &&)" (??0AppStateModule@react@facebook@@QAE@$$QAV?$shared_ptr@VAppState@react@facebook@@@std@@@Z) referenced in function "class std::unique_ptr<class facebook::react::AppStateModule,struct std::default_delete<class facebook::react::AppStateModule> > __stdcall std::make_unique<class facebook::react::AppStateModule,class std::unique_ptr<class facebook::react::AppState,struct std::default_delete<class facebook::react::AppState> >,0>(class std::unique_ptr<class facebook::react::AppState,struct std::default_delete<class facebook::react::AppState> > &&)" (??$make_unique@VAppStateModule@react@facebook@@V?$unique_ptr@VAppState@react@facebook@@U?$default_delete@VAppState@react@facebook@@@std@@@std@@$0A@@std@@YG?AV?$unique_ptr@VAppStateModule@react@facebook@@U?$default_delete@VAppStateModule@react@facebook@@@std@@@0@$$QAV?$unique_ptr@VAppState@react@facebook@@U?$default_delete@VAppState@react@facebook@@@std@@@0@@Z)	React.Windows.Universal.UnitTests	F:\code\rnw\RNWCPP\Universal.UnitTests\AppStateModuleTests.obj	1	
Error	LNK2001	unresolved external symbol "public: __thiscall facebook::react::AppStateModule::AppStateModule(class std::shared_ptr<class facebook::react::AppState> &&)" (??0AppStateModule@react@facebook@@QAE@$$QAV?$shared_ptr@VAppState@react@facebook@@@std@@@Z)	React.Windows.Universal.UnitTests	F:\code\rnw\RNWCPP\Universal.UnitTests\CreateModulesTests.obj	1	
Error	LNK2019	unresolved external symbol "class std::unique_ptr<class facebook::xplat::module::CxxModule,struct std::default_delete<class facebook::xplat::module::CxxModule> > __stdcall facebook::react::CreateTimingModule(class std::shared_ptr<class facebook::react::MessageQueueThread> const &)" (?CreateTimingModule@react@facebook@@YG?AV?$unique_ptr@VCxxModule@module@xplat@facebook@@U?$default_delete@VCxxModule@module@xplat@facebook@@@std@@@std@@ABV?$shared_ptr@VMessageQueueThread@react@facebook@@@4@@Z) referenced in function "private: void __thiscall CreateModulesTest::CreateModules_TimingModule(void)" (?CreateModules_TimingModule@CreateModulesTest@@AAEXXZ)	React.Windows.Universal.UnitTests	F:\code\rnw\RNWCPP\Universal.UnitTests\CreateModulesTests.obj	1	
Error	LNK2001	unresolved external symbol "public: virtual class std::function<class std::unique_ptr<class facebook::react::JSExecutor,struct std::default_delete<class facebook::react::JSExecutor> > __stdcall(class std::shared_ptr<class facebook::react::ExecutorDelegate>,class std::shared_ptr<class facebook::react::MessageQueueThread>)> __thiscall react::uwp::DevSupportManager::LoadJavaScriptInProxyMode(struct facebook::react::DevSettings const &)" (?LoadJavaScriptInProxyMode@DevSupportManager@uwp@react@@UAE?AV?$function@$$A6G?AV?$unique_ptr@VJSExecutor@react@facebook@@U?$default_delete@VJSExecutor@react@facebook@@@std@@@std@@V?$shared_ptr@VExecutorDelegate@react@facebook@@@2@V?$shared_ptr@VMessageQueueThread@react@facebook@@@2@@Z@std@@ABUDevSettings@3facebook@@@Z)	React.Windows.Universal.UnitTests	F:\code\rnw\RNWCPP\Universal.UnitTests\CreateModulesTests.obj	1	
Error	LNK2001	unresolved external symbol "public: virtual class std::function<class std::unique_ptr<class facebook::react::JSExecutor,struct std::default_delete<class facebook::react::JSExecutor> > __stdcall(class std::shared_ptr<class facebook::react::ExecutorDelegate>,class std::shared_ptr<class facebook::react::MessageQueueThread>)> __thiscall react::uwp::DevSupportManager::LoadJavaScriptInSandboxMode(struct facebook::react::DevSettings const &)" (?LoadJavaScriptInSandboxMode@DevSupportManager@uwp@react@@UAE?AV?$function@$$A6G?AV?$unique_ptr@VJSExecutor@react@facebook@@U?$default_delete@VJSExecutor@react@facebook@@@std@@@std@@V?$shared_ptr@VExecutorDelegate@react@facebook@@@2@V?$shared_ptr@VMessageQueueThread@react@facebook@@@2@@Z@std@@ABUDevSettings@3facebook@@@Z)	React.Windows.Universal.UnitTests	F:\code\rnw\RNWCPP\Universal.UnitTests\CreateModulesTests.obj	1	
Error	LNK2001	unresolved external symbol "public: virtual class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __thiscall react::uwp::DevSupportManager::GetJavaScriptFromServer(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?GetJavaScriptFromServer@DevSupportManager@uwp@react@@UAE?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABV45@00@Z)	React.Windows.Universal.UnitTests	F:\code\rnw\RNWCPP\Universal.UnitTests\CreateModulesTests.obj	1	
Error	LNK2001	unresolved external symbol "public: virtual void __thiscall react::uwp::DevSupportManager::StartPollingLiveReload(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::function<void __stdcall(void)>)" (?StartPollingLiveReload@DevSupportManager@uwp@react@@UAEXABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$function@$$A6GXXZ@5@@Z)	React.Windows.Universal.UnitTests	F:\code\rnw\RNWCPP\Universal.UnitTests\CreateModulesTests.obj	1	
Error	LNK2001	unresolved external symbol "public: virtual void __thiscall react::uwp::DevSupportManager::StopPollingLiveReload(void)" (?StopPollingLiveReload@DevSupportManager@uwp@react@@UAEXXZ)	React.Windows.Universal.UnitTests	F:\code\rnw\RNWCPP\Universal.UnitTests\CreateModulesTests.obj	1	
Error	LNK2019	unresolved external symbol "public: __thiscall react::uwp::NativeUIManager::NativeUIManager(void)" (??0NativeUIManager@uwp@react@@QAE@XZ) referenced in function "class std::unique_ptr<class react::uwp::NativeUIManager,struct std::default_delete<class react::uwp::NativeUIManager> > __stdcall std::make_unique<class react::uwp::NativeUIManager,0>(void)" (??$make_unique@VNativeUIManager@uwp@react@@$$V$0A@@std@@YG?AV?$unique_ptr@VNativeUIManager@uwp@react@@U?$default_delete@VNativeUIManager@uwp@react@@@std@@@0@XZ)	React.Windows.Universal.UnitTests	F:\code\rnw\RNWCPP\Universal.UnitTests\CreateModulesTests.obj	1	
Error	LNK2019	unresolved external symbol "class std::unique_ptr<class facebook::xplat::module::CxxModule,struct std::default_delete<class facebook::xplat::module::CxxModule> > __stdcall facebook::react::createUIManagerModule(class std::shared_ptr<class facebook::react::IUIManager>)" (?createUIManagerModule@react@facebook@@YG?AV?$unique_ptr@VCxxModule@module@xplat@facebook@@U?$default_delete@VCxxModule@module@xplat@facebook@@@std@@@std@@V?$shared_ptr@VIUIManager@react@facebook@@@4@@Z) referenced in function "private: void __thiscall CreateModulesTest::CreateModules_UIManagerModule(void)" (?CreateModules_UIManagerModule@CreateModulesTest@@AAEXXZ)	React.Windows.Universal.UnitTests	F:\code\rnw\RNWCPP\Universal.UnitTests\CreateModulesTests.obj	1	
Error	LNK2019	unresolved external symbol "public: __thiscall react::uwp::ImageViewManager::ImageViewManager(class std::shared_ptr<struct react::uwp::IReactInstance> const &)" (??0ImageViewManager@uwp@react@@QAE@ABV?$shared_ptr@UIReactInstance@uwp@react@@@std@@@Z) referenced in function "class std::unique_ptr<class react::uwp::ImageViewManager,struct std::default_delete<class react::uwp::ImageViewManager> > __stdcall std::make_unique<class react::uwp::ImageViewManager,std::nullptr_t,0>(std::nullptr_t &&)" (??$make_unique@VImageViewManager@uwp@react@@$$T$0A@@std@@YG?AV?$unique_ptr@VImageViewManager@uwp@react@@U?$default_delete@VImageViewManager@uwp@react@@@std@@@0@$$QA$$T@Z)	React.Windows.Universal.UnitTests	F:\code\rnw\RNWCPP\Universal.UnitTests\CreateViewManagersTests.obj	1	
Error	LNK2019	unresolved external symbol "public: __thiscall react::uwp::RawTextViewManager::RawTextViewManager(class std::shared_ptr<struct react::uwp::IReactInstance> const &)" (??0RawTextViewManager@uwp@react@@QAE@ABV?$shared_ptr@UIReactInstance@uwp@react@@@std@@@Z) referenced in function "class std::unique_ptr<class react::uwp::RawTextViewManager,struct std::default_delete<class react::uwp::RawTextViewManager> > __stdcall std::make_unique<class react::uwp::RawTextViewManager,std::nullptr_t,0>(std::nullptr_t &&)" (??$make_unique@VRawTextViewManager@uwp@react@@$$T$0A@@std@@YG?AV?$unique_ptr@VRawTextViewManager@uwp@react@@U?$default_delete@VRawTextViewManager@uwp@react@@@std@@@0@$$QA$$T@Z)	React.Windows.Universal.UnitTests	F:\code\rnw\RNWCPP\Universal.UnitTests\CreateViewManagersTests.obj	1	
Error	LNK2019	unresolved external symbol "public: __thiscall react::uwp::RootViewManager::RootViewManager(class std::shared_ptr<struct react::uwp::IReactInstance> const &)" (??0RootViewManager@uwp@react@@QAE@ABV?$shared_ptr@UIReactInstance@uwp@react@@@std@@@Z) referenced in function "class std::unique_ptr<class react::uwp::RootViewManager,struct std::default_delete<class react::uwp::RootViewManager> > __stdcall std::make_unique<class react::uwp::RootViewManager,std::nullptr_t,0>(std::nullptr_t &&)" (??$make_unique@VRootViewManager@uwp@react@@$$T$0A@@std@@YG?AV?$unique_ptr@VRootViewManager@uwp@react@@U?$default_delete@VRootViewManager@uwp@react@@@std@@@0@$$QA$$T@Z)	React.Windows.Universal.UnitTests	F:\code\rnw\RNWCPP\Universal.UnitTests\CreateViewManagersTests.obj	1	
Error	LNK2019	unresolved external symbol "public: __thiscall react::uwp::ScrollViewManager::ScrollViewManager(class std::shared_ptr<struct react::uwp::IReactInstance> const &)" (??0ScrollViewManager@uwp@react@@QAE@ABV?$shared_ptr@UIReactInstance@uwp@react@@@std@@@Z) referenced in function "class std::unique_ptr<class react::uwp::ScrollViewManager,struct std::default_delete<class react::uwp::ScrollViewManager> > __stdcall std::make_unique<class react::uwp::ScrollViewManager,std::nullptr_t,0>(std::nullptr_t &&)" (??$make_unique@VScrollViewManager@uwp@react@@$$T$0A@@std@@YG?AV?$unique_ptr@VScrollViewManager@uwp@react@@U?$default_delete@VScrollViewManager@uwp@react@@@std@@@0@$$QA$$T@Z)	React.Windows.Universal.UnitTests	F:\code\rnw\RNWCPP\Universal.UnitTests\CreateViewManagersTests.obj	1	
Error	LNK2019	unresolved external symbol "public: __thiscall react::uwp::TextInputViewManager::TextInputViewManager(class std::shared_ptr<struct react::uwp::IReactInstance> const &)" (??0TextInputViewManager@uwp@react@@QAE@ABV?$shared_ptr@UIReactInstance@uwp@react@@@std@@@Z) referenced in function "class std::unique_ptr<class react::uwp::TextInputViewManager,struct std::default_delete<class react::uwp::TextInputViewManager> > __stdcall std::make_unique<class react::uwp::TextInputViewManager,std::nullptr_t,0>(std::nullptr_t &&)" (??$make_unique@VTextInputViewManager@uwp@react@@$$T$0A@@std@@YG?AV?$unique_ptr@VTextInputViewManager@uwp@react@@U?$default_delete@VTextInputViewManager@uwp@react@@@std@@@0@$$QA$$T@Z)	React.Windows.Universal.UnitTests	F:\code\rnw\RNWCPP\Universal.UnitTests\CreateViewManagersTests.obj	1	
Error	LNK2019	unresolved external symbol "public: __thiscall react::uwp::TextViewManager::TextViewManager(class std::shared_ptr<struct react::uwp::IReactInstance> const &)" (??0TextViewManager@uwp@react@@QAE@ABV?$shared_ptr@UIReactInstance@uwp@react@@@std@@@Z) referenced in function "class std::unique_ptr<class react::uwp::TextViewManager,struct std::default_delete<class react::uwp::TextViewManager> > __stdcall std::make_unique<class react::uwp::TextViewManager,std::nullptr_t,0>(std::nullptr_t &&)" (??$make_unique@VTextViewManager@uwp@react@@$$T$0A@@std@@YG?AV?$unique_ptr@VTextViewManager@uwp@react@@U?$default_delete@VTextViewManager@uwp@react@@@std@@@0@$$QA$$T@Z)	React.Windows.Universal.UnitTests	F:\code\rnw\RNWCPP\Universal.UnitTests\CreateViewManagersTests.obj	1	
Error	LNK2019	unresolved external symbol "public: __thiscall react::uwp::ViewViewManager::ViewViewManager(class std::shared_ptr<struct react::uwp::IReactInstance> const &)" (??0ViewViewManager@uwp@react@@QAE@ABV?$shared_ptr@UIReactInstance@uwp@react@@@std@@@Z) referenced in function "class std::unique_ptr<class react::uwp::ViewViewManager,struct std::default_delete<class react::uwp::ViewViewManager> > __stdcall std::make_unique<class react::uwp::ViewViewManager,std::nullptr_t,0>(std::nullptr_t &&)" (??$make_unique@VViewViewManager@uwp@react@@$$T$0A@@std@@YG?AV?$unique_ptr@VViewViewManager@uwp@react@@U?$default_delete@VViewViewManager@uwp@react@@@std@@@0@$$QA$$T@Z)	React.Windows.Universal.UnitTests	F:\code\rnw\RNWCPP\Universal.UnitTests\CreateViewManagersTests.obj	1	
Error	LNK2019	unresolved external symbol "public: __thiscall react::uwp::WebViewManager::WebViewManager(class std::shared_ptr<struct react::uwp::IReactInstance> const &)" (??0WebViewManager@uwp@react@@QAE@ABV?$shared_ptr@UIReactInstance@uwp@react@@@std@@@Z) referenced in function "class std::unique_ptr<class react::uwp::WebViewManager,struct std::default_delete<class react::uwp::WebViewManager> > __stdcall std::make_unique<class react::uwp::WebViewManager,std::nullptr_t,0>(std::nullptr_t &&)" (??$make_unique@VWebViewManager@uwp@react@@$$T$0A@@std@@YG?AV?$unique_ptr@VWebViewManager@uwp@react@@U?$default_delete@VWebViewManager@uwp@react@@@std@@@0@$$QA$$T@Z)	React.Windows.Universal.UnitTests	F:\code\rnw\RNWCPP\Universal.UnitTests\CreateViewManagersTests.obj	1	
Error	LNK2019	unresolved external symbol "enum _JsErrorCode __stdcall facebook::react::JsPointerToStringUtf8(char const *,unsigned int,void * *)" (?JsPointerToStringUtf8@react@facebook@@YG?AW4_JsErrorCode@@PBDIPAPAX@Z) referenced in function "public: void __thiscall StringConversionTest_Universal::StringConversionTest_UniversalTest(void)" (?StringConversionTest_UniversalTest@StringConversionTest_Universal@@QAEXXZ)	React.Windows.Universal.UnitTests	F:\code\rnw\RNWCPP\Universal.UnitTests\StringConversionTests_Universal.obj	1	
Error	LNK2019	unresolved external symbol "enum _JsErrorCode __stdcall facebook::react::JsStringToStdStringUtf8(void *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &)" (?JsStringToStdStringUtf8@react@facebook@@YG?AW4_JsErrorCode@@PAXAAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) referenced in function "public: void __thiscall StringConversionTest_Universal::StringConversionTest_UniversalTest(void)" (?StringConversionTest_UniversalTest@StringConversionTest_Universal@@QAEXXZ)	React.Windows.Universal.UnitTests	F:\code\rnw\RNWCPP\Universal.UnitTests\StringConversionTests_Universal.obj	1	
Error	LNK1120	19 unresolved externals	React.Windows.Universal.UnitTests	F:\code\rnw\RNWCPP\target\Win32\Debug\React.Windows.Universal.UnitTests\React.Windows.Universal.UnitTests.exe	1

**Comment by jonthysell** [comment]
I think this is an issue with the calling conventions, though I don't understand why it only affects x86.

**Comment by kmelmon** [comment]
@jonthysell I've marked this as should-have (P2).  Let me know if you feel differently.

**Comment by jonthysell** [comment]
As mentioned in #2549, this issue is a side-effect of a deeper problem:

> Right now there is a problem with how we export types - on x64, everything gets exported to the dll, on x86, it's only the things exposed explicitly with REACTWINDOWS_EXPORT.
>
> This is why the unit tests all build and link on x64, everything is visible. On x86, we get linker errors when trying to build the unit tests.
>
> This PR fixes many of the unit tests, mostly by sprinkling REACTWINDOWS_EXPORT, throughout the code for tested types. However some types unit tests are still disabled on x86 because exposing their types is more complicated.
