### ISSUE TITLE
[Documentation] Publish parity status for rnwcpp

### ISSUE THREAD

**Issue by harinikmsft** [microsoft/react-native-windows#2233]
This task is tracking documenting the parity status of rnwcpp APIs against react native. We should publish something like [Core parity status](https://github.com/Microsoft/react-native-windows/blob/master/RNWCS/docs/CoreParityStatus.md) with links to issues tracking what is incomplete in rnwcpp.

**Comment by kikisaints** [comment]
@harinikmsft did you have ideas of where this status document should live?

**Comment by harinikmsft** [comment]
Yeah - lets put it [here](https://github.com/Microsoft/react-native-windows/tree/rnwcpp-preview/RNWCPP/docs). At a later point, these docs can be merged with the master docs as it makes sense.
