### ISSUE TITLE
RN's <View/> layers cleanly over the native framework

### ISSUE THREAD

**Issue by micahl** [microsoft/react-native-windows#2245]
The matrix of what properties/behaviors are provided by XAML and what styling React Native's View supports don't line up well.  This is apparent in the case of borders (which makes up most of the [View Style props](https://facebook.github.io/react-native/docs/view-style-props)).  Depending on which combination of properties are targeted by an app the current implementation has to manage various trees of XAML elements to get the desired effect with proper clipping of children, per edge border coloring and thicknes, rounded corners, etc.  

Given that <View> is such a fundamental type and widely used it is worth investigating how we can be more performant (e.g. flatten the native UI tree required).

**Comment by cliffkoh** [comment]
test

**Comment by chrisglein** [comment]
This issue has sat for awhile. We've had other similar proposals (e.g. #3875) and also creative workarounds for XAML inflexibility (e.g. #5187). Which is to say I think we've both captured this elsewhere and evolved our thinking. Closing this issue.
