### ISSUE TITLE
Implement the snapToInterval and snapToAlignment logic in ScrollViewer

### ISSUE THREAD

**Issue by christophermussack** [microsoft/react-native-windows#2261]

**Comment by christophermussack** [comment]
piece of issue #2113

**Comment by harinikmsft** [comment]
#2263

**Comment by chrisglein** [comment]
It looks like PR for this stalled out in April and was closed. But then @StephenLPeters addressed this in #2443. Closing this out. Stephen, let me know if I missed anything.
