### ISSUE TITLE
react-native-windows should work against public react-native and/or the fork

### ISSUE THREAD

**Issue by harinikmsft** [microsoft/react-native-windows#2264]
This work item is tracking getting off the fork of react-native and also allowing react-native-windows to either use the public react-native or a fork for bug fixes, unblocking etc.

**Comment by harinikmsft** [comment]
Need to investigate and come up with a POR for what needs to be done here, when we do it, how much work there is.

**Comment by kmelmon** [comment]
First we need to move off the fork, which isn't scheduled for Milestone 2.  Moving this to Milestone 3.

**Comment by acoates-ms** [comment]
RNW works without using the fork version.  I think this can be closed.
