### ISSUE TITLE
Figure out if TryUpdateForeground should be in ControlViewManager

### ISSUE THREAD

**Issue by marlenecota** [microsoft/react-native-windows#2268]
interesting, the base class has TryUpdateForeground but not all react-native controls are documented to have a 'color' prop.  Picker, ActivityIndicator, Text do but everything else is just backgroundColor.  so maybe TryUpdateForeground shouldn't be in the base.

_Originally posted by @ahimberg in https://github.com/Microsoft/react-native-windows/pull/2253#issuecomment-480136538_

**Comment by harinikmsft** [comment]
Is there a developer facing issue here where a real scenario might be broken? @marlenecota please investigate.

**Comment by kmelmon** [comment]
This isn't critical for Milestone 2.  Moving to Milestone 3.
