### ISSUE TITLE
Add support for Community's Async Storage

### ISSUE THREAD

**Issue by Krizzu** [microsoft/react-native-windows#2270]
Hello 👋 

As part of [Lean Core effort in React Native](https://github.com/facebook/react-native/issues/23313), some modules are extracted into external repos, under RN Community's org. 

One of them is Async Storage, used in most of the apps. In order to deprecate old AS module, we've ditched `NativeModule`'s name from `AsyncLocalStorage` to `PlatformLocalStorage`.

Currently, [`RN-windows` uses deprecated name](https://github.com/Microsoft/react-native-windows/blob/master/RNWCS/ReactWindows/ReactNative/Modules/Storage/AsyncStorageModule.cs#L28), so it'd be great to keep it in sync.

Let me know what you think.

thanks.

**Comment by chrisglein** [comment]
We are tracking this against vnext as #2271. We will not complete this against current (.NET).
