### ISSUE TITLE
Add support for Community's Async Storage

### ISSUE THREAD

**Issue by Krizzu** [microsoft/react-native-windows#2271]
Hello 👋 

As part of [Lean Core effort in React Native](https://github.com/facebook/react-native/issues/23313), some modules are extracted into external repos, under RN Community's org. 

One of them is Async Storage, used in most of the apps. In order to deprecate old AS module, we've ditched `NativeModule`'s name from `AsyncLocalStorage` to `PlatformLocalStorage`.

Currently, [`RN-windows` uses deprecated name](https://github.com/Microsoft/react-native-windows/blob/rnwcpp-preview/RNWCPP/Shared/AsyncStorageModule.cpp#L23), so it'd be great to keep it in sync.

Let me know what you think.

thanks.

**Comment by chrisglein** [comment]
Customer is currently unblocked. We have limited time for M4 (~1 month) so this will wait for the new year.

**Comment by robertev** [comment]
For my customer, this is a dependency for several different libraries for them. This is one that absolutely will be necessary for things like our offline data storage for Realm and Redux; token storage for Azure Auth; etc.
