### ISSUE TITLE
Add Developer menu, direct debugging support

### ISSUE THREAD

**Issue by harinikmsft** [microsoft/react-native-windows#2276]
The C# implementation (and other platforms supported by react-native) have direct debugging support where developer can bring up the debug menu through a keyboard shortcut and then expose more debugging options including enabling web debugger. We should get this added to RNWCPP.

In addition to the debug menu, we will need to add a hook to make sure VS Code Command palette RN extension can plug into the developer menu

**Comment by harinikmsft** [comment]
@ahimberg - can you describe what work is left to do here post this commit - #2504

**Comment by chrisglein** [comment]
The issues tracked by this epic are being handled independently (and are complete). No need to keep the ZenHub epic around.
