### ISSUE TITLE
Implement Native Driver for Smooth Animations

### ISSUE THREAD

**Issue by stmoy** [microsoft/react-native-windows#2297]
Native Driver offloads animations off of the JS thread onto the native thread. https://facebook.github.io/react-native/blog/2017/02/14/using-native-driver-for-animated.html

We need to implement the NativeAnimated module if we're going to get "buttery smooth" (ie. >60fps) animations. 

Related: #566

**Comment by kmelmon** [comment]
This work is complete, closing.
