### ISSUE TITLE
Enable authoring a view manager in C# (or C++/CX)

### ISSUE THREAD

**Issue by micahl** [microsoft/react-native-windows#2298]
Someone using c++/winrt should be able to author a view manager already.  But, for someone that wants to create a C# app (or C++/CX), our RNWCPP version does not provide the Windows runtime version of interfaces/types that a consuming C# app would need to create a custom view manager.

**Comment by rozele** [comment]
Not sure if you want to use this issue in lieu of #2130 and #2131, unless we want to use those for documentation purposes only.

**Comment by micahl** [comment]
I expected to use those to track documentation.

**Comment by jonthysell** [comment]
Currently working on this here: https://github.com/jonthysell/react-native-windows/tree/jonthysell/nativemodules

Warning, don't expect the branch to be stable, I'm rebasing and refactoring a lot.

**Comment by jonthysell** [comment]
Adding a large estimate, as this requires not only adding to the ABI but also refactoring and hooking everything up underneath.
