### ISSUE TITLE
Enable authoring native modules in C# (or C++/CX)

### ISSUE THREAD

**Issue by micahl** [microsoft/react-native-windows#2310]
Some functionality already exists in the RNWCPP implementation.  This task is to investigate what (if anything remains).

**Comment by jonthysell** [comment]
Why does this exist? You can already author native modules in C#/C++Cx. The only thing remaining is for feature parity is #2391.

**Comment by micahl** [comment]
It's an issue to track investigation and identify if we're missing anything.  Sounds like you've identified what remains and its covered by #2391.  So, we can close out this issue.
