### ISSUE TITLE
Implement transforms

### ISSUE THREAD

**Issue by stmoy** [microsoft/react-native-windows#2315]
Transforms do not currently work in RNWCPP. For example, the following animation animates both Opacity and Transform - only the opacity animation plays and the offset animation is ignored. However, the offset animation plays when deployed to iPhone. 

``` js
    const startupTransitionStyle = {
      opacity: startupAnim,
      transform: [
        {
          translateY: startupAnim.interpolate({
            inputRange: [0, 1],
            outputRange: [120, 0]
          })
        }
      ]
    };
```

**Comment by kmelmon** [comment]
I am currently working on implementing this.

**Comment by kmelmon** [comment]
Fixed with this PR:
https://github.com/microsoft/react-native-windows/pull/2513
We now handle statically set values and also javascript-driven animations.
The nativeDriver support is still being worked on, and is being tracked by:
https://github.com/microsoft/react-native-windows/issues/2297
