### ISSUE TITLE
Add support for C++ template in CLI

### ISSUE THREAD

**Issue by harinikmsft** [microsoft/react-native-windows#2337]
The current CLI generates a C# sample app. We should add support for generating an equivalent C++/WinRT sample app to the CLI, perhaps with a flag like so - `react-native windows --template vnext cpp`. The default can continue to be C#.

**Comment by kmelmon** [comment]
I'd really like to see this happen.  Assigning this to myself as a starting point.

**Comment by kmelmon** [comment]
I now have a cppwinrt "sample" template working.  It's currently hard-coded to a single project that needs to be manually grafted into a CLI-generated app.  Will work on templatizing it next.

Current code is in this branch in a staging area:  https://github.com/kmelmon/react-native-windows/tree/templatecpp
