### ISSUE TITLE
Separate build pipeline for UWP builds

### ISSUE THREAD

**Issue by harinikmsft** [microsoft/react-native-windows#2346]
Right now we're using internal build servers for our build loop.  This task is tracking doing builds on an externally facing ADO service.  We may need to do this in stages (first use the Microsoft pool).

>

**Comment by kmelmon** [comment]
This isn't critical for Milestone 2.  Moving to Milestone 3.

**Comment by chrisglein** [comment]
This seems non-critical for MVP. @harinikmsft I'm moving out to Milestone 4. Let me know if you disagree.

**Comment by NickGerleman** [comment]
Looks like we've already done this. Closing.
