### ISSUE TITLE
Split UIManager into a separate VS project

### ISSUE THREAD

**Issue by harinikmsft** [microsoft/react-native-windows#2347]
The UIManager module is currently built along with the rest of RNWCPP.  This task is tracking separating this module into a separate project so we can build other solutions that just bring this component in.

**Comment by kmelmon** [comment]
This isn't critical for Milestone 2.  Moving to Milestone 3.

**Comment by NickGerleman** [comment]
Is this still relevant? Seems like we've made some decent architectural shifts since this was created.
