### ISSUE TITLE
Remove Tapped event handler for View in UWP

### ISSUE THREAD

**Issue by randy-flynn** [microsoft/react-native-windows#2349]
This was added as a temporary solution to an LPC need, but the code using it has been removed in favor of newer work.

**Comment by stmoy** [comment]
@chrisglein - is this still needed, or can we close this out?

**Comment by chrisglein** [comment]
I think this ended up on PM as a result of consolidating for #2099.
A quick search didn't pull up a Tapped event. I think this we can close this out. Going to do so, @rectified95 keep me honest and reactivate if I'm wrong.
