### ISSUE TITLE
Remove windesktop files

### ISSUE THREAD

**Issue by acoates-ms** [microsoft/react-native-windows#2351]
We created a dummy "windesktop" platform for our unit tests. 
At the very least we should be able to not include those files in the published package.

But we should look at if we can now run those UTs without a bunch of override files.

**Comment by JunielKatarn** [comment]
Won't this break Desktop integration tests?

**Comment by NickGerleman** [comment]
@chrisglein @kmelmon @jonthysell we should close this one or #4087

**Comment by NickGerleman** [comment]
Closing this in favor of #4087. I intend to take a look at that shortly after we're continuously integrating FB master.
