### ISSUE TITLE
Ensure manually adding react-native-windows to react-native project works

### ISSUE THREAD

**Issue by harinikmsft** [microsoft/react-native-windows#2353]
the CLI does a lot of steps today to smoothen installing react-native-windows. There appear to be a few bugs when trying to manually install react-native-windows as a dependency after installing react-native. We should make sure this work flow works.

**Comment by kmelmon** [comment]
please get more info from the customer on what they did and what doesn't work - is there a workaround?  Also try to answer the question of if we need this for Milestone 2.

**Comment by chrisglein** [comment]
Need more detail in this bug to be actionable, and it's very stale at this point. Closing out awaiting more specific feedback.
