### ISSUE TITLE
crash on click

### ISSUE THREAD

**Issue by RobertGoins** [Microsoft/react-native-windows#2355]
I created a project from scratch, ran it and then clicked inside of the app window.  The app crashes at 

void TouchEventHandler::OnPointerPressed(const winrt::IInspectable& sender, const winrt::PointerRoutedEventArgs& args)

Looks like the following assert is triggered: 

 if (IndexOfPointerWithId(args.Pointer().PointerId()) == std::nullopt)
  {
    // A pointer with this ID already exists
    assert(false);
    return;
  }

**Comment by ahimberg** [comment]
This was just fixed - https://github.com/Microsoft/react-native-windows/pull/2342
