### ISSUE TITLE
ReactNative in Win32:  Set XamlRoot where appropriate

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#2364]
When hosting ReactNative inside a DesktopWindowXamlSource, parts of the implementation will need to become "islands-enlightened".  The most common pattern will be to set a XamlRoot (eg Popup will need to set one).  Part of this task should be to determine if there are other requirements specific to supporting islands (and open more tasks if necessary).

MSFT has an internal doc describing the API requirements, here:
https://microsoft.sharepoint.com/:w:/r/teams/specstore/_layouts/15/Doc.aspx?sourcedoc=%7B45E349E7-0241-4B31-B535-BABCC40575AD%7D&file=%5b17468132%5d%20Xaml%20Islands%20ContentRoot%20API%20Spec.docx&action=default&mobileredirect=true&DefaultItemOpen=1

See table starting on page 10.

**Comment by licanhua** [comment]
It's more like just API change. Target version should be changed to 19h1, and I ran into some issue like pipeline, build error, cppwinrt error.

**Comment by licanhua** [comment]
depends on internal task to install SDK: [3358057](https://office.visualstudio.com/OE/_workitems/edit/3358057)

**Comment by harinikmsft** [comment]
Fixed by #2456
