### ISSUE TITLE
Add support for running RNWCPP on RS2

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#2366]
Currently RNWCPP targets RS3 as a min target.  This issue is tracking making RS2 the minimum supported platform.  Reason:  To support SurfaceHub, which is currently running RS2.

A few things are required:
-Change the VS solutions:  set min platform version to RS2
-Andy says:  We have the version numbers in react.cpp.props for SDK target versions.  We should be able to set it back to RS2, I don't think those settings actually do much with cppwinrt includes anyway
-Ensure we aren't calling any WinRT APIs that don't exist on RS2.  Andy says:  
There are 2 things that check SDK version right now: if you search for ApiInformation::IsPropertyPresent its TextDecortations to support underline/strikethrough text requires RS2, editable ComboBox in Picker lights up with RS5. 
What we could do is temporarily change the target version to RS2 and the compiler will find any other APIs that didn't exist then.
-Change build pipeline(s) to install the RS2 SDK.
-Update readme (RS2 SDK is required instead of RS3)

**Comment by ahimberg** [comment]
We build with the latest public SDK (so we can reference new features, and use latest cppwinrt), but tell it to target the min version we're supporting.  So the next to last point (install rs2 sdk) probably isn't needed.

**Comment by licanhua** [comment]
tests will be tracked by other test task.
