### ISSUE TITLE
React Native 0.59 ETA

### ISSUE THREAD

**Issue by EdwardNickson** [microsoft/react-native-windows#2397]
Hi,

Is there a roadmap for when the RN 0.59 release will be coming out?
As of 1st August the Android app store will require 64 bit versions of apps and this is only supported in RN 0.59 plus. If Windows doesn't support 0.59 by then we're going to have to branch our codebase with windows on 0.57 and android on 0.59 which is a bit of a hassle.

**Comment by harinikmsft** [comment]
Hello! 

Both the current (.NET) and vnext (C++) react-native-windows versions have been migrated to support RN 0.58 version at this time. We are working on migrating them to 0.59 next and will have an update on the ETA soon. Our goal is to make sure you are unblocked before the August timeline at least with using the current (.NET) version. We are working out the exact ETA at this time.

**Comment by ralexand56** [comment]
Huh, no hooks support until August?

**Comment by harinikmsft** [comment]
The `current` implementation has an active PR out for updating to 0.59 - #2411 

We are also working to update `vnext` to support 0.59 - you should start seeing PR activity on this shortly as well.

**Comment by harinikmsft** [comment]
Closing to track via ongoing PRs.
