### ISSUE TITLE
Helper codegen for authoring components and corresponding docs

### ISSUE THREAD

**Issue by licanhua** [microsoft/react-native-windows#2402]
Goal:
1. Easy to maintain
2. Reduce bugs
3. Easy to support a new control
4. generate API documents

There are too much common thing we need to do when a new control is introduced:
1. provide GetNativeProps
2. GetName
3. Hook up events
4.  Update properties pattern
```
  if (propertyName.asString() == "isLightDismissEnabled")
    {
      if (propertyValue.isBool())
        m_isLightDismissEnabled = propertyValue.asBool();
      else if (propertyValue.isNull())
        m_isLightDismissEnabled = true;
    }
```
5. enum mapping:
  ```
winrt::FlyoutPlacementMode placement;
    if (json == "top")
    {
      placement = winrt::FlyoutPlacementMode::Top;
    }
    else if (json == "bottom")
    {
      placement = winrt::FlyoutPlacementMode::Bottom;
    }
```
6. features related to special version of os.
```
  if (textBox.try_as<winrt::IUIElement7>())
  {
 textBox.CharacterReceived([=](auto&&, winrt::CharacterReceivedRoutedEventArgs const& args) {...});
  }
```
7. Possible test case authoring
8. document and API consistency.
9. createView

Current we need to do everything manually, and it's possible that we only define a mapping table, then codegen helps to generate a base class for the control.

We just need to provide information like below, then it will generate codes for FlyoutShadowNode_Base. then we can do FlyoutShadowNode: FlyoutShadowNode_Base  

FlyoutShadowNode mapping to winrt::Flyout
Name=RCTFlyout
    ("isLightDismissEnabled", "boolean", RS2+)
    ("isOpen", "boolean")
    ("placement", "number")
    ("target", "number")
export event:
{ topDismiss: onDismiss}

**Comment by harinikmsft** [comment]
Thanks for the suggestion. Lets revisit when the benefits here outweigh the costs (since we are not necessarily adding too much new API or docs at this time).
