### ISSUE TITLE
Feature Request: Improve remote device development support.

### ISSUE THREAD

**Issue by stecrain** [microsoft/react-native-windows#2403]
Currently to develop a React Native app on Xbox we have to manually edit DevServerHelper.h and insert the dev box ip address.

I think the min bar for making this a better experience is to add debug host ip to react::uwp::ReactInstanceSettings. that way if developing on a device requires a code edit at least it is a code edit in the consuming app instead of going into node_modules and changing the framework package.

**Comment by kmelmon** [comment]
@stecrain can you implement the min bar described above?

**Comment by stecrain** [comment]
Sure, I think I can get to it in the next couple of days

**Comment by kmelmon** [comment]
Awesome thanks!  Your help is appreciated :)

**Comment by chrisglein** [comment]
Hey @stecrain: You had a PR merge for this back in May/June. Is there more work here or can we close out this issue?
@harinikmsft you added the "needs PM design" label. What's the work here?

**Comment by harinikmsft** [comment]
I think we have the minbar completed by @stecrain for now. 

Long term - it feels like there could be a better tooling story around these customizations as well. That was the part I thought could use some PM design and vision. I think we can close this issue for now and create another one later for the long term aspects.
