### ISSUE TITLE
Navigation page jump ERR

### ISSUE THREAD

**Issue by wrzfeijianshen** [microsoft/react-native-windows#2414]
## 1. Configuration instructions ： 
vs2017 
react-native-cli: 2.0.1
react-native: 0.57.8
node -v: v10.15.3
npm -v: 6.4.1

## 2. Mistakes show 
Simple two page jump, unexpectedly appear so error, beg big god plan, or recommend a few available navigation!!!

![image](https://user-images.githubusercontent.com/23181790/57188282-7eeab300-6f2e-11e9-9cd7-054a8276b00f.png)

**Comment by nsxr51** [comment]
@wrzfeijianshen Can you leave instructions on how to reproduce it ?

**Comment by kmelmon** [comment]
There isn't any actionable information in this bug.  Closing
