### ISSUE TITLE
Provides IModule COM wrapper to accept CxxModule when registering the module for cpp user.

### ISSUE THREAD

**Issue by licanhua** [microsoft/react-native-windows#2416]
For a cpp application, we need extra effort to implement a WRT module, and here is the step:
1. Create an interface (IDL) file to define any local Windows Runtime 
    classes referenced in the app's XAML pages.
2. Build the project once to generate implementation templates under 
    the "Generated Files" folder, as well as skeleton class definitions 
    under "Generated Files\sources".  
3. Use the skeleton class definitions for reference to implement your
    Windows Runtime classes.

And here is how the customer use it:
```
auto instance = Instance::Create(JSFILENAME);
auto module = winrt::make<SampleModule>();
instance.RegisterModule(*module);
instance.Start(settings);

```
The heavy part is implement WRT components. We can simplify the process and customer may only need to implement facebook::xplat::module::CxxModule other than COM.
then we do the magic(eg: make_module) and wrap it as a COM.

```
auto module = make_module<SampleModule>();
instance.RegisterModule(module);
```

**Comment by jonthysell** [comment]
The model is:

C++ developers should inherit directly from CxxModule. No WinRT no IDLs.

IModule is only for C# and C++/Cx developers.

**Comment by licanhua** [comment]
disagree. we should just provide one set of API to user(at least the format looks the same), and it should be very clean.
If we look at HostingPanel.xaml.cpp in React.Windows.Universal.SampleApp, it's very hard to understand by non cppwinrt developers.

**Comment by jonthysell** [comment]
Unfortunately that's the model. We can make some of the API signatures similar, but otherwise we will have to force everyone to do everything through WinRT.

**Comment by licanhua** [comment]
I don't know too much about C++/Cx, but I think we should use the IModule interface anywhere like this:

      C# user
      var instance = Instance.Create(JSFILENAME);

      //instantiate sample module for registering callbacks for live reload, JS error handling etc.,
      instance.RegisterModule(new SampleModule());
      instance.Start(settings);

      RootElement.Instance = instance;
      
      Cppwinrt user
      
      auto instance = Instance::Create(JSFILENAME);
      auto module = winrt::make<SampleModule>();
      instance.RegisterModule(module);
      instance.Start(settings);
      RootElement.Instance = instance;

      C++/CX user
      
      auto instance = new InstanceCreate(JSFILENAME);
      auto module = new CreateModule<SampleModule>();
      instance.RegisterModule(module);
      instance.Start(settings);
      RootElement.Instance = instance;

**Comment by chrisglein** [comment]
@jonthysell Not sure what the ask is here. Weigh it alongside your native modules plan and close out if there's nothing we want to do here..

**Comment by jonthysell** [comment]
This is outdated, closing.
