### ISSUE TITLE
Invariant Violation: Native component for "RCTMobileHostView" does not exist

### ISSUE THREAD

**Issue by nageshwar-uideveloper** [microsoft/react-native-windows#2417]
### Environment

1. `react-native -v`: 0.55.4
2. `npm ls rnpm-plugin-windows`: rnpm-plugin-windows@0.2.9
3. `npm ls react-native-windows`:  react-native-windows@0.55.0-rc.0
4. `node -v`: v12.0.0
5. `npm -v`: 6.9.0
6. `yarn --version`: 1.15.2

Then, specify:

- Target Platform: UWP

- Target Platform Version(s): 10.0.14393

- Target Device(s): Desktop

- Development Operating System: Windows 10 Pro

- Visual Studio Version: Visual Studio 2017

- Build Configuration: Debug

### Steps to Reproduce

I am trying to convert existing react native app to windows version

1. The issue is in React Native Modal
2. Screenshot
![RCTModalHostView error](https://user-images.githubusercontent.com/17724230/57238874-4bb42c80-6fdf-11e9-973a-38d02acd2f61.png)

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by peterfei** [comment]
> ### Environment
> 1. `react-native -v`: 0.55.4
> 2. `npm ls rnpm-plugin-windows`: rnpm-plugin-windows@0.2.9
> 3. `npm ls react-native-windows`:  react-native-windows@0.55.0-rc.0
> 4. `node -v`: v12.0.0
> 5. `npm -v`: 6.9.0
> 6. `yarn --version`: 1.15.2
> 
> Then, specify:
> 
> * Target Platform: UWP
> 
> * Target Platform Version(s): 10.0.14393
> 
> * Target Device(s): Desktop
> 
> * Development Operating System: Windows 10 Pro
> 
> * Visual Studio Version: Visual Studio 2017
> 
> * Build Configuration: Debug
> 
> ### Steps to Reproduce
> I am trying to convert existing react native app to windows version
> 
> 1. The issue is in React Native Modal
> 2. Screenshot
>    ![RCTModalHostView error](https://user-images.githubusercontent.com/17724230/57238874-4bb42c80-6fdf-11e9-973a-38d02acd2f61.png)
> 
> ### Expected Behavior
> (Write what you thought would happen.)
> 
> ### Actual Behavior
> (Write what happened. Add screenshots!)
> 
> ### Reproducible Demo
> (Paste the link to an example project and exact instructions to reproduce the issue.)

Also not work
