### ISSUE TITLE
Can't build, boost libs or something is unreachable

### ISSUE THREAD

**Issue by liquidboy** [microsoft/react-native-windows#2419]
seems like the "boost" libs that nuget is trying to pull down are only available within the MS network? 

```
  <package id="boost" version="1.68.0.0" targetFramework="native" />
  <package id="boost_date_time-vc141" version="1.68.0.0" targetFramework="native" />
  <package id="boost_system-vc141" version="1.68.0.0" targetFramework="native" />

```

Is there plans to publish these to nuget, i would love to build the demo.

**Comment by ahimberg** [comment]
You're trying to build the Playground.sln?  I think right now a custom nuget commandline is required.  Can you try this?

C:\git\react-native-windows\vnext\Playground>nuget restore Playground.sln -PackagesDirectory Playground\packages

**Comment by liquidboy** [comment]
thanks @ahimberg    i should of thought of doing that from command line, (after trying to do it via VS2019 preview failed) ...  

That fixed my nuget packages ... Now off to npm install the node packages thanks again


`E:\source\gh\microsoft\react-native-windows\vnext\Playground>nuget restore Playground.sln -PackagesDirectory packages
MSBuild auto-detection: using msbuild version '16.1.59.61912' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\bin'.
Restoring NuGet package boost_system-vc141.1.68.0.
Restoring NuGet package boost.1.68.0.
Restoring NuGet package boost_date_time-vc141.1.68.0.
Adding package 'boost.1.68.0' to folder 'E:\source\gh\microsoft\react-native-windows\vnext\Playground\packages'
Adding package 'boost_date_time-vc141.1.68.0' to folder 'E:\source\gh\microsoft\react-native-windows\vnext\Playground\packages'
Adding package 'boost_system-vc141.1.68.0' to folder 'E:\source\gh\microsoft\react-native-windows\vnext\Playground\packages'
Added package 'boost_system-vc141.1.68.0' to folder 'E:\source\gh\microsoft\react-native-windows\vnext\Playground\packages'
Added package 'boost_date_time-vc141.1.68.0' to folder 'E:\source\gh\microsoft\react-native-windows\vnext\Playground\packages'
Added package 'boost.1.68.0' to folder 'E:\source\gh\microsoft\react-native-windows\vnext\Playground\packages'
Restoring packages for E:\source\gh\microsoft\react-native-windows\vnext\Playground\Playground\Playground.csproj...
  CACHE https://api.nuget.org/v3-flatcontainer/microsoft.netcore.universalwindowsplatform/index.json
  CACHE https://api.nuget.org/v3-flatcontainer/microsoft.netcore.universalwindowsplatform/6.0.6/microsoft.netcore.universalwindowsplatform.6.0.6.nupkg
  CACHE https://api.nuget.org/v3-flatcontainer/microsoft.net.native.compiler/index.json
  CACHE https://api.nuget.org/v3-flatcontainer/microsoft.net.native.compiler/2.0.2/microsoft.net.native.compiler.2.0.2.nupkg
  CACHE https://api.nuget.org/v3-flatcontainer/microsoft.net.native.sharedlibrary-arm/index.json
  CACHE https://api.nuget.org/v3-flatcontainer/microsoft.net.native.sharedlibrary-arm/2.0.0/microsoft.net.native.sharedlibrary-arm.2.0.0.nupkg
  CACHE https://api.nuget.org/v3-flatcontainer/microsoft.net.native.sharedlibrary-x64/index.json
  CACHE https://api.nuget.org/v3-flatcontainer/microsoft.net.native.sharedlibrary-x64/2.0.0/microsoft.net.native.sharedlibrary-x64.2.0.0.nupkg
  CACHE https://api.nuget.org/v3-flatcontainer/microsoft.net.native.sharedlibrary-x86/index.json
  CACHE https://api.nuget.org/v3-flatcontainer/microsoft.net.native.sharedlibrary-x86/2.0.0/microsoft.net.native.sharedlibrary-x86.2.0.0.nupkg
  CACHE https://api.nuget.org/v3-flatcontainer/microsoft.net.uwpcoreruntimesdk/index.json
  CACHE https://api.nuget.org/v3-flatcontainer/microsoft.net.uwpcoreruntimesdk/2.1.1/microsoft.net.uwpcoreruntimesdk.2.1.1.nupkg
  CACHE https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.uwpcoreruntimesdk/index.json
  CACHE https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.uwpcoreruntimesdk/2.1.1/runtime.win10-arm.microsoft.net.uwpcoreruntimesdk.2.1.1.nupkg
  CACHE https://api.nuget.org/v3-flatcontainer/runtime.win10-x64.microsoft.net.uwpcoreruntimesdk/index.json
  CACHE https://api.nuget.org/v3-flatcontainer/runtime.win10-x64.microsoft.net.uwpcoreruntimesdk/2.1.1/runtime.win10-x64.microsoft.net.uwpcoreruntimesdk.2.1.1.nupkg
  CACHE https://api.nuget.org/v3-flatcontainer/runtime.win10-x86.microsoft.net.uwpcoreruntimesdk/index.json
  CACHE https://api.nuget.org/v3-flatcontainer/runtime.win10-x86.microsoft.net.uwpcoreruntimesdk/2.1.1/runtime.win10-x86.microsoft.net.uwpcoreruntimesdk.2.1.1.nupkg
  CACHE https://api.nuget.org/v3-flatcontainer/microsoft.netcore.platforms/index.json
  CACHE https://api.nuget.org/v3-flatcontainer/microsoft.netcore.platforms/2.0.0/microsoft.netcore.platforms.2.0.0.nupkg
  CACHE https://api.nuget.org/v3-flatcontainer/netstandard.library/index.json
  CACHE https://api.nuget.org/v3-flatcontainer/netstandard.library/2.0.1/netstandard.library.2.0.1.nupkg
Installing runtime.win10-x86.Microsoft.Net.UWPCoreRuntimeSdk 2.1.1.
Installing runtime.win10-x64.Microsoft.Net.UWPCoreRuntimeSdk 2.1.1.
Installing runtime.win10-arm.Microsoft.Net.UWPCoreRuntimeSdk 2.1.1.
Installing Microsoft.Net.Native.SharedLibrary-x86 2.0.0.
Installing Microsoft.Net.Native.SharedLibrary-x64 2.0.0.
Installing Microsoft.Net.Native.SharedLibrary-arm 2.0.0.
Installing NETStandard.Library 2.0.1.
Installing Microsoft.NETCore.Platforms 2.0.0.
Installing Microsoft.Net.UWPCoreRuntimeSdk 2.1.1.
Installing Microsoft.Net.Native.Compiler 2.0.2.
Installing Microsoft.NETCore.UniversalWindowsPlatform 6.0.6.
Please provide credentials for: https://office.pkgs.visualstudio.com/_packaging/Office/nuget/v3/index.json
UserName:   CACHE https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.netcore.universalwindowsplatform/index.json
  CACHE https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.netcore.universalwindowsplatform/6.0.6/runtime.win10-arm.microsoft.netcore.universalwindowsplatform.6.0.6.nupkg
  CACHE https://api.nuget.org/v3-flatcontainer/runtime.win10-arm-aot.microsoft.netcore.universalwindowsplatform/index.json
  CACHE https://api.nuget.org/v3-flatcontainer/runtime.win10-arm-aot.microsoft.netcore.universalwindowsplatform/6.0.6/runtime.win10-arm-aot.microsoft.netcore.universalwindowsplatform.6.0.6.nupkg
  CACHE https://api.nuget.org/v3-flatcontainer/runtime.win10-x64.microsoft.netcore.universalwindowsplatform/index.json
  CACHE https://api.nuget.org/v3-flatcontainer/runtime.win10-x64.microsoft.netcore.universalwindowsplatform/6.0.6/runtime.win10-x64.microsoft.netcore.universalwindowsplatform.6.0.6.nupkg
  CACHE https://api.nuget.org/v3-flatcontainer/runtime.win10-x64-aot.microsoft.netcore.universalwindowsplatform/index.json
  CACHE https://api.nuget.org/v3-flatcontainer/runtime.win10-x64-aot.microsoft.netcore.universalwindowsplatform/6.0.6/runtime.win10-x64-aot.microsoft.netcore.universalwindowsplatform.6.0.6.nupkg
  CACHE https://api.nuget.org/v3-flatcontainer/runtime.win10-x86.microsoft.netcore.universalwindowsplatform/index.json
  CACHE https://api.nuget.org/v3-flatcontainer/runtime.win10-x86.microsoft.netcore.universalwindowsplatform/6.0.6/runtime.win10-x86.microsoft.netcore.universalwindowsplatform.6.0.6.nupkg
  CACHE https://api.nuget.org/v3-flatcontainer/runtime.win10-x86-aot.microsoft.netcore.universalwindowsplatform/index.json
  CACHE https://api.nuget.org/v3-flatcontainer/runtime.win10-x86-aot.microsoft.netcore.universalwindowsplatform/6.0.6/runtime.win10-x86-aot.microsoft.netcore.universalwindowsplatform.6.0.6.nupkg
Installing runtime.win10-x86-aot.Microsoft.NETCore.UniversalWindowsPlatform 6.0.6.
Installing runtime.win10-x86.Microsoft.NETCore.UniversalWindowsPlatform 6.0.6.
Installing runtime.win10-x64-aot.Microsoft.NETCore.UniversalWindowsPlatform 6.0.6.
Installing runtime.win10-x64.Microsoft.NETCore.UniversalWindowsPlatform 6.0.6.
Installing runtime.win10-arm-aot.Microsoft.NETCore.UniversalWindowsPlatform 6.0.6.
Installing runtime.win10-arm.Microsoft.NETCore.UniversalWindowsPlatform 6.0.6.
Committing restore...
Generating MSBuild file E:\source\gh\microsoft\react-native-windows\vnext\Playground\Playground\obj\Playground.csproj.nuget.g.props.
Generating MSBuild file E:\source\gh\microsoft\react-native-windows\vnext\Playground\Playground\obj\Playground.csproj.nuget.g.targets.
Writing assets file to disk. Path: E:\source\gh\microsoft\react-native-windows\vnext\Playground\Playground\obj\project.assets.json
Restore completed in 20.86 sec for E:\source\gh\microsoft\react-native-windows\vnext\Playground\Playground\Playground.csproj.

NuGet Config files used:
    E:\source\gh\microsoft\react-native-windows\vnext\NuGet.Config
    C:\Users\AconexAdmin\AppData\Roaming\NuGet\NuGet.Config
    C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config
    C:\Program Files (x86)\NuGet\Config\Xamarin.Offline.config

Feeds used:
    C:\Users\AconexAdmin\.nuget\packages\
    https://api.nuget.org/v3/index.json
    https://office.pkgs.visualstudio.com/_packaging/Office/nuget/v3/index.json
    C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

Installed:
    3 package(s) to packages.config projects
    17 package(s) to E:\source\gh\microsoft\react-native-windows\vnext\Playground\Playground\Playground.csproj
`

**Comment by liquidboy** [comment]
followed by an "npm install" via command line i was able to get VS2019 preview building the project ... thanks a million :)
```

1>------ Build started: Project: Folly, Configuration: Debug x64 ------
2>------ Build started: Project: ReactCommon, Configuration: Debug x64 ------
1>Assume.cpp
1>json_pointer.cpp
2>CxxNativeModule.cpp
1>Format.cpp
1>String.cpp
1>F14Table.cpp
1>Conv.cpp
1>Demangle.cpp
1>dynamic.cpp
2>Instance.cpp
2>JSBundleType.cpp
2>JSExecutor.cpp
2>JSIndexedRAMBundle.cpp
2>MethodCall.cpp
2>ModuleRegistry.cpp
2>NativeToJsBridge.cpp
2>Platform.cpp
1>json.cpp
1>SpookyHashV2.cpp
1>ScopeGuard.cpp
1>Unicode.cpp
2>RAMBundleRegistry.cpp
1>MallocImpl.cpp
1>ColdClass.cpp
2>ReactMarker.cpp
2>jsi.cpp
2>JSIDynamic.cpp
2>JSIExecutor.cpp
2>JSINativeModules.cpp
2>Utils.cpp
2>YGConfig.cpp
2>YGEnums.cpp
2>YGFloatOptional.cpp
2>YGLayout.cpp
2>YGNode.cpp
2>YGNodePrint.cpp
2>YGStyle.cpp
2>Yoga.cpp
1>string.cpp
1>Folly.vcxproj -> E:\source\gh\microsoft\react-native-windows\vnext\target\x64\Debug\Folly\Folly.lib
2>ReactCommon.vcxproj -> E:\source\gh\microsoft\react-native-windows\vnext\target\x64\Debug\ReactCommon\ReactCommon.lib
3>------ Build started: Project: ReactWindowsCore, Configuration: Debug x64 ------
3>CxxMessageQueue.cpp
3>JSBigAbiString.cpp
3>LayoutAnimation.cpp
3>AppStateModule.cpp
3>ExceptionsManagerModule.cpp
3>I18nModule.cpp
3>SourceCodeModule.cpp
3>UIManagerModule.cpp
3>ShadowNode.cpp
3>ShadowNodeRegistry.cpp
3>ViewManager.cpp
3>ReactWindowsCore.vcxproj -> E:\source\gh\microsoft\react-native-windows\vnext\target\x64\Debug\ReactWindowsCore\ReactWindowsCore.lib
4>------ Build started: Project: ReactUWP, Configuration: Debug x64 ------
4>ChakraExecutor.cpp
4>ChakraHelpers.cpp
4>ChakraNativeModules.cpp
4>ChakraPlatform.cpp
4>ChakraTracing.cpp
4>ChakraUtils.cpp
4>ChakraValue.cpp
4>AsyncStorageModule.cpp
4>AsyncStorageManager.cpp
4>FollyDynamicConverter.cpp
4>Logging.cpp
4>MemoryTracker.cpp
4>ABIModuleLoader.cpp
4>Instance_rt.cpp
4>ReactControl_rt.cpp
4>InstanceManager.cpp
4>OInstance.cpp
4>InstanceFactory.cpp
4>UwpReactInstance.cpp
4>JSBigString.cpp
4>WebSocketJSExecutorFactory.cpp
4>WebSocketJSExecutorUwp.cpp
4>AppStateModuleUwp.cpp
4>ClipboardModule.cpp
4>DeviceInfoModule.cpp
4>DevSupportManagerUwp.cpp
4>I18nModule.cpp
4>LinkingManagerModule.cpp
4>LocationObserverModule.cpp
4>NativeUIManager.cpp
4>NetworkingModule.cpp
4>TimingModule.cpp
4>WebSocketModuleUwp.cpp
4>ButtonContentViewManager.cpp
4>ButtonViewManager.cpp
4>ContentControlViewManager.cpp
4>HyperlinkViewManager.cpp
4>IconViewManager.cpp
4>DevSupportManagerUwpSandbox.cpp
4>JSQueueThread.cpp
4>UIMessageQueueThread.cpp
4>WorkerMessageQueueThread.cpp
4>LocalBundleReader.cpp
4>ValueUtils.cpp
4>ActivityIndicatorViewManager.cpp
4>CheckboxViewManager.cpp
4>ControlViewManager.cpp
4>DatePickerViewManager.cpp
4>FlyoutViewManager.cpp
4>FrameworkElementViewManager.cpp
4>ImageViewManager.cpp
4>PickerViewManager.cpp
4>PopupViewManager.cpp
4>RawTextViewManager.cpp
4>ReactControl.cpp
4>ReactRootView.cpp
4>RootViewManager.cpp
4>ScrollViewManager.cpp
4>ShadowNodeBase.cpp
4>SwitchViewManager.cpp
4>TextInputViewManager.cpp
4>TextViewManager.cpp
4>TouchEventHandler.cpp
4>ViewControl.cpp
4>ViewManagerBase.cpp
4>ViewViewManager.cpp
4>VirtualTextViewManager.cpp
4>WebViewManager.cpp
4>   Creating library E:\source\gh\microsoft\react-native-windows\vnext\target\x64\Debug\ReactUWP\React.UWP.lib and object E:\source\gh\microsoft\react-native-windows\vnext\target\x64\Debug\ReactUWP\React.UWP.exp
4>ReactUWP.vcxproj -> E:\source\gh\microsoft\react-native-windows\vnext\target\x64\Debug\ReactUWP\React.UWP.dll
5>------ Build started: Project: Playground, Configuration: Debug x64 ------
5>  Playground -> E:\source\gh\microsoft\react-native-windows\vnext\target\x64\Debug\Playground\Playground\Playground.exe
========== Build: 5 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

```

**Comment by liquidboy** [comment]
sry :( ....   Everything builds successfully BUT when i run it (F5) it fails with a big red screen 

In the process of trying to troubleshoot this ... but thought i'd mention it here 

![image](https://user-images.githubusercontent.com/599657/57278473-de40f280-70e9-11e9-81a5-f9b715aaf8b0.png)

**Comment by harinikmsft** [comment]
Your packager is not running. Please run `yarn start` in a command prompt on the repo folder before F5 on the UWP app. Make sure chrome is running.

The easiest and recommended developer experience to building your own app is to use the CLI tools we have published which take care of all these steps for you. Please refer to the docs: https://github.com/microsoft/react-native-windows/blob/master/vnext/docs/GettingStarted.md
