### ISSUE TITLE
Build failed with message Error: MSBuild tools not found. Check your build configuration.

### ISSUE THREAD

**Issue by birobirobiro** [microsoft/react-native-windows#2420]
![image](https://user-images.githubusercontent.com/22185823/57272705-308efe80-706b-11e9-98f1-9e0367017152.png)

**Comment by harinikmsft** [comment]
Can you provide details of your setup? Which VS version, Windows SDK, setup steps are you running?

**Comment by reddvid** [comment]
I also got this issue, I'm on Win 10 Insider Preview 18890, VS 2019 (as per requirements VS2017 or greater).

Followed Getting-started-current and failed on that step (run on VS/run-windows).

Installed C++ workload and MSVC/ATL 141 build tools. Still fails.

**Comment by MungeParty** [comment]
I had the same issue until I installed VS 2017 specifically.

**Comment by birobirobiro** [comment]
I was able to solve using v-next

https://youtu.be/kvfuGsOA_T8

**Comment by reutopiaer** [comment]
I can build success with sln but still get error "Build failed with message Error: MSBuild tools not found. Check your build configuration."
![rnw](https://user-images.githubusercontent.com/759279/57498183-7b2fa580-730d-11e9-8c72-3466bfcb77ad.png)

**Comment by mateuszgazdziak** [comment]
Anyone knows how to run it on vs 2019?

**Comment by stratospheres** [comment]
> Anyone knows how to run it on vs 2019?

Pretty sure it's going to be related to a lack of support here:

``` 
<yourapp>\node_modules\react-native-windows\local-cli\runWindows\utils\msbuildtools.js
```

Working on hacking it now (for a vNext version of the template) but don't have a fix yet.

**Comment by reutopiaer** [comment]
@stratospheres Tank you very much! It's works!

**Comment by nguyen-tam** [comment]
The same here, MS should fix this.

**Comment by saraswathirbt** [comment]
Build failed with message Error: MSBuild tools not found. Check your build configuration. facing with the same issue can any one help to solve this, Thanks in advance

**Comment by ShrinathGupta** [comment]
I tried with both the VS 2017 as well as 2019  and even tried doing above hack. But not succeed.  Getting same error. 
Does anyone know about any other work around? Thanks.

**Comment by ShrinathGupta** [comment]
> I can build success with sln but still get error "Build failed with message Error: MSBuild tools not found. Check your build configuration."
> ![rnw](https://user-images.githubusercontent.com/759279/57498183-7b2fa580-730d-11e9-8c72-3466bfcb77ad.png)

I tried with both the VS 2017 as well as 2019 and even tried doing above hack. But not succeed. Getting same error.
Does anyone know about any other work around? Thanks.

**Comment by ralexand56** [comment]
So frustrating that this doesn't work with MS' own latest dev tools and doesn't work with the latest version of react native. I wish MS would devote more resources to this project.

**Comment by harinikmsft** [comment]
Apologies on this. As @stratospheres pointed out, we are working on making the CLI for vnext work with VS 2019. Issue #2320 is tracking this (we just submitted a first PR #2539) . 

You can follow the Advanced install method specified here - [Advanced install](https://github.com/microsoft/react-native-windows/blob/master/vnext/docs/GettingStarted.md#2-advanced-install-method) for working on vNext with VS 2019 until we fix the buildpath issues with the CLI.

**Comment by ShrinathGupta** [comment]
@harinikmsft Thanks for addressing issue and giving workaround.

**Comment by marlenecota** [comment]
We merged a couple of fixes yesterday (#2539 and #2396). Please try it out and let us know if you are still seeing issues.

**Comment by harinikmsft** [comment]
Closing as verified locally. Please reopen if you are still seeing issues post the fixes from PRs #2539 and #2396

**Comment by hmheng** [comment]
@harinikmsft, still facing the same issue with rnwindows 0.57 versions.
I have VS2017 and VS2019 installed.

**Comment by harinikmsft** [comment]
Sorry to hear that @hmheng. @marlenecota  - can you take a look again?

**Comment by ShrinathGupta** [comment]
@harinikmsft  Even same behavior for me.  :( It's not working.

**Comment by MungeParty** [comment]
Same here on version 0.57.1, haven't tried vnext since due to lack of transform animation.

**Comment by marlenecota** [comment]
Ah, my fix was only for vnext. @ShrinathGupta were you also using current?

**Comment by hmheng** [comment]
If we upgrade to vnext, it will break android compilation. I haven't try ios yet.

**Comment by ShrinathGupta** [comment]
> Ah, my fix was only for vnext. @ShrinathGupta were you also using current?

@marlenecota  Yes i was using vnext and i was building uwp app.

**Comment by marlenecota** [comment]
@hmheng, @ShrinathGupta - 0.57.2 and 0.58.0-rc.2 have been patched. Please give that a go.

**Comment by hmheng** [comment]
@marlenecota  thank you..
My reactnative version is RN 0.57..

PS D:\PS\Repos\RNWindows> react-native windows --template current
Reading application name from package.json...
Reading react-native version from node_modules...
Checking for react-native-windows version matching 0.57.*...
Could not find react-native-windows@0.57.*-current.*.

**Comment by ShrinathGupta** [comment]
@marlenecota It has been long time since i worked on it. Good news today i checked and it worked. Awesome thanks @marlenecota   :clap: :100:

**Comment by ShrinathGupta** [comment]
If anybody wants to give a try to react native windows vnext. 
They can try https://github.com/ShrinathGupta/React-native-windows-demo 
It's awesome. I worked on previous version of it, vnext is far better then that although development is still ongoing.

**Comment by chrisglein** [comment]
Sounds like this is resolved.

**Comment by pablogarayprosis** [comment]
try it today - 2019-10-03. Visual Studio 2017. react-native --version 0.59
same error message. windows 10.

**Comment by EngDjango** [comment]
> > Anyone knows how to run it on vs 2019?
> 
> Pretty sure it's going to be related to a lack of support here:
> 
> ```
> <yourapp>\node_modules\react-native-windows\local-cli\runWindows\utils\msbuildtools.js
> ```
> 
> I can get it to finish building and start by (and please don't do this and expect anything but a hack, but...) doing the following in the checkMSBuildVersion() function, just before the final return:
> 
> ```
> if (version === "16.0") {
>    toolsPath = "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\MSBuild\\Current\\Bin"
> }
> ```
> 
> In order to get that to be called, I updated the array of possible version values at line 12 of the file to:
> 
> ```
> MSBUILD_VERSIONS = ['16.0', '15.0', '14.0', '12.0', '4.0'];
> ```
> 
> Finally, you need to hack the buildProject() function as well to handle VS2019 version numbers... look for the comment around line 40 referring to VS2017 and do something similar for V16/VS2019.
> 
> ```
> if (this.version === '16.0') {
>   args.push('/p:PlatformToolset=v142');
>   args.push('/p:VisualStudioVersion=16.0');
> }
> ```
> 
> Also
> To be super clear - this is for a machine with VS2019 _only_ (no VS2017 installation) and the vNext template. Also, YMMV, and this is a hack - just to get up and running to play. Don't leave your code like this in the long haul, even if you get it working.
> 
> UPDATE: there's a tracking issue for VS2019 support here: #2320 .

### just provided "msbuild.exe" path to "toolsPath" var , 
### in "\node_modules\react-native-windows\local-cli\runWindows\utils\msbuildtools.js"
### and now it is working ,
### thank you.

**Comment by matt-d-webb** [comment]
> > > Anyone knows how to run it on vs 2019?
> > 
> > 
> > Pretty sure it's going to be related to a lack of support here:
> > ```
> > <yourapp>\node_modules\react-native-windows\local-cli\runWindows\utils\msbuildtools.js
> > ```
> > 
> > 
> > I can get it to finish building and start by (and please don't do this and expect anything but a hack, but...) doing the following in the checkMSBuildVersion() function, just before the final return:
> > ```
> > if (version === "16.0") {
> >    toolsPath = "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\MSBuild\\Current\\Bin"
> > }
> > ```
> > 
> > 
> > In order to get that to be called, I updated the array of possible version values at line 12 of the file to:
> > ```
> > MSBUILD_VERSIONS = ['16.0', '15.0', '14.0', '12.0', '4.0'];
> > ```
> > 
> > 
> > Finally, you need to hack the buildProject() function as well to handle VS2019 version numbers... look for the comment around line 40 referring to VS2017 and do something similar for V16/VS2019.
> > ```
> > if (this.version === '16.0') {
> >   args.push('/p:PlatformToolset=v142');
> >   args.push('/p:VisualStudioVersion=16.0');
> > }
> > ```
> > 
> > 
> > Also
> > To be super clear - this is for a machine with VS2019 _only_ (no VS2017 installation) and the vNext template. Also, YMMV, and this is a hack - just to get up and running to play. Don't leave your code like this in the long haul, even if you get it working.
> > UPDATE: there's a tracking issue for VS2019 support here: #2320 .
> 
> ### just provided "msbuild.exe" path to "toolsPath" var ,
> ### in "\node_modules\react-native-windows\local-cli\runWindows\utils\msbuildtools.js"
> ### and now it is working ,
> ### thank you.

Can you explain this in more detail, please?

**Comment by GauravBacancy** [comment]
> > Anyone knows how to run it on vs 2019?
> 
> Pretty sure it's going to be related to a lack of support here:
> 
> ```
> <yourapp>\node_modules\react-native-windows\local-cli\runWindows\utils\msbuildtools.js
> ```
> 
> I can get it to finish building and start by (and please don't do this and expect anything but a hack, but...) doing the following in the checkMSBuildVersion() function, just before the final return:
> 
> ```
> if (version === "16.0") {
>    toolsPath = "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\MSBuild\\Current\\Bin"
> }
> ```
> 
> In order to get that to be called, I updated the array of possible version values at line 12 of the file to:
> 
> ```
> MSBUILD_VERSIONS = ['16.0', '15.0', '14.0', '12.0', '4.0'];
> ```
> 
> Finally, you need to hack the buildProject() function as well to handle VS2019 version numbers... look for the comment around line 40 referring to VS2017 and do something similar for V16/VS2019.
> 
> ```
> if (this.version === '16.0') {
>   args.push('/p:PlatformToolset=v142');
>   args.push('/p:VisualStudioVersion=16.0');
> }
> ```
> 
> Also
> To be super clear - this is for a machine with VS2019 _only_ (no VS2017 installation) and the vNext template. Also, YMMV, and this is a hack - just to get up and running to play. Don't leave your code like this in the long haul, even if you get it working.
> 
> UPDATE: there's a tracking issue for VS2019 support here: #2320 .

I can not find any path like this 
"\node_modules\react-native-windows\local-cli\runWindows\utils\msbuildtools.js"
I found file with this path
"\node_modules\@react-native-windows\cli\lib-commonjs\runWindows\utils\msbuildtools.js"
But there is no such code mentioned
Please provide support

**Comment by gaurav8809** [comment]
> > Anyone knows how to run it on vs 2019?
> 
> Pretty sure it's going to be related to a lack of support here:
> 
> ```
> <yourapp>\node_modules\react-native-windows\local-cli\runWindows\utils\msbuildtools.js
> ```
> 
> I can get it to finish building and start by (and please don't do this and expect anything but a hack, but...) doing the following in the checkMSBuildVersion() function, just before the final return:
> 
> ```
> if (version === "16.0") {
>    toolsPath = "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\MSBuild\\Current\\Bin"
> }
> ```
> 
> In order to get that to be called, I updated the array of possible version values at line 12 of the file to:
> 
> ```
> MSBUILD_VERSIONS = ['16.0', '15.0', '14.0', '12.0', '4.0'];
> ```
> 
> Finally, you need to hack the buildProject() function as well to handle VS2019 version numbers... look for the comment around line 40 referring to VS2017 and do something similar for V16/VS2019.
> 
> ```
> if (this.version === '16.0') {
>   args.push('/p:PlatformToolset=v142');
>   args.push('/p:VisualStudioVersion=16.0');
> }
> ```
> 
> Also
> To be super clear - this is for a machine with VS2019 _only_ (no VS2017 installation) and the vNext template. Also, YMMV, and this is a hack - just to get up and running to play. Don't leave your code like this in the long haul, even if you get it working.
> 
> UPDATE: there's a tracking issue for VS2019 support here: #2320 .

I can not find any path like this
"\node_modules\react-native-windows\local-cli\runWindows\utils\msbuildtools.js"
I found file with this path
"\node_modules@react-native-windows\cli\lib-commonjs\runWindows\utils\msbuildtools.js"
But there is no such code mentioned
Please provide support

**Comment by chrisglein** [comment]
> > > Anyone knows how to run it on vs 2019?
> > 
> > 
> > Pretty sure it's going to be related to a lack of support here:
> > ```
> > <yourapp>\node_modules\react-native-windows\local-cli\runWindows\utils\msbuildtools.js
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I can get it to finish building and start by (and please don't do this and expect anything but a hack, but...) doing the following in the checkMSBuildVersion() function, just before the final return:
> > ```
> > if (version === "16.0") {
> >    toolsPath = "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\MSBuild\\Current\\Bin"
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In order to get that to be called, I updated the array of possible version values at line 12 of the file to:
> > ```
> > MSBUILD_VERSIONS = ['16.0', '15.0', '14.0', '12.0', '4.0'];
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Finally, you need to hack the buildProject() function as well to handle VS2019 version numbers... look for the comment around line 40 referring to VS2017 and do something similar for V16/VS2019.
> > ```
> > if (this.version === '16.0') {
> >   args.push('/p:PlatformToolset=v142');
> >   args.push('/p:VisualStudioVersion=16.0');
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also
> > To be super clear - this is for a machine with VS2019 _only_ (no VS2017 installation) and the vNext template. Also, YMMV, and this is a hack - just to get up and running to play. Don't leave your code like this in the long haul, even if you get it working.
> > UPDATE: there's a tracking issue for VS2019 support here: #2320 .
> 
> I can not find any path like this
> "\node_modules\react-native-windows\local-cli\runWindows\utils\msbuildtools.js"
> I found file with this path
> "\node_modules@react-native-windows\cli\lib-commonjs\runWindows\utils\msbuildtools.js"
> But there is no such code mentioned
> Please provide support

@gaurav8809 This issue is almost a year old. Can you open a fresh issue that contains your environment info?

**Comment by gaurav8809** [comment]
I can provide you my environment info here
 

> > > > Anyone knows how to run it on vs 2019?
> > > 
> > > 
> > > Pretty sure it's going to be related to a lack of support here:
> > > ```
> > > <yourapp>\node_modules\react-native-windows\local-cli\runWindows\utils\msbuildtools.js
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I can get it to finish building and start by (and please don't do this and expect anything but a hack, but...) doing the following in the checkMSBuildVersion() function, just before the final return:
> > > ```
> > > if (version === "16.0") {
> > >    toolsPath = "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\MSBuild\\Current\\Bin"
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > In order to get that to be called, I updated the array of possible version values at line 12 of the file to:
> > > ```
> > > MSBUILD_VERSIONS = ['16.0', '15.0', '14.0', '12.0', '4.0'];
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Finally, you need to hack the buildProject() function as well to handle VS2019 version numbers... look for the comment around line 40 referring to VS2017 and do something similar for V16/VS2019.
> > > ```
> > > if (this.version === '16.0') {
> > >   args.push('/p:PlatformToolset=v142');
> > >   args.push('/p:VisualStudioVersion=16.0');
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Also
> > > To be super clear - this is for a machine with VS2019 _only_ (no VS2017 installation) and the vNext template. Also, YMMV, and this is a hack - just to get up and running to play. Don't leave your code like this in the long haul, even if you get it working.
> > > UPDATE: there's a tracking issue for VS2019 support here: #2320 .
> > 
> > 
> > I can not find any path like this
> > "\node_modules\react-native-windows\local-cli\runWindows\utils\msbuildtools.js"
> > I found file with this path
> > "\node_modules@react-native-windows\cli\lib-commonjs\runWindows\utils\msbuildtools.js"
> > But there is no such code mentioned
> > Please provide support
> 
> @gaurav8809 This issue is almost a year old. Can you open a fresh issue that contains your environment info?

**Comment by chrisglein** [comment]
> I can provide you my environment info here
> > @gaurav8809 This issue is almost a year old. Can you open a fresh issue that contains your environment info?

Please open a new issue and follow the instructions in the template. That's the best way to help us to provide support.
