### ISSUE TITLE
Create RN libraries

### ISSUE THREAD

**Issue by jdnichollsc** [microsoft/react-native-windows#2421]
Hello guys,
Sorry for this informal issue... but what're the steps to support Windows creating a RN library => https://github.com/frostney/react-native-create-library
Let me know and I can add support for Windows from my plugins too 🤘

Thanks in advance,  
Nicholls

**Comment by rozele** [comment]
@jdnichollsc - I believe we already have templates, but they may be slightly out of date. Are you having specific problems with the `react-native-create-library` tool?

**Comment by jdnichollsc** [comment]
Honestly I can see any example supporting windows with that tool. So if you can give me any example would be awesome!

**Comment by rozele** [comment]
@jdnichollsc - the main README has a GIF of using the CLI tool, which by default generates a windows library.

**Comment by jdnichollsc** [comment]
@rozele what GIF?

**Comment by jdnichollsc** [comment]
I mean, How can I know if `react-native-create-library` is already using `react-native-windows`?

**Comment by rozele** [comment]
Run the tool - check if a windows folder is generated.
