### ISSUE TITLE
Feature request: WebGL support

### ISSUE THREAD

**Issue by rohan-deshpande** [microsoft/react-native-windows#2424]
Would love to see WebGL contexts being supported through this library. This would open the door for 3D apps to be built with JavaScript for Windows environments. It would be a huge win for libraries like Babylon and Three. 

I think that `react-native` itself doesn’t yet support WebGL, but it would be an awesome feature to see Microsoft take charge of.

**Comment by chrisglein** [comment]
Would be sweet. No action anytime soon for react-native-windows so closing this issue.

**Comment by boundaryfree** [comment]
@rohan-deshpande Why not embed WebView to your App. The WebView support WebGL naturally.

**Comment by Losses** [comment]
As expo-gl bring webGL api to ReactNative, I'm not sure if React Native for Windows could support it.
