### ISSUE TITLE
Publish current version to npm to pick up readme

### ISSUE THREAD

**Issue by harinikmsft** [microsoft/react-native-windows#2438]
The C# implementation needs to be published to npm manually in order for the main landing page [here](https://www.npmjs.com/package/react-native-windows) to show the readme file from [here](https://github.com/microsoft/react-native-windows/tree/master/current)

**Comment by harinikmsft** [comment]
Hey @in4margaret - can you help with this?

**Comment by harinikmsft** [comment]
@rozele - can you see if you can get this fixed so the main landing page [here](https://www.npmjs.com/package/react-native-windows) is picking up the right readme file?

**Comment by rozele** [comment]
@harinikmsft will do

**Comment by rozele** [comment]
Done: https://www.npmjs.com/package/react-native-windows
