### ISSUE TITLE
Bundled images assets in appxs aren't found

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#2452]
Right now, we hardcode ReactUWP to expect packaged bundles to be in `ms-appx://Bundle/{filename}.bundle`

The developer passes in `{filename}`.

So if you run `react-native bundle --platform uwp--entry-file index.js --bundle-output Bundle\index.uwp.bundle --assets-dest Bundle` to get:

```
Bundle\
- index.uwp.bundle
  assets\
    - asset1.png
    - asset2.png
```

However, when loading images, we translate the path `file://assets/asset1.png` to `ms-appx:///assets/asset1.png`

**Comment by jonthysell** [comment]
We need to figure out #2220 and get this consistent

**Comment by NickGerleman** [comment]
https://github.com/microsoft/react-native-windows/issues/2220 was closed, where it sounds like this is all working now Anything left for this?
