### ISSUE TITLE
Support 2.0 CppWinRT

### ISSUE THREAD

**Issue by licanhua** [microsoft/react-native-windows#2455]
To support this, we migrate/author instance_rt/reactControl_rt/ module_rt in a new way. Here are some details we need to pay attention to:

- Update CppWinRT nuget from 1.0 to 2.0
- Remove all term of ABI
- Remove all Microsoft::WRL::ComPtr and replace then with winrt:: namespace.
- vcxproj change and target changes. for example, remove midlrt.targets
- It's possible that we don't need mdmerge target
- Remove OLD_CPPWINRT
- Check with other workstream who use make.inc
- 

Some document about cppwinrt
[move-to-winrt-from-wrl](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/move-to-winrt-from-wrl)
[author-apis](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/author-apis)

**Comment by kmelmon** [comment]
This would be nice to do but not high in priority.  marking as nice-to-have.

**Comment by licanhua** [comment]
The left task is to move WRL to cppwinrt.
Since IModule and other WRL implementation would be moved to other project, I will close this task, and left task is tracking by #3236
