### ISSUE TITLE
Axios Fails on RNW (Add support for useIncrementalUpdates in Networking Module)

### ISSUE THREAD

**Issue by stecrain** [microsoft/react-native-windows#2460]
Any http requests from a react native app which request progress updates will currently fail.

We currently use axios for http requests, and the library requests progress updates.
https://github.com/axios/axios/blob/503418718f669fcc674719fd862b355605d7b41f/lib/adapters/xhr.js

**Comment by kmelmon** [comment]
@stecrain Is this needed before our June 30 milestone?

**Comment by stecrain** [comment]
@kmelmon No, for now we can get our network requests working by monkey patching RCTNetworking.sendRequest to always pass down false for incrementalUpdates.
https://microsoft.visualstudio.com/Xbox.Apps/_git/Xbox.Apps.Store.RNPrototype/pullrequest/3262449?_a=files&path=%2FApp.tsx


We don't have application logic that depends on this, a library that we use requests progress events so that it can fail early.

I am much more interested in issue #2466.
Without something to fix that issue we will wind up consuming a fork of react-native-windwos to make progress on our prototyping.

**Comment by namrog84** [comment]
@harinikmsft, Partner(Xbox) has a use-case for this.  So want to +1 it for the prioritization in Milestone 4.

"useIncrementalUpdates in Networking"

**Comment by namrog84** [comment]
FYI. This is going to become a higher pri for us.

**Comment by marlenecota** [comment]
useIncrementalUpdates is a parameter in RTCNetworking.sendRequest. 

Implementation goes here:
https://github.com/microsoft/react-native-windows/blob/master/vnext/ReactUWP/Modules/NetworkingModule.cpp#L111

And this assert should be removed:
https://github.com/microsoft/react-native-windows/blob/master/vnext/ReactUWP/Modules/NetworkingModule.cpp#L245

**Comment by chrisglein** [comment]
Per comment above about partner being unblocked, downgrading priority of this.

**Comment by lukago** [comment]
is react-native-windows at all development ready? Axios is a standrad library that is present in most react projects and here it is not supported here since almost one year. Is there a way to overcome this bug before this issue is closed?

**Comment by YuliKl** [comment]
@marlenecota looks like Axios is a fundamental module and we should fix this sooner rather than later.

**Comment by chrisglein** [comment]
Still an important bug, but we're told this is no longer immediately blocking for partners. Downgrading from 'must-have' but leaving as potential for 0.62

**Comment by asklar** [comment]
Looks like there isn't new customer requests for this, is there any urgency to implement this?

**Comment by JunielKatarn** [comment]
Incremental updates is not currently supported in Microsoft.ReactNative.

We will open the corresponding issue for follow up.
