### ISSUE TITLE
CI Loop:  Use standard pool for automated builds

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#2464]
Our CI loop is currently using internal Office build machines to build.  This isn't very flexible as we aren't in control of how these machines are configured (eg if we need to install an additional SDK, we need to make a special request).

This issue is tracking moving our build CI loop to "standard" machine pools.  One possible choice is the Microsoft pool:
https://dev.azure.com/microsoft

**Comment by harinikmsft** [comment]
This is also needed so that people submitting PRs from outside Microsoft have access to build errors etc.,

**Comment by NickGerleman** [comment]
Did we do this one already?

**Comment by acoates-ms** [comment]
Yes this is done.
