### ISSUE TITLE
DeviceInfo not reporting window size

### ISSUE THREAD

**Issue by ahimberg** [microsoft/react-native-windows#2470]
DeviceInfo module reports the screen size, but not the window size (hard coded to 100x100 right now).  We should send both and send events when they change.

There is the weirdness of multimon that is not supported by the current API

ReactUWP\Modules\DeviceInfoModule.cpp
    ("windowPhysicalPixels", folly::dynamic::object
      ("width", 100)
      ("height", 100)

Workaround for now is to use the onLayout event to get dimensions of content, but that is async and can force a client to need to delay render inner content if they need to use size values with a component like flatlist.

related issue: https://github.com/microsoft/react-native-windows/issues/2162

**Comment by harinikmsft** [comment]
The primary work here is to return the CoreWindow size in physical pixels from the DeviceInfo implementation.

**Comment by kmelmon** [comment]
@2818 added support for the app when running in a CoreWindow.  We also need to add support for islands.

**Comment by jonthysell** [comment]
We also need to add support for when the root RN control is not the main root element of the window.

**Comment by ddalp** [comment]
Working on it..

**Comment by ddalp** [comment]
Change merged, close the issue.
