### ISSUE TITLE
Ensure React Native for Windows works with CodePush

### ISSUE THREAD

**Issue by kikisaints** [microsoft/react-native-windows#2477]
Currently, there is not an easy, documented way to hook up and use CodePush with our React Native Windows vnext implementation (or even possible to yet?).

It would be good to have that tested to ensure it *can* work, and then a PM to document what's needed to get it *to* work.

**Comment by harinikmsft** [comment]
This is being tracked by App Center CodePush team [here](https://github.com/microsoft/appcenter/issues/463).

**Comment by chrisglein** [comment]
Reactivating. Tracking (and documenting) that this works is pretty important, given how popular CodePush is. It's unclear from the App Center contact whether we have work to do or not. Let's keep an eye on this and push it to completion.

**Comment by stmoy** [comment]
Done! 

https://github.com/microsoft/react-native-code-push/pull/1994

https://www.npmjs.com/package/react-native-code-push

**Comment by aalbaharnah** [comment]
Hey @stmoy, are there any documentations about setting up code push on react native windows  ^0.63.11  applications that use C# as native code base?

**Comment by stmoy** [comment]
Hi @aalbaharnah - this is a good callout. 

The current docs for C++ are here: https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-windows.md

@vmoroz @alexmoroz15 - have y'all tried integrating CodePush with C#? It'd be helpful to include those steps in the docs.
