### ISSUE TITLE
Run react windows app on the mac

### ISSUE THREAD

**Issue by tahagit** [microsoft/react-native-windows#2486]
Hi 
How to run react windows app for test on MAC?

**Comment by harinikmsft** [comment]
Hello - 

React Native for Windows apps can only be run on Windows. See [System requirements](https://github.com/microsoft/react-native-windows#system-requirements).

Are you trying to develop a React Native for Windows app on a mac?

**Comment by tahagit** [comment]
Hi
Yes i do, i have mac and i‘m developing all of my react and reactNative projects on mac.
maybe i should use virtual machine for install windows on the mac?

**Comment by ahimberg** [comment]
It is possible to build the js and run jest tests on mac, but yes if you want to build and run actual native code that requires a windows OS somewhere.

**Comment by harinikmsft** [comment]
Thanks for the feedback. You can use VS for Mac to develop Windows 10 apps using a Mac. However, you need to spin up a Windows 10 VM in order to test/run the app against Windows.
