### ISSUE TITLE
react-native-windows interop with WinUI 3.0

### ISSUE THREAD

**Issue by jesbis** [microsoft/react-native-windows#2492]
With the planned upcoming release of [WinUI 3.0](https://github.com/microsoft/microsoft-ui-xaml/blob/master/docs/roadmap.md) which will be the next version of the native Windows UI platform, it seems worth considering: 

1. react-windows-native core using WinUI instead of the older version of Windows::UI::Xaml

2. enabling using WinUI controls in native UI components/views

**Comment by kikisaints** [comment]
An expansion on #2 would be to make sure that any Windows, separate npm components installed into a React Native project, use WinUI where it makes sense to.

For example if we make a react-native-windows-progressbar, it's using a WinUI progress bar as well - not only the components in react-native-windows.

**Comment by chrisglein** [comment]
WinUI3 alpha [exists](https://docs.microsoft.com/en-us/uwp/toolkits/winui3/), enabling us to begin investigation into this. It's likely that there will be gaps and roadblocks, and that many of those won't be clear until we have an app targeting this. So it seems like we would potentially want to create a branch and separate nuget preview for this so we can solicit feedback. As that it may be floating in pre-release for awhile we may also need a mechanism for supporting both side by side (namespace macros?).

**Comment by chrisglein** [comment]
@asklar I think at this point we can close this issue, agree? As in we've graduated on to more specific issues.
