### ISSUE TITLE
Add Jest to test pipeline

### ISSUE THREAD

**Issue by licanhua** [microsoft/react-native-windows#2499]
Our projects includes JavaScript, half of them are typescript and half of them are not.
So we should add Jest tests.
Add Jest test examples

**Comment by harinikmsft** [comment]
Enabling unit tests are P2 for Milestone 2.

**Comment by kmelmon** [comment]
Setting up the test infrastructure is higher priority and will take the rest of Milestone 2, Moving this to Milestone 3.

**Comment by licanhua** [comment]
Currently we already have tslint, I suggest we move it into late milestone. 
I prefer we delay this until we implement #3166

**Comment by chrisglein** [comment]
Removed references to Flow from this issue. We'll track that as part of #3166. This issue is now just about Jest.

**Comment by licanhua** [comment]
We will not Jest but Jasmine in E2E test. It's nice to close this task.
