### ISSUE TITLE
Unblock VS code extension work

### ISSUE THREAD

**Issue by harinikmsft** [microsoft/react-native-windows#2505]
VS Code extension for react-native-windows-vnext is being developed and they are running into some platform bundling issues and packager issues. Repro steps and details are [here](https://github.com/microsoft/vscode-react-native/issues/1007). This is tracking work on our side to unblock them.

**Comment by harinikmsft** [comment]
Hey @acoates-ms  - can you help @kmelmon on this one so we can unblock Vs code work earlier than later?

**Comment by kmelmon** [comment]
This was addressed by:
https://github.com/microsoft/react-native-windows/pull/2727

All that remains is changing the cs code extension itself, which is being tacked by:
https://github.com/microsoft/vscode-react-native/issues/1007
Closing.
