### ISSUE TITLE
Investigate if RN Windows have memory leak

### ISSUE THREAD

**Issue by licanhua** [microsoft/react-native-windows#2509]
Memory leak often happens on .net and native.

![image](https://user-images.githubusercontent.com/6290692/58131899-badf7280-7bd4-11e9-92ab-799852ebdc66.png)

In pure C# this would be perfectly fine but as RatingControl is implemented in native, .NET knows about MyClass and the Delegate but it doesn't inherently know about RatingControl.

The result is that this reference cycle would never be collected.

In WinUI, ReferenceTracker is used to handle this kind of problem.

React-Native-Windows may be complex, and it may be among C#/C++ and javascript.

**Comment by harinikmsft** [comment]
Please reopen if there is an actual memory leak
