### ISSUE TITLE
[C4819] Incorrect? file encoding format

### ISSUE THREAD

**Issue by aiya000** [microsoft/react-native-windows#2531]
## Versions

```shell-session
>node --version
v12.3.1

>yarn --version
1.16.0

>npm --version
6.9.0
```

## Problem

Hi, I'm a new Japanese user :smiley:

A build error occured.

```
....\neko\node_modules\react-native-windows\reactuwp\threading\asyncworkqueue.cpp(1): error C2220: 警告をエラーとして扱いました。'object' ファイルは生成されません。 [....\neko\node_modules\react-native-windows\ReactUWP\ReactUWP.vcxproj]
....\neko\node_modules\react-native-windows\reactuwp\threading\asyncworkqueue.cpp(1): warning C4819: ファイルは、現在のコード ページ (932) で表示できない文字を含んでいます。データの損失を防ぐために、ファイルを Unicode 形式で保存してください。 [....\neko\node_modules\react-native-windows\ReactUWP\ReactUWP.vcxproj]
```

It says

- error C2220: the warning is regarded as an error. the 'object' file doesn't make.
- warning C4819: the file contains a character that cannot be shown on the current code page (932). Save the file by the Unicode format to protect breaking data.

I made the react-native project by :point_down:

```shell-session
> react-native init neko
> cd neko
> yarn add rnpm-plugin-windows
> react-native windows --template vnext
> react-native run-windows
```

And then, it shew.

```shell-session
Restoring NuGet packages
Building ..../neko/windows/neko.sln
Found MSBuild v15.0 at C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin
Building Solution: ..../neko/windows/neko.sln
Build configuration: Debug
Build platform: x86
このソリューション内のプロジェクトを 1 度に 1 つずつビルドします。並行ビルドを有効にするには、"/m" スイッチを追加してください。
....\neko\node_modules\react-native-windows\reactuwp\threading\asyncworkqueue.cpp(1): error C2220: 警告をエラーとして扱いました。'object' ファイルは生成されません。 [....\neko\node_modules\react-native-windows\ReactUWP\ReactUWP.vcxproj]
....\neko\node_modules\react-native-windows\reactuwp\threading\asyncworkqueue.cpp(1): warning C4819: ファイルは、現在のコード ページ (932) で表示できない文字を含んでいます。データの損失を防ぐために、ファイルを Unicode 形式で保存してください。 [....\neko\node_modules\react-native-windows\ReactUWP\ReactUWP.vcxproj]
Build failed with message Error: Command failed: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\msbuild.exe" "..../neko/windows/neko.sln" /clp:NoSummary;NoItemAndPropertyList;Verbosity=quiet /nologo /p:Configuration=Debug /p:Platform=x86 /p:AppxBundle=Never /p:PlatformToolset=v141 /p:VisualStudioVersion=15.0. Check your build configuration.
```

Also, this problem can be fixed.

I re-save `....\neko\node_modules\react-native-windows\reactuwp\threading\asyncworkqueue.cpp` as UTF-8 with BOM, by Vim.

```shell-session
> vim ....\neko\node_modules\react-native-windows\reactuwp\threading\asyncworkqueue.cpp
:set bomb
:wq
> react-native run-windows
(OK)
```

Thanks :+1:

**Comment by harinikmsft** [comment]
Hellow @aiya000 - can you provide the SDK/VS tools versions you are using? Please ensure you are running the dependencies as outlined in [System requirements](https://github.com/microsoft/react-native-windows/blob/master/vnext/docs/GettingStarted.md#system-requirements).

**Comment by aiya000** [comment]
I have both Visual Studio 2017 and 2019, with :point_down:
Does this ensure System requirements?

(Screenshots in Japanese, sorry.)
![installed-visual-studio](https://user-images.githubusercontent.com/4897842/58602958-d976f500-82c9-11e9-97a8-069f39cf6f73.png)
![installed-visual-studio-2017-s-workloads](https://user-images.githubusercontent.com/4897842/58602959-d976f500-82c9-11e9-9a62-485110962fc7.png)
![installed-visual-studio-2019-s-workloads](https://user-images.githubusercontent.com/4897842/58602960-da0f8b80-82c9-11e9-8ff1-619a6d504968.png)

**Comment by kmelmon** [comment]
Here's what msdn says about warning C4819:

The file contains a character that cannot be represented in the current code page (number). Save the file in Unicode format to prevent data loss.

C4819 occurs when you compile an ANSI source file on a system using a codepage that can't represent all characters in the file.

There are several ways to resolve C4819. One simple way is to remove the offending character, if you don't need it, for example, if it's in a comment. You can set the system codepage in the Control Panel to one that supports the character set used by your source code. You can use Unicode escape sequences to create characters or strings that use only the basic ANSI character set in your source code. Finally, you can save the file in a Unicode format with a signature, also known as a byte-order mark (BOM).

To save a file in Unicode format, in Visual Studio, choose File > Save As. In the Save File As dialog box, select the drop-down on the Save button and choose Save with Encoding. If you save to the same file name, you may need to confirm that you want to replace the file. In the Advanced Save Options dialog, choose an encoding that can represent all the characters in the file—for example, Unicode (UTF-8 with signature) - Codepage 65001—and then choose OK.

**Comment by kmelmon** [comment]
Evidently there's some character in asyncworkqueue.cpp that is causing issues on a system that is running Japanese as the primary language.

Seems like the easiest fix here is to save the file as UTF-8

**Comment by kmelmon** [comment]
asyncworkqueue.cpp does have a bom so we think this issue is likely a config problem.  Closing.
