### ISSUE TITLE
Request: Running React Native in background on HoloLens

### ISSUE THREAD

**Issue by Rosehart** [microsoft/react-native-windows#2532]
I have a React Native app that I'd like to port to the HoloLens. I would like to have multiple instances open at once. Is it possible to run React Native in the background and have control over the renders it produces? I would like to show these elsewhere as images.

**Comment by harinikmsft** [comment]
Hello @Rosehart -

To clarify your scenario - do you want bitmaps out of the framework that you can put into your hololens UWP app? Or is it something else you are after?

**Comment by Rosehart** [comment]
Exactly! Running it in the background of a UWP app and having access to the renders. This would enable a massive amount of freedom and really speed up development. Getting to use existing UI in this new environment.

**Comment by harinikmsft** [comment]
Thanks for raising this. After discussing with the crew, this appears to be more of a native platform feature request than a react-native-windows feature request. Can you please email me : harinik@microsoft.com? We are taking this conversation forward with the native Windows crews that can help here. Would love to loop you in to get more context on your scenarios.

Closing this issue from this repo.
