### ISSUE TITLE
Support for react-native-navigation by Wix

### ISSUE THREAD

**Issue by MakhouT** [microsoft/react-native-windows#2546]
The 2 most popular navigation libraries for react-native are [react-navigation](https://github.com/react-navigation/react-navigation) and [react-native-navigation.](https://github.com/wix/react-native-navigation/) 
As react-navigation is done on JS side, I am assuming this will be working out of the box.
However [react-native-navigation](https://github.com/wix/react-native-navigation/) is built natively, for obvious performance reasons. Please add support for this library so we can also use native navigation with UWP.

**Comment by harinikmsft** [comment]
Thanks for raising this. We plan to address these as part of Milestone 3 coming up.

**Comment by chrisglein** [comment]
@harinikmsft Given our shift in definitions is this on the short list for M3 or is M4 okay?

**Comment by Yajan** [comment]
I don't think react navigation  work on react native windows  as mentioned in this issue. Please add support to any navigation library

https://github.com/Microsoft/react-native-windows/issues/2033

**Comment by MakhouT** [comment]
@harinikmsft Any update on this? Can we get some more info please?

**Comment by DonovanDeSmedt** [comment]
@harinikmsft We also need to have React Native Navigation by Wix supported on Windows. Any ETA on this topic?

**Comment by erksch** [comment]
Hmm, am I wrong or does that mean there is currently no navigation solution for react-native-windows?

**Comment by MakhouT** [comment]
@erksch I also couldn't find any way to do navigation in rnw currently...

**Comment by stmoy** [comment]
@MakhouT @erksch @DonovanDeSmedt - thank you for your patience, sorry for the radio silence. We're tracking adding Windows support to a bunch of modules. The overall status is here: https://github.com/microsoft/react-native-windows/projects/23

Since we have so many, we're actively prioritizing and implementing. Right now, this module is in our backlog and not on our immediate roadmap. 

That said, we recognize the need for a navigation module and wix/react-native-navigation has come up both internally and externally (#3884) so we're reassessing if this module needs to be reprioritized. I'm following up internally - I'll report back with any updates.

**Comment by SanderNouwynck** [comment]
@stmoy 
Since this module is currently parked on backlog, and not immediate roadmap:
what do you advise as for navigation in rnw?

**Comment by MakhouT** [comment]
@harinikmsft I see the label 'must-have' has been removed, does this mean this won't be supported anymore? 
I think the roadmap isn't really clear of what is going to be supported at the moment...
Are we going for react-native-navigation by Wix? Or are we going for react-navigation?
Also as an other user mentioned, what is currently advised to use navigation in react-native-windows vnext.

**Comment by stmoy** [comment]
Hi all - I just posted a follow up on the react-navigation issue https://github.com/microsoft/react-native-windows/issues/3884#issuecomment-656421845, but following up here as well: we're interested in supporting both react-navigation and react-native-navigation, but we're starting with react-navigation first.

**Comment by chrisglein** [comment]
Closing this module request as not in plan. Not that this module _shouldn't_ receive a Windows implementation, but it makes more sense to track that request on the module's repo rather this repo.
