### ISSUE TITLE
Support react-native-camera on RNW vNext

### ISSUE THREAD

**Issue by harishkrishnav** [microsoft/react-native-windows#2550]
I saw the presentation made at //Build and also some issues from years ago about camera support. Does vnext now have the functionality?

**Comment by harinikmsft** [comment]
Hello -

We are planning to add windows vnext support for the [react-native-cameraroll](https://github.com/react-native-community/react-native-cameraroll) module in Milestone 3. Is this the one you are referring to?

**Comment by harishkrishnav** [comment]
Yes. Thank you for the response.

**Comment by harinikmsft** [comment]
Thanks. Moving this to Milestone 3.

**Comment by chrisglein** [comment]
@harinikmsft is this on our short list of first line extensions for M3 or this okay to do in M4?

**Comment by harinikmsft** [comment]
This can be done in Milestone 4. We will need to first complete the view manager story and then add support this (now community) module.

**Comment by chrisglein** [comment]
Moving back to M3 as we'll want to use this as a test case for native modules.

**Comment by harinikmsft** [comment]
@stmoy - you can use this issue for the validation of custom view manager story.

**Comment by stmoy** [comment]
The original intent of this issue was to support camera. CameraRoll probably isn't the right module for that - we want Camera instead: [react-native-camera](https://github.com/react-native-community/react-native-camera).

Renaming. Please leave a comment if you disagree. @harishkrishnav

**Comment by ddalp** [comment]
React Native Camera native module is checked in.

**Comment by chrisglein** [comment]
Providing link to PR to help people looking back over the process of adding Windows support to existing native modules: https://github.com/react-native-community/react-native-camera/pull/2723
