### ISSUE TITLE
Unauthorized access error

### ISSUE THREAD

**Issue by sumedha-harshit** [microsoft/react-native-windows#2555]
### Environment

1. "react-native": "^0.59.8",
2. "rnpm-plugin-windows": "^0.2.9"
3."react-native-windows": "^0.58.0-rc.0",
4. `node -v11..14.0`:
5. `npm -6.7.0`:

Target Platform:  UAP
Target Platform Version(s):  10.0.14393.0, 
Target Device(s): Emulator
Development Operating System: Windows 10
Visual Studio Version: 15.0.27130.2024
Build Configuration: Debug

I am using react-native-windows for creating windows version of react app and i am trying to upload file and then create base64 data of that file.

I am using `@foqum/react-native-document-picker` to upload file. It's working fine.

And i am using `react-native-fs` to get base64 data of uploaded file.

```
const res = await DocumentPicker.pick({
                    type: [DocumentPicker.types.allFiles],
                });
                console.log(
                    res.uri,
                    res.type, // mime type
                    res.name,
                    res.size
                );
                var url = res.uri;

                RNFS.readFile(url, 'base64')
                    .then((result) => {
                        Alert.alert("", "File Uploaded successfully.");

                    })
                    .catch((err) => {
                        Alert.alert("", "File not uploaded.")
                    });
            } catch (err) {
                if (DocumentPicker.isCancel(err)) {
                    // User cancelled the picker, exit any dialogs or menus and move on
                } else {
                    Alert.alert("", "File not uploaded.")
                    throw err;
                }
            }
```

After File upload `RNFS.readFile` is called, this function call windows function, see attached image but this function not able to read uploaded file.

`using (var file = new FileStream(filepath, FileMode.Open, FileAccess.Read, FileShare.ReadWrite) )`

Got unauthrozied access error.

I have add all required permision in `package.appxmanifest` file.

```
<uap:Capability Name="picturesLibrary" /> 
<uap:Capability Name="videosLibrary" />
<rescap:Capability Name="broadFileSystemAccess" />
```

but still getting Unauthorized access error.

Please see attached image.

![windows](https://user-images.githubusercontent.com/49197416/58784201-7aceb580-8600-11e9-9291-314259dc9a0c.png)

I have also tried `StorageFile` but this line also give same error.
`
StorageFile folder = await StorageFile.GetFileFromPathAsync(filepath);`

can you please help me.

**Comment by rozele** [comment]
Looks like you are writing to `C:\Users\raj\Documents`. Can you try adding `documentsLibrary` to the capabilities in .appxmanifest?
