### ISSUE TITLE
Migrate from CoreDispatcher => DispatcherQueue

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#2557]
Currently, vnext uses CoreDispatcher internally as the implementation for enqueuing work coming across the bridge.

After discussing with Scott Moore,  we learned that CoreDispatcher has limitations when used in a win32 context.  The recommendation for anyone using XAML within islands is to switch to using DispatcherQueue which is win32 message-pump friendly.

We will likely run into issues in Xaml Islands scenarios because we are using CoreDispatcher.  This work item is tracking switching our internal usage of CoreDispatcher over to using DispatcherQueue instead.

**Comment by kmelmon** [comment]
More details:
•	CoreDispatcher was written specifically for UWP and makes a hard assumption that it is driving the message loop for the app.  There are no plans to lift CoreDispatcher.
•	DispatcherQueue is built on top of CoreMessaging, which was designed with win32 scenarios in mind.  It can function correctly when the message loop is owned by the app.  DispatcherQueue is being lifted.
•	CoreMessaging is lower level and offers even more fine grained control over how work is dispatched (has the notion of different priorities).  CoreMessaging is private, but will become public when it gets lifted along with DispatcherQueue.
•	Both CoreDispatcher and DispatcherQueue are WinRT APIs, as such there’s some overhead per dispatched item (transient heap allocations).

One significant learning:  IIUC, CoreDispatcher will have issues when used in a win32 app (Xaml Islands is the canonical scenario).  XAML has already switched to using DispatcherQueue internally and we’re driving to get everyone else to migrate, starting with first party apps.  @Scott Moore I’m unclear on what issues will occur – can you elaborate on this?

For ReactNative’s “batches” being sent over the bridge:
•	We will get better performance if we create our own queue of work items rather than dispatching individual work items, regardless of which type of dispatcher we use.  ReactNative currently has something built-in that signals when a batch is complete, I need to follow-up on exactly how this works, but it seems like we can continue using it as a signal to process a batch.
•	Although there isn’t any significant perf difference between using DispatcherQueue and CoreDispatcher, I think we will likely need to switch any use we have of CoreDispatcher to DispatcherQueue to correctly handle the scenario where ReactNative is being hosted in a XamlIsland.

**Comment by NickGerleman** [comment]
#4102 adding a XAML Islands Win32 playground app is relevant,

**Comment by vmoroz** [comment]
@kmelmon, @chrisglein, @asklar,  I am closing this issue because we do not use the CoreDispatcher for a long time already. About a year ago we switched to using the Windows::System::DispatcherQueue and in #6962 @asklar added a switch to use Micrtosoft::System::DispatcherQueue for WinUI 3.
