### ISSUE TITLE
Touchable* doesn't fire onFocus event

### ISSUE THREAD

**Issue by Thristhart** [microsoft/react-native-windows#2560]
## Repro steps
```tsx
logOnFocus = () => {
  console.log("focused");
};

<TouchableWithoutFeedback accessible={true} onFocus={logOnFocus}>
  <View>
    <Text>Focus this!</Text>
  </View>
</TouchableWithoutFeedback>
```
Focus the `TouchableWithoutFeedback` (e.g. using tab, or controller on Xbox)

## Expected behavior
`logOnFocus` is called and console log appears

## Observed behavior
logOnFocus is never called.

**Comment by Thristhart** [comment]
I was able to work around this issue by adding focus listeners to the View itself, and adding the not-well-documented `acceptsKeyboardFocus`:
```tsx
<TouchableWithoutFeedback>
  <View acceptsKeyboardFocus={true} onFocus={logOnFocus}>
    <Text>Focus this!</Text>
  </View>
</TouchableWithoutFeedback>
```

**Comment by harinikmsft** [comment]
The primary issue here is being tracked through #2107. Closing this to track through that issue.
