### ISSUE TITLE
Bring accessibility up to par with the RN 60 API surface

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#2566]
This epic tracks all of the work necessary in RNW vNext to meet the accessibility APIs defined for RN 60 here: https://facebook.github.io/react-native/docs/accessibility

**Comment by chrisglein** [comment]
I believe we're tracking everything here via this project now: https://github.com/microsoft/react-native-windows/projects/21
Closing out this issue. @jonthysell speak up if I missed something.
