### ISSUE TITLE
Implement 'checked' and 'unchecked' accessibilityState

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#2574]
Work:
- [x] Pipe through new state values into RNW
- [x] Consume state values in DynamicAutomationPeer
- [ ] Update RN fork to recognize new values so TS compiles.

**Comment by jonthysell** [comment]
This is done in RNW, but we need to update the RN fork so that TS doesn't complain with the new values.

**Comment by jonthysell** [comment]
PR in the RN fork: https://github.com/microsoft/react-native/pull/99

**Comment by kmelmon** [comment]
@jonthysell can this issue be closed now?

**Comment by harinikmsft** [comment]
Closing this since the last item here has been worked around by Calendar app (typescript support). We can add support for this if it is a major adoption blocker for other apps.
