### ISSUE TITLE
Implement 'checkbox' accessibilityRole

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#2576]
Work:
- [x] Pipe through new role values into RNW
- [x] Consume role values in DynamicAutomationPeer
- [ ] Update RN fork to recognize new values so TS compiles.

**Comment by jonthysell** [comment]
This is done in RNW, but we need to update the RN fork so that TS doesn't complain with the new values.

**Comment by jonthysell** [comment]
PR in the RN fork: https://github.com/microsoft/react-native/pull/99

**Comment by harinikmsft** [comment]
Closing this since the last item here has been worked around by Calendar app (typescript support). We can add support for this if it is a major adoption blocker for other apps.
