### ISSUE TITLE
Implement 'list' and 'listitem' accessibilityRole extension

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#2578]
This includes both adding the values and setting the appropriate XAML UIA properties.

Work:
- [x] Pipe through new role values into RNW
- [x] Consume role values in DynamicAutomationPeer
- [ ] Update RN fork to recognize new values so TS compiles.

**Comment by harinikmsft** [comment]
The role names - `list` and `listitem` - do match the corresponding ARIA equivalents ([ARIA list role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/List_role), [ARIA listitem role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Listitem_role)). 

I will start a proposal for this shortly.

**Comment by harinikmsft** [comment]
Spec for this is being staged [here](https://github.com/ReactWindows/discussions-and-proposals/blob/harinik-accessibility/proposals/0000-accessibilityapis-lists.md)

**Comment by kmelmon** [comment]
Work on this is in progress, I'm hopeful it will be finished before 7/12, bringing this back to Milestone 2.

**Comment by jonthysell** [comment]
PR to update the RN fork here: https://github.com/microsoft/react-native/pull/106
