### ISSUE TITLE
Implement 'x of n' list item support within native views

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#2579]
This involves making sure the native views marked as list items announce the correct 'x of n' counts by narrator

**Comment by harinikmsft** [comment]
The UIA properties that describe these for accessibility tools are [PositionInSet](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Automation.AutomationProperties.PositionInSetProperty) and [SizeOfSet](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Automation.AutomationProperties.SizeOfSetProperty) 

The corresponding ARIA properties are [posInSet](https://www.w3.org/TR/wai-aria-1.1/#aria-posinset) and [setSize](https://www.w3.org/TR/wai-aria-1.1/#aria-setsize)

I will start a proposal shortly to spec the APIs for these we want to bring to RN - for the names, we will want to align with ARIA names.

**Comment by harinikmsft** [comment]
Spec for this is being staged [here](https://github.com/ReactWindows/discussions-and-proposals/blob/harinik-accessibility/proposals/0000-accessibilityapis-lists.md)

**Comment by kmelmon** [comment]
Work on this is in progress, I'm hopeful it will be finished before 7/12, bringing this back to Milestone 2.

**Comment by jonthysell** [comment]
PR to update the RN fork here: https://github.com/microsoft/react-native/pull/106
