### ISSUE TITLE
Reduce chattiness across the bridge when loading images

### ISSUE THREAD

**Issue by micahl** [microsoft/react-native-windows#2588]
While discussing a perf trace we noticed that there's lots of chatter across the bridge when looking at images downloaded and opened.  @ahimberg suggested its a bug we ought to be able to fix.  It should help startup for media-heavy apps that show lots of images.

**Comment by stecrain** [comment]
This is fixed with https://github.com/microsoft/react-native-windows/pull/2648 what I thought was chattiness was really just the ui thread waiting for the image to download.
