### ISSUE TITLE
[Performance] vnext should use fast-path text for simple <Text>

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#2620]
This was discovered by Xbox folks when measuring perf.  The current implementation always creates a Run for the text property of <Text> and inserts it into the TextBlock's InlineCollection.  This disables XAML fast-path text so we're always getting slow-path for all Text in RNW.

This bug is tracking optimizing.  We should be able to change this code to use the TextBlock.Text property instead of inserting a Run into the InlineCollection.

**Comment by decrowle** [comment]
Already implemented.
