### ISSUE TITLE
Implement View.focus() and View.blur()

### ISSUE THREAD

**Issue by harinikmsft** [microsoft/react-native-windows#2627]
It appears that [focus()](https://facebook.github.io/react-native/docs/direct-manipulation#focus) and [blur()](https://facebook.github.io/react-native/docs/direct-manipulation#blur) are not working when used with View in react-native-windows today. We should wire it up the same way TextInput works and ensure these methods set focus on the View when invoked.

**Comment by kmelmon** [comment]
Pulling this into Milestone 2 and assigned to CanHua
