### ISSUE TITLE
Image defaultSource

### ISSUE THREAD

**Issue by marlenecota** [microsoft/react-native-windows#2632]
Split out from #2111
https://facebook.github.io/react-native/docs/image#defaultsource

_A static image to display while loading the image source._
Not directly supported by Image. Would need to manually load/display this, similar to loadingIndicatorSource (#2633).

**Comment by chrisglein** [comment]
Not something we plan to address on the Paper renderer as we move towards Fabric.
Fabric API completion for `Image` tracked here: https://github.com/microsoft/react-native-windows/issues/11144 (and is completed for Fabric)
