### ISSUE TITLE
Image loadingIndicatorSource

### ISSUE THREAD

**Issue by marlenecota** [microsoft/react-native-windows#2633]
Split out from #2111
https://facebook.github.io/react-native/docs/image#loadingindicatorsource

_Similarly to source, this property represents the resource used to render the loading indicator for the image, displayed until image is ready to be displayed, typically after when it got downloaded from network._

Not directly supported by Image. Would need to manually load/display the loading indicator image and switch to the real image when it's ready. There is likely open-source code for this that could be borrowed.

**Comment by chrisglein** [comment]
Not something we plan to address on the Paper renderer as we move towards Fabric.
Fabric API completion for `Image` tracked here: https://github.com/microsoft/react-native-windows/issues/11144 (and is completed for Fabric)
