### ISSUE TITLE
Image progressiveRenderingEnabled

### ISSUE THREAD

**Issue by marlenecota** [microsoft/react-native-windows#2635]
Split out from #2111
https://facebook.github.io/react-native/docs/image#progressiverenderingenabled

_Typically Android only. When true, enables progressive jpeg streaming. [See here](https://frescolib.org/docs/progressive-jpegs.html)._
Not supported by XAML. Would need to do the decoding ourselves and render ourselves.

When true, enables progressive jpeg streaming. https://frescolib.org/docs/progressive-jpegs.html

**Comment by jrdnlx** [comment]
hey can i try this, can you provide more detail on what to do?

**Comment by chrisglein** [comment]
Not something we plan to address on the Paper renderer as we move towards Fabric.
Fabric API completion for `Image` tracked here: https://github.com/microsoft/react-native-windows/issues/11144 (And is completed for Fabric)
