### ISSUE TITLE
Layout is run on XAML controls that haven't expanded their control templates

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#2642]
This is a follow-up on:
https://github.com/microsoft/react-native-windows/pull/2584

The flow of operations for batch processing and running layout goes like this:
1)	Process all the commands from the bridge
2)	Run yoga layout
3)	Push results of yoga into the XAML tree
4)	XAML ticks and runs its own layout pass/render walk
When a new tree is being created, step 1 is creating all the views and adding the views to the tree, which in turn creates/adds the backing XAML elements to the XAML tree.  However, not all of the backing XAML elements will be “live” yet.  The reason for this is that controls don’t expand their control templates until the first time layout is run on them, which leaves children un-parented during that time.  ScrollViewer is an example of this.  When we set ScrollViewer.Content, ScrollViewer just caches Content until it expands its template, which means ScrollViewer.Content is not live yet, and neither is anything under it.  I believe there are other controls that work this way as well.  

Another aspect of this is that the control template applies the style for the control, which can have a huge effect on what’s in the tree.  ComboBox is an example of this.  While ComboBox is not live, it will use its default style, which is to put all the ComboBox items directly under the ComboBox inside a StackPanel.  This isn’t the final tree – when the style is applied, the StackPanel goes away and the ComboBox items go under a collapsed Popup.

You are probably beginning to see the problem this creates.  When we run yoga layout, even though we’ve called all the correct XAML APIs to build the XAML tree, the tree isn’t completely built yet because we haven’t let XAML layout run on it yet.  We are selectively calling Measure only on the views that perform self-layout, but such a view might not be in the live tree yet because it could be underneath a control like a ScrollViewer that itself doesn’t self measure.  In this scenario we’ll measure the ComboBox before it’s had its style applied, and we end up measuring the temporary StackPanel, and come up with a desired size that includes all the ComboBoxItems.  I confirmed this in the debugger.

This also explains why when you resize the window the issue goes away – by the time we run layout again, everything is now live and the ComboBox has expanded its control template, the ComboBox items are now under a collapsed Popup.

This is a general problem for all controls, I’m actually kind of surprised we haven’t seen more issues like this.  The simple fix for this is to call UpdateLayout on the root Xaml element just before we run yoga layout, but of course that will cause a perf penalty.  Open to other ideas.  Longer term, I think we should implement flexbox layout directly in XAML.  This would be better for perf even if we didn’t have this control template issue as we’re currently running layout again after.  It would also accrue value to XAML.

**Comment by micahl** [comment]
https://github.com/microsoft/microsoft-ui-xaml/issues/694

**Comment by decrowle** [comment]
Closed with PR #2859
