### ISSUE TITLE
Remove nuget.exe from NPM package

### ISSUE THREAD

**Issue by acoates-ms** [microsoft/react-native-windows#2645]
The vnext NPM package is 6.2MB.  4.3MB of that is a copy of nuget.exe in the local-cli.  There has to be a better way to use nuget than us having to ship another copy of it.

**Comment by marlenecota** [comment]
Looks like we can use msbuild -t:restore if we migrate the solutions from packages.config to PackageReference.

https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#restore-target
https://docs.microsoft.com/en-us/nuget/reference/migrate-packages-config-to-package-reference

**Comment by marlenecota** [comment]
Maybe not... C++ projects might not be supported yet. I've reached out to the nuget team to verify.

> Looks like we can use msbuild -t:restore if we migrate the solutions from packages.config to PackageReference.
> 
> https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#restore-target
> https://docs.microsoft.com/en-us/nuget/reference/migrate-packages-config-to-package-reference

**Comment by nkolev92** [comment]
@marlenecota discussed this concern offline with me. 

NuGet PackageReference is integrated with MSBuild and has a target that allows you to restore. 
Unfortunately this is not supported for C++ yet. 
PackageReference was a significant undertaking, and it required changes by the projects themselves. 
Specifically C++ has not made those changes. The issue tracking this ask if the following: 
https://developercommunity.visualstudio.com/content/idea/351636/use-packagereference-in-vcxproj.html

In the meantime, you cannot move away from nuget.exe . 

If possible though, I'd recommend moving your managed projects to PackageReference. 
The package install/uninstall/update story is a lot more efficient there.

**Comment by marlenecota** [comment]
#2801
