### ISSUE TITLE
How to refresh from red screen?

### ISSUE THREAD

**Issue by zzyyzz1992** [microsoft/react-native-windows#2668]
When debugging iOS and Android, sometimes the nodejs server get error and we must restart the server, but restarting the UWP app is very slow. Is there a way to refresh the UWP app just like debugging iOS and Android, for example 'Press F5 to Reload'.
This is 'the red screen' what I mean:
![image](https://user-images.githubusercontent.com/3894825/60037618-9ea78780-96e4-11e9-8cf9-0318d26bbc45.png)

**Comment by kmelmon** [comment]
Thanks for reporting this.  We'll investigate as time warrants.

**Comment by kmelmon** [comment]
RedBox now has a Reload button in master.
