### ISSUE TITLE
Add support for more fields to IKeyboardEvent

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#2672]
In our initial implementation of keyboard events, we implemented these fields:

export interface INativeKeyboardEvent {
  altKey: boolean;
  ctrlKey: boolean;
  metaKey: boolean;
  shiftKey: boolean;
  key: string;
  eventPhase: EventPhase;
}

This isn't a complete list.  See:
https://www.w3.org/TR/uievents/#interface-keyboardevent

We need to go over this list and decide which of the remaining fields we should add support for.

**Comment by kmelmon** [comment]
@harinikmsft can you go through the remaining fields and figure out which ones we should add to our event?

**Comment by harinikmsft** [comment]
We are adding `repeat` to this list with #5513 and at this point, this is considered enough for the scenarios targeted. Closing this for now, please reopen if there are specific fields from the w3 spec that you would need for a scenario.
