### ISSUE TITLE
TypeError: CameraManager.takePicture is not a function: on Windows UWP

### ISSUE THREAD

**Issue by SunilPandey-** [microsoft/react-native-windows#2674]
### Environment

1. `react-native -v`: 0.57.0
2. `npm ls rnpm-plugin-windows`: 0.2.9
3. `npm ls react-native-windows`:0.57.1
4. `node -v`: v10.16.0
5. `npm -v`: 6.9.0
6. `yarn --version`:

Then, specify:

- Target Platform:
UWP

- Target Platform Version(s):
10.0.14393

- Target Device(s):
Local Machine desktop

- Development Operating System:
Windows

- Visual Studio Version:
VS-2017

- Build Configuration:
Debug
### Steps to Reproduce

(Write your steps here:)

1.Below is code. 

Below is code and getting error for windows app development
TypeError: CameraManager.takePicture is not a function

RN: 0.57
App development for windows platform

class BadInstagramCloneApp extends Component {
render() {
return (

<RNCamera
ref={ref => {
this.camera = ref;
}}
style = {styles.preview}
type={RNCamera.Constants.Type.back}
flashMode={RNCamera.Constants.FlashMode.on}
permissionDialogTitle={'Permission to use camera'}
permissionDialogMessage={'We need your permission to use your camera phone'}
/>
<View style={{flex: 0, flexDirection: 'row', justifyContent: 'center',}}>

<Text style={{fontSize: 14}}> SNAP 

);
}

takePicture = async function() {
if (this.camera) {
const options = { quality: 0.5, base64: true };
const data = await this.camera.takePictureAsync(options)
console.log(data.uri);
}
};
}

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by rozele** [comment]
Thanks for filing @SunilPandey - seems like this should be filed on https://github.com/react-native-community/react-native-camera. Unfortunately, I'm not aware of any active maintainers for the react-native-camera module, so it's likely that the windows native module is quite out of date.

**Comment by SunilPandey-** [comment]
@rozele  I need to open camera, for taking picture and video. when i click on my pic button it should open for camera, when i click on my video button it should open for video, what would you suggest for this. any other library or windows support this.
