### ISSUE TITLE
Enable focus()/blur() on Checkbox, Picker and possible other controls.

### ISSUE THREAD

**Issue by licanhua** [microsoft/react-native-windows#2683]
Checkbox and Picker are Composite components, and forwardref is a way to [direct-manipulation](https://facebook.github.io/react-native/docs/direct-manipulation#docsNav) and set focus.

Their android implementation is already use forwardref and we need to follow the same way.

**Comment by kmelmon** [comment]
@harinikmsft can you figure out our overall story for what controls can receive focus?  This one is calling out Checkbox/Picker as good examples, there will likely be more.

**Comment by kmelmon** [comment]
@licanhua I see you've added forwardref support to the keyboard events.  Can we close this issue?

**Comment by licanhua** [comment]
> @licanhua I see you've added forwardref support to the keyboard events.  Can we close this issue?

They are totally different. RCTCheckBox is the native component, then Checkbox is a wrapper on RCTCheckBox, then supportKeyboard and others are another wrapper on CheckBox.
CheckBox doesn't support forwardref, so even outer pass a ref, it's been ignored by CheckBox.
CheckBox/Picker is just two examples I know, maybe other controls have the same problem.

**Comment by kmelmon** [comment]
@licanhua thanks for clarifying.  I changed the wording on the issue slightly to capture the general issue, and it looks like forwardref simply won't work anyway.

**Comment by chrisglein** [comment]
Related #5589

**Comment by harinikmsft** [comment]
View and Pressable are the only core components that need focus()/blur() at this time. Since Checkbox, Picker and others have been moved out of core, we don't need to track this here any more.
