### ISSUE TITLE
Could wpf support modal ?

### ISSUE THREAD

**Issue by peterfei** [microsoft/react-native-windows#2686]
### Environment
```
react-native -v: 0.57
npm ls rnpm-plugin-windows: 0.2.9
npm ls react-native-windows: (empty)
node -v: 8.11.3
npm -v: 5.6.0
yarn --version: 1.7.0
```
Seems modal supported only by uwp which run in `react-native windows` , could wpf also support modal  for `ReactNative.Net46`?

**Comment by rozele** [comment]
We'll happily accept PRs, most modules for WPF translate fairly seamlessly.

**Comment by peterfei** [comment]
@rozele  Thanks a million！
