### ISSUE TITLE
Unable to activate WinRT types in ReactUWP created using buildcppwinrt.cmd

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#2712]
Right now, we are not consuming cppwinrt properly in the ReactUWP project. We are running the tools manually to generate the files based on the idls (using a buildcppwinrt.cmd script), but those generated classes aren't part of the DLL's WINRT_GetActivationFactory, and so can't be RoActivated.

This means for a type winrt::react::uwp::Example, you'' get a runtime error if you try

`auto example = winrt::react::uwp::Example()`

Instead, (and only ReactUWP can do this) you have to call:

`auto example = winrt::make<winrt::react::uwp::implementation::Example>()`

This also means you can't access static methods/properties on those types, as it requires a runtime activation.

This bug will be fixed when we redo all of the cppwinrt code, but in the meantime I'm using this issue number to track the places in the code where we're working around this limitation by calling the implementation class directly, instead of the projected class.

**Comment by licanhua** [comment]
#3596 fixed part of them

**Comment by kmelmon** [comment]
@jonthysell can you update this issue to reflect what is remaining on this issue after CanHua's recent changes?

**Comment by jonthysell** [comment]
The remaining issues are in our ABI implementation of Instance and ReactControl, and our hard-coded `modules.g.cpp`. All of which will go away when we finally do #3564.

**Comment by jonthysell** [comment]
This was fixed in #3809.
