### ISSUE TITLE
System.Runtime.interopServices.COMException 'An async operation was not properly started. Only a single ContentDialog can be open at a time

### ISSUE THREAD

**Issue by SunilPandey-** [microsoft/react-native-windows#2718]
react-native -v: 0.57.0
npm ls rnpm-plugin-windows: 0.2.9
npm ls react-native-windows: 0.57.1
node -v: v10.16.0
npm -v: 6.9.0

Issue Details:

I have one Modal from 'react-native'; and inside that i have many fields like, inputText, ModalDropDown.
Whenever i am clicking on dropdown i am getting error "System.Runtime.interopServices.COMException 'An async operation was not properly started. Only a single ContentDialog can be open at a time".

While if drop down is inside normal View then it is working fine.

**Comment by rozele** [comment]
Can you send pointers to the components you are using for Modal and ModalDropDown? Seems like both are implemented with a ContentDialog, of which only can be displayed at a time, so you may need to look at other options for implementing the ModalDropDown functionality...

**Comment by SunilPandey-** [comment]
> Can you send pointers to the components you are using for Modal and ModalDropDown? Seems like both are implemented with a ContentDialog, of which only can be displayed at a time, so you may need to look at other options for implementing the ModalDropDown functionality...

This is how component is renderd
<Modal>
<KeyboardAwareScrollView> //from react-native-keyboard-aware-scroll-view
<View>
<ModalDropdown>
</ModalDropdown>
</View>
</KeyboardAwareScrollView>
<Modal>

Is this what you asked or any other information ? @rozele
