### ISSUE TITLE
runWindows deploy is too fragile and specific. Can't find path. 

### ISSUE THREAD

**Issue by namrog84** [microsoft/react-native-windows#2722]
Part 1: The path is too fragile

Currently C# and C++ UWP apps build slightly different paths.  And the current mechanism in deployToWindows is quite fragile and too specific

```return glob.sync(`windows/*/AppPackages/*_${options.arch}_${configuration}_*`)[0];```
https://github.com/microsoft/react-native-windows/blob/48a23b5181c7e91c1ec243c9556a6e81351a8927/vnext/local-cli/runWindows/utils/deploy.js#L21

Should be changed to this instead ```return glob.sync(`windows/**/AppPackages/*_${options.arch}_${configuration}_*`)[0];``` 
Note the * to ** after windows/
So that it can better capture different paths. In my particular case the default path is
`\windows\target\x64\Debug\UwpAppName\UwpAppName\AppPackages\UwpAppName_1.0.0.0_x64_Debug_Test`

part 2.
Also looking for the AppxManifest.xml 
https://github.com/microsoft/react-native-windows/blob/48a23b5181c7e91c1ec243c9556a6e81351a8927/vnext/local-cli/runWindows/utils/deploy.js#L34

In the C++ UWP this generates to
``` `windows/target/${options.arch}/${configuration}/appName/AppName/AppxManifest.xml`) ```
So this would work.  ``` const appxPath = glob.sync(path.join(options.root, `windows/*/${options.arch}/${configuration}/**/AppxManifest.xml`))[0]; ```

part 3.
Although it does properly rely on Add-AppDevPackage instead of *.appx now. It then falls back onto a WindowsStoreAppUtils.ps1
https://github.com/microsoft/react-native-windows/blob/48a23b5181c7e91c1ec243c9556a6e81351a8927/vnext/local-cli/runWindows/utils/WindowsStoreAppUtils.ps1#L94

Which is out dated and only supports appx and appxbundle. 
But comparing it against the Add-AppDevPackage which supports appx, msix (the new format), appxbundle, msixbundle, among others. 

To be honest, a lot of the functionality of WindowsStoreAppUtils, shouldn't even be needed anymore since Add-AppDevPackage should be handling most of the stuff here now. 

At the time of this post, I was still using "react-native-windows": "0.59.0-vnext.32", but it doesn't appear to be resolved as of July 2, 2019.

**Comment by asklar** [comment]
CC @svetbonev @srdjanjovcic
