### ISSUE TITLE
Add tests for ChakraCoreRuntime specific behaviors.

### ISSUE THREAD

**Issue by hansenyy** [microsoft/react-native-windows#2729]
# Proposal: Add tests for ChakraCoreRuntime specific behaviors.

## Summary
We need tests for ChakraCoreRuntime specific behaviors such as ScriptStore and promises.

**Comment by NickGerleman** [comment]
Closing this, since I can't see us investing any more effort into the Chakra JSI stack. Feel free to reopen if you disagree.
