### ISSUE TITLE
Share Code Between Test Projects

### ISSUE THREAD

**Issue by hansenyy** [microsoft/react-native-windows#2730]
# Proposal: Add a vcxitem for code shared between test projects.

## Summary
For example Desktop.IntegrationTests/TestMessageQueueThread.h is used in both Desktop.IntegrationTests and JSI.Desktop.UnitTests. We should create a shared vcxitem for files like this.

**Comment by JunielKatarn** [comment]
Why VCXITEMS and not VCXPROJ of type StaticLib?

**Comment by hansenyy** [comment]
Actually now that I think about it, static lib might work better. In the end, we just need some way to share code between different test projects.

**Comment by NickGerleman** [comment]
Is this still relevant after test infra changes?
