### ISSUE TITLE
Will Azure AD be supported?

### ISSUE THREAD

**Issue by xuanyichen5096** [microsoft/react-native-windows#2731]
Hi

Will Azure AD authentication be support in the future? If yes, please provide a general date for it.

Thanks!

Regards
Xuanyi

**Comment by harinikmsft** [comment]
Can you clarify a scenario where you might use this? 

In general, this feels outside the scope of the react-native-windows repo and would be something that could be tackled as a separate community module.

**Comment by xuanyichen5096** [comment]
Hello Harini!

I did a lot of search online to see if there's an an equivalent for react-native windows for the following library:
   - https://github.com/AzureAD/microsoft-authentication-library-for-js
   - https://github.com/AzureAD/microsoft-authentication-library-for-js

I couldn't find it. It may sound like a separate community module but .Net probably has a library to do the above. As this project is building on Windows and might leverage on some .Net components, so I am checking if there's possibility that it will be supported in this react-native-windows project or there's a plan to have a separate module.

Sorry if i put the question at the wrong place! I don't where else is better to post this question...

Thanks for your attention to this matter!

Regards
Xuanyi

**Comment by xuanyichen5096** [comment]
hello, any news? :)

**Comment by xuanyichen5096** [comment]
Hello Harini!

The organization, which I am working for, uses ADFS for their application authentication. This is the scenario in which I will need to utilize Azure AD Authentication.

Let me know if there's any source of information, which i can go to directly... :)

Regards
Xuanyi

**Comment by micahl** [comment]
Hi @xuanyichen5096, we recognize how important it is for RN apps to be able to leverage platform capabilities via modules.  Enabling developers to author modules that work with the vnext is one of our current focus areas.  The set of modules in the react-native-windows project that we would maintain will be limited.  I'd recommend making sure you're request is logged with the team that owns Azure AD.  From their UserVoice page it looks like there's [already a few people that have asked for a RN support](https://feedback.azure.com/forums/169401-azure-active-directory?query=react).  

Fwiw, the Microsoft Identity Platform (a.k.a MSAL or Azure AD 2.0) provides a number of supported libraries including a C# version that is intended to cover desktop ([link](https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-v2-libraries)).  According to their docs the identify platform supports industry standard OAuth 2.0 and OpenID Connect 1.0 protocols.  So, I'd expect that any open source libraries which support those protocols could also be used.  There's also a non-Microsoft maintained module for React Native with support for iOS/Android ([link](https://github.com/FormidableLabs/react-native-app-auth)).  Once we unblock native modules then theoretically someone could create an implementation for Windows or contribute to an existing module.

**Comment by xuanyichen5096** [comment]
Hi micahl

Thank you for the information.

I guess the support for RN will lie with the Azure AD team. I will check up their page.

All the best for the vnext project!

Regards
Xuanyi

**Comment by stecrain** [comment]
@xuanyichen5096
This package from the community may be worth a shot. 

https://www.npmjs.com/package/react-native-azure-ad

I tried to use this for a hackathon project with react native for Android, it seemed to work reasonably well.
