### ISSUE TITLE
Conflict on macos packages since /lib change (building vnext uwp)

### ISSUE THREAD

**Issue by namrog84** [microsoft/react-native-windows#2740]
I am running react-native run-windows --arch=x64 for a vnext uwp cpp project.
on: 
* "react-native-windows": "0.59.0-vnext.75",
* "react-native": "https://github.com/microsoft/react-native/archive/v0.59.0-microsoft.12.tar.gz",

And I see 

Loading dependency graph...(node:7056) UnhandledPromiseRejectionWarning: Error: jest-haste-map: Haste module naming collision:
  Duplicate module name: SafeAreaView
  Paths: <snipped>\node_modules\react-native\Libraries\Components\SafeAreaView\SafeAreaView.macos.js collides with <snipped>\node_modules\react-native\Libraries\Components\SafeAreaView\SafeAreaView.js

Also on:
"collides with <snipped>\node_modules\react-native\Libraries\react-native\react-native-implementation.js collides with <snipped>\node_modules\react-native\Libraries\react-native\react-native-implementation.macos.js"

Also on: 
Paths: <snipped>\node_modules\react-native-windows\Libraries\Components\CheckBox\CheckBox.js collides with <snipped>\node_modules\react-native\Libraries\Components\CheckBox\CheckBox.macos.js

These are the only ones I am currently seeing.

**Comment by harinikmsft** [comment]
@acoates-ms - can you take a look at this to see if your change updating from lib to libraries has impacted this scenario?

**Comment by acoates-ms** [comment]
It looks like react-native init with the vnext template is broken currently, so I can't try it on a brand new app.

But this looks like either you have bad data in your haste cache (try deleting %temp%\haste*).
Or your rn cli config isn't adding macos as a platform for your haste map.  The default run-windows command should currently be using the rn-cli config in react-native-windows.  But maybe its not getting used due to some changes in your repo?

**Comment by acoates-ms** [comment]
The issue appears to be when using the `microsoft/react-native` fork, no-one is adding `macos` to the list of haste platforms.

This issue should go away once we update to RN 0.60, and the hastemap goes away.  Until then, you can add the following to your metro.config.js:

```
 resolver: {
   platforms: ['ios', 'android', 'windows', 'macos']
}
```
