### ISSUE TITLE
Use explicit captures rather than [=]

### ISSUE THREAD

**Issue by licanhua** [microsoft/react-native-windows#2748]
We have lot of [=] in callbacks, it's better to use explicit captures.
see [F.54: If you capture this, capture all variables explicitly (no default capture)](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rf-this-capture) 
```
checkbox.Checked(winrt::auto_revoke, [=](auto &&, auto &&) {
        auto instance = wkinstance.lock();
        if (!m_updating && instance != nullptr)
          OnCheckedChanged(*instance, m_tag, true);
```

**Comment by chrisglein** [comment]
It seems unlikely action is going to be taken as a result of this issue. Will need to enforce more strongly in code review and clean up bit by bit opportunistically.
