### ISSUE TITLE
Unrecognized Command "windows" 

### ISSUE THREAD

**Issue by destinyb-realityi** [microsoft/react-native-windows#2755]
I have the latest react native installed on my computer and followed [these ](https://github.com/microsoft/react-native-windows/blob/master/current/docs/GettingStarted.md) instructions to the letter, but I'm still getting the below error: 

error Unrecognized command "windows".
info Run "react-native --help" to see a list of all available commands.

**Comment by harinikmsft** [comment]
Hello - 

Can you please check if the error still occurs if you try the following:

1. Please use the version number like `react-native init <project name> --version 0.58.0`. Without the version number, you are probably picking up 0.60 which is not supported yet by react-native-windows current. 

2. cd into your react-native project before running `react-native windows`

3. Ensure you have installed the plugin for windows: 
```
npm install --save-dev rnpm-plugin-windows
```

**Comment by manojk-vs** [comment]
Thanks @harinikmsft, its working

**Comment by destinyb-realityi** [comment]
@hansenyy It's no longer saying command not found, but I'm getting a completely different error:

'C:\Users\<user>\Desktop\Development\React-Native\R' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.
(node:21220) UnhandledPromiseRejectionWarning: Error: Command failed: C:\Users\<user>\Desktop\Development\React-Native\R&D\myapp\node_modules\react-native\local-cli\setup_env.bat
'C:\Users\<user>\Desktop\Development\React-Native\R' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.

    at checkExecSyncError (child_process.js:602:13)
    at Object.execFileSync (child_process.js:622:13)
    at Object.run (C:\Users\<user>\Desktop\Development\React-Native\R&D\myapp\node_modules\react-native\local-cli\cliEntry.js:146:16)
    at <anonymous>
(node:21220) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21220) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by hansenyy** [comment]
@harinikmsft to make sure she gets notified.

**Comment by J4s0nDRevs** [comment]
@harinikmsft I already have 0.60 and it is not letting me use 0.58
![image](https://user-images.githubusercontent.com/23364645/61264420-21d96c00-a7bf-11e9-8fc5-674df3720c6a.png)

**Comment by J4s0nDRevs** [comment]
@harinikmsft I used 0.58 it runs but have the following output

[Reactnative log.txt](https://github.com/microsoft/react-native-windows/files/3395686/Reactnative.log.txt)

**Comment by harinikmsft** [comment]
@rozele - can you take a look?

**Comment by destinyb-realityi** [comment]
To fix the following issue: 

Make sure there is no `&` symbol in your project path. 
Make sure your PC is in `developer mode` 
Make sure you have all the UWP SDKs installed.

**Comment by gcox** [comment]
@J4s0nDRevs FYI, I got that error as well. Running `npm install` then `react-native windows` one more time fixed it for me.
