### ISSUE TITLE
Border color changes in transfer properties causes RNTester to crash

### ISSUE THREAD

**Issue by t-wihatz** [microsoft/react-native-windows#2758]
I was trying to make a test that changes the backing XAML element of a component in order to test transfer properties. I was trying to do this by changing the backing element to a border, so I had 2 styles; one with a border that has corner radius, and one that didn't have any border, and I had a view that alternated between the two styles.

When I was going from not having a border to having a border with color and radius, it worked fine. But when I went back to the style without a border, it caused RNTester to crash.

![ExceptionScreenshot](https://user-images.githubusercontent.com/52328511/61068676-6b8d1580-a3bf-11e9-884f-503ebebc6d6c.PNG)

Here is the test that I had, if you paste this into 
react-native-windows\vnext\node_modules\react-native\RNTester\js\ViewExample.js
and change the border twice you should get the exception.

{
   title: 'Direction Transfer Properties',
    render() {

    const styles = StyleSheet.create({
      withBorder: {
        direction: 'rtl',
        borderColor: '#ff1e00', borderWidth: 5, borderRadius: 5,
      },
      withoutBorder: {
        direction: 'rtl',
      },
    });

    class FlowDirectionChange extends React.Component<Props, State> {
      state = {
       useBorder : false,
      };

      render() {

        const currentStyle = this.state.useBorder ? styles.withBorder : styles.withoutBorder;
        return (
          <View style={{flex: 1}}>
            <View style={ currentStyle }>
              <Text style={{ fontSize: 11 }}>This text should remain on the right after changing the radius</Text>
            </View>
            <Button onPress={this.handleClick} title="Change Border Radius" />
          </View>
        );
      }

       handleClick = () => {
         this.setState({ useBorder: !this.state.useBorder });
       };
      }

      return <FlowDirectionChange/>
    },
  },

**Comment by randy-flynn** [comment]
https://github.com/microsoft/react-native-windows/pull/3040

**Comment by randy-flynn** [comment]
https://github.com/microsoft/react-native-windows/pull/3040
