### ISSUE TITLE
Adding border radius to a style that already has border causes RNTester crash

### ISSUE THREAD

**Issue by t-wihatz** [microsoft/react-native-windows#2759]
Once again I was working a test that changes the backing XAML element of a component in order to test transfer properties. I made a view and was alternating it between 2 styles; one with a border that had corner radius, and one that had a border but no corner radius.

It starts out with a border, but when you try to change the style to the one with corner radius, RNTester crashes.
![ExceptionScreenshot2](https://user-images.githubusercontent.com/52328511/61071090-0fc58b00-a3c5-11e9-889a-03f98e884227.PNG)

I have pasted in the test I was using below, you can put it into 
react-native-windows\vnext\node_modules\react-native\RNTester\js\ViewExample.js
and try changing the style to get the crash.

 {
   title: 'Direction Transfer Properties',
    render() {

    const styles = StyleSheet.create({
      withBorder: {
        direction: 'rtl',
        borderColor: '#ff1e00', borderWidth: 5, borderRadius: 5,
      },
      withoutBorder: {
        direction: 'rtl', borderColor: '#ff1e00', borderWidth: 5,
      },
    });

    class FlowDirectionChange extends React.Component<Props, State> {
      state = {
       useBorder : false,
      };

      render() {

        const currentStyle = this.state.useBorder ? styles.withBorder : styles.withoutBorder;
        return (
          <View style={{flex: 1}}>
            <View style={ currentStyle }>
              <Text style={{ fontSize: 11 }}>This text should remain on the right after changing the radius</Text>
            </View>
            <Button onPress={this.handleClick} title="Change Border Radius" />
          </View>
        );
      }

       handleClick = () => {
         this.setState({ useBorder: !this.state.useBorder });
       };
      }

      return <FlowDirectionChange/>
    },
  },

**Comment by ahimberg** [comment]
We ran into this too, @randy-flynn has been looking at fixing up the area.  Randy & @licanhua should sync up

**Comment by randy-flynn** [comment]
https://github.com/microsoft/react-native-windows/pull/3040
