### ISSUE TITLE
dummy issue for images

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#2761]
Do not triage this issue, it simply contains images used in the wiki...

![image](https://user-images.githubusercontent.com/33470154/61091349-b413f580-a3f6-11e9-90a1-e399c19e29cf.png)
![image](https://user-images.githubusercontent.com/33470154/61091366-c3933e80-a3f6-11e9-993b-c6a478d66b37.png)
![image](https://user-images.githubusercontent.com/33470154/61091374-c8f08900-a3f6-11e9-8a46-b084dd63dd1b.png)

**Comment by harinikmsft** [comment]
Closing this dummy issue.
