### ISSUE TITLE
Changing border radius causes issue with the top and left margins transfer

### ISSUE THREAD

**Issue by t-wihatz** [microsoft/react-native-windows#2762]
I was creating a test to make sure that zIndex is being included in transfer properties when the backing XAML element is changed. One issue that I ran into however, was if you update the border radius, the margins appear to get lost and the squares are stacked on top of each other. 

Before:
![BugBefore](https://user-images.githubusercontent.com/52328511/61092840-bd07c580-a3fc-11e9-920c-8fe404a1bffa.PNG)

After:
![BugAfter](https://user-images.githubusercontent.com/52328511/61092844-c002b600-a3fc-11e9-91d8-4674d27d9750.PNG)

However, after readjusting the size of the window, the layout gets updated and the margins are returned back to normal.

![BugAfter2](https://user-images.githubusercontent.com/52328511/61092848-c133e300-a3fc-11e9-952a-4b62e0c25248.PNG)

The layout is not getting updated when the backing element changes, and so the top and left margins either aren't being updated, or aren't being transferred correctly.

The code I was using for this test is down below. If you paste it into 
react-native-windows\vnext\node_modules\react-native\RNTester\js\ViewExample.js
you should be able to get the same results

{
  title: 'ZIndex Transfer Properties',
    render() {

    const styles = StyleSheet.create({
      zIndex: {
        justifyContent: 'space-around',
        width: 100,
        height: 50,
        marginTop: -10,
      },
      blankStyle: {
        borderRadius: null,
      },
      border: {
        borderRadius: 5
      },
    });

    class ZIndexChange extends React.Component<Props, State> {
      state = {
        cornerRadius: false,
      };

      render() {
        const hasRadius = this.state.cornerRadius ? styles.border : styles.blankStyle;
        const indices = this.state.flipped ? [-1, 0, 1, 2] : [2, 1, 0, -1];
        return (
          <View>
          <TouchableWithoutFeedback onPress={this._handlePress}>
              <View>
              <Text style={{ paddingBottom: 10 }}>
                The zIndex should remain the same after changing the border radius
                </Text>
              <View
                style={[
                    styles.zIndex,
                  {
                    marginTop: 0,
                    backgroundColor: '#E57373',
                    zIndex: indices[0],
                    }, hasRadius,
                ]}>
                <Text>ZIndex {indices[0]}</Text>
              </View>
              <View
                style={[
                    styles.zIndex, 
                  {
                    marginLeft: 50,
                    backgroundColor: '#FFF176',
                    zIndex: indices[1],
                    }, hasRadius,
                ]}>
                <Text>ZIndex {indices[1]}</Text>
              </View>
              <View
                style={[
                    styles.zIndex,
                  {
                    marginLeft: 100,
                    backgroundColor: '#81C784',
                    zIndex: indices[2],
                    }, hasRadius,
                ]}>
                <Text>ZIndex {indices[2]}</Text>
              </View>
              <View
                style={[
                    styles.zIndex,
                  {
                    marginLeft: 150,
                    backgroundColor: '#64B5F6',
                    zIndex: indices[3],
                    }, hasRadius,
                ]}>
                <Text>ZIndex {indices[3]}</Text>
              </View>
            </View>
            </TouchableWithoutFeedback>
            <Button onPress={this.handleClick} title="Change Border Radius" style={{ marginTop: 10 }} />
            <Button onPress={this.handlePress} title="Change Sorting Order" style={{ marginTop: 10 }} />
          </View>
        );
      }

      handleClick = () => {
        this.setState({ cornerRadius: !this.state.cornerRadius });
      };

      handlePress = () => {
        this.setState({ flipped: !this.state.flipped });
      };
    }
    return <ZIndexChange />
  },
},

**Comment by randy-flynn** [comment]
https://github.com/microsoft/react-native-windows/pull/3040
