### ISSUE TITLE
Fix remaining Image features

### ISSUE THREAD

**Issue by rozele** [microsoft/react-native-windows#278]
The following Image features are not working in UIExplorer:
- Resize Method
- Tint Color
- Background Color
- Plain Static Image

**Comment by rozele** [comment]
And ImageSize

**Comment by Pokute** [comment]
It looks like this feature has been pretty close to finished, but it hasn't been merged into master yet.
I tried to merge it myself and the merge isn't clean (imagecache isn't used) but it implements the background and tintcolor features.

I need this feature within a couple of weeks and would like it in a master branch for minimal hassle. Is there any way I can help with this task, @ebragge, @rozele ?

**Comment by lznt** [comment]
Any idea when this might be moving to PR stage?

**Comment by phongcao** [comment]
And blurRadius also doesn't work.
