### ISSUE TITLE
"react-native run-windows" failing

### ISSUE THREAD

**Issue by destinyb-realityi** [microsoft/react-native-windows#2782]
I'm getting the below error when I'm trying to call `react-native run-windows` 

Restoring NuGet packages
Building C:/Users/<user>/Desktop/Development/React-Native/RD/pinkjay/windows/pinkjay.sln
Found MSBuild v15.0 at C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin
Building Solution: C:/Users/<user>/Desktop/Development/React-Native/RD/pinkjay/windows/pinkjay.sln
Build configuration: Debug
Build platform: x86
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(5712,5): warning APPX1901: The DefaultLanguage property is either missing from the project file
 or does not have a value. The fallback language is set to the Visual Studio language: en-US. [C:\Users\<user>\Desktop\Development\React-Native\RD\pinkjay\node_modules\react-native-windows\Yoga\csharp\Yoga\Yoga.Universal.vcxproj]
React-Native Server already started
Failed to deploy: The "path" argument must be one of type string, Buffer, or URL. Received type undefined

**Comment by rozele** [comment]
Which version of react-native-windows are you using?

**Comment by destinyb-realityi** [comment]
Whatever the latest windows update is.

**Comment by J4s0nDRevs** [comment]
i am get this (refer to log)
[Reactnative log.txt](https://github.com/microsoft/react-native-windows/files/3409279/Reactnative.log.txt)
