### ISSUE TITLE
Is visual studio 2019(community) compatible for running react native windows app?

### ISSUE THREAD

**Issue by J4s0nDRevs** [microsoft/react-native-windows#2790]
Hi,

I am trying to build my first react native windows app. But when I compile, I got this error(shown below). I tried re-targeting by the error is not solved. 

MSB8020	The build tools for Visual Studio 2017 (Platform Toolset = 'v141') cannot be found. To build using the v141 build tools, please install Visual Studio 2017 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".	yoga.uwp	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets	379

**Comment by ShrinathGupta** [comment]
@J4s0nDRevs Yes VS 2019 is compatible to run.
You can test my demo project which is on latest vnext.
https://github.com/ShrinathGupta/React-native-windows-demo. 
**It covers few react native windows vnext elements see attached screenshot.**

![image](https://user-images.githubusercontent.com/12642711/61487545-ce843b00-a9c3-11e9-92bd-7cdb0cfc15f4.png)

@marlenecota @harinikmsft

**Comment by harinikmsft** [comment]
Thanks @ShrinathGupta !

Yup - VS2019 is supported now.
