### ISSUE TITLE
[Component]: FlatList property completion

### ISSUE THREAD

**Issue by harinikmsft** [microsoft/react-native-windows#2795]
Filing a placeholder issue to track the remaining properties to be implemented for FlatList. Note - almost all these should work already, the first task is to validate. This may include:
- renderItem
- ItemSeparatorComponent
- ListEmptyComponent
- columnWrapperStyle
- extraData
- inverted
- keyExtractor
- removeClippedSubviews
- viewabilityConfig
- viewabilityConfigCallbackPairs

TBD: Need to verify if above are still incomplete and bucketize by priority and XAML-equivalents.

**Comment by decrowle** [comment]
Verified basic cases for all of these properties. Can dig into specific scenarios at request if need be. Will go ahead and close this issue for now.

**Comment by harinikmsft** [comment]
Thanks @decrowle . Can you update the [Parity status doc](https://github.com/microsoft/react-native-windows/blob/master/vnext/docs/ParityStatus.md) line item for FlatList?

**Comment by kmelmon** [comment]
@harinikmsft What is remaining on this task?  Dexter verified basic cases for all the properties so this appears to be working.

**Comment by kmelmon** [comment]
I see this was marked done... Closing
