### ISSUE TITLE
Document View - Style API completion

### ISSUE THREAD

**Issue by harinikmsft** [microsoft/react-native-windows#2796]
This is a placeholder issue to validate and implement (if not already supported) the remaining [Style props](https://facebook.github.io/react-native/docs/0.59/view-style-props) on View:
- [x] opacity
- [x] backgroundColor
- [ ] borderRightColor #3077
- [ ] borderBottomColor #3077
- [x] borderBottomEndRadius #3074
- [x] borderBottomLeftRadius #3074
- [x] borderBottomRightRadius #3074
- [x] borderBottomStartRadius #3074
- [x] borderBottomWidth
- [x] borderColor
- [ ] borderEndColor #3077
- [ ] borderLeftColor #3077
- [x] borderLeftWidth
- [x] borderRadius #3074
- [x] borderRightWidth
- [ ] borderStartColor #3077
- [ ] borderStyle #3078
- [ ] borderTopColor #3077
- [x] borderTopEndRadius #3074
- [x] borderTopLeftRadius #3074
- [x] borderTopRightRadius #3074
- [x] borderTopStartRadius #3074
- [x] borderTopWidth
- [x] borderWidth
- [ ] Shadow props #2800 

Not implementing
- [elevation](https://facebook.github.io/react-native/docs/0.59/view-style-props#elevation)
_(Android-only) Sets the elevation of a view, using Android's underlying elevation API. This adds a drop shadow to the item and affects z-order for overlapping views. Only supported on Android 5.0+, has no effect on earlier versions._

**Comment by chrisglein** [comment]
Expanded list of border* props so we can be specific. Will be breaking out into a few issues soon.
Also [`elevation`](https://facebook.github.io/react-native/docs/0.59/view-style-props#elevation) was missing from the list. Not sure if that was intentional (@harinikmsft ?).

**Comment by harinikmsft** [comment]
I had left out elevation since it was Android-only which meant it may not be part of lean-core long term.

**Comment by chrisglein** [comment]
I've split out the individual issues and put them on this project board: https://github.com/microsoft/react-native-windows/issues/2796
At which point we don't need this issue. But we will want the information on an API. @harinikmsft can you coordinate that? (sync with Savoy/Kiki) Converting this issue to a documentation issue.

**Comment by harinikmsft** [comment]
@kikisaints - can you take a look at documenting this?

**Comment by kikisaints** [comment]
@harinikmsft can you defined documenting - do you mean put this up in the API section of our RNW website?

**Comment by chrisglein** [comment]
Switching Facebook label to specific issue on mixed borders: #3077

**Comment by chrisglein** [comment]
Not planned for Paper renderer.
For the Fabric renderer, tracked here: https://github.com/microsoft/react-native-windows/issues/11135
