### ISSUE TITLE
RNW CLI assumes App.windows.js entry point, ignoring existing code

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#2810]
### Environment

1. `react-native -v`:

```
react-native-cli: 2.0.1
react-native: 0.59.8
```

2. `npm ls rnpm-plugin-windows`:

```
`-- rnpm-plugin-windows@0.2.11
```

3. `npm ls react-native-windows`:

```
`-- react-native-windows@0.59.0-vnext.95
```
4. `node -v`:

```
v10.15.3
```

5. `npm -v`:

```
6.10.1
```

Then, specify:

- Target Platform Version(s): 10.0.18362

- Target Device(s): Desktop

- Visual Studio Version: 2017

- Build Configuration: Debug

### Steps to Reproduce

I reprored with when using the `expo-cli` but it should be a problem with any existing app. I want add a RNW vnext target using `rnpm-plugin-windows`.

1. `expo eject`
2. Select "plain" RN project
3. As per #2808 , I add the missing `"name"` entry
4. `react-native windows --template vnext`
5. `react-native run-windows`

### Expected Behavior

The new project builds and launches my existing app. It should be smart enough to identify (and refer) any existing entry point:

* The "main" key in package.json
* The "entryPoint" key in app.json

### Actual Behavior

The generated project both creates an App.windows.js and hardcodes the entry-point to it in the native code.

**Comment by harinikmsft** [comment]
We will need to go see what the template (post 0.59) currently does and try to mimic that more closely in our CLI.

**Comment by licanhua** [comment]
@jonthysell I think neither iOS or Android supports this. It's index.js by default.
Both node_modules/expo/AppEntry.js and index.js import App from App.js, and the actual entrypoint is index.js outside of expo.

Here is app.json after expo eject. and entryPoint should only be used in expo.

```
{
  "expo": {
    "name": "AwesomeProject",
    "slug": "AwesomeProject",
    "privacy": "public",
    "sdkVersion": "36.0.0",
    "platforms": [
      "ios",
      "android",
      "web"
    ],
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    },
    "entryPoint": "node_modules/expo/AppEntry.js"
  },
  "displayName": "AwesomeProject",
  "name": "AwesomeProject"
}
```

**Comment by NickGerleman** [comment]
Is this still relevant?
