### ISSUE TITLE
RNW CLI doesn't add node_modules to .gitignore

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#2811]
### Environment

1. `react-native -v`:

```
react-native-cli: 2.0.1
react-native: 0.59.8
```

2. `npm ls rnpm-plugin-windows`:

```
`-- rnpm-plugin-windows@0.2.11
```

3. `npm ls react-native-windows`:

```
`-- react-native-windows@0.59.0-vnext.95
```
4. `node -v`:

```
v10.15.3
```

5. `npm -v`:

```
6.10.1
```

Then, specify:

- Target Platform Version(s): 10.0.18362

- Target Device(s): Desktop

- Visual Studio Version: 2017

- Build Configuration: Debug

### Steps to Reproduce

Starting with an app created using `expo-cli`. I want to eject into a plain RN project and add a RNW vnext target using `rnpm-plugin-windows`.

1. `expo eject`
2. Select "plain" RN project
3. `react-native windows --template vnext`
4. git add .

### Expected Behavior

`windows/node_modules` is not included with the `git add .`

### Actual Behavior

The .gitignore in the windows folder doesn't contain `node_modules`, assuming the parent directory covers it. The expo CLI however only ignores the `node_modules` at the parent, not any node_modules that may be lurking in otherwise valid subdirectories.

**Comment by licanhua** [comment]
@jonthysell why do we need windows/node_modules and which script introduced it?

**Comment by acoates-ms** [comment]
yeah, there shouldn't be a node_modules directory in the windows directory.

**Comment by licanhua** [comment]
Close it because we don't have a repro any more
