### ISSUE TITLE
RNW adding new npm package breaks vs 2017 sln  and forces reinstall from scratch not .net but i cant delete the label

### ISSUE THREAD

**Issue by velociwabbit** [microsoft/react-native-windows#2821]
### Environment
 
 React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i7-6700T CPU @ 2.80GHz
      Memory: 4.35 GB / 15.88 GB
    Binaries:
      Yarn: 1.7.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD

react-native-cli: 2.0.1
react-native: 0.58.0
 
 
 
- Target Platform: x64 debug

 -  framework   10.0.14393,  

  Desktop, 
 
- Development Operating System: windows 10
 
- Visual Studio Version: 2017 community

 
- Build Configuration: Debug

### Steps to Reproduce
 

1.Start with an installed version of react-native for windows
2.try to add any new npm package (npm i -s *)  (and package will do 
3.  try and rebuild solution under visual studio 17

### Expected Behavior
 
no errors 
 

### Actual Behavior

6>D:\ddesktop\rn\windows\rn\App.xaml.cs(24,25,24,40): error CS0433: The type 'ReactNativeHost' exists in both 'ReactNative.Net46, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'ReactNative, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
6>D:\ddesktop\rn\windows\rn\MainReactNativeHost.cs(9,33,9,48): error CS0433: The type 'ReactNativeHost' exists in both 'ReactNative.Net46, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'ReactNative, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
6>D:\ddesktop\rn\windows\rn\App.xaml.cs(24,41,24,45): error CS1715: 'App.Host': type must be 'ReactNativeHost' to match overridden member 'ReactApplication.Host'
6>D:\ddesktop\rn\windows\rn\App.xaml.cs(8,26,8,29): error CS0534: 'App' does not implement inherited abstract member 'ReactApplication.Host.get'
6>D:\ddesktop\rn\windows\rn\App.xaml.cs(10,26,10,41): error CS0433: The type 'ReactNativeHost' exists in both 'ReactNative.Net46, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'ReactNative, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
6>D:\ddesktop\rn\windows\rn\MainReactNativeHost.cs(25,33,25,46): error CS0433: The type 'IReactPackage' exists in both 'ReactNative.Net46, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'ReactNative, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
6>D:\ddesktop\rn\windows\rn\MainReactNativeHost.cs(11,32,11,49): error CS0115: 'MainReactNativeHost.MainComponentName': no suitable method found to override
6>D:\ddesktop\rn\windows\rn\MainReactNativeHost.cs(14,30,14,49): error CS0115: 'MainReactNativeHost.UseDeveloperSupport': no suitable method found to override
6>D:\ddesktop\rn\windows\rn\MainReactNativeHost.cs(19,35,19,59): error CS0115: 'MainReactNativeHost.JavaScriptMainModuleName': no suitable method found to override
6>D:\ddesktop\rn\windows\rn\MainReactNativeHost.cs(25,48,25,56): error CS0115: 'MainReactNativeHost.Packages': no suitable method found to override

 
Add Any npm package and it forces and entire rebuild from scratch of react-native for windows

 

### Reproducible Demo

 this is my package.json  

{
  "name": "rn",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "mrn": "^0.1.7",
    "react": "16.6.3",
    "react-native": "0.58.0",
    "react-native-material-ui": "^1.30.1",
                                                                           "react-native-svg": "^9.5.3",  added
    "react-native-vector-icons": "^4.0.0",
    "react-native-windows": "^0.58.0-rc.2"
  },
  "devDependencies": {
    "babel-core": "7.0.0-bridge.0",
    "babel-jest": "24.8.0",
    "jest": "24.8.0",
    "metro-react-native-babel-preset": "0.55.0",
    "react-test-renderer": "16.6.3",
    "rnpm-plugin-windows": "^0.2.11"
  },
  "assets": [
    "./Assets/fonts"
  ],
  "jest": {
    "preset": "react-native"
  }
}

remove react-native-svg and install, react-native windows etc
it should run fine.

then try and add svg to it... it wont work.

This is true for any of the packages in the dependency  list.  

remove and add    "react-native-material-ui": "^1.30.1"

**Comment by rozele** [comment]
@velociwabbit - are you building for UWP or WPF?

**Comment by rozele** [comment]
Ah - sorry - is this for vnext?

**Comment by velociwabbit** [comment]
universal windows... sorry

**Comment by rozele** [comment]
@velociwabbit - any chance you can post a public repro with your .sln and .csproj files?

**Comment by velociwabbit** [comment]
I could zip it and attach it here there is nothing special about the repo as it is only a test bed so that i can port an app.  will that work?

**Comment by velociwabbit** [comment]
this is the sln file


Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio 15
VisualStudioVersion = 15.0.27703.2035
MinimumVisualStudioVersion = 10.0.40219.1
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "rn", "rn\rn.csproj", "{A326C347-20D5-4681-B9B6-186351C2A699}"
	ProjectSection(ProjectDependencies) = postProject
		{2EACF721-73B5-46AE-9775-4A8674D05A9C} = {2EACF721-73B5-46AE-9775-4A8674D05A9C}
	EndProjectSection
EndProject
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "ReactNative", "..\node_modules\react-native-windows\ReactWindows\ReactNative\ReactNative.csproj", "{C7673AD5-E3AA-468C-A5FD-FA38154E205C}"
EndProject
Project("{D954291E-2A0B-460D-934E-DC6B0785DB48}") = "ReactNative.Shared", "..\node_modules\react-native-windows\ReactWindows\ReactNative.Shared\ReactNative.Shared.shproj", "{EEA8B852-4D07-48E1-8294-A21AB5909FE5}"
EndProject
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "ChakraBridge", "..\node_modules\react-native-windows\ReactWindows\ChakraBridge\ChakraBridge.vcxproj", "{4B72C796-16D5-4E3A-81C0-3E36F531E578}"
EndProject
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "ReactNativeWebViewBridge", "..\node_modules\react-native-windows\ReactWindows\ReactNativeWebViewBridge\ReactNativeWebViewBridge.csproj", "{7596216B-669C-41F8-86DA-F3637F6545C0}"
EndProject
Project("{D954291E-2A0B-460D-934E-DC6B0785DB48}") = "Facebook.Yoga.Shared", "..\node_modules\react-native-windows\Yoga\csharp\Facebook.Yoga\Facebook.Yoga.Shared.shproj", "{91C42D32-291D-4B72-90B4-551663D60B8B}"
EndProject
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "yoga.uwp", "..\node_modules\react-native-windows\Yoga\csharp\Yoga\Yoga.Universal.vcxproj", "{2EACF721-73B5-46AE-9775-4A8674D05A9C}"
EndProject
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "ReactNative.Net46", "..\node_modules\react-native-windows\ReactWindows\ReactNative.Net46\ReactNative.Net46.csproj", "{22CBFF9C-FE36-43E8-A246-266C7635E662}"
EndProject
Global
	GlobalSection(SharedMSBuildProjectFiles) = preSolution
		..\node_modules\react-native-windows\ReactWindows\ReactNative.Shared\ReactNative.Shared.projitems*{22cbff9c-fe36-43e8-a246-266c7635e662}*SharedItemsImports = 4
		..\node_modules\react-native-windows\Yoga\csharp\Facebook.Yoga\Facebook.Yoga.Shared.projitems*{22cbff9c-fe36-43e8-a246-266c7635e662}*SharedItemsImports = 4
		..\node_modules\react-native-windows\Yoga\csharp\Facebook.Yoga\Facebook.Yoga.Shared.projitems*{91c42d32-291d-4b72-90b4-551663d60b8b}*SharedItemsImports = 13
		..\node_modules\react-native-windows\ReactWindows\ReactNative.Shared\ReactNative.Shared.projitems*{c7673ad5-e3aa-468c-a5fd-fa38154e205c}*SharedItemsImports = 4
		..\node_modules\react-native-windows\Yoga\csharp\Facebook.Yoga\Facebook.Yoga.Shared.projitems*{c7673ad5-e3aa-468c-a5fd-fa38154e205c}*SharedItemsImports = 4
		..\node_modules\react-native-windows\ReactWindows\ReactNative.Shared\ReactNative.Shared.projitems*{eea8b852-4d07-48e1-8294-a21ab5909fe5}*SharedItemsImports = 13
	EndGlobalSection
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|ARM = Debug|ARM
		Debug|x64 = Debug|x64
		Debug|x86 = Debug|x86
		DebugBundle|ARM = DebugBundle|ARM
		DebugBundle|x64 = DebugBundle|x64
		DebugBundle|x86 = DebugBundle|x86
		Release|ARM = Release|ARM
		Release|x64 = Release|x64
		Release|x86 = Release|x86
		ReleaseBundle|ARM = ReleaseBundle|ARM
		ReleaseBundle|x64 = ReleaseBundle|x64
		ReleaseBundle|x86 = ReleaseBundle|x86
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{A326C347-20D5-4681-B9B6-186351C2A699}.Debug|ARM.ActiveCfg = Debug|ARM
		{A326C347-20D5-4681-B9B6-186351C2A699}.Debug|ARM.Build.0 = Debug|ARM
		{A326C347-20D5-4681-B9B6-186351C2A699}.Debug|ARM.Deploy.0 = Debug|ARM
		{A326C347-20D5-4681-B9B6-186351C2A699}.Debug|x64.ActiveCfg = Debug|x64
		{A326C347-20D5-4681-B9B6-186351C2A699}.Debug|x64.Build.0 = Debug|x64
		{A326C347-20D5-4681-B9B6-186351C2A699}.Debug|x64.Deploy.0 = Debug|x64
		{A326C347-20D5-4681-B9B6-186351C2A699}.Debug|x86.ActiveCfg = Debug|x86
		{A326C347-20D5-4681-B9B6-186351C2A699}.Debug|x86.Build.0 = Debug|x86
		{A326C347-20D5-4681-B9B6-186351C2A699}.Debug|x86.Deploy.0 = Debug|x86
		{A326C347-20D5-4681-B9B6-186351C2A699}.DebugBundle|ARM.ActiveCfg = DebugBundle|ARM
		{A326C347-20D5-4681-B9B6-186351C2A699}.DebugBundle|ARM.Build.0 = DebugBundle|ARM
		{A326C347-20D5-4681-B9B6-186351C2A699}.DebugBundle|ARM.Deploy.0 = DebugBundle|ARM
		{A326C347-20D5-4681-B9B6-186351C2A699}.DebugBundle|x64.ActiveCfg = DebugBundle|x64
		{A326C347-20D5-4681-B9B6-186351C2A699}.DebugBundle|x64.Build.0 = DebugBundle|x64
		{A326C347-20D5-4681-B9B6-186351C2A699}.DebugBundle|x64.Deploy.0 = DebugBundle|x64
		{A326C347-20D5-4681-B9B6-186351C2A699}.DebugBundle|x86.ActiveCfg = DebugBundle|x86
		{A326C347-20D5-4681-B9B6-186351C2A699}.DebugBundle|x86.Build.0 = DebugBundle|x86
		{A326C347-20D5-4681-B9B6-186351C2A699}.DebugBundle|x86.Deploy.0 = DebugBundle|x86
		{A326C347-20D5-4681-B9B6-186351C2A699}.Release|ARM.ActiveCfg = Release|ARM
		{A326C347-20D5-4681-B9B6-186351C2A699}.Release|ARM.Build.0 = Release|ARM
		{A326C347-20D5-4681-B9B6-186351C2A699}.Release|ARM.Deploy.0 = Release|ARM
		{A326C347-20D5-4681-B9B6-186351C2A699}.Release|x64.ActiveCfg = Release|x64
		{A326C347-20D5-4681-B9B6-186351C2A699}.Release|x64.Build.0 = Release|x64
		{A326C347-20D5-4681-B9B6-186351C2A699}.Release|x64.Deploy.0 = Release|x64
		{A326C347-20D5-4681-B9B6-186351C2A699}.Release|x86.ActiveCfg = Release|x86
		{A326C347-20D5-4681-B9B6-186351C2A699}.Release|x86.Build.0 = Release|x86
		{A326C347-20D5-4681-B9B6-186351C2A699}.Release|x86.Deploy.0 = Release|x86
		{A326C347-20D5-4681-B9B6-186351C2A699}.ReleaseBundle|ARM.ActiveCfg = ReleaseBundle|ARM
		{A326C347-20D5-4681-B9B6-186351C2A699}.ReleaseBundle|ARM.Build.0 = ReleaseBundle|ARM
		{A326C347-20D5-4681-B9B6-186351C2A699}.ReleaseBundle|ARM.Deploy.0 = ReleaseBundle|ARM
		{A326C347-20D5-4681-B9B6-186351C2A699}.ReleaseBundle|x64.ActiveCfg = ReleaseBundle|x64
		{A326C347-20D5-4681-B9B6-186351C2A699}.ReleaseBundle|x64.Build.0 = ReleaseBundle|x64
		{A326C347-20D5-4681-B9B6-186351C2A699}.ReleaseBundle|x64.Deploy.0 = ReleaseBundle|x64
		{A326C347-20D5-4681-B9B6-186351C2A699}.ReleaseBundle|x86.ActiveCfg = ReleaseBundle|x86
		{A326C347-20D5-4681-B9B6-186351C2A699}.ReleaseBundle|x86.Build.0 = ReleaseBundle|x86
		{A326C347-20D5-4681-B9B6-186351C2A699}.ReleaseBundle|x86.Deploy.0 = ReleaseBundle|x86
		{C7673AD5-E3AA-468C-A5FD-FA38154E205C}.Debug|ARM.ActiveCfg = Debug|ARM
		{C7673AD5-E3AA-468C-A5FD-FA38154E205C}.Debug|ARM.Build.0 = Debug|ARM
		{C7673AD5-E3AA-468C-A5FD-FA38154E205C}.Debug|x64.ActiveCfg = Debug|x64
		{C7673AD5-E3AA-468C-A5FD-FA38154E205C}.Debug|x64.Build.0 = Debug|x64
		{C7673AD5-E3AA-468C-A5FD-FA38154E205C}.Debug|x86.ActiveCfg = Debug|x86
		{C7673AD5-E3AA-468C-A5FD-FA38154E205C}.Debug|x86.Build.0 = Debug|x86
		{C7673AD5-E3AA-468C-A5FD-FA38154E205C}.DebugBundle|ARM.ActiveCfg = Debug|ARM
		{C7673AD5-E3AA-468C-A5FD-FA38154E205C}.DebugBundle|ARM.Build.0 = Debug|ARM
		{C7673AD5-E3AA-468C-A5FD-FA38154E205C}.DebugBundle|x64.ActiveCfg = Debug|x64
		{C7673AD5-E3AA-468C-A5FD-FA38154E205C}.DebugBundle|x64.Build.0 = Debug|x64
		{C7673AD5-E3AA-468C-A5FD-FA38154E205C}.DebugBundle|x86.ActiveCfg = Debug|x86
		{C7673AD5-E3AA-468C-A5FD-FA38154E205C}.DebugBundle|x86.Build.0 = Debug|x86
		{C7673AD5-E3AA-468C-A5FD-FA38154E205C}.Release|ARM.ActiveCfg = Release|ARM
		{C7673AD5-E3AA-468C-A5FD-FA38154E205C}.Release|ARM.Build.0 = Release|ARM
		{C7673AD5-E3AA-468C-A5FD-FA38154E205C}.Release|x64.ActiveCfg = Release|x64
		{C7673AD5-E3AA-468C-A5FD-FA38154E205C}.Release|x64.Build.0 = Release|x64
		{C7673AD5-E3AA-468C-A5FD-FA38154E205C}.Release|x86.ActiveCfg = Release|x86
		{C7673AD5-E3AA-468C-A5FD-FA38154E205C}.Release|x86.Build.0 = Release|x86
		{C7673AD5-E3AA-468C-A5FD-FA38154E205C}.ReleaseBundle|ARM.ActiveCfg = Release|ARM
		{C7673AD5-E3AA-468C-A5FD-FA38154E205C}.ReleaseBundle|ARM.Build.0 = Release|ARM
		{C7673AD5-E3AA-468C-A5FD-FA38154E205C}.ReleaseBundle|x64.ActiveCfg = Release|x64
		{C7673AD5-E3AA-468C-A5FD-FA38154E205C}.ReleaseBundle|x64.Build.0 = Release|x64
		{C7673AD5-E3AA-468C-A5FD-FA38154E205C}.ReleaseBundle|x86.ActiveCfg = Release|x86
		{C7673AD5-E3AA-468C-A5FD-FA38154E205C}.ReleaseBundle|x86.Build.0 = Release|x86
		{4B72C796-16D5-4E3A-81C0-3E36F531E578}.Debug|ARM.ActiveCfg = Debug|ARM
		{4B72C796-16D5-4E3A-81C0-3E36F531E578}.Debug|ARM.Build.0 = Debug|ARM
		{4B72C796-16D5-4E3A-81C0-3E36F531E578}.Debug|x64.ActiveCfg = Debug|x64
		{4B72C796-16D5-4E3A-81C0-3E36F531E578}.Debug|x64.Build.0 = Debug|x64
		{4B72C796-16D5-4E3A-81C0-3E36F531E578}.Debug|x86.ActiveCfg = Debug|Win32
		{4B72C796-16D5-4E3A-81C0-3E36F531E578}.Debug|x86.Build.0 = Debug|Win32
		{4B72C796-16D5-4E3A-81C0-3E36F531E578}.DebugBundle|ARM.ActiveCfg = Debug|ARM
		{4B72C796-16D5-4E3A-81C0-3E36F531E578}.DebugBundle|ARM.Build.0 = Debug|ARM
		{4B72C796-16D5-4E3A-81C0-3E36F531E578}.DebugBundle|x64.ActiveCfg = Debug|x64
		{4B72C796-16D5-4E3A-81C0-3E36F531E578}.DebugBundle|x64.Build.0 = Debug|x64
		{4B72C796-16D5-4E3A-81C0-3E36F531E578}.DebugBundle|x86.ActiveCfg = Debug|Win32
		{4B72C796-16D5-4E3A-81C0-3E36F531E578}.DebugBundle|x86.Build.0 = Debug|Win32
		{4B72C796-16D5-4E3A-81C0-3E36F531E578}.Release|ARM.ActiveCfg = Release|ARM
		{4B72C796-16D5-4E3A-81C0-3E36F531E578}.Release|ARM.Build.0 = Release|ARM
		{4B72C796-16D5-4E3A-81C0-3E36F531E578}.Release|x64.ActiveCfg = Release|x64
		{4B72C796-16D5-4E3A-81C0-3E36F531E578}.Release|x64.Build.0 = Release|x64
		{4B72C796-16D5-4E3A-81C0-3E36F531E578}.Release|x86.ActiveCfg = Release|Win32
		{4B72C796-16D5-4E3A-81C0-3E36F531E578}.Release|x86.Build.0 = Release|Win32
		{4B72C796-16D5-4E3A-81C0-3E36F531E578}.ReleaseBundle|ARM.ActiveCfg = Release|ARM
		{4B72C796-16D5-4E3A-81C0-3E36F531E578}.ReleaseBundle|ARM.Build.0 = Release|ARM
		{4B72C796-16D5-4E3A-81C0-3E36F531E578}.ReleaseBundle|x64.ActiveCfg = Release|x64
		{4B72C796-16D5-4E3A-81C0-3E36F531E578}.ReleaseBundle|x64.Build.0 = Release|x64
		{4B72C796-16D5-4E3A-81C0-3E36F531E578}.ReleaseBundle|x86.ActiveCfg = Release|Win32
		{4B72C796-16D5-4E3A-81C0-3E36F531E578}.ReleaseBundle|x86.Build.0 = Release|Win32
		{7596216B-669C-41F8-86DA-F3637F6545C0}.Debug|ARM.ActiveCfg = Debug|ARM
		{7596216B-669C-41F8-86DA-F3637F6545C0}.Debug|ARM.Build.0 = Debug|ARM
		{7596216B-669C-41F8-86DA-F3637F6545C0}.Debug|x64.ActiveCfg = Debug|x64
		{7596216B-669C-41F8-86DA-F3637F6545C0}.Debug|x64.Build.0 = Debug|x64
		{7596216B-669C-41F8-86DA-F3637F6545C0}.Debug|x86.ActiveCfg = Debug|x86
		{7596216B-669C-41F8-86DA-F3637F6545C0}.Debug|x86.Build.0 = Debug|x86
		{7596216B-669C-41F8-86DA-F3637F6545C0}.DebugBundle|ARM.ActiveCfg = Debug|ARM
		{7596216B-669C-41F8-86DA-F3637F6545C0}.DebugBundle|ARM.Build.0 = Debug|ARM
		{7596216B-669C-41F8-86DA-F3637F6545C0}.DebugBundle|x64.ActiveCfg = Debug|x64
		{7596216B-669C-41F8-86DA-F3637F6545C0}.DebugBundle|x64.Build.0 = Debug|x64
		{7596216B-669C-41F8-86DA-F3637F6545C0}.DebugBundle|x86.ActiveCfg = Debug|x86
		{7596216B-669C-41F8-86DA-F3637F6545C0}.DebugBundle|x86.Build.0 = Debug|x86
		{7596216B-669C-41F8-86DA-F3637F6545C0}.Release|ARM.ActiveCfg = Release|ARM
		{7596216B-669C-41F8-86DA-F3637F6545C0}.Release|ARM.Build.0 = Release|ARM
		{7596216B-669C-41F8-86DA-F3637F6545C0}.Release|x64.ActiveCfg = Release|x64
		{7596216B-669C-41F8-86DA-F3637F6545C0}.Release|x64.Build.0 = Release|x64
		{7596216B-669C-41F8-86DA-F3637F6545C0}.Release|x86.ActiveCfg = Release|x86
		{7596216B-669C-41F8-86DA-F3637F6545C0}.Release|x86.Build.0 = Release|x86
		{7596216B-669C-41F8-86DA-F3637F6545C0}.ReleaseBundle|ARM.ActiveCfg = Release|ARM
		{7596216B-669C-41F8-86DA-F3637F6545C0}.ReleaseBundle|ARM.Build.0 = Release|ARM
		{7596216B-669C-41F8-86DA-F3637F6545C0}.ReleaseBundle|x64.ActiveCfg = Release|x64
		{7596216B-669C-41F8-86DA-F3637F6545C0}.ReleaseBundle|x64.Build.0 = Release|x64
		{7596216B-669C-41F8-86DA-F3637F6545C0}.ReleaseBundle|x86.ActiveCfg = Release|x86
		{7596216B-669C-41F8-86DA-F3637F6545C0}.ReleaseBundle|x86.Build.0 = Release|x86
		{2EACF721-73B5-46AE-9775-4A8674D05A9C}.Debug|ARM.ActiveCfg = Debug|ARM
		{2EACF721-73B5-46AE-9775-4A8674D05A9C}.Debug|ARM.Build.0 = Debug|ARM
		{2EACF721-73B5-46AE-9775-4A8674D05A9C}.Debug|x64.ActiveCfg = Debug|x64
		{2EACF721-73B5-46AE-9775-4A8674D05A9C}.Debug|x64.Build.0 = Debug|x64
		{2EACF721-73B5-46AE-9775-4A8674D05A9C}.Debug|x86.ActiveCfg = Debug|Win32
		{2EACF721-73B5-46AE-9775-4A8674D05A9C}.Debug|x86.Build.0 = Debug|Win32
		{2EACF721-73B5-46AE-9775-4A8674D05A9C}.DebugBundle|ARM.ActiveCfg = Debug|ARM
		{2EACF721-73B5-46AE-9775-4A8674D05A9C}.DebugBundle|ARM.Build.0 = Debug|ARM
		{2EACF721-73B5-46AE-9775-4A8674D05A9C}.DebugBundle|x64.ActiveCfg = Debug|x64
		{2EACF721-73B5-46AE-9775-4A8674D05A9C}.DebugBundle|x64.Build.0 = Debug|x64
		{2EACF721-73B5-46AE-9775-4A8674D05A9C}.DebugBundle|x86.ActiveCfg = Debug|Win32
		{2EACF721-73B5-46AE-9775-4A8674D05A9C}.DebugBundle|x86.Build.0 = Debug|Win32
		{2EACF721-73B5-46AE-9775-4A8674D05A9C}.Release|ARM.ActiveCfg = Release|ARM
		{2EACF721-73B5-46AE-9775-4A8674D05A9C}.Release|ARM.Build.0 = Release|ARM
		{2EACF721-73B5-46AE-9775-4A8674D05A9C}.Release|x64.ActiveCfg = Release|x64
		{2EACF721-73B5-46AE-9775-4A8674D05A9C}.Release|x64.Build.0 = Release|x64
		{2EACF721-73B5-46AE-9775-4A8674D05A9C}.Release|x86.ActiveCfg = Release|Win32
		{2EACF721-73B5-46AE-9775-4A8674D05A9C}.Release|x86.Build.0 = Release|Win32
		{2EACF721-73B5-46AE-9775-4A8674D05A9C}.ReleaseBundle|ARM.ActiveCfg = Release|ARM
		{2EACF721-73B5-46AE-9775-4A8674D05A9C}.ReleaseBundle|ARM.Build.0 = Release|ARM
		{2EACF721-73B5-46AE-9775-4A8674D05A9C}.ReleaseBundle|x64.ActiveCfg = Release|x64
		{2EACF721-73B5-46AE-9775-4A8674D05A9C}.ReleaseBundle|x64.Build.0 = Release|x64
		{2EACF721-73B5-46AE-9775-4A8674D05A9C}.ReleaseBundle|x86.ActiveCfg = Release|Win32
		{2EACF721-73B5-46AE-9775-4A8674D05A9C}.ReleaseBundle|x86.Build.0 = Release|Win32
		{22CBFF9C-FE36-43E8-A246-266C7635E662}.Debug|ARM.ActiveCfg = Debug|ARM
		{22CBFF9C-FE36-43E8-A246-266C7635E662}.Debug|ARM.Build.0 = Debug|ARM
		{22CBFF9C-FE36-43E8-A246-266C7635E662}.Debug|x64.ActiveCfg = Debug|x64
		{22CBFF9C-FE36-43E8-A246-266C7635E662}.Debug|x64.Build.0 = Debug|x64
		{22CBFF9C-FE36-43E8-A246-266C7635E662}.Debug|x86.ActiveCfg = Debug|x86
		{22CBFF9C-FE36-43E8-A246-266C7635E662}.Debug|x86.Build.0 = Debug|x86
		{22CBFF9C-FE36-43E8-A246-266C7635E662}.DebugBundle|ARM.ActiveCfg = Debug|ARM
		{22CBFF9C-FE36-43E8-A246-266C7635E662}.DebugBundle|ARM.Build.0 = Debug|ARM
		{22CBFF9C-FE36-43E8-A246-266C7635E662}.DebugBundle|x64.ActiveCfg = Debug|x64
		{22CBFF9C-FE36-43E8-A246-266C7635E662}.DebugBundle|x64.Build.0 = Debug|x64
		{22CBFF9C-FE36-43E8-A246-266C7635E662}.DebugBundle|x86.ActiveCfg = Debug|x86
		{22CBFF9C-FE36-43E8-A246-266C7635E662}.DebugBundle|x86.Build.0 = Debug|x86
		{22CBFF9C-FE36-43E8-A246-266C7635E662}.Release|ARM.ActiveCfg = Release|ARM
		{22CBFF9C-FE36-43E8-A246-266C7635E662}.Release|ARM.Build.0 = Release|ARM
		{22CBFF9C-FE36-43E8-A246-266C7635E662}.Release|x64.ActiveCfg = Release|x64
		{22CBFF9C-FE36-43E8-A246-266C7635E662}.Release|x64.Build.0 = Release|x64
		{22CBFF9C-FE36-43E8-A246-266C7635E662}.Release|x86.ActiveCfg = Release|x86
		{22CBFF9C-FE36-43E8-A246-266C7635E662}.Release|x86.Build.0 = Release|x86
		{22CBFF9C-FE36-43E8-A246-266C7635E662}.ReleaseBundle|ARM.ActiveCfg = Release|ARM
		{22CBFF9C-FE36-43E8-A246-266C7635E662}.ReleaseBundle|ARM.Build.0 = Release|ARM
		{22CBFF9C-FE36-43E8-A246-266C7635E662}.ReleaseBundle|x64.ActiveCfg = Release|x64
		{22CBFF9C-FE36-43E8-A246-266C7635E662}.ReleaseBundle|x64.Build.0 = Release|x64
		{22CBFF9C-FE36-43E8-A246-266C7635E662}.ReleaseBundle|x86.ActiveCfg = Release|x86
		{22CBFF9C-FE36-43E8-A246-266C7635E662}.ReleaseBundle|x86.Build.0 = Release|x86
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
	GlobalSection(ExtensibilityGlobals) = postSolution
		SolutionGuid = {49BE6BE9-22F7-4E4D-9846-3ED3CBE83365}
	EndGlobalSection
EndGlobal

**Comment by velociwabbit** [comment]
[rnzip.zip](https://github.com/microsoft/react-native-windows/files/3427956/rnzip.zip)
if you npm install this and react-native windows it should work but then try adding a repo to it and you will see that it breaks the sln

**Comment by velociwabbit** [comment]
no, i could not get vnext to work.

also do you know of any relatively full featured example app that runs in
react-native windows?  I am having trouble installing nearly every example
for react-native with rn for w.

Ideally i would love to have something that i could npm i, react-native
windows run the 2017 sln dev environment and see a full function app.

thanks

/jpr

**Comment by chrisglein** [comment]
Issue has gone a bit stale. Looks like you tried vnext in the past. We've put a ton of development into it since then. It's worth another try.
