### ISSUE TITLE
React-Native linking of react-native-svg not working error generated

### ISSUE THREAD

**Issue by velociwabbit** [microsoft/react-native-windows#2827]
React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i7-6700T CPU @ 2.80GHz
      Memory: 5.83 GB / 15.88 GB
    Binaries:
      Yarn: 1.7.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD

UWP

 10.0.14393, 

Desktop
 
  Visual Studio 2017  community  
 

 

(Write your steps here:)

1.install the attached zip file 
2.try and link (there will be a bug that i have a fix for below)
3.Even with the fix the linking of react-native-svg does not work

this bug is generated 
Invariant Violation: requireNativeComponent: "RNSVGRect" was not found in the UIManager.

This error is located at:
    in RNSVGRect (at Rect.js:22)
    in Rect (at App.windows.js:141)
    in RNSVGGroup (at G.js:23)
    in G (at Svg.js:127)
    in RNSVGSvgView (at Svg.js:116)
    in Svg (at App.windows.js:140)
    in RCTView (at View.js:45)
    in View (at App.windows.js:138)
    in App (at renderApplication.js:34)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:33)
 
on line 99 of  react-native/local-cli/link/link.js 

    if (!linkConfig || !linkConfig.copyAssets ) {
      return;
    }

should be

    if (!linkConfig || !linkConfig.copyAssets || !  project[platform]) {
      return;
    }

It fixes a bug but linking still does not take place  

[rnbugrepo.zip](https://github.com/microsoft/react-native-windows/files/3429299/rnbugrepo.zip)

**Comment by rozele** [comment]
which version of react-native-windows?

**Comment by velociwabbit** [comment]
it is in the attached zip repo including the package_json and the other files

    "react": "16.6.3",
    "react-native": "0.58.0",
    "react-native-material-ui": "^1.30.1",
    "react-native-svg": "^9.5.3",
    "react-native-vector-icons": "^4.0.0",
    "react-native-windows": "^0.58.0-rc.2"

**Comment by chrisglein** [comment]
Of note, SVG support is built in with "vnext" (soon to be current with 0.61): #3573.
