### ISSUE TITLE
[BUG] react-navigation-stack and Platform.Select issue

### ISSUE THREAD

**Issue by namrog84** [microsoft/react-native-windows#2834]
**react-navigation-stack** uses a  `const platformContainerStyles = Platform.select({`
where Platform comes from `'react-native'` but I know react-native-windows overrides and exports a Platform.select.
But it doesn't work in this scenario.

Propogates out as 
`react_native_1.Platform.select(...) is not a function`

**Comment by harinikmsft** [comment]
This may be an app issue. @acoates-ms is verifying if there is an underlying issue on our side.

**Comment by namrog84** [comment]
After furthest investigation. I believe this might have been happening because there was no 'uwp' or 'default' use case in a scenario that there HAD to be a value or something.

This issue is not what I had thought it was originally.  It is unclear exactly what triggers it, but there are cases that it is working and some that isn't.  It might have to do something with use of default: or in certain circumstances a required value. 

I don't think the error 'platform.select is not a function' is exactly the problem.  I think its more subtle than that.

**Comment by acoates-ms** [comment]
Yeah, that sounds more like an issue with react-navigation-stack not handling platforms it doesn't know about.  Some of that may be fixed when we rename our platform back to windows instead of uwp.
