### ISSUE TITLE
TypeError: Cannot read property 'toString' of null 

### ISSUE THREAD

**Issue by ramdeoangh** [microsoft/react-native-windows#2843]
### Environment

1. `react-native:`0.55.4
2.  `react-native-cli:`2.0.1
3. `npm ls rnpm-plugin-windows`: -- rnpm-plugin-windows@0.2.11
4. `npm ls react-native-windows`: --react-native-windows@0.55.0-rc.0
5. `node -v`: 10.16.0
6. `npm -v`: 6.9.0

Then, specify:

- Target Platform: UWP

- Target Platform Version(s):10.0.14393

- Target Device(s): Laptop (HP)

- Development Operating System: Windows

- Visual Studio Version: 2019
 
### Steps to Reproduce

(Write your steps here:)

1. Install React Native command-line interface. -- Success
         `npm install -g react-native-cli`
2. Generate a React Native project  -- Success
         `react-native init HelloWorld`
3. cd  HelloWorld
4. Install React-native windows plugin from this command --Success
  `npm install --save-dev rnpm-plugin-windows`
5. Install React-Native windows
  ` react-native windows`
 
### Expected Behavior
 It should install without error.

I am not sure but It might be possible that versioning Issue. error Is from `node_modules\react-native-windows\local-cli\generator-windows\index.js:69:60`

### Actual Behavior
I am getting an exception. I tried with the latest version of 'react-native' still I am facing the same issue. 
It should Install the react windows dependencies along with `app.window.js` file and generate the required C# piece of code. 
Here is the screenshot. 
![Untitled](https://user-images.githubusercontent.com/25610591/62058036-57119f80-b23e-11e9-86b0-3a373aafa341.png)

**Comment by rozele** [comment]
Cherry picked https://github.com/microsoft/react-native-windows/pull/1902. Should be fixed in 0.55.0-rc.1
