### ISSUE TITLE
[BUG] Text is sized incorrectly if numberOfLines is set to 1 and content is longer than container

### ISSUE THREAD

**Issue by sayzenberg** [microsoft/react-native-windows#2849]
### Steps to Reproduce

1. Wrap a Text element in any kind of View or other container
2. Set the Text element's content to make it wider than the width of the parent container
3. Set the Text element's numberOfLines property to 1 and do not specify a width or minWidth

### Expected Behavior

Text element should show ellipsis or be cut off, depending on what ellipsizeMode is set to.

This is what happens for the string 'abcd-efghijklmnopqrstuvwxyzabcdefghijklmnop'
![image](https://user-images.githubusercontent.com/1684243/62156815-9aaced80-b2c0-11e9-96eb-f02333f36257.png)

### Actual Behavior

Text is cut off at the point of text where it would wrap if numberOfLines were greater than 1.

This is what happens for the string 'abcd-efghijklmnopqrstuvwxyzabcdefghijklmnop'
![image](https://user-images.githubusercontent.com/1684243/62156565-21ad9600-b2c0-11e9-9eb6-229dd1c8c503.png)

### Reproducible Demo

This is a rough example of what the bug looks like, with the string cut off for approximation:
https://snack.expo.io/rJS1xGCfH

### Additional context

Examining the Text element in Visual Studio reveals that the width is being set to whatever the width of the "first line" would be if the Text element were wrapped. This is what's causing the text to be obscured.

**Comment by harinikmsft** [comment]
This looks like a bug on our side - perhaps a conflict between ellipsize and textwrapping on native xaml text defaults.

**Comment by ahimberg** [comment]
in RNW.current they set a default texttrimming of TextTrimming.CharacterEllipsis.  vnext is not doing that so we get a default of TextTrimming.None which I guess has this behavior when wrap is on.

**Comment by ddalp** [comment]
Checking the live visual tree the TextTrimming property is set to CharacterEllipsis by default (I think react sets the default ellipsizeMode to tail). CharacterEllipsis and WordEllipsis probably behave same when wrapping is on. I think we probably should set text to no wrap when numberOfLines is 1

**Comment by ddalp** [comment]
Fixed.
