### ISSUE TITLE
Add support for Keyboard native module

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#2852]
# Proposal: Add support for Keyboard module 

## Summary
This issue is tracking implementing the Keyboard native module in vnext.  See https://facebook.github.io/react-native/docs/keyboard

**Comment by chrisglein** [comment]
Hey @ddalp, this one needs someone to dig in and find what's missing/broken. Can you give this one a breakdown?

**Comment by ddalp** [comment]
There are six types of events defined for keyBoard by React Native:
keyboardWillShow
keyboardDidShow
keyboardWillHide
keyboardDidHide
keyboardWillChangeFrame
keyboardDidChangeFrame

I think we can only map keyboardDidShow and keyboardDidShow for Windows.

**Comment by ddalp** [comment]
Checked in, we are now firing keyboardDidShow and keyboardDidHide events and verified keyboardAvoidingView works ok with the change.
