### ISSUE TITLE
Implement auto linking

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#2853]
# Proposal: Add support for auto-linking native modules.  Also consider implementing react-native link (lower priority)

## Summary
With version 60, react-native now supports auto-linking.  This item is tracking making sure RNW supports it as well.  See https://facebook.github.io/react-native/blog/2019/07/03/version-60

In addition we can consider implementing the Linking native module.  See:  https://facebook.github.io/react-native/docs/linking
We'll use this issue to decide whether or not we actually do this work as it might be unnecessary.

**Comment by ahimberg** [comment]
We do have https://github.com/microsoft/react-native-windows/blob/master/vnext/ReactUWP/Modules/LinkingManagerModule.cpp which partially implements the Linking module.

A couple notes:
1) openURL doesn't have all the args we'd probably expect on a windows machine. specifically there is no arg to control if this is an external url where a safety prompt should be included.  We for now do not include the prompt.
2) we're missing initialurl and opensettings.  In our app we looked at doing this but have multiple activation scenarios that the ios/android impl didn't seem to handle so added our own protocol activation events instead

**Comment by chrisglein** [comment]
@kmelmon Is this the same as [this](https://github.com/microsoft/react-native-windows/issues/2132)? Don't want to track in duplicate.

**Comment by kmelmon** [comment]
@chrisglein I'm 90% sure these are separate features.  #2132 involves changes to the CLI which control how your build pulls in other modules at build time, whereas the linking module happens at runtime.

**Comment by ahimberg** [comment]
Yes they're totally different things

**Comment by acoates-ms** [comment]
Added the triage tag back, it sounds like the expo guys would like this module to work, as they use it to open user projects.  -- So maybe that would bump the priority up some.

**Comment by kmelmon** [comment]
Now that we're on version 60 we should make sure we support auto-linking.

From:  https://facebook.github.io/react-native/blog/2019/07/03/version-60

"**Native Modules are now Autolinked
The team working on the React Native CLI has introduced major improvements to native module linking called autolinking! Most scenarios will not require the use of react-native link anymore. At the same time, the team overhauled the linking process in general. Be sure to react-native unlink any preexisting dependencies as mentioned in the docs above.**"

**Comment by ddalp** [comment]
TODO at autlink.js

-- Update main project file to add references to dependencies.
-- Update soluntion file to build dependency native module projects.

**Comment by chrisglein** [comment]
Updated the tile. This issue predates auto linking, but the actual interpretation of this work is to make this sort of thing work on Windows: https://reactnative.dev/docs/linking-libraries-ios#automatic-linking

**Comment by NickGerleman** [comment]
Removing the "must-have" label per recent discussion. This issue does seem super important, but will not be done in time for 0.62. It feels hard to block a release on this item in general until we're closer to having a final implementation.

**Comment by chrisglein** [comment]
Shared project change will be taken for 62, but full auto linking is targeted for 63 now.
