### ISSUE TITLE
Cannot compile after upgraded to VS2019 v16.2

### ISSUE THREAD

**Issue by hmheng** [microsoft/react-native-windows#2854]
1. `react-native -v`: react-native-cli: 2.0.1, react-native: 0.59.10
2. `npm ls rnpm-plugin-windows`: `-- rnpm-plugin-windows@0.2.11
3. `npm ls react-native-windows`: react-native-windows@0.59.0-rc.1
4. `node -v`:v10.16.0
5. `npm -v`: 6.9.0

Facing error after upgraded to VS2019 16.2.

> C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsof
t.AppXPackage.Targets(821,5): error : Certificate could not be opened: RNWebWindows_TemporaryKey.pfx. [D:\PS\Repos\Reac
tNativeLabs\RNWebWindows\windows\RNWebWindows\RNWebWindows.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsof
t.AppXPackage.Targets(821,5): error : The specified network password is not correct. [D:\PS\Repos\ReactNativeLabs\RNWeb
Windows\windows\RNWebWindows\RNWebWindows.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsof
t.AppXPackage.Targets(821,5): error :  [D:\PS\Repos\ReactNativeLabs\RNWebWindows\windows\RNWebWindows\RNWebWindows.cspr
oj]
Build failed with message Error: Command failed: "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\msbuild.exe" "D:/PS/Repos/ReactNativeLabs/RNWebWindows/windows/RNWebWindows.sln" /clp:NoSummary;NoItemAndPropertyList;Verbosity=quiet /nologo /p:Configuration=Debug /p:Platform=x86 /p:AppxBundle=Never /p:PlatformToolset=v142 /p:VisualStudioVersion=16.0. Check your build configuration.

>

**Comment by drcharris** [comment]
This sounds familiar to my issue in #2844 - I managed to fix that, perhaps that will work for you?

**Comment by hmheng** [comment]
@drcharris 
thank you. I've reinstalled 16.0 again to continue my development temporarily.

May I know if you face the issue only after upgraded to VS2019 16.2?

**Comment by drcharris** [comment]
@hmheng I wasn't upgrading - VS2019 was my first install.

**Comment by J4s0nDRevs** [comment]
> @drcharris
> thank you. I've reinstalled 16.0 again to continue my development temporarily. Let me try after the development done ;)
> 
> May I know if you face the issue only after upgraded to VS2019 16.2?

I am having the same problem. did u fixed it? i am uninstalling my VS now

**Comment by mtepro** [comment]
Just as temporary workaround the temp certificate can be removed. With some warnings application starts then.

**Comment by J4s0nDRevs** [comment]
> Just as temporary workaround the temp certificate can be removed. With some warnings application starts then.
how do i remove the temp certificate

**Comment by mtepro** [comment]
There's pfx file in <app_dir>\windows\<app>
Something like <your_app_name>_temporaryCertificate.pfx

**Comment by J4s0nDRevs** [comment]
> There's pfx file in <app_dir>\windows<app>
> Something like <your_app_name>_temporaryCertificate.pfx

wow I didn't thought of just removing it. I know which file is it. but didn't think just removing it works haha thanks

**Comment by liudonghua123** [comment]
I have the same problem.

```
D:\code\react-native\react_native_windows_quickstart> npx react-native run-windows
- Auto-linking...
✔ Auto-linking...
Success: No auto-linking changes necessary. (356ms)
- Found MSBuild v16.0 at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin (16.7.30517.126)
✔ Found MSBuild v16.0 at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin (16.7.30517.126)
- Restoring NuGet packages
(node:26448) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:26448) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:26448) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:26448) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:26448) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:26448) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:26448) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:26448) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:26448) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
(node:26448) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
(node:26448) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
(node:26448) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
(node:26448) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
(node:26448) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
(node:26448) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
(node:26448) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
(node:26448) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
(node:26448) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
(node:26448) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
(node:26448) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
(node:26448) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
(node:26448) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
(node:26448) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
(node:26448) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
(node:26448) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
(node:26448) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
(node:26448) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
(node:26448) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
(node:26448) Warning: Accessing non-existent property 'which' of module exports inside circular dependency
✔ Restoring NuGet packages
- Found Solution: D:\code\react-native\react_native_windows_quickstart\windows\react_native_windows_quickstart.sln
✔ Found Solution: D:\code\react-native\react_native_windows_quickstart\windows\react_native_windows_quickstart.sln
- Build configuration: Debug
ℹ Build configuration: Debug
- Build platform: x86
ℹ Build platform: x86
- Building Solution
✖ Building Solution: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VisualStudi...
- Build failed with message      9>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(831,5): error : Certificate could not be opened: react_native_windows_quickstart_TemporaryKey.pfx. [D:\code\react-native\react_native_windows_quickstart\windows\react_native_windows_quickstart\react_native_windows_quickstart.vcxproj]. Check your build configuration.
✖ Build failed with message      9>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(831,5): error : Certificate could not be opened: react_native_windows_quickstart_TemporaryKey.pfx. [D:\code\react-native\react_native_windows_quickstart\windows\react_native_windows_quickstart\react_native_windows_quickstart.vcxproj]. Check your build configuration.
See C:\Users\LIUD~1.H\AppData\Local\Temp\msbuild_26448.err
Re-run the command with --logging for more information

D:\code\react-native\react_native_windows_quickstart>
```

**Comment by chrisglein** [comment]
> I have the same problem.

@liudonghua123 this issue is a year old, and a lot has happened in that time. Can you open a fresh bug that will better capture your full environment? (the bug template will provide instructions for that)

**Comment by liudonghua123** [comment]
@chrisglein I find `(node:26448) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency` is just a warning, and the error is related with certificate corruption. After I re-run `npx react-native-windows-init --overwrite` I can make it work. But the warnings are still exist.
