### ISSUE TITLE
[BUG] Image onLoad never fires

### ISSUE THREAD

**Issue by Thristhart** [microsoft/react-native-windows#2855]
### Environment
- `npm ls react-native-windows`: `react-native-windows@0.59.0-vnext.109`

- Target Platform Version(s): 10.0.18362.0

- Target Device(s): Xbox

- Visual Studio Version: 2019

- Build Configuration: Debug

### Steps to Reproduce

`<Image source={{uri: "http://someImageUri", width: 240, height: 240}} onLoad={() => console.log("loaded")} />`

### Expected Behavior

onLoad fires, calling `console.log("loaded")`.

### Actual Behavior

onLoad never fires.

### Additional context

After a very light investigation, I think the reason this is happening is that `ImageShadowNode` in `ImageViewManager` is not actually being used, which currently contains all the onLoad event logic.

**Comment by ahimberg** [comment]
@stecrain added this ShadowNode in https://github.com/microsoft/react-native-windows/pull/2667 . but didn't override createShadow on ImageViewManager to use it.

**Comment by stecrain** [comment]
oh man, I can take this one. my bad clearly
