### ISSUE TITLE
ReactNative.dll not found.

### ISSUE THREAD

**Issue by huming-china** [microsoft/react-native-windows#2856]
windowsSDK\bin\10.0.16299.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets(263,5): Xaml Internal Error error WMC9999:  (  from HRESULT:0x80070003)

not found.
\node_modules\react-native-windows\ReactWindows\ReactNative\bin\x64\Release\ReactNative.dll

"react-native": "0.58.0",
 "react-native-windows": "0.58.0-rc.2"
"rnpm-plugin-windows": "^0.2.10"
windows target sdk  10.0.16299.0
windows mini sdk  10.0.14393.0

**Comment by harinikmsft** [comment]
Hello - can you share more details on how you are installing (are you using our CLI?). A sample repo pointer with the bug repro would be good to have.
