### ISSUE TITLE
Investigate the Text api's needed for core parity 

### ISSUE THREAD

**Issue by StephenLPeters** [microsoft/react-native-windows#2865]
Record notes and initial guess at the cost for the unimplemented APIs for the Text control in the rnw core parity status spread sheet.

- [x] selectable
- [x] accessibilityHint 
- [x] accessible
- [x] numberOfLines
- [x] onLayout
- [x] onLongPress
- [x] onPress
- [x] selectionColor

- [ ] ellipsizeMode
- [ ] nativeID
- [ ] pressRetentionOffset
- [ ] allowFontScaling
- [ ] maxFontSizeMultiplier
- [ ] testID
- [ ] disabled
- [ ] textBreakStrategy
- [ ] adjustsFontSizeToFit
- [ ] minimumFontScale
- [ ] suppressHighlighting
- [ ] Nested Text
- [ ] Style Sheet

**Comment by licanhua** [comment]
dup of #2121
