### ISSUE TITLE
Implement the Inspector feature from Developer Menu

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#2872]
# Proposal: Implement the Inspector feature from Developer Menu

## Summary
React-native has an "inspector" that lets you spy on the react-native tree.  We don't support this yet in vnext.  It's supposed to be available from the Developer Menu.  We have a button but it doesn't do anything yet.

**Comment by dotnetjunky** [comment]
I have just merged the commit which lights up the Inpsector.
