### ISSUE TITLE
[VS Code] Debugging Extension is busted for vnext

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#2875]
Currently, using the react-native extension in VS Code to debug react-native apps is busted when using vnext.

This epic is tracking fixing the various issues to establish a baseline of working functionality.  When complete, a dev should be able to:
-Open their react-native project in VS Code.  Primary scenario is an app created with the CLI.
-Add a Debug configuration to their launch.json
-Hit the Debug button and then be able to debug the javascript for their app (set breakpoints, look at locals, and everything else that the VS Code debugging experience supports).

**Comment by akrantz** [comment]
sorry -- accidental click...
