### ISSUE TITLE
[VS Code]Validate the bundle loading for vnext

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#2876]
Currently, when using the VS Code debugging extension for react-native, starting a debugging session is not working.  This issue is tracking one of the issues in that experience.

The issue here is that the VS Code extension was written against 'current' which makes some assumptions about how current works.  It has a "pre warm bundle cache" step which downloads the bundle in parallel with doing a build, which makes it faster to start a debug session.  However this pre-warming step tries to load a bundle using the platform string of "windows".  This won't work on vnext because vnext is doing some things differently than current.  The vs code extension is looking for index.bundle?platform=windows, instead of app.bundle?platform=uwp

So there are 2 problems here:
1) [The platform string is "uwp" instead of "windows"](
https://github.com/microsoft/react-native-windows/issues/2745)
2) The bundle is app.bundle instead of index.bundle

However it's not clear when we'll get to part 1, so we may need to change the VS Code extension in the short term.

For the bundle name part of this issue, we need to decide how to best fix this.  We may want to change the CLI to work similar to how it does on current, or we may decide to keep this as is, and instead change the VS Code extension to look for app.bundle.

Also see this bug on the VS Code side of things:
https://github.com/microsoft/vscode-react-native/issues/1007

**Comment by chrisglein** [comment]
> For the bundle name part of this issue, we need to decide how to best fix this. We may want to change the CLI to work similar to how it does on current, or we may decide to keep this as is, and instead change the VS Code extension to look for app.bundle.

The recommendation here seems to be to change the CLI and go with the flow of whatever the other platforms use as a naming pattern.

**Comment by chrisglein** [comment]
@kmelmon We did the rename. So... what now?

**Comment by kmelmon** [comment]
@chrisglein we still need to do #2901, I just assigned to @savatia

**Comment by savatia** [comment]
Done here: #3099
