### ISSUE TITLE
Implement AccessibilityInfo module

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#2888]
The AccessibilityInfo module provides some utility functions and events for interacting with UIA.

RN60 docs: https://facebook.github.io/react-native/docs/accessibilityinfo

Needed for RNW:
- [ ] isScreenReaderEnabled #3115
- [ ] addEventListener #3159
- [ ] setAccessibilityFocus #3116
- [ ] announceForAccessibility #3117
- [ ] removeEventListener #3158

Out of scope for this issue:
- isBoldTextEnabled (iOS-only)
- isGrayscaleEnabled (iOS-only)
- isInvertColorsEnabled (iOS-only)
- isReduceMotionEnabled
- isReduceTransparencyEnabled (iOS-only)

addEventListener and removeEventListener should allow subscribing to `screenReaderChanged` and `announcementFinished` events.

Possible UWP APIs we'll need:
- isScreenReaderEnabled: https://docs.microsoft.com/en-us/uwp/api/windows.ui.accessibility.screenreaderservice
- setAccessibilityFocus: https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.input.focusmanager.trymovefocus
- announceForAccessibility: https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.automation.peers.automationpeer.raiseautomationevent

**Comment by chrisglein** [comment]
Updated the description above with links to individual issues.
We have one top level issue that has been tracking this already #3016. But really this is moved to a project board: https://github.com/microsoft/react-native-windows/projects/21
