### ISSUE TITLE
[VS Code] Change the CLI bundle name to index.bundle

### ISSUE THREAD

**Issue by harinikmsft** [microsoft/react-native-windows#2901]
This is needed to complete #2876 . 

The decision here is to rename the bundle that is being generated through the CLI to index.bundle to match current as well as iOS/Android instead of the "app.bundle" name that it does today.

**Comment by kmelmon** [comment]
@savatia we think we still need to implement this for pre-warming to work, and to be consistent with the CLI on other platforms.
