### ISSUE TITLE
Picker items should take Text styles

### ISSUE THREAD

**Issue by rhussin** [microsoft/react-native-windows#2907]
# Proposal: Picker items should take Text styles

## Summary
Currently, Picker items only have View props, not Text props.  This makes it impossible to change their font and font size, among other things.  It would be nice to be able to customize the children more easily, or use arbitrary child elements, though for my purposes simply being able to change those two properties (font and font size) would be sufficient.

## Motivation

I am attempting to create search filters using Picker in RNW, but the built-in font and font size in Picker items does not match the design I am trying to implement, and there is no apparent way to change them from typescript. Seeing as they are essentially plain text boxes, I expected their props to reflect that and include text styling.  I believe the IOS Picker already supports this through an itemStyle prop, which would also be helpful.

## Open Questions

Could we ever see child components for these Picker Items?  I'd love to be able to do something like:
<Picker.Item>
    \<Text\>Color:\</Text\>
    \<Text\>Blue\</Text\>
</Picker.Item>

**Comment by chrisglein** [comment]
@rhussin this looks like a nice thing to add but not something we're considering critical for MVP. Are you at all blocked on it? Also, do you know if the iOS solution is also present for Android?

**Comment by rhussin** [comment]
I'm not sure about Android.  Luckily, the base style is _reasonable enough_ that I'm not blocked on it for now.

**Comment by kaiguo** [comment]
I don't think you can put `<Text>` directly inside `<Picker.Item>`, but iOS does support `itemsStyle` property where you can set styles of picker items. I'll probably add something similar in Windows picker.

https://snack.expo.io/@kai2003/picker-itemstyle
