### ISSUE TITLE
missing measureInWindow

### ISSUE THREAD

**Issue by namrog84** [microsoft/react-native-windows#2921]
So I've hit an issue with `TypeError: TaskQueue: Error with task : UIManager.measureInWindow is not a function`
and it looks like "measureInWindow" exists in react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/UIManagerModule.java as a registered function
However, in the react-native-windows/ReactWindowsCore/Modules/UIManagerModule.h/cpp there only exists a "measure" and no "measureInWindow".

It looks like this function is used in various places. One such example is via react-native-safe-area-view. As someone mentioned elsewhere, if this was measureInWindow was just routed to measure. I don't see that as necessarily as a problem. Though I don't know the exact difference in the functions.

**Comment by chrisglein** [comment]
[https://react-native.org/doc/direct-manipulation.html#measureinwindowcallback](https://react-native.org/doc/direct-manipulation.html#measureinwindowcallback)
> measureInWindow(callback)
Determines the location of the given view in the window and returns the values via an async callback. If the React root view is embedded in another native view, this will give you the absolute coordinates. If successful, the callback will be called with the following arguments:
x
y
width
height
```

**Comment by chrisglein** [comment]
@licanhua this has become a blocking issue for one of our partners, so we need attention on it sooner. Can you take a crack at this one?

**Comment by namrog84** [comment]
Awesome!! Thanks!
