### ISSUE TITLE
Implement the receiving of events for EventAnimationDriver

### ISSUE THREAD

**Issue by StephenLPeters** [microsoft/react-native-windows#2941]
The NativeAnimationModule does not properly receive events when making an EventAnimationDriver.

The Naive solution that is implemented by current and andriod implementations involves quite a bit of use of the bridge as the event is raised by the target competent, and then tunneled back to the native side.  We could bypass this exchange, and in some cases remove the need to rely on the UI thread for the event by having shadow nodes declare how to route these events.

Regardless, one of these implementations is needed to complete the NativeAnimationModule.

**Comment by chrisglein** [comment]
Linking back to Stephen's native animated module doc: https://github.com/microsoft/react-native-windows/wiki/NativeAnimatedModule

**Comment by chrisglein** [comment]
Not something we plan to address on the Paper renderer as we move towards Fabric.
Fabric API completion is tracked here: https://github.com/microsoft/react-native-windows/issues/11135
