### ISSUE TITLE
[BUG] Playground app fails with web debugger checked, Chrome launches but not with debugger

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#2943]
If you:
1. Build and run packages\playground
2. Get metro running
3. Load RNTester with web debugger enabled

Expected: Bundle is made, app loads, Chrome launches web debugger

Actual: Chrome launches to blank tab, no bundle, app fails with websocket error

**Comment by kmelmon** [comment]
dupe of #2964
