### ISSUE TITLE
ERROR: Instance failed to start -- A connection with the server could not be estabilished

### ISSUE THREAD

**Issue by bitnota** [microsoft/react-native-windows#2952]
I am trying to run a React UWP remotely from PC to a Raspberry Pi 3 with Windows IOT on the same WiFi Network, using Debug ARM Remote Machine on Visual Studio, but when the app open, it show a red screen with:

`ERROR: Instance failed to start -- A connection with the server could not be estabilished`

I can already use Debug x86 Local Machine and it works well.

PD: Its running with `yarn start` and vnext version

Please help, thank you.

**Comment by kmelmon** [comment]
We don't have any plans to add tooling for this feature.

The manual workaround steps are as follows:
Modify ReactInstanceSettings.debugHost to point to your development server eg "10.192.64.24"
When you do react-native start, supply --host <host ip>
