### ISSUE TITLE
startListeningToAnimatedNodeValue is not a function

### ISSUE THREAD

**Issue by adamgorMSFT** [microsoft/react-native-windows#2980]
startListeningToAnimatedNodeValue is not a function
NativeAnimatedModule.startListeningToAnimatedNodeValue(tag);

https://github.com/microsoft/react-native-windows/blob/6be900885a4fa128dfd637b016b1ad9d23473134/vnext/ReactUWP/Modules/Animated/NativeAnimatedModule.cpp#L241

```
void NativeAnimatedModule::StartListeningToAnimatedNodeValue(int64_t tag) {
  // NotImplemented
}

void NativeAnimatedModule::StopListeningToAnimatedNodeValue(int64_t tag) {
  // NotImplemented
}
```

It looks like its stubbed out but not implemented nor registered.
Please fix. Thanks!

**Comment by StephenLPeters** [comment]
@adamgorMSFT I've been doing some investigations into this and it turns out this particular API rather problematic for our UI thread independent solution.  Can you please share your scenario that requires this? We want to make sure we cover the scenario in test and that we choose the best solution.

**Comment by namrog84** [comment]
@StephenLPeters 

I believe this came from something like this. 

```
const [opacity] = useState(new Animated.Value(0));
    const [focused, setFocused] = useState(false);

    const onPressIn = () => {
        Animated.timing(opacity, {
            toValue: 0.1,
            duration: 150,
            easing: Easing.out(Easing.quad),
            useNativeDriver: true,
        }).start();
    };
    const onPressOut = () => {
        Animated.timing(opacity, {
            toValue: 0,
            duration: 100,
            easing: Easing.in(Easing.quad),
            useNativeDriver: true,
        }).start();
    };

<SomeOtherView 
...
    onPressIn={onPressIn}
    onPressOut={onPressOut}
.../>

<Animated.View style={[styles.overlay, { opacity }]} />

```

**Comment by namrog84** [comment]
Additionally for the
`import { Animated } from 'react-native';`

We use animations directly in a variety of other places.  Here is a quick list of keywords from this module I know we are using in other places in our app, but I think most of these work today.  There could be some additional uses indirectly but I don't think so. 


We use Animated.loop,  Animated.sequence, Animated.parallel,  Animated.timing, Animated.Value, Animated.createAnimatedComponent, Animated.delay, Animated.AnimatedInterpolation,  <Animated.view></Animated.view>, <Animated.ScrollView></Animated.ScrollView>

**Comment by namrog84** [comment]
1 more bit of information. I did a search of our codebase and node_modules, and I only really see 2 places that its called
`react-native\Libraries\Animated\src\NativeAnimatedHelper.js`
`react-native\Libraries\Animated\src\nodes\AnimatedNode.js`

So I am not super knowledgeable about react and how calls are made, or if its being used indirectly somewhere, but I know we never explicitly call `startListeningToAnimatedNodeValue` anywhere. So I am not sure if we aren't actually using it or not, and it's just because its not registered as a native module that its causing an issue.

**Comment by namrog84** [comment]
So I've identified it doesn't have anything to do with the pages themselves.

It is coming from the screen-react navigation somehow

navigation.navigate(routes.detailScreen); causes to hit the function
navigation.navigate(routes.feedbackScreen); doesn't hit it.

in the above example, feedbackScreen is one of the primary pages, but detailScreen occurs dynamically.  If I make feedbackScreen NOT a primary page, it will then start hitting it.

Some kind of indirect thing in navigation seems to be hitting this.

**Comment by StephenLPeters** [comment]
looks like @felisadeang is still hitting this. @asklar what was the fix?

**Comment by StephenLPeters** [comment]
> looks like @felisadeang is still hitting this. @asklar what was the fix?

I clicked on the wrong issue! this one is properly closed.
