### ISSUE TITLE
react-native run-windows hits build error using VS 2019

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#2985]
On a fresh machine with only Visual Studio 2019 installed, I'm unable to successfully build a CLI created app.

Repro Steps:
react-native init foobarapp --version 0.59.10
cd foobarapp
yarn add rnpm-plugin-windows
react-native windows --template vnext
react-native run-windows

RESULT
Build error.  The build output looks like this:
D:\helloworld>react-native run-windows
√ Found NuGet Binary
√ Restoring NuGets
× Build failed with message Error: Must have a minimum Windows SDK version 10.0.10586.0 installed. Check your build configuration.

I am in fact already meeting this requirement as I have SDK version 10.0.18362 installed.

I can workaround the problem by opening the solution in Visual Studio and building from there (strangely this works).  It's just react-native run-windows that is busted.  Somehow msbuild is doing something different and getting confused.

**Comment by 0xbs0d** [comment]
I tried this with and without visual studio. On both occasions it fails with 
× Build failed with message Error: Must have a minimum Windows SDK version 10.0.10586.0 installed. Check your build configuration.

I tried reinstalling the SDK and build tools to no avail. I tried to re-create an empty project but it didn't help. Using VS 2019.

**Comment by chrisglein** [comment]
@marlenecota Where are we on this one with the recent churn? Are we back to the setup steps being correct, or is there a missing requirement?

**Comment by kmelmon** [comment]
On a recent build after the move to 0.60, I no longer repro the issue.  Tried both C++ and C# template apps.  Closing for now.
