### ISSUE TITLE
request to fix unreferenced formal parameter in ToExponential (double-conversion.h)

### ISSUE THREAD

**Issue by adamgorMSFT** [microsoft/react-native-windows#3014]
https://github.com/microsoft/react-native-windows/blob/968d96aa9a3c4c2bb54762a929425729b29a99bc/vnext/stubs/double-conversion/double-conversion.h#L117

requested_digits: unreferenced formal parameter
Warning	C4100	'requested_digits': unreferenced formal parameter (compiling source file <snipped>\node_modules\react-native-windows\stubs\double-conversion\double-conversion.h	117	

inconsequential but because of the way c++ includes work, it gets flagged as warnings and our team tries our best to minimize any warnings. 

Any chance you could change 
`bool ToExponential(double value, int requested_digits, StringBuilder *s)`
to
`bool ToExponential(double value, int /*requested_digits*/, StringBuilder *s)`

**Comment by agarcia-caicedo** [comment]
Hi, I would like to work on this issue
