### ISSUE TITLE
Setup Helix test pipeline

### ISSUE THREAD

**Issue by licanhua** [microsoft/react-native-windows#3018]
Helix provides machines from rs2 to 19h1.

Helix is a test execution environment run by the .net core team. It is a part of the Arcade SDK:
https://github.com/dotnet/arcade
https://github.com/dotnet/arcade/tree/master/src/Microsoft.DotNet.Helix/Sdk

**Comment by chrisglein** [comment]
@licanhua is the main benefit of Helix in this context to get downlevel VMs (which is something we need, but not as part of this milestone as our support commitment is to 19H1), or is there functionality we need out of it sooner?

**Comment by ddalp** [comment]
@chrisglein My understanding is to duplicate the test pipeline running on build machine for down-level OS verifications.

**Comment by licanhua** [comment]
build machine is RS5, and we have some features on 19H1. That's the major reason for helix currently.
Personally I think down-level is not high priority

**Comment by ddalp** [comment]
I see, up-level to 19h1 is the main reason driving the helix, thanks for clarification.
