### ISSUE TITLE
Finish implementation of UniversalTestRunner for RNTester.

### ISSUE THREAD

**Issue by JunielKatarn** [microsoft/react-native-windows#3024]
Project Universal.Integration tests lacks some UWP-specific functionality in its TestRunner implementation.

Finish implementing the test runner to the point the Dummy JS-driven integration test runs successfully in UWP.

**Comment by NickGerleman** [comment]
Closing in favor of #4087 which tracks integration test improvements to support UWP and kill `.windesktop`.
