### ISSUE TITLE
Picker from react-native-windows vs Picker from react-native

### ISSUE THREAD

**Issue by adamgorMSFT** [microsoft/react-native-windows#3036]
We have a 

`import { Picker } from 'react-native';`

But this throws a bunch of weird errors. I was able to get it to work when switching to using 
`import { Picker } from 'react-native-windows';`

Any chance it can be properly piped through react-native?

using versions
"react-native": "0.59.0-microsoft.68"
"react-native-windows": "^0.59.0-vnext.157",

**Comment by licanhua** [comment]
As I know, except Picker, these controls like CheckBox, DatePicker, Popup, Picker should be imported from 'react-native-windows'.

**Comment by adamgorMSFT** [comment]
So if we want to develop for both android, ios, and windows.
We will need to abstract out these things with some kind of Platform.Select or some other conditional mechanism then?

Ideally we'd like to re-use views whenever it makes sense too. 

Aside from switching the import, everything seems to work the same, at least in our scenario.

**Comment by chrisglein** [comment]
Since Picker is being moved out of react-native it shouldn't be in react-native-windows. It probably should be in react-native-picker or something like that.

**Comment by chrisglein** [comment]
https://github.com/react-native-community/react-native-picker

**Comment by namrog84** [comment]
I am not sure what changed, but `import { Picker } from 'react-native';` works for us now and does a drop down and works as intended.

So I believe this can likely be closed/resolved. I am not sure if anything else needs to change internally or not.

**Comment by chrisglein** [comment]
In progress PR: https://github.com/react-native-community/react-native-picker/pull/58
