### ISSUE TITLE
Add C++/WinRT ABI to test DLL

### ISSUE THREAD

**Issue by JunielKatarn** [microsoft/react-native-windows#3052]
# Proposal: Add C++/WinRT ABI to test DLL

## Summary
`React.Windows.Desktop.Test.dll` is not ABI-safe.
Adding the C++/WinRT layer should fix this.

## Motivation

As we progress towards achieving ABI safety for `react-native-win32.dll`, the test DLL is a good starting point for experimentation.

**Comment by chrisglein** [comment]
@JunielKatarn Looks like this test DLL is part of your workstream and not what @licanhua has been building, is that correct? Your comments make it sound like you want to test the waters on the ABI surface here for some other project, not that you need specifics here. Can you clarify the needs/timeline for this proposal?

**Comment by JunielKatarn** [comment]
Hi, @chrisglein.
The timeline is undefined.
For ReactWindows (Desktop), we are experimenting on defining a safe ABI layer for consumption in projects with different compiler toolsets and flags.
Because this test DLL is not production code, it's convenient for such experimentation.

**Comment by NickGerleman** [comment]
Closing this since there hasn't been discussion and there isn't a concrete follow-up action. Feel free to reopen if you disagree.
