### ISSUE TITLE
ScrollView snapToStart

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#3065]
Split out from #2113
_Use in conjunction with `snapToOffsets`. By default, the beginning of the list counts as a snap offset. Set `snapToStart` to false to disable this behavior and allow the list to scroll freely between its start and the first `snapToOffsets` offset. The default value is true._
Not directly supported by ScrollViewer. Can be implemented in conjunction with adding snap points (Win 8) to the child of the ScrollViewer.

**Comment by ddalp** [comment]
Done.
