### ISSUE TITLE
ScrollView snapToEnd

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#3066]
Split out from #2113
_Use in conjuction with `snapToOffsets`. By default, the end of the list counts as a snap offset. Set `snapToEnd` to false to disable this behavior and allow the list to scroll freely between its end and the last `snapToOffsets` offset. The default value is true._
Not directly supported by ScrollViewer. Can be implemented in conjunction with adding snap points (Win 8) to the child of the ScrollViewer.

**Comment by ddalp** [comment]
done.
