### ISSUE TITLE
View removeClippedSubviews

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#3067]
Split out from #2113
_Experimental: When true, offscreen child views (whose overflow value is hidden) are removed from their native backing superview when offscreen. This can improve scrolling performance on long lists. The default value is true._
Not directly supported by ScrollViewer. Seems difficult. Needs deep dive.

**Comment by NickGerleman** [comment]
This now seems to be on View itself, and not experimental. New description at https://reactnative.dev/docs/view#removeclippedsubviews

> This is a reserved performance property exposed by RCTView and is useful for scrolling content when there are many subviews, most of which are offscreen. For this property to be effective, it must be applied to a view that contains many subviews that extend outside its bound. The subviews must also have overflow: hidden, as should the containing view (or one of its superviews).

**Comment by chrisglein** [comment]
Not something we plan to address on the Paper renderer as we move towards Fabric.
Fabric API completion for 'View' is tracked here: https://github.com/microsoft/react-native-windows/issues/11136 (and is completed for Fabric)
