### ISSUE TITLE
ScrollView keyboardDismissMode

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#3068]
Split out from #2113
https://facebook.github.io/react-native/docs/scrollview#keyboarddismissmode
_Determines whether the keyboard gets dismissed in response to a drag._
Not directly supported by ScrollViewer. Mobile-specific. Could be difficult, needs deep dive.

**Comment by ddalp** [comment]
Checked in.

**Comment by ddalp** [comment]
There is a crash on VB build, change will be reverted.

**Comment by ddalp** [comment]
Checked in with crash fixed.
