### ISSUE TITLE
ScrollView refreshControl

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#3069]
Split out from #2113
_A RefreshControl component, used to provide pull-to-refresh functionality for the ScrollView. Only works for vertical ScrollViews (`horizontal` prop must be `false`)._
Not directly supported by ScrollViewer. Could maybe use RefreshContainer from MUX (RS4), or drop down to InteractionTracker (RS1) and build one from scratch.

**Comment by ddalp** [comment]
RefreshControl support checked in.
