### ISSUE TITLE
ScrollView stickyHeaderIndices

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#3070]
Split out from #2113
_An array of child indices determining which children get docked to the top of the screen when scrolling. For example, passing `stickyHeaderIndices={[0]}` will cause the first child to be fixed to the top of the scroll view. This property is not supported in conjunction with `horizontal={true}`._
Not directly supported by ScrollViewer. Seems difficult. Needs deep dive.

**Comment by kmelmon** [comment]
@chrisglein @randy-flynn tells me they need this feature for something inside office.  My instinct is mplementing this will be complex because we can't just leverage ListView, we'll likely need a new implementation based on comp animations, so we should get someone thinking about the design for this soon.

**Comment by ddalp** [comment]
StickyHeaderIndices are implemented using the event driven animation: it creates animated view with the scrollview's children cloned inside, the animated view does some Y translation and is hooked up with scrollView's  onScroll event (ContentOffset -> Y)

#2941 is tracking RNW's event driven animation implementation, I believe the StickyHeaderIndices should just work after event driven animation is done.

**Comment by quicksilverr** [comment]
Any updates on this?

**Comment by ttruongatl** [comment]
+1

**Comment by chrisglein** [comment]
Not something we plan to address on the Paper renderer as we move towards Fabric.
Fabric API completion for `ScrollView` tracked here: https://github.com/microsoft/react-native-windows/issues/11152
