### ISSUE TITLE
ScrollView keyboardShouldPersistTaps

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#3073]
Split out from #2113
https://facebook.github.io/react-native/docs/scrollview#keyboardshouldpersisttaps
_Determines when the keyboard should stay visible after a tap._
Not directly supported by ScrollViewer. Mobile-specific. Could be difficult, needs deep dive.

**Comment by NickGerleman** [comment]
This prop is JS only, so we get it for free and it works as expected on RNW last I played around in the area. Please feel free to reopen if there are any known issues.
