### ISSUE TITLE
Timing module doesn't seem to work correctly

### ISSUE THREAD

**Issue by stecrain** [microsoft/react-native-windows#3076]
### Environment

1. `react-native -v`: 0.59.0-microsoft.71
2. `npm ls rnpm-plugin-windows`: rnpm-plugin-windows@0.2.11
3. `npm ls react-native-windows`: react-native-windows@0.59.0-vnext.167
4. `node -v`: v10.15.0
5. `npm -v`:6.4.1

Then, specify:

- Target Platform Version(s): 10.0.18362
- Target Device(s): Desktop

- Visual Studio Version: 2019

- Build Configuration: Debug

**Comment by stecrain** [comment]
Looking into this, I need to add more detail. but wanted to at least file the issue.

**Comment by chrisglein** [comment]
Thanks, @stecrain. Fill in info when you have it. What do you mean by "doesn't seem to work correctly"?

**Comment by stecrain** [comment]
I'm going to close this for now.
Most of our issues seem related to web debugging, and web debugging is kind of a dead end since it won't work correctly with turbo modules and fabric
