### ISSUE TITLE
ViewStyleProps border*Color

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#3077]
Split out from #2796
https://facebook.github.io/react-native/docs/0.59/view-style-props#borderbottomcolor
- [ ] borderRightColor
- [ ] borderBottomColor
- [ ] borderEndColor
- [ ] borderLeftColor
- [ ] borderStartColor
- [ ] borderTopColor

**Comment by chrisglein** [comment]
The immediate pressure on this has been relieved, so we may not need this for 0.64. However it's also something that coming from web is just expected. In [XAML Border](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.Border?view=winrt-19041) you can have per-side thickness on a border. Which effectively means you can show/hide sides. But you can't specify a different color per side. In order to do that you'd need multiple Border elements or maybe to [drop down to Composition](https://docs.microsoft.com/en-us/windows/uwp/composition/using-the-visual-layer-with-xaml) in some way to draw multiple parts without creating so many heavy-weight objects.

@rectified95, after coming up with some clever options for grafting borders onto Text where they weren't natively supported 1:1, any thoughts on this one?

**Comment by rectified95** [comment]
Unfortunately, this is a different problem. If XAML doesn't provide the needed properties, then we can't hack around way through it in JS like I did with Text borders.

**Comment by chrisglein** [comment]
Not something we plan to address on the Paper renderer as we move towards Fabric.
Fabric API completion for 'View' is tracked here: https://github.com/microsoft/react-native-windows/issues/11136 (and this is completed for Fabric)
