### ISSUE TITLE
TextInput autoComplete

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#3079]
Split out from #2136
https://facebook.github.io/react-native/docs/textinput.html#autocompletetype
Maps to TextBox.IsSpellCheckEnabled (Win8)

**Comment by ddalp** [comment]
Need some clarifications on this property, I don't think it should map to IsSpellCheckEnabled as that will turn on Spelling checking, not auto completion. There is a new feature for VB windows release done by Text Intelligence team where the Auto Completion is turned on for Multiline textBox automatically, but there is no XAML property exposed at this moment yet. We probably should leave this issue open until RNW moves to Lifted XAML and a new XAML property is exposed by Lifted XAML to turn AutoComplete on/off.

**Comment by chrisglein** [comment]
Not something we plan to address on the Paper renderer as we move towards Fabric.
Fabric API completion for TextInput tracked here: https://github.com/microsoft/react-native-windows/issues/11145 (and is completed for Fabric)
