### ISSUE TITLE
secureTextEntry

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#3081]
Split out from #2136
https://facebook.github.io/react-native/docs/textinput.html#securetextentry
Not directly supported by TextBox. PasswordBox has this functionality. Can we hot-swap between TextBox/PasswordBox?

**Comment by ddalp** [comment]
Completed by PR #3075

**Comment by dzunisanindlhovu** [comment]
@chrisglein @ddalp   Is this functionality that isn't available yet? I see that by setting `secureTextEntry` to true on Windows it causes the TextInput to break and not render at all. I tested this on React Native Windows 61
![image](https://user-images.githubusercontent.com/44168415/77033213-d980d800-6963-11ea-8aa1-34dbfb23757b.png)

**Comment by chrisglein** [comment]
> @chrisglein @ddalp Is this functionality that isn't available yet? I see that by setting `secureTextEntry` to true on Windows it causes the TextInput to break and not render at all. I tested this on React Native Windows 61

@dzunisanindlhovu Yes it's supposed to work now. Can you open a new issue with your environment info and repro?
