### ISSUE TITLE
TextInput autoCapitalize

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#3085]
Split out from #2136
facebook.github.io/react-native/docs/textinput.html#autocapitalize
Incomplete support in XAML. This guy is an enum:
-characters: Maps to TextBox.CharacterCasing.Upper (RS3)
-words: Not supported
-sentences: Not directly supported. TextBox.IsSpellCheckEnabled (Win8) turns on auto-capitalizing first word in a sentence (which maps to autoCapitalize.sentences) but this also turns on spell-checking. Also, MikeHill says: Some of the auto capitalization functionality in TextBox is behind the InputScope API.
-none: Supported by default

**Comment by ddalp** [comment]
RichEdit supprts all scenarios, see below tom flags, but we only expose LowerCase and UpperCase for XAML TextBox today. I will add characters support and leave this issue open to be completed after integration with lifted xaml.

 *		tomSentenceCase	= 0: capitalize first letter of each sentence
 *		tomLowerCase	= 1: change all letters to lower case
 *		tomUpperCase	= 2: change all letters to upper case
 *		tomTitleCase	= 3: capitalize the first letter of each word
 *		tomToggleCase	= 4: toggle the case of each letter

**Comment by ddalp** [comment]
Checked in Characters support, Words and Sentences support have to wait until after we use lifted XAML.

**Comment by chrisglein** [comment]
Not something we plan to address on the Paper renderer as we move towards Fabric.
Fabric API completion is tracked here: https://github.com/microsoft/react-native-windows/issues/11145
