### ISSUE TITLE
'Question: [Create a WPF project(Without dying in the attempt)]'

### ISSUE THREAD

**Issue by SaulNunez** [microsoft/react-native-windows#3102]
Here's what I've got:
I made a React Native project with `react-native init myproject --version react-native@0.59.0` and install `npm install --save-dev rnpm-plugin-windows` to help with creating our project.
I need a WPF project so I run `npm i react-native-windows` which in package.json defaults to
```JSON
"react-native-windows": "0.59.0-rc.3"
```
which should be OK because **current** supports WPF.  I run `react-native wpf` and it totally ignores react-native-windows version and installs react-native-windows@0.59.0-vnext.173 which doesn't supports WPF and destroys my hope and somewhat my react native project. Any ideas to how override this?

**Comment by rozele** [comment]
Published PR with fix: https://github.com/microsoft/react-native-windows/pull/3185 will ping back after merge. Thanks for reporting.
