### ISSUE TITLE
Question: how to force a layout update/collect extra updates from shadow node?

### ISSUE THREAD

**Issue by shmax** [microsoft/react-native-windows#3106]
Let's say you have a shadow node react prop like this:

```
[ReactProp("foo")]
public void SetFoo(string value)
{
    this.foo = value;
    MarkUpdated();
    Dirty();
}
```

This will trigger a call to `OnCollectExtraUpdates`, and you can shuttle properties between your shadow node and your native node. No problem.

But what about a situation like this?

```
[ReactProp("imageUri")]
public void SetImage(string uri)
{
	ImageLoader::loadAsync(uri, () => {
      MarkUpdated(); 
      Dirty();
    }   
}
```

In this case, by the time the loading callback fires, the layout update has already finished, and calling `MarkUpdated` or `Dirty` has no effect. Is there a way to force a complete layout update or `OnCollectExtraUpdates` on demand?

**Comment by rozele** [comment]
Not that I'm aware of. The best recommendation I can think of would be to trigger some async API call from JS before setting the prop and triggering the update synchronously. In the case of ImageLoader, I believe there is already a JS module for that.

**Comment by rozele** [comment]
@acoates-ms - is there any such mechanism for triggering an a UI batch internally in vnext? I think you probably don't have this problem because the architecture is slightly different.

**Comment by shmax** [comment]
> Not that I'm aware of. The best recommendation I can think of would be to trigger some async API call from JS before setting the prop and triggering the update synchronously. In the case of ImageLoader, I believe there is already a JS module for that.

> Would this be possible for your use case?

Sure, there are various schemes we can do that involve dancing back and forth over the bridge (we already have something in place), but it involves a lot of boilerplate, and I thought I'd check to see if you knew of a way to drive it all from the native side.

Thanks very much for your insight!
