### ISSUE TITLE
View accessibilityViewIsModal

### ISSUE THREAD

**Issue by SavoySchuler** [microsoft/react-native-windows#3118]
https://facebook.github.io/react-native/docs/accessibility.html#accessibilityviewismodal-ios
Investigating

**Comment by aschultz** [comment]
Will this flag also disable keyboard tab navigation in the sibling elements (and their children)? If not, is there an issue tracking that capability?

For components with semi-transparent overlays that cover buttons and other interactive elements, its critical that there be a mechanism for fully blocking interaction with those underlying elements (without requiring manually setting tabIndex or similar on every single element in the subtree). A simple example here is a centered modal with a full-window acrylic soft-dismiss backdrop, but even smaller components may have temporary overlays that need this.

**Comment by chrisglein** [comment]
Not something we plan to address on the Paper renderer as we move towards Fabric.
Fabric API completion for accessibility is tracked here: https://github.com/microsoft/react-native-windows/issues/11898
