### ISSUE TITLE
'Question: Are there any complete example apps'

### ISSUE THREAD

**Issue by chinwobble** [microsoft/react-native-windows#3141]
I've checked all the docs in this repo and not able to find a complete example.

Is there a complete example of a UWP app with native looking styling, keyboard shortcuts, navigations with native controls, etc.

Thanks

**Comment by licanhua** [comment]
Playground includes examples you need. please follow [BuildingRNW.md](https://github.com/microsoft/react-native-windows/blob/master/vnext/docs/BuildingRNW.md) to build and launch Playground, then select RNTester like below.
![image](https://user-images.githubusercontent.com/6290692/64885281-8d518580-d618-11e9-997d-488274bd0596.png)

the source code of RNTester example is in react-native-windows\vnext\src

**Comment by chinwobble** [comment]
@licanhua Thanks for the quick reply. I tried to run the app and followed all the instructions getting started -vnext guide.
However when I try to run using `react-native run-windows` I get the following error message:
![image](https://user-images.githubusercontent.com/18226001/64916613-050fe380-d7c4-11e9-9c0a-d7053ef8311b.png)

**Comment by licanhua** [comment]
I need more information from you. most likely, it's a timing issue.

Wait until you see 'Loading dependency graph, done'
1. click Load or Reload button on Playground app. If it doesn't work, continue next step
2. Follow [ensure-debugger-is-running](https://github.com/microsoft/react-native-windows/blob/master/vnext/docs/BuildingRNW.md#ensure-debugger-is-running). It will open the chrome Dev Tools, then click Load or Reload Button on Playground app. If it still doesn't work, I expect some error message in chrome dev or the terminal which showed  'Loading dependency graph, done'.
Here is the success output on my machine
![image](https://user-images.githubusercontent.com/6290692/64917523-5ed1c880-d746-11e9-8703-6b4d6bcb8fdb.png)
3. If it still doesn't work, try open Playground solution from visual studio, select debug and X86(or X64) configuration, then deploy and start the Playground.

You may need to share your dev environment information for further investigation.

**Comment by harinikmsft** [comment]
The playground sample app is a good place to start with. We are also at the beginning of a wider samples effort. @YuliKl will update with more info shortly.

**Comment by YuliKl** [comment]
@chinwobble, we recently started a new repo with sample apps: [microsoft/react-native-windows-samples](https://github.com/microsoft/react-native-windows-samples)

The repo's [TodosFeed](https://github.com/microsoft/react-native-windows-samples/tree/master/samples/TodosFeed) sample in particular has several end-to-end scenarios and an accompanying [blog post](https://techcommunity.microsoft.com/t5/Windows-Dev-AppConsult/Getting-started-with-React-Native-for-Windows/ba-p/912093).
