### ISSUE TITLE
Emit AccessibilityInfo Events

### ISSUE THREAD

**Issue by SavoySchuler** [microsoft/react-native-windows#3159]
https://facebook.github.io/react-native/docs/accessibilityinfo.html#addeventlistener
Stub (JS)
Implemented in JS code, not sure if it works

**Comment by NickGerleman** [comment]
This is already provided JS side. We need to properly emit events though.

**Comment by AgneLukoseviciute** [comment]
Note: from @jonthysell in #2888
>addEventListener and removeEventListener should allow subscribing to screenReaderChanged and announcementFinished events.

**Comment by chrisglein** [comment]
Not something we plan to address on the Paper renderer as we move towards Fabric.
Fabric API completion for accessibility is tracked here: https://github.com/microsoft/react-native-windows/issues/11898
