### ISSUE TITLE
TouchableWithoutFeedback  accessibilityTraits

### ISSUE THREAD

**Issue by SavoySchuler** [microsoft/react-native-windows#3161]
Stub (JS)
In JS type definition, never consumed by native code, don't add

**Comment by AgneLukoseviciute** [comment]
Closing as this property has been deprecated https://reactnative.dev/blog/2018/08/13/react-native-accessibility-updates#solution-one-combining-accessibilitycomponenttype-android-and-accessibilitytraits-ios
