### ISSUE TITLE
react-native-windows code should be written in flow

### ISSUE THREAD

**Issue by acoates-ms** [microsoft/react-native-windows#3166]
We currently have a mixture of typescript and flow being used to implement react-native-windows.

All things being equal typescript is a generally preferred language to write things in.  It also means that we get generated typescript type definitions for consumers, most of which are using typescript.

However, since we are implementing a react-native platform, much of the interface that we are writing code against is no the public react-native interface, but internal interfaces within react-native.  These are all written in flow, so the only way to get real type checking if for our files to be written in flow too.

Note:
react-native use Jest for the JS testing and we need to do it too. and it's possible to share the test case.

**Comment by NickGerleman** [comment]
Folks working on `react-native-win32` are also mostly on board. I may bulk convert some stuff once we're on master and typings get worse. I looked around a bit and there's unfortunately not automated tooling to do TS to Flow, only the other way.
