### ISSUE TITLE
Add BlobManager support

### ISSUE THREAD

**Issue by acoates-ms** [microsoft/react-native-windows#3178]
Better Blob support was added in react-native 0.60, but requires a native module to work, which isn't implemented in react-native-windows.

Blobs allow better large file network calls using streams, rather than everything ending up in a single string.

Currently the networking JS call throws internal exceptions attempting to use blobs, which makes it more annoying to have break on exception turned on when debugging JS code.

**Comment by JunielKatarn** [comment]
This is required for WebSockets when setting the `binaryType` to `blob` since RN 0.63.
Starting development.

**Comment by namrog84** [comment]
Hey we recently started hitting this in our upgrade to RN63,  any update on progress on this?

**Comment by JunielKatarn** [comment]
> Hey we recently started hitting this in our upgrade to RN63, any update on progress on this?

#6079 is implementing this. Work in progress.

**Comment by namrog84** [comment]
Just giving update.  We don't actually need this for RN63, it was a red herring, during investigation. It does throw an exception, but its caught and eaten.

**Comment by mandrigin** [comment]
I have compatibility issues with 3rd party libraries because of that in RN63.
Some of these libraries (like amazon's ones) are just assume that you have the latest and greatest blob support and fall apart without it :-/
So far I had to fake it, but if it is possible, I even can help with implementation...

**Comment by JunielKatarn** [comment]
> I have compatibility issues with 3rd party libraries because of that in RN63.
> Some of these libraries (like amazon's ones) are just assume that you have the latest and greatest blob support and fall apart without it :-/
> So far I had to fake it, but if it is possible, I even can help with implementation...

The Blob implementation got de-prioritized, but if this blocking and your are interested, I'd be happy to work with you.
You can start by taking a look at #6079, which is the ongoing implementation.

**Comment by mandrigin** [comment]
Yep, that is my plan, to try to finish #6079

**Comment by JunielKatarn** [comment]
Removing the `ehnancement` label.

This is a required feature.
