### ISSUE TITLE
Animated does not animate Opacity using the native driver

### ISSUE THREAD

**Issue by rhussin** [microsoft/react-native-windows#3180]
### Environment

1. `react-native -v`: react-native-cli: 2.0.1    react-native: 0.59.0-microsoft.82
2. `npm ls rnpm-plugin-windows`: rnpm-plugin-windows@0.2.11
3. `npm ls react-native-windows`: react-native-windows@0.59.0-vnext.187
4. `node -v`: v12.2.0
5. `npm -v`: 6.9.0
:

- Target Platform Version(s): 10.0.18362.0

- Target Device(s): Desktop, Xbox

Desktop OS version: 10.0.18362 Build 18362
Xbox OS version: 18363.7082.amd64fre.19h1_release_xbox_dev_19h2hold_1910.190806-1945

- Visual Studio Version: Visual Studio Enterprise 2019 v. 16.2.0

- Build Configuration: Debug and Release

### Steps to Reproduce

1. Create any Animated component (i.e. `Animated.View`) and give it a style with an animated value for `opacity`.
2. Use an `Animated.timing` to animate that opacity from 0 to 1 or vice versa
3. Observe that it animates without the `useNativeDriver` flag, but does not change at all with `useNativeDriver` on.

### Expected Behavior

From what I have read, `opacity` is one of the two properties that the native driver for Animated definitely supports (The other being `transform`).  Therefore, if my opacity animation works without the native driver, it should also work with it.

### Actual Behavior

When `useNativeDriver` is set to true, the animation simply does not occur.  The Animated.Value remains its initial value.  No error is output, unlike in the situations where the native driver doesn't support the property.

### Reproducible Demo

```ts
import React, { useState, useEffect } from "react";
import { StyleSheet, View, Text, Animated, Easing } from "react-native";

const styles = StyleSheet.create({
    contents: {
        height: 1080,
        width: 1920,
        alignItems: "center",
        justifyContent: "center",
    },
    fadingText: {
        fontSize: 26,
    },
    fadingContainer: {
        alignItems: "center",
        justifyContent: "center",
    },
});

export const FaderModule = () => {
    const [animatedOpacity] = useState(new Animated.Value(1));
    const [fadingContainer] = useState({
        ...styles.fadingContainer,
        opacity: animatedOpacity,
    });

    const fade = () => {
        animatedOpacity.stopAnimation();
        Animated.timing(animatedOpacity, {
            toValue: 0,
            duration: 5000,
            easing: Easing.linear,
            useNativeDriver: true,
        }).start();
    };

    useEffect(fade, []);

    return (
        <View style={styles.contents}>
            <Animated.View style={fadingContainer}>
                <Text style={styles.fadingText}>This should fade!</Text>
            </Animated.View>
        </View>
    );
};
```

### Additional context

The native driver also has a bug with the `transform` property (which I will open a separate issue on #3181), but it *does* mostly work.

**Comment by chrisglein** [comment]
@rhussin Do you happen to know what OS version you were running on? There are animation behaviors in vnext that depend on 18362 (19H1) features. That's the target version you've referenced but not necessarily the min version (or the version this repro'd on).

@StephenLPeters Can you confirm that this is part of the set of behavior that requires 19H1?

@harinikmsft We should get our OS version dependencies for the in-progress vnext effort documented. Do you have a thought about where we want to do that or should I open up a doc issue?

**Comment by StephenLPeters** [comment]
@chrisglein @rhussin @kmelmon  I believe you could get away with RS5 for this, it should only require the opacity facade which I believe came in the first batch of facade changes which were introduced in RS5. Some of the transform changes require 19H1 so to be safe I would say 19H1 is our supported version.

**Comment by rhussin** [comment]
Both my PC and Xbox are running 19H1.

Desktop OS version: 10.0.18362 Build 18362
Xbox OS version: 18363.7082.amd64fre.19h1_release_xbox_dev_19h2hold_1910.190806-1945

**Comment by StephenLPeters** [comment]
Thanks, I'll spend some time investigating today.

**Comment by acoates-ms** [comment]
I enabled the native driver animation RNTester page in the 0.60 PR.  That page seems to crash too.  -- I'm also on a build new enough that it should be supported.  Seems like there are some issues with native driven animations currently.
