### ISSUE TITLE
Animated doesn't properly animate chained Translations using the native driver

### ISSUE THREAD

**Issue by rhussin** [microsoft/react-native-windows#3181]
### Environment

1. `react-native -v`: react-native-cli: 2.0.1    react-native: 0.59.0-microsoft.82
2. `npm ls rnpm-plugin-windows`: rnpm-plugin-windows@0.2.11
3. `npm ls react-native-windows`: react-native-windows@0.59.0-vnext.187
4. `node -v`: v12.2.0
5. `npm -v`: 6.9.0
:

- Target Platform Version(s): 10.0.18362.0

- Target Device(s): Desktop, Xbox

Desktop OS version: 10.0.18362 Build 18362
Xbox OS version: 18363.7082.amd64fre.19h1_release_xbox_dev_19h2hold_1910.190806-1945

- Visual Studio Version: Visual Studio Enterprise 2019 v. 16.2.0

- Build Configuration: Debug and Release

### Steps to Reproduce

1. Create any Animated component (i.e. `Animated.View`) and give it a style with an animated value for `transform`'s `translateX` or `translateY` property.
2. Use an `Animated.timing` to animate that translation to several different values sequentially.
3. Observe that it animates properly from value to value without the `useNativeDriver` flag, but only the first animation works correctly with `useNativeDriver` on.

### Expected Behavior

From what I have read, `transform` is one of the two properties that the native driver for Animated definitely supports (The other being `opacity`).  Therefore, my transform animation should work the same way with or without the native driver.

### Actual Behavior

When `useNativeDriver` is set to true, only the first animation has any effect on the value.  No error is output.
In my real project, I also saw situations where the animation *would* play each time, but its value would be reset to 0 inbetween animations (rather than retaining its current translation to smoothly transition to the next).  However, that's somewhat different from the way that this issue manifested in the minimal reproducible demo, where the animations after the first simply don't play.

### Reproducible Demo

```ts
import React, { useState, useEffect } from "react";
import { StyleSheet, View, Text, Animated, Easing } from "react-native";

const styles = StyleSheet.create({
    contents: {
        height: 1080,
        width: 1920,
        alignItems: "center",
        justifyContent: "center",
    },
    shiftingText: {
        fontSize: 26,
    },
    shiftingContainer: {
        alignItems: "center",
        justifyContent: "center",
    },
});

export const TranslatingModule = () => {
    const [animatedTranslation] = useState(new Animated.Value(0));
    const [shiftingContainer] = useState({
        ...styles.shiftingContainer,
        transform: [{ translateX: animatedTranslation }],
    });

    const shiftSteps = (numStepsLeft: number) => {
        if (numStepsLeft > 0) {
            Animated.timing(animatedTranslation, {
                toValue: (6 - numStepsLeft) * 100,
                duration: 1000,
                easing: Easing.linear,
                useNativeDriver: true,
            }).start(() => {
                shiftSteps(numStepsLeft - 1);
            });
        }
    };

    useEffect(() => {
        shiftSteps(5);
    }, []);

    return (
        <View style={styles.contents}>
            <Animated.View style={shiftingContainer}>
                <Text style={styles.shiftingText}>This should slide smoothly 500px to the right!</Text>
            </Animated.View>
        </View>
    );
};
```

### Additional context

The native driver also has a bug with the `opacity` property not working at all (which I have opened a separate issue on). #3180

**Comment by chrisglein** [comment]
Similar to #3180 this may be related to OS version. I'm told that's true for all of native driver, is likely the same root cause.

**Comment by rhussin** [comment]
I wouldn't be surprised if it was the same root cause, but I *should* be on a supported OS version.

Desktop OS version: 10.0.18362 Build 18362
Xbox OS version: 18363.7082.amd64fre.19h1_release_xbox_dev_19h2hold_1910.190806-1945

**Comment by chrisglein** [comment]
@StephenLPeters this seems to not be working even on 19H1. Can you look?
