### ISSUE TITLE
React-Native-Win32.dll should have proper Version

### ISSUE THREAD

**Issue by NikoAri** [microsoft/react-native-windows#3183]
### Steps to Reproduce

1. Build react-native-win32.dll
(Result is "vnext\target\x64\Debug\React.Windows.Desktop.DLL\react-native-win32.dll")
1. Check its File Version and Product Version
  1. In Windows Explorer
  1. Right Click on react-native-win32.dll
  1. Click Properties
  1. Click Details

### Expected Behavior

Version should be dynamic, ideally match the one which is specified in the Git Tag
git tag | grep 0.59.0-vnext.171
react-native-windows_v0.59.0-vnext.171

Thus File Version should be something like:
0.59.0.171

### Actual Behavior

File Version is static and always:
1000.0.0.0
![image](https://user-images.githubusercontent.com/43590492/65444196-63504e00-dde4-11e9-93ed-5a1d1a93c95a.png)

**Comment by NikoAri** [comment]
Yichen, can you follow up here or we can discuss who it should be assigned to.

Not having a proper version hinders any investigation, especially crashes, as Version is one of core parameters that Watson uses to analyze and bucket failures.

**Comment by acoates-ms** [comment]
The official versions should have the correct build number.  -- Your private builds will have the 1000 version number.

**Comment by hansenyy** [comment]
I took a look at the react-native-win32.dll installed by Office and it indeed has the correct version number:

![image](https://user-images.githubusercontent.com/9127136/65460509-ebdfe600-de06-11e9-8601-c03e7d0aef4e.png)

**Comment by NikoAri** [comment]
What about other binaries that are part of the Nuget?

Product Version looks messed up on React.UWP.dll
![image](https://user-images.githubusercontent.com/43590492/65460848-acfe6000-de07-11e9-8e83-64af93f0837e.png)

React.Windows.Desktop.Test.dll fields are not even set:
![image](https://user-images.githubusercontent.com/43590492/65460908-c7d0d480-de07-11e9-9c42-6c44d23ff65a.png)

**Comment by NickGerleman** [comment]
Closing this, since we're planning on revamping how we do DLL distribution soon anyway. We can readdress if someone needs this.

**Comment by NickGerleman** [comment]
Rather, revamping how we do distribution for anything using Microsoft.ReactNative. Not changing win32 Office but we are doing stamping correctly there.

**Comment by ajaynk123** [comment]
> Closing this, since we're planning on revamping how we do DLL distribution soon anyway. We can readdress if someone needs this.

need this dll file can anyone help?

**Comment by asklar** [comment]
This DLL is produced and used for internal use only.
