### ISSUE TITLE
Remove forked Switch.tsx/js file from RNW

### ISSUE THREAD

**Issue by rurikoaraki** [microsoft/react-native-windows#3188]
# Proposal: Remove forked Switch.tsx/js file from RNW

## Summary

We should remove the forked Switch.tsx/js file once we sync a release of RN that contains [this commit](https://github.com/facebook/react-native/commit/b782934f3f2a80ae7e3872cc7d7a610aa6680ec4).

## Motivation

We wanted to fix a bug in the Switch component in which it would toggle excessively after being invoked once. The fix was committed to RNW first so that the bug would be resolved more quickly for apps that depend on RNW, since it was the only platform visibly showing the bug. However, since the fix was applicable to other platforms using RN as well, there was an ask to port the fix to RN so that RNW doesn't have a fork of Switch.tsx/js from RN if it doesn't need to.

The fix has now been committed to RN. This issue is to track work to remove the fork when RNW gets that commit from RN.

**Comment by chrisglein** [comment]
We'll need to find out what version this shows up in. 62? Let's check in again later in M4.

**Comment by NickGerleman** [comment]
We can do this once we're at 0.62. Adding Deforking label to track.
