### ISSUE TITLE
Switch universal build to require VS2019 and v142 toolset

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#3196]
Microsoft.ReactNative (and the current CPP/WinRT) requires VS 2019 and the 142 toolset.

- [ ] Update all of Universal projects to use v142.
- [ ] Update CI loop to use VMs with VS 2019

**Comment by JunielKatarn** [comment]
Hi. You can assign this to me. #3176 (draft) working on this already.
Note, the Desktop variant **must** stay with v141 for now. Both in CI loops and local development environment.

**Comment by chrisglein** [comment]
@jonthysell this should be all wrapped up now. Let us know if it isn't.
