### ISSUE TITLE
Enable building of SampleApps solution in CI loop

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#3197]
Right now SampleApps is disabled because it runs out of space on the build machines. Mitigations:

- [ ] Build a smaller, common pch to be shared by our projects under vnext and our projects under packages
- [ ] Fix out nuget restore story to make sure we aren't duplicating downloads into different paths, and therby confusing msbuild into building things multiple times.

**Comment by chrisglein** [comment]
@jonthysell this should be unblocked

**Comment by jonthysell** [comment]
**Manager:** Why did you move this to M4?
**Me:** Build's haunted.
**Manager:** Excuse me?
**Me (grabbing gun):** Build's haunted.

**Comment by licanhua** [comment]
Disk should not be a problem anymore.

But it has other issue that some of them requires C# 7.2 or greater:
##[error]vnext\Microsoft.ReactNative.SharedManaged\JSValue.cs(100,36): Error CS8107: Feature 'readonly references' is not available in C# 7.0. Please use language version 7.2 or greater.
##[error]vnext\Microsoft.ReactNative.SharedManaged\JSValueReader.cs(330,9): Error CS8107: Feature 'default literal' is not available in C# 7.0. Please use language version 7.1 or greater.
##[error]vnext\Microsoft.ReactNative.SharedManaged\OneOf.cs(24,35): Error CS8107: Feature 'default literal' is not available in C# 7.0. Please use language version 7.1 or greater.
...
