### ISSUE TITLE
Enable the CLI to create a C++/WinRT native module library that consumes Microsoft.ReactNative

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#3203]
Project should be set up similar to the SampleLibraryCPP sample:

- [ ] C++/WinRT component library
- [ ] Depends only on Microsoft.ReactNative and Microsoft.ReactNative.Cxx
- [ ] Provides a ReactPackageProvider that automatically includes all native modules, and view managers
- [ ] Provides a simple sample native module

**Comment by jonthysell** [comment]
Stretch goal for M3, possibly move to M4.

**Comment by namrog84** [comment]
This sounds super awesome!  We currently have about 15 native packages/modules inside our main app's project and would love an easier time creating new libraries for each one and pull them out properly.

**Comment by jonthysell** [comment]
Potentially considering putting this in [@brodybits/create-react-native-module](https://github.com/brodybits/create-react-native-module), rather than our own CLI.
