### ISSUE TITLE
NM: Add support for native modules accessing ReactContext

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#3208]
CxxModules normally have access to the react instance - we want out native modules to have access to the react context.

**Comment by jonthysell** [comment]
IReactContext exists, but we need to get the new ReactNativeHost straightened out first to fix the ordering.

CxxModules work like this:

- Modules are created.
- Instance is created.
- Instance sets the instance on each module
- Modules use the instance.

But since we're crossing the winrt boundary, we need to pass in the context (wrapped instance) at creation time, since otherwise the modules have no way of getting a context.

**Comment by jonthysell** [comment]
As part of @vmoroz 's hosting work, we should be able to get the correct ReactContext from thread storage for use by the native module.

**Comment by vmoroz** [comment]
It is already implemented by the using the REACT_INIT attribute in C++ and ReactInitializerAttribute in C#. Please see the corresponding sample code in:
- C++: https://github.com/microsoft/react-native-windows/blob/master/packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCPP/SampleModuleCPP.h
- C#: https://github.com/microsoft/react-native-windows/blob/master/packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCS/SampleModuleCS.cs
