### ISSUE TITLE
rnpm-plugin-windows no longer detected by the CLI with RN 0.60.6

### ISSUE THREAD

**Issue by zamotany** [microsoft/react-native-windows#3239]
### Environment

1. `react-native -v`:
    ```
    react-native-cli: 2.0.1
    react-native: 0.60.6
    ```
2. `npm ls rnpm-plugin-windows`: `rnpm-plugin-windows@0.2.11`
3. `npm ls react-native-windows`: `react-native-windows@0.60.0-vnext.3`
4. `node -v`: `v12.10.0`
5. `npm -v`: `6.10.3`
6. `yarn --version`: `1.17.3`

### Steps to Reproduce

Following the steps from [Consuming react native windows](https://github.com/microsoft/react-native-windows/blob/master/vnext/docs/ConsumingRNW.md):

1. `react-native init <project name> --version 0.60.6`
2.  `cd <project name>`
3. `yarn add rnpm-plugin-windows`
4. `react-native windows --template vnext`

### Expected Behavior

React Native Windows specific files to be created.

### Actual Behavior
Command `react-native windows --template vnext` fails:

```
PS C:\Users\user\Documents\TestApp> react-native windows --template vnext
error Unrecognized command "windows"
```

__`rnpm-plugin-windows` is no longer auto-detected__ by the `@react-native-community/cli@2.9.0` installed with `react-native@0.60.0`.

### Workaround

Create `react-native.config.js` file with the following content:
```js
module.exports = {
  commands: require('rnpm-plugin-windows')
}
```

### Additional context

In `@react-native-community/cli@2.9.0` the logic for auto-detection for plugins was removed and the user must explicitly specify what additional commands should be available to `react-native` CLI -
https://github.com/react-native-community/cli/blob/master/docs/plugins.md#migrating-from-rnpm-configuration

### Possible solutions

The quickest solution would be to tell the user to create `react-native.config.js` themselves, then run `react-native windows --template vnext`. The template for `react-native.config.js` would also need to be updated to include `commands: require('rnpm-plugin-windows')`.

---

Another solution is to include a standalone binary in `rnpm-plugin-windows`, without relying on `@react-native-community/cli`.

I can do the PR, but I need some feedback, which direction to go.

cc: @acoates-ms

**Comment by acoates-ms** [comment]
This has been fixed.  We actually already had the fix published, but the version of `rnpm-plugin-windows` with the fix was published as @vnext.  I've corrected the error, so it should work now.
