### ISSUE TITLE
The last item of FlatList is not clickable

### ISSUE THREAD

**Issue by licanhua** [microsoft/react-native-windows#3254]
![image](https://user-images.githubusercontent.com/6290692/65646392-cd691e80-dfaf-11e9-841d-7c947637542b.png)

Like above, launch ReactUWPTestApp, then try to click 'Unknown Page' item with mouse. Instead of a clickable item, a scrollbar showed up and customer can't click the last item.
If it's navigated by Keyboard, then I didn't see this problem.

**Comment by chrisglein** [comment]
@licanhua Why is there a horizontal scrollbar there in the first place? It doesn't look like it should need one. Is this a layout issue? Can you look into the details of the test page? We need more detail.
