### ISSUE TITLE
Add an e2e test for Flyouts

### ISSUE THREAD

**Issue by KAnder425** [microsoft/react-native-windows#3256]
The Flyout is new-ish and unique. It also tends to act like a canary in the coal mine. As such it would benefit from an e2e test, especially now that RNW has a nice e2e framework (thanks @licanhua!)

**Comment by chrisglein** [comment]
@KAnder425 We're probably not going to look into this for a month+. But it'd be great if you can try out our new test infrastructure and add tests yourself. We'd love the feedback, also over time we'll get adding tests to be part of our contribution guide when adding new components.

**Comment by chiaramooney** [comment]
Duplicate. New issue for fabric.
