### ISSUE TITLE
Allow developer to start RNW development without VS or without C++ compiler support

### ISSUE THREAD

**Issue by licanhua** [microsoft/react-native-windows#3257]
Currently RNW is shipped with source code. So VS is mandatory even if customer just want to 'try' or make change to its JS.
Problem1: To compile C++, a large bundle of nuget(1.5G) dependency is downloaded
Problem2: VS is required in our document

There are some possible improvement we can do:
1. ship RNW with binary and nuget, so customer doesn't need to compile RNW project
2. remove the dependency on vs. It really rely on is vsbuild. vsbuild is enough to build things the whole project.
3. Ship RNW app. customer don't need vs or vsbuild anymore. developer just needs to put JS or bundle codes somewhere and RNW app pick it up from there.

**Comment by chrisglein** [comment]
Would an expo client fit your needs here?
There's a lot of potential scenarios here. I'm curious which ones you're most passionate about.
