### ISSUE TITLE
Create test that validates Getting Started CLI steps verbatim

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#3274]
# Proposal: Create test that validates Getting Started CLI steps verbatim

## Summary
Create validation of the [Getting Started](https://github.com/microsoft/react-native-windows/blob/master/vnext/docs/GettingStarted.md) steps as written.
We have some indirect validation through our E2E tests, which use `react-native run-windows`, but there are differences that aren't always caught (example, see #3263 or #2985). A separate daily pipeline built outside of react-native-windows that replicates the developer experience would give us a better safety net.

## Motivation
Any break to our Getting Started steps is very painful to new developers. We promise that those steps work, so we should validate that.

**Comment by NickGerleman** [comment]
We more or less have this right now with the react-native-init job. Recent improvements have been made to make it replicate public instructions as closely as possible.
