### ISSUE TITLE
Identify the gap and merge RNW Javascript with RN 60

### ISSUE THREAD

**Issue by licanhua** [microsoft/react-native-windows#3297]
JavaScript for Windows (in Libraries/) are implemented very long time ago based on Android implementation of React Native like 57. A lot of new added features are missing. for example [[NativeMethodsMixin] CheckBox: Convert NativeMethodsMixin to forwardedRef, convert to class](https://github.com/facebook/react-native/pull/21585)

**Comment by chrisglein** [comment]
I remember you mentioning that you talked to @acoates-ms about what files were missed in the diff with 60. Do we have a list of files that we know we need to go through? Any proposal for how we can track why these files were initially forked and work to drive that number down?
