### ISSUE TITLE
Flyout Component to have new offsets in case it flips

### ISSUE THREAD

**Issue by irakaundal** [microsoft/react-native-windows#3324]
It would be nice to add a functionality to pass offsets (vertical/horizontal) which should be used in case the flyout flips. An e.g. where this is helpful; In case typing in a text input launches a flyout below the text input, then on flipping, the flyout should not be rendered over the text input. It should be able to accept an offset value which can then be used to make it display just above the text.

**Comment by chrisglein** [comment]
@irakaundal By flipping do you mean landscape/portrait device rotation? 
Today we anchor to a target. Are you observing that it doesn't track that as it goes through the "flip"? Or do you want some custom behavior. A picture would be helpful :)
