### ISSUE TITLE
New template project doesn't reference PropertySheets properly (C++)

### ISSUE THREAD

**Issue by namrog84** [microsoft/react-native-windows#3354]
Looks like VisualStudio is considering the root to be \testProject\windows\
and looking here \testProject\windows\PropertySheets\x64.props
but they exist in \testProject\node_modules\react-native-windows\PropertySheets\x64.props

repro steps
```
> npm install -g react-native-cli
> react-native init testProject --version 0.60.6
> cd testProject
> yarn add rnpm-plugin-windows
> react-native windows --template vnext
```

and inside my (testProject/windows/testProject.sln) 
this is where they were added and seemingly have the wrong paths? 
```
Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "PropertySheets", "PropertySheets", "{6F24927E-EE45-4DB2-91DA-DCC6E98B0C42}"
    ProjectSection(SolutionItems) = preProject
        PropertySheets\ARM.props = PropertySheets\ARM.props
        PropertySheets\Debug.props = PropertySheets\Debug.props
        PropertySheets\React.Cpp.props = PropertySheets\React.Cpp.props
        PropertySheets\Release.props = PropertySheets\Release.props
        PropertySheets\Warnings.props = PropertySheets\Warnings.props
        PropertySheets\Win32.props = PropertySheets\Win32.props
        PropertySheets\x64.props = PropertySheets\x64.props
        PropertySheets\x86.props = PropertySheets\x86.props
    EndProjectSection
EndProject
```

Either these files need to be copied to project root, or the paths of where to find them need to be updated.

Presumably, if user is expected to edit/add to these at all, they should be copied, since nothing in node_moduels gets checked into project's git.

**Comment by kmelmon** [comment]
This is a pre-existing issue, copied from the C# template into the C++ template.  We should fix both templates.

Also coates mentioned that "It looks like the template isn't using ReactPackageDirectories.props and ReactCommunity.cpp.props too.  Which it probably should to deal with some of the more complex node_module setups..."

**Comment by kmelmon** [comment]
Moving to Milestone 4 due to other priorities.

**Comment by NickGerleman** [comment]
To my understanding we're by-design not doing this for the current template. Exposing Microsoft.ReactNative as a boundary means consumers shouldn't need to know about internal React directories, compiler settings, etc.

Going to close this for now. @kmelmon  @acoates-ms @jonthysell please reopen if there is still an issue here.

**Comment by namrog84** [comment]
It does look like the main issue I was filing against was solved when it was removed from the generator sln file

From this PR
https://github.com/microsoft/react-native-windows/commit/8afa0a2ba14dbcece63fe659d08dc9b6ced2caf8#diff-dce7d16e2f2d26251d7cab0737c0d110
