### ISSUE TITLE
How to pakage Make an Installation program for RN-windows applications?

### ISSUE THREAD

**Issue by EattingGrass** [microsoft/react-native-windows#3357]
Which part should be add to application Folder when I use visual studio installer to make a Setup Project?

**Comment by licanhua** [comment]
RN-Windows app is an UWP app, and here is procedure to package it.
https://docs.microsoft.com/en-us/windows/msix/package/packaging-uwp-apps

**Comment by EattingGrass** [comment]
Thanks!
