### ISSUE TITLE
"Camera not authorized" message is showing

### ISSUE THREAD

**Issue by sajadj313** [microsoft/react-native-windows#3369]
**Environment:**
React Native : 0.59.10 
RNCamera 3.7.0
React Native for UWP

**Issue**
Camera is not working

**Expected Behavior**
Camera should show the preview when the screen is shown

**Steps to reproduce**

1. Install RNCamera
2. Allow capabilities for the web cam
3. Use the camera library in a component with desire props
4. Run the project
5. Gives an error saying "Camera not authorized"

![Capture3](https://user-images.githubusercontent.com/34274720/66463423-a70cae00-ea9a-11e9-86a4-826103350b7d.PNG)
![Capture1](https://user-images.githubusercontent.com/34274720/66463424-a7a54480-ea9a-11e9-94dc-bee8caf30b5e.PNG)
![Capture2](https://user-images.githubusercontent.com/34274720/66463425-a7a54480-ea9a-11e9-9bb8-3de79902ea3e.PNG)

**Comment by chrisglein** [comment]
Hmm... the bot didn't kick in for this one, but here's the message it was supposed to give:

> We are not investing in new features or lower priority bug fixes on the C# implementation of React Native for Windows (previously known as "vCurrent"). All investment moving forward is in the C++ infrastructure (previously known as "vNext") and that is the only option as of 0.61 (and was the default as of 0.60). If this issue is still relevant on the modern implementation please open a new issue. If this issue is of significant severity for a vCurrent app and vNext is not an option, re-open with justification.

We do have support for react-native-camera on the latest version.
