### ISSUE TITLE
SplitView DisplayModes

### ISSUE THREAD

**Issue by rozele** [Microsoft/react-native-windows#337]
We should have a mechanism for setting the SplitView.DisplayMode

**Comment by souhe** [comment]
@rozele, I would like to do this but I've seen your commit and it looks ok. So what could I do with this issue?

**Comment by rozele** [comment]
`Windows.UI.Xaml.Controls.SplitView` has a `DisplayMode` property that lets you change it from Compact to Overlay or Inline.  There are more details about these modes here: https://msdn.microsoft.com/en-us/windows/uwp/controls-and-patterns/split-view

Unfortunately, there's a larger issue with SplitView in that the layout is not working correctly.  The issue is very apparent when you run the UIExplorer (which uses the SplitView) on Desktop and resize the Window.  The layout of the SplitView shifts from being centered in the window.

**Comment by rozele** [comment]
Closing as there have not been updates on this in some time.
