### ISSUE TITLE
Add autoFocus property to View

### ISSUE THREAD

**Issue by harinikmsft** [microsoft/react-native-windows#3372]
# Proposal: Need ability to set initial focus on any UI component

## Summary

React Native has an `autoFocus` property on `TextInput` element today which allows developers to set initial focus to a TextInput component. We should move/add this property to `View` instead to support keyboard focus. 

## Motivation

With React Native, the mobile-centric usecases are mostly served by having focus concepts only on `TextInput`. This is no longer true in Windows as we have added all focus concepts to View since keyboard focus can be placed on any UI component and react-native-windows apps should be navigable through Keyboard. 

Adding `autoFocus` to `View` completes this story. This was requested by Xbox team. 

## Basic example

With the below code, the initial focus should be on the Button. 

```xml
<View>
   <Button title="Click to read privacy policy"
      autoFocus="true"
      onPress={() => Alert.alert('Privacy policy blah blah text')}
        />
   <Text>Enter your name:</Text>
   <TextInput />
</View>
```
## Open Questions

1. Should this be proposed back to React Native and not necessarily remain in react-native-windows?

**Comment by KAnder425** [comment]
+1 from Stellar. I'm not sure, but I think we can use this to prevent some lost focus issues that we are seeing with our heavy use of Flyouts.

**Comment by harinikmsft** [comment]
Discussion during review:
- Will this conflict with default initial focus behaviors built into native XAML?
- What happens when this is an island of content? Which one wins?
- What happens when more than one element has autoFocus?
- This should also be added to all elements that support other Focus/Key stroke properties - likely includes View, Touchable*, Button, TextInput.
- This is an accessibility requirement and is hard to achieve in client logic using focus events since by the time the client gets a chance to handle this, the component/page has already rendered and may be too late. 
- Earliest this is needed is before 02/2020. Need to kick off conversations with WinUI.

**Comment by harinikmsft** [comment]
Given that this feature is a good-to-have with lots of open issues several of which clash with the native Windows platform accessibility, and is pretty stale at this point, I am closing this. Please reopen if this is a pressing need for your app and we can revisit.
