### ISSUE TITLE
add CLI to collect settings for 'enviroment'

### ISSUE THREAD

**Issue by licanhua** [microsoft/react-native-windows#3374]
When customer report vnext issue, we expect to collect below information, and we should provide CLI to consolidate to one command. For example: yarn run environment

### Environment

1. `react-native -v`:
2. `npm ls rnpm-plugin-windows`:
3. `npm ls react-native-windows`:
4. `node -v`:
5. `npm -v`:
6. `yarn --version`:

Then, specify:

- Target Platform Version(s):

- Target Device(s):

- Visual Studio Version:

- Build Configuration:

**Comment by chrisglein** [comment]
The more time passes the more I think this is an awesome idea that we should do sooner, not later. @licanhua I'm assigning over to you to build a solution.
To my success looks like:
- single easy to run command with no prerequisites beyond whatever you needed to set up to consume RNW (note that yarn is not required for this)
- documented in the bug template
