### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by J-Cake** [microsoft/react-native-windows#3384]
Hi, I'm trying to build React-Native windows but I'm getting these 9 errors.
Yes, I've confirmed I'm following the guide, but VS is throwing errors.

Severity | Code | Description | Project | File | Line | Suppression State
--- | --- | --- | --- | --- | --- | ---
Error | CS0534 | `'App' does not implement inherited abstract member 'ReactApplication.Host.get'` | react_native_windows_test | C:\Users\Jacob Schneider\Code\Projects\react_native_windows_test\windows\react_native_windows_test\App.xaml.cs | 8 | Active
Error | CS0433 | `The type 'ReactNativeHost' exists in both 'ReactNative, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'ReactNative.Net46, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'` | react_native_windows_test | C:\Users\Jacob Schneider\Code\Projects\react_native_windows_test\windows\react_native_windows_test\App.xaml.cs | 10 | Active
Error | CS0433 | `The type 'ReactNativeHost' exists in both 'ReactNative, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'ReactNative.Net46, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'` | react_native_windows_test | C:\Users\Jacob Schneider\Code\Projects\react_native_windows_test\windows\react_native_windows_test\App.xaml.cs | 24 | Active
Error | CS0433 | `The type 'ReactNativeHost' exists in both 'ReactNative.Net46, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'ReactNative, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'` | react_native_windows_test | C:\Users\Jacob Schneider\Code\Projects\react_native_windows_test\windows\react_native_windows_test\MainReactNativeHost.cs | 9 | Active
Error | CS0115 | `'MainReactNativeHost.MainComponentName': no suitable method found to override` | react_native_windows_test | C:\Users\Jacob Schneider\Code\Projects\react_native_windows_test\windows\react_native_windows_test\MainReactNativeHost.cs | 11 | Active
Error | CS0115 | `'MainReactNativeHost.UseDeveloperSupport': no suitable method found to override` | react_native_windows_test | C:\Users\Jacob Schneider\Code\Projects\react_native_windows_test\windows\react_native_windows_test\MainReactNativeHost.cs | 14 | Active
Error | CS0115 | `'MainReactNativeHost.JavaScriptMainModuleName': no suitable method found to override` | react_native_windows_test | C:\Users\Jacob Schneider\Code\Projects\react_native_windows_test\windows\react_native_windows_test\MainReactNativeHost.cs | 19 | Active
Error | CS0433 | `The type 'IReactPackage' exists in both 'ReactNative.Net46, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'ReactNative, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'` | react_native_windows_test | C:\Users\Jacob Schneider\Code\Projects\react_native_windows_test\windows\react_native_windows_test\MainReactNativeHost.cs | 25 | Active
Error | CS0115 | `'MainReactNativeHost.Packages': no suitable method found to override` | react_native_windows_test | C:\Users\Jacob Schneider\Code\Projects\react_native_windows_test\windows\react_native_windows_test\MainReactNativeHost.cs | 25 | Active

**Comment by surminen** [comment]
I see exactly the same errors as above. When building my project without react-navigation, it works fine. As soon as I add the react-navigation package (npm install --save react-navigation), I get the above when building.

**Comment by surminen** [comment]
It is worth mentioning that I am trying to build a very simple react-native-windows project with just a hard-coded text on the main  screen. Nothing else. I am then trying to link in the react-navigation npm project, just linking, not even using it. When I do, the ReactNative.Net46 project appears in Visual Studio, next to the ReactNative project, and the build fails as above.
