### ISSUE TITLE
Consistent naming convention throughout the repo.

### ISSUE THREAD

**Issue by hansenyy** [microsoft/react-native-windows#3385]
Currently the repo used a weird mix of Microsoft's and Facebook's naming conventions. For example, some functions are camelCase (Facebook's convention), while some are PascalCase (Microsoft's convention). We need a somewhat consistent naming convention through out the whole repo. Everything under the Microsoft namespace should follow Microsoft's conventions, and everything under the facebook namespace should follow facebook's conventions.

**Comment by chrisglein** [comment]
Totally agree we should have a firm set of rules here, but by itself this isn't an actionable issue. I'd love to here a more detailed proposal though. Would you mind breaking down your thoughts into some easy to follow rules and point to examples of how we'd transition?

**Comment by hansenyy** [comment]
> Totally agree we should have a firm set of rules here, but by itself this isn't an actionable issue. I'd love to here a more detailed proposal though. Would you mind breaking down your thoughts into some easy to follow rules and point to examples of how we'd transition?

Adding @NikoAri to the discussion, since he is another proponent of a simple but firm set of rules that we can follow.

The two different set of conventions that I have observed are the following:

Microsoft-style convention:
- Variable names are camelCase, with a few prefixes allowed: "m_" for member, "s_" for static, and "g_" for global.
- Function names and class names are both PascalCase.
- Namespace names has their first letter capitalized, e.g. namespace Microsoft.

Facebook-style convention
- Variable names are camelCase. Member variables are suffixed with "_". I have also find some files that used a 'k' prefix to denote constants.
- Function names are camelCase, while class names are PascalCase.
- Namespace names are lower case, e.g. namespace facebook (but then all namespaces are one word, so they could be camelCase or kabob-case.) 

@JunielKatarn have been strongly advocating moving Windows specific code into the Microsoft namespace. I think it would make sense for us to follow the Microsoft-style convention in namespace Microsoft, and follow the Facebook-style convention in namespace facebook.

I don't have a concrete plan, but I feel that this is something we can do alongside moving code into the Microsoft namespace. During our offline discussion, @aeulitz mentioned that it would be nice to have a tool that can automatically check these naming conventions - we are already using clang format. @acoates-ms, do you know if clang format can help us out here as well?

**Comment by NikoAri** [comment]
Here are some guidelines that Cxe has used in the past:
https://microsoft.sharepoint-df.com/:w:/r/teams/cxe/_layouts/15/Doc.aspx?sourcedoc=%7B5AE8C294-68DB-4465-976F-9D6348A1C907%7D&file=Coding%20Conventions.docx&action=default&mobileredirect=true&DefaultItemOpen=1

Here are some guidelines about best C++ coding practice which AlexeiE is trying to consolidate, organize, and promote across Office apps:
https://office.visualstudio.com/Personal/_git/alexeie?path=%2Fdocs%2FAlexeiE-Code-Review.md&version=GBmaster&createIfNew=true&anchor=acknowledgements

**Comment by licanhua** [comment]
Here is the reason why we have mixed naming convention wich is described in #3318
For example, ShadowNodeBase methods:
    removeAllChildren
    AddView

The best way may be keep Facebook-style in the API boundary. Other native code follows Microsoft's style

**Comment by NickGerleman** [comment]
Closing since there's no active discussion. Feel free to reopen if this comes up again.

**Comment by NikoAri** [comment]
So, the end result seems to:
Keep Microsoft naming convention everywhere except when interacting with existing Apis from Facebook?

**Comment by JunielKatarn** [comment]
> So, the end result seems to:
> Keep Microsoft naming convention everywhere except when interacting with existing Apis from Facebook?

Facebook being treated as a third-party dependency, I'd say yes.
GTest, boost and other dependencies will also have their own conventions, which we can't change and may be subject to change..
We should stick with ours.
