### ISSUE TITLE
'Question: VNEXT native modules'

### ISSUE THREAD

**Issue by RonAmihai** [microsoft/react-native-windows#3405]
Does there any docs/information about creating native modules to the VNEXT implementation? 

(Similar to the [existing docs for the CURRENT implementation](https://github.com/microsoft/react-native-windows/blob/master/current/docs/NativeModulesWindows.md) ) 

Is it possible to write native DotNet (C#) extensions to VNEXT? 
Or the only possible method is using UWP's C++ API (WinRT) / Win32 API?

**Comment by licanhua** [comment]
Jon is working on vnext native modules, and his PR #3308 is still under review.
You can comment his PR if you have further question.

**Comment by chrisglein** [comment]
Not yet, but it's on the way! @stmoy can you link to the issue tracking this or better yet the doc?

**Comment by stmoy** [comment]
Hi @RonAmihai - thank you for reaching out. We are actively working on supporting native modules for vNext. We support both C# and C++ implementations. 

Instructions can be found here: [Native Modules](https://github.com/microsoft/react-native-windows/blob/master/vnext/docs/NativeModules.md)

Hope this helps! Please reopen this issue or reach out to me if you have issues.
