### ISSUE TITLE
Live-reload fails after a bit

### ISSUE THREAD

**Issue by kikisaints** [microsoft/react-native-windows#3410]
### Environment

1. `react-native -v`: 
```
react-native-cli: 2.0.1
react-native: 0.60.6
```
2. `npm ls rnpm-plugin-windows`:
```
blankproject@0.0.1 C:\Users\kisai\Documents\RN4W\IgniteDemos\demoproject
`-- rnpm-plugin-windows@0.2.13
```
3. `npm ls react-native-windows`:
```
blankproject@0.0.1 C:\Users\kisai\Documents\RN4W\IgniteDemos\demoproject
`-- react-native-windows@0.60.0-vnext.4
```
4. `node -v`:
```
v10.15.1
```
5. `npm -v`:
```
6.4.1
```

Then, specify:
- Target Platform Version(s): 10.0.18865
- Target Device(s): Desktop/UWP
- Visual Studio Version: 2017
- Build Configuration: Debug

### Steps to Reproduce

1. Create an app
2. Launch server
3. Build and deploy app
4. Make some changes and save
5. Watch live-reload update
6. Repet 4-5 until live-reload stops updating

### Expected Behavior

I would expect it to continue to live-reload, not stop after a certain period of time.

### Actual Behavior

After a while it just shows a blank white app and doesn't reload anything.

**Comment by kikisaints** [comment]
@chrisglein haven't tried yet- I will on Monday.

**Comment by kikisaints** [comment]
@chrisglein

**Comment by kmelmon** [comment]
With Live Refresh, I can no longer repro the instability.  Yay!  
@chrisglein FYI
Closing.
