### ISSUE TITLE
borderBottom/Top/Left/RightWidth doesn't apply

### ISSUE THREAD

**Issue by kikisaints** [microsoft/react-native-windows#3411]
### Environment

1. `react-native -v`: 
```
react-native-cli: 2.0.1
react-native: 0.60.6
```
2. `npm ls rnpm-plugin-windows`:
```
blankproject@0.0.1 C:\Users\kisai\Documents\RN4W\IgniteDemos\demoproject
`-- rnpm-plugin-windows@0.2.13
```
3. `npm ls react-native-windows`:
```
blankproject@0.0.1 C:\Users\kisai\Documents\RN4W\IgniteDemos\demoproject
`-- react-native-windows@0.60.0-vnext.4
```
4. `node -v`:
```
v10.15.1
```
5. `npm -v`:
```
6.4.1
```

Then, specify:

- Target Platform Version(s): 10.0.18865
- Target Device(s): Desktop/UWP
- Visual Studio Version: 2017
- Build Configuration: Debug

### Steps to Reproduce

1. Create an app
2. Set the Bottom/Top/Left/RightWidth style property on a view component
3. Deploy and watch it not display (but will display if deployed to a different platform, like Android)

### Expected Behavior

I would see the border.

### Actual Behavior

I don't see any border.

**Comment by caiolv** [comment]
From what I tested, the color doesn't apply, but the 'margin' of the border is applied.

react-native: 0.61.2

**Comment by chrisglein** [comment]
@kikisaints Did you also set color? That's not support as being different per side on XAML. But the widths should work.

**Comment by chrisglein** [comment]
@kikisaints Can you share the repro markup?
