### ISSUE TITLE
Backdrop Acrylic does not work

### ISSUE THREAD

**Issue by kikisaints** [microsoft/react-native-windows#3412]
### Environment

1. `react-native -v`: 
```
react-native-cli: 2.0.1
react-native: 0.60.6
```
2. `npm ls rnpm-plugin-windows`:
```
blankproject@0.0.1 C:\Users\kisai\Documents\RN4W\IgniteDemos\demoproject
`-- rnpm-plugin-windows@0.2.13
```
3. `npm ls react-native-windows`:
```
blankproject@0.0.1 C:\Users\kisai\Documents\RN4W\IgniteDemos\demoproject
`-- react-native-windows@0.60.0-vnext.4
```
4. `node -v`:
```
v10.15.1
```
5. `npm -v`:
```
6.4.1
```

Then, specify:

- Target Platform Version(s): 10.0.18865
- Target Device(s): Desktop/UWP
- Visual Studio Version: 2017
- Build Configuration: Debug

### Steps to Reproduce

1. Create an app
2. Use the `windowsbrush` API to specifiy an acrylic brush in a component's style
3. Notice that *Host Backdrop* acrylic works, but in app acrylic (*Backdrop*) does not

### Expected Behavior

Backdrop/in-app acrylic should show content behind it, the way the host backdrop shows what's behind the app itself.

### Actual Behavior

The acrylic appears to be in fallback mode, so a solid color is applied.

**Comment by chrisglein** [comment]
@kikisaints Can you provide a bit of repro markup for this?
It's surprising that in-app works but host doesn't, I'd expect the other way around.
Repro screenshot?
