### ISSUE TITLE
Performance and visual issues when height/width both set to '%' on Image

### ISSUE THREAD

**Issue by kikisaints** [microsoft/react-native-windows#3416]
### Environment

1. `react-native -v`: 
```
react-native-cli: 2.0.1
react-native: 0.60.6
```
2. `npm ls rnpm-plugin-windows`:
```
blankproject@0.0.1 C:\Users\kisai\Documents\RN4W\IgniteDemos\demoproject
`-- rnpm-plugin-windows@0.2.13
```
3. `npm ls react-native-windows`:
```
blankproject@0.0.1 C:\Users\kisai\Documents\RN4W\IgniteDemos\demoproject
`-- react-native-windows@0.60.0-vnext.4
```
4. `node -v`:
```
v10.15.1
```
5. `npm -v`:
```
6.4.1
```

Then, specify:

- Target Platform Version(s): 10.0.18865
- Target Device(s): Desktop/UWP
- Visual Studio Version: 2017
- Build Configuration: Debug

### Steps to Reproduce

1. Create an app with an image in it
2. Set that image's style to this:
```
<Image style={{ width: '100%', height: '100%'}} source={imgsource}/>
```
3. Attempt to resize the window
4. Notice the extreme lag
5. Notice the fact that setting the image width/height to 100% offsets your layout by a lot

### Expected Behavior

Layout would remain mostly the same and window re-sizing would be smooth.

### Actual Behavior

Extreme lag on window resizing and layout issues when both height and width are set to a %.

**Note**: If height or width are set to a % separately, meaning only one or the other is set to a %. No issues appear to arise.

**Comment by chrisglein** [comment]
@kikisaints Can you provide a screenshot or better yet a GIF of the resizing behavior?

**Comment by kikisaints** [comment]
@chrisglein hmm, so this no longer repos for me - but a few points to note that could be causing it to no longer repo:

1. I downgraded my Java engine to 1.8
2. I updated my OS
3. I downgraded node js to a version in 8

Any one of those things could have caused this bug to go away. Either way, if it no longer repos for me, and doesn't repo for you perhaps we can close this bug for now.
