### ISSUE TITLE
Proposal for better developer user experience via VM or docker

### ISSUE THREAD

**Issue by licanhua** [microsoft/react-native-windows#3418]
It took hours or days for new customer to setup dev environment successfully to start and evaluate react-native-windows.

The best solution is expo, but I didn't see it supports windows in the next 6 months. We may go with other options: VM and docker.

There is a very good example that customer could finish 'Pre-Configured environments in the cloud for Data Science and AI Development' in less than 15 minutes by [data-science-virtual-machines](https://azure.microsoft.com/en-us/services/virtual-machines/data-science-virtual-machines/)

[azure-pipelines-image-generation](https://github.com/microsoft/azure-pipelines-image-generation) provides procedures and pipeline to build the virtual machine automatically, and it's possible for us to ship VM of react native windows dev enviroment monthly or weekly.

I don't know if docker supports for UWP apps or not, it's also worth to investigate if customer can recover a react native windows dev enviroment by docker.

**Comment by Rechdan** [comment]
Do we have a way of running it inside a Docker container already?
