### ISSUE TITLE
attempt by method 'Newtonsoft.Json.JsonSerializerSettings.."cctor()" to access field 'Newtonsoft.Json.JsonSerializerSettings.DefaultContext' failed.

### ISSUE THREAD

**Issue by admin-excior** [microsoft/react-native-windows#3421]
### Environment

1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.59.10
2. `npm ls rnpm-plugin-windows`:
rnpm-plugin-windows@0.3.5
3. `npm ls react-native-windows`:
react-native-windows@0.59.0-rc.3
4. `node -v`:
v10.16.3
5. `npm -v`:
6.9.0
6. `yarn --version`:
1.19.1
SDK version 
10.0.14393.795
- Target Platform Version(s):
Windows IOT boards
- Target Device(s):
Desktop, Windows IOT boards

- Visual Studio Version:
2019
- Build Configuration:
Debug

1. react-native init <project name> --version 0.59.10
2. cd <project name>
3. npm install --save-dev rnpm-plugin-windows
4. react-native windows
5. react-native run-windows
6. Close CMD, and app emulator then 
7. Re-run react-native run-windows
### Expected Behavior
The app local emulator runs as before 
### Actual Behavior
Red screen with error 
attempt by method 'Newtonsoft.Json.JsonSerializerSettings.."cctor()" to access field 'Newtonsoft.Json.JsonSerializerSettings.DefaultContext' failed.

![Screenshot (4)](https://user-images.githubusercontent.com/54540616/66837938-1e8f8100-ef64-11e9-8b6e-85d7704302a6.png)

### Additional context
It seems un-checking "Enable the visual studio hosting process" helps most people URL: https://stackoverflow.com/questions/7066726/attempt-by-method-system-web-helpers-json-cctor-to-access-method-system-we. I can't seem to find this option in Visual Studio 2019.

**Comment by AddictArts** [comment]
+1
