### ISSUE TITLE
Need to whitelist pngs/gifs submitted to docs directory

### ISSUE THREAD

**Issue by harinikmsft** [microsoft/react-native-windows#3427]
PRs to add docs need not run the CI loop. This is mostly done now, except gifs/pngs/jpeg files added to docs folders also need to be whitelisted to not trigger build pipeline.

**Comment by kartik-budhiraja** [comment]
@harinikmsft, @chrisglein  I would like to work on this issue, if it's available.

**Comment by acoates-ms** [comment]
@kartik-budhiraja  -- absolutely.  PRs welcome!
