### ISSUE TITLE
Is it possible to publish the App to Windows App Store

### ISSUE THREAD

**Issue by veenedu** [microsoft/react-native-windows#3441]
If I build the APP from using react-native-windows, is it then possible to publish the APP to windows store?

**Comment by licanhua** [comment]
yes. react-native windows app is an UWP app, and it has the same procedure as [packaging-uwp-apps](https://docs.microsoft.com/en-us/windows/msix/package/packaging-uwp-apps).
Compared to UWP app, you have to `bundle` the JS, and here is the procedure for this:
[building-a-standalone-react-native-windows-app](https://github.com/microsoft/react-native-windows/blob/master/vnext/docs/ConsumingRNW.md#building-a-standalone-react-native-windows-app)

**Comment by chrisglein** [comment]
Issue tracking providing better documentation here: #3503
