### ISSUE TITLE
react-native-cookies is not supported for windows.

### ISSUE THREAD

**Issue by sakthivel-servicemax** [microsoft/react-native-windows#3448]
react-native-cookies is not supported for windows. It throws error like it supports only ios and android. 

is there  any alternate for this library or do we any solution for cookie storage?

**Comment by chrisglein** [comment]
Support for native modules on vNext is still underway: https://github.com/microsoft/react-native-windows/projects/6
When that is complete we will have information on how to add support for React Native for Windows to community modules, and will be adding support to some of them ourselves.

**Comment by chrisglein** [comment]
In the meantime you can add support for a vCurrent module, although given how close we are to rolling out our vNext solution I think it's better to wait.

**Comment by chrisglein** [comment]
@stmoy When we have our docs lined up can you reply to this and close with instructions?

**Comment by stmoy** [comment]
@sakthivel-servicemax - are you building a vCurrent or vNext app?

**Comment by safaiyeh** [comment]
Want to mention since https://github.com/joeferraro/react-native-cookies went un maintained the community picked up the project. Here: https://github.com/react-native-community/react-native-cookies

Let me know how I could help!

**Comment by chrisglein** [comment]
Closing this module request as not in plan. Not that this module _shouldn't_ receive a Windows implementation, but it makes more sense to track that request on the module's repo rather this repo.
