### ISSUE TITLE
Provide a hook for registering global keyboard shortcuts

### ISSUE THREAD

**Issue by harinikmsft** [microsoft/react-native-windows#3449]
Scenario: Brown field scenarios where the react-native-windows islands content wants to add keyboard shotcuts on the fly without getting bubbled into the native code. 

Copied from Andrew's suggestion below:

Basic design should be something like:
https://johannesklauss.github.io/react-hotkeys-hook/docs-use-hotkeys

We could have the key should be specified as a single string, as in the above package, but I think it probably makes more sense to stick with the interface we have on our keyboarding events, which would take an object:
```
  useHotkeys({key: 'N', ctrlKey: true}, () => setAmount(prevAmount => prevAmount + 100));
```
An array should probably also be an option (in the above library a , deliminated string is valid:
```
  useHotkeys([ {key: 'N', ctrlKey: true}, {key: 'A'} ], () => setAmount(prevAmount => prevAmount + 100));
```
Some thought should be done on if we need to have some way of specifying if it should mark the accelerator as handled.

**Comment by chrisglein** [comment]
@acoates-ms Can you fill out a proposal here?

**Comment by acoates-ms** [comment]
Basic design should be something like: 
https://johannesklauss.github.io/react-hotkeys-hook/docs-use-hotkeys

We could have the key should be specified as a single string, as in the above package, but I think it probably makes more sense to stick with the interface we have on our keyboarding events, which would take an object:

```
  useHotkeys({key: 'N', ctrlKey: true}, () => setAmount(prevAmount => prevAmount + 100));
```

An array should probably also be an option (in the above library a , deliminated string is valid:
```
  useHotkeys([ {key: 'N', ctrlKey: true}, {key: 'A'} ], () => setAmount(prevAmount => prevAmount + 100));
```

Some thought should be done on if we need to have some way of specifying if it should mark the accelerator as handled.

**Comment by harinikmsft** [comment]
Moving to backlog - apps should be unblocked from enabling this through native modules today. The default scenarios should work without any work.
