### ISSUE TITLE
Persistent data storage

### ISSUE THREAD

**Issue by veenedu** [microsoft/react-native-windows#3451]
Which library does it support for persistent data storage?

**Comment by chrisglein** [comment]
@stmoy You're tracking the top set of native modules. What's the most popular one for accessing storage? We likely don't have support for Windows in it yet (unless someone put in vCurrent), but we'll want to when the native modules project is complete (https://github.com/microsoft/react-native-windows/projects/6).

**Comment by chrisglein** [comment]
Would #2271  work for your needs?

**Comment by veenedu** [comment]
No. My application needs some solid database.

**Comment by stmoy** [comment]
@veenedu - it looks like there are several database options that can be used with React Native. [React Native Database – Choosing the right database for your React Native app](https://www.simform.com/react-native-database-selection-guide/)

Is there a particular database that you need us to support? As @chrisglein mentioned, we'll likely need your help figuring out which solution/module you want us to support.

**Comment by stecrain** [comment]
I have had success creating a native module to wrap LevelDB's interface https://github.com/google/leveldb

**Comment by enrico-hic** [comment]
> I have had success creating a native module to wrap LevelDB's interface https://github.com/google/leveldb

Hi @stecrain , is it possible for you to share it? It would be very helpful. Thank you in advance
