### ISSUE TITLE
Make sure that react-native-windows crashes generate Watson reports.

### ISSUE THREAD

**Issue by hansenyy** [microsoft/react-native-windows#3454]
We've using std::terminate() when we need to crash in react-native-windows. @NikoAri pointed out in #3445 that std::terminate() does not generate Watson reports. We ought to fix this.

**Comment by chrisglein** [comment]
Consensus at triage seemed to be that this _does_ generate Watson reports just fine. If you have more information that this doesn't please reactivate (from what I was able to find from poking around the source PR, this was assumed true but not validated).

**Comment by NikoAri** [comment]
@hansenyy can you double check this behavior?

My understanding is that by default std::terminate will call Wer for Release bits, but not for Debug.

This setting should be controlled by _set_abort_behavior Api.

Ideally, this behavior would be the same for Ship and Debug, can you investigate what is right approach here? Ping me if more info is needed.

**Comment by htpiv** [comment]
I don't really know why anyone would want to collect Watson data from debug builds, but if someone did, that would be a decision for the app owner to make, not a library like RNW.

**Comment by NikoAri** [comment]
It's not specifically about Watson service, but rather whether std::terminate in App produces a Crash (Release) or Exits (Debug). The main point here is about consistency. If failure repros in Debug builds it is much easier to investigate. So if someone wants to repro a crash from std::terminate locally, ideally it should produce a crash in Debug bits as well. Currently, default Debug std::terminate just exit the process with error code.

Office Apps do remap Debug std::terminate to a crash, so they are consistent on Release and Debug. 

Yes, we can leave it up to all apps using RNW to choose for themselves std::terminate behavior between flavors.
