### ISSUE TITLE
Need upgrade helper to CLI

### ISSUE THREAD

**Issue by harinikmsft** [microsoft/react-native-windows#3470]
When upgrading, RN CLI has helpers that show diffs between what was before and after in the boiler plate code. We would need to do similar infrastructure for RNW.

**Comment by chrisglein** [comment]
In the meantime, manual support for upgrades is being directed here: https://github.com/react-native-community/upgrade-support

**Comment by chrisglein** [comment]
RNW-specific upgrade help is available here: https://github.com/acoates-ms/rnw-diff

**Comment by chrisglein** [comment]
Upgrade helper now supports RNW with version 0.65. For example: [upgrade from 0.64.15 to 0.65.0](https://react-native-community.github.io/upgrade-helper/?from=0.64.15&to=0.65.0&package=react-native-windows)
