### ISSUE TITLE
Use latest toolset, optionally use v141

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#3476]
allow building with v141, but use the latest toolset installed (v142 for VS2019) by default.

**Comment by JunielKatarn** [comment]
The only concern I have is the following:
Isn't v141 a requirement for dependent projects (i.e. Stellar)?

@acoates-ms do you know the current Universal toolset requirements for office?

**Comment by acoates-ms** [comment]
Yes Stellar needs v141, but the issue here is to allow both.  Normal devs should use v142/VS2019 by default.  But the nuget for stellar should use v141

**Comment by JunielKatarn** [comment]
This should be simple enough for developer workflows, especially if the VS solutions are now split.
We should discuss however how to approach the PR/CI automated builds.

- Should everything regarding universal be built only using v142?
- Should we add another strategy/matrix variant for v141|v142 toolsets?
- Should we only build v141 for those dependencies during the Publish pipeline?

**Comment by asklar** [comment]
> The only concern I have is the following:
> Isn't v141 a requirement for dependent projects (i.e. Stellar)?
> 
> @acoates-ms do you know the current Universal toolset requirements for office?

@KAnder425 was going to investigate if/why Stellar requires v141. Any updates on this?

**Comment by chrisglein** [comment]
@KAnder425 Any updates on Stellar's v141 requirement?

**Comment by qmatteoq** [comment]
I add to this issue that moving to 142 would simplify a lot the adoption of Azure DevOps for building React Native for Windows projects. Currently you can't use a Hosted-Agent, but you're forced to use a private custom agent. The "vs2017-win2016" agent (which comes with Visual Studio 2017 and the v141 tools) isn't suitable because the project uses some C# 7.1 features, which are supported only by Visual Studio 2019. On the other side, the "windows-latest" image can't be leverage because the v141 platform toolset isn't installed in the Visual Studio 2019 version that comes with the hosted agent.

**Comment by licanhua** [comment]
The installation of VS v141 dependencies consumes 4.1G on D, and spend 16 minutes on pipeline.

**Comment by chrisglein** [comment]
@asklar When you were looking into this how much work was needed to change the toolset? We haven't heard justification back from the partner so I say we move to latest. I'd be great to lose the additional setup step and disk cost.

**Comment by lewixlabs** [comment]
Hi!
Any update for this issue?
I have 2 PCs, on which I installed from scratch VS 2019 with all tools needed (UWP development, c++, v141 msbuild tools, etc) and on both PCs I get error: "msbuild tools v141 not found". Only working (annoying) workaround is to install VS 2017 with same development environment (installing into VS 2017 only msbuild tools 2017 doesn't work).
If there is another workaround let me know, thanks guys!

**Comment by qmatteoq** [comment]
Hello @lewixlabs ,
did you install exactly the requirements listed [here](https://github.com/microsoft/react-native-windows/blob/master/vnext/docs/GettingStarted.md)?

* [Visual Studio 2019](https://www.visualstudio.com/downloads) with the following options:
  * Workloads
    * Universal Windows Platform development
      * Enable the optional `C++ (v141) Universal Windows Platform tools`
    * Desktop development with C++
  * Individual Components
    * Compilers, build tools and runtimes
      * MSVC v141 - VS 2017 C++ x64/x86 build tools (v14.16)
      * MSVC v141 - VS 2017 C++ ARM build tools (v14.16)
    * Development activities
      * Node.js development support (optional)

I agree that removing the dependency from v141 would be nice to have, but it shouldn't be a blocker for building on a local machine. On my PC I have installed only Visual Studio 2019 and I can build React Native projects just fine.

**Comment by lewixlabs** [comment]
> Hello @lewixlabs ,
> did you install exactly the requirements listed [here](https://github.com/microsoft/react-native-windows/blob/master/vnext/docs/GettingStarted.md)?
> 
> * [Visual Studio 2019](https://www.visualstudio.com/downloads) with the following options:
>   
>   * Workloads
>     
>     * Universal Windows Platform development
>       
>       * Enable the optional `C++ (v141) Universal Windows Platform tools`
>     * Desktop development with C++
>   * Individual Components
>     
>     * Compilers, build tools and runtimes
>       
>       * MSVC v141 - VS 2017 C++ x64/x86 build tools (v14.16)
>       * MSVC v141 - VS 2017 C++ ARM build tools (v14.16)
>     * Development activities
>       
>       * Node.js development support (optional)
> 
> I agree that removing the dependency from v141 would be nice to have, but it shouldn't be a blocker for building on a local machine. On my PC I have installed only Visual Studio 2019 and I can build React Native projects just fine.

Hi Matteo,
I confirm I installed all requirements you listed.
Yesterday I tried also on a fresh virtual machine (Win10 Pro build 1903) and I got  the same issue.

**Comment by lewixlabs** [comment]
Maybe I'm wrong, but I remember I read RNW searches msbuild tools v141 using an hardcoded path.
Is this an old issue? Probably it has been fixed
