### ISSUE TITLE
borderRadius style attribute for nested Views alters the alignment of content

### ISSUE THREAD

**Issue by Tatious** [microsoft/react-native-windows#3488]
### Environment

react-native-cli: 2.0.1
react-native: 0.60.6
`-- (empty)
`-- react-native-windows@0.60.0-vnext.32
node: v10.16.3
npm: 6.9.0
yarn: 1.17.3

- SDK Version(s):
10.0.18362.0

- Target Device(s):
Desktop

- Visual Studio Version:
Visual Studio 2017

- Build Configuration:
Debug

### Steps to Reproduce
borderRadius style attribute for nested Views alters the alignment of content. If the outer view is given a borderRadius other than the default of 0, the inner View will no longer be centered within the outer View.

First, we create two Views, the outer view being invisible with a white border, the inner being a bluish color. They are separated by a padding of 4.
```
<View
    style={{
        borderWidth: 2,
        padding: 4,
        alignContent: 'center',
        justifyContent: 'center',
        borderColor: COLOR_WHITE,
    }}
>
    <View style={{
        height: 42,
        backgroundColor: '#6666FF',
    }}/>
</View>
```
This produces the following, as expected. 
<img width="630" alt="button1" src="https://user-images.githubusercontent.com/32688486/67307103-d1079c80-f4ac-11e9-8841-e226e62622c0.png">

However, when we apply a borderRadius to the outer View, we get unexpected alignment issues.
```
<View
    style={{
        borderWidth: 2,
        padding: 4,
        alignContent: 'center',
        justifyContent: 'center',
        borderColor: COLOR_WHITE,
        borderRadius:10,
    }}
>
    <View style={{
        height: 42,
        backgroundColor: '#6666FF',
    }}/>
</View>
```
This produces the following. Note how the top & left portions have a larger margin than the bottom & right.
<img width="627" alt="button2" src="https://user-images.githubusercontent.com/32688486/67307113-d369f680-f4ac-11e9-966f-d60e241e31a0.png">

The severity of the issue directly correlates to the borderWidth. As a test, setting padding to something extreme like 40, borderWidth to something small like 1, and borderRadius to 1 (all for the outer View) will result in an offset barely noticeable. However, change borderWidth to 40 and suddenly the offset is much greater. In these tests, the value of the borderRadius did not affect the severity of the error, the only important role that borderRadius played was whether or not it was 0 or >0. If it was zero, nothing would be wrong, as described. But if it was changed to even 1, the correlation between borderWidth and the error would start to show.

### Expected Behavior

The inner View would be centered.

### Actual Behavior

The inner View is offset such that the top and left side have more of a margin.

### Additional context

Adam Gorman(adamgor)
Austin Beaulieu(aubeauli)

**Comment by namrog84** [comment]
+1 on this.

**Comment by ddalp** [comment]
Fix is in.
