### ISSUE TITLE
Vulnerabilities found when running `npm install --save rnpm-plugin-windows`

### ISSUE THREAD

**Issue by ZihanChen-MSFT** [microsoft/react-native-windows#3494]
### Environment

1. `react-native -v`:
react-native-cli: 2.0.1
react-native: n/a - not inside a React Native project directory

2. `npm ls rnpm-plugin-windows`:`-- (empty)
3. `npm ls react-native-windows`:`-- (empty)
4. `node -v`:v12.11.0
5. `npm -v`:6.11.3

Then, specify:

- Target Platform Version(s):10.0.17134.137

- Target Device(s):Desktop

- Visual Studio Version:It doesn't matter

- Build Configuration:It doesn't matter

### Steps to Reproduce

1. Prepare a react-native project template
2. Run `npm install --save rnpm-plugin-windows`

### Expected Behavior

The plugin should be installed without any problem

### Actual Behavior

```
+ rnpm-plugin-windows@0.3.7
added 97 packages from 28 contributors, removed 44 packages, updated 856 packages and audited 951838 packages in 123.518s
found 4 vulnerabilities (3 low, 1 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by asklar** [comment]
These are vulnerabilities in dependencies of npm-registry, which is used by the CLI/new project.
npm-registry hasn't been updated in 5 years and we don't think this is a problem since this only impacts the project creation codepath which only runs once.

**Comment by chrisglein** [comment]
Need to do a pass on dependency updating on rnpm-plugin-windows. Should move out of current into its own separate package.

**Comment by asklar** [comment]
@chrisglein this is still applicable as far as I can tell. Not sure how one goes about fixing this since the vulnerabilities are in the npm-registry package, last updated 5 years ago. So I suppose the fix is for rnpm-plugin-windows to not use npm-registry and instead move to something else (what?)

**Comment by NickGerleman** [comment]
@asklar you likely can find an alternate package, but if not, we could maybe go the route of selective dependency resolution to force new dependencies.

**Comment by NickGerleman** [comment]
The dependency is also used in the new react-native-windows-init. Changing the title since we no longer support rnpm-plugin-windows.

**Comment by NickGerleman** [comment]
This should have been fixed by component governance work.
