### ISSUE TITLE
Projects that are referenced by ReactUWP aren't built with the right config unless they are added to the solution

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#3495]
Customer problem:

> I'm trying to update from 0.60.0.vnext.23 to 0.60.0.vnext.39 and I'm running into a linking error below. I'm building with VS2017.
> 
> Has anyone else seen this?
> 
> "C:\BA\3932\s\node_modules\react-native-windows\ReactUWP\ReactUWP.vcxproj" (default target) (4) ->
> (Link target) -> 
>   Common.lib(Unicode.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in ChakraExecutor.obj [C:\BA\3932\s\node_modules\react-native-windows\ReactUWP\ReactUWP.vcxproj]
>   Common.lib(Unicode.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MD_DynamicRelease' in ChakraExecutor.obj [C:\BA\3932\s\node_modules\react-native-windows\ReactUWP\ReactUWP.vcxproj]
>   Common.lib(Unicode.obj) : error LNK2001: unresolved external symbol __imp__invalid_parameter [C:\BA\3932\s\node_modules\react-native-windows\ReactUWP\ReactUWP.vcxproj]
>   Common.lib(Unicode.obj) : error LNK2001: unresolved external symbol __imp__CrtDbgReport [C:\BA\3932\s\node_modules\react-native-windows\ReactUWP\ReactUWP.vcxproj]
>   MSVCRTD.lib(init.obj) : error LNK2001: unresolved external symbol _CrtDbgReport [C:\BA\3932\s\node_modules\react-native-windows\ReactUWP\ReactUWP.vcxproj]
>   MSVCRTD.lib(init.obj) : error LNK2001: unresolved external symbol _CrtDbgReportW [C:\BA\3932\s\node_modules\react-native-windows\ReactUWP\ReactUWP.vcxproj]
>   C:\BA\3932\s\node_modules\react-native-windows\target\x64\Release\ReactUWP\React.UWP.dll : fatal error LNK1120: 4 unresolved externals [C:\BA\3932\s\node_modules\react-native-windows\ReactUWP\ReactUWP.vcxproj]
>     151 Warning(s)
>     7 Error(s)

Response:
> Check that the Common project is added to your solution. There is an annoying quirk where projects that are referenced by ReactUWP aren't built with the right config unless they are added to the solution
> What I've seen a couple of times is a debug/release config mismatch. If the project is not in the solution seems to just be a coin toss 

To which Harini says:
> That seems annoying. is this something we can fix with the upgrade process?

**Comment by licanhua** [comment]
Most of time, `yarn install` and `yarn build` is enough. If you hit issue, You may delete node_modules, then redo the `yarn install` and `yarn build`

**Comment by chrisglein** [comment]
Maybe the best solution here is to cover it in a troubleshooting guide?

**Comment by chrisglein** [comment]
We don't handle project updates, bringing the app through the transition.

**Comment by NickGerleman** [comment]
This won't be an issue with Microsoft.ReactNative, and we don't expose ReactUwp publicly. Seems like we can close this?

**Comment by ddalp** [comment]
Close the issue since it should not be an issue with Microsoft.ReactNative any more.
