### ISSUE TITLE
Add improved support for Acrylic (such as for blur).

### ISSUE THREAD

**Issue by namrog84** [microsoft/react-native-windows#3506]
Add improved support for Acrylic (blur).

https://docs.microsoft.com/en-us/windows/uwp/design/style/acrylic

previous issue brought up on current (.NET)
https://github.com/microsoft/react-native-windows/issues/1404

**Comment by chrisglein** [comment]
This is supported. Check out this doc:
https://github.com/microsoft/react-native-windows/blob/master/vnext/docs/windowsbrushandtheme.md
Is there something that you still need here that isn't covered by the above?
