### ISSUE TITLE
react-native run-windows on Playground app causes "Failed to deploy" error if not using admin prompt

### ISSUE THREAD

**Issue by harinikmsft** [microsoft/react-native-windows#3518]
Open regular command prompt.

1. Follow all the steps in Getting Started guide
2. Run `yarn build` at the root of the repo
3. Navigate to the playground folder and run `react-native run-windows`

### Expected Behavior

Playground project compiles, metro bundler is started and the app launches successfully

### Actual Behavior

Error in the command window at the last step before installing/deployment of the app:
`Failed to deploy: Fail to check the installed app, maybe developer mode is off on Windows`

Developer mode is ON in Windows settings. The only way to get around this was to retry with admin prompt and it worked.

**Comment by chrisglein** [comment]
@harinikmsft You've updated the readme (thank you). I assume you want this issue to track removing the elevation requirement?

**Comment by liudonghua123** [comment]
I have the same issue, after I run it in a admin cmd, then it works, so the message should be more clear about this. Now the current error message is misunderstand.

**Comment by Lechus** [comment]
same error, running from VS code terminal.
The error message should be clear why.
` × Failed to deploy: Fail to check the installed app, maybe developer mode is off on Windows`

**Comment by linkstrifer** [comment]
Running the project as an Administrator fixed the problem for me

**Comment by parksj10** [comment]
Getting the same failure, except with the following error:

`Add-AppxPackage : Deployment failed with HRESULT: 0x80073D1F, Remote drives are not supported`

This is happening because I'm developing in MacOS and testing on a Windows VM (Parallels), with the Mac repo access happening through a network drive (Z:).

Any suggestions on workarounds/fixes? I think this might become a common issue for Mac developers trying to develop windows apps

**Comment by chrisglein** [comment]
@parksj10 I don't think this issue from last October really captures your scenario. Can you please log a new issue, in particular following the template steps to capture your environment so we can dig into the interaction with your macOS config?
