### ISSUE TITLE
Playground app crashes on re-load

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#3522]
* Native Animation example
* click on any animation and quickly click the Load button to reload
we crash because:
- we destroy the native module list
- but then callbacks from javascript come in and are processed. these callbacks have one of their arguments bound to a native module that got destroyed.
Arguably at the point where the callbacks bind the module, they should be using a smart pointer to make sure that either the module stays in memory or better yet when it goes away, we know and don't do anything when the callback is triggered.

**Comment by asklar** [comment]
Note that this can be triggered without animations in the mix - by double clicking on the Load button in the Playground app.
This could be a problem for hot reload scenarios

**Comment by NickGerleman** [comment]
I think ACoates fixed this specific issue recently. Is there still anything remaining that this tracks?
