### ISSUE TITLE
Getting started for vNext should call out NodeJS 10

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#3528]
The latest NodeJS and the one we get from chocolatey don't work with the react-native-community CLI:
https://github.com/facebook/react-native/issues/26598

Update the RNW docs to tell people about this

**Comment by FLGMwt** [comment]
FYI, 12.9.1 seems to be the latest working version:

Direct downloads: https://nodejs.org/download/release/v12.9.1/

Chocolatey:

```
choco install nodejs.install --version=12.9.1
```
