### ISSUE TITLE
ViewStyleProps backfaceVisibility

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#3538]
Set backfaceVisibility='hidden' on a square with text, it's a no-op. Rotate the item 180 degrees and see the text reversed (should not be shown)
![image](https://user-images.githubusercontent.com/22989529/67661088-8f984680-f91d-11e9-8e83-50eee9a53a89.png)

**Comment by asklar** [comment]
looks like this was an issue for Android until recently. See here https://github.com/facebook/react-native/pull/15970

**Comment by chrisglein** [comment]
Comp supports this but we believe XAML does not. Either needs us to go directly to Comp or add support to XAML in WinUI3.

**Comment by kmelmon** [comment]
A possible solution here would be to stop using the "facade" animation properties and instead animate the underlying Composition Visual directly, by using ElementCompositionPreview.GetElementVisual().  This has the advantage of going further downlevel as well, but has a possible disadvantage:  GetElementVisual is the "old" way of doing animations and isn't compatible with facades.  Stephen Peters pointed out that the WinUI controls use facades on Content controls, so if someone were to wrap a WinUI control and also wrap the Content that goes inside the WinUI control, those controls will be locked into using facades.  We don't currently have any such controls but it could happen someday.

**Comment by chrisglein** [comment]
Not something we plan to address on the Paper renderer as we move towards Fabric.
Fabric API completion is tracked here: https://github.com/microsoft/react-native-windows/issues/11144
