### ISSUE TITLE
Centering a child of a View with borderRadius ignores border size

### ISSUE THREAD

**Issue by Thristhart** [microsoft/react-native-windows#3549]
### Environment

1. `react-native -v`:
```
react-native-cli: 2.0.1
react-native: 0.60.6
```
2. `npm ls rnpm-plugin-windows`:
```
rnpm-plugin-windows@0.3.7
```
3. `npm ls react-native-windows`:
```
react-native-windows@0.60.0-vnext.41
```
4. `node -v`:
```
v10.15.0
```
5. `npm -v`:
```
6.4.1
```

- Target Platform Version(s): 10.0.18362

- Target Device(s): Desktop, Xbox

- Visual Studio Version: 2019

- Build Configuration: Debug and Release

### Steps to Reproduce

(Write your steps here:)

1. Create a View, with any child
2. Style the parent View with a borderWidth and borderRadius, as well as justifyContent: "center" and alignItems: "center"

### Expected Behavior

Child would be centered within its parent, like so:
![image](https://user-images.githubusercontent.com/43013/67725198-c06c9000-f99e-11e9-8f20-11e4351d0409.png)

### Actual Behavior

Child has a marginTop and marginLeft applied that does not take into account the border size, so it ends up pushed down and right equal to the border:
![image](https://user-images.githubusercontent.com/43013/67725275-01fd3b00-f99f-11e9-9ba5-44df5611b0a8.png)

### Reproducible Demo

```jsx
const styles = StyleSheet.create({
  container: {
    borderWidth: 50,
    borderColor: "cornflowerblue",
    borderRadius: 10,
    backgroundColor: "peachpuff",
    width: 240,
    height: 240,
    justifyContent: "center",
    alignItems: "center",
  },
  child: {
    backgroundColor: "yellow",
    alignSelf: "center",
    width: 64,
    height: 64
  }
})

const BorderCenteringRepro = () => {
  return (
    <>
      <View style={styles.container}>
        <View style={styles.child}></View>
      </View>
    </>
  );
};
```

### Additional context

This doesn't happen when the parent has no borderRadius, so presumably this is the result of different handling for borders with a radius.

This is especially annoying when attempting to center text within a circular view, a common pattern in Xbox for notification counts and things like that. We currently work around it by applying negative margins equal to the border width manually.

**Comment by chrisglein** [comment]
Is this something that can be addressed by changing the border policy we use in XAML? https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.border.backgroundsizing

**Comment by ddalp** [comment]
Fix is in.
