### ISSUE TITLE
Multiline TextInput does not behave as expected

### ISSUE THREAD

**Issue by Tatious** [microsoft/react-native-windows#3553]
### Environment
react-native-cli: 2.0.1
react-native: 0.60.6
`-- (empty)
`-- react-native-windows@0.60.0-vnext.45
node: v10.16.3
npm: 6.9.0
yarn: 1.19.1

- SDK Version(s):
10.0.18362.0

- Target Device(s):
Desktop

- Visual Studio Version:
Visual Studio 2017

- Build Configuration:
Debug

### Steps to Reproduce

When wrapped in a fixed height View and a native component with ```flexGrow: 1``` styling, TextInput with a set height will not expand to new lines as expected like on other platforms.
```
const GamepadSupport = requireNativeComponent('GamepadSupport');

export const TextInputWithCount = memo(() => {
    return (
        <View
            style={{
                backgroundColor: '#303030',
                height: 208,
                flex: 1,
            }}
        >
            <GamepadSupport style={{ flexGrow: 1 }}>
                <TextInput
                    style={{
                        height: 48,
                        backgroundColor: '#303030',
                    }}
                    multiline
                />
            </GamepadSupport>
        </View>
    );
});
```

### Expected Behavior

The size of the text box expands as new lines are written. Here the input is 3 separate lines.
<img width="1267" alt="MultiWindowsGood" src="https://user-images.githubusercontent.com/32688486/67796749-d0877c80-fa3d-11e9-9a0d-d4b8ef0cf67e.PNG">

### Actual Behavior

The size of the text box expands as new lines are written. Here the input is 3 separate lines, but we can only see 2, since it didn't expand. This should expand until it reaches the full size of the view, then it should have scrolling text. However, this does not happen, and we get scrolling text inside this smaller TextInput.
<img width="1262" alt="MultiWindowsBad" src="https://user-images.githubusercontent.com/32688486/67796837-f280ff00-fa3d-11e9-8dfc-0f82922cbcbe.PNG">

### Additional context

Adam Gorman(adamgor)
Austin Beaulieu(aubeauli)

**Comment by chrisglein** [comment]
May be an issue in the custom Measure function for TextInput

**Comment by kaiguo** [comment]
@Tatious I feel the current behavior is what I would expect. If you set a fixed height, the height should be fixed. `minHeight` is probably more appropriate for this auto expand scenario, and I just did some quick tests on that, it should be working as expected.
