### ISSUE TITLE
Image from React-Native blurRadius doesn't work

### ISSUE THREAD

**Issue by namrog84** [microsoft/react-native-windows#3556]
As of at least "react-native-windows": "0.60.0-vnext.45",

```
import { Image } from 'react-native';
<Image blurRadius={100} source={someUri} />
```

Currently does nothing.
Should blur the image by some amount. 

example: 
https://www.c-sharpcorner.com/article/how-to-blur-an-image-using-uwp-with-xaml-and-c-sharp/
```
<Image x:Name="imgblur" Source="Assets/01.jpg">  
    <interactivity:Interaction.Behaviors>  
        <behaviors:Blur x:Name="blur" /> </interactivity:Interaction.Behaviors>  
</Image>  
```

It looks like XAML should have support for blurring an image.

So its likely just a bug that its not being piped through correctly?

**Comment by kikisaints** [comment]
Yup! Looks like this is in the backlog, but has not been implemented yet.

You can find the [Image component status here](https://github.com/microsoft/react-native-windows/issues/2111).
And the dev-logged issue for that work [tracked here](https://github.com/microsoft/react-native-windows/issues/2631).

**Comment by namrog84** [comment]
Closing because tracked here https://github.com/microsoft/react-native-windows/issues/2631
