### ISSUE TITLE
VCXProj files rely on SolutionDir

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#3566]
SolutionDir is only set when building inside of VS, so building individual projects is broken (you can only build a whole solution)

**Comment by JunielKatarn** [comment]
Can you provide an example?
I frequently build individual projects directly from the command line.

**Comment by asklar** [comment]
Just about any project that uses SolutionDir is wrong in that the variable is only set by VS. See e.g. Microsoft.ReactNative.vcxproj

**Comment by NickGerleman** [comment]
My understanding is that new versions of MSBuild are aware of solutions? We run raw msbuild in quite a few cases, so we don't seem to be running into issues here. Going to close this, but feel free to reopen if you disagree.
