### ISSUE TITLE
<Image> component should support static svg files

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#3573]
In RN4W, the react-native Image component currently only supports anything that a LoadedImageSurface can load.  This is limited to image file formats (eg JPG, PNG, etc), and not svg.

This issue is tracking allowing the Image react-native component to support .svg files.  Internally XAML does support svg, through both Image and SvgImageSource.  XAML's imaging code needs to know ahead of time if the file is an svg before decoding.  Image.Source has some logic to auto-detect .svg/.svgz file extensions.  At the lower level we have SvgImageSource that's used explicitly for svg files.

What I think the above means for our code is that we should probably do a file extension check and if it is .svg/.svgz, create an SvgImageSource. 

In addition, we'll need a new code path that uses an ImageBrush + SvgImageSource instead of LoadedImageSurface + XCBB.

**Comment by chrisglein** [comment]
@marlenecota This is the call out from the Friday meeting. Can you see what it'd take to get this?

**Comment by marlenecota** [comment]
#3845 adds basic svg support based on file extension. Raw stream is no supported. We also don't currently have a good way to get the width and height off of the svg file, so developers will need to specify them in the Image's style properties.

**Comment by chrisglein** [comment]
@marlenecota you had checked with the partner that some of their images worked. Do they need raw stream support or will they be unblocked with extension based detection?

**Comment by marlenecota** [comment]
> @marlenecota you had checked with the partner that some of their images worked. Do they need raw stream support or will they be unblocked with extension based detection?

They should be unblocked by #3845.

**Comment by chrisglein** [comment]
Opened #3917 to track raw stream support. Closing this issue.
