### ISSUE TITLE
Provide test guideline for native module

### ISSUE THREAD

**Issue by licanhua** [microsoft/react-native-windows#3576]
We don't have test case for native module framework, also doesn't have examples to verify the native modules customer authors.

**Comment by chrisglein** [comment]
@jonthysell Do you have issues tracking this? I assume it's on your work list somewhere.
Sounds like there's two asks here:
- test case
- examples (which I know is already happening)

**Comment by chrisglein** [comment]
Misread this a bit. I think the ask is actually to help community modules test their Windows support so they don't break it as time goes on. @jonthysell and @licanhua can you put your heads together to think through what we can do here that melds well with a probably large amount of difference between community module expectations?
