### ISSUE TITLE
Something is corrupting asyncStorage.txt persist:root on non clean app shutdown

### ISSUE THREAD

**Issue by namrog84** [microsoft/react-native-windows#3579]
Similar but slightly different issue than the one called out here #3392 

That one is specifically calling attention to throwing an exception on async call and it hanging at startup because of a corrupt asyncStorage.txt.  

I am opening this separate but related issue because something is corrupting the asyncStorage.txt in the first place. It appears like sometimes asyncStorage.txt fails to flush the full buffer or something.  There is something, somewhere in AsyncStorage/KeyValueStorage.cpp that I think could be improved.

Specifically if you end process or have an exception shutdown.   And possibly with a moderate amount(300kb) of data being written to asyncStorage.txt.   Something needs to be improved here so that it can either write the full amount, or none at all? (asyncStorage.txt creates multiple lines of persist:root) and I think it'd be better experience to be able to use the last instance of instead of corrupting it and losing all the data stored there.

I think I could repro within a few tries if need more information.

**Comment by chrisglein** [comment]
Plan is to move this to #2271. We don't really want to burn time fixing the existing implementation, unless this is also relevant there.
Since we're likely to start with the existing implementation we'll keep this issue around to track that, but probably not look into before we're making the migration.
@namrog84 Obviously data corruption bad. Is this only happening in the case of a crash?

**Comment by namrog84** [comment]
2 cases it can corrupt. 
    1. an exception is thrown.
    2. clicking visual studio stop debugging (hard shutdown?)

1 case I don't think it corrupts.
    1. hitting the "x" on the window and closing the app normally.


It presents typically presents itself as what looks like an unfinished writing.  Like it was writing out to aynscstorage.txt but gets interrupted before it reaches the proper termination.  So its ends up an invalid data object (json in this case).  I am not really sure what the right fix is here but while its critical for us long term to preserve state between sessions before we launch our product into a beta, it's manageable most of the time right now internally.

**Comment by kmelmon** [comment]
Since this depends on #2271, which is scheduled for M5, moving this to M5 as well.

**Comment by chrisglein** [comment]
If it's going to take awhile to move out AsyncStorage we'll want to fix this first. The app experience is bad.

**Comment by NickGerleman** [comment]
IIRC the native module interface between legacy AsyncStorage and the community version is the same, except for module name where we would want to call it PlatformLocalStorage. I'm guessing current code would be mostly reused regardless? The next generation version of community AsyncStorage changes things, so I'm not sure if that would require rework.

**Comment by ddalp** [comment]
Fixed and will move the code to native module next.
