### ISSUE TITLE
Native animations have variable drift

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#3583]
Scenario 1: Have the same native animation playing side by side (same configuration, just each using a different state variable)
Result: The two animations will not be in sync. This is similar to what I reported in #3537 

Scenario 2: Have a JS and a native animation, both using the same duration, let's say 15000 ms.
Every time an animation is 'completed' have it call into a callback that will log to the console how long it's been since the last time the callback was called, and how much that deviates from 15000ms. Average this number out by the number of animation iterations so far. Call this the average drift.

You'll see that the Native animation drift starts out around 500ms sometimes, but then quickly converges to about 70ms. This is still well above the drift for JS animations which is around 20ms. Anything over 20-25ms is visible and perceived as out of sync.
Even if the animations eventually converge to having a smallish drift, the fact that the first ones have high values means that animations in the wild will be out of sync with each other if they need to be coordinated.

**Comment by chrisglein** [comment]
@asklar Can you provide more info on the code/markup repro so we can better understand and differentiate from the other issue? (#3537 )
