### ISSUE TITLE
Unable to toggle JS debugging from Developer Menu with ReactApplication

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#3610]
Clicking the button refreshes the app, but does not toggle the state. Repros in SampleApps, and new CLI apps.

**Comment by chrisglein** [comment]
Regression from the ReactApplication change?

**Comment by jonthysell** [comment]
> Regression from the ReactApplication change?

Probably, but shouldn't need to be me to fix it.

**Comment by ddalp** [comment]
Fixed.
