### ISSUE TITLE
Optimize the pipeline by reduce the disk usage and build time

### ISSUE THREAD

**Issue by licanhua** [microsoft/react-native-windows#3620]
We are starting to hit the 'not enough space' issue(see  https://dev.azure.com/ms/react-native-windows/_build/results?buildId=47129). Currently I workaround the problem by deleting the buildout of ReactWindows-Desktop.sln before it builds Playground project.

There are possible two places we can improve:
1. Reduce the build time of some jobs
2. We didn't reuse the buildout put of vnext/ReactWindows-Desktop.sln in the next Playground project. so it hits `not enough space`.

not enough space error:
```
 ##[error]C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4365,5): Error MSB3021: Unable to copy file "d:\a\1\s\vnext\target\x64\Debug\ReactUWP\React.UWP.pdb" to "d:\a\1\s\packages\playground\windows\x64\Debug\Playground\React.UWP.pdb". There is not enough space on the disk.
```

**Comment by JunielKatarn** [comment]
I am confused. How is `ReactWindows-Desktop.sln` related to the `Playground` project?
The only failures that show in the link provided are related to the Universal variant.
Do you perhaps mean `ReactWindows-Universal.sln`? The Desktop solution gets build exactly 4 times:
![image](https://user-images.githubusercontent.com/4507319/68433797-455c6400-016c-11ea-854a-bfaae04bbe92.png)

**Comment by acoates-ms** [comment]
Playground is a standalone solution, that look much more like a normal user of RNW would look like.
Its in packages/playground/windows/Playground.sln.

**Comment by chrisglein** [comment]
We either need to address this by upgrading the machine pool (which costs money) or improving our disk usage. We can work on the latter while we're having conversations about the former.

**Comment by licanhua** [comment]
I tried https://devblogs.microsoft.com/cppblog/shared-pch-usage-sample-in-visual-studio/, but I have two problems to go with this solution:
1.	Although only one project used WinUI nuget, to use the shared precompile header, I need to move WinUI dependency to shared-pch project, then all cppwinrt projects depends on WinUI.
2.	The projects have different PreprocessorDefinitions, AdditionalOptions and other settings, and finally the compiler complains the incompatibility with the shared header.

C++ modules may resolve this problem in the future, we it needs compiler support.

For the short term solution:
1. reduce the size of nuget packages by removing duplication. For example #3729 will reduce 1.3G
2. redirect the BaseIntDir part from D to C in pipeline, it will reduce 6G

**Comment by JunielKatarn** [comment]
Should we perhaps rename this issue? It doesn't appear to be related to the Desktop solution.

**Comment by JunielKatarn** [comment]
@licanhua I believe we are placing several `packages` folders in the repo.
One in the root for the Universal and Desktop solution, and one for each Playground/Sample solution location.

If we use environment/build variables smartly, we should be able to consolidate all packages in a single folder, avoiding such duplication.

**Comment by licanhua** [comment]
From the log, build machine has 270G(free 120G) on C drive, and 15G(free 12G) on D. If we can redirect the buildoutput to C, it's possible to allow to build all solutions in job.

DeviceID     : C:
DriveType    : 3
ProviderName : 
FreeSpace    : 120233426944
Size         : 274351517696
VolumeName   : Windows

DeviceID     : D:
DriveType    : 3
ProviderName : 
FreeSpace    : 12003606528
Size         : 15031267328
VolumeName   : Temporary Storage

**Comment by licanhua** [comment]
> @licanhua I believe we are placing several packages folders in the repo.
> One in the root for the Universal and Desktop solution, and one for each Playground/Sample solution location.
> If we use environment/build variables smartly, we should be able to consolidate all packages in a single folder, avoiding such duplication.

#3736 is create to track it
