### ISSUE TITLE
Guide for NativeModules, ViewManagers is missing steps for adding to project

### ISSUE THREAD

**Issue by harinikmsft** [microsoft/react-native-windows#3623]
We need to flesh out the guidance docs for Native modules and View managers to articulate how to actually setup the VS project in addition to what is written down today. 

Additionally, it would be good to add a standalone sample app in [Sample Apps Repo](https://github.com/microsoft/react-native-windows-samples) illustrating both. The current sample app in this repo is confusing to understand since it is an extended package within the repo and has dependencies that do not mimic the external developer's work flow.

**Comment by jonthysell** [comment]
> We need to flesh out the guidance docs for Native modules and View managers to articulate how to actually setup the VS project in addition to what is written down today.

Will do.

> Additionally, it would be good to add a standalone sample app in [Sample Apps Repo](https://github.com/microsoft/react-native-windows-samples) illustrating both. The current sample app in this repo is confusing to understand since it is an extended package within the repo and has dependencies that do not mimic the external developer's work flow.

The current SampleApp in this repo has no extra dependencies, though you're right that you couldn;t just copy and past it into a new repo. However, this would be better captured by a task on the samples repo.
