### ISSUE TITLE
TwoPaneView component

### ISSUE THREAD

**Issue by YuliKl** [microsoft/react-native-windows#3624]
# Proposal: TwoPaneView component

## Summary

Provide a RN component analogous to [TwoPaneView](https://docs.microsoft.com/en-us/uwp/api/microsoft.ui.xaml.controls.twopaneview?view=winui-2.2)

Details being tracked in https://github.com/react-native-community/discussions-and-proposals/issues/197

**Comment by YuliKl** [comment]
This component has a dependency on #3929 and #3931

**Comment by chrisglein** [comment]
Worth adding a link here to the repo where the work is happening: https://github.com/microsoft/react-native-dualscreen
