### ISSUE TITLE
Add ARM64 build configurations

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#3629]
Our RN4W projects are currently missing ARM64 build configurations.  This will be needed to run bits on ARM64 devices (although we can rely on x86 emulation via https://docs.microsoft.com/en-us/windows/uwp/porting/apps-on-arm, ARM64 would be better)...  This task is tracking getting stuff to build on ARM64.

**Comment by kmelmon** [comment]
We'll also need to sort through the native module story - will we need to ensure all native modules have ARM64 configurations?

**Comment by JunielKatarn** [comment]
There is a stale PR for this.
It won’t be trivial (some lower level code may need adjustments).

I can take on this one.

**Comment by jaredhms** [comment]
Attempting to bump the priority on this, as my team is targeting some ARM64 scenarios that we'd like to light up asap.

**Comment by NickGerleman** [comment]
Closing in favor of #4031 which is tracking issues with ARM64.
