### ISSUE TITLE
Text inside a TextInput does not obey padding on the TextInput

### ISSUE THREAD

**Issue by rhussin** [microsoft/react-native-windows#3630]
### Environment

1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.60.0-microsoft.13
2. `npm ls rnpm-plugin-windows`: rnpm-plugin-windows@0.3.7
3. `npm ls react-native-windows`: react-native-windows@0.60.0-vnext.49
4. `node -v`: v12.2.0
5. `npm -v`: 6.9.0
6. `yarn --version`: N/A

Then, specify:

- Target Platform Version(s): 10.0.18362.0

- Target Device(s): Xbox

- Visual Studio Version: Visual Studio Enterprise 2019 v. 16.2.0

- Build Configuration: Debug and Release

### Steps to Reproduce

1. Create a TextInput control and give it a style with non-zero `padding`
2. Observe that the placeholder text does properly shift based on the padding.
3. Try typing something in the box.  Observe that the input text does not obey the padding, unlike the placeholder text.

### Expected Behavior

I expect there to be some way to position the text inside the TextInput.  Ideally, there would be some way to vertically align the text as well, but that also doesn't seem to work in any way I've tested.

### Actual Behavior

The placeholder text obeys `padding`, but the input text does not.  Neither of them seem to care about `alignContent`, `alignItems`, `justifyContent`, or `textAlignVertical`.

Placeholder text:
![image](https://user-images.githubusercontent.com/7649133/68520662-406fe100-024e-11ea-8714-1bb642277cd0.png)

Input text:
![image](https://user-images.githubusercontent.com/7649133/68520707-d277e980-024e-11ea-8c3a-fbc6cb96bcc3.png)

### Reproducible Demo

```
import React from "react";
import { StyleSheet, TextInput, View } from "react-native";

const styles = StyleSheet.create({
    page: {
        alignItems: "center",
        marginTop: 100,
    },
    input: {
        width: 1000,
        height: 64,
        fontSize: 26,
        marginVertical: 10,
    },
});

export const TextInputStylingDemo = () => {
    const withPadding = [
        styles.input,
        {
            paddingLeft: 30,
            paddingTop: 10,
        },
    ];

    const withVerticalAlign = [
        styles.input,
        {
            textAlignVertical: "center" as "center",
        },
    ];

    const withAlignItems = [
        styles.input,
        {
            alignItems: "center" as "center",
            alignContent: "center" as "center",
            justifyContent: "center" as "center",
        },
    ];

    return (
        <View style={styles.page}>
            <TextInput style={withPadding} placeholder={"withPadding"} />
            <TextInput style={withVerticalAlign} placeholder={"withVerticalAlign"} />
            <TextInput style={styles.input} textAlignVertical={"center"} placeholder={"withVerticalAlignProp"} />
            <TextInput style={withAlignItems} placeholder={"withAlignItems"} />
        </View>
    );
};
```

**Comment by ddalp** [comment]
@rhussin  I could not repro the issue with the latest VNext bits, could you upgrade and try it out? Please reactivate if it still repro for you.
![image](https://user-images.githubusercontent.com/30847337/68720624-bc2aa000-0564-11ea-9002-92666b901536.png)

**Comment by rhussin** [comment]
I'm still seeing the same behavior as before, trying with:
```
  "react-native": "https://github.com/microsoft/react-native/archive/v0.60.0-microsoft.20.tar.gz",
  "react-native-windows": "0.60.0-vnext.71",
```

**Comment by rhussin** [comment]
I don't have the permission level required to reopen this issue, @ddalp.  It looks like if a Contributor closes an issue, a non-Contributor cannot re-open it.

**Comment by ddalp** [comment]
Reopened and will get clarifications on re-pro.

**Comment by rhussin** [comment]
Hold on, don't put any work into this just yet - I may not have properly upgraded RN and RNW before reproing this; our build system confused me briefly.  I'm closing again for now, I'll reopen if I confirm it is definitely still an issue.  Sorry for the confusion!
