### ISSUE TITLE
NativeModule Setup(Manually Adding Windows Support) failed

### ISSUE THREAD

**Issue by enm10k** [microsoft/react-native-windows#3633]
### Environment

1. `react-native -v`:
2. `npm ls rnpm-plugin-windows`:
3. `npm ls react-native-windows`:
4. `node -v`:
5. `npm -v`:
6. `yarn --version`:

```
C:\Users\enm10k\shiguredo\react-native-webrtc-kit>react-native -v
react-native-cli: 2.0.1
react-native: 0.60.6

C:\Users\enm10k\shiguredo\react-native-webrtc-kit>npm ls rnpm-plugin-windows
react-native-webrtc-kit@3.0.0 C:\Users\enm10k\shiguredo\react-native-webrtc-kit
`-- (empty)


C:\Users\enm10k\shiguredo\react-native-webrtc-kit>npm ls react-native-windows
react-native-webrtc-kit@3.0.0 C:\Users\enm10k\shiguredo\react-native-webrtc-kit
`-- react-native-windows@0.60.0-vnext.68  extraneous

npm ERR! extraneous: react-native-windows@0.60.0-vnext.68 C:\Users\enm10k\shiguredo\react-native-webrtc-kit\node_modules\react-native-windows

C:\Users\enm10k\shiguredo\react-native-webrtc-kit>node -v
v12.9.0

C:\Users\enm10k\shiguredo\react-native-webrtc-kit>npm -v
6.10.2

C:\Users\enm10k\shiguredo\react-native-webrtc-kit>yarn --version
1.17.3
```

- Target Platform Version(s): 10.0.18362.0

- Target Device(s): Desktop

- Visual Studio Version: Visual Studio 2019 (v142)

- Build Configuration: Debug(x64)

### Steps to Reproduce

1. Tried https://github.com/microsoft/react-native-windows/blob/8afa0a2/vnext/docs/NativeModulesSetup.md#manually-adding-windows-support

### Expected Behavior

The testing build is successful.

### Actual Behavior

The testing build failed with the following message.

```
1>------ ビルド開始: プロジェクト: ReactNativeWebRTCKit, 構成: Debug x64 ------
1>ModuleRegistration.cpp
1>C:\Users\enm10k\shiguredo\react-native-webrtc-kit\node_modules\react-native-windows\Microsoft.ReactNative.Cxx\ModuleRegistration.h(5,10): error C1083:  include ファイルを開けません。'winrt/Microsoft.ReactNative.Bridge.h':No such file or directory
1>プロジェクト "ReactNativeWebRTCKit.vcxproj" のビルドが終了しました -- 失敗。
========== ビルド: 0 正常終了、1 失敗、6 更新不要、0 スキップ ==========
```

The error message says `node_modules\react-native-windows\Microsoft.ReactNative.Cxx\ModuleRegistration.h` cannot include `winrt/Microsoft.ReactNative.Bridge.h`.

### Reproducible Demo

My solution file and project file is here https://github.com/shiguredo/react-native-webrtc-kit/commit/7a290c6c195298c77017215ab4b6bf79365aa41a .

### Additional context

(Write any other additional context that may help in root causing the issue.)

**Comment by jonthysell** [comment]
First off, you seem to have created a C++/CX project. While that may work, it's not a scenario supported in the setup doc. If you want to use C++, you should use C++/WinRT. You'll need to install an extension to get the C++/WinRT project types:

>If you're planning on writing in C++, you'll also want to download and install the [C++/WinRT Visual Studio Extension](https://marketplace.visualstudio.com/items?itemName=CppWinRTTeam.cppwinrt101804264).

Can you try again with the C++/WinRT Windows Runtime Component project type?

**Comment by jonthysell** [comment]
If I remove the reference to Microsoft.ReactNative.Cxx, your code builds fine. Those headers get included directly into your project, and without C++/WinRT, the code-gen files don't exist. If for some reason you **need** to write in C++/CX, see [Move to C++/WinRT from C++/CX](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/move-to-winrt-from-cx) so you can have a hybrid project that supports both.

**Comment by enm10k** [comment]
> First off, you seem to have created a C++/CX project. While that may work, it's not a scenario supported in the setup doc. If you want to use C++, you should use C++/WinRT. You'll need to install an extension to get the C++/WinRT project types:

You're absolutely right. I should have created a C++/WinRT project to use C++.
I recreated the project and the testing build passed successfully.
I appreciate your kind explanation.

> ... If for some reason you need to write in C++/CX, see Move to C++/WinRT from C++/CX so you can have a hybrid project that supports both.

Thank you so much for your advice, very helpful.
I may need to use this in the future, thanks again.
