### ISSUE TITLE
How to use it on windows 7?

### ISSUE THREAD

**Issue by HelloJack0** [microsoft/react-native-windows#3634]
I get error minimum 8.1 when run-wpf , it's can't use on windows 7?
F:\Develop Work\RNCode\RnWin7>react-native run-wpf
Restoring NuGet packages
**Build failed with message Error: Must have a minimum Windows SDK version 8.1 installed. Check your build configuration.**

F:\Develop Work\RNCode\RnWin7>react-native -v
react-native-cli: 2.0.1
react-native: 0.59.10

  "dependencies": {
    "react": "16.8.3",
    "react-native": "0.59.10",
    "react-native-windows": "0.59.0-rc.5"
  },
  "devDependencies": {
    "@babel/core": "^7.7.2",
    "@babel/runtime": "^7.7.2",
    "babel-jest": "^24.9.0",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.57.0",
    "react-test-renderer": "16.8.3",
    "rnpm-plugin-windows": "^0.3.8",
    "rnpm-plugin-wpf": "^0.2.15"
  },

**Comment by HelloJack0** [comment]
![image](https://user-images.githubusercontent.com/47816656/68989229-3ff2ce00-087e-11ea-82fc-93fae45566ee.png)

**Comment by licanhua** [comment]
I don't know too much about `current` implementation, from [Readme](https://github.com/microsoft/react-native-windows/blob/f7ccfa1426f557911b67a2e8171b7bee9befa5a6/README.md), you are required to install Windows 10 SDK. Could you please check if you installed SDK 14393.

- You can run React Native Windows UWP apps only on Windows 10 devices
   - React Native Windows -[current](https://github.com/microsoft/react-native-windows/tree/master/current) supports Windows 10 SDK >= [14393](https://developer.microsoft.com/en-us/windows/downloads/sdk-archive) and Windows 8.1
 
- You can run React Native Windows WPF apps using the [current](https://github.com/microsoft/react-native-windows/tree/master/current) implementation on Windows 7-10 so long as .NET 4.6 is installed on the end user's machine
- Download [Visual Studio 2017 Community or Greater](https://www.visualstudio.com/downloads/). (Visual Studio 2015 support has been deprecated.)
	- You will need to start Visual Studio after it is installed to do some final setup before it can be used to build or run your React Native Windows application
