### ISSUE TITLE
Is there are any way to call function from props?

### ISSUE THREAD

**Issue by Xandron3** [microsoft/react-native-windows#3636]
I want to call function from props in windows Native Module.

I already tried two ways:
  1) UIManagerModule().EventDispatcher.DispatchEvent(Event)
  In this case I need to edit UIManagerModule.Constants.cs file, because function has custom name (does not meet another event name)

  2) RCTDeviceEventEmitter().emit(Event)
  But in this method I need to add listener to JS module's file.

Can I invoke function in some other way?

**Comment by chrisglein** [comment]
Are you using vnext or current?
Can you provide more of your code so we can know what function you're talking about?
Is this issue specific to windows or have you tried on Android/iOS/Web?
Can you give more context on what you're trying to do?

**Comment by Xandron3** [comment]
> Are you using vnext or current?
current version
> Can you provide more of your code so we can know what function you're talking about?
I'm trying to invoke onBarCodeRead function in react-native-camera lib.
It is looks like this
```
return (
  <RNCamera
    onBarCodeRead={this._onObjectDetected(this.props.onBarCodeRead)}
    ...
  />
)

const RNCamera = requireNativeComponent('RNCamera', Camera, {
  nativeOnly: {
    onBarCodeRead: true,
    ...
  },
});
```

> Is this issue specific to windows or have you tried on Android/iOS/Web?
Actual only for windows

**Comment by chrisglein** [comment]
We are actively developing this for vnext and @stmoy may be able to provide some documentation on that.

**Comment by chrisglein** [comment]
@ddalp Itl ooks like iOS/Android were updated for this new `onBarCodeRead` but Windows wasn't updated. As we update this for vnext we'll want to track this.

**Comment by ddalp** [comment]
@chrisglein The current c# implementation for Camera does not work with RN-Camera, it has not been updated for a long time. For example: its module name is "CameraModule", should be updated to "RNCameraModule". Method "capture" should be changed to "takePicture" and "record" etc... Not sure if I should update current implementation to have it working or just make sure vNext working only.

**Comment by chrisglein** [comment]
Agreed, we want to focus on the vnext implementation. Since that's coming up it doesn't seem pressing to update current.
