### ISSUE TITLE
Update samples to use new ReactApplication

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#3639]
The samples in https://github.com/microsoft/react-native-windows-samples should be updated with native code generated from the latest CLI.

**Comment by chrisglein** [comment]
@stmoy have you and Jon worked out who should be updating documentation to match what's available at the end of the milestone?

**Comment by stmoy** [comment]
Handing this back to @jonthysell who agreed to update these.

Meta question: how can we ensure that our samples are always up-to-date?

**Comment by jonthysell** [comment]
Updated calculator: https://github.com/microsoft/react-native-windows-samples/pull/16

**Comment by jonthysell** [comment]
Updated nativemodules: https://github.com/microsoft/react-native-windows-samples/pull/17

**Comment by jonthysell** [comment]
Not going to update the todosfeed samples, those are attached with a particular blog post.
