### ISSUE TITLE
Documentation only changes shouldn't require a CI loop build

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#3642]
I just submitted a PR #3641 

It only has doc changes, and I specifically picked `none` when using `yarn change`.

And yet, it's building everything.

**Comment by chrisglein** [comment]
This PR shouldn't have actually needed to. It's the fact that you had a changefile that made it a requirement. MD files should be exempt. So... for this kind of change don't preemptively make a changefile?
