### ISSUE TITLE
Desktop integration tests should dynamically load RNW

### ISSUE THREAD

**Issue by JunielKatarn** [microsoft/react-native-windows#3646]
Currently, project `React.Windows.Desktop.IntegrationTests` consumes `React.Windows.Desktop` instead of `React.Windows.Desktop.DLL`.

Change this to make integration testing work on a component to component base.

**Comment by NickGerleman** [comment]
Could be addressed with #4087

**Comment by JunielKatarn** [comment]
Solved a while ago.
