### ISSUE TITLE
ERROR: Instance failed to start

### ISSUE THREAD

**Issue by YajanaRao** [microsoft/react-native-windows#3658]
### Environment

1. `react-native -v`: 0.60.6
2. `npm ls rnpm-plugin-windows`: 0.3.8
3. `npm ls react-native-windows`: 0.60.0-vnext.70
4. `node -v`: v10.16.0
5. `npm -v`: 6.9.0 
6. `yarn --version`:  1.19.1

Then, specify:

- Target Platform Version(s): 10.0.17763 build 17763

- Target Device(s): Desktop

- Visual Studio Version: Visual Studio 2019

- Build Configuration: Debug

### Steps to Reproduce

(Write your steps here:)

1. Consume react native windows 
2. Execute `react-native run-windows` or Use visual studio 2019 to build
3. Open the app

### Expected Behavior

Startup Screen should open

### Actual Behavior

![Screenshot (74)](https://user-images.githubusercontent.com/38914337/68852833-b668c200-06fe-11ea-8236-17c2a3a15296.png)

I am running command prompt in admin privilage

**Comment by chrisglein** [comment]
@YajanaRao From the screenshot it looks like you have Firefox open and not Chrome. Does this repro if you run Chrome? We'd like to guarantee that all browsers work, but it'd be helpful to know if it's necessary for the repro.

Were there any errors on the command line when you attempted from the command line? (from your repro steps it looks like you tried both that and through VS)

**Comment by YajanaRao** [comment]
I find this issue when I firefox is opened along with Chrome

**Comment by chrisglein** [comment]
@YajanaRao Glad to hear you have a workaround. Did this repro for you with iOS/Android too, or just Windows?

**Comment by YajanaRao** [comment]
@chrisglein It is for Android and Windows.

**Comment by chrisglein** [comment]
Issue seemed to have been solved by using just Chrome and not Firefox. Closing issue.

**Comment by widersky** [comment]
Have this issue on Chromium Edge Stable. I can't work at all. I don't want to use Chrome when there is Edge Chromium. MS was moving Edge to Chromium engine to recommend Chrome? It doesn't look good.
