### ISSUE TITLE
overflow "hidden" does not clip children of View when borderWidth is set

### ISSUE THREAD

**Issue by ddalp** [microsoft/react-native-windows#3661]
1. With the following React script:
const styles = StyleSheet.create({
  container: {
    borderColor: "cornflowerblue",
    backgroundColor: "peachpuff",
    width: 240,
    height: 240,
    justifyContent: "center",
    alignItems: "center",
    **overflow: "hidden"**
  },
  child: {
    backgroundColor: "yellow",
    width: 64,
    height: 400
  }
})

export default class Bootstrap extends React.Component {
  render() {
  return (
      <View style={styles.container}>
        <View style={styles.child}></View>
      </View>
  );
  }
}

We are getting output below, note the child view is clipped due to overflow = "hidden"
![image](https://user-images.githubusercontent.com/30847337/68886295-cdda8780-06cb-11ea-9a54-55fa19eb8b5d.png)

Update script to include borderwidth:
const styles = StyleSheet.create({
  container: {
    **borderWidth: 2,**
    borderColor: "cornflowerblue",
    backgroundColor: "peachpuff",
    width: 240,
    height: 240,
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden"
  },
  child: {
    backgroundColor: "yellow",
    width: 64,
    height: 400
  }
})

Clipping does not work any more on the children element.
![image](https://user-images.githubusercontent.com/30847337/68886439-14c87d00-06cc-11ea-883c-18dfecbbbb37.png)

**Comment by chrisglein** [comment]
Unclear how much work we've done to implement overflow. It may be that we haven't actually implemented this.

**Comment by ddalp** [comment]
We already support overflow = hidden for View, except this bug when outer border is present. I don't think we support overflow = scroll yet.  

Also I have a PR to address this bug already.

**Comment by ddalp** [comment]
Fix is in.
