### ISSUE TITLE
Make vNext the default

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#3671]
- The vNext C++ implementation of RNW should be the default implementation
- The C# implementation currently known as vCurrent should still be accessible to unblock developers currently dependent on it and developers who can't use vNext (as there will be areas where our API completion doesn't line up 100%)
- It may be worthwhile to keep a prev|next|current breakdown for future breaking changes, although given the sheer number of references to "vnext" it may be confusing to rebrand.

**Comment by NickGerleman** [comment]
@chrisglein @kmelmon is this issue set up as something we want to do long-term, are are there short-term plans to make this change? I know our team has been under the assumption we can make breaking changes without too much fuss.

**Comment by chrisglein** [comment]
@NickGerleman We intend to do it roughly within the next month and half. There's no longer engineers dedicated to vCurrent support, so to be responsible we need to move forward to vNext and not keep pointing new developers to a solution we intend to move off of.
What kind of breaking changes do you anticipate making?

**Comment by kmelmon** [comment]
Initial list of things to do here, which may require opening further tasks:

**Publishing Changes**

**CLI Changes**

**Comment by chrisglein** [comment]
Moved the above items into a project board: https://github.com/microsoft/react-native-windows/projects/24
We can go through those and decide which to promote into issues (currently they're notes).

**Comment by kmelmon** [comment]
0.61 beta has landed!
