### ISSUE TITLE
How to handle bundled assets

### ISSUE THREAD

**Issue by licanhua** [microsoft/react-native-windows#3674]
In the bundle command, there is –bundle-output and also –asserts-dest parameters. Even if I redirect –asserts-dest to Asserts folder, it may still has problem to access the resource. Because the link is file://assets/abc in the bundled file, and the app expect it to be msappx://Assets/abc.

Andrew suggested It's possible to fork the logic in AssetSourceResolver to have it generate the right urls.

I also found an internal commit on this topic: 
https://github.com/Microsoft/react-native-windows/commit/2812a4506322917709fc6f27ac82f053c2414c4b

**Comment by licanhua** [comment]
Expert it will fix #2452

**Comment by NickGerleman** [comment]
Anything left here to complete?
