### ISSUE TITLE
Add Windows support to expo's native directory (and expand other metadata about reliability)

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#3718]
# Proposal: Add Windows support to expo's native directory (and expand other metadata about reliability)

## Summary

There's an existing directory of React Native modules here: https://www.native.directory/
It doesn't list Windows support. And it'd be nice if it factored in some other details like CI level. The directory is open source, so we could contribute back to it. Or, if we feel like there's a better direction for React Native module discovery then we could propose a new solution.

## Motivation

Help developers discover React Native community modules that meet their needs

## Resources

Logic for calculating the score:
https://github.com/react-native-community/react-native-directory/blob/master/scripts/calculate-score.js
Metadata for specific libraries:
https://github.com/react-native-community/react-native-directory/blob/master/react-native-libraries.json
    
Some other plugin directories:
https://pub.dev/flutter
https://www.gatsbyjs.org/plugins/

**Comment by harinikmsft** [comment]
@stmoy is working on a proposal around this. We should write this up and engage through [discussions repo](https://github.com/react-native-community/discussions-and-proposals)

**Comment by chrisglein** [comment]
This is now supported: https://reactnative.directory/?windows=true
