### ISSUE TITLE
ReactInstanceManager has many interfaces not implemented yet

### ISSUE THREAD

**Issue by ddalp** [microsoft/react-native-windows#3721]
For example: ReactInstanceManager::OnBackPressed, OnSuspending etc. Currently it throws exception if those methods hit, we are currently waiting for host interface to complete before we can implement those interfaces, so creating issue to make sure we don't forget about it.

**Comment by jonthysell** [comment]
This should be done as part of the hosting work.

**Comment by NickGerleman** [comment]
I think all of this code has been replaced. Going to close this.
