### ISSUE TITLE
RNW should be use Microsoft.Windows.CppWinRT 2.0.191202.6

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#3726]
When using the VS extension to create a new CppWinRT project, it uses Microsoft.Windows.CppWinRT 2.0.191202.6.

We should be using the latest version.

**Comment by kmelmon** [comment]
@jonthysell is this required for new native modules (ie should be part of M4)?

**Comment by licanhua** [comment]
Why do you want to do it? I suggest we hold this until you need them.
1. new cppwinrt project would always keep updated, so 2.0.191202.6 will not be always the latest.
2. some cppwinrt features(https://github.com/microsoft/cppwinrt/issues/401) require the latest VS to support them, and that's why I chose an old one.
3. I hit several issues when working on WinUI bugs

**Comment by jonthysell** [comment]
> @jonthysell Jon Thysell (JAUNTY) FTE is this required for new native modules (ie should be part of M4)?

I don't think it's strictly necessary for M4. I've already got us back up to 2.0.190730.2, which is the most "popular" version out there by nuget downloads. 

> Why do you want to do it? I suggest we hold this until you need them.
> 
> 1. new cppwinrt project would always keep updated, so 2.0.191202.6 will not be always the latest.
> 2. some cppwinrt features([microsoft/cppwinrt#401](https://github.com/microsoft/cppwinrt/issues/401)) require the latest VS to support them, and that's why I chose an old one.
> 3. I hit several issues when working on WinUI bugs

We have a lot of hacks and workarounds in our code/projects to support cppwinrt because of the old versions we use. Upgrading to newer versions forces us to clean up the code our customers interact with the most, the ABI. At some point we're going to want something from cppwinrt that requires us to upgrade to take a fix, so why not get us as up to date as possible before take on customers, rather than forcing all of us to upgrade later?

**Comment by jonthysell** [comment]
@licanhua I'm not going to check in any changes right now, as we're rearranging and cleaning up the ABI surface. But I'm still working through the PR to identify the issues we'll need to address when we do finally upgrade.

**Comment by chrisglein** [comment]
Fixed with https://github.com/microsoft/react-native-windows/pull/4449 by @vmoroz .

> C++/WinRT is updated from 2.0.190730.2 to the latest 2.0.200316.3

Closing this issue.
