### ISSUE TITLE
Redirect build directory to C drive for vs2017-win2016 build machine

### ISSUE THREAD

**Issue by licanhua** [microsoft/react-native-windows#3735]
From the log, vs 2017 build machine has 270G(free 120G) on C drive, and 15G(free 12G) on D. If we can redirect the buildoutput to C, it's possible to allow to build all solutions in one job.
vs2019 has far less space on C drive

- vs2017-win2016
```
DeviceID : C:
DriveType : 3
ProviderName :
FreeSpace : 120233426944
Size : 274351517696
VolumeName : Windows

DeviceID : D:
DriveType : 3
ProviderName :
FreeSpace : 12003606528
Size : 15031267328
VolumeName : Temporary Storage
```

- windows-2019
```
DeviceID     : C:
DriveType    : 3
ProviderName : 
FreeSpace    : 16611737600
Size         : 136912564224
VolumeName   : Windows

DeviceID     : D:
DriveType    : 3
ProviderName : 
FreeSpace    : 12006678528
Size         : 15031267328
VolumeName   : Temporary Storage
```

**Comment by kmelmon** [comment]
@licanhua Can you also look into having the RNW CI loop use another pool that has more space?  This would solve the problem without any work on our part.  And I believe eventually we will want to update to build using VS 2019 anyway.
