### ISSUE TITLE
Alert:  prompt API is not implemented

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#3743]
RN Alert has a prompt API which isn't yet implemented in RN4W.

Note that the Facebook docs are incorrect.  The docs say AlertiOS has a prompt API but it's actually on Alert.  To add to the confusion, this API is only implemented on iOS.

See:  https://facebook.github.io/react-native/docs/alertios#prompt
and https://github.com/facebook/react-native/blob/master/Libraries/Alert/Alert.js

We should implement the missing API on Windows, and we should follow up with Facebook about getting an Android implementation.

**Comment by kmelmon** [comment]
Not critical for MVP as this API is currently not supported on all platforms.

**Comment by chrisglein** [comment]
Updating with links to the shared module: https://reactnative.dev/docs/alert#prompt-ios
Note that prompt is iOS only, but the module is shared now.
Windows implementation is here: https://github.com/microsoft/react-native-windows/blob/7f99d6048a4c220da68733a010e472168a774c7b/vnext/Microsoft.ReactNative/Modules/AlertModule.h
As we move to Fabric, yes Alert needs to work, but `prompt` remains at the same priority as with Paper as it's not a true cross-platform method.
