### ISSUE TITLE
Unified way to manage all nugets in React-Native-Windows

### ISSUE THREAD

**Issue by licanhua** [microsoft/react-native-windows#3753]
This problem is raised in code review of #3729

We have nugets: boost, Hermes, J8JSI, WinUI, but we managed them in different ways. 
Each time we modify a nuget version, we need make the same change across multiple projects. we need a simple way to maintain it. We may fix it by:
1. package.config doesn't accept parameters like HERMES_Version. [PackageReference](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files) may fix the problem 
2. Prefer to define the path as HERMES_Package other than package + version 
```
   <Import Project="$(HERMES_Package)\build\native\ReactNative.Hermes.Windows.targets" Condition="Exists('$(HERMES_Package)\build\native\ReactNative.Hermes.Windows.targets') AND '$(OSS_RN)' != 'true' AND '$(USE_HERMES)' == 'true'" />
    <Import Project="$(V8_Package)\build\native\ReactNative.V8JSI.Windows.targets" Condition="Exists('$(V8_Package)\build\native\ReactNative.V8JSI.Windows.targets') AND '$(OSS_RN)' != 'true' AND '$(USE_V8)' == 'true'" />
 
```
is better than
```
    <Import Project="$(SolutionDir)packages\ReactNative.Hermes.Windows.0.1.3\build\native\ReactNative.Hermes.Windows.targets" Condition="Exists('$(SolutionDir)packages\ReactNative.Hermes.Windows.0.1.3\build\native\ReactNative.Hermes.Windows.targets') AND '$(OSS_RN)' != 'true' AND '$(USE_HERMES)' == 'true'" />
    <Import Project="$(SolutionDir)packages\ReactNative.V8JSI.Windows.0.1.4\build\native\ReactNative.V8JSI.Windows.targets" Condition="Exists('$(SolutionDir)packages\ReactNative.V8JSI.Windows.0.1.4\build\native\ReactNative.V8JSI.Windows.targets') AND '$(OSS_RN)' != 'true' AND '$(USE_V8)' == 'true'" />
  
```

**Comment by licanhua** [comment]
Another benefit is it may save space and time because for most of customer, they doesn't need to download v8 and Hermes.

**Comment by JunielKatarn** [comment]
> package.config doesn't accept parameters like HERMES_Version. PackageReference may fix the problem

Do Visual C++ projects support `PackageReference`?

**Comment by NickGerleman** [comment]
Not sure there is anything actionable unless we had PackageReference support.
