### ISSUE TITLE
Investigate and apply the Screenshot functionality of WinAppDriver to RNW test framework.

### ISSUE THREAD

**Issue by licanhua** [microsoft/react-native-windows#3755]
Look like WinAppDriver supports snapshot on UIElement.
We can use it:
1. screenshot on fail
2. visual diff.

It doesn't like a standard WebDriver API, and it may need additional work make JS happy.

Here is C# example of screenshot:
https://github.com/microsoft/WinAppDriver/blob/master/Tests/WebDriverAPI/Screenshot.cs

**Comment by NickGerleman** [comment]
We will screenshot on test failure for the current test framework.
