### ISSUE TITLE
Move CI Loop to machines with more hard drive space

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#3759]
This is likely a longer term goal as we can limp along with a short term solution while we're using the VS 2017 images.

Longer term we'll likely be upgrading to using the VS 2019 images and these have limited disk space.  We need a long term solution that will allow us to use the latest build tools and not have disk space issues.  We've started a conversation with the WinUI team who are facing similar issues, they have identified helix as a possible alternative.

We should work further with WinUI folks and implement a long term solution that will allow us to move our CI loop to machines with more space.

**Comment by JunielKatarn** [comment]
Ideally, we should be able to use a custom base image with exact VS, MSVC, Node, Yarn, etc versions we need.

This is not my area of expertise, but this should theoretically be doable with Azure VMs.

**Comment by licanhua** [comment]
We can low the priority for this task. I did a lot of work on this very recently, and disk is not a issue on pipeline after these PRs even if we will use windows-2019 build machines :
#3773 reduce build flavors for RNWUniversalPR
#3768 Redirect build directory to C: on vs2017-win2016 build machine
#3771 Delete .pch after build on pipeline
#3734 Reduce build time on pipeline
#3729 Use ReactNative.V8JSI.Windows.0.1.6 and ReactNative.Hermes.Windows.0.1.6

In the future, if we hit disk space issue:
Apply #3771 to the concerned project which is not in vnext folder
Spin another job to do the build other than build multiple solutions in one job. and it will save build time, also not hit the disk space issue

**Comment by jonthysell** [comment]
We're already working around this I think.
