### ISSUE TITLE
Investigate and resolve warnings

### ISSUE THREAD

**Issue by licanhua** [microsoft/react-native-windows#3772]
The new pipeline showed all warnings on the top of PR. It has too much warnings.
we should investigate and resolve the warnings.

![image](https://user-images.githubusercontent.com/6290692/70831911-a4834900-1da8-11ea-9ff8-d6e4355a70d5.png)

**Comment by chrisglein** [comment]
@licanhua Instead of a screenshot can you actually paste the warning text in here so this is searchable?
