### ISSUE TITLE
Escape key should dismiss Developer Menu

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#3774]
Ctrl + Shift + D brings up the Developer Menu, but you must click the Cancel button to dismiss it.

The escape key should also dismiss the Developer Menu.

**Comment by sumitparakh** [comment]
Hi @kmelmon and @chrisglein  , I would like to contribute to this task with your permission.

**Comment by kmelmon** [comment]
@sumitparakh Thanks and feel free to jump on this!  Note that the developer menu has has a bunch of improvements made since this task was filed.  I would recommend trying out the latest version and confirming this functionality is still missing.  If so, feel free to fix and submit a pull request, we can review and merge it.

**Comment by sumitparakh** [comment]
@kmelmon , I've created a react-native windows app by following [this](https://microsoft.github.io/react-native-windows/docs/getting-started) tutorial and you were right. Now the escape key also dismisses the Developer Menu.

Can we close this issue now?

![image](https://user-images.githubusercontent.com/4236211/100103392-d80c9580-2e8a-11eb-9218-259b7a7f2034.png)

**Comment by kmelmon** [comment]
@sumitparakh thanks for verifying!  Closing.
