### ISSUE TITLE
Question: is it full compatible with react-native projects?

### ISSUE THREAD

**Issue by ericfelipe99** [microsoft/react-native-windows#3776]
Sorry for this basic question.

Can i compile my react-native projects with this project without rewriting code to linux desktop ? 
It's full compatible with projects with oficial react-native ?

**Comment by licanhua** [comment]
I don't think Linux desktop is in our scope. The official supported platforms are iOS, Android, and the this repo add Windows.

> It's full compatible with projects with official react-native ?

If `compatible` means one React and share code across platforms, then yes.
If it means features parity with iOS and Android, then some components(
https://github.com/microsoft/react-native-windows/blob/master/vnext/docs/ParityStatus.md) are still in progress

**Comment by ericfelipe99** [comment]
> I don't think Linux desktop is in our scope. The official supported platforms are iOS, Android, and the this repo add Windows.
> 
> > It's full compatible with projects with official react-native ?
> 
> If `compatible` means one React and share code across platforms, then yes.
> If it means features parity with iOS and Android, then some components(
> https://github.com/microsoft/react-native-windows/blob/master/vnext/docs/ParityStatus.md) are still in progress

i'm very sorry. 
I'm searching for react-native for linux, and one post in stackoverflow indicated 2 links, one is this repo, and another is a project that is compatible with linux... i made a mistake and put my question in wrong repo. 

Sorry, i will close this now.
