### ISSUE TITLE
Is it possible to add Tab view to windows top bar from react native?

### ISSUE THREAD

**Issue by sakthivel-servicemax** [microsoft/react-native-windows#3777]
Hi,
I am developing the app from the version 0.59.2. Is it possible to add Tab view to windows top bar from react native? If it is possible, please give me some sample.

**Comment by chrisglein** [comment]
@sakthivel-servicemax I assume you mean putting tabs into the Windows title bar? Similar to what you get from Chrome, for example? To customize the titlebar you'd need this: #2527. It's possible with native code (Windows allows you to disable the default titlebar and draw your own), but there's no existing out of the box solution for react-native-windows today.
