### ISSUE TITLE
E2E test TreeDump utility update to fire event when comparison succeed

### ISSUE THREAD

**Issue by ddalp** [microsoft/react-native-windows#3779]
This is low priority test infra enhancement issue:

Currently we are polling on the test tree dump comparison result (getTreeDumpResult in BasePage.ts), we should be firing event when layout tree dump comprison pass. Currently the custom view manager fails in release mode because constructor with the Context object is optimized away, we need Context object to fire event from custom view manager.

**Comment by asklar** [comment]
moving to you @kmelmon since you're looking at e2etests now

**Comment by kmelmon** [comment]
This will be superseded by #5841.
