### ISSUE TITLE
Accessibility label updates for Views using accessibilityLiveRegion are not being read aloud by Narrator

### ISSUE THREAD

**Issue by jagorrin** [microsoft/react-native-windows#3783]
### Environment

1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.60.6
2. `npm ls rnpm-plugin-windows`:
rnpm-plugin-windows@0.3.5
3. `npm ls react-native-windows`:
react-native-windows@0.60.0-vnext.39
4. `node -v`:
v10.15.0
5. `npm -v`:
6.13.1

Then, specify:

- Target Platform Version(s): 10.0.18362.0

- Target Device(s): Desktop

- Visual Studio Version: 2017

- Build Configuration: Debug

### Steps to Reproduce

1. Create a View and provide it an accessibilityLiveRegion of 'assertive'
2. Enable Narrator
2. Update the accessibilityLabel of the View created in step 1

### Expected Behavior

Narrator will announce the accessibility label when it changes.

### Actual Behavior

Accessibility label is not read aloud.

### Additional context

When a breakpoint was placed in `UpdateProperties` in `FrameworkElementViewManager`, the execution never entered the code in the `propertyName == "accessibilityLiveRegion"` conditional. Locally, I added the accessibilityLiveRegion prop to the list of props in `GetNativeProps` in the same file, and then the accessibility label was read when it updated, as I expected. It looks like today accessibilityLiveRegion is being filtered out since it is not in the list in `GetNativeProps`.

**Comment by chrisglein** [comment]
Likely not yet implemented, we may not be listening to the events and updating as expected here.

**Comment by jagorrin** [comment]
I merged in a change that resolves this issue, so I am closing it.
