### ISSUE TITLE
folly warnings during build

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#3785]
We can see this in all of our CI loop builds.  For example see:  https://dev.azure.com/ms/8d8e50dd-c5b4-4b44-8668-86558c5aa5b7/_apis/build/builds/54891/logs/374

Relevant warnings:
**##[warning]vnext\Folly\Folly.vcxproj(274,5): Warning MSB3936: Failed to open unzip file "folly-2019.09.30.00/" to "d:\a\1\s\node_modules\.folly\folly-2019.09.30.00\".  Could not find a part of the path 'd:\a\1\s\node_modules\.folly\folly-2019.09.30.00\'.**

The build is spewing a gigantic number of these "Failed to open unzip file ..." warnings.  This spew is annoying and is making our CI loop pages hard to navigate, due to all the warning spew showing up above the test results.

We should figure out why the build is unable to find these unzip files and fix this.

**Comment by acoates-ms** [comment]
There is a comment about this in ReactFolly.vcxproj: https://github.com/microsoft/react-native-windows/blob/4b79a5f4fba6ca510927176867b858b2e6c8aa22/vnext/Folly/Folly.vcxproj#L273

Its a msbuild bug: https://github.com/Microsoft/msbuild/issues/3884

We are also setting `ContinueOnError="true"` on that build task, becuase of this, which should be cleared up once the msbuild fix is mroe broadly deployed.

**Comment by chrisglein** [comment]
Looks like it's fixed and will come via this (probably in an upcoming VS update):
16.5 Preview3, MSBuild 16.5 Preview 3
However, will not just get fixed on VS2017, so...
