### ISSUE TITLE
MSB8020  Build Tools for Vistual Studio 2017 not found (but everything is installed)

### ISSUE THREAD

**Issue by dejawho** [microsoft/react-native-windows#3786]
Hi, I'm trying to build a windows app from my react native project, but I alwyas get this error MSB8020, even if I've installed everything specified in the readme. I'm using the version next because my project is using react native 0.60

### Environment

react-native-cli: 2.0.1
react-native: 0.60.6

2. `react-native run-windows --info`:

System:
    OS: Windows 10 10.0.17763
    CPU: (6) x64 Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
    Memory: 6.94 GB / 15.96 GB
  Binaries:
    Node: 12.4.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: ^0.60.0 => 0.60.6
    react-native-windows: 0.60.0-vnext.96 => 0.60.0-vnext.96
    rnpm-plugin-windows: ^0.3.8 => 0.3.8
  Installed UWP SDKs:
    10.0.17763.0
    10.0.18362.0

- Target Device(s): Local

- Visual Studio Version: 2019

- Build Configuration: Debug

### Steps to Reproduce

1. Import my working react native project
2.	react-native windows --template vnext
3. yarn start
4. open with visual studio 2019 the sln file
5. select near debug x64
6. hit the run button

### Expected Behavior

The project is runned in browser

### Actual Behavior

1>------ Inizio compilazione: Progetto: Folly, Configurazione: Debug x64 ------
2>------ Inizio compilazione: Progetto: Common, Configurazione: Debug x64 ------
1>Compilazione progetto "Folly.vcxproj" NON COMPLETATA.
3>------ Inizio compilazione: Progetto: ReactCommon, Configurazione: Debug x64 ------
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(382,5): error MSB8020: The build tools for Visual Studio 2017 (Platform Toolset = 'v141') cannot be found. To build using the v141 build tools, please install Visual Studio 2017 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".
3>Compilazione progetto "ReactCommon.vcxproj" NON COMPLETATA.
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(382,5): error MSB8020: The build tools for Visual Studio 2017 (Platform Toolset = 'v141') cannot be found. To build using the v141 build tools, please install Visual Studio 2017 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".
2>Compilazione progetto "Common.vcxproj" NON COMPLETATA.
4>------ Inizio compilazione: Progetto: ReactWindowsCore, Configurazione: Debug x64 ------
4>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(382,5): error MSB8020: The build tools for Visual Studio 2017 (Platform Toolset = 'v141') cannot be found. To build using the v141 build tools, please install Visual Studio 2017 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".
4>Compilazione progetto "ReactWindowsCore.vcxproj" NON COMPLETATA.
5>------ Inizio compilazione: Progetto: ReactUWP, Configurazione: Debug x64 ------
5>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(382,5): error MSB8020: The build tools for Visual Studio 2017 (Platform Toolset = 'v141') cannot be found. To build using the v141 build tools, please install Visual Studio 2017 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".
5>Compilazione progetto "ReactUWP.vcxproj" NON COMPLETATA.
6>------ Inizio compilazione: Progetto: Microsoft.ReactNative, Configurazione: Debug x64 ------
6>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(382,5): error MSB8020: The build tools for Visual Studio 2017 (Platform Toolset = 'v141') cannot be found. To build using the v141 build tools, please install Visual Studio 2017 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".
6>Compilazione progetto "Microsoft.ReactNative.vcxproj" NON COMPLETATA.
7>------ Inizio compilazione: Progetto: DarkSoulsDungeons, Configurazione: Debug x64 ------
7>C:\Users\Marco\git\DarkSoulsDungeonsWindows\windows\DarkSoulsDungeons\DarkSoulsDungeons.vcxproj : XamlCompiler error WMC1006: Cannot resolve Assembly or Windows Metadata file 'C:\Users\Marco\git\DarkSoulsDungeonsWindows\node_modules\react-native-windows\target\x64\Debug\Microsoft.ReactNative\Microsoft.ReactNative.winmd'
7>pch.cpp
7>C:\Users\Marco\git\DarkSoulsDungeonsWindows\windows\DarkSoulsDungeons\pch.h(18,10): fatal error C1083: Non è possibile aprire il file inclusione: 'winrt/Microsoft.ReactNative.Bridge.h': No such file or directory
7>Compilazione progetto "DarkSoulsDungeons.vcxproj" NON COMPLETATA.
========== Compilazione: 0 completate, 7 non riuscite, 0 aggiornate, 0 ignorate ==========
========== Distribuzione: 0 completate, 0 non riuscite, 0 ignorate ==========

### Additional context

Every requirements was installed, here the visual studio installed components:

[vs configuration screenshot](https://ibb.co/thjRMFg)

**Comment by JunielKatarn** [comment]
One thing that stands out from the log is the following line:
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets
```

MSVC v141 tools should using the targets file `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v150\Microsoft.CppBuild.targets` instead (note **v150**).

**Comment by dejawho** [comment]
Mmmm, strangely in that folder I don't have the v141, only v150 and v160, but everything requested in the requisites was installed. How can I install che 141?

**Comment by dejawho** [comment]
I was able to solve this by reinstalling the UWP tools from the VS2019 package manager, and carefully selecting everything on the right panel. Then on VS I've selected the project -> properties -> general (for all configuration) and selected as platform target the value 141

**Comment by JunielKatarn** [comment]
> I was able to solve this by reinstalling the UWP tools from the VS2019 package manager, and carefully selecting everything on the right panel. Then on VS I've selected the project -> properties -> general (for all configuration) and selected as platform toolset the value Visual Studio 2017 (v141)

Glad that worked.
To clarify on your previous comment, `v141` corresponds to the Microsoft Visual C++ toolset version, which would ultimately be located inside `v150`, which refers to Visual Studio 15.0 (2017).

Meaning, Visual Studio 2019 has a folder designated for VS2017 tools.

**Comment by jevansaks** [comment]
I ran into this too, and it was confusing because if you search the "Individual Components" list for v141 the thing you need isn't there. But you find it on the sidebar under "Universal Platform Development". A picture to help others:

![image](https://user-images.githubusercontent.com/20667023/71218389-2a563700-2276-11ea-9b30-b577e7de0642.png)
