### ISSUE TITLE
windowsbrush cannot be used in TypeScript

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#3787]
If you try to use a windowsbrush in a TypeScript app file, this generates a TypeScript compiler error.

For example this jsx:
        <Button
          title="Sample Button"
          color={{windowsbrush: 'SystemAccentColorLight3'}}
          onPress={this._onPress}
        />
generates this compiler error:
23           color={{windowsbrush: 'SystemAccentColorLight3'}}
  ../node_modules/@types/react-native/index.d.ts:6916:5
    6916     color?: string;
The expected type comes from property 'color' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<Button> & Readonly<ButtonProps> & Readonly<{ children?: ReactNode; }>'

I believe this is another instance where DefinitelyTyped changes would be needed:
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-native

For now apps can work-around the issue by adding // @ts-ignore but this is not ideal.

**Comment by chrisglein** [comment]
For this specific example we probably want to follow the new platform color (not Windows specific) solution. But this does raise issues about how we want to handle platform-specific APIs for TypeScript. There's also an issue with different versions of types, but @acoates-ms has a change to enable that.

**Comment by chrisglein** [comment]
@harinikmsft Create an issue to track creating a proposal for how to deal with the larger issue of platform-specific types.

**Comment by harinikmsft** [comment]
@kikisaints has started discussions in the dicussions and proposals repo for these conversations - [platform specific properties](https://github.com/react-native-community/discussions-and-proposals/issues/188), [platform specific styles](https://github.com/react-native-community/discussions-and-proposals/issues/254). 

Assigning to @kikisaints to conclude those conversations and then update the proposal for windowsBrush.

**Comment by acoates-ms** [comment]
People shouldn't use windowsbrush directly, but instead use PlatformColor, which the typescript definitions in 0.63 should support.

**Comment by kikisaints** [comment]
@acoates-ms or @chrisglein has `windowsbrush` been removed? if not, I can create an issue for that and we can close this one.

**Comment by acoates-ms** [comment]
xamlbrush never really worked with the typescript typings.  Now you can use PlatformColor which is supported by the typings.

I think we can close this one.
