### ISSUE TITLE
Flicker when dynamically switching an Image's source

### ISSUE THREAD

**Issue by marlenecota** [microsoft/react-native-windows#3794]
Create an issue to track removing the temporary workaround and link it in the comment.
(unless you're planning on addressing before merging the PR)

_Originally posted by @chrisglein in https://github.com/microsoft/react-native-windows/pull/3712_

**Comment by chrisglein** [comment]
@acoates-ms had some comments about Facebook having some different patterns here about requiring a fixed size on the element up front and using an image store to pre-load images before changing the source. These avoid the flicker but don't necessarily align with the XAML way of decoding images. It's worth checking with the other platforms to know what they're expecting to do so we don't have any additional platform-specific policy. Sync with Andrew on this.
