### ISSUE TITLE
Picker does not have rounded corners when "borderRadius" style is used

### ISSUE THREAD

**Issue by jagorrin** [microsoft/react-native-windows#3796]
### Environment

1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.60.6
2. `npm ls rnpm-plugin-windows`:
rnpm-plugin-windows@0.3.5
3. `npm ls react-native-windows`:
react-native-windows@0.60.0-vnext.39
4. `node -v`:
v10.15.0
5. `npm -v`:
6.13.1

Then, specify:

- Target Platform Version(s): 10.0.18362.0

- Target Device(s): Desktop

- Visual Studio Version: 2017

- Build Configuration: Debug

### Steps to Reproduce

1. Create a Picker in a project using React Native Windows
2. Apply a style containing "borderRadius"
3. Observe that the Picker does not have rounded corners

Example code:

```
import { Picker, StyleSheet } from "react-native";

const styleSheet = StyleSheet.create({
    roundedCorners: {
        borderRadius: 3,
    },
});

render() {
    return (
          <Picker style={styleSheet.roundedCorners}>
                <Picker.Item label="Any" value="Any" />
          </Picker>
     );
}
```

### Expected Behavior

I expected the Picker to have rounded corners using the supplied border radius.

### Actual Behavior

Applying the "borderRadius" style did not visually change the box. It still has rounded corners.

Screenshot:
![snip1](https://user-images.githubusercontent.com/58611963/71039598-60aa7f80-20d9-11ea-9817-75d6fe2d6e66.png)

**Comment by chrisglein** [comment]
@jagorrin We recently changed react-native-windows to bring in WinUI2.3 which should include various fixes for border radius. Can you update to the latest version and let us know if this is fixed or not for you?
@licanhua if you happen to know the version number that adds this can you add a note here?

**Comment by jagorrin** [comment]
@licanhua Can you provide the version number when the upgrade to WinUI2.3 occurred?

**Comment by chrisglein** [comment]
PR that added it is here: https://github.com/microsoft/react-native-windows/pull/3707, from November 7th.
@kmelmon do you know how to get from a commit to the version number that will include that?

**Comment by kmelmon** [comment]
@chrisglein currently, every change triggers a publish to npm so if it's checked in, it's already out there.

**Comment by acoates-ms** [comment]
You can also look at the change log:
https://github.com/microsoft/react-native-windows/blob/master/vnext/CHANGELOG.md#0600-vnext86

Admittedly the change log info entered on that change wasn't particularly descriptive.

**Comment by jagorrin** [comment]
Thank you. I will test on 0.60.0-vnext.86.

**Comment by jagorrin** [comment]
This is working for me now as of 0.60.0-vnext.86. Thanks!
