### ISSUE TITLE
Update copyright notice on forked files

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#3797]
We have a bunch of forked files that need their copyright notice updated:

Run this command from vnext\src:

`findstr /snip facebook *.* | findstr /snip copyright`

The copyright notices should change to look like:
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License.

We already have a LICENSE file at the root of the repo stating some of this code is based on facebook's implementation.

**Comment by acoates-ms** [comment]
I know when facebook updated their license, they added a quick CI check that failed builds if someone tried to use the old license.  I wonder if we should have some similar detection for detecting the facebook license on our files.

**Comment by vmoroz** [comment]
Could someone check the official LCA open source guidelines before we start removing Facebook license from modified files.

**Comment by NickGerleman** [comment]
I think we decided that there wasn't any action items here.
