### ISSUE TITLE
vnext default:  Update Getting Started Guide

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#3798]
Need to update the Getting Started Guide on the github. These docs currently talk about both vCurrent and vNext. 

Proposal:  Update the Getting Started Guide to only talk about vnext.  I don't see a strong reason to mention vCurrent on our landing page anymore.  We can leave the docs about vCurrent inside legacy directory in case someone does need them.

We'll also need to update the guide with latest details about installing unforked 61.  One of those things will be which version to install.  We're updating to 0.61.5.  Note that when we first publish version 61, it will be published to npm as a beta (the package version will look something like 0.61.0-beta.1) as we work through stabilizing it.  This will be the first time we’ve done a beta!  I think we’ll likely want a special section on how to install the beta version in the getting started guide, say, below the instructions for using the current stable bits (which will still be on version 60).  When we think it’s stable, we can publish without the beta tag and remove the beta instructions.

**Comment by kikisaints** [comment]
So it looks like we'll have two sets of getting started guidance:

- How to install the latest stable,
  `` react-native init <myproject> --version 0.61.5``
- How to get the beta of RNW
  `` react-native init <myproject> --0.61.0-beta.1`` ??

I'm a little unclear how a developer is supposed to get the stable version versus the latest beta version - can you write out the commands one would need to step through to get either of these?

Thanks!

**Comment by acoates-ms** [comment]
To use 61:
 `react-native init <myproject> --version ^0.61` 
`react-native windows --template beta`  (this will just become `react-native windows` once we are out of beta)

To use 60:
 `react-native init <myproject> --version ^0.60` 
`react-native windows`

I believe...

**Comment by harinikmsft** [comment]
Updated - [guide](https://microsoft.github.io/react-native-windows/docs/getting-started). Closing on behalf of @kikisaints
