### ISSUE TITLE
UIManager is missing measureLayout

### ISSUE THREAD

**Issue by ashkling** [microsoft/react-native-windows#3805]
It looks like UIManager.measureLayout is not currently implemented (I'm getting TypeError: Object doesn't support property or method 'measureLayout').

It does exist in the React Native API: https://facebook.github.io/react-native/docs/direct-manipulation.html#measurelayoutrelativetonativenode-onsuccess-onfail but in react-native-windows/vnext/ReactWindowsCore/Modules/UIManagerModule.h there's only measure and measureInWindow, but no measureLayout. 

We have a class that used measureLayout in ReactXP to help find where in the page a component is so we can scroll directly to it. To make the jump to React Native Windows we'll need this function.

**Comment by chrisglein** [comment]
Looks like we did measureInWindow but not measureLayout with #2921
