### ISSUE TITLE
Enable C++/WinRT heap enforcement

### ISSUE THREAD

**Issue by licanhua** [microsoft/react-native-windows#3807]
WinUI did this two C++/WinRT enhancements and it's possible apply to react-native-windows too:
1. [Enable C++/WinRT heap enforcement](https://github.com/microsoft/microsoft-ui-xaml/pull/1772).
 Turn on the C++/WinRT heap enforcement to catch cases where we incorrectly stack-allocate a WinRT object.
2. [Switch to C++/WinRT -optimized](https://github.com/microsoft/microsoft-ui-xaml/pull/1737).
Moved to issue #4019

**Comment by chrisglein** [comment]
Note: Should split this into two issues

**Comment by chrisglein** [comment]
Forked out #4019, adjusting this issue to just cover "Enable C++/WinRT heap enforcement."

**Comment by NickGerleman** [comment]
@vmoroz I closed this since I saw your PR was merged, but does this issue affect other projects than the template or Microsoft.ReactNative?

**Comment by vmoroz** [comment]
@NickGerleman, this flag is C++/WinRT only which we currently use only for Microsoft.ReactNative.dll, templates, and some uni tests. I would not worry much about the test projects.

**Comment by vmoroz** [comment]
Ouch, we still use it in our sample project. I will fix it before closing the issue.
