### ISSUE TITLE
react native vector icons are not displayed in the app.

### ISSUE THREAD

**Issue by YajanaRao** [microsoft/react-native-windows#3819]
### Environment

If you are using latest version:
1. `react-native -v`: 0.60.6
2. `react-native run-windows --info`: 

Otherwise if `--info` doesn't exist:
1. `react-native -v`: 0.60.6
2. `npm ls rnpm-plugin-windows`: 
3. `npm ls react-native-windows`:
4. `node -v`: 10.17.0
5. `npm -v`: 6.11.3
6. `yarn --version`:

Then, specify:

- Target Platform Version(s):  10.0.18362

- Target Device(s): Desktop

- Visual Studio Version: Visual Studio 2019

- Build Configuration: Debug

### Steps to Reproduce

(Write your steps here:)

1. Copy .ttf  file to /windows/${appname}/Assets folder
2. Check the properties

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

.ttf file is being ignored and no icons are showing up in the app.

![image](https://user-images.githubusercontent.com/38914337/71518163-89035c80-28d7-11ea-9db2-c785ded04165.png)

**Comment by chrisglein** [comment]
Lots of discussion about custom fonts on this other issue: #3463. @YajanaRao can you take a look at that and see if you're running into similar problems?
