### ISSUE TITLE
Port RNW LocationObserverModule to react-native-community/geoLocation

### ISSUE THREAD

**Issue by KAnder425** [microsoft/react-native-windows#3832]
# Proposal: Port RNW LocationObserverModule to react-native-community/geoLocation

## Summary
With the move to the 0.60 branch, navigator.geoLocation is no longer supported by react-native. It has been moved to react-native-community/geoLocation and deprecated from react-native. However, react-native-community/geoLocation doesn't support windows...yet. Our react-native-windows LocationObserver module is now 'orphaned'.

https://github.com/react-native-geolocation/react-native-geolocation

## Motivation
In our UWP calendar app, the weather feature depended on navigator.geoLocation from react-native-windows. The weather feature is now broken.  

## Open Questions
In the interim, we might consider moving this support to react-native-windows-extended.

**Comment by kmelmon** [comment]
The right longer term solution is to add windows support to the community module, but we haven't fully setup the infra for linking them yet.

@KAnder425 for now we could add this into react-native-windows-extended.  If you're blocked on this I suggest unblocking yourself by doing this.  Let us know if you need more.

**Comment by kmelmon** [comment]
@chrisglein how are we tracking adding support to the top community modules?  This should likely be on the list.

**Comment by chrisglein** [comment]
@stmoy is tracking the whole list, and we have a project board for them as well: https://github.com/microsoft/react-native-windows/projects/23
I've added it to the board.

**Comment by burtonrodman** [comment]
I have submitted this pull request on react-native-geolocation to add Windows Support.  Please feel free to provide any feedback.

https://github.com/react-native-geolocation/react-native-geolocation/pull/146
