### ISSUE TITLE
react-native windows doesn't work after installing windows plug-in using npm

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#3862]
Our Getting Started guide says that we still support installing rnpm-plugin-windows via npm but it is currently broken.

REPRO STEPS:
react-native init myproject --version 0.60.0
cd myproject
npm install --save rnpm-plugin-windows
react-native windows --template vnext

RESULT
warn Package rnpm-plugin-windows has been ignored because it contains invalid configuration. Reason: Cannot find module '@react-native-community/cli/build/tools/generator/promptSync'
error Unrecognized command "windows".

**Comment by kmelmon** [comment]
This may be a lack of proper dependency declarations in package.json.  Yarn apparently works due to hoisting up to root.  We should try to fix this, if not then update docs to use yarn.

**Comment by chrisglein** [comment]
If we can't figure this out quickly let's update the steps to require yarn.
@kikisaints as an FYI for that
