### ISSUE TITLE
Bundling stuck at 0% (simple project using projectstorm/react-diagrams)

### ISSUE THREAD

**Issue by johnsmithlon** [microsoft/react-native-windows#3864]
### Environment

1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.59.10
2. `npm ls rnpm-plugin-windows`:
reactnativewinapp@0.0.1 C:\react\reactnativewinapp
`-- rnpm-plugin-windows@0.4.0
3. `npm ls react-native-windows`:
reactnativewinapp@0.0.1 C:\react\reactnativewinapp
`-- UNMET DEPENDENCY react-native-windows@0.59.0-vnext.203

npm ERR! missing: react-native-windows@0.59.0-vnext.203, required by reactnativewinapp@0.0.1
4. `node -v`:
v12.14.0
5. `npm -v`:
6.13.4
6. `yarn --version`:

Then, specify:

- Target Platform:
UWP

- Target Platform Version(s):
10.0.18362.0

- Target Device(s):
Desktop X64

- Development Operating System:
Windows 10

- Visual Studio Version:
2017

- Build Configuration:
Debug
### Steps to Reproduce
Download code from: https://github.com/johnsmithlon/reactnativebug

Install dependencies: 
npm install --save-dev @projectstorm/react-diagrams@next
npm install --save-dev @emotion/core @emotion mathjs@^6.0.3 closest@^0.0.1 resize-observer-polyfill@^1.5.1 @emotion/styled@^10.* pathfinding@^0.4.18 typescript@>=3.7.0-dev paths-js@^0.4.9 @types/styled-components styled-components dagre@^0.8.4 react-dom@>= 16.3.0 shelljs ora xml-parser 

Build VS project.

If I do react-native start and run VS2017 in debug mode I get:
Loading dependency graph, done.
 BUNDLE  [windows, dev] ./index.windows.js ░░░░░░░░░░░░░░░░ 0.0% (0/1)

The project works fine in react, but not react native. Any ideas much appreciated!

**Comment by kmelmon** [comment]
@johnsmithlon can you confirm you ran react-native windows in your project directory?  The error indicates your project doesn't support react-native-windows, which might happen if you didn't properly run react-native windows.

If you did this, can you share your package.json and we can take a look?

**Comment by johnsmithlon** [comment]
Yes I can confirm that I ran react-native windows in the project directory. The github link I provided (https://github.com/johnsmithlon/reactnativebug) includes the package.json file along with the code.

**Comment by acoates-ms** [comment]
Are you using yarn or npm?  Your yarn.lock has react-native-windows in it, but your package-lock.json does not.  Are you mixing usage of npm and yarn?

After running `npm install` or `yarn` you should have react-native-windows in your node_modules folder.

**Comment by johnsmithlon** [comment]
I am running npm only. After running npm install I do have
react-native-windows in the node_modules folder - note I didnt upload the
contents of node_modules as the files are large.

**Comment by chrisglein** [comment]
@acoates-ms We still require Node version 12.9.1, correct? The info here lists 12.14.0. Could that be the problem?

**Comment by licanhua** [comment]
I have problem to build your project, here are two cents I didn't verify it but it may help:
1. Try to use 'react-native bundle' to see if there is any error to bundle the JS. Here is an example  `react-native bundle --platform windows --entry-file index.windows.js --bundle-output windows/SampleAppCpp/Bundle/index.windows.bundle --assets-dest windows/SampleAppCpp/Bundle`
2. try `react-native run-windows`. It should helps you launch metro-bundle, chrome, also the application.
3. I expect you have Chrome installed, and open http://localhost:8081/debugger-ui/. Press F12 or Ctrl+Shift+I in Chrome to open its Developer Tools, then check if there are any error message on chrome console when the downloading start.
4. you have hard coded directory like `import 'C:\react\helloWorld\app.css';`. please put everything in reactnativebug or its sub directory, and use relative path
5. Try nodejs 12.9.1. Your problem may not related to this, but you may run into other issue which described in #3611

**Comment by licanhua** [comment]
You may also set breakpoint on functions start with `InstanceImpl::loadBundle`, and check the port, path, exceptions, and output in VS.
