### ISSUE TITLE
Build a proper ReactView control

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#3875]
Right now we fulfill the need for a View component with a complicated composition of a ViewControl, a Border, and a ViewPanel. This is not only ugly, slow, and expensive to maintain, but it causes feature gaps, especially with regards to Accessibility.

Some of these requirements include:
* Canvas-style relative positioned children
* Optional, fully featured bordering (with rounding, etc)
* Runtime Focusable/Non-Focusable

To fulfill the requirements of the very powerful and flexible View component, we really need a new low-level element in WinUI3.

Related bugs: #3111, #3836, #3874

**Comment by chrisglein** [comment]
@jonthysell Could you file a proposal on the WinUI repo that captures our needs for this?
