### ISSUE TITLE
Consider re-aligning with Facebook's clang format rules

### ISSUE THREAD

**Issue by acoates-ms** [microsoft/react-native-windows#3883]
From #3881 :
> A clang-format file matching facebook/react-native is
> added to the DeforkingPatches directory to hopefully make diffing with Facebook
> source easier.

This is the reason I went with having our clang format match Facebook's in the first place - to make it easier to move code between the two repos with the understanding that we would be working across the repos more and more.

Additive rules that only affect windows code (such as for MS UT frameworks as in #3612 should be fine.  But thing change affect all the shared Facebook code seems problematic.  At some point a decision was made to deviate from their format.  -- I think the main one being allowing longer lines.  -- As the code is being more and more intermingle with core RN code, It might make sense to align, esp if we are going to be having to diff between the two.

**Comment by NickGerleman** [comment]
I like the idea, but really really dislike the 80 character line limit. Having the project root .clang-format align and giving subprojects freedom to diverge seems like a decent compromise though. We could also just leave things as is and add matching clang-format files once there's an area we have an intent to share.
