### ISSUE TITLE
"Build and Pack Nuget" Doing No Work in PR Pipeline (Effected by Enabling LayoutHeaders)

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#3889]
We seem to at least sometimes completely no-op on "Build and Pack Nuget" for both Desktop and UWP. E.g. [this build](https://dev.azure.com/ms/react-native-windows/_build/results?buildId=58716&view=logs&jobId=afba87e8-dea4-546b-a936-828d8962d9a2&j=afba87e8-dea4-546b-a936-828d8962d9a2&t=526ad6bb-e2f8-527f-c697-9df6289f62f3)

![image](https://user-images.githubusercontent.com/835219/72506236-5f629480-37f6-11ea-8f2f-0993d2b29c66.png)

Oddly enough, enabling LayoutHeaders for UWP x86 Release, as in #3888, causes us to actually run, for both UWP and desktop. Doing this, we see issues trying to pack ReactUWP. This is despite the build step to patch the NuSpec to exclude ReactUWP. It seems like this patching step may be broken, but we hadn't noticed because we weren't running it. [Build Link](https://dev.azure.com/ms/react-native-windows/_build/results?buildId=58721&view=logs&j=560fd8c1-f9f7-5dba-ba2b-9ffa0365d89a&t=e798cde8-6fee-5b77-93c9-5bbc07fe365f)

![image](https://user-images.githubusercontent.com/835219/72506290-74d7be80-37f6-11ea-9ae9-b6a237d036de.png)

**Comment by NickGerleman** [comment]
Removing LayoutHeaders from the build matrix moved us back to the first state where we no-op, even for Desktop.

**Comment by chrisglein** [comment]
@NickGerleman Based on your comment above are you currently unblocked on this?
You assigned @JunielKatarn @licanhua and @acoates-ms and yourself to this. Is anyone actively looking at this?

**Comment by NickGerleman** [comment]
@chrisglein this isn't blocking anything, but does mean we currently lack some CI coverage we claim to have, and prevents adding back separate coverage that was accidentally removed recently, which would have prevented a bug.

I originally just added those who I know had context on the problem as assignees, but I don't think anyone is actively looking at this.

**Comment by chrisglein** [comment]
@asklar can you work with @NickGerleman to figure out what's lacking here? Seems to be another example of where we have less coverage than we should.

**Comment by asklar** [comment]
@NickGerleman said
> Still relevant, though some of it is going away with the work @Andrew Coates (REDMOND) is doing around dll distribution. 
Right now we don't test any of our legacy NuGet distribution logic in the PR pipeline, so we'll somewhat regularly see build logic changes break our ability to publish a binary for Stellar and Office.
Andrew Coates added new NuGet logic for distribution of Microsoft.ReactNative. This is run during PR, and will eventually replace the legacy logic when everything is consuming Microsoft.ReactNative (no idea how far out).
Seems puntable at this point probably.
