### ISSUE TITLE
Unable to initialize RNW vNext Project Using Current Instructions

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#3895]
### Environment

react-native-cli: 2.0.1
react-native: 0.60.6
rnpm-plugin-windows@0.4.0
Node v10.13.0
NPM 6.4.1

### Steps to Reproduce
Follow instructions for [Consuming React Native Windows](https://github.com/microsoft/react-native-windows/blob/master/vnext/docs/ConsumingRNW.md#installing-react-native-windows-vnext).

When trying to initialize the project we see this error:
```
D:\rntest\test>react-native windows --template vnext
warn Package rnpm-plugin-windows has been ignored because it contains invalid configuration. Reason: Cannot find module '@react-native-community/cli/build/tools/generator/promptSync'
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-windows: https://github.com/microsoft/react-native-windows#readme
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.
error Unrecognized command "windows".
```

**Comment by chrisglein** [comment]
@NickGerleman Those look like warnings. Does it emit the warnings and also succeed or does it outright fail?

**Comment by NickGerleman** [comment]
@chrisglein The last line 'error Unrecognized command "windows".' will stop the command from moving forward.

**Comment by chrisglein** [comment]
@NickGerleman We've often seen troubles with the plugin installed in the wrong directory, which can manifest this error. I see you've listed your plugin version, can you confirm where it is installed. It should be run inside the project directory and run before you run `react-native windows`, which is a subtle detail.

**Comment by chrisglein** [comment]
Just hit this sitting down with @jeffstall.
@NickGerleman by chance were you using NPM direct or Yarn?

**Comment by chrisglein** [comment]
Confirmed working with Jeff that using Yarn unblocked him. Seems like we have some problem in the getting started instructions when using just npm that is broken now. @acoates-ms any ideas?

**Comment by NickGerleman** [comment]
Haven't looked at this at all, but I wonder if npm and yarn will resolve different packages. E.g. if they handle pre-releases differently or something.

**Comment by NickGerleman** [comment]
@chrisglein I seem to run into the same issue using npm instructions. Is there a known good lockfile we could diff mine to?

**Comment by tbandrowsky** [comment]
Just as an FYI, the instructions should be followed by running a command line console in administrative mode.  That fixes a lot.

**Comment by NickGerleman** [comment]
Closing since this is a dupe of #3862 

@tbandrowsky have you had issues following the instructions using a non-administrator command prompt? I don't think that's something we intend to require.

**Comment by tbandrowsky** [comment]
Hey Nick.  Looks to me like there's two cases.  One is, it's moving some md files to projects for the benefit of React Native.  That may be a consequence of only having Visual Studio 2019 although I do have earlier build tools installed. The other is, when it goes to actually deploy the application to my Windows desktop.  I have developer mode on but for some reason when I do react-native run-windows and it does the build, at deploy, it gets irritated unless I'm in admin mode on the command line.
