### ISSUE TITLE
Beachball Publish in Pipeline Times out When Bumping Version

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#3896]
![image](https://user-images.githubusercontent.com/835219/72596363-bfbe0880-38c0-11ea-9ed7-074004ef431d.png)
https://dev.azure.com/ms/react-native-windows/_build/results?buildId=58911&view=results

This seems potentially related to a beachball update that just happened. The hang happens before we even try to publish to the NPM registry.

**Comment by NickGerleman** [comment]
Confirmed this is due to the dependency change.

With Beachball 1.18.1 installed locally, `npx beachball publish --no-push --no-publish` at master works as expected.

```
D:\react-native-windows>npx beachball publish --no-push --no-publish -y
Checking for changes against "origin/master"
fetching latest from remotes
Publishing with the following configuration:

  registry: https://registry.npmjs.org/

  current branch: master
  target branch: origin/master
  tag:

  publishes to npm registry: no
  pushes to remote git repo: no


Bumping version for npm publish
Skipping bumping private package "e2etest"
Skipping bumping private package "microsoft-reactnative-sampleapps"
Skipping bumping private package "playground"
Skipping publish
Skipping git push and tagging
git checkout master
```

After updating to 1.18.2 I see the hang.

**Comment by kenotron** [comment]
I just added some bits of logic to allow for customizable change type for dependent package bumps. This turned out to cause an infinite loop. I'm working on this now. Thanks for reporting this on https://github.com/microsoft/beachball/issues/241
