### ISSUE TITLE
环境配置问题

### ISSUE THREAD

**Issue by 527395632** [microsoft/react-native-windows#3898]
版本更新比较多, 然后现在的环境配置文档感觉不太对, 多次配置始终配置不成功, 不知是否可以得到帮助! 我的email: 527395632@qq.com, tel: +86 177 0581 4618, 希望可以得到团队帮助, 目前一直卡在环境配置过程中。current文件夹中的项目能正常编译, 启动后会访问一个http://localhost:8081/***.bundle?***的一个url, 这个我猜应该是notejs环境运行的, 只是这个环境一直起不来, 这个url访问不到, 返回一直是httpCode=404

**Comment by chrisglein** [comment]
(automated) Translation:

> Environmental configuration issues

> There are more version updates, and the current environment configuration document doesn't feel right. The configuration has been unsuccessful for many times. I don't know if I can get help! My email: 527395632@qq.com, tel: +86 177 0581 4618, I hope I can With the help of the team, I have been stuck in the environment configuration process. The project in the current folder can be compiled normally. After starting, it will visit a URL of http: // localhost: 8081 / ***. bundle? ***. I guess this should be run in the notejs environment, but this environment has been Can't get up, this URL cannot be accessed, and the return is always httpCode = 404

@527395632 Can you give us more detail on the steps you've followed for setup and where you are in that process? The issue template has some instructions for how to gather environmental data so we can better help you.
