### ISSUE TITLE
windowPhysicalPixels is in DIPs and not in pixels

### ISSUE THREAD

**Issue by azchohfi** [microsoft/react-native-windows#3924]
This is an issue on vnext. vnext\ReactUWP\Modules\DeviceInfoModule.cpp should return Physical Pixels but it's returning DIPs for the windowPhysicalPixels variable. Also, the scale variable is not correct when using, for example, 175%. This is a rounding issue on the DeviceInfo::update method.

**Comment by chrisglein** [comment]
Sounds like there's an issue with this new event that was added.
It's reflecting the root element, and not the window. Also it's returning DIPs and not physical pixels. Also the scaling factor seems to not work in non-integers. Seems like this needs some fixes and some tests to cover these scenarios.

**Comment by ddalp** [comment]
Fixed.
