### ISSUE TITLE
Running default vNext project fails at 'react-native start'

### ISSUE THREAD

**Issue by anjc** [microsoft/react-native-windows#3925]
### Environment

If you are using latest version:
1. `react-native -v`:
```
react-native-cli: 2.0.1
react-native: 0.60.6
```

2. `react-native run-windows --info`:
```
System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 3.37 GB / 7.93 GB
Binaries:
    Node: 13.5.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: ^0.60.0 => 0.60.6
    react-native-windows: 0.60.0-vnext.115 => 0.60.0-vnext.115
    rnpm-plugin-windows: ^0.4.0 => 0.4.0
Installed UWP SDKs:
    10.0.18362.0
```

Then, specify:

- Target Platform Version(s): 10.0.18362.0

- Target Device(s): X86 when using react-native run-windows, X64 in VS 2019

- Visual Studio Version: VS 2019 v16.4.3

- Build Configuration: Debug

### Steps to Reproduce

1.  I followed the steps in [Getting Started](https://microsoft.github.io/react-native-windows/docs/getting-started) & [Consuming](https://microsoft.github.io/react-native-windows/docs/consuming-rnw) with an elevated command prompt after installing Chocolatey, Yarn and verifying that I had all of the necessary components from VS 2019 ready to go - wow, that was some questionable grammar.
a. `choco install nodejs`
b. `npm install -g react-native-cli`
c. `react-native init vNext --version 0.60.6`
d. `cd vNext`
e. `yarn add rnpm-plugin-windows`
f. `react-native windows --template vnext`

2. Then I downloaded [Chrome](https://www.google.com/chrome/), closed the rest of my browsers, and left Google's running.

3. This is where everything falls apart. When I try to run `react-native run-windows`, the script fails upon executing `react-native start`. This of course means debugging with Visual Studio won't work either, since I would need to run `yarn start` - which also executes `react-native start`.

### Expected Behavior

I expected the react-native service to start? I don't know what else to say, I'm a bit perplexed.

### Actual Behavior

Primary prompt
![image](https://user-images.githubusercontent.com/36517378/72857796-b64fea00-3c8c-11ea-95fe-2d3928926587.png)
*Developer mode is on.*

Temporary prompt
![image](https://user-images.githubusercontent.com/36517378/72857915-0dee5580-3c8d-11ea-92b5-dfd190688f71.png)
*Would you like the [log](https://github.com/microsoft/react-native-windows/files/4094822/2020-01-22T00_51_22_253Z-debug.log) instead?*

### Reproducible Demo

You can view the source code for the project [here](https://github.com/anjc/SRequests/tree/master/vNext) to see if you encounter the same problems when running `react-native run-windows` - or `yarn start`, if you’d rather compile the app with Visual Studio instead.

### Additional context

This is the first time I've ever touched React Native - I've traditionally worked with C# + .NET Core, raw JS on the web, and Java stuff - so I can't think of anything useful to add.

**Comment by NickGerleman** [comment]
@acoates-ms was this the issue with newer versions of Node?

**Comment by anjc** [comment]
Yes, it was. I reinstalled the specific version of node listed in the docs - and then rebuilt the project for good measure - and the service started successfully.

**Comment by chrisglein** [comment]
@anjc Sounds like updating to the supported Node version unblocked you. If that's not the case reactivate this issue.
