### ISSUE TITLE
Serial port communication

### ISSUE THREAD

**Issue by dubiao** [microsoft/react-native-windows#3926]
# Proposal: [Is that possible to have serial port communication on this] 

## Summary

We are building a professional app that may will use serial port communication to send commands to our devices.
How can I  select a COM port and send commands to that port?

**Comment by chrisglein** [comment]
@dubiao the short answer is you'll need to write a native module to expose this platform behavior (for something like a serial port you're not going to find existing modules for Android or iOS I'm guessing ;)). We're currently landing more support for this in our 0.61 milestone. @stmoy Can you provide the best documentation links here?

**Comment by chrisglein** [comment]
This might be of use: https://techcommunity.microsoft.com/t5/windows-dev-appconsult/building-a-react-native-module-for-windows/ba-p/1067893#M202

**Comment by NickGerleman** [comment]
The React Native Windows page has documentation for modules now. Closing this issue.

**Comment by divyanshgarg96-6** [comment]
Now do we have any npm package that can do the stuff mentioned above?
Like passing the commands to our device and reading the output provided by the device?
