### ISSUE TITLE
ExtendedDeviceInfo Windows module

### ISSUE THREAD

**Issue by YuliKl** [microsoft/react-native-windows#3929]
# Proposal: ExtendedDeviceInfo Windows module

## Summary

Encapsulate [Surface Neo](https://www.microsoft.com/en-us/surface/devices/surface-neo) device info to be readily available in RN.

Details tracked in https://github.com/react-native-community/discussions-and-proposals/issues/189

## Motivation

Make it easier to [develop apps for Windows 10X dual-screen devices](https://docs.microsoft.com/en-us/dual-screen/windows/)

**Comment by chrisglein** [comment]
Worth adding a link here to the repo where the work is happening: https://github.com/microsoft/react-native-dualscreen
