### ISSUE TITLE
Must run elevated (otherwise stuck "Generating self-signed certificate")

### ISSUE THREAD

**Issue by mpiannucci** [microsoft/react-native-windows#3930]
### Environment

If you are using latest version:
1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.60.6

2. `react-native run-windows --info`:
  System:
    OS: Windows 10 10.0.18362
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 16.86 GB / 31.78 GB
  Binaries:
    Node: 10.16.0 - C:\Users\miannucci.NAVATEKLTD\Development\nodejs\node.EXE
    Yarn: 1.17.3 - C:\Users\miannucci.NAVATEKLTD\Development\nodejs\yarn.CMD
    npm: 6.9.0 - C:\Users\miannucci.NAVATEKLTD\Development\nodejs\npm.CMD
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: ^0.60.0 => 0.60.6
    react-native-windows: 0.60.0-vnext.118 => 0.60.0-vnext.118
    rnpm-plugin-windows: ^0.4.0 => 0.4.0
  Installed UWP SDKs:
    10.0.17134.0
    10.0.17763.0

Then, specify:

- Target Platform Version(s): 10.0.18362

- Target Device(s): Desktop

- Visual Studio Version: 2017

- Build Configuration: Any

### Steps to Reproduce

1. `react-native init myproject --version 0.60.6`
2. `yarn add rnpm-plugin-windows`
3. `react-native windows --template vnext`

### Expected Behavior

Expected the project to be generated

### Actual Behavior

The install process gets stuck indefinitely on `Generating self-signed certificate...`

![image](https://user-images.githubusercontent.com/1832671/72928806-9d941280-3d26-11ea-982c-317278215cd6.png)

### Reproducible Demo

Just the instructions for consuming the project

### Additional context

No elevated cmd prompt available

**Comment by chrisglein** [comment]
@mpiannucci Currently the steps require you to be in an elevated command prompt, and I believe this is the reason why. Is it possible to run this elevated and unblock yourself.

We would like to remove that requirement, but for the short term that's the case. I'll use this issue to track this requirement.

**Comment by mpiannucci** [comment]
@chrisglein unfortunately its not possible on this machine. It is a corporate managed laptop with no admin for the time being. 

Good to know that's whats going on though.

**Comment by mpiannucci** [comment]
Is this available from the beta channel now? I tried to create a fresh project using the beta channel and still see the hang

**Comment by NickGerleman** [comment]
@mpiannucci the fix should be available in `react-native-windows@0.61.0-beta.72`. Is this version or later what ends up getting installed?

**Comment by mpiannucci** [comment]
Yeah its telling me that beta.73 is installed but it still hangs unfortunately . I checked the if this patch is in the node_modules/react-native-windows folder and it is, but for some reaason it hangs. 

For now I can work around it by commenting out the powershell stuff then commenting out the rnpm commands that download the latest version but I figured id keep the issue up to date

**Comment by NickGerleman** [comment]
Thanks for letting us know! I'm going to reopen this. FYI @acoates-ms

**Comment by mpiannucci** [comment]
Awesome it works!! Thank you!
