### ISSUE TITLE
react-native windows not working

### ISSUE THREAD

**Issue by fs-kanayama** [microsoft/react-native-windows#3937]
run latest

```
$ react-native windows
Reading application name from package.json...
Reading react-native version from node_modules...
What version of react-native-windows would you like to install?  Choose one of:  legacy, latest [default]:
legacy
Checking for react-native-windows version matching 0.61.*...
Could not find react-native-windows@0.61.*. Latest version of react-native-windows is 0.59.0-legacy.1, try switching to react-native@0.59.*.
```

run regacy

```
$ react-native windows
Reading application name from package.json...
Reading react-native version from node_modules...
What version of react-native-windows would you like to install?  Choose one of:  legacy, latest [default]:
latest
Checking for react-native-windows version matching 0.61.*...
Could not find react-native-windows@0.61.*. Latest version of react-native-windows is 0.59.0-legacy.1, try switching to react-native@0.59.*.
```

not working?

**Comment by leoek** [comment]
@fs-kanayama The newest available react-native-windows `current` version is `0.59`, even if 0.60@current was planned for fall 2019. There is an open issue about the roadmap of react-native-windows here: https://github.com/microsoft/react-native-windows/issues/2815

@harinikmsft Can you please take a look at https://github.com/microsoft/react-native-windows/issues/2815 and update the roadmap and etas or forward this to someone who can?

**Comment by chrisglein** [comment]
@fs-kanayama When you did your `react-native init` what version did you supply? Doing legacy (aka current) only supports 59 as stated above. Currently the CLI tool does help you with the supported version.

@kmelmon as an FYI if you want to make the error message better and/or include version support.

**Comment by kirill-zhukov** [comment]
It indeed does not work out of the box.
The solution is to implicitly declare the version of latest available package:
npx react-native windows --windowsVersion 0.61.0-beta.8
