### ISSUE TITLE
Re-enable E2E test 

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#3953]
We recently had to disable E2E test because of out-of-disk-space issues.  See:

https://dev.azure.com/ms/react-native-windows/_build/results?buildId=60011&view=logs&jobId=a27d21fd-a31d-5038-a902-0ee58cd3b281&j=a27d21fd-a31d-5038-a902-0ee58cd3b281&t=6750b87c-c5d0-5ba3-de8e-6dea356eee8d

and

https://dev.azure.com/ms/react-native-windows/_build/results?buildId=60035&view=logs&j=a27d21fd-a31d-5038-a902-0ee58cd3b281&t=b9160bdc-c3f8-5729-1c03-449e66b7943e

This task is tracking solving the disk space issue and re-enabling the test.

**Comment by licanhua** [comment]
From Andrew's testing, C: is running out of space: https://dev.azure.com/ms/react-native-windows/_build/results?buildId=60035&view=logs&j=a27d21fd-a31d-5038-a902-0ee58cd3b281&t=b9160bdc-c3f8-5729-1c03-449e66b7943e

It's possible introduced by vs2019 image version: '20200116.1'
