### ISSUE TITLE
Use v142 for E2E test on vs2019 build machine

### ISSUE THREAD

**Issue by licanhua** [microsoft/react-native-windows#3960]
It has two benefits:
1. we don't need to install v141 toolsets which would save 17 minutes on E2E pipeline, also ~2GB disk on D drive(currently D is not the bottleneck yet).
2. Don't need workaround for #3953 which would save 7 minutes. Since vs2019 image version: '20200116.1', C drive only have 4G free space, which has problem to restore all nugets(lots of them are installed to C drive) to build E2E test and other projects which would using vs2019 image.

**Comment by chrisglein** [comment]
Related to #3476

**Comment by chrisglein** [comment]
If instead we were shipping the dll instead of the source could we avoid these build issues? At least for the general case (could have source for those who need it).
