### ISSUE TITLE
Inventory of Forked/Copied Code from Other Libraries

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#3962]
We should consider moving these to some package import scheme when time permits. This is especially true for Facebook code, which we need to keep in sync. Having large source copies has also historically encouraged local changes that are not pushed back.

- JSI Unit Tests (@hansenyy)
  - Are these published right now?
- IntegrationTest and RNTester Javascript (@NickGerleman and @ddalp)
  - https://github.com/react-native-community/discussions-and-proposals/issues/187]
- Deforking Patches (@NickGerleman)
  - Some likely no longer needed
  - Try to upstream Yoga changes
- Mso (@vmoroz)

**Comment by hansenyy** [comment]
The JSI unit tests are now published under ReactCommon\jsi\jsi\test\testlib.h and cpp. I have been wanting to remove JsiRuntimeUnitTests.h/cpp in favor of testlib.h, but have not gotten around to it.

**Comment by NickGerleman** [comment]
We have separate bugs for Yoga(#3994), JSI Unit tests(#4053), RNTester/IntegrationTests(#4054) and Instance Management(#4051). Going to close this bug in favor or them.
