### ISSUE TITLE
'Question: gradually migrating from a WPF app'

### ISSUE THREAD

**Issue by promontis** [microsoft/react-native-windows#3963]
Hi there! 

I was wondering if it is possible to gradually migrate from a WPF to React Native Windows? To be more precise, I would like to either:

1. Load newly build React Native Windows components (or whole 'modules') in the existing WPF app, and gradually migrate each existing WPF component to its equivalent in React Native Windows.

2. The other way around... load parts of the existing WPF app in a React Native Windows application, and gradually migrate each existing WPF component to its equivalent in React Native Windows

Is it possible to host such existing WPF components in React Native Windows? Or the other way around? If yes, could you point me into the right direction?

Thanks,

Michel

**Comment by chrisglein** [comment]
There's a sample (and blog) that covers the scenario of hosting RN content inside a WPF app: https://github.com/microsoft/react-native-windows-samples/tree/master/samples/TodosFeed

Hopefully that has enough info to get you started!
