### ISSUE TITLE
Focus cannot be set on a Picker

### ISSUE THREAD

**Issue by melvsparks** [microsoft/react-native-windows#3982]
# Proposal: Allow focus to be set on a Picker

## Summary
Add a public focus method to the component that allows focus to be set to a picker

## Motivation
In Universal calendar accessibility, we need to be able to set focus to the reminder picker to allow the user to navigate (using tab and shift+tab) to the picker.

All main components should allow focus to be programitically set.

**Comment by chrisglein** [comment]
The infrastructure is there to have all views support this, but there may be issues preventing it from working for anything other than View or TextInput. Seems like there's per-component work.

This component is planned to move out via #3036. That will mean that we'll also need to support this in the community module on Windows but not on Android, for example. So there's some design work here.

**Comment by licanhua** [comment]
Dup of #2683.
