### ISSUE TITLE
Remove NativeOrDynamicColor Related Patches When PlatformColor is Available

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#3990]
These are replicated for both win32 and windows right now (but might diverge further). These will be superseded by https://github.com/react-native-community/discussions-and-proposals/issues/126.

**Comment by harinikmsft** [comment]
PlatformColor API will be part of RN v0.63. Windows will consume this once it is available and match when shipping corresponding react-native-windows v0.63.

**Comment by acoates-ms** [comment]
Fixed in #5028
