### ISSUE TITLE
Make DeviceInfo XAML-Islands-friendly

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#4002]
DeviceInfo has code in it that is specific to CoreWindow (for the window bounds) and DisplayInformation (for the DPI).  The module feeds this data into Dimensions which reports the window size & scale factor to apps.  Neither of these will return the correct answer in a multi-window or multimon scenario.  This comes up both for XAML Islands as well as other future-looking scenarios such as the new HWND hosting mode being built for WinUI 3.0.

We'll need to think through how to make Dimensions be a multi-window and multimon aware.

**Comment by chrisglein** [comment]
Related to #3567 .

**Comment by chrisglein** [comment]
May need to propose changes to the DeviceInfo shape in order to really handle this stuff.

**Comment by asklar** [comment]
Related: https://github.com/microsoft/ProjectReunion/issues/114
