### ISSUE TITLE
Investigate Reenabling Integration Tests

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#4007]
The Microsoft fork of React Native commented out several integration tests in `IntegrationTestsApp.js`. We should investigate if we can enable some of them on Windows to increase test coverage a bit.

**Comment by chrisglein** [comment]
Some history here is that some of these tests were flaky. Probably an opportunity to communicate back to Facebook about those and see if they should be addressed/retired. We'd rather invest in E2E of RNTester.
The tests aren't currently published. This is currently an issue on the fork but could become an issue here if they are published (as has been proposed).

**Comment by NickGerleman** [comment]
Closing this since there isn't active work for desktop integration tests
