### ISSUE TITLE
RNTester Example Text is Invisible When Windows Using Dark Theme

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#4014]
Steps to repro:
1. Build playground project
2. Launch and load RNTester bundle
3. Go to ActivityIndicator page

Windows Light theme:
![image](https://user-images.githubusercontent.com/835219/73586092-86a79b80-445d-11ea-9395-8e46aa8f6e41.png)

Windows Dark theme:
![image](https://user-images.githubusercontent.com/835219/73586100-a5a62d80-445d-11ea-8e8a-4141d09b39d9.png)

**Comment by NickGerleman** [comment]
Reproes on 0.60.0-vnext.133
Reproes on 0.60.0-vnext.100 (Dec 19)

This does not appear to be a recent regression.

**Comment by chrisglein** [comment]
Either the app needs to respect light/dark theme using the new/current API. Or it needs to not let you change theme and choose one.

**Comment by NickGerleman** [comment]
Closing since this was fixed.

**Comment by marlenecota** [comment]
Re-activating as the workaround was removed.

**Comment by NickGerleman** [comment]
@marlenecota this should be fixed in 62 due to upstream changes. Can you confirm?

**Comment by marlenecota** [comment]
That's using the Appearance module which we don't currently have. I was going to use AppTheme until the upgrade to 63 where AppTheme will be migrated to Appearance.

**Comment by NickGerleman** [comment]
@marlenecota I implemented AppearanceModule during the 0.62 work. You can confirm in Playground so long as you turn off web debugging. The Appearance JS otherwise always claims to be in light mode.

**Comment by marlenecota** [comment]
Can confirm dark mode works with web debugger off
