### ISSUE TITLE
Switch to C++/WinRT -optimized

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#4019]
Forked from #3807

[Switch to C++/WinRT -optimized.](https://github.com/microsoft/microsoft-ui-xaml/pull/1737)

C++/WinRT has a mode for generating the component projection called "Optimized". The big advantage here is that constructing objects and calling static methods of things that are in the same component can go to the implementation directly and avoid going through GetActivationFactory.

**Comment by vmoroz** [comment]
As far as I know the Microsoft.ReactNative and Sample projects use the C++/WinRT -optimized flag for some time already. I this bug about some other projects?

**Comment by vmoroz** [comment]
Closing it as we already use the -optimized flag.
