### ISSUE TITLE
Add void support to Microsoft::ReactNative::ReactPromise

### ISSUE THREAD

**Issue by namrog84** [microsoft/react-native-windows#4020]
Example scenario:

```
REACT_METHOD(SomeFunc)
void SomeModule::SomeFunc(ReactPromise<void>&& promise){
    promise.Resolve( ??? );
}
```
There isn't anything that is valid that can go in ??? when it is void

* `promise.Resolve()`
  * errors on "too few arguments in functon call"
* `promise.Resolve({})`
  * cannot convert initializer list to int &

However something like this does work
```
void SomeModule::SomeFunc(ReactPromise<void>&& promise){
    int dummyValue;
    promise.Resolve(dummyValue);
```

The workarounds are less than ideal. Such as using dummyValue, or changing from void to int or string. 

I believe there needs to be an special edge case for ReactPromises for void.

Unless there is some other special C++ magic way of handling this that I am not aware of.

**Comment by vmoroz** [comment]
Good point! I will fix it.

**Comment by vmoroz** [comment]
Fixed by https://github.com/microsoft/react-native-windows/pull/4041
