### ISSUE TITLE
Images are mirrored in RTL mode

### ISSUE THREAD

**Issue by sayzenberg** [microsoft/react-native-windows#4026]
### Environment

```
$ react-native -v
react-native-cli: 2.0.1
react-native: 0.60.0-microsoft.35

$ react-native run-windows --info
  System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz
    Memory: 37.32 GB / 63.90 GB
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react-native: 0.60.0-microsoft.35 => 0.60.0-microsoft.35
    react-native-windows: 0.60.0-vnext.121 => 0.60.0-vnext.121
  Installed UWP SDKs:
    10.0.14393.0
    10.0.17134.0
    10.0.17763.0
    10.0.18362.0
                                        
```

Target Device: Desktop
VS 2019
Repros in Debug and Release

### Steps to Reproduce

1. Create a View with an Image element in it
2. Set the preferred language in the OS to any RTL language (Arabic, for example)

### Expected Behavior
Layout elements should be mirrored in position, but Images should not be mirrored.

### Actual Behavior
Images are mirrored along with everything else in the UI. The only mitigation is to set `direction: 'ltr'` on the style of the Image element.

Sample image in en-US:
![image](https://user-images.githubusercontent.com/1684243/73779935-64a26780-4742-11ea-8c0f-138fdb33ef99.png)

Sample image in ar-SA:
![image](https://user-images.githubusercontent.com/1684243/73779956-6f5cfc80-4742-11ea-9443-e103e115f6eb.png)

**Comment by harinikmsft** [comment]
We accomplish RTL layout in the yoga layout rather than using XAML's FlowDirection APIs. Fix here may involve doing something similar to what XAML does and unflip images.
