### ISSUE TITLE
Universal ARM64 needs a 16299+ (RS3) 

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#4031]
PR #3903 added some ARM64 configurations, and added it in the CI loop, but did not
* Update the min version to 16299
* Add ARM64 configurations to every project
* Enable solution configurations to actually build all of the projects in ARM64

**Comment by harinikmsft** [comment]
@JunielKatarn - can you take a look at this?

**Comment by JunielKatarn** [comment]
@harinikmsft Hi. I don't have enough context to validate these scenarios, plus I'm currently working on the OpenSSL upgrade for Desktop.

Can this be assigned to someone else?
For context, I got involved with `ARM64` because I happened to have an experimental branch, and an external team asked to accelerate its delivery.

**Comment by jonthysell** [comment]
Well, we need to decide what we want to do:

1. Remove the ARM64 references since they don't work and might confuse customers into thinking we support something we don't.
2. Actually bump our min version to 16299 so we can support ARM64.
3. Only bump to 16299 for ARM64.

I think 1 is the easiest thing to do in the short term.

**Comment by JunielKatarn** [comment]
@jonthysell 

`ARM64` was strongly requested. It apparently is critical for a  consuming team for performance reasons (they can't rely on CHPE). I would vote against `1`.
Solution `2`  sounds best to me, but I don't know if there is a requirement for older Windows 10 releases.
Solution `3` will surely work as a compromise. In short, I don't think we are  blocked. Just need to decide whether `16299` can be set as the global minimum version or not.

**Comment by YuliKl** [comment]
> 3. Only bump to 16299 for ARM64.

Let's investigate this option. @jonthysell can you ping Jared about their status for this?

**Comment by NickGerleman** [comment]
Closing "#3629 Add ARM64 build configurations" in favor of this, and adding marking this P1 since the old bug was.

FYI @chrisglein @kmelmon

**Comment by jonthysell** [comment]
Looking into this now that we're on RS3+
