### ISSUE TITLE
Releases should contain a description of the changes in that release

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#4033]
Look at RNW's release changelog: https://github.com/microsoft/react-native-windows/releases

![image](https://user-images.githubusercontent.com/26607885/73799533-148bcb00-476b-11ea-993f-d533241e2d44.png)

Compare to RN's release changelog: https://github.com/facebook/react-native/releases/

![image](https://user-images.githubusercontent.com/26607885/73799458-ec03d100-476a-11ea-9b80-b7078bc06031.png)

Or WinUI's changelog: https://github.com/microsoft/microsoft-ui-xaml/releases/

![image](https://user-images.githubusercontent.com/26607885/73799499-0342be80-476b-11ea-93dc-b8c5e36801da.png)

Another example in the VSCode React Native extension: https://github.com/microsoft/vscode-react-native/releases/tag/0.16.0. Seem to be auto generated with their ADO pipeline.

There's no hand-authored release notes. But we also don't see any of the changes in the changelog or commit descriptions, making it not at all informative as to what's in that release.

We need a low-effort solution to this so that it actually happens. Maybe it's fully automated, maybe it's partially automated, maybe it's fully manual. But regardless we shouldn't continue putting out releases with zero description.

**Comment by NickGerleman** [comment]
I was curious about this earlier, and there doesn't seem to be a way to filter out tags from our releases page in Github. I.e. we would get 30 entries a month unless we changed how we publish our builds.

We have a generated changelist in vnext that's not super useful for public facing documentation.

**Comment by chrisglein** [comment]
WinUI's answer on how they do this:
> We’re using the Azure DevOps Release pipelines to automate it. The [GitHub Release task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/github-release?view=azure-devops) handles the creation of the release on GitHub and also generating the changelog.

**Comment by NickGerleman** [comment]
There's been offline discussion about the viability of this in virtual shiproom. Haven't seen followup conversation on this. Flagging for retriage.

**Comment by chrisglein** [comment]
We want an automated solution. You can see what WinUI is doing linked above. Maybe we can harvest what beachball is doing.

In the short term even a manual process would be a huge upgrade for big releases. Plus a blog post...

Kiki is swamped with Build conference stuff. Also this likely needs more engineering attention.
@NickGerleman I'm going to give to you to look into.

**Comment by NickGerleman** [comment]
FTY @kikisaints @chrisglein I don't think automated release notes in GH will be valuable to most consumers since we have nightly builds. We do have automated changelogs generated in `vnext/CHANEGLOG.md` that I linked to offline already that can be utilized if we want to do blog posts from them.

I realistically can't see myself working on an automated way to get changes to show up in GH releases in the near future. Assigning to the backlog for now. Will defer to PM on what release notes should look like in blog posts, if we want to link them in other docs, etc.

**Comment by chrisglein** [comment]
> FYI @kikisaints @chrisglein I don't think automated release notes in GH will be valuable to most consumers since we have nightly builds. We do have automated changelogs generated in `vnext/CHANEGLOG.md` that I linked to offline already that can be utilized if we want to do blog posts from them.

The format of release notes that WinUI uses has proven to be useful to consumers, and is at least partially automated. I definitely think there's value here. Also, they have existing processes we can likely copy and follow, so hopefully we don't need to reinvent the wheel.

Put the priority another way, if you click through Releases on our github you get the a pretty lackluster set of information. I've had to direct partners through finding the build with the change they want and... it's not as smooth of an experience as it should be. Fixing that is a must, at least for major releases.

If we survive by doing that manually for major releases, okay (sounds like that's your plan for 0.62?). But we really should be lowering the effort needed here.

> I realistically can't see myself working on an automated way to get changes to show up in GH releases in the near future. Assigning to the backlog for now. Will defer to PM on what release notes should look like in blog posts, if we want to link them in other docs, etc.

I think the timeline is still valid, so I'm restoring to a milestone (although I'm assuming you're doing manual notes for 0.62). In the future if you personally don't have bandwidth you should unassign yourself rather than change the milestone.

**Comment by NickGerleman** [comment]
@chrisglein the automated notes would show up mostly for our nightly master builds instead of anything users have. That's where the confusion comes from. E.g. imagine something looking like this: https://github.com/microsoft/react-native-windows/blob/master/vnext/CHANGELOG.md

**Comment by NickGerleman** [comment]
So like, right now while we're doing work on the 0.62 preview, only one bit would show something useful to users in what was cherry-picked.
![image](https://user-images.githubusercontent.com/835219/82288650-d0a68580-9957-11ea-876b-f94c9ee346f7.png)

**Comment by NickGerleman** [comment]
Can talk more offline if interested but with branch structure it will be hard to make this useful imo. Downgrading priority was more of "this isn't going to work well given current constraints" than the individual bandwidth part.

**Comment by NickGerleman** [comment]
Taking further conversation offline, but I'm going to set the priority according to my understanding of the issue. Apologies if I've had trouble communicating this.

**Comment by chrisglein** [comment]
A way to filter out nightly builds?
Can we learn from facebook in using [tags] to call out breaking changes etc.?
How can we link up the more curated messages?
We have a changelog, how do we link that up and/or make more discoverable? https://github.com/microsoft/react-native-windows/blob/master/vnext/CHANGELOG.md

If none of the above, can we hide the Releases tab?

**Comment by NickGerleman** [comment]
Beachball added functionality to control tagging. I have another PR out to Beachball to add a bit more granularity, and an accompanying change to cut down on tag spam. Tags have been cleaned up, and we have a script to manually populate release notes. It's not automated yet, and needs to be backported to stable branches, but the overall work is there now. Linking that script to close this.
