### ISSUE TITLE
Create plan to move/retire vCurrent

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#4034]
With M4 we're firmly switching to the C++-based `vnext` as the default RNW implementation and officially end investment in the C#-based `current`. So... what happens to `current`?

The short answer is we need a plan.

Existing consumers of `current` need to keep working, and developers who need some feature that may work on `current` but not on `vnext` (yet) need a solution. But we don't need to support both in this source tree simultaneously for that to be true. We need our labels in order so someone can pull the right content from the CLI. And we should have some level of documentation for how to stay on `current` ("legacy") so we minimize disruption to these developers.

Then we can move `current` within the source tree, or delete it entirely (relying on a fork off an old commit if we need to patch it for some reason).

This issue tracks coming up with a plan for this transition. The goal at the end of the day is that it's abundantly clear that `vnext` is the _the_ solution, and that we don't disrupt developers that depend on `current` as it exists today.

**Comment by jonthysell** [comment]
Resolved in #4272
