### ISSUE TITLE
Upgrade to 61:  View.accessibilityState API change

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#4042]
In the upgrade to react-native 0.61, View got some new accessibility props:
accessibilityState, which will replace accessibilityStates.
accessibilityActions
onAccessibilityAction

For accessibilityState, see:
https://github.com/facebook/react-native/pull/24608

We'll need to add support for these new props in react-native-windows starting with 61

**Comment by NickGerleman** [comment]
AccessibilityStates (plural) is completely removed in 0.62. Is this going to break us?

**Comment by NickGerleman** [comment]
I.e. did we do the work in our view managers to support the new API. Guessing not.

**Comment by kmelmon** [comment]
Yes I am pretty sure this will break us.  @jonthysell can you confirm?

**Comment by NickGerleman** [comment]
Going to mark this for retriage. If we don't have it before 0.62 comes around we lose the accessibility functionality in general. Looking at the change though, I don't think this would be hard to reimplement, since the data is just presented in a slightly different way.

https://github.com/facebook/react-native/pull/24608

**Comment by kmelmon** [comment]
I just played around with the accessibility RNTester page on 0.62.  The older accessibilityStates API technically still works, but only because the RNW code happens to allow the property.  The RN docs now have no mention of accessibilityStates so we really need to implement accessibilityState in order to be compatible with the new standard.

**Comment by kmelmon** [comment]
Note:
These two APIs were already implemented:
accessibilityActions
onAccessibilityAction
