### ISSUE TITLE
react-navigation-stack causes errors when imported

### ISSUE THREAD

**Issue by brukberhane** [microsoft/react-native-windows#4044]
### Environment

 - `react-native` Version: 0.60.6
- `react-native-windows` Version: 0.60.0-vnext.136 
- Target Platform Version(s): 18362
- Target Device(s): Desktop
- Visual Studio Version: Visual Studio 2019
- Build Configuration: Debug

### Steps to Reproduce

```
react-native init <project> --version 0.60.6
cd <project>
yarn add rnpm-plugin-windows
react-native windows --template vnext
yarn add react-navigation react-navigation-stack
```

### Expected Behavior

I would expect to be able to use the createStackNavigator function without any hiccups maybe minus the header.

### Actual Behavior

Upon import of `react-navigation-stack` into the App.js file![image](https://user-images.githubusercontent.com/20716815/73967376-d4724700-4928-11ea-8f93-0916109ee027.png)
, I am greeted with an error that says: 
![image](https://user-images.githubusercontent.com/20716815/73967928-ea343c00-4929-11ea-9122-c3652875f770.png)

### Reproducible Demo

https://github.com/brukbrhane/rn-windows_navigation_demo.git

### Additional context

I only found this error on the import of react-navigation-stack but it is prevalent in react-navigation-drawer but react-navigation-drawer doesn't show the error until you've tried to actually use `createDrawerNavigator`

**Comment by harinikmsft** [comment]
@stmoy - can you check on the priority of this community module? It appears that this is a JS module and may have some bugs with the windows side of things. Will need to understand how high pri this is before funding it.

**Comment by stmoy** [comment]
It looks like this is part of react-navigation, which is tracked here: https://github.com/microsoft/react-native-windows/issues/2546

This task is currently on the backlog and isn't actively funded right now, but has come up several times.

**Comment by harinikmsft** [comment]
Moving this to backlog and assigned to @stmoy to figure out the right navigation module we want to add contribution to. We can tackle this once we identify our next steps.
