### ISSUE TITLE
Move Patch-Style JS Overrides to a Diff Based Representation With Integrity Checks

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#4052]
We currently replace a lot of the JS used in React Native with custom versions.  Many of these are making small patch style changes to existing code. Doing this makes it easy to change the API surface more than it already is, and makes it harder to reason about what has actually changed.

Move to a diff based representation, and have the JS build use these diffs to reconstruct the right files. We will need to ensure that whatever we do will only build when the expected file is present (maybe checks a file-hash?). This integrity checking will also help a lot to keep us in sync with Facebook code once we get to a model of often pulling from Facebook master.

Must be done concurrently with tooling work (#3907)

**Comment by kmelmon** [comment]
Chris wants us to upgrade to 62 as soon as possible, so we should implement this soon.  @NickGerleman can you start thinking about a solution for this?

**Comment by NickGerleman** [comment]
@kmelmon does Chris have a firm timeline? There's some low-hanging fruit beyond this item that we should maybe take a look at before 0.62.

**Comment by kmelmon** [comment]
@NickGerleman Chris is on vacation until 2/24, but I do know he wanted to do the upgrade immediately.  Now, since react-native 0.62 is still in rc we would probably need to do this in our own rc branch, and I can see some advantage to doing things this way.  Thoughts?

**Comment by NickGerleman** [comment]
@kmelmon There are a few high impact items that I think could make sense. @acoates-ms had implied this upgrade may be nastier than the last, so upgrade-velocity efforts could pay off, and starting the upgrade could block other efforts for some time.

1. Diffs for patch style overrides (this item)
2. Tooling to make the upgrade easier, which ties into this
3. Removal of most of the native patches, which I think I can do pretty easily
4. Tool-based conversion of our TS overrides to flow so we can catch more errors during upgrade at build/lint time
5. Maybe windesktop platform removal depending on how expensive it is?

I know @acoates-ms was eager to explore DLL ingestion soon as well. This would also help Facebook's RNW efforts, since they won't need to try to stand us up in their monorepo.

I also worry about upgrading to 0.62 before 0.61 is out of beta. We have the potential to layer new bugs over old by doing that.
