### ISSUE TITLE
warn The following packages use deprecated "rnpm" config that will stop working from next release:   - react-native-windows: https://npmjs.com/package/react-native-windows Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.

### ISSUE THREAD

**Issue by smcardle** [microsoft/react-native-windows#4059]

**Comment by acoates-ms** [comment]
Please provide more information about what version of react-native-windows you are using?
I believe this is fixed on the latest versions of react-native-windows.

**Comment by smcardle** [comment]
I was using whichever one is installed by default using 

yarn add react-native-windows

I believe the version in my package.json reported a legacy version.
However, I have removed the dependency for the moment because I could not run my app.

I am using React "16.9.0" and react-native "0.61.5" and my project is typescript if that helps

**Comment by NickGerleman** [comment]
Would you be able to give us the version of `react-native-windows` specifically?

As a heads up, we do not yet support React Native 0.61 (though this will change soon!). We currently require installation of 0.60.6, which is mentioned early in the Getting Started guide.

**Comment by NickGerleman** [comment]
Actually, I'm not sure you'll have `react-native-windows` yet if the CLI fails this early. What version of `rnpm-plugin-windows` do you have?

**Comment by smcardle** [comment]
I am using react-native-opencv3 which has a dependency on react-native-fs which in turn has a dependency on react-native-windows.

As I said, I can't remember the exact version of react-native-windows as I have no requirement for it and am not using it directly.

I posted this as a heads up to you guys and I've spent enough time on this.

As a result of this I am no longer using the react-native-opencv3 project either... I will add this myself as a react-native component to both my ios and android projects.

I'm fed up with having to installing packages as dependencies for functionality I don't use.
It's becoming more and more obvious that using 3rd party packages for projects is just a PITA and unless they support the latest react and react-native I for one won't be using them

**Comment by acoates-ms** [comment]
Looks like react-native-fs has a peerDependency of react-native-windows@^0.57.2.  

We'll need to update that when we get to updating that module to support vnext of RNW.  In the meantime, @smcardle, if you are not using react-native-windows, you should probably leave that peerDependency unmet, and not install it locally.

#2829 is already tracking react-native-fs work, so hopefully this will be covered by that work.
