### ISSUE TITLE
Support for Fast Reload (React Refresh)

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#4062]
We commented out the usage of `require('./setUpReactRefresh');`. This is supposed to be required for live reload. We should figure out the right thing to do here. @ddalp do you have any more context on the issue when you made the change?

**Comment by NickGerleman** [comment]
This may or may not break something.

**Comment by harinikmsft** [comment]
Assigning to @chrisglein for now, this needs to be done sooner rather than later since Fast Reload is a star feature for v61. Will need to figure out resourcing.
