### ISSUE TITLE
Run IntegrationTests on Debug Builds Instead of Release

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#4063]
Andrew Coates brought up that we will currently miss out on asserts, since we opt to run integration tests in debug mode for CI instead of release. We should switch this, and fix any new issues that pop up.

**Comment by harinikmsft** [comment]
Related to #4007

**Comment by NickGerleman** [comment]
Closing this since there isn't active work for desktop integration tests
