### ISSUE TITLE
Use Consistent C++ Commenting Styles

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#4070]
We do not use a standard commenting format within React Native Windows. Examples:

Javadoc style Doxygen
```c++
/**
 * @class MemoryTracker
 *
 * @brief Provides properties and events related to the memory consumption of a
 * JS engine instance.
 */
```

XMLDoc
```c++
  /// <summary>
  /// <see cref="facebook::xplat::module::CxxModule::getName" />
  /// </summary>
```

XMLDoc Style Doxygen
```c++
  /// For direct debugging, name of runtime instance, or empty for default.
```

Another Doxygen style
```c++
//! A simple struct that describes the basic properties/needs of an SDX. Whenever a new SDX is
//! getting hosted in React, properties here will be used to construct the SDX.
```

Plain comments
```c++
// Try to call ReadValue for JSValue unless it is already called us with TypeWrapper parameter.
```

We should pick one and use it everywhere.

**Comment by harinikmsft** [comment]
Per @kmelmon, plain comments is the style used in the Windows crew (for the most part). This feels like something we could resolve with an internal poll. I will start one in our local channel. Resolving this as it is not actionable here.
