### ISSUE TITLE
Live Reload and Developer Menu don't work

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#4072]
Recent regression in master.  Repro:
-Build/run the sample app out of packages\microsoft-reactnative-sampleapps
-Launch  => app launches correctly
-Hit Ctrl + Shift + D => nothing happens.  Developer Menu is supposed to appear
-Change your app code and save => nothing happens.  Live Reload is supposed to reload the app.

I debugged this with Jon - the new instance management code is not passing through the "developer menu" or "live reload" settings down from the host to the react control.  It's being left behind in the legacy settings.

**Comment by kmelmon** [comment]
@vmoroz can you look into this?  Live Reload is a very important feature, so we should fix this asap.

**Comment by vmoroz** [comment]
I will fix it today

**Comment by vmoroz** [comment]
Fixed by https://github.com/microsoft/react-native-windows/pull/4092
