### ISSUE TITLE
Adding windows to a project breaks Metro configuration for other platforms

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#4081]
This is an issue for customers that are building apps that target more platforms than just Windows.

To repro:
-Create an app using the CLI (react-native init)
-Add Windows support to this project (by installing rnpm-plugin-windows and running react-native windows).

At this point the project will no longer work correctly for Android.

The problem here is that installing windows overwrites metro.config.js with a custom configuration that only works on Windows.  Unfortunately this is the only real option at the moment for react-native-windows, as the windows implementation needs to override core JS functionality, and metro doesn't have a better way for out-of-tree platforms to do this.

We're tracking proposing a solution in metro itself to solve this.  See:  https://github.com/react-native-community/discussions-and-proposals/issues/182

This bug is tracking resolving this for react-native-windows.

**Comment by kmelmon** [comment]
@jonthysell This is a super important issue that I don't have the cycles for.  Can you help drive this?  It's being discussed with facebook and the community here:
https://github.com/react-native-community/discussions-and-proposals/issues/182

**Comment by jainthedestroyer** [comment]
I was trying to create a new Project using the command in documentation and same thing happened to me like i execute `react-native run-android` , the metro server starts in new window and closes immediately due to some error and when I use the separate command to start metro server using `react-native start`, The metro server gets stuck to above mentioned lines and never build the project....

**Comment by kmelmon** [comment]
@jainthedestroyer I'm working on fixing this now.  In the mean-time, there is a workaround which we've been using in community modules.  The basic idea is to add a metro.config.windows.js and a custom react-native.config.js to use this config when launching metro with an additional parameter.  See https://github.com/react-native-community/react-native-webview/pull/1220 as an example.

**Comment by jainthedestroyer** [comment]
So the fix will be released in next major release??

**Comment by jainthedestroyer** [comment]
I need a boilerplate code to start. So can you provide me the repository using previous versions without any error...

**Comment by jainthedestroyer** [comment]
Still unable to bundle the application...

**Comment by kmelmon** [comment]
@jainthedestroyer please file a separate issue for this.  We have this working for the samples in community modules so your issue is likely something specific to your setup.  We'll need the details of how you've created your project, what version of windows, react-native, etc.
