### ISSUE TITLE
RN 61 breaking API change:  clickable => focusable

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#4084]
In the upgrade to version 61, an API change was made in Touchables:
clickable prop was renamed to focusable

Although this is a change in stock RN, we should announce this breaking change to RNW customers.

**Comment by harinikmsft** [comment]
@kikisaints - This would be good to add to the list of upgrade gotchas in the getting started guide.

**Comment by chrisglein** [comment]
Should be covered by the core RN documentation? I don't think there's documentation for us here.
