### ISSUE TITLE
New API in version 61: ScrollView.StickyHeaderComponent

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#4085]
With the upgrade to react-native version 61, we got a new prop on ScrollView:
ScrollView.StickyHeaderComponent

From my read of the code it looks like you can supply your own child to manage the sticky headers rather than relying on the native platform to create one for you.

We will need to add support for this new API in react-native-windows.

**Comment by chrisglein** [comment]
Not something we plan to address on the Paper renderer as we move towards Fabric.
Fabric API completion is tracked here: https://github.com/microsoft/react-native-windows/issues/11152
