### ISSUE TITLE
Integration Tests:  un-fork windesktop

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#4087]
A couple integration test related cleanup tasks here:

1) The integration tests currently define a platform override called "windesktop".  This added a large number of .windesktop files to the repo.  This makes it difficult to do an upgrade as have to merge all the react-native JS files into the windesktop overrides.

2) The integration tests are currently building/running as part of the ReactWindows-Universal.sln, which is tailored for win32, not the public version.  We should be running integration tests against the UWP implemention and using Microsoft.ReactNative.

**Comment by NickGerleman** [comment]
#2730 could make sense to pair with this

**Comment by NickGerleman** [comment]
I'm going to take this as something to work on this quarter.

**Comment by NickGerleman** [comment]
Julio did this work earlier.
