### ISSUE TITLE
Use `__cdecl` for x86 builds

### ISSUE THREAD

**Issue by JunielKatarn** [microsoft/react-native-windows#4096]
## Motivation

See https://docs.microsoft.com/en-us/cpp/cpp/calling-conventions?view=vs-2019
Some third party native dependencies (i.e. OpenSSL) expect to be built and run using `__cdecl`.
React Native Windows is currently built using `__stdcall` for legacy/historic reasons.
Changing the convention will help defork and unpatch some third party dependencies, removing one significant variable from the build/integration process.

**Comment by NickGerleman** [comment]
I'm sure you're aware, but there are implications here for Office using react-native-windows. I.e. we export functions that Office will expect to be __stdcall until we've moved to only using ABI safe/explicit types at the DLL boundary.

**Comment by JunielKatarn** [comment]
> I'm sure you're aware, but there are implications here for Office using react-native-windows. I.e. we export functions that Office will expect to be __stdcall until we've moved to only using ABI safe/explicit types at the DLL boundary.

That's exactly what my upcoming pull requests willl be about :)

**Comment by JunielKatarn** [comment]
Reopening. Pending further investigation and planning.

**Comment by JunielKatarn** [comment]
Well revisit after ABI-safe API has been established.
