### ISSUE TITLE
Move Playground from ReactUwp to Microsoft.ReactNative

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#4103]
Playground is the app we provide to run JS, like RNTester in a frame. (Think Rex, for Win32 folks).

Having this use ReactUwp causes us lost test coverage during manual validation (E.g. React upgrades). It can also provide a bad example to those looking at code. ReactUwp is undocumented, but not clearly deprecated.

**Comment by acoates-ms** [comment]
Same as #3854
