### ISSUE TITLE
Support react-native-cameraroll

### ISSUE THREAD

**Issue by freistli** [microsoft/react-native-windows#4110]
# Support `Support react-native-cameraroll` on RNW vNext

## Basic Info
- Module Repo URL: [https://github.com/react-native-community/react-native-cameraroll](https://github.com/react-native-community/react-native-cameraroll)
- Target version: 0.61.5
- [ ] Issue exists on module repo (if so, [link]())

## Overview of Required Functionality
react-native-community/cameraroll works in 0.61.5 for IOS&Android, but not in RN4W vNext. It is not a pureJS. Expect getPhotos can work for Windows vNext.

    CameraRoll.getPhotos({
      first: 10,
      assetType: 'Photos',
    }).then(r => {
      this.setState({ photos: r.edges });
    })
      .catch((err) => {
        this.setState({ info: err });
      });

**Comment by NickGerleman** [comment]
@stmoy who is following community modules

**Comment by harinikmsft** [comment]
Keeping this in the backlog until @stmoy has evaluated the priority of this module.

**Comment by chrisglein** [comment]
Closing this module request as not in plan. Not that this module _shouldn't_ receive a Windows implementation, but it makes more sense to track that request on the module's repo rather this repo.
