### ISSUE TITLE
Context menu behavior on dual-screen

### ISSUE THREAD

**Issue by YuliKl** [microsoft/react-native-windows#4119]
# Context menu behavior on dual-screen

## Summary

RN core does not include a context menu component. Need to investigate which popular modules exist for showing context menus and whether we can update these to position away from the seam.

## Motivation

Showing a context menu with a vertical or horizontal seam running through it disrupts the user experience. When an app is spanned on dual-screen, this component should position itself in a way to remain usable.

## TextInput's context menu
TextInput includes the `contextMenuHidden` prop, implying that the component shows the native text input/edit menu. We need to validate whether the component gets the native positioning behavior for free and nudge the menu out of the way if not.

## Open Questions

1. What module or modules are most popular for showing context menus in RN?

**Comment by harinikmsft** [comment]
@YuliKl to ping Calendar team to see if there is a context menu component they are using and then bring this to an upcoming checkpoint review meeting.
