### ISSUE TITLE
Update react-native-video for dual-screen

### ISSUE THREAD

**Issue by YuliKl** [microsoft/react-native-windows#4120]
# Update react-native-video for dual-screen

## Summary

With #2095 we're completing work to enable video playback. This module also needs to work correctly when used in a spanned app on a dual-screen device.

## Motivation

Typically, media playback components include a centered play button, and/or a full width playback scrubber. On dual-screen, these vital components may be split or occluded by the seam, resulting in poor to unusable UX. 

## Open Questions

1. Can the design of react-native-video be aligned with other media playback controls? What is that design and which framework(s) should this component be aligned with?

**Comment by harinikmsft** [comment]
react-native-video is using native media player components under the covers. @YuliKl to figure out if the XAML native work to update media player component is happening in WinUI3. Also, would be good to play with the component on Neo/Duo and see what is broken.
