### ISSUE TITLE
E2ETest failure: Padding doesn't work for Views on VS 2019, v142 tools, Release x64

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#4122]
As part of PR #4101, the measureLayout E2E test is failing on the windows-2019 VM because the View's padding is not being applied.

I've confirmed that it repros on my 19H1+ machine, when building in VS 2019 and the v142 toolset.

We are patching Yoga.cpp in `vnext\DeforkingPatches\ReactCommon\yoga\yoga\Yoga.cpp` to add an extra measure call, apparently for the benefit of react-native-win32, but it has the side effect of messing up react-native-windows.

Removing that patch fixes the issue for react-native-windows, but may cause other unintended side-effects in react-native-windows, and of course probably messes up react-native-win32.

**Comment by jonthysell** [comment]
Making things even weirder, this only seems to happen with release bits, and since the E2eTest app is in C#, it's possible this is a .NetNative issue.

**Comment by jonthysell** [comment]
This only repros on Release x64, not Release x86.

**Comment by acoates-ms** [comment]
To be clear this is unrelated to the win32 patch -- and just started with the new version of the tools.

RNTester in playground app in Debug:
<img width="901" alt="RNTester_Debug" src="https://user-images.githubusercontent.com/30809111/79263353-88231600-7e47-11ea-9f05-7a7a9d8c5d0d.PNG">
RNTester in playground app in Release:
<img width="901" alt="RNTester_Release" src="https://user-images.githubusercontent.com/30809111/79263356-88bbac80-7e47-11ea-8d23-469145529a92.PNG">

**Comment by acoates-ms** [comment]
In `YGNode::getLeadingPadding`

```
  YGFloatOptional resolvedValue = YGResolveValue(
      YGComputedEdgeValue(
          style_.padding(), leading[axis], CompactValue::ofZero()),
      widthSize);
```
Is returning 0 in release x64, even when the node.style_.padding_ contains values.

**Comment by acoates-ms** [comment]
```c++

  // these are signaling NaNs with specific bit pattern as payload they will be
  // silenced whenever going through an FPU operation on ARM + x86
  static constexpr uint32_t AUTO_BITS = 0x7faaaaaa;
  static constexpr uint32_t ZERO_BITS_POINT = 0x7f8f0f0f;
  static constexpr uint32_t ZERO_BITS_PERCENT = 0x7f80f0f0;
```
I believe its an issue with CompactValue::isUndefined.  The above comment looks suspious.

**Comment by asklar** [comment]
Here is the comparison for Release|x64, Debug|x86 (which looks the same as Release|x86 and Debug|x64), and Release|x64 with FP:strict

![image](https://user-images.githubusercontent.com/22989529/79604050-45a94580-80a2-11ea-9a6a-60945b5f5a65.png)
