### ISSUE TITLE
Implement Windows API Desktop WebSocket module.

### ISSUE THREAD

**Issue by JunielKatarn** [microsoft/react-native-windows#4127]
## Summary
Implement `Microsoft::React::IWebSocket` using plain Windows APIs as an alternative to the current `Boost/Beast` implementation.

## Motivation
- Current Desktop WebSocket implementation heavily relies on third party `boost` dependencies, and transitively on `OpenSSL. This adds a significant file size and memory footprint, plus makes dependency management more complex.

**Comment by harinikmsft** [comment]
@JunielKatarn  - can you describe the nature of the changes here? Will this be on Win32 only or in the shared core?

**Comment by JunielKatarn** [comment]
It is a Desktop-only change, yes.
It bumps up the supported version to give access to APIs required for upcoming features.
