### ISSUE TITLE
Misleading "^" character in getting started command lines

### ISSUE THREAD

**Issue by jjgh** [microsoft/react-native-windows#4132]
Please remove the "^" character from the following lines:

`react-native init <project name> --version ^0.60.0`

`react-native init <project name> --version ^0.61.5`

at https://microsoft.github.io/react-native-windows/docs/getting-started.

Emphasizing something in a command line should not alter the command line.

**Comment by chrisglein** [comment]
@kikisaints this issue report hid for a bit being mis-labeled as .NET (I'm fixing the template). But the ^ still seems to be there in the steps. The CLI doesn't support the ^.

**Comment by kikisaints** [comment]
@chrisglein is this still valid? Our steps include the ^. Should I remove this or not? I've gotten some steps from Andrew that appear to say otherwise.

**Comment by chrisglein** [comment]
@kikisaints If I recall @acoates-ms said that the ^ wasn't processed by our CLI. The caret [has meaning](https://nodesource.com/blog/semver-tilde-and-caret/), but in our case isn't actually doing the thing it's supposed to do. So we should remove it from the steps. @acoates-ms correct me if I'm wrong.

**Comment by harinikmsft** [comment]
Pinging @acoates-ms

**Comment by chrisglein** [comment]
@kikisaints this is still open and the ^ [is still there](https://microsoft.github.io/react-native-windows/docs/getting-started). Can you work with Andrew to get clarity here.

**Comment by kikisaints** [comment]
This was addressed in the recent PR linked here. Closing.
