### ISSUE TITLE
Error while executing command: react-native.cmd run-windows --proxy --no-packager

### ISSUE THREAD

**Issue by jjgh** [microsoft/react-native-windows#4134]
> react-native -v

react-native-cli: 2.0.1
react-native: 0.60.6

> npm ls rnpm-plugin-windows

myapp@0.0.1 D:\dev\nodejs\myapp
`-- rnpm-plugin-windows@0.5.1-0

> `npm ls react-native-windows`

"react-native-windows" -> command not found

> node -v

v13.9.0

> npm -v

6.13.7

> yarn --version

1.22.0

- Target Platform: UWP
- Targeted framework version: UWP
- Target Platform Version(s): Windows 10
- Target Device(s): Desktop
- Development Operating System: Windows 10
- Visual Studio Version: Visual Studio 2017
- Build Configuration: Debug

### Steps to Reproduce

1. Start debug in Visual Studio Code
2. Error message appears

### Expected Behavior
No errors...

### Actual Behavior

`Error while executing command 'd:\dev\nodejs\myapp\node_modules\.bin\react-native.cmd run-windows --proxy --no-packager': (error code 101)`

**Comment by acoates-ms** [comment]
It looks like you dont have react-native-windows in your project.  Did you run `react-native windows` to add the windows platform to your project?

**Comment by jjgh** [comment]
@acoates-ms yes I did run `react-native windows` as I've followed all the steps from the getting started guide. Moreover the following command shows that react-native windows is installed: 
> npm ls react-native-windows
```
myapp@0.0.1 D:\dev\nodejs\myapp
-- react-native-windows@0.60.0-vnext.138
```

**Comment by widersky** [comment]
I have the same problem on node v10.15.1 , npm v6.13.7, yarn v1.22.0

**Comment by chrisglein** [comment]
@kaiguo We have a couple people here running into setup issues. Let's try to validate their steps and see where things are going wrong. They're on 60 and not the supported version of Node to match that (that didn't have the fix), but that shouldn't generate this error. Can you dig in with them?

**Comment by kaiguo** [comment]
@jjgh I did some tests, I think you'd have to either downgrade your node to 12.9.1 or upgrade to react-native-windows 0.61. Also make sure you installed all the Visual Studio components [here](https://microsoft.github.io/react-native-windows/docs/rnw-dependencies).

**Comment by Zekfad** [comment]
I bump this up.
I have the same issue, but i can run the app just using `react-native run-windows --arch x64` and i can actually debug it if i run it from visual studio.

**Comment by chrisglein** [comment]
> I bump this up.
> I have the same issue, but i can run the app just using `react-native run-windows --arch x64` and i can actually debug it if i run it from visual studio.

@Zekfad The original reported issue is 6 months old now. Can you open a new issue that contains your current environment and repro so we can look at it fresh?
