### ISSUE TITLE
Support <react-native-gesture-handler>

### ISSUE THREAD

**Issue by robertev** [microsoft/react-native-windows#4140]
# Support  react-native-gesture-handler on RNW vNext
## Basic Info
- Module Repo URL: https://github.com/software-mansion/react-native-gesture-handler
- Target version: NA
## Overview of Required Functionality
Navigation
Note: this is a dependency of React Native Navigation.  It may be possible for the windows implementation to stub this out to ignore calls; not sure – but it helps with swipe-to-nav events.

**Comment by stmoy** [comment]
As Robert mentions, this is a dependency for #2546 - bumping the priority.

**Comment by namrog84** [comment]
+1 on our team needing this too

**Comment by harinikmsft** [comment]
This is needed for #3884

**Comment by qmatteoq** [comment]
+1 Another AppConsult customer, who is being followed by @harsk, is asking for this in order to move their project from the legacy C# core to the new C++ one

**Comment by kaiguo** [comment]
The issue was originally created as a react-navigation dependency. We've added stubs in react-navigation to work around the issue so we should be unblocked now. We can come back and add a real implementation when we need full gesture support.

**Comment by asklar** [comment]
Adding triage tag to reevaluate milestone now that the stub is in place (i.e. by when do we need the full implementation?)

**Comment by chrisglein** [comment]
I'm assuming we can deprioritize (relatively) for a bit. @stmoy weigh in if there are partners that asked for this specifically (and not just react-navigation).

**Comment by capc0** [comment]
with the stub in react-navigation, when  I do not import ```react-native-gesture-handler``` (documentet as needed in react-navigation)  the app crashes on button clicks. But since gesture handler is not supported, I cant import it. So we kinda need this now IMO.

**Comment by stmoy** [comment]
Following up with some of the folks that @qmatteoq is working with: 

> As for gesture handler we are using two components from this lib. One is the DrawerLayout and the other TextInput component.

**Comment by creambyemute** [comment]
[#1081 on RN-GH](https://github.com/software-mansion/react-native-gesture-handler/issues/1081) contains a temporary solution to get RN-GH + React-Navigation not crashing the app on RN-Windows.

This is just a reference link for ppl to stumble upon.

**Comment by stmoy** [comment]
https://github.com/software-mansion/react-native-gesture-handler/pull/1366
