### ISSUE TITLE
Support <react-native-maps>

### ISSUE THREAD

**Issue by robertev** [microsoft/react-native-windows#4142]
# Support react-native-maps on RNW vNext
## Basic Info
- Module Repo URL:  https://github.com/react-native-community/react-native-maps
- Target version: 0.26.1
- [ ] Issue exists on module repo (if so, [link]())
## Overview of Required Functionality
Maps functionality, Show map of lat long.
Note: removing JS only as apparently this does require native modules.
They are using Maps to display a pushpin right now.  In the future they will add more capabilities, but right now they lock to a static zoom level and render a pin.  So no panning/zooming/custom layers/etc.

**Comment by harinikmsft** [comment]
JS-only might "just work". @stmoy can you investigate if there is any work needed to get this working in Windows? Also - would be good to understand the priority of the customer.

**Comment by smilealdway** [comment]
What is a js-only <react-native-maps>?  May be I don't understand the issue.

**Comment by robertev** [comment]
JS-Only indicates we believe this to be a JS only (no native modules) component. There were no iOS nor Android subfolders for this component in github. The [JS-Only] tag approach for these was specified by stmoy - perhaps he can provide more details on next steps? I have not tested this to confirm if it will really work "as is" in vNext.

**Comment by smilealdway** [comment]
I believe it has native components. 

> https://github.com/react-native-community/react-native-maps/tree/master/lib/ios

and 

> https://github.com/react-native-community/react-native-maps/tree/master/lib/android

**Comment by robertev** [comment]
Use case info:
Map - display a map of the well site locations and the current location of the user at that time. 
Zoom in on location. 
Click on a location to drive a custom action (dispatch a worker to that location).

**Comment by chrisglein** [comment]
Closing this module request as not in plan. Not that this module _shouldn't_ receive a Windows implementation, but it makes more sense to track that request on the module's repo rather this repo.
