### ISSUE TITLE
[JS-only] Support <appcenter>

### ISSUE THREAD

**Issue by robertev** [microsoft/react-native-windows#4144]
# Support appcenter on RNW vNext

## Basic Info
- Module Repo URL: https://github.com/microsoft/appcenter-sdk-react-native
- Target version: ^2.6.1
- [ ] Issue exists on module repo (if so, [link]())

## Overview of Required Functionality
AppCenter integration

**Comment by harshadak2020** [comment]
An AppConsult customer is impacted and requesting this

**Comment by chrisglein** [comment]
Closing this module request as not in plan. Not that this module _shouldn't_ receive a Windows implementation, but it makes more sense to track that request on the module's repo rather this repo.
