### ISSUE TITLE
Support <appcenter-analytics>

### ISSUE THREAD

**Issue by robertev** [microsoft/react-native-windows#4145]
# Support appcenter-analytics on RNW vNext

## Basic Info
- Module Repo URL: https://github.com/microsoft/appcenter-sdk-react-native/tree/develop/appcenter-analytics
- Target version: 
- [ ] Issue exists on module repo (if so, [link]())

## Overview of Required Functionality
Pure JS - no
AppCenter Analytics

Customer uses these all pretty heavily, but most especially the Push libraries.  They are slowly refocusing analytics on Application Insights, but the dashboard in AppCenter is a firm favorite for several of their Business Analysts.

**Comment by chrisglein** [comment]
Closing this module request as not in plan. Not that this module _shouldn't_ receive a Windows implementation, but it makes more sense to track that request on the module's repo rather this repo.
