### ISSUE TITLE
Support <appcenter-crashes>

### ISSUE THREAD

**Issue by robertev** [microsoft/react-native-windows#4146]
# Support appcenter-crashes on RNW vNext

## Basic Info
- Module Repo URL: https://github.com/microsoft/appcenter-sdk-react-native/tree/develop/appcenter-crashes
- Target version: NA
- [ ] Issue exists on module repo (if so, [link]())

## Overview of Required Functionality
Analyze crashes
PureJS - no

**Comment by chrisglein** [comment]
Closing this module request as not in plan. Not that this module _shouldn't_ receive a Windows implementation, but it makes more sense to track that request on the module's repo rather this repo.
