### ISSUE TITLE
Support <react-native-config>

### ISSUE THREAD

**Issue by robertev** [microsoft/react-native-windows#4149]
# Support react-native-config on RNW vNext

## Basic Info
- Module Repo URL: https://github.com/luggit/react-native-config
- Target version: 
- [ ] Issue exists on module repo (if so, [link]())

## Overview of Required Functionality
Configuration
PureJS - no

They use this for their build (gradle) and for per-environment configurations (dotenv).  I’m a little surprised this has native dependencies.  Maybe because it has to access the filesystem or Environment variables to select the proper .env file?

**Comment by bzoz** [comment]
PR with Windows support: https://github.com/luggit/react-native-config/pull/492

**Comment by chrisglein** [comment]
And merged! Thanks @bzoz.
