### ISSUE TITLE
Support <react-native-reanimated>

### ISSUE THREAD

**Issue by robertev** [microsoft/react-native-windows#4151]
# Support react-native-reanimated on RNW vNext

## Basic Info
- Module Repo URL: https://github.com/software-mansion/react-native-reanimated
- Target version: ^1.3.0
- [ ] Issue exists on module repo (if so, [link]())

## Overview of Required Functionality
React   Native's Animated library reimplemented
PureJS - no

Similar to Gesture Handler, this is dependency of React Native Navigation. I assume it animates scene transitions during navigation. Perhaps Windows implementation can stub out empty behaviors for an initial version?

**Comment by namrog84** [comment]
+1  as this is still causing us issues (indirectly thru react native navigation)

**Comment by harinikmsft** [comment]
This is needed for #3884

**Comment by kmagiera** [comment]
This issue has recently been brought to my attention. As a creator and maintainer of gesture-handler and reanimated I'd be happy to discuss how me and team can help push this forward. 

An important aspect is that soon we are going to be releasing next version of reanimated that will primarily be written in c++. I believe this should make it more approachable to port to other platforms.

**Comment by kaiguo** [comment]
> An important aspect is that soon we are going to be releasing next version of reanimated that will primarily be written in c++. I believe this should make it more approachable to port to other platforms.

Hi @kmagiera, thanks for reaching out!

Do you have an ETA of the next release (c++ version)? Can you point me to the branch if it's available? I was planning to map existing Android/iOS implementation to Windows c++/winrt, how hard is it to migrate existing implementation to the next c++ release?

Tring to figure out whether we should start the work now based on the current js implementation or wait for the next c++ release first.

**Comment by kmagiera** [comment]
We should have the first alpha release of the c++ implementation out in the next two weeks. Can't share too many details just yet on that though. 

On another note, I noticed that this got marked as priority because of react-navigation which supposedly depends on reanimated. However this is no longer true as of react-navigation v5 where despite reanimated being listed among indirect dependencies the library is not used.

**Comment by namrog84** [comment]
You say it's not being used, but 
github.com/react-navigation 's master branch says its for v5 

but I can still see a 2 places where react-native-reanimated is being used in the drawer component?

* https://github.com/react-navigation/react-navigation/blob/master/packages/drawer/src/views/Overlay.tsx
* https://github.com/react-navigation/react-navigation/blob/master/packages/drawer/src/types.tsx

**Comment by kmagiera** [comment]
Ah, yes, I definitely missed that. It is used by some navigation packages (could be only drawer) but not by the core. On top of that even when new reanimated is released it will take some time for components such as drawer to migrate to new version that relies on the c++ core.

**Comment by kaiguo** [comment]
@namrog84 are we using drawer in our apps? If not I think we should be unblocked?

If we do use drawer sounds like we'll need to add Windows reanimated based on current implementation since it'll take some time for other components to migrate to the new version as @kmagiera mentioned.

**Comment by namrog84** [comment]
Yes, we use drawer.

We currently use "react-navigation", "react-navigation-drawer", "react-navigation-hooks", "react-navigation-stack", and "react-navigation-tabs"

**Comment by kaiguo** [comment]
@robertev @namrog84 what react-native-windows version are you guys on?

I think I'll need @vmoroz's notification service above to implement this module.  Currently that service is targeting 0.63(+) which means this reanimated module will only be available on 0.63+ as well. Will that work for you guys? We are trying to decide whether we should backport the notification service to 62. Thanks!

**Comment by namrog84** [comment]
In process of moving onto RN 62 right now. Then further progress will be de-prioritized. 

However, waiting until 63+ is totally fine for us. As some temporary reprioritzation is happening for us for next few months.

**Comment by kaiguo** [comment]
Hi @kmagiera, I saw you submitted the cpp implementation, any idea when will drawer be migrated to the new version?

I guess another options is (I haven't dig into the drawer code yet), can we use the built-in animated instead of reanimated in drawer? If that's possible I'm happy to help making the change, since our end goal is to unblock the usage of react-navigation.

**Comment by ArksHub** [comment]
As of 2025 , react navigation drawer still doesnt work in RNW because of same reason that it doesnt have reanimated support. Kind of furstrating.
