### ISSUE TITLE
Support <react-native-screens>

### ISSUE THREAD

**Issue by robertev** [microsoft/react-native-windows#4152]
# Support react-native-screens on RNW vNext

## Basic Info
- Module Repo URL: https://github.com/kmagiera/react-native-screens
- Target version: ^2.0.0-alpha.3
- [ ] Issue exists on module repo (if so, [link]()): https://github.com/software-mansion/react-native-gesture-handler/issues/676

## Overview of Required Functionality
kmagiera
Native   navigation primitives for React Native app.
PureJS - no

Again, a dependency of React Native Navigation

**Comment by creambyemute** [comment]
Temporary solution would be to just not `enableScreens()` on Windows. I made a `App.windows.tsx` removing the rn-gh import and the react-native-screens import/enabling.

**Comment by chiaramooney** [comment]
Partial implementation now merged into react-native-screens repo. Still some work to be done here including missing animations when doing screen transitioning, and native navigation stack support. There was also a bug reported on the PR: "It looks like you're unable to navigate back to a previously rendered screen. For example, calling navigator.navigate("Home") after navigating to Notifications renders a completely blank screen, as does calling navigator.goBack()." that should be investigated.

**Comment by chrisglein** [comment]
We have some part of screens, so that's good. We have two scenarios to check in on before closing this issue:
- @robertev needs above are met (with native navigation)
- react-navigation no longer experiences perf issues with pages on the backstack not being discarded 

@stmoy FYI

**Comment by chiaramooney** [comment]
Module now builds successfully on Windows. Make note to add to the list of functionality that still needs to be added to the module: Support for [detaching inactive screens](https://reactnavigation.org/docs/drawer-navigator#detachinactivescreens).

**Comment by chrisglein** [comment]
Partial implementation exists. Closing this module request. Not that this module _shouldn't_ receive a more complete Windows implementation, but it makes more sense to track gaps on the module's repo rather this repo.
