### ISSUE TITLE
[JS-only] Support <prop-types>

### ISSUE THREAD

**Issue by robertev** [microsoft/react-native-windows#4154]
# Support prop-types on RNW vNext

## Basic Info
- Module Repo URL: https://github.com/facebook/prop-types
- Target version: ^15.7.2
- [ ] Issue exists on module repo (if so, [link]())

## Overview of Required Functionality
Runtime   type checking for React props and similar objects
PureJS - YES

**Comment by stmoy** [comment]
@robertev - I believe this module is supported as there are references to it within the core RNW repo. Can you double check with the customer that it doesn't work?

**Comment by acoates-ms** [comment]
`prop-types` has been deprecated in favor of using typescript/flow to type check your JavaScript.  In any case, `prop-types` is a react feature and as such should work the same in react-native-windows as in react-native or react-dom.  (In so far as that still works?)
