### ISSUE TITLE
Support <react-native-community/datetimepicker>

### ISSUE THREAD

**Issue by robertev** [microsoft/react-native-windows#4156]
# Support react-native-community/datetimepicker on RNW vNext

## Basic Info
- Module Repo URL: https://github.com/react-native-community/react-native-datetimepicker
- Target version: ^2.1.0
- [ ] Issue exists on module repo (if so, [link]())

## Overview of Required Functionality
React   Native date & time picker component for iOS and Android
PureJS - no

we use this for data entry in our forms – it allows cross platform Date Time pickers to be displayed to the user, and for us to customize some behaviors.  We already treat them slightly differently for different operating systems.  We’ve wrapped it up in it’s own component, so we might have some way to make this work easily enough; but I’d expect windows to have a datepicker defined:

Our current abstraction around DateTimePicker:

`{Platform.OS === 'android' && dlgVisible && (
        <DateTimePicker
          minimumDate={rest.minimumDate}
          mode={rest.mode}
          onChange={onChangeHandler}
          value={value}
        />
      )}
      {Platform.OS === 'ios' && (
        <BottomSheet
          onCancel={dismiss}
          onDone={() => onChange(result)}
          title={title || placeholder}
          visible={dlgVisible}
        >
          <DateTimePicker
            minimumDate={rest.minimumDate}
            mode={rest.mode}
            onChange={onChangeHandler}
            value={result}
          />
        </BottomSheet>
      )}
`

**Comment by rectified95** [comment]
@robertev Windows support in the community module was added today. Once they make a new release, you should be able to consume it. Contact me with issues using it.

**Comment by rectified95** [comment]
DateTimePicker community module v2.4.0 has been released, and it contains Windows support.
I will soon start work on removing the existing implementation from this repo.
Closing this issue.
FYI @robertev
