### ISSUE TITLE
Move AsyncStorageManagerWin32 to run on a background thread

### ISSUE THREAD

**Issue by htpiv** [microsoft/react-native-windows#4163]
ASMW32 currently blocks on SQLite APIs completing, which may take a relatively long time (however long the disk IO takes). The implementation of ASM on Android & iOS do their disk IO asynchronously. We should make ASMW32 asynchronous for parity with those platforms.

**Comment by htpiv** [comment]
@ddalp as an FYI

**Comment by chrisglein** [comment]
Related #2271 , but for Win32. This is scheduled for deletion once it's moved to the community module. 
Given that we're going to get rid of this maybe it's not worth the investment in improving this?
We need to understand what the story is for an islands app to access storage and then have the module able to support both the Win32 and UWP solutions.

**Comment by ddalp** [comment]
The current file I/O solution already does the update async, I think we need the async method call to work asynchronously, before we can migrate the SQLLite solution to native module.

**Comment by NickGerleman** [comment]
I remember @htpiv submiting a PR to fix this. Closing the issue. Note that we cannot deleted our existing implementation until stock React Native removes builtin Asyncstorage support.
