### ISSUE TITLE
[JS-only]  Support react-native-picker-select

### ISSUE THREAD

**Issue by robertev** [microsoft/react-native-windows#4164]
# Support react-native-picker-select on RNW vNext

## Basic Info
- Module Repo URL: https://github.com/lawnstarter/react-native-picker-select
- Target version: ^6.3.3
- [ ] Issue exists on module repo (if so, [link]())

## Overview of Required Functionality
A Picker component for React Native which emulates the native select interfaces for iOS and Android

**Comment by chrisglein** [comment]
@stmoy as this is JS only you were going to evaluate what work was necessary to onboard a JS only one, correct? Will be assigning these to you to check that.

**Comment by stmoy** [comment]
@chrisglein - do you know offhand if Picker is part of the "slimmening"? We already have a picker component implemented, right?

**Comment by chrisglein** [comment]
@stmoy It is. We've added it to the community module (#3036), but haven't been able to remove it from the core repo entirely (#4611) as it isn't removed from Facebook's core repo. The API isn't public, but the code is still there.

**Comment by chrisglein** [comment]
Uses Picker, which is supported on Windows. So this should work? Try it and find out?
