### ISSUE TITLE
[JS-only] Support react-native-keyboard-aware-scroll-view

### ISSUE THREAD

**Issue by robertev** [microsoft/react-native-windows#4165]
# Support react-native-keyboard-aware-scroll-view on RNW vNext

## Basic Info
- Module Repo URL: https://github.com/APSL/react-native-keyboard-aware-scroll-view
- Target version: ^0.9.1
- [ ] Issue exists on module repo (if so, [link]())
## Overview of Required Functionality
A ScrollView component that handles keyboard appearance and automatically scrolls to focused TextInput.

**Comment by chrisglein** [comment]
As a JS-only module, this _should_ work on Windows? Has anyone tried? Does it have non-Windows dependency?

Regardless, closing this module request as not in plan. Not that this module _shouldn't_ receive a Windows implementation, but it makes more sense to track that request on the module's repo rather this repo.
