### ISSUE TITLE
JSValue has unexpected behavior on Double vs Int64 (compared to folly::dynamic)

### ISSUE THREAD

**Issue by namrog84** [microsoft/react-native-windows#4181]
Both ways are reading the same javascript code with no changes but derive different values. 

Old way
```
void updateProperties(const folly::dynamic&& props)
...
auto speed = prop.second.asDouble();
speed has value of 1
```

new way
```
void UpdateProperties(FrameworkElement const& view, IJSValueReader const& propertyValueReader) noexcept
...
const JSValueObject& propertyMap = JSValue::ReadObjectFrom(propertyValueReader);
...
auto speed = prop.second.Double();
speed has a value of 0
```

Source of speed on javascript/typescript side
default value is `speed: 1` otherwise its a decimal

The problem is that if it comes in as "1" JSValue thinks its an int64
but if it comes in as 1.5 as a Double.

It worked fine previously in folly::dynamic but doesn't work as expected in JSValue.

Current workaround:
Every single instance of reading a JSValueType::Number check for both `Type() == JSValueType::Double` and `Type() == JSValueType::Int64` and extract them for the proper type.

Expected outcomes:
// Assuming JSValue val  is 5 and came from a ViewManagerPropertyType::Number
EXPECT_EQ(val.Int64(), 5);
EXPECT_EQ(val.Double(), 5.0);

Either let me specify Double or Int64 instead of Number(Violate the TS contract), 
or I'd expect Double to always work in all cases (Even if it was an integer).  And Int64 to only work when it was a proper integer value.

Partner: Xbox

**Comment by chrisglein** [comment]
@jonthysell is this related to what you were describing yesterday?
This team is trying to migrate onto the new stuff and is hitting an issue, can you take a look?

**Comment by jonthysell** [comment]
Looking into it.

dynamic's ::getDouble() type checks and only works if the the value is actually a double, else throws an exception.
dynamic's ::asDouble() type checks and converts if possible, else throws and exception.

JSValue's Double() returns the DoubleValue field of the internal union struct, with no type checking, no expcetions.

I think the correct answer here is to extend JSValue with mimiced dynamic API in JSValue with both ::asDouble() and ::getDouble() behaviors that do the type checking.

My guess is that @vmoroz wanted ::Double() to be as fast as possible, when you know you're reading a Double. It's complicated by ViewManagerPropertyType specifying Number - I couldn't figure out if we actually need/want to have Int64/Double also supported as types or not.

**Comment by vmoroz** [comment]
JSValue.Double() is semantically the same as getDouble(), but it does not crash and returns 0 in case of error. For the asDouble() please use the JSValue.To<Double>().

**Comment by vmoroz** [comment]
Though the JSValue.To<double>() is quite inefficient. We better to add an API that can have more efficient asDouble behavior. @jonthysell I can add it. I already have the functionality in different place and can just move/reuse it here.

**Comment by vmoroz** [comment]
The new API to have JavaScript-like behavior is jsValue.AsJSNumber(). We also have folly::dynamic-like jsValue.AsDouble() method.
