### ISSUE TITLE
RNW shouldn't use Tag property internally.

### ISSUE THREAD

**Issue by namrog84** [microsoft/react-native-windows#4187]
Note: The term 'tag' has slightly conflicting definitions.
in RN a ReactTag is the id number of a react view.  Which is how RNW is using the WinUI's Tag, which is perfectly reasonable. 
in WinUI a Tag is intended for an arbitrary object value. "the Tag property is to provide an general-purpose property on all FrameworkElement classes"

Example:
```
FrameworkElement FocusContainerManager::CreateView() noexcept {
    auto view = winrt::Border();
    view.Tag(MyCustomObject);;
    return view;
}
```

MyCustomObject gets stomped internally by RNW's usage of SetTag
https://github.com/microsoft/react-native-windows/blob/a4e1bf334e57b46bee88833a403688f6912e87a3/vnext/include/ReactUWP/XamlView.h#L25

The Tag on FrameworkElement is a common place to stick some extra information about an element
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.frameworkelement.tag

Instead RNW should internally register a custom field for usage of ReactTAg instead or some other way of dealing with this.
e.g.  https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.dependencyproperty.registerattached

It requires a little bit of boiler plate to set it up, but the RNW code consumer shouldn't have their WinUI Tag stomped on when they later try to retrieve it from the view.
Tomorrow I will post follow up of our example workaround and that RNW might take into consideration implementing internally.

Alternatively, there used to be ShadowNode's that made our need for Tag unnecessary, but in the new Microsoft.ReactNative ViewManager world, we need a way to easily attach additional information to Views because many XAML classes are sealed and can't be directly inherited from and it can be heavyweight/painful to have a nested child view inside another just for an extra field.

Partner: Xbox

**Comment by jonthysell** [comment]
We could move the react tag to its own attached property, to avoid stomping on existing controls use of Tag. Similarly, you are able to attach any data to any View, sealed or not, with your own attached property.

Also, if there's a particular XAML class that is sealed that's in your way, file a bug on https://github.com/microsoft/microsoft-ui-xaml. I know there's been an effort to unseal controls, as the rationale for why some are sealed and some aren't is ambiguous.

**Comment by namrog84** [comment]
Our current workaround is to do something like this


```
static winrt::Windows::UI::Xaml::DependencyProperty s_lottieViewProperty;
...
Windows::UI::Xaml::DependencyProperty LottieAnimationViewManager::s_lottieViewProperty=
    Windows::UI::Xaml::DependencyProperty::RegisterAttached(
        L"customLottieViewTag",
        winrt::xaml_typename<winrt::LottieAnimationCPP::LottieAnimationView>(),
        winrt::xaml_typename<winrt::Microsoft::UI::Xaml::Controls::AnimatedVisualPlayer>(),
        Windows::UI::Xaml::PropertyMetadata{nullptr});
...
FrameworkElement LottieAnimationViewManager::CreateView() noexcept{
...
view.SetValue(s_lottieViewProperty, lottieView);
...
}
....
auto lottieView =view.GetValue(s_lottieViewProperty).as<winrt::LottieAnimationCPP::implementation::LottieAnimationView>();
```
