### ISSUE TITLE
readme have broken link for getting started

### ISSUE THREAD

**Issue by namrog84** [microsoft/react-native-windows#4191]
https://github.com/microsoft/react-native-windows/blob/master/vnext/README.md

Getting Started
See Getting Started Guide for React Native Windows C++.
has a link to https://github.com/microsoft/react-native-windows/blob/master/vnext/docs/GettingStarted.md
Which doesn't exist.

I don't see a GettingStarted.md anywhere for vnext (it exists for /current)
So I am not sure what you want it to point to, so that is why I am not PRing a fix myself.

**Comment by kikisaints** [comment]
For your reference, the getting starting guide was moved to our [documentation site](https://microsoft.github.io/react-native-windows/docs/getting-started).

However I am also in the process of starting a scrub of the README and will try and remove old links like these. Thanks for bringing it up!

**Comment by chrisglein** [comment]
Link appears to be fixed. @kikisaints , safe to close this issue out?

**Comment by namrog84** [comment]
Looks good to me!

**Comment by harinikmsft** [comment]
This is done.
