### ISSUE TITLE
Add OnUnmount/DestroyView for ViewManagers

### ISSUE THREAD

**Issue by namrog84** [microsoft/react-native-windows#4192]
There exists a 
`winrt::Windows::UI::Xaml::FrameworkElement CreateView() noexcept;`

But we have no idea when the view goes away.
We used to have the ShadowNodes CreateShadow and destroyShadow but in new View Managers there aren't shadownodes anymore. 

There should be some kind of OnUnmountView or something, so that if we have some internal map of all views or if we need to do any special clean up we will know when a view is going away.

**Comment by namrog84** [comment]
Our current workaround is to RegisterAttached an object to the view and make sure no one else takes a reference to it, and then take a weak ref to the object inside the attached (weak ciruclar ref) and attached goes out of scope upon views destruction and we can handle it, but its a bit ugly and generally feels a little unsafe.

**Comment by chrisglein** [comment]
@vmoroz @jonthysell Do either of you have opinions about how and when we want to handle this?

**Comment by chrisglein** [comment]
Despite presence of a workaround, the partner is raising this as one of their important issues. Adding for consideration in 63.
