### ISSUE TITLE
IDL Error with c++ project

### ISSUE THREAD

**Issue by gillpeacegood** [microsoft/react-native-windows#4210]
I've been trying to create a module by following the instructions, but I get an error processing my IDL file (see below):

```
Error | MIDL1002 | [msg]error while reading input file [context]: Error processing WinMD metadata. Interface Microsoft.ReactNative.IReactPackageProvider: Member CreatePackage: Method CreatePackage: Custom attribute Windows.Foundation.Metadata.NoExceptionAttribute: Custom attribute Windows.Foundation.Metadata.NoExceptionAttribute could not be found.
```

**Comment by jonthysell** [comment]
Is your code up somewhere I can look at?

Can you clean out the output folders (bin/obj) for your project (and Microsoft.ReactNative) and try building again?

**Comment by gillpeacegood** [comment]
Hi, you could look at my solution here, there is a c# project which is my eventual implementation and a c++ one which is what I started out with before I got blocked by this problem

https://github.com/axsy-dev/react-native-sqlcipher-storage/blob/autolinking/windows/react-native-sqlcipher-storage-cpp.sln

**Comment by jonthysell** [comment]
https://github.com/axsy-dev/react-native-sqlcipher-storage/pull/3

**Comment by gillpeacegood** [comment]
Thanks very much
