### ISSUE TITLE
Unable to add Microsoft.ReactNative to native module project

### ISSUE THREAD

**Issue by dstaley** [microsoft/react-native-windows#4211]
### Environment

1. `react-native -v`: 0.61.5
2. `npm ls rnpm-plugin-windows`:
3. `npm ls react-native-windows`: 0.60.0-vnext.133
4. `node -v`: v12.15.0
5. `npm -v`: 6.13.4
6. `yarn --version`:

Then, specify:

- Target Platform Version(s): 10.0.18362

- Target Device(s): N/A

- Visual Studio Version: 16.4.5

- Build Configuration: N/A

### Steps to Reproduce

(Write your steps here:)

1. Try to add a reference to Microsoft.ReactNative to native module project

### Expected Behavior

Reference is added to project

### Actual Behavior

An error occurs when attempting to add the reference:

```
A reference to 'Microsoft.ReactNative' could not be added.
PrimaryWinMDOutputGroup
Parameter name: Output group '{0}' not known or another build error occurred.
```

![image](https://user-images.githubusercontent.com/88163/75586359-16267700-5a29-11ea-81ee-88fb9bbf10a6.png)

### Additional context

I'm attempting to follow the [native module setup guide](https://microsoft.github.io/react-native-windows/docs/native-modules-setup) on the website to add a Windows native module to an existing React Native native modules library.

**Comment by namrog84** [comment]
I see 
```
react-native -v: 0.61.5
npm ls react-native-windows: 0.60.0-vnext.133
```

I think you might need to be on a 61 version of rnw if you are using a 61 version of rn

**Comment by dstaley** [comment]
@namrog84 I think that was the issue! After running `npm install --no-save react-native-windows@beta` and adding the reference it seems to have worked! If I run into any other issues I'll be sure to file a new issue. Please feel free to close this unless it's useful to keep around.

**Comment by dstaley** [comment]
@namrog84 Whoops, I seem to have spoken too soon. It looks like some of the references were removed, and when I attempted to add `Microsoft.ReactNative.SharedManaged` I got the following:

![image](https://user-images.githubusercontent.com/88163/75596785-e7b79480-5a46-11ea-9d7f-ab2f42ace66f.png)

**Comment by meddyrainzo** [comment]
Followed the current setup guide. Getting the same error.

### Steps to reproduce

Tried to add a reference to `Microsoft.ReactNative`

### Versions
`react-native: 0.62.2`

`react-native-windows: 0.62.7`

### Error
```
A reference to 'Microsoft.ReactNative' could not be added. 
Output group 'PrimaryWinMDOutputGroup' not known or another build error occurred.
```

**Comment by meddyrainzo** [comment]
I got it to work by using version `0.63` for both `react-native` and `react-native-windows`. I also checked the `.sln` file in the [samples project](https://github.com/microsoft/react-native-windows-samples/blob/master/samples/NativeModuleSample/csharp/windows/NativeModuleSample.sln) and compared the missing references to that in the current setup guide
