### ISSUE TITLE
Unable to activate Windows Store app after adding C++ native module

### ISSUE THREAD

**Issue by dstaley** [microsoft/react-native-windows#4215]
### Environment

If you are using latest version:
1. `react-native -v`: 0.61.4
2. `react-native run-windows --info`:
```
  System:
    OS: Windows 10 10.0.18363
    CPU: (32) x64 AMD Ryzen 9 3950X 16-Core Processor
    Memory: 41.75 GB / 63.92 GB
  Binaries:
    Node: 12.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
    react-native-windows: ^0.61.0-beta.28 => 0.61.0-beta.28
    rnpm-plugin-windows: ^0.5.1-0 => 0.5.1-0
  Installed UWP SDKs:
    10.0.18362.0
```

Then, specify:

- Target Platform Version(s): 10.0.18362

- Target Device(s): Desktop

- Visual Studio Version: Visual Studio 2019

- Build Configuration: Debug

### Steps to Reproduce

(Write your steps here:)

1. Add the C++ [Native Modules Sample](https://github.com/microsoft/react-native-windows-samples/tree/master/samples/NativeModuleSample/cppwinrt/windows/NativeModuleSample) to solution
2. Register module in App.cpp

### Expected Behavior

App launches correctly, loading bundle from running Metro server.

### Actual Behavior

The app builds correctly, but I get the following error:

```
Unable to activate Windows Store app 'blah!App'. The activation request failed with error 'Operation not supported. Unknown error: 0x80040905'.
```

Sometimes the blue app shell launches, sometimes it doesn't. So it's not a build-time error.

### Reproducible Demo

I'm not using any custom code, just the default beta template and the module linked above.

### Additional context

If I comment out the following line, the app launches correctly:

```
PackageProviders().Append(winrt::NativeModuleSample::ReactPackageProvider());
```

I originally thought the error was due to the custom native module I wrote (possibly a configuration or syntax error). I decided to test with a known good module (the NativeSampleModule) linked above and received the same error. Interestingly enough I _don't_ get this error when using a C# module, but I understand that's significantly different so it might not be relevant that I'm able to use C# modules but not C++ modules.

**Comment by jonthysell** [comment]
Investigating.

**Comment by jonthysell** [comment]
Apparently CppWinRT projects in VS, by default, don't generate winmds. 🤦‍♂️

For the NativeModule Sample project:

1. Right-click on the project and choose `Properties`
    1. Under `Linker > Windows Metadata` set `Generate Windows Metadata` to `Yes`.

You'll have to clean and rebuild your solution.

Updating the docs and sample to reflect this.

**Comment by jonthysell** [comment]
Fixed in the sample here: https://github.com/microsoft/react-native-windows-samples/pull/40

**Comment by dstaley** [comment]
Just wanted to drop a note confirming that this worked!
