### ISSUE TITLE
ENOENT / MyApp_TemporaryKey.pfx When initializing project.

### ISSUE THREAD

**Issue by lociero** [microsoft/react-native-windows#4216]
### Environment

1. `react-native -v`: 
```
react-native-cli: 2.0.1
react-native: 0.59.10
```
2. `npm ls rnpm-plugin-windows`:
```
appname@0.0.1 /mnt/d/learnJS/appname
└── rnpm-plugin-windows@0.5.1-0
```
3. `npm ls react-native-windows`:
```
appname@0.0.1 /mnt/d/learnJS/appname
└── react-native-windows@0.59.0-vnext.208
```
4. `node -v`: `v12.16.1`
5. `npm -v`: `6.13.4`
6. `yarn --version`: `1.22.0`

- Target Device(s): Desktop (Windows 10)
- Development Operating System: Windows 10 Version 1809 (OS Build 17763.1039) (I'm using windows subsystem for Linux / Ubuntu from Microsoft Store)

### Steps to Reproduce
```
$ yarn global add react-native-cli
$ react-native init appname --version 0.59.10
$ cd appname/
$ yarn add rnpm-plugin-windows --dev
$ react-native windows
```

### Expected Behavior
Init project I guess. I followed instructions from [Getting Started section](https://github.com/microsoft/react-native-windows/blob/master/current/docs/GettingStarted.md).

### Actual Behavior
```bash
mega@DESKTOP-UB5K3VE:/mnt/d/learnJS/appname$ react-native windows
Reading application name from package.json...
Reading react-native version from node_modules...
✔ What version of react-native-windows would you like to install? ›  Latest      - High performance react-native-windows built on a shared C++ core from facebook (supports C++ or C#).
Checking for react-native-windows version matching 0.59.*...
Installing react-native-windows@0.59.0-vnext.208...
warning "react-native-windows > react-native-local-cli@1.0.0-alpha.5" has incorrect peer dependency "react-native@^0.57.0".
react-native-windows@0.59.0-vnext.208 successfully installed.
Updating to compatible version of react-native:
    ^0.59.0
warning "react-native-windows > react-native-local-cli@1.0.0-alpha.5" has incorrect peer dependency "react-native@^0.57.0".
Generating self-signed certificate...
Using Default Certificate. Use Visual Studio to renew it.
ENOENT: no such file or directory, lstat '/mnt/d/learnJS/appname/node_modules/react-native-windows/local-cli/generator-windows/templates/keys/MyApp_TemporaryKey.pfx'
Error: ENOENT: no such file or directory, lstat '/mnt/d/learnJS/appname/node_modules/react-native-windows/local-cli/generator-windows/templates/keys/MyApp_TemporaryKey.pfx'
    at Object.lstatSync (fs.js:923:3)
    at Object.lstatSync (/mnt/d/learnJS/appname/node_modules/graceful-fs/polyfills.js:308:16)
    at copyAndReplace (/mnt/d/learnJS/appname/node_modules/react-native-local-cli/util/copyAndReplace.js:34:10)
    at copyAndReplaceWithChangedCallback (/mnt/d/learnJS/appname/node_modules/react-native-windows/local-cli/generator-common/index.js:25:3)
    at generateCertificate (/mnt/d/learnJS/appname/node_modules/react-native-windows/local-cli/generator-windows/index.js:45:5)
    at copyProjectTemplateAndReplace (/mnt/d/learnJS/appname/node_modules/react-native-windows/local-cli/generator-windows/index.js:78:33)
    at generateWindows (/mnt/d/learnJS/appname/node_modules/react-native-windows/local-cli/generate-windows.js:25:3)
    at Object.module.exports [as func] (/mnt/d/learnJS/appname/node_modules/rnpm-plugin-windows/src/windows.js:65:5) {
  errno: -2,
  syscall: 'lstat',
  code: 'ENOENT',
  path: '/mnt/d/learnJS/appname/node_modules/react-native-windows/local-cli/generator-windows/templates/keys/MyApp_TemporaryKey.pfx'
}
```
So the actual problem is:
```bash
Generating self-signed certificate...
Using Default Certificate. Use Visual Studio to renew it.
ENOENT: no such file or directory, lstat '/mnt/d/learnJS/appname/node_modules/react-native-windows/local-cli/generator-windows/templates/keys/MyApp_TemporaryKey.pfx'
Error: ENOENT: no such file or directory, lstat '/mnt/d/learnJS/appname/node_modules/react-native-windows/local-cli/generator-windows/templates/keys/MyApp_TemporaryKey.pfx'
```

### Reproducible Demo
All steps are above. I think its enough.

**Comment by NickGerleman** [comment]
I'm interested in the `/mnt/d/learnJS/appname/... ` path. Are you trying to run this using Git Bash or Cygwin shell by chance? I'm not sure that we've tried to make our tooling work with anything other than the standard command prompt. 

FYI for the future, we usually use the ".Net" label to refer to current vs vnext. Since this isn't specific to current, we shouldn't add that label.

**Comment by lociero** [comment]
@NickGerleman 
> I'm interested in the `/mnt/d/learnJS/appname/... ` path. Are you trying to run this using Git Bash or Cygwin shell by chance? I'm not sure that we've tried to make our tooling work with anything other than the standard command prompt.

I'm using Ubuntu bash from Microsoft Store, its working on WSL if I'm not mistaken.
If it doesn't work with this, I'm sorry, will try in Kali next time.

> FYI for the future, we usually use the ".Net" label to refer to current vs vnext. Since this isn't specific to current, we shouldn't add that label.

It's the first time I've created an issue, my bad, sorry  =)

**Comment by NickGerleman** [comment]
I don't believe that usage from WSL is a supported scenario currently, since we rely on quite a few Windows build tools. Does the issue still occur when using native Windows tooling?

**Comment by lociero** [comment]
> I don't believe that usage from WSL is a supported scenario currently, since we rely on quite a few Windows build tools. Does the issue still occur when using native Windows tooling?

Everything is fine for now, thanks =) I'm closing the issue.
