### ISSUE TITLE
Question: can Microsoft work with Facebook to create IG and FB Messenger RNW apps?

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/react-native-windows#4217]
I was dumbfounded when I saw that Facebook updated their iOS ports to PWAs and apparently Facebook will be making an Electron Messenger app. Facebook has React Native apps for Instagram and Facebook Messenger and yet they did that a few months before you guys, Microsoft, released 0.61 of react-native-windows.

**Comment by chrisglein** [comment]
@Poopooracoocoo This question is interesting but not really in the scope of questions about this repo and it's tech :)

**Comment by Poopooracoocoo** [comment]
@chrisglein 

i thought that microsoft and facebook were working together on this and that eventually this'd be merged with react native. i'm out of the loop lol

well idk if there's a way to contact facebook with this ~feedback\~ . im really glad someone saw this! is there any way to tell facebook about this?

**Comment by chrisglein** [comment]
We really only interface with Facebook's React Native team, not their app teams, which is why we can't really help with that part. As we make RNW an easier proposition for existing RN apps to adopt we are of course hoping that leads to more Windows apps.

**Comment by Poopooracoocoo** [comment]
@chrisglein
Thanks for the reply! I believe that if Facebook's RN team found out about this odd fact, I'm sure they'd do something. Even if they only said "Really? That's strange!", it'd mean that they took notice. And I'm sure the people who work on Instagram and FB Messenger talk to the React Native team. I understand that it's not really relevant to the RN and RNW projects but I don't know of any other way of contacting them 

off topic question: Does the UWP/Microsoft Store Skype app use the new RNW now?

**Comment by Poopooracoocoo** [comment]
hey @chrisglein I don't know if you saw my above comment

**Comment by Poopooracoocoo** [comment]
And I just found out that FB Messenger doesn't use RN. Instagram defs does.
