### ISSUE TITLE
FacadeType assert.  Can it be a noop warning instead of assert?

### ISSUE THREAD

**Issue by namrog84** [microsoft/react-native-windows#4220]
"react-native-windows": "0.61.0-beta.22",

Running into an issue with  FacadeType.h
https://github.com/microsoft/react-native-windows/blob/a2f28bc4e3a6aacf9f63867effea0850b7400e39/vnext/ReactUWP/Modules/Animated/FacadeType.h#L44

is hitting the  `assert(value == "progress");` but the value is "borderRadius"

Can we just remove the assert and have some other warning with no-op fallback?  This is the 2nd time I've hit facadeType issue (last time was from the 'progress' but I don't think checking in another noop is the right solution

The only change I did was add react-native-video. I am investigating if its on our side or RNV side

**Comment by chrisglein** [comment]
Would be better as a yellow box warning. This scenario isn't supported, but that's not an internal programming error, therefore should not be an assert. We'll downgrade this.

**Comment by harrisrobin** [comment]
hitting this too, this causes the app to crash on windows.

**Comment by rozele** [comment]
Looks like this issue can be closed, we no longer include this assert.

**Comment by namrog84** [comment]
Agreed. It looks like now it'll just return a FacadeType::None when not detected. I am going to close this issue.

I double checked to make sure the assert didn't just move, and investigated up the callers of the function, and it looks like its all good to me.


https://github.com/microsoft/react-native-windows/blob/main/vnext/Microsoft.ReactNative/Modules/Animated/FacadeType.h#L50
