### ISSUE TITLE
Fix or Remove Cross-Plat Stubs of Windows-Specific Components

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#4222]
We have a number of Windows specific components. E.g. `Glyph` and `Flyout`. We provide non-Windows implementations of these that no-op, similar to React Native stubs. I'm guessing the motivation here is for cross-plat apps, so that we could select to create the component based on run-time platform but still correctly bundle.

This won't actually work as-is though. We only expose these components in `react-native-implementation.windows.ts` instead of the shared implementation. This means our stub components can never be exposed, since we only ever put them on the React Native API surface when we're already Windows.

**Comment by NickGerleman** [comment]
@ahimberg do you have any thoughts here on a preferred solution?

**Comment by chrisglein** [comment]
Either we have to create the stub implementation in React Native core, and implement in Windows. Or we only implement in Windows and there's no stub. Or there's community module for these (react-native-windows-extended?). For these particular components there shouldn't be any dependencies of the core on this, just app code, so they could be separate.

I believe the suggestion that came up this week was that `react-native-implementation.ts` that was the default stub and the real implementation in `react-native-implementation.windows.ts`.

Can we make the bundler smarter? Is that the better way to solve this? 

Overall, this needs design work.

**Comment by chrisglein** [comment]
Design needs to be jump started now, and include partner stakeholders. Scheduling that for now, and then we'll figure out what the work is.

**Comment by kmelmon** [comment]
Here's a list of all the components we're including via react-native-implementation.windows.js:
DatePicker
Flyout
Glyph
Picker
Popup
supportKeyboard
EventPhase - used for keyboard events
HandledEventPhase - used for keyboard events
ViewWindows
AppTheme

If I write app code that imports Popup from react-native, it works.  But if I import Popup from react-native-windows, it also works.  I think this is an artifact of our metro config, which redirects react-native to react-native-windows.  So at this point I can't tell what the original intent was behind react-native-implementation but it seems wrong that we've made it possible to import these types from react-native.

**Comment by acoates-ms** [comment]
Yes I would expect it to work at a code level, but if you import it from react-native you should get type errors because its not part of the public interface.

**Comment by kmelmon** [comment]
I propose cleaning this up as follows:

1) Move the previously lean-core components out to community modules along with the others already in this camp for core RN.  I think that includes:
-DatePicker
-Picker (already in progress)

2) Move others out to community modules if we think they would make sense as xplat modules (eg Popup may fall into this category).

3) Move the components that are Windows-specific, but don't need to be in core code, out to react-native-windows-extended (eg Glyph)

4) Whatever must truly stay in the core stays in react-native-windows.  I think ViewWindows and the keybaord/event stuff is in this category.  These should ideally not be importable from react-native as this will inevitably cause problems down the road.

**Comment by acoates-ms** [comment]
I agree with the exception of point 3. React-native-windows-extended was a temporary dumping ground for code that was being used by Stella but that we wanted to remove from core.  We should be making community modules for those long term.  react-native-glyph might be something that could make sense on other platforms too?  I dont think react-native-windows-extended makes any real sense as a long term plan.  Either things should be in core like ViewWindows, or community modules.  Its OK to have community modules which are windows only.

**Comment by kmelmon** [comment]
Regarding point 3- I don't have any objections to creating more community modules.  The important question we'll need to answer is if it's OK for @KAnder425 team to consume Flyout/Popup and others from community modules.

Looking at react-native-windows-extended, I don't see anything useful there, just a couple samples, so maybe part of this cleanup should include deleting react-native-windows-extended.

**Comment by ahimberg** [comment]
On the stubs, yeah I think we had those so you could successfully bundle even with an accidental reference.  I forget why those kept coming up, maybe from when everything was in 'react-native' proper - I ran into problems a couple times using stubbed components on mac, when standing up some cross-plat code.  I think what was also annoying there is bundling would work but you'd get run time errors with typos in the stubs.

As for glyph/etc.  Its probably possible to move things to Stellar if necessary.  But also potentially be aware if things are being used by the old polyester support in the LivePersonaCard on uwp, until we deprecated classic Mail later this year that is in use.

**Comment by chrisglein** [comment]
FYI, here is list that Keith provided updated with issue links:
- [DatePicker](https://github.com/microsoft/react-native-windows/issues/4156)
- [Flyout](https://github.com/microsoft/react-native-windows/issues/4343)
- [Glyph](https://github.com/microsoft/react-native-windows/issues/4344)
- [Picker](https://github.com/microsoft/react-native-windows/issues/3036)
- [Popup](https://github.com/microsoft/react-native-windows/issues/4345)
- supportKeyboard 
- EventPhase - used for keyboard events 
- HandledEventPhase - used for keyboard events 
- ViewWindows 
- [AppTheme](https://github.com/microsoft/react-native-windows/issues/4322)

For our current design for platform specific properties ([discussion here](https://github.com/react-native-community/discussions-and-proposals/issues/188)) we still need ViewWindows, so that stays.

For the keyboarding components I have opened [this issue](https://github.com/microsoft/react-native-windows/issues/4346) to track how we either upstream those or develop a plan to align with MacOS.

Does that set of issues capture everything we want to here?

**Comment by kmelmon** [comment]
Thanks @chrisglein!  This looks good.  All that remains here is to remove the apparently unnecessary stubs.  Let's leave this issue open to track doing that.
