### ISSUE TITLE
Native Modules in application namespace are not auto registering

### ISSUE THREAD

**Issue by bradcondo** [microsoft/react-native-windows#4228]
### Environment

1. `react-native -v`:
```
react-native-cli: 2.0.1
react-native: 0.60.6
```
2. `react-native run-windows --info`:
```
  System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i5-1035G4 CPU @ 1.10GHz
    Memory: 3.24 GB / 7.60 GB
  Binaries:
    Node: 12.9.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Users\bradc\AppData\Roaming\npm\yarn.CMD
    npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: ^0.60.5 => 0.60.6
    react-native-windows: 0.60.0-vnext.136 => 0.60.0-vnext.136
    rnpm-plugin-windows: ^0.4.0 => 0.4.1
  Installed UWP SDKs:
    10.0.18362.0
```

- Target Platform Version(s): 10.0.18362
- Target Device(s): Desktop
- Visual Studio Version: Microsoft Visual Studio Community 2019, Version 16.4.3
- Build Configuration: Debug

### Steps to Reproduce

1. Follow [Getting Started](https://microsoft.github.io/react-native-windows/docs/getting-started) guide to create RNW project.
2. Follow [Native Modules](https://microsoft.github.io/react-native-windows/docs/native-modules#sample-native-module-c-1) guide to create `FancyMath` native module, without step 2 since using the application namespace in `App.idl` should make the module automatically registered.

### Expected Behavior

`FancyMath` to be available in `NativeModules` object imported from `react-native` in JavaScript.

### Actual Behavior

`FancyMath` is not available in `NativeModules`.

### Additional Context

I am fully expecting this to be an issue with my approach to creating the native module, but I followed the instructions given and am not sure why the native module isn't available.

**Comment by bradcondo** [comment]
I fixed this when I realized that I need to include my `FancyMath.h` file in my `App.h`.

**Comment by giregk** [comment]
I ran into the same issue. Maybe the doc isn't clear enough : I understood I could skip part 2 of the tutorial, so I didn't see I needed to include my file in App.cpp
