### ISSUE TITLE
react-native-windows doesn't build

### ISSUE THREAD

**Issue by aemre** [microsoft/react-native-windows#4247]
I couldn't build for windows.
Error logs is below:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Element <LanguageStandard> has an invalid value of "stdcpp17".	Common	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	358	
Error		Element <LanguageStandard> has an invalid value of "stdcpp17".	Folly	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	358	
Error	MSB6011	Invalid parameters passed to the Microsoft.Build.CPPTasks.CL task.	Folly	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	358	
Error	MSB6011	Invalid parameters passed to the Microsoft.Build.CPPTasks.CL task.	Common	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	358	
Error		Element <LanguageStandard> has an invalid value of "stdcpp17".	ReactCommon	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	358	
Error	MSB6011	Invalid parameters passed to the Microsoft.Build.CPPTasks.CL task.	ReactCommon	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	358	
Error		Element <LanguageStandard> has an invalid value of "stdcpp17".	ReactWindowsCore	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	253	
Error	MSB6011	Invalid parameters passed to the Microsoft.Build.CPPTasks.CL task.	ReactWindowsCore	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	253

**Comment by chrisglein** [comment]
Can you provide more detail on your setup?

If you are using latest version:
1. `react-native -v`:
2. `react-native run-windows --info`:

Otherwise if `--info` doesn't exist:
1. `react-native -v`:
2. `npm ls rnpm-plugin-windows`:
3. `npm ls react-native-windows`:
4. `node -v`:
5. `npm -v`:
6. `yarn --version`:
