### ISSUE TITLE
"Loading Bundle" is not hidden on release builds

### ISSUE THREAD

**Issue by AAAstorga** [microsoft/react-native-windows#4252]
### Steps to Reproduce

(Write your steps here:)

1. Configure app for release build
2. Notice "Loading Bundle" is still present on launch
3.

### Expected Behavior

There should be no "Loading Bundle" text.

### Actual Behavior

"Loading Bundle" text shows up. It looks like that UI code should be wrapped in an #if DEBUG

**Comment by namrog84** [comment]
https://github.com/microsoft/react-native-windows/blob/f75c1978ac0e6661397c4dbc0a368574f4298fec/vnext/Microsoft.ReactNative/Views/ReactRootControl.cpp#L357

Looks like this is maybe where it is coming from.

**Comment by acoates-ms** [comment]
Actually I think it should be based on IsDevModeEnabled rather than debug.
