### ISSUE TITLE
UWP + RNW + RN long term conflicts with StorageFile file access

### ISSUE THREAD

**Issue by namrog84** [microsoft/react-native-windows#4255]
We recently ran into an issue that is likely going to cause a bigger issue for all RNW consumers and might possibly require a windows API change or we might have to forever deal with some kind of non ideal work around.

We implemented a native module RNImagePicker (https://github.com/react-native-community/react-native-image-picker)

It let's the user prompt for a file a file to use
`StorageFile file = co_await filePicker.PickSingleFileAsync();`
But this module only returns a string, not a reference to the StorageFile.
```
JSValueObject response;
response["uri"] = to_string(file.Path());
promise.Resolve(response);
```
Then later on another ReactModule such as the react native file system wants to read this file.(https://github.com/itinance/react-native-fs)

Something like
```
StorageFolder folder = co_await StorageFolder::GetFolderFromPathAsync(directoryPath);
StorageFile file = co_await folder.GetFileAsync(fileName);
```

However, this will not work because UWP cannot access any arbitrary StorageFolder/StorageFile locations outside of ApplicationData::Current() or with right elevated privileges certain user folders.
The only way UWP can access arbitrary file locations is if user action selected the file through a pop up FilePicker and continued use of the returned StorageFile.  But we have no way to translate the StorageFile handle from 1 native module to another native module. Especially when they are in different repos and cant have a standardized backdoor pass thru.

Our current workaround is inside the RNImagePicker to make a copy of the file to
`winrt::Windows::Storage::ApplicationData::Current().TemporaryFolder()`
and return this copied file path instead.   Then later on the RNFS can access this file.

This will probably work for most people on the short term, but is not ideal because its making unnecessary copies of files. 

React Native often passes things around in strings and I don't think anything can be done about that.
So does UWP/windows need some kind of new API or special permission or dictionary look up to keep a hidden internal StorageFile handle so it can be access in an independent separate code after the file selection?  
I am not sure and while we have a viable workaround on the short term. I know it might require some long poll items from other teams if a new API is needed.

**Comment by chrisglein** [comment]
Great issue, tricky problem. This isn't specific to this pairing of modules, as there are other pickers and other file system modules. We'd kind of need to get them to all coordinate on some solution. This needs design work to figure out a good solution. In the meantime I'm glad you have a (not ideal) workaround.

**Comment by vmoroz** [comment]
It sounds that we need a dictionary of values that can be kept in application context to be shared between different native modules. We have a similar mechanism in our RN host in Office. We should one here too.
