### ISSUE TITLE
Landing page readme (main and vnext) should link to rnw site

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#4264]
no mention to Microsoft.github.io/react-native-windows

**Comment by kikisaints** [comment]
Should we even still have a mention of vnext on the readme, @chrisglein?

**Comment by chrisglein** [comment]
The Getting Started section does link to the website.
@kikisaints are you happy with the scrub to point to the website? Not everything will be there, maybe we should highlight it a bit more. There is a fair amount of stale data.

We should be dumping mentions of vnext.

Assigning to you Kiki to see how you want to scrub this.

**Comment by kikisaints** [comment]
I think if there's still vnext mentions and it's not obvious how to get to the site from the README, it needs a good scrubing. I'll fork and start a PR on cleaning it up.

**Comment by kikisaints** [comment]
@chrisglein the PR for the README to be updated has been merged. there should now be links out to our website. The vnext README has yet to be removed. Is that an @jonthysell work item or should I go ahead and create a PR for that?

**Comment by chrisglein** [comment]
Yeah, according to Andrew that readme drives what shows up in the package:

> The one in vnext will show up on npmjs.org for the published npm package, since its part of the actual npm package.
> 
> The one in the root is the one that will show when people go to the GitHub repo.  The one in vnext is the one they will see on npmjs.org.   If we want them to be the same, we should probably just delete the one in vnext, but ensure that we have a build step to copy the one in the root into vnext before publishing.

I've created a new issue to track that course of action: #4632

> Is that an @jonthysell work item or should I go ahead and create a PR for that?

@asklar was doing the index of various markdown files to see what we could delete. But that was to just check in on what was needed. We'll have #4632 track taking action on that.

**Comment by harinikmsft** [comment]
@chrisglein what is the action remaining on this task? Are we trying to keep a manual copy of the main read me in the vnext/readme so the npm feed picks up the right thing until #4632 is done?

We should really not even have a vnext folder (perhaps rename to source) and just have npm feed pick up from the main landing page like all other repos do.

**Comment by chrisglein** [comment]
> @chrisglein what is the action remaining on this task? Are we trying to keep a manual copy of the main read me in the vnext/readme so the npm feed picks up the right thing until #4632 is done?

Until we have an automated process for updating the vnext/readme (#4632) it seems like we need to keep it up to date - snapping to whatever content is in the main readme.

But as for what is the actionable item here... it agree it's too muddy. I believe all that's left is snapshotting the vnext readme with what's in the root. I'll create a unique issue to track that so we can close out this one.

> We should really not even have a vnext folder (perhaps rename to source) and just have npm feed pick up from the main landing page like all other repos do.

Yes to restructuring the folders. That's #3748.
Perhaps if that happens we don't need to do the above propagation of the readme. @jonthysell do you have thoughts on the ideal directory structure? Does it still involve living in a packages subfolder (in which case propagating the readme is still necessary)?

**Comment by chrisglein** [comment]
> > @chrisglein what is the action remaining on this task? Are we trying to keep a manual copy of the main read me in the vnext/readme so the npm feed picks up the right thing until #4632 is done?
> But as for what is the actionable item here... it agree it's too muddy. I believe all that's left is snapshotting the vnext readme with what's in the root. I'll create a unique issue to track that so we can close out this one.

Created #4671
