### ISSUE TITLE
Onboarding for RNW is steep

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#4265]
At the very least we need instructions (in the form of a .md file maybe), for a new person trying to build with RNW (not just building an app). Specifically: what does each folder under vNext refer to? There's Microsoft.ReactNative, ReactUWP, but there's also ReactWindowsCore...

**Comment by chrisglein** [comment]
@jonthysell was looking into some folder restructuring, which would help make it look less confusion. There are also some documents like this one that I don't think are correctly linked into the contributing md:
https://github.com/microsoft/react-native-windows/blob/master/docs/project-structure.md
Overall the contributor documentation needs a cleanup to remove the vnext/current duplication in the docs.

Jon, assigning to you to weigh in with where you were with any restructuring you had thought out (not saying you need to do all of that here, but let us know where it is).

**Comment by jonthysell** [comment]
BTW: The new home of that file is here: https://microsoft.github.io/react-native-windows/docs/project-structure

First off, we should probably clear out the documentation here and point people toward the docs site.

For all of these docs, whether for app/module developers or framework contributors, it will need to be properly versioned, either by using branches or "archived" folders, so that we don't stomp on old docs with new changes, esp. in something like this, where we're actively refactoring project structures.

**Comment by chrisglein** [comment]
Lots of potential next steps here.

First we need to remove any duplication between this and the website. Let's use this issue to track doing that first.

Then we need to make sure there's room for collaborator docs versus general app developer docs. Part of that is internal repo documentation, which could make sense as mds here or via the wiki. TBD. But first step, put things on the website that should be on the website, and delete them from here.

**Comment by chrisglein** [comment]
I've tried to capture some of the deficiencies of the problems with the contribution docs in [this issue](https://github.com/microsoft/react-native-windows-samples/issues/95) in the samples repo (where Kiki has us tracking website issues). There's impact on the website, and also the repo. We need to break this down into actionable steps. First decision is: what's our philosophy about where contribution docs live? (then we can start deleting the duplicates)

**Comment by chrisglein** [comment]
We've got some concrete follow ups filed in the docs repo. I think as is the issue here isn't actionable enough.
@asklar Is there more you want to capture? As is I think we should close this issue out and move forward with fine-grained issues.
