### ISSUE TITLE
Can't find DebugBundle and ReleaseBundle Configurations in VS 2019

### ISSUE THREAD

**Issue by brukbrhane** [microsoft/react-native-windows#4266]
### Environment

1. `react-native -v`: 0.60.0 and 0.61.5
2. `react-native run-windows --info`: 0.61.0-beta.46 and 0.60.0-vnext.136

- Target Platform Version(s):10.0.18362

- Target Device(s):Desktop

- Visual Studio Version: Visual Studio 2019

- Build Configuration: Debug

### Steps to Reproduce

1. Run installation instructions shown [here](https://microsoft.github.io/react-native-windows/docs/getting-started)
2. Open Visual Studio

### Expected Behavior

I expected to find the DebugBundle and DebugRelease Configuration Options available 

### Actual Behavior

Only the default `Debug` and `Release` options were available for use.

(Write what happened. Add screenshots!)
![image](https://user-images.githubusercontent.com/20716815/76142737-62a13080-6081-11ea-97a6-fff009893975.png)

### Reproducible Demo

https://github.com/brukbrhane/win-test-rn

### Additional context

- The only time "Bundle" was referenced in the vsxproj file was within the BundleCommand tag running the `react-native bundle` command. This BundleCommand doesn't seem to be linked to any Build Configurations though. If there is another way to create a standalone app. I am not aware of it because the current implementation of the app doesn't seem to cache the bundles...

**Comment by namrog84** [comment]
The document is out of date. There is no more DebugBundle and ReleaseBundle configuration.

Debug is non bundle by default.
Release is bundle by default.

You can override this behavior if you want a debug bundle build by overriding a PropertyGroup UseBundle

`<UseBundle>true</UseBundle>`

**Comment by brukbrhane** [comment]
Gotcha. Thanks for the help @namrog84
