### ISSUE TITLE
The release bundle builds should have --dev false flag

### ISSUE THREAD

**Issue by namrog84** [microsoft/react-native-windows#4276]
see:

https://github.com/microsoft/react-native-windows/blob/4a1c8bb418ec91302880b2cea89a236eaed4dbc2/packages/microsoft-reactnative-sampleapps/windows/SampleAppCPP/SampleAppCpp.vcxproj#L179

https://github.com/microsoft/react-native-windows/blob/744a02c3997197082e35efa74b55775fc8a7f25b/vnext/local-cli/generator-windows/templates/cpp/proj/MyApp.vcxproj#L163

If running this command:
`npx react-native bundle --help`

you can see its defaulting to true
...
 --dev [boolean]                    If false, warnings are disabled and the bundle is minified (default: true)
...

This is what can help lead to some 'yellow box' warnings appearing in release builds.

**Comment by namrog84** [comment]
RN set's it using a flag for for android. Thus RNW should align with RN. 
https://github.com/facebook/react-native/blob/1fb815ed4314c1396999e64354ca0b5d4ed83663/react.gradle#L156

**Comment by chrisglein** [comment]
@namrog84 is this fixed with your PR?
(FYI you can use "Fixes #asdf" and github will automatically create a link and resolve)

**Comment by namrog84** [comment]
I abandoned my PR and my work trying to address this because things moved into an area I am not as familiar with, as I was getting the impression I was stepping on toes on other people works/plans for redesign of packaging/bundling/etc...  and other priorities have come up, so I am taking a step back from trying to address this at the moment. 

When I get some extra time again, I'll be glad to take another crack at it, but it probably wont happen for a little bit now.
