### ISSUE TITLE
CLI generated solution file is invalid for C#

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#4283]
Because we weren't actually building new C# apps (#4281), we didn't know that the solution file being generated isn't valid

**Comment by acoates-ms** [comment]
Doesn't the `Verify react-native init DebugCs` job verify that the CLI generated C# solution builds?
It looks like its running build on the generated solution, no?

**Comment by jonthysell** [comment]
No, it only runs cpp because the yaml is invalid and therefore we only ever build cpp. See #4281.
