### ISSUE TITLE
Image with svg asset source cannot be resized

### ISSUE THREAD

**Issue by Tatious** [microsoft/react-native-windows#4284]
### Environment
react-native-cli: 2.0.1
react-native: 0.61.5
  System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz
    Memory: 15.79 GB / 31.73 GB
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: ^0.61.5 => 0.61.5
    react-native-windows: 0.61.0-beta.22 => 0.61.0-beta.44
  Installed UWP SDKs:
    10.0.17763.0
    10.0.18362.0

### Steps to Reproduce
```
 <Image style={{ height: 600, resizeMode: 'center' }} source={require('../../../../assets/svgs/test.svg')} />
```

### Expected Behavior

The image resizes

### Actual Behavior

The image takes up more area, but the actual image asset remains the same size
### Additional context

Adam Gorman(adamgor)
Austin Beaulieu(aubeauli)

**Comment by chrisglein** [comment]
@marlenecota is it required that they specify the width here as well? It looks like they're only specifying the height.

**Comment by Tatious** [comment]
I have tried specifying both and nothing happened

**Comment by Tatious** [comment]
After further investigation, it seems that svgs made through the app 'Sketch' cannot be resized, but others can.

**Comment by alexzobi** [comment]
i'm experiencing this as well with svgs downloaded through figma

**Comment by marlenecota** [comment]
@alexzobi, @Tatious - do the assets have height/width set in the svg file? Those properties override any width/height values set through styles or source.
