### ISSUE TITLE
ByteCodeFileUri only works for chakracore (doesn't work for hermes)

### ISSUE THREAD

**Issue by namrog84** [microsoft/react-native-windows#4289]
When using Hermes and generating the bytecode. Ideally this would need to occur in BundleCommand step

Something like
```
      call npx react-native bundle --platform windows --entry-file index.js --dev false --bundle-output windows/$(SolutionName)/Bundle/index.bundle --assets-dest windows/$(SolutionName)/Bundle --minify 'true'
      call $(SolutionDir)packages\ReactNative.Hermes.Windows.0.1.6\installed\x64-windows\bin\hermes.exe -Wno-undefined-variable -O -emit-binary -non-strict -target=HBC -out windows/$(SolutionName)/Bundle/index.bytecode.bundle windows/$(SolutionName)/Bundle/index.bundle -fstrip-function-names
```
So the sample should be updated to support bytecode either as a secondary step or something.

A few changes need to happen here.
1st is the the switch to 'call' so that multiple commands can occur.

Currently Hermes seemingly only accepts bytecode as a form of input. 
And I have to do `JavaScriptBundleFile(L"index.bytecode");` even though the file is named index.bytecode.bundle because .bundle is always appended.  Why does magic string modification have to happen?  why cant I just give it the proper filename? 

The problem with this, is that index.bytecode.bundle is a binary, but JavaScriptBundleFile indirectly reads it in as a string.  Although it technically does work. It just feels wrong to read a binary file as a string. 

Also, I'd expect `InstanceSettings().ByteCodeFileUri(L"index.bytecode");` or something equivalent to work for Hermes (It appears only currently hooked up for chakracore and not for hermes or v8.

Alternatively, just make a full switch to hermes, and fully drop all support for v8 and chakracore.

**Comment by NickGerleman** [comment]
Reconciling the story for bytecode generation on Hermes is currently on @hansenyy's plate. How we do bytecode pre-generation for Hermes needs some design work still.

Please let me know if you have any Hermes questions. It's still an area with a lot of active development, and not quite ready set for production use-cases.

**Comment by NickGerleman** [comment]
Going to close this for now, since we a new design for bytecode consumption is something on @hansenyy's plate already
