### ISSUE TITLE
Creating a standalone AppX / MSIX package in Release mode generates a crashing app

### ISSUE THREAD

**Issue by qmatteoq** [microsoft/react-native-windows#4295]
### Environment

If you are using latest version:
1. `react-native -v`: 

react-native-cli: 2.0.1
react-native: 0.61.5

2. `react-native run-windows --info`:

 System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 5.35 GB / 15.60 GB
  Binaries:
    Node: 12.9.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
    react-native-windows: 0.61.0-beta.50 => 0.61.0-beta.50
    rnpm-plugin-windows: ^0.5.1-0 => 0.5.1-0
  Installed UWP SDKs:
    10.0.14393.0
    10.0.15063.0
    10.0.17763.0
    10.0.18362.0

Then, specify:

- Target Platform Version(s): 10.0.18362

- Target Device(s): Desktop

- Visual Studio Version: Visual Studio 2019

- Build Configuration: Release

### Steps to Reproduce

1. Create a new React Native project and add Windows support using the beta template
2. Open the Visual Studio solution in the windows folder
3. Right click on the main project and choose Publish -> Create app packages
4. Complete the wizard and generate a package for any architecture (eg. x64), just make sure to choose Release mode
5. Install the generated package
6. Launch the application

### Expected Behavior

The application starts with the default React Native template.

### Actual Behavior

The application crashes at startup.
By launching the project directly from Visual Studio in Release mode, you observe the following exceptions:

```
Exception thrown at 0x00007FFDE5133E49 (KernelBase.dll) in TestProject.exe: WinRT originate error - 0x80070057 : 'assets/node_modules/react-native-windows/Libraries/NewAppScreen/components/logo.png is not a valid absolute URI.'.
Exception thrown at 0x00007FFDE5133E49 in TestProject.exe: Microsoft C++ exception: winrt::hresult_invalid_argument at memory location 0x00000079B89FEA50.
Unhandled exception at 0x00007FFDE586284E (ucrtbase.dll) in TestProject.exe: Fatal program exit requested.
```
The culprit is Header component included in the NewAppScreen library, which is failing to parse the Uri for the logo.

**Comment by chrisglein** [comment]
Error is with loading the logo.png. Something wrong with the manifest or how the assets are transferred over?

**Comment by jonthysell** [comment]
Either the uri for the asset is hard-coded or the bundle command does not include the assets dir. Looking into it.

**Comment by jonthysell** [comment]
Found the issue, will have a PR out soon.
