### ISSUE TITLE
Use lifted DispatcherQueue

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#4306]
All uses of CoreDispatcher/DispatcherQueue should ideally be converged to use the lifted DispatcherQueue.

Details from internal mail thread:

The general guidance is that components should be self-consistent.

Both lifted and system DispatcherQueues work fine within their own domains in all scenarios.  Imagine the following pseudocode running on a single thread: 

_systemDQ.TryEnqueue(High, <sysHigh>); 
_systemDQ.TryEnqueue(Normal, <sysNormal>);
_liftedDQ.TryEnqueue(High, <liftedHigh>);
_liftedDQ.TryEnqueue (Normal, <liftedNormal>);

All four tasks will execute in all environments.   Furthermore, <sysHigh> will always execute before <sysNormal> and <liftedHigh> will execute before <liftedNormal> (because there is ordering within the separate queues).

The thing which is non-deterministic is the order that the system tasks execute relative to the lifted ones and vice-versa, which is why we don’t recommend mixing and matching – ie we don’t guarantee that the execution order is <sysHigh>, <liftedHigh>, <sysNormal>, <liftedNormal>.   -  <liftedHigh>, <sysHigh>, <sysNormal>, <liftedNormal> is equally valid, as are other permuations 😊

If a component is taking a dependency on their enqueued task executing in an order relative to something that a different component (or the system) also has enqueued (ex I do a same-thread TryEnqueue in response to an event handler, and the callback relies on other ordering), then yes, you are potentially in for mix and match badness.

**Comment by chrisglein** [comment]
Move from CoreDispatcher to DispatcherQueue (#2557), and also from inbox DispatcherQueue to lifted DispatcherQueue (this issue).

**Comment by asklar** [comment]
@kmelmon @chrisglein assigning this to myself unless you were planning on doing it already

**Comment by asklar** [comment]
Done already (only one usage of CoreDispatcher for accelerator keys - see m_coreDispatcherAKARevoker - but that is behind a null check so it's fine).
