### ISSUE TITLE
New CLI app on v0.60 can't run react-native start (error Invalid regular expression)

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#4307]
Error:

> D:\ReactWindowsUwp>yarn start
yarn run v1.21.1
warning ..\package.json: No license field
$ react-native start
error Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class. Run CLI with --verbose flag for more details.
SyntaxError: Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class
    at new RegExp (<anonymous>)
    at blacklist (D:\ReactWindowsUwp\node_modules\metro-config\src\defaults\blacklist.js:34:10)
    at getBlacklistRE (D:\ReactWindowsUwp\node_modules\@react-native-community\cli\build\tools\loadMetroConfig.js:69:59)
    at getDefaultConfig (D:\ReactWindowsUwp\node_modules\@react-native-community\cli\build\tools\loadMetroConfig.js:84:20)
    at load (D:\ReactWindowsUwp\node_modules\@react-native-community\cli\build\tools\loadMetroConfig.js:112:25)
    at Object.runServer [as func] (D:\ReactWindowsUwp\node_modules\@react-native-community\cli\build\commands\server\runServer.js:82:58)
    at Command.handleAction (D:\ReactWindowsUwp\node_modules\@react-native-community\cli\build\cliEntry.js:160:21)
    at Command.listener (D:\ReactWindowsUwp\node_modules\commander\index.js:315:8)
    at Command.emit (events.js:223:5)
    at Command.parseArgs (D:\ReactWindowsUwp\node_modules\commander\index.js:651:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by NickGerleman** [comment]
This is related to using too new of a version of node. If you search for the error you'll get some issues with more context. I think we fixed this recently in 0.61

**Comment by chrisglein** [comment]
@kikisaints This is an issue where we have different setup steps depending on version. This is a general prerequisite (you have to install an older version of Node) that was lost in the move to the website. We need to capture that step associated with version 0.60.

Until this is fixed we have the wrong instructions for people using 0.60 and we're going to get a lot of confusion.

**Comment by chrisglein** [comment]
We had the specific version of Node called out in an earlier version of the vnext getting started guide - should be able to get it from the file history in this repo.

**Comment by jonthysell** [comment]
(This fix helps: https://iamsapankumar.blogspot.com/2019/10/error-invalid-regular-expression.html?m=1&fbclid=IwAR24kM7FvVFPR9ZTdq6HAmFDvF-Th7MnV2IvS3Yo_F9m6snDFh_QNsr0vgs)

**Comment by kikisaints** [comment]
@chrisglein this is now called out in the [Dependencies](https://microsoft.github.io/react-native-windows/docs/rnw-dependencies#dependencies) section under System Requirements in the doc.

**Comment by chrisglein** [comment]
> @chrisglein this is now called out in the [Dependencies](https://microsoft.github.io/react-native-windows/docs/rnw-dependencies#dependencies) section under System Requirements in the doc.

@kikisaints That says "make sure a recent version of Node is installed", which implies we just need latest, as opposed to needing a very specific version of Node. And that you only need that for specific versions of RNW.

**Comment by chrisglein** [comment]
@kikisaints Is the documentation fixed on this? Are we okay to close?

**Comment by kikisaints** [comment]
> @kikisaints Is the documentation fixed on this? Are we okay to close?

Updated the dependencies sections to be clearer. [See this section of the docs](https://microsoft.github.io/react-native-windows/docs/rnw-dependencies#react-native-development-dependencies)

**Comment by chrisglein** [comment]
@kikisaints Isn't this incorrect for non v0.60 now though?
There's a major missing component here which is the requirements are different dependent on what version you are targeting. For v0.60 you need to use a very specific version of Node. For anything beyond that (0.61, master which is now 0.62), we do _not_ want them targeting an old version of Node.

We need per-version steps, and we need only one of the versions to make this recommendation.

**Comment by harinikmsft** [comment]
This issue needs versioning in the docs to be complete which is a larger undertaking than we have time for right now. Closing this and tracking via samples repo issue - https://github.com/microsoft/react-native-windows-samples/issues/69
