### ISSUE TITLE
Animated.View does not position itself properly pre and post animation

### ISSUE THREAD

**Issue by Tatious** [microsoft/react-native-windows#4313]
Animated.View does not initially position itself to the original value of the Animated.Value that drives its translation. Once the animation is complete, it also goes back to a position that ignores the end value. 

### Environment
react-native-cli: 2.0.1
react-native: 0.61.5
  System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz
    Memory: 15.79 GB / 31.73 GB
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: ^0.61.5 => 0.61.5
    react-native-windows: 0.61.0-beta.22 => 0.61.0-beta.44
  Installed UWP SDKs:
    10.0.17763.0
    10.0.18362.0

### Steps to Reproduce

```
export const SomeComponent = memo(() => {
    const textTranslationY = useAnimatedValue(180);
    const [someState, setSomeState] = useState(0);

    useEffect(() => {
        const animation = Animated.parallel([
            Animated.sequence([
                Animated.timing(textTranslationY, {
                    toValue: 100,
                    delay: 600,
                    duration: 750,
                    easing: Easing.linear,
                    useNativeDriver: true,
                }),
            ]),
        ]);

        animation.start(() => {
            setSomeState(1);
        });
    }, []);

    return (
        <Animated.View style={{ transform: [{ translateY: textTranslationY }] }}>
            <Text>{getString('Celebration_Title')}</Text>
        </Animated.View>
    );
});
```

### Expected Behavior

The Animated.View initally positions itself at y translation 180 (like on other platforms), animates, and then arrives and stays at y translation 100.

### Actual Behavior

The Animated.View initally positions itself at a different y value than expected, animates, and then arrives and stays at another unexpected y value after state is updated.

### Additional context

Adam Gorman(adamgor)
Austin Beaulieu(aubeauli)

**Comment by chrisglein** [comment]
Related to #3460?

**Comment by asklar** [comment]
@chrisglein  confirmed with @Tatious that this is not blocking/needed as they took a workaround to not animate the text and Design was ok with this. Should we remove the must-have tag/reprioritize?

**Comment by asklar** [comment]
closing per the last comment, please let us know if this is still happening for you @Tatious
