### ISSUE TITLE
Add DebuggerPort to ReactInstanceSettings

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#4315]
For CLI generated apps, direct debugging doesn't work because there is no DebuggerPort  property, which is needed to tell the core what port to open a WebSocket on.

From Anandraj:
"Developer configures the JSI runtime to additionally spawn a debugger (websocket) server listening for Chrome debug protocol messages at a specific port. The debugger server directly talks to the Javascript engine using engine specific debugger APIs"

**Comment by nasadigital** [comment]
I will go ahead and close the issue, as the PR has been merged.
