### ISSUE TITLE
Desktop/Office Networking Module Ignores the `withCredentials` parameter of sendRequest

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#4317]
This was discovered during the 0.62 update, where I did a bit of deforking of our version of `RCTNetworking.win32.ts`. This param was added three years ago to support enabling or disabling sending cookies with XHR requests. See https://github.com/facebook/react-native/commit/e544563bd20a3ba0ed9ebe91d593bdf2e2cac2c6

**Comment by NickGerleman** [comment]
FYI @JunielKatarn. Not sure if this applies to the ReactUWP implementation as well.

**Comment by JunielKatarn** [comment]
Need more context. There is no production-ready HTTP native module implementation in RNW/Desktop.

This repository does NOT ship such module.

Are there concrete steps to reproduce?

**Comment by NickGerleman** [comment]
The forked JS-side library in `react-native-win32` was missing the param, so we don't even shuttle it to native. The impact of this is likely that Native ignores what JS specifies and uses whatever default behavior it has. The `Desktop` `NetworkingModule` in RNW and `NetworkingHttpModule` in Office of course doesn't do anything with the param since it was never given to them.

Hoping we can see some convergence in the future between:
- `ReactUwp`
- `RNW Desktop`
- `NetworkingHttpModule` in Office

**Comment by JunielKatarn** [comment]
This is what I can't make sense of:
> The Desktop `NetworkingModule` in RNW

As far as I know, there is no Desktop `NetworkingModule` in RNW.
It is only implemented in Office, which is not yet using RN 0.62.

**Comment by NickGerleman** [comment]
https://github.com/microsoft/react-native-windows/blob/master/vnext/Desktop/Modules/NetworkingModule.cpp From some inspection, we seem to only use it in integration tests?

This specific param though was added three years ago, far before the 0.62 upgrade. I just caught it now because I'm trying to do some cleanup to get type safety for our forked JS files. The link to the commit that added it is in the issue description.

**Comment by NickGerleman** [comment]
Oh wow, that module actually just stubs everything. looks like there was some intent to make it real, but it was just left as a skeleton? We should clean that up.

**Comment by JunielKatarn** [comment]
Thought so.
That is an experimental unreleased module we do NOT export in the Desktop DLL.
It's unfinished, and not production ready.

At this point, there is no Desktop HTTP native module implementation outside of Office.
The implementation if `IHttpResource`, `Microsoft::React::Experimental::HttpResource` is not finished, and would likely be replaced by a C++/WinRT implementation at this point.

**Comment by JunielKatarn** [comment]
> Oh wow, that module actually just stubs everything. looks like there was some intent to make it real, but it was just left as a skeleton? We should clean that up.

Yeah, I wrote that class.
We will actually want to write a Desktop-compatible HTTP module, but it never got prioritized.
That's why it's still in the `Experimental` workspace.

**Comment by NickGerleman** [comment]
I'm guessing the new module you're writing is going into RNW? Will that implementation use the param that we previously weren't shuttling?

**Comment by JunielKatarn** [comment]
> I'm guessing the new module you're writing is going into RNW? Will that implementation use the param that we previously weren't shuttling?

Yes. It will be written in RNW, and naturally comply with the current JavaScript API.
Note, not currently prioritized, but that can be discussed with the team.

**Comment by NickGerleman** [comment]
I don't think this is a high priority, but do want any API gaps that we have to be logged. I will leave this open if we think the new module will have the same gap.

For reference, this is the change I made to the JS side. Assuming the native module doesn't assert the number of parameters (no implementations currently do), this should just plumb the extra parameter which the native module with ignore. https://github.com/microsoft/react-native-windows/pull/4300/commits/e9e4931fb3620f45537480f3b046bec20c420763
