### ISSUE TITLE
Make upstream changes to share RCTNetworking Between Platforms

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#4318]
Windows currently uses the exact same JS as the Android implementation, only differing in the name of the Native module. We should consider looking at unifying the Native module interface upstream so we can share implementations of this across all platforms.

**Comment by JunielKatarn** [comment]
#12199 makes `RCTNetworking.win32` fully based on `RCTNetworking.ios`, which was already the case for `RCTNetworking.windows`.

This unifies the JS interface between four platforms: `windows`, `win32`, `ios` and `macos`.

Regarding Android, I'd argue this issue should be raised at Meta's react-native repository.

The mentioned pull request will close this issue, for there are no further changes to make or contribute from RNW to upstream RN.
Rather, the unification should take place among Android and iOS variants.
