### ISSUE TITLE
Update CLI to say "To Run your app on UWP: npx react-native run-windows"

### ISSUE THREAD

**Issue by kikisaints** [microsoft/react-native-windows#4326]
### Steps to Reproduce
When you follow the Getting Started guide on the RNW website it instructs you to now install React Native locally. Which means the last step to actually kick-off the build process is:

`npx react-native run-windows`

However, the CLI advises you to run `react-native run-windows` which was the old instructions and with the local install will no longer work.

### Expected Behavior
At the end of the CLI instructions you will be given a notice to do the following:

```
To run you app on UWP:
npx react-native run-windows
````

### Actual Behavior

After you finish CLI installation instructions for RNW, you get this:

![image](https://user-images.githubusercontent.com/6964369/76796788-69b6f580-6789-11ea-9a45-51d168316f25.png)

Which if a user is following the new guidance will not work.

### react-native run-windows --logging
^^ Also this section header in the template needs to be updated for the same reasons.

**Comment by riverar** [comment]
Nit: UWP is an ambiguous term (conflates appmodel, winrt xaml, etc.), so I'd advise against using that acronym.

**Comment by rectified95** [comment]
@riverar What wording would you suggest instead of 'run on UWP'?

**Comment by riverar** [comment]
@rectified95 "run on Windows" perhaps? Just a minor nit/peeve, don't want to create a lot of churn here.

**Comment by rectified95** [comment]
The problem has been fixed in another issue, as I can now see the expected string in the CLI.
