### ISSUE TITLE
Update react-native-picker for dual-screen

### ISSUE THREAD

**Issue by YuliKl** [microsoft/react-native-windows#4334]
Components with flyouts/popups need to be aware of the seam and avoid having their content cup/split if possible. We're updating [react-native-picker](https://github.com/react-native-community/react-native-picker) to use Xaml ComboBox on Windows, which will result in the correct dual-screen behavior. This issue tracks validating or updating this component to work correctly on Android / Duo.

**Comment by chrisglein** [comment]
We haven't been opening issues on other component repos for components we're modifying. We can't assume what sort of issue management they have. But it also feels weird to do it here without some sort of system. @stmoy do you have opinions about how we should handle this? We definitely need some filtering/label/project something something for these.
