### ISSUE TITLE
[Dev inner loop] OneTimeSetup script

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#4335]
We have a complex set of requirements (multiple tools, specific versions) that also keep changing over time. It's hard for folks trying to build apps or the platform itself to be in a good known/supported state. 
This issue tracks adding a setup script like the one I wrote for WinUI 3.

**Comment by chrisglein** [comment]
Overall I think we want to bring down that list of requirements first. Once that list is shorter we should evaluate what we need here.

There's a command called 'react-native doctor' that does all sorts of checks and fixes that we don't plug into today but we could in the future. That might be the best way to solve this and not diverge from the ecosystem.

**Comment by molant** [comment]
I agree with @chrisglein that ideally this should be done in `doctor`.
I've been adding a few things there [to improve the Windows setup experience](https://github.com/react-native-community/cli/pulls?q=is%3Apr+author%3Amolant+) so I could help with that or provide some guidance if needed.

There's a proposal to split [doctor to a separate package](https://github.com/react-native-community/cli/issues/1047). Maybe this could be an opportunity to add better support for out of tree platforms?
