### ISSUE TITLE
Add CI loop for docs

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#4339]
we should have a parallel CI loop to ensure docs don't have broken links in them

**Comment by chrisglein** [comment]
@jonthysell This is good to go, yes?

**Comment by chrisglein** [comment]
Ping @jonthysell / @asklar - We can close this, yes?

**Comment by chrisglein** [comment]
Closing this out lacking more specific detail (and knowing we've done some work here). Open more specific actionable issues on the samples repo if we have them.

**Comment by asklar** [comment]
reopening to check in the CI loop for in-repo docs
