### ISSUE TITLE
Distribute react-native-windows as DLL

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#4352]
The current source code distribution model has limitations:
-It requires customers to install just the right set of build tools/sdks.  For example we require a specific version of CppWinRT, if you don't install it, your build breaks.
-It's time consuming to build
-More internal facing:  our own CI loop is suffering from these same problems, which creates disk space issues and runs that take longer than strictly necessary due to building the same code multiple times.

This task is tracking the first step in the process towards moving to a binary distribution model - publish a binary, very likely to Nuget.

**Comment by vmoroz** [comment]
We are planning to work on implementing these DLLs in Q2 CY 2020.

**Comment by kmelmon** [comment]
We now have a project board and lots of tasks covering this, closing
