### ISSUE TITLE
Simplify the internals for instances and settings

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#4354]
Part of the hosting refactoring has complicated how we pass settings around internally. We have like three different types of instances and settings objects, and we do a lot of manual copying of values between them, or keep multiple objects side by side, with no clear precedence on which ones to set/consume.

This means we keep running into bugs when we set a setting in one object, only to find that we read the setting from different object, or due to timing issues, (or on reloads) we overwrite a user setting with a default one.

**Comment by jonthysell** [comment]
#4295 - A sample bug, where in release builds, we default set the root path for loading bundled assets to `ms-appx://Bundle/` in one field, but at runtime we load from a different field.

**Comment by jonthysell** [comment]
#4072 - Another sample bug, where we broke the developer menu because the developer settings weren't being passed around properly.

**Comment by chrisglein** [comment]
Good cleanup, will need to notify Stellar and have Playground updated to match this.

**Comment by vmoroz** [comment]
We will do it in Q2 CY 2020
