### ISSUE TITLE
Checkbox styles do not apply as expected

### ISSUE THREAD

**Issue by jagorrin** [microsoft/react-native-windows#4367]
### Environment

If you are using latest version:
1. `react-native -v`: 0.60.6
2. `react-native run-windows --info`:
  System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 18.01 GB / 31.84 GB
  Binaries:
    Node: 10.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.7 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.6 => 0.60.6
    react-native-windows: 0.60.0-vnext.149 => 0.60.0-vnext.149
    rnpm-plugin-windows: 0.3.5 => 0.3.5
  Installed UWP SDKs:
    10.0.14393.0
    10.0.15063.0
    10.0.16299.0
    10.0.17134.0
    10.0.17749.0
    10.0.17763.0
    10.0.18362.0

Then, specify:

- Target Platform Version(s): 10.0.18362.0

- Target Device(s): Desktop

- Visual Studio Version: 2017

- Build Configuration: Debug

### Steps to Reproduce

Create a project using react-native-windows that includes Checkboxes. Attempt to provide width, height, backgroundColor and color (see code example below).

### Expected Behavior

The border should be around the component at the given width/height. The background color should match the one provided. The foreground color should match the color provided.

### Actual Behavior

The border is only visible on the left side of the component (in this case I am decreasing the size to 16x16). The foreground color is always blue and is not affected by the "color" style applied.

### Screenshots
![cb](https://user-images.githubusercontent.com/58611963/77095556-4e3b2d00-69cb-11ea-9fc3-d4bbd58a4010.PNG)

### Code Example
This code produces the screenshot above.

```
import React, { PureComponent } from "react";
import { CheckBox } from "react-native";
...
<CheckBox value={false} style={{ width: 16, height: 16, backgroundColor: "#FF0000", color: "#00FF00" }} />
<CheckBox value={true} style={{ width: 16, height: 16, backgroundColor: "#FF0000", color: "#00FF00" }} />
...
```

**Comment by chrisglein** [comment]
CheckBox is being ejected, but we will still want to fix this.
Likely this isn't matching colors to the right state values for the control (a classic XAML problem). We should be hiding the quirkyness for the RNW customer.

**Comment by NickGerleman** [comment]
Checkbox was totally ejected for 0.64.

**Comment by jagorrin** [comment]
We have an item in our backlog to switch to the community module. Closing this issue.
