### ISSUE TITLE
UWP React-native-windows app not able to install on windows 10 LTSB 14393

### ISSUE THREAD

**Issue by seven11dev** [microsoft/react-native-windows#4381]
### Environment
Development environment:
Windows 10 LTSC 2018 17763

1. `react-native -v`:
react-native-cli: 2.0.1
react-native: n/a - not inside a React Native project directory
2. `react-native run-windows --info`:
  System:
    OS: Windows 10 10.0.17763
    CPU: (4) x64 Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz
    Memory: 9.71 GB / 15.89 GB
  Binaries:
    Node: 12.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.3 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: ^0.60.0-0 => 0.60.6
    react-native-windows: 0.60.0-vnext.147 => 0.60.0-vnext.147
    rnpm-plugin-windows: ^0.5.1-0 => 0.5.1-0
  Installed UWP SDKs:
    10.0.18362.0

- Target Platform Version(s):
Windows 10

- Target Device(s):
Windows 10 desktop LTSB 2015 14393
- Visual Studio Version:
Visual Studio 2019
- Build Configuration:
Release x64, x86

### Steps to Reproduce
1. Create a sample React-native-windows vnext app 
2. Create an App package from the windows solution targeted to windows 10 
3. Try installing the created react-native-windows app in Windows 10 LTSB version 14393

### Actual Behavior
Add-AppxPackage : Deployment failed with HRESULT: 0x80073CFD, A Prerequisite for an install could
not be satisfied.
Unspecified error
NOTE: For additional information, look for [ActivityId] c1811d4a-f650-0002-c057-85c150f6d501 in
the Event Log or use the command line Get-AppxLog -ActivityID c1811d4a-f650-0002-c057-85c150f6d501
At C:\Users\bbpos\Documents\POS_1.0.0.0_Test\Add-AppDevPackage.ps1:441 char:13
+             Add-AppxPackage -Path $DeveloperPackagePath.FullName -Dep ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:\Users\bbpos\..._x64.appxbundle:String) [Add-AppxP
   ackage], Exception
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddA
   ppxPackageCommand

**Comment by asklar** [comment]
@seven11dev can you paste the content of the event log entry that the error references?

**Comment by seven11dev** [comment]
`3/18/2020 10:45:03 AM     613          Adding uri to the list of Uris: file:///C:/Users/Documents/POS_1.0.0.0_Tes
                                       t/Dependencies/x64/Microsoft.VCLibs.x64.14.00.appx.         
                    
3/18/2020 10:45:03 AM     605          The last successful state reached was BundleProcessed. Failure occurred before  
                                       reaching the next state Indexed. hr: 0x80073CFD           
                      
3/18/2020 10:45:03 AM     401          Deployment Add operation with target volume C: on Package                       
                                       d06e1345-b5f3-4b93-96a5-a3edaaf97831_1.0.0.0_neutral_~_zxfp9v5syx21m from:      
                                       (POS_1.0.0.0_x86_x64.appxbundle)  failed with error 0x80073CFD. See             
                                       http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app           
                                       deployment issues.                                                              
3/18/2020 10:45:03 AM     404          AppX Deployment operation failed for package                                    
                                       d06e1345-b5f3-4b93-96a5-a3edaaf97831_1.0.0.0_neutral_~_zxfp9v5syx21m with error 
                                       0x80073CFD. The specific error text for this failure is: Unspecified error   `

**Comment by chrisglein** [comment]
We only support versions 10.0.15063.0 or higher:
https://microsoft.github.io/react-native-windows/docs/rnw-dependencies
You're trying on "RS1", and the oldest we support is the next Windows release after that.
