### ISSUE TITLE
RNW to support 10X

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#4383]
We don't currently test/validate that 10X works as expected. It's possible there are APIs we are using in RNW that are universal but only have the desired implementation on Desktop.

**Comment by chrisglein** [comment]
@asklar Is there a way to scan our code for unsupported APIs? Like WACK but for 10X? What's the recommended guidance here?.

**Comment by asklar** [comment]
> @asklar Is there a way to scan our code for unsupported APIs? Like WACK but for 10X? What's the recommended guidance here?.

there is no such thing. We can check my hand-collected "APIs that don't work" sheet but that's just an anecdotal list. The only way is to try and see what works/doesn't.

**Comment by chrisglein** [comment]
Next step here would be to try out RNTester on a 10X emulator and see what works and what doesn't. We do know that some level of functionality is there as we built out a dual screen demo a few months ago.

**Comment by asklar** [comment]
bringing this up for discussion again given recent developments :)
