### ISSUE TITLE
Add support for reload/developer menu from metro prompt

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#4385]
With the latest version of metro that comes with react-native 0.61, there are now a couple commands directly available from the CLI after launching metro:

┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│  Running Metro Bundler on port 8081.                                         │
│                                                                              │
│  Keep Metro running while developing on any JS projects. Feel free to        │
│  close this tab and run your own Metro instance if you prefer.               │
│                                                                              │
│  https://github.com/facebook/react-native                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

Looking for JS files in
   D:\mytest61app

Loading dependency graph, done.

**To reload the app press "r"
To open developer menu press "d"**

Notice the "r" and "d" commands.  react-native-windows doesn't currently support these.

This bug is tracking adding support for those options.

**Comment by chrisglein** [comment]
@acoates-ms believes the reload one _might_ work, needs to check.

**Comment by rectified95** [comment]
Reload does work.

**Comment by BartoszKlonowski** [comment]
I can work on implementing the support for **"d"** command.
@chrisglein Please assign me to this issue.

**Comment by BartoszKlonowski** [comment]
I've just checked that **"d"** command works fine:
![DeveloperMenu](https://user-images.githubusercontent.com/70535775/104575976-ec356d80-5657-11eb-8c8c-88ae2e7e7b90.gif)

---

Issue can be closed now - both "r" and "d" are supported.

**Comment by chrisglein** [comment]
Thanks @BartoszKlonowski !
