### ISSUE TITLE
Support react-native-community/art

### ISSUE THREAD

**Issue by stmoy** [microsoft/react-native-windows#4388]
# Support `react-native-community/art` on RNW

## Basic Info
- Module Repo URL: [react-native-community/art](https://github.com/react-native-community/art)
- Target version: 
- [ ] Issue exists on module repo (if so, [link]())

- [ ] Module has a Legacy/C# implementation (if so, [link]())

## Which app/customer is requesting this module?

Mac parity

## Essential Features

React Native module that allows you to draw vector graphics

**Comment by NickGerleman** [comment]
It seems like this module may be deprecated soon https://github.com/react-native-art/art/issues/75
