### ISSUE TITLE
Support react-native-community/progress-view

### ISSUE THREAD

**Issue by stmoy** [microsoft/react-native-windows#4389]
# Support `react-native-community/progress-view` on RNW

## Basic Info
- Module Repo URL: [react-native-community/progress-view](https://github.com/react-native-community/progress-view)
- Target version: 
- [ ] Issue exists on module repo (if so, [link]())

- [ ] Module has a Legacy/C# implementation (if so, [link]())

**NOTE: This module currently only works on iOS**

## Which app/customer is requesting this module?

Mac parity

## Essential Features

ProgressBar Component for iOS, based on UIProgressView. 
Supports:
* progress
* progressImage
* progressTintColor
* progressViewStyle
* trackImage
* trackTintColor

**Comment by chrisglein** [comment]
Progress bar is merged. Not yet released quote yet. The v1.1.0 [release](https://github.com/react-native-community/progress-view/releases) was missing the windows files, but that should be fixed with whatever the next release is.
