### ISSUE TITLE
Shouldn't rnpm-plugin-windows be a dev-dependency ?

### ISSUE THREAD

**Issue by giregk** [microsoft/react-native-windows#4395]
If I'm not mistaken, `rnpm-plugin-windows` should be a dev-dependency. I'm concerned that installing it as a dependency will unecessarily increase the build size of the final package. Is that wrong ?

I think the documentation should be updated, either to change the install command to `yarn add rnpm-plugin-windows --dev` or to explain why it has to be a true dependency.

**Comment by chrisglein** [comment]
Correct, this should be a dev dependency.
@kikisaints has been updating our docs on getting started steps - can you handle this?

Also of note we use this for one command and then never again. We may want to rethink how our steps work here. But for now let's update this.

**Comment by NickGerleman** [comment]
Documentation now reccomends running react-native-windows-init instead of adding rnpm-plugin-windows.
