### ISSUE TITLE
Getting LaunchActivatedEventArgs (Property User) into a native module

### ISSUE THREAD

**Issue by namrog84** [microsoft/react-native-windows#4396]
https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.activation.launchactivatedeventargs

`void OnLaunched(Windows::ApplicationModel::Activation::LaunchActivatedEventArgs const &e);`

LaunchActivatedEventArgs has a property "User"

In one of our react native modules (for auth login) we need to pass this property down from OnLaunched to a ReactNativeModule but currently have no good way to do it.  There was another mechanism we previously used on windows that worked fine, but it doesnt work on WCOS which is why we need it from here for WCOS devices. 

Recently a thing was added for Linking #4392 for the URI.

We currently are doing something kinda ugly to get it through, but if there was a built in mechanism to pass this information along properly it would be great.

**Comment by chrisglein** [comment]
We need to come up with a plan for where this platform specific additional data should live. Needs design work.

@namrog84 How ugly is your workaround?

**Comment by namrog84** [comment]
A global static basically is in a NativeModule from App.cpp 

This static doesn't get consumed until a normal NativeModule REACT_METHOD operation takes place during login and checks to see if this global static is set or not. 

Which also adds complications to migrate this NativeModule into its own repo/project right now as well, which we had originally wanted to soon, but is now delayed until this can be worked around.

**Comment by namrog84** [comment]
```
void App::OnLaunched(const Windows::ApplicationModel::Activation::LaunchActivatedEventArgs& e)
{
    AuthReactModule::SetLaunchUser(e.User());
    ...
}
```

```
REACT_MODULE(AuthReactModule, L"AuthReactModule");
struct AuthReactModule { 
static void SetLaunchUser(winrt::Windows::System::User launchUser);
...
```

```
winrt::Windows::System::User g_launchUser(nullptr);

// TODO: Reconcile this with AuthReactModuleInitialize called from reactnative
void AuthReactModule::SetLaunchUser(winrt::Windows::System::User launchUser)
{
    g_launchUser = launchUser;
}
```

**Comment by vmoroz** [comment]
I will add a dictionary to access all such launch parameters from a single place. The dictionary should be accessible from the ReactContext. Ideally, we should be able to use something like attached properties. Give me a few days to play with it.
