### ISSUE TITLE
REACT_EVENT doesn't support events with 0 params

### ISSUE THREAD

**Issue by benhamlin** [microsoft/react-native-windows#4401]
### Environment
1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.61.5
2. `react-native run-windows --info`:
 System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz
    Memory: 14.88 GB / 31.73 GB
  Binaries:
    Node: 10.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.7.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: 4.9.4 - C:\Users\bhamlin\bin\watchman.EXE
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: ^0.61.5 => 0.61.5
    react-native-windows: 0.61.0-beta.44 => 0.61.0-beta.44
  Installed UWP SDKs:
    10.0.17763.0
    10.0.18362.0

### Steps to Reproduce

Within a native module, declare an event with 0 params:

```
REACT_EVENT(MyEvent, L"myEvent")
std::function<void()> MyEvent;
```

### Expected Behavior

Compiles and I can fire my event with `MyEvent()`

### Actual Behavior
```
Microsoft.ReactNative.Cxx\NativeModules.h(802,66): error C2027: use of undefined type 'winrt::Microsoft::ReactNative::ModuleEventFieldInfo<TField>'
  with
 [
     TField=std::function<void (void)> MyModule::*
 ] (compiling source file MyModule.cpp)
```
Looks like a simple oversight, unless there's some valid reason I'm unaware of

**Comment by vmoroz** [comment]
This is by design. The REACT_FUNCTION allows 0..n parameters, but the REACT_EVENT always requires a single parameter to communicate result back to JS. What is your scenarios for not having a parameter for an event?

**Comment by benhamlin** [comment]
I'm not sure we're talking about the same thing, events don't have "results"; they're one way signals from native to javascript that may or may not have additional parameters.

The documentation example for this at https://microsoft.github.io/react-native-windows/docs/native-modules#attributes-1 is not a great example because it's using an event to double-communicate the result of a REACT_METHOD, which might be what you're thinking of? But events can be fired from anywhere.

And just to be clear, parity with Android/iOS requires supporting 0 param events. On Android, you can write this:
```
reactContext
      .getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter.class)
      .emit("eventName", null);
```
And it will fire an event with no parameters.

**Comment by benhamlin** [comment]
Actually the more I look at this the more it looks like REACT_EVENT is wrong? Events on Android and iOS only accept a single map (or null) as parameters, not primitive types like a double or a string. What would the example 
```
REACT_EVENT(AddEvent);
std::function<void(double)> AddEvent;
```
even do?

**Comment by vmoroz** [comment]
Let's not jump into conclusions like this. :) It works and works as any other RN event. The Event is just a function call with name "emit" that receives an array with two elements: the event name and the event argument. Thus, the argument can be of any type, not necessary object or null, but the argument is required.

Today we can write:
```
REACT_EVENT(AddEvent);
std::function<void(std::nullptr_t)> AddEvent;
```
And pass `nullptr` as a parameter.

The question is only here whether we should improve the null passing experience to avoid use of the  std::nullptr_t? Could you share some concrete examples where RN raises events without parameters? Are there cases when more than one parameter is passed?

The current `REACT_EVENT` implementation is based on my experience and understanding, but obviously, I may not be aware about all scenarios. :)

**Comment by vmoroz** [comment]
It always helps to see the source code...
I just found that based on the RN JS source code, the events may have 0..n parameters.
I will change the REACT_EVENT to support this contract.

File: node_modules\react-native\Libraries\vendor\emitter\EventEmitter.js 

 ``` JavaScript
 /**
   * Emits an event of the given type with the given data. All handlers of that
   * particular type will be notified.
   *
   * @param {string} eventType - Name of the event to emit
   * @param {...*} Arbitrary arguments to be passed to each registered listener
   *
   * @example
   *   emitter.addListener('someEvent', function(message) {
   *     console.log(message);
   *   });
   *
   *   emitter.emit('someEvent', 'abc'); // logs 'abc'
   */
  emit(eventType: string) {
    const subscriptions = this._subscriber.getSubscriptionsForType(eventType);
    if (subscriptions) {
      for (let i = 0, l = subscriptions.length; i < l; i++) {
        const subscription = subscriptions[i];

        // The subscription may have been removed during this event loop.
        if (subscription && subscription.listener) {
          this._currentSubscription = subscription;
          subscription.listener.apply(
            subscription.context,
            Array.prototype.slice.call(arguments, 1),
          );
        }
      }
      this._currentSubscription = null;
    }
  }
```

The `Array.prototype.slice.call(arguments, 1)` will pass all remaining arguments to the event handler after removing the event name that is the first element in the `arguments` array.

**Comment by benhamlin** [comment]
Awesome! And thanks for the source code, that is helpful.
