### ISSUE TITLE
REACT_MODULE wrong param has no collision detection? 

### ISSUE THREAD

**Issue by namrog84** [microsoft/react-native-windows#4407]
This has happened to me in the past, and just recently happened to a coworker.  
Simple mistake from bad copy/paste but quite unintuitive to diagnose. 

Example: 
We have 2 modules
```
// SomeModule1.h
REACT_MODULE(SomeModule1, L"Module1");
struct SomeModule1{
   ...
}
// SomeModule2.h
REACT_MODULE(SomeModule1, L"Module2");
struct SomeModule2{
   ...
```
Notice that both of them used SomeModule1 as the first param of REACT_MODULE

But what makes this really hard to diagnose, is you might be working on SomeModule1 the whole time, and keep looking at it and seeing nothing wrong, but you can't debug break into it either. 
Because you don't think SomeModule2 has anything to do with what you are working on so you never double check it.  But its somehow doing all the wrong things without any complaints. 
What is weird is that in this case, lots of things seemingly don't work right but nothing clearly is broken from the dev experience.

If the same struct is registered under 2 names, seems like this isn't ever a desired behavior?
Can this be detected/caught?  At least even in debug builds?

Its a super tricky to diagnose problem that anyone with larger code bases might run into.

**Comment by vmoroz** [comment]
I will investigate it.

**Comment by vmoroz** [comment]
I had investigated this issue last year and I did not find a solution that does not significantly increases the complexity. We will keep the current "not verifiable" approach unless there are more requests to address it from customers.
