### ISSUE TITLE
Need to specify `--template beta` when using adding RNW to a 0.61 app

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#4414]
We automatically add "vnext" tag when the version is >= 0.60.

However, 0.61 has the beta tag currently, and eventually, it will be removed.

Can we update the plugin CLI to automatically pick the correct 0.61 version instead of just erroring out?

**Comment by NickGerleman** [comment]
@jonthysell this is intentional, since we didn't want to allow people to use pre-release. This will be fixed imminently with having untagged  0.61 and the CLI changes currently out for PR to not append vnext to everything.

**Comment by NickGerleman** [comment]
See https://github.com/microsoft/react-native-windows/pull/4403
