### ISSUE TITLE
Playground CI Loop instability

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#4425]
Recently our CI loop has started to randomly fail while building the playground app.  ADO automation reported seeing this fail around 20 out of the last 120 runs.

Here's an example run that failed:
https://dev.azure.com/ms/react-native-windows/_build/results?buildId=69965&view=results

This is being discussed on Teams.  It appears we're running out of heap space due to using the 32-bit build tools instead of the 64-bit tools.

**Comment by NickGerleman** [comment]
This also affects publishes it looks like.

**Comment by jonthysell** [comment]
This has nothing to do with msbuild x32/x64. Looking at the logs, it failed WITH the x64 msbuild. A ReactUWP build just seemed to fail, but gave no errors.

**Comment by chrisglein** [comment]
@jonthysell With the recent attention on our CI loop how active is this particular instability? Previously it looked like 1/6 failed, but I don't know if we have more current information (and a lot has changed).

**Comment by kmelmon** [comment]
@jonthysell @chrisglein It looks like PR #4462 fixed this.  I don't see any more hits in recent CI loops.  Closing.
