### ISSUE TITLE
Support react-native-text-input-mask

### ISSUE THREAD

**Issue by giregk** [microsoft/react-native-windows#4443]
# Support `react-native-text-input-mask` on RNW

## Basic Info
- Module Repo URL: [link to repo](https://github.com/react-native-community/react-native-text-input-mask)
- Target version: 0.61
- [x] [Issue exists on module repo](https://github.com/react-native-community/react-native-text-input-mask/issues/154)
- [ ] Module has a Legacy/C# implementation

## Which app/customer is requesting this module?
All apps that need to work with date inputs, credit card inputs, and other inputs where a masked text input can help a lot to improve UX.

## In what scenarios will this module be used?
Credit card inputs, date inputs, phone number inputs, ...

## Essential Features
Masked text input with configurable mask.

**Comment by giregk** [comment]
I managed to do something in pure JS. It's not super performant and does not work with text selection, but it's usable. So this is not urgent for me. But if this development does happen someday, I'll definitely include it in my project.

**Comment by creambyemute** [comment]
Not sure how similiar this one is, it's view instead of TextInput, unfortunately used by React-Navigation:
https://github.com/react-native-community/react-native-masked-view

**Comment by stmoy** [comment]
@giregk - thank you for filing this request. The underlying WinUI platform doesn't have great support for text masking so it'd be difficult to achieve this in a performant way without changes in the underlying Windows platform.

I'm glad to hear you're unblocked, as it'll be difficult to achieve this in the short term.
