### ISSUE TITLE
TextInput not reflecting the correct text value

### ISSUE THREAD

**Issue by khetanashita** [microsoft/react-native-windows#4444]
### Steps to Reproduce

(Write your steps here:)
When the text prop update happens back to back quickly and programmatically (not via user interaction), the latest update request is ignored.

### Basic Triage

(Write what you thought would happen.)
The Js side gets updated as expected and an update is triggered to the native side as well, but I think it's ignored in the TextInputViewManager because of this condition:

```
else if (propertyName == "text") {
 if (m_mostRecentEventCount == m_nativeEventCount) {
   .
   .
   .
  }
} 
```

The event counts for native and javascript are out of sync. If I manipulate those values it updates correctly.

**Comment by chrisglein** [comment]
@ahimberg There's some history here with interactions with Redux that I'm told you might be aware of. Can you describe or link to a discussion about this?

@khetanashita Are you using Redux or something similar? Also, can we get more info on the repro so we can start working towards a standalone repro on this?

**Comment by khetanashita** [comment]
Yes we are using Redux. I was able to repro the issue using Samples/textinput.tsx in the playground app. The code looked something like this:

state = {
  testCounter: 1,
};

onPressChangeText = () => {
  var testCounter = ++this.state.testCounter;
  this.setState({testCounter: testCounter});
};

render() {
  console.log('Counter value: ' + this.state.testCounter);
  return (
    <View style={styles.container}>
      <TextInput
        style={styles.input}
        defaultValue={this.state.testCounter + ''}
      />
      <Button title={'Change text'} onPress={this.onPressChangeText} />
    </View>
  );
}

**Comment by chrisglein** [comment]
We did make some fixes here to address fast typing. So please give this a shake on latest, as we believe it to be fixed.
However it is possible there's additional problems given the indirection through Redux. If you still repro on 0.62 please let us know.

**Comment by creambyemute** [comment]
@chrisglein I've experienced the same problem on 0.63 as well as 0.64.

The following does not work/not reflect the value change in the textInput but works perfectly fine on Android/iOS:
```javascript
<React.Fragment>
    <TextInput value={this.state.quantity.toString()} />
    <Button
        onPress={() => {
            this.setState({
                quantity: this.state.quantity + 1
            });
        }}
    >
        Count up
    </Button>
</React.Fragment>
```

**Comment by chrisglein** [comment]
> ```js
> <React.Fragment>
>     <TextInput value={this.state.quantity.toString()} />
>     <Button
>         onPress={() => {
>             this.setState({
>                 quantity: this.state.quantity + 1
>             });
>         }}
>     >
>         Count up
>     </Button>
> </React.Fragment>
> ```

I tried to break your example into a Snack: https://snack.expo.io/Z77jwIshk. As in your fragment it's not assigning through to `onChangeText` so the `TextInput` won't actually be interactive.
The behavior I'm seeing for this fragment looks the same to me on iOS and Windows: I see the characters briefly as I'm trying to type, but in the end the driven value wins. Which is expected. Is there more to your repro that I'm missing?

**Comment by creambyemute** [comment]
@chrisglein I'm not typing into the TextInput. Only using the CountUp Button to change the value which does not work.
I simplified the example to exclude the onChangeText event because after actually typing into the TextInput the Count up button works as expected.

I'll setup a minimal repro in a fresh 0.64 init project tomorrow to ensure there are no other factor interfering. 
But the above example didn't work in our App on the LoginScreen which is Component-State driven (no mobx/redux).

**Comment by creambyemute** [comment]
@chrisglein Okay so I created two fresh inits, one for 0.63 and one for 0.64. I replaced the App.tsx content with the following:

```javascript
const App = () => {
  const [quantity, setQuantity] = React.useState<number>(0);
  return (
    <>
      <StatusBar barStyle="dark-content" />
      <SafeAreaView>
        <TextInput value={quantity.toString()} />
        <Button
          title={'Count Up'}
          onPress={() => {
            setQuantity(quantity + 1);
          }}
        />
      </SafeAreaView>
    </>
  );
};
```

I additionally recorded 2 small video showcases (mp4)  of the problem and added it to Google-Drive. You can watch it here:
* https://drive.google.com/file/d/1LRll1O-SYo8X8vj6QinKONegDNVdFAOt/view?usp=sharing
* https://drive.google.com/file/d/1ziNzS4bDwlwSFKP3ux1etNzGUXQkLs-s/view?usp=sharing

As you can see, the value shown by the textInput is not what it actually has registered as state. As soon as I type into the textInput it replaces the value with the correct one. After that, the count up button works.

**Comment by chrisglein** [comment]
Thanks for the detailed info @creambyemute! I've created a new issue for this (#7638) since this issue is closed and I don't want to confuse any of the >1 year old details with your fresh tasty info. Again, appreciate your diligence.
