### ISSUE TITLE
'Question: how is navigation handled in react-native-windows'

### ISSUE THREAD

**Issue by BenJeau** [microsoft/react-native-windows#4446]
I've tried React Navigation, searched through issues and StackOverflow posts without any success. 

How is navigation supposed to be handled in a react-native-windows application? Is it possible to use native navigation elements with UWP?

**Comment by chrisglein** [comment]
There are community modules for handling navigation, such as #3884 (there are others). These aren't implemented with the core platform, but added on top. Track that issue for status on that module.

Alternatively you may wrap native functionality on your own: https://microsoft.github.io/react-native-windows/docs/native-modules
However if you're going to take on something as complicated as, say, `NavigationView`, there may some limitations for authoring that kind of view manager.
