### ISSUE TITLE
'Question: [Unable to build release appx]'

### ISSUE THREAD

**Issue by nanduahmed** [microsoft/react-native-windows#4447]
I tried builing a release appx for sideloading with react native windows but getting following error 

Error
MSB3073
The command "      cd C:\Users\<user>\source\repos\appxtest\windows\..      react-native bundle --platform windows --entry-file index.js --bundle-output windows/appxtest/Bundle/index.windows.bundle --assets-dest windows/appxtest/Bundle    " exited with code 9009.

I am able to build a successful Debug appx. 
Could someone guide me how to build the release appx with react native windows 

When I enable verbose build " Tools > Option> Project and Solution > Built and run, and change "MsBuild project build output verbosity" to "Diagnostic"

I get this log 

7>C:\Users\<user>\source\repos\appxtest\node_modules\react-native-windows\PropertySheets\Bundle.Common.targets(13,9): error MSB3073: The command "
7>C:\Users\<user>\source\repos\appxtest\node_modules\react-native-windows\PropertySheets\Bundle.Common.targets(13,9): error MSB3073:       cd C:\Users\naveen\source\repos\appxtest\windows\..
7>C:\Users\<user>\source\repos\appxtest\node_modules\react-native-windows\PropertySheets\Bundle.Common.targets(13,9): error MSB3073:       react-native bundle --platform windows --entry-file index.js --bundle-output windows/appxtest/Bundle/index.windows.bundle --assets-dest windows/appxtest/Bundle
7>C:\Users\<user>\source\repos\appxtest\node_modules\react-native-windows\PropertySheets\Bundle.Common.targets(13,9): error MSB3073:     " exited with code 9009.

**Comment by mosamlife** [comment]
Install react-native CLI as a global dependency 

use this command: npm install –g react-native-cli
