### ISSUE TITLE
Populate "Lean Core Refactor" project board

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#4454]
This board:
https://github.com/microsoft/react-native-windows/projects/16

Should contain all the Components/APIs that are deprecated, and in which version, so that we know when to remove them from RNW. It's partial right now. This issue tracks filling in the table.

I'm not sure if there's a better single source for deprecations, but worst case we can manually diff the docs (and look for deprecation flags) and go from there:
https://reactnative.dev/docs/0.59/activityindicator
https://reactnative.dev/docs/0.60/activityindicator
https://reactnative.dev/docs/0.61/activityindicator
https://reactnative.dev/docs/activityindicator

**Comment by chrisglein** [comment]
Lean core refactor master issue - https://github.com/facebook/react-native/issues/23313 
Could perhaps use the linked issues from that one to see version numbers when each was moved out.

**Comment by chrisglein** [comment]
Note a board here isn't as important as answering this question: Are there upcoming lean core ejections that are going to impact that RNW that we need to anticipate? If there are modules we need to start adding Windows support it'd be good to know now rather than when the release is imminent. If through a manual review we find no cases of that then this issue is safe to close out (also close the project board).

**Comment by chiaramooney** [comment]
Currently, https://github.com/facebook/react-native has the following projects that were ejected to community modules but are still in core:
- Clipboard
- DatePicker
- Slider
- Sound

Currently, RNW has the following projects that were ejected to community modules but are still in the repo:
- DatePicker -> PR #7685 out now to remove DatePicker
- Picker -> Filed issue to track work item #8264 of removing. 

RNW is ahead of RN in removing ejected projects from their repositories. No incoming changes from Facebook anticipated that RNW has not already made. Closing Issue.
