### ISSUE TITLE
Glyph gets cut off at the bottom

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#4467]
RNTester

![image](https://user-images.githubusercontent.com/22989529/78093949-2c0cbc00-7388-11ea-8676-b89b963445ff.png)

red center glyph gets cut off

**Comment by chrisglein** [comment]
This may just be a bug in the test page. The second glyph is being given a different size from the first.

**Comment by tannersteele** [comment]
fix PR @ https://github.com/microsoft/react-native-windows/pull/5595
