### ISSUE TITLE
CLI should support standard typescript template

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#4505]
The react-native init CLI has a --template typescript option which installs an additional template directory with typescript app code in it.

react-native-windows doesn't currently support this template.  We should improve the windows CLI to support this.

**Comment by chrisglein** [comment]
If we're not writing any JavaScript files it seems like we should have supported this. We need to dig in and find out what we need to do to support this.

**Comment by chrisglein** [comment]
Could be a bug in the RN CLI, not our CLI. Needs some investigation.

**Comment by kaiguo** [comment]
Looks like they created a [react-native-template-typescript](https://github.com/react-native-community/react-native-template-typescript) community module for this, and we just need to run `npx react-native init MyApp --template react-native-template-typescript` instead. I created a PR to include this in our getting started doc.

**Comment by kmelmon** [comment]
@kaiguo I thought someone tried this and found it doesn't quite work, due to the directory structure created for the template.  Can you confirm?

**Comment by kaiguo** [comment]
@kmelmon yes, I tested on both RNW 0.61 and 0.62, they worked fine. The only caveat is you need to have right versions of cli and react-native-template-typescript module, which they mentioned in their [doc](https://github.com/react-native-community/react-native-template-typescript#arrow_forward-usage).
