### ISSUE TITLE
Drop legacyImplementation argument from IWebSocketResource::Make

### ISSUE THREAD

**Issue by JunielKatarn** [microsoft/react-native-windows#4509]
Remove the optional legacy implementation switch from `IWebSocketModule`'s factory method once the new implementation has been proven stable and the old one has been removed from the code base.

**Comment by chrisglein** [comment]
> Remove the optional legacy implementation switch from IWebSocketModule's factory method once the new implementation has been proven stable and the old one has been removed from the code base.

@JunielKatarn do you know the approximate timeline for when the old one is going to be removed?

**Comment by JunielKatarn** [comment]
My estimate is by the time Office May fork is released to  production.
