### ISSUE TITLE
Get managed unit tests running in CI

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#4515]
Thanks to #3838, the managed unit tests crash when compiled with .net native.

So right now, they build but don't run in the CI.

We should get as many of these tests running as possible, whether that means fixing the crashing tests or only running the tests in debug, etc.

**Comment by vmoroz** [comment]
@jonthysell , why we cannot run these tests without .Net Native as they were run originally? It would be better to run the tests in Debug mode without the .Net Native than not running them at all.

**Comment by jonthysell** [comment]
Well, it looks like Managed unit tests are explicitly not supported by .net native, because the unit test framework uses APIs that .net native doesn't support.

https://docs.microsoft.com/en-us/dotnet/framework/net-native/migrating-your-windows-store-app-to-net-native#visual-studio-differences

If you look at the build spew, even though it builds, it throws all kinds of warnings with APIs used that are hardcoded to throw NotImplementedExceptions.

I'm just going to disable .net native for the manged tests.

**Comment by jonthysell** [comment]
Even with .net native disabled, and the latest test infra, x64 release fails. Opening https://github.com/microsoft/react-native-windows/issues/4533 to track and moving on with what works.

**Comment by jonthysell** [comment]
Looks like you have to use the *.build.appxrecipe file as the target assembly, and use the pre-installed vstest (16.5, not the 16.6 from the installer)
