### ISSUE TITLE
Add support to client for --port parameter

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#4520]
When launching metro, there is a --port parameter which tells metro to listen for connections on a port other than 8081.  The client doesn't support this as it's hard-coded to always use port 8081.

We should add support for this.  The feature request is very similar to: https://github.com/microsoft/react-native-windows/issues/4316

Perhaps we can get @nasadigital to take this task as well.

**Comment by chrisglein** [comment]
Duplicate of #2586
