### ISSUE TITLE
Create a one-line command to install VS environment

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#4523]
As part of PR #4512, I'm updating the `Install-VSFeatures.ps1` to much more powerful in terms of installing VS components.

With the right list of components, there's no reason we couldn't create a "new dev environment" setup script, that calls `Install-VSFeatures.ps1` and installs everything necessary to build RNW.

Even if it can't "set it up from scratch", if the user already has some part of VS 2019 installed, the script would fill in the gaps.

**Comment by asklar** [comment]
@chrisglein @jonthysell this is covered by #4335

**Comment by asklar** [comment]
@jonthysell can we close this now or is there more to do?

**Comment by jonthysell** [comment]
Yes, we can close this.
