### ISSUE TITLE
https://nativebase.io/ third party component  support 

### ISSUE THREAD

**Issue by gsmental** [microsoft/react-native-windows#4526]

**Comment by chrisglein** [comment]
Hey @gsmental, we had never heard of NativeBase. This is super interesting. At first inspection this looks like how supporting expo modules can get you a great tooling experience, except perhaps with a different set of modules? Do you have certain ones that you're interested in? Or a min set that would unblock some scenarios here? We have an issue template for asking for Windows support for specific modules. It'd be great to hear more about your scenario.
