### ISSUE TITLE
Improve dev inner loop

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#4537]
Filing an issue to track assorted improvements to the inner loop (specifically the CLI with a focus on the experience for RNW engineers)

**Comment by chrisglein** [comment]
I'm all for it, but I want to make sure our issues are actionable. Looks like there's some info in the PR. Can you reflect more of that back here? This isn't terribly granular as is and I don't know what "done" looks like.

**Comment by asklar** [comment]
> I'm all for it, but I want to make sure our issues are actionable. Looks like there's some info in the PR. Can you reflect more of that back here? This isn't terribly granular as is and I don't know what "done" looks like.

I kind of filed this to have an issue to reuse and link to when making opportunistic changes like this one. Would you rather I file individual issues instead as I find them? wanted to reduce the noise :)
