### ISSUE TITLE
Add Microsoft.ReactNative.dll API into react-native-win32.dll

### ISSUE THREAD

**Issue by vmoroz** [microsoft/react-native-windows#4541]
# Task: Add Microsoft.ReactNative.dll API into react-native-win32.dll

## Summary
This is a step towards common Microsoft.ReactNative.dll for UWP and Win32 platforms. The react-native-win32.dll should have the new and old APIs for some time to let us move the MS Office code to the new APIs. After the conversion completed we must merge the Microsoft.ReactNative.dll and react-native-win32.dll.

## Motivation

There are several scenarios we would like to address:
- MS Office wants to use the new ABI-safe API offered by Microsoft.ReactNative.dll and changing all code in one move is not possible. We to do it in several steps and thus need the old and new APIs to co-exist.
- We want to have the sane Microsoft.ReactNative.dll shared for UWP and Win32 applications.

## Open Questions

- Would it be possible to share the same ReactNative instance between the old and new APIs?

**Comment by chrisglein** [comment]
Related to #4540 I assume.

**Comment by vmoroz** [comment]
@chrisglein, yes I am adding a number of tasks that are under the https://github.com/microsoft/react-native-windows/projects/33 project. It is a big change and want to be able to stage the implementation and be able to split it up between developers.

**Comment by Khalef1** [comment]
Closing this. @aeulitz  opened several different issues for different parts of this one.
