### ISSUE TITLE
Implement unit test project for Microsoft.ReactNative.dll

### ISSUE THREAD

**Issue by vmoroz** [microsoft/react-native-windows#4543]
# Task: Implement unit test project for Microsoft.ReactNative.dll

## Summary
We must have a unit test project that exercises the Microsoft.ReactNative.dll API. Ideally, it must be two unit test projects: one in C++ and another in C#. This will ensure that the Microsoft.ReactNative.dll API works correctly after any modifications.

## Motivation

- We must be able to evolve the Microsoft.ReactNative.dll API without fear of breaking changes.
- We must be able to refactor the internals of Microsoft.ReactNative.dll while keeping it functional.

**Comment by JunielKatarn** [comment]
Can existing project `React.Windows.Universa.UnitTests` be used for thi purpose? (It currently aims at testing `ReactUWP`).
