### ISSUE TITLE
Should we change Microsoft.ReactNative DLL name?

### ISSUE THREAD

**Issue by vmoroz** [microsoft/react-native-windows#4544]
The DLL name `Microsoft.ReactNative.dll` started from a prototype where this name probably was chosen because we must name our Nuget package starting with `Microsoft` prefix and to avoid naming conflicts with existing DLLs. We must decide whether we keep this name or change it to a name without the `Microsoft` prefix. E.g. `ReactNative.Windows.dll`.
Are there any guidance in that are someone aware of?

**Comment by chrisglein** [comment]
With sharing between UWP and Win32 code we may actually need 2 dlls. Which could be something like `Microsoft.ReactNative.Core` vs `Microsoft.ReactNative.Something` (obviously not the right names). So we need multiple names.

@stmoy Can you spend some time absorbing the options here, the rules, and create a proposal?

**Comment by stmoy** [comment]
After chatting with @vmoroz @acoates-ms - it doesn't seem like we should change the DLL names without a "smoking gun" reason to do so. Closing.
