### ISSUE TITLE
Generate and Publish Release Playground Appx as Part of CI

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#4558]
We've seen multiple issues before come time for someone to publish an app using our project. E.g. WACK validation, .Net Native incompatibilities, etc. We should ideally add coverage for this.

This intersects with an idea brought up by @FalseLobster around "productizing" our test apps (e.g. like Expo). Allowing easy consumption of examples, along with the ability to load trivial RN bundles can be useful to demonstrate the platform, provide simple JS repros, etc.

**Comment by chrisglein** [comment]
Linking related issue #4475 that's an example of why we'd benefit from this.

**Comment by NickGerleman** [comment]
The motivations behind this are mostly satisfied by the gallery app. Closing this.
