### ISSUE TITLE
[0.60] Roll back hard-code usage of BeastWebSocketResource in WebSocketModule

### ISSUE THREAD

**Issue by JunielKatarn** [microsoft/react-native-windows#4559]
While a destruction-related hang in `WinRTWebSocketResource` is investigated, `WebSocketModule` will use `BeastWebSocketResource` exclusively in branch `0.60-stable`.

Once the hang is fixed, re-enable using `WinRTWebSocketResource`.

**Comment by NickGerleman** [comment]
Looks like my earlier renaming of labels messed this one up. Removed "Backported to 0.60" since nothing happened there yet.

**Comment by JunielKatarn** [comment]
Resolved by #4561.
