### ISSUE TITLE
Create daily validation, separate (and more stringent) than the per-PR validation

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#4567]
For various reasons we need to reduce the amount of validation spent on each PR but still keep overall validation constant at a daily cadence. Over time this will enable us to add things to daily checks that we can't afford to do today.

Proposal from @jonthysell :
- On PR: Current PR yaml, but only x86 debug
  - Faster PRs, don’t need to run the whole suite for each PR iteration
- On Push: Current PR yaml, some/most/all flavors
  - Only happens when code actually gets pushed in, and we can still identify commits that broke other flavors
- Publish: Current publish yaml, but daily
  - Only do an all flavor build and publish once per day

Potential plan:
- [ ] Enable building/publishing nuget packages in parallel to what we’re already doing
- [ ] Create a new cli template (not the default) that consumes the package
- [ ] Update the RN init CI tasks to try that package-based template (including the just built as part of the CI nuget package, which is probably easier since we don’t need something like veradaccio)
- [ ] When we’re good and confident, switch the default cli template to package instead of source
- [ ] Maybe in some distant future, consider stop publishing native source to npm all-together

**Comment by NickGerleman** [comment]
I'm not sure that I agree with reducing PR coverage. We do often find platform specific issues before push time, and we have parallel builds which mitigates PR time. Doing work on push would add more delays as well, and would be more resource utilization than doing everything at PR time for the common case of a single commit PR. 

Parallel builds do use more resources, but there has been some goal to go from Pipelines to Github Actions, where we wouldn't share a pool with other teams.

Out of curiosity, what type of expensive operations were we wanting for daily builds? I'm all for adding extra coverage if something is so expensive that we couldn't do it as frequently.

**Comment by NickGerleman** [comment]
Removing the must-have tag from this one since it shouldn't block the 0.62 release based on the most recent discussion.

**Comment by chrisglein** [comment]
Not something we're able to push for in 62, so moving to 63. But this is important for a variety of business reasons. The goal is not at all to reduce coverage. It's to distribute the coverage differently. This actually opens up opportunity to have _more_ validation when we have a lower cadence validation loop (e.g. downlevel testing on various versions of Windows)

**Comment by jonthysell** [comment]
We have daily CI, this can be closed.
