### ISSUE TITLE
API docs for Microsoft.ReactNative

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#4569]
Documentation needed in light of #3853 

Paraphrasing @acoates-ms:
"We have docs on NativeModules and ViewManagers, but we don’t have any documentation on the brownfield APIs.  We don’t have any for ReactApplication either.  We need docs on our whole API surface.

If we have good docs on the new APIs, I think apps can potentially work out what they are trying to do, and how to rewrite their code, without migration docs for each bit of ReactUWP surface (which is a much messier and broad surface in many ways)"

**Comment by harinikmsft** [comment]
@stmoy  is working on this, but realistically may not have docs on the site before 0.62. Moving this to 0.63 milestone instead.

**Comment by stmoy** [comment]
First pass of API docs complete: https://microsoft.github.io/react-native-windows/docs/reactapplication-api
