### ISSUE TITLE
E2ETest failures need to fail the PR build

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#4577]
Recently we regressed the tests so that they do not fail the PR build. We now have failing tests that do not fail the PR build and we are regressing functionality.
Test pass with failed tests (PR build succeeded)
https://dev.azure.com/ms/react-native-windows/_build/results?buildId=73072&view=ms.vss-test-web.build-test-results-tab&runId=2230688&resultId=100002&paneView=debug

**Comment by chrisglein** [comment]
Adding some additional context from @asklar's comments elsewhere:

> I noticed today a couple of concerning things:
> 1.	The PR build has been having failing tests for a whole week
> o	Filed [E2E have been failing since around 4/2-4/3](https://github.com/microsoft/react-native-windows/issues/4579)
> 2.	Even if the tests fail, the PR build does not break which enables people to break the tests without knowing it.
> o	Azure Pipeline requires that a task set its exit code (errorlevel) to be non-zero for it to be considered failed
> o	Running yarn e2etest does NOT set the process exit code.
> o	I’ve filed E2ETest failures need to fail the PR build (#4577, aka this issue)
>
