### ISSUE TITLE
E2E have been failing since around 4/2-4/3

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#4579]
Need to get those tests back up:
![image](https://user-images.githubusercontent.com/22989529/79122532-bd970900-7d4c-11ea-82b4-31ed08ee1bb6.png)

**Comment by chrisglein** [comment]
Would be more helpful if this issue listed specific tests, or had a link to the failures. For example, Jon mentioned that one of these is known and tracked:

> The other test, meaureLayoutTest, has already been captured here: https://github.com/microsoft/react-native-windows/issues/4122. I already spent almost two weeks trying to debug the optimized yoga code and not making any headway. Something is being optimized and causing a problem where padding doesn’t calculated properly only on release x64 bits.

The other issue had [this link](https://dev.azure.com/ms/react-native-windows/_build/results?buildId=73072&view=ms.vss-test-web.build-test-results-tab&runId=2230688&resultId=100002&paneView=debug). That points to `ControlStyleTestWithRegularBorder` and friends failing.
https://dev.azure.com/ms/react-native-windows/_build/results?buildId=73072&view=ms.vss-test-web.build-test-results-tab
Specifically:
- ControlStyleTestWithRegularBorder_2
- ControlStyleTestWithRoundBorder
- ControlStyleTestWithRegularBorder
