### ISSUE TITLE
Add SourceBundleHost and SourceBundlePort to ReactInstanceSettings

### ISSUE THREAD

**Issue by Thristhart** [microsoft/react-native-windows#4582]
`DeveloperSettings.SourceBundleHost` and `DeveloperSettings.SourceBundlePort` are passed to the client JS for HMR, and default to localhost:8081 when these values are not set.

There isn't currently a way to set those values from ReactApplication, which makes it difficult to take advantage of Fast Refresh while developing on remote clients (such as an Xbox). Adding them to ReactInstanceSettings would enable that functionality.

**Comment by rectified95** [comment]
@Thristhart I believe the required functionality is being added in this PR, can you confirm?
https://github.com/microsoft/react-native-windows/pull/4979/files

FYI @chrisglein

**Comment by Thristhart** [comment]
@rectified95 confirmed, that's what I'm looking for!

**Comment by rectified95** [comment]
Closing as duplicate.
FYI @chrisglein
