### ISSUE TITLE
Verify that the updated masters are correct 

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#4589]
We weren't failing the PR/CI builds when tests failed. As a result the output xaml tree has drifted from the masters we once had. I've changed the masters to match what we output now (i.e. re-baseline), but component owners should verify that the behavior the masters describe is the one we want, and if not, fix the code (and push new masters). The differences were mostly around sizes and colors of elements - but one that stuck out to me was that ImageRTL has FlowDirection=LeftToRight, I'm not sure how it's _supposed_ to work but hopefully someone does :)

**Comment by chrisglein** [comment]
Apparently that example (the RTL one) is correct, as the image shouldn't be flipped.
The color ones are worth investigation.

**Comment by chrisglein** [comment]
Worth investigating:
- Control size differences
- Scaling differences #4619 
- Differences depending on release/flavor #4122 

Accent color has been handled.

Let's get to an itemized list here with issues tracking each.
