### ISSUE TITLE
Integrate With New 0.62 View Events

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#4592]
0.62 added:
- BlurEvent,
- FocusEvent,
- MouseEvent,

MouseEvent directly overlaps with our special version. It seems like these might not actually be implemented to do anything in OSS RN right now though? Followup investigation is needed.

**Comment by chrisglein** [comment]
These don't appear to be in the docs: https://reactnative.dev/docs/view
@kikisaints you've been interacting with FB over the Pressable API - why were these ones not added to the docs? Is it on a list that hasn't been updated?
@harinikmsft This seems like something we should raise in the next sync.

**Comment by harinikmsft** [comment]
@NickGerleman , @kmelmon - would one of you be able to unearth the actual commits that brought these changes in? Per the latest sync, it is not clear whether these events are fully baked and why they were introduced. 

Given the ambiguity on this and the fact that they are net new (non-breaking for windows apps), we should be ok to reconcile after 0.62 preview is ready. Moving to next milestone.

**Comment by NickGerleman** [comment]
https://github.com/facebook/react-native/commit/95158ec692f6d72c69fe81a6f601417a10fb99a2

**Comment by kmelmon** [comment]
Thanks Nick. The commit was done in October 2019, well before we started reviewing the changelogs, so this explains why we were unaware of the change.  @harinikmsft I do think it would be good to circle back with facebook folks, it may require a one-off meeting.

**Comment by chrisglein** [comment]
@harinikmsft does this tie in with the keyboard work we're doing? Seems important to partners (can you confirm and tag as appropriate), but also is it necessary for 0.63? May be appropriate to break this into separate issues.

**Comment by harinikmsft** [comment]
Pinging @TheSavior - can you share some additional context for these events that seem to have been introduced during 0.62? 

These did not come up in the review of keyboard/focus API [docs](https://github.com/microsoft/react-native-windows/pull/5590). Are these relevant to consider for all platforms?

**Comment by harinikmsft** [comment]
Confirmed with React Native team that these APIs are not being used anywhere and can be ignored (do not integrate in RNW at this time). The RN team is aligned that these should be revisited as part of the focus/pointer APIs that are getting designed in the RNW repo at this time and reconcile with web APIs as makes sense. 

Closing this issue and linking to other relevant feature requests for book keeping: #2099 , #5706
