### ISSUE TITLE
Reimplement Keyboarding Behavior on top of Pressability 

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#4598]
We had previously patched Touchable to support activation by pressing down on spacebar, enter, or the gamepad "A" key. This code was rewritten in 0.62 with the introduction of Pressability. We need to reimplement our patches here. We should ideally make this change upstream as well, but we likely don't have enough keyboarding changes there yet.

**Comment by chrisglein** [comment]
Obviously un-breaking controller and stuff is top priority (labeling must-fix). Upstreaming the changes would be good but isn't necessarily on the same timeline. Feel free to split out a separate issue for that.

**Comment by NickGerleman** [comment]
Dropping this for now because I don't have the bandwidth to look at both this and the OOM issues preventing developers from building the app at the same time.

Clarified the title of this issue, since this requires a new implementation for 0.62 instead of straight mechanical work. Marking for discussion.

**Comment by NickGerleman** [comment]
Jumping back onto this. Don't remember why I took the triage tag off of this one...
