### ISSUE TITLE
Perform Detailed Comparison of RNTester Between 0.61 and 0.62

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#4599]
We did something of a smoke test during the upgrade, where we can tell that most things work and a few don't. We still need to do some in-depth manual testing to catch less obvious regressions the merge may have added.

**Comment by chrisglein** [comment]
Related future task that may be relevant for making this easier in the future: #4037

**Comment by NickGerleman** [comment]
Played with everything I could think of. Filed bugs based on results.
