### ISSUE TITLE
Support the Backhandler React Native API

### ISSUE THREAD

**Issue by DrewHiggins** [microsoft/react-native-windows#4606]
# Proposal: Support the Backhandler React Native API on Windows

## Summary
React Native has a [Backhandler API ](https://reactnative.dev/docs/backhandler) that detects when the user presses the hardware back button on Android and tvOS devices and calls listeners that subscribe to it. Having support for this in Windows with the various input methods for back navigation (mouse button, Xbox controller B button, etc.) would be useful.

Currently, this API is scaffolded out with empty functions and TODOs, but no open issue is tracking it (the [last issue ](https://github.com/microsoft/react-native-windows/issues/2021) I could find was from the last version of RNW based on .NET).

## Motivation

Users expect native Windows app to support mouse back button, and the JS/web APIs for detecting it aren't great, since the browser would normally handle back button behavior. The [UWP documentation also recommends ](https://docs.microsoft.com/en-us/windows/uwp/design/basics/navigation-history-and-backwards-navigation?redirectedfrom=MSDN#code-example) that apps implement support for common back inputs.

## Basic example

```javascript
import { BackHandler } from 'react-native';
// ...
BackHandler.addEventListener("hardwareBackPress", this.props.onBackRequested);
```

**Comment by chrisglein** [comment]
@DrewHiggins Thanks for reporting this. We're trying to get better about proactively detecting these gaps, but it helps to be poked. Do you have a timeline for when you need this?

**Comment by DrewHiggins** [comment]
@chrisglein Not urgently, we have a fix in our codebase to fire the correct event for the time being. 

I have a PR open (https://github.com/microsoft/react-native-windows/pull/4623) to integrate something similar to this project as well.
