### ISSUE TITLE
Pull out Picker as Part of Lean Core

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#4611]
As of 0.62, Picker shows deprecation messages, as it has moved to the community repo. We should implement our version there as well. https://github.com/react-native-community/react-native-picker

**Comment by chrisglein** [comment]
Plan was that @kaiguo was going to handle this as part of his Picker tasks. Although it could be separately because they are two pieces of work (different PRs).

**Comment by chrisglein** [comment]
Picker task: #3036.

**Comment by NickGerleman** [comment]
I took a closer look at that PR, and it's doing something right now that will cause crashes in 0.62 (it's sharing ViewManager names with the built in module).

@kaiguo have we been renaming modules/components in other PRs? If not we will need to fix those. It could lead to using the wrong native code, but 0.62 will actually immediately assert if we ever call requireNativeComponent on the same view manager twice.

**Comment by NickGerleman** [comment]
In general though it might be worth testing out community modules for 62 before we release it, since it's not quite in the test matrix while upgrading.

**Comment by kaiguo** [comment]
@NickGerleman the community module implementation is not checked in yet so I'll go and rename it to be safe.

**Comment by NickGerleman** [comment]
I took a quick look and it seems like webview had the same issue. That one is less worrying though, so long as we also made sure to validate against a version where the builtin view manager was completely removed.

**Comment by kaiguo** [comment]
Picker is still in RN core, https://github.com/facebook/react-native/blob/master/Libraries/Components/Picker/Picker.js, 
need to wait for it to be removed before pulling it out from RNW.

**Comment by NickGerleman** [comment]
Remaining work tracked here is for removal, which will happen automatically once we hit the build where FB removes Picker. Closing this issue.
