### ISSUE TITLE
Implement Slider

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#4612]
As of 0.62, Slider shows deprecations warnings in favor of the community module. We should implement our version there: https://github.com/react-native-community/react-native-slider

**Comment by chrisglein** [comment]
@stmoy another to add to your community module board.

**Comment by rectified95** [comment]
@NickGerleman I actually think this issue should be named 'Implement Slider', since we don't really an implementation in this repo. Even though we do have the SliderViewManager, not only does it not implement most of the props and events of the RN Slider, we lack the JavaScript implementation to use it. (this can be seen when looking at the SliderExample from ReactCopies, which don't inlcude in our RNTester examples). 
@chrisglein I could implement this module.

**Comment by NickGerleman** [comment]
@rectified95 we shouldn't need any custom JS. We already have `Slider.js` shared between platforms upstream https://github.com/facebook/react-native/blob/master/Libraries/Components/Slider/Slider.js That JS getting included is actually what led me to discovering this. We will Yellowbox in RNTester from including it. I would guess the community module would also share this.

I wonder if there was some necessity of an implementation to run RNTester, and we did a quick and dirty ViewManager to make it happy. If what we have is broken, maybe it's not too important to move this out.

**Comment by NickGerleman** [comment]
Yeah, I think that component does have a require-time dependency on the native component. It seems quite possible a ViewManager was added to prevent red-boxing but wasn't properly implemented.

**Comment by Sharcoux** [comment]
Well... For those in need, you can use `npm i @sharcoux/slider` that should solve the issue (and some other issues from this project)

**Comment by rectified95** [comment]
We tend to add support module in the react-native-community domain, rather than ones created by individuals. My PR is already out with a new native implementation for the Slider recommended by Facebook.

**Comment by Sharcoux** [comment]
I agree, but the current implementation brings some issues and the "officiel" project doesn't seem very reactive on most of them...

**Comment by rectified95** [comment]
FYI @NickGerleman The PR just got merged.
