### ISSUE TITLE
Image does not call onLoad when initialized from base64 inline data

### ISSUE THREAD

**Issue by mtalley** [microsoft/react-native-windows#4616]
### Environment

1. `react-native -v`:

react-native-cli: 2.0.1
react-native: 0.60.6

2. `react-native run-windows --info`:

  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
    Memory: 16.44 GB / 31.94 GB
  Binaries:
    Node: 10.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.13.0 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.6 => 0.60.6
    react-native-windows: 0.60.0-vnext.155 => 0.60.0-vnext.155
  Installed UWP SDKs:
    10.0.16299.0
    10.0.17763.0
    10.0.18362.0

- Target Platform Version(s):
10.0.18362.0

- Target Device(s):
Desktop

- Visual Studio Version:
Visual Studio 2017

### Steps to Reproduce

1. Initialize an `Image` component with an inline data source (using the data: uri scheme)
2. Set an onLoad callback
3. Run

### Expected Behavior

onLoad is called when the image finishes loading the data stream

### Actual Behavior

onLoad is never called (whereas it does get called for images loaded from a "normal" URI)

### Reproducible Demo

https://snack.expo.io/@mtalley/imageloadcallbacks

**Comment by chrisglein** [comment]
@marlenecota Are there any known issues here with inline data? I know that's pretty recent. In fact, this was reported on 60... is there maybe payload in 61 that could fix this?

**Comment by chrisglein** [comment]
Not something we plan to address on the Paper renderer as we move towards Fabric.
Fabric API completion for `Image` tracked here: https://github.com/microsoft/react-native-windows/issues/11144
Fabric will not use XAML for the fundamentals here, so this isn't necessarily applicable.
