### ISSUE TITLE
RNW has hardcoded MS Office paths in AsyncStorage

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#4618]
Since RNW is a platform, it should be agnostic to how apps like Office store their data.

vnext/Shared/AsyncStorage/StorageFileIO.cpp

![image](https://user-images.githubusercontent.com/22989529/79399861-4f636980-7f39-11ea-9f65-2ad8cee12a89.png)

**Comment by NickGerleman** [comment]
Oh wow. That's kind of horrifying, especially since Office doesn't actually use the RNW builtin implementation of Asyncstorage.

Id be tempted to switch the internal Asyncstorage to always uses @htpiv's new version. We can't use the community module in the repo, but whatever existing implementation we've had is pretty bad.

**Comment by NickGerleman** [comment]
Switching is a breaking change though, unless we have whatever builtin migration logic. @asklar is this path actually used anywhere? It's likely an artifact of a time long ago when this code lived in the Office monorepo and a couple teams were a bit liberal in how they changed it.

**Comment by htpiv** [comment]
Yeah, I think the right thing to do migration-wise is:
1. Get the community module version done
2. Whenever AsyncStorage drops out of core, delete our icky core version.

@NickGerleman, my recollection from when I wrote ALS was that this ugly path code wasn't compiled into ReactUWP, and instead only showed up in react-native-win32.dll. It's still definitely horrifying code... for rnw32.dll we ought to kick ALS out of the DLL and use our own version of the community module that uses the version of sqlite3 in Office (which could just be winsqlite3 once our min Windows version is high enough). If we did that, then we could delete this code.

If this code is somehow getting into react.uwp.dll, or Microsoft.ReactNative, that's bad and we should definitely not do that!

**Comment by NickGerleman** [comment]
Office has a completely custom version of win32 AsyncStorage in devmain anyway. If there's anything react-native-win32 specific right now we should just remove it.

Asyncstorage hasn't been pulled out of core yet in FB master for unknown reasons. I agree though that the community module should be the eventual goal for all platforms. There's work being done to move Office to Microsoft.ReactNative,but we'll need to figure out things like distribution still.

**Comment by chrisglein** [comment]
@kaiguo is working on adding AsyncStorage to the community module: #2271 .
I'm a little confused about the comments that this exists in FB master even though it's been deprecated. Is the code there but the API is not exposed? Is it used internally?
I was assuming that with @kaiguo 's task that he would just delete whatever AsyncStorage code we had in RNW.

**Comment by NickGerleman** [comment]
The API is still exposed. It's slated for removal but hasn't been removed yet, and some internal bits like RNTester still rely on the built in nodule.
