### ISSUE TITLE
Scaling is wrong in RNW, possible Yoga issue

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#4619]
Run e2etest Release x64 on 200% DPI, and the RenderSize for different elements will be different than the masters. The masters represent the sizes in the lab which are running at 1024x768 @ 100%

**Comment by acoates-ms** [comment]
Yoga seems to have issues on release ever since we moved to 142 toolset.
#4122

**Comment by asklar** [comment]
Need to verify whether this is applicable after the fix to #4122

**Comment by chrisglein** [comment]
What's the visible result of this? Do we have some screenshots?
How are we applying the scale factor to yoga and what is it doing with it?
