### ISSUE TITLE
为什么放弃JSC.exe

### ISSUE THREAD

**Issue by a4646054** [microsoft/react-native-windows#4633]
jsc.exe 非常不错，就是文档少到几乎没有！虽然jsc 是JSript，但是在此基础上作扩展支持更多的javascript特性不好吗？jsc不但可以写桌面应用，还可以写服务器端应用！在不使用nodejs的情况下！

**Comment by chrisglein** [comment]
Here's our attempt at a machine translation (sorry if it's wrong):
> Why give up jsc.exe ?
jsc.exe is very good, but there are so few documents! Although jsc is JSript, is it bad to expand on this basis to support more JavaScript features? jsc can not only write desktop applications, but also server-side applications! Without using nodejs!

The goal of React Native for Windows is to build upon the decisions already made by React Native, so this is out of scope for us.
