### ISSUE TITLE
'Question: Is React Native for Windows and Mac supported on WSL 2?'

### ISSUE THREAD

**Issue by gulshanmudgal** [microsoft/react-native-windows#4637]

**Comment by chrisglein** [comment]
In general the only supported development environment for React Native for Windows today is Windows, however this is a great question. We'd certainly like WSL to be an option. Let us do some poking around and get back to you.

**Comment by gulshanmudgal** [comment]
> In general the only supported development environment for React Native for Windows today is Windows, however this is a great question. We'd certainly like WSL to be an option. Let us do some poking around and get back to you.

I have created a feature request if you could look at it, would be great.

**Comment by NickGerleman** [comment]
React Native for Windows is pretty coupled to Windows specific build tools, and React Native for Mac is pretty coupled to Mac build tools. Neither of these can be run from WSL. I can't think of a way it would be possible to accomplish this unfortunately.

**Comment by NickGerleman** [comment]
Leaving the discussion issue open if there's any interest in followup discussion. Closed this original issue for now.
