### ISSUE TITLE
UWP app crashes on loading sample RN app from local bundle

### ISSUE THREAD

**Issue by NandhiniVishwanath** [microsoft/react-native-windows#4639]
The sample RN app is crashed while running a local bundle.

**Environment**
1.	react-native -v : react-native-cli: 2.0.1, react-native: 0.61.5
2.	npm ls react-native-windows: react-native-windows: 0.61.2
3.	npm ls rnpm-plugin-windows: rnpm-plugin-windows@0.6.1
4.	node -v : 12.12.0
5.	npm -v : 6.11.3
6.	yarn –version : 1.21.1
•	Target Platform: UWP
•	Target Platform Version(s): 10.0.18362.0 (min: 10.0.10586.0)
•	Target Device(s): Desktop
•	Development Operating System: Windows Build 17763
•	Visual Studio Version: Visual Studio 2017
•	Build Configuration: Debug x64

Steps to Reproduce
1. Build app with command react-native start.
2. Run the App from Visual Studio 2017
3. Wait for the JS bundle to be loaded from the packager.

**Expected Behavior**
The Root React Component should be rendered.

**Actual Behavior**
The app crashes with the following error:
Exception thrown at 0x00007FFCF6E49179 (KernelBase.dll) in project61Latest.exe: WinRT originate error - 0x80072F78 : 'The server returned an invalid or unrecognized response'.
Exception thrown at 0x00007FFCF6E49179 in project61Latest.exe: Microsoft C++ exception: winrt::hresult_error at memory location 0x000000521E1FDDA8.

**Comment by chrisglein** [comment]
The `react-native start` command should launch Metro bundler. Was Chrome launched when this happened?
How much app logic is here? Was this just a starting app and you hit this, or with something more established? (i.e. is there a repo with a repro you can share?)
We'd probably want more detail on that WinRT originate exception (inner callstack) if you're comfortable getting that.
