### ISSUE TITLE
Clean up how RNTester gets copied

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#4648]
https://github.com/microsoft/react-native-windows/blob/ae37f8e7518f808116ce906a7f7b32f00412612d/vnext/just-task.js#L51

Today RNTester gets "built" by overlaying the content of \vnext\src\RNTester\ with \vnext\ReactCopies\RNTester, into \vnext\RNTester

however these two copies happen as part of two parts of the yarn build process
 
vnext/just-task.js
```
task('copyFlowFiles', () => {
  return copyTask(['src/**/*.js'], '.');
});
task('initRNLibraries', () => {
  require('./Scripts/copyRNLibraries').copyRNLibraries(__dirname);
});
```

vnext/Scripts/copyRNLibraries.js
```
 copyDirectories(reactNativeWindowsPath, baseDir, [
    {
      src: 'ReactCopies/RNTester',
      dest: 'RNTester',
    },
```

**Comment by NickGerleman** [comment]
This is any JS source. Not just RNTester.
