### ISSUE TITLE
New RNW app project doesn't include JS/JSX code

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#4651]
create a new RNW app by following the getting started guide

the resulting app vcxproj doesn't include the react native JS/JSX code for the app, we should include this and a README. Link to it from AppRegistry.

(@rectified95 ran into this today)

Mention this in #4265

**Comment by acoates-ms** [comment]
I'm not clear on what the issue here is.

`react-native init` doesnt' have a vcxproj.  Assuming you are talking about the whole init process for a react-native-windows app.  That doesn't include some js code for the default new app screen.

**Comment by asklar** [comment]
@acoates-ms yes, I'm talking about the scenario a new RNW developer like Igor runs into which is: I follow the steps in the getting started guide, now what? where do I put my react code?
Just like creating a new project in VS gives you a hello world or makes it clear where your code should go, we should do the same for a new app from the CLI

**Comment by chrisglein** [comment]
At the very least it seems like the App.js file should be linked into the generated VS solution. I think effectively today most app developers use VSCode to edit their JS, but there's no reason you shouldn't be able to use VS and it seems like linking that App.js file will help with that.
