### ISSUE TITLE
Unable to Consistently Build React Native Windows Apps on Machines with Less Than 32GB of RAM

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#4652]
We previously saw CI instability due to running out of memory during PCH generation. This is showing up on home machines with less than 32GB of RAM. On a home machine with 16GB of RAM I was unable to consistently build React Native Windows, often needing to close all background programs to get the build to pass. This seems to be affected by physical memory, instead of available pagefile space.

We previously thought this might be related to x64 vs x86 compiler toolchain, but upgrading physical memory resolves the issue, which seems to disprove that theory.

Possible resolutions are reducing PCH size or changing compiler flags. This could impact build perf (needs to be measured).

**Comment by chrisglein** [comment]
How do we know this is an OOM issue? Do we have any error codes or diagnostics? Or is this some sort of tool chain flakiness? Can we get the error message?

Is there any pattern to this? Machine under load?

Should we switch the PR builds to use x64 so we can use x64 across the board (which would help with heap issues)?

@NickGerleman Can you add some more data?
@kmelmon It sounds like you've hit this before too. Next time you hit add info to this issue?

**Comment by NickGerleman** [comment]
```
##[error]c1xx(0,0): Error C3859: Failed to create virtual memory for PCH
c1xx : error C3859: Failed to create virtual memory for PCH [d:\a\1\s\vnext\ReactUWP\ReactUWP.vcxproj]
  c1xx: note: the system returned code 1455: The paging file is too small for this operation to complete.
  
  
  c1xx: note: please visit https://aka.ms/pch-help for more details
```

The pagefile part seems to be inaccurate, as the issue goes away with changes to physical memory, even when a large pagefile is present.

E.g. on my home machine the difference between 16GB and 32GB meant unreliable vs reliable builds. Anecdotally someone else working on RNW mentioned they weren't able to get the project to consistently build on their home machine.

**Comment by NickGerleman** [comment]
This is hitting more developers internally who are unable to build the project. x64 toolset does not seem to help. Marking for retriage and starting work to cut down our PCH, since it's blocking development.
