### ISSUE TITLE
RNW msbuild projects are not set up for multiproc builds 

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#4654]
https://github.com/microsoft/react-native-windows/blob/ff6f8f57587f7364143a701ef6637039b6643cf4/vnext/local-cli/runWindows/utils/msbuildtools.js#L56

We need to survey our projects to correct the inter-project dependencies so that we can enable multi proc builds

**Comment by chrisglein** [comment]
Need to enable the feature in the projects, and then fix up some project references in response to whatever unreliable results result from unclear sequence dependencies.
Could improve build time significantly.

**Comment by JunielKatarn** [comment]
@asklar Can you elaborate on this?
Isn't the `/m` switch for `MSBuild.exe` enough to make the builds happen in parallel using separate processes when possible?
