### ISSUE TITLE
Custom Views sample in RNTester crashes

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#4655]
Start Playground
Click the 4th option (Custom View - "example of custom view managers")

![image](https://user-images.githubusercontent.com/22989529/79859142-695fda80-8385-11ea-9efa-b4e27804f586.png)

**Comment by NickGerleman** [comment]
FYI, I've been trying to keep our list of examples in sync with iOS + Android during upgrades when they add new things. It's possible some new stuff we haven't implemented crashes, rather than any specific regression. Do you know if this example was part of 0.61?

**Comment by asklar** [comment]
@NickGerleman I don't know if it was working before or not, I just noticed it crashes on master today.

**Comment by NickGerleman** [comment]
This reproes in 0.61-stable.

![image](https://user-images.githubusercontent.com/835219/80171460-5294d000-859f-11ea-9fd3-58acccaa7288.png)

**Comment by NickGerleman** [comment]
Removing the must-have tag from this since it reproes in 0.61. If we're missing a view manager required for the example page it's likely this has never worked.
