### ISSUE TITLE
Remove personal branches from the react-native-windows repo

### ISSUE THREAD

**Issue by vmoroz** [microsoft/react-native-windows#4661]
To keep the repo size smaller we must adopt a style where all personal branches are in user's forks.
Currently our repo seems to have several personal branches.
Could we ask developers who created them to move them to their personal forks and delete them in the https://github.com/microsoft/react-native-windows repo?

These are the user branches that I see today (4/21/2020):
https://github.com/microsoft/react-native-windows/tree/adewar/PersonaCoinSize
https://github.com/microsoft/react-native-windows/tree/officedev/junefork-backportopenssl
https://github.com/microsoft/react-native-windows/tree/user/asklar/docMD
https://github.com/microsoft/react-native-windows/tree/user/asklar/mappedProperties
https://github.com/microsoft/react-native-windows/tree/user/asklar/smallmap

@Dewsk, @JunielKatarn, @asklar, could you have a look if these are your branches and if you could  delete them.

**Comment by chrisglein** [comment]
Did another audit, and got all of the above cleaned up.
