### ISSUE TITLE
Update vnext/readme.md to match latest in root readme.md

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#4671]
> @chrisglein what is the action remaining on this task? Are we trying to keep a manual copy of the main read me in the vnext/readme so the npm feed picks up the right thing until #4632 is done?

Until we have an automated process for updating the vnext/readme (#4632) it seems like we need to keep it up to date - snapping to whatever content is in the main readme.

But as for what is the actionable item here... it agree it's too muddy. I believe all that's left is snapshotting the vnext readme with what's in the root. I'll create a unique issue to track that so we can close out this one.

> We should really not even have a vnext folder (perhaps rename to source) and just have npm feed pick up from the main landing page like all other repos do.

Yes to restructuring the folders. That's #3748.
Perhaps if that happens we don't need to do the above propagation of the readme. @jonthysell do you have thoughts on the ideal directory structure? Does it still involve living in a packages subfolder (in which case propagating the readme is still necessary)?

_Originally posted by @chrisglein in https://github.com/microsoft/react-native-windows/issues/4264#issuecomment-617464036_

**Comment by acoates-ms** [comment]
#4632 will take care of this for master.  We should do the manual update on the 0.62-stable branch though.

**Comment by chrisglein** [comment]
@harinikmsft believe this was addressed with your PR. Closing.
