### ISSUE TITLE
Update react-native-webview with ViewManager API Changes Once 0.62 Preview Released

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#4679]
react-native-webview uses view manager commands, whose APIs change in 0.62 from https://github.com/microsoft/react-native-windows/pull/4667

We need to update it for compatibility with 0.62 once we have a preview released that the package can target.

**Comment by chrisglein** [comment]
There was a breaking API change here in 0.62, and we will need to update WebView to match.
@NickGerleman is there a Windows-specific change here, or something across all platforms? If it's the latter then this should just be part of updating to 0.62 for all platforms, no need to track here. Is this breaking or we'll want to update at some point?

**Comment by NickGerleman** [comment]
@chrisglein there was a Windows specific breaking change with 0.62 but it looks like react-native-webview isn't updated to 0.62 in general yet.

**Comment by NickGerleman** [comment]
Awesome to see this checked in!
