### ISSUE TITLE
borderColor draws black by default on all other platforms, but draws transparent on Windows

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#4682]
I noticed this while debugging RTL issues...

See this snack:
https://snack.expo.io/PJTPipoRS

Notice the outer border, which has border thickness but no borderColor pop set, draws a black border.  It draws black on all platforms supported by Snack.

On react-native-windows, the border draws transparent (but does take up layout space).  This inconsistency is bound to cause problems for xplat code.

I'm not sure if we should default to black, or a brush that's guaranteed to contrast against the default theme.  Needs a bit of investigation.

**Comment by chrisglein** [comment]
Need to have the right default here that matches the other platforms (and perhaps cares about light/dark theme).

**Comment by acoates-ms** [comment]
https://github.com/facebook/react-native/blob/a4b15a4a8821181cf272775188d0006f899d6b9f/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewBackgroundDrawable.java#L48

This appears to be the android default.

**Comment by kmelmon** [comment]
This looks like a super easy fix, and is needed before fixing #4678.  I'll take this.
