### ISSUE TITLE
Windows Custom RNTester Pages Do Not Work Well in Dark Mode

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#4688]
When not using Chrome debugging, RNTester will apply a theme based on system appearance. Our examples need to be updated to consume this theme, as they currently will not show up correctly in dark mode.

![image](https://user-images.githubusercontent.com/835219/80053253-535f3080-84d1-11ea-914a-046e9815d402.png)

**Comment by NickGerleman** [comment]
This only seems to affect a couple of pages.

**Comment by chrisglein** [comment]
These pages should be updated to use PlatformColor, as a real app would.

**Comment by NickGerleman** [comment]
In 0.62 Facebook added a ThemeContext based on the `useColorScheme` hook for RNTester examples to set a stylesheet. I think most things "just work" if they don't override the background color or anything.
