### ISSUE TITLE
Image page in RNTester hits runtime assert

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#4691]
The page uses Image's resizeMode = repeat which is not currently supported and asserts in Debug builds. See #2111. 

Results: the app crashes (no redbox, just a hard crash)

**Comment by NickGerleman** [comment]
We had this as a bug for a while, but it looks like @jonthysell fixed it https://github.com/microsoft/react-native-windows/issues/3738?

**Comment by NickGerleman** [comment]
Seems like there were seperate issues with the image example. I wonder if resizeMode is new.

**Comment by NickGerleman** [comment]
resizeMode "repeat" has been around for both Android + iOS since 0.56. @jonthysell do you know if the RNTesterExample page was working after your change? I assumed it was still broken during 0.62 validation.

**Comment by NickGerleman** [comment]
Confirmed this reproes in 0.61-stable.

**Comment by chrisglein** [comment]
Created card (will upgrade to issue) for missing mode: https://github.com/microsoft/react-native-windows/projects/18#card-37114262
This should be a yellow box error, not an assert.
Should hook up unimplemented property to do that.

**Comment by acoates-ms** [comment]
This is how you show a yellowbox from native:
instance->CallJsFunction("RCTLog", "logToConsole", folly::dynamic::array("warn", "yellow box message goes here"));

Normally this kind of thing would go in a warnOnce which is a JS side thing.  We'd probably want to only send the message once. Ideally per instance.

**Comment by asklar** [comment]
sent mail to @marlenecota who added the assert. I'll track adding the yellowbox separately since it's still useful to have the ability to easily surface errors in the UI, let's keep this bug for tracking the resizeMode=repeat assert (is the assert and comment in the code still applicable?)
introduced in: #3712
assert happens [here](https://github.com/microsoft/react-native-windows/blob/567fc48cf6858ece96ff60fcd52e20cded72cbfc/vnext/ReactUWP/Views/Image/ReactImage.cpp#L87)
