### ISSUE TITLE
Remove deprecated Checkbox component from RNW core.

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#4694]
Last documented in 61: https://reactnative.dev/docs/0.61/checkbox
Latest changelog tracking against facebook master has this finally being removed.

> [General] [Removed] This diff removes the CheckBox export from React Native. Internally, we are requiring CheckBox directly now and externally people will have to use the community maintained module. ([dff17ef](https://github.com/facebook/react-native/commit/dff17ef) by [@poteto](https://github.com/poteto))

**Comment by rectified95** [comment]
Splitting this issue in 2 parts - one tracking the reimplementation of the Checkbox module using ABI-safe interfaces, the other to represent us removing the existing implementation from this repo.
