### ISSUE TITLE
(0.62) PanResponderEample Does Not Render Correctly 

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#4701]
The PanResponder test page no longer looks correct after pulling in updates to it in 0.62. Oddly, the example doesn't seem to show a correct example container. Possibly an upstream regression?

0.61
![image](https://user-images.githubusercontent.com/835219/80173867-fa150100-85a5-11ea-9a20-e7bfdfbbe399.png)

0.62
![image](https://user-images.githubusercontent.com/835219/80173875-013c0f00-85a6-11ea-985c-9c9594a79053.png)

**Comment by chrisglein** [comment]
Need to validate that this isn't an upstream bug.
At first glance looks like:
- container background is missing (or container is different size)
- green dot moved
Anything else?

**Comment by NickGerleman** [comment]
From above referenced PR, it sounds like Eric has fixed upstream in the tester example.

**Comment by rozele** [comment]
Fixed once https://github.com/facebook/react-native/commit/917f83c94043d78b1c7dd301abb5716db2b5d563 is pulled in.
