### ISSUE TITLE
(0.62) Picker Will Steal Focus Afer Moving Focus Elsewhere

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#4702]
In the keyboard Focus Example page, the picker to focus on an element no longer works correctly. On selection focus will correctly be moved to another element, but it seems to quickly return to the picker.

![image](https://user-images.githubusercontent.com/835219/80175378-47936d00-85aa-11ea-8e64-73252b8ee23d.png)

It is unknown how many scenarios are affected by this. It looks like there has been some focus issues from before 0.61.

**Comment by NickGerleman** [comment]
Calling `focus()` on the ref is correctly going through the UIManager and calling `winrt::FocusManaager::TryFocusAsync()`. 

Accessibility insights confirms the combo box steals focus after it is programatically moved elsewhere. This focus change is seemingly happening in native. 
![image](https://user-images.githubusercontent.com/835219/80254314-ce3e5d80-862f-11ea-8eb8-9b675fd5d082.png)

**Comment by NickGerleman** [comment]
There was code introduced with https://github.com/microsoft/react-native-windows/commit/f21d0946c8d009b654f540f9e0bce5221940b3c4 to set focus on the combo box after it is dismissed.

It seems like the two async focus calls are racing and the order changed.

**Comment by NickGerleman** [comment]
Unmarking as must-have since the issue seems specific to programmatic focus changes from combo box item selection, instead of a more general issue.

**Comment by chrisglein** [comment]
A common pattern I've seen for this class of issue is to validate that focus is on what you expect before forcing it elsewhere, to avoid collision with other programmatic focus.
