### ISSUE TITLE
RNW 0.61 Does not Allow Keyboard Navigation To or Activation of Touchables

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#4703]
In 0.61, views/touchables marked with accepsKeyboardtFocus do not seem to be focusable. E.g. We're able to focus on the "View accept focus" view in 0.60, but not later.

![image](https://user-images.githubusercontent.com/835219/80176594-f4231e00-85ad-11ea-8ca9-c0bb7a57f4f7.png)

Similarly, focus events for touchables do not seem to work correctly since 0.61 (See the "Last Focus Event" text in the above screenshot)

**Comment by NickGerleman** [comment]
This one is very bad... Marking as must fix, since it even blocks another must fix bug.

**Comment by kmelmon** [comment]
This is a blocking issue, I'll take it

**Comment by kmelmon** [comment]
First observation:  The View that doesn't work expands to this XAML sub-tree:

        CContentControl 0x15e65fb8
            CContentPresenter 0x15e46d38
            CPanel 0x15e4ced8 "<reacttag>: 5595"
                CTextBlock 0x15e65538 "<reacttag>: 5593", text {View accept focus}

The outer ContentControl has IsTabStop = false.  This might explain why it's not focusable.

**Comment by chrisglein** [comment]
Plan is to get rid of the -1 stuff. And align on [focusable](https://reactnative.dev/docs/view#focusable)

**Comment by kmelmon** [comment]
Will fix this by doing part of #2784 
Remove the logic for tabIndex = -1 since that is web-only behavior that conflicts with the boolean prop. After this change,tabIndex can only be >=0.

**Comment by NickGerleman** [comment]
It just now hit me that this issue was applying to normal touchables as well, since they set this internally to try to be focusable by default.

I.e. in 0.60 touchables were focusable and allowed keyboard activation, etc. In 0.61 we couldn't keyboard navigate between them.

Going to reopen and mark for triage just because I think this bug is an interesting conversation on our policy on when to backport, our capability to catch regressions in a timely manor, our current bar, etc. I know we've talked about this already but I'm not sure if the implications for stock controls were realized at the time.

**Comment by NickGerleman** [comment]
This one is going to be a bit messy to label, since we already backported to 0.62, but now want to backport to 0.62.

**Comment by NickGerleman** [comment]
Updated the backing PR with the "Backport approved label" so we can track that as well.

**Comment by NickGerleman** [comment]
Closing since this was backported.
