### ISSUE TITLE
Text styled with Bahnschrift is off center despite being centered in a View

### ISSUE THREAD

**Issue by Tatious** [microsoft/react-native-windows#4709]
### Steps to Reproduce

```
<View
  style={{
    backgroundColor: '#FF0000',
    marginTop: 200,
    width: 200,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
}}
>
  <Text 
    style={{ 
      color: 'white',
      fontSize: 14,
      lineHeight: 14,
      fontFamily:'Assets/Fonts/BS-Static-Regular.ttf#BahnschriftStaticReg' }}>
  {'Hello World'}
  </Text>
</View>

```

Note, the fontFamily asset location and font family name uses a modified version of the font file since RNW does not yet support the standard way of importing font files, and since winrt seems to require a very specific font family name internally for it to be able to load the font.

### Expected Behavior

Font family: Segoe, text is properly centered

<img width="201" alt="s" src="https://user-images.githubusercontent.com/32688486/80258622-87a13100-8638-11ea-8333-07408bdec639.png">

### Actual Behavior

Font family: Bahnschrift, text it slightly too high. This issue does not occur on other platforms with the same font file

<img width="201" alt="b" src="https://user-images.githubusercontent.com/32688486/80258625-8a038b00-8638-11ea-807f-6d70ee534daa.png">

### Additional context

Adam Gorman(adamgor)
Austin Beaulieu(aubeauli)

**Comment by chrisglein** [comment]
Is this an issue with `lineHeight` being treated in the wrong units?

**Comment by Thristhart** [comment]
This happens in a blank XAML sample app as well:
```xaml
    <StackPanel Orientation="Horizontal" HorizontalAlignment="Center" VerticalAlignment="Center">
        <Button x:Name="myButton" Click="ClickHandler" FontFamily="Bahnschrift">Click Me</Button>
    </StackPanel>
```
![image](https://user-images.githubusercontent.com/43013/83312828-aca13a80-a1c8-11ea-8a52-8c74eedce7b8.png)

so this probably isn't an RNW issue, although it's likely to be annoying for RNW users.

**Comment by chrisglein** [comment]
Not something we plan to address on the Paper renderer as we move towards Fabric.
As that Fabric uses a raw RichEdit to render instead of XAML, this issue likely doesn't come along.

**Comment by JakobKrummeichAndrena** [comment]
@chrisglein Can you please give some context as to why this happens on Paper and how to address this? We have the same problem currently (though with a different font) and would be grateful for some help on this. Thank you!
