### ISSUE TITLE
Please add support for React Native Windows app development from WSL 2

### ISSUE THREAD

**Issue by gulshanmudgal** [microsoft/react-native-windows#4718]
# Proposal: Enable development of React Native for Windows and Mac  in WSL 2

## Summary
I would like to have a feature where I can have all my React Native related dev setup in WSL 2 and emulators running in Windows. If the process becomes seamless, it would be a very joyful experience for any cross platform app developer.

## Motivation
I have created a similar setup for React Native for Android, if such a feature is implemented it would help a lot more developers in simplifying their development setup.

**Comment by NickGerleman** [comment]
React Native for Windows is pretty coupled to Windows specific build tools, and React Native for Mac is pretty coupled to Mac build tools. Neither of these can be run from WSL. I can't think of a way it would be possible to accomplish this unfortunately.

**Comment by gulshanmudgal** [comment]
As you stated above, for obvious reasons, Eeact Native for Mac can't be supported on WSL, but for in case of React Native for Windows i guess, if possible, some sort of RPC can be used to build, debug and deploy the application on emulator. Like VS Code allows for remote development with help of extensions. In this the scenario would be reversed, We would want to access Windows binaries from WSL. I hope this should be possible.

**Comment by gulshanmudgal** [comment]
.Net Core is now supporting app debugging with WSL 2, we can add a similar extension for React Native as well.

**Comment by jamespacileo** [comment]
Is this still not supported?

**Comment by gulshanmudgal** [comment]
> Is this still not supported?

Nope.

**Comment by chiaramooney** [comment]
Closing issue as this work will most likely not be tackled by the team. We will reopen if priorities change.
