### ISSUE TITLE
`Can't find Husky, skipping post-checkout hook` during checkout

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#4726]
I get the following error when checking out branches:

```
Can't find Husky, skipping post-checkout hook
You can reinstall it using 'npm install husky --save-dev' or delete this hook
```

Looks like someone added a step without adding it to the package.json.

**Comment by NickGerleman** [comment]
@jonthysell the ordering was kind of the opposite. I had a hook, removed the hook, then removed Husky, but Husky doesn't seem to uninstall cleanly. We were thinking about adding a hook back though, so I think adding Husky back is fine.
