### ISSUE TITLE
Allow Looser Peer Dependency on React Native

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#4735]
In 0.61, our peer dependency was set to a strict "0.61.5". This was never an issue since that was already the last release. The peer dependency for RNW is currently set to 0.62.2, which will give people errors if they rev react-native further than that.

From recent discussion, we're still giving folks guidance that has them potentially installing a newer patch release than we explicitly target. We should update our peer dependency to support this.

**Comment by chrisglein** [comment]
@NickGerleman Can you capture more of this discussion here?

> From recent discussion, we're still giving folks guidance that has them potentially installing a newer patch release than we explicitly target.

We're definitely not testing combinations with newer versions, so I'm uneasy about advertising it as supported. How are you thinking that part plays out?

**Comment by NickGerleman** [comment]
@chrisglein our CLI tooling and documentation has pointed people towards installing the latest patch version of RN. There's some risk here, but the alternative seems pretty bad as well, and patch releases are usually pretty small.

That's definitely worth a conversation, but tooling + docs point towards allowing different patch versions already.
