### ISSUE TITLE
'Question: Will GettingStarted link work in near future?'

### ISSUE THREAD

**Issue by Lechus** [microsoft/react-native-windows#4736]
on todofeed sample
https://github.com/microsoft/react-native-windows/blob/master/vnext/docs/GettingStarted.md

**Comment by chrisglein** [comment]
Not much of a question. I think you just mean this is a bug :)
Looks like this document has a broken link: https://github.com/microsoft/react-native-windows-samples/tree/master/samples/TodosFeed
We've [created an issue over there](https://github.com/microsoft/react-native-windows-samples/issues/84). In the future please log bugs against the samples repo.
@jonthysell I would have thought this would have been caught by unbroken. Is that not targeting the samples part of that repo?
