### ISSUE TITLE
Add support for a JavaScript projection of the Windows Runtime API

### ISSUE THREAD

**Issue by dstaley** [microsoft/react-native-windows#4759]
# Proposal: Add support for a JavaScript projection of the Windows Runtime API

## Summary

As a JavaScript developer, I'd like to be able to call Windows Runtime APIs without writing a native module in an unfamiliar language such as C++ or C#.

## Motivation

As a JavaScript developer building a Windows app with React Native, I'd like to avoid having to switch languages to call useful Windows Runtime APIs. Since there's already a precedent for the Windows Runtime supporting multiple language projections (C++, C#, and now Rust), and, most importantly, since there was already a JavaScript language projection at one point, it would be great for React Native for Windows to support calling these APIs from JavaScript either out of the box or through an easily-installable module.

### External Package

```js
import CryptographicBuffer from 'react-native-windows-runtime/security/cryptography';

const num = CryptographicBuffer.GenerateRandomNumber();
```

### Built-in

```js
import { NativeModules } from 'react-native';
const { CryptographicBuffer } = NativeModules.Windows.Security.Cryptography;

const num = CryptographicBuffer.GenerateRandomNumber();
```

## Open Questions

The biggest question I have is whether this is possible given that React Native for Windows uses JSC/Hermes, whereas I believe the JavaScript projection was only ever supported in ChakraCore.

**Comment by chrisglein** [comment]
@asklar has had some recent discussions on the viability of this. It's something we've considered. @asklar can you represent the current thinking in this issue?

**Comment by asklar** [comment]
Quickly evolving discussions with several teams that are presenting different options (xlang, the 'thing' we talked about today, nodert). we'll have more data in the coming weeks.

**Comment by asklar** [comment]
closing this one out as it is not a RNW-specific ask, and filed a bug in the windev repo instead.

**Comment by asklar** [comment]
We’re excited to share **React Native WinRT** is now in public preview. This is an extension that can be added to React Native for Windows apps, that enables calling WinRT APIs directly from JavaScript.

Learn more here: https://microsoft.github.io/react-native-windows/blog/2022/02/11/rnwinrt
