### ISSUE TITLE
Question: Available UI Components

### ISSUE THREAD

**Issue by woodrufs** [microsoft/react-native-windows#4768]
Hi all,
First off, thanks to everyone at MSFT who has been working on this. Hats off to you all as I can only imagine the scope and complexity of this project. I am not going to lie, I am _very_ new to RN and RNW still, so I apologize if I sound like I am clueless here (hint: I am). 

I have a question regarding available UI components. I am taking over a RN app that is currently on .59. We are attempting to upgrade this to .61. The team that was originally working on this app included a handful of packages to support things for RNW. For instance, one is a package they wrote to render a calendar view for Windows. I first attempted to port this package to support .61, but I was running into issues where I could never get the calendar component to actually render. After many hours of struggling, I noticed that RNW has a DatePicker component baked in I could use .

I didn't expect this to be the case when I read the API Parity documents [here](https://microsoft.github.io/react-native-windows/docs/parity-status) because I was under the impression that DatePickerAndroid and DatePickerIOS were not core components. 

Is there somewhere else I should be looking to see what other components are supported with RNW? I am really enjoying working with RNW and being able to develop a UWP application, but I am having a difficult time getting started with some of the Windows specific aspects. Do I need to maybe spend more time digging through the react-native-windows repository to see what is actually supported? If I didn't do this, I don't think I would have seen that there is a DatePicker component that is ready for me to use. I hope I don't sound lazy... Our company lost our RN developers, so I am trying to pick up the pieces as quickly as possible. Any input is really appreciated!

Thank you,
Stephen W

**Comment by asklar** [comment]
Relevant work: #3587 and #4156

**Comment by chrisglein** [comment]
As Alex linked, we're trying to get better about documenting what is and isn't working (while also just getting things working :)) As for community modules, the link you provided is correct. Anything else you're looking to get answers on?

**Comment by woodrufs** [comment]
I don't think so for this issue. It sounds like I should continue to dig through the source code for now. Thank you for the replies.
