### ISSUE TITLE
RTL:  Template app manifest resources only have EN-US, makes app layout LTR on RTL locales

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#4770]
This was discovered while implementing the direction property and allowRTL API.

We now have proper support for i18nManager.allowRTL(true), which will auto-detect the language and flow direction.  However, for the template app generated by the CLI, it has a hard-coded EN-US in its manifest, which makes this auto-detection logic think the app only wants english.  Thus the app still does an LTR layout in RTL locales.

The manifest entry is here, in AppxManifest.xml:
  <Resources>
    <Resource Language="EN-US" />
  </Resources>

If on a Hebrew system, I change Language to "He-il", the auto-detection logic in RNW then works correctly and the app flips to RTL.

Note that this resource setting also controls whether the minimize/maximize/close buttons flip to the other side of the app frame.

I'm not sure yet how to fix this.  The hope is that we can find a solution that will 'just work' without requiring app authors to muck around with their appxmanifest, as many won't know how to do this.

**Comment by chrisglein** [comment]
> The manifest entry is here, in AppxManifest.xml:

@kmelmon looks like this didn't paste in

**Comment by chrisglein** [comment]
A UWP app should respect RTL out of the box. The XAML controls will handle RTL in appropriate ways (usually flipped, sometimes not (e.g. a time indicator)).

How do we differ from the normal UWP template? Have we drifted?

**Comment by chrisglein** [comment]
We also need to understand the overlap here with XamlIslands, where we won't have the UWP APIs necessarily to query state here. Things like MRT are also going to be impacted by WinUI3.

**Comment by kmelmon** [comment]
This article may help:  https://docs.microsoft.com/en-us/windows/uwp/app-resources/build-resources-into-app-package
