### ISSUE TITLE
Support direct debugging when using Chakra in VS Code.

### ISSUE THREAD

**Issue by nasadigital** [microsoft/react-native-windows#4771]
# Proposal: Support direct debugging in visual studio code

## Summary

You can use VS Code for direct debugging when using V8/Hermes, but not for Chakra. This issue is for adding support.

## Motivation

The only way to do direct debugging with Chakra is through Visual Studio. Adding support for VS Code would allow developers to pick the tool that better suits their needs.

**Comment by chrisglein** [comment]
This is system Chakra, so this isn't really RNW specific but also _very_ important to a good experience on RNW. @harinikmsft who do we contact to get traction on this?
Of note we use ChakraCore for Win32, not getting into that here.

**Comment by EricCornelson** [comment]
@chrisglein , you can open an issue here: https://github.com/microsoft/vscode-react-native/issues for Chakra debugging

**Comment by harinikmsft** [comment]
Filed this in VS Code issues per @EricCornelson 's comment above. See https://github.com/microsoft/vscode-react-native/issues/1371
