### ISSUE TITLE
'Question: New react-native-windows V0.62 consuming lot space. It consumed 12gb'

### ISSUE THREAD

**Issue by tejaat1995** [microsoft/react-native-windows#4775]
I just created a new project and it occupied 12gb space. 

Is anyone knows how to overcome this problem?

**Comment by NickGerleman** [comment]
@tejaat1995 would you be able to let us know the files that are large? I get a feeling this might be related to our precompiled headers.

**Comment by asklar** [comment]
Likely it's the node_modules first, then the PCHs.

**Comment by chrisglein** [comment]
Can we measure what's expected here? It seems like we could just look at what people _should_ see. Has something recently blown up? Also, compare to core RN.
Moving to binary distribution will definitely help here long term.

**Comment by chrisglein** [comment]
Data from @asklar : node_modules is 4.6 GBs....

**Comment by NickGerleman** [comment]
Note that we build `react-native-windows` source within node_modules currently. IIRC our actual deps are much smaller, but this is worth checking up on.

**Comment by asklar** [comment]
@NickGerleman @chrisglein the main culprits are actually a combination of node_modules, RNW built and PCH :) 
a new project is 6.8 GB and it's spent thusly:

- 4.6GB  node_modules
  - 4.3 GB in react-native-windows/build/x86
    - 2 GB in each Debug and Release, out of which **1.4 GB for every PCH**
- 2.2GB  windows
  - 1.6 GB in Packages
    - 800 MB ReactNative.V8Jsi.Windows
    - 670 MB ReactNative.Hermes.Windows
  - 400 MB is the app's build (still seems unreasonably large). 
    - 148 MB obj
    - 140 MB bin
    - 100 MB AppX.

Note that this is only x86. If you build x64/ARM/ARM64, then it's probably another 5GB/arch.

- Moving to DLL would get rid of about 4.6 GB/arch. 
- We should also not force install V8 and Hermes if the app isn't going to use it, that would save another 2 GB.

**Comment by asklar** [comment]
Filed #4787 to shave off 1.6 GB.
Once we move to DLL in the nuget, we'll save the 4.5GB per {platform x config} combination

**Comment by tejaat1995** [comment]
> @tejaat1995 would you be able to let us know the files that are large? I get a feeling this might be related to our precompiled headers.

Yes, it's coming because of precompiled headers.

**Comment by tejaat1995** [comment]
> @NickGerleman @chrisglein the main culprits are actually a combination of node_modules, RNW built and PCH :)
> a new project is 6.8 GB and it's spent thusly:
> 
> * 4.6GB  node_modules
>   
>   * 4.3 GB in react-native-windows/build/x86
>     
>     * 2 GB in each Debug and Release, out of which **1.4 GB for every PCH**
> * 2.2GB  windows
>   
>   * 1.6 GB in Packages
>     
>     * 800 MB ReactNative.V8Jsi.Windows
>     * 670 MB ReactNative.Hermes.Windows
>   * 400 MB is the app's build (still seems unreasonably large).
>     
>     * 148 MB obj
>     * 140 MB bin
>     * 100 MB AppX.
> 
> Note that this is only x86. If you build x64/ARM/ARM64, then it's probably another 5GB/arch.
> 
> * Moving to DLL would get rid of about 4.6 GB/arch.
> * We should also not force install V8 and Hermes if the app isn't going to use it, that would save another 2 GB.

Thanks for the information @asklar.

**Comment by asklar** [comment]
#4787 will remove the v8 and Hermes nugets which will give you back 1.6 GB. 
Then once we move to a binary/nuget distribution model we'll remove the 4.5 GB per arch cost. That's tracked in #4550 for new projects, part of https://github.com/microsoft/react-native-windows/projects/33

**Comment by tejaat1995** [comment]
> @tejaat1995 #4787 will remove the v8 and Hermes nugets which will give you back 1.6 GB.
> Then once we move to a binary/nuget distribution model we'll remove the 4.5 GB per arch cost. That's tracked in #4546, part of https://github.com/microsoft/react-native-windows/projects/33

Thanks @asklar

**Comment by asklar** [comment]
Closing stale issue
