### ISSUE TITLE
Determine How to Handle Breaking Change Causing Runtime Crash

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#4776]
#4755 removes a user-facing workaround we left in our template app. It has a nasty side-effect of causing any apps upgrading to see a crash if they don't remove the workaround.

This is a breaking change that could cause a lot of frustration, as the crash will appear somewhat cryptic. Following up with @vmoroz to understand if there are alternate fixes that could avoid the crash, or if we could convert the crash into a build-time error.

Pending that we have a couple options:
1. Cherry-pick into 0.62 and try to rip the band-aid off early. This will break people using our preview, which is not ideal.
2. Delay the change until 0.63, so that we can try to catch people with initial release notes.
3. Invest in infrastructure like `react-native-upgrade` to mitigate before making the change (likely not possible)

**Comment by asklar** [comment]
This might be even more relevant with WinUI3 since we'd be inheriting from MUX's Application instead of WUX's

**Comment by chrisglein** [comment]
I think we should take #1, which is to break the preview. It's early enough in (one week out), so there's not too many on that yet.

Linking to this (general desire for upgrade helper) for reference: #3470

**Comment by NickGerleman** [comment]
We decided to cherry pick into 0.62.0-preview.3
