### ISSUE TITLE
Changing Configuration or Platform hangs VS for a few minutes

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#4777]
open any solution like E2ETest or Playground
Change the configuration (debug/release) or platform (x86/x64)
Observe that VS hangs for 5-10 minutes
this is because something triggers it to run node jest and hang the VS UI

**Comment by chrisglein** [comment]
May just be E2ETest with bringing in `jest`, not necessarily Playground. But yeah, seems like something is happening here that shouldn't.

**Comment by chrisglein** [comment]
Expect this only applies to these solutions, not a general app solution. Would be much more painful it affected every configuration change on an app solution.

**Comment by acoates-ms** [comment]
@asklar  - I'd like to understand where you see the `jest` stuff.  I'm not sure I see this issue on my machine. -- And having some log or something might help work out what is going on.

**Comment by asklar** [comment]
@acoates-ms there are multiple node.exe processes but the main one seems to be running with this command line:
`"C:\Program Files\nodejs\\node.exe"  "C:\Program Files\nodejs\\node_modules\npm\bin\npx-cli.js" --no-install react-native bundle --platform windows --entry-file index.js --bundle-output C:\Users\asklar\source\repos\testcpp\windows\testcpp\Bundle\index.windows.bundle --assets-dest C:\Users\asklar\source\repos\testcpp\windows\testcpp\Bundle --dev false --reset-cache --sourcemap-output windows\Release\testcpp\sourcemaps\react\index.windows.bundle.map`

**Comment by asklar** [comment]
@acoates-ms  Ah I know what's going on now. Intellisense is triggering a bundling operation because we say Release should run the bundler. We need a way to turn this off during Intellisense.
