### ISSUE TITLE
Cleanup from OS XAML/WinUI 3 straddle

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#4778]
While migrating to WinUI3, I had to keep a lot of code that is relevant only for OS XAML. This issue tracks cleaning that up once we migrate to WinUI 3 completely.

- Monolithic CppWinRTIncludes.h - we can make this smaller and make individual cpp files include one-off headers. This could speed up builds.

- Version checks - we do version checks for IUIElement7/8/9/10, which should go away with WinUI 3.

- Remove WinUI3 Configuration and USE_WINUI3 and make it the default 

- Remove WebView code in favor of WebView2

**Comment by chrisglein** [comment]
@asklar @AgneLukoseviciute How does this differ from #9135?

**Comment by AgneLukoseviciute** [comment]
> @asklar @AgneLukoseviciute How does this differ from #9135?

@asklar can correct me if I'm wrong, but my read on this is that #9135 tracks cleanup related to only supporting WinUI3 on WASDK (and not UWP, islands), whereas this issue tracks cleanup related to removing OS XAML support entirely in favor of WinUI3.

**Comment by asklar** [comment]
yes that's correct. Since we're likely to support UWP for a while, I think this issue can be closed

**Comment by AgneLukoseviciute** [comment]
> yes that's correct. Since we're likely to support UWP for a while, I think this issue can be closed

Thanks! I'll go ahead and close.
