### ISSUE TITLE
Fast Refresh does not work on RNW 0.62

### ISSUE THREAD

**Issue by Sosaalt** [microsoft/react-native-windows#4779]
Hello there :)

I have been playing around with rn-windows/macos and it seems that enabling FR always leads to a full reload of the UI even when editing isolated functional components. In contrast, in react-native android/ios only the component subtree which has been affected by the change ends up being re-rendered.
Is this behavior by design or is there an existing limitation imposed by the current implementation of fast refresh? If it is the latter I would be more than happy to work on a pull request.

Thanks for reading!

**Comment by chrisglein** [comment]
Fast Refresh should be working for Windows at least as of 61.5. Can you clarify what version you're using? Fast Refresh came with 61, and there's very recently a version of macOS that supports 61.

**Comment by Sosaalt** [comment]
Hello Chris,

Spot on! It was a versioning issue. It seems the problem only occurs with the 0.62 preview.

Working setup:
  System:
    OS: Windows 10 10.0.18362
    CPU: (6) x64 Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz
    Memory: 2.50 GB / 8.00 GB
  Binaries:
    Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
    react-native-windows: ^0.61.0-0 => 0.61.7
  Installed UWP SDKs:
    10.0.17134.0
    10.0.17763.0
    10.0.18362.0

Broken Fast Refresh:

  System:
    OS: Windows 10 10.0.18362
    CPU: (6) x64 Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz
    Memory: 2.41 GB / 8.00 GB
  Binaries:
    Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 16.11.0 => 16.11.0
    react-native: ^0.62.0-0 => 0.62.2
    react-native-windows: ^0.62.0-0 => 0.62.0-preview.2
  Installed UWP SDKs:
    10.0.17134.0
    10.0.17763.0
    10.0.18362.0

**Comment by NickGerleman** [comment]
We're not yet tracking fast refresh issues with 0.62. @acoates-ms could you take a look?

**Comment by acoates-ms** [comment]
Hmm. I've confirmed the issue.
I'll look into it.

**Comment by NickGerleman** [comment]
Marking for re-triage so we can discuss whether this blocks 0.62 from exiting prerelease.

**Comment by daveteu** [comment]
May I mention this seems to happen on react-native-macos as well.
     "react-native": "0.62.0",
    "react-native-macos": "^0.62.21",

and accompanying this issue of not being able to fast refresh, is the following message.

![image](https://user-images.githubusercontent.com/18649392/102981440-e8746680-4543-11eb-8940-cc65bfb1b30f.png)
```

Unable to find module for DevSettings

-[RCTCxxBridge moduleForName:lazilyLoadIfNecessary:]
    RCTCxxBridge.mm:528
-[RCTCxxBridge moduleForClass:]
-[RCTBridge(RCTDevSettings) devSettings]
__21-[RCTCxxBridge start]_block_invoke.176
invocation function for block in attemptAsynchronousLoadOfBundleAtURL(NSURL*, void (RCTLoadingProgress*) block_pointer, void (NSError*, RCTSource*) block_pointer)
-[RCTMultipartStreamReader emitProgress:contentLength:final:callback:]
-[RCTMultipartStreamReader readAllPartsWithCompletionCallback:progressCallback:]
-[RCTMultipartDataTask URLSession:streamTask:didBecomeInputStream:outputStream:]
CFHTTPCookieStorageUnscheduleFromRunLoop
__NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__
-[NSBlockOperation main]
__NSOPERATION_IS_INVOKING_MAIN__
-[NSOperation start]
__NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__
__NSOQSchedule_f
_dispatch_block_async_invoke2
_dispatch_client_callout
_dispatch_continuation_pop
_dispatch_async_redirect_invoke
_dispatch_root_queue_drain
_dispatch_worker_thread2
_pthread_wqthread
start_wqthread

```

**Comment by chrisglein** [comment]
> May I mention this seems to happen on react-native-macos as well.
> "react-native": "0.62.0",
> "react-native-macos": "^0.62.21",

FYI the macos repo handles issues separately, here: https://github.com/microsoft/react-native-macos/issues
