### ISSUE TITLE
new app includes 1.6 GB of unused packages

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#4787]
The default app will include 1.6 GB used by Hermes and V8 packages, even though 99% of apps won't use this.

**Comment by asklar** [comment]
@tudorms it looks like you added USE_V8 and USE_HERMES in PR #4234. This seems problematic for a couple of reasons:
* This uses up 1.6 GB in nuget packages for V8 and Hermes for every project even if they just use Chakra.
* This delay loads some binaries which might not pass Store certification for UWP apps.

It sounds like this was only tested for Win32.

I'm planning on doing the following, let me know if you have objections:
* Remove the V8 and Hermes entries from packages.config and individual apps can add them if they would like
* Change USE_V8 and USE_HERMES to add a condition for "path to the nuget package exists"

**Comment by NickGerleman** [comment]
Mentioned this in the PR, but the store validation issue has been fixed and backported. We don't package the delay-loaded binary, and Microsoft.ReactNative does not yet expose engine selection, so there's no way to get to the path where we could even try to load it. There's definitely room for a cleaner design here, and reduction of package size that I'm sure we will eventually move towards.

**Comment by chrisglein** [comment]
Related: #4775

**Comment by chrisglein** [comment]
Sounds like we're going to need a second step (in addition to setting USE_*) to enable these in the package. It adds another step, but better than having people pay for this stuff they're not using.

Will be a cost for core repo, but not for the apps.

**Comment by tudorms** [comment]
The store validation was fixed by adding a hack to not copy the dll into target for uwp projects (see https://github.com/microsoft/react-native-windows/pull/4714); is this issue about the size on disk of a development environment?

We may need to refactor the build system to properly separate uwp and win32 (perhaps by using PackageReferences throughout the vcxproj files). Office needs the win32 package built with USE_V8=true.

**Comment by chrisglein** [comment]
> The store validation was fixed by adding a hack to not copy the dll into target for uwp projects (see #4714); is this issue about the size on disk of a development environment?

Will taking this change remove the need for the hack? That change looks to be for V8. Have we validated that both V8 _and_ Hermes aren't being included in the app size for apps that aren't opting in?

This PR resulted from the linked bug which in turn was reported by and end developer experiencing the dev bloat and being (rightfully) frustrated. So we've already got signal that this is impacting developers negatively. I would like to understand the app size impact as well.

> We may need to refactor the build system to properly separate uwp and win32 (perhaps by using PackageReferences throughout the vcxproj files). Office needs the win32 package built with USE_V8=true.

How can we validate this change meets Office needs? As far as I know there isn't sufficient CI in place to validate that, so can you please provide guidance? This this refactor of the build system immediately feasible, or large in scope?

**Comment by tudorms** [comment]
Should we set up a quick meeting offline to chat about V8 / Hermes and Office specific stuff?

We can include @Khalef1 , @asklar  and @acoates-ms

**Comment by Khalef1** [comment]
> Should we set up a quick meeting offline to chat about V8 / Hermes and Office specific stuff?
> 
> We can include @Khalef1 , @asklar and @acoates-ms

Yes, please. It will be much easier to chat about this specific one offline and we can help share context on our requirements and how they can be validated. Can you set something up?
