### ISSUE TITLE
DatePicker module: system locale not reflected in how RNW apps format or translate dates 

### ISSUE THREAD

**Issue by rectified95** [microsoft/react-native-windows#4791]
### Steps to Reproduce

Run the DatePicker example in Playground\RNTester or create a test app using the date picker component.

### Expected Behavior

Changing Regional Format in the Windows Settings app should affect how the underlying CalendatDatePicker XAML control formats dates, as well as their display language.

### Actual Behavior

No change can be observed in the RN app, even though they're reflected in the shell.
(Disregard the date format settings in the screenshot of my demo - I commented out the props they controlled)

![region_date](https://user-images.githubusercontent.com/12816515/81030290-2d288180-8e3d-11ea-9471-45cba4d1f7e7.png)

**Comment by chrisglein** [comment]
Sounds like there is some level of involvement for the behalf of datepicker, where it has bugs that are not internationlization ready. We should be crisp about where the platform is not following through, versus where the module is ready.
The `intl` JavaScript module is supposed to expose much of this kind of functionality. It should be available on Chakra at least (pending on Hermes).
We need to figure out what level of support we can give to improve the community date picker versus supporting it as it is. If there's something that's not working just on Windows versus not working on Android/iOS.

@rectified95 can you clarify what's Windows-only here and what's lacking in the control as a whole?
(for the latter maybe we open issues on that repo?)

**Comment by rectified95** [comment]
Sorry this one slipped through the cracks. Commenting to prevent the issue getting closed. Assigning to myself while I look into `intl`.

**Comment by NickGerleman** [comment]
Have a PR out removing DatePicker. I would guess this issue still affects the community module version. Potentially affects what to do with this issue.

**Comment by asklar** [comment]
The core control (DatePickerIOS / DatePickerAndroid) is ejected (they warn but they work), we have a Windows only API DatePicker.

We want to redirect folks to the community module; this yellow boxes in RNW 0.64, so we should leave enough time for people to see it before we remove it from RNW core. Slate it for removal in 0.66?

**Comment by asklar** [comment]
@rectified95 can you check if the community module has this issue filed and if so, close this one.
