### ISSUE TITLE
Reenable FH4 When Consumers are on V142

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#4804]
See linked PR.

**Comment by asklar** [comment]
AFAIK the only consumer not on 142 is Office - can this be opt in for Office as opposed to forcing everyone to get this disabled?

**Comment by NickGerleman** [comment]
We discussed this on the Office side, and the only ways to do this were pretty invasive/unnatural. A lot of our projects produce static libraries that would include code with CxxFrameHandler4. That means we would need to do things like add a temporary Office specific build config to each static library, or move away from producing static libs in general.

Turning off globally avoids a lot of pain/fragmentation. It does affect binary size a bit, but it's not a regression relative to 0.61, and we haven't been particularly sensitive to it before or measuring when adding new projects, turning of RTTI, etc. 

In the short term, Office will get to v142 pretty soon, so we're only delaying enabling FH4 by likely a release. Longer term, enabling Office to benefit from the ABI safety work we did for Universal is the point of the core DLL effort.

**Comment by chrisglein** [comment]
@NickGerleman Can you edit the issue description to provide more background here?
My summary is that the move from 141 to 142 is a blocker for Office, which needs to move to 0.62. Disabling this feature is a regression in behavior on 142, but basically parity with what had 141. This issue tracks rolling that back and getting the winnings again.
