### ISSUE TITLE
Please add support for building native Linux GTK apps

### ISSUE THREAD

**Issue by KristijanZic** [microsoft/react-native-windows#4823]
Like the title says, please add support for building native Linux GTK apps. It would be great to have Linux supported too.

**Comment by chrisglein** [comment]
Don't disagree :)
Unfortunately this repo is just targeted towards Windows so we won't keep this issue open here :)

**Comment by kaioduarte** [comment]
@chrisglein do you know if there is at least a plan for Microsoft supporting Linux platform? I'm aware that exist other projects that aim to do that, but it'd be great if it was officially supported by you guys.

**Comment by ratoi-crysty** [comment]
@chrisglein I know this is a closed issue, but closing the issue because the repo is just targeted towards windows, is wrong, as currently the project also supports macOS. 
Could you please reopen this? Maybe this will be prioritized in the future, as this is a desired feature.

**Comment by asklar** [comment]
No plans for this at this time, sorry!

**Comment by tom-sherman** [comment]
> Unfortunately this repo is just targeted towards Windows

@asklar @chrisglein I guess this statement is now no longer the case 😅 has there been any movement on Linux support or discussions about it?

**Comment by asklar** [comment]
@tom-sherman this repo is still very much about Windows and exposing the native Windows UI platform :) There are no plans to support Linux apps.

**Comment by dragonDScript** [comment]
Where should we ask this feature? A GNOME or Qt version would be nice :)

**Comment by asklar** [comment]
there are still no plans to build support for Linux, sorry.

**Comment by dragonDScript** [comment]
> 
> 
> there are still no plans to build support for Linux, sorry.

Okay. Is this an internal decision?

**Comment by NickGerleman** [comment]
There's a lot of people required to stand up and maintain an out of tree platform for react-native. We have a lot of existing expertise for both Windows and macOS, and we will support these. Usually OSS supported by corporations works best when OSS goals and business goals are aligned. As great as Linux is, most of the scenarios MSFT works on don't target it.

A goal of RN Windows and RN macOS has been to introduce desktop idioms into react-native. E.g. primitives for mouse and keyboard interaction. These will I think be universally applicable across desktop focused platforms. 

There was previously a project to back RN with Qt but I'm not sure where it ended up. There's a separate effort targeting skia, but iirc it might be targeted towards embedded.
