### ISSUE TITLE
Support for native modules across multiple islands/DispatcherQueue (multiple islands in same app)

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#4834]
Today most/all of the code assumes there is one UI thread. We need a design for how this will work in an app where there is more than one island. Namely, a native module gets instantiated by the host/instance - it needs to know what island it would be associated with. Can we have more than one instance of a native module per app? e.g. one datetime picker for each island? or do these need to be singletons and therefore the NM needs to be able to reason which island/DQ to deal with across every API?

Related: #2557 and #4833

**Comment by NickGerleman** [comment]
This is something @vmoroz is looking into.

The design gets complicated wrt native modules assuming instance global UI. We already see that with multi-Window with Win32, but multi-UI thread gets more hazy. Multiple of the same native module per instance would break a lot of assumptions and is likely not possible. There was some consideration for view managers to potentially associate UI thread with view tree and dispatch based on React tag, and using an instance global UI thread for modules. A lot of modules need "a UI thread" and some of the ones that are UI based already have APIs that don't work in multi window.

**Comment by asklar** [comment]
@NickGerleman yes, I know

**Comment by chrisglein** [comment]
Sounds like multiple UI threads is out of scope for RN core works today (or instead, use multiple instances).
Multiple islands _on one UI thread_ is supported.
