### ISSUE TITLE
applicaiton name alphanumeric

### ISSUE THREAD

**Issue by albseb511** [microsoft/react-native-windows#4835]
"first-app" is not a valid name for a project. Please use a valid identifier name (alphanumeric)

Got this on creating an app.

Support for characters like -, _ etc?

Is this intentional? and will it change for future?

**Comment by asklar** [comment]
@albseb511 this limitation is not specific to React Native for Windows but it's a core React Native convention (see https://github.com/facebook/react-native/issues/19473).
It sounds like the CLI only allows names that match the regex `[$A-Z_][0-9A-Z_$]`
However once you create the RN app and link in Windows, you can change your app's name in Visual Studio in the project properties.

**Comment by albseb511** [comment]
Thanks for clarification. 

I've not been able to setup on macOs. I'm guessing some issue with cocoaPods

**Comment by NickGerleman** [comment]
Going to close this issue since it isn't directly related to `react-native-windows`

**Comment by asklar** [comment]
@NickGerleman please do not close issue out from under triage. Thanks.
