### ISSUE TITLE
Generating a new certificate in VS 16.5+ breaks app signing

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#4836]
@qmatteoq ran into this, filing on his behalf.

> Today I was working on a React Native for Windows project and I’ve noticed something wrong with Visual Studio 16.5.4. Maybe it’s something you’re already aware and it’s already fixed in internal versions, but better to double check 😊
I had to create a new self-signing certificate to sign the UWP app, so I’ve proceeded using the UI wizard which is available in the Packaging section of the manifest. Everything completed fine but, when I tried to run the React Native scripts which signs and deploys the package through PowerShell, I got the following error:
 
`Certificates specifies an incompatible key usage`
 
> From the documentation, it seems the problem is related to the certificate missing the extended key usage flags required for code signing. At this point I tried to generate a new certificate manually using the guidance here: https://docs.microsoft.com/en-us/windows/win32/appxpkg/how-to-create-a-package-signing-certificate
The certificate generated this way, instead, works fine. The package is signed and deployed just fine.
 
VS folks said this is a known issue: https://developercommunity.visualstudio.com/content/problem/1012921/uwp-packaging-generates-incompatible-certificate.html

This will be fixed in VS 16.7 but in the meantime 16.5 and 16.6 will be broken.
The certificates created by VS 16.5 and up in the VS UI are going to be broken in the sense that `Add-AppxPackage`  will error out:
> There are two scenarios that introduce the blocked EKU’s. They are:
> 1)	The user generates a signing certificate through the Packaging Wizard or Manifest Designer. The cert we generate contains one of the new EKUs designating it as one generated within the UWP UX.
> 2)	The user packages the app for store and checks the box to generate test artifacts to run WACK (on by default) without specifying a certificate manually. In this case we’ll generate a disposable cert containing both new EKUs.
> Certs generated through powershell with the proper code signing EKU, or certs generated in versions of VS prior to 16.5 will continue to work unimpeded.

**Comment by chrisglein** [comment]
Workaround: Ship `Add-AppxPackage` conditional on version while we wait for the VS fix.
Of note, this isn't specific to RNW, we're just impacted via UWP tools. As much as possible we want to forward to standard guidance.
@harinikmsft Can you follow up with app model team for guidance?

**Comment by chrisglein** [comment]
Suggestion: Identify VS version and emit a warning (and/or do workaround for them) so it's obvious up front.
