### ISSUE TITLE
How to use Bluetooth 4.x?

### ISSUE THREAD

**Issue by mboworldbest** [microsoft/react-native-windows#4849]

**Comment by chrisglein** [comment]
Can you elaborate more? That's a pretty open ended question? :)
Code snippet, etc. Is this a RNW issue?

**Comment by mboworldbest** [comment]
yes, I need to develop the project IOT communication Bluetooth Low Energy for cross-platform 
with react-native-windows

**Comment by harinikmsft** [comment]
Hello @mboworldbest - Is there a specific cross-platform react-native BLE community module you are trying to use for Windows and it is not working for you? 

Or, if you are trying to develop with react-native to target Windows only, you can use [Native Modules](https://microsoft.github.io/react-native-windows/docs/native-modules) to access native [Windows Bluetooth APIs](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth?view=winrt-19041) yourself.

**Comment by mboworldbest** [comment]
hi harinikmsft,
yes, Thanks!

**Comment by SachinK25** [comment]
Hi @mboworldbest
were you able to implement  IOT communication Bluetooth Low Energy for cross-platform
with react-native-windows?

**Comment by shivamsaviant** [comment]
Is there any plugin that I can use directly on windows platform to achieve this instead of writing my own logic? Thanks
