### ISSUE TITLE
Silent Audio Playback from Native Module

### ISSUE THREAD

**Issue by rossbreytberg** [microsoft/react-native-windows#4850]
Hi,

I'm working on a text-to-speech native module for an app, which receives a text string from JS. However, despite trying several approaches including `MediaPlayer` and `AudioGraph`, I haven't been able to get the native module to play any sound.

I've confirmed the speech synthesizer parses the string into an audio stream correctly, because I tried saving it to a file and was able to playback the file successfully. 

Here's my native module:
```
#pragma once

#include <functional>
#include <string>
#include "pch.h"
#include "winrt/Windows.Foundation.h"
#include "winrt/Windows.Media.Core.h"
#include "winrt/Windows.Media.Playback.h"
#include "winrt/Windows.Media.SpeechSynthesis.h"
#include "winrt/Windows.Storage.Streams.h"
#include "NativeModules.h"

using namespace winrt;
using namespace winrt::Windows::Foundation;
using namespace winrt::Windows::Media::Core;
using namespace winrt::Windows::Media::Playback;
using namespace winrt::Windows::Media::SpeechSynthesis;
using namespace winrt::Windows::Storage::Streams;

namespace TwitchTTS
{
  REACT_MODULE(TextToSpeech)
  struct TextToSpeech {
 
    REACT_METHOD(speak);
    void speak(std::wstring text) noexcept
    {
      SpeakImpl(hstring(text));
    }

    REACT_EVENT(OnSpeak);
    std::function<void(double)> OnSpeak;

    IAsyncAction SpeakImpl(hstring text) noexcept {
      SpeechSynthesizer synthesizer = SpeechSynthesizer();
      SpeechSynthesisStream audioStream = co_await synthesizer.SynthesizeTextToStreamAsync(text);
      MediaPlayer mediaPlayer = MediaPlayer();
      mediaPlayer.AudioCategory(MediaPlayerAudioCategory::Communications);
      mediaPlayer.Source(MediaSource::CreateFromStream(
        audioStream,
        audioStream.ContentType()
      ));
      mediaPlayer.Play();
      OnSpeak(0);
    }
  };
}
```

Anyone know what might be missing, or if I've run into a bug?

**Comment by chrisglein** [comment]
@rossbreytberg Do you know if that code snippet works fine in a non-ReactNative UWP app? We're not personally familiar with the Media Player winrt API, so I can't say for sure if that's correct. Are you getting errors/logs? How does this compare to available samples?

**Comment by rossbreytberg** [comment]
@chrisglein thanks for the idea. In a non-ReactNative UWP app the same issue does occur, but can be solved by explicitly adding a `<MediaPlayerElement x:Name="mediaPlayerElement" />` to `MainPage.xaml`. Then with a call `mediaPlayerElement().setMediaPlayer(mediaPlayer)` from `MainPage.cpp`, any sounds played by `mediaPlayer` will be audible.

Is there a way I can add a hidden `<MediaPlayerElement />` to my ReactNative UI and reference it from my module? Or is there an alternative best practice here?

**Comment by chrisglein** [comment]
Sounds like you solved this by using a custom view manager, which is one of the 2 main ways to solve this. The other would be to add it in the host (which we do need to document better, noted by #4925). Essentially, either add your custom native XAML at the root, or embed with your own view manager.
