### ISSUE TITLE
Convert run-windows to Typescript 

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#4866]
Developer experience working on run-windows is suboptimal. Move this project to the typescript package format we've been using for override-tools, react-native-windows-init, react-native-window-codegen.

This can be done largely incrementally if we allow "implicit any".

**Comment by chrisglein** [comment]
Isn't there a specific Typescript template? #4505
My understanding is RN expectation is you get a JS project unless you use that template, and we have something blocking that template from working (that's the above issue).

Answer: This is about our code, not the app code stub.

Core code talking to facebook should be flow: #3166

This is about the CLI

**Comment by chrisglein** [comment]
Would be nice to align with macOS on this (maximize code sharing where we can).
