### ISSUE TITLE
Update C++/WinRT to version 2.0200508.4

### ISSUE THREAD

**Issue by vmoroz** [microsoft/react-native-windows#4868]
We have a new version of C++/WinRT available. We should move our code to the newer version to avoid accumulating technical debt.

**Comment by chrisglein** [comment]
@vmoroz Does every project that's compiling from source need to be aligned here? I know we've had problems with that in the past. Or is this in the post-binary world? As is seems like a breaking change?

**Comment by vmoroz** [comment]
I expect that customer code may use different version on C++/WinRT because it does not have the source dependency anymore on the Microsoft.ReactNative.dll. Even if the MS.RN.dll project is compiled in user solution, the dependency is always on binary .winmd and .dll files. It is different from the ReactUWP where we had dependency on C++ code.

Usually doing incremental updates is good. Last time we had a big issue to upgrade mostly because we were using a very old version. If we can incrementally update to the newer C++/WinRT as they release we should get much less pain.

**Comment by NickGerleman** [comment]
Current version used is `2.0.210312.4`. Anything left here to do?
