### ISSUE TITLE
Update the version of Microsoft.NETCore.UniversalWindowsPlatform

### ISSUE THREAD

**Issue by vmoroz** [microsoft/react-native-windows#4869]
We should update the .Net code dependency on Microsoft.NETCore.UniverslaWindowsPlatform from version 6.2.8 to 6.2.10.

**Comment by chrisglein** [comment]
@vmoroz Does this unblock anything with this? Does this come with a min target version update? What do we get from this?

**Comment by vmoroz** [comment]
@chrisglein, this is the list of issues fixed in the latest releases: https://github.com/microsoft/dotnet/blob/master/releases/UWP/net-native2.2/README.md

We are two releases behind on more than one year old version.
I would expect our customers prefer using the latest versions.

I am not aware about any immediate issue in our code that the new version addresses.

**Comment by vmoroz** [comment]
It is interesting to see that currently some of our projects use version 2.2.9 (Microsoft.ReactNative.Managed), and some version 2.2.10 (E2E tree dump). We better be consistent. Adding @dannyvv and @asklar for visibility.

**Comment by asklar** [comment]
I think this is probably ok? as long as the min version >= RS3 we should be ok to update this

**Comment by chiaramooney** [comment]
Flagged. With Fabric, this work might not be relevant anymore.
