### ISSUE TITLE
Build react-native-windows controls gallery app

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#4874]
We should build a "react-native-windows controls gallery" app.  It would serve several purposes:
-Help us validate quality, API completeness, Store deployment, etc.
-Give us a place to show off the full capabilities of the framework (including Windows-specific stuff)
-Acts as a forcing function for the team to wear their customer hat and use the framework end-to-end

**Comment by NickGerleman** [comment]
Potentially related to #4558 which tracks publishing playground as its own app during CI. Same theme of giving users something to play with the stack and validating our ability to deply.

**Comment by harinikmsft** [comment]
A comprehensive gallery app will take a while to build. To help stage things, here is an early strawman for a phased approach:
- Phase 1: Showcase for Core components with example usecases published to Windows store
- Phase 2: Take the above and output for Mac. At this point it becomes an “RN-desktop” sample gallery
- Phase 3: Add a few top community modules – especially the ones moved out of core
- Phase 4: Add a few FluentRN components once they have been stood up

And so on. There is an ongoing effort to make the RN Tester app be more modular, we may want to keep a pulse on that effort and see if we can leverage the infrastructure pieces from there to keep it consistent.

**Comment by chrisglein** [comment]
Would be great to hook up to AppCenter for easier deploy compared to XAML Controls Gallery

**Comment by kmelmon** [comment]
First version of app now complete.

**Comment by cameronmaske** [comment]
@kmelmon Congrats on the first version, any chance of a link to it?

**Comment by kmelmon** [comment]
@cameronmaske see:  https://github.com/microsoft/react-native-gallery
