### ISSUE TITLE
Children with negative margins yield unexpected behavior

### ISSUE THREAD

**Issue by Tatious** [microsoft/react-native-windows#4875]
### Steps to Reproduce

Create a view with a child that has a negative margin:

```
<View style={{ paddingLeft: 100, paddingTop: 200 }}>
  <View style={{ width: 200, height: 40, backgroundColor: 'green', borderRadius: 4 }}>
    <View
      style={{
        position: 'absolute',
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        borderWidth: 2,
        borderRadius: 10,
        borderColor: 'white',
        margin: -6,
      }}
    />
  </View>
</View>
```

### Expected Behavior

In this case, there is a border around the parent (iOS):
![IMG_0527](https://user-images.githubusercontent.com/32688486/81607215-2fcd2e80-9389-11ea-8ee3-49c6869dd072.PNG)

### Actual Behavior

The child view does not show: (Windows):
<img width="423" alt="Screen Shot 2020-05-11 at 1 08 13 PM" src="https://user-images.githubusercontent.com/32688486/81607225-32c81f00-9389-11ea-8a78-a936610c6846.png">

### Additional context

Adam Gorman(adamgor)
Austin Beaulieu(aubeauli)

**Comment by chrisglein** [comment]
May be a clipping issue?

**Comment by CarpeDiEmma** [comment]
Is there any headway or information with this? I am also running into this issue.

**Comment by HansHugli** [comment]
Yes, this is a negative margin issue. We are still experiencing this problem and it does cause problems for several desired scenarios

**Comment by chiaramooney** [comment]
Closing. Will not be an added feature for RNW on Paper. Will flag issue to make sure this behavior is supported on Fabric.
