### ISSUE TITLE
Add property to DatePicker that allows the user to control what type of calendar they want to display.

### ISSUE THREAD

**Issue by rectified95** [microsoft/react-native-windows#4879]
Add support for the CalendarIdentifier property.

Ref: https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.calendardatepicker?view=winrt-18362#globalization

**Comment by asklar** [comment]
@chrisglein do we have a globalization Area label? or a world readiness or enterprise readiness one?

**Comment by NickGerleman** [comment]
@rectified95 I see you have a PR out for the community module. To my understanding there is intent to remove the version we have in-tree once this happens, since the Windows version doesn't quite conform to a builtin RN API. Should we put the issue in the community module's repo? Relates to #4221

**Comment by chrisglein** [comment]
> @chrisglein do we have a globalization Area label? or a world readiness or enterprise readiness one?

Just "Area: Localization". Which is close but not the same. I'll rebrand it.

**Comment by rectified95** [comment]
@NickGerleman I was thinking about that, but thought it'd be strange to create an issue in that repo about updating a component that is not in it yet. Can move this issue there, once the check-in is made.

**Comment by chrisglein** [comment]
If we already have some issues on that repo, we might as well continue. @rectified95 can you migrate this issue to that repo and then we can close this out and track there.

**Comment by rectified95** [comment]
Created an issue in the community repo to track this work: https://github.com/react-native-community/datetimepicker/issues/165 

Closing. 
FYI @chrisglein
