### ISSUE TITLE
react-native run-windows can't find path because there is no /bin/ 

### ISSUE THREAD

**Issue by namrog84** [microsoft/react-native-windows#4881]
"react-native": "0.62.2",
"react-native-windows": "0.62.0-preview.5",
Using Visual Studio 2019  (16.5)

When using react-native run-windows, I receive this error. 
× Failed to deploy: Unable to find AppxManifest from "E:\repo\src\apps\ContentTestApp", using search path: "windows/{*/bin/x64/Debug,Debug/*}/AppxManifest.xml"

Because the correct path is
"E:\repo\src\apps\ContentTestApp\node_modules\react-native-windows\target\x64\Debug\ContentTestApp\AppxManifest.xml"

there is no /bin/ for us. The regexp is TOO specific.  This wasn't an override or anything to not put it in a bin, just by default VS it didn't go to /bin/ 
I haven't seen anything go to /bin in a long time. So I am not sure what is configured differently if anything. 

Suggested is to not have /bin/ in the path and/or also look for */x64/Debug/* in this case.

**Comment by chrisglein** [comment]
@namrog84 Just to clarify, you intentionally moved from a `bin` output to a `target` output?

Should be an easy fix, just want to understand.

**Comment by namrog84** [comment]
We never moved or changed the output from whatever the default project VS created some years ago. It always went to target instead of bin?

Where/how is that configured and I can check.
