### ISSUE TITLE
Remove AccessibilityStates from ViewWin32 Typings

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#4885]
ViewWin32 typings manually add states to AccessibilityStates even in 0.62. The API is going through removal and we don't want people targeting 0.62 to be able to use it. Change this to a fork of AccessibilityState in preparation for NetUI work.

**Comment by chrisglein** [comment]
@NickGerleman Is this pressing? Would we want to backport to 62? More context would be nice.

**Comment by NickGerleman** [comment]
@chrisglein we need to back port to 0.62 to prevent accessibility regressions that would come up due to people not removing usages of a removed api. Already talked to Eloy about fixing official typings.
