### ISSUE TITLE
'Question: File drag and drop'

### ISSUE THREAD

**Issue by ngburke** [microsoft/react-native-windows#4887]
Looking for some advice on how to implement file drag/drop from the desktop into the RNW app. 

In our prior app version with Electron and ReactXP, we were using a `View` component that had various `onDrag*` methods that yielded a [DataTransfer](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/files) type result to process dropped files. 

After looking through the React Native and your documentation, plus some searching I was not able to find a clear path forward here. Any tip in the right direction is much appreciated.

**Comment by chrisglein** [comment]
We don't have any immediate plans to build a file drag and drop solution, but you could write a custom view manager and do it there.

@harinikmsft can you track down a knowledgeable person about drag and drop to provide direction here?

**Comment by ngburke** [comment]
Any luck finding someone?

**Comment by dstaley** [comment]
As it turns out, adding drag and drop support (at least a basic version) is quite easy! I've uploaded an example project here https://github.com/dstaley/react-native-windows-drag-drop-sample

This particular example only handles text files, but it should provide most of what you need to at least get started adding support.

**Comment by ngburke** [comment]
Excellent, thank you for sharing. I'll give it a go shortly.

**Comment by harinikmsft** [comment]
Thanks @dstaley for the sample.

**Comment by DhanushSuryaM** [comment]
The same file was copied and implemented in my sample but it's not working. Except the code we need to add anything.

**Comment by chrisglein** [comment]
> The same file was copied and implemented in my sample but it's not working. Except the code we need to add anything.

If you're experiencing a problem implementing this can you open a new issue that captures your full repro?

**Comment by Victor0814gui** [comment]
is there an implementation of this in C++?
