### ISSUE TITLE
Setup E2ETest for React Native Win32/NetUI

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#4901]
https://github.com/microsoft/fluentui-react-native is building infrastructure to perform Appium based e2etests on Windows controls. Their matrix includes both XAML React Native WIndows and Office NetUI.

Core runtime and Platform JS for React Native Win32 lives in React Native Windows. We should test our changes against it.

Checks should not block check in since we will need to allowing breaking changes to view managers and native modules in this repo. React Native Win32 should initially just be a warning sign.

We should consider leveraging this for react-native-win32 to catch JS breaks. We cannot use it to catch native breaks yet due to the NetUI publish story, so we should not cause it to block check in.

**Comment by NickGerleman** [comment]
@samuelfreiberg is working on the efforts for Flurn. @asklar has been spending time trying to improve the reliability and coverage of E2ETest for XAML. It might be good for you two to talk to each other about the efforts your making so we can make both great (or even better share things 😀 ).

**Comment by asklar** [comment]
Yes, I spoke to Samuel the other day about run_wdio. @samuelfreiberg  check out the new doc content I created [here](https://github.com/microsoft/react-native-windows/blob/b05376dd911c8e965458c2df0853489be4241a9f/docs/e2e-testing.md#e2e-tests-and-masters)

**Comment by samuelfreiberg** [comment]
@asklar I will take a look, thanks! Turns our our CI needs more work in order to handle our E2E testing for Windows. I'm working on getting that squared away today and then I'll look into this more!

**Comment by chiaramooney** [comment]
Closing. We are migrating to testing Fabric which will no longer require a separate rn-win32 package.
