### ISSUE TITLE
Consider Moving Office React Native Sandbox Into React Native Windows

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#4902]
Office is a widely distributed brownfield (Islands style) application with high requirements for stability. To isolate from the instability of React Native, multiple teams within Office have built sandboxes for React Native. These are difficult to maintain using React Native's current boundaries, and multiple sandbox implementations exist.

We should consider leveraging this sandboxing work to offer better stability for our consumers who want headless integration.

**Comment by NickGerleman** [comment]
Is there a label we've been using for Islands related issues?

**Comment by chrisglein** [comment]
We don't have a ton of interest in headless+untrusted scenarios outside of Office, plus frankly we're not as familiar with it. Can you add some more detail on what the scenario and payoff is for this?

**Comment by NickGerleman** [comment]
One of the sandboxes is for untrusted code, the other is to isolate the overall app from instability from RNW.

There's been some discussion of what this could look like for scenarios with UI. Not much investigation happened there, but there was some talk of whether on Fabric we could share the shadow-node tree across processes since its immutable.

Part of this potentially requires the sandbox to be tied to some of the guts of RNW. In the past, teams have taken "creative" solutions to move parts of RNW out of process using the public APIs we expose.

Benefits would be:
1. Leveraging the work from Office to enable other brownfield apps a stable experience
2. Avoid fragmentation of different sandboxes
3. Allow sandboxing to work correctly with components on the inner boundary

This is very long-term, but the use-case is one we need to support.
