### ISSUE TITLE
The implementation of Back button doesn't make sense

### ISSUE THREAD

**Issue by acoates-ms** [microsoft/react-native-windows#4904]
The current implementation of BackHandler relies on the ReactRootControls to register for the window back button -- it also registers various keyboard handlers for the back button, at the ReactRootControl level, but that would break UI that is listening for those keyboard events above the rootview.

I think the BackHandler native module should be responsible for registering the SystemNavigationManager event.  -- I'm less sure where the keyboard event registrations should happen. -- Maybe those could be registered against the core window by the native module too?

**Comment by chrisglein** [comment]
Is currently crashing Win32 XAML islands...
Will need to at least address that, maybe just with a workaround for now.

**Comment by asklar** [comment]
Related: Reunion https://github.com/microsoft/ProjectReunion/issues/114

**Comment by chiaramooney** [comment]
Closing. Will not be implemented on RNW Paper. Flagging issue to ensure this is implemented correctly on Fabric.
