### ISSUE TITLE
Better error handling of Views inside Text components

### ISSUE THREAD

**Issue by acoates-ms** [microsoft/react-native-windows#4927]
#4921 fixed a crash when adding view's within a text element.  This is something thats supported on iOS and Android, but not currently in RNW.

The error provided in that case has lost all context of what caused the issue, and provides a very native specific error message that wont make sense to most JS / RN developers.  ("ViewViewManager::AddView expects a UIElement but got a Windows.UI.Documents.Span")

Instead we should reenable the check that used to exist in view.js to detect View's inside Text elements and report the error at the place where the app developer will get the exact location in their code thats causing the issue.
https://github.com/facebook/react-native/commit/a2285b17907cfd3d7cfd311e18027da800a48b2e#diff-a562e4a7ac9e900c6d2bc644453e9152

**Comment by chrisglein** [comment]
Text has lots of nesting problems: #3373 #3417. I think there are others too. 
Message isn't particularly understandable to React developers. Worth fleshing that out. Also... we should round up the issues and add support for this.
