### ISSUE TITLE
E2ETest is Flaky for TextInputTestPage

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#4934]
In this run we fail looking at TextInputTestPage https://dev.azure.com/ms/react-native-windows/_build/results?buildId=79994&view=logs&j=a27d21fd-a31d-5038-a902-0ee58cd3b281&t=6e4bfa1c-1783-56a1-0786-dc5a0d94bafb

In the next run, where the only difference is committing some auto-generated docs, we pass:
https://dev.azure.com/ms/react-native-windows/_build/results?buildId=80081&view=results

Some other runs seem to be hitting a similar issue with the same test page. E.g. https://dev.azure.com/ms/react-native-windows/_build/results?buildId=79709&view=logs&j=a27d21fd-a31d-5038-a902-0ee58cd3b281&t=6e4bfa1c-1783-56a1-0786-dc5a0d94bafb

**Comment by asklar** [comment]
Fixed by https://github.com/microsoft/react-native-windows/pull/5040
