### ISSUE TITLE
'Question: [How to generate signed appx so that it can be installable]'

### ISSUE THREAD

**Issue by ShivamJoker** [microsoft/react-native-windows#4936]
Hey I am trying to create a package which can be installable or playable on any windows 10 computer but even if i try installing in my computer it says 

```
Ask the app developer for a new app package. This one isn't signed with a trusted certificate (0x800B0100)
```

I also installed the temp pfx on my machine

**Comment by chrisglein** [comment]
There's an issue with certain versions of VS and certificates: #4836
(not specific to RN, is a UWP issue) 
Can you give us some more information on your environment? What version of Visual Studio? Have you enabled developer mode? Does it work when running from the CLI `run-windows`? It sounds like there are two computers here (a dev machine and a test machine), is that correct?
Can you run `npx react-native info`?
Also `yarn why react-native-windows`
