### ISSUE TITLE
'Question: [How to use FullTrustProcessLauncher in RNW application]'

### ISSUE THREAD

**Issue by RonAmihai** [microsoft/react-native-windows#4944]
I need to use external system EXEs in my RNW application. 

[As far as I have understood](https://stefanwick.com/2018/04/06/uwp-with-desktop-extension-part-1/), the best way to achieve this in UWP application is by using `FullTrustProcessLauncher`, alongside Windows Packaging Project as the startup project in the solution (and use win32 console application as a "launcher" for my system EXEs).

The question is how can I achieve this in RNW? 
How can I setup RNW to pick the packaging project in my solution instead of the default UWP? 

If It isn't possible, how should I use `FullTrustProcessLauncher` in RNW?

**Comment by asklar** [comment]
@RonAmihai  When you link in RNW into a RN app, a solution and project file will be generated for you. At that point, the project is a UWP project and the same customizations can be applied as to any other UWP apps.

**Comment by RonAmihai** [comment]
> @RonAmihai When you link in RNW into a RN app, a solution and project file will be generated for you. At that point, the project is a UWP project and the same customizations can be applied as to any other UWP apps.

Let me ask differently - how can I set `react-native run-windows` command to run the packaging project instead of the core UWP project? 

Running the packaging project through Visual Studio seems to throw some exceptions, I'll update here soon.

**Comment by asklar** [comment]
`react-native run-windows` would build the whole solution i.e. all of the projects in the solution, so if you add your packaging project to the solution it should get built. If VS is throwing an exception then that seems like a good first thing to investigate :)
