### ISSUE TITLE
Rename "master" Builds to "canary" or "nightly"

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#4963]
We currently release builds from our development branch as `0.0.0-master.xxx`. This scheme seems to be causing confusion. We should switch to `canary` to better set expectations. This should be safe to do since we haven't yet externally documented guarantees.

**Comment by NickGerleman** [comment]
This might mess with semver, but folks shouldn't be automatically consuming updates to our master build as is.

**Comment by chrisglein** [comment]
My preference is for `canary` given it doesn't imply a timeline.
