### ISSUE TITLE
WebView URL redirection does not work for RNW app 

### ISSUE THREAD

**Issue by harshadak2020** [microsoft/react-native-windows#4972]
### Issue
  WebView URL redirection does not work for RNW app 

### Steps to Reproduce
1. Created a fresh RN4W project.
2. Created a component to render a WebView and handle the onNavigationStateChange event
3. Imported this component in the App.js and used it:
4. Deployed the app on the Windows 10 Machine from Visual Studio(the issue is reproducible with both – Debug and Release mode)

### Expected Behavior: 
Whenever onNavigationStateChange Event occurs, the app should navigate to Bing.com page

### Actual Behavior/Issue:
The app instead continues to show the other URLs the user clicked on.
**Note: we tested the same app on Android and the issue does not happen there.**
 
### Reproducible Demo
The project is shared here: 
https://github.com/harshadak2020/ReactNativeForWindows2.git 

### Reference:
https://github.com/react-native-community/react-native-webview/blob/master/docs/Guide.md#controlling-navigation-state-changes 

### Environment
1.	`react-native -v` : react-native: 0.61.5
2.	`react-native run-windows --info`:
      System :
•	OS: Windows 10 10.0.19033
•	CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
•	Memory: 17.71 GB / 31.83 GB
•	Binaries:
•	Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
•	Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
•	npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
•	npmPackages:
•	react: 16.9.0 => 16.9.0
•	react-native: 0.61.5 => 0.61.5
•	react-native-windows: 0.61.0 => 0.61.0
•	rnpm-plugin-windows: ^0.6.1 => 0.6.1
•	Installed UWP SDKs:
•	10.0.16299.0
•	10.0.17134.0
•	10.0.17763.0
•	10.0.18362.0
•	10.0.19041.0

3. `reg query "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock"`
•	HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock
AllowDevelopmentWithoutDevLicense    REG_DWORD    0x1

### Target Platform Version(s):
•	10.0.17763.0
•	10.0.18362.0
•	10.0.19041.0

### Target Device(s): Desktop
Visual Studio Version: Visual Studio 2019
Build Configuration:
•	Debug – x64 and Release – x64

**Comment by chrisglein** [comment]
@kaiguo check in to see if this something broke with the transition, already broken, and if we can/should track in that repo? Or is this a result of using version 0.61?
(also, we should talk about this in a Monday design discussion about community module support)

**Comment by harinikmsft** [comment]
This is blocking an AppConsult customer. Bringing back to triage to reprioritize

**Comment by kaiguo** [comment]
@harshadak2020 looks like Windows didn't implement `onNavigationStateChange`, I'll add it. 

There's a workaround you can do to get unblocked, since onNavigationStateChange is just a callback for onLoadStart+onLoadEnd ([doc](https://github.com/react-native-community/react-native-webview/blob/master/docs/Reference.md#onnavigationstatechange)), I think you can use [onLoadStart](https://github.com/react-native-community/react-native-webview/blob/master/docs/Reference.md#onloadstart) for redirects.

**Comment by kaiguo** [comment]
Ah, ignore my previous comment (onNavigationStateChange is implemented on js side so it should work). 

@harshadak2020 your repro project is no longer available so I'm not sure how you are doing the redirect, I tried the following and it seemed to be working.
``` js
  handleWebViewNavigationStateChange = newNavState => {
    if (url.includes('google.com')) {
      const newURL = 'https://reactnative.dev/';
      const redirectTo = 'window.location = "' + newURL + '"';
      this.webview.injectJavaScript(redirectTo);
    }
  };
```
There was a bug in `injectJavaScript`, you probably hit that. Updating to the latest version of WebView module should fix it. If you are on RNW 0.61, use WebView 10.0.0 (no caret). RNW 0.62 use WebView ^10.1.0.
