### ISSUE TITLE
Question: C# Native Module that uses P/Invoke on x64

### ISSUE THREAD

**Issue by erksch** [microsoft/react-native-windows#4978]
Hey there!

I am trying to write a C# Native Module that uses a SWIG wrapper for a C API with P/Invoke and DLLImports.
When I run the solution with Debug x86 it works fine but as soon as I switch to x64 it fails with the following error:
```
'Could not load type 'System.Runtime.InteropServices.HandleRef' 
from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.'
``` 
So I guess `HandleRef` can not be found in `System.Runtime.InteropServices`. 
Why does this work for x86 but not for x64. Is there a workaround to use the same code anyway?

**Comment by erksch** [comment]
I fixed by replacing `HandleRef` with `IntPtr` to my best knowledge and it fixed the error.
I'll update if that actually works, and would still like to know why that is.

**Comment by asklar** [comment]
@erksch you can't load a binary of a different bitness. If a process is x86, all its libraries must be x86. If it's x64, all its libraries must be x64. The way to solve cross bitness scenarios usually involves running the library in a hosting process that matches the library bitness, and then IPC/marshal the calls back and forth between the app and this hosting process.
I'm not sure what you were able to achieve by replacing HandleRef with IntPtr, nor do I know anything about SWIG, but you can't mix and match library and app bitness.

**Comment by erksch** [comment]
Thanks for the answer!
But I guess HandleRef/IntPtr/PInvoke and arch issues are not really related to RNW anyway, so closing :)
