### ISSUE TITLE
I18nManager has options to force LTR but only affects new root views

### ISSUE THREAD

**Issue by acoates-ms** [microsoft/react-native-windows#4998]
If the app sets I18n.allowRTL(false), or I18n.forceRTL(true) it should affect the app immediately.

But this setting is only used in `NativeUIManager::AddRootView` - which seems wrong.

This needs more investigation.

**Comment by chrisglein** [comment]
Pushes to the root view, but if you already had one created it won't affect that.

**Comment by chiaramooney** [comment]
Connected https://github.com/microsoft/react-native-windows/issues/4770?
