### ISSUE TITLE
Consume RNW native modules through NuGet

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#5008]
This is an opportunity to provide a simple e2e experience for developers writing RNW apps.
Publish Native Modules nugets that can easily be added to a RNW solution.
Each nuget would contain the DLL/WinMD/props/targets to link in that native module automatically.

This is in addition to the autolinking / CLI way of doing things "the RN way", the point is to provide a one-click way of getting this working in a well established dev workflow like NuGet.

**Comment by chrisglein** [comment]
Is this in addition to autolinking or in opposition?
This makes sense from the perspective of the Windows-first developer, but how would it filter out to their Android/iOS projects?
Talk to @jonthysell who's been working through autolinking requirements.

**Comment by chrisglein** [comment]
Good topic for a Monday meeting :)
