### ISSUE TITLE
Restructure directories

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#5014]
The directory structure is a little messy right now. Here's a proposal:
```
/
              Src
              Test
              CLI
              Docs
              Node_modules
              Packages
              Apps
              Build
              Desktop
              Other directories like .ado, .github, etc.
```

**Comment by JunielKatarn** [comment]
A few considerations:
- Why leave `Desktop` our of `Src`? It's true it may eventually disappear, but it IS actual source code.
- Is the `Build`+`Target` convention not good enough for intermediate outputs / final outputs? Don't we want to keep those separated?
- While this is not addressed in the issue description, it would be convenient to keep the main solution (`Microsoft.React.sln`) in the repo root, for ease of command-line building.

**Comment by asklar** [comment]
> A few considerations:
> 
> * Why leave `Desktop` out of `Src`? It's true it may eventually disappear, but it IS actual source code.
> * Is the `Build`+`Target` convention not good enough for intermediate outputs / final outputs? Don't we want to keep those separated?
> * While this is not addressed in the issue description, it would be convenient to keep the main solution (`Microsoft.React.sln`) in the repo root, for ease of command-line building.

* I think Desktop should be separate for now as we don't expect most contributors to have to even know there is a desktop variant. The product we're building for everybody (except Office) as "RNW" is a UWP-targetting RN.

* I personally find the names/distinction between Build and Target confusing. I'm fine keeping those separate, but maybe as "obj" and "bin" instead?

* +1 to keeping the main solution `Microsoft.ReactNative.sln` at the root.

**Comment by NickGerleman** [comment]
This gets super wonky on the JS side with us needing to replicate the structure of RN. I.e. we need to put targets for Libraries, RNTester, etc in the root directory. Was looking at how we might be able to fix this, but ACoates thought we couldn't really easily do this.

**Comment by chrisglein** [comment]
Let's give ample bake time on this and lots of discussion before we take action, as we don't want to churn this with intermediate results. Shop it around, get feedback/requirements.

**Comment by vmoroz** [comment]
I was thinking about the restructuring the set of projects we have as part of the Core DLL effort. I should get a proposal for the folder structure soon. Though, I do not have much thoughts about the JS and RNTester parts.
Also, it would be nice to have a high level project structure to match common open source practices. For example, please have a look at https://github.com/vector-of-bool/pitchfork and the related links. The common high level project folder structure lowers barrier of entry for the new developers.
As for the 'Desktop', I would rename it to 'Legacy' as we work towards restructuring and removing it at some point. Going forward we will provide UWP and Win32 application support, and the Desktop/Legacy code will go away as soon as Office code starts to use ABI-safe API.

**Comment by chrisglein** [comment]
@acoates-ms You've mentioned that there's some strict requirements on directory structure that results from what the package needs. Can you link to or capture those requirements here? Our files we can edit, versus built ones that need to show up in the package.
This came from mentioning `vnext\src` -> `src\src`.

**Comment by asklar** [comment]
* Npm package has reqs on directory structure so that JS content matches RN
  * Vnext\src can be renamed
  * Vnext\src\Libraries gets copied onto a built folder: vnext\Libraries
    * Vnext\Libraries must keep its name
    * Package.json+vnext\libraries should be under source control tree - not under Built



* RNW should go into the \packages folder. NodeJS Packages vs NuGet packages
  * Neither nodejs packages nor nuget packages folders are hardcoded, they're just default. Can we update one of these?
  * May not be a big deal if it's only RNW devs affected

* Should Local-cli be its own nodejs package folder? It has to be tightly coupled to RNW's package. React-native-windows-init has a dependency on local-cli.

* Test sibling of src
* Desktop is only consumed via nuget [by Office] so it can be pulled out

* Put C++ and C# code into src

* Once we are producing nuget we can revise how we get folly, mso, etc. (e.g. submodule instead of download source during build)

* Clean up vnext\scripts - #5147 

* Test apps in \packages is ok
* Native tests separate

* Consider renaming desktop to Legacy
* Build/Target is an Office naming convention, let's look for an OSS convention

* MRN.sln location?
  * Root?
  * Packages\RNW?
  * Bigger solution - avoids rebuilding the same thing over and over, can be at root
  * Smaller solution in project location

* Incremental build and project dependencies issues - #5147


* Should be able to run CI locally - #5149

**Comment by JunielKatarn** [comment]
Still don't see the value of having the Desktop source code as a sibling to the actual source code directory. It creates two C++ code paths that ultimately consume the common base.

I insist Desktop should be kept within the 'src' directory, and eventually eliminated.
This would be clearer to understand and more disruptive.

"Legacy" is also not a very accurate name, for it's not "the legacy implementation of RNW". It's more the current implementation for the Desktop variant. When it becomes unnecessary, we just remove the folder.
