### ISSUE TITLE
Enable long path support in rnw-dependencies

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#5015]
When an enlistment clone is created in a deep part of the filesystem, sometimes we can get build breaks if the paths we deal with are >MAX_PATH. 
Enabling long paths should palliate that.

https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#enable-long-paths-in-windows-10-version-1607-and-later

**Comment by JunielKatarn** [comment]
Sample command-line workaround (pending #5012):
```
msbuild.exe Microsoft.ReactNative.sln /p:RootOutDir=D:\short
```

Outputting the target artifacts to a shorter root path allows keeping the cloned sources in place for now.
