### ISSUE TITLE
IViewManagerWithNativeProperties should expose UpdateProperty instead of UpdateProperties

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#5029]
Today, the `IViewManagerWithNativeProperties` interface exposes `UpdateProperties`. This does not allow detecting Unimplemented Properties. Instead, we should be exposing/using `UpdateProperty` and letting the `ViewManagerBase` class iterate through the set of properties.

If we don't do this we have lots of false positive debug spew when interacting with a control implemented in a native module - it will report all properties as not implemented (Igor ran into this).

https://github.com/microsoft/react-native-windows/blob/f467d8b06d481b6e36a7cd239608594017f4ebbf/vnext/Microsoft.ReactNative/IViewManager.idl#L47

**Comment by chrisglein** [comment]
Goal here is to reduce the false positive debug spew. If we can do that without an interface breaking change that'd be preferable. But if it's necessary it's necessary.

**Comment by asklar** [comment]
we should revisit for RNW on WinAppSDK. CC @AgneLukoseviciute

**Comment by chiaramooney** [comment]
Not something we plan to address on the Paper renderer as we move towards Fabric.
This behavior should be different on the new renderer.
