### ISSUE TITLE
Queue up CallJSFunction while bundle is loaded

### ISSUE THREAD

**Issue by vmoroz** [microsoft/react-native-windows#5057]
While working on implementing unit tests I have noticed that we have a race condition for the native module initialization. A native module can be initialized before the JS bundle is completed to load.
It means that any calls to CallJSFunction are ignored.
There are two possibilities to fix it:
1. Queue up all CallJSFunction calls until the JS bundle finishes to load.
1. Initialize the native modules only after the JS bundle is loaded.

Both approaches will not work for the JSI-based synchronous communication, but queuing up sounds to be better in the long run because the native module is initialized before its constants are requested. Otherwise it will be impossible to provide meaningful constant without valid ReactContext.

**Comment by asklar** [comment]
For startup perf I think we don't want to delay NM init until after the bundle is loaded but at the same time we want correctness :)
is it safe for a NM to proceed after queuing a call? or do NMs expect that these calls be sync?

**Comment by vmoroz** [comment]
All current NM calls to JS side are asynchronous. It is fine to continues after queuing the calls. it must not affect any visible behavior as it used to be, but it will help to fix crashes or other random not functioning code because we have a race condition today.
I have discovered this issue while writing an integration test for the ReactNativeHost component. Without the queuing the test just hangs.
