### ISSUE TITLE
Handling page unresponsiveness in react native webview for windows

### ISSUE THREAD

**Issue by NandhiniVishwanath** [microsoft/react-native-windows#5075]
I have an url that is loaded on webview from react-native, which renders information from an API response. However, if the api response is taking time, the app is getting hanged, not allowing user to perform any further action. I tried to load the same url on web browser, seems like this is actually happening when the page becomes unresponsive. However in browser we get a popup which says page unresponsive, with options kill pages or wait, but in webview I dont see any popup shown. Is there a way to show these popup on webview so that the user can take an action or any event that can be used to handle this issue, so that I can programmatically close the webview? Please let me know.

**Comment by chrisglein** [comment]
@kaiguo Can you check in here and potentially migrate this issue to the WebView repo as appropriate?

**Comment by kaiguo** [comment]
@NandhiniVishwanath WebView has [onLoadStart](https://github.com/react-native-community/react-native-webview/blob/master/docs/Reference.md#onloadstart) and [onLoadEnd](https://github.com/react-native-community/react-native-webview/blob/master/docs/Reference.md#onloadend) callbacks which can be useful here. You can add [setTimeOut](https://www.w3schools.com/jsref/met_win_settimeout.asp) in `onLoadStart` and clears it in `onLoadEnd`.
