### ISSUE TITLE
Support "react-native-sensitive-info"

### ISSUE THREAD

**Issue by harshadak2020** [microsoft/react-native-windows#5076]
# Support "react-native-sensitive-info"

## Basic Info
- Module Repo URL: https://github.com/mcodex/react-native-sensitive-info

- Target version: ^5.5.5
- [x] Module has a Legacy/C# implementation (if so, [link](https://github.com/mCodex/react-native-sensitive-info/tree/master/windows/RNSensitiveInfo))

## Functionality

react-native-sensitive-info manages all data stored in Android Shared Preferences, iOS Keychain and Windows Credentials. You can set and get all key/value using simple methods.

## Which app/customer is requesting this module?
An AppConsult TAP customer is impacted with this issue

**Comment by bzoz** [comment]
PR with C++ implementation: https://github.com/mCodex/react-native-sensitive-info/pull/239

**Comment by chrisglein** [comment]
PR has been merged, directory updated.
