### ISSUE TITLE
Support react-native-file-viewer

### ISSUE THREAD

**Issue by harshadak2020** [microsoft/react-native-windows#5077]
# Support "react-native-file-viewer"

## Basic Info
- Module Repo URL: https://github.com/vinzscam/react-native-file-viewer#readme

- Target version: ^2.0.2
- [x] Module has a Legacy/C# implementation (if so, [link](https://github.com/vinzscam/react-native-file-viewer/tree/master/windows))

## Functionality

Native file viewer for react-native. Preview any type of file supported by the mobile device.

iOS: it uses QuickLook Framework

Android: it uses ACTION_VIEW Intent to start the default app associated with the specified file.

Windows: Start the default app associated with the specified file.

## Which app/customer is requesting this module?
An AppConsult TAP customer is impacted with this issue

**Comment by stmoy** [comment]
Note that there is a PR out for this module: https://github.com/vinzscam/react-native-file-viewer/pull/80

**Comment by chrisglein** [comment]
Assigning to you @stmoy to track that @qmatteoq has a PR up for this (since I can't assign the issue to him). PRs been up for awhile - do we think it's ready and need to ping the repo owner?

**Comment by chiaramooney** [comment]
Not something we plan to address on the Paper renderer as we move towards Fabric. If you would like to see support for this module on Fabric. Please file the issue on the react-native-file-viewer module.

**Comment by AhmedMustafa505** [comment]
Are there any updates regarding the issue of library not working in RNW ??
