### ISSUE TITLE
Publishing NuGet Packages Broken for RNW 0.62

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#5079]
We see errors after the change from @tudorms about multiple copies of the ReactNativeWindows project in the universal solution. 

`Error parsing solution file at D:\a\1\s\vnext\ReactWindows-Universal.sln: Exception has been thrown by the target of an invocation.  The solution file has two projects named "ReactWindowsCore".  D:\a\1\s\vnext\ReactWindows-Universal.sln`

https://dev.azure.com/ms/react-native-windows/_build/results?buildId=82226&view=results

Unsure of why this wasn't caught by PR validation. Possibly there is some setup difference or this was related to image changes?

**Comment by NickGerleman** [comment]
This likely only impacts RNW developers instead of end-users.

**Comment by tudorms** [comment]
@asklar Do you have any ideas here? The file is identical to what we had in master when you did the change there.

**Comment by asklar** [comment]
@tudorms right - I think you might need #5012 but that might be too intrusive for a backport.
An easy fix would be to change the display name for one of the projects:
e.g. change:
```
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "ReactWindowsCore", "ReactWindowsCore\ReactWindowsCore.vcxitems", "{11C084A3-A57C-4296-A679-CAC17B603145}"
EndProject
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "ReactWindowsCore", "ReactWindowsCore\ReactWindowsCore.vcxproj", "{11C084A3-A57C-4296-A679-CAC17B603144}"
```

into
```
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "ReactWindowsCore-Items", "ReactWindowsCore\ReactWindowsCore.vcxitems", "{11C084A3-A57C-4296-A679-CAC17B603145}"
EndProject
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "ReactWindowsCore", "ReactWindowsCore\ReactWindowsCore.vcxproj", "{11C084A3-A57C-4296-A679-CAC17B603144}"
```

**Comment by tudorms** [comment]
So master branch publish was broken back then 3 weeks ago? I'm trying to figure out how we can catch something like this in the future.

**Comment by tudorms** [comment]
> An easy fix would be to change the display name for one of the projects:

Visual Studio doesn't like that, it just reverts the change.

**Comment by NickGerleman** [comment]
Closing since we're able to publish now.
