### ISSUE TITLE
Accessibility Conformance test pass

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#5089]
This came out of as part of taking the Accessibility C+ AI course (see https://learningplayer.microsoft.com/activity/S2586609/launch)

We should perform a test pass over our accessibility features and validate that react-native-windows meets basic accessibility requirements.  One option is to do a formal accessibility conformance test pass, as described here:
https://microsoft.sharepoint.com/teams/ceacc/_layouts/15/Doc.aspx?sourcedoc={bc7bfa47-ea7c-4801-95a9-dd353ecde6a8}&action=edit&wd=target%28C%2BE%20Accessibility.one%7Ca475a190-f7ae-4c58-84b0-9bbcb43d4bf2%2FDHS%20Trusted%20Tester%20Program%7Ce511e88e-fadb-4350-bdda-2b7452e969f3%2F%29

This will tell us how well RNW actually conforms to the accessibility standard.

**Comment by chrisglein** [comment]
To get this we'll need an app to target. Best candidate would be some sort of gallery app (#4874), which is the process that we follow for core XAML platform testing. Once we have that app, we should target the Accessibility audit against that. We may need more than one app, but that's a good place to start.

**Comment by chrisglein** [comment]
Could also benefit from a manual control-by-control-centric approach that's less outsourced but would give us higher level data. Obviously need to figure out how to carve out time for that and be clear what bar we're applying.

**Comment by chiaramooney** [comment]
Does the test pass we now do on Gallery fulfill this?

**Comment by chrisglein** [comment]
> Does the test pass we now do on Gallery fulfill this?

I'd say yes! We are doing regular accessibility conformance passes via the Gallery app now. This is complete.
