### ISSUE TITLE
onMouseEnter doesn't trigger on View where backgroundColor is not set

### ISSUE THREAD

**Issue by MasonBergstrom** [microsoft/react-native-windows#5094]
### Environment
- React Native Windows Version: `0.62.0-preview.6`

- Target Platform Version(s): `10.0.18362.0`

- Target Device(s): `Desktop`

- Visual Studio Version: `16.6.0`

- Build Configuration: `Debug`

### Steps to Reproduce

1. Create a View, DON'T set a backgroundColor style
1. Add onMouseEnter prop to View
1. See that onMouseEnter doesn't trigger inside View

### Expected Behavior

1. View should trigger onMouseEnter

### Actual Behavior

Nothing happens

### Additional context

XAML apps won't trigger mouse events if they aren't hit-testable: https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/events-and-routed-events-overview#hit-testing-and-input-events

This behavior is different from other implementations of React. This should either be well documented or, a default backgroundColor of "transparent" should be applied to Views so they trigger the mouse events.

**Comment by chrisglein** [comment]
We could set a default backgroundColor of "transparent" on everything. We will be able to share the brushes, so that's okay, but of course it's going to bring a bunch more nodes into hit test calculations. One way to limit that would be to only do it if `onMouseEnter` is set, that way it's pretty scoped.

May be opportunities to tidy this up with WinUI3.

**Comment by TheSavior** [comment]
This sounds like the same problem we are having on Messenger. Labeling with the partner tag.

**Comment by TheSavior** [comment]
We've bumped into this bug in a couple more places that we've had to work around (for example `backgroundColor: 'rgba(0,0,0,.01)'`). It would be great to get this bumped up in priority as we only know to add these workarounds when something is broken on Windows that works on Mac vs systematically.

**Comment by chrisglein** [comment]
> We've bumped into this bug in a couple more places that we've had to work around (for example `backgroundColor: 'rgba(0,0,0,.01)'`). It would be great to get this bumped up in priority as we only know to add these workarounds when something is broken on Windows that works on Mac vs systematically.

From native you can set background to transparent, which is treated differently from null. For the cases where you have a custom native control.
