### ISSUE TITLE
Get Started not working

### ISSUE THREAD

**Issue by rubens-schmitz** [microsoft/react-native-windows#5111]
### Environment

1. `react-native -v`:
Not using global react-native.

2. `react-native run-windows --info`:
Not using global react-native.

3. `reg query "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock"`
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock
    AllowDevelopmentWithoutDevLicense    REG_DWORD    0x1
    AllowAllTrustedApps    REG_DWORD    0x1

1. `react-native -v`:
Not using global react-native.
3. `npm ls react-native-windows`:
C:\Users\r
`-- (empty)

4. `node -v`:
v12.9.1

5. `npm -v`:
6.10.2

6. `yarn --version`:
Not using yarn

- Target Platform Version(s):
10.0.18362.1
10.0.17763.132

- Target Device(s):
Desktop

- Visual Studio Version:
Installed 2019, however there is some 2017 Build Tools installed somehow. But I'm using VSCode.

- Build Configuration:
I don't know.

### Steps to Reproduce

1.Do whatever [rnw-dependencies](https://microsoft.github.io/react-native-windows/docs/rnw-dependencies) tells you to do.
2.Do whatever [get-started](https://microsoft.github.io/react-native-windows/docs/getting-started) tells you to do

### Expected Behavior

To work

### Actual Behavior

r@DESKTOP-8P2ILP1 MINGW64 ~/viewer
$ npx react-native-windows-init --overwrite
npx: installed 114 in 29.703s
Reading application name from package.json...
Reading react-native version from node_modules...
Reading react-native version from node_modules...
Latest matching version of react-native-windows for react-native@0.61.5 is react-native-windows@0.61.11
Installing react-native-windows@^0.61.0-0...
npm WARN @typescript-eslint/eslint-plugin@1.13.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/parser@1.13.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-react@7.12.4 requires a peer of eslint@^3.0.0 || ^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-react-native@3.6.0 requires a peer of eslint@^3.17.0 || ^4 || 
^5 but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})        

react-native-windows@0.61.9 successfully installed.
Cannot find module '@react-native-community/cli/build/tools/copyAndReplace'
Require stack:
- C:\Users\r\viewer\node_modules\react-native-windows\local-cli\generator-common\index.js
- C:\Users\r\viewer\node_modules\react-native-windows\local-cli\generator-windows\index.js
- C:\Users\r\viewer\node_modules\react-native-windows\local-cli\generate-windows.js  
- C:\Users\r\AppData\Roaming\npm-cache\_npx\6048\node_modules\react-native-windows-init\lib-commonjs\Cli.js
- C:\Users\r\AppData\Roaming\npm-cache\_npx\6048\node_modules\react-native-windows-init\bin.js
Error: Cannot find module '@react-native-community/cli/build/tools/copyAndReplace'   
Require stack:
- C:\Users\r\viewer\node_modules\react-native-windows\local-cli\generator-common\index.js
- C:\Users\r\viewer\node_modules\react-native-windows\local-cli\generator-windows\index.js
- C:\Users\r\viewer\node_modules\react-native-windows\local-cli\generate-windows.js  
- C:\Users\r\AppData\Roaming\npm-cache\_npx\6048\node_modules\react-native-windows-init\lib-commonjs\Cli.js
- C:\Users\r\AppData\Roaming\npm-cache\_npx\6048\node_modules\react-native-windows-init\bin.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)      
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (C:\Users\r\viewer\node_modules\react-native-windows\local-cli\generator-common\index.js:4:24)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\r\\viewer\\node_modules\\react-native-windows\\local-cli\\generator-common\\index.js',
    'C:\\Users\\r\\viewer\\node_modules\\react-native-windows\\local-cli\\generator-windows\\index.js',
    'C:\\Users\\r\\viewer\\node_modules\\react-native-windows\\local-cli\\generate-windows.js',
    'C:\\Users\\r\\AppData\\Roaming\\npm-cache\\_npx\\6048\\node_modules\\react-native-windows-init\\lib-commonjs\\Cli.js',
    'C:\\Users\\r\\AppData\\Roaming\\npm-cache\\_npx\\6048\\node_modules\\react-native-windows-init\\bin.js'
  ]
}

-------------------------------------------------------------------------------

[Info] Starting Packager

┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│  Running Metro Bundler on port 8081.                                         │
│                                                                              │
│  Keep Metro running while developing on any JS projects. Feel free to        │
│  close this tab and run your own Metro instance if you prefer.               │
│                                                                              │
│  https://github.com/facebook/react-native                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

Looking for JS files in
   c:\Users\r\viewer 

[Info] Packager started.

[Info] Prewarming bundle cache. This may take a while ...

[Info] About to get: http://localhost:8081/index.bundle?platform=windows

::1 - - [03/Jun/2020:16:35:49 +0000] "GET /favicon.ico HTTP/1.1" 404 150 "http://localhost:8081/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36"
Loading dependency graph, done.
[Info] Building and running application.

error: bundling failed: Error: Unable to resolve module `../Components/AccessibilityInfo/AccessibilityInfo` from `node_modules\react-native\Libraries\react-native\react-native-implementation.js`: 

None of these files exist:
  * node_modules\react-native\Libraries\Components\AccessibilityInfo\AccessibilityInfo(.native|.windows.js|.native.js|.js|.windows.json|.native.json|.json|.windows.ts|.native.ts|.ts|.windows.tsx|.native.tsx|.tsx)
  * node_modules\react-native\Libraries\Components\AccessibilityInfo\AccessibilityInfo\index(.native|.windows.js|.native.js|.js|.windows.json|.native.json|.json|.windows.ts|.native.ts|.ts|.windows.tsx|.native.tsx|.tsx)
    at ModuleResolver.resolveDependency (c:\Users\r\viewer\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (c:\Users\r\viewer\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (c:\Users\r\viewer\node_modules\metro\src\node-haste\DependencyGraph.js:282:16)
    at Object.resolve (c:\Users\r\viewer\node_modules\metro\src\lib\transformHelpers.js:267:42)
    at c:\Users\r\viewer\node_modules\metro\src\DeltaBundler\traverseDependencies.js:426:31
    at Array.map (<anonymous>)
    at resolveDependencies (c:\Users\r\viewer\node_modules\metro\src\DeltaBundler\traverseDependencies.js:423:18)
    at c:\Users\r\viewer\node_modules\metro\src\DeltaBundler\traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (c:\Users\r\viewer\node_modules\metro\src\DeltaBundler\traverseDependencies.js:87:24)
 BUNDLE  [windows, dev] ./index.js ▓░░░░░░░░░░░░░░░ 6.3% (2/8), failed.

[Error] Error: Error while executing command 'c:\Users\r\viewer\node_modules\.bin\react-native.cmd run-windows --proxy --no-packager': Error while executing command 'c:\Users\r\viewer\node_modules\.bin\react-native.cmd run-windows --proxy --no-packager' (error code 101)

::ffff:127.0.0.1 - - [03/Jun/2020:16:36:08 +0000] "GET /index.bundle?platform=windows HTTP/1.1" 500 - "-" "-"

### Additional context

Tried something but got nothing

r@DESKTOP-8P2ILP1 MINGW64 ~/viewer
$ npm i --save-dev @react-native-community/cli
npm WARN @typescript-eslint/eslint-plugin@1.13.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/parser@1.13.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-react@7.12.4 requires a peer of eslint@^3.0.0 || ^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-react-native@3.6.0 requires a peer of eslint@^3.17.0 || ^4 || 
^5 but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN @react-native-community/cli@4.9.0 requires a peer of react-native@^0.62.0-rc.0 but none is installed. You must install peer dependencies yourself.

npm ERR! path C:\Users\r\viewer\node_modules\@react-native-community\cli-server-api\node_modules\mime
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\r\viewer\node_modules\@react-native-community\cli-server-api\node_modules\mime' -> 'C:\Users\r\viewer\node_modules\@react-native-community\cli-server-api\node_modules\.mime.DELETE'       
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\r\AppData\Roaming\npm-cache\_logs\2020-06-03T16_49_10_299Z-debug.log

**Comment by temetvince** [comment]
Confirmed an issue for me as well.

**Comment by wagnerma** [comment]
For me, it is also not working, but in an other area:

Fehler "0x80073CF3" beim AppX Deployment-Vorgang für Paket "d3b72452-3ec2-4715-a716-22882e9e22cb_1.0.0.0_x86__gvrvptvq5k5s6". Der
                                       Fehlertext lautet: Das Paket d3b72452-3ec2-4715-a716-22882e9e22cb_1.0.0.0_x86__gvrvptvq5k5s6 kann von Windows nicht installiert werden, da
                                       es von einem Framework abhängig ist, das nicht gefunden wurde. Stellen Sie das von CN=Microsoft Corporation, O=Microsoft Corporation,
                                       L=Redmond, S=Washington, C=US veröffentlichte Framework Microsoft.VCLibs.140.00.Debug mit einer neutralen oder x86-Prozessorarchitektur und
                                       Mindestversion 14.0.27810.0 zusammen mit dem zu installierenden Paket bereit. Die derzeit installierten Frameworks mit dem Namen
                                       Microsoft.VCLibs.140.00.Debug sind: {Microsoft.VCLibs.140.00.Debug_14.0.27810.0_x86__8wekyb3d8bbwe
                                       Microsoft.VCLibs.140.00.Debug_14.0.27810.0_x64__8wekyb3d8bbwe}

Some dependencies seems missing. It is quite difficult to get all right. It would be fantastic if all ist managed through a packet manager to get the stuff right, like npm or cargo.

My Env:
  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 8.80 GB / 15.42 GB
  Binaries:
    Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 16.11.0 => 16.11.0
    react-native: ^0.62.0-0 => 0.62.2
    react-native-windows: ^0.62.0-0 => 0.62.0-preview.9
  Installed UWP SDKs:
    10.0.17763.0
    10.0.18362.0

**Comment by chrisglein** [comment]
This is the key indicator I'm seeing:

> react-native-windows@0.61.9 successfully installed.
Cannot find module '@react-native-community/cli/build/tools/copyAndReplace'

Which is this issue #4882.
This occurs from a preexisting global installation. The docs have been updated to indicate some steps for how to address this: https://microsoft.github.io/react-native-windows/docs/getting-started#install-react-native-for-windows
I also understand that we have a fix coming in 0.63 that will fix this particular CLI issue. 

@rubens-schmitz give those steps a try, hope that unblocks you.
