### ISSUE TITLE
Work out how to use XAML codegen in MS.RN

### ISSUE THREAD

**Issue by acoates-ms** [microsoft/react-native-windows#5116]
Currently there are a couple of places where we are using XAML markup in MS.RN.  In particular the devmenu and redbox.  In both these cases we are using markup in a string and calling XamlReader::Load.  It would be great if we could use a more normal XAML dev experience with markup, x:Bind etc.  However, the normal winrt dev experience requires the XAML file have an idl file, which would add the control to the public interface of the dll.  We dont want to add these to the public interface.

**Comment by chrisglein** [comment]
Interfaces in winRT can be private, but the classes/structs have to be public. Is that potentially impacting this?

**Comment by NickGerleman** [comment]
I think we're doing this now. Is there anything that still needs to be addressed?
