### ISSUE TITLE
Image 'tintColor' style prop does not apply 

### ISSUE THREAD

**Issue by mtalley** [microsoft/react-native-windows#5124]
### Environment

D:\src\rnwtest> react-native -v
react-native-cli: 2.0.1
react-native: 0.62.2

D:\src\rnwtest> react-native run-windows --info
  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
    Memory: 11.63 GB / 31.94 GB
  Binaries:
    Node: 10.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.13.0 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 16.11.0 => 16.11.0
    react-native: ^0.62.0-0 => 0.62.2
    react-native-windows: ^0.62.0-0 => 0.62.0-preview.9
  Installed UWP SDKs:
    10.0.16299.0
    10.0.17763.0
    10.0.18362.0

D:\src\rnwtest> reg query "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock"

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock
    AllowDevelopmentWithoutDevLicense    REG_DWORD    0x1
    AllowAllTrustedApps    REG_DWORD    0x1

Then, specify:

- Target Platform Version(s): 10.0.18362.0

- Target Device(s): Desktop

- Visual Studio Version: 2019

- Build Configuration: Release

### Steps to Reproduce

When hosting an image (a png with transparency, for this example) in the `Image` component, assign a style that populates the `tintColor` property.

### Expected Behavior

Color information for non-transparent pixels in the image are replaced with the provided `tintColor` per react-native spec: https://reactnative.dev/docs/image#style 

![image](https://user-images.githubusercontent.com/1459302/83819285-4d3aa300-a67e-11ea-9579-5a7582741ddb.png)

### Actual Behavior

Image source is rendered as if no `tintColor` was provided.

![image](https://user-images.githubusercontent.com/1459302/83819308-5c215580-a67e-11ea-92fc-1024314efbf4.png)

### Reproducible Demo

```
<Image
        style={{tintColor: '#FF0000', height: 256, width: 256}}
        source={{uri: 'https://github.com/microsoft/react-native-windows/raw/master/.github/hero2.png'}}
      />
```

**Comment by chrisglein** [comment]
Will require dropping down to composition and creating an effect, similar to #2631.

**Comment by jdschinan** [comment]
Hey there, the tintColor doesnt work when using the components property.

<Image
       tintColor={'#FF0000'}
        style={{height: 256, width: 256}}
        source={{uri: 'https://github.com/microsoft/react-native-windows/raw/main/.github/hero2.png'}}
      />
