### ISSUE TITLE
Default app crashes on Windows 10 1709 and 1803

### ISSUE THREAD

**Issue by RatikKapoor** [microsoft/react-native-windows#5132]
### Environment

If you are using latest version:
1. `3.2.1`:
2. `  System:
    OS: Windows 10 10.0.16299
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 3.00 GB / 5.86 GB
  Binaries:
    Node: 12.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
    react-native-windows: ^0.61.11 => 0.61.11
  Installed UWP SDKs:
    10.0.18362.0
`:
3. `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock
    AllowAllTrustedApps    REG_DWORD    0x1
    AllowDevelopmentWithoutDevLicense    REG_DWORD    0x1`

Otherwise if `--info` doesn't exist:
1. `react-native -v`:
3. `npm ls react-native-windows`:
4. `node -v`:
5. `npm -v`:
6. `yarn --version`:

Then, specify:

- Target Platform Version(s): 10.0.16299+

- Target Device(s): Windows 10 Desktops/Laptops

- Visual Studio Version: 2019

- Build Configuration: Debug

### Steps to Reproduce

(Write your steps here:)

1. `npx react-native init testingApp --version ^0.61.5`
2. `yarn install`
3. Build solution in VS2019 as Debug
4. Run `yarn start`
5. Start app from VS
6. Default React Native app is visible and can scroll around, clicking any link will crash it

### Expected Behavior

(Write what you thought would happen.)

Clicking link in set of default links will open link. 

### Actual Behavior

(Write what happened. Add screenshots!)

The app faces an exception and cannot continue. This issue is not present in 1809 or higher builds of Windows. Apps developed on those builds of Windows work great from Debug development to Release deployment. I have not yet been able to get past initial screen on 1709 and 1803. Please see screenshot below.

### react-native run-windows --logging

There are no issue in compiling using this method either

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

Running the default app generated by instructions at https://microsoft.github.io/react-native-windows/docs/getting-started will reproduce this issue. The same instructions work fine on newer builds of Windows. I have also tested on three different VMs and one real computer with the 16299 build and all crash.

### Additional context

(Write any other additional context that may help in root causing the issue.)

Event Viewer points the faulting module name to be ReactNative.dll when testing a Release build. When testing Debug the error points to the location shown in the image attached. Any help is greatly appreciated, thank you!
![VS2019Error](https://user-images.githubusercontent.com/14501811/83913714-17a0c300-a72d-11ea-93a0-44f019e81f90.png)

**Comment by asklar** [comment]
`UIElement.RotationAxis` is only available in 1809 (RS5) and up so it makes sense that the API crashes in 1709 and 1803. We should fix this if we want to support RS3 and RS4.

**Comment by asklar** [comment]
@RatikKapoor see [Win10 compatibility](https://microsoft.github.io/react-native-windows/docs/win10-compat) for details on which versions are compatible. Native animations are not available in 1709 and 1803 .

**Comment by RatikKapoor** [comment]
Thank you @asklar, in my opinion it is fine if animations do not work but the React Native app will still be semi-usable until the user upgrades their version of windows. I apprecaite you looking into this!

**Comment by RatikKapoor** [comment]
Also, once your pull request is accepted, is there a quicker way to use this in my app than to wait for the next release?

**Comment by RatikKapoor** [comment]
I tested the patch this morning and that seems to be working well. There is another issue in CxxNativeModule.cpp that seems to be causing touble in 1709 and 1803. @asklar would you know if this is related to this animations issue? This again was caused by clicking a link inside the default Welcome to React Native app.
![Annotation 2020-06-09 122222](https://user-images.githubusercontent.com/14501811/84185399-2ef0f080-aa4c-11ea-8bec-d60f9eebe2a4.png)

**Comment by tbottke** [comment]
Hello, @RatikKapoor were you able to fix that? I'm running into the same problem right now ( Windows 10 1709 ).

**Comment by asklar** [comment]
@RatikKapoor @tbottke could you post the full content of the stack trace window at the point of failure? It's possible there is a similar issue elsewhere

**Comment by tbottke** [comment]
@asklar thanks for your quick response. When I click on continue after the first exception occurs I will get to the point where     
```
template <typename D> WINRT_IMPL_AUTO(void) consume_Windows_UI_Xaml_IUIElement8<D>::KeyboardAcceleratorPlacementMode(Windows::UI::Xaml::Input::KeyboardAcceleratorPlacementMode const& value) const
    {
        check_hresult(WINRT_IMPL_SHIM(Windows::UI::Xaml::IUIElement8)->put_KeyboardAcceleratorPlacementMode(static_cast<int32_t>(value)));
    }
```
throws an error.


![react_native_info](https://user-images.githubusercontent.com/70366492/106250816-706d2080-6214-11eb-81a6-2ca5938ba08c.PNG)
![first_error](https://user-images.githubusercontent.com/70366492/106250814-6f3bf380-6214-11eb-8371-580848993bdc.PNG)
![second_error](https://user-images.githubusercontent.com/70366492/106250819-706d2080-6214-11eb-9271-c3f5b614093d.PNG)

**Comment by tbottke** [comment]
When I out comment the line in the last screenshot I get to the point where I can see the react native template app. When I click on a link like @RatikKapoor already said in his last post I'm getting the same error thrown at me like he did.

**Comment by asklar** [comment]
@tbottke could you copy/paste the content from the `Call stack` window at the bottom of the screen?

**Comment by tbottke** [comment]
@asklar I applied your fix there is still some errors (2nd_callstack) after clicking on continue I get another error. 

![callstack](https://user-images.githubusercontent.com/70366492/106255816-cb097b00-621a-11eb-9760-c47211ee52ca.PNG)
![2nd_callstack](https://user-images.githubusercontent.com/70366492/106255817-cb097b00-621a-11eb-9f4e-b52045f8a901.PNG)
![after_clicking_link_callstack](https://user-images.githubusercontent.com/70366492/106255812-ca70e480-621a-11eb-85ff-72e9c146f5e5.PNG)

**Comment by asklar** [comment]
@tbottke If I remember correctly, that one is due to a VS bug in the designer. You might be able to work around that bug by disabling the designer (Debug > Options):
![image](https://user-images.githubusercontent.com/22989529/106256228-daafa200-61cf-11eb-9a21-46bf06ed24cb.png)

Try launching the app from the start menu instead of VS, it might not crash that way :)

**Comment by tbottke** [comment]
@asklar app launch is fine from the menu after clicking on a link in the app it crashed again.

**Comment by tbottke** [comment]
![after_clicking_link](https://user-images.githubusercontent.com/70366492/106256878-24be7500-621c-11eb-91fc-6870ec51d31c.PNG)

**Comment by asklar** [comment]
thanks. It's likely there will be more call sites calling APIs not available on RS3, as we aren't really testing on Windows versions that are that old. If possible I'd recommend you get onto a newer version of Windows. If this is still blocking you, could you file a new issue so we have a clean one to track?

**Comment by tbottke** [comment]
@asklar thanks for your help 👍 it is indeed blocking me so I will create a new issue.
