### ISSUE TITLE
Upgrade C# codegen to .net 6 / LTS

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#5146]
Currently the C# codegen project uses .netcoreapp 2.2.
With .net core 5 supporting UWP, it would be a good opportunity to have everything in one framework and not have to hack around .net core 2.2 + UWP unsupported-ness.

**Comment by chrisglein** [comment]
.netcore 5 is currently in preview. This will need to wait for it to be released, then we can clean all this up.

**Comment by asklar** [comment]
@dannyvv want to assign this to yourself to do when .net core 5 RTMs?

**Comment by dannyvv** [comment]
NetCore 5 is not out yet, but we just updated to 3.1
