### ISSUE TITLE
run-windows fails to fail in CI

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#5153]
When `run-windows` fails, it fails to set the exitcode which would tell ADO that it failed. So ADO thinks it succeeded and continues merrily.
See: https://dev.azure.com/ms/react-native-windows/_build/results?buildId=85285&view=logs&j=02e0f8ca-f841-5ce7-6017-ca58c2eabceb&t=2dc7ee33-ee04-56af-37c0-a2c6518a947f&l=8383

**Comment by rectified95** [comment]
@asklar as discussed before, I've reproduced the failing run locally, and run: echo %ERRORLEVEL% - it output '0'
