### ISSUE TITLE
LinearGradientBrush doesn't work for HighContrastBlack

### ISSUE THREAD

**Issue by gary-hu-ms** [microsoft/react-native-windows#5160]
### Environment
"react-native-windows": "0.60.0-vnext.155",
Window desktop
sdk: 10.0.18362
vs 2017

### Description
I have defined HighContrastWhite and HighContrastBlack ResourceDictionary in ThemeDictionaries. 
 the SolidColorBrush with "ThemeResource SystemColorWindowColor" works fine.
 the LinearGradientBrush value of customized value doesn't work well. when switching from non-hc to HighContrastBlack, the LinearGradientBrush somehow always picks brush from HighContrastWhite.

 <ResourceDictionary.ThemeDictionaries>
                <ResourceDictionary x:Key="Default">
 		      <LinearGradientBrush x:Key="DrivePickerDownwardFade" StartPoint="0.5,0" EndPoint="0.5,1">
                        <GradientStop Offset="0" Color="#80000000" />
                        <GradientStop Offset="0.6" Color="#B3171717" />
                        <GradientStop Offset="0.9" Color="#171717" />
                        <GradientStop Offset="1" Color="#171717" />
                    </LinearGradientBrush>

                    <LinearGradientBrush x:Key="BackgroundImageDownwardFade100" StartPoint="0.5,0" EndPoint="0.5,1">
                        <GradientStop Offset="0" Color="#00171717" />
                        <GradientStop Offset="1" Color="#171717" />
                    </LinearGradientBrush>
                </ResourceDictionary>
                <ResourceDictionary x:Key="HighContrastBlack">
                    <SolidColorBrush x:Key="DrivePickerDownwardFade" Color="{ThemeResource SystemColorWindowColor}"/>

                     <LinearGradientBrush x:Key="BackgroundImageDownwardFade100" StartPoint="0.5,0" EndPoint="0.5,1">
                        <GradientStop Offset="0" Color="Red" />
                        <GradientStop Offset="1" Color="Blue" />
                    </LinearGradientBrush>
                </ResourceDictionary>
                <ResourceDictionary x:Key="HighContrastWhite">
<SolidColorBrush x:Key="DrivePickerDownwardFade" Color="{ThemeResource SystemColorWindowColor}"/>

                    <LinearGradientBrush x:Key="BackgroundImageDownwardFade100" StartPoint="0.5,0" EndPoint="0.5,1">
                        <GradientStop Offset="0" Color="Yellow" />
                        <GradientStop Offset="1" Color="Green" />
                    </LinearGradientBrush>

                </ResourceDictionary>
            </ResourceDictionary.ThemeDictionaries>

### Steps to Reproduce

(Write your steps here:)

1. Start app with HighContrastBlack, noticed the LinearGradientBrush is using color from HighContrastBlack.
2. Switch from HighContrastBlack to HighContrastWhite, noticed the LinearGradientBrush is using color from HighContrastWhite
3. Switch from HighContrastWhite to HighContrastBlack, noticed the LinearGradientBrush is still using color from HighContrastWhite, seems like HighContrastWhite color is picked prior to HighContrastBlack.

### Expected Behavior

  Expect the LinearGradientBrush align with the theme settings.

(Write what you thought would happen.)

### Actual Behavior

the LinearGradientBrush somehow always picks brush from HighContrastWhite.

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

### Additional context

(Write any other additional context that may help in root causing the issue.)

**Comment by chrisglein** [comment]
This looks like a core XAML issue, not specific to react-native-windows. In which case you should migrate this issue to the WinUI repo: https://github.com/Microsoft/microsoft-ui-xaml/issues

It's possible that linear gradients are suppressed by default when high contrast is enabled, and that's causing this issue. If so, it'd be good to have a way to opt out of that behavior (for XAML authors that know what they're doing and are making high contrast friendly gradients). I'm not sure if that exists. I'm not even certain if that's what's happening here.

@kikisaints Can you advise on what the interaction is between high contrast and gradients? (preparing you for when this issue arrives on the WinUI repo)

**Comment by gary-hu-ms** [comment]
I will move this to ui-xaml nothing did in RNW. Thanks @chrisglein
