### ISSUE TITLE
Autolinking Checks Will Not Consistently Run When Using Binary Distribution Because FastUpToDateCheck Enabled

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#5168]
By default Visual Studio has its own set of incremental build logic where it will not re-run msbuild targets unless a project filter file has been edited. This provides incorrect results when targets depend on files outside of filters (e.g. something in node_modules).

For react patching we get around this by setting `<DisableFastUpToDateCheck>true</DisableFastUpToDateCheck>`. This property present in any open project will cause Visual Studio to disable the optimization (with a restart potentially required to take affect).

Using binary distribution/experimental Nuget means we will no longer include projects including the React patching target which sets this prop. This impacts autolinking, and potentially other scenarios, which do not disable the optimization, but do rely on its behavior to get correct builds. @jonthysell  mentioned we have some other targets impacted.

**Comment by NickGerleman** [comment]
Adding recent regression and bug labels to track this, since it will be impacting if we turn on binary distribution by default

**Comment by jonthysell** [comment]
How do I link a target to an input file when it doesn't actually use the input file? It looks like I would have to add `package.json` or `react-native.config.js` as files in the app project and copy them to the output.
