### ISSUE TITLE
Support react-native-permissions

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#5172]
# Support `react-native-permissions` on RNW

## Basic Info
- Module Repo URL: [react-native-permissions](https://github.com/react-native-community/react-native-permissions)
- Target version: 
- [ ] Issue exists on module repo (if so, [link]())

- [ ] Module has a Legacy/C# implementation (if so, [link]())

## Which app/customer is requesting this module?

Partner: Facebook

## In what scenarios will this module be used?

We would have used this module to grant access to the webcam and microphone.

**Comment by TheSavior** [comment]
We would have used this module to grant access to the webcam and microphone. We are planning to bridge those methods ourselves minimally since this module doesn’t exist.

**Comment by bzoz** [comment]
PR with Windows implementation for the module: https://github.com/zoontek/react-native-permissions/pull/530

**Comment by chrisglein** [comment]
This should be clear to close as the PR has been merged. @stmoy as an FYI.
Although [React Native Directory](https://reactnative.directory/?search=react-native-permissions) doesn't list it yet. @stmoy are you including that in the checklist for modules or are we handling it in batches?

**Comment by stmoy** [comment]
> Although React Native Directory doesn't list it yet. @stmoy are you including that in the checklist for modules or are we handling it in batches?

@chrisglein - handling in batches. Closing this and adding it to the next "batch".
