### ISSUE TITLE
Problem with stale vnext\react-native.config.js

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#5188]
when creating an app with the local repo as source/CLI, you end up with a copy from vnext which for some reason puts react-native.config.js into the app's folder, but then this breaks Metro
![image](https://user-images.githubusercontent.com/22989529/84464927-a54b4980-ac2a-11ea-83d6-f6ea0db9029a.png)
and it's pretty hard to debug why my app is trying to access my repo clone
Keith mentioned ACoates said we might not need this file and it certainly has nefarious effects, so this tracks possibly getting  rid of it

**Comment by chrisglein** [comment]
Andrew says we can't get rid of this file. It's how Metro knows where RNW is. This is the mechanism for how we plug into the CLI.

Did something break about the file copy? Didn't get a new version of the file on `init`. Was looking for RNW in the wrong place.

**Comment by chrisglein** [comment]
Sounds like there were some additional steps here to run `init` again. Can you spell out the repro steps?

**Comment by asklar** [comment]
might not be an issue anymore, closing for now
