### ISSUE TITLE
Cannot add/init rn-windows on existing 0.61.5 Project. Works on fresh 0.61.5 project

### ISSUE THREAD

**Issue by creambyemute** [microsoft/react-native-windows#5190]
### Environment

If you are using latest version:
1. `react-native -v`:
`bash: react-native: command not found`
2. `react-native run-windows --info`:
`bash: react-native: command not found`
3. `reg query "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock"`
```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock
    AllowDevelopmentWithoutDevLicense    REG_DWORD    0x1
    AllowAllTrustedApps    REG_DWORD    0x1
```

Otherwise if `--info` doesn't exist:
1. `react-native -v`:
`bash: react-native: command not found`
3. `npm ls react-native-windows`:
`-- (empty)`
4. `node -v`:
`v12.9.1`
5. `npm -v`:
`6.10.2`
6. `yarn --version`:
`1.22.0`

- Target Platform Version(s):
None, can't init

Desktop

- Visual Studio Version: 2019

- Build Configuration: Would be Debug if init works

### Steps to Reproduce

1. `npx react-native init myProject` (version does not matter)
2. `cd myProject/`
3. Create a .npmrc with a registry in myProject
4. `npx react-native-windows-init --overwrite`

### Expected Behavior

It installs/inits react-native-windows in the existing project

### Actual Behavior
```
$ npx react-native-windows-init --overwrite
npx: Installierte 115 in 4.557s
Reading application name from package.json...
Reading react-native version from node_modules...

No compatible version of react-native-windows found.
The latest supported version is react-native-windows@0.61.9.
Please modify your application to use react-native@^0.61 or another supported version of react-native and try again.

```

### Additional context

* Our project is using react-native 0.61.5. I can clearly see it in node_modules, it's the same as if I create a new react-native 0.61.5 project.
* Creating a new react-native 0.61.5 project and running `npx react-native-windows-init --overwrite` works
* We have a .npmrc with our own registry, If I comment/delete that it works. Why is that? Why is it only a problem for react-native-windows?

**Comment by chrisglein** [comment]
May be a bug with how the CLI is handling npmrc files.
Is it correct that you're unblocked by putting it back after the init?
(regardless we'll want to investigate - just want to know if you're unblocked)

**Comment by creambyemute** [comment]
@chrisglein Yes after the initial init, the `rm -rf node_modules/ && yarn` works. So we're not blocked by that.
