### ISSUE TITLE
Error while publishing app to Windows store Windows Runtime metadata validation FAILED Type name correctness

### ISSUE THREAD

**Issue by coronatime2020** [microsoft/react-native-windows#5201]
Hi everyone,

Windows Runtime metadata validation FAILED Type name correctness Error Found: The type name correctness test detected the following errors: Impact if not fixed: Microsoft store doesn't allow apps that don't pass Windows Runtime Metadata Validation. How to fix: Please ensure there are no Windows Runtime types in the global namespace or in the Windows top-level namespace.

Can tell me where to look and what?

**Comment by asklar** [comment]
@coronatime2020 sounds like it's saying you have types in the global namespace (or in the Windows namespace) and that's not allowed for UWP apps. Make sure whatever types your app consumes (and your app's type too) are in some namespace. BTW this isn't specific to React Native for Windows though, just a general UWP requirement.

**Comment by coronatime2020** [comment]
@asklar what is global namespace (or in the Windows namespace)? 😂

**Comment by asklar** [comment]
@coronatime2020 take a look at [Diagnosing Windows Runtime errors](https://docs.microsoft.com/en-us/windows/uwp/winrt-components/diagnosing-windows-runtime-component-error-conditions) doc. Basically you need something like:
```cs
namespace MyNamespaceName {
... // your code goes here
}
```

**Comment by coronatime2020** [comment]
@asklar can i use this code in uwp app?
App.xaml.cs
`
using Windows.ApplicationModel.Activation;
using Windows.Foundation;
using Windows.UI.Core;
using Windows.UI.ViewManagement;
`
`
protected override void OnLaunched(LaunchActivatedEventArgs e)
{
  base.OnLaunched(e);
  ApplicationView.GetForCurrentView().SetPreferredMinSize(new Size(500, 500));
  SystemNavigationManager.GetForCurrentView().AppViewBackButtonVisibility =         AppViewBackButtonVisibility.Collapsed;
}
`
