### ISSUE TITLE
Build "react-native-platform-integrate" script

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#5207]
We want to automate integration with RN core. Apart from existing platform override logic we need to handle things like bumping package dependencies, generating commits for changes, etc.

We need to build a script to do this. This is conceptually similar to the evergreen script we had in most of 0.60 and below.

**Comment by chrisglein** [comment]
@NickGerleman This one sounds like goodness. Do you think you're getting to this in 0.63? I'm currently viewing it as a stretch goal that would be nice to have but I don't know if it's on your hit list.

**Comment by NickGerleman** [comment]
We have the initial bits with the integrate-rn script. Will create some followup items for it later.
