### ISSUE TITLE
Automatically Create an Issue if a Publish Job Fails

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#5210]
We will sometimes see issues that break our publish pipeline that go unnoticed for some time. We should add a step to our publish definition to create an issue in our repo if the pipeline fails.

**Comment by chrisglein** [comment]
Publishing nightly on master, and after each change on stable branches. This is all after you check in, so this can't be part of a PR check. So we need some sort of new mechanism here.
Whether this is an email or issue, we need to know who to direct it to. We can start broad (email core team) and go from there.

**Comment by NickGerleman** [comment]
We have a general need for reporting when our automated processes go wrong beyond just this one even. E.g. when automatic integration fails, which is what led to me thinking about this. I haven't looked at what ADO has built-in yet. Issue creatiion via the Github rest API seems simple to script, but I would be a bit surprised if there wasn't a built-in email based solution.

**Comment by NickGerleman** [comment]
Re: the built in way to do this, AzDo lets you set up notifications for build failure and add a query for a specific definition (Publish). That seems like a simple option, but we're also going to be automated processes using the GH REST API anyway, so I'd almost rather create issues, since we'd want to anyway for real failures (assuming they aren't too spamy).
