### ISSUE TITLE
Native Modules must be run in JS queue

### ISSUE THREAD

**Issue by vmoroz** [microsoft/react-native-windows#5211]
We should change the code to always use the JS queue for native modules.

Currently we do not specify the queue where the native modules run. We create a new serial queue for them. In the "classic" ReactNative each module can specify the queue where it runs. In the newer versions of ReactNative the plans are that all TurboModules run in the JS queue. 

Since we did not implement the correct "classic" RN threading yet, we have a good chance to implement the future-proof behavior where all modules are run in JS queue without affecting existing code.

**Comment by asklar** [comment]
@vmoroz I thought modules calls run on the UI thread? e.g. CreateView returns a xaml element so it has to either run on the ui thread, or post a message to the ui thread to create it, wait, and return it...

**Comment by vmoroz** [comment]
@asklar, all calls to native modules originate from the JS queue. RN native modules can specify on what queue they must be called. Some of them specify the UI thread. When we implemented the ABI-safe boundary and the ABI-safe native modules (aka "NativeModules 2.0"), we did not implement a mechanism to associate them with a queue. Currently, the "NativeModules 2.0" use a background serial queue. The proposed change is about the "NativeModules 2.0" and any internal modules that are moving to this model.

Recently we had discussed with @acoates-ms the "NativeModules 2.0" association with a queue and he suggested to ask Facebook team about the future plans for the queue association. I have received a response on the Discord #turbomodules channel that the current plans are to move all TurboModules interaction to JS queue. Any current UI-bound modules must do the call marshaling to UI on their own.

As for the CreateView calls, I think the best approach is to have a UI model updated in JS queue and marshal changes to that model to the UI thread. It means that the CreateView call must synchronously create a View "shadow" node in JS thread and return it immediately. Then, the creation of this shadow node is marshaled to the UI thread and causes creation of the XAML View element. This way we can keep the work in JS queue to be very fast and not be blocked by every single interaction with UI thread. We essentially would have a one-way flow of changes from JS queue to UI queue.

The only problem is when JS needs a value from UI thread. There are several ways a native module can address it:
- Make the API asynchronous and let the JS observe the async result.
- Return cached or 'fake/lie' value first and then provide the real one asynchronously through an event.
- For application initial value, we can add a mechanism where a list of modules initialize their initial values from the main thread. This way instead of 'fake/lie' values they can use the initial values.
- Block the JS queue until UI queue results are ready. (It can be quite dangerous and inefficient.)

I hope some new patterns may emerge, but as a first step we must establish the initial baseline where all "NativeModules 2.0" use JS queue instead of a newly created serial queue.

**Comment by acoates-ms** [comment]
@vmoroz , just for clarification, CreateView is part of a viewManager, and all viewmanager calls will continue to be posted to the UI thread.  -- When we move the UIManager to NM2, we'll have to write it so that it forwards its calls to the UI thread.
