### ISSUE TITLE
Support react-native-safe-area-context

### ISSUE THREAD

**Issue by creambyemute** [microsoft/react-native-windows#5230]
# Support `react-native-safe-area-context` on RNW

## Basic Info
- Module Repo URL: [https://github.com/th3rdwave/react-native-safe-area-context]()
- Target version: ?
- [ ] Issue exists on module repo (if so, [link]())
- [ ] Module has a Legacy/C# implementation (if so, [link]())

## Which app/customer is requesting this module?
React-Navigation is using react-native-safe-area-context, so a big part of the RN Community.

## In what scenarios will this module be used?
React-Navigation Dependency

## Essential Features
I think this was mostly created for the notches and statusbar/navBar handling.

Could this just be stubbed? I'm not aware of notches on Windows.

**Comment by kmelmon** [comment]
Related to #3884

**Comment by kmelmon** [comment]
This is needed to implement react-navigation

**Comment by kmelmon** [comment]
@harinikmsft this would be a good first task for our partner team as it helps unblock the dependency chain for react-navigation (see #3884)

**Comment by kaiguo** [comment]
Done by https://github.com/th3rdwave/react-native-safe-area-context/commit/a10b7eafd800bb97c7c7c4ff049c5e19cc0ff9a9.
