### ISSUE TITLE
Trying to set min window size crashes React Native app

### ISSUE THREAD

**Issue by RatikKapoor** [microsoft/react-native-windows#5232]
### Environment

If you are using latest version:
1. `react-native -v`: 3.2.1
2. `react-native run-windows --info`: `System: OS: Windows 10 10.0.16299 CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz Memory: 3.00 GB / 5.86 GB Binaries: Node: 12.17.0 - C:\Program Files\nodejs\node.EXE Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD npmPackages: react: 16.9.0 => 16.9.0 react-native: 0.61.5 => 0.61.5 react-native-windows: ^0.61.11 => 0.61.11 Installed UWP SDKs: 10.0.18362.0`
3. `reg query "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock"`
`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock AllowAllTrustedApps REG_DWORD 0x1 AllowDevelopmentWithoutDevLicense REG_DWORD 0x1`

Then, specify:

- Target Platform Version(s): 1803+

- Target Device(s): Windows 10 Desktops/Laptops

- Visual Studio Version: VS2019

- Build Configuration: Debug and Release

### Steps to Reproduce

(Write your steps here:)

1. Inside App.xaml > App.cpp
2. Add ApplicationView::GetForCurrentView() call as shown in image
![Annotation 2020-06-16 110934](https://user-images.githubusercontent.com/14501811/84805698-e85a4380-afc1-11ea-8556-7d3afe31a9f9.png)
3. App crashes, this behaviour can be replicated on any new React Native Windows app. However, creating a new UWP C++ app (not RN) and using this code works to set window sizing.

### Expected Behavior

(Write what you thought would happen.)
App size is correctly set as desired.

### Actual Behavior

(Write what happened. Add screenshots!)
App crashes and exception is thrown.
![Annotation 2020-06-16 110527](https://user-images.githubusercontent.com/14501811/84805629-cb257500-afc1-11ea-9a33-be4bc977f9d0.png)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)
This can be reproduced on any starter RNW app.

### Additional context

(Write any other additional context that may help in root causing the issue.)
Something that may help in diagnosing the issue that that any call to GetForCurrentView() seemingly crashes the app.

**Comment by chrisglein** [comment]
Can you provide the stack for the crash?
@kmelmon Can you attempt to repro this and see if we see the same? (no clue if this is affected between 61->62)

**Comment by RatikKapoor** [comment]
Thanks for looking into this @chrisglein. 

This image is the crash when resize view is tried:
![Annotation 2020-06-18 130215](https://user-images.githubusercontent.com/14501811/85061588-50e12600-b164-11ea-9c7d-9f0b5d5ecf3e.png)

This image is the stack when SetPrefferedMinSize is called
![Annotation 2020-06-18 130354](https://user-images.githubusercontent.com/14501811/85061643-6a826d80-b164-11ea-804e-32b9c980ef40.png)

Please let me know if you need any further information.

**Comment by kmelmon** [comment]
This looks to be a WinUI3 issue:
https://github.com/microsoft/microsoft-ui-xaml/issues/2509

**Comment by asklar** [comment]
@kmelmon I don't think @RatikKapoor is running the experimental WinUI 3 code, in fact the stack shows `Windows.UI.ViewManagement` not `Microsoft.UI.ViewManagement`, so I think this is different.

@RatikKapoor when you hit a crash, you can save a crash dump by going to the Debug menu in VS and clicking Save Dump. If you are comfortable with it, you can upload this to your OneDrive and send us the link, and I can take a look at why it's crashing for you. Note that crash dumps might include personally identifiable information.
![image](https://user-images.githubusercontent.com/22989529/85219913-5739f280-b35c-11ea-9549-f2a31507b4ca.png)

**Comment by kmelmon** [comment]
@asklar Maybe this is also happening with WinUI2?

I can easily repro this on a "hello world" CLI app.  Just use this for your App.cpp

#include "pch.h"

#include "App.h"
#include "ReactPackageProvider.h"



using namespace winrt::my61test;
using namespace winrt::my61test::implementation;
using namespace winrt::Windows::UI::ViewManagement;
using namespace winrt::Windows::Foundation;

/// <summary>
/// Initializes the singleton application object.  This is the first line of
/// authored code executed, and as such is the logical equivalent of main() or
/// WinMain().
/// </summary>
App::App() noexcept
{
    MainComponentName(L"my61test");

#if BUNDLE
    JavaScriptBundleFile(L"index.windows");
    InstanceSettings().UseWebDebugger(false);
    InstanceSettings().UseFastRefresh(false);
#else
    JavaScriptMainModuleName(L"index");
    InstanceSettings().UseWebDebugger(true);
    InstanceSettings().UseFastRefresh(true);
#endif

#if _DEBUG
    InstanceSettings().EnableDeveloperMenu(true);
#else
    InstanceSettings().EnableDeveloperMenu(false);
#endif

    auto appView = ApplicationView::GetForCurrentView();
    appView.SetPreferredMinSize(Size(200, 650));
    ApplicationView::PreferredLaunchViewSize(Size(200, 650));
    ApplicationView::PreferredLaunchWindowingMode(ApplicationViewWindowingMode::PreferredLaunchViewSize);

    PackageProviders().Append(make<ReactPackageProvider>()); // Includes all modules in this project

    REACT_REGISTER_NATIVE_MODULE_PACKAGES(); //code-gen macro from autolink

    InitializeComponent();

    // This works around a cpp/winrt bug with composable/aggregable types tracked
    // by 22116519
    AddRef();
    m_inner.as<::IUnknown>()->Release();
}

**Comment by asklar** [comment]
Thanks @kmelmon for the repro. This is failing because there is no `CoreWindow` for the calling thread yet at the time of creating the App (we get an `E_NOTFOUND` hresult out of twinapi_appcore). I think it's illegal to call `ApplicationView` functionality in an app's constructor since the app seems to get constructed before the `CoreWindow`. 

@RatikKapoor - try moving the call to ApplicationView into `OnLaunched` instead, that should work.

**Comment by asklar** [comment]
filed https://github.com/MicrosoftDocs/winrt-api/issues/1698

**Comment by RatikKapoor** [comment]
Thank you @asklar and @kmelmon! I added the following code to App.cpp:
`void App::OnLaunched(Windows::ApplicationModel::Activation::LaunchActivatedEventArgs const& /*e*/)
    {
        super::OnLaunched(e);
        ApplicationView::GetForCurrentView().SetPreferredMinSize(Size(200, 650));
        ApplicationView::PreferredLaunchViewSize(Size(200, 650));
        ApplicationView::PreferredLaunchWindowingMode(ApplicationViewWindowingMode::PreferredLaunchViewSize);
    }`

And App.h looks like this:
`namespace winrt::beta::implementation
{
    struct App : AppT<App>
    {
        App() noexcept;
        void OnLaunched(Windows::ApplicationModel::Activation::LaunchActivatedEventArgs const&);

    private:
        using super = AppT<App>;

    };
} // namespace winrt::beta::implementation` 

I can confirm this successfully sets the proper window size! Most online tutorials showed GetForCurrentView() to be set in App::App() but I can totally see why this is needed OnLaunched instead here. Closing the issue now as it is working, thanks again folks!

**Comment by asklar** [comment]
Filed ADO bug: [Bug 27657319: ApplicationView.GetForCurrentView crashes app when invoked in App's constructor](http://osgvsowi/27657319)

**Comment by sandeepmachiraju** [comment]
Just want to clearly mention the steps of what RatikKapoor mentioned above:

In App.cpp(in windows folder if you are using microsoft-react-native) add a function:

```
void App::OnLaunched(Windows::ApplicationModel::Activation::LaunchActivatedEventArgs const& e)
{
    super::OnLaunched(e); 
    ApplicationView::GetForCurrentView().SetPreferredMinSize(Size(490, 590)); 
    ApplicationView::PreferredLaunchViewSize(Size(490, 590)); 
    ApplicationView::PreferredLaunchWindowingMode(ApplicationViewWindowingMode::PreferredLaunchViewSize);
}

```
In App.h add the definition and private variable to the existing struct
```
struct App : AppT<App>
    {
        App() noexcept;
        void OnLaunched(const Windows::ApplicationModel::Activation::LaunchActivatedEventArgs& e);
        private:
            using super = AppT<App>;
    };
```

This worked for me. Let me know if you have any questions.

**Comment by taduyde** [comment]
it's not working, I got the error
"Severity	Code	Description	Project	File	Line	Suppression State
Error	C3779	'winrt::Windows::UI::ViewManagement::ApplicationView::GetForCurrentView': a function that returns 'auto' cannot be used before it is defined	test77	C:\Users\Admin\Desktop\test77\windows\test77\MainPage.cpp	31	
Error	C3779	'winrt::Windows::UI::ViewManagement::ApplicationView::GetForCurrentView': a function that returns 'auto' cannot be used before it is defined	test77	C:\Users\Admin\Desktop\test77\windows\test77\MainPage.cpp	31	
"

**Comment by cjhines** [comment]
> void App::OnLaunched(Windows::ApplicationModel::Activation::LaunchActivatedEventArgs const& e)

You need this in `App.h`:

```
#include <winrt/Windows.UI.ViewManagement.h>
```
