### ISSUE TITLE
Write-up a "backporting guide"

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#5261]
This came out of a discussion with @NickGerleman about steps needed for backporting a change to a previous version.  There is some process devs all need to go through backport a change, including:
-Doing the PR:  Title should begin with [62.0] or whatever version it's targeting
-Changefile:  The type needs to be changed to "patch"
-Adding/removing tags

This stuff should get written-up and posted somewhere.

**Comment by NickGerleman** [comment]
Just added the same issue yesterday with #5217 and added that one to a project that I'm using to track work. We should be able to close one of these as dupes of the other.

**Comment by chrisglein** [comment]
Duplicate of #5217
