### ISSUE TITLE
Fix usage of SolutionDir from projects

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#5263]
`SolutionDir` is a VS-only variable, we fake it in `Directory.Build.props` but sometimes we import stuff before that gets imported which results in MIDL breaks like the following when building just a single project instead of a solution:
```
"C:\rnw\vnext\Microsoft.ReactNative\Microsoft.ReactNative.vcxproj" (default target) (1:7) ->
       (Midl target) -> C:\rnw\vnext\ReactUWP\Views\cppwinrt\AccessibilityAction.idl(1): error MIDL2531: [msg]The reference option requires the /nomidl switch [C:\rnw\vnext\Microsoft.ReactNative\Microsoft.ReactNative.vcxproj]
```

The fix is to move the import of cppwinrt after microsoft.cpp.props. Ensure all projects can be built individually.

**Comment by JunielKatarn** [comment]
Agreed. I don't think MSBuild has a predefined variable name for the use we give to `SolutionDir`.
We should probably name it ourselves, and replace `SolutionDir` usages.
