### ISSUE TITLE
Tests WebSocketModule_* fail on Release configuration

### ISSUE THREAD

**Issue by JunielKatarn** [microsoft/react-native-windows#5265]
Tests `WebSocketModuleIntegrationTest::WebSocketModule_Ping` and `WebSocketModuleIntegrationTest::WebSocketModule_SendMultiple` fail on CI validation.

See https://dev.azure.com/ms/react-native-windows/_build/results?buildId=88534&view=logs&j=6a576c64-c360-5968-e6e9-1b092bc6a5ec&t=9867c3b7-ae0e-5159-b6d0-da40bcc7a881&l=90

Steps to reproduce
1. Build `ReactWindows-Desktop.sln` for `x64|Release`.
2. Run `Scripts\IntegrationTests.ps1 -NoServers -Include WebSocketModuleIntegrationTest::WebSocketModule_ -Configuration Release'.

**Comment by chrisglein** [comment]
Julio says: "Those tests should be removed and replaced with unit tests." He's expecting to deal with this soon, but I don't believe we have a strong requirement to get this in 0.64 (can also backport after we look at the fix).
