### ISSUE TITLE
Support react-native-fs

### ISSUE THREAD

**Issue by branislavantic87** [microsoft/react-native-windows#5267]
# Support react-native-fs on RNW

## Basic Info
- Module Repo URL: https://github.com/itinance/react-native-fs
- [x] Module has a Legacy/C# implementation (https://github.com/itinance/react-native-fs/tree/master/windows/RNFS)

## Which app/customer is requesting this module?
It's a common thing to use file system when creating react-native app!

**Comment by chrisglein** [comment]
Yep, we've got this on our list. Definitely much-requested and on our radar. Please add all you requirements to the linked issue.
Duplicate of #2829
