### ISSUE TITLE
Use a more appropriate default button style

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#5268]
Right now button components get a bright blue color and rounded corners by default. This seems to be because we directly copy/paste the stylesheet used by Android in `button.windows.js`. We should consider a more appropriate default style, as even iOS will do something quite different here.

```jsx
const styles = StyleSheet.create({
  button: Platform.select({
    ios: {},
    android: {
      elevation: 4,
      // Material design blue from https://material.google.com/style/color.html#color-color-palette
      backgroundColor: '#2196F3',
      borderRadius: 2,
    },
    // [Windows
    windows: {
      backgroundColor: '#2196F3',
      borderRadius: 2,
    },
    // Windows]
  }),
...
```

![image](https://user-images.githubusercontent.com/835219/84885378-d1f6cb00-b047-11ea-9333-0ad369052026.png)

**Comment by chrisglein** [comment]
iOS has a different look and feel here with its style, so it's not a matter of everything matching Android. Does seem arbitrary to match Android then. But of course whatever it means to be platform specific is a deep rabbit hole. We'll need to be intentional about where we bring in platform details and where we try to unify across them.

**Comment by chrisglein** [comment]
At the very least using PlatformColor to use the right colors for Windows seems like a start.
@kikisaints there's definitely design work here to figure out how deep we should go.

**Comment by TheSavior** [comment]
The goal of <Button> is "A basic button component that should render nicely on any platform."

I believe the intent of the existing platform styles is to kinda (but not super well) match the experience of default platform buttons. So on Windows I'd expect Button to kinda look like a default Windows button. Similar on Mac. 

In reality, this component doesn't matter and nobody should really be using it in prod. It's just there to make it really easy out of the box to get some button behavior to prototype something with and not need to bring in a 3rd party library for that. So don't put too much time into making this perfect. :) Feel free to style it however you'd like :)
