### ISSUE TITLE
Remove Appearance and DebugEnvironment Overrides When We Hit Facebook's 4/6 Nightly Build

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#5270]
AppearanceModule broke web debugging until a fix was added to facebook/master on 4/6. This was cherry-picked into 0.62, and is in the final version of 0.63, but isn't in the 3/22 nightly build we're beginning integration of. We should remove it when we hit the 4/6 nightly build.

The base of 0.63-stable is the 4/9 build.

**Comment by chrisglein** [comment]
We have a copy of this fix and need to remove it when we get far enough forward.
This should generate merge conflicts with the tooling. Issue is linked in the manifest so should be enough trail back to this.

**Comment by NickGerleman** [comment]
Hmm, this was supposed to be closed with a recent PR. Closing now.
