### ISSUE TITLE
Invalid XML in Microsoft.ReactNative.vcxproj.filters (0.62)

### ISSUE THREAD

**Issue by aschultz** [microsoft/react-native-windows#5285]
In the 0.62 branch, Microsoft.ReactNative.vcxproj.filters is missing XML tags in two places, making the file invalid:

```
<ClInclude Include="..\ReactUWP\Modules\DeviceInfoModule.h">
    <Filter>Modules</Filter>
</ClInclude>
<Filter>Modules</Filter>
</ClInclude>
```

```
<ClCompile Include="..\ReactUWP\Modules\DeviceInfoModule.cpp">
    <Filter>Modules</Filter>
</ClCompile>
<Filter>Modules</Filter>
</ClCompile>
```

**Comment by NickGerleman** [comment]
This was introduced with  https://github.com/microsoft/react-native-windows/commit/fe11a96ebecc3ea9a2afb5fe24e0cf694e3968ab 3 days ago. @aschultz I will have this fixed up imminently (we're about to release) but you can use the build right before and should be unimpacted.

**Comment by NickGerleman** [comment]
We should consider adding validation for these files to CI since we tend to let them degrade in other ways and MSBuild/VSBuild tasks won't catch them since they don't functionallly affect the build. Will create a separate issue for that.
