### ISSUE TITLE
'Question: Can I access the Windows Shell and the USB Ports via React-native-windows?'

### ISSUE THREAD

**Issue by ASchwad** [microsoft/react-native-windows#5286]
Hey guys,
i would like to write a program to flash microcontroller, which also gives some visual feedback about the processes for non-technical users. We are working with texas instruments CLI tools to do the actuall flashing.

Can I access the windows shell and the USB ports via this module? 

Thanks in advance!

**Comment by asklar** [comment]
@ASchwad React Native for Windows creates a UWP app so any API that is callable from UWP will be callable from your app.

**Comment by kmelmon** [comment]
@kmelmon figure out how to leverage the bot to direct to stackoverflow
