### ISSUE TITLE
Add PR Validation for Filter Files

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#5287]
We will often accidentally let filter files get out of date, missing newer files, or referencing deleted files. This isn't caught during CI because they affect the VIsual Studio interface instead of impacting build. Recently in #5285 we ended up adding a filter that was totally invalid, which would show user-facing issues.

We should CI enforce filter validity, like we enforce Clang Format etc. Ex:
1. Filters should be valid XML
2. All headers and cpp files should be referenced in a filter
3. All files referenced in a filter should exist

Filters can rely on MSBuild properites, so we would likely need to do some amount of project evaluation before parsing XML. Maybe something off the shelf exists to do this already?

**Comment by muhdmud** [comment]
Hi, can i work on this?

**Comment by acoates-ms** [comment]
PRs welcome!

**Comment by muhdmud** [comment]
thanks for the opportunity!
how do i see how the clang format is being enforced? or if you can point me on the right direction, example where these filters work?

**Comment by NickGerleman** [comment]
This specific issue might be a little bit tricky without prior MSBuild experience. I took a quick look at this one a while ago but discovered the problem was more complicated than I originally thought. 

@muhdmud are there any other "Good First Task" issues that look interesting to you?

**Comment by muhdmud** [comment]
Oh i see. no worries i admit i too was not sure how big the scope was going to be.
i did find 4 other good first task issues, and i don't mind working on any. Which one would you recommend ?

**Comment by NickGerleman** [comment]
Going to close this after it was discovered this is nontrivial. Don't think it's likely anyone will be looking at this.
