### ISSUE TITLE
Determine Compliance Needs for Binary Distribution

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#5292]
@Khalef1 has pointed out that fully reproducible binaries are required by some compliance standards. We are currently unable to accomplish this due to the level of non-determinism in our CI environment. This could prevent teams from using our binary.

We should take a look at what is needed to create a deterministic binary. This would require pinning toolset versions for the produced binary. @jonthysell and @asklar have pointed out that we do want to provide latest toolset support even for stable branches. We can ideally do this and provide coverage for latest without sacrificing binary determinism.

Produced binaries of different versions should generally be compatible because we have an abi safe boundary. One solution could be to split CI to pinned and non-pinned. This extra usage is potentially mitigated by the lower commit frequency into stable branches.

**Comment by kmelmon** [comment]
@Khalef1 can you drive the discussion around what the requirements are, starting with Office?

**Comment by NickGerleman** [comment]
Not sure if there's anything still actionable here. @dannyvv will probably know better (feel free to close this if there isn't anything we still need).
