### ISSUE TITLE
Initialization failure on npx react-native-windows-init --overwrite

### ISSUE THREAD

**Issue by barto98** [microsoft/react-native-windows#5296]
Hi,
I have problem when I run this command it can no longer execute it
**` npx react-native-windows-init --overwrite`**
because it cannot find the package of **`
react-native-windows@^0.61.0-0
`**
```
Reading application name from package.json...
Reading react-native version from node_modules...
Reading react-native version from node_modules...
Latest matching version of react-native-windows for react-native@0.61.5 is react-native-windows@0.61.14
Installing react-native-windows@^0.61.0-0...
npm ERR! code ETARGET
npm ERR! notarget No matching version found for react-native-windows@0.61.0-0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\alessandrobartoli\AppData\Roaming\npm-cache\_logs\2020-06-22T15_45_34_650Z-debug.log
Command failed: npm install --save react-native-windows@^0.61.0-0
npm ERR! code ETARGET
npm ERR! notarget No matching version found for react-native-windows@0.61.0-0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\alessandrobartoli\AppData\Roaming\npm-cache\_logs\2020-06-22T15_45_34_650Z-debug.log

Error: Command failed: npm install --save react-native-windows@^0.61.0-0
npm ERR! code ETARGET
npm ERR! notarget No matching version found for react-native-windows@0.61.0-0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```
I hope you can help me

npm version: 6.11.3
node version: v12.11.1

**Comment by hfsnetbr** [comment]
I have the same issue here.

**Comment by btav** [comment]
@barto98 and @hfsnetbr,

I have the same issue. I found a work-around to get it to work. Not saying that this is the best solution... But it will at least hopefully unblock you guys for now. 

First install `@react-native-community/cli` locally in your project.

` npm i @react-native-community/cli`

Then run the following command to init `react-native-windows`

` npx react-native-windows-init --version 0.61.14 --overwrite`

**Comment by kmelmon** [comment]
@acoates-ms It looks like an issue with react-native-windows-init against version 61.  I had issues as well.  Can you take a look?

**Comment by yepMad** [comment]
Same here.

**Comment by yepMad** [comment]
> @barto98 and @hfsnetbr,
> 
> I have the same issue. I found a work-around to get it to work. Not saying that this is the best solution... But it will at least hopefully unblock you guys for now.
> 
> First install `@react-native-community/cli` locally in your project.
> 
> ` npm i @react-native-community/cli`
> 
> Then run the following command to init `react-native-windows`
> 
> ` npx react-native-windows-init --version 0.61.14 --overwrite`

I can't say if it's the best gambiarra for the moment, but it worked as it should. Gratitude!

**Comment by btav** [comment]
> > @barto98 and @hfsnetbr,
> > I have the same issue. I found a work-around to get it to work. Not saying that this is the best solution... But it will at least hopefully unblock you guys for now.
> > First install `@react-native-community/cli` locally in your project.
> > ` npm i @react-native-community/cli`
> > Then run the following command to init `react-native-windows`
> > ` npx react-native-windows-init --version 0.61.14 --overwrite`
> 
> I can't say if it's the best trick for the moment, but it worked as it should. Gratitude!

You can remove `@react-native-community/cli` afterwards from your `package.json`. Its just needed for the other command to work properly!

**Comment by hfsnetbr** [comment]
@btav thank you very much! it's working fine now!
