### ISSUE TITLE
WinUI3: No UIContext property for SIP

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#5305]
We implement the `keyboardDidHide` and `keyboardDidShow` events by [hooking into `CoreInputView`'s occlusion events](https://github.com/microsoft/react-native-windows/blob/3f17d742ee5045994fda3f10d2a489bde71659e3/vnext/ReactUWP/Views/SIPEventHandler.cpp#L44). This has a special codepath for xaml islands which won't be supported in WinUI 3.

We need to figure out how we can use the Win32 [`IInputPaneInterop::GetForWindow`](https://docs.microsoft.com/en-us/windows/win32/api/inputpaneinterop/nf-inputpaneinterop-iinputpaneinterop-getforwindow)

**Comment by chiaramooney** [comment]
Not something we plan to address on the Paper renderer as we move towards Fabric.
This behavior should be different on the non-XAML Fabric renderer.
