### ISSUE TITLE
Support react-native-config

### ISSUE THREAD

**Issue by qmatteoq** [microsoft/react-native-windows#5310]
# Support `react-native-config` on RNW

## Basic Info
- Module Repo URL: [https://github.com/luggit/react-native-config](https://github.com/luggit/react-native-config)
- Target version: 0.61
- [ ] Issue exists on module repo (if so, [link]())
- [ ] Module has a Legacy/C# implementation (if so, [link]())

## Which app/customer is requesting this module?
An AppConsult customer

## In what scenarios will this module be used?
This module allows to expose config variables to your javascript code in React Native through a .env file. The customer is using this module to keep all the default settings of the app in a dedicated configuration file.

## Essential Features
Read a setting from the .env file

**Comment by chrisglein** [comment]
@jonthysell What's the status on react-native-config? Did you get it working?

**Comment by asklar** [comment]
@chrisglein this is different - this is `react-native-config` which is a native module for handling app configuration. @jonthysell 's thing was the `react-native config` command to get config data about build-time preferences for a project

**Comment by stmoy** [comment]
Dupe of #4149
