### ISSUE TITLE
Support react-native-device-info

### ISSUE THREAD

**Issue by qmatteoq** [microsoft/react-native-windows#5311]
# Support `react-native-device-info` on RNW

## Basic Info
- Module Repo URL: [https://github.com/react-native-community/react-native-device-info](https://github.com/react-native-community/react-native-device-info)
- Target version: 0.61
- [ ] Issue exists on module repo (if so, [link]())

- [x] Module has a Legacy/C# implementation (if so, [https://github.com/react-native-community/react-native-device-info/tree/master/windows](https://github.com/react-native-community/react-native-device-info/tree/master/windows))

## Which app/customer is requesting this module?
An AppConsult customer

## In what scenarios will this module be used?
The customer is using this module to get essential information about the device and the platform where the application is running for internal analytics purposes

**Comment by stmoy** [comment]
Note: there is a C# implementation of this module (woot!) but we'd prefer to get a C++ implementation if possible since this module is often used. There is a separate issue tracking the conversion: https://github.com/react-native-community/react-native-device-info/issues/1073

**Comment by jaimecbernardo** [comment]
I've opened a PR porting the C# implementation to C++ : https://github.com/react-native-device-info/react-native-device-info/pull/1113

This also adds a test and runs the example app in GitHub workflows.

**Comment by jaimecbernardo** [comment]
The PR porting the code to C++ has been merged: https://github.com/react-native-device-info/react-native-device-info/pull/1113

The PR supporting additional functionality on Windows has been merged as well: https://github.com/react-native-device-info/react-native-device-info/pull/1122
