### ISSUE TITLE
Support react-native-geolocation-service

### ISSUE THREAD

**Issue by qmatteoq** [microsoft/react-native-windows#5312]
# Support `react-native-geolocation-service` on RNW

## Basic Info
- Module Repo URL: [https://github.com/Agontuk/react-native-geolocation-service](https://github.com/Agontuk/react-native-geolocation-service)
- Target version: 0.61
- [ ] Issue exists on module repo (if so, [link]())

- [ ] Module has a Legacy/C# implementation (if so, [link]())

## Which app/customer is requesting this module?
An AppConsult customer

## In what scenarios will this module be used?
The customer is using geolocation features to detect the current position of the user. However, the current standard geolocation module isn't very reliable, since it's still based on the old Google APIs for geolocation. This module adds support for the new Google APIs, along by providing geolocation support for iOS.

## Essential Features
Get the current position of the user

**Comment by burtonrodman** [comment]
Checkout this PR to react-native-geolocation.  Happy to have any feedback.
https://github.com/react-native-geolocation/react-native-geolocation/pull/146

**Comment by chiaramooney** [comment]
Not something we plan to address on the Paper renderer as we move towards Fabric. If you want this module to be supported on Fabric, please file an issue on the react-native-geolocation service repo.
