### ISSUE TITLE
Support react-native-pdf

### ISSUE THREAD

**Issue by qmatteoq** [microsoft/react-native-windows#5313]
# Support `react-native-pdf` on RNW

## Basic Info
- Module Repo URL: [https://github.com/wonday/react-native-pdf](https://github.com/wonday/react-native-pdf)
- Target version: 0.61
- [ ] Issue exists on module repo (if so, [link]())

- [ ] Module has a Legacy/C# implementation (if so, [link]())

## Which app/customer is requesting this module?
An AppConsult customer

## In what scenarios will this module be used?
The customer needs to render PDFs within the application and it's using this module to achieve this goal in the Android version

## Essential Features
Viewing and rendering PDFs

**Comment by bzoz** [comment]
[PR with Windows support](https://github.com/wonday/react-native-pdf/pull/522) was merged recently.

**Comment by stmoy** [comment]
PR was merged - closing!
