### ISSUE TITLE
Support react-native-print

### ISSUE THREAD

**Issue by qmatteoq** [microsoft/react-native-windows#5314]
# Support `react-native-print` on RNW

## Basic Info
- Module Repo URL: [https://github.com/christopherdro/react-native-print](https://github.com/christopherdro/react-native-print)
- Target version: 0.61
- [ ] Issue exists on module repo (if so, [link]())

- [ ] Module has a Legacy/C# implementation (if so, [link]())

## Which app/customer is requesting this module?
An AppConsult customer

## In what scenarios will this module be used?
The application needs to print documents which are generated and download from the application.

## Essential Features
- Trigger the UI to select a printer connected to the computer
- Print a document

**Comment by jaimecbernardo** [comment]
I've opened a PR with Windows support for PDF printing here: https://github.com/christopherdro/react-native-print/pull/121

Regarding HTML printing, the UWP WebView doesn’t implement `window.print()`, and alternative implementations for this feature would have suboptimal results. This should be revisited once WebView2 is stable.

**Comment by jaimecbernardo** [comment]
The PDF printing PR has been merged: https://github.com/christopherdro/react-native-print/pull/121
The HTML printing functionality still needs to be revisited.

**Comment by stmoy** [comment]
Closing since the PDF functionality has been added.
