### ISSUE TITLE
Support react-native-view-shot

### ISSUE THREAD

**Issue by qmatteoq** [microsoft/react-native-windows#5315]
# Support `react-native-view-shot` on RNW

## Basic Info
- Module Repo URL: [https://github.com/gre/react-native-view-shot](https://github.com/gre/react-native-view-shot)
- Target version: 0.61
- [ ] Issue exists on module repo (if so, [link]())

- [x] Module has a Legacy/C# implementation (if so, [https://github.com/gre/react-native-view-shot/tree/master/windows](https://github.com/gre/react-native-view-shot/tree/master/windows))

## Which app/customer is requesting this module?
An AppConsult customer

## In what scenarios will this module be used?
The customer is using this module to turn specific views of the application into images, that can be shared later through mail or other communication systems

## Essential Features
Create an image out from a View and save it

**Comment by qmatteoq** [comment]
A PR with the support to the new React Native core is pending PR: https://github.com/gre/react-native-view-shot/pull/334

**Comment by chiaramooney** [comment]
Not something we plan to address on the Paper renderer as we move towards Fabric. If you want this module supported on Fabric, please file an issue in the react-native-view-shot repo.
