### ISSUE TITLE
Validate CI loop on older releases

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#5325]
Currently, we run the CI loop for older branches on demand, typically when we backport a change.  This isn't quite enough to validate quality for the build, because Visual Studio updates can happen at any time.

This task is tracking adding a scheduled CI loop run for these older stable branches.  Possibly just run daily.

**Comment by kmelmon** [comment]
Also need a mechanism to notify us when something in automated tests fail.

**Comment by kmelmon** [comment]
Also need to know when things fail!

**Comment by kmelmon** [comment]
@chrisglein we should find someone to work on this.

**Comment by chrisglein** [comment]
> Possibly just run daily.

Candidate to make use of #4567

**Comment by NickGerleman** [comment]
We have a CI loop running regularly on multiple branches now, starting on 0.65. https://dev.azure.com/ms/react-native-windows/_build?definitionId=468&_a=summary. Dashboard on the same instance.
