### ISSUE TITLE
Rename DebugHost from ReactInstanceSettings to something more appropriate?

### ISSUE THREAD

**Issue by nasadigital** [microsoft/react-native-windows#5329]
The `DebugHost` property is used to specify the bundler, which might not be clear from the name (particularly in remote debugging scenarios).
To boot, the individual settings to set the hostname (`SourceBundleHost`) and port (`SourceBundlePort`) don't align with the naming scheme.
After talking with @asklar the conclusion was that the name should better reflect this or that this could be better documented.

**Comment by kmelmon** [comment]
Note:  Android or iOS may already have this name.
