### ISSUE TITLE
A Roadmap?

### ISSUE THREAD

**Issue by rmevans9** [Microsoft/react-native-windows#533]
Hello,

I have been looking around to see if there was anything that outlined where you guys stand with parity to iOS/Android but came up with nothing. Do you guys have a roadmap of sorts outlining that? It would be very helpful for developers with iOS/Android apps on React Native possibly thinking about getting a Windows Phone app up and running as well.

**Comment by rozele** [comment]
Thanks for asking @rmevans9.  We do have [https://github.com/ReactWindows/react-native-windows/blob/master/docs/CoreParityStatus.md](https://github.com/ReactWindows/react-native-windows/blob/master/docs/CoreParityStatus.md), but it's not necessarily up to date.  I'm going to push some updates to it today.

**Comment by rmevans9** [comment]
Oh Excellent - that is exactly what I was looking for but I guess I didn't see it anywhere. Thanks for that!

**Comment by GeekOnCoffee** [comment]
Hello team! I don't want to spam the project by opening a new issue, so hopefully you'll see this comment and respond :) We're evaluating whether it would make sense for us to pursue Windows phone support at this time, and it looks like @rozele and team are doing incredible work building and maintaining this, but the Core Parity Status hasn't been updated in months. Not sure if it would be a quick exercise for somebody familiar with the project to go through and update, but it'd be super valuable for us in our evaluation!

**Comment by rozele** [comment]
Thanks @GeekOnCoffee.  I can try to take a quick pass through.  No guarantees on completeness though.

**Comment by GeekOnCoffee** [comment]
@rozele perfect, I've got no need for perfection, just a more up to date picture of how things look :)

**Comment by rozele** [comment]
@GeekOnCoffee I've taken a pass through CoreParityStatus, sorry for the delay. Let me know if you have any questions!
