### ISSUE TITLE
SIP keyboard event won't fire in WinUI 3 in XamlIsland

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#5333]
See #5309. 

We have events that we need to fire when the SIP keyboard shows/hides and we were using the UIContext to get the CoreInputView
https://github.com/microsoft/react-native-windows/blob/3f17d742ee5045994fda3f10d2a489bde71659e3/vnext/ReactUWP/Views/SIPEventHandler.cpp#L50-L78

WinUI 3 has no  `UIElement.UIContext` property so we right now we go down the fallback path. We need to evaluate if this is ok/enough.

**Comment by kmelmon** [comment]
Note that we may need something new in WinUI 3 to fix this.  @chrisglein do we need a new label to capture this sort of ask?

**Comment by chrisglein** [comment]
Just the "Needs WinUI 3" label. We need to do a pass through those and differentiate the few that will automatically be fixed by WinUI 3 (e.g. something suddenly available downlevel) versus will need changes _on top of_ WinUI3 to address (the majority)

**Comment by asklar** [comment]
Reunion https://github.com/microsoft/ProjectReunion/issues/114

**Comment by asklar** [comment]
Duping to #5305
