### ISSUE TITLE
Show a Better Error Message When Trying to Use TurboModules While Web Debugging

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#5348]
Trying to load the TurboModuleExample while web debugging leads to this redbox error:
![image](https://user-images.githubusercontent.com/835219/85818427-70a8b900-b725-11ea-9048-af16de1f4fc9.png)

It's expected that TurboModules won't work when web debugging, but the error here is a bit confusing. Can we make it clearer?

**Comment by TheSavior** [comment]
I think this is a problem upstream as well

**Comment by chrisglein** [comment]
@NickGerleman can you create a bug on the core repo to improve this across the board?

**Comment by chrisglein** [comment]
May just be won't fix because web debugging will be going away...

**Comment by asklar** [comment]
@NickGerleman @TheSavior Was there a bug filed for this in core? 
Currently the turbomodule page in RNTester is commented out but I'd like to enable it. It works fine if I disable web debugging. Is there a path for turbomodules to work with web debugging on, or is web debugging finally going away (being replaced with?), or?

**Comment by NickGerleman** [comment]
FYI that as of https://github.com/microsoft/react-native-windows/pull/6397, TurboModuleExample is dynamically added to RNTesterList by testing the presence of TurboModule infrastructure on the JS side. I.e. it will show up when using a JSI runtime, and will disappear when web debugging.
