### ISSUE TITLE
The hotreloading is broken when we add a new package

### ISSUE THREAD

**Issue by javieraparisivaldes** [microsoft/react-native-windows#5357]
Environment

If you are using latest version:
1. `react-native -v`: 4.9.0
2. `react-native run-windows --info`:System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 3.93 GB / 15.73 GB
  Binaries:
    Node: 12.9.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.2 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 16.11.0 => 16.11.0
    react-native: ^0.62.0-0 => 0.62.2
    react-native-windows: ^0.62.0-0 => 0.62.0
  Installed UWP SDKs:
    10.0.18362.0
3. `reg query "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock"`:
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock
    AllowDevelopmentWithoutDevLicense    REG_DWORD    0x1
    AllowAllTrustedApps    REG_DWORD    0x1

- Target Platform Version(s):10.0.18362
- Target Device(s): Desktop
- Visual Studio Version: Visual Code 1.46.1

### Steps to Reproduce

1.npx react-native init ex1 --version ^0.62.2
2.cd ex1
3.npx react-native-windows-init --overwrite --language cs
4.yarn install
5.yarn run windows
6.yarn add react-native-webview

### Expected Behavior
The metro console should reload the new package

### Actual Behavior
The metro console stop working

![image](https://user-images.githubusercontent.com/56872233/85885691-0c4d2e80-b7e5-11ea-8ea1-06d55d8dafaf.png)

**Comment by chrisglein** [comment]
The issue seems to be that you're running the packager and then are changing dependencies while that is running. That will lose your packager, and that appears to the be problem. If you re-run the packager then you should be good.

Hot reload isn't going to work across this kind of change.

Let us know if restarting it doesn't resolve you're issue.
