### ISSUE TITLE
Microsoft.ReactNative 0.62 does not pass WACK

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#5362]
We added a call to AppPolicyGetWindowingModel which is not WACK-compliant, this will block submission of apps to the Store.

**Comment by asklar** [comment]
Turns out this API got added to the 19041 SDK release of WACK so this is not needed anymore.

**Comment by asklar** [comment]
however we still have a reference to kernel32 __C_specific_handler which comes via onecoreuap.lib which we had added to be able to call AppPolicyGetWindowingModel so maybe we still need this after all.

**Comment by Khalef1** [comment]
@asklar : I'm removing the request backport label here, and will track the backport using #5369
