### ISSUE TITLE
Provide the framework "Microsoft.VCLibs.140.00.Debug"

### ISSUE THREAD

**Issue by jajabarr** [microsoft/react-native-windows#5371]
### Environment

If you are using latest version:
1. `react-native -v`: react-native-cli: 2.0.1 react-native: 0.62.2
2. `react-native run-windows --info`: 
 System:
    OS: Windows 10 10.0.18363
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Memory: 57.70 GB / 63.91 GB
  Binaries:
    Node: 12.9.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 16.11.0 => 16.11.0
    react-native: ^0.62.0-0 => 0.62.2
    react-native-windows: ^0.62.0-0 => 0.62.0
  Installed UWP SDKs:
    10.0.18362.0
3. `reg query "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock"`:
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock
    AllowDevelopmentWithoutDevLicense    REG_DWORD    0x1

- Visual Studio Version: Visual Studio 2019

### Steps to Reproduce

Trying to get my first UWP React-Native app running (previously I had only targeted IOS via Expo. I ran through this guide:
https://microsoft.github.io/react-native-windows/docs/getting-started

Previous I already had react-native installed, as well as Visual Studio 2019.

At first, this command failed:
```
npx react-native run-windows
```
at this step:
```
 i Build configuration: Debug
 i Build platform: x86
```
But was fixed after modifying my VS2019 to include the UWP packages

Note that this step from https://microsoft.github.io/react-native-windows/docs/rnw-dependencies: 

```
Run this command: Start-Process -Verb RunAs powershell -ArgumentList @("-command", "iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/microsoft/react-native-windows/master/vnext/Scripts/rnw-dependencies.ps1'))")
```

Did not work, and it was misleading to think that I could do one or the other (either the pshell script OR modify Visual Studio)

Now, when I run: **yarn windows** my build fails with this error:
```
× Installing new version of the app from layout
 × Failed to deploy: Installing new version of the app from layout
```
When I run with --logging, I see this error:

```
√ Enabling Developer Mode
 Add-AppxPackage : Deployment failed with HRESULT: 0x80073CF3, Package failed updates, dependency or conflict
validation.
Windows cannot install package 16666044-447a-45d1-b76f-118a2441e6d2_1.0.0.0_x86__5kdbcj42ddrzt because this package
depends on a framework that could not be found. Provide the framework "Microsoft.VCLibs.140.00.Debug" published by
"CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x86 processor
architecture and minimum version 14.0.27810.0, along with this package to install. The frameworks with name
"Microsoft.VCLibs.140.00.Debug" currently installed are: {}
NOTE: For additional information, look for [ActivityId] fdd87787-4cd0-0012-d878-d8fdd04cd601 in the Event Log or use
the command line Get-AppPackageLog -ActivityID fdd87787-4cd0-0012-d878-d8fdd04cd601
+     Add-AppxPackage -Path $Path -Register -ForceApplicationShutdown
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\progs\vsbudd...ppxManifest.xml:String) [Add-AppxPackage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand
```

I found this link to download the framework: https://www.microsoft.com/en-us/download/details.aspx?id=53175

But after installing and restarting my computer, it still did not work.

### Expected Behavior

I expect the build to succeed and the hello world react-native-windows app to launch

### Actual Behavior

The build fails

(see attached logging)
[debug.txt](https://github.com/microsoft/react-native-windows/files/4841365/debug.txt)

**Comment by chrisglein** [comment]
There is an issue on @asklar about installing dependent framework packages. Alex, find the issue and dupe out?

**Comment by asklar** [comment]
This is #5179
