### ISSUE TITLE
React navigation for windows & macOS

### ISSUE THREAD

**Issue by Numbers-sa** [microsoft/react-native-windows#5381]
I wanted to know if react navigation works with windows & macOS, if not what alternatives can I use for navigation with these platforms.

**Comment by chrisglein** [comment]
Our effort to try to get Windows support for react-navigation is tracked here: #3884
Short answer is not yet, but it's being worked on.
For macOS you'll want to check in via the [macOS repo](https://github.com/Microsoft/react-native-macos), but according to the [directory](https://reactnative.directory/?search=navigation) it's not yet supported.

**Comment by chrisglein** [comment]
(as for alternatives, this one also isn't implemented yet either #2546)
