### ISSUE TITLE
exception thrown when navigating between views

### ISSUE THREAD

**Issue by JoshyAbraham** [microsoft/react-native-windows#5421]
Exception is raised when user navigate between screens with in the application. noticed this issue on multiple windows version ( 10.0.18362.1,  10.0.19041.1).   react native  version : 0.59.0

COMMENT:  
*** "C:\Procdump\procdump.exe" -accepteula -ma -j "c:\crashdumps" 20452 492 000001D382280000
*** Just-In-Time debugger. PID: 20452 Event Handle: 492 JIT Context: .jdinfo 0x1d382280000
 
NTGLOBALFLAG:  0
 
PROCESS_BAM_CURRENT_THROTTLED: 0
 
PROCESS_BAM_PREVIOUS_THROTTLED: 0
 
APPLICATION_VERIFIER_FLAGS:  0
 
CONTEXT:  (.ecxr)
rax=0000002b4abfe290 rbx=0000002b4abfe8a0 rcx=0000002b4abfe290
rdx=0000000000000000 rsi=000001d39a07efa0 rdi=0000002b4abfe290
rip=00007fff61c8b37c rsp=0000002b4abfe1b0 rbp=0000000000000001
r8=0000000000000000  r9=0000000000000000 r10=0000000000000000
r11=0000002b4abfe8a0 r12=0000000000000001 r13=0000000000000000
r14=0000000000000002 r15=0000400000000000
iopl=0         nv up ei pl nz na pe nc
cs=0033  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00000200
KERNELBASE!RaiseFailFastException+0x15c:
00007fff`61c8b37c 0f1f440000      nop     dword ptr [rax+rax]
Resetting default scope
 
EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 00007fff61c8b37c (KERNELBASE!RaiseFailFastException+0x000000000000015c)
   ExceptionCode: c000027b
  ExceptionFlags: 00000001
NumberParameters: 2
   Parameter[0]: 000001d39a07efa0
   Parameter[1]: 0000000000000003
 
PROCESS_NAME: *.exe
 
ERROR_CODE: (NTSTATUS) 0xc000027b - An application-internal exception has occurred.
 
EXCEPTION_CODE_STR:  800f1001
 
EXCEPTION_PARAMETER1:  000001d39a07efa0
 
EXCEPTION_PARAMETER2:  0000000000000003
 
FAULTING_THREAD:  ffffffff
 
STACK_TEXT:  
000001d3`9a121450 00007fff`63a4bf4d combase!RoOriginateErrorW+0x4d
000001d3`9a121458 00007fff`4b0d6eb4 Windows_UI_Xaml!DirectUI::ErrorHelper::OriginateError+0x13c
000001d3`9a121460 00007fff`4b0c8308 Windows_UI_Xaml!CJupiterErrorServiceListener::NotifyErrorAdded+0x188
000001d3`9a121468 00007fff`4aeea30c Windows_UI_Xaml!CErrorService::AddError+0x13c
000001d3`9a121470 00007fff`4aeebc52 Windows_UI_Xaml!CErrorService::ReportRuntimeError+0xd2
000001d3`9a121478 00007fff`4aeeb935 Windows_UI_Xaml!CErrorService::ReportGenericError+0x155
000001d3`9a121480 00007fff`4ae77576 Windows_UI_Xaml!CDependencyObject::SetAndOriginateError+0x86
000001d3`9a121488 00007fff`4ad60e2a Windows_UI_Xaml!CAnimation::DoAnimationValueOperation+0x281c2a
000001d3`9a121490 00007fff`4abd0af6 Windows_UI_Xaml!CAnimation::UpdateAnimationUsingKeyFrames+0x346
000001d3`9a121498 00007fff`4ab2ed61 Windows_UI_Xaml!CAnimation::UpdateAnimation+0x1d1
000001d3`9a1214a0 00007fff`4abd13e7 Windows_UI_Xaml!CTimeline::ComputeStateImpl+0x277
000001d3`9a1214a8 00007fff`4ac0b545 Windows_UI_Xaml!CTimelineGroup::ComputeStateImpl+0x175
000001d3`9a1214b0 00007fff`4ac0b1aa Windows_UI_Xaml!CStoryboard::ComputeStateImpl+0x21a
000001d3`9a1214b8 00007fff`4aac504f Windows_UI_Xaml!CTimeManager::Tick+0x23f
000001d3`9a1214c0 00007fff`4abc5d6f Windows_UI_Xaml!CCoreServices::NWDrawTree+0x46f
000001d3`9a1214c8 00007fff`4ab641ad Windows_UI_Xaml!CCoreServices::NWDrawMainTree+0xad
000001d3`9a1214d0 00007fff`4ab6403f Windows_UI_Xaml!CWindowRenderTarget::Draw+0x6f
000001d3`9a1214d8 00007fff`4ab63f66 Windows_UI_Xaml!CXcpBrowserHost::OnTick+0x96
000001d3`9a1214e0 00007fff`4abfce8d Windows_UI_Xaml!CXcpDispatcher::Tick+0x8d
000001d3`9a1214e8 00007fff`4abfcd96 Windows_UI_Xaml!CXcpDispatcher::OnReentrancyProtectedWindowMessage+0x42
000001d3`9a1214f0 00007fff`4aad6289 Windows_UI_Xaml!CXcpDispatcher::WindowProc+0x119
000001d3`9a1214f8 00007fff`4aad82ab Windows_UI_Xaml!CDeferredInvoke::DispatchQueuedMessage+0xcb
000001d3`9a121500 00007fff`4aad819c Windows_UI_Xaml!CXcpDispatcher::MessageTimerCallbackStatic+0x1c
000001d3`9a121508 00007fff`5ed953cb CoreMessaging!Microsoft__CoreUI__Dispatch__TimeoutHandler$CallbackThunk+0x11b
000001d3`9a121510 00007fff`5edbc79b CoreMessaging!Microsoft::CoreUI::Dispatch::TimeoutManager::Callback_OnDispatch+0x18b
000001d3`9a121518 00007fff`5ed9995b CoreMessaging!Microsoft::CoreUI::Dispatch::EventLoop::Callback_RunCoreLoop+0x6fb
000001d3`9a121520 00007fff`5ed98e16 CoreMessaging!Microsoft::CoreUI::Dispatch::UserAdapter::OnUserDispatch+0x1d6
000001d3`9a121528 00007fff`5ed97051 CoreMessaging!Microsoft::CoreUI::Dispatch::UserAdapter_DoWork+0xf1
000001d3`9a121530 00007fff`5ed96e73 CoreMessaging!Microsoft::CoreUI::Dispatch::UserAdapter_WindowProc+0xa3
000001d3`9a121538 00007fff`63cee338 user32!UserCallWinProcCheckWow+0x2f8
000001d3`9a121540 00007fff`63cedd79 user32!DispatchMessageWorker+0x249
000001d3`9a121548 00007fff`4bc5b69b Windows_UI!Windows::UI::Core::CDispatcher::ProcessMessage+0x18b
000001d3`9a121550 00007fff`4bc5b390 Windows_UI!Windows::UI::Core::CDispatcher::WaitAndProcessMessagesInternal+0xc0
000001d3`9a121558 00007fff`4bc5b21b Windows_UI!Windows::UI::Core::CDispatcher::ProcessEvents+0x7b
000001d3`9a121560 00007fff`4acc8960 Windows_UI_Xaml!CJupiterWindow::RunCoreWindowMessageLoop+0x4c
000001d3`9a121568 00007fff`4acc88ff Windows_UI_Xaml!DirectUI::DXamlCore::RunMessageLoop+0x47
000001d3`9a121570 00007fff`4fb9650a twinapi_appcore!Windows::ApplicationModel::Core::CoreApplicationView::Run+0x3a
000001d3`9a121578 00007fff`4fb4ed9f twinapi_appcore!<lambda_643db08282a766b00cec20194396f531>::operator+0x1ef
000001d3`9a121580 00007fff`638ee829 SHCore!_WrapperThreadProc+0xe9
000001d3`9a121588 00007fff`63816fd4 kernel32!BaseThreadInitThunk+0x14
000001d3`9a121590 00007fff`6447cec1 ntdll!RtlUserThreadStart+0x21
 
 
STACK_COMMAND:  *** Stowed Exception v2 ***; .exr -1; dpp 0x1d39a07efa0 L0x3; dt 0x1d399ecfa68 combase!STOWED_EXCEPTION_INFORMATION_V2 -r; dps 0x1d39a121450 L0x29; *** combase!RoOriginate* ***; dt 0x1d399ecf9d8-0x8 combase!CRestrictedError _hrError _pszRestrictedDescription;
 
FAULTING_SOURCE_LINE:  onecoreuap\windows\dxaml\xcp\dxaml\lib\errorhelper.cpp
 
FAULTING_SOURCE_FILE:  onecoreuap\windows\dxaml\xcp\dxaml\lib\errorhelper.cpp
 
FAULTING_SOURCE_LINE_NUMBER:  675
 
SYMBOL_NAME:  Windows_UI_Xaml!DirectUI::ErrorHelper::OriginateError+13c
 
MODULE_NAME: Windows_UI_Xaml
 
IMAGE_NAME:  Windows.UI.Xaml.dll
 
FAILURE_BUCKET_ID:  STOWED_EXCEPTION_XAML_TEXT_Invalid_attribute_value_Unknown_for_property_Stroke_800f1001_Windows.UI.Xaml.dll!DirectUI::ErrorHelper::OriginateError
 
OS_VERSION:  10.0.19041.1
 
BUILDLAB_STR:  vb_release
 
OSPLATFORM_TYPE:  x64
 
OSNAME:  Windows 10
 
FAILURE_ID_HASH:  {8d1419ef-44f7-fde8-c077-5a21c35faa49}

**Comment by JoshyAbraham** [comment]
we are in the process of moving to the latest version of react native, to support our existing customers will it be possible for you to give your assessment on root cause of the issue helping as mitigate the impact until we move to the latest version of react.

**Comment by chrisglein** [comment]
It looks like the failure is part of processing a Storyboard animation, aka a XAML animation not a React Native animation. Do you have the context of which control was executing here? In order to delve further we'd probably need a dump to get into that stowed exception. Looks like an issue targeting a Stroke property? Context on what custom native modules you have may help, in case it's the app XAML and not the RNW core control XAML.
