### ISSUE TITLE
Certain components no longer render without the 'height' prop specified

### ISSUE THREAD

**Issue by rectified95** [microsoft/react-native-windows#5437]
### Environment

RNW 0.62.0

### Steps to Reproduce
Include certain RN tags, such as Slider or DatePicker (in timer mode) in your JSX, and observe the output on the screen,
Code that used to work now needs to have height specified to render.

### Expected Behavior

Component renders on screen.

### Actual Behavior

Component doesn't show up on screen,

**Comment by chrisglein** [comment]
I'm fairly certain we've seen this on TextInput before.
Slider and DatePicker have templates that come from WinUI... maybe pulling in a new WinUI version there had some affect between 61 and 62? Or was there a Yoga change?

**Comment by chrisglein** [comment]
We'll want a list of controls that are affected by this. @rectified95 can you check a few more and see how widespread this is?

**Comment by rectified95** [comment]
Sure, I'll take a look next week, after I'm done with Slider.

**Comment by rectified95** [comment]
@chrisglein 
I have verified these controls are affected by this:
- DateTimePicker (in time mode)
- Slider
- Textinput (needs both width and height)
- Checkbox

**Comment by rectified95** [comment]
#5686 found that sometimes TextInput will render without the height value specified, though not always; in that case resizing the window helped.

**Comment by NickGerleman** [comment]
Don't think this should block 0.63, since we've reproed since at least 0.62.

**Comment by rectified95** [comment]
The problem with TextInput is being addressed by #6451.

I've tested this fix together with adding a custom yoga measure function for Slider - it solves the issue when used in the shadow node-based view manager we used to have  in core, but requires changes to the native module API to allow a fix in the community module.

Checkbox still needs debugging as the above fix doesn't work for it.

I'm closing this issue, as the highest-impact and most reported problem was with TextInput, while we have another issue tracking the extension of the native module ABI to allow these changes in modules outside of core. - #6411

**Comment by rectified95** [comment]
Update: the combination of forcing a xaml layout pass and providing a custom yoga measure function solves the problem for both Slider and Checkbox. Need to provide a way to specify those via the winrt API for community modules, as indicated above.
