### ISSUE TITLE
Support for writing native modules in Rust

### ISSUE THREAD

**Issue by wagnerma** [microsoft/react-native-windows#5459]
# Proposal: Support for writing native modules in Rust

## Summary
Rust is a fast and safe multi plattform language, perfectly fitted for writing native modules plattform neutral. Actual C# and C++ are supported and this proposal suggest to add the same support for building native modules in Rust.

## Motivation
Possibility to have support for a language to write application logic plattform neutral, with the same ecosystem accross all plattforms. Especially having a language build in build system (cargo) and dependency management accross all plattform ease the developement process for different plattforms. The application architecture is using React Native for UI Design accross the targets, but develop the application logic in Rust.
A future extension could also be to develop Rust/WinRT components/UI components and use it in react native windows.

**Comment by chrisglein** [comment]
As long as we've done our core work with keeping nice ABI safe boundaries this should be possible as a future option. Lots of questions to explore here. @stmoy do you want to take a crack at capturing this?
