### ISSUE TITLE
MSRN NuGet Binaries Are Not Kept in Sync With NPM Package

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#5472]
We have a really painful user experience around binary distribution and version updates. When a user updates their react-native-windows package, they will have a dangling version in the `packages.config` NuGet package configuration that has to be manually updated, even for patch releases.

An ideal solution would to be to use PackageReference and include targets we wanted to restore within the NPM package. We cannot use PackageReference in C++ projects though, which limits our options. Two solutions were identified:

1. **Alter packages.config during prebuild**
Add msbuild logic to update our packages.config. It's unknown whether VS does NuGet restore after a target we could hook into, as packages.config based NuGet usage isn't integrated with MSBuild. This would also mean changing the custom NuGet restore logic in the CLI.

2. **Driving NuGet ourselves**
We now guarantee that a  NuGet binary is present as part of JS install of react-native-windows. We can have our own target that drives it. E.g. restore a packages.config internal to the project into a temp directory and copy outputs to our project. There are bits we need to be careful of when making this opaque, such as respecting NuGet configuration defined in the solution's `nuget.config`.

**Comment by NickGerleman** [comment]
Marking for 63, since binary distribution would be painful without this.

**Comment by chrisglein** [comment]
Min bar: Have the build system validate that you have the right version installed that matches what you specified.

Ideally something better where we make sure you get the right thing.

**Comment by NickGerleman** [comment]
Marking as a recent regression as we'll see problems with this when we enable binary distribution by default.

**Comment by NickGerleman** [comment]
See #5473 which previously tracked doing this for C# porojects.

**Comment by NickGerleman** [comment]
Actually I'm going to hold the label until we enable binary distribution by default.

**Comment by NickGerleman** [comment]
Initial fix added with #5836
