### ISSUE TITLE
Remove usage of DisplayInformation GetForCurrentView

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#5474]
Islands / winui 3 won't work well with `DisplayInformation.GetForCurrentView` , so we need to instead use something like `XamlRoot.RasterizationScale` and `XamlRoot.Size`, and listen to events from `XamlRoot.Changed`

**Comment by chrisglein** [comment]
APIs will only exist where islands are, like 19H1+ or WinUI3.
Some concerns raised here about multiple window/screen scenarios.
These are WinRT APIs, not WinUI APIs. Maybe addressed with Reunion?
We've raised these topics before, need to find the links.

**Comment by chrisglein** [comment]
Related issues: #4002 #3567

**Comment by asklar** [comment]
Reunion: https://github.com/microsoft/ProjectReunion/issues/114

**Comment by chiaramooney** [comment]
Not something we plan to address on the Paper renderer as we move towards Fabric.
This behavior should be different on the non-XAML Fabric renderer.
