### ISSUE TITLE
DComp SRW leak and crash when destroying an island using DWXS when more than one DWXS exist

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#5477]
Hitting this when running a win32/island with multiple windows, when calling DWXS.Close with appverifier turned on.
Unclear if we shouldn't call Close, docs say we should but most of the docs on islands are wrong. I have a thread with Oscar, using this to track.

**Comment by asklar** [comment]
IXP Comp bug: [Bug 27544005: DesktopWindowXamlSource::Close frees SRW then crashes app](http://osgvsowi/27544005)

**Comment by chrisglein** [comment]
Hoping for an update to the sample that includes the right practices to workaround this scenario (so we don't need to wait for a comp fix).

**Comment by asklar** [comment]
Comp bug is fixed (will be included in WinUI 3), unclear whether this needs to be serviced or not, depends on whether @jackerghan  can work around it by following the xaml islands "complex sample" :)

**Comment by asklar** [comment]
Confirmed with @jackerghan that he can work around it by delaying destruction of the DesktopWindowXamlSource objects.
Jack, if you're able to, we'd love to have that work-around integrated into the playground-win32 app 😊
