### ISSUE TITLE
TouchEventHandler uses ExpPointerPointProperties Pressure and IsEraser

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#5481]
These properties aren't supported in lifted comp.
Internal tracking bug for IXP: [Bug 27533745: ExpPointerPointProperties needs IsEraser and Pressure properties](https://microsoft.visualstudio.com/DefaultCollection/OS/_workitems/edit/27533745)

**Comment by chrisglein** [comment]
May need to take a step back in parity while we wait (lose pressure sensitivity and pen eraser).
