### ISSUE TITLE
RNTester Native animations page - JavaScript animations don't work

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#5491]
None of the javascript animations work in the Native Animations page

![image](https://user-images.githubusercontent.com/22989529/87113533-5261b380-c223-11ea-9faa-6a82bc3d9647.png)

**Comment by chrisglein** [comment]
Regressed at some point. Was working in 0.61 at least.

**Comment by chrisglein** [comment]
First thing: Make sure it's not broken in 0.62 release :o

**Comment by kaiguo** [comment]
I think it worked fine for me in the latest master branch. Can you double check @asklar ?

**Comment by NickGerleman** [comment]
Tried this out as well when I was scrubbing through issues to find new regressions. JS Animations work correctly for me with web debugging enabled or disabled. 

```
  System:
    OS: Windows 10 10.0.18362
    CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
    Memory: 18.36 GB / 31.93 GB
  Binaries:
    Node: 12.16.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Installed UWP SDKs:
    10.0.18362.0
```

@asklar was there anything unique about the setup here? E.g. was it in an island or using WINUI?
