### ISSUE TITLE
Switching light/dark mode and theme does not take effect until app is restarted

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#5493]
- set dark mode in Settings
- launch playground
- change to light mode
playground is not re-rendered to show in light mode
(same vice versa)

**Comment by NickGerleman** [comment]
Are you able to ever get it to show in dark mode with web debugging enabled? With it disabled, I'm able to switch dynamically and have everything work as expected.

**Comment by chrisglein** [comment]
Weird. @NickGerleman any guesses as to why these two are linked?

**Comment by NickGerleman** [comment]
Mentioned this in another issue, but Appearance uses synchronous native module calls under the hood, which don't work when web debugging. Facebook decided to hard code light mode when web debugging to get around this. There's nothing we can really do here, but web debugging will be going away soon enough in general, and PlatformColor doesn't have the issue.

I'm still not able to repro this, and I remember explicitly adding support for this. @asklar could you share some more details on environment or other details?

**Comment by NickGerleman** [comment]
@marlenecota was running into similar, where this used to work for her but now doesn't. I can't repro running 1903, but the issue is happening for her at least in rs_prerelease. Possible Windows behavior change.

**Comment by marlenecota** [comment]
I am not sure what I did to get in that state, but I can't get a repro anymore.
