### ISSUE TITLE
Add isFocused() to View and Pressable

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#5511]
From [Keyboarding in React Native Desktop](https://github.com/microsoft/react-native-windows/pull/5590/files) document:

> TextInput also includes an isFocused() method that returns true/false based on whether this TextInput currently has focus. It may be useful to add this to View to complete the set. 
> TODO: Add this API to View and upstream as a separate PR. Tee this up with the previous one.

**Comment by chrisglein** [comment]
macOS peer issue: https://github.com/microsoft/react-native-macos/issues/499

**Comment by rectified95** [comment]
Waiting for upstreaming PRs to complete before making further changes to RNW.

**Comment by rectified95** [comment]
We haven't really heard of a need to use this - seems like onFocus callback should be enough for this. Can revisit based on future need.
