### ISSUE TITLE
Re-write Effects.idl using modern IDL

### ISSUE THREAD

**Issue by marlenecota** [microsoft/react-native-windows#5534]
@marlenecota You don't have to do it in this PR, but it looks like `Effects.idl` is the last file to still use the old IDL style (with HRESULTS, property get / set methods, etc.) which is a pain to parse. Please open an issue to track re-writing the file with modern idl (which of course will mean some changes to the code-behind).

_Originally posted by @jonthysell in https://github.com/microsoft/react-native-windows/pull/5521#issuecomment-658964307_

**Comment by NickGerleman** [comment]
I think we did this. Anything left to do?
