### ISSUE TITLE
forceRTL from app.cpp

### ISSUE THREAD

**Issue by elcssmouhsine** [microsoft/react-native-windows#5548]
how can we include i18n module from app.cpp and force rtl .

**Comment by chrisglein** [comment]
This was implemented in #4676.
Why do you need to do this from native code? We'd expect you to target the JavaScript API. Does that work for you? This may depend on what version or RNW you're targeting.

The timing is important in this setting, that if you set it too late you'd need to reload everything. This is an option only expected for testing, not for product code.
