### ISSUE TITLE
rnw-dependencies.ps1 does not work on powershell 6 or higher

### ISSUE THREAD

**Issue by dannyvv** [microsoft/react-native-windows#5553]
When trying to run `rnw-dependecies.ps1` on the latest powershell core (pwsh, not powershell) I got the error:

```
Get-WmiObject: Z:\src\r4\vnext\Scripts\rnw-dependencies.ps1:138:18
Line |
 138 |          Valid = (Get-WmiObject -Class win32_computersystem).TotalPhys …
     |                   ~~~~~~~~~~~~~
     | The term 'Get-WmiObject' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path
     | is correct and try again.
```

It turns out WMI is deprecated and now one has to use CIM? per: https://github.com/PowerShell/vscode-powershell/issues/2333 Didn't have energy to search further, so just filed an issue.

**Comment by asklar** [comment]
@dannyvv: weird, I can use it just fine:
![image](https://user-images.githubusercontent.com/22989529/87827612-12f12380-c830-11ea-9f05-8625886819bd.png)

is this a problem only on PS6 and it's fixed in PS7?

**Comment by JunielKatarn** [comment]
In any case, we should aim for PowerShell 7.
I believe that's the LTS.

**Comment by asklar** [comment]
@dannyvv can you check whether it works for you on 7? it works for me :)
