### ISSUE TITLE
npx react-native run-windows breaks react-native node_module

### ISSUE THREAD

**Issue by bralax** [microsoft/react-native-windows#5565]
### Environment

1. I am working in a VirtualBox virtual machine downloaded here: [https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/)
2. I then installed chocolatey, node and ran the dependency installer provided by Microsoft.
3. I installed C/C++ development for windows in visual studio 2019

`react-native run-windows --info`:   
> System:
>     OS: Windows 10 10.0.19041
>     CPU: (1) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
>     Memory: 458.73 MB / 2.00 GB
>   Binaries:
>     Node: 12.18.2 - C:\Program Files\nodejs\node.EXE
>     Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
>     npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
>   npmPackages:
>     react: 16.11.0 => 16.11.0
>     react-native: ^0.62.0-0 => 0.62.2
>     react-native-windows: ^0.62.0-0 => 0.62.2
>   Installed UWP SDKs:
>     10.0.16299.0
>     10.0.17134.0
>     10.0.17763.0
>     10.0.18362.0

- Target Platform Version(s): (any)
- Target Device(s): Desktop
- Visual Studio Version: Visual Studio 2019
- Build Configuration:  Debug

### Steps to Reproduce

1. I pulled my existing project from GitHub
2. Ran yarn at the root of the project 
3. ran `npx react-native run-windows`

### Expected Behavior

I thought the project would build. I might have some issues with unlinked dependencies as I setup this vm just to fix those issues and build the project.

### Actual Behavior

The build crashed.

The main window gave this issue:

> npx react-native run-windows
>  √ Found MSBuild v16.0 at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin (16.6.30204.135)
> - Restoring NuGet packages C:\Users\User\AppData\Local\Temp\nuget.4.9.2.exe
>  √ Restoring NuGet packages
>  √ Found MSBuild v16.0 at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin (16.6.30204.135)
>  √ Found Solution: C:/Users/User/Documents/2020-spring-group-Gecko/project/gecko-frontend/native/windows/native.sln
>  i Build configuration: Debug
>  i Build platform: x86
>  √ Building Solution
>  √ Starting the React-Native Server
>  √ Removing old version of the app
>  √ Enabling Developer Mode
>  / Installing new version of the app from layout- Failed to deploy: Installing new version of the app fr × Failed to deploy: Installing new version of the app from layout
> Re-run the command with --logging for more information

The secondary command prompt also popped up before it crashed and gave this:

> native@0.0.1 start C:\Users\User\Documents\2020-spring-group-Gecko\project\gecko-frontend\native
> 
>
> react-native start
>
> 
> internal/modules/cjs/loader.js:969
>   throw err;
>   ^
> 
> Error: Cannot find module 'C:\Users\User\Documents\2020-spring-group-Gecko\project\gecko-frontend\native\node_modules\react-native\cli.js'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:842:27)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
>     at internal/main/run_main_module.js:17:47 {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: []
> }
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! native@0.0.1 start: `react-native start`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the native@0.0.1 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2020-07-21T18_53_56_485Z-debug.log
> 

After this all happened the first time, I wanted to try again so I cleaned out all of the node_modules directories and re-ran yarn. I then [confirmed](https://drive.google.com/file/d/1Qof-f8-4nqoAuzCckq7mDw3jeRg_a48z/view?usp=sharing) that react-native was a valid and [full module](https://drive.google.com/file/d/1qlru2isS2g8tKDUIPR_EdLgBBKj6TK2q/view?usp=sharing) in the node_modules folder.

I then re-ran npx react-native run-windows with the folder open in finder and right before the secondary window opened, everything in the folder disappeared and a minute later the app crashed.  Looking in the node_modules react-native became [a link](https://drive.google.com/file/d/1y7GGb0dxSiqKZ7THTWdJIICpRZSYvhuu/view?usp=sharing) to a non-existent place.

I don't know what could be causing it.

### react-native run-windows --logging

[log.txt](https://github.com/microsoft/react-native-windows/files/4956344/log.txt)

**Comment by asklar** [comment]
Hi @bralax , thanks for reaching out. I'm pretty sure the first issue is something we fixed recently in master but haven't shipped a fix down to 62 yet (@jonthysell was working on porting the fixes necessary). #5581 tracks that.
For the time being you should be able to get unblocked by opening the .sln file in visual studio and building/deploying with F5. After the first time you do that, from that point on you should be able to build in the command line as you are [trying to do/doing] today.

As for the other issue, I'm not too sure what's going on, I can't access the google drive links :(

**Comment by bralax** [comment]
Hi @asklar Thank you so much for the help. I was finally able to work on my application by running it in debug through visual studio. It still however crashes in the same way when running from the command line. As for other issue, that was my fault and has been resolved.

**Comment by chrisglein** [comment]
If we're reading it correctly it sounds like the fix you need (#5581) has been serviced to 0.62 (and is in our upcoming preview of 0.63). So if you update to latest there I believe you're unblocked? Going to close this out but speak up if we got it wrong.

@asklar Can you identify the right set of other changes we might want to backport to avoid these first Windows hits?
