### ISSUE TITLE
Provide implementation for View's accessible prop

### ISSUE THREAD

**Issue by rigdern** [Microsoft/react-native-windows#557]

**Comment by zholobov** [comment]
`accessible` property functionality intersects with `importantForAccessibility` on Android. It's not clear which one should take precedence if, for example, on Android someone sets `accessible=yes` and `importantForAccessibility=no`. Maybe we should not implement `accessible` and instead implement `importantForAccessibility` only?

**Comment by rozele** [comment]
@zholobov - should we close this out? Do we need to have both `accessible` and `importantForAccessibility`?

**Comment by zholobov** [comment]
@rozele In my opinion, we don't need to implement `accessible`. But we should document that in React Native Windows `accessible` is noop. I guess proper place for such a documentation is [here](https://github.com/Microsoft/react-native-windows/blob/master/docs/CoreParityStatus.md)? I'll go create a PR.

**Comment by rozele** [comment]
Happy to close this if not necessary for UWP.
