### ISSUE TITLE
React Navigation Drawer [jest in not defined]

### ISSUE THREAD

**Issue by Hawiie13** [microsoft/react-native-windows#5593]
### Environment

1. `react-native -v`:
react-native: 0.62.2

2. `react-native run-windows --info`:
System:
    OS: Windows 10 10.0.18362
    CPU: (4) x64 Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz
    Memory: 1.04 GB / 7.88 GB
  Binaries:
    Node: 11.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.13.0 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 16.11.0 => 16.11.0
    react-native: ^0.62.0-0 => 0.62.2
    react-native-windows: ^0.62.0-0 => 0.62.2
  Installed UWP SDKs:
    10.0.17134.0
    10.0.18362.0
    10.0.19041.0

3. `npm ls react-native-windows`:
react-native-windows@0.62.2 

4. `node -v`:
v11.15.0

5. `npm -v`:
6.14.6

6. `yarn --version`:

Then, specify:

- Target Platform Version(s):
10.0.18362

- Target Device(s):
Desktop

- Visual Studio Version:
2019

- Build Configuration:
Debug

### Steps to Reproduce

(Write your steps here:)

1. Install @react-navigation/drawer
2. Update react-native-reanimated to 1.10.1
3.run npx react-native run-windows --reset-cache

### Expected Behavior

* Show Nagivation Drawer *
![image](https://user-images.githubusercontent.com/4424330/88093849-75effc80-cb47-11ea-8271-591bd3713e45.gif)

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

I install react navigation drawer and update the react-native-reanimated to 1.10.1 (  [this fix drawer issue](https://github.com/software-mansion/react-native-reanimated/pull/1000#issue-453782600) )
but after I import the @react-navigation/drawer
import {createDrawerNavigator} from '@react-navigation/drawer';
I got this error

![image](https://user-images.githubusercontent.com/6790102/88479036-121e6700-cf7f-11ea-8f3e-5fab28335219.png)

![image](https://user-images.githubusercontent.com/6790102/88478946-a50ad180-cf7e-11ea-8f9b-0ebb0db04474.png)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

### Additional context

(Write any other additional context that may help in root causing the issue.)

**Comment by chrisglein** [comment]
@kaiguo I believe you've implemented this, yes? This issue may have just been opened before you did. Feel free to link and close.

**Comment by kaiguo** [comment]
Yeah drawer should be hooked up and the code is checked in to master. But it's not released yet, so @Hawiie13 please wait for the next release that includes this change https://github.com/react-navigation/react-navigation/pull/8570.
