### ISSUE TITLE
Is it possible to write a "native module" for Windows Runtime for Javascript Libraries?

### ISSUE THREAD

**Issue by bralax** [microsoft/react-native-windows#5602]
I am currently working on a project and am using react-native-windows to try to create a version for windows. I have a UWP Library that i need to use that only exists in Javascript (based on the limited documentation). I am perfectly fine writing a wrapper around it as I see based on #4759, even though React-Native and the Runtime are both in Javascript, they are not connected. My question is whether it is possible to do this and if so, how would one start on it? There is documentation on how to work with C++/C# libraries on the projects website but not javascript.

**Comment by asklar** [comment]
It is not currently possible to write a native module in Javascript. 
There are 3 possible avenues for writing a JS app in Windows:
- WinJS is a Javascript projection of WinRT - no new features being added/as-is support: https://github.com/winjs/winjs
- PWA - https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps-edgehtml/
However as far as I can tell this avenue doesn't let you write a module
- a different JS projection like cppwinrt that would let you write a WinRT component (dll). I'm not aware of one TBH.

So:
- You can create a UWP app in JS but not a WinRT component (i.e. a DLL). See https://docs.microsoft.com/en-us/windows/uwp/get-started/create-a-hello-world-app-js-uwp for WinJS.
- To create the app, only VS 2017 is supported, not 2019.
- WinJS allows calling WinRT interfaces but does not allow **implementing** WinRT interfaces which is a requirement for writing a native module in Windows.
