### ISSUE TITLE
Unable to create native module method in C# using ReactPromise<JSValueObject>

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#5617]
When writing a native module in C#, you can't seem to be able to define a promise-based method that returns a `JSValueObject`.

It compiles, but at runtime an exception is thrown in `JSValueGenerator`:

> System.NullReferenceException
>   HResult=0x80004003
>   Message=Object reference not set to an instance of an object.
>   Source=camera62cs
>   StackTrace:
>    at Microsoft.ReactNative.Managed.JSValueWriterGenerator.<>c.<GenerateWriteValueForClass>b__20_3(<>f__AnonymousType12`2 <>h__TransparentIdentifier0) in C:\code\camera62cs\node_modules\react-native-windows\Microsoft.ReactNative.SharedManaged\JSValueWriterGenerator.cs:line 226
> 

This repos on 0.61 and 0.62, I'm not sure if it repos with the code-gen in 0.63.

The workaround is to use `ReactPromise<JSValue>` which works just fine.

Sample module I was testing, where I'm using the workaround: https://github.com/microsoft/react-native-windows-samples/blob/master/samples/NativeModuleSample/csharp/windows/NativeModuleSample/AsyncMethodExamples.cs

**Comment by chrisglein** [comment]
Worth checking on 0.63 as it sounds like @dannyvv has rewritten a lot of code around here. Danny do you know if this issue still repros?

**Comment by asklar** [comment]
@vmoroz I think you wrote the promise stuff, is this still applicable?

**Comment by acoates-ms** [comment]
@dannyvv I think knows the C# side better.

**Comment by dannyvv** [comment]
Side-Note: C# now has Task<T> support:

The following will work just fine now.

```cs
        public struct Result
        {
            public int statusCode { get; set; }
            public string content { get; set; }
        }

        [ReactMethod]
        public async Task<object> GetHttpResponseAsync(string uri)
        {
            // Create an HttpClient object
            var httpClient = new HttpClient();

            // Send the GET request asynchronously
            var httpResponseMessage = await httpClient.GetAsync(new Uri(uri));

            var statusCode = httpResponseMessage.StatusCode;
            var content = await httpResponseMessage.Content.ReadAsStringAsync();
            
            return new Result()
            {
                statusCode = (int) statusCode,
                content = content,
            };
        }
```

**Comment by dannyvv** [comment]
This discovered 2 issues:
 * There was no direct serialization for JsValueObject
 * The C# codegen assumed people used the interface IReactPromise<T> and not the instance struct. 
The Associated PR addresses both.

**Comment by dannyvv** [comment]
Still need backporting to 0.63

**Comment by NickGerleman** [comment]
>
