### ISSUE TITLE
ScrollView embedded in Animated.View not responding to touch

### ISSUE THREAD

**Issue by rozele** [Microsoft/react-native-windows#563]
Will follow up with repro.

**Comment by rozele** [comment]
The repro is embedding a ScrollView in an Animated.View with a translate animation.  Even the XAML approach does not work:

  <Canvas Width="200" Height="200">
            <Canvas.Projection>
                <Matrix3DProjection ProjectionMatrix="1, 0, 0, 0,
                                                      0, 1, 0, 0,
                                                      0, 0, 1, 0,
                                                      0, 1, 0, 1">
                </Matrix3DProjection>
            </Canvas.Projection>
            <ScrollViewer Width="200" Height="200">
                <Canvas Width="200" Height="400">
                    <Rectangle Width="200" Height="200" Fill="Blue" />
                    <Rectangle Width="200" Height="200" Canvas.Top="200" Fill="Red" />
                </Canvas>
            </ScrollViewer>
        </Canvas>

**Comment by rozele** [comment]
@chukcha-wtf could you take a look at this commit https://github.com/rozele/react-native-windows/commit/a316f3db574eca81d448b822b216007c99c5370d and see if this:
a) would allow you to remove your current workaround for this issue
b) also does not cause that weird issue where the hit targets are messed up by the Composite3DTransform?

The theory is that we can work around this issue with the RenderTransform at least until we can get a resolution for why ScrollViewer and Matrix3DProjection do not cooperate.

**Comment by rozele** [comment]
It would be good to follow up if the hack is still needed for newer versions of UWP.

**Comment by chukcha-wtf** [comment]
@rozele It's hard to say for sure, it seems that we're still using it on top of 0.46 but tbh we haven't tried app w/out this hack.

**Comment by rozele** [comment]
We seem to have a sufficient workaround for this given the lack of activity.
