### ISSUE TITLE
Fix dependency in integration tests on OS dispatcher type

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#5641]
This will probably not work in WinUI 3 so we'll have to address it at some point

https://github.com/microsoft/react-native-windows/blob/7236d61e5736083eec1992df73183c400c787306/vnext/Microsoft.ReactNative.IntegrationTests/ReactInstanceSettingsTests.cpp#L29

https://github.com/microsoft/react-native-windows/blob/f2aa9eeacca65f709b74740b715a282fdae5486b/vnext/Microsoft.ReactNative.IntegrationTests/ReactNativeHostTests.cpp#L81

https://github.com/microsoft/react-native-windows/blob/2f30afa4f87e0b6c3a5003b573589e698d27bdef/vnext/Microsoft.ReactNative.IntegrationTests/TurboModuleTests.cpp#L178

**Comment by chrisglein** [comment]
The dispatchers may work, but may not maintain guarantees about correct ordering (which could cause subtle problems and some gnarly investigations).

**Comment by chiaramooney** [comment]
Current test suite work will focus on validate Fabric. This is not something we plant to address on Paper.
