### ISSUE TITLE
Reload button says "Reload (NYI)" (Not Yet Implemented) but in fact works

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#5655]
## Environment

npx react-native -v
```
error: unknown option `-v'
```

npx react-native run-windows --info
```
  System:
    OS: Windows 10 10.0.18363
    Memory: 2.22 GB / 15.92 GB
  Binaries:
    Node: 12.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.3 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: ^16.13.1 => 16.13.1
    react-native: ^0.62.0-0 => 0.62.2
    react-native-windows: ^0.62.0-0 => 0.62.2
  Installed UWP SDKs:
    10.0.14393.0
    10.0.17763.0
    10.0.18362.0
```
reg query "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock"
```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock
    AllowDevelopmentWithoutDevLicense    REG_DWORD    0x1
    AllowAllTrustedApps    REG_DWORD    0x1
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Do something dump in your JavaScript
2. Get error screen
3. Be dissuaded from clicking button that totally works

## Expected Results
Button that works doesn't indicate that it doesn't work.

## Snack, code example, screenshot, or link to a repository:
![image](https://user-images.githubusercontent.com/26607885/89586494-a6e15a00-d7f4-11ea-9a6f-c2201668c052.png)

**Comment by acoates-ms** [comment]
Wow.. that's amazing.  It's been like that for ages.
