### ISSUE TITLE
Catalog API completion of View/Text/Image props

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#5677]
The "props" documentation is separate from the components documentation, and through discovery of issues like #5668 it seems like we maybe missed a scrub of the props for API completion. Specifically, these pages:
https://reactnative.dev/docs/image-style-props
https://reactnative.dev/docs/layout-props
https://reactnative.dev/docs/shadow-props
https://reactnative.dev/docs/text-style-props
https://reactnative.dev/docs/view-style-props

## Environment
npx react-native --version
```4.10.1```
npx react-native run-windows --info
```
  System:
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 3.66 GB / 15.92 GB
  Binaries:
    Node: 12.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.3 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: ^16.13.1 => 16.13.1
    react-native: ^0.62.0-0 => 0.62.2
    react-native-windows: ^0.62.0-0 => 0.62.2
  Installed UWP SDKs:
    10.0.14393.0
    10.0.17763.0
    10.0.18362.0
```
reg query "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock"
```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock
    AllowDevelopmentWithoutDevLicense    REG_DWORD    0x1
    AllowAllTrustedApps    REG_DWORD    0x1
```

## Steps To Reproduce
Use any of the style props defined in these pages:
https://reactnative.dev/docs/image-style-props
https://reactnative.dev/docs/layout-props
https://reactnative.dev/docs/shadow-props
https://reactnative.dev/docs/text-style-props
https://reactnative.dev/docs/view-style-props

## Expected Results
Any property that doesn't work has a tracking issue on this repo. Some are, some are not. The goal here is to track those that are not.

### Image Style props
https://github.com/microsoft/react-native-windows/projects/18
#2111

- borderTopRightRadius
- backfaceVisibility
- borderBottomLeftRadius
- borderBottomRightRadius
- borderColor
- borderRadius
- borderTopLeftRadius
- backgroundColor
- borderWidth
- opacity
- overflow
- resizeMode
- tintColor
- overlayColor

### Layout props
#2636

- alignContent
- alignItems
- alignSelf
- aspectRatio
- borderBottomWidth
- borderEndWidth
- borderLeftWidth
- borderRightWidth
- borderStartWidth
- borderTopWidth
- borderWidth
- bottom
- direction
- display
- end
- flex
- flexBasis
- flexDirection
- flexGrow
- flexShrink
- flexWrap
- height
- justifyContent
- left
- margin
- marginBottom
- marginEnd
- marginHorizontal
- marginLeft
- marginRight
- marginStart
- marginTop
- marginVertical
- maxHeight
- maxWidth
- minHeight
- minWidth
- overflow
- padding
- paddingBottom
- paddingEnd
- paddingHorizontal
- paddingLeft
- paddingRight
- paddingStart
- paddingTop
- paddingVertical
- position
- right
- start
- top
- width
- zIndex

### Shadow props
#2800

- shadowColor
- shadowOffset
- shadowOpacity
- shadowRadius

### Text Style props
#4155
#5187
#5668 

- textShadowOffset
- color
- fontSize
- fontStyle
- fontWeight
- lineHeight
- textAlign
- textDecorationLine
- textShadowColor
- fontFamily
- textShadowRadius
- includeFontPadding
- textAlignVertical
- fontVariant
- letterSpacing
- textDecorationColor
- textDecorationStyle
- textTransform
- writingDirection

### View Style props
https://github.com/microsoft/react-native-windows/projects/19
#3078
#3077

- borderRightColor
- backfaceVisibility
- borderBottomColor
- borderBottomEndRadius
- borderBottomLeftRadius
- borderBottomRightRadius
- borderBottomStartRadius
- borderBottomWidth
- borderColor
- borderEndColor
- borderLeftColor
- borderLeftWidth
- borderRadius
- backgroundColor
- borderRightWidth
- borderStartColor
- borderStyle
- borderTopColor
- borderTopEndRadius
- borderTopLeftRadius
- borderTopRightRadius
- borderTopStartRadius
- borderTopWidth
- borderWidth
- opacity
- elevation

## Snack, code example, screenshot, or link to a repository:
TBD
Some of these can be checked via playground, some are not exercised at all (and either need manual repros or new test pages).

**Comment by chiaramooney** [comment]
Reopened View - Style API completion project. 

- Added one existing issue to project which is tracking incomplete/not working functionality for backfaceVisibility prop.
- Remaining props that are lacking functionality already have issues tracking the work needed and are added to the project. (i.e. borderStyling and border*Color)
- Sample usage of View style props added to gallery microsoft/react-native-gallery#142

**Comment by chiaramooney** [comment]
Reopened Image - API Completion Project.

- Created issue tracking incorrect functionality of backfaceVisibility style prop #8001 
- Created issue tracking implementation of backgroundColor style prop for Image #8011 
- Sample usage of Image style props added to gallery microsoft/react-native-gallery#144

**Comment by chiaramooney** [comment]
Opened Text - API Completion Project
- Created issue tracking implementation of textShadow* props. #8012
- Created issue tracking implementation of letter spacing style prop. #8013 
- Sample usage of Text style props added to gallery microsoft/react-native-gallery#147

**Comment by chiaramooney** [comment]
All layout style props are implemented and functional
