### ISSUE TITLE
TextInput Controls in TextInputExample Only Show Correctly After Window Resize

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#5686]
Tested on x86 debug using web debugging on 0.0.0-canary.137

Before Resize
![image](https://user-images.githubusercontent.com/835219/89888236-7b5bc800-db84-11ea-986e-9200b74ebf78.png)

After Resize
![image](https://user-images.githubusercontent.com/835219/89888265-89a9e400-db84-11ea-8df1-eb0a3a06a771.png)

The code creating these: https://github.com/facebook/react-native/blob/c03b7dd772803484f18c08d6bfe5bd7837e4b541/RNTester/js/examples/TextInput/TextInputSharedExamples.js

No explicit height it set. Discovered this after adding back a working TextInputExample. Unsure how long-lived the issue has been.

**Comment by chrisglein** [comment]
@rectified95 This sounds related to your investigation to zero height issues with controls. Can you give a look and see how this overlaps?

**Comment by rectified95** [comment]
@chrisglein I'm surprised some of the TextInputs here render at all before the resize. 
I'd say this can be closed, since #5437 records the issue for this control, and the resize context can be included there.
