### ISSUE TITLE
Support react-native-clipboard

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#5694]
# Support `react-native-clipboard` on RNW

## Basic Info
- Module Repo URL: [link to repo](https://github.com/react-native-community/clipboard)
- Target version: 0.62+
- [ ] Issue exists on module repo

- [ ] Module has a Legacy/C# implementation

## Which app/customer is requesting this module?
This is currently being investigated for [macOS](https://github.com/microsoft/react-native-macos/issues/388).
It also looks like there's a PR to add [Web](https://github.com/react-native-community/clipboard/pull/59) support, so this is on the cusp of being a multi-platform module.

**Comment by stmoy** [comment]
In PR: https://github.com/react-native-community/clipboard/pull/70

**Comment by asklar** [comment]
PR merged, awaiting new npm package release and adding it to reactnative.directory

**Comment by asklar** [comment]
And done!
