### ISSUE TITLE
App fails App Certification on 0.63 preview 1

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#5737]
## Environment
```
npx react-native --version
4.12.0
npx react-native run-windows --info
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 4.76 GB / 15.92 GB
  Binaries:
    Node: 12.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.3 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
    react-native-windows: ^0.63.0-0 => 0.63.0-preview.2
  Installed UWP SDKs:
    10.0.14393.0
    10.0.17763.0
    10.0.18362.0
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock
    AllowDevelopmentWithoutDevLicense    REG_DWORD    0x1
    AllowAllTrustedApps    REG_DWORD    0x1
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. sln -> Publish -> Create App Packages
2. Ignore "Certificate is password protected" prompt?
3. Select distribution method: Microsoft Store as "<app name>" by "<publisher name>"
4. Select and configure packages: create
5. wait
6. Launch Windows App Certification Kit
7. Next
8. wait more
9. Errors!

##### Supported APIs
Error Found: The supported APIs test detected the following errors:
```
API __CxxFrameHandler4 in vcruntime140_1_app.dll is not supported for this application type. src.exe calls this API.
API AppPolicyGetWindowingModel in api-ms-win-appmodel-runtime-l1-1-2.dll is not supported for this application type. Microsoft.ReactNative.dll calls this API.
API __CxxFrameHandler4 in vcruntime140_1_app.dll is not supported for this application type. Microsoft.ReactNative.dll calls this API.
API __CxxFrameHandler4 in vcruntime140_1_app.dll is not supported for this application type. ReactNativeAsyncStorage.dll calls this API.
```

##### Type location
Error Found: The type location test detected the following errors:
```
The types in the Windows.AI.MachineLearning namespace are located in file C:\Program Files\WindowsApps\REDACTED_1.0.0.0_x64__1xbcbvy0ms58g\Windows.AI.MachineLearning.MachineLearningContract.winmd that does not match the namespace.
The types in the Windows.AI.MachineLearning.Preview namespace are located in file C:\Program Files\WindowsApps\REDACTED_1.0.0.0_x64__1xbcbvy0ms58g\Windows.AI.MachineLearning.Preview.MachineLearningPreviewContract.winmd that does not match the namespace.
The types in the Windows.ApplicationModel.Background namespace are located in file C:\Program Files\WindowsApps\REDACTED_1.0.0.0_x64__1xbcbvy0ms58g\Windows.ApplicationModel.Calls.Background.CallsBackgroundContract.winmd that does not match the namespace.
The types in the Windows.ApplicationModel.Calls.Background namespace are located in file C:\Program Files\WindowsApps\REDACTED_1.0.0.0_x64__1xbcbvy0ms58g\Windows.ApplicationModel.Calls.Background.CallsBackgroundContract.winmd that does not match the namespace.
The types in the Windows.ApplicationModel.Calls namespace are located in file C:\Program Files\WindowsApps\REDACTED_1.0.0.0_x64__1xbcbvy0ms58g\Windows.ApplicationModel.Calls.CallsPhoneContract.winmd that does not match the namespace.
```
(lots lots more of these)

##### Type name correctness
Error Found: The type name correctness test detected the following errors:
```
The Windows.AI.MachineLearning.LearningModelDeviceKind type in the C:\Program Files\WindowsApps\REDACTED_1.0.0.0_x64__1xbcbvy0ms58g\Windows.AI.MachineLearning.MachineLearningContract.winmd file is in the Windows namespace.
The Windows.AI.MachineLearning.LearningModelFeatureKind type in the C:\Program Files\WindowsApps\REDACTED_1.0.0.0_x64__1xbcbvy0ms58g\Windows.AI.MachineLearning.MachineLearningContract.winmd file is in the Windows namespace.
The Windows.AI.MachineLearning.TensorKind type in the C:\Program Files\WindowsApps\REDACTED_1.0.0.0_x64__1xbcbvy0ms58g\Windows.AI.MachineLearning.MachineLearningContract.winmd file is in the Windows namespace.
The Windows.AI.MachineLearning.IImageFeatureDescriptor type in the C:\Program Files\WindowsApps\REDACTED_1.0.0.0_x64__1xbcbvy0ms58g\Windows.AI.MachineLearning.MachineLearningContract.winmd file is in the Windows namespace.
```
(lots lots more of these)

##### General metadata correctness
Error Found: The general metadata correctness test detected the following errors:
```
The type Windows.Foundation.IAsyncInfo in file C:\Program Files\WindowsApps\REDACTED_1.0.0.0_x64__1xbcbvy0ms58g\Windows.Foundation.FoundationContract.winmd has the same GUID as the following types: Windows.Foundation.IAsyncInfo. All GUIDs must be unique.
The type Windows.Devices.SmartCards.ISmartCardCryptogramStorageKeyInfo2 in file C:\Program Files\WindowsApps\REDACTED_1.0.0.0_x64__1xbcbvy0ms58g\Windows.Devices.SmartCards.SmartCardEmulatorContract.winmd has the same GUID as the following types: Windows.Devices.SmartCards.ISmartCardCryptogramStorageKeyInfo2. All GUIDs must be unique.
The type Windows.Graphics.Printing3D.IPrinting3DColorMaterialGroup in file C:\Program Files\WindowsApps\REDACTED_1.0.0.0_x64__1xbcbvy0ms58g\Windows.Graphics.Printing3D.Printing3DContract.winmd has the same GUID as the following types: Windows.Graphics.Printing3D.IPrinting3DColorMaterialGroup. All GUIDs must be unique.
The type Windows.UI.Xaml.Media.Animation.IConnectedAnimationConfiguration in file C:\Program Files\WindowsApps\REDACTED_1.0.0.0_x64__1xbcbvy0ms58g\Windows.Foundation.UniversalApiContract.winmd has the same GUID as the following types: Windows.UI.Xaml.Media.Animation.IConnectedAnimationConfiguration. All GUIDs must be unique.
```
(lots lots more of these)

## Expected Results
App Certification passes.

## Snack, code example, screenshot, or link to a repository:
https://github.com/chrisglein/react-native-github-dashboard/tree/update063
App is not a huge departure from a newly created app. Has one added module dependency, which is async storage. App also has integrated react-native-web.

**Comment by chrisglein** [comment]
@NickGerleman Is it possible that PR #5691 has the fix for the `__CxxFrameHandler4` errors above? That PR isn't currently labeled for 0.63 backport - should we take it?

**Comment by NickGerleman** [comment]
@chrisglein CxxFrameHandler4 being flagged by WACK shows up only in older versions of WACK. It shouldn't show up in new versions of WACK (we run it in CI) or when submitting to the store. The issue effected all UWP apps using Visual Studio 2019, and will get some Google hits if you search for the error. We're no longer able to disable CxxFrameHandler4 in new MSVC versions actually (we were using an undocumented flag to do it before). 

Could you try running this again with a newer version of MSVC/WACK or trying to submit to the store?

**Comment by asklar** [comment]
@chrisglein This passes with the 19041 cert kit. It's important to always run local wack against the latest available kit. The store may run an even newer, unreleased wack.

![image](https://user-images.githubusercontent.com/22989529/90286535-ef1efe80-de2a-11ea-8946-d88ee1209c1e.png)

**Comment by chrisglein** [comment]
Confirmed the `__CxxFrameHandler4 ` errors go away on 10.0.19041.1.
Still hitting Type location / type name correctness / general metadata correctness errors.

We either need to link to existing troubleshooting or add our own as part of [#62](https://github.com/microsoft/react-native-windows-samples/issues/62).

**Comment by mudaligekosala** [comment]
@chrisglein What kind of troubleshooting can we do fix these Type location / type name correctness / general metadata correctness validation errors

**Comment by mudaligekosala** [comment]
Downgrading the version of cppwinrt nuget package to 2.0.200602.3 (in my project not the libraries's packages) worked for me.

**Comment by chiaramooney** [comment]
Gallery faced same WACK failures with type location / type name correctness / general metadata correctness validation. Cppwinrt repo [thread](https://github.com/Microsoft/cppwinrt/issues/738) explains that this was a cppwinrt error. Updating gallery's copy of cppwinrt to the latest fixed the issue.

**Comment by marnusw** [comment]
@chrisglein since RNW 0.63 seems to still be actively maintained I'm wondering whether it makes sense to downgrade cppwinrt to 2.0.200602.3 in this version so it can pass WACK without any custom changes? Since react-native-tvos is still on 0.63 using this version of RNW is the only option in a monorepo project. I can confirm this is the only requirement for RNW 0.63 apps to pass WACK.

**Comment by chrisglein** [comment]
Workarounds for anyone else hitting this are to similarly downgrade their cppwinrt version to `2.0.200602.3` (down from what RNW 0.63 defaults to), to upgrade to a newer version of cppwinrt, or to upgrade to RNW 0.64. New apps on 0.64+ shouldn't hit this if they use the 0.64 app template.
