### ISSUE TITLE
DevMenu box shows clipped in Islands

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#5741]
Something is wrong with the sizing in islands (dialog shows only tall enough to fit 3 options instead of all of them) - same layout looks ok in UWP

![image](https://user-images.githubusercontent.com/22989529/90304432-89ebfd00-de6c-11ea-9aa3-57e6fcc530a5.png)

**Comment by chrisglein** [comment]
Dev Menu may be trying to not clip the app, so this could be an issue with the layout policy for the Dev Menu.
