### ISSUE TITLE
Move RedBox to XAML markup file

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#5743]
We currently have a few places where we have a large-ish control that gets created by parsing a string of text with xaml markup at runtime. This makes it difficult to use something like the designer and live visual tree to iterate or debug issues.

RedBox and DevMenu are two such controls that follow this pattern

Related: #5742

**Comment by chiaramooney** [comment]
Not something we plan to address on the Paper renderer as we move towards Fabric.
This behavior should be different on the non-XAML Fabric renderer.
