### ISSUE TITLE
DLLs not found

### ISSUE THREAD

**Issue by johncaling40** [microsoft/react-native-windows#5747]
When I try to launch the standalone app, I get the following errors:

- The code execution cannot proceed because MSVCP140_APP.dll was not found. Reinstalling the program may fix this problem.
- The code execution cannot proceed because VCRUNTIME140_APP.dll was not found. Reinstalling the program may fix this problem. 
- The code execution cannot proceed because MSVCP140_1_APP.dll was not found. Reinstalling the program may fix this problem.

## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`: 4.12.0
2. `npx react-native run-windows --info`: ` System:
    OS: Windows 10 10.0.20190
    CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
    Memory: 20.03 GB / 31.95 GB
  Binaries:
    Node: 14.4.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
    react-native-windows: ^0.63.0-0 => 0.63.0-preview.2
  Installed UWP SDKs:
    10.0.17763.0
    10.0.18362.0'
3. `reg query "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock"`: `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock
    AllowDevelopmentWithoutDevLicense    REG_DWORD    0x1
    AllowAllTrustedApps    REG_DWORD    0x1`

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Follow the steps in [this](https://microsoft.github.io/react-native-windows/docs/getting-started) guide until the last step. 
2. See error on step ***Building a standalone React Native Windows App***

## Expected Results
Describe what you expected to happen.
I expected the standalone app to launch properly. 

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
https://microsoft.github.io/react-native-windows/docs/getting-started#building-a-standalone-react-native-windows-app
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by johncaling40** [comment]
I figured it out. I was trying to run the exe that is created in windows/x64/Release. When I run this exe, it gives the error. I did not realize that it was adding the application to the start menu when I built it. When I run the application form the start menu, it works fine.

**Comment by petr7555** [comment]
Is there a way to create a standalone .exe that is not missing the DLLs?

**Comment by shashwatjolly** [comment]
Facing the same issue. 
@johncaling40 are you sure starting it from the start menu isn't loading the debug version? I think it is for me. Can you try with the metro bundler not running?

**Comment by petr7555** [comment]
For me to run the app in start menu I need to have a bundler running.

**Comment by shashwatjolly** [comment]
I just saw https://github.com/microsoft/react-native-windows/issues/5855#issuecomment-692241113
It seems we can't just run the exe :)
My use case is satisfied with building it in release config with `npm react-native run-windows --release`. 
The other alternative seems to be making an installer using Visual Studio.

**Comment by asklar** [comment]
you have to build the app in release mode and then you can deploy the generated APPX file. This can be done in Visual Studio, or alternatively the CLI will do it for you when you pass `--release`

**Comment by imuhammadarsalan** [comment]
I am also facing the same issue the DLL files are missing when exe the file ....

**Comment by jonthysell** [comment]
Closing necro-bump. UWP apps cannot be launched by double-clicking the exe. See https://learn.microsoft.com/en-us/windows/uwp/get-started/universal-application-platform-guide
