### ISSUE TITLE
How do I create a setup/installer for the app?

### ISSUE THREAD

**Issue by johncaling40** [microsoft/react-native-windows#5748]
How do I create a setup/installer for the app? When I build the app, it adds the app to start menu and I can run it from there. How do I create a installer that will install the app on another persons machine?

**Comment by asklar** [comment]
The .appx file that is generated is the installer. Normally UWP apps are distributed and installed by the Microsoft store. See [the documentation] (https://docs.microsoft.com/en-us/windows/uwp/publish/)

**Comment by johncaling40** [comment]
Does that mean that I can only distribute the app through the app store?

**Comment by kmelmon** [comment]
Yes as far as UWP goes, the distribution path is through the app store.  We are working on a way to make it possible to use react-native-windows in a win32 app but this isn't ready for public consumption yet.  Keep an eye out for our blog posts as we evolve this.

**Comment by johncaling40** [comment]
K.
