### ISSUE TITLE
e2etest crashes in CI

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#5763]
https://dev.azure.com/ms/react-native-windows/_build/results?buildId=102185&view=artifacts&type=publishedArtifacts

[Crash dump](https://artprodwus21.artifacts.visualstudio.com/Aea964927-e753-4550-bf48-b63004033439/8d8e50dd-c5b4-4b44-8668-86558c5aa5b7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zL3Byb2plY3RJZC84ZDhlNTBkZC1jNWI0LTRiNDQtODY2OC04NjU1OGM1YWE1YjcvYnVpbGRJZC8xMDIxODUvYXJ0aWZhY3ROYW1lL1JlYWN0VVdQVGVzdEFwcFRyZWVEdW1wLTE1/content?format=file&subPath=%2FCrashDumps%2FReactUWPTestApp.exe.2284.dmp)
[AppxSym](https://artprodwus21.artifacts.visualstudio.com/Aea964927-e753-4550-bf48-b63004033439/8d8e50dd-c5b4-4b44-8668-86558c5aa5b7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zL3Byb2plY3RJZC84ZDhlNTBkZC1jNWI0LTRiNDQtODY2OC04NjU1OGM1YWE1YjcvYnVpbGRJZC8xMDIxODUvYXJ0aWZhY3ROYW1lL1JlYWN0VVdQVGVzdEFwcC0x0/content?format=file&subPath=%2FAppPackages%2FReactUWPTestApp_1.0.0.0_x64_Test%2FReactUWPTestApp_1.0.0.0_x64.appxsym)

Seems like an exception about file in use:
```
0:008> dv
                   e = 0x00007ff3`f44c2b20
pRestrictedErrorInfo = struct System::IntPtr
           callbacks = <value unavailable>
0:008> dx -r1 ((SharedLibrary!System::Exception *)0x7ff3f44c2b20)
((SharedLibrary!System::Exception *)0x7ff3f44c2b20)                 : 0x7ff3f44c2b20 [Type: System::IO::FileLoadException * (derived from System::Exception *)]
    [+0x000] m_pEEType        [Type: System::IntPtr]
    [+0x008] _message         : 0x7ff3f44c29e8 [Type: System::String &]
    [+0x010] _data            : 0x7ff3f44c2b88 [Type: System::Collections::IDictionary &]
    [+0x018] _innerException  : 0x0 [Type: System::Exception &]
    [+0x020] _helpURL         : 0x0 [Type: System::String &]
    [+0x028] _source          : 0x0 [Type: System::String &]
    [+0x030] _HResult         : -2147024864 [Type: int]
    [+0x038] _stackTrace      : 0x0 [Type: System::String &]
    [+0x040] _corDbgStackTrace : 0x7ff3f46208c8 [Type: System::IntPtr[] &]
    [+0x048] _idxFirstFreeStackTraceEntry : 24 [Type: int]
    [+0x050] <FileName>k__BackingField : 0x0 [Type: System::String &]
    [+0x058] <FusionLog>k__BackingField : 0x0 [Type: System::String &]

0:008> !error -0n2147024864
Error code: (HRESULT) 0x80070020 (2147942432) - The process cannot access the file because it is being used by another process.
```

**Comment by kmelmon** [comment]
@chrisglein This is a randomly occurring issue, currently happens at a low frequency.
