### ISSUE TITLE
Adding { overflow: hidden } to a view's style will prevent the accessibility label from being read

### ISSUE THREAD

**Issue by niwiller** [microsoft/react-native-windows#5766]
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`: 4.10.1
2. `npx react-native run-windows --info`: 
System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz
    Memory: 16.93 GB / 31.92 GB
  Binaries:
    Node: 12.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.7 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: https://github.com/microsoft/react-native-macos/archive/v0.60.0-microsoft.13.tar.gz => 0.62.2
    react-native-windows: 0.60.0-vnext-headlessjs.49 => 0.62.3
    rnpm-plugin-windows: ^0.2.9 => 0.2.13
  Installed UWP SDKs:
    10.0.15063.0
    10.0.16299.0
    10.0.17134.0
    10.0.17763.0
    10.0.18362.0
    10.0.19041.0
3. `reg query "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock"`
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock
    AllowDevelopmentWithoutDevLicense    REG_DWORD    0x1
    AllowAllTrustedApps    REG_DWORD    0x1

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create a view that has the following properties:
  accessible: true
  acceptsKeyboardFocus: true
  accessibilityLabel: "This value should be read"
  accessibilityRole: "button"
  style: { overflow: hidden }
2. Turn on Narrator
3. Run the application and focus the view with the keyboard
4. Observe that Narrator does not read the label text
5. Repeat with overflow removed and note that Narrator does read the text

## Expected Results

If an accessibility label is set on an element, that label should be read when it's focused, regardless of what value overflow is set to.

As a note, while investigating to determine what was causing this issue, I discovered that the key factor was that when overflow was set to hidden, the focused underlying XAML element was tagged as being in the raw accessibility tree while when overflow was removed, the element was instead in the content accessibility tree.

**Comment by asklar** [comment]
@niwiller thanks for filing! We believe this is the right behavior on Windows, where an element that isn't visible should not be read by accessibility tools.

**Comment by niwiller** [comment]
Hey @asklar, while I agree that generally non-visible things shouldn't be read, overflow hidden does not mean that something is not visible. Its use encompasses situations in which there is no overflow and so nothing will be hidden, or cases in which only part of the content is hidden. In the case that we saw this, we had an image button control (implemented with a view) that has an overlay for text. Since the button itself had overflow hidden, the entire thing was in the wrong accessibility tree even though the button and text were clearly visible. Because the containing component had the overflow hidden, nothing was read even though it was clearly visible.

**Comment by kmelmon** [comment]
Thanks for the report.  Will debug as a first step to see where things are going wrong.

**Comment by kmelmon** [comment]
I am unable to repro this issue out of master branch, which is now on version 0.63.  I looked at how the native XAML code handles overflow:hidden, this just adds a clip to the backing XAML element, which I would not expect to have any effect on Narrator.

Please try on latest as you may have something additional that is triggering this issue.  If so please provide a min repro app and I can look further into this.

Note that as of version 63, the acceptsKeyboardFocus property is deprecated, it has been replaced by the focusable property, so you can just use focusable = true instead.
