### ISSUE TITLE
Dead OpenSSL.nuspec package

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#5769]
We have an OpenSSL.nuspec package in vnext\scripts alongside a targets file, i dont think anyone is using it, it's confusing to have it there

**Comment by JunielKatarn** [comment]
It's not "dead".
We use it to generate the RNW-specific NuGet.

It will be updated soon.

**Comment by asklar** [comment]
@JunielKatarn I couldn't find anything that uses this specific nuspec, can you please point to where this is packaged?

**Comment by JunielKatarn** [comment]
Generated NuGet package is published here.

https://dev.azure.com/ms/react-native/_packaging?_a=package&feed=react-native-public%40Local&package=ReactWindows.OpenSSL.StdCall.Static&protocolType=NuGet&version=1.0.2-p.5

**Comment by asklar** [comment]
@JunielKatarn where is the package being created? there are no references to this nuspec within the react-native-windows repo as far as I can see
