### ISSUE TITLE
react-native-splash-screen

### ISSUE THREAD

**Issue by stmoy** [microsoft/react-native-windows#5770]
https://github.com/crazycodeboy/react-native-splash-screen

**Comment by jaimecbernardo** [comment]
The PR with the Windows port of this module has been opened here: https://github.com/crazycodeboy/react-native-splash-screen/pull/514

**Comment by chiaramooney** [comment]
Not something we plan to address on the Paper renderer as we move towards Fabric. If you want this module supported on Fabric, please file an issue on the react-native-splash-screen repo.
