### ISSUE TITLE
React Native config and autolinking does not work in 0.63

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#5771]
In the conversion to TS, both config and autolinking were broken.

Relevant Commits:

https://github.com/microsoft/react-native-windows/commit/5b28bba588d7c2edd076a60353accad9cbe37b34
https://github.com/microsoft/react-native-windows/commit/228e0bc5dc985b6eb71c94395304d99a0d054e2c

Namely, by default the objects created by `react-native config` require the flexibility of returning null field values, so the new project objects are defined incorrectly.

Also, the logic for fast failing config was explicitly changed from (A && B && C) to (A || (B && C)), which means that it almost always fails, because the golden path is (A == false, B == true and C == true).

**Comment by NickGerleman** [comment]
Thank you for taking a look at this. In the future I will give some more time on the PR, since you hadn't left comments yet (I mentioned you in the PR on the condition, but went ahead and merged after a day). Do we have any issues tracking adding test coverage for autolinking/config?
