### ISSUE TITLE
CI loop instability:  WinUI3 builds out of heap space

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#5779]
The CI loop is currently unstable due to the WinUI3 projects running out of heap space.
For example, see:
https://github.com/microsoft/react-native-windows/pull/5776/checks?check_run_id=1000900335

**Comment by kmelmon** [comment]
Danny says:

Several options:
a) Remove the /MP on the compile and link to go to singel threaded build
b) Reduce the nr of WinRT dependencies (most of the time I see it fail on the WInRT generated files)
c) Better VM's the DevOps VMSS has not been stable enough, I keep trying every week running into new issues... Now admin and UI are not supported, it is either one or the other...
 
a) is the only easy quick one but it will make the builds slower... Perhaps we can only do it for the winui3 one which seems to be the worst.

**Comment by kmelmon** [comment]
Nick says:

[11:34 AM] Nick Gerleman
There was some discussion before about what it would look like to do builds without a PCH. The tricky part is that a lot of our source makes assumptions that headers are implicitly included by the PCH. I think a good first step would be Danny's suggestion of trying to reduce parallelism, but we have to do something here.

**Comment by asklar** [comment]
One of the problems that's breaking CI is PDB API call failed.
The PDB API call problem is a 16.7 race condition bug that I had filed with VS, it is not related to out of memory/PCH.
I'm also trying to see if disabling mp for winui3 will alleviate the breaks: https://github.com/microsoft/react-native-windows/pull/5784
