### ISSUE TITLE
CI loop instability: experimental nuget / npm

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#5785]
the experimental nuget init tasks sometimes fail but succeed on a rerun, owing to npm/verdaccio failures
```
npm ERR! code E404
npm ERR! 404 Not Found - GET http://localhost:***@types%2fyargs - no such package available
npm ERR! 404 
npm ERR! 404  '@types/yargs@^15.0.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of '@jest/types'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\npm\cache\_logs\2020-08-19T22_33_26_085Z-debug.log
Instalace [ 'react-native@latest' ] selhala s kódem 1
```

**Comment by asklar** [comment]
@NickGerleman will this be addressed by your recent change / do you know what we can do to make this more reliable?

**Comment by NickGerleman** [comment]
My recent change shifted the majority of package downloads off of Verdaccio (maybe like 75%?). Empirically I haven't seen issues since the change on any of my PRs. Going to bias to close this, and we can reopen if we see the issue come back.
