### ISSUE TITLE
Run yarn windows failed when path contains whitespaces

### ISSUE THREAD

**Issue by dgomezc** [microsoft/react-native-windows#5805]
## Environment
1. `npx react-native --version`: 4.12.0
2. `npx react-native run-windows --info`:
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 8.20 GB / 15.81 GB
  Binaries:
    Node: 12.9.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 16.11.0 => 16.11.0
    react-native: ^0.62.0-0 => 0.62.2
    react-native-windows: ^0.62.0-0 => 0.62.5
  Installed UWP SDKs:
    10.0.17763.0
    10.0.18362.0
3. `reg query "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock"`
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock
    AllowDevelopmentWithoutDevLicense    REG_DWORD    0x1
    AllowAllTrustedApps    REG_DWORD    0x1

What SDK version are you building for? 10.0.15063
- Target Platform Version(s):Desktop
- Target Device(s):Visual Studio 2019
- Visual Studio Version:Debug
- Build Configuration:

## Steps To Reproduce

1.Run script on elevated power shell 'https://raw.githubusercontent.com/microsoft/react-native-windows/master/vnext/Scripts/rnw-dependencies.ps1'
2. Run `npx react-native init <projectName> --template react-native@^0.62.2`
3. cd projectName
4. Run `npx react-native-windows-init --overwrite`
5. Run `yarn install`
6. Run `yarn windows`

## Expected Results
Show RNW app correctly.

## Snack, code example, screenshot, or link to a repository:
Error to build RNW app on run  `yarn windows`:
![con-todo-instalado-falla-yarn-windows](https://user-images.githubusercontent.com/12777039/90872098-6b21c500-e39c-11ea-824a-01193b3abee1.jpg)

**Comment by asklar** [comment]
@dgomezc It looks like react-native prevents creating a project under a directory with a space, even before react-native-windows is involved:
![image](https://user-images.githubusercontent.com/22989529/93842079-7f323e00-fc4a-11ea-9ce0-a6a9156d9c54.png)

So this is really a problem only when cloning or downloading an existing project onto a folder with a space in it

**Comment by asklar** [comment]
I verified that: created an app, added react native windows, then moved it to a folder with a space in it. After that, running `npx react-native run-windows` works fine.
