### ISSUE TITLE
Question: Is there any way to draw 2D stuff?

### ISSUE THREAD

**Issue by peterholak** [microsoft/react-native-windows#5814]
I see that react-native-svg is not supported yet. Let's say I want to draw something like an analog clock, is there any way to achieve this without a custom native module?

**Comment by asklar** [comment]
@peterholak Not without a native module, but you could write a native module that wraps a Win2D canvas which would allow you to draw into it from javascript.

**Comment by peterholak** [comment]
Ok, thanks for the info.
