### ISSUE TITLE
App disappear when you try to move it to a different screen.

### ISSUE THREAD

**Issue by prupipho** [microsoft/react-native-windows#5819]
## Environment

1. `npx react-native --version`: **4.10.1**
2. `npx react-native run-windows --info`: 
  ```
System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i5-2435M CPU @ 2.40GHz
    Memory: 1.80 GB / 7.91 GB
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 16.11.0 => 16.11.0
    react-native: ^0.62.0-0 => 0.62.2
    react-native-windows: ^0.62.0-0 => 0.62.4
  Installed UWP SDKs:
    10.0.18362.0
```

3. `reg query "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock"`
```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock
    AllowDevelopmentWithoutDevLicense    REG_DWORD    0x1
```

What SDK version are you building for? **10.0.15063**
- Target Platform Version(s):  **Desktop**
- Target Device(s): **Visual Studio 2019**
- Visual Studio Version: **Debug**

## Steps To Reproduce

1. Clone Calculator from repo rnw-react-native-windows-samples
2. Run on elevated power shell: `cd ReactNativeWindows/react-native-windows-samples/samples/Calculator`
3. `yarn install`
4. `yarn windows` 
5. While using the app I try to move it to a different screen

## Expected Results
App moves correctly to new position in the second screen 

## Snack, code example, screenshot, or link to a repository:
When working with more than one monitor the App disappear/close when you try to move it to a different screen. Holding the application from the top bar of the app (red arrow on the image below).

![image](https://user-images.githubusercontent.com/1333036/91029042-91469f80-e5fe-11ea-9715-e26976f0bc91.png)

**Comment by asklar** [comment]
@prupipho thanks for filing this! We think the issue might be that the app crashes instead of disappearing. Would it be possible for you to capture a crash dump? To do that, launch the app from Visual Studio (F5), reproduce the problem, and when it breaks into the debugger, select Save Dump under the Debug menu and share a link to the resulting `.dmp` file.
![image](https://user-images.githubusercontent.com/22989529/91084093-4b8ad680-e600-11ea-811a-87683450fe21.png)

**Comment by prupipho** [comment]
Thanks for having a look. See if this is the file you need: https://1drv.ms/u/s!AlHAeLUrqoyIgpIYYPGdU5-pdASszA?e=D9pzHx 

It took a lot of time to build and run the app the first time!

**Comment by asklar** [comment]
thanks @prupipho . Could you also provide the file `Microsoft.ReactNative.pdb` from the x64 build?
Also, do you remember if the metro bundler was running at the time you got the error in red above?

**Comment by prupipho** [comment]
I don´t think the metro bundler was running at that moment no.
Here you can find the .pbd file https://1drv.ms/u/s!AlHAeLUrqoyIgpIdX5bXroEIUN0cTg?e=Qa29Zl 
thanks @asklar 

This is another [dump file](https://1drv.ms/u/s!AlHAeLUrqoyIgpIe6uU_wDQ6hKWciA?e=aQEYZa) with the metro bundler running properly and the Calculator app properly displayed, in case it makes any difference. The pbd was unmodified and remain the same as the one above.

Kind regards

**Comment by asklar** [comment]
Awesome, I was able to use the symbols with the dump, it looks like the code is crashing in ``DeviceInfo::update()` when we detect a change in screen size or similar, which is consistent with the "move to a different monitor" scenario you described. We actually refactored/rewrote the crashing code back in May, see #4991 and you shouldn't hit this once we get the sample updated to use the latest version of RNW :)

**Comment by prupipho** [comment]
Great ! I´ve updated the version locally and works smoothly ! Thanks !
