### ISSUE TITLE
Implement event.stopPropagation() when keyboarding declarative properties are set

### ISSUE THREAD

**Issue by harinikmsft** [microsoft/react-native-windows#5822]
To ensure that the JS side matches the native side when declarative properties for handling specific keyboard keys are set, it would be good to implement `preventDefault()` on the JS side similar to how we marked handled() in the native side. 

See [comment thread](https://github.com/microsoft/react-native-windows/pull/5590/files#r461946783) for details.

**Comment by rectified95** [comment]
Additional detail from an offline discussion:
> The bug is tracking adding some logic to the JS that says when a component gets the keydown event, it should call preventDefault if the component marked keyDownEvents for that key.  And it shouldn't call it if the component didn't mark keyDownEvents.  That way, the native and JS event propegation are in sync with each other.  And in the future we can potentially make the key events happen synchronously and it wont be a behavior change.

Also, this requires calling `event.stopPropagation()`, rathern than `preventDefault()`
