### ISSUE TITLE
Pull out Slider code from RNW and use community impl.

### ISSUE THREAD

**Issue by rectified95** [microsoft/react-native-windows#5824]
Now that the community module Slider has got Windows support, we should use that in our code.
Remove stub Slider view manager from RNW.
Re-enable the Slider example in RNTester.

**Comment by acoates-ms** [comment]
core RNW shouldn't use the community module.
We should just leave the core as is until its removed from core.

**Comment by rectified95** [comment]
Sure, I just created this issue to track the work to be done. Do you think it's better to close it until it's removed upstream?

**Comment by acoates-ms** [comment]
The slider code should merge away when it gets removed from upstream.  Hopefully, there isn't really any work to do here.  I think we can just close this.
