### ISSUE TITLE
Can't use C# module from C++ on 0.63

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#5825]
@qmatteoq ran into this when trying to update the GeolocationSample to 0.63

> I have another question  Is there new guidance to follow to reference a native module built in C#? I've noticed that the Microsoft.ReactNative.SharedManaged project is gone and now there's a Microsoft.ReactNative.Managed project, which isn't a shared project but a regular C# one. I've added it in my React Native solution and I've referenced it from my native module. Everything works when it comes to the native module (I can build it just fine), but the main project which references the module doesn't build anymore due to this error:

```

C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(1361,5): error MSB3816: Loading assembly "C:\GeolocationSample\node_modules\react-native-windows\target\x86\Debug\Microsoft.ReactNative.Managed\Microsoft.ReactNative.Managed\Microsoft.ReactNative.Managed.dll" failed. System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(1361,5): error MSB3816: File name: 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```

> here is the original version pre 0.63: https://github.com/microsoft/Windows-AppConsult-Samples-UWP/tree/main/GeolocationSample

> 0.63 attempt: https://microsofteur-my.sharepoint.com/:u:/g/personal/mpagani_microsoft_com/EfR3tQmG2Z1NsEV71ZRp8oEBuGJtwSA20q_j8V7GaJwNgw?e=gs2Idd

**Comment by NickGerleman** [comment]
Marking for 0.63 since we can scoop this into discussion. @asklar would you be able to add details? Relevant is whether this is a new regression.

**Comment by asklar** [comment]
Added comments from the Teams thread. @jonthysell mentioned that this is because the cpp project doesn't include references to the microsoft.reactnative.managed.dll which I would expect we wouldn't by default (since you shouldn't need it if you only have C++ native modules), but we should have a documented way for you to consume C# modules from C++)

**Comment by jonthysell** [comment]
I've figured it out, the reason SampleAppCPP works loading SampleLibraryCS - it imports ~40 .Net/UWP/.NetNative targets to make the scenario work, and none of that was added to the CLI template for other apps.

Working on a fix.
