### ISSUE TITLE
Support ARM64 on Windows Desktop

### ISSUE THREAD

**Issue by JunielKatarn** [microsoft/react-native-windows#5828]
## Summary
Produce native ARM64 binaries for Windows Desktop (Windows 8.1 and later).

Work will be tracked on this fork branch:
https://github.com/jurocha-ms/react-native-windows/tree/desktop-arm64

## Motivation

Partner project (MS Office) now requires ARM64 builds of React Native. This requires porting `react-native-win32.dll`.

## Dependencies

To deliver this new platform build, we need to either port or stub the following external libraries:

- [x] [ReactWindows.OpenSSL.StdCall.Static](https://dev.azure.com/ms/react-native/_packaging?_a=package&feed=react-native-public&package=ReactWindows.OpenSSL.StdCall.Static&protocolType=NuGet&version=1.0.2-p.5)
  Available in version [`1.0.2-p.5`](https://dev.azure.com/ms/react-native/_packaging?_a=package&feed=react-native-public&package=ReactWindows.OpenSSL.StdCall.Static&protocolType=NuGet&version=1.0.2-p.5).
- [ ] [ReactNative.V8Jsi.Windows](https://www.nuget.org/packages/ReactNative.V8Jsi.Windows)
  Currently non-critical because we default to ChakraCore. Follow up with @tudorms.
- [ ] [~~Microsoft.googletest.v140.windesktop.msvcstl.static.rt-dyn~~](https://www.nuget.org/packages/Microsoft.googletest.v140.windesktop.msvcstl.static.rt-dyn)
  Optional. Skipping. Only needed for test projects. Some of those are only supported on `x64` (not even `x86`).
- [ ] [ChakraCore.Debugger](https://www.nuget.org/packages/ChakraCore.Debugger)
  Awaiting PR https://github.com/microsoft/ChakraCore-Debugger/pull/92
  - [x] [Microsoft.ChakraCore.vc140](https://www.nuget.org/packages/Microsoft.ChakraCore.vc140)
    Package [ReactWindows.ChakraCore.ARM64](https://dev.azure.com/ms/react-native/_packaging?_a=package&feed=react-native-public&package=ReactWindows.ChakraCore.ARM64&protocolType=NuGet&version=1.11.20) released.

**Comment by Poopooracoocoo** [comment]
Why do you guys use ChakraCore? And do you guys know if Facebook will be using RNW for Instagram? That'd convince a lot of people. And how come Skype moved away from RNW? What does that say to anyone thinking of using RNW?

**Comment by asklar** [comment]
@Poopooracoocoo Skype never used RNW, they had a thing called ReactXP: https://microsoft.github.io/reactxp/blog/2017/04/27/building-skype-on-reactxp.html

My personal opinion (not Microsoft-official :-) ) is that the cost of updating and maintaining ReactXP to keep up with react native became too much. At the end of the day they are an app/service team, not an app framework team.

**Comment by Poopooracoocoo** [comment]
@asklar thank you for the response. <3 I didn't  want a microsoft official response anyway :p 
let's hope they switch to RNW and that Facebook notices and uses your project. :)

I thought that Microsoft wasn't using ChakraCore: https://github.com/microsoft/ChakraCore/issues/6384

**Comment by JunielKatarn** [comment]
Reopening, this issue was not meant to be fully closed by #5864.

We need to set the V8 (and Hermes?) story straight so we have no pending relevant dependencies.

**Comment by NickGerleman** [comment]
I believe this was completed. Please reopen if this wasn't.

**Comment by JunielKatarn** [comment]
> I believe this was completed. Please reopen if this wasn't.

See the Dependencies section in the description.

Those correspond to other projects. I leave it to your criteria if those should be considered into keeping a RNW issue open or not.
