### ISSUE TITLE
How to build Windows app? 

### ISSUE THREAD

**Issue by lexoveri** [microsoft/react-native-windows#5855]
Can I build app like for android with command line?

**Comment by harinikmsft** [comment]
Hello @lexoveri - Yes, indeed you can. Please take a look at our website and documentation to get started on Windows: [Getting Started Guide](https://microsoft.github.io/react-native-windows/docs/getting-started)

**Comment by keenghost** [comment]
> Hello @lexoveri - Yes, indeed you can. Please take a look at our website and documentation to get started on Windows: [Getting Started Guide](https://microsoft.github.io/react-native-windows/docs/getting-started)

Hi @harinikmsft , I built the `Windows/{ProjectName}.sln` through visual studio in realease x64 mode, then i try to run `Windows/x64/Release/{ProjectName}.exe`, but got `VCRUNTIME140_1_APP.dll` error. but the entry from startmenu works fine.

Actually what i want is just getting all the assembly files that will finally placed in `C:\Program Files` by react native,  i will do the rest of packing & publishing jobs manually.

I'm a pure frontend-web programmer, all i wish is that i can just use a command like `npm run build` to get final app assembly folder.

Are these posible? Thanks!

**Comment by chrisglein** [comment]
You can't just run the exe, you need to side load it using the Visual Studio tools, or publish it to the store. Using the `run-windows` CLI command should do this for you, and after that it'll be installed. But that's not a deployment option for putting elsewhere - you'll eventually need to put together an installer or publish to the store.
