### ISSUE TITLE
Running C# module from C++ app fails 0.62

### ISSUE THREAD

**Issue by jaimecbernardo** [microsoft/react-native-windows#5858]
A C++ `react-native-windows` 0,62 application causes a runtime error when loading a C# native module.

## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`: 4.12.0
2. `npx react-native run-windows --info`:
```
  System:
    OS: Windows 10 10.0.19041
    CPU: (6) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 8.85 GB / 16.00 GB
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 16.11.0 => 16.11.0
    react-native: ^0.62.0-0 => 0.62.2
    react-native-windows: ^0.62.0-0 => 0.62.6
  Installed UWP SDKs:
    10.0.17763.0
    10.0.18362.0
```

3. `reg query "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock"`
```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock
    AllowDevelopmentWithoutDevLicense    REG_DWORD    0x1
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create a C++ `react-native-windows` application with the template:
```
npx react-native init WindowsRNSample --template react-native@^0.62.2
cd WindowsRNSample
npx react-native-windows-init --overwrite
```
2. Add a C# native module (in this case used the [PR that's open to bring `react-native-device-info` to `0.62` support](https://github.com/react-native-community/react-native-device-info/pull/1059):
```
yarn add react-native-community/react-native-device-info#1059/head
```

3. Run `npx react-native run-windows` so that there's the background web-server that serves the app running and close the application.

4. Do the manual linking of the native module:
- Open `windows\WindowsRNSample.sln` in Visual Studio.
- Right-click the solution and `Add` > `Existing Project` and select `node_modules/react-native-device-info/windows/RNDeviceInfo/RNDeviceInfo.csproj`
- Right-click the WindowsRNSample project and `Add` > `Reference` and add `Projects`/`RNDeviceInfo`.
- In `pch.h` add `#include <winrt/RNDeviceInfo.h>`
- In `app.cpp` add `PackageProviders().Append(winrt::RNDeviceInfo::ReactPackageProvider());` before `InitializeComponent()`.

5. Try to run the WindowsRNSample project on  `Debug` `x86`.

It'll throw a `hresult_error` exception when trying to run `PackageProviders().Append(winrt::RNDeviceInfo::ReactPackageProvider());` and crashes the application. The exception has the `0x80131040` value (`The located assembly's manifest definition does not match the assembly reference.`)

## Expected Results

I expect the app to start successfully and show the default Window.

## Current workaround

Setting the `Target`'s `Min version` of the `RNDeviceInfo` C# project  from `Windows 10 Fall Creators Update (10.0; Build 16299)` to `Windows 10 Creators Update (10.0; Build 15063)` and rebuilding `RNDeviceInfo` solves the issue and allows the application to start successfully.

## Explanation

From Raymond Chen's https://devblogs.microsoft.com/oldnewthing/20200615-00/?p=103868

> Here’s what’s going on: Visual Studio checks the Min version of the C# project. This version controls which version of .NET Core and .NET Native are used. In mixed-language scenarios, such as we have here with C++/WinRT and C#, Visual Studio defaults to .NET Core 1.1 and .NET Native 1.4. However, if the minimum version is set to Windows 10 version 1709 (Build 16299) or higher, then Visual Studio copies the .NET Core 2 libraries into the application output folder and tries to run them against .NET Core 1.1.
That is the version mismatch that’s being reported. The mismatch is not with the version of your C# component. The mismatch is with the version of .NET Core.
The workaround is to set your C# component’s minimum version to Windows 10 version 1703 (Build 15063) or lower: From your C# project, go to Properties, Library, and under Targeting, set the Min version to Windows 10 Creators Update (10.0; Build 15063) or lower.

This looks like it's a broader issue, since the instructions to create a native module for `react-native-windows` indicate that the module should be created with Minimum version set to `Windows 10 Fall Creators Update (10.0; Build 16299)`, so every C# module created for version 0.62 of React Native Windows will potentially hit this issue when being included in a C++ application project.

Ref: https://microsoft.github.io/react-native-windows/docs/native-modules-setup#creating-the-visual-studio-project--solution

**Comment by stmoy** [comment]
CC: @jonthysell @vmoroz  - is this known?

**Comment by asklar** [comment]
This is a known issue that we need .net to address and document. In the meantime we should update our documentation.
See: https://github.com/microsoft/dotnet/issues/1196
