### ISSUE TITLE
Support react-native-side-menu

### ISSUE THREAD

**Issue by Adam-Oudaimah-SCASE** [microsoft/react-native-windows#5877]
# Support `react-native-side-menu` on RNW

## Basic Info
- Module Repo URL: [https://github.com/react-native-community/react-native-side-menu](https://github.com/react-native-community/react-native-side-menu)
- Target version: V1.0.0

## Which app/customer is requesting this module?
I believe this module has to be supported not only for me but for all the users of RNW because I think it is very useful.

## In what scenarios will this module be used?
The side menu is like the navigation bar in web applications.

**Comment by chrisglein** [comment]
Thanks for filing the community module request!
I haven't used side-menu before, but just so you know [react-navigation](https://github.com/microsoft/react-native-windows/issues/3884) has a 'drawer' feature that at least superficially seems similar, and that module does support Windows today. So if you're looking to unblock yourself sooner, that may be viable.

**Comment by Adam-Oudaimah-SCASE** [comment]
Thank you very much.
I've seen the 'drawer' component already.
