### ISSUE TITLE
react-native-windows-init hangs when running on top of existing project without `--overwrite`

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#5879]
If you don't specify `--overwrite`, after you answer yes/no to overwrite the first file, the second file is mentioned but the prompt never appears as the CLI just hangs. You have to Control-C to exit.

## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`: 4.12.0
2. `npx react-native run-windows --info`:

  System:
    OS: Windows 10 10.0.20201
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 5.20 GB / 15.84 GB
  Binaries:
    Node: 12.9.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
    react-native-windows: ^0.63.0-0 => 0.63.0
  Installed UWP SDKs:
    10.0.18362.0

3. `reg query "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock"`

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock
    AllowDevelopmentWithoutDevLicense    REG_DWORD    0x1
    AllowAllTrustedApps    REG_DWORD    0x1

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. `yarn upgrade react-native-windows`
2. `npx react-native-windows-init`
3. Select yes or no when prompted to overwrite the solution file

## Expected Results
Prompted to overwrite the next (project) file

## Snack, code example, screenshot, or link to a repository:

https://github.com/jonthysell/react-native-windows-samples/tree/samples63

**Comment by NickGerleman** [comment]
There was some work I did for 0.63 to allow async functions in generator (and to remove the hacked up prompt we had). Tested prompting logic worked correctly in the happy path of new project asking about Metro config, but wondering if this could be related.  https://github.com/microsoft/react-native-windows/pull/5417

**Comment by NickGerleman** [comment]
Doing some fixup for an issue in the same area and am no longer able to repo this. Thinking it might have been fixed with the floating promises cleanup or other refactoring that has happened. Going to close this, but please reopen if you are still able to repro.
