### ISSUE TITLE
Update changelogs to include upstream changes

### ISSUE THREAD

**Issue by harinikmsft** [microsoft/react-native-windows#5881]
Filing this to track the point raised during review of versions doc. We should update our generated changelogs for Windows to include upstream changes for completeness.

Might want to consider looking at https://github.com/facebook/react-native/releases/tag/v0.63.0 

One other idea is to update the stable version release notes to point to a bigger generated changelog with a more curated commit history as well.

**Comment by chrisglein** [comment]
Do we capture highlights? Do we link to the whole release notes? What would be the most helpful to include without duplicating and/or being overwhelming?

**Comment by NickGerleman** [comment]
Created an issue for implementation with #7429
