### ISSUE TITLE
Image onLoad Event Structure Using React Native 0.64 Type in RNW 0.63

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#5896]
https://github.com/microsoft/react-native-windows/issues/5278 previously tracked an API change that happened to Image load with the intent of updating our own code. We changed our own native interface to conform prematurely in https://github.com/microsoft/react-native-windows/pull/5028 which made it into RNW 0.63.

The effect is that apps trying to read URL from an image load event get an undocumented breaking change a version early, that conflicts with RN typings. The existing structure did differ between iOS and Android, and the problem will resolve itself once we release 0.64.

**Comment by chrisglein** [comment]
Documentation doesn't cover the details of what's passed here: https://reactnative.dev/docs/image#onload
Essentially this was a 0.63 breaking change, which we could go revert... but none of this is documented and we have the behavior we want for 0.64 so... leave it as is?
