### ISSUE TITLE
Build errors on fresh project

### ISSUE THREAD

**Issue by EricCornelson** [microsoft/react-native-windows#5900]
Hi All, 

I'm seeing build errors on a brand new freshly created project (from the steps at https://microsoft.github.io/react-native-windows/docs/getting-started).

I see these errors when trying to build in Visual Studio (Version 16.8.0 Preview 3.0 [30426.262.main]):
![image](https://user-images.githubusercontent.com/38218905/91891698-57048000-ec46-11ea-8bf9-f8e658c1f6bb.png)

I see these errors when trying to build from command line using `npx react-native run-windows --logging`
![image](https://user-images.githubusercontent.com/38218905/91891812-81563d80-ec46-11ea-8c55-0ba378a09913.png)

I've run the rnw-deps.ps1 script and I seem to have all the correct dependencies
![image](https://user-images.githubusercontent.com/38218905/91892332-515b6a00-ec47-11ea-80ba-c763bdb51d60.png)

Am I missing something?

## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`:
![image](https://user-images.githubusercontent.com/38218905/91891078-3f78c780-ec45-11ea-9d01-0fffe809f220.png)
2. `npx react-native run-windows --info`:
![image](https://user-images.githubusercontent.com/38218905/91891141-56b7b500-ec45-11ea-9bba-c4e6ecf5db27.png)
3. `reg query "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock"`
![image](https://user-images.githubusercontent.com/38218905/91891213-7949ce00-ec45-11ea-979f-f855dc64fb87.png)

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create a fresh project using the steps at https://microsoft.github.io/react-native-windows/docs/getting-started
2. Try to build the project

## Expected Results
The project builds successfully

**Comment by asklar** [comment]
@EricCornelson This is because we use `VSWhere` to locate msbuild in a VS 16.x installation but we don't include pre-release/preview bits. We've run into issues when VS upgrades that break RNW builds in real ways and require fixes to RNW to work around them (e.g. generating edit and continue symbols got broken, or UWP packaging was broken in 16.5-16.6).

**Comment by chrisglein** [comment]
We currently intentionally don't work with pre-release bits. Although maybe we can give a clear early error message while that is the case. We could have an opt-in option to support this.

The `__builtin_clz` failure may indicate a problem that we'd want to know about early. We should have someone on our side look at this latest version.

Action on this looks like:
- Add an option to support prerelease bits
- Add a warning if you're not using prerelease bits
- Look at what's going wrong with the new bits

**Comment by asklar** [comment]
I've started a thread for the __builtin_clz issue, this seems like a breaking change we will hit in 16.8. Either we need to take an updated folly that doesn't use this intrinsic, or we need a way to get the intrinsic's behavior into 16.8.
Using this bug to track the preview issue with the CLI, and filing a new bug for the intrinsic.

**Comment by asklar** [comment]
__builtin_clz issue is #5987
