### ISSUE TITLE
"Latest Release" in GitHub Isn't Always the Latest Release

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#5903]
We just created a release for 0.63.0, but GitHub shows 0.62.7 as the latest 
![8C13082F-329B-4F18-A933-8EA15F80361A](https://user-images.githubusercontent.com/835219/91909120-7c52b780-ec61-11ea-9ea3-bedfd8a2f647.jpeg)

Some googling suggests the label might be added to the release with most recent chronological tag that's not prerelease, which often times won't be what we want.

We can try to maybe avoid the issue with how we schedule jobs, but we'd still see issues if we needed to backport something to an older branch but not update the the newest. That category would be rare, but would require disabling releases for older stable versions to solve.

**Comment by chrisglein** [comment]
We probably have to do unnatural things in order to get the right thing to show up here. Maybe we can influence github's policy for this view instead? It sounds like there are community complaints about this as well. Can you link to those and we can add our voice to that?
