### ISSUE TITLE
Bundling is broken in Release for apps not at the root of a project

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#5912]
We define a `BundleConfigFile` (to empty) and never use it

https://github.com/microsoft/react-native-windows/blob/c4025b80c454a06eb9d86958cab7487c4981aae9/vnext/PropertySheets/Bundle.props#L47

I am hitting an issue where running metro (in debug) picks up the metro.config.js by default as expected, but `npx react-native bundle` doesn't pick it up. It does only if I pass `--config metro.config.js`

**Comment by asklar** [comment]
Metro and `react-native bundle` will use metro.config.js if they can find it *at the root of the project*. 
In the case of the RNC clipboard repo, metro.config.js lives in the `example` folder, so instead metro sees there is no config file and uses an empty one. Filed bug https://github.com/facebook/metro/issues/588 to fix the "only at the root" problem.

There are a couple of issues then:

1) We should use `BundleConfigFile` if the project specifies it (and pass it to `react-native bundle` via the `--config` option)
2) Metro should arguably spew some warning in verbose mode when it doesn't find a config file and instead ends up using the fake `.stub.js`. Filed bug https://github.com/facebook/metro/issues/589. Relevant code in Metro:

```js
function _resolveConfig() {
  _resolveConfig = _asyncToGenerator(function*(path, cwd) {
    if (path) {
      return explorer.load(path);
    }

    const result = yield explorer.search(cwd);

    if (result == null) {
      // No config file found, return a default
      return {
        isEmpty: true,
        filepath: join(cwd || process.cwd(), "metro.config.stub.js"),
        config: {}
      };
    }

    return result;
  });
  return _resolveConfig.apply(this, arguments);
}
```

**Comment by chrisglein** [comment]
Workaround is to move the file to the root, but as Alex found in Clipboard the module may have built up around it not being this way and changing that can be breaking for their other platforms. Or the modules may be misconfigured and not know.

The solution here may be to change how we configure metro. Add functionality to the CLI to insert platform specific defaults without requiring people write a custom metro config for that.

**Comment by aschultz** [comment]
Ran into this today with a library project, since we have the library and test app sitting side-by-side rather than the app as the root. Thankfully, unlike `BundleConfigFile` the `BundlerExtraArgs` prop is actually applied to the bundler command, so I was able to pass in `--config <path>\metro.config.js`.

**Comment by asklar** [comment]
We should just consume the `BundleConfigFile` param, marking "good first task"
