### ISSUE TITLE
rnw-dependencies will fail to install VS in Codespaces

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#5913]
The Visual Studio Codespaces VM has the VS installer as well as vswhere, but no actual VS installed and no workloads (!!). So when determining whether the VS product needs to be installed, instead of checking for the presence of vswhere we should invoke vswhere to look for a product instead.

**Comment by chrisglein** [comment]
This would track work we need to do on our end to support the unattended / run in vscode environment that's required here.
