### ISSUE TITLE
无法打开证书TemporaryKey.pfx

### ISSUE THREAD

**Issue by k1195453766** [microsoft/react-native-windows#5930]
How should this problem be solved（thanks）：
![image](https://user-images.githubusercontent.com/45040711/92345695-f8834a00-f0fc-11ea-841e-7b9e2f565129.png)

**Comment by asklar** [comment]
Hi @k1195453766 we're going to need more info from you including repro steps, version numbers, and preferably what the rest of the error message says in English (from the bug title it seems like it is that the certificate cannot be found but it isn't clear what the rest of the message is or how you got there). Please include what steps you took to get there.

**Comment by k1195453766** [comment]
Thank you for your reply, this problem has just been solved, I reconfigured the certificate, it is OK

**Comment by w0955524096** [comment]
@k1195453766 How did you reconfigure the certificate file? I face the same error around temporarykey file with you.

**Comment by k1195453766** [comment]
> @k1195453766 How did you reconfigure the certificate file? I face the same error around temporarykey file with you.

1.Open project in Visual Studio
2.open Package.appxmanifest
![~Q4YPTIM7CGMH I34LO%FH8](https://user-images.githubusercontent.com/45040711/92446639-b0415600-f1e8-11ea-8449-e8a4db2b9f46.png)
![image](https://user-images.githubusercontent.com/45040711/92446734-d5ce5f80-f1e8-11ea-83e1-094a2b86f43d.png)

**Comment by k1195453766** [comment]
@w0955524096

**Comment by w0955524096** [comment]
> > @k1195453766 How did you reconfigure the certificate file? I face the same error around temporarykey file with you.
> 
> 1.Open project in Visual Studio
> 2.open Package.appxmanifest
> ![~Q4YPTIM7CGMH I34LO%FH8](https://user-images.githubusercontent.com/45040711/92446639-b0415600-f1e8-11ea-8449-e8a4db2b9f46.png)
> ![image](https://user-images.githubusercontent.com/45040711/92446734-d5ce5f80-f1e8-11ea-83e1-094a2b86f43d.png)

Thanks for the solutions. It does greatful help!
