### ISSUE TITLE
react-native-windows-init/generator-windows should add "windows" script

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#5931]
After running react-native-windows-init against a recent build with `--useDevMode`, we add dependencies to package.json, but don't add a `windows` script. We're instead left with:

```json
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
```

Our own packages add:

```json
    "windows": "react-native run-windows",
```

**Comment by NickGerleman** [comment]
We used to do this correctly. The logic is folded into dependency installation in generator, but we no longer try to install dependencies if they're already satisfied. I.e. this has been broken since 0.62.

The dependency setup between init + generator could use some attention + test coverage in general.

**Comment by sumitparakh** [comment]
Hi, is this issue still relevant? Can I pick it?
