### ISSUE TITLE
Playground is not loading 

### ISSUE THREAD

**Issue by manohargss** [microsoft/react-native-windows#5941]
I followed the steps to build react-native-windows but when I start loading playground I am getting issue as 
Error 80072eff downloading http://localhost:8081/Samples\rntester.bundle?platform=windows&dev=true&hot=false&inlineSourceMap=true

**Comment by manohargss** [comment]
1) 4.12.0
2) System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 15.37 GB / 31.86 GB
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
  Installed UWP SDKs:
    10.0.17134.0
    10.0.17763.0
    10.0.18362.0

**Comment by chrisglein** [comment]
@manohargss That environment issue still isn't showing what version of react-native or react-native-windows you're on. Did you happen to specify a version when you did your project init? Those commands should also provide the RN versions.

**Comment by manohargss** [comment]
@chrisglein  added the versions let me know if you need more information: 

react-native-cli: 2.0.1
react-native: 0.0.0-e75557b48
node - v12.18.3
npm - 6.14.6
yarn - 1.22.4

**Comment by asklar** [comment]
@manohargss please provide the version of react-native-windows too as well as what steps specifically you took to get into this state. Make sure that the bundler is running if you are launching the app from VS instead of using run-windows.

**Comment by manohargss** [comment]
react-native-windows@0.58.0-rc.2

**Comment by asklar** [comment]
Thanks. That's a very old version of RNW that has not been supported for a long time, please update to the latest (0.63.x). Thanks!

**Comment by manohargss** [comment]
I upgraded to the latest version but still I see the same issue with the playground.

**Comment by chrisglein** [comment]
@manohargss What commit are you synced to? We haven't been able to repro any problems here but there may be something more about your config that we're missing. Can't hurt to also provide your environment info dump after that 'upgrade' (sync to master).

**Comment by manohargss** [comment]
@chrisglein  how do I find out the commit version?

**Comment by chrisglein** [comment]
> @chrisglein how do I find out the commit version?

Using `git log` should do it

```
\repos\react-native-windows> git log
commit 0a7974d00bd9c9ee12bef57f2678d64fc335d061 (HEAD -> master, upstream/master, origin/master, origin/HEAD)
Author: dependabot-preview[bot] <27856297+dependabot-preview[bot]@users.noreply.github.com>
Date:   Tue Sep 15 16:30:37 2020 +0000

    Bump beachball from 1.35.5 to 1.36.0 (#5994)

commit 836197fbaa0d24e931f65b53efca186d693fdaf2
Author: dependabot-preview[bot] <27856297+dependabot-preview[bot]@users.noreply.github.com>
Date:   Tue Sep 15 16:06:55 2020 +0000

    Bump @react-native-community/cli from 4.12.0 to 4.13.0 (#5961)
```

**Comment by manohargss** [comment]
I was able to solve the issue. Thanks for your help. Only when I switched off another web app that is supposed to run only in port 8081. Is there a way to customize the running of react-native windows app to a different port.
This issue can be closed once the answer to the change port is given.

**Comment by acoates-ms** [comment]
You can use the SourceBundlePort property on ReactInstanceSettings to customize the port used.
https://microsoft.github.io/react-native-windows/docs/reactinstancesettings-api#sourcebundleport

**Comment by manohargss** [comment]
thanks but where should it be done in the app.js?

**Comment by chrisglein** [comment]
It can't be done from app.js (it needs to be set up well before then).

**Comment by manohargss** [comment]
@chrisglein what setup should I do ?

**Comment by chrisglein** [comment]
> @chrisglein what setup should I do ?

See the comment above: https://microsoft.github.io/react-native-windows/docs/reactinstancesettings-api#sourcebundleport
