### ISSUE TITLE
fatal error C1060: compiler is out of heap space

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#5949]
The ADO CI pipeline often has CL.exe running out of heap space.

`- Build failed with message D:\a\1\testcli\node_modules\react-native-windows\Microsoft.ReactNative\Views\VirtualTextViewManager.cpp(100,1): fatal error C1060: compiler is out of heap space [D:\a\1\testcli\node_modules\react-native-windows\Microsoft.ReactNative\Microsoft.ReactNative.vcxproj]. Check your build configuration.`

See full build log [here](https://dev.azure.com/ms/react-native-windows/_build/results?buildId=107864&view=logs&j=2368c293-a607-576b-f9cf-404335799b61&t=1a201d0f-5774-5d0e-663e-854e14ddef55&l=8601). Note that this happens for both WinUI 3 as well as regular (UWP XAML) jobs.

**Comment by asklar** [comment]
Possible solutions: 
1) get beefier VMs, the ADO ones have 7GB of RAM. Someone will need to fund this but PackageES could be an option if they all OSS. Keith was following the WinUI breadcumbs here.
2) revise what we include in PCHs so we don't run out of heap. Unclear _if_ we can get there.

**Comment by asklar** [comment]
this will likely be taken care of by using the hosted pool

**Comment by Venipa** [comment]
16gb available but still out of heap:
![image](https://user-images.githubusercontent.com/17952364/96620679-0cc78300-1308-11eb-9d0b-1fd6f599ca6d.png)

**Comment by chrisglein** [comment]
We're working on addressing this on a more fundamental level with binary distribution in 0.64 and other infrastructure.
In the meantime your workarounds are unfortunately to clear up some memory and try running again. Unfortunately the combination of tools we're relying on right now is demanding a lot of memory and we're working to address that or build in more mitigations.

**Comment by kingdevnl** [comment]
I even get this error on my PC.
I've got 32GB ram.... (Only ~10 is in use)


 compiler is out of heap space (compiling source file Modules\Animated\EventAnimationDriver.cpp) [D:\dev\ts\projectName\node_modules\react-native-windows\Microsoft.ReactNative\Microsoft.ReactNative.vcxproj]. Check your build configuration.

**Comment by shirakaba** [comment]
On my MacBook, increasing the RAM allocated to my ARM Windows VM from the default 8 GB RAM to 32 GB, and setting `--single-proc`, got me past the error.

- 8 GB: fail
- 8 GB with `--single-proc`: fail
- 8 GB with `--single-proc` and hard-coding `/Zm200` to increase the compiler's heap allocation: fail
- 12 GB with `--single-proc`: fail
- 16 GB with `--single-proc`: fail
- 32 GB: not tested
- 32 GB with `--single-proc`: pass ✅

Would love if the build could be less RAM-hungry!
