### ISSUE TITLE
react-native-windows-init fails if target package.json doesn't have dependencies

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#5956]
If the target project's package.json doesn't have `dependencies` set, then `react-native-windows-init` fails because the way we "install" RNW is by adding a `react-native-windows` key to the dependencies object, then running `yarn` or `npm install`.

This happens to work currently because pretty much all react-native apps have, at least, react and react-native as dependencies.

However, in extending `react-native-windows-init` for native modules, where typically they are peer/dev dependencies, this fails.

**Comment by NickGerleman** [comment]
It seems like a workaround for this was added in #5921
