### ISSUE TITLE
Animated.Value is not preserved if component is unmounted during animation

### ISSUE THREAD

**Issue by rectified95** [microsoft/react-native-windows#5958]
While integrating https://github.com/microsoft/react-native-windows/pull/5957 I added an implementation of animated value caching callback to try and match https://github.com/facebook/react-native/commit/d92284216f4b079079f7ee479f35c94c900bc701
It's partial in that it only returns correct values at the beginning of or after an animation ends.
Still, we are not able inspect XAML properties while they are being animated, which is what the RN API allows.

**Comment by chrisglein** [comment]
This seems related to other issues we have with native animation driver in that XAML composition doesn't make it easy to get the value for an animation in progress. Will likely be very difficult to implement without changes in XAML/composition.

**Comment by chrisglein** [comment]
I'm trying to remember why we had this flagged for 0.64. I'm guessing based on it being a fresh integration of a new API/behavior change? But without other pending needs we have around animation events (e.g. #2941) is this ready to act on? Also curious about interaction with #3460. @rectified95 do you think this is possible to act on in the near term or does it need that other stuff?
