### ISSUE TITLE
Modifying code from RNTester while in Playground doesn't take effect

### ISSUE THREAD

**Issue by lyahdav** [microsoft/react-native-windows#5968]
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`: 4.12.0
2. `npx react-native run-windows --info`:
```
  System:
    OS: Windows 10 10.0.19041
    CPU: (40) x64 Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz
    Memory: 156.26 GB / 190.60 GB
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.0-20190429.1820 - C:\open\fbsource\xplat\third-party\yarn\yarn.BAT
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
    Watchman: 20200724.030019 - C:\tools\watchman\watchman.EXE
  Installed UWP SDKs:
    10.0.18362.0
```
3. `reg query "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock"`
```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock
    AllowDevelopmentWithoutDevLicense    REG_DWORD    0x1
    AllowAllTrustedApps    REG_DWORD    0x1
```

## Steps To Reproduce
1. Clone this repo (I'm on commit 8922cf2873e3c5ae8dd2fa88c506d43df92dc908)
1. Make changes to https://github.com/microsoft/react-native-windows/blob/master/vnext/src/RNTester/js/examples-win/Flyout/FlyoutExample.windows.tsx
1. Run Playground app per https://github.com/microsoft/react-native-windows/blob/master/docs/building-rnw.md#automatic
1. Select Samples\rntester for JavaScript File
1. Select App Name: RNTesterApp
1. Uncheck Web Debugger
1. Click Load
1. Click Flyout
1. Observe changes don't take effect, it's running the code as if I made no changes

## Expected Results
I'd expect to see my changes

**Comment by acoates-ms** [comment]
Yup super lame.  But you'd have to run `yarn build` in the vnext package? or from the root of the repo to pickup that change.

We do a merge of our files and the original RN files as part of build, and since metro doesn't like symlinks we can't just symlink the source to the target.

**Comment by acoates-ms** [comment]
For quick playing with code, you can edit the version in vnext/RNTester/js/examples-win/Flyout/FlyoutExample.windows.js.  But to checkin youd have to change the one in src.

**Comment by NickGerleman** [comment]
I think we might be able to get around this with a bit of trickery. Instead of doing a build and copying, could have a special metro config locally that had a custom resolver to look in both unmerged folders?

I.e. if we're trying to load RNTester/.../FooExample, the custom resolver could test for a file existing in our "src" one first and load the Flow/Typescript directly.

We wouldn't want to ship this, but it could be nice for local developer experience.

**Comment by chrisglein** [comment]
Could be possible to trick Metro into looking in two places to avoid the need to build. As is, within our own RNW app you don't get the fast reload experience. You can edit the copies, but of course then you're not editing the source files.

Currently a pain point for our internal development. @lyahdav how important is this to you for right now?
Assigning to @acoates-ms to think through options.

**Comment by lyahdav** [comment]
It’s not very important. I didn’t realize I can modify the other version of the same file. Thanks.
