### ISSUE TITLE
Investigate Adding react-native-windows Support for Detox

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#5972]
[Detox](https://github.com/wix/Detox) is a commonly used end-to-end testing framework for react-native. It makes some design decisions different from Appium to try to reduce fragility.

React Native Core has started adding Detox tests against RNTester. We cannot leverage or contribute to these currently.

**Comment by chrisglein** [comment]
We had a large investigation into this last year and that's captured [here](https://github.com/microsoft/react-native-windows/blob/master/docs/e2e-testing.md). Can you point to the recent investment in Detox so we know what sort of app collateral we'd be missing out on (I'm assuming that'd be the motivation - sharing tests)?

**Comment by NickGerleman** [comment]
Sharing tests is a big motivation. See [here](https://github.com/facebook/react-native/tree/master/packages/rn-tester/e2e) for the Detox tests core has added to RNTester. There was conversation pretty early in the year about the intent to add these, but I'm not sure how far it will go. The goal is more or less the same as the E2ETest work we started, so it would be great if we could avoid divergent work.

The other motivation is for customers who already have Detox tests.

**Comment by chrisglein** [comment]
@kmelmon We've talked maybe having more luck moving Appium forward rather than funding Detox support. We have CanHua's test writeup, and we have your test plan writeup, and then some conversations about where RN core's test infrastructure may or may not be heading. Can you weigh in with a recommendation here, maybe covered by putting/updating the test plan in the open?

**Comment by NickGerleman** [comment]
Not sure there's an immediate action item here. Closing for now unless anyone disagrees.
