### ISSUE TITLE
Support react-native-responsive-screen

### ISSUE THREAD

**Issue by syedibrahimt** [microsoft/react-native-windows#5976]
# Support `react-native-responsive-screen` on RNW

## Basic Info
- Module Repo URL: [link to repo](https://github.com/marudy/react-native-responsive-screen)
- Target version: react native 0.63
- [ ] Issue exists on module repo (if so, [link]())

- [ ] Module has a Legacy/C# implementation (if so, [link]())

## Which app/customer is requesting this module?

BackPack - Knomadix corporation

## In what scenarios will this module be used?

react-native-responsive-screen is a small library that provides 2 simple methods so that React Native developers can code their UI elements fully responsive. No media queries needed.

It also provides an optional third method for screen orientation detection and automatic rerendering according to new dimensions.

## Essential Features

In order to create responsive UIs, you need to import and use these 2 methods called widthPercentageToDP and heightPercentageToDP. The names are a bit big but they try to be indicative. That being said, both methods accept a string like percentage ('30%') as an argument and return the percentage of the screen’s actual width or height respectively in dp.

**Comment by stmoy** [comment]
This should be fixed by PR: https://github.com/microsoft/react-native-windows/pull/6286
