### ISSUE TITLE
Support react-native-render-html

### ISSUE THREAD

**Issue by syedibrahimt** [microsoft/react-native-windows#5977]
# Support `react-native-render-html` on RNW

## Basic Info
- Module Repo URL: [link to repo](https://github.com/archriss/react-native-render-html)
- Target version: react native - 0.63
- [ ] Issue exists on module repo (if so, [link]())

- [ ] Module has a Legacy/C# implementation (if so, [link]())

## Which app/customer is requesting this module?

BackPack - Knomadix corporation

## In what scenarios will this module be used?

The app will receive some HTML code from the api, we need the same view to be rendered in the mobile.

## Essential Features

An iOS/Android pure javascript react-native component that renders your HTML into 100% native views. It's made to be extremely customizable and easy to use and aims at being able to render anything you throw at it.

**Comment by stmoy** [comment]
This has been verified to work as a JS-only module.
