### ISSUE TITLE
Needs help in integrating react-native-video

### ISSUE THREAD

**Issue by syedibrahimt** [microsoft/react-native-windows#5979]
I'm using react-native-video package in my android/ios app.

I need the same in react-native-windows app.

I did the installation steps as shown here ([link](https://www.npmjs.com/package/react-native-video#windows-installation))

But getting the below error. Can someone please help me in sorting this out. 

`Build failed with message E:\Projects\BackPack\backpackwindows\node_modules\react-native-video\windows\ReactNativeVideoCPP\ReactVideoViewManager.cpp(67,47): error C4996: 'winrt::Microsoft::ReactNative::JSValue::Object': Use TryGetObject or AsObject [E:\Projects\BackPack\backpackwindows\node_modules\react-native-video\windows\ReactNativeVideoCPP\ReactNativeVideoCPP.vcxproj]. Check your build configuration.`

**Comment by NickGerleman** [comment]
I think this was a change Vlad made back in 0.61 to deprecate an API. We likely need to update the package. 

If this is a compiler warning, you might be able to just suppress it in the meantime.

**Comment by chrisglein** [comment]
[react-native-video](https://github.com/react-native-community/react-native-video) was the first community module we took on after the new "vnext" module infrastructure. It may have been lost behind in the updates. We'll get someone to take a look and see if it needs some love.

**Comment by chrisglein** [comment]
@jonthysell You did a great job fixing up [camera](https://github.com/react-native-community/react-native-camera), which had been implemented in the same timeframe. Is there some similar clean up that video may also need?

**Comment by jonthysell** [comment]
This was fixed 1 month ago by https://github.com/react-native-video/react-native-video/pull/2119.

However react-native-video has not released a new version for 3 months.

Please ask the owners of react-native-video to release a new version with the fix.
