### ISSUE TITLE
VS 16.8 will break Folly (__builtin_clz missing)

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#5987]
The new VS 16.8 update will fail due to undefined `__builtin_clz`  once it RTW.

**Comment by asklar** [comment]
DevCom link: https://developercommunity.visualstudio.com/content/problem/1183035/-builtin-clz-missing-in-latest-168-preview.html

**Comment by chrisglein** [comment]
Our cloud builds will be automatically upgraded to latest VS and this could hit... basically all the versions.
Fix according to the DevCom link is to take a new drop of folly.
