### ISSUE TITLE
Can't build C++ app referencing C# module with XAML component

### ISSUE THREAD

**Issue by elcssmouhsine** [microsoft/react-native-windows#6003]
Run the following in your terminal and copy the results here.
1. `npx react-native --version`: 

4.10.1

2. `npx react-native run-windows --info`:

 System:
    OS: Windows 10 10.0.18363
    CPU: (6) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 1.23 GB / 3.98 GB
  Binaries:
    Node: 12.18.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 16.13.1 => 16.13.1
    react-native: ^0.62.0-0 => 0.62.2
    react-native-windows: 0.62.10 => 0.62.10
  Installed UWP SDKs:
    10.0.18362.0

3. `reg query "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock"`

 AllowDevelopmentWithoutDevLicense    REG_DWORD    0x1
    AllowAllTrustedApps    REG_DWORD    0x1

 Debug

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create a new react-native-windows app ,and run it and it works perfectly
2. create a c# project inside the solution and add necessary references Microsoft.ReactNative etc... as per the docs
3. add reference of c# project to main c++ project and add ReactPackageProvider etc...
4. Run solution and it runs perfectly
5. add a CustomUserControl to c# project
6. Run solution but wont run and i get this errors

## Expected Results
App Runs

## Snack, code example, screenshot, or link to a repository:
`

Severity | Code | Description | Project | File | Line | Suppression State
-- | -- | -- | -- | -- | -- | --
Error | C2039 | 'XamlMetaDataProvider': is not a member of 'winrt::Cam' | ExamApp | C:\Users\elcss\Documents\examappnative\windows\ExamApp\Generated Files\XamlTypeInfo.g.cpp | 606 |  
Error | C2039 | 'Cam_XamlTypeInfo': is not a member of 'winrt::Cam' | ExamApp | C:\Users\elcss\Documents\examappnative\windows\ExamApp\Generated Files\XamlTypeInfo.g.cpp | 604 |  
Error | C2039 | 'Cam_XamlTypeInfo': is not a member of 'winrt::Cam' | ExamApp | C:\Users\elcss\Documents\examappnative\windows\ExamApp\Generated Files\XamlTypeInfo.g.cpp | 606 |  
Error | C3083 | 'Cam_XamlTypeInfo': the symbol to the left of a '::' must be a type | ExamApp | C:\Users\elcss\Documents\examappnative\windows\ExamApp\Generated Files\XamlTypeInfo.g.cpp | 604 |  
Error | C3083 | 'Cam_XamlTypeInfo': the symbol to the left of a '::' must be a type | ExamApp | C:\Users\elcss\Documents\examappnative\windows\ExamApp\Generated Files\XamlTypeInfo.g.cpp | 606 |  
Warning | C4100 | 'packageProviders': unreferenced formal parameter | ExamApp | C:\Users\elcss\Documents\examappnative\windows\ExamApp\AutolinkedNativeModules.g.cpp | 9 |  
Error | C2039 | 'XamlMetaDataProvider': is not a member of 'winrt::Cam' | ExamApp | C:\Users\elcss\Documents\examappnative\windows\ExamApp\Generated Files\XamlTypeInfo.g.cpp | 604 |  

`

**Comment by asklar** [comment]
@elcssmouhsine can you please clarify what kind of C# projects you are adding? note that only C# UWP or C++/WinRT projects are allowed (e.g. no C++/CX, and no desktop C# projects). Is the C# project a library (what kind?) or an app?

**Comment by elcssmouhsine** [comment]
i am adding a c# UWP project, i create it inside the same app solution
<img width="343" alt="Screen Shot 2020-09-16 at 7 52 21 AM" src="https://user-images.githubusercontent.com/64892714/93290384-a1166580-f7f1-11ea-9080-fb5c14438b9d.png">

**Comment by asklar** [comment]
Make sure your C++ app includes this in the pch:
```cpp
#include <winrt/Microsoft.UI.Xaml.XamlTypeInfo.h>
```

rebuild and try again

**Comment by elcssmouhsine** [comment]
yes it does include it, but still same issue, i have also tried making the c# project as a separate project then adding it but still same problem when i add any XML item to c# project i get this error, i tried making a clean project many time, still same issue.

**Comment by asklar** [comment]
Hmm. Nothing comes to mind... would it be possible for you to share your repo for us to take a look?

**Comment by elcssmouhsine** [comment]
Thank you, here is a fresh repo that i made with same issue
https://github.com/elcssmouhsine/CSSample

**Comment by asklar** [comment]
I don't get any errors, it builds fine for me... make sure you change the platform to a native platform (x86 or x64, not Any CPU):
![image](https://user-images.githubusercontent.com/22989529/93310281-70b2d500-f7b9-11ea-96ef-7584115eee7a.png)

![image](https://user-images.githubusercontent.com/22989529/93310301-77414c80-f7b9-11ea-8759-111e6218d7e6.png)

**Comment by asklar** [comment]
Ok I see the issue. You have some XAML in your project, which requires that you add the xaml type info to the consuming C++ app's PCH:

#include <winrt/Cam.Cam_XamlTypeInfo.h>

And also you will need to add a reference from the C++ app onto the Microsoft.ReactNative.Managed project.
Please also read the caveats about using C# modules from C++ apps in our documentation: https://microsoft.github.io/react-native-windows/docs/native-modules#c-vs-c-for-native-modules

**Comment by elcssmouhsine** [comment]
Thank you for your help. I have been struggling with this for the past 2 days.
I think this should be added to the docs.

**Comment by asklar** [comment]
Agree, I'll add a note.

**Comment by chrisglein** [comment]
@asklar Can you open an issue on the cppwinrt repo that links to this one? Then given your troubleshooting guide issue we can close out this issue. Thank you for helping unblock everything through this :)

**Comment by asklar** [comment]
@elcssmouhsine @chrisglein 
Updated the cppwinrt troubleshooting docs with this info:
ref: https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/troubleshooting
ref: https://docs.microsoft.com/en-us/windows/uwp/winrt-components/create-a-windows-runtime-component-in-cppwinrt
