### ISSUE TITLE
Is it possible to create appbar for react native windows app

### ISSUE THREAD

**Issue by h4wwk3ye** [microsoft/react-native-windows#6004]
I want to create a simple app but the whole functionality of the app resides in appbar.
[Win32 docs](https://docs.microsoft.com/en-us/windows/win32/shell/application-desktop-toolbars)
So, is it possible to create an appbar for a react native app?

**Comment by asklar** [comment]
@h4wwk3ye The only supported React Native Windows apps are UWP apps and so they only have access to APIs available to UWP, and they all have a top level window with full chrome, so the APIs you mention will not available.
