### ISSUE TITLE
NuGet packages include symbols

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#6011]
The current nuget packages we produce (like v8jsi etc.) include PDBs which bloat the on-disk footprint, and 99% of developers won't need symbols for v8jsi, chakra, etc. These should instead be distributed via snupkg: https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg

![image](https://user-images.githubusercontent.com/22989529/93245672-7a4c2680-f740-11ea-9216-c8800e542f8d.png)

PDBs account for 1.3 GB:

FullName | Length
-- | --
ReactNative.V8Jsi.Windows.0.64.2\lib\win32\Debug\x64\v8jsi.dll.pdb | 170332160
ReactNative.V8Jsi.Windows.0.64.2\lib\win32\Debug\x86\v8jsi.dll.pdb | 168587264
ReactNative.V8Jsi.Windows.0.64.2\lib\win32\Release\x64\v8jsi.dll.pdb | 134377472
ReactNative.V8Jsi.Windows.0.64.2\lib\win32\Release\x86\v8jsi.dll.pdb | 130871296
Microsoft.ChakraCore.vc140.1.11.20\lib\native\v140\x86\release\ChakraCore.pdb | 70201344
Microsoft.ChakraCore.vc140.1.11.20\lib\native\v140\x86\debug\ChakraCore.pdb | 70201344
ReactWindows.ChakraCore.ARM64.1.11.20\lib\native\v140\arm64\release\ChakraCore.pdb | 69480448
ReactWindows.ChakraCore.ARM64.1.11.20\lib\native\v140\arm64\debug\ChakraCore.pdb | 69480448
Microsoft.ChakraCore.vc140.1.11.20\lib\native\v140\x64\debug\ChakraCore.pdb | 68505600
Microsoft.ChakraCore.vc140.1.11.20\lib\native\v140\x64\release\ChakraCore.pdb | 68505600
Microsoft.ChakraCore.vc140.1.11.20\lib\native\v140\arm\debug\ChakraCore.pdb | 55914496
Microsoft.ChakraCore.vc140.1.11.20\lib\native\v140\arm\release\ChakraCore.pdb | 55914496
ChakraCore.Debugger.0.0.0.44\lib\native\x86\Debug\ChakraCore.Debugger.pdb | 28020736
ChakraCore.Debugger.0.0.0.44\lib\native\x64\Debug\ChakraCore.Debugger.pdb | 27308032
ChakraCore.Debugger.0.0.0.44\lib\native\ARM64\Debug\ChakraCore.Debugger.pdb | 26341376
ChakraCore.Debugger.0.0.0.44\lib\native\ARM\Debug\ChakraCore.Debugger.pdb | 23670784
ReactNative.V8Jsi.Windows.0.64.2\lib\win32\Debug\arm64\v8jsi.dll.pdb | 14708736
ChakraCore.Debugger.0.0.0.44\lib\native\x64\Release\ChakraCore.Debugger.pdb | 13774848
ChakraCore.Debugger.0.0.0.44\lib\native\ARM64\Release\ChakraCore.Debugger.pdb | 13316096
ChakraCore.Debugger.0.0.0.44\lib\native\x86\Release\ChakraCore.Debugger.pdb | 13152256
ChakraCore.Debugger.0.0.0.44\lib\native\ARM\Release\ChakraCore.Debugger.pdb | 10727424
ReactNative.V8Jsi.Windows.0.64.2\lib\win32\Release\arm64\v8jsi.dll.pdb | 9695232
ReactWindows.ChakraCore.ARM64.1.11.20\lib\native\v140\arm64\release\ch.pdb | 4804608
ReactWindows.ChakraCore.ARM64.1.11.20\lib\native\v140\arm64\debug\ch.pdb | 4804608
Microsoft.ChakraCore.vc140.1.11.20\lib\native\v140\x64\debug\ch.pdb | 4755456
Microsoft.ChakraCore.vc140.1.11.20\lib\native\v140\x64\release\ch.pdb | 4755456
Microsoft.ChakraCore.vc140.1.11.20\lib\native\v140\x86\debug\ch.pdb | 4616192
Microsoft.ChakraCore.vc140.1.11.20\lib\native\v140\x86\release\ch.pdb | 4616192
Microsoft.ChakraCore.vc140.1.11.20\lib\native\v140\arm\debug\ch.pdb | 4239360
Microsoft.ChakraCore.vc140.1.11.20\lib\native\v140\arm\release\ch.pdb | 4239360
Microsoft.googletest.v140.windesktop.msvcstl.static.rt-dyn.1.8.1\lib\native\v140\windesktop\msvcstl\static\rt-dyn\x64\Debug\gtest.pdb | 1429504
Microsoft.googletest.v140.windesktop.msvcstl.static.rt-dyn.1.8.1\lib\native\v140\windesktop\msvcstl\static\rt-dyn\x86\Debug\gtest.pdb | 1421312
Microsoft.googletest.v140.windesktop.msvcstl.static.rt-dyn.1.8.1\lib\native\v140\windesktop\msvcstl\static\rt-dyn\x64\Release\gtest.pdb | 1339392
Microsoft.googletest.v140.windesktop.msvcstl.static.rt-dyn.1.8.1\lib\native\v140\windesktop\msvcstl\static\rt-dyn\x86\Release\gtest.pdb | 1331200
Microsoft.googletest.v140.windesktop.msvcstl.static.rt-dyn.1.8.1\lib\native\v140\windesktop\msvcstl\static\rt-dyn\x86\Debug\gtest_main.pdb | 724992
Microsoft.googletest.v140.windesktop.msvcstl.static.rt-dyn.1.8.1\lib\native\v140\windesktop\msvcstl\static\rt-dyn\x64\Debug\gtest_main.pdb | 716800
Microsoft.googletest.v140.windesktop.msvcstl.static.rt-dyn.1.8.1\lib\native\v140\windesktop\msvcstl\static\rt-dyn\x86\Release\gtest_main.pdb | 692224
Microsoft.googletest.v140.windesktop.msvcstl.static.rt-dyn.1.8.1\lib\native\v140\windesktop\msvcstl\static\rt-dyn\x64\Release\gtest_main.pdb | 684032

**Comment by JunielKatarn** [comment]
Note, SNUPKG with native symbols is not yet supported by nuget.org.
Meaning, we wouldn't be able to publish them on that site.

We may be better of using the [legacy format](https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages) for now.

**Comment by asklar** [comment]
@JunielKatarn I think it's the other way around, nuget only support snupkg. See the notice _right above_ this: https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg#publishing-a-symbol-package

>   Note
The legacy format .symbols.nupkg is still supported but only for compatibility reasons (see Legacy Symbol Packages). NuGet.org's symbol server only accepts the new symbol package format - .snupkg.

**Comment by chrisglein** [comment]
@jonthysell I know there was discussion about changes to the nuget packages for binary distribution. This seems like a reasonable ask to drop these symbols into a separate symbols package.

**Comment by acoates-ms** [comment]
We should be publishing the symbols to a symbol server, then we wouldn't need to distribute the pbds at all.

**Comment by JunielKatarn** [comment]
> We should be publishing the symbols to a symbol server, then we wouldn't need to distribute the pbds at all.

Does ADO support symbol serving?
We could use a similar approach to our public read-only NuGet feed.

**Comment by jonthysell** [comment]
It looks like publishing a legacy symbol package to NuGet.org means it gets added to the ` https://nuget.smbsrc.net/` symbol server. We'd have to make sure to add instructions for people to be able to debug.

**Comment by jonthysell** [comment]
I tested adding the `-Symbols` flag to the nuget pack, which tells the command to create two packages, one without symbols, and one with symbols included:

![image](https://user-images.githubusercontent.com/10852185/131926998-e9257755-9c61-4c30-a509-afcccf8c7841.png)

So generating the packages may be this simple. Then it's a matter of making sure our publish pipeline pushes both files to the build artifacts, and that the release pipeline pushes both to nuget.org, and that we make sure we have instructions for people on how to get the symbols in VS.

**Comment by jonthysell** [comment]
Need to verify if we **need** to modify the nuspecs to also include sources in the package in order for it all to work. The command didn't complain, but I haven't tried "actually" debugging.
