### ISSUE TITLE
Resizing Window when Alert's ContentDialog is open breaks focus trap zone and overlay (XAML Islands only)

### ISSUE THREAD

**Issue by lyahdav** [microsoft/react-native-windows#6017]
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`: 4.12.0
2. `npx react-native run-windows --info`:
```
  System:
    OS: Windows 10 10.0.19041
    CPU: (40) x64 Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz
    Memory: 159.80 GB / 190.60 GB
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.0-20190429.1820 - C:\open\fbsource\xplat\third-party\yarn\yarn.BAT
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
    Watchman: 20200724.030019 - C:\tools\watchman\watchman.EXE
  Installed UWP SDKs:
    10.0.18362.0
```

3. `reg query "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock"`
```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock
    AllowDevelopmentWithoutDevLicense    REG_DWORD    0x1
    AllowAllTrustedApps    REG_DWORD    0x1
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Clone repo
2. Run the playground-win32.sln
3. Open alert
4. When alert is visible, resize window

## Expected Results
Cannot interact with controls outside of the Alert ContentDialog. Also overlay should resize to cover resized window.

![image](https://user-images.githubusercontent.com/359157/93277805-a59e3800-f777-11ea-9539-df14e7dce3a9.png)

**Comment by asklar** [comment]
The overlay is probably a OS XAML Islands bug where it isn't listening to the xamlroot's size change notification.
The fact you can't interact with other controls is by design as `ContentDialogs` which is how Alert is implemented are modal. Are Alerts not supposed to be modal?

**Comment by lyahdav** [comment]
Regarding interacting with controls behind the ContentDialog, I was saying that was the expected behavior, but after I resize I can interact with controls (since the overlay isn't resized), which is a bug. Alerts are supposed to be modal.

For now I plan to workaround this by disabling window resizing when a ContentDialog is up, but open to better ideas if you have them.
