### ISSUE TITLE
Not able to find app.js  when app.tsx is present

### ISSUE THREAD

**Issue by manohargss** [microsoft/react-native-windows#6019]
I have an app which is using app.tsx and not app.js  but the app.tsx is the folder .\src\components\app
because of which the app is not able  to start:

error: Error: Unable to resolve module `./lib/app/app` from `index.js`: ./lib/app/app could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules: rm -rf node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
    at ModuleResolver.resolveDependency (D:\Sourcecode\GVC\gvcReactNativeApp\gvcreactnative\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:186:15)
    at ResolutionRequest.resolveDependency (D:\Sourcecode\GVC\gvcReactNativeApp\gvcreactnative\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (D:\Sourcecode\GVC\gvcReactNativeApp\gvcreactnative\node_modules\metro\src\node-haste\DependencyGraph.js:287:16)
    at Object.resolve (D:\Sourcecode\GVC\gvcReactNativeApp\gvcreactnative\node_modules\metro\src\lib\transformHelpers.js:267:42)
    at D:\Sourcecode\GVC\gvcReactNativeApp\gvcreactnative\node_modules\metro\src\DeltaBundler\traverseDependencies.js:434:31
    at Array.map (<anonymous>)
    at resolveDependencies (D:\Sourcecode\GVC\gvcReactNativeApp\gvcreactnative\node_modules\metro\src\DeltaBundler\traverseDependencies.js:431:18)
    at D:\Sourcecode\GVC\gvcReactNativeApp\gvcreactnative\node_modules\metro\src\DeltaBundler\traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (D:\Sourcecode\GVC\gvcReactNativeApp\gvcreactnative\node_modules\metro\src\DeltaBundler\traverseDependencies.js:87:24)

**Comment by asklar** [comment]
We would need to know more about your setup in order to be able to help you. e.g. what is lib/app/app?
My guess is either your index.js at the root of your project is pointing to the wrong thing, or you have a bug in your metro config.

**Comment by manohargss** [comment]
> This issue lacks the environment info requested in the bug template. Please edit your issue report to add this information.
> 
> If you are using latest version:
> 
> 1. `npx react-native --version`: 4.13.0
> 2. `npx react-native run-windows --info`:
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 14.93 GB / 31.86 GB
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @react-native-community/cli: ^4.13.0 => 4.13.0
    react: 16.8.6 => 16.8.6
    react-native: ^0.63.0-0 => 0.63.2
    react-native-cli: ^2.0.1 => 2.0.1
    react-native-windows: 0.63.1 => 0.63.1
  Installed UWP SDKs:
    10.0.17134.0
    10.0.17763.0
    10.0.18362.0
> 
> Otherwise if `--info` doesn't exist:
> 
> 1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.63.2
> 2. `npm ls rnpm-plugin-windows`: empty
> 3. `npm ls react-native-windows`: -- react-native-windows@0.63.1
> 4. `node -v`: v12.18.3
> 5. `npm -v`: 6.14.6
> 6. `yarn --version`: 1.22.4

The code of index.js

import { AppRegistry } from 'react-native';
import GVCTestApp from './lib/app/app';

AppRegistry.registerComponent('GVCTestApp', () => GVCTestApp);

**Comment by chrisglein** [comment]
It'd be helpful to know more about what your TypeScript pipeline is (what babel transforms versus compilation). @kmelmon has been working through this on another app recently and trying to find the best practices for RN and TypeScript and it sounds like not using the compilation. It looks like you're putting in a `lib` directory - have you tried putting them side by side? There's nothing particularly Windows about this setup so you may have luck looking for TypeScript resources on the RN docs or on StackOverflow.

**Comment by kmelmon** [comment]
The RN guidance on adding typescript is here:  https://reactnative.dev/docs/typescript#docsNav
