### ISSUE TITLE
Using of WinRTC (WebRTC)

### ISSUE THREAD

**Issue by YuryFokin** [microsoft/react-native-windows#6020]
I'm developing an application in RN4W for Hololens and need to use WebRTC. How can i do it? I've found repo with WinRTC and it seems good for me. But how to connect with this project from RN ?

**Comment by asklar** [comment]
You will need to write a native module to wrap the webrtc APIs and expose them to your javascript.
Instructions on native modules can be found here: https://microsoft.github.io/react-native-windows/docs/native-modules

**Comment by YuryFokin** [comment]
Ok. I wanted to do so. It is a serious job. But may be i can use something that is already done? For example, WinRTC. 
https://github.com/microsoft/winrtc
Seems there are the same wrappers here that i need.

**Comment by asklar** [comment]
The wrappers in winrtc are just to expose it to native apps, not to react native. What you need is to add Windows support to the react-native-webrtc module: https://github.com/react-native-webrtc/react-native-webrtc 
which you can do with the instructions I mentioned in the previous comment (see the section about adding Windows support to an existing module).

**Comment by YuryFokin** [comment]
!!! It's an unexpected idea.  I use this module im my RN app for mobile. And it works great on android and apple. But transform it for Windows ... Is it possible? I have to think a little.

**Comment by YuryFokin** [comment]
So, adding Windows support to the react-native-webrtc module isn't a simple job. Though it is possible.

But i don't understand why i can't use WinRTC  in my RN4W project. 
Here is the description from https://github.com/microsoft/winrtc :
_When incorporating WinRTC with React Native, use the XAML control on top of the WinRTC for the best WinRTC experience._

But there is no example of linking WinRTC with RN4W.

**Comment by asklar** [comment]
I hadn't seen that comment. This might be a better question to pose in the winrtc repo then, but from what I understand by reading that page, what they're saying is: when you write a react native for windows app that wants to consume RTC, you would use the XAML control that winrtc provides. This translates into two options:
- If you want to interact with the winrtc control via javascript, you must create a native module to expose it to javascript
- Or if you only need to interact with it from your RNW app native code, then you can add the winrtc XAML control to the app's `mainpage.xaml`.

**Comment by chrisglein** [comment]
The form for making a module request is here: https://github.com/microsoft/react-native-windows/issues/new/choose
We haven't had a request for this particular module (https://github.com/react-native-webrtc/react-native-webrtc) so there isn't an existing issue and you can go ahead and open one. But for full transparency, that doesn't mean we'll go and add support necessarily - we just try to track requests and measure interest for when we do have bandwidth to implement modules.

I think the question here is resolved so I'll go ahead and close this issue.
