### ISSUE TITLE
After publishing my app as a release build: App cannot be opened / crashes immediatley after launch. How to debug?

### ISSUE THREAD

**Issue by exotexot** [microsoft/react-native-windows#6022]
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`: 4.12.0
2. `npx react-native run-windows --info`:
System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Memory: 9.58 GB / 15.97 GB
  Binaries:
    Node: 12.9.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @react-native-community/cli: ^4.12.0 => 4.12.0
    react: 16.11.0 => 16.11.0
    react-native: ^0.62.0-0 => 0.62.2
    react-native-windows: ^0.62.0-0 => 0.62.7
  Installed UWP SDKs:
    10.0.18362.0
    10.0.19041.0
3. `reg query "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock"`
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock
    AllowDevelopmentWithoutDevLicense    REG_DWORD    0x1
    AllowAllTrustedApps    REG_DWORD    0x1

What SDK version are you building for? Choose from 10.0.15063, 10.0.16299, 10.0.18362, etc.
- Target Platform Version(s): 10.0.1836 (MIN 10.0.15063)
What device(s) are you targeting? Choose any from Desktop, Xbox, Hololens)
- Target Device(s): Desktop
Which version of Visual Studio are you using? Specify Visual Studio 2017 or Visual Studio 2019
- Visual Studio Version: Visual Studio 2019
Which build configuration are you running? Choose from Debug, DebugBundle, Release, ReleaseBundle 
- Build Configuration: Release

Trying to get Release builds ready for my app. When running release builds from Visual studio, they do work.
After going through Project -> Publish -> Create App Packages, I can build without errors. After launching (and installing certificate etc...) the app launches, but crashes almost instantly. I'm not even able to see the UI of the App. Just crashes. 

As a comparison, I created a newly React-native project, as described on the Getting Started page, I can build and publish, and launch the default app without problems. So therefore the problem has to be somewhere in my code. Question is just how to debug it in order to solve the issue? Any advice?

**Comment by asklar** [comment]
@exotexot we'll probably need some more information about what is crashing and how. 
You can debug installed apps in Visual Studio via the Debug installed app package option:
![image](https://user-images.githubusercontent.com/22989529/93386409-81e0fd80-f81c-11ea-918a-db5da5a201b8.png)

It would be useful to know what your app setup is. Is it all C++? Or does it contain any C# code?

**Comment by exotexot** [comment]
Hi @asklar!

Thanks for this tip. I'm new to VS so i wasnt aware of this feature. And it helped me solving the issue. But I just want to describe a bit, because it is a bit confusing to me. 

I've appended the entire log as a text. At the very bottom you can see the crash:
Exception thrown: 'System.Reflection.ReflectionTypeLoadException' in System.Private.CoreLib.ni.dll
Exception thrown: 'System.Reflection.ReflectionTypeLoadException' in System.Private.CoreLib.ni.dll
Exception thrown at 0x00007FFBD75A3E49 (KernelBase.dll) in cateurope.exe: WinRT originate error - 0x80131602 : 'System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Microsoft.ReactNative.Managed.ReactPackageBuilderExtensions.InitAttributedModules()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Microsoft.ReactNative.Managed.ReactPackageBuilderExte'.
onecore\com\combase\winrt\error\restrictederror.cpp(1016)\combase.dll!00007FFBD7BDE1B3: (caller: 00007FFBD7B75EF9) ReturnHr(1) tid(3734) 8007007E The specified module could not be found.
Exception thrown at 0x00007FFBD75A3E49 in cateurope.exe: Microsoft C++ exception: winrt::hresult_error at memory location 0x000000D8F07FD830.

The application crashed becaused it couldnt find some .dlls from a react-native-module I'm using. I've made my own fork of react-native-static-server (https://github.com/exotexot/react-native-static-server/) which apparently fails to copy some .dlls which are included in the package from a respetive Nuget packet (https://www.nuget.org/packages/Restup/). The crash resolved after inserting the Restup.WebServer.dll, Restup.WebServer.Logging.dll and Restup.Webserver.Models.winmd into the AppX folder. 

Even though this is out-of-scope for this issue - which is acutally solved as I wanted to know how to debug it - could anyone help my finding out how to make share that a c# project does include its dll's into the appx folder after it has been linked successfully to a solution file?

[LOG2.txt](https://github.com/microsoft/react-native-windows/files/5239376/LOG2.txt)

**Comment by exotexot** [comment]
I'm also confused about the Debug log. Why doenst it say that those specific dlls are missing, and instead report a System.Reflection.ReflectionTypeLoadException?

**Comment by asklar** [comment]
in every References entry there is a property dialog you can go into and select "copy to output" or something like that.

**Comment by chrisglein** [comment]
> The crash resolved after inserting the Restup.WebServer.dll, Restup.WebServer.Logging.dll and Restup.Webserver.Models.winmd into the AppX folder.

@exotexot Sounds like your issue is resolved? If not, let us know.

**Comment by asklar** [comment]
re: why it doesn't report what DLLs are missing, I think it's likely that the code throwing the exception doesn't know which DLLs it is missing, it  tries to activate the type, and nobody replied "Me! I know!".
