### ISSUE TITLE
Support react-native-webrtc

### ISSUE THREAD

**Issue by YuryFokin** [microsoft/react-native-windows#6028]
# Support `react-native-webrtc` on RNW

## Basic Info
- Module Repo URL: [https://github.com/react-native-webrtc/react-native-webrtc]()
- Target version: 
- [ ] Issue exists on module repo (if so, [link]())

- [ ] Module has a Legacy/C# implementation (if so, [link]())

## In what scenarios will this module be used?
Real time video/audio for Hololens.

## Essential Features
video streaming
audio streaming
data transfering

**Comment by asklar** [comment]
Related: #6020
