### ISSUE TITLE
UWP TimingModule Potentially Prevents Sleep When Periodic Timers (e.g. setInterval) Set

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#6032]
The UWP implementation of TimingModule vaguely resembles the Android implementation, where we evaluate timers before rendering a frame. This is potentially needed for a correct implementation of `requestAnimationFrame` which uses the standard native timer interface. The implementation works by checking timers in the CompositionTarget.rendering callback. [Docs suggest](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.compositiontarget.rendering?view=winrt-19041) this potentially neutralizes energy saving features.

The desktop TimingModule takes an alternate approach of using kernel timers. We might be able to take a hybrid approach to be better for battery but retain frame-related behavior.

**Comment by NickGerleman** [comment]
Android also evaluates timers per-frame, and has some limitations. It currently asserts when relatively long intervals are set, but it is mentioned in code that the system will put the app to sleep if it's out of foreground.

**Comment by chrisglein** [comment]
Sounds like there's some reconciliation between the two implementations. They might both be incorrect in different ways. Are they intentionally different? Can they be unified?
