### ISSUE TITLE
Support react-native-sqlite-storage 

### ISSUE THREAD

**Issue by riq** [microsoft/react-native-windows#6033]
- Module Repo URL: [link to repo](https://github.com/andpor/react-native-sqlite-storage/)
- [ ] Issue exists on module repo 

- [x] Module has a Legacy/C# implementation [link](https://github.com/andpor/react-native-sqlite-storage/tree/master/platforms/windows)

## In what scenarios will this module be used?
Create, Open and Query SQLite Databases

**Comment by asklar** [comment]
@riq does react-native-asyncstorage not fulfill your requirements? if not could you elaborate on why?

**Comment by riq** [comment]
@asklar Unfortunately it does not. My use case in this particular scenario is to load an offline accessible [RxNorm](https://www.nlm.nih.gov/research/umls/rxnorm/index.html) medications database.

**Comment by asklar** [comment]
thanks for clarifying. The react-native-asyncstorage module implementation for Windows uses sqlite (winsqlite) as the backing store, so it could be a good starting point to implement react-native-sqlite-storage.

**Comment by stmoy** [comment]
@asklar - FWIW, react-native-sqlite-storage already has a Windows implementation: https://github.com/andpor/react-native-sqlite-storage/tree/master/platforms/windows

CC: @RobertEv

**Comment by robertev** [comment]
I noticed that, but it has not been updated in over 1 year... I am a bit wary to recommend that one... would react-native-asyncstorage be better? Seeking some guidance.

**Comment by chrisglein** [comment]
Looks like the module needs updating to the "vnext" style. But should be straightforward given there's already a 0.59 implementation (presumably).

**Comment by riq** [comment]
@stmoy -  Looks like @tsytsarkin has an open PR at https://github.com/andpor/react-native-sqlite-storage/pull/461

**Comment by chiaramooney** [comment]
Not something we plan to address on the Paper renderer as we move towards Fabric. If you would like to see this module supported on Fabric, please file an issue on the react-native-sqlite-storage repo.
