### ISSUE TITLE
LocationObserverModule will Fail Thread Checks

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#6037]
This uses react::uwp::BatchingMessageQueue created on the UI thread, and will fail thread checks as BatchingMessageQueue is itself weirdly thread-affined. We also seem to be using it like it should be the NM thread, even though it's not. Likely an artifact of the MSRN migration.

**Comment by NickGerleman** [comment]
There's a fun comment at the bottom here

```c++
  modules.emplace_back(
      LocationObserverModule::name,
      [messageQueue]() { return std::make_unique<LocationObserverModule>(messageQueue); },
      MakeSerialQueueThread()); // TODO: figure out threading
```

**Comment by chrisglein** [comment]
Duplicate of #6038
