### ISSUE TITLE
LocationObserverModule Should Be Removed

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#6038]
This existed to serve an API no longer in React Native, and has seemingly had some issues for a while (see #6037). We should remove this. We were previously still exposing the native APIs though, so it's possible this is still in some form of use.

**Comment by NickGerleman** [comment]
Some existing comments on https://github.com/microsoft/react-native-windows/issues/3832

Not sure if Stellar is still using the built in native bits. Hopefully not since they've been broken for a while.

**Comment by chrisglein** [comment]
Should be safe to remove without a deprecation warning. This should have been gone awhile ago and has been broken.
