### ISSUE TITLE
E2ETest BasePage.treeDumpResult() Has Faulty Wait

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#6041]
#5980 turned on extra eslint rules to catch cases where we have an async function but forget the `await` operator. One of these cases is in E2ETest, where BasePage defines an async Wait function that it doesn't await for.

I.e. the call to wait 100ms effectively no-ops.

Adding `await` and converting callers to async functions seems to cause ControlStyle tests to fail. Leaving the faulty code as-is for now with a suppression. We should either fix the tests or just remove the wait.

We're using a version of Jasmine that should support async functions, but the switch of callers to async functions might have side effects.

**Comment by kmelmon** [comment]
Not worth the effort.
