### ISSUE TITLE
c# native component example not rendering

### ISSUE THREAD

**Issue by mouhsinelonly** [microsoft/react-native-windows#6061]
I have followed the steps on https://microsoft.github.io/react-native-windows/docs/view-managers#sample-viewmanager-c
to create a native c# component, everything is working fine but the component is not rendering anything, also only the height/width style parameter seems to be working 

the area marked the text is where the component should be.

<img width="572" alt="Screen Shot 2020-09-22 at 10 07 34 AM" src="https://user-images.githubusercontent.com/514711/93848731-804f8380-fcbb-11ea-9271-c1a04920aa8f.png">

1. npx react-native --version:
4.13.0

2. npx react-native run-windows --info:

System:
    OS: Windows 10 10.0.18363
    CPU: (6) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 382.43 MB / 3.98 GB
  Binaries:
    Node: 12.18.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 16.13.1 => 16.13.1
    react-native: ^0.62.0-0 => 0.62.2
    react-native-windows: 0.62.11 => 0.62.11
  Installed UWP SDKs:
    10.0.18362.0

react-native -v: 0.62.11
npm ls rnpm-plugin-windows:  ExamApp@0.0.1 C:\Users\elcss\Documents\examappnative
`-- (empty)
npm ls react-native-windows: `-- react-native-windows@0.62.11
node -v:v12.18.2
npm -v: 6.14.5
yarn --version: 1.22.4

**Comment by mouhsinelonly** [comment]
npx react-native --version:
4.13.0

npx react-native run-windows --info:

System:
OS: Windows 10 10.0.18363
CPU: (6) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
Memory: 382.43 MB / 3.98 GB
Binaries:
Node: 12.18.2 - C:\Program Files\nodejs\node.EXE
Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
npmPackages:
react: 16.13.1 => 16.13.1
react-native: ^0.62.0-0 => 0.62.2
react-native-windows: 0.62.11 => 0.62.11
Installed UWP SDKs:
10.0.18362.0

react-native -v: 0.62.11
npm ls rnpm-plugin-windows: ExamApp@0.0.1 C:\Users\elcss\Documents\examappnative
-- (empty) npm ls react-native-windows: -- react-native-windows@0.62.11
node -v:v12.18.2
npm -v: 6.14.5
yarn --version: 1.22.4

**Comment by chrisglein** [comment]
Can you share a repo or some snippets of what you're doing? Without details on what your custom code is it's hard to help.

**Comment by mouhsinelonly** [comment]
i will upload example tomorrow
