### ISSUE TITLE
JSValue is not truly ABI safe

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#6082]
JSValue uses STL which renders it not ABI safe unless everyone is using the same tools/libs.

> It is provided for native developers (writing native modules or view managers) who want an equivalent to the folly::dynamic type that is compatible with the WinRT ABI surface provided by Microsoft.ReactNative.

**Comment by NickGerleman** [comment]
@vmoroz will know better but I believe we only expose JSValueReader/JSValueWriter on the ABI boundary, which is designed to be safe.
