### ISSUE TITLE
Crash When Trying to Load Certain Images on Pre-1903

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#6085]
Hitting this deterministically running integration tests in CI, which run on an older version of Windows Server 2019. In [ReactImage.cpp](https://github.com/microsoft/react-native-windows/blob/master/vnext/Microsoft.ReactNative/Views/Image/ReactImage.cpp) we have the following code:

```c++
            if (args.Status() == winrt::LoadedImageSourceLoadStatus::Success) {
              ...

                // If we are dynamically switching the resizeMode to 'repeat', then
                // the SizeChanged event has already fired and the ReactImageBrush's
                // size has not been set. Use ActualSize in that case.
                if (compositionBrush->AvailableSize() == winrt::Size{0, 0}) {
                  compositionBrush->AvailableSize(strong_this->ActualSize());
                }

                ...
            }
```

`ActualSize()` is only available in IUIElement10 introduced in 1903, which we fail to QI to and crash.

This specific code was added in https://github.com/microsoft/react-native-windows/pull/3712 which made it into later builds of 0.60. It's possible the path is newly hit though. Not sure why E2ETest isn't hitting this.

I think this is happening when we try to load the "x" close button image for LogBox. It's possible it has some effect we're not guarding on.

**Comment by NickGerleman** [comment]
Can be reproduced using `ComponentExample` in the `SampleTests` integration test

**Comment by NickGerleman** [comment]
Actually, I think this happens any time we redbox. This is kind of nasty since it means ITs crash in CI if we ever see an exception.

**Comment by NickGerleman** [comment]
Confirmed this happens when showing the mini logbox. I.e. this 
![image](https://user-images.githubusercontent.com/835219/94167909-e5cd7c80-fe41-11ea-9119-8fce1ded6997.png)

**Comment by chrisglein** [comment]
Comment from Andrew is that maybe this can just use ActualWidth and ActualHeight separately if those exist.

**Comment by NickGerleman** [comment]
@marlenecota have any ideas on when you'll be able to address this one? It currently creates a pretty bad experience for integration test failures.

**Comment by gillpeacegood** [comment]
We're using cloud VMs which are 1809 is it possible to put this on 0.63?

**Comment by chrisglein** [comment]
Yep, it was backported here: https://github.com/microsoft/react-native-windows/pull/6172
