### ISSUE TITLE
RNTesterIntegrationTests::Logging Sporadically Crashes

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#6089]
See https://dev.azure.com/ms/react-native-windows/_build/results?buildId=111850&view=logs&jobId=6a576c64-c360-5968-e6e9-1b092bc6a5ec&j=6a576c64-c360-5968-e6e9-1b092bc6a5ec&t=9867c3b7-ae0e-5159-b6d0-da40bcc7a881

This was just re-enabled. From this + past experiences, we seem to have sporadic crashes with desktop ITs in general, but previously all other tests were disabled.

**Comment by chrisglein** [comment]
Sounds like these tests have a history of being unstable, being turned off, then being turned on. Do we need a different way to get this coverage?

**Comment by JunielKatarn** [comment]
Did you re-run that pipeline?
All jobs show as passed right now.

**Comment by acoates-ms** [comment]
You can click on show previous attempts in the ADO page. It looks like in attempt #1 it failed

**Comment by NickGerleman** [comment]
Yes it was re-run to merge. Didn't realize the link would go to the new one. You can click "show previous attempts" to see the original

**Comment by JunielKatarn** [comment]
> Sounds like these tests have a history of being unstable, being turned off, then being turned on. Do we need a different way to get this coverage?

The instability has different reasons for different types of tests with also different fixes.

The main historic source of instability is an issue with node networking servers.

This test is unrelated. If I get ahold of a sample failure, I can look into it.

**Comment by JunielKatarn** [comment]
It just shows as a crash. This is unfortunate.

I’ll monitor this test throughout the day and disable if frequency is non-negligible, worst case.
