### ISSUE TITLE
Error when following "Get Started -> With VS Code" directions for Windows: unknown option `--proxy'

### ISSUE THREAD

**Issue by jesbis** [microsoft/react-native-windows#6091]
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`:
```
4.13.0
```
2. `npx react-native run-windows --info`:
```
 System:
    OS: Windows 10 10.0.19041
  Binaries:
    Node: 12.18.4 - C:\Program Files (x86)\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.8 - C:\Program Files (x86)\nodejs\npm.CMD
  npmPackages:
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
    react-native-windows: ^0.63.0-0 => 0.63.3
  Installed UWP SDKs:
    10.0.17134.0
    10.0.18362.0
```
3. `reg query "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock"`
```
    AllowDevelopmentWithoutDevLicense    REG_DWORD    0x1
    AllowAllTrustedApps    REG_DWORD    0x1
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Follow "With VS Code" directions to create a new app per: 
https://microsoft.github.io/react-native-windows/docs/getting-started

```
> npx react-native init testapp --template react-native-template-typescript@6.5.*
> cd testapp
> npx react-native-windows-init --overwrite
```
2. add .vscode/launch.json
3. F5

VS Code debugging works for Android but not Windows. Windows fails with below error.
CLI (`npx react-native run-windows`) and VS work fine.

Looks like the same problem as this comment but I didn't see an issue for it:

https://github.com/microsoft/react-native-windows/issues/4134#issuecomment-671596103

#### `React Native` tab output:
```
[Error] Error: Error while executing command 'c:\Users\testuser\Source\Repos\testapp\node_modules\.bin\react-native.cmd run-windows --proxy --no-packager': Error while executing command 'c:\Users\testuser\Source\Repos\testapp\node_modules\.bin\react-native.cmd run-windows --proxy --no-packager' (error code 101)
```

#### `React Native: Run windows` tab output:
```
[Info] Starting React Native Packager.
[Info] Attaching to running React Native packager
error: unknown option `--proxy'
```

**Comment by asklar** [comment]
The `--proxy` is coming from the react native extension: https://github.com/microsoft/vscode-react-native/blob/4dfc9ffdec1cdd7d033000fe778fbe6574e31917/src/extension/windows/windowsPlatform.ts#L50

we don't have a --proxy option in our CLI anymore, it's called --remote-debugging now:
https://github.com/microsoft/react-native-windows/commit/8f12940f753cee4f1ad8d4da7d9d3a3e755b9241

**Comment by asklar** [comment]
Filed bug in the extension repo and sent mail to the team.

**Comment by chrisglein** [comment]
Looks like the 1.0 release that just dropped has this fix: https://github.com/microsoft/vscode-react-native/releases/tag/1.0.0
Grab that and you should be good.
