### ISSUE TITLE
Add C++/WinRT VSIX to rnw-dependencies for app devs

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#6095]
_Originally posted by @asklar in https://github.com/microsoft/react-native-windows-samples/pull/268#discussion_r495129034_

The VSIX adds the necessary templates to VS to create new projects (libraries, winrt components, apps) and items (classes) written in cppwinrt.

**Comment by chrisglein** [comment]
Can be installed from VS, but may not be obvious that they need to go get it.
