### ISSUE TITLE
TextInput onPressIn/onPressOut properties don't work

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#6101]
Two new APIs were added to textInput in RN version 0.64:
onPressIn
onPressOut
See:  https://github.com/facebook/react-native/commit/b7b0e23

The new APIs are events that fire when the pointer goes down/up.

Although the new APIs are just leveraging pressable, there is a possibility that XAML TextBox will process the pointer events and not propagate them up to the JS layer.

This issues is tracking verifying if these APIs work when we do the upgrade to 0.64

**Comment by NickGerleman** [comment]
IIRC we've already pulled this change into our repo, so we can test now.

**Comment by NickGerleman** [comment]
Oh nope, we don't have this one yet. We hopefully should soon though.

**Comment by NickGerleman** [comment]
Testing the build now and can confirm the new properties do not work as-is.

**Comment by rectified95** [comment]
I also tried it yesterday and they don't work.
Moreover, Simply registering the PointerPressed/PointerReleased events on the underlying XAML TextBox doesn't solve the issue. Seems that TextBox is composed of a view XAML controls, one of which swallows the event - needs deeper debugging.
