### ISSUE TITLE
Crashing Desktop IntegrationTests

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#6113]
#6094 re-enabled additional desktop integration tests and closed the previous issue about reliability

They were sporadically crashing within the PR, and we're seeing crashes affect new PRs now (e.g https://dev.azure.com/ms/react-native-windows/_build/results?buildId=112298&view=logs&jobId=6a576c64-c360-5968-e6e9-1b092bc6a5ec&j=6a576c64-c360-5968-e6e9-1b092bc6a5ec&t=9867c3b7-ae0e-5159-b6d0-da40bcc7a881 )

This hit 2/3 of PRs I made this morning.

**Comment by JunielKatarn** [comment]
PR out to silence this test.

Did you see any instances of another test failing, or was it only AsyncStorage?

**Comment by asklar** [comment]
This shouldn't need to be clarified, but we should only be enabling tests that will reliably pass.

**Comment by NickGerleman** [comment]
I want to reiterate some previous feedback from the PR enabling them, that if IntegrationTestHarnessTest was crashing, there's a crash beyond what the individual test is doing. It could be that we're triggering some async work that causes a crash before the one reported (e.g if we start a new test before XHRTest actually does its work). It could be an issue with the platform instead.

We shouldn't have any of these enabled right now.

**Comment by NickGerleman** [comment]
Leaving this open per comments in the PR.

**Comment by JunielKatarn** [comment]
Updated by #6119.

Moved to Mso::DispatchQueue-based MessageQueueThread.
Fixes hangs in Debug.

Will conduct deep validation before re-enabling.

**Comment by NickGerleman** [comment]
Had a really productive discussion about this earlier with some folks about desktop integration tests. We have a path forward, with the eventual goal to be to remove integration tests against the desktop DLL from this repo.

Some discussed steps to get there:
1. Converge UWP and Desktop websocket implementation (desktop ITs most valuable coverage)
2. Port any additional test coverage for WS from desktop ITs to MSRN ITs
3. Keep UTs against the desktop DLL to cover win32 specific code in OInstance, etc, until we have Core DLL
4. Work towards the ability to run JS integration tests in devmain itself, instead of trying to replicate the Office environment in-repo for ITs
5. Work on accelerating uptake of RNW bits into a devmain branch, as a match for the motivation of trying to catch issues added to RNW that effect Office before we integrate released builds
6. Remove desktop integration tests once we have a better devmain story

The understanding was that if we see new issues with the stubbing pop up during integration (runtime failures, build failures, failure to bundle), we can disable the tests. There may be some light investment in reliability, but we're not wanting to significantly invest in desktop ITs in repo, and expect the devmain architecture to likely look different (e.g. using Rex instead of the custom instance management code).

In the meantime, we haven't seen failures in the last couple days after we disabled AsyncStorageTest, so there isn't an immediately pressing issue, but if we see failures pop up, we should file separate issues.
