### ISSUE TITLE
CI Failures for WinUI3 Builds Due to OOM

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#6129]
After removing some added headers to the PCH we're seeing non-WinUI3 builds are stable again. WinUI3 builds, despite having a smaller PCH, seem to still be effected by OOM issues compiling individual translation units. Investigation is possibly needed as to why these jobs specifically are using more memory. We might be able to just ignore this until we have a new pool.

Converting the WinUI3 jobs to warnings in the meantime. This creates some risk of lost coverage, but in most cases where we would break the WinUI3 build, seeing all jobs fail would be a good indicator, and customers aren't using WinUI3 yet.

**Comment by chrisglein** [comment]
How do we want to track this versus issue #5949?
If we've resolved non-WinUI3 usage then maybe we want to unify on that in one issue. But let's confirm.

**Comment by NickGerleman** [comment]
Looks like the other issue was closed.
