### ISSUE TITLE
Building Solution: The contents of <bit> are available only with C++20 or later....

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#6138]
This started showing up frequently in build logs. This is pretty disruptive to build logs in `run-windows` which flash between this error and the file.

Likely related to the Folly upgrade.

**Comment by NickGerleman** [comment]
Screenshot of what this does to the line-by-line run-windows output.

![image](https://user-images.githubusercontent.com/835219/94731355-7d870b00-0319-11eb-8f4a-7341e2459bbd.png)

**Comment by asklar** [comment]
This is a Folly bug which I've fixed in Folly already:
https://github.com/facebook/folly/issues/1454

We just need to upgrade to the newer version.
