### ISSUE TITLE
Polyester controls roadmap

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#6149]
Some polyester controls are missing documentation and don't have RNTester pages, but the code is there.
- ButtonContentViewManager ("PLYButtonContent")
- ButtonViewManager ("PLYButton")
- ContentControlViewManager (is a superclass of the other ones, not directly available to JS?)
- HyperlinkViewManager ("PLYHyperlink")
- IconViewManager (this maps to `<Glyph>`)

The only one in that list that has an RNTester page is Glyph, and the controls documentation is pretty light 
https://microsoft.github.io/react-native-windows/docs/glyph-component

- Should the controls under the polyester folder be removed from the core RNW?
- If not, we should add RNTester pages for the other polyester controls?

**Comment by chrisglein** [comment]
These should all be deleted.
