### ISSUE TITLE
Enable inspecting state of Hermes environment from a crash dump

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#6152]
This likely means a windbg debugger extension

**Comment by chrisglein** [comment]
@Khalef1 Is there any work already done on this? Should this be tracked on the Hermes repo?

**Comment by Khalef1** [comment]
@chrisglein: No work is currently being done. I agree, it's better to track this in the Hermes repo: https://github.com/microsoft/hermes-windows/issues/21

**Comment by chrisglein** [comment]
Thanks Khalef. Closing this issue out as Khalef has opened on that repo.
