### ISSUE TITLE
Add ReadValue / WriteValue for winrt::hstring

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#6166]
>winrt::hstring [](start = 94, length = 14)

Since native module methods can support any parameter type which has ReadValue and WriteValue functions. we must fix this issue by adding the reader writer for winrt::hstring to avoid extra memory allocation due to the conversion.

_Originally posted by @vmoroz in https://github.com/microsoft/react-native-windows-samples/pull/280#discussion_r498542159_

**Comment by BartoszKlonowski** [comment]
@asklar / @chrisglein  Please assign me to this item, so I can work on it.
