### ISSUE TITLE
CI fails with timeout

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#6179]
https://github.com/microsoft/react-native-windows/pull/6178/checks?check_run_id=1201360112
https://dev.azure.com/ms/react-native-windows/_build/results?buildId=113866&view=logs&jobId=4ffd4db3-6d8f-510f-3ddf-442192d0d8d8&j=4ffd4db3-6d8f-510f-3ddf-442192d0d8d8

![image](https://user-images.githubusercontent.com/22989529/94978965-fa121900-04d4-11eb-9dab-1c0b7c39ecb8.png)

**Comment by NickGerleman** [comment]
Looks like Azure Pipelines network degredation. The job was stuck for 40 minutes trying to check out the git repo at 23kb/s.

![image](https://user-images.githubusercontent.com/835219/94983130-a7485980-04f4-11eb-8d9e-9894d015b05a.png)


```
Receiving objects:  29% (38550/130912), 53.53 MiB | 22.00 KiB/s
Receiving objects:  29% (38550/130912), 53.57 MiB | 23.00 KiB/s
Receiving objects:  29% (38550/130912), 53.64 MiB | 27.00 KiB/s
Receiving objects:  29% (38550/130912), 53.67 MiB | 23.00 KiB/s
Receiving objects:  29% (38550/130912), 53.68 MiB | 29.00 KiB/s
Receiving objects:  29% (38550/130912), 53.70 MiB | 28.00 KiB/s
Receiving objects:  29% (38550/130912), 53.71 MiB | 25.00 KiB/s
Receiving objects:  29% (38550/130912), 53.75 MiB | 27.00 KiB/s
Receiving objects:  29% (38550/130912), 53.77 MiB | 23.00 KiB/s
```

**Comment by chrisglein** [comment]
Looks like a core infrastructure with Azure here. If this is rare, we'll just have to manually retry. If this becomes more common maybe we need to do something.
