### ISSUE TITLE
CI fails with out of memory even after the winui 3-as-warning change

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#6180]
It's not clear why but we are still seeing winui 3 related builds fail the CI

https://dev.azure.com/ms/react-native-windows/_build/results?buildId=113800&view=logs&j=286475db-899e-5101-5f85-8c45c94030c2&t=0cea8897-d1c1-5011-2e20-d39a9e62ee23&l=8958

**Comment by asklar** [comment]
assigning to nick since he made the recent change to the winui 3 ci

**Comment by NickGerleman** [comment]
This PR targeted 0.63. It won't have any CI changes made since then.

**Comment by NickGerleman** [comment]
If we did want a fix in an older branch we could backport the change, but then we lose coverage on our release branches which matters a bit more. Not sure it's worth it.

**Comment by chrisglein** [comment]
We're not expecting a high PR volume specifically on the stable branch, so while taking the warning change over could help there it would also come at the expense of coverage. If we end up jamming more on 0.63 we can revisit this, but it sounds like we should not take the fix back.
