### ISSUE TITLE
Unexpected tab order with ScrollView and components around it

### ISSUE THREAD

**Issue by lyahdav** [microsoft/react-native-windows#6181]
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`: 4.13.0
2. `npx react-native run-windows --info`:
```
  System:
    OS: Windows 10 10.0.19041
    CPU: (40) x64 Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz
    Memory: 157.00 GB / 190.60 GB
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.0-20190429.1820 - C:\open\fbsource\xplat\third-party\yarn\yarn.BAT
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
    Watchman: 20200724.030019 - C:\tools\watchman\watchman.EXE
  Installed UWP SDKs:
    10.0.18362.0
```
3. `reg query "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock"`
```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock
    AllowDevelopmentWithoutDevLicense    REG_DWORD    0x1
    AllowAllTrustedApps    REG_DWORD    0x1
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Clone this repo
2. Run playground app (UWP or Win32)
3. Modify one of the RNTester examples to:
```
function ScrollViewBugExample() {
  return (
    <View>
      <Button title="Button 1" />
      <ScrollView>
        <Button title="Button 2" />
      </ScrollView>
      <Button title="Button 3" />
    </View>
  );
}
```

4. Use tab to cycle focus in the app

## Expected Results
Tab order expected: Button 1, Button 2, Button 3
Tab order actual: Button 2, Button 1, Button 3

I also verified this isn't a Xaml bug as the following Xaml has the expected tab order:
```
    <StackPanel>
        <Button Content="Button 1" />
        <ScrollViewer Height="20">
            <Button Content="Button 2" />
        </ScrollViewer>
        <Button Content="Button 3" />
    </StackPanel>
```

**Comment by chrisglein** [comment]
Possible app workaround may be to use `tabIndex`, which isn't in the API docs (@harinikmsft FYI). Just in case that helps while we figure out the bug.

**Comment by lyahdav** [comment]
FYI, I confirmed that setting `tabIndex` is a workaround for now.

**Comment by lyahdav** [comment]
I spoke too soon. `tabIndex` doesn't seem to help. I tried with this React component and tab order goes 2,1,3 instead of 1,2,3:
```
function FocusZoneViewExample() {
  const itemStyle: ViewStyle = {
    width: 120,
    height: 50,
    backgroundColor: 'aqua',
    justifyContent: 'center',
    alignItems: 'center',
  };
  return (
    <View
      style={{
        flex: 1,
        justifyContent: 'space-between',
      }}>
      <TouchableHighlight style={itemStyle} {...{tabIndex: 1}}>
        <Text>tabIndex 1</Text>
      </TouchableHighlight>
      <ScrollView>
        <TouchableHighlight style={itemStyle} {...{tabIndex: 2}}>
          <Text>tabIndex 2</Text>
        </TouchableHighlight>
      </ScrollView>
      <TouchableHighlight style={itemStyle} {...{tabIndex: 3}}>
        <Text>tabIndex 3</Text>
      </TouchableHighlight>
    </View>
  );
}
```

**Comment by lyahdav** [comment]
Oh wait, I just tried setting tabIndex on the ScrollView and it works:

    <View
      style={{
        flex: 1,
        justifyContent: 'space-between',
      }}>
      <TouchableHighlight style={itemStyle} {...{tabIndex: 1}}>
        <Text>tabIndex 1</Text>
      </TouchableHighlight>
      <ScrollView {...{tabIndex: 2}}>
        <TouchableHighlight style={itemStyle}>
          <Text>tabIndex 2</Text>
        </TouchableHighlight>
      </ScrollView>
      <TouchableHighlight style={itemStyle} {...{tabIndex: 3}}>
        <Text>tabIndex 3</Text>
      </TouchableHighlight>
    </View>

**Comment by kmelmon** [comment]
This is almost certainly due to the structure of the XAML tree we generate when we render it... The default focus search algorithm derives the order from the structure, which is the case when you don't set any tab index.

**Comment by kmelmon** [comment]
XAML tree looks like this:

**CRootVisual 0x010659f8, comp node 0x04bbe858
  CGrid 0x04ba88d0
  CXamlIslandRootCollection 0x04b95e98
  CConnectedAnimationRoot 0x080971b0
  CPopupRoot 0x04ba9000
  CPrintRoot 0x04b65030
  CTransitionRoot 0x04b95bf8
  CFullWindowMediaRoot 0x04b65c90
  CRootScrollViewer 0x08075428
    CScrollContentPresenter 0x0802a308
      CBorder 0x04b631b0, comp node 0x04bbad28
        CFrame 0x08086b18
          CContentPresenter 0x04ba8480
            CPage 0x04b8f1c0
              CGrid 0x0802a478 "ReactRootView"
                CGrid 0x0802aba8, comp node 0x04bdde78
                  CPanel 0x11b8f2d0 "<reacttag>: 43"
                    CPanel 0x11b8fff0 "<reacttag>: 39"
                      CPanel 0x11b8f6c0 "<reacttag>: 37"
                        CContentControl 0x0104b3e0
                          CContentPresenter 0x11ab3a40
                            CPanel 0x11a19920 "<reacttag>: 9"
                              CBorder 0x11ac20b0, comp node 0x0103e128
                                CPanel 0x11a19d10 "<reacttag>: 7"
                                  CTextBlock 0x11a09c68 "<reacttag>: 5", text {Button 1}
                        CScrollViewer 0x08075a28 "<reacttag>: 25"
                          CBorder 0x11ac1ab0 "Root"
                            CGrid 0x11ab3d20
                              CScrollContentPresenter 0x11ab45c0 "ScrollContentPresenter"
                                CContentControl 0x01053c30, comp node 0x0104a060
                                  CContentPresenter 0x11ab4b80
                                    CPanel 0x11a19530 "<reacttag>: 23"
                                      CContentControl 0x0103ebe0
                                        CContentPresenter 0x11ab4e60
                                          CPanel 0x11a197d0 "<reacttag>: 19"
                                            CBorder 0x11ac1c30, comp node 0x0104a250
                                              CPanel 0x11a19e60 "<reacttag>: 17"
                                                CTextBlock 0x11a09aa8 "<reacttag>: 15", text {Button 2}
                                      CTransitionRoot 0x11b46810, comp node 0x01002118
                                        CLayoutTransitionElement 0x11ab1fa0, target 0x11b46ff0, comp node 0x11b1def0
                              CGrid 0x11ab3030
                              CScrollBar 0x11a09568 "VerticalScrollBar"
                              CScrollBar 0x11a09728 "HorizontalScrollBar"
                              CBorder 0x11ac1630 "ScrollBarSeparator"
                        CContentControl 0x04be0408
                          CContentPresenter 0x11ab4cf0
                            CPanel 0x11a19a70 "<reacttag>: 35"
                              CBorder 0x11ac26b0, comp node 0x11a2bcd0
                                CPanel 0x11a19680 "<reacttag>: 33"
                                  CTextBlock 0x11a09e28 "<reacttag>: 29", text {Button 3}
                        CTransitionRoot 0x11b46960
**

**Comment by kmelmon** [comment]
Bug understood.  We mistakenly set a default TabIndex for ScrollView to 0 instead of int_max, which is the default TabIndex for XAML.  This causes confusion for FocusManager and the result is wacky tab ordering.

Simple fix, will have PR soon.
