### ISSUE TITLE
E2ETest "TypeError: Cannot read property 'testsuites' of null"

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#6215]
E2ETest under some failure condition (not sure what) will run infinitely, then eventually get killed by ADO timeout and fails to produce a useful error.

```
TypeError: Cannot read property 'testsuites' of null
    at D:\a\1\s\packages\E2ETest\run_wdio.js:82:14
    at Parser.<anonymous> (D:\a\1\s\node_modules\xml2js\lib\parser.js:303:18)
    at Parser.emit (events.js:315:20)
    at Parser.EventEmitter.emit (domain.js:483:12)
    at Parser.exports.Parser.Parser.parseString (D:\a\1\s\node_modules\xml2js\lib\parser.js:313:16)
    at Parser.parseString (D:\a\1\s\node_modules\xml2js\lib\parser.js:5:59)
    at parseLog (D:\a\1\s\packages\E2ETest\run_wdio.js:81:10)
    at D:\a\1\s\packages\E2ETest\run_wdio.js:115:15
    at Array.map (<anonymous>)
    at parseLogs (D:\a\1\s\packages\E2ETest\run_wdio.js:115:6)
```

![image](https://user-images.githubusercontent.com/835219/95414689-49948280-08e3-11eb-8936-c459485a368b.png)

**Comment by chrisglein** [comment]
Could be an error in Jasmine or WebDriver.io. `run_wdio` is working around the fact that Jasmine isn't surfacing an error code. May be an issue with running manually on Windows versus what we do CI.
Error that's surfacing is definitely unclear. 

What are the conditions where this repos? @NickGerleman can you add in some detail about when this hits so this issue is actionable?

**Comment by NickGerleman** [comment]
Talked about this a bit in the meeting, but the issue is that we don't do proper error handling. We actually suppress a warning about this, so the right thing to do here should be pretty clear.

```js
// eslint-disable-next-line handle-callback-err
  parser.parseString(xmlString, (err, res) => {
    if (!res.testsuites) {
      console.error(`Something went wrong processing file ${logfile}`);
    } else {
      for (const testsuite of res.testsuites.testsuite) {
        const attr = testsuite.ATTR;
```

This can be hit when the test runner is killed (ctrl+c). This specific instance it was when it infinitely ran in CI and ADO killed it. From what I can tell it seems to show up in many other cases.

Jasmine will set error codes. We were doing something wrong before if we were seeing issues and needed to wrap it.
