### ISSUE TITLE
C++ app/lib project templates use C# projects

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#6218]
We should not require any C# components in C++ apps or modules by default.

Related: #5549 
CC @jonthysell

**Comment by jonthysell** [comment]
What do you mean? What is used?

**Comment by asklar** [comment]
right - this won't be the default case though so by default we should not have them in the solution. 
A couple of options:
- add an option to opt in at project creation time, or
- add a script to opt in after the fact

**Comment by jonthysell** [comment]
I'd rather C# be a first class citizen and out of the box compatibility should not be opt-in.

While we're still building from source, if developers want to speed up their build, they can remove the projects if they really want to. Once we're on binaries, it won't matter.

In the meantime, it's not affecting their app runtime in any way.

**Comment by chrisglein** [comment]
We've had a lot of varied and strong opinions on this, seems like we should strike up a meeting and sort it out. We missed this Monday's slot so let's set up a one-off.

**Comment by asklar** [comment]
Discussion notes:

- add logic to autolinking to detect the language the native module was written in (e.g. via the project extension, either vcxproj/csproj). Based on that:
  - if there is one or more C# module then add the property to the app's project to enable bringing in the .net native props/targets
  - add the Microsoft.ReactNative.Managed project to the solution
