### ISSUE TITLE
Due diligence:  Declare correct dependencies in community modules

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#6223]
In the past, when adding support for Windows to community modules, we've accidentally made the community module package depend on a specific version of react-native-windows, or a specific major version.  This isn't the best way to declare the dependency as when we upgrade react-native-windows the module won't pick up the new dependency automatically.  The preferred way to declare the dependency is, as a peer dependency, and should use the >= specifier and begin at some min version, typically 0.62.0 (if it works with the module).

Example of doing it the "right" way (taken from https://github.com/react-native-community/react-native-checkbox/blob/ee84209e1a45454401894523654fa763fc924974/src/package.json#L45):

  "peerDependencies": {
    "react": "*",
    "react-native": ">= 0.62",
    "react-native-windows": ">=0.62"
  },

This task is tracking going back through every community module we've added windows support for and making sure we've declared the react-native-windows dependency in the preferred way.

**Comment by TheSavior** [comment]
There probably aren't many repos with this problem yet but wanted to share this neat tool. If you can find all the repos (even with some false positives) using GitHub search then you can use Shepherd to send automated PRs to all the repos with the applicable changes.

It's a neat tool for when we have to do changes across the ecosystem. https://www.nerdwallet.com/blog/engineering/shepherd-automating-code-changes/

**Comment by chrisglein** [comment]
@stmoy Other than the directory do we have a good single list of all the modules we've touched that we can create into a burn-down list on this issue?

**Comment by chrisglein** [comment]
Since October the list of modules has grown significantly, but we've also gotten better about updating the Directory so that's the right list. @chiaramooney has some experience going through a wide selection of them through that `Deploy` fix. Or this could fall in the work list you coordinate with your elves, @stmoy.

**Comment by chiaramooney** [comment]
All modules look good. Some declare no rnw peer dependency. I assume that's because the maintainer does not want to require those consuming the module for a pure rn app to have to install rnw.
