### ISSUE TITLE
Migrate CI Loop to use Azure scale set

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#6226]
WinDev is bringing up a pool of VMs with better hardware to share across the WinDev teams.  Using this pool will solve a major pain point for our CI loop - running out of memory.

This task is tracking moving our CI loop off of the "free" Microsoft hosted agents onto this pool when it comes online (ETA is ~2 weeks).

High level list of work:
-Change yml to use the new pool
-Install components that will not come installed by default.  Currently known set of components includes:
 - node.js
 -  winappdriver
 - yarn
-Cut down on the total work being done to save $.  We currently build the product binaries ~20 times across all the jobs that run in PR.

Keith Mahoney is on point from WinDev and is bringing up the pool.  In the mean-time we can use a "prototype" pool that was created as part of Keith's hackathon project.  It's very simple to use, see:  https://github.com/kmelmon/react-native-windows/blob/b286dc37ee6b6c505c97d3f6f5fcc394f59ffae6/.ado/windows-vs-pr.yml#L23

I prototyped some of the work to move over to Keith's prototype scale set, which we can borrow from as a starting point.  see:  https://github.com/kmelmon/react-native-windows/tree/winuipool

**Comment by kmelmon** [comment]
Instructions on how to create a scale set agent:
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops

**Comment by kmelmon** [comment]
@dannyvv  thank you for volunteering to help from RNW side!  I've re-pathed this issue to you as I am refocusing on other work, assuming you're OK with doing the work to actually change our CI loop to use the new pool.  Let me know if you have any questions/concerns.

**Comment by kmelmon** [comment]
Keith Mahoney says:

Ok, I have created two new build pools, both named ‘windevbuildagents’.
One in https://dev.azure.com/ms for OSS and one in https://dev.azure.com/microsoft for closed source.

These have VS 16.7 installed. Any other dependencies will need to be installed at build time. These are 8 core (D8s_v3) machines with 200GB drives.

Let’s see how this goes for the next month or so. I will keep an eye on budget to see how things look.

**Comment by dannyvv** [comment]
We could not use the WinDev pool for most of our validations because Azure VMSS backed Azure PipeLines Agent Pool must be either:
* Admin
* Interactive UI
you cannot have both at the same time.

and UWP installation and testing needs both...
We have solved this by setting up a 1ES Hosted pool with 4c32g machines that have the same image as the hosted pools.
