### ISSUE TITLE
async-storage module: error MSB4057: The target "Deploy" does not exist in the project

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#6239]
See issue on async storage repo: https://github.com/react-native-async-storage/async-storage/issues/448

```
ReactNativeAsyncStorage.vcxproj : error MSB4057: The target "Deploy" does not exist in the project
```

## Environment

```
RN : 4.13.0
System:
OS: Windows 10 10.0.19041
CPU: (24) x64 AMD Ryzen 9 3900XT 12-Core Processor
Memory: 20.82 GB / 31.91 GB
Binaries:
Node: 12.9.1 - C:\Program Files\nodejs\node.EXE
Yarn: 2.0.0-rc.36 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
npmPackages:
@react-native-community/cli: ^4.10.0 => 4.13.0
react: ^16.13.1 => 16.13.1
react-native: ^0.63.3 => 0.63.3
react-native-windows: ^0.63.0-0 => 0.63.4
Installed UWP SDKs:
10.0.18362.0
```

**Comment by asklar** [comment]
The project might have been created in an older version of RNW before layout deploy so fix is to update the project by adding the following to the project (just anywhere towards the bottom, right before </Project>
```xml
<Target Name="Deploy"/>
```

**Comment by chrisglein** [comment]
We should add this module to the gallery app to help us catch other issues in the future.

**Comment by chrisglein** [comment]
This might be a general issue for modules that were created before this Deploy target was added and we may need to scrub quite a few to add this. We also hit this same error with Checkbox in the RN Gallery app when running from the CLI but not from VS.

**Comment by hondek** [comment]
Same issue in Picker from @react-native-community/picker

**Comment by chiaramooney** [comment]
Issue Resolved: [PR](https://github.com/react-native-async-storage/async-storage/pull/463)

> Same issue in Picker from @react-native-community/picker
Issue Handled: [PR](https://github.com/react-native-picker/react-native-picker/pull/151)


> This might be a general issue for modules that were created before this Deploy target was added and we may need to scrub quite a few to add this. We also hit this same error with Checkbox in the RN Gallery app when running from the CLI but not from VS.
Issue Handled: [PR](https://github.com/react-native-checkbox/react-native-checkbox/pull/94)

Also Handled:
[DateTimePicker PR](https://github.com/react-native-datetimepicker/datetimepicker/pull/311)
