### ISSUE TITLE
Dimensions change event never fires

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#6269]
This issue was discovered by a partner in PAX team, currently blocking with no workaround.

The issue is that the Dimensions object never fires any change events.  So if you resize the window or change the DPI, any listeners to Dimensions will not receive the new dimensions.

To Repro:
Load RNTester
Go to Dimensions page
Resize the window

RESULT
the text showing the current dimensions does not update.

I dug a bit into the code, which led me here:  https://github.com/microsoft/react-native-windows/blob/958ebb9ceb5cab3241369c7305cab0d82e1c01a0/vnext/Microsoft.ReactNative/Modules/DeviceInfoModule.cpp#L60

```
void DeviceInfoHolder::notifyChanged() noexcept {
  if (m_notifyCallback) {
    m_notifyCallback(getDimensions());
  }
}
```
This is supposed to get called whenever we're supposed to fire the change event, but nobody is calling it.

This used to work so it is a regression.

**Comment by stmoy** [comment]
This work is required to unblock: https://github.com/microsoft/react-native-windows/issues/5976

**Comment by kmelmon** [comment]
There are 2 issues here:

- We introduced a regression when we refactored DeviceInfoModule.cpp, this caused us to stop firing the event when dimensions change.  That happens here:

```
void DeviceInfoHolder::updateDeviceInfo() noexcept {
  if (xaml::Window::Current()) {
    auto const window = xaml::Window::Current().CoreWindow();

    m_windowWidth = window.Bounds().Width;
    m_windowHeight = window.Bounds().Height;
  } else {
    /// TODO: WinUI 3 Island - mock for now
    m_windowWidth = 600;
    m_windowHeight = 800;
  }
  winrt::Windows::UI::ViewManagement::UISettings uiSettings;
  m_textScaleFactor = uiSettings.TextScaleFactor();
  auto const displayInfo = winrt::Windows::Graphics::Display::DisplayInformation::GetForCurrentView();
  m_scale = static_cast<float>(displayInfo.ResolutionScale()) / 100;
  m_dpi = displayInfo.LogicalDpi();
  m_screenWidth = displayInfo.ScreenWidthInRawPixels();
  m_screenHeight = displayInfo.ScreenHeightInRawPixels();
}

```
This function is supposed to call notifyChanged() at the bottom, but it doesn't, and thus we don't raise the event.

I fixed this but it exposed another bug:
- Once we start firing the event, the JS code is receiving an array instead of an object and throws an exception.  This is in Vlad’s area.  Fixing this has implications across a variety of scenarios (C# vs C++, native modules vs JSI).  In the RNTester repro, I see this code in Dimensions.js getting confused:

```
static set(dims: $ReadOnly<{[key: string]: any, ...}>): void {
    // We calculate the window dimensions in JS so that we don't encounter loss of
    // precision in transferring the dimensions (which could be non-integers) over
    // the bridge.
    let {screen, window} = dims;

```  
dims gets sent to JS as an array with one entry instead of an object:
![image](https://user-images.githubusercontent.com/33470154/96521529-58a1fb80-1226-11eb-8d20-4c61e8c3f113.png)

The code that produces the param in the event looks like this:

```
React::JSValueObject DeviceInfoHolder::getDimensions() noexcept {
  return React::JSValueObject{
      {"window",
       React::JSValueObject{{"width", m_windowWidth * m_scale},
                            {"height", m_windowHeight * m_scale},
                            {"scale", m_scale},
                            {"fontScale", m_textScaleFactor},
                            {"densityDpi", m_dpi}}},
      {"screen",
       React::JSValueObject{{"width", m_screenWidth},
                            {"height", m_screenHeight},
                            {"scale", m_scale},
                            {"fontScale", m_textScaleFactor},
                            {"densityDpi", m_dpi}}},
  };
}

```

So somehow JSValueObject is generating an array when it should generate an object.  This code used to work back before we moved in the direction of specs/codegen.  So something in there needs to change.

**Comment by chrisglein** [comment]
Any relation between this issue and [this one](https://github.com/facebook/react-native/issues/29451) on the core repo? I guess that one is "doesn't work consistently" and this is "doesn't work". But if there's anything shared between them I wanted to raise awareness.

**Comment by kmelmon** [comment]
Nope, this issue is RNW-specific as the bug is in our C++ code which isn't shared with any other platform.  FWIW it seems like the Android bug is also in native code.

**Comment by stmoy** [comment]
To help with prioritization, it bears mentioning that this underlying bug blocks key functionality of the Education ISV that we're working with. CC @chrisglein @vmoroz

**Comment by kmelmon** [comment]
Priority understood.  Chatted with Andrew, I found there is actually a straightforward fix that can be made.  I'll take a shot at fixing this.
