### ISSUE TITLE
RNW 0.63: is there a replacement for ReactContext.GetNativeModule?

### ISSUE THREAD

**Issue by gtRfnkN** [microsoft/react-native-windows#6278]
We're currently in the process of upgrading from rn-windows 0.59 to 0.63. Unfortunately, we are stuck with one functionality that was available in 0.59 but isn't anymore: `ReactContext.GetNativeModule()`. We use it in two ways and I would like to ask what the best replacement could be.

About our app: it's a kiosk application which communicates with different hardware components. For that, we have written .NET services that handle the hardware and communicate with our UI (written with rn-windows) via WCF. We created a native module (and sometimes a view manager) for each of those services to keep them separated.

Use Case 1:
We have a native module to get the device information and another to report metrics. It makes sense to keep them mostly separated but some device information should also be sent to the metrics module. So far, the easiest and most straight-forward solution was to get the other module and call the function directly using `reactContext.GetNativeModule<MyModule>().foo()`. But without `GetNativeModule` this is not possible anymore.

Use Case 2:
Our camera implementation provides both a module and view manager. The view manager has some logic integrated in there as well and calls a function from the module. Again, this was easy to do with `GetNativeModule` but doesn't seem as easy without it.

Is there any suggestion on what approach would be best to replace this functionality? Is there something already integrated that we can use? Should we implement it ourselves into the App.xaml.cs? Or should we pass all calls & data across rn?

Looking forward to some input. Thank you!

**Comment by chrisglein** [comment]
You should put it in the property bag. Here's the docs on that:
https://microsoft.github.io/react-native-windows/docs/ireactpropertybag-api
Let us know if that doesn't help solve your problem.

**Comment by gtRfnkN** [comment]
Thank you very much, this works well!

For anyone coming across the same issue: as suggested in the docs, I created a class to store the namespace & names for all the modules I want to share as well as strongly typed getters & setters:
```
private static IReactPropertyNamespace MyNamespace = ReactPropertyBagHelper.GetNamespace("MYNAMESPACE");
private static IReactPropertyName MetricsModuleName = ReactPropertyBagHelper.GetName(MyNamespace, "METRICS");

public static void SetMetricsModule(IReactContext reactContext, MyModule myModule)
{
    reactContext.Properties.Set(MetricsModuleName, myModule);
}

public static MyModule GetMetricsModule(IReactContext reactContext)
{
    return (MyModule)reactContext.Properties.Get(MetricsModuleName);
}
```

In `MyModule`, I set it like this:
```
[ReactInitializer]
public void Initialize(ReactContext reactContext)
{
	SetMetricsModule(reactContext.Handle, this);
}
```

And then consume it in the other native modules like this:
`GetMetricsModule(reactContext.Handle)?.Foo();`
Or in native views like this:
`GetMetricsModule(ReactContext)?.Foo();`

**Comment by SurajMDurgad** [comment]
> Thank you very much, this works well!
> 
> For anyone coming across the same issue: as suggested in the docs, I created a class to store the namespace & names for all the modules I want to share as well as strongly typed getters & setters:
> 
> ```
> private static IReactPropertyNamespace MyNamespace = ReactPropertyBagHelper.GetNamespace("MYNAMESPACE");
> private static IReactPropertyName MetricsModuleName = ReactPropertyBagHelper.GetName(MyNamespace, "METRICS");
> 
> public static void SetMetricsModule(IReactContext reactContext, MyModule myModule)
> {
>     reactContext.Properties.Set(MetricsModuleName, myModule);
> }
> 
> public static MyModule GetMetricsModule(IReactContext reactContext)
> {
>     return (MyModule)reactContext.Properties.Get(MetricsModuleName);
> }
> ```
> 
> In `MyModule`, I set it like this:
> 
> ```
> [ReactInitializer]
> public void Initialize(ReactContext reactContext)
> {
> 	SetMetricsModule(reactContext.Handle, this);
> }
> ```
> 
> And then consume it in the other native modules like this:
> `GetMetricsModule(reactContext.Handle)?.Foo();`
> Or in native views like this:
> `GetMetricsModule(ReactContext)?.Foo();`

How can I access reactContext in App.xaml.cs? @gtRfnkN

**Comment by acoates-ms** [comment]
`ReactContext` is created when the react-native instance is created, so depending on what you want it for in App.xaml.cs it will not be there.

You can access the PropertyBag from the `InstanceSettings`.  But using the code above, the module will not be set into the PropertyBag until the module is created, which will happen when the JS first requires the module.

If you wanted to put some native logic into the PropertyBag before the instance is loaded, you should create a native class that has your logic and put that into the PropertyBag Instead of putting the NativeModule directly into the PropertyBag.  Then your NativeModule can retrieve that class from the PropertyBag in its Initialize method.   --- This will also ensure make the same object be in the PropertyBag across instance reloads, which depending on your scenario might be beneficial.
