### ISSUE TITLE
RNW 0.63: how to properly dispose native modules & view managers?

### ISSUE THREAD

**Issue by gtRfnkN** [microsoft/react-native-windows#6279]
In rn-windows 0.59, there was a method for native modules when the module gets disposed (`OnReactInstanceDisposeAsync`) and another one for view managers (`OnDropViewInstance`). We use them to close the WCF connection to our native services.

Looking through the documentation & code, there doesn't seem to be any current alternative. Is there still a way to achieve this functionality?

Thank you!

**Comment by chrisglein** [comment]
The object should get released and you should be able to handle this when the object is finalized. Of course that's at the mercy of when the GC releases the object, it won't necessarily be immediately. Can be an option in the interim?

There is an instance destroyed event coming in 0.64, but it's not necessarily easy to get to if you're in a community module. It's not quite as direct as what you're describing. It looks like something where the API could be improved. We need to make sure we're in alignment with destruction patterns that Facebook is following.

**Comment by lvalentine** [comment]
I ran into a similar issue on RNW 0.64 recently with a native view that has some external resources (network connection, etc.) and it doesn't always get destroyed right away when the react component is removed from the tree. Eventually it looks like a XAML cleanup process will come in and destroy it (at some unspecified future time, possibly right away, but possibly not if the actual UI on the screen is pretty static), and this lead to some unexpected behavior from our view that was assuming it would die right away when it was no longer in the UI.

Was there any work done yet to add an event to notify the view or view manager when the component is destroyed?
