### ISSUE TITLE
Check existing modules for missing Deploy target

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#6280]
See this issue: #6239

There are other native module targets likely missing the Deploy target. We should check to see which are broken.
- [x] react-navigation
- [x] datetimepicker
- [x] progressview
- [x] async-storage
- [x] slider
- [x] camera
- [x] clipboard
- [x] picker
- [x] react-native-webview
- [x] checkbox
- [x] video 
- [x] netinfo

[Full list](https://reactnative.directory/?windows=true) (some of which are from an older incompatible version of react-native-windows)

## Steps To Reproduce
1. Add module as a dependency
2. Launch app from CLI

```error MSB4057: The target "Deploy" does not exist in the project.```

**Comment by chiaramooney** [comment]
Track progress-view PR: https://github.com/react-native-progress-view/progress-view/pull/49

Track clipboard PR: https://github.com/react-native-clipboard/clipboard/pull/79

Track react-native-webview PR: https://github.com/react-native-webview/react-native-webview/pull/1716

Track netinfo PR: https://github.com/react-native-netinfo/react-native-netinfo/pull/426

react-navigation and camera do not need changes.

**Comment by chiaramooney** [comment]
Track slider PR: https://github.com/callstack/react-native-slider/pull/242
