### ISSUE TITLE
Timeout can cause failure to create self-signed certificate on slower machines.

### ISSUE THREAD

**Issue by stratospheres** [microsoft/react-native-windows#6281]
Sadly, my developer machine fails on creating the self-signed certificate due to this timeout value:

https://github.com/microsoft/react-native-windows/blob/9bc6c559fc350480d6d014644c3fbf4882d5a39a/packages/%40react-native-windows/cli/src/generator-windows/index.ts#L38

![image](https://user-images.githubusercontent.com/1381129/96611393-78323600-12b1-11eb-82e2-6263d9c6c06d.png)

Hacking in some code to throw up the underlying error revealed it:

![image](https://user-images.githubusercontent.com/1381129/96612038-28a03a00-12b2-11eb-86d5-8b1ceda55c2b.png)

Also, it took quite awhile to diagnose (thanks @asklar !) because the underlying error is swallowed up here:

https://github.com/microsoft/react-native-windows/blob/0062570de8dc1755d65ee4cd5a4f07b478a17335/packages/%40react-native-windows/cli/src/generator-windows/index.ts#L62

Yes, I'd love a faster machine (you can tell my boss...), but in the meantime, I'd suggest that we don't need a timeout here, or it needs to be configurable. Additionally, it would be great to not swallow up the errors.

**Comment by BartoszKlonowski** [comment]
@asklar @chrisglein  I would like to work on this issue, so please assign me to it.
