### ISSUE TITLE
Unable to scroll the content inside a WebView using react native windows on surface device with touch action.

### ISSUE THREAD

**Issue by rahman2835** [microsoft/react-native-windows#6287]
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`:  4.13.0
2. `npx react-native run-windows --info`:  System:
    OS: Windows 10 10.0.18363
  Binaries:
    Node: 12.9.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-windows: ^0.63.0-0 => 0.63.5
  Installed UWP SDKs:
    10.0.17763.0
    10.0.18362.0

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.
1. create react-native-windows uwp app by using below steps.
   npm install -g react-native-cli
   react-native init ReactNativeWebViewDemo
   cd ReactNativeWebViewDemo
   Include "react-native-webview": "^10.9.2" in the package.json (in the dependencies)
   npx react-native-windows-init --overwrite
   
2.  Link the react-native-webview using below url.
https://github.com/react-native-webview/react-native-webview/blob/master/docs/Getting-Started.md

3. From the terminal : npm run start or yarn start

4.  Open the app.js file and import webview from react-native-webview and add below logic.
import { WebView } from 'react-native-webview';

const App: () => React$Node = () => {
  return (
    <>
         <WebView
         source = {{ uri:
         'https://www.google.com/?gws_rd=cr,ssl&ei=SICcV9_EFqqk6ASA3ZaABA#q=tutorialspoint' }}
         />
    </>
  );
};

5. run the app again or reload the app and try to scroll  the content inside  WebView using touch(surface device)

## Expected Results

It should try to scroll the content inside a WebView. But its not scrolling using touch actions of surface device.

**Comment by chrisglein** [comment]
@chiaramooney Can you try to repro this (feel free to use this as an opportunity to add a WebView to the gallery)?

**Comment by rahman2835** [comment]
Hi Team,

any update on this defect. We have a GA release next month. Before that we have to fix this. 

Thanks in advance.

**Comment by XunlaY** [comment]
Hey @rahman2835,
have you figured out how to fix this or do you know what could cause that problem? 
UWP Apps in general, react-native-windows or [react-native-webview](https://github.com/react-native-webview/react-native-webview/issues/1711) ?

**Comment by rahman2835** [comment]
@XunlaY 
Still we did not get the fix. When I tried Web view with UWP app, I'm able to scroll the content with touch actions. But when I use same web view/ react-native-webview inside react native windows then I'm unable to scroll the content using touch actions (surface windows device).

So its clearly a problem with react-native-windows. Same issue I created in react-native-webview too. 
Please find the defect details below.

https://github.com/react-native-webview/react-native-webview/issues/1711

I see lot of people are facing this issue on surface devices (touch devices).

Can you please help us how to fix this issue?

Thanks in advance.

Regards,
Rahman

**Comment by chiaramooney** [comment]
WebView component page add to gallery. Issue is reproduced. Cannot use touch to scroll through WebView content. 

Working on fixing bug now.

**Comment by rahman2835** [comment]
@chiaramooney Thank you so much for taking up this defect. When can we expect this fix ? In which release version? Actually our app is now GA.

**Comment by chiaramooney** [comment]
Alright sorry for the delay! The issue stems from the perspective transform that exists at the root of RNW. Removing the perspective transform resolves the issue but that isn't a valid solution since we are reliant on the transform for other behavior. A workaround that should work for you is to disable perspective for your specific app via [ReactRootView.IsPerspectiveEnabled](https://microsoft.github.io/react-native-windows/docs/ReactRootView#isperspectiveenabled) this should resolve the WebView scrolling issue as long as your app isn't dependent on 3D animations. Ultimately we're looking to add the ability to declare requirements when it comes to perspective for community modules. At that point we will update WebView so it will work without adjustments.

**Comment by chiaramooney** [comment]
PR out with docs updated to include workaround: https://github.com/react-native-webview/react-native-webview/pull/1927

**Comment by chiaramooney** [comment]
See [here](https://github.com/microsoft/react-native-gallery/blob/88601c3f9caa4b3fd5e496db81f7e89f2d7ba006/windows/rngallery/MainPage.cpp#L19) for code needed to disable perspective for the app.

**Comment by ehrhardf** [comment]
Thanks for providing a workaround, @chiaramooney. From what I see here (maybe I missed something), the workaround is only available on RNW 0.64+. Our app is still using 0.63 and we're not ready to update to 0.64 just now. Do you have an alternative solution to solve this on RNW 0.63? Thanks in advance!

**Comment by chiaramooney** [comment]
@ehrhardf We are about to release 0.65 at which point we are going to offer limited support for 0.63, so unfortunately we won't be able to offer support to workaround this problem from our end. If you see https://github.com/microsoft/react-native-windows/pull/5798. This is the code change needed to enable the IsPerspectiveEnabled API for the workaround. One option for you if you aren't ready to move to 0.64 would be to manage your own patch with the PR until you are ready to upgrade.
