### ISSUE TITLE
Documentation for Getting Started in VSCode

### ISSUE THREAD

**Issue by robertev** [microsoft/react-native-windows#6290]
# Proposal: Documentation for Getting Started in VSCode

## Summary
In general, getting started in VS Code building a Hello World application for React Native for Windows (or Android) is over simplified and very challenging when compared to other "getting started" tutorials in other languages.

The VS Code Getting Started steps here:
https://microsoft.github.io/react-native-windows/docs/getting-started
Result in a message box error  with gramatical errors and a link (that is not a clickable hyperlink) - error code 303, 604 - "An error occurred while launching the application. Seems to be that you are trying to debug from within directory that is not a React Native project root." (should at least be "a directory").
![error](https://user-images.githubusercontent.com/11981468/96766906-c9bdec00-13a9-11eb-924c-b8ed8bc20178.png)

The react tutorial here is slightly better, but reads more about the list of great features in VS Code versus a getting started tutorial. It has you open the existing Hello World sample... not build the actual Hello World.
https://code.visualstudio.com/docs/nodejs/reactjs-tutorial

There are many complexities not shown, such as getting Android studio up and running. Just getting to a Hello World from scratch with VS Code requires referencing many different non-MS sources. It would be great to have that encapsulated in one help doc somewhere - with caveats and pointers to common problems.

## Motivation
Feedback from our @microsoft/windows-appconsult team and customers getting started.

**Comment by chrisglein** [comment]
The error message itself is coming from the vscode extension. Can you create an issue on that repo? https://github.com/microsoft/vscode-react-native
(I'm assuming your feedback is more about the larger picture, and we shouldn't lose track of this specific issue)

As for the getting started guide we have as compared to the other platforms, I'm actually not sure if you're saying that the React tutorial should be more like the RNW one or the other way around. The React tutorial is hiding complexities by having you work from an existing project, not building one. Do you think that's a good thing or not? Should there be a separate tutorials for this (one to use a project, one to build a new project)?

Our Getting Started guide has grown to cover a lot of ground and we're definitely interested in feedback and suggestions on how to make it better.
