### ISSUE TITLE
Add a FocusZoneView component

### ISSUE THREAD

**Issue by lyahdav** [microsoft/react-native-windows#6293]
# Proposal: Add a FocusZoneView component

## Summary

There are places in apps where it's useful to have keyboard arrow keys move focus instead of tab/shift, e.g. in lists. This issue proposes a FocusZoneView component for this.

## Basic example
Assume the FlatList renders buttons:
```
<FocusZoneView>
  <FlatList ... />
</FocusZoneView>
```

## Open Questions

I don't have time to make a PR for this, but here's a working implementation (be warned this is off an older RNW commit):
[FocusZoneView.zip](https://github.com/microsoft/react-native-windows/files/5418442/FocusZoneView.zip)

NOTE: This required moving `ViewShadowNode` interface to `ViewViewManager.h` so it could be subclassed.

**Comment by lyahdav** [comment]
I decided to make a separate issue from #5397 since that one mentions focus trapping which is different from focus zone as far as I understood.

**Comment by harinikmsft** [comment]
Like @lyahdav says, this is purely about focus zones which I believe @rectified95 will need when he tackles #2107 

I will work on adding a spec based on @lyahdav's proposal for this shortly.

**Comment by rectified95** [comment]
After discussion with @harinikmsft I used this code to implement proper keyboard navigation for FlatList. Since that was a priority, the FocusZone component is no longer immediately necessary.

**Comment by lyahdav** [comment]
In case anyone looks at my code linked above in the future, it has a couple bugs. See my comments on https://github.com/microsoft/react-native-windows/pull/6565.
