### ISSUE TITLE
webgl binding for Directx

### ISSUE THREAD

**Issue by EhsanSarshar** [microsoft/react-native-windows#6301]
Is there any plan to map webgl to Dirext. as expo-gl did for opengl.
it will open whole much of opportunity. like using existing web 3d libraries and especially using Tensorflow.js for machine learning.

**Comment by chrisglein** [comment]
We don't have any plans certainly from the perspective of react-native-windows, but maybe it's another slice of technology you're looking for this to come from? Other than the broad opportunity is there something you were looking to accomplish?

**Comment by EhsanSarshar** [comment]
I want to use Three.js or Tensorflow.js (Machine learning) as it's currently possible in react-native with the help of expo-gl

**Comment by chrisglein** [comment]
There's been interest in combining Babylon and RNW, which seems like an interesting path (#2424). But overall the answer is that core contributors of RNW this isn't on our roadmap yet.

Would supporting [expo-gl](https://github.com/expo/expo/blob/master/docs/pages/versions/unversioned/sdk/gl-view.md) for RNW be enough? We have a module support issue template, if you want to file that (or we can transfer this issue into it). We try to coordinate community effort for filling in Windows support for modules via that.

**Comment by EhsanSarshar** [comment]
yes supporting expo-gl is enough

**Comment by EhsanSarshar** [comment]
my actual concern is using Tensorflow.js.

**Comment by EhsanSarshar** [comment]
if there is a better way to support Tensorflow.js. like the way Node.js or electron.js did would be appreciable

**Comment by asklar** [comment]
We don't have current plans to support this but here is a project that you could add Windows/DirectX support to: https://www.npmjs.com/package/@tensorflow/tfjs-react-native

If you want to use WebGL then you could use react-native-webview

**Comment by EhsanSarshar** [comment]
The project that you mentioned only supports mobile devices and open-gl.

**Comment by asklar** [comment]
@EhsanSarshar right - you could possibly implement the Windows / DirectX support and add it to that module though

**Comment by EhsanSarshar** [comment]
maybe react native  windows can inspire by the way tensorflow.js works in node.js

**Comment by leontepe** [comment]
Are there any updates on this? I am especially interested in Web/OpenGL implementation for RNW and RN for macOS. Is there any schedule for this?

**Comment by asklar** [comment]
There is no plan to implement this right now, but if someone wants to send a PR / create a module for it, we could review.
