### ISSUE TITLE
Support react-native-track-player with vnext

### ISSUE THREAD

**Issue by ryfow** [microsoft/react-native-windows#6302]
# Support `react-native-track-player` on RNW

I've got a PR started that works for me, but it'd be worth having someone that knows what they're doing look at it. [https://github.com/react-native-kit/react-native-track-player/pull/1054](https://github.com/react-native-kit/react-native-track-player/pull/1054)

## Basic Info
- Module Repo URL: [https://github.com/react-native-kit/react-native-track-player]()
- Target version: 0.63
- [x] Issue exists on module repo (if so, [https://github.com/react-native-kit/react-native-track-player/pull/1054]())

- [x] Module has a Legacy/C# implementation (if so, [https://github.com/react-native-kit/react-native-track-player/tree/dev/windows]())

## Which app/customer is requesting this module?

Singlewire Software
## In what scenarios will this module be used?

The  module will be used to play audio

**Comment by stmoy** [comment]
https://github.com/react-native-kit/react-native-track-player/pull/1159

**Comment by stmoy** [comment]
https://github.com/DoubleSymmetry/react-native-track-player/pull/1180
