### ISSUE TITLE
RNTester After Redesign Doesn't Handle Window Resize

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#6303]
Before resize:

![image](https://user-images.githubusercontent.com/835219/96915370-01d13780-145b-11eb-8c1e-0888b4e988ed.png)

After resize:
![image](https://user-images.githubusercontent.com/835219/96915772-858b2400-145b-11eb-97f8-a7782da8185d.png)

Not sure how the inner section is being sized. Impact is dev-only/pretty low.

**Comment by NickGerleman** [comment]
This is because `ExamplePage.js` caches screen width into a global and uses that.

https://github.com/facebook/react-native/blob/master/packages/rn-tester/js/components/ExamplePage.js#L25

```
const ScreenWidth = Dimensions.get('window').width;
import {RNTesterThemeContext} from './RNTesterTheme';
```

**Comment by chrisglein** [comment]
@NickGerleman can you open an issue on rn-tester to fix this upstream? We may make the fix ourselves, but we should log it there.

**Comment by NickGerleman** [comment]
Logged in FB's repo. Keeping it in both until we take in a fix.

**Comment by NickGerleman** [comment]
Merged upstream.
