### ISSUE TITLE
JSDispatcher should call through JSCallInvoker to flush the JS queue

### ISSUE THREAD

**Issue by acoates-ms** [microsoft/react-native-windows#6309]
JSDispatcher should use JSCallInvoker internally so that the JS thread's native module queue gets flushed.  This is required at least until the Promise polyfil is removed.  But will probably be needed until we are completely rid of all NativeModules. (Everything running on TurboModules)

**Comment by chrisglein** [comment]
Suspected that this is calling delays on things on the JS thread.
