### ISSUE TITLE
Wrong Copyright Info

### ISSUE THREAD

**Issue by emmanuj** [microsoft/react-native-windows#6311]
https://github.com/microsoft/react-native-windows/blob/3ea4305551ec7bc57a220575dd0ea3db49289383/vnext/src/Libraries/Components/ToastAndroid/ToastAndroid.windows.js#L2

Should this say Microsoft instead of Facebook?

**Comment by NickGerleman** [comment]
We've seen this come up before. A number of the files in our repo are either synchronized source copies or forks from source in `react-native` core which uses Facebook copyright headers. This is something that is too our understanding okay given the MIT license, and the license in the root of our repo attributing to Microsoft.
