### ISSUE TITLE
[CI Instability] Timeout Running E2ETest

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#6312]
We've been seeing this time out a bit more recently. Contributing factors seem to include longer build times than previously with the PCH reduction, along with general performance variability.

We should probably just extend the timeout for now.

Build speed improvements for consumers will come with binary distribution, and we ideally want to ensure the actual application responsiveness doesn't go down, but we don't have great infrastructure for perf gates right now.

**Comment by NickGerleman** [comment]
Should be fixed by #6318 which seriously reduces the time taken by E2ETest since AppVerifier/PageHeap is no longer enabled by default.

**Comment by chrisglein** [comment]
@kmelmon Is there a path for how we get back AppVerifier coverage in tests? Definitely we need a reliable CI, that's important. But if we can have reliability _and_ AppVerifier that'd be better. Can we bring this back after we've done other work to our UI tests to not be so flakey.

**Comment by kmelmon** [comment]
I strongly suspect PageHeap is putting too much stress on the under-powered VMs we're currently using, as we're seeing that the tests are not having this issue on dev boxes.  Once we get the better hardware up and running we can try to re-enable.
