### ISSUE TITLE
Expose AsyncStorage Module in Rex

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#6316]
RNTester has been adding more dependencies to AsyncStorage. We've been patching around it in the react-native-win32 variant of RNTester. We should change Rex to include the builtin module instead.

**Comment by chrisglein** [comment]
AsyncStorage is supposed to be deprecated, or at least heading that direction (it's moved out to a community module). Why are there new instances of usage of AsyncStorage in core? @NickGerleman can you add links to commits that are expanding usage here? We should discuss why that's going the wrong direction. It'd be good to be clear on whether that is indeed the long term plan.

Decision here seems to be around whether we're correct to keep patching around (assuming it's going away) or if there needs to be an implementation.
