### ISSUE TITLE
Update E2ETest to Launch RNTester Example Via Linking Instead of UI Manipulation

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#6319]
RNTester supports launching an example via LinkingModule/Linking. Instead of using this, we currently manipulate the testesr UI to get to the page we want. This has a few issues:

- After the RNTester redesign, we will go to the last seem example on launch, which breaks tests. We get around that by clearing local storage before launching RNTester for now
- We need to update E2ETest if the overall RNTester UI changes
- The process to go from one page to another is pretty slow

These are mitigated by using linking to tell RNTester to go directly to the page.

**Comment by NickGerleman** [comment]
We could theoeretically do this out of process, but it might be kind of tricky. Seems like it could solve some of the reliability issues we've been seeing though.

**Comment by NickGerleman** [comment]
Upstream end to end tests seem to launch by UI manipulation, so I'm not sure what is using the URI functionality for launching. 

I'm not sure our activation story is quite good enough for this yet. Going to close this, but try to keep this in mind if we see more reliability issues.

**Comment by asklar** [comment]
Clearing local storage is breaking collection of visual tree dumps, since those are stored in local storage. #6684
