### ISSUE TITLE
Cannot initialize native modules constants that depend on UI thread

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#6339]
@chiaramooney is working on implementing the device orientation community module. As part of that she needs to expose a constant that expresses the device orientation at the time the app first started.
The native module is created on the JS thread, not the UI thread, and at that time there is yet no current window object either.
The RNW core DeviceInfoModule gets around this by exposing a constants provider that delegates to a DeviceInfoHolder object, and the RNW core has special logic to initialize this DeviceInfoHolder object on the UI thread.
However it is unclear whether this kind of functionality is available to community modules without requiring changes to the React instance initialization:

https://github.com/microsoft/react-native-windows/blob/034770c8c764ecd97c28d69296eca6f49ce729d2/vnext/Microsoft.ReactNative/ReactHost/ReactInstanceWin.cpp#L260-L273

**Comment by asklar** [comment]
this might be doable via REACT_INIT to capture a ReactContext, then using a REACT_CONSTANTS_PROVIDER to delay initialize constants, and finally using the context's UIDispatcher to post some work to fetch the values and wait for the results to come back.
If this works, we should document it (we don't document REACT_INIT today for example)

**Comment by chiaramooney** [comment]
Orientation locker now implemented. Closing for now. Can be reopened if additional functionality needed.
