### ISSUE TITLE
Is it possible to call LinkingManagerModule::OpenUri from App.xaml.cs?

### ISSUE THREAD

**Issue by ryfow** [microsoft/react-native-windows#6347]
I'd like my application to be able to do command line arguments. It seems reasonable to pass information to JS via LinkingManagerModule but I don't know how to access it from App.xaml.cs.

Thanks!
Ryan

**Comment by tero-paananen** [comment]
It seems that rn windows calls it automatically in `ReactApplication::OnActivated`  

```
void ReactApplication::OnActivated(IActivatedEventArgs const &e) {
  if (e.Kind() == ActivationKind::Protocol) {
    auto protocolActivatedEventArgs{e.as<ProtocolActivatedEventArgs>()};
    react::uwp::LinkingManagerModule::OpenUri(protocolActivatedEventArgs.Uri());
    this->OnCreate(e);
  }
}
```

**Comment by ryfow** [comment]
Yeah, it does that on protocol activation. It doesn't on command line activation.

**Comment by chrisglein** [comment]
How are you running your UWP app with command line arguments? Are you getting them in your OnActivated? Once you have them there you can write a native module capture that and bring it to JS. You can look into the implementation of OpenUri to see how that forwards to the JS - there shouldn't be much magic there. 

If you're dealing with how to get arguments to a UWP app from a Win32 app [here's how to do that](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-iapplicationactivationmanager-activateapplication).

**Comment by ryfow** [comment]
Thanks @chrisglein,

Yeah, I'm getting them in OnActivated.

Looks like a `[ReactEvent("url")]` might work.

Is there a good way to get a handle on the Module from App.xaml.cs?

**Comment by asklar** [comment]
LinkingModule doesn't seem like part of the public API on the native side, which seems like a bug on the RNW side.
ReactNotificationService should be able to achieve this but we haven't documented it yet, _but_ there are some samples in this issue: https://github.com/microsoft/react-native-windows-samples/issues/198
