### ISSUE TITLE
Desktop apps support

### ISSUE THREAD

**Issue by annavar** [microsoft/react-native-windows#6351]
Hi,

we are highly interested in using React Native for our Windows applications, but all our apps are classic Win32 applications, not to mention that some features require elevated execution. However, as far as I can see, React Native supports only UWP projects. Are you going to introduce support for Desktop apps? Option when using XAML islands to host the React Native Windows content isn't appropriate because our apps usually have complex UI and logic.

**Comment by asklar** [comment]
@annavar could you clarify your last statement around xaml islands "isn't being appropriate because our apps usually have complex UI and logic"? are there any specific issues that are blocking you from using it?
