### ISSUE TITLE
Components under "display: none" still participate in focus, UIA, etc

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#6355]
RNW will pass the "display: none" property to Yoga for layout, but doesn't take it into consideration for XAML visibility. This means we create the same XAML tree as normal, but elements are hidden by virtue of being sized as (0,0).

Because of this, components under "display: none" still participate in UIA, focus, or other bits that they likely shouldn't. @kmelmon mentioned this also defeats certain XAML perf optimizations. Concretely, this causes issues with RNTester refactoring, leading to multiple UIA elements with the same automation ID to be displayed at once.

We should propagate this to the XAML tree (maybe just mark the tree as collapsed?).

**Comment by acoates-ms** [comment]
+1 Sounds like we should set Visibility=Hidden when display: none.
