### ISSUE TITLE
Update E2E test infrastructure from update to WinAppDriver 1.2

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#6393]
We are about to update the MSFT hosted agents to install WinAppDriver 1.2.  This is a breaking change for our E2E tests as the version of WinAppDriver is tightly coupled with Appium and WebDriverIO.

We are also in the process of moving our entire CI loop to better hardware and VMs that we control.  We should install version 1.2 on these VMs as well.  See https://github.com/microsoft/react-native-windows/issues/6226

This task is tracking changing our E2E test infrastructure to use the matching versions of Appium and WebDriverIO to use WinAppDriver 1.2.  It may also require some additional work in the tests themselves or surrounding code.

**Comment by NickGerleman** [comment]
appium-windows-driver needs to be updated for any new release of WinAppDriver it looks like. I.e. the package will need to be updated before we're able to use the installed verison of WinAppDriver. https://github.com/appium/appium-windows-driver/blob/master/lib/installer.js

Going to try to install WinApppDriver 1.1 on CI machines until we have a change to get real working packages.

**Comment by NickGerleman** [comment]
Fixed with CanHua's changes.
