### ISSUE TITLE
microsoft-reactnative-sampleapps package fails to build - Folly directory does not resolve generating visual studio build errors

### ISSUE THREAD

**Issue by chrisfromwork** [microsoft/react-native-windows#6416]
## Environment
1. `npx react-native --version`: 4.13.0
2. `npx react-native info`:
System:
    OS: Windows 10 10.0.19042
    CPU: (36) x64 Intel(R) Core(TM) i9-10980XE CPU @ 3.00GHz
    Memory: 48.65 GB / 63.80 GB
  Binaries:
    Node: 12.18.2 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.1
      Android NDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0
  IDEs:
    Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6626763
    Visual Studio: 16.7.30611.23 (Visual Studio Enterprise 2019)
  Languages:
    Java: Not Found
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
    react-native-windows: 0.63.6 => 0.63.6
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Checkout 0.63-stable branch
2. Run `npm install` in react-native-windows\packages\microsoft-reactnative-sampleapps
3. Run `npm run windows` in react-native-windows\packages\microsoft-react-native-sampleapps
4. I see the following:
D√ Auto-linking...rk\react-native-windows\packages\microsoft-reactnative-sampleapps>npm run windows
Success: No auto-linking changes necessary. (92ms)
 √ Found MSBuild v16.0 at C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin (16.7.30611.23)
 \ Restoring NuGet packages - Failed to restore the NuGet packages: Error: D:\git\chrisfromwork\react-native-windows\vnext\Directory.Build.props(54,5): error MSB4184: The expression "[MSB × Failed to restore the NuGet packages: Error: D:\git\chrisfromwork\react-native-windows\vnext\Directory.Build.props(54,5): error MSB4184: The expression "[MSBuild]::NormalizeDirectory('')" cannot be evaluated. Parameter "path" cannot have zero length. [D:\git\chrisfromwork\react-native-windows\vnext\Microsoft.ReactNative.Managed\Microsoft.ReactNative.Managed.csproj]
D:\git\chrisfromwork\react-native-windows\vnext\Directory.Build.props(54,5): error MSB4184: The expression "[MSBuild]::NormalizeDirectory('')" cannot be evaluated. Parameter "path" cannot have zero length. [D:\git\chrisfromwork\react-native-windows\vnext\Microsoft.ReactNative.Managed.CodeGen\Microsoft.ReactNative.Managed.CodeGen.csproj]
D:\git\chrisfromwork\react-native-windows\vnext\Directory.Build.props(54,5): error MSB4184: The expression "[MSBuild]::NormalizeDirectory('')" cannot be evaluated. Parameter "path" cannot have zero length. [D:\git\chrisfromwork\react-native-windows\vnext\Folly\Folly.vcxproj]
D:\git\chrisfromwork\react-native-windows\vnext\Directory.Build.props(54,5): error MSB4184: The expression "[MSBuild]::NormalizeDirectory('')" cannot be evaluated. Parameter "path" cannot have zero length. [D:\git\chrisfromwork\react-native-windows\vnext\ReactCommon\ReactCommon.vcxproj]
D:\git\chrisfromwork\react-native-windows\vnext\Directory.Build.props(54,5): error MSB4184: The expression "[MSBuild]::NormalizeDirectory('')" cannot be evaluated. Parameter "path" cannot have zero length. [D:\git\chrisfromwork\react-native-windows\vnext\Microsoft.ReactNative\Microsoft.ReactNative.vcxproj]
D:\git\chrisfromwork\react-native-windows\vnext\Directory.Build.props(54,5): error MSB4184: The expression "[MSBuild]::NormalizeDirectory('')" cannot be evaluated. Parameter "path" cannot have zero length. [D:\git\chrisfromwork\react-native-windows\vnext\JSI\Universal\JSI.Universal.vcxproj]
D:\git\chrisfromwork\react-native-windows\vnext\Directory.Build.props(54,5): error MSB4184: The expression "[MSBuild]::NormalizeDirectory('')" cannot be evaluated. Parameter "path" cannot have zero length. [D:\git\chrisfromwork\react-native-windows\vnext\Common\Common.vcxproj]

Re-run the command with --logging for more information
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! microsoft-reactnative-sampleapps@0.0.54 windows: `react-native run-windows`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the microsoft-reactnative-sampleapps@0.0.54 windows script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\chriba\AppData\Roaming\npm-cache\_logs\2020-11-03T17_22_14_791Z-debug.log

## Expected Results
The application builds successfully or there should be documentation calling out the correct steps for building and running the samples (I am likely doing something incorrectly with setup).

## Snack, code example, screenshot, or link to a repository:
This should repro in a fresh clone of the react-native-windows repo.

**Comment by acoates-ms** [comment]
The react-native-windows repo is a yarn workspace repo, so you need to use `yarn` to install the dependencies.  Then `yarn build` to build the `react-native-windows` package before you can build the sampleapps package.

**Comment by chrisfromwork** [comment]
Thanks @acoates-ms !
