### ISSUE TITLE
AsyncStorage data persistance between app runs

### ISSUE THREAD

**Issue by capc0** [microsoft/react-native-windows#6418]
I just opened an issue regarding AsyncStorage an windows https://github.com/react-native-async-storage/async-storage/issues/482

The problem: between runs of my windows app with ```react-native run-windows``` all stored data is lost.
Could this be a behaviour because of some OS paths/folders are re-created when the CLI starts or builds the windows project?

Has someone AsyncStorage working with data persistance between app runs or can recommend another approach for doing that?

**Comment by asklar** [comment]
My hunch is that nothing is calling `sqlite3_close`. This method is called when encountering an error or when destroying the `DBStorage` object, but it's possible that when you're closing the app, the destructor for the DBStorage which is part of the native module, isn't running. The native module doesn't seem to expose the ability to flush and close the storage programmatically, so it seems like it expects all operations to be flushed to disk asap. @chrisglein  FYI.

**Comment by capc0** [comment]
can I inspect the sqlite DB in AppData or somewhere else on the filesystem to check that?

**Comment by asklar** [comment]
from looking at the code it looks like the db is stored in %localappdata%\Packages\pfn\LocalState
where pfn is the Package ID and publisher ID. You can see these properties if you open the Package.appxmanifest file and navigate to the Packaging tab:
![image](https://user-images.githubusercontent.com/22989529/98031965-25d03980-1dc8-11eb-8b1d-95b8c5e6303f.png)

**Comment by exotexot** [comment]
The .db file is stored at:
C:\Users\USERNAME\AppData\Local\Packages\PACKAGE_FAMILY_NAME\LocalState

**Comment by capc0** [comment]
Ok so what happens is that the folder ```C:\Users\USERNAME\AppData\Local\Packages\PACKAGE_FAMILY_NAME``` gets completly deleted and re-created whenever i restart via ```react-native run-windows```.

@exotexot are you using another start script? im using the c++ (default) setup btw.

**Comment by exotexot** [comment]
I was using c++ setup but recently switched to c# and never observed this behaviour tbh.

**Comment by exotexot** [comment]
One thing you should test: try using 1.12.x version. Since version 1.13 they've added some mechanism re which affects the persistance of the AsyncStorage. What seems weird to me is your report, that the entire LocalState folder is being deleted?

Also: as I'm using 0.62.x i'm not auto-linking but manually linking my modules and build through Visual Studio and not the terminal.

**Comment by capc0** [comment]
The folder with the "package family name" (uuid string) is being deleted, so even one level higher than LocalState.
I could imagine auto-linking being responsible for such behaviour.

**Comment by exotexot** [comment]
Not sure. Linking native modules just "links" native code to functions you call from the js side of things. Every app has its own architecture and folder-structure. In case you want to explore that you can take a look at react-native-fs which provides you access to the filesystem. In those folders you can store e.g. downloaded data.

**Comment by asklar** [comment]
ah ok that makes sense because react-native run-windows will uninstall the app before installing the new version - which will delete the local state.

**Comment by capc0** [comment]
ok thats a bit annoying for development but should have no effect in production than

**Comment by asklar** [comment]
right. Note that it might still be an issue when upgrading the app, so you might want to ensure that data is somehow persisted outside the app's store (e.g. uploading it to the cloud)

**Comment by capc0** [comment]
If I build once and then start the app via the .sln and hitting run (F5), the data will not be lost. Is there a CLI command to invoke the same functionality (run without rebuilding)? 

I guess that would be sufficient enough to deal workaround this issue.

**Comment by asklar** [comment]
@capc0 `run-windows` can take some options e.g. `--no-build` to skip building, `--no-deploy` to skip deploying, etc.
 However when you want to try new changes to native code you need to build and deploy, and the current implementation of deploy doesn't have a way to skip uninstalling the app.
@svetbonev @srdjanj FYI

**Comment by exotexot** [comment]
@asklar does that really mean the entire appfamily directory is being deleted after an app update? Even in release mode? In my app users store large binary data in their documents directory (localstate) and it would be really weird to lose all of this during an app update

**Comment by asklar** [comment]
@exotexot looks like the localstate folder is preserved across app updates - but it gets blown away by uninstalls (which run-windows does). So app updates should be ok. More info here: https://blogs.windows.com/windowsdeveloper/2016/05/10/getting-started-storing-app-data-locally/
