### ISSUE TITLE
Calling base.OnActivated(e) on second activation when app is already running causes crash 

### ISSUE THREAD

**Issue by sureshsvmx** [microsoft/react-native-windows#6435]
> ## Description
> Our app is being deployed to the Xbox console and is using a C# UWP host. We require to protocol activate our app, and be made aware of the activation from the JS so that we can reset state and route appropriately. If we register a protocol, override the OnActivated lifecycle method, and call 'base.OnActivated()', everything seems to work fine. In the JS, we are using Linking in order to get the initial url that activated the app as well as its event listener if we are activated again. However, if the app is already running and we protocol again, we seem to hit an access violation in ReactNative.dll. This appears to happen only if 'base.OnActivated()' is called on the second activation. If we do not call that, no AV occurs, but then the Linking event listener is not triggered and the Linking.getInitialUrl() only returns the first protocol url, not the second, even if the JS app is renavigated/reinitialized. Unsure of best way to get the url from the second activation.
> ![OnActivatedException](https://user-images.githubusercontent.com/73371242/97064822-c9665200-155d-11eb-8052-fb16608c5c85.png)
> ![OnActivatedSample](https://user-images.githubusercontent.com/73371242/97064823-c9665200-155d-11eb-8db8-5e326f878506.png)
> 
> ## React Native version:
> react-native@0.63.3
> react-native-windows@0.63.5
> 
> ## Steps To Reproduce
> Provide a detailed list of steps that reproduce the issue.
> 
> 1. Register a protocol with the app in the appxmanifest file
> 2. In the App.xaml.cs, override the OnActivated lifecycle function
> 3. Within the OnActivated method, call 'base.OnActivated(e)'. If the protocol is the first time launching the app, this works fine. However if the app is already running, calling 'base.OnActivated(e)' causes an access violation in Microsoft.ReactNative.dll
> 
> ## Expected Results
> Console app is allowed to protocol a second time, and the 'Linking.addEventListener('url', handler)' is made aware of the second activation

**Comment by chrisglein** [comment]
There may be some issues with protocol activation as we don't have test coverage here. With protocol activation you'll go through a path where your already active app gets called here and it seems like there's a problem.

Let's get someone to look at this by just adding protocol activation to an empty app and see if this repros. Then we can walk back to see if there's something specific about this app versus just broken overall.

**Comment by asklar** [comment]
This is being hit by XBOX team (@mattlop1342) who filed this bug in the facebook RN github:
https://github.com/facebook/react-native/issues/30238

>   Currently, we are working around this bug by having the C# hosting app restart if it detects a second activation.
    We pass the activationUrl to the restart, so that after the restart when the OnLauched lifecycle hook is called, it has url on e.Parameters

CC @chrisglein FYI

**Comment by asklar** [comment]
I'm seeing something different. The app doesn't crash - it seems to be getting killed by the shell.
I attached a debugger to the app, and when the 2nd activation happens, both the app and the debugger are closed and the app is relaunched.
So... I'm not seeing the same behavior. If you can repro this with what we have in master and you can provide a repro app I'd be happy to take a look at it
