### ISSUE TITLE
Calling Navigate in onActivated.

### ISSUE THREAD

**Issue by sureshsvmx** [microsoft/react-native-windows#6436]
**Just wanted to know is there any specific way to reload the RNW app.** 

We tried Host.ReloadInstance() by calling NativeModules which crashes the app frequently even when the app is active in foreground .

and we  tried the like below which leads to multiple frame. Please can you explain why we see multiple frames.Does caching happens and when we do _Frame.Navigate() does RNW loads the cached page and current page

var _Frame = Window.Current.Content as Windows.UI.Xaml.Controls.Frame;
            _Frame.Navigate(_Frame.Content.GetType());
            _Frame.GoBack();

**Comment by chrisglein** [comment]
Having a hard time understanding what your question is here. The code in question doesn't look like RNW, but rather the C# UWP code. Was there something specific about React Native in your question? Can you provide more context?

**Comment by sureshsvmx** [comment]
ust wanted to know is there any specific way to reload the RNW app.

We tried Host.ReloadInstance() by calling NativeModules which crashes the app frequently even when the app is active in foreground .

and we tried the like below which leads to multiple frame. Please can you explain why we see multiple frames.Does caching happens and when we do _Frame.Navigate() does RNW loads the cached page and current page

var _Frame = Window.Current.Content as Windows.UI.Xaml.Controls.Frame;
_Frame.Navigate(_Frame.Content.GetType());
_Frame.GoBack();

**Comment by asklar** [comment]
Can you also share more information about the crash that you are seeing? It's still unclear what you mean by multiple frames, out of the box we only ever create one window.
