### ISSUE TITLE
AppInsights Outputs to stderr for react-native commands When Network Flaky or Unavailable

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#6456]
Showed up during CI when running `react-native bundle` https://dev.azure.com/ms/react-native-windows/_build/results?buildId=121398&view=logs&j=2aef21c9-0610-5c30-26c1-4f046de16038&s=d654deb9-056d-50a2-1717-90c08683d50a&t=93f898e5-507a-5eb1-f73b-c0c953f43c13&l=11471

It looks like telemetry client init does network operations and will take things down and error out if it fails. Since this is done in telemetry setup, it's likely this also happens with the no-telemetry option.

```
MakeTestBundles:
  Creating directory "D:\a\1\s\\vnext\\target\x86\Debug\React.Windows.Desktop.ABITests\".
  npx --no-install react-native bundle --platform windows --entry-file D:\a\1\s\vnext\Microsoft.ReactNative.IntegrationTests\AddValues.js --bundle-output D:\a\1\s\\vnext\\target\x86\Debug\React.Windows.Desktop.ABITests\AddValues.bundle
                   Welcome to React Native!
                  Learn once, write anywhere
  
  
  ApplicationInsights:CorrelationIdManager [
##[error]EXEC(0,0): Error : getaddrinfo ENOTFOUND dc.services.visualstudio.com
EXEC : error : getaddrinfo ENOTFOUND dc.services.visualstudio.com [D:\a\1\s\vnext\Desktop.ABITests\React.Windows.Desktop.ABITests.vcxproj]
        at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
      errno: 'ENOTFOUND',
      code: 'ENOTFOUND',
      syscall: 'getaddrinfo',
      hostname: 'dc.services.visualstudio.com'
    }
  ]
  info Writing bundle output to:, D:\a\1\s\\vnext\\target\x86\Debug\React.Windows.Desktop.ABITests\AddValues.bundle
  info Done writing bundle output
  warn Assets destination folder is not set, skipping...
##[error]vnext\Microsoft.ReactNative.IntegrationTests\TestBundle.targets(9,3): Error MSB3073: The command "npx --no-install react-native bundle --platform windows --entry-file D:\a\1\s\vnext\Microsoft.ReactNative.IntegrationTests\AddValues.js --bundle-output D:\a\1\s\\vnext\\target\x86\Debug\React.Windows.Desktop.ABITests\AddValues.bundle" exited with code -1.


```

**Comment by NickGerleman** [comment]
I can't actually tell if this is throwing or erroring out the process in a different way, but the command is failing.

**Comment by NickGerleman** [comment]
Pausing our publish pipeline since this was backported to 0.63 but hasn't been published yet. Seems like there is the potential for a bad regression or unintentional telemetry as-is.

**Comment by NickGerleman** [comment]
Code in the appinsights SDK creating the error is at https://github.com/microsoft/ApplicationInsights-node.js/blob/162d73176bae9927e73996df5cc0139102fab9f5/Library/CorrelationIdManager.ts#L79-L85

AppInsights seems to print out any of its internal warnings.

It's likely we're calling into this because we setup appinsights if anything requires @react-native-windows/telemetry, which will be included indirectly for all react-native commands.

I'm unsure why the warning is also setting a failing exit code. It seems like that may happen more indirectly.

**Comment by NickGerleman** [comment]
Easy repro is to just go offline and use run-windows or most other react-native commands.

**Comment by NickGerleman** [comment]
Impact is more scoped. Looks like failing commands is limited to generating release bundles in MSBuild, which will detect stderr and log a misleading message about error code.

**Comment by asklar** [comment]
PR is out for suppressing the error, following up on possibly delaying initialization of AI.
