### ISSUE TITLE
Kill girls/women

### ISSUE THREAD

**Issue by ReverentOne** [microsoft/react-native-windows#6461]
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`:
2. `npx react-native info`:

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.
2.

## Expected Results
Describe what you expected to happen.

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by JunielKatarn** [comment]
Spam.

Closing.
