### ISSUE TITLE
How to deal with NM breaking changes

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#6468]
Meta-point: we have breaking changes for NM across releases (C# for 0.63, e.g.). How do we deal with keeping community modules working despite breaking changes in the platform? 
Breaking changes in Native Modules should have a higher bar than other breaking changes. 
Do we need to make the breaking change now at all?

_Originally posted by @asklar in https://github.com/microsoft/react-native-windows/issues/6444#issuecomment-724225605_

**Comment by vmoroz** [comment]
Closing as not actionable.
