### ISSUE TITLE
C++/WinRT based apps are unable to consume C# native modules that contain nuget dependencies

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#6470]
This repros in RNW 0.62, 0.63, and seems to be a problem with Visual Studio and/or the C++/WinRT toolchain.

I am attempting to write a [C#-based windows implementation for Lottie React Native](https://github.com/lottie-react-native/lottie-react-native/pull/692). The module has a dependency on the C# library [LottieWindows](https://github.com/windows-toolkit/Lottie-Windows), via its [nuget package](https://www.nuget.org/packages/Microsoft.Toolkit.Uwp.UI.Lottie/).

I've found that C++/WinRT based RNW apps will not correctly package the application and will therefore crash at runtime. The C# binaries for LottieWindows will not be included in the application package in either Debug or Release mode (ie, with/without .Net Native). Therefore the app will crash at runtime when it attempts to call into LottieWindows.

i.e.: C++ App consuming C# Module consuming C# nuget does not work.

Note that this *not* fixed by the `<ConsumeCSharpModules>true</ConsumeCSharpModules>` workaround support we added to 0.63 and backported to 0.62. That is necessary to enable C++ App consuming C# Module, but has no impact on making sure the transitive dependency is included.

I have tried multiple workaround with no impact. Manually copying the missing binary files into the package causes mismatch manifest errors and the app won't start. Adding the C# nuget as a direct dependency of the C++ app does not work either.

Edit: I've confirmed that this makes no difference if the nuget is C# or C++, all transitive nugets will not be packaged with the C++ app

**Comment by jonthysell** [comment]
The symptoms are similar to #5639, however that case is for C++ nugets consumed by C++ libraries, and only repros when building with `run-windows`.

**Comment by jonthysell** [comment]
Updating to reflect that C++ app + C# module that consumes C++ nuget also does not work.

**Comment by asklar** [comment]
If we can't find a fix let's document this
