### ISSUE TITLE
Exclude other CIs from telemetry

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#6477]
We should figure out a way to exclude CircleCI and Travis from telemetry collection

**Comment by NickGerleman** [comment]
This could also be interesting to capture, and just make sure whatever query included/excluded it.

E.g. measuring build success rate of 3p CI

**Comment by asklar** [comment]
we're not currently budgeted to capture _all_ telemetry so we have to make sure we are capturing the minimal set of data required to answer the existing business questions: are customers hitting issues creating projects and building them on their dev machines?
