### ISSUE TITLE
Evaluate telemetry costs and changing the "disable in CI" to "log and tag as CI"

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#6479]
Once we've had enough data we'll want to figure out cost for a month and then we can reevaluate changing the "disable" to "log and tag as CI"

_Originally posted by @asklar in https://github.com/microsoft/react-native-windows/pull/6478#discussion_r520829110_

**Comment by jonthysell** [comment]
As we explore 1DS onboarding, the details of this task may change slightly.

**Comment by jonthysell** [comment]
We will need to find our from 1DS if this is something we need to worry about or not.

**Comment by danielayala94** [comment]
Telemetry costs are not a concern. One requirement to obtain a 1DS instrumentation key was to specify an estimated telemetry volume, so Cosmos/Asimov folks could do appropriate budgeting. The onboarding process was approved without costing concerns on the volume expectations.
