### ISSUE TITLE
Lage prints non-printable characters on the console

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#6480]
#6454 moved us from Lerna to Lage. It looks like there is some control character or something that's being printed wrongly to the console on Windows:

![image](https://user-images.githubusercontent.com/22989529/98726896-f97a6700-234b-11eb-8cbd-0f82c3a4c4ce.png)

**Comment by acoates-ms** [comment]
If you use the new windows terminal it will work fine.  -- Sadly this happens with a lot of JS tools that assume a wider range of supported characters from the terminal.
We should probably file a bug on the lage repo that it should fall back to using less fancy text when on legacy windows consoles.

**Comment by asklar** [comment]
sadly I can't use the new windows terminal since it hasn't yet implemented lots of keyboard navigation that are native to conhost

**Comment by NickGerleman** [comment]
The characters are some emojis that reflect the text to the right. This is confusing/annoying but no real functional impact.
