### ISSUE TITLE
AppState.currentState is always returning undefined in RNW 0.63.6

### ISSUE THREAD

**Issue by shanelile** [microsoft/react-native-windows#6482]
My team is trying to upgrade to RNW 0.63, and I've noticed what looks like a regression in a component that relies on AppState from react-native, where AppState.currentState is always returning undefined.

Digging into the code, it looks like a possible regression from updating \node_modules\react-native-windows\Microsoft.ReactNative\Modules\AppStateModule.cpp - GetCurrentAppState returns a plain string, either "active" or "background". However, node_modules\react-native-windows\Libraries\AppState\AppState.js attempts to compare its currentState value to appStateData.app_state, which is not a valid field to reference.

**Comment by NickGerleman** [comment]
It does look like we changed the event shape in https://github.com/microsoft/react-native-windows/pull/4991 (FYI @acoates-ms). Seems like this should be simple to fix, and add an integration test for to make sure the JS library interacts correctly with our module.
