### ISSUE TITLE
Consider using MsBuilds support to restore packages during the build (even for packages.config)

### ISSUE THREAD

**Issue by dannyvv** [microsoft/react-native-windows#6505]
MsBuild+Nuget claim to now support package restore during the build not only for <PackageReferences> but also for packages.config projects...

This issue is to track investigating if it works and if we can use it.
* Use it for our selfhost build in PR & CI
* Update react-native-windows-cli to not have a custom nuget version to restore, but use the msbuild target.

The behavior is documneted in https://github.com/NuGet/docs.microsoft.com-nuget/issues/1944

**Comment by NickGerleman** [comment]
Ooh yes, we should definitely do that if it's officially supported.
