### ISSUE TITLE
[Breaking change] .net framework in ADO is .net core 5

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#6511]
https://github.com/actions/virtual-environments/issues/1891

**Comment by asklar** [comment]
This will likely affect all of our supported versions when it happens.
Need to understand how to ask for a specific version of .net core (for the managed codegen project) and whether .net UWP is affected.

**Comment by JunielKatarn** [comment]
@asklar I believe this task should solve the issue:
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops

It allows setting a specific .NET core version to use in the pipeline.
