### ISSUE TITLE
Plan for ADO/VS releases

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#6515]
For the last few months, every time VS releases a new version or ADO updates the CI image, we end up putting out fires for a few days. We should figure out a way to reduce stress and do this in a more planful manner.

**Comment by chrisglein** [comment]
Agreed this is a pain point. We need to track when releases are coming, get early warning by doing self host of that prior to full release. Essentially avoid fire drills by knowing that the fire is coming :)
However we can't really capture that as an issue on the repo effectively, as we're handling planning externally. I'll take this as a topic for how to integrate into planning.

**Comment by chrisglein** [comment]
We've filed some work internally for this.
