### ISSUE TITLE
Unable to build new native module library due to CodeGen problem

### ISSUE THREAD

**Issue by getuliovdmnaweb** [microsoft/react-native-windows#6516]
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`: 4.13.0
2. `npx react-native info`:
![image](https://user-images.githubusercontent.com/65790521/99064555-de466c00-2584-11eb-8453-77323c8759f2.png)

- SDK version : 10.0.18363.1198

- Target Platform Version(s):
Desktop

- Target Device(s):
Visual Studio 2019

- Visual Studio Version:
Debug

- Build Configuration:
-->x64

## Steps To Reproduce

1. Follow the instructions on https://microsoft.github.io/react-native-windows/docs/native-modules-setup#creating-a-new-native-module-library-project, to create new native module library.

2. Try to Build It

## Expected Results
Building the project should succeed, instead this is the result:

![CodeGenerror](https://user-images.githubusercontent.com/65790521/99067068-cc66c800-2588-11eb-95db-4446fd7b183f.png)

## link to a repository:
https://github.com/getuliovdmnaweb/MyLibrary

**Comment by NickGerleman** [comment]
@jonthysell @dannyvv does this look familiar?

**Comment by asklar** [comment]
@getuliovdmnaweb : I was able to get things to build with this change:

```diff
namespace MyLibrary
{
-    public sealed class ReactPackageProvider : IReactPackageProvider
+    public sealed partial class ReactPackageProvider : IReactPackageProvider
    {
        public void CreatePackage(IReactPackageBuilder packageBuilder)
        {
            packageBuilder.AddAttributedModules();
        }

+        partial void CreatePackageImplementation(IReactPackageBuilder p);
    }
}
```

**Comment by tarasvakulka** [comment]
> ## Environment
> Run the following in your terminal and copy the results here.
> 
> 1. `npx react-native --version`: 4.13.0
> 2. `npx react-native info`:
>    ![image](https://user-images.githubusercontent.com/65790521/99064555-de466c00-2584-11eb-8453-77323c8759f2.png)
> 
> * SDK version : 10.0.18363.1198
> * Target Platform Version(s):
>   Desktop
> * Target Device(s):
>   Visual Studio 2019
> * Visual Studio Version:
>   Debug
> * Build Configuration:
>   -->x64
> 
> ## Steps To Reproduce
> 1. Follow the instructions on https://microsoft.github.io/react-native-windows/docs/native-modules-setup#creating-a-new-native-module-library-project, to create new native module library.
> 2. Try to Build It
> 
> ## Expected Results
> Building the project should succeed, instead this is the result:
> 
> ![CodeGenerror](https://user-images.githubusercontent.com/65790521/99067068-cc66c800-2588-11eb-95db-4446fd7b183f.png)
> 
> ## link to a repository:
> https://github.com/getuliovdmnaweb/MyLibrary

I have the same in project from scratch (https://microsoft.github.io/react-native-windows/docs/getting-started) when build in console, see screenshot ManagedCodGen.jpg. When build via VisualStudio all ok, but when app starting I got crash, see screenshot crashWhenStarting.jpg.

VisualStudio version - 16.8.1
npm version - 6.14.8
node versio - v14.15.1
![ManagedCodGen](https://user-images.githubusercontent.com/20745370/99318245-04635900-2870-11eb-9a00-804dc4fcae7d.jpg)
![crashWhenStarting](https://user-images.githubusercontent.com/20745370/99318252-075e4980-2870-11eb-9d4d-160e0c85f151.jpg)


Dependecies:
"dependencies": {
    "react": "16.13.1",
    "react-native": "0.63.2",
    "react-native-windows": "^0.63.0-0"
  },
  "devDependencies": {
    "@babel/core": "^7.8.4",
    "@babel/runtime": "^7.8.4",
    "@react-native-community/eslint-config": "^1.1.0",
    "babel-jest": "^25.1.0",
    "eslint": "^6.5.1",
    "jest": "^25.1.0",
    "metro-react-native-babel-preset": "^0.59.0",
    "react-test-renderer": "16.13.1"
  },

**Comment by tarasvakulka** [comment]
> @getuliovdmnaweb : I was able to get things to build with this change (which is present in the template, I'm curious if you may have undone this change locally or if we are creating the project wrongly on some older version...?)
> 
> ```diff
> namespace MyLibrary
> {
> -    public sealed class ReactPackageProvider : IReactPackageProvider
> +    public sealed partial class ReactPackageProvider : IReactPackageProvider
>     {
>         public void CreatePackage(IReactPackageBuilder packageBuilder)
>         {
>             packageBuilder.AddAttributedModules();
>         }
> 
> +        partial void CreatePackageImplementation(IReactPackageBuilder p);
>     }
> }
> ```

I have this changes, but still can't build app via console and get crash when app starting in build via VS see my message above.
![image](https://user-images.githubusercontent.com/20745370/99318402-4a202180-2870-11eb-89be-cc3206072f5c.png)

**Comment by asklar** [comment]
@tarasvakulka your issue seems unrelated to the issue being discussed here, please file a new issue.
