### ISSUE TITLE
Implement Per-Monitor (V2) DPI Awareness

### ISSUE THREAD

**Issue by exotexot** [microsoft/react-native-windows#6517]
Asking for support of https://docs.microsoft.com/en-us/windows/win32/hidpi/high-dpi-desktop-application-development-on-windows. Currently, React-native apps are running in Per-Monitor (v1) mode. You can see by opening task manager -> details tab > right click on table header: select columns -> check DPI awareness.  Here yourapp.exe reports runnin in per-monitor mode.

**Comment by asklar** [comment]
All UWP apps (including React Native for Windows apps) report being "Per monitor aware" but will scale properly on all displays
