### ISSUE TITLE
Changes in Monorepo Dependencies of react-native-windows not reflected in automated release notes

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#6523]
E.g. https://github.com/microsoft/react-native-windows/releases/tag/react-native-windows_v0.63.8 did not contain information from the bump in @react-native-windows/telemetry.

Beachball has support for version groups, which we opted not to use, that keep changelogs as one entity across monorepo packages. It looks like changes from bumped packages normally don't get propagated as changes to what they're bumping, which could be considered a bug in beachball, or by design.

**Comment by NickGerleman** [comment]
Response from Ken re changelog propagation:
> I would love to have changelog linking: something that tells users that a change caused subsequent changes and a link back to the original change

**Comment by asklar** [comment]
need to file beachball issue

**Comment by NickGerleman** [comment]
Fixed in Beachball 1.49.0 with https://github.com/microsoft/beachball/commit/3a2f081fd36cedc6124ba4253d8abac2e8a145b7
