### ISSUE TITLE
Support google-signin

### ISSUE THREAD

**Issue by petr7555** [microsoft/react-native-windows#6531]
# Support `google-signin` on RNW

## Basic Info
- Module Repo URL: [link to repo](https://github.com/react-native-google-signin/google-signin)
- Target version: v5.0.0

## Which app/customer is requesting this module?
- I am creating an app as my bachelors thesis and I need to authenticate users with Google to have the same identity on Android and Windows.

## In what scenarios will this module be used?
To authenticate users with Google to have the same identity on Android and Windows.

## Essential Features
Ability to log in with Google account.

**Comment by asklar** [comment]
CC @stmoy FYI

@petr7555 we'd love for you to add this support :)

**Comment by petr7555** [comment]
I am afraid I won't be able to implement this functionality. I have no experience with UWP programming.
Which of these two guides is the relevant one for implementing this? https://microsoft.github.io/react-native-windows/docs/native-modules or https://microsoft.github.io/react-native-windows/docs/native-modules-setup?

**Comment by chrisglein** [comment]
Closing this module request as not in plan. Not that this module _shouldn't_ receive a Windows implementation, but it makes more sense to track that request on the module's repo rather this repo.
