### ISSUE TITLE
App Store Validation failed due to HighVersionLie

### ISSUE THREAD

**Issue by DRAirey1** [microsoft/react-native-windows#6533]
I tried to publish my app.  Only thing to change was the version of Microsoft and a new certificate that I pulled down from the store.

## Environment
VIsual Studio 2019 - Version 16.8.1

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Upgrade to Visual Studio 2019 - Version 16.8.1
2. Open an existing VS solution that has previously published to the Windows Store
3. Recompile the package for production.
4. Select Publish -> Create App Package... 
5. Run the Validation Program

## Expected Results
I expect the validation to run to completion with no errors.

## Actual Results
FAILED Platform version launch
Error Found: The high OS version validation detected the following errors:
Task failed to enable HighVersionLie.
     Impact if not fixed: The app should not use version information to provide functionality that is specific to the OS.
     How to fix: Please use recommended methods to check for available functionality in the OS. See the link below for more information.

Operating System Version:
Windows 10

**Comment by asklar** [comment]
@DRAirey1 known issue affecting all Store apps, not just React Native for Windows apps. See #6331 - it should be ok to ignore the local failure and submit to the store anyways.

**Comment by DRAirey1** [comment]
Verified.  The error message in the Validation program on the PC doesn't seem to impact the ability to publish to the store.
