### ISSUE TITLE
Investigate using .net core 5 and cswinrt to target system XAML

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#6539]
There are a number of problems mixing C++ and C# with .net native (see main issue #6469).
Investigate whether it is possible to use .net core 5 and cswinrt in order to target system XAML, without requiring .net native-ization and assess what interop gaps between C++ and C#/netcore5 exist.

**Comment by sylveon** [comment]
I think the biggest issue here is that .NET 5 doesn't support UWP, see https://github.com/microsoft/ProjectReunion/issues/105
