### ISSUE TITLE
Usage of CornerRadius doesn't gracefully degrade and crashes app in RS4

### ISSUE THREAD

**Issue by tarasvakulka** [microsoft/react-native-windows#6544]
I created project from scratch (https://microsoft.github.io/react-native-windows/docs/getting-started). When build in console get error, see screenshot ManagedCodGen.jpg. When build via VisualStudio all ok, but when app starting I got crash, see screenshot crashWhenStarting.jpg. I tried delete node_modules and run yarn install again, but it didn't help.

![ManagedCodGen](https://user-images.githubusercontent.com/20745370/99366771-c0993f80-28c1-11eb-99b9-32baf5344f61.png)
![crashWhenStarted](https://user-images.githubusercontent.com/20745370/99366017-b4f94900-28c0-11eb-95fd-280f4b17c7cc.jpg)
![photo_2020-11-17 10 52 11](https://user-images.githubusercontent.com/20745370/99367707-fab71100-28c2-11eb-997a-10d3de1e5f8b.jpeg)

VisualStudio version - 16.8.1
npm version - 6.14.8
node version - v14.15.1
Dependecies:
"dependencies": {
"react": "16.13.1",
"react-native": "0.63.2",
"react-native-windows": "^0.63.0-0"
},
"devDependencies": {
"@babel/core": "^7.8.4",
"@babel/runtime": "^7.8.4",
"@react-native-community/eslint-config": "^1.1.0",
"babel-jest": "^25.1.0",
"eslint": "^6.5.1",
"jest": "^25.1.0",
"metro-react-native-babel-preset": "^0.59.0",
"react-test-renderer": "16.13.1"
},

**Comment by Frekansapp** [comment]
Same problem  @tarasvakulka  can you try with "react-native-windows": "^0.63.9" version

**Comment by tarasvakulka** [comment]
> Same problem @tarasvakulka can you try with "react-native-windows": "^0.63.9" version

I have 0.63.9 in my yarn.lock, but I will try to change my package.lock, I don't think it will help
![image](https://user-images.githubusercontent.com/20745370/99369072-a4e36880-28c4-11eb-8f13-be57374aac2f.png)

**Comment by tarasvakulka** [comment]
> Same problem @tarasvakulka can you try with "react-native-windows": "^0.63.9" version

I already had "react-native-windows": "^0.63.9" version, doesn't help

**Comment by tarasvakulka** [comment]
@asklar Could you please help?

**Comment by asklar** [comment]
A few things to check:
- Under node_modules there should be a nuget-exe folder with a nuget.exe in it. What version does it say it is when you run it?
- the version of react-native-windows in package.json should be 0.63.9. Try updating that and rerun yarn
- what does the error message translate to? Is there a crash? If so can you share the stack trace?
- what version of Windows are you running this on?
- see if the info here helps with the metro error: http://aka.ms/RNWTroubleshootMetro

**Comment by tarasvakulka** [comment]
> A few things to check:
> 
> * Under node_modules there should be a nuget-exe folder with a nuget.exe in it. What version does it say it is when you run it?
> * the version of react-native-windows in package.json should be 0.63.9. Try updating that and rerun yarn
> * what does the error message translate to? Is there a crash? If so can you share the stack trace?
> * what version of Windows are you running this on?
> * see if the info here helps with the metro error: http://aka.ms/RNWTroubleshootMetro

1) nuget-4.9.2
![image](https://user-images.githubusercontent.com/20745370/99403980-c3148d00-28f3-11eb-8ade-c5f5e629c290.png)
2) I have 0.63.9 in my yarn.lock, and also set in package json an reinstall node_modules but problem still remained
3) This screen shot describe my problem:
![image](https://user-images.githubusercontent.com/20745370/99405175-2357fe80-28f5-11eb-9668-c56de4ab4c11.png)
![image](https://user-images.githubusercontent.com/20745370/99405206-2d79fd00-28f5-11eb-87c3-39ea664d0cb5.png)
After I press ok in alert my app crash and close.
4) Windows version:
![image](https://user-images.githubusercontent.com/20745370/99405460-7631b600-28f5-11eb-83fa-04672274ad20.png)

**Comment by NickGerleman** [comment]
Beachball reverted the dependency change back from NuGet 5.8.0 to 4.9.2? https://github.com/microsoft/react-native-windows/commit/df6eabe87538b1afc78ff7958f063c028e5baec3#diff-7d7b3041526ba0af511bedc0cb371991e270eeb39a70c0d5bf86219a8cb1adf2

I'm not sure why it did this... This seems like a possible bug. Will take a look.

**Comment by tarasvakulka** [comment]
> Beachball reverted the dependency change back from NuGet 5.8.0 to 4.9.2? [df6eabe#diff-7d7b3041526ba0af511bedc0cb371991e270eeb39a70c0d5bf86219a8cb1adf2](https://github.com/microsoft/react-native-windows/commit/df6eabe87538b1afc78ff7958f063c028e5baec3#diff-7d7b3041526ba0af511bedc0cb371991e270eeb39a70c0d5bf86219a8cb1adf2)
> 
> I'm not sure why it did this... This seems like a possible bug. Will take a look.

Looking forward for fix. Thanks)

**Comment by NickGerleman** [comment]
What this means in practice is that the bug with VS 16.8 and run-windows was not fixed in 0.63.9 and will instead be fixed in 0.63.10. To mitigate that bug, you should be able to just use Visual Studio instead of `run-windows`.

The crash during start is interesting though, and a different issue. Do you have a callstack of what this looks like?

**Comment by tarasvakulka** [comment]
> What this means in practice is that the bug with VS 16.8 and run-windows was not fixed in 0.63.9 and will instead be fixed in 0.63.10. To mitigate that bug, you should be able to just use Visual Studio instead of `run-windows`.
> 
> The crash during start is interesting though, and a different issue. Do you have a callstack of what this looks like?

I have only this two screenshots, in VS studio I don't see any logs or a callstack, because app closing immdiatly after I press Cancel button on this alert.
![image](https://user-images.githubusercontent.com/20745370/99408429-e8f06080-28f8-11eb-9c14-c7db33be2583.png)
If I press ok it open new VS studio window and I see alert with error that debbuger couldn't connect and nothing logs or callstack.

And screenshot with metro bundler after app crash and close:
![Uploading image.png…]()

**Comment by asklar** [comment]
translation of the error message from russian (this took me a while...)
> A debugger is attached to, but not configured to debug this unhandled exception. to debug the exception, detach the current debugger

In VS, can you go into  Debug -> Debug properties -> Debugging and make sure either **Native** or **Native and Managed** is selected in Debugger Type? 
![image](https://user-images.githubusercontent.com/22989529/99413073-3d202400-28aa-11eb-981d-67aa4375655c.png)

**Comment by tarasvakulka** [comment]
> translation of the error message from russian (this took me a while...)
> 
> > A debugger is attached to, but not configured to debug this unhandled exception. to debug the exception, detach the current debugger
> 
> In VS, can you go into Debug -> Debug properties -> Debugging and make sure either **Native** or **Managed and Native** is selected in Debugger Type?
> ![image](https://user-images.githubusercontent.com/22989529/99413214-66d94b00-28aa-11eb-843e-59521f4907e8.png)

![image](https://user-images.githubusercontent.com/20745370/99420421-db8da300-2905-11eb-9e2f-e35355023253.png)
I have Managed only, this can cause the problem?

**Comment by asklar** [comment]
yes, if you hit a native exception, then debugging in "Managed only" mode will skip breaking when the exception is thrown and you will get the error you're getting.

**Comment by tarasvakulka** [comment]
> yes, if you hit a native exception, then debugging in "Managed only" mode will skip breaking when the exception is thrown and you will get the error you're getting.

I changed dubugger type to Managed and Native, and now I get 
![image](https://user-images.githubusercontent.com/20745370/99422413-31fbe100-2908-11eb-8dca-77b7f13f68a9.png)
![image](https://user-images.githubusercontent.com/20745370/99422573-5bb50800-2908-11eb-80dd-dd7ee31b34c1.png)

**Comment by asklar** [comment]
please share the callstack (see Call Stack window in your screenshot)

**Comment by tarasvakulka** [comment]
> please share the callstack (see Call Stack window in your screenshot)

![image](https://user-images.githubusercontent.com/20745370/99426661-0fb89200-290d-11eb-925f-ebeb28771f79.png)

I commented template code in App.js, and application stop crashing:
![image](https://user-images.githubusercontent.com/20745370/99426780-41c9f400-290d-11eb-9273-cd586ee0c356.png)

**Comment by asklar** [comment]
It's likely the default app relies on something that isn't available in Windows 10 1803 (RS4).

See the compatibility table here: https://microsoft.github.io/react-native-windows/docs/win10-compat

**Comment by NickGerleman** [comment]
I wonder if we have incompatibilities with 1803 and CornerRadius. It wouldn't be the first time we degraded badly on older versions of Windows 10.

**Comment by asklar** [comment]
Yes indeed, CornerRadius property only exists in 1809 and up:
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.control.cornerradius?#windows-10-requirements

**Comment by asklar** [comment]
Looks like this broke when I first ported RNW to WinUI3: https://github.com/microsoft/react-native-windows/pull/4766/files#diff-19cc4c16e8a69089b23a95a5c510ca4e1146678e5dd50b2a88a7c92825851faeL35-L36

**Comment by asklar** [comment]
thanks for reporting @tarasvakulka , I'll put out a change to address this

**Comment by tarasvakulka** [comment]
> thanks for reporting @tarasvakulka , I'll put out a change to address this

thank you too, looking forward to merging your pull request with fix

**Comment by tarasvakulka** [comment]
@asklar I changed react-native-windows to 0.63.10 in my package.json, then delete and reinstall node_modules, but get new error, when app start, this is empty app from scratch with default template:
![image](https://user-images.githubusercontent.com/20745370/99526351-d1ba7d00-29a3-11eb-8a43-5b788427d8b1.png)

**Comment by NickGerleman** [comment]
@tarasvakulka theres a separate issue where redbox errors aren't shown gracefully on older OS's (pre 19H1). So, if you see a Javascript exception when developing on am older OS, you will crash instead of seeing the error in-app. This is something we caught and fixed recently, but hasn't been brought back to 0.63. 

That issue shouldn't affect users running your app on an older OS, just dev experience on one.

It does mean you are seeing an exception from Javascript or the instance very early. So you see any output from the console window when this happens?

**Comment by tarasvakulka** [comment]
> @tarasvakulka theres a separate issue where redbox errors aren't shown gracefully on older OS's (pre 19H1). So, if you see a Javascript exception when developing on am older OS, you will crash instead of seeing the error in-app. This is something we caught and fixed recently, but hasn't been brought back to 0.63.
> 
> That issue shouldn't affect users running your app on an older OS, just dev experience on one.
> 
> It does mean you are seeing an exception from Javascript or the instance very early. So you see any output from the console window when this happens?

![image](https://user-images.githubusercontent.com/20745370/99533588-d0428200-29ae-11eb-81c1-c18d02218534.png)
![image](https://user-images.githubusercontent.com/20745370/99533641-df293480-29ae-11eb-833a-92a09ed321a2.png)

**Comment by tarasvakulka** [comment]
@NickGerleman Should I just update my Windows?

**Comment by NickGerleman** [comment]
@tarasvakulka upgrading would be a good idea if you can.

Newer versions of Windows get more testing, especially for dev experience. If you find any crashes for older versions we would love to know and fix them, but there will be a degraded experience using anything older than Windows 10 1903 (May 2019 update).
