### ISSUE TITLE
[Xaml Islands] Picker does not respect dark mode theme

### ISSUE THREAD

**Issue by lyahdav** [microsoft/react-native-windows#6554]
## Environment
1. `npx react-native --version`: 4.13.0
2. `npx react-native run-windows --info`:
```
  System:
    OS: Windows 10 10.0.19041
    CPU: (40) x64 Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz
    Memory: 157.00 GB / 190.60 GB
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.0-20190429.1820 - C:\open\fbsource\xplat\third-party\yarn\yarn.BAT
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
    Watchman: 20200724.030019 - C:\tools\watchman\watchman.EXE
  Installed UWP SDKs:
    10.0.18362.0
```
3. `reg query "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock"`
```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock
    AllowDevelopmentWithoutDevLicense    REG_DWORD    0x1
    AllowAllTrustedApps    REG_DWORD    0x1
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Use `Picker` inside a Xaml Islands app that sets Theme to dark mode via `rootElement.RequestedTheme(winrt::ElementTheme::Dark)`.

Note this is a Xaml Islands bug with `ComboBox`, not specific to RNW.

## Expected Results
Expected dropdown to render as dark mode, but it renders as light mode:
![image](https://user-images.githubusercontent.com/359157/99459476-031f4400-28e3-11eb-9a4d-e57b65693af6.png)

A hacky workaround is [here](https://github.com/microsoft/react-native-windows/compare/master...lyahdav:patch-4). I didn't want to PR it since I'm assuming there's a clearer solution. I tried using `VisualTreeHelper::GetOpenPopupsForXamlRoot` to update the RequestedTheme on the popup but it didn't help.

CC @asklar

**Comment by asklar** [comment]
Filed internal tracking bug. https://task.ms/30615440

**Comment by lyahdav** [comment]
Austin actually gave me an idea for a better fix, which I confirmed works. In the `Loaded `callback in my hacky workaround linked above you can run the following code:
```
		auto popups = VisualTreeHelper::GetOpenPopupsForXamlRoot(cb.XamlRoot());
		for (auto const& popup : popups)
		{
			popup.RequestedTheme(cb.ActualTheme());
			popup.Child().as<FrameworkElement>().RequestedTheme(cb.ActualTheme());
		}
```
It would be even cleaner if there was a way to get the popup corresponding to the ComboBox directly. This could lead to theme changing on unrelated popups.

**Comment by lyahdav** [comment]
Another minor optimization: in the code from my last comment, you don't need to set `RequestedTheme` on `popup`, just `popup.Child()`.

**Comment by rectified95** [comment]
Since I saw another issue today with the deprecated built-in Picker, I thought I'd comment here as well. 
Heads-up: I suggest you apply your workaround linked above - https://github.com/microsoft/react-native-windows/compare/master...lyahdav:patch-4 - to the community module, as this picker view manager will get removed from this repo in due course.

**Comment by asklar** [comment]
Closing this issue as it isn't blocking and there is an internal bug tracking
