### ISSUE TITLE
Unable to build SimpleHttpModule in C# Example in RNW documentation

### ISSUE THREAD

**Issue by getuliovdmnaweb** [microsoft/react-native-windows#6563]
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`: 4.13.0
2. `npx react-native info`:
![image](https://user-images.githubusercontent.com/65790521/99571882-a5f2c380-29b2-11eb-8ce2-b300d3355556.png)

## Steps To Reproduce

1. Create a NativeModuleSample following this tutorial https://microsoft.github.io/react-native-windows/docs/native-modules-setup
2. Implement asyncronous windows following this example https://microsoft.github.io/react-native-windows/docs/native-modules-async#simplehttpmodule-in-c
3. Both the Example discribed there and the Implementation discribed here (https://github.com/microsoft/react-native-windows-samples/blob/master/samples/NativeModuleSample/csharp/windows/NativeModuleSample/AsyncMethodExamples.cs) should be tested.
## Expected Results
We should be able to build the Native Module Library

## Snack, code example, screenshot, or link to a repository:
Example using the Documentation : 
![SimpleHTTPEx](https://user-images.githubusercontent.com/65790521/99572509-8a3bed00-29b3-11eb-834a-111cb482dff9.png)

Example using Githubs Repository 
![SimpleHTTPEx](https://user-images.githubusercontent.com/65790521/99572657-bfe0d600-29b3-11eb-9b9a-fe1e9b1485ba.png)

**Comment by NickGerleman** [comment]
@getuliovdmnaweb does the example work if you change `Task<string>` to `IAsyncOperation<string>`? This seems like a potential docs issue.

FYI @dannyvv

**Comment by caiovictor** [comment]
Hi guys @NickGerleman @dannyvv @chrisglein @jonthysell, I have the same error as @getuliovdmnaweb , but when I create a constant using ReactConstantProvider:

![image](https://user-images.githubusercontent.com/16005238/99812488-479a2200-2b25-11eb-835a-a10706bda6ef.png)

This method I copied from that link:
https://github.com/microsoft/react-native-windows/blob/abee26d14b3ffed5210a97283a1353f38b0b1989/vnext/Microsoft.ReactNative.Managed.UnitTests/NativeModuleTest.cs#L498

Isn't this related to the public methods of a Windows Runtime project not being able to expose types that do not inherit from IAsyncInfo?

**Comment by jonthysell** [comment]
The NativeModuleSample builds just fine but does not match what's in the docs.

**Comment by jonthysell** [comment]
The documentation has been updated to reflect the working sample. Please re-open if the new code doesn't work.

**Comment by getuliovdmnaweb** [comment]
This is the Example:
![image](https://user-images.githubusercontent.com/65790521/100101862-91467d80-2e41-11eb-8c6e-b502edc62811.png)
This is the Error:
![image](https://user-images.githubusercontent.com/65790521/100101961-b20ed300-2e41-11eb-9771-3fed74cece18.png)

**Comment by getuliovdmnaweb** [comment]
@jonthysell

**Comment by jonthysell** [comment]
@getuliovdmnaweb Can you post a link to your project source? It think this has less to do with the code and more to do with the structure of the solution/project files.

**Comment by getuliovdmnaweb** [comment]
@jonthysell Hello, here is the link to a github repository with the example
https://github.com/getuliovdmnaweb/NativeModuleSample

**Comment by jonthysell** [comment]
> @jonthysell Hello, here is the link to a github repository with the example
> https://github.com/getuliovdmnaweb/NativeModuleSample

As per the docs and samples, please remove `public sealed` from your module class, so that it defaults to an `internal` class.

```diff
-    public sealed class NativeModuleSample
+    class NativeModuleSample
```

Making a public WinRT class exports that class externally (to be consumed directly by any WinRT app/lib) however this requires that all public members and methods only use publicly available WinRT types. The types in `Microsoft.ReactNative.Managed` (such as `JSValue` and `ReactPromise<>`) are not publicly available WinRT types, as `Microsoft.ReactNative.Managed` is a just a Class Library, not a WinRT Library.

The expectation is that your project *only* exposes the `ReactPackageProvider` - everything else should be internal types.
