### ISSUE TITLE
run-windows Failed to restore the NuGet packages

### ISSUE THREAD

**Issue by nerocui** [microsoft/react-native-windows#6564]
## Environment
npx react-native --version
4.13.0

npx react-native info
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 1.88 GB / 15.84 GB
  Binaries:
    Node: 12.16.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.16299.0, 10.0.17134.0, 10.0.17763.0, 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6626763
    Visual Studio: 16.9.30709.64 (Visual Studio Community 2019), 16.8.30711.63 (Visual Studio Community 2019)
  Languages:
    Java: 14.0.2
    Python: 3.8.2
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-windows: ^0.63.0-0 => 0.63.8
  npmGlobalPackages:
    *react-native*: Not Found

Visual Studio Version
16.8

Installed SDK Version
16299, 17134, 17763, 18362, 19041

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. npx react-native init <projectName> --template react-native-template-typescript@6.5.*
2. cd projectName
3. npx react-native-windows-init --overwrite
4. npx react-native run-windows

5. Error
Failed to restore the NuGet packages: Error: C:\Users\Nero\code\jithub\node_modules\react-native-windows\Microsoft.ReactNative.Managed\Microsoft.ReactNative.Managed.csproj(154,11): error MSB4226: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\WindowsXaml\v16.0\Microsoft.Windows.UI.Xaml.CSharp.targets" was not found. Also, tried to find "Microsoft\WindowsXaml\v16.0\Microsoft.Windows.UI.Xaml.CSharp.targets" in the fallback search path(s) for $(MSBuildExtensionsPath) - "C:\Program Files (x86)\MSBuild" . These search paths are defined in "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\bin\msbuild.exe.Config". Confirm that the path in the <Import> declaration is correct, and that the file exists on disk in one of the search paths.
C:\Users\Nero\code\jithub\node_modules\react-native-windows\Microsoft.ReactNative.Managed.CodeGen\Microsoft.ReactNative.Managed.CodeGen.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.

## Expected Results
"A new Command Prompt window will open with the React packager as well as a react-native-windows app. "

## react-native run-windows --logging
× Building Solution
 × Build failed with message     11>C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(241,5): error NETSDK1004: Assets file 'C:\Users\Nero\code\jithub\node_modules\react-native-windows\Microsoft.ReactNative.Managed.CodeGen\obj\project.assets.json' not found. Run a NuGet package restore to generate this file. [C:\Users\Nero\code\jithub\node_modules\react-native-windows\Microsoft.ReactNative.Managed.CodeGen\Microsoft.ReactNative.Managed.CodeGen.csproj]. Check your build configuration.
See C:\Users\Nero\AppData\Local\Temp\msbuild_27456.err

## Related issue
https://github.com/microsoft/react-native-windows/issues/2031
https://github.com/microsoft/react-native-windows/issues/6495

**Comment by NickGerleman** [comment]
It seems like you might be missing some dependencies, could you try a couple of things?

1. Update to react-native-windows 0.63.10 which fixes some compatibility issues with VS 16.8
2. Run the dependency installation script documented [here](https://microsoft.github.io/react-native-windows/docs/rnw-dependencies)

**Comment by nerocui** [comment]
@NickGerleman Thanks for the tips. I tried both methods. The dependency script shows everything is fine. And switching to react-native-windows 0.63.10 didn't help either. The same error remains.

**Comment by asklar** [comment]
It sounds like your nuget restore got wedged in a bad state. Can you try the following:
1) delete your node_modules and re-run yarn to re-populate
2) delete Debug, bin and obj folders if there are any under your solution folder
Then try again? :)

**Comment by nerocui** [comment]
@asklar Thanks for the help. Unfortunately neither of the two methods worked for me.

**Comment by asklar** [comment]
A few possible bugs identified:
CC @dannyvv This could be due to the codegen project using .netcore 3.x, which might be missing?
If there are more than one VS install, then the CLI will pick the newer one, without checking whether it has the managed desktop payload

@nerocui could you try launching the VS Installer tool and manually selecting the following options, let it install them, then retry?
- .net desktop development
- uwp development
- desktop C++
- .net core 3.1

**Comment by nerocui** [comment]
@asklar thanks for the suggestion, I've looked, all those options are already installed.

**Comment by BartoszKlonowski** [comment]
@asklar  I've been facing the same issue for a while, when launching the app using command line or Visual Studio, but I've found out that **it is possible to launch build and launch successfully using Visual Studio Code**.

What I did was:
* `npm install`
* go to VS Code, add basic *.\.vscode\launch.json* settings:
```
    {
        "name": "Debug Windows",
        "cwd": "${workspaceFolder}",
        "type": "reactnative",
        "request": "launch",
        "platform": "windows"
    }
```
* launch the app by pressing F5

I've been trying to launch the same app "manually" by:
* `yarn install`
* `npx react-native run-windows`

but I was getting the same error as @nerocui.

---

I've checked how does VS Code launches the RNW app by default and I've found out, that it is using:
```
.\node_modules\.bin\react-native.cmd run-windows --logging --remote-debugging --no-packager
```

The are two differences between failing and non-failing methods:
| failing | non-failing |
|-------|-------------|
| yarn install | npm install |
| npx react-native run-windows | react-native.cmd run-windows |

---

I will try to find out more on this topic.

**Comment by BartoszKlonowski** [comment]
@asklar @nerocui  I've made some more test builds and the conclusion is that the build will fail when doing `yarn install`, but it will build successfully (no matter if running from VS Code, or terminal, and no matter what arguments are given) with `npm install`.
So most probably there's something wrong with how Yarn installs the packages.

The next thing to do is to check what are the differences between `yarn install` and `npm install`.

**Comment by nerocui** [comment]
@BartoszKlonowski So I do have yarn install on my machine. But I did not use `yarn install` for installing the packages. I then uninstalled yarn and tried again, still with the same error. So I don't think my issue specifically has anything to do with yarn.

**Comment by BartoszKlonowski** [comment]
@nerocui  It's not about Yarn being installed on the machine or not, but about which tool is used as a package installer. Looking at the *Steps to reproduce* part of your issue, I can see you did not install packages at all, as you are making a new project, but packages are installed by default.
What you can do, according to my findings, is:
* delete all the node_modules
(they are downloaded by default when creating the project, but it looks like they should be reinstalled using npm)
* use npm to install packages `npm install`
* build and run the app like always `npx react-native run-windows`

Please give it a try and share the result, it did solve the same issue on my side.

**Comment by nerocui** [comment]
@BartoszKlonowski My fault not including my steps in the reply. I did delete node_modules and installed packages with `npm install` then `npx react-native run-windows`. Same error.

**Comment by asklar** [comment]
Are you still blocked or were you able to get this working @nerocui ? If you are still hitting an issue and are able to reliably hit this locally, could you share a repo repro so I can look at it?

**Comment by nerocui** [comment]
@asklar I assumed everything to be the same, but when I tried again the steps today, it worked. Not much has changed on my machine config wise except node version. It was 12 before, now it's 14. I'm not sure if that's thing that fixed it.
