### ISSUE TITLE
Enable tabbing into SectionList headers

### ISSUE THREAD

**Issue by rectified95** [microsoft/react-native-windows#6566]
extracted from #2107

**Comment by chrisglein** [comment]
Sounds like there's been some analysis of this and it's not a trivial change. @rectified95 can you capture that here in the issue and we may have to come back to this later?

**Comment by rectified95** [comment]
I've just managed to tab into the headers in the SectionList example of RNTester. 
The code in VirtualizedSectionList.js relies on the user to provide render functions for list entries and headers/footers. So in order to make the section headers be tab stops, the user needs to provide a function returning a focusable element.
In the RNtester example, I was able to accomplish that by simply adding the `focusable` prop the `\<View>`
```js
const renderSectionHeader = ({section}) => (
  <View style={styles.header} focusable>
    <Text style={styles.headerText}>SECTION HEADER: {section.key}</Text>
    <SeparatorComponent />
  </View>
);
``` 
This is consistent with how lists work in RN overall - unless list entries are focusable elements, it's not possible to navigate between them with a keyboard.

@chrisglein @harinikmsft I think the way forward is to document this behavior and close the issue. I'm thinking I could try and make a change to the upstream docs to make a reference to Windows-specific behavior. That would be a first one, though, so might not work. Barring that, we could somehow make a note in our docs.

**Comment by rectified95** [comment]
To capture more context: when we fix keyboard navigation of `FlatList` (which shares the implementation with `SectionList`), it will only be possible to tab into the list once, and move between entries using arrow keys - headers will be treated like any other entry. Pressing tab again, will move focus out of the list to the subsequent component in the UI.

**Comment by rectified95** [comment]
Tagging again to revive thread after winter break.
@harinikmsft @chrisglein

**Comment by rectified95** [comment]
Unassigning and moving to backlog - context given in comments above: we aren't able to tab into headers but will be able to navigate to them using arrows. This could be possible if were using more advanced XAML list elements, rather than ScrollView.
