### ISSUE TITLE
Visual Studio shouldn't pause execution on packager disconnect when web debugging

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#6569]
WebSocketJSExecutor uses WinRT websocket APIs which throw on control flow (e.g. disconnect). This means that Visual Studio will pause excution if debugging and then killing the packager.

We should use `lessthrow_await_adapter` to silence these warnings.

**Comment by JunielKatarn** [comment]
I just published a 0.62-aimed backport of the WebSocketResource analog change.
Might as well take care of this one now.

**Comment by JunielKatarn** [comment]
The issue goes beyond the type of error thrown.

The connect operation does not exercise any sort of error handling.

```
  co_await m_socket.ConnectAsync(uri);

```

**Comment by NickGerleman** [comment]
The underlying issue can still be reproed after the change by killing the packager during a web debugging session. Different looking issue though, where the failure is in calling `GetDataReader()` in a message received callback.

```cpp
  m_msgReceived = m_socket.MessageReceived(winrt::auto_revoke, [this](auto &&, auto &&args) {
    try {
      std::string response;
      if (args.MessageType() == winrt::Windows::Networking::Sockets::SocketMessageType::Utf8) {
        winrt::Windows::Storage::Streams::DataReader reader = args.GetDataReader();
        reader.UnicodeEncoding(winrt::Windows::Storage::Streams::UnicodeEncoding::Utf8);
        uint32_t len = reader.UnconsumedBufferLength();
        std::vector<uint8_t> data(len);
        reader.ReadBytes(data);

        std::string str(Microsoft::Common::Utilities::CheckedReinterpretCast<char *>(data.data()), data.size());
        OnMessageReceived(str);
      } else {
        OnHitError("Unexpected MessageType from MessageWebSocket.");
      }
```
