### ISSUE TITLE
Re-enable babel-plugin-codegen (inline viewconfigs) with new react-native-tscodegen drop

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#6570]
After integrating the 11/18 nightly build, inline view configs seem to generate invalid code and we fail to bundle. We're using a forked very old version of react-native-codegen. We should rev the codegen package (or use the stock published one) and reenable the plugin.

**Comment by NickGerleman** [comment]
Looked closer and the invalid code generated was due to a bad merge. We should still probably rev soon, since there seems to have been a number of parsing changes, but we're still good for now.

**Comment by NickGerleman** [comment]
Actually it looks like CI is running into issues here that I didn't see locally for some reason. https://dev.azure.com/ms/react-native-windows/_build/results?buildId=123456&view=logs&jobId=95c38ed8-9ebc-5252-0e1a-a56bef4e7831&j=95c38ed8-9ebc-5252-0e1a-a56bef4e7831&t=0ba72d16-294a-545b-2be8-5d817af3e94a

**Comment by acoates-ms** [comment]
This was completed as part of enabling bridgeless.
