### ISSUE TITLE
Using Picker as the first component in a Flyout causes it to not close when clicking in Flyout

### ISSUE THREAD

**Issue by lyahdav** [microsoft/react-native-windows#6584]
## Environment
1. `npx react-native --version`: 4.13.0
2. `npx react-native run-windows --info`:
```
  System:
    OS: Windows 10 10.0.19041
    CPU: (40) x64 Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz
    Memory: 157.00 GB / 190.60 GB
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.0-20190429.1820 - C:\open\fbsource\xplat\third-party\yarn\yarn.BAT
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
    Watchman: 20200724.030019 - C:\tools\watchman\watchman.EXE
  Installed UWP SDKs:
    10.0.18362.0
```
3. `reg query "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock"`
```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock
    AllowDevelopmentWithoutDevLicense    REG_DWORD    0x1
    AllowAllTrustedApps    REG_DWORD    0x1
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Run playground-win32 app and go to RNTester Flyout example
2. Modify Flyout example to have this Flyout: `<Flyout><View style={{margin: 50}}><Picker ... /></View></Flyout>`
3. Open the Flyout, open the picker, then click in the margin of the Flyout.

## Expected Results
Expected: Picker should close.
Actual: Nothing happens.

Note if you but some other component that is focusable first in the Flyout (e.g. Button)  the issue is resolved.
I realize Picker is being extracted from core, but I'm pretty sure this is an issue with Flyout, not Picker.

Also, this issue doesn't happen in the UWP playground app and it doesn't happen in a plain Xaml Islands app. So seems RNW Xaml Islands specific.

CC @asklar

**Comment by asklar** [comment]
@lyahdav just wanted to confirm this is still an issue since you mentioned you were unblocked this afternoon. I don't see the picker when I move it around but I'm not sure if there's something different in my setup:
![image](https://user-images.githubusercontent.com/22989529/99764127-3dd6d700-2ab1-11eb-8591-3d442b880657.png)

**Comment by lyahdav** [comment]
I got unblocked by adding another component (a close button) at the top of all our Flyouts that have a Picker as the first component, not ideal. Did you move the `<Picker>` in that example to the top of the Flyout but inside the container `<View>`?

**Comment by chrisglein** [comment]
Not something we plan to address on the Paper renderer as we move towards Fabric. The equivalent component for Fabric is tracked [here](https://github.com/microsoft/react-native-windows/issues/11921).
