### ISSUE TITLE
[RNTester] On Windows the buttons at the top should include Windows, not iOS & Android

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#6588]
![image](https://user-images.githubusercontent.com/22989529/99764426-dff6bf00-2ab1-11eb-939b-c68d1d8238c0.png)

**Comment by NickGerleman** [comment]
Dupe of https://github.com/microsoft/react-native-windows/issues/6314

When we discussed this, the overall thought was that it wasn't really worth the effort.
