### ISSUE TITLE
Flyout doesn't size to its content if no width/height is set in first child component

### ISSUE THREAD

**Issue by lyahdav** [microsoft/react-native-windows#6591]
## Environment
1. `npx react-native --version`: 4.13.0
2. `npx react-native run-windows --info`:
```
  System:
    OS: Windows 10 10.0.19041
    CPU: (40) x64 Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz
    Memory: 157.00 GB / 190.60 GB
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.0-20190429.1820 - C:\open\fbsource\xplat\third-party\yarn\yarn.BAT
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
    Watchman: 20200724.030019 - C:\tools\watchman\watchman.EXE
  Installed UWP SDKs:
    10.0.18362.0
```
3. `reg query "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock"`
```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock
    AllowDevelopmentWithoutDevLicense    REG_DWORD    0x1
    AllowAllTrustedApps    REG_DWORD    0x1
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Run playground win32 app
2. Go to Flyout example
3. Change the code so that no width/height is set on the Flyout's child View

## Expected Results
Expected: Flyout width/height is set automatically based on the size of its children.
Actual: Flyout size is set based on where the Flyout is present in the view hierarchy outside of the Flyout.

On Mac we fixed this by correctly resetting the shadow layout context:
```
@implementation PopoverShadowView

- (CGSize)contentSize {
  // There should only be one child.
  RCTShadowView* childShadowView = self.reactSubviews.firstObject;
  return childShadowView ? childShadowView.layoutMetrics.frame.size : CGSizeZero;
}

- (void)layoutSubviewsWithContext:(RCTLayoutContext)layoutContext {
  for (RCTShadowView* childShadowView in self.reactSubviews) {
    layoutContext.absolutePosition = CGPointZero;

    [childShadowView
        layoutWithMinimumSize:CGSizeZero
                  maximumSize:CGSizeMake(INFINITY, INFINITY)
              layoutDirection:RCTUIKitLayoutDirectionFromYogaLayoutDirection(self.direction)
                layoutContext:layoutContext];
  }
}

@end
```

**Comment by lyahdav** [comment]
Note I found a quick workaround: add a `position: absolution` style to the first child view in Flyout.

**Comment by asklar** [comment]
Could be an issue with the flyout viewmanager not setting the constraints properly. CC @kmelmon in case this looks familiar?
Putting in backlog as it isn't blocking right now.

**Comment by chrisglein** [comment]
Not something we plan to address on the Paper renderer as we move towards Fabric. The equivalent component for Fabric is tracked [here](https://github.com/microsoft/react-native-windows/issues/11921).
