### ISSUE TITLE
App.js Type annotations can only be used in TypeScript files.

### ISSUE THREAD

**Issue by dstampher** [microsoft/react-native-windows#6596]
VSCode showing a red squiggly on line 27 of App.js boilerplate code generated by following the Get Started tutorial:  https://microsoft.github.io/react-native-windows/docs/getting-started

`Type annotations can only be used in TypeScript files.ts(8010)`

## Environment
react-native --version
4.13.1

react-native info
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
    Memory: 7.66 GB / 15.95 GB
  Binaries:
    Node: 12.18.4 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowAllTrustedApps: Enabled
      AllowDevelopmentWithoutDevLicense: Enabled
      Versions: 10.0.17763.0, 10.0.18362.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.8.30709.132 (Visual Studio Community 2019)
  Languages:
    Java: Not Found
    Python: 3.8.6
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-windows: ^0.63.0-0 => 0.63.10
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
1. Run npx react-native init example-bug --template react-native@^0.63.2
2. cd example-bug
3. Run npx react-native-windows-init --overwrite

**Comment by NickGerleman** [comment]
This is an unfortunate artifact of the template app for react-native writing App.js in Flow instead of TypeScript or raw JS. It will confuse VSCode, and likely other editors that aren't able to work with Flow. This happens when building an iOS or Android app as well.

There are some instructions in our documentation to use a typescript template instead of flow, but IMO the default should be that or raw JS. Will try to spin up a conversation related to that.

**Comment by dstampher** [comment]
@NickGerleman Thanks for the explanation.  Luckily everything still builds/runs fine, I just changed the line from const App: () => React$Node = () => { to const App = () => { and it seems to remove the error and still work as well.

I'll look into using the Typescript template like you mentioned though.
