### ISSUE TITLE
Move CLI from `inquirer` to `prompts`

### ISSUE THREAD

**Issue by acoates-ms** [microsoft/react-native-windows#6607]
https://github.com/react-native-community/cli/pull/1010 moved the RN cli from `inquirer` to `prompts`.  We should move our CLI tools to `prompts` too to avoid additional packages.

**Comment by NickGerleman** [comment]
Heh, `prompts` has better typings too. I remember moving to inquirer because it was being used in the CLI at the time 😆 ,
