### ISSUE TITLE
Information in @react-native-windows/cli README should be in a public README

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#6620]
We've added some information about usage and data collection to the README for @react-native-windows/cli. https://www.npmjs.com/package/@react-native-windows/cli This package is private, and its README will not be seen by users. We should find a new home for these, if we need to make anything visible.

**Comment by chrisglein** [comment]
Some decisions need to be made here about where this should show up. We could elevate important information into the main readme (it's present in other places, but redundancy isn't bad here). Other things like the command line arguments are covered in the website. Is there a canonical place to put this content?
