### ISSUE TITLE
Adding react-native-windows to an existing react-native project with expo?

### ISSUE THREAD

**Issue by dstampher** [microsoft/react-native-windows#6624]
Like the title says, I have an expo app, and I would like to be able to add react-native-windows to it so that I can execute npx react-native run-windows.  Following the Get Started docs creates a new blank application, which is not what I am looking for in this case.

What are the proper steps of accomplishing this?

**Comment by chrisglein** [comment]
We don't yet support the set of expo modules you'd need to run the same app with react-native-windows. It's something we'd love to support (and [Snack support](https://github.com/microsoft/react-native-windows/issues/5173) too!), but won't work today. A good ask for the future roadmap, though. You could try logging an issue against the expo repo to make your desire for this clear, though, as it'll likely be a group effort.

**Comment by bwjohns4** [comment]
Is there any update on this? I have an ejected Expo app. How could I make this work with React Native Windows?

**Comment by acoates-ms** [comment]
Have you tried running `npx react-native-windows-init` in your project?
You'll want to look carefully at what it does to your project, but it should get things started.

**Comment by bwjohns4** [comment]
I got it to build with react-native-windows, but I can't get past this runtime issue:

Uncaught Error
Expo native runtime is not available: something went wrong and we aren't sure what it was. Please post more information and get support at https://forums.expo.dev.

Source
...
9 | !Constants?.expoVersion&&
10 | Constants?.executionEnvironment!=ExecutionEnvironment.Bare) {
> 11 | thrownewError('Expo native runtime is not available: something went wrong and we aren't sure what it was. Please post more information and get support at https://forums.expo.dev.');

**Comment by acoates-ms** [comment]
That indicates that some part of your application is using expo specific modules.  Expo does not currently support desktop platforms, so you'll have to ensure that the windows version of your application does not hit any of the code that requires expo.

**Comment by bwjohns4** [comment]
I'm not fully knowledgeable of Expo under the hood mechanisms. Is it as simple as starting with App.js and working through to find and conditionally remove Expo modules?

Do you know if Expo updates and things like that will be a problem? Not sure when/how they get bundled in, but I do not call them directly anywhere. Does RNWindows do its own bundling so stuff like that won't be a problem?
