### ISSUE TITLE
Support react-native-restart

### ISSUE THREAD

**Issue by creambyemute** [microsoft/react-native-windows#6627]
# Support `react-native-restart` on RNW

It's a pretty small module and already has a C# implementation, would it be hard to bring that over to C++?

## Basic Info
- Module Repo URL: https://github.com/avishayil/react-native-restart
- Target version: ?
- [x] Issue exists on module repo ([#145](https://github.com/avishayil/react-native-restart/issues/145))
- [x] Module has a Legacy/C# implementation ([C# Implementation](https://github.com/avishayil/react-native-restart/tree/master/windows))

## Which app/customer is requesting this module?
Community Module.

## In what scenarios will this module be used?
Restart the App/Reload Bundle. It's something extracted from AppCenter/CodePush.
We, for example, use it after a logout to clear out the apollo cache etc.

## Essential Features
-  `RNRestart.Restart();` to restart the app/reload the bundle

**Comment by chrisglein** [comment]
Didn't realize this already had a C# windows implementation (it's isn't listed in [the directory](https://github.com/avishayil/react-native-restart)). That should make this an easy port.

If you're at all interested on taking this on yourself we have had some modules go through the C# -> vnext C++ transition lately and so there should be good examples to reference.

@stmoy Maybe include some of those links here?

**Comment by creambyemute** [comment]
@chrisglein If there's some guidance, I might really give it a try this weekend as it's such a small module with almost no code :-). Though will be my first time with C++ 👍

**Comment by stmoy** [comment]
@creambyemute - any luck?

**Comment by creambyemute** [comment]
@stmoy Oh I didn't start yet. Chris mentioned above, that there are some examples/references for transitioning a module from C# to C++. 
Are there any links to them? Would it be worth to include them somewhere on the Readme?

**Comment by creambyemute** [comment]
@stmoy @chrisglein  Hey, sorry for pinging you both again, I'd really like to give this small C# --> C++ refactoring a try. 
You mentioned there may be some examples for reference?

I'll be on vacation the first week of February and would look into this as I'm interested in the process of writing/transitioning a C# to C++ Module and thought I'd ping again before I'll dig into the unknown :).

**Comment by creambyemute** [comment]
PR was opened in the RN-Restart repository leveraging `CoreApplication::RequestRestartAsync(...)`. This can be closed probably as the solution is there and the PR will most likely be merged in the near future.

**Comment by creambyemute** [comment]
@stmoy React-Native-Restart now has a C++ Implementation.

I just tested it and it works great 👍
