### ISSUE TITLE
Support react-native-calendars

### ISSUE THREAD

**Issue by syedibrahimt** [microsoft/react-native-windows#6637]
# Support `react-native-calendars` on RNW

## Basic Info
- Module Repo URL: [link to repo](https://github.com/wix/react-native-calendars)
- Target version: react native 0.63
- [ ] Issue exists on module repo (if so, [link]())

- [ ] Module has a Legacy/C# implementation (if so, [link]())

## Which app/customer is requesting this module?

BackPack - Knomadix corporation

## In what scenarios will this module be used?

We need a calendar component in which user can able to select date and get corresponding lesson unit for the particualr day.

## Essential Features

* User can able to navigate between months.
* User can able to make date selection.

**Comment by asklar** [comment]
@syedibrahimt you can use [react-native-datetimepicker](https://github.com/react-native-datetimepicker/) instead

**Comment by chrisglein** [comment]
Likely will involve wrapping the built in XAML [CalendarView](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.CalendarView?view=winrt-19041) control.
