### ISSUE TITLE
Support react-native-tts

### ISSUE THREAD

**Issue by syedibrahimt** [microsoft/react-native-windows#6638]
# Support `react-native-tts` on RNW

## Basic Info
- Module Repo URL: [link to repo](https://github.com/ak1394/react-native-tts)
- Target version: 
- [ ] Issue exists on module repo (if so, [link]())

- [ ] Module has a Legacy/C# implementation (if so, [link]())

## Which app/customer is requesting this module?

BackPack - Knomadix corporation

## In what scenarios will this module be used?

The app will be able to for text to speech for educational purposes.

## Essential Features

* Text to speech
* English Female voice is required

**Comment by tritao** [comment]
This has now been implemented: https://github.com/ak1394/react-native-tts/pull/161
