### ISSUE TITLE
Contributing to the CLI - Creating initial example project fails for repo version

### ISSUE THREAD

**Issue by BartoszKlonowski** [microsoft/react-native-windows#6641]
I'm following the guide for [Contributing to the CLI](https://github.com/microsoft/react-native-windows/wiki/Contributing-to-the-CLI) and I'm trying to create the test application so I can debug my changes.
But the issue is that when creating the initial project, just like described [here](https://github.com/microsoft/react-native-windows/wiki/Contributing-to-the-CLI#1-create-the-initial-project):
```
npx react-native init testapp --version 0.0.0-canary.218
```
I'm using the version *0.0.0-canary.218* which I've found in the *<repo>\vnext\package.json* file:
```
{
  "name": "react-native-windows",
  "version": "0.0.0-canary.218",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "git@github.com:microsoft/react-native-windows.git",
    "directory": "vnext"
  },
...
```
which ends up with the following error:
```
× Downloading template
error Error: Command failed: yarn add react-native@0.0.0-canary.218
warning ..\..\..\..\package.json: No license field
error Couldn't find any versions for "react-native" that matches "0.0.0-canary.218"
```

---

I've been trying to figure the solution out on my own, but though I've been trying to use other versions found in other *package.json* files, or trim the version to leading numbers only, it doesn't help. So perhaps there's an issue in the docs?

Or if there's anything I've missed or something I just don't understand then I'm eager to learn.

## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`:
4.13.1

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Follow the guide to [Testing react-native-windows-init E2E with only local CLI bits](https://github.com/microsoft/react-native-windows/wiki/Contributing-to-the-CLI#testing-react-native-windows-init-e2e-with-only-local-cli-bits)
2. Create the testapp using the version given in *<root>/vnext/package.json* file.

## Expected Results
*testapp* is created successfully.

**Comment by asklar** [comment]
@BartoszKlonowski you're passing the version of `react-native-windows` to `react-native init`, but you're supposed to use the version of `react-native` instead (it's lower down in the package.json file)
```
    "react-native": "0.0.0-19d4cc2d4",
```

**Comment by chrisglein** [comment]
@BartoszKlonowski Are you unblocked with that? Do we need a change to the documentation to help with clarity?

**Comment by BartoszKlonowski** [comment]
Thank you for asking, @chrisglein. I've decided to use the default version by not specifying any version and it worked fine.
But thanks to @asklar  explanation I'm completely unblocked now, so I can close this issue now.
Thank you!
