### ISSUE TITLE
Support redux-persist-fs-storage (JS-Only)

### ISSUE THREAD

**Issue by creambyemute** [microsoft/react-native-windows#6651]
# Support `redux-persist-fs-storage` on RNW

**It's basically already done, JS-Changes review desired**

It's a FSStorageAdapter acting like AsyncStorage (methods). It uses react-native-fs under the hood.

The only changes needed are in the index.js for Windows path compatibility anf fs-checks (like .exists before .mkdir). I've already done some and would like someone to quickly cross-check.

Have tested the changes on Windows & Android for now.

## Basic Info
- Module Repo URL: [redux-persist-fs-storage](https://github.com/wwimmo/redux-persist-fs-storage) (it's a fork atm) [PR Here](https://github.com/ConnectedHomes/redux-persist-fs-storage/pull/2)
- Target version: ?
- [ ] Issue exists on module repo (if so, [link]())
- [ ] Module has a Legacy/C# implementation (if so, [link]())

## Which app/customer is requesting this module?
Community Module

## In what scenarios will this module be used?
It allows to persist data to the FS with the usual AsyncStorage methods. Usually used together with apollo-cache-persist in React-Native (due to AsyncStorage size limit on Android).

## Essential Features
* setItem()
* getItem()
* removeItem()
* getAllKeys()

**Comment by chrisglein** [comment]
@creambyemute If I understand correctly you mostly have this buttoned up and are looking for some additional eyeballs on it to help get it merged into the main repo for redux-persist-fs-storage? Let me know if I'm misunderstanding. We'd be happy to help!

**Comment by creambyemute** [comment]
@chrisglein Yeah exactly. Mainly for some eyeballing over the JS as I had to add the OSPathSeperator and a `.exist`+`.mkdir` check before writing.

RN-FS which is used, is using avmoroz Win 10 C++ Implementation. He has a PR open on the RN-FS repo.

**Comment by stmoy** [comment]
@creambyemute - happy new year! Bubbling this up. It looks like @asklar added some comments on the PR that haven't yet been addressed. Is there more info that we need to provide?

**Comment by creambyemute** [comment]
@stmoy I don't think so. I can't use NodeJS FS there. Seems like @asklar Approved these recently.

Not sure if it ever will get merged to either to original nor the @ConnectedHomes repository so I forked it and added it there. Seems to be working so far.

**Comment by creambyemute** [comment]
Fork is available at: https://github.com/wwimmo/redux-persist-fs-storage

Original repo is unmaintained, the one where I create a PR seems to be unmaintained as well.

I've been using it since then and didn't have problems yet, so for me it's solved.
