### ISSUE TITLE
Control with "AccessibilityRole" automatically get tab focus no matter the value of focusable prop

### ISSUE THREAD

**Issue by gary-hu-ms** [microsoft/react-native-windows#6652]
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`: 4.13.0
2. `npx react-native info`:
  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Xeon(R) CPU E3-1240 v3 @ 3.40GHz
    Memory: 6.07 GB / 15.76 GB
  Binaries:
    Node: 10.18.1 - C:\Program Files\nodejs\node.EXE      
    Yarn: 1.9.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.6 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @react-native-community/cli: 4.13.0 => 4.13.0         
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-windows: 0.63.6 => 0.63.6
  Installed UWP SDKs:
    10.0.16299.0
    10.0.17134.0
    10.0.17749.0
    10.0.17763.0
    10.0.18362.0

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.  create some View1, View2 component 
2.  set accessibilityRole={"text"} and focusable={true} to View1
3.  set accessibilityRole={"text"} and focusable={false} to View2

## Expected Results
View2 should not have tab focus

**Comment by chrisglein** [comment]
@kmelmon Was it you that was talking about this yesterday? Or was it @rectified95? I remember some discussion about tab focus being possible even when focusability was disabled.

**Comment by kmelmon** [comment]
@chrisglein yes this is the issue I was working with Gary and Lam on.  @lamxdoan  said he would try to submit a PR to fix this.

**Comment by lamxdoan** [comment]
@chrisglein @kmelmon yes I'll be submitting a PR soon. I'll also be sending one to backport down to 0.63

**Comment by NickGerleman** [comment]
We would not want to backport this change. There was a teams thread where someone mentioned they were assuming accessibility label is what led to their components being focusable. Removing focusability of existing components in a patch release is a large behavior change.

**Comment by lamxdoan** [comment]
Ah that's unfortunate. I guess we'll make the change for 0.64 only then.

@gary-hu-ms @aschultz fyi
