### ISSUE TITLE
Remove legacy "deploy from layout" codepath once a new VS has enough usage

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#6658]
Could we file a new issue to remove the legacy deploy cruft once a new VS has enough usage? E.g. the custom deploy targets, or deploy specific code in `buildProject` and `buildSolution`.

_Originally posted by @NickGerleman in https://github.com/microsoft/react-native-windows/pull/6594#discussion_r528276577_

**Comment by chrisglein** [comment]
@asklar I saw some updates on deploy from layout being adopted. Do we have a release timeline for that?

**Comment by asklar** [comment]
@chrisglein The PR for 6594 should keep older VS versions working, but opt to use the now-built-in tool that VS implemented, on the versions that have them. So that PR is mergeable anytime really.

**Comment by chrisglein** [comment]
@asklar It's been a year. Is now okay to clean this up and close this out?
