### ISSUE TITLE
Support react-native-progress

### ISSUE THREAD

**Issue by syedibrahimt** [microsoft/react-native-windows#6667]
# Support `react-native-progress` on RNW

## Basic Info
- Module Repo URL: [link to repo](https://github.com/oblador/react-native-progress)
- Target version: react native 0.63
- [ ] Issue exists on module repo (if so, [link]())

- [ ] Module has a Legacy/C# implementation (if so, [link]())

## Which app/customer is requesting this module?

BackPack - Knomadix corporation

## In what scenarios will this module be used?

To show user loading progress when they download, upload data.

## Essential Features

* Horizontal loader
* Circle loader

**Comment by chrisglein** [comment]
It won't help you with a circular progress control, but if you just need a horizontal progress control to unblock in the meantime you we do have Windows support for [progress-view](https://github.com/react-native-progress-view/progress-view).

**Comment by creambyemute** [comment]
If no progress indicator (how far are we) is needed, but just activity, then the ActivityIndicator is also not a bad choice. Looks pretty dandy with a good color.

We're using that + showing 5 / 27 Images downloaded (for example)
