### ISSUE TITLE
Support react-native-chart-kit

### ISSUE THREAD

**Issue by syedibrahimt** [microsoft/react-native-windows#6668]
# Support `react-native-chart-kit` on RNW

## Basic Info
- Module Repo URL: [link to repo](https://github.com/indiespirit/react-native-chart-kit)
- Target version: 
- [ ] Issue exists on module repo (if so, [link]())

- [ ] Module has a Legacy/C# implementation (if so, [link]())

## Which app/customer is requesting this module?

Knomadix corporation

## In what scenarios will this module be used?

To give user graphical representation of statistical data.

## Essential Features

* Bezier Line Chart
* Bar chart
* Line chart

**Comment by stmoy** [comment]
@syedibrahimt - looks like this module is JS-only so I'd expect that it "just works". Can you verify that it does not (and if not, what errors it throws)?

**Comment by syedibrahimt** [comment]
Thanks @stmoy . I'll try the and verify the same.
