### ISSUE TITLE
Remove Appium and WinAppDriver dependency from rnw-dependencies.ps1. 

### ISSUE THREAD

**Issue by licanhua** [microsoft/react-native-windows#6676]
Because of PR #6636 , appium and winappdriver is removed from the project. we need to update rnw-dependencies.ps1 too

**Comment by chrisglein** [comment]
@kmelmon Assuming we take the linked PR what timeline had you talked about for updating this?

**Comment by kmelmon** [comment]
@chrisglein it would be really nice to do this as soon as the PR is in.

**Comment by rectified95** [comment]
We're still using WinAppDriver for E2E tests. 
https://github.com/microsoft/react-native-windows/pull/7228 adjusted the script to install the required 1.2.1 version
We don't install appium in the script, there's just a leftover comment mentioning it - removing in a quick PR.
FYI @kmelmon @chrisglein
