### ISSUE TITLE
E2E test:  Clicking on hyperlinks crashes test app

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#6682]
We have a possible product bug here.  The bug manifests when a treedump comparison test fails and you try to click on the hyperlinks related to getting test comparison results.

Repro Steps:
1) First you'll need a change to one of the tests that will produce a test master failure.  I've pushed a branch here that does that:  
https://github.com/kmelmon/react-native-windows/tree/test-master-fail
2) Build E2E test and launch it manually
3) Load a test page that has a treedump comparison failure.  For the private branch above that's ControlStyleTestPage

You should see a page that looks like this:
![testfail](https://user-images.githubusercontent.com/33470154/101230442-2fb0bb00-365a-11eb-96ed-e1c63309c6a7.PNG)

4) Click on the "Treedump failed!" text

You should see this page:
![testfail2](https://user-images.githubusercontent.com/33470154/101230461-4525e500-365a-11eb-9f19-300bf50b68d0.PNG)

5) Click on the "output" hyperlink

RESULT
The app crashes.

We are crashing in the hit-testing code for inlines.  Here's the callstack:

 	Microsoft.ReactNative.dll!winrt::impl::consume_Windows_UI_Xaml_IDependencyObject<winrt::Windows::UI::Xaml::Documents::Inline>::GetValue(const winrt::Windows::UI::Xaml::DependencyProperty & dp) Line 867	C++
>	Microsoft.ReactNative.dll!Microsoft::ReactNative::TouchEventHandler::TestHit(const winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::UI::Xaml::Documents::Inline> & inlines, const winrt::Windows::Foundation::Point & pointerPos, bool & isHit) Line 463	C++
 	Microsoft.ReactNative.dll!Microsoft::ReactNative::TouchEventHandler::TagFromOriginalSource(const winrt::Windows::UI::Xaml::Input::PointerRoutedEventArgs & args, __int64 * pTag, winrt::Windows::UI::Xaml::UIElement * pSourceElement) Line 426	C++
 	Microsoft.ReactNative.dll!Microsoft::ReactNative::TouchEventHandler::OnPointerMoved(const winrt::Windows::Foundation::IInspectable & __formal, const winrt::Windows::UI::Xaml::Input::PointerRoutedEventArgs & args) Line 145	C++
 	Microsoft.ReactNative.dll!<lambda_75a942c2d1a566590605619a37de0a06>::operator()<winrt::Windows::Foundation::IInspectable const &,winrt::Windows::UI::Xaml::Input::PointerRoutedEventArgs const &>(const winrt::Windows::Foundation::IInspectable & <args_0>, const winrt::Windows::UI::Xaml::Input::PointerRoutedEventArgs & <args_1>) Line 4181	C++
 	Microsoft.ReactNative.dll!winrt::impl::delegate<winrt::Windows::UI::Xaml::Input::PointerEventHandler,<lambda_75a942c2d1a566590605619a37de0a06>>::Invoke(void * sender, void * e) Line 1460	C++

We're here:

```
winrt::IPropertyValue TouchEventHandler::TestHit(
    const winrt::Collections::IVectorView<xaml::Documents::Inline> &inlines,
    const winrt::Point &pointerPos,
    bool &isHit) {
  winrt::IPropertyValue tag(nullptr);

  for (const auto &el : inlines) {
    if (const auto span = el.try_as<xaml::Documents::Span>()) {
      auto resTag = TestHit(span.Inlines().GetView(), pointerPos, isHit);

      if (resTag)
        return resTag;

      if (isHit) {
        tag = el.GetValue(xaml::FrameworkElement::TagProperty()).try_as<winrt::IPropertyValue>();

```

The attempt to GetValue is failing with -2147418113.  I haven't debugged further, but the problem seems pretty clearly related to the Inlines that this Text element generates.

**Comment by asklar** [comment]
The inlines that are involved in the links are created outside react native, they're created in code by the C# app directly, so they will not have RNW tags. The RNW should be resilient to dealing with elements not created by the framework as apps can mix and match XAML and RNW content
