### ISSUE TITLE
Cannot build release e2eTest in Visual Studio

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#6687]
In VS, OutDir is a relative path for C# projects, e.g. `bin\x86\Release`
```
    <BundleSourceMapDir Condition="'$(BundleSourceMapDir)' == ''">$([MSBuild]::NormalizePath('$(OutDir)\sourcemaps\react'))</BundleSourceMapDir>
```

Therefore `BundleSourceMapDir` ends up wrongly pointing under the VS install dir

**Comment by chrisglein** [comment]
Is this only affecting E2ETest or more than this?

**Comment by asklar** [comment]
theory is that all C# apps can't be built in VS, only through CLI

**Comment by asklar** [comment]
Regressed by #6369
