### ISSUE TITLE
useWindowDimensions hook always returns fixed values

### ISSUE THREAD

**Issue by matevzpoljanc-spin** [microsoft/react-native-windows#6689]
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`: 4.13.1
2. `npx react-native info`:
System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz
    Memory: 24.39 GB / 47.91 GB
  Binaries:
    Node: 12.9.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.8.30711.63 (Visual Studio Professional 2019), 15.9.28307.344 (Visual Studio Community 2017)
  Languages:
    Java: Not Found
    Python: 3.8.6
  npmPackages:
    @react-native-community/cli: ^4.13.1 => 4.13.1 
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-windows: ^0.63.0-0 => 0.63.11 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create RN App and use UseWindowDimensions hook
```
import { Text, View, useWindowDimensions } from 'react-native';

const App = () => {
    const dimensions = useWindowDimensions()
    console.log(dimensions.width)
    console.log(dimensions.height)

    return (
            <View>
                <Header />
                <LoginComponent />
                <View style={{flex: 1, flexDirection: 'row'}}>
                    <SideMenu />
                    <MainBody />
                </View>
            </View>
    )
}
```
2. Resize application window. Logged dimensions are always 1200 for width and 900 for height, regardless of actual window size.

## Expected Results
Dimesnions would update as window size changes.

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by NickGerleman** [comment]
Needs backport of https://github.com/microsoft/react-native-windows/issues/6269

We cannot backport the EmitJSEvent fix that the PR fixing the issue depended on, but can work around that trivially. Some discussion in the thread.

**Comment by BartoszKlonowski** [comment]
@NickGerleman & @chrisglein  I can work on this backport in my spare time, so please assign me to this item.

**Comment by BartoszKlonowski** [comment]
The pull request fixing this issue has been merged - this issue should be closed now.

It's strange that neither this PR has been linked to this issue automatically, but the mention is there...

**Comment by rectified95** [comment]
Closing as fixed.

**Comment by GHEAD1802** [comment]
This issue was originally created with expo and they passed it to React-native as useWindowDimensions id under react native. 
Here is the Link for your reference 
https://github.com/expo/expo/issues/29746
Issue #29746
