### ISSUE TITLE
textDecorationLine text style persists after setting it to "none"

### ISSUE THREAD

**Issue by JakovS** [microsoft/react-native-windows#6715]
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`: 
4.13.0
2. `npx react-native info`: 
System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz
    Memory: 14.91 GB / 31.91 GB
  Binaries:
    Node: 12.9.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.16299.0, 10.0.17134.0, 10.0.17749.0, 10.0.17763.0, 10.0.18362.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 15.9.28307.1300 (Visual Studio Enterprise 2017), 16.8.30717.126 (Visual Studio Enterprise 2019)
  Languages:
    Java: Not Found
    Python: 2.7.15 - C:\Users\jakovs\\.windows-build-tools\python27\python.EXE
  npmPackages:
    @react-native-community/cli: 4.13.0 => 4.13.0
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-windows: 0.63.6 => 0.63.6
  npmGlobalPackages:
    *react-native*: Not Found

- Target Platform Version(s): 10.0.18362.0
- Target Device(s): Desktop
- Visual Studio Version: Visual Studio 2019
- Build Configuration: Debug, Release

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create a Text component
2. Add `{textDecorationLine: "underline"}` style to the text component (same with `"line-through"` and `"underline line-through"`)
3. Replace style with `{textDecorationLine: "none"}` or remove style from the component altogether
4. Observe that text remains underlined

## Expected Results
When style is removed/replaced it should remove the underline decoration from text element

There is a workaround of wrapping the the above Text in another Text component, which then produces expected result:
```
                <Text>
                    <Text
                        style={this.state.underlined ? styles2.underlined : styles2.notUnderlined}
                        key={this.state.key}>
                        {"Some text"}
                    </Text>
                </Text>
```

## Snack, code example, screenshot, or link to a repository:
Drop this component inside a RNW application:
[https://snack.expo.io/PoDBtyQKi](https://snack.expo.io/PoDBtyQKi)
You may provide a screenshot of the application if you think it is relevant to your bug report.
![underline_remains](https://user-images.githubusercontent.com/3286780/101611757-bf3dcd00-39be-11eb-9011-d505180bdfc8.gif)

**Comment by rectified95** [comment]
Looks like this is a bug in XAML - see this thread:
https://github.com/microsoft/microsoft-ui-xaml/issues/1093#issuecomment-514282402
There appears to be a workaround, though
