### ISSUE TITLE
RedBox about topMouseLeave when hovering away from RNTester bottom buttons

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#6738]
1. Launch Playground and load RNTester
2. Hover the mouse over the bottom buttons ("Components / APIs").
3. Move the mouse away from those buttons, wait a couple of seconds.

![image](https://user-images.githubusercontent.com/22989529/102037894-ced06380-3d7a-11eb-9994-072cc323c23a.png)

**Comment by asklar** [comment]
Regressed in #6663

**Comment by rectified95** [comment]
The 12/2 nightly build integration only exposed a bug from October - details in PR.

**Comment by asklar** [comment]
Thanks @rectified95 for the quick fix! A little worrying that we had this regression for over 2 months without noticing :-/
