### ISSUE TITLE
Add react-native upgrade-windows command

### ISSUE THREAD

**Issue by rozele** [microsoft/react-native-windows#674]
We're going to need something to re-run the yeoman generator (like react-native upgrade).

**Comment by achipa** [comment]
Any progress/plan on this? The recent change in how Yoga is referenced was a good example why this can come handy (as opposed to manually mucking with templates and figuring out what/how has changed in csproj/sln templates)

**Comment by rozele** [comment]
@achipa Thanks for pinging on this. I think the right solution is to build the right, stable project configuration hooks into react-native-windows so we don't have to deal with breaking changes. One such attempt was recently added in the 0.55 RC:
https://github.com/Microsoft/react-native-windows/commit/cdde4d71eee2168f2500c1c00ddf1c9d4d1a0eee

The problem comes along with what projects need to be added to the project `.sln` file, as this is not something you can "modularize".  The "right" thing to do is to publish a compiled version of react-native-windows on NuGet so you don't need to include the projects in the solution, but realistically we're still a ways from that, and there are many arguments to be made for building from source (many enterprises require it, we can guarantee we're using the same Yoga implementation across platforms, native debugging is easier, etc.)

**Comment by rozele** [comment]
So, I think I've just convinced myself we need to bump the priority on this so we can easily support building from source :-)

**Comment by rozele** [comment]
Not sure if this is a dupe or just related to #1358

**Comment by achipa** [comment]
Related (two different implementation points for the same issues), in the sense that it's a[ separate project ](https://github.com/facebook/react-native/tree/master/react-native-git-upgrade) for upgrading the templates via git, whereas this issue describes it as part of react-native-windows. 

I can think of arguments for both, so can't really say I have a preference (as long as there _is_ a way to track these upgrades in at least a semi-automated fashion).
