### ISSUE TITLE
CLI switches parsed by commander.js with false defaults don't behave as expected

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#6759]
The RN CLI uses commander to parse options. It allows specifying defaults for options as well as understands that `--no-myoption` means that `myoption` is the name of the option, has default value = `true` and `--no-myoption` means it should be false.

As a result if an option is specified as `--no-myoption`, then its default value, if specified, is ignored. It is always assumed that myoption will be set to true, unless you pass `--no-myoption`.

CC @jonthysell fyi

**Comment by chrisglein** [comment]
It's possible this is fixed by making the community CLI upgrade the version of commander... depending on what's changed with commander.

**Comment by jonthysell** [comment]
We have tests which make sure we don't make mistakes with setting defaults that will get ignored.
