### ISSUE TITLE
application doesn't run or open anything when npx react-native run-windows

### ISSUE THREAD

**Issue by MehdiRaza1998** [microsoft/react-native-windows#6769]
I am using windows 10, 
I don't understand why the output is not showing, nor there is any error to deal with. 
Please have a look

<img width="558" alt="issue" src="https://user-images.githubusercontent.com/35404364/102590047-c9379c80-4131-11eb-877f-5d64d8cc048f.PNG">

It shows nothing and outputs nothing too.
Why is that so? 
How am I suppose to run windows then?

My environment Info:

npx react-native --version: 4.13.1
npx react-native run-windows --info:
      
 System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz
    Memory: 10.09 GB / 15.91 GB
  Binaries:
    Node: 14.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
    react-native-windows: ^0.63.0-0 => 0.63.14
  Installed UWP SDKs:
    10.0.17763.0

npm ls rnpm-plugin-windows:
windowsproject@0.0.1 C:\Users\MehdiRaza\Desktop\ReactNative\windowsproject
`-- (empty)
npm ls react-native-windows:
windowsproject@0.0.1 C:\Users\MehdiRaza\Desktop\ReactNative\windowsproject
`-- react-native-windows@0.63.14

node -v: v14.15.1
npm -v: 6.14.8
yarn --version: 1.22.5

**Comment by asklar** [comment]
@MehdiRaza1998  can you run `npx react-native run-windows --logging` to see if there are any errors?
Also, can you share your environment info?

**Comment by MehdiRaza1998** [comment]
> @MehdiRaza1998 can you run `npx react-native run-windows --logging` to see if there are any errors?
> Also, can you share your environment info?

this is the output by running this command already `npx react-native run-windows --logging`

**Comment by MehdiRaza1998** [comment]
When I run it through VS code 
<img width="419" alt="22" src="https://user-images.githubusercontent.com/35404364/102603405-8fbc5c80-4144-11eb-80b5-6e3448009e78.PNG">
I get following Error!!

This is the launch.json file

{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug Windows",
            "cwd": "${workspaceFolder}",
            "type": "reactnative",
            "request": "launch",
            "platform": "windows"
        }
    ]
}

**Comment by asklar** [comment]
The error from VSCode is not coming from react native for windows, it's coming from the VSCode extension which is written and maintained by a different team, please file a bug here for that particular issue: https://github.com/microsoft/vscode-react-native/

For the issue in the RNW CLI, I haven't seen this before. Is it possible for you to post your project somewhere so that I can try it?

**Comment by MehdiRaza1998** [comment]
ok ignore the Vs code issue, I always run through CLI. I will upload it on the git repository and share the link here.

**Comment by MehdiRaza1998** [comment]
I am following the exact documentation mentioned here

> The error from VSCode is not coming from react native for windows, it's coming from the VSCode extension which is written and maintained by a different team, please file a bug here for that particular issue: https://github.com/microsoft/vscode-react-native/
> 
> For the issue in the RNW CLI, I haven't seen this before. Is it possible for you to post your project somewhere so that I can try it?

I am following the exact documentation mentioned here, you can also follow this to create a project directly, maybe there is a bugging update.

**Comment by asklar** [comment]
@MehdiRaza1998 just to confirm - did you make sure to install the development dependencies? https://microsoft.github.io/react-native-windows/docs/rnw-dependencies

**Comment by MehdiRaza1998** [comment]
> @MehdiRaza1998 just to confirm - did you make sure to install the development dependencies? https://microsoft.github.io/react-native-windows/docs/rnw-dependencies

This can be probably the reason. Thanks, I didn't run the setup command from elevated PowerShell, that might be the reason.

**Comment by asklar** [comment]
Repurposing this issue to track the fact that we should have been printing the error message instead of swallowing the error.
