### ISSUE TITLE
TextInput cursor position gets reset when text is changed

### ISSUE THREAD

**Issue by qmatteoq** [microsoft/react-native-windows#6786]
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`:
4.13.1
2. `npx react-native info`:

System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 1.92 GB / 15.60 GB
  Binaries:
    Node: 12.9.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.14393.0, 10.0.15063.0, 10.0.17763.0, 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.8.30804.86 (Visual Studio Enterprise 2019), 16.9.30803.129 (Visual Studio Enterprise 2019)
  Languages:
    Java: Not Found
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
    react-native-windows: ^0.63.0-0 => 0.63.12
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Define a function to store a string property:

```
const [title, setTitle] = useState('');
```

2. Define a function which takes a string in input and converts it into uppercase:

```
const changeToUppercase= (value) => {
  var newValue = value.toUpperCase();    
  setTitle(newValue);
}
```

3. Add a TextInput control and connect the onChangeText event to the changeToUppercase function. Connect also the value property to the one stored in the state and changed by the function.

```
<TextInput onChangeText={changeToUppercase} value={title} />
```

## Expected Results
Whenever you type something in the TextInput, its value becomes uppercase and the cursor is kept at the end of the text, so that you can continue writing.
Instead, the cursor is reset at the first position every time the onChangeText event is triggered, making impossible to continue writing.

## Snack, code example, screenshot, or link to a repository:
```
import React, {useState} from 'react';
import {
  View,
  TextInput,
} from 'react-native';

const App: () => React$Node = () => {

const [title, setTitle] = useState('');

const changeToUppercase = (value) => {
  var newValue = value.toUpperCase();    
  setTitle(newValue);
}

  return (
    <View>
      <TextInput onChangeText={changeToUppercase} value={title} />
    </View>
  );
};

export default App;
```

**Comment by chrisglein** [comment]
Looks like the same as #5687.
Given that this one has a repro and such I'll dupe the other one to this one.

**Comment by rectified95** [comment]
I think this is because of the way XAML behaves when setting `TextBox.Text()` programmatically.
I've created a plain XAML app that updates the contents of a TextBox in response to a button click, and the cursor also gets moved to the beginning, no matter where it was before the update.
(Toggling focus between the button and textbox preserves cursor position, so this is not caused by clicking outside the textbox.)

**Comment by rectified95** [comment]
Seems like we need to deviate from the native behavior here as it blocks some dynamic text replacement scenarios. Will try to work around it.

**Comment by rectified95** [comment]
@qmatteoq I have a PR out fixing this. Will you be able to upgrade to 0.64 to get the fix?

Btw, your example of autocapitalization can also be handled like this, which will more efficient.
`<TextInput autoCapitalize="characters" style={styles.default} />`

**Comment by qmatteoq** [comment]
Thanks @rectified95 for the hint! However, this was just a sample to show the problem. My customer is using this feature in order to auto correct phone numbers (for example, by automatically adding the international prefix as they type).
