### ISSUE TITLE
Support react-native-auth0

### ISSUE THREAD

**Issue by qmatteoq** [microsoft/react-native-windows#6787]
# Support `react-native-auth0` on RNW

## Basic Info
- Module Repo URL: [https://github.com/auth0/react-native-auth0](https://github.com/auth0/react-native-auth0)
- Target version: 0.62
- [ ] Issue exists on module repo (if so, [link]())

- [ ] Module has a Legacy/C# implementation (if so, [link]())

## Which app/customer is requesting this module?
An AppConsult customer

## In what scenarios will this module be used?
Provide authentication using Auth0 as identity provider.

## Essential Features
Authenticating the user against Autho0 as identity provider.

**Comment by chrisglein** [comment]
FYI there's also a request for Azure auth: #4148

**Comment by stmoy** [comment]
Closing. The following PR adds the implementation, but it seems like our friends at Auth0 are not interested in accepting the PR. https://github.com/auth0/react-native-auth0/pull/356
