### ISSUE TITLE
Support react-viro

### ISSUE THREAD

**Issue by soplwang** [microsoft/react-native-windows#6797]
# Support `react-viro` on RNW

## Basic Info
- Module Repo URL: [ViroCommunity](https://github.com/ViroCommunity/viro)
  - Original outdated repo URL: [Viro](https://github.com/viromedia/viro)
  - Original site: [Viro Media](https://viromedia.com)
- Target version: 0.63

- [ ] Issue exists on module repo (if so, [link]())
- [ ] Module has a Legacy/C# implementation (if so, [link]())

## Which app/customer is requesting this module?

Posemoji, Figment and many react-native AR/VR projects wants to port to Windows and HoloLens platforms.

## In what scenarios will this module be used?

Enabling AR/VR Application Development Everywhere. ARkit, ARCore, Cardboard, Daydream, Gear VR and maybe HoloLens.

## Essential Features

- REAL WORLD 3D TRACKING
  Accurately positions users and enables placement of virtual objects within their world.
- PLANE/SURFACE DETECTION
  Finds horizontal and vertical surfaces that allow users to place virtual objects.
- IMAGE/MARKER RECOGNITION
  Detects and recognizes images/markers in the user's world and determines the position.
- POWERFUL RENDERER
  PBR support, Image Based Lighting, HDR, Physics, Particles, and more.
- REAL WORLD EFFECTS
  Add physics and animation to your objects. Simulate smoke, fog, fire, and other phenomena in your scenes.

**Comment by asklar** [comment]
This will likely require someone with knowledge of hololens. Assigning to @stmoy to see how this should be prioritized.

**Comment by soplwang** [comment]
https://docs.microsoft.com/en-us/windows/mixed-reality/

Windows MR isn't only for HoloLens, but also support Surface & Surface Pro.

**Comment by stmoy** [comment]
Hi @soplwang - this looks like a super cool library! I looked a bit through the repo and it looks like this module is mostly platform-native code for iOS/Android (as opposed to some modules where the native code is just a thin wrapper). To that end, this would be a big investment for the platform team and we don't have the bandwidth to tackle this right now. 

Although we can't implement this module internally right now, we could help advise if you (or others) are looking to add Windows support. 

Adding this to the Backlog in our community module project and unassigning myself.
