### ISSUE TITLE
c# AttributedViewManager doesn's register  "attributed methods" inside base class

### ISSUE THREAD

**Issue by yingxuepeng** [microsoft/react-native-windows#6800]
If we want put some common nativeProps inside base class, such as width, color,etc... , the attributed method will not work because the AttributedViewManager only scan the "DeclaredMethod".

## Example
if we have base and child class like this( react-native-svg demo):

Base:
```C#
abstract class BaseShapeManager : MyAttributedViewManager<Shape>
{
  [ViewManagerProperty("stroke", ViewManagerPropertyType.Number)]
  public void SetStroke(Shape view, uint? jsColor)
  {
    Debug.WriteLine("BaseShapeManager SetStroke:" + jsColor);
  }
}
```

Child
```C#
class LineViewManager : BaseShapeManager
{
  public override string Name => "RNSVGLine";
  public override FrameworkElement CreateView()
  {
    var line = new Line()
    {
      X1 = 0,
      Y1 = 0,
      X2 = 90,
      Y2 = 90
    };
    line.Stroke = new SolidColorBrush(Colors.Black);
    return line;
  }

  [ViewManagerProperty("x1", ViewManagerPropertyType.Map)]
  public void setX1(ShadowElement view, JSValue x1)
  {
    Debug.WriteLine("RNSVGLine x1：" + ele.X1);
  }
}
```
Only the x1 prop methods can have debug output.

### It is because AttributedViewManager(master) line 123
```C#
// only contain Current Class Declared Method info
foreach (var methodInfo in GetType().GetTypeInfo().DeclaredMethods)
```
### I suggest to change to 
```C#
// will return both self and base class method info
foreach (var methodInfo in GetType().GetMethods())
```
Now i have to copy all the AttributedViewManager code, and change this line, is work as i expected.

## Environment
D:\workspace\rn\RnTest>npx react-native --version
4.13.1

D:\workspace\rn\RnTest>npx react-native info
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19041
    CPU: (16) ia32 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 6.05 GB / 15.94 GB
  Binaries:
    Node: 12.8.1 - D:\software\nodejs\node.EXE
    Yarn: 1.22.4 - D:\software\Yarn\bin\yarn.CMD
    npm: 6.14.4 - D:\software\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 26.0.2, 28.0.3, 29.0.3
      System Images: android-28 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.8.30717.126 (Visual Studio Community 2019)
  Languages:
    Java: 1.8.0_241 - C:\Program Files\Java\jdk1.8.0_241\bin\javac.EXE
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
    react-native-windows: 0.62.17 => 0.62.17
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by asklar** [comment]
thanks for reporting @yingxuepeng! I noticed you are using 0.62, the latest stable version is 0.63 (or you can try the 0.64 preview). I'm not sure if a newer version will fix the issue you mentioned but it's worth trying.
CC @vmoroz @dannyvv @stmoy fyi
