### ISSUE TITLE
Can we use react-native-config variables in the Package.appxmanifest?

### ISSUE THREAD

**Issue by creambyemute** [microsoft/react-native-windows#6818]
Hello there,

The Windows support for [react-native-config](https://github.com/luggit/react-native-config) was added recently and I'm already using it, though I got a question if what I'm after is possible and if so how?
We have an app which is branded and has 3 environments: Dev, Test and Production. The differences are minimal:

* Different Theme 
    * JS-Side, this is already possible
* Different API-Urls
    * JS-Side, this is already possible
* Different AppName / App-DisplayName
    * How would I achieve that?
* Different PackageName
    * How would I achieve that?
* Different App-Icon and logo on Splashscreen and Login-Screen
    * Probably just copying/moving assets before building?

**PackageName:** 
* On Android I was able to use the RN-Config variables in the gradle build script for packageName, is the same possible with RN-Windows + RN-Config? Couldn't find it on the readme.
* On iOS it's specified in the build target (for example in the Brand1-Dev Target/Scheme)

**AppName / DisplayName:** 
* On Android there is the the concept of build variants which let's you use/merge different assets/resources
* On iOS it's specified in the build target (for example in the Brand1-Dev Target/Scheme)

**Comment by creambyemute** [comment]
So I need a second project? That's a bummer. That means full-project code duplication and maintaining/keeping in sync two repositories only to change the packageName/AppName. 
Are there no build configurations like on iOS/Android to change stuff like that?

We need do be able to automate this so maintaining two projects doesn't sound quite right.

**Comment by asklar** [comment]
You don't need a separate repo. Just a separate project within the same solution (in the same repo)

**Comment by creambyemute** [comment]
@asklar Ah alright, so like a myAppBrand1 and myAppBrand2 folder instead of just the myApp project folder within the solution?

Can I tell the (command-line) build which of those two to build? Or would I add a (pre)build-step which would copy the correct Manifest and vcxproj before building?

**Comment by asklar** [comment]
if they are just separate projects within the same SLN file, then the `run-windows` command will build both (it will no-op if one of the projects don't need to be built). You don't need to copy any files before every build, just a single time, and then in the copied vcxproj you'd update the reference to the manifest to point to the new one. You'd push that into your repo and as far as the build process knows, it just sees two app projects, they just happen to share all of the code files.

**Comment by creambyemute** [comment]
@asklar Thanks for the clarification. I've been trying to get it working since friday and have mostly made it but the proposed solution didn't quite work. I'll write down my findings here:

### Example 1 (Not working)
**Duplicating the `appName/` folder inside `windows/` (the whole folder containing .vcxproj and Manifest)**

After duplicating and replacing the bits that needed to be replaced I was able to build from _within VS2019_ by selecting the Build-Target and was also able to `Project --> Publish --> Create App-Package`.

The Build/Run command on the command line didn't work anymore though.
First it complained about multiple .vcxproj (projects) available and I should edit the react-native-config.
So I appended the `--proj windows/appName/appName.vcxproj` to run-windows but the build then failed while building the solution.

Not sure why that worked from within VS2019 but not the command-line.

### Example 2 (Not working)
**Duplicating only the `.vcxproj`, `.vcxproj.filters` and `.appxmanifest`**

After duplicating, renaming and adapting some bits so it takes the correct `.appxmanifest` I was not able to run it from within VS2019 anymore due to a build-error but on the command-line the build itself worked, but took the wrong manifest/.vcxproj and thus displayed a incorrect appname, logo and packagename.

### Example 3 (Working)
**Duplicating only the `.appxmanifest`  as well as Assets (no .vcxproj duplication)**

The last thing I tried was to only duplicate the `.appxmanifest`. This approach requires copying the correct Assets + manifest before running/building.

* Duplicate .appxmanifest twice, rename and adapt name etc (so I have the default `Package.appxmanifest`, `PackageBrand1.appxmanifest` and `PackageBrand2.appxmanifest`)
* Duplicate Assets folder twice (so I have the default `Assets/`, `AssetsBrand1` and `AssetsBrand2`)
    * The AssetsBrand1 and AssetsBrand2 only contain the different image assets (app icon, logo, store logo, splash), nothing else so we can `merge` it into the "managed" Assets/ folder
* Before building/running:
   * The `.env` (for react-native-config library) file is being overwritten with the correct env file (for example .env.brand1.dev to .env)
   * The correct Assets folder is copied into the default `Assets/` folder (for example `cp -R windows/appName/AssetsBrand1/. windows/appName/Assets`
   * The .appxmanifest is being overwritten with the brand1/brand2 .appxmanifest

That way now works for both: Running from command-line as well as running/building/publishing from within VS2019.
I have one last question though as I couldn't find it anywhere in the docs nor in the 14 pages of issues I searched through

How to build (not run) from the command-line so we get something we can then sign for sideloading or for publishing?
What's the process of invoking the (VS2019 GUI) `Project --> Publish --> Create App-Package` from command line so we can set up a pipeline for ci/cd?

Shouldn't that be documented on [Building a standalone React Native Windows App](https://microsoft.github.io/react-native-windows/docs/getting-started#building-a-standalone-react-native-windows-app)? Or is using CI/CD uncommon for windows projects?

**Comment by asklar** [comment]
@creambyemute in order to build and not run you can simply run `npx react-native run-windows <other options> --no-launch`. This is documented in the help for `run-windows` and in the CLI's readme but I agree we don't talk about it in the docs so I've added a link: https://github.com/microsoft/react-native-windows-samples/pull/356.
It sounds like you are unblocked so I'm going to close this, feel free to let us know if you still need help!
