### ISSUE TITLE
Move docs from samples repo to RNW repo

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#6827]
After the meeting on 1/6 we decided it would be a good idea to move the docs to the code repo so that API changes can have an accompanying doc change in the same PR.

There needs to be some work to figure out how to do versioning; ideally we'd like to have only one copy of the docs per branch (i.e. in master, 0.63-stable, etc.) but then that means we need something to fetch the docs for all versions before we build the website.

**Comment by chrisglein** [comment]
Big challenge is to figure out how to feed into Docusaurus's version system from a set of github branches. It's not a native match. So while we all want the docs closer to the source I think there's some design needed to figure out how we can do that. Need some time on this to make a recommendation.

**Comment by chrisglein** [comment]
Notes from planning poker:
> The reason to do this would be if it helps cut on release execution time. 3 years ago we moved the docs outside of the repo. We don't want to put it into the core repo to maintain agility. There are some questions about how Docusaurus is panning out over time (do we evaluate a different system, docs.microsoft.com or otherwise - also we have a pending update to v2). We discussed this on 1/6/21... but there are notes and no recording :( (turns out that day came with distractions).
We should go back to the drawing board and discuss what's our efficient+current doc strategy. Won't Fix this as written.
