### ISSUE TITLE
react-native-windows-init doesn't specify that --projectType is 0.64+ (was" --projectType  switch ignored when creating RNW solution)

### ISSUE THREAD

**Issue by BartoszKlonowski** [microsoft/react-native-windows#6829]
## Environment
1. `npx react-native --version`: **4.10.1**
2. `npx react-native info`:
```
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 14.52 GB / 23.76 GB
  Binaries:
    Node: 12.9.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: Not Found
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^16.13.1 => 16.13.1
    react-native: ^0.63.2 => 0.63.2
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
1. Print the *help* of RNW init:
`npx react-native-windows-init --help`
And check the `--projectType` switch description:
>   --projectType  The type of project to initialize.
                               [string] [choices: "app", "lib"] [default: "app"]

2. Create RNW solution with `--projectType` set to *"lib"*:
`npx react-native-windows-init --version "0.63.15" --projectType "lib" --overwrite`

## Expected Results
RNW solution is created with the main project configured as *library*
**NOTE:** --help results does not say whether it will be static or dynamic library, but that's not a big issue.

## Actual Results
RNW solution is created with the main project configured as *Application .exe* even if *lib* has been chosen:
![obraz](https://user-images.githubusercontent.com/70535775/103877545-86843700-50d5-11eb-87f5-cb44f1279163.png)

Also the app certificate and assets are generated, while they should not be required for a library.

---

**NOTES:**

1. It is possible to manually switch the type of project to a library, but this behavior is misleading. CLI switches should not be ignored.

2. The official documentation at the [Install the Windows extension](https://microsoft.github.io/react-native-windows/docs/getting-started#install-the-windows-extension) part does not mention the `--projectType` switch at all, but the `--projectType` switch implementation seems to be there in the source code:
https://github.com/microsoft/react-native-windows/blob/e8d6ada8d776452f6c94c481a62c27cb323ced05/packages/%40react-native-windows/cli/src/generator-windows/index.ts#L135-L149

**Comment by NickGerleman** [comment]
I don't think the underlying flag is supported until 0.64, so the flag would be passed from react-native-windows-init to the react-native-windows project generator but ignored.

https://github.com/microsoft/react-native-windows/issues/6445 tracks moving command flag options out of react-native-windows-init, which would prevent this sort of mismatch in the future. In the meantime, maybe it would make sense to add something like "(0.64+ only)" to the help option. This is what we did for Hermes flags. 

FYI @jonthysell

**Comment by BartoszKlonowski** [comment]
Thank you for the explanation!

So the question is: How can one achieve creating the dynamically linked library for the existing module?
I've been following the [guide](https://microsoft.github.io/react-native-windows/docs/native-modules-setup#adding-windows-support-to-an-existing-library) but after updating the *package.json* the docs says that all further steps should be covered by
`npx react-native-windows-init`.

I've created the project manually following the steps described further, but I'm still thinking about easier setup solution
(currently unavailable due to lack of `--projectType` support until 0.64?).

---

If there's nothing to be done but to wait for 0.64, then you can assign me to this issue - I can update the *help* output in the meantime.

**Comment by NickGerleman** [comment]
@jonthysell will have a better idea of the best option here.

If you want to try the new workflow, you could add a preview version of react-native-windows (e.g. 0.64.0-preview.5) instead of `latest`. That leaves you with a preview version of RNW though (it's likely we will release it at the end of the month).

**Comment by chrisglein** [comment]
Sounds like we need to update the documentation to be more clear about version support, as well as some deeper changes about how we handle unsupported command line arguments.

**Comment by jonthysell** [comment]
For 0.61, 0.62, and 0.63, the docs include version-specific setup steps, and already say:

> These steps are unnecessary as of 0.64, as react-native-windows-init will create the correct projects and solutions for you. However we have retained the manual process here for developers who are unable to use the CLI.

We could update the text to be something like:

> These are the version specific manual steps for setting up the native projects and solutions. If you upgrade your module to RN >= 0.64, the `react-native-windows-init` command can create the correct projects and solutions for you, using the `--projectType lib` flag.

I also think updating the CLI to say 0.64+ for the flag is the best move.
