### ISSUE TITLE
red box error when running Playground project on Xbox One

### ISSUE THREAD

**Issue by matthargett** [Microsoft/react-native-windows#684]
Following instructions here:
https://msdn.microsoft.com/windows/uwp/xbox-apps/getting-started

Using latest master (f07540a479937322d17f8208a330413add33b651).

Build and deploy works fine, but red box appears after app tries to load the JavaScript bundle:
![win_20160909_14_21_06_pro](https://cloud.githubusercontent.com/assets/1550766/18403282/abe15274-7698-11e6-9bf9-47c7a32b790d.jpg)

**Comment by rozele** [comment]
Related to https://github.com/ReactWindows/react-native-windows/issues/358.  We need a way of setting the dev server endpoint from an app, but in the meantime, you can just configure it statically in DevInternalSettings.cs

**Comment by rozele** [comment]
Also related to https://github.com/ReactWindows/react-native-windows/issues/683.

**Comment by rozele** [comment]
Closing - known issue, we just need to provide an option to configure the dev support base URI.
