### ISSUE TITLE
ReactNotificationService does not send notifications from app to modules

### ISSUE THREAD

**Issue by vmoroz** [microsoft/react-native-windows#6840]
Internally the `ReactNotificationService` has a parent-child relationship between `ReactNativeHost` `ReactNotificationService` and `ReactInstance` `ReactNotificationService`. It currently propagates notifications from the child to parent, but not vice versa.
We must fix this issue. The goal of the parent-child relationship was to auto-unsubscribe all `ReactInstance` `ReactNotificationService` subscription after the instance unload. We may need to reconsider the way we implemented this feature.

**Comment by NickGerleman** [comment]
Some more context here https://teams.microsoft.com/l/message/19:d18a996a978f4ef8a55443c75c293b35@thread.skype/1610060496991?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=8034415f-bc0a-4b5d-9453-78ee27e16b22&parentMessageId=1610060496991&teamName=React%20Native%20%40Microsoft&channelName=Developer%20Help&createdTime=1610060496991

**Comment by chrisglein** [comment]
See #6836 for more repro context.

**Comment by vmoroz** [comment]
Fixed by #6877
