### ISSUE TITLE
Update version of  C++/WinRT to 2.0.201201.7 or later

### ISSUE THREAD

**Issue by vmoroz** [microsoft/react-native-windows#6841]
The version 2.0.201201.7 is adopted internally by some Microsoft teams. We should do the update too.
According to @kennykerr it has the following notable changes: 
- Many coroutine improvements
- C++20 coroutine conformance
- Clang conformance improvements
- try_capture and try_create_instance helpers (https://github.com/microsoft/cppwinrt/pull/663)
- Improved compile-time and run-time diagnostics
- Add value type support to as() and try_as() (https://github.com/microsoft/cppwinrt/pull/695)
- Enable conversion between winrt::clock and std::chrono::system_clock (https://github.com/microsoft/cppwinrt/pull/698)
- Add multi-threaded collections (https://github.com/microsoft/cppwinrt/pull/692)
- Add try_get_activation_factory overloads with class name (https://github.com/microsoft/cppwinrt/pull/769)
- Support boxing delegates

**Comment by chrisglein** [comment]
I remember there being some things we needed to do to get community modules on the same version otherwise there were issues. @jonthysell where are we with mixed-cppwinrt versions? Is that a problem still? What should our policy be for updating?

**Comment by jonthysell** [comment]
AFAIK it's not really an issue anymore, as long as the projects are properly set up with the whole `$(SolutionDir)\packages` setup.

IIRC camera still targets the version used in 0.62, and still works with 0.63 and 0.64, despite their use of a newer version.

And starting with 0.64, my hope is people use `react-native-windows-init` to create their project, and perhaps later even to partially update it (as I have done to stamp the latest template files), such that modules will get the newer cppwinrt versions too.
