### ISSUE TITLE
Exception when putting Text inside of an inline view

### ISSUE THREAD

**Issue by rigdern** [microsoft/react-native-windows#685]
The exception occurs because the `isInAParentText` flag never gets reset back to false. Consequently, the topmost Text in an inline view gets created as an `RCTVirtualText` instead of as an `RCTText`. In the RN UWP implementation, this is illegal because an `RCTVirtualText` node can only be a child of an `RCTText` or `RCTVirtualText` node and in this case it's a child of a view.

**Comment by rozele** [comment]
@rigdern How does iOS handle this?

**Comment by rozele** [comment]
It's gross - but this is technically a workaround that can be done at the application level:
```
class Untext extends Component {

  static childContextTypes = ViewContextTypes;
  
  getChildContext() {
    return {
      isInAParentText: false,
    }
  }

  render() {
    return this.props.children;
  }
}

class Example extends Component {
  render() {
    return (
      <View>
        <Text>
          Outer Text
          <Text> </Text>
          <Untext>
            <View style={{height: 20, width: 85, borderWidth: 2}}>
              <Text>Nested Text</Text>
            </View>
          </Untext>
        </Text>
      </View>
    );
  }
}
```

**Comment by rozele** [comment]
@rigdern any updates on how this is handled on iOS? Will close if it's not still a major issue.
