### ISSUE TITLE
Support react-native-tab-view / MaterialBottomTabNavigator / MaterialTopTabNavigator ?

### ISSUE THREAD

**Issue by creambyemute** [microsoft/react-native-windows#6867]
# Support `react-native-tab-view` on RNW

This would make creating TabBars (and the appropriate scene/page) or Tab-Navigation (with React-Navigation) a lot easier and comfortable to achieve.

## Basic Info
- Module Repo URL: [react-native-tab-view](https://github.com/satya164/react-native-tab-view#readme)
- Target version: ? Latest ?
- [ ] Issue exists on module repo
- [ ] Module has a Legacy/C# implementation

## Which app/customer is requesting this module?
Community: Used in React-Navigation, react-native-tab-view can be used as a standalone component (without React-Navigation)

## In what scenarios will this module be used?
You want to display either a TabNavigator (react-native-tab-view + React-Navigation) or just a TabBar which renders the appropriate scene (only react-native-tab-view)

## Essential Features
* Functional TopTabNavigator
* Functional Pager for react-native-tab-view

## Current Situation
1. React-Native-Tab-View offers functionality to render Tabs as well as a corresponding scene but none of the available Pagers work on RN-Windows.
2. React-Navigation offers 3 default Navigators for TabNavigation: `createBottomTabNavigator`, `createMaterialBottomTabNavigator`and `createMaterialTopTabNavigator`
2.1. `createBottomTabNavigator` does not use react-native-tab-view and **works**
2.2. `createMaterialBottomTabNavigator` and `createMaterialTopTabNavigator` use react-native-tab-view and **do not work** due to the above described scenario + some RN-Gesture-Handler and RN-Reanimated stuff included in those two Navigators.

## Desired Outcome ?
* A Pager for react-native-tab-view which works
* A TopTabNavigator in react-navigation for Windows which works and is similiar styled to the MaterialTopTabNavigator
    * I have a simple implementation of that, would just need to make indicatorColor a passable prop)

**Comment by stmoy** [comment]
@creambyemute - thank you for filing this issue! I very briefly looked at the react-native-tab-view repo, and it looks to be entirely TypeScript + JavaScript (ie. no native code). That would indicate that it might "just work". If it doesn't it could either be because it's calling into platform APIs that RNW hasn't yet implemented, or it has dependencies on other modules that haven't yet been implemented. I'm not super familiar with react-native-tab-view, so I'm wondering if you might have more insight into what specifically is broken (since it sounds like you've tried it already).

**Comment by creambyemute** [comment]
@stmoy  It seems to be related to RN-Gesture-Handler things.

You can very easily reproduce it by just using the TabView with the Default-Pager on RN-Windows.
Or by providing the ScrollPager as Pager Component to TabView. Then it'll open/show, but no interactions possible.

**Comment by creambyemute** [comment]
@stmoy Just a heads up: material-top-tab-navigator seems to work now when upgrading react-native-tab-view to Version >= 3.5.0.

I've tested it with the following React-Navigation package versions:
* react-native-tab-view 3.5.0/3.5.1
* React-Navigation latest V5 versions
* @react-navigation/native": "^6.1.6" + "@react-navigation/material-top-tabs": "^5.3.19"
* @react-navigation/native": "^6.1.6" + "@react-navigation/material-top-tabs": "^6.6.2"

We can close this 👍
