### ISSUE TITLE
Support Share API

### ISSUE THREAD

**Issue by rectified95** [microsoft/react-native-windows#6871]
RN vnext includes the Share API - https://reactnative.dev/docs/next/share - which brings up the 'Share with..' context menu listing apps (eg. whatsapp, fb messenger) to share content with. 

Is there an equivalent in UWP and should we try to match it at all?

**Comment by rectified95** [comment]
This looks relevant:
https://docs.microsoft.com/en-us/windows/uwp/app-to-app/share-data

**Comment by chrisglein** [comment]
This API was designed for the mobile conventions around share, doesn't map as cleanly to Windows. While this will be a cross platform gap for RNW, it's more accurate to say this isn't planned rather than leave it parked on the backlog. We can bring it back if there's a clearer mapping.
