### ISSUE TITLE
Need a way to turn off text scaling (set IsTextScaleFactorEnabled to false) for controls--or ideally the entire app

### ISSUE THREAD

**Issue by Murtaya** [microsoft/react-native-windows#6890]
# Proposal: Accessibility: Need a way to turn off text scaling (set IsTextScaleFactorEnabled to false) for all text-based controls--or ideally the entire app.

## Summary
Our app needs a way to turn off UWP text scaling at a global level.  By default UWP lets OS text scaling factor changes change every text-based control in the app, but as our app relies on app scaling (instead of text scaling), automatic text scaling causes accessibility issues.  Standard UWP has the ability to set this at a global level and propagate down to every control; it doesn't look like RNW currently exposes this ability, and it only exposes the switch on some of its text-based controls--not all--so even turning text scaling off at every text instance in the app is not possible.

## Motivation

With Windows accessibility moving from text scaling to app scaling, apps are being designed to support the latter.  However, high-density desktop apps can run into issues when trying to also support text scaling.  The advice from Microsoft Accessibility is to just rely on app scaling and disable text scaling for the entire app.

While UWP easily supports this at a global scale (for example, you can set IsTextScaleFactorEnabled to false on the MainPage.xaml and disable it for the entire app), there's no built-in way to do this in RNW without modifying the base code (which complicates RNW upgrades for our product).

As-is, there doesn't seem to be a way to turn off text scaling at a global level in RNW (not having a global page like standard UWP apps, and trying to inject a Control at the root view and turning off IsTextScaleFactorEnabled on it does not propagate down the generated XAML tree).  As such, we either have to turn off each instance of a text control for those that have the "allowFontScaling" property, or otherwise manually inject code into the text-based view managers to turn off text scaling for each of them.  Besides making future upgrades difficult, making one off changes like this to the RNW base code is not very maintainable: odds are if another new text control was added, they'd miss out on adding this line and create a new accessibility bug in the app.

Without making these changes to address this accessibility issue (either with an official RNW change our our "hacks" to our local RNW code), our app will have reduced accessibility scores, which creates issues and might even block us from shipping it.

## Basic example

There is already some functionality to set this property on the TextInputViewManager and TextViewManager; the RNW property is "allowFontScaling":

 if (propertyName == "allowFontScaling") {
      if (propertyValue.isBool())
        control.IsTextScaleFactorEnabled(propertyValue.asBool());
      else if (propertyValue.isNull())
        control.ClearValue(xaml::Controls::Control::IsTextScaleFactorEnabledProperty());
        }

However, this is missing from RawTextViewManager, which prevents us from turning it off on related text-based controls.

That said, turning this feature off at every text control instance is not very efficient or maintainable if you just want to turn it off for the entire app.  Ideally there would be a global boolean or way of turning it off.

## Open Questions

1.) Design: Add a single app-wide boolean property that disables text scaling for the entire app, or add properties to each of the remaining text-based control that don't have the "allowFontScaling".  While both would be useful for different reasons, apps like ours would benefit more from the single, app-wide switch.  But should both be supported?

**Comment by chrisglein** [comment]
Potential workaround: Could include setting the native API for this on the XAML root.
If that works, then I don't think we'll need a RNW option for this. Native API should suffice.

**Comment by chrisglein** [comment]
@Murtaya can you try that on the MainPage.xaml and if it doesn't work reopen and we can talk through other options.

**Comment by Murtaya** [comment]
Unfortunately our project doesn't have a MainPage.xaml--we're creating the page dynamically in code.  This is something new I discovered since posting (we have three different teams working on our project, and it has evolved from an Electron project).

As such, we're probably in a very rare space and will need a custom solution, so it's probably not a big concern for most RNW projects (and you can probably close this request).

For now, I've addressed this by modifying each text-based control's viewmanager.  It requires more work when we do upgrades, but it should work for us for now.  Thanks-

**Comment by acoates-ms** [comment]
@Murtaya, If you are creating the Page in code, couldn't you just set that property on the Page in code too?
