### ISSUE TITLE
Use AzDO version of python

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#6903]
The newly added dependency on Python is using a python distro that gets installed as part of the CI build.
We should instead be using the pre-installed Python install (and update rnw-dependencies.ps1 which currently skips checking Python in CI).

**Comment by NickGerleman** [comment]
We are now running part of the build on the WinDev pool whose images don't include as much. E.g. we started needing to reinstall yarn on them.

May encounter the same thing here if it isn't part of the WinDev image.

**Comment by chrisglein** [comment]
@dannyvv Do you know if the new pool machines have python pre-installed? If not, then no action here and we can close.
