### ISSUE TITLE
Add thread checks to XamlUIService::ElementFromReactTag

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#6913]
Garrison ran into some timing issues related to the thread affinity changes in 0.64. Sample code showed that we were accessing UIManager state on the JS thread. This is unsafe, but we don't fail loudly if this happens.

```c++
winrt::fire_and_forget TitleBarModule::pushTitleBar(int64_t reactTag) noexcept {
    auto uiService = XamlUIService::FromContext(m_reactContext.Handle());
    auto element = uiService.ElementFromReactTag(reactTag);
    auto uielement = element.try_as<winrt::UIElement>();
    if (uielement) {
        co_await winrt::resume_foreground(element.Dispatcher());
        winrt::Window::Current().SetTitleBar(uielement);
        m_stack.push_back(uielement);
    }
```

**Comment by aschultz** [comment]
Which thread should XamlUIService be accessed on? The UI thread? What if there are multiple windows (and thus multiple UI threads)?

**Comment by acoates-ms** [comment]
A react instance can only have one thread.  If you have multiple windows with multiple UI threads you'd need multiple react instances.   You would use the UIDispatcher property from the ReactContext to get to the correct UI thread in a generic way.

**Comment by aschultz** [comment]
@acoates-ms It looks like UIDispatcher is a ReactDispatcher object, not a DispatcherQueue or CoreDispatcher. Are there any awaitable helpers like winrt::resume_foreground for use with co_await?

**Comment by acoates-ms** [comment]
Good question.  @vmoroz would know better.

**Comment by NickGerleman** [comment]
If we don't, you could also save the apartment_context from the UI thread to resume to.

E.g. https://github.com/microsoft/react-native-windows/pull/6109/files

Would be nice to support it without doing something like that if we don't.

**Comment by vmoroz** [comment]
@aschultz , @acoates-ms, @NickGerleman, we currently do not have support for the co-routines in our C++ API. We should add it. It is probably too late for 0.64 though.

**Comment by aschultz** [comment]
@NickGerleman That wouldn't work in this case, since we start on the JS thread and we need to move to UI before we can do anything.

@vmoroz That's fine, I just wanted to check. It's easy enough for me to build my own helper for now.

**Comment by NickGerleman** [comment]
@aschultz by default the UIDispatcher corresponds to the thread where the ReactNativeHost is created. When creating the instance, you can pass variables to the ReactContext through the PropertyBag on ReactInstanceSettings.

I.e. you could do something like grab the apartment_context before instance initialization, and it would be passed to all of your native modules on the JS thread.

That general pattern can be used if you need native modules to access UI thread affined object that cannot be created lazily.

It's a bit smelly to pass a parallel thread context to the builtin dispatcher, but could maybe be useful in confined scenarios. Not sure what ordering guarantees would look like with different access to the queue (though I think the ReactDispatcher iirc posts to DispatcherQueue under the hood).
