### ISSUE TITLE
Dynamically identify net native version at build time 

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#6926]
> Today we check for a couple of versions, which means every time VS updates there is a risk that they will break this for all versions of RNW that support ConsumeCSharpModules. Ideally we make this smarter by adding some logic either in the targets file or in the CLI to locate the right version that is installed on the system.

Related: #6924

**Comment by chrisglein** [comment]
This is the longer term that avoids the hardcoded versions in the workaround.
