### ISSUE TITLE
AppState Change Listener Not Working on RNW

### ISSUE THREAD

**Issue by emmanuj** [microsoft/react-native-windows#6943]
Registering a change listener like below does not seem to work on React Native Windows:

```
export const useAppState = () => {
  const [appState, setAppState] = useState(AppState.currentState);

  const changeHandler = useCallback(
    (currentState: AppStateStatus) => {
      console.log(
        `current app state ${currentState} | previous app state ${appState}`,
      );
      setAppState(currentState);
    },
    [appState],
  );

  useEffect(() => {
    AppState.addEventListener('change', changeHandler);
    return () => AppState.removeEventListener('change', changeHandler);
  }, [changeHandler]);
  return appState;
};
```

I'm using hooks here but I tested in a class component and that doesn't make a difference

## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`: 5.0.1-alpha.0
2. `npx react-native info`:
```
System:
    OS: Windows 10 10.0.19042
    CPU: (6) x64 Intel(R) Xeon(R) Gold 6226 CPU @ 2.70GHz
    Memory: 2.54 GB / 12.00 GB
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
    Watchman: 20200816.222424.0 - C:\libs\watchman-v2020.08.17.00-windows\watchman-v2020.08.17.00-windows\bin\watchman.EXE
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.8.30907.101 (Visual Studio Professional 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: ^0.64.0-rc.1 => 0.64.0-rc.2
    react-native-windows: 0.64.0-preview.7 => 0.64.0-preview.7
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Register AppState change listener like above
2. Call the hook in your App.tsx
3. Run the app then minimize the app window. 
4. Notice no logs in the console.

## Expected Results
When I minimize the window, I expected to see:

> current app state background | previous app state active

## Troubleshooting
FWIW, the background events work in App.xaml.cs:

```
this.EnteredBackground += (object sender, EnteredBackgroundEventArgs args) =>
{
    appState = "background";
    Debug.WriteLine(appState);
};

this.LeavingBackground += (object sender, LeavingBackgroundEventArgs args) =>
{
    appState = "active";
    Debug.WriteLine(appState);
};
```

## Example Project
https://github.com/emmanuj/RNWPlayground

**Comment by asklar** [comment]
the native side seems to not be implemented:
```cpp
void AppState::AddListener(std::string && /*eventName*/) noexcept {
  // noop
}

void AppState::RemoveListeners(double /*count*/) noexcept {
  // noop
}
```

**Comment by emmanuj** [comment]
@asklar The Android version does the same thing so I'm guessing that's not the problem?
https://github.com/facebook/react-native/blob/6e6443afd04a847ef23fb6254a84e48c70b45896/ReactAndroid/src/main/java/com/facebook/react/modules/appstate/AppStateModule.java#L114
```
@Override
  public void addListener(String eventName) {
    // iOS only
  }

  @Override
  public void removeListeners(double count) {
    // iOS only
  }
```

**Comment by asklar** [comment]
@emmanuj - looked at this in more depth, I see what's happening (we're registering for events from the wrong thread). I'll send a PR out, thanks for reporting!

**Comment by chrisglein** [comment]
@asklar Does this indicate there are other modules that might have a similar problem?
Sounds like there's a request to port to 0.63. Tagging for that.
