### ISSUE TITLE
UIScheduler_WinRT is tied to system XAML

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#6950]
this helper class uses Windows::System::DispatcherQueue and related, which won't work with WinUI 3; need to just use the aliased namespace.

**Comment by chrisglein** [comment]
Specific example related to #6805 and #2557.

**Comment by vmoroz** [comment]
@chrisglein, I have closed the #2557. The #6805 is still opened because it applies to the direct use of Windows::System::DispatcherQueue in unit tests.
