### ISSUE TITLE
How do i run a node server ? 

### ISSUE THREAD

**Issue by hb1998** [microsoft/react-native-windows#6965]
I want to run a node server that will expose rest-API .
I'm migrating from electron, in which I had the same setup, where my frontend is an angular app and backend is a node express app.

**Comment by chrisglein** [comment]
This is a question I think a number of people coming from Electron will be asking. We should put together some help on that. @acoates-ms can you either provide some detail or find someone who can?

**Comment by hb1998** [comment]
> This is a question I think a number of people coming from Electron will be asking. We should put together some help on that. @acoates-ms can you either provide some detail or find someone who can?

any updates ?

**Comment by jonthysell** [comment]
The model in RN is different - you run all of your JS front-end code within your app (which you'll have to rewrite from Angular to React Native). The closest thing you could do is create a native module (that either runs your node server) and responds, and the closest example we have is [AppServiceDemo](https://github.com/microsoft/react-native-windows-samples/tree/main/samples/AppServiceDemo) where a Win32 app is running that the RNW app can communicate with.
