### ISSUE TITLE
Freshly generated C# app fails to start

### ISSUE THREAD

**Issue by nsab1n** [microsoft/react-native-windows#6975]
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`: 4.13.1
2. `npx react-native info`:
System:
    OS: Windows 10 10.0.17763
    CPU: (4) x64 Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz
    Memory: 4.98 GB / 15.89 GB
  Binaries:
    Node: 12.9.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.17763.0, 10.0.18362.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.8.30804.86 (Visual Studio Professional 2019)
  Languages:
    Java: Not Found
    Python: 3.7.8
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
    react-native-windows: 0.63.19 => 0.63.19
  npmGlobalPackages:
    *react-native*: Not Found

What SDK version are you building for? Choose from 10.0.15063, 10.0.16299, 10.0.18362, etc.
- Target Platform Version(s): Not sure. 10.0.17763.0, 10.0.18362.0 based on the above output?
What device(s) are you targeting? Choose any from Desktop, Xbox, Hololens)
- Target Device(s): Desktop
Which version of Visual Studio are you using? Specify Visual Studio 2017 or Visual Studio 2019
- Visual Studio Version: Visual Studio 2019, 16.8.3
Which build configuration are you running? Choose from Debug, DebugBundle, Release, ReleaseBundle 
- Build Configuration: Debug, x64/x86

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Ran the following in console:
```
npx react-native-init myProject --template react-native@^0.63.2
cd myProject
npx react-native-windows-init --overwrite --language cs --version 0.63.19
yarn start
```
3. Opened myProject.sln in Visual Studio, set build to Debug/x64 and started without debugging
4. myProject app opens, but only shows a white window (no content from the React app). If I run using `react-native run-windows`, the app seems to close before the react native server has finished creating the bundle.

If I set the debug properties for myProject.sln to Mixed (Managed and Native) and start the solution with debugging, I sometimes hit this exception:
```
Exception thrown at 0x00007FFA5BAD5250 (Microsoft.ReactNative.dll) in testapp2.exe: 0xC0000005: Access violation reading location 0x0000000000000000.
```
The call stack from Visual Studio is as follows:
```
Microsoft.ReactNative.dll!winrt::impl::consume_Windows_UI_Xaml_IUIElement10<winrt::Windows::UI::Xaml::FrameworkElement>::ActualSize() Line 3031
 	Microsoft.ReactNative.dll!Mso::React::RedBox::ShowNewJSError() Line 134
 	Microsoft.ReactNative.dll!Mso::React::DefaultRedBoxHandler::showTopJSError::__l2::<lambda>() Line 516
 	Microsoft.ReactNative.dll!Mso::Details::FunctionObjectWrapper<void <lambda>(void),void>::Invoke() Line 165
 	Microsoft.ReactNative.dll!Mso::QueueService::InvokeTask(Mso::Functor<void __cdecl(void)> && task, std::optional<std::chrono::time_point<std::chrono::steady_clock,std::chrono::duration<__int64,std::ratio<1,1000000000>>>> endTime) Line 210
 	Microsoft.ReactNative.dll!Mso::TaskDispatcherHandler::Invoke() Line 166
```
I also see this error in the Debug output in Visual Studio:
```
windows\advcore\winrt\uisettings\uisettings.cpp(767)\Windows.UI.dll!00007FFACB9A3147: (caller: 00007FFA5BA7E22D) LogHr(4) tid(5634) 80070002 The system cannot find the file specified.
```
Are there any more logs I can take a look at?

## Expected Results
I actually set up react-native for windows successfully and got the template app working without much issue a few weeks ago. Perhaps a windows update is to blame?

I also ran `npx react-native run-windows --logging`, but I didn't see any build issues and the app window closed without displaying any content.

## Snack, code example, screenshot, or link to a repository:
I haven't made any changes to the files written by the basic build scripts.

**Comment by NickGerleman** [comment]
The specific crash here happens when running dev tooling on a Windows 10 version prior to 19H1/1903. RNW 0.64 (still in preview) fixes this crash, but there will still be a degraded experience when using older operating systems. Would be best to update if possible.

**Comment by nsab1n** [comment]
Great, 0.64 works! But thanks for the prompt to ask my organisation to update my Windows installation, I was running version 1809 for some reason. And thanks for RNW!
