### ISSUE TITLE
Support background colors and borders on <Text> components

### ISSUE THREAD

**Issue by rigdern** [microsoft/react-native-windows#698]
These features work on iOS and Android.

**Comment by rozele** [comment]
These are not available features of the UWP RichTextBlock implementation.  This would have to be done in JavaScript to simulate, by putting a view behind the text.  Of course, it would not support background colors of virtual text nodes.
________________________________

**Comment by Pokute** [comment]
I did use some time to try and implement a glow for text natively. I was successful for many elements, but I think it was RichTextBlock which proved to be very complicated to implement it for. Basically required multiple different render operations combined to make a mask from which to generate the glow.

**Comment by rozele** [comment]
@Pokute any sample code or other details you'd like to share?
