### ISSUE TITLE
Windows-Search shows wrong Icon (the default Placeholder instead of the actual Icon)

### ISSUE THREAD

**Issue by creambyemute** [microsoft/react-native-windows#6981]
Hey there,

I've used the Asset Generator in VS2019 yesterday to generate the different Asset/AppIcon/SplashScreen scales and it worked pretty well but I'm fighting with a problem on my W10 machine.

The AppIcon displayed in the Windows-Search is wrong. It still displays the Placeholder (grey rect).
The 'Recently added', TaskBar etc though show the correct Icon.

I've sent the side-loading bundle to another Computer and there the Search-Icon is correct so I guess it's a caching Problem?
I tried uninstalling the app, cleaning + rebuilding the W10 IconCache and rebooting multiple times to no success.

Do you have a clue why this might happen?

**Comment by asklar** [comment]
It sounds like this might be a problem unrelated to React Native Windows, could you maybe file this on the [windev](https://github.com/microsoft/windev) repo
