### ISSUE TITLE
Fix compile warning C4267 and C4100 in FB's TurboModule code.

### ISSUE THREAD

**Issue by dannyvv** [microsoft/react-native-windows#6986]
Discussed in PR: #6984

When fixed, pleae remove the disablewarning from `vnext\Microsoft.ReactNative.Cxx\Microsoft.ReactNative.Cxx.vcxitems` as well.

**Comment by asklar** [comment]
Related to #6918

**Comment by acoates-ms** [comment]
This should help:
https://github.com/facebook/react-native/pull/31002
