### ISSUE TITLE
Make usewinui3 a build-time switch for app/libs

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#6993]
Today when a new app or lib is created, you have to choose between system xaml (default) or winui3.
We should instead write the scaffolding in a way that allows esp. modules to dual-compile as a way to soften the blow of an API break w.r.t. xaml --> winui

**Comment by asklar** [comment]
keeping on triage to bring it up again

**Comment by chrisglein** [comment]
Do we want some indication on RN directory or RN gallery of which modules support WinUI3? Directory doesn't have space for this metadata, but we could add it? @stmoy, thoughts?
