### ISSUE TITLE
New module project is missing JSI.Universal project

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#6997]
create new lib, try to build it from VS, it's missing the JSI.Universal project in the SLN

**Comment by NickGerleman** [comment]
Project removed with https://github.com/microsoft/react-native-windows/pull/6783/files

Project should be removed from `MyLib.sln` template with the change. Are you seeing a build issue? Seems like potential version mismatch?

**Comment by asklar** [comment]
- [ ] Need to ensure CLI is testing that libs build properly
will add the commands/package.json, heads up @jonthysell
