### ISSUE TITLE
Hot reload is broken 

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#6998]
- Run an app that loads a view manager module (debug mode w/metro)
- change the app code
- get an error saying "tried to register two views with the same name"

![image](https://user-images.githubusercontent.com/22989529/106383443-d7a4e500-637a-11eb-8684-7de8cf871251.png)

**Comment by NickGerleman** [comment]
This means a call to "requireNativeComponent" is happening twice, and the JS for the ViewManager isn't quite correct. 

Native components should be exported from their own modules to avoid fast refresh trying to re-setup global state. There's some good react-native docs on fast refresh talking about side effects, and some conversation on this exact issue here: https://teams.microsoft.com/l/message/19:d18a996a978f4ef8a55443c75c293b35@thread.skype/1595377202048?groupId=8034415f-bc0a-4b5d-9453-78ee27e16b22

**Comment by asklar** [comment]
Message tells people what's wrong :) there is a pattern to declare the requireNativeComponent as not supporting fast refresh, or you can isolate the requireNativeComponent to a module
