### ISSUE TITLE
Add support for sync native methods

### ISSUE THREAD

**Issue by rozele** [Microsoft/react-native-windows#700]
That is, methods that can be called directly from the JavaScript thread.

**Comment by matthargett** [comment]
what's an example of a an app-level feature that would be enabled by this? any Android or iOS react-native example app sources?

**Comment by rozele** [comment]
I didn't see any uses of this for ReactAndroid yet (just the infrastructure to allow it).  It kind of makes sense though.

**Comment by rozele** [comment]
Closed by #1678
