### ISSUE TITLE
react-native-linear-gradient Needs Updating

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-windows#7008]
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`: 4.13.0
2. `npx react-native info`:
```
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 5.65 GB / 15.60 GB
  Binaries:
    Node: 12.9.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2
      System Images: android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.17763.0, 10.0.18362.0
  IDEs:
    Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6626763
    Visual Studio: 16.8.30804.86 (Visual Studio Community 2019)
  Languages:
    Java: 1.8.0_262
    Python: 2.7.18
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
    react-native-windows: ^0.63.2 => 0.63.14
  npmGlobalPackages:
    *react-native*: Not Found
```

- Target Platform Version(s): 10.0.18362
- Target Device(s): Desktop
- Visual Studio Version: 2019
- Build Configuration: Debug

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Add react-native-linear-gradient module to RNW app running on 0.63 (RN Gallery App)
2. Try to build app...build fails. Module is not compatible with RNW 0.63.

## Notes
Currently react-native-linear-gradient is built on RNW 0.60 using C#. Spoke with @jonthysell. Module was written for the legacy C#-only React Native Windows module - it needs to be re-written to be used by the current RNW. It must run on at least RNW 0.62, remove any reflection (the default with C# modules), and not depend on any nuget packages. Doesn't look like too complicated of a module but the module is targeting 0.60.5 for ios/android and so the repo maintainers may not want to upgrade.

**Comment by asklar** [comment]
repo: https://github.com/react-native-linear-gradient/react-native-linear-gradient
The existing implementation supports the now deprecated WPF implementation of RNW and the C# RNW UWP.

**Comment by chrisglein** [comment]
Closing this module request as not in plan. Not that this module _shouldn't_ receive a Windows implementation, but it makes more sense to track that request on the module's repo rather this repo.
