### ISSUE TITLE
BabylonReactNative.dll needs Microsoft.ReactNative.dll to be distributed as precompiled binary through NuGet

### ISSUE THREAD

**Issue by chrisfromwork** [microsoft/react-native-windows#7010]
# Proposal:  Microsoft.ReactNative.dll should be distributed and referenced as a precompiled binary

## Summary
Right now it isn't clear how to precompile and distribute a native module component that references Microsoft.ReactNative.dll. The precompiled binary will be built against a different version of Microsoft.ReactNative.dll compared to other native modules compiled at the same time as the application. In addition to not ensuring that the correct version of the Microsoft.ReactNative.dll is used by all components, these different compilations of Microsoft.ReactNative.dll generate xaml errors due to conflicting *.xbf files. 

## Motivation
[BabylonReactNative](https://github.com/babylonjs/babylonreactnative) implements a react-native-windows native module for [Babylon.js](https://github.com/babylonjs/babylon.js) engine support. It populates javascript content through the jsi runtime and node api in static libs built from [BabylonNative](https://github.com/babylonjs/babylonreactnative). To gain access to the jsi runtime, this logic needs to reference Microsoft.ReactNative.dll/ABI safe react-native types. We want to distribute a precompiled BabylonReactNative.dll so that developers don't have to resolve and compile the BabylonNative codebase (40+ static libs, ~5 layers of submodule references). To do so, we need to reference a precompiled Microsoft.ReactNative.dll that is then referenced by all other react-native-windows native module components when compiling the application.

## Open Questions
* Are any existing native module components distributed as precompiled binaries?
* Are there any existing workarounds for compilation errors due to conflicting DevMenuControl.xbf files based on different winmds being generated for different compilations of Microsoft.ReactNative.dll?

**Comment by chrisfromwork** [comment]
It sounds like we will also need a plan to understand how community modules setup to build against Microsoft.ReactNative.dll source can also be compiled against the nuget distributed Microsoft.ReactNative.dll

**Comment by asklar** [comment]
Currently the supported way to consume RNW is via source. There is a NuGet package that is experimental being used internally. We haven't done the work to support binary-distributed community modules, and there are likely to be bugs. The best path forward at this point if you need to get unblocked, is to ship the primary logic of your module as a binary, but the glue that talks to React Native as source.
Adding this issue as part of the Binary Distribution project, CC @stmoy @harinikmsft @chrisglein
