### ISSUE TITLE
Support WatermelonDB

### ISSUE THREAD

**Issue by qmatteoq** [microsoft/react-native-windows#7016]
# Support `WatermelonDB` on RNW

## Basic Info
- Module Repo URL: [https://github.com/Nozbe/WatermelonDB](https://github.com/Nozbe/WatermelonDB)
- Target version: React Native 0.63+
- [ ] Issue exists on module repo (if so, [link]())

- [ ] Module has a Legacy/C# implementation (if so, [link]())

## Which app/customer is requesting this module?

An App Consult customer

## In what scenarios will this module be used?

This module, which sits on top of SQLite, is used by the customer to enable online / offline data sync.

## Essential Features

Data saving and offline sync.

**Comment by asklar** [comment]
Assigning to @stmoy to figure out timeline for adding support for this module

**Comment by radex** [comment]
https://github.com/Nozbe/WatermelonDB/issues/178 has some (partly outdated) information about the scope of work needed to support 🍉 on RN Windows.

In my opinion, the best way to implement the support is not to develop the whole Windows NativeModule, but instead to [reuse C++ JSI-only implementation](https://github.com/Nozbe/WatermelonDB/tree/master/native/shared) - only JSI build pipeline, a few basic platform bits are required to get this to work:

- this is the whole JSI Android support: https://github.com/Nozbe/WatermelonDB/tree/master/native/android-jsi and this file is the biggest bit: https://github.com/Nozbe/WatermelonDB/blob/master/native/android-jsi/src/main/cpp/DatabasePlatformAndroid.cpp
- on iOS: https://github.com/Nozbe/WatermelonDB/blob/master/native/ios/WatermelonDB/DatabasePlatformIOS.mm and https://github.com/Nozbe/WatermelonDB/blob/master/native/ios/WatermelonDB/JSIInstaller.mm
