### ISSUE TITLE
Windows: ReactNative frontend IPC/Communication with Windows Parent System Process

### ISSUE THREAD

**Issue by tlnsave12345** [microsoft/react-native-windows#7018]
Hi,
Is there a library that can be used to communicate with the Parent System Process on Windows? Our current Native app' System Process uses "Anonymous Pipes" to communicate with its Child UI process. 

- I understand that I can add C++ Bridge/Native code to handle this. Please suggest if there is an alternative.
- Also is it possible to use Golang as Bridge/Native code to handle this IPC part?

Thanks
Lin

**Comment by asklar** [comment]
Hi @tlnsave12345  - RNW apps are UWP apps so all of the same solutions apply, here's the documentation about inter-process communication in UWP apps: https://docs.microsoft.com/windows/uwp/communication/interprocess-communication
