### ISSUE TITLE
Support react-native-firebase

### ISSUE THREAD

**Issue by qmatteoq** [microsoft/react-native-windows#7045]
# Support `react-native-firebase` on RNW

## Basic Info
- Module Repo URL: [https://github.com/invertase/react-native-firebase](https://github.com/invertase/react-native-firebase)
- Target version: 0-63+
- [ ] Issue exists on module repo (if so, [link]())

- [ ] Module has a Legacy/C# implementation (if so, [link]())

## Which app/customer is requesting this module?

An App Consult customer

## In what scenarios will this module be used?

To collect analytics and use some of the utilities provided by the library

## Essential Features

The initial request is about the app and analytics modules.

**Comment by mdehghani65** [comment]
Sounds great. but how is this going to reflect on the firebase dashboard? firebase analytics only support apps of android, ios,web and unity platforms. maybe adding support for ms appcenter would be more reasonable.

**Comment by Victor0814gui** [comment]
any support predictions?
