### ISSUE TITLE
Is windows7 or windows 8 supported?

### ISSUE THREAD

**Issue by iamweilee** [microsoft/react-native-windows#7052]
Hi, I want to know if windows7 or windows8 is supported?
Thanks.

**Comment by asklar** [comment]
hi @iamweilee , The earliest Windows release that is supported is Windows 10 1703 (though some features won't work there). The oldest release where all features are supported is 1903. Here's the full matrix: https://microsoft.github.io/react-native-windows/docs/win10-compat

**Comment by iamweilee** [comment]
> hi @iamweilee , The earliest Windows release that is supported is Windows 10 1703 (though some features won't work there). The oldest release where all features are supported is 1903. Here's the full matrix: https://microsoft.github.io/react-native-windows/docs/win10-compat

I got it, Thank you.
