### ISSUE TITLE
Surface the view manager name as a property in the XAML tree

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#7069]
For debugging purposes it would be useful to show the RN view manager name as a property in the XAML tree
bonus brownie points add it to uiext

**Comment by chrisglein** [comment]
We'd want to only apply to debug builds probably so there's no cost to always applying this.
What property would this be applied to? It needs to be somewhere that the live visual tree will report. Does it show all attached properties? We also want this to work in WinDbg scenarios with the uiext extension, which would need more custom work to get this to show up.
