### ISSUE TITLE
react-native-webview doesn't work with React Native 0.63 apps

### ISSUE THREAD

**Issue by qmatteoq** [microsoft/react-native-windows#7088]
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`:

4.14.0

2. `npx react-native info`:

```
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 2.38 GB / 15.60 GB
  Binaries:
    Node: 12.9.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.14393.0, 10.0.15063.0, 10.0.17134.0, 10.0.17763.0, 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.8.31005.135 (Visual Studio Enterprise 2019), 16.9.31004.235 (Visual Studio Enterprise 2019)
  Languages:
    Java: Not Found
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
    react-native-windows: ^0.63.0-0 => 0.63.20
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create a new React Native 0.63 project and add Windows support
2. Add the react-native-webview module
3. Build and run the app with npx react-native run-windows

## Expected Results
The application starts and you can use the WebView control in your React Native app. Instead, at first, you get the following error:

```
Error This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them. For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is C:....\windows\packages\Microsoft.Windows.CppWinRT.2.0.200729.8\build\native\Microsoft.Windows.CppWinRT.props. ReactNativeWebView C:...\node_module
```

I did some troubleshooting and it seems the problem is that it’s referencing the React Native framework in the old way, instead of using the guidance here: [https://microsoft.github.io/react-native-windows/docs/native-modules-setup](https://microsoft.github.io/react-native-windows/docs/native-modules-setup). As such, I forked the project and fixed the references. Now comes the challenging part. My forked module works, but then auto linking is creating troubles. The react-native-webview component is made by a solution with two C++ project: one is the real module and one is a utility library used by the module. However, since they’re both C++ projects and both in the windows folder of the module, autolinking adds both of them to the React Native application. This leads to:

1. Break the application if you’re using a C++ host. The reason is that autolinking adds the following code in the AutolinkedNativeModules.g.cpp file:

```
void RegisterAutolinkedNativeModulePackages(winrt::Windows::Foundation::Collections::IVector<winrt::Microsoft::ReactNative::IReactPackageProvider> const& packageProviders)
{ 
    // IReactPackageProviders from react-native-webview
    packageProviders.Append(winrt::ReactNativeWebView::ReactPackageProvider());
    // IReactPackageProviders from react-native-webview
    packageProviders.Append(winrt::WebViewBridgeComponent::ReactPackageProvider());
}

```
However, WebViewBridgeComponent (which is the utility class) doesn’t have a ReactPackageProvider() class, thus the compilation breaks.

2. If the application uses a C# host, it works because in this case it adds only the namespaces in the AutolinkedNativeModule.g.cs file instead of a direct reference to the ReactPackageProvider class:

```
// AutolinkedNativeModules.g.cs contents generated by "react-native autolink-windows"

using System.Collections.Generic;

// Namespaces from react-native-webview
using ReactNativeWebView;

// Namespaces from react-native-webview
using WebViewBridgeComponent;

namespace Microsoft.ReactNative.Managed
{
    internal static class AutolinkedNativeModules
    {
        internal static void RegisterAutolinkedNativeModulePackages(IList<IReactPackageProvider> packageProviders)
        { 
        }
    }
}
```
        
However, you still need to some manual work, because the reference added by the autolinking process is invalid and you need to manually add ReactNativeWebView (the C++ class which implements the  module) and remove WebViewBridgeComponent (the utility library).

## Snack, code example, screenshot, or link to a repository:
My forked project is available here: [https://github.com/qmatteoq/react-native-webview](https://github.com/qmatteoq/react-native-webview)

**Comment by chrisglein** [comment]
Sounds like there's some offline conversation that's happened on this, and that the winRT component that's not indeded to be a module is being identified as a module. @qmatteoq I believe you're working on unraveling this, report back with how that works out.
