### ISSUE TITLE
Support line-through and underlining,  textDecorationLine on <Text> components

### ISSUE THREAD

**Issue by jmcginty** [microsoft/react-native-windows#709]
The following textDecoration works on ios, but not on Windows. 

```
<Text style={{ textDecorationLine: 'line-through' }} >
          This text should be struck out
</Text>
<Text style={{ textDecorationLine: 'underline' }} >
          This text should be underlined
</Text>

<Text style={{ textDecorationLine: 'underline line-through' }} >
          This text should be underlined and struck out
</Text>
```

In the [react-native doco](https://facebook.github.io/react-native/docs/text.html#style), textDecorationLine can be one of ..
['none' /_default_/, 'underline', 'line-through', 'underline line-through'] )

**Comment by rozele** [comment]
Thanks @jmcginty.  UWP has an "Underline" span type, but does not have a Strikethrough span type.  We haven't yet added the underline feature.

**Comment by rozele** [comment]
Most of this can be supported as of RS3 with APIs demonstrated in #1723. We just need to update the target and ensure that we do ApiInformation checks to make sure the target is RS3 or later.
