### ISSUE TITLE
Source Maps from callstack

### ISSUE THREAD

**Issue by joewood** [Microsoft/react-native-windows#710]
I have `inlineSourceMaps` enables for TypeScript code. This works fine for Android and iOS, call stacks are reported correctly by the JS exceptions on the device. For Windows I'm only seeing the JS bundle line numbers. Is there an extra setting that I'm missing?

**Comment by rozele** [comment]
@joewood Interesting, I don't know if that's a feature of JSCore or a feature of the bundler.  To my knowledge, the JSRT on the device is only aware of the bundle line numbers.  It sends these line numbers to the packager service to have them translated to their original files.

**Comment by rozele** [comment]
@joewood please advise if this is still an issue. Will close otherwise.
