### ISSUE TITLE
How to call native "in project" code from js in a C++ RNW app

### ISSUE THREAD

**Issue by burtonrodman** [microsoft/react-native-windows#7126]
Ok, super basic question/problem that I feel like should be obvious but i've spent the last 2 days getting nowhere...

Really, I'd rather be writing an external native module (i.e. adding Windows support to a community module), but that's too many details and I just have to get ANYTHING working.

I stripped down the FancyMath sample module and included it in my app's C++ project -- everything I've read seems to suggest this should "just work".  Now when I try to call a parameterless function I get the below error, the component doesn't render (white screen) and I get "undefined" in the console.

```
[Fri Feb 12 2021 11:06:05.204]  BUNDLE  ./index.js

Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:612:3)
    at tryReadSync (node:fs:382:20)
    at Object.readFileSync (node:fs:419:19)
    at UnableToResolveError.buildCodeFrameMessage (REDACTED_PATH\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:304:17)
    at new UnableToResolveError (REDACTED_PATH\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:290:35)
    at ModuleResolver.resolveDependency (REDACTED_PATH\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:191:15)
    at DependencyGraph.resolveDependency (REDACTED_PATH\node_modules\metro\src\node-haste\DependencyGraph.js:353:43)
    at REDACTED_PATH\node_modules\metro\src\lib\transformHelpers.js:271:42
    at Server.<anonymous> (REDACTED_PATH\node_modules\metro\src\Server.js:842:41)
    at Generator.next (<anonymous>)
```

If it has parameters (double a, double b), I get this error:
``
No callback found with cbID 2 and callID 1 for module <unknown>. Args: '[5]'
``

If I switch the case (add vs Add) in the js call, it says:
``
_reactNative.NativeModules.BurtonMath.Add is not a function
``

So I can surmise that the module and method are getting registered, but something else is missing.

```
#pragma once

#include "pch.h"

#include <functional>
#define _USE_MATH_DEFINES
#include <math.h>

#include "NativeModules.h"

namespace MyProjectName
{
    REACT_MODULE(BurtonMath);
    struct BurtonMath
    {

        REACT_METHOD(Add, L"add");
        double Add() noexcept
        {
            return 5.0;
        }
    };
}
```

My Component Code:

```
const LoginPage: React.FC<LoginProps> = ({ navigation }) => {
  var addend = NativeModules.BurtonMath.add();
  console.log(addend);
```

**Comment by burtonrodman** [comment]
I used the question template, but ok i'll play along...

npx react-native --version
```
4.14.0
```

npx react-native run-windows --info
```
  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 5.10 GB / 15.92 GB
  Binaries:
    Node: 15.8.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
    react-native-windows: ^0.63.0-0 => 0.63.20
  Installed UWP SDKs:
    10.0.18362.0
```

**Comment by burtonrodman** [comment]
Here is a repo with a newly created RNW app (TypeScript).  I added FancyMath.h, added an import in ReactPackageProvider.cpp and tried to call it from App.tsx.  I receive this error:
```
No callback found with cbID 2 and callID 1 for module <unknown>. Args: '[1]'
```
[BurtonNativeTest](https://github.com/burtonrodman/BurtonNativeTest)

**Comment by acoates-ms** [comment]
Native modules are async by default.

So the JS call site would look like:

```tsx
NativeModules.FancyMath.add(1, 2, (result: number) => {console.log(result)});
```

You could also change the native definition to use REACT_SYNC_METHOD.  But as with RN on android/iOS, synchronous methods will not work when doing remote debugging.

**Comment by burtonrodman** [comment]
That was the trick.  Thanks so much!
