### ISSUE TITLE
System requirements Page. v 0.63 shows a nodejs version that is not supported

### ISSUE THREAD

**Issue by Robertschv** [microsoft/react-native-windows#7145]
nodejs v 12 is no working with this tutorial.

better change it to nodejs-lts

I know this change is already made in the "next" version of the page. but the default link is to the 0.63 version.  

PLUS. the Warning of "Next" is not showed in the "0.63 version. "

![Captura de pantalla (37)](https://user-images.githubusercontent.com/62678042/108136115-c6a0e700-708f-11eb-90b3-ffade4e410b7.png)

**Comment by chrisglein** [comment]
@AgneLukoseviciute with this backported are you set to close this issue?
