### ISSUE TITLE
AppThemeModuleUwp captures this pointer unsafely

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#7147]
>this [](start = 78, length = 4)

It used to be before, but capturing this doe snot seem to be safe.

_Originally posted by @vmoroz in https://github.com/microsoft/react-native-windows/pull/7135#discussion_r577005438_

**Comment by chrisglein** [comment]
Do we need a review of this class of capture across the codebase? Does the member here cover auto revoking? This class of issue should be something we can handle with general patterns.
