### ISSUE TITLE
User projects always download WinUI 3 Preview NuGet package (~130MB)

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#7178]
To repro, build the 0.63 Calculator sample in `react-native-windows-samples` repo.

The `Microsoft.WinUI.3.0.0-preview2.200713.0` package is pulled in, possibly because the Microsoft.ReactNative project requires it in packages.config.

Affects multiple versions. I.e. not a new regression.

**Comment by NickGerleman** [comment]
FWIW, if we've had it there and nobody has been complaining, a different option is to explicitly take the hit to simplify logic around maintaining NuGet packages.

**Comment by chrisglein** [comment]
Won't be pulled in for the build, but will be downloaded. There isn't a mechanism for Visual Studio to have this conditional on something. It's possible we could create a custom solution here. It'd be nice to reduce our footprint.
