### ISSUE TITLE
Cannot setup and run react-native-windows project on VSCode

### ISSUE THREAD

**Issue by MadeByRaymond** [microsoft/react-native-windows#7180]
Following the setup steps for when using VS Code in https://microsoft.github.io/react-native-windows/docs/getting-started#running-a-react-native-windows-app, I keep getting this error `[Error] Error: Error while executing command 'c:\Users\RAYMOND\Desktop\React\ReactNativeDesktop\demo\node_modules\.bin\react-native.cmd run-windows --logging --remote-debugging --no-packager': Error while executing command 'c:\Users\RAYMOND\Desktop\React\ReactNativeDesktop\demo\node_modules\.bin\react-native.cmd run-windows --logging --remote-debugging --no-packager' (error code 101)` (also see image attached) when trying to run debug. 

![Screenshot (14)](https://user-images.githubusercontent.com/29353783/108593875-b8481900-7376-11eb-93bd-78913c3edd6e.png)

**How can this be resolved please**

**Comment by asklar** [comment]
It looks like you are using the vscode-react-native extension. Are you able to build and run the app from the command line? (`npx react-native run-windows`). If so, could you please file the issue in the [vscode-react-native](https://github.com/microsoft/vscode-react-native) project instead? I see they have some bugs filed about error 101/303.

**Comment by MadeByRaymond** [comment]
Alright. I cannot run `npx react-native run-windows` due to it requires me to have installed and setup Visual Studio on my system,  which I haven't. That is why I am using the setup guide with VSCode instead.

**Comment by rectified95** [comment]
I'm not sure if VS is strictly needed - what is necessary though are the many SDKs we say need to be installed with it. Check the list of dependencies and see if that helps. https://microsoft.github.io/react-native-windows/docs/rnw-dependencies
There's also a Powershell script that installs everything for you.

**Comment by MadeByRaymond** [comment]
> Check the list of dependencies and see if that helps. https://microsoft.github.io/react-native-windows/docs/rnw-dependencies
> There's also a Powershell script that installs everything for you.

![Screenshot (15)](https://user-images.githubusercontent.com/29353783/109228856-c3f66e00-77c2-11eb-836f-ee87262bc8be.png)
 this is what I get after running the script.

**Comment by asklar** [comment]
@MadeByRaymond in order to be able to build React Native Windows apps, you need a number of tools, compilers, etc. which are included in that workload that says "Failed". You have to install those and then you can use VSCode as a front end, but you still need to install VS with the different compilers and tools in order to be able to build the app, VSCode is just an editor.

**Comment by asklar** [comment]
@MadeByRaymond  Let us know if you are still blocked after installing the dependencies

**Comment by MadeByRaymond** [comment]
Well apparently Visual Studio is required, even to run on VS Code. The problem was solved by installing VS and dependencies.
