### ISSUE TITLE
Confirm whether onLoad events must be called for all Image source changes

### ISSUE THREAD

**Issue by rozele** [microsoft/react-native-windows#7194]
In https://github.com/microsoft/react-native-windows/pull/7193, the `ReactImage::SetBackground` behavior was changed to bail out if the image source was updated before the async operation to either download an image or load an inline image into an IRandomAccessStream completed. When this occurs, onLoad and onLoadEnd will not be called for the "canceled" source prop. We should check whether this violates an implicit contract established on iOS / Android.

**Comment by chrisglein** [comment]
First step will be to establish what Android/iOS do and we should match that behavior. Off hand, don't know what that is. Will need someone to look.

**Comment by rozele** [comment]
I think we can safely close this issue. It looks like on iOS there is no requirement that onLoad / onLoadEnd fires if the source changes: https://github.com/facebook/react-native/blob/master/Libraries/Image/RCTImageView.mm#L364-L367
