### ISSUE TITLE
Backport adding IViewManagerRequiresNativeLayout to 0.63

### ISSUE THREAD

**Issue by rectified95** [microsoft/react-native-windows#7195]
Originally the issue of the lack of a way to specify a custom measure function was spotted in 2 community modules, which are running 0.63. Do we see issues backporting https://github.com/microsoft/react-native-windows/pull/7013 to that version of RNW?
If not, I'll go a head and make the PR.

**Comment by chrisglein** [comment]
May be too much of a breaking change to bring back. It's passing on some compat complexity to the apps/modules. If we could "quirk" the modules to do a version check that would mean we could patch them in a way that they could support both. Were we to do this it'd require we come up with a design for how to do capability/version/quirk checks. This is not going to be the last of these we'd do, so we need to pattern that's robust and scales to more of these. 

@rectified95 Look through some options for this and make a proposal? I think if we have that in place we'd take a fix.

**Comment by chiaramooney** [comment]
0.63 is out of support.
