### ISSUE TITLE
Images rendered with ReactImageBrush disappear in multiple monitors

### ISSUE THREAD

**Issue by rozele** [microsoft/react-native-windows#7205]
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Run RNTester with multiple monitors on host device.
2. Open the Image component example
3. Scroll to images with tintColor example
4. Move app to a different monitor 

## Expected Results
Tinted images should still be rendered on the screen, but instead they disappear. I suspect this has something to do with not registering for events related to the CanvasDevice / CompositionGraphicsDevice to trigger redrawing when needed. Not sure if it's expected that the XamlCompositionBrushBase is expected to handle this for you (and thus a bug with that component) or if we need to create something similar to the ImageLoader here: https://github.com/microsoft/WindowsCompositionSamples/blob/master/SamplesCommon/SamplesCommon/ImageLoader/ImageLoader.cs 

## Snack, code example, screenshot, or link to a repository:

https://user-images.githubusercontent.com/1106239/108873791-7b279500-75c9-11eb-8c50-f7c038a7e68d.mp4

**Comment by chrisglein** [comment]
@rozele It sounded like you had some immediate need for this that I'm not sure we'll get to in the next couple weeks. Want to take a look? @marlenecota can be a resource if you need help knowing where to look.
