### ISSUE TITLE
Auto-linking does not find native packages that are dependencies of dependencies

### ISSUE THREAD

**Issue by jeanmaried** [microsoft/react-native-windows#7206]
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`:
    react-native version 4.14.0
2. `npx react-native info`:
```
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz
    Memory: 11.87 GB / 31.81 GB
  Binaries:
    Node: 12.9.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.17134.0, 10.0.17763.0, 10.0.18362.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.8.31019.35 (Visual Studio Community 2019), 16.8.31005.135 (Visual Studio Enterprise 2019)
  Languages:
    Java: Not Found
    Python: 2.7.18
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
    react-native-windows: ^0.63.0-0 => 0.63.22
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. I have two npm modules: module A and module B. (Unfortunately these modules are private so I can not share them here)
2. Module A has a dependency on one of module B's native methods which is invoked from module A's TS code.
3. I install module A

## Expected Results
After installing module A, I would expect that both A and B are found for auto-linking.

Actual result: Only module A is found.

## Snack, code example, screenshot, or link to a repository:
I will try to create an example soon, time allowing.

**Comment by chrisglein** [comment]
@jonthysell Do you know whether the other platforms are able to handle deeper transitive dependencies? Is this limited on our end or by how far the config passes through?

**Comment by chrisglein** [comment]
@jeanmaried It would be helpful if you had a standalone repro to help compare different platform behaviors. Understand you can't compare your direct repro as it's private.

**Comment by jeanmaried** [comment]
@chrisglein sorry I'm insanely busy these days. If I have some free time I will put something together.

**Comment by jonthysell** [comment]
Does module B work with autolinking on it's own? Autolinking looks at whatever packages `react-native config` sees, and then determines if those packages can be linked.
