### ISSUE TITLE
Read, Write, Watch windows registry?

### ISSUE THREAD

**Issue by rendomnet** [microsoft/react-native-windows#7219]
Can react-native-windows Read, Write, Watch windows registry?
Did not found any info about this.

**Comment by chrisglein** [comment]
There's no built in functionality for this in React Native Windows. You'd need to use the native desktop APIs to do this.

**Comment by rendomnet** [comment]
@chrisglein Maybe you could provide an example?

**Comment by chrisglein** [comment]
@rendomnet You'll have better luck poking around yourself. I just did some searches for "windows registry APIs" and got hits like this:
- [Win32 Registry](https://docs.microsoft.com/en-us/windows/win32/sysinfo/registry)
- [How to access registry keys in a UWP app](https://stackoverflow.com/questions/48899692/how-to-access-registry-key-in-a-uwp-app)
- [Alternatives to Windows APIs UWP](https://docs.microsoft.com/en-us/uwp/win32-and-com/alternatives-to-windows-apis-uwp)

**Comment by rendomnet** [comment]
@chrisglein this links are for react native developers? I'm not C# C++ native windows developer I don't understand there a thing, I'm using React native windows. And windows registry CRUD is essential for app development.

**Comment by chrisglein** [comment]
> I'm not C# C++ native windows developer I don't understand there a thing, I'm using React native windows.

Unfortunately at the point that you're looking for functionality that isn't covered by existing community modules, you need to drop into native code which requires the skills/knowledge for that platform (be it iOS, Android, or in this case Windows). You can find the documentation about how to do that [here](https://microsoft.github.io/react-native-windows/docs/native-modules).

> Windows registry CRUD is essential for windows app development.

It depends on your scenario? Lots of apps don't need access to the registry. Generally app local storage is sufficient. But it's hard to give more guidance without knowing why you need the registry.

**Comment by rendomnet** [comment]
@chrisglein Well Windows registry is important part of Windows. 
And I think almost all popular Windows apps is using windows registry in some way. (Photoshop, Office, Steam for example)
In my case I need to access some specific system information which is stored in windows registry, and accordingly use it to have better UX.
Electron apps can do it. I was considering switching from electron to RNW. But it looks like it is not ready yet?

**Comment by chrisglein** [comment]
An Electron app is not a UWP app. React Native for Windows apps are UWP apps. As such if you're just using the default app template you're going to be in a different app container than you're used to and have different restrictions. We've attempted to capture that in [this article](https://microsoft.github.io/react-native-windows/docs/native-code). But the short is that you'd be dealing with these same questions if you created a new UWP app from Visual Studio, it's not specific to RNW. It is possible to host your UI inside a Win32 app using XAML Islands (see [here](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/xaml-islands)), but that's a bit of an advanced topic. There's an article that walks through that [here](https://techcommunity.microsoft.com/t5/windows-dev-appconsult/getting-started-with-react-native-for-windows/ba-p/912093). Better integration there is on our longer term radar but isn't available today.
