### ISSUE TITLE
Can't run e2etest locally, fails to start 100%

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#7223]
Running the e2e tests locally fail with "unknown error", "port in use", or some other random error. I haven't been able to run the tests locally since the infrastructure was rewritten.

<details>
```
yarn e2etest

$ jest --color
2021-02-27T02:25:47.231Z ERROR webdriver: Request failed with status 200 due to Error: unknown error
2021-02-27T02:33:51.991Z ERROR webdriver: Request failed with status 404 due to invalid session id: No active session with ID 55616151-DB32-4E6B-998E-25FC684CAD6B
 FAIL  test/LegacyTextInputTest.test.ts
  ● Test suite failed to run

    invalid session id: No active session with ID 55616151-DB32-4E6B-998E-25FC684CAD6B

      89 |   async teardown() {
      90 |     if (this.browser) {
    > 91 |       await this.browser.deleteSession();
         |       ^
      92 |     }
      93 |
      94 |     if (this.rpcClient) {

      at Object.getErrorFromResponseBody (../../node_modules/webdriver/build/utils.js:94:12)
      at WebDriverRequest._request (../../node_modules/webdriver/build/request.js:134:31)
          at runMicrotasks (<anonymous>)
      at Browser.wrapCommandFn (../../node_modules/@wdio/utils/build/shim.js:63:29)
      at WinAppDriverEnvironment.teardown (../jest-environment-winappdriver/src/WinAppDriverEnvironment.ts:91:7)

 FAIL  test/LegacyLoginTest.test.ts
  ● Test suite failed to run

    Failed to start WinAppDriver:
    Address 'http://127.0.0.1:4723/' is already in use

    Failed to initialize: 0x80004005

      124 |         resolve(process);
      125 |       } else if (s.includes('Failed to initialize')) {
    > 126 |         reject(new Error('Failed to start WinAppDriver: ' + s));
          |                ^
      127 |       }
      128 |     });
      129 |

      at Socket.<anonymous> (../jest-environment-winappdriver/src/WinAppDriverEnvironment.ts:126:16)

 FAIL  test/visitAllPages.test.ts
  ● Test suite failed to run

    Failed to start WinAppDriver:
    Address 'http://127.0.0.1:4723/' is already in use

    Failed to initialize: 0x80004005

      124 |         resolve(process);
      125 |       } else if (s.includes('Failed to initialize')) {
    > 126 |         reject(new Error('Failed to start WinAppDriver: ' + s));
          |                ^
      127 |       }
      128 |     });
      129 |

      at Socket.<anonymous> (../jest-environment-winappdriver/src/WinAppDriverEnvironment.ts:126:16)

 FAIL  test/LegacyImageTest.test.ts
  ● Test suite failed to run

    Failed to start WinAppDriver: Address 'http://127.0.0.1:4723/' is already in use

    Failed to initialize: 0x80004005

      124 |         resolve(process);
      125 |       } else if (s.includes('Failed to initialize')) {
    > 126 |         reject(new Error('Failed to start WinAppDriver: ' + s));
          |                ^
```

**Comment by NickGerleman** [comment]
What version of WinAppDriver do you have installed locally?

From the logs, WinAppDriver does not recognize the session it has returned, and we then throw when trying to shut the app down. Because we fail to destroy the session, the subsequent tests fail to start a new one.

**Comment by NickGerleman** [comment]
Another thing to check for is if there are two instances of Jest running at once. E.g. if you have VSCode opened to E2ETest in the background, trying to run tests at the same time.

**Comment by asklar** [comment]
Whatever the dependencies script had installed:
![image](https://user-images.githubusercontent.com/22989529/109373435-9f060780-7863-11eb-94ef-648f10886fc1.png)

**Comment by asklar** [comment]
I also see a bunch of these. The app starts, the mouse moves to the Components button and nothing happens other than these errors:
![image](https://user-images.githubusercontent.com/22989529/109373609-ba254700-7864-11eb-9f5b-85c488dd96d5.png)

**Comment by NickGerleman** [comment]
@asklar  could you try updating to 1.2? It changed some behavior a bit. Need to check that the tests script is up to date, but I think we changed it.

**Comment by NickGerleman** [comment]
Are you seeing a Window with UI open?

**Comment by NickGerleman** [comment]
Hmm, it looks like the version in the dependencies script is out of date compared to the version in docs or used by CI.

**Comment by asklar** [comment]
Updating WAD to 1.2.1 fixed this. Can you please update the script to check for/download the right version?

**Comment by NickGerleman** [comment]
It looks like this issue was added during CanHua's Appium removal, before the Jest conversion or RPC based tree dumping. 

Would appreciate if you could create an issue (or edit this one) to change dependency script version. Since I'm on loan to another team at the moment I may not be able to respond immediately.
