### ISSUE TITLE
No way to debug e2etest from VS?

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#7224]
I haven't been able to get the tests to run, but it seems like there isn't a good way to run the tests while having VS attached to  the native app now that the tests have been re-written to be driven by JS; before, the comparison happened on the native side so if something was off you could just run the app from VS and get the results there.

**Comment by NickGerleman** [comment]
You should be able debug the JS side like you would debug other Jest Tests.

You could also place a breakpoint on the native side where the tree is dumped and sent over the wire.

**Comment by asklar** [comment]
I meant debugging the native side has gotten more difficult because now I have to either attach post-hoc or use IFEO to attach, instead of being able to launch the app and run all of the interesting logic on the native side within VS.

**Comment by NickGerleman** [comment]
I think that's kind of by design. We want the flexibility to assert on various RNTester pages without needing to run test assertions every time an RNTester page is visited.

**Comment by chrisglein** [comment]
@NickGerleman is there documentation on how to attach to do native debugging? It sounds like JS debugging is easier and native debugging has taken a hit. If there's a new process for how you dig and debug native here we should write that down. Is there any "WaitForDebugger" style option to help with this?

**Comment by NickGerleman** [comment]
Before and after the change we had a JS test runner. It's not expected that you be able to run/debug UI tests from native.

**Comment by asklar** [comment]
It's necessary to be able to debug the native portion of the test (and the underlying framework library).

**Comment by NickGerleman** [comment]
I think I'm still missing the scenario where this is useful. Could you help me understand the specific scenario you are trying to debug and having trouble with?

The goal of E2ETest is to perform and evaluate the result of end user interactions. Any test that can fail can be reproduced as a simple series of user actions against the test app. Breakpoints can be set to do this in the same way as normal. Just like before, you can launch the app manually to visit RNTester, or run via a test runner which manages app lifetime automatically. We have not had a way before, or after, to automate test interactions while allowing debugging native.

We did have TreeDumpControl per assertion, which a limited set of basic checks were possible to observe on native. This could never have worked for expanding capabilities to test arbitrary pages, whether that be moving the control up in the tree or removing it.

**Comment by chrisglein** [comment]
> The goal of E2ETest is to perform and evaluate the result of end user interactions. Any test that can fail can be reproduced as a simple series of user actions against the test app. 

It's not uncommon to get bugs that don't repro through manual steps but do through the test automation equivalent. Also being able to replicate the steps is an extra burden beyond just "run the test until it explodes". Based on experience with other UI interaction test runners I'd say being able to run the automated interaction and also debug is pretty important.

However if that's functionality that wasn't there before and still isn't now then that certainly colors the priority here. That's why I was asking about what the expected attach process was and whether we had "best practices" written down.

**Comment by NickGerleman** [comment]
To that question, we don't have the debugging workflow well documented. We will give actionable feedback on snapshot comparison failure, but there are some scenarios like native crashes, where you're right, that I could see being useful.

"Break on start" seems reasonable to add, and maybe not so hard to add to jest-environment-winappdriver based on CLI args.

I think that would be the right approach if we did want the "run until native explodes" conveniece, while performing the interactions from the actual JS test code.

I think this is a good enhancement to consider for the future. The clarification of priority here is helpful though.

**Comment by NickGerleman** [comment]
One other bit that ties in here is heap dumps from CI. We do still collect these (I think Alex set that up), and they are still useful. I've used that before to diagnose failing integration tests on Server 2019.
