### ISSUE TITLE
Hermes NuGet Package Incompatible with C# Projects

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#7225]
Steps to repro:
1. Add PackageReference with "ReactNative.Hermes.Windows" to template C# project
2. Build project

```
Package ReactNative.Hermes.Windows 0.7.2-microsoft.4 is not compatible with uap10.0.16299
```

**Comment by chrisglein** [comment]
Why is the combination of C# and Hermes an issue. @dannyvv do you know?
The blockage here seems intentional. @NickGerleman was this meant to track overcoming whatever issue is blocking the combination?

**Comment by NickGerleman** [comment]
This issue tracks that the NuGet package itself will show errors when its targets are included in the user project (I think needed to ensure outputs are copied to the appx).

>  @NickGerleman was this meant to track overcoming whatever issue is blocking the combination?
👍

**Comment by NickGerleman** [comment]
Anandraj fixed this. Looks like a dupe of this above was closed out.
