### ISSUE TITLE
Enable modules to consume Microsoft.ReactNative nuget package

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#7227]
Today you can create an app and choose to use the RNW nuget package, however realistically you will need to use some community module. The problem is that there is no way for a module to consume the nuget, they must build against RNW source instead, which negates any gains from the app using the RNW nuget.

Linking to issues provided by @jonthysell 
- [ ] #9588 
- [x] #9581
- [x] #9580
- [x] #9579
- [ ] #9578
- [ ] #9577
- [ ] #9576
- [ ] #9570
- [ ] https://github.com/microsoft/react-native-windows-samples/issues/646
- [ ] https://github.com/microsoft/react-native-windows-samples/issues/645

**Comment by chrisglein** [comment]
@jonthysell where is module consumption of the nuget in the binary plan? Is that already tracked? There's all sorts of questions about how versions will need to be coordinated (different modules pointing to different nugets). These aren't new questions, but I'm not sure what we have tracked.

**Comment by br4in3x** [comment]
Having native modules to consume RN nuget package would be a real life-changer for developer experience. Thank you :)

**Comment by asklar** [comment]
My proposal to enable this is as follows:

1. Move declaration of UseExperimentalNuget from the project file to EF.props
2. module project imports app's EF.props and discovers the app wants to use the nuget package - therefore the module should too.
3. module project then knows it must import the nuget's props/targets. This requires knowing the path to these files which requires knowing the RNW version. Either:
  - specify the RNW version in EF.props, or 
  - ideally have a target that sets a variable ReactNativeWindowsVersion, so that we can import from `$(SolutionDir)\packages\Microsoft.ReactNative.$(ReactNativeWindowsVersion)\build\Microsoft.ReactNative.props` and `.targets`. However, this target must run before `Import`s are processed so I'm not sure how likely this approach is

**Comment by jonthysell** [comment]
This was done for 0.68 thanks to the PackageReference work. A module that updates to at least RNW 0.68 (aligning with the changes in the project files) will be able to be consumed by apps building by source or the MS.RN nuget binaries.

The unfinished tasks in the main description refer to apps consuming modules that themselves publish nugets (rather than requiring the building of their native source). Which, while related, are that themselves have published NuGet binaries.
