### ISSUE TITLE
Support react-native-serialport

### ISSUE THREAD

**Issue by omdxp** [microsoft/react-native-windows#7229]
# Support `react-native-serialport` on RNW

## Basic Info
- Module Repo URL: [https://github.com/melihyarikkaya/react-native-serialport](https://github.com/melihyarikkaya/react-native-serialport)
- Target version: 0.63
- [x] Module has a Legacy/C# implementation (if so, [https://www.nuget.org/packages/SerialPort.Net/](https://www.nuget.org/packages/SerialPort.Net/))

## Which app/customer is requesting this module?
I want to try this module in order to have the ability to use the esc pos printer.

## In what scenarios will this module be used?
- using esc pos printer.
- link with arduino board.
- read data from sensors.

**Comment by chrisglein** [comment]
Doesn't look like this module is in the RN directory: https://reactnative.directory/?search=react-native-serialport
Module appears to be Android-only. There isn't an existing Windows implementation but there is some C# library that is linked above (Desktop, not UWP). Alternatively there are WinRT APIs for point of sale devices, which you can hit directly instead of through this module.

**Comment by Omar-Belghaouti** [comment]
> Doesn't look like this module is in the RN directory: https://reactnative.directory/?search=react-native-serialport
> Module appears to be Android-only. There isn't an existing Windows implementation but there is some C# library that is linked above (Desktop, not UWP). Alternatively there are WinRT APIs for point of sale devices, which you can hit directly instead of through this module.

Thanks for the suggestion. It would have a great effect and a wide scalability if this module is implemented (and other modules like Bluetooth).

**Comment by Omar-Belghaouti** [comment]
@chrisglein You can check [this repo](https://github.com/Omar-Belghaouti/react-native-windows-posprinter) where I implemented the print receipt method natively for esc pos printer.
