### ISSUE TITLE
RNW version didn't pick up latest CLI

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#7230]
App using react-native-windows 0.64-0.preview-12, ends up with an older CLI:

    "@react-native-windows/cli": "0.64.0-preview.7",

But it should be preview 8

**Comment by NickGerleman** [comment]
The CLI package is only bumped when there is a a CLI change, so it is possible for its version to be lesser than RNW itself. This also means users don't need to redownload a new CLI package if an RNW update doesn't touch the CLI.

**Comment by NickGerleman** [comment]
It does look like newest RNW 0.64 declares a  dependency on the newest version of the CLI https://github.com/microsoft/react-native-windows/blob/0.64-stable/vnext/package.json

Depending on what is reporting the older version, the install might need a "yarn install", or there may be multiple copies of the CLI depending on how dependencies are configured.

**Comment by chrisglein** [comment]
There was an RNW update and a CLI update on the same day (RN 12 and CLI 8). We don't know why it didn't get bumped to 8. @acoates-ms can you take a look?

**Comment by acoates-ms** [comment]
`npm info react-native-windows@0.64.0-preview.12 dependencies`

Says that preview 12 does use preview 8 of the CLI which is correct.
`'@react-native-windows/cli': '0.64.0-preview.8'`

So I dont think there is an issue here.
