### ISSUE TITLE
e2e tests launch app for non-matching tests

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#7240]
`yarn e2etest -t LegacyTextBackgroundColorTest`

The test driver iterates through every test, launches the app, then if the test name doesn't match what's passed in, it kills the app.
The test driver should not start the app for tests that do not match the test passed in the command line

**Comment by NickGerleman** [comment]
I noticed this as well.

"-t" specifies a test regex https://jestjs.io/docs/en/cli#--testnamepatternregex

It seems like it spawns workers when it doesn't have to. 

You can also run 'jest "path/to/test.test.ts"' and run a single without hitting the issue. Maybe we should document that as the preferred way to run a test.

**Comment by asklar** [comment]
Even with just running `jest pathToTest` it looks like the path spec is hostile to Windows, neither .\foo\bar or foo\bar works, only foo/bar
It would be good to fix this to be OS agnostic

![image](https://user-images.githubusercontent.com/22989529/109716187-6151f900-7b59-11eb-8831-4d021ec53bc5.png)

**Comment by NickGerleman** [comment]
@rectified95 @asklar I found what I was doing before.

```
packages/e2e-test-app/test>  yarn e2etest "LegacyControlStyleTest.test.ts"
```

Key here is that it only seems to work in the test directory. I think we could likely change jest config or directory structure to make that work in the repo root as well.

In the meantime I can update the docs to recommend this approach instead of the regex one.

**Comment by NickGerleman** [comment]
https://github.com/microsoft/react-native-windows/issues/7272 tracks fixing the above Jest config.

I will resolve this specific issue with a documentation fix.
