### ISSUE TITLE
[VS 16.9.0] executeAsynchronously discards std::thread

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#7247]
RN core bug: https://github.com/facebook/react-native/issues/31088
we need a patch in the meantime

**Comment by NickGerleman** [comment]
FYI that it is unlikely this issue will be fixed upstream without us creating a PR upstream. Best to just send PRs for this sort of thing.

**Comment by asklar** [comment]
@NickGerleman thanks for your comment, I already have a PR upstream for this: https://github.com/facebook/react-native/pull/31090
