### ISSUE TITLE
[Override tool] "override type" names are unintuitive

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#7254]
When adding an override, the tool asks for the type of override. There are four options: 

   |  
-- | --
Platform | Platform-specific logic that doesn't map to an upstream file
Derived | An override derived from an upstream file. Changes to the original file will be merged into the override.
Patch | An upstream file with changes made to it. Changes to the original file will be merged into the override.
Copy | An exact copy of an upstream file or directory. Overrides of this type will remain identical to their originals.

- Derived == Patch?
- Patch however does not refer to a git patch file
- Copy doesn't mean "I copied the file once and I want changes to continue flowing to it".

We should give them different names to better reflect the intent

**Comment by chrisglein** [comment]
> We should give them different names to better reflect the intent

Open call for suggestions.

Naming things is hard :)

**Comment by chiaramooney** [comment]
Closing for now. Unless proposal is given.
