### ISSUE TITLE
Re-enable CG for PR/CI pipeline

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#7261]
Component Governance was having some kind of connectivity issue, which is blocking our PRs, so I've temporarily disabled it.

Filing this bug as a reminder to re-enable it as soon as possible.

**Comment by NickGerleman** [comment]
Marking for followup to understand 0.65 impact.

**Comment by asklar** [comment]
Jon thinks this is already done, assigned to Jon to close
