### ISSUE TITLE
Image with GaussianBlurEffect disappears when moving monitors

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#7263]
@asklar agree the effect definitely needs to be fixed, but as you said this fix has it's own merits of removing unnecessary effects.

I looked at what's happening with the RN copy of GaussianBlurEffect, and all it seems to be doing is forwarding props to D2D, so my thought was that the bug was with D2D, and thus not fixable here. Since it repro'd in Win2D, I thought they might have some better idea of how to work around or fix.

_Originally posted by @rozele in https://github.com/microsoft/react-native-windows/issues/7222#issuecomment-786881483_

**Comment by rozele** [comment]
FYI - this is being tracked on Win2D as well: https://github.com/microsoft/Win2D/issues/809
