### ISSUE TITLE
RNW app accessed through RDP gets into a bad state while right clicking

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#7269]
TS into another device
Launch a RNW app
Right click with touchpad/mouse

![image](https://user-images.githubusercontent.com/22989529/109926719-1d094a80-7c78-11eb-9110-d9a6dcba799e.png)

![image](https://user-images.githubusercontent.com/22989529/109926653-09f67a80-7c78-11eb-903e-6afb62b73092.png)

**Comment by chrisglein** [comment]
According to @rectified95 this can occur without using RDP.
Error looks like it's un-paired mouse events, which is messing up input state machines.

**Comment by chrisglein** [comment]
We're planning on reviewing the mouse APIs very very soon, this should be checked as part of that.

**Comment by rectified95** [comment]
Locally, I can only see the second warning: 'ended a touch event which was not counted...' Pushed a PR addressing that.
Don't see or know why the first one would appear - could actually be related to RDP.

**Comment by rectified95** [comment]
@asklar Can you check if you're still seeing either of these errors in RDP? I'd at least expect to see one of them go.
