### ISSUE TITLE
newer Metro crashes often when rebuilding app, seems to ignore blocklist

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#7270]
I keep having to restart metro because it crashes with file in use; started in the last month or so

![image](https://user-images.githubusercontent.com/22989529/109962403-fe1eae80-7c9f-11eb-9e9c-5a3b4cfa9355.png)

**Comment by NickGerleman** [comment]
@asklar what version of react-native is being run here?

**Comment by asklar** [comment]
Using RN 0.64-rc.3, RNW 0.64-preview.13

**Comment by chrisglein** [comment]
regex is matching a .tsx.blah.tmp file and doesn't seem like it should be. Who's creating the temp file? VS Code? File opened by something else?
We hit lots of issues with Windows file system quirks and Metro. There may be a larger discussion to have there.
Is this a fix to our Metro config or to Metro itself? I'm curious about this part:

> seems to ignore blocklist

**Comment by chrisglein** [comment]
Workaround is to relaunch Metro.
Not a good experience though.

**Comment by acoates-ms** [comment]
As far as I can tell there is no default blocklist.  If this is something VS does consistently we should look at adding .TMP files to the default blocklist in metro config in the template. (And also to our configs within our repo)

If this is something that happens more broadly, like say from VSCode, then we could look at adding it to the default metro config in core.

Any idea what process is creating the .TMP file?
