### ISSUE TITLE
New warnings from recent ingestion?

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#7295]
![image](https://user-images.githubusercontent.com/22989529/110236684-108d2800-7eec-11eb-97ac-7b7437e2bf62.png)

![image](https://user-images.githubusercontent.com/22989529/110236695-1c78ea00-7eec-11eb-9a28-cfe556fcf763.png)

![image](https://user-images.githubusercontent.com/22989529/110236699-213d9e00-7eec-11eb-86d3-a75462055026.png)

There's also a warning about a leak in the Image page:
![image](https://user-images.githubusercontent.com/22989529/110237303-30264f80-7ef0-11eb-8441-bc5ccfca0222.png)

**Comment by chrisglein** [comment]
Check to see if web debugging has the same issue on Facebook master (could show there as well). It's not used equally across partners (planned to be deprecated in future versions) and so could have been broken.

Is affecting these components
- Text
- Image
- TextInput

Side note, do we have up to date docs on our direct debugging steps? Including steps on how to debug script and native at the same time.
