### ISSUE TITLE
Alert module uses ContentDialog which can crash app when called multiple times

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#7297]
ContentDialog has a restriction that there can only be one per window at a time.
Showing the content dialog is an async operation, so an app can call alert twice in a row, and the second alert can happen before the first ContentDialog has been dismissed.

This kills the app.

**Comment by chrisglein** [comment]
Could workaround by implementing a dialog manager that handles only one ContentDialog at a time.
Or we could not use ContentDialog.
Or we could press on WinUI to create a dialog control that allows more than one at a time. This should happen regardless, but we'll need to do something to handle this in the meantime.
