### ISSUE TITLE
Community View Managers cannot provide a view property named "transform" (causes runtime error)

### ISSUE THREAD

**Issue by jaimecbernardo** [microsoft/react-native-windows#7300]
When building a C++ native module for React Native Windows, it's not possible to use a "transform" property in the module that has a different semantics than being a 16-sized array, since "FrameworkElementViewManager.cpp" asserts this: https://github.com/microsoft/react-native-windows/blob/74fade929f70270e6174ad70c263efa6059fbef5/vnext/Microsoft.ReactNative/Views/FrameworkElementViewManager.cpp#L210

When a "transform" property is set to an array of another size (ex.: 6-sized array for 3x2 Matrixes), I'd expect to handle this in the module's own `UpdateProperty`, but the `FrameworkElementViewManager::UpdateProperty` is still called and hits that assert.

I expect similar issues might occur on the other property names defined in `FrameworkElementViewManager::UpdateProperty`.

Current workaround for this is using other names, like `transform_windows` instead, and adding `ifs` in `JavaScript` to use different property names depending on `Platform.OS`, but this is not ideal.

## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`:
```
4.14.0
```
2. `npx react-native info`:
```
System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 5.05 GB / 15.92 GB
  Binaries:
    Node: 12.16.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.2, 29.0.3
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.17763.0, 10.0.18362.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.8.31005.135 (Visual Studio Community 2019)
  Languages:
    Java: 1.8.0_262
    Python: 3.8.2
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
    react-native-windows: ^0.63.0-0 => 0.63.22
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce

We can use this repo's C++ sample app and custom user control to replicate this issue: https://github.com/microsoft/react-native-windows/tree/74fade929f70270e6174ad70c263efa6059fbef5/packages/sample-apps

1. In https://github.com/microsoft/react-native-windows/blob/74fade929f70270e6174ad70c263efa6059fbef5/packages/sample-apps/windows/SampleLibraryCPP/CustomUserControlViewManagerCPP.cpp#L65-L69 add `nativeProps.Insert(L"transform", ViewManagerPropertyType::Array);` to `CustomUserControlViewManagerCpp::NativeProps()`.
2. In https://github.com/microsoft/react-native-windows/blob/74fade929f70270e6174ad70c263efa6059fbef5/packages/sample-apps/index.windows.js#L343 add `transform={[1,0,0,0,1,0]}` to the `CustomUserControlCpp` properties.
3. Run the `SampleAppCpp` project in Debug and it will hit the assert: https://github.com/microsoft/react-native-windows/blob/74fade929f70270e6174ad70c263efa6059fbef5/vnext/Microsoft.ReactNative/Views/FrameworkElementViewManager.cpp#L210

## Expected Results
I expect to be able to use the same property names as I'm able to use on other platforms in my native modules.

**Comment by chrisglein** [comment]
> I expect to be able to use the same property names as I'm able to use on other platforms in my native modules.

FrameworkViewManager is interpreting "transform", making this a special property name for RNW where it isn't for other platforms. This problem isn't specific to "transform". UpdateProperties needs to let you control whether you also want to call the super.

In the meantime, yes your workaround is to use a different name
