### ISSUE TITLE
DevMenu sizes wrong, should contain a scrollviewer 

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#7301]
If the window is near the top, the popup will only go as far as the top of the screen and as low as the top of the app window

![image](https://user-images.githubusercontent.com/22989529/110322481-0c363d00-7fc8-11eb-9b0b-22b5e8a2f007.png)

Slightly more room:

![image](https://user-images.githubusercontent.com/22989529/110322700-633c1200-7fc8-11eb-9ad4-545aaaf80dd5.png)

**Comment by chrisglein** [comment]
XAML is in charge of the flyout positioning here. Which is half of the problem. Maybe a core XAML bug? But independent of that this should probably have a scroll viewer for cases where it does get clipped.

**Comment by jonthysell** [comment]
No longer repros.
