### ISSUE TITLE
Pointer events firing before blur events cause TextInput to lose focus

### ISSUE THREAD

**Issue by rozele** [microsoft/react-native-windows#7303]
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Open RNTester > TextInput examples
2. Scroll to "Text selection & cursor placement" example
3. Set focus on single line TextInput control
4. Select an item to change the focus (e.g., "Place at Start (0, 0)")
5. Observe that TextInput loses focus

What is happening here is the following sequence of events:
1. TouchEventHandler.cpp receives PointerPressed event
  a. Triggers `RCTEventEmitter.receiveTouches` for `topTouchStart`
  b. Triggers `onPress` callback for Text component
  c. Calls `.focus()` on TextInput ref
  d. Calls `TextInputState.focusTextInput`, which sees `currentlyFocusedInputRef` is already set to the target TextInput
2. TextInputViewManager.cpp receives LostFocus event
  a. Triggers `RCTEventEmitter.receiveEvent` for `onBlur`
  b. Triggers `onBlur` on TextInput
  c. Calls `TextInputState.blurTextInput`, which sets `currentlyFocusedInputRef` to null.
  
So the problem is that the call to 2c comes after the check in 1d, which is deterministic in react-native-windows because the PointerPressed event will always fire before the FocusLost event.
   
## Expected Results
TextInput should be focused after step 4 of the repro.

## Snack, code example, screenshot, or link to a repository:

https://user-images.githubusercontent.com/1106239/110357204-0876da80-8009-11eb-98b0-2a863dfa7241.mp4

**Comment by rectified95** [comment]
@NickGerleman This looks similar to the fix you upstreamed for clicks getting 'swallowed' - is this a different scenario?

**Comment by NickGerleman** [comment]
Different scenario. The clicks being swallowed issue was related to ScrollView capturing then stopping propagation of touches when JS thought we had a currently focused input. This was due to a faulty assumption upstream that having an input focused meant we always needed to eat the tap to dismiss soft keyboard.
