### ISSUE TITLE
Image crashes on path with non en-us characters

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#7321]
I have problem to open image if user's home folder contains some charasters that needs to be encoded. 

Images are shown from app in folder `C:\Users\smith\AppData\Local\Packages...` but
images are empty from folder  `C:\Users\smithé\AppData\Local\Packages...` there is `é` char in path

_Originally posted by @tero-paananen in https://github.com/microsoft/react-native-windows/issues/7197#issuecomment-793452781_

**Comment by tero-paananen** [comment]
react-native: 0.62.2 => 0.62.2                                                                                                                         
react-native-windows: 0.62.15 => 0.62.15

**Comment by tero-paananen** [comment]
I use currently images with url `file:///c:/...`

I will try images with url `ms-appdata:///local/users/...`

**Comment by tero-paananen** [comment]
> I use currently images with url `file:///c:/...`
> 
> I will try images with url `ms-appdata:///local/users/...`

Yes! Image urls with `ms-appdata:///` prefix that contains non us letters works.

**Comment by asklar** [comment]
Can you clarify if the `file` scheme works if the path _only_ contains en-us letters? It's also possible the issue might be related to the app in the appcontainer not having permissions so want to make sure you can say whether a new path (never navigated to within the app) works with file:// and with/without non english characters

**Comment by tero-paananen** [comment]
> Can you clarify if the `file` scheme works if the path _only_ contains en-us letters? It's also possible the issue might be related to the app in the appcontainer not having permissions so want to make sure you can say whether a new path (never navigated to within the app) works with file:// and with/without non english characters

file:// scheme works with us letters and in app container. 

file:// scheme with some special letters for example è may work if it is not encoded. After encoding it and sending to ReactImage.cpp it does not work.

**Comment by tero-paananen** [comment]
More other problems, i could not use `ms-appdata:///` prefix with the image path because after that is image file somehow locked in ReactImage and it cannot be removed from disk.

I use `file:///` urls and i call `decodeURI ` before sending urls to ReactImage

**Comment by juhasuni** [comment]
We've further investigated the issue and according to documentation:
https://docs.microsoft.com/en-us/windows/uwp/app-resources/uri-schemes

> The characters "?", "#", "/", "*", and '"' (the double-quote character) must be percent-encoded in a path to represent data such as file or folder names.

So basically this says, that we should only encode the reserved characters mentioned in the documentation (see above) or according to RFC 3986 (the standard has more reserved characters). 

> The path component matches the generic RFC 3986 syntax and supports non-ASCII characters in IRIs.

Here it also says that it is OK to use non-ASCII characters without encoding.

For developer this means, that the URLs used should not be encoded using `encodeURI` or  `encodeURIComponent` as those functions encode too much (they encode all non-ASCII characters).

So here's our attempt for reference for re-encoding the URL:

```ts
const MATCH_RFC_3986_RESERVED = /[:/?#[\]@!$&'()*+,;="]/g;

/**
 * Convert local file URL to a format that is compatible
 * with the current platform. Platforms may have special rules regarding
 * to URL encodings that they support and they may not for instance
 * support multi-byte characters in URL/percent encoded form.
 */
export function toPlatformEncodedUrl(url: string) {
  // Windows doesn't support multi-byte characters that are percent-encoded
  // like "ä" which becomes "%C3%A4". For that reason we encode the `path` section
  // of the URL again using reserved characters as specified in RFC 3986 standard.
  if (Platform.OS === 'windows') {
    // Capture (1) the beginning of the URL (protocol and hostname),
    // (2) the path and (3) the remaining items like query string and fragment.
    // We're not using URL parsing library here, because they are not well suitable
    // for the case, where we may have "C:" as the hostname (they except port number to appear
    // after "C:"" but it doesn't).
    const match = /^(file:\/\/[^/]*)([^?#]+)(.*)/.exec(url);

    if (match) {
      const [_full, protocolAndHostname, path, searchAndFragment] = match;

      // We can't just decode the entire path using decodeURI, since then we won't be able
      // to distinguish which "/" were path delimiters and which were part of the filenames.
      // For that reason we split the path and decode-encode each item separately.
      const reEncodedPath = path
        .split('/')
        .map(item =>
          decodeURIComponent(item).replace(
            MATCH_RFC_3986_RESERVED,
            c => '%' + c.charCodeAt(0).toString(16).toUpperCase()
          )
        )
        .join('/');

      return `${protocolAndHostname}${reEncodedPath}${searchAndFragment}`;
    }
  }

  return url;
}
```

So this is not strictly a bug but could we somehow make this more developer-friendly? This generates hard-to-trace bugs as in our case where the bug appeared only with specific user folder names.

**Comment by juhasuni** [comment]
As a side note, I must say I wasn't aware of IRI (vs URI) which is by definition:

> An Internationalized Resource Identifier is defined similarly to a URI, but the character set is extended to the Universal Coded Character Set. Therefore, it can contain any Latin and non Latin characters except the reserved characters.

So we should also have `encodeIRI` and `encodeIRIComponent` 😉

**Comment by asklar** [comment]
@tero-paananen if you are still affected by this (though unblocked by not encoding), can you share a callstack of the crash and some more info on how you're passing the image url  (is that from JS? or?)

**Comment by tero-paananen** [comment]
> @tero-paananen if you are still affected by this (though unblocked by not encoding), can you share a callstack of the crash and some more info on how you're passing the image url (is that from JS? or?)

This works when uri is not encoded.
```
render() {
    const filename = 'imageé.jpg';  // NOTE:  è letter here
    const source = {
      uri:
        'file:///C:/Users/tepaa/AppData/Local/Packages/MyApp_hjvck6e55h582/LocalState/' +
        filename,
    };
    return (
      <Image
        source={source}
        style={{ width: 100, height: 100, resizeMode: 'contain' }}
      />
    );
  }
```

after uri is encoded to `file:///C:/Users/tepaa/AppData/Local/Packages/MyApp/LocalState/image%C3%A9.jpg` image is not shown

```
const filename = encodeURIComponent('imageé.jpg');   // NOTE:  è letter here
    source = {
      uri:
        'file:///C:/Users/tepaa/AppData/Local/Packages/MyApp_hjvck6e55h582/LocalState/' +
        filename,
    };
```

**Comment by tero-paananen** [comment]
But for example image with name `image#.jpg` can be encoded and it works

```
const filename = encodeURIComponent('image#.jpg');
    const source = {
      uri:
        'file:///C:/Users/tepaa/AppData/Local/Packages/MyApp_hjvck6e55h582/LocalState/' +
        filename,
    };
```

**Comment by tero-paananen** [comment]
I found that at least encoding `imagè` and `image=` are the special cases when image is not shown.

**Comment by tero-paananen** [comment]
Place where uri handling goes invalid is the call `winrt::Uri uri{Utf8ToUtf16(source.uri)};` in `ReactImage::Source()` in `ReactImage.cpp`

**Comment by asklar** [comment]
There's this note in the Uri doc: https://docs.microsoft.com/en-us/uwp/api/Windows.Foundation.Uri?view=winrt-19041#remarks

> ## Important
> When programming with .NET, this class is hidden and developers should use the System.Uri class, which uses RFC 3987 rules to encode and decode Uniform Resource Identifier (URI). The Windows.Foundation.Uri class doesn't percent-encode non-ASCII characters in Uniform Resource Identifier (URI) where the scheme refers to a Windows file path (like ms-appx:). Windows.Foundation.Uri also interprets percent-encoding using the user's current codepage.

So I think that explains what you're seeing.

**Comment by tero-paananen** [comment]
> There's this note in the Uri doc: https://docs.microsoft.com/en-us/uwp/api/Windows.Foundation.Uri?view=winrt-19041#remarks
> 
> > ## Important
> > When programming with .NET, this class is hidden and developers should use the System.Uri class, which uses RFC 3987 rules to encode and decode Uniform Resource Identifier (URI). The Windows.Foundation.Uri class doesn't percent-encode non-ASCII characters in Uniform Resource Identifier (URI) where the scheme refers to a Windows file path (like ms-appx:). Windows.Foundation.Uri also interprets percent-encoding using the user's current codepage.
> 
> So I think that explains what you're seeing.

You mean that `System.Uri` handles this encoding but we are now using `Foundiation.Uri` that does not handle encoding for example `è` ?

**Comment by asklar** [comment]
Correct, React Native Windows uses cppwinrt to interface with system WinRT APIs, specifically it uses Windows.Foundation.Uri, so it behaves different from how .NET System.Uri or JS's uri encoding/decoding does.

**Comment by chrisglein** [comment]
Based on that I think the uri encoding behavior observed here seems to be by design, correct? (we match the behavior of our dependencies)
@tero-paananen are you unblocked here?

**Comment by tero-paananen** [comment]
> Based on that I think the uri encoding behavior observed here seems to be by design, correct? (we match the behavior of our dependencies)
> @tero-paananen are you unblocked here?

I have to use our uri helper encoder function toPlatformEncodedUrl
