### ISSUE TITLE
How to access ReactNativeHost? Can't get Sample to work.

### ISSUE THREAD

**Issue by creambyemute** [microsoft/react-native-windows#7324]
Hey there,

I'm trying to use the ReloadInstance method of the ReactNativeHost to restart the App/reload the bundle. I had a look at the sample which implements this it seems: https://github.com/microsoft/react-native-windows/blob/910ed096b6fcea634b3206d3448cc3a335bc8e89/packages/sample-apps/windows/SampleLibraryCPP/SampleModuleCPP.h

I've tried different things now but always end up with an error message when trying to get to the ReactNativeHost or its ReloadInstance method.:
* FromContext is not a member of "winrt::Microsoft::ReactNative::ReactNativeHost"
* GetReactNativeHost is not a member of "winrt::Microsoft::ReactNative::ReactNativeHost"
* "invalid call of a non-static member function ReloadInstance"

Is this even possible?

React-Native-Windows Version: 0.63.11

The Module is placed directly under the windows/mySlnName in my project.
AppRestart.h
```
#pragma once
#include "pch.h"
#include "NativeModules.h"
#include <string>
namespace RN = winrt::Microsoft::ReactNative;

namespace myApp::AppRestart {
    REACT_MODULE(AppRestart, L"AppRestart");
    struct AppRestart final {
        RN::ReactContext m_reactContext;

        REACT_INIT(Initialize)
            void Initialize(RN::ReactContext const& reactContext) noexcept;

        REACT_METHOD(Restart)
        winrt::fire_and_forget Restart(RN::ReactPromise<RN::JSValue> promise) noexcept;
    };
}
```

AppRestart.cpp
```
#include "pch.h"
#include "AppRestart.h"
#include <windows.h>
#include <winrt/Windows.Foundation.h>
#include <winrt/Windows.System.h>

using namespace winrt;
using namespace winrt::Windows::Foundation;
using namespace Windows::System;

namespace myApp::AppRestart{
    void AppRestart::Initialize(RN::ReactContext const& reactContext) noexcept {
        m_reactContext = reactContext;
    }

    winrt::fire_and_forget AppRestart::Restart(RN::ReactPromise<RN::JSValue> promise) noexcept
   {
        RN::ReactNativeHost::GetReactNativeHost(m_reactContext.Properties()).ReloadInstance();
        // co_await RN::implementation::ReactNativeHost::GetReactNativeHost(m_reactContext.Properties());
       // ... some more unsucessful tries ...
        promise.resolve(RN::JSValue::Null)
    }
}
```

**Comment by asklar** [comment]
@creambyemute you might be looking at the wrong version, I believe the sample you mentioned is using a preview version of 0.64.
 can check out the native API reference for 0.64 here: https://microsoft.github.io/react-native-windows/docs/next/Native-API-Reference

**Comment by asklar** [comment]
In 0.64 we started to auto-generate our docs from our interface definition source code. In 0.63 we don't have the textual description of the APIs, but there's still value in having the types and APIs documented. PR is here: https://github.com/microsoft/react-native-windows-samples/pull/403

**Comment by creambyemute** [comment]
Alright, I already starting suspecting this. Will try again in 0.64 👍

**Comment by asklar** [comment]
You can do this from the JS side with a public API - @NickGerleman can you share the details?

**Comment by acoates-ms** [comment]
This should work today:

```js
import {DevSettings} from 'react-native';
DevSettings.reload();
```

**Comment by creambyemute** [comment]
Does devSettings.reload work in production though?

**Comment by acoates-ms** [comment]
It should work yeah.

**Comment by creambyemute** [comment]
I've tried that now and it works in Dev/Debug mode but not in Production. It seems React-Native exports a noop there on prod builds.

I then tried to directly go via the NativeModules:
```
import { NativeModules } from "react-native";

NativeModules.DevSettings.reload(); // Works in debug, but not in prod either
```

**Comment by acoates-ms** [comment]
Oh looks like you are right, the js DevSettings module is no-op'd in production.

DevSettings isn't a NativeModule in all cases. In particularly in production it'll be a TurboModule.  Try:

```js
import {TurboModuleRegistry} from 'react-native';
TurboModuleRegistry.getEnforcing('DevSettings').reload();
```

**Comment by creambyemute** [comment]
Unfortunately no luck, I tried with 

```javascript
import * as TurboModuleRegistry from "react-native/Libraries/TurboModule/TurboModuleRegistry";
TurboModuleRegistry.getEnforcing('DevSettings').reload();
```

which works in debug again and in release/production is closing or crashing the App, not quite sure there :-).

**Comment by chrisglein** [comment]
This scenario sounds very similar to what [code-push](https://github.com/Microsoft/react-native-code-push) enables. Is there anything to be gained from looking into how it does what it does?

> which works in debug again and in release/production is closing or crashing the App, not quite sure if it's a crash or just closing the app :-)

@creambyemute If it is a crash can you get the callstack? Also, was this after upgrading to 0.64 (just moved out of preview on Monday, hot off the presses :D)

@acoates-ms  / @NickGerleman Is there an other option outside of `DevSettings` that you can comment on?

**Comment by vmoroz** [comment]
@creambyemute, we have the 0.64 already released and you can use the new APIs.
In 0.63 as a work around for the code-push module we just stored the ReactNativeHost instance inside of the ReactInstanceSettings.Properties and then access it from the native module ReactContext.Properties.
It creates a reference loop, but it should be OK if there is only one ReactNativeHost per app. Otherwise, it must be explicitly removed from Properties.

**Comment by creambyemute** [comment]
I'm just upgrading from 0.63.3 to 0.64 and will try again afterwards and report back and close the issue if it works 👍 .
