### ISSUE TITLE
View managers don't have a way to listen for JS event/detach 

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#7334]
Right now view managers are not able to get notifications when JS adds/removes an event handler. This means view managers must set up native event handlers "just in case" the JS side wants to listen for them

**Comment by chrisglein** [comment]
Do we need this for 0.64? Would it be a breaking change to include in a dot release?
Are there documentation implications?

**Comment by asklar** [comment]
@chrisglein not needed for 0.64; I found out from Eric that there is an undocumented way to do this (declare the event as part of the set of supported native props, with type boolean (!!!)). This work will just make it more clear that this is possible to do without resorting to arcane workarounds :)
