### ISSUE TITLE
Reevaluate which nodejs version we should require

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#7336]
E.g. any odd number of Node is not an LTS, but we allow 13. Same with 12 no longer being LTS. Maybe we should just check for Node >= 12

_Originally posted by @NickGerleman in https://github.com/microsoft/react-native-windows/pull/7294#discussion_r589628343_

**Comment by NickGerleman** [comment]
In the meantime, the description in the dependencies script for Node is no longer accurate 😕.

**Comment by asklar** [comment]
Message should say >=12.

**Comment by chrisglein** [comment]
Related to #8345

**Comment by NickGerleman** [comment]
Both should be fixed with https://github.com/microsoft/react-native-windows/pull/8982
