### ISSUE TITLE
Pressable.Cancelable not implemented

### ISSUE THREAD

**Issue by rectified95** [microsoft/react-native-windows#7344]
In a recent commit - https://github.com/facebook/react-native/commit/7f005e6077398d2a7f31cb78313c90c667050792 - the `cancelable` prop was added to `Pressable`. We should understand if/how it should be implemented in RNW.

**Comment by NickGerleman** [comment]
I don't think there are native changes needed. See its usable in Pressability: https://github.com/facebook/react-native/blob/master/Libraries/Pressability/Pressability.js

**Comment by asklar** [comment]
This should be handled on the JS side, we shouldn't need to do anything.
