### ISSUE TITLE
Validate Microsoft.ReactNative with binskim

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#7345]
[BinSkim](https://github.com/Microsoft/binskim) performs static analysis on PE binaries and validates "the right flags" (compiler, linker, etc.) are set for shipping binaries (to ensure security, performance, etc.). We should run this on M.RN.

**Comment by asklar** [comment]
Duplicate of #7313

**Comment by chrisglein** [comment]
Tracking with [internal issue](https://microsoft.visualstudio.com/DefaultCollection/OS/_workitems/edit/32089296)
