### ISSUE TITLE
Rework CLI to create minimal projects with pluggable item templates

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#7348]
Today you can create an app or a module. This makes it harder to add a module to an app (i.e. one that isn't distributed separately). There is a lot of code that would get duplicated, and if the dev wants to ship the app/module together and doesn't care about OSS the module, there is manual work to move things around in VS.

Ideally here's what I'd like to see:

### Create an app
```
npx react-native-windows-init MyApp
```

### Create a barebones project
```
npx react-native-windows-init MyRNWProject --projectType barebones
```

### Add items to a barebones project
```
npx react-native-windows-init MyRNWProject --projectType barebones
cd MyRNWProject
npx react-native-windows-init --projectType app
npx react-native-windows-init --projectType module MyModule
npx react-native-windows-init --projectType viewManager MyViewManager
```

As an added bonus, this can be integrated into Visual Studio as a RNW VSIX. This last bit seems like a good intern project :)

**Comment by NickGerleman** [comment]
There's been some desire to refactor the upstream community CLI to support composable templates. This is another interesting angle, since it makes it easier to adopt RNW, and removes the need for a separate react-native-windows-init.

**Comment by jonthysell** [comment]
Interesting idea, but the priority of the CLI **is** making OSS customers lives' easier.
