### ISSUE TITLE
Unable to resolve module which basically included in Node.js

### ISSUE THREAD

**Issue by jihoobyeon** [microsoft/react-native-windows#7353]
I am working for simple React Native for Windows app which reads MS Access file and Shows data on screen.\
But when I run my app with `react-native run-windows`, A red screen appears and shows this error:\
``Unable to resolve module `bar` from `C:\Users\myname\Desktop\project1\node_modules\baz\lib\qux.js` ``

When I fix it, another one appears. again fix it, and another.\
The clue is every module `` `bar` ``s are modules basically included in Node.js, such as `` `fs` ``, `` `path` ``, and `` `events` ``.\
So I deleted every `const bar = require('bar');` in every `qux.js`. and finally, screen became blank, and this error appears in terminal:
`Package react-native-windows has been ignored because it contains invaild configuration. Reason: events is not defined`

I asked it to `odbc` team, but they said it's not their fault. I think so too, since many `baz`s are outside in `odbc`.
But strangely, if I exclude `odbc`, the app works fine.

## Environment
Microsoft Windows 10
JetBrains Webstorm 2020.3
TypeScript 4.1.3
Node.js 14.15.4 LTS
npm 6.14.10
Yarn 1.22.10
React 16.13.1
React Native 0.63.4
React Native for Windows 0.63.23
Microsoft Access 2019

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Include [`odbc`](https://www.npmjs.com/package/odbc) in your project.
2. Voilà!

## Expected Results
Just show `Hello, world!`

## Snack, code example, screenshot, or link to a repository:
My still incomplete `App.ts`:
```
import React, { Component } from 'react';
import { Text, View } from 'react-native';
import odbc from 'odbc';

const e = undefined;
const c = undefined;

odbc.connect("Driver={Microsoft Access Driver (*.mdb)};Dbq=C:\\Users\\myname\\Desktop\\foo.mdb;Uid=Admin;Pwd=;", (e, c) =>
{
  // TO DO
});

class App extends Component
{
  render()
  {
    return React.createElement(View, null, React.createElement(Text, null, "Hello, world!");
  }
}

export default App;
```

**Comment by asklar** [comment]
you can't use npm packages in RN just like you can in nodejs; for example, packages that use filesystem APIs, registry APIs, etc. won't work in UWP apps.

**Comment by jihoobyeon** [comment]
@asklar Oh, then how can I make my app to read MS Access files?
maybe make another Node.js app and call that in RN app <-- is this possible?

**Comment by asklar** [comment]
@jihoobyeon It might be possible through something called Desktop Bridge (aka "Centennial") apps. This is not something our team supports or has deep expertise in, but you can investigate this on the docs.microsoft.com website.

For the time being I recommend reading this doc of ours that talks about what a RNW UWP app can do: https://microsoft.github.io/react-native-windows/docs/next/native-code

**Comment by jihoobyeon** [comment]
@asklar Ok, thanks! I'll try it.
