### ISSUE TITLE
WinUI 3/Reunion Desktop app template

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#7359]
<I could have sworn I had something filed but I can't find it.>
WinUI 3 introduces a new way to build desktop apps via the new Window type. This targets several new technologies that - if we were to adopt - would put us on a more future-looking path forward:
- WinUI 3, the Fluent UI platform, decoupled from Windows
- Win32 app model, a la carte uwp-like features without requiring app container, etc.
- .net core 5 / 6 & C#/WinRT

The proposal here is to either create a new app template to target this app type, or re-target the existing WinUI experimental template to use this.

**Comment by 500-internal-server-error** [comment]
Hello, may I know if RNW can create a win32 winui 3 app instead of an UWP app yet?

**Comment by asklar** [comment]
@500-internal-server-error  still not currently supported (no easy-to-use template, etc.), though the foundational pieces are there

**Comment by chrisglein** [comment]
Back in late 2021 / early 2022 we started a WinAppSDK new app template based on understanding of WinAppSDK at the time. And then came [Fabric](https://github.com/microsoft/react-native-windows/issues/12042) and impact on our overall strategy for how to handle Win32/WinAppSDK. As such these original plans don't make as much sense and we'll be closing them as Not Planned. That's not in any way to say RNW isn't going to support WinAppSDK, we're just doing it differently! Track our [Fabric](https://github.com/microsoft/react-native-windows/issues/12042) progress for details on the new app template and how that'll be compatible with WinAppSDK.

In particular for this, this is the first item to watch: https://github.com/microsoft/react-native-windows/issues/11908
