### ISSUE TITLE
react-native link <package> doesn't work

### ISSUE THREAD

**Issue by joewood** [Microsoft/react-native-windows#738]
I think this is on the to-do list, but I didn't see an issue for it. If I try:

```
npm i react-native-vector-icons
react-native link react-native-vector-icons
```

I would expect the **rnpm** section in package.json file in [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons):

``` json
 "rnpm": {
    "assets": [
      "Fonts"
    ]
  },
```

to be recognized by the **react-native-plugin-windows** package and add the contents of that directory as asset links to the app's csproj file.

This problem was found doing this PR: https://github.com/oblador/react-native-vector-icons/pull/308

Note, this was **rnpm link** - which doesn't work either (seems to error out).

**Comment by rozele** [comment]
:+1: there are a few steps leading up to this, one of which is getting the RNPM config for platforms other than iOS and Android.
https://www.facebook.com/groups/reactnativeoss/permalink/1588254314804530/

**Comment by rozele** [comment]
It looks like this will be resolved in react-native 0.41: https://github.com/facebook/react-native/commit/445182c7076593863bcf7dd191d2c4285d6c4b22

**Comment by rozele** [comment]
Closing now that we have react-native-windows@0.41.0-rc.1 available.

**Comment by rozele** [comment]
Re-opening, I don't think this is working again

**Comment by mehdijjz** [comment]
It's not working for me neither, only shows: 
`➜  <PROJECT> git:(master) react-native link <PACKAGE>
Scanning 866 folders for symlinks in /Users/mehdijjz/Development/Projects/<PROJECT>/node_modules `

**Comment by rozele** [comment]
Link should be working again!
