### ISSUE TITLE
How to dispatch to UWP UI thread in native module

### ISSUE THREAD

**Issue by jicailiu1** [microsoft/react-native-windows#7385]
Hi,

I'm writing a native module wants to open a window picker to do screen capture. Knowing PickSingleItemAsync need to be called on UWP UI thread, I'm trying to dispatch the call.

First I tried to do it the way used to work for me via a dispatcher from core window, the callback got triggered but at the same thread on caller, which results access decline on opening Windows UI.  
```
    winrt::GraphicsCaptureItem item = nullptr;
    awaitable_event pickEvent;
//    co_await winrt::Windows::UI::Core::CoreWindow::GetForCurrentThread().Dispatcher().RunAsync(
    winrt::Windows::ApplicationModel::Core::CoreApplication::MainView().CoreWindow().Dispatcher().RunAsync(
        winrt::Windows::UI::Core::CoreDispatcherPriority::Normal, [&item, &pickEvent]() -> winrt::IAsyncAction
    {
        auto picker = winrt::Windows::Graphics::Capture::GraphicsCapturePicker();
        item = co_await picker.PickSingleItemAsync();
        pickEvent.set();
    });

    co_await pickEvent;

```

I also tried using a dispatch from react native API, it gave the same result. 
```
    auto dispatcher = winrt::ReactDispatcherHelper::UIThreadDispatcher();
    dispatcher.Post([&item, &pickEvent]() -> winrt::IAsyncAction {...});
```

Did I do anything wrong? What is the correct way of dispatch to UWP UI thread?

**Comment by asklar** [comment]
We should document REACT_INIT - tracked by https://github.com/microsoft/react-native-windows-samples/issues/254

**Comment by asklar** [comment]
https://microsoft.github.io/react-native-windows/docs/next/ReactDispatcherHelper#uithreaddispatcher

we should update the documentation to say that UIThreadDispatcher property can only be called from a UI thread - so the idea is you call it from a UI thread, put the value in the property bag, then access the property bag value from the non-UI thread

**Comment by acoates-ms** [comment]
Basically within your module:

```cpp
    REACT_INIT(Initialize)
    void Initialize(ReactContext const &reactContext) noexcept
    {
        m_reactContext = reactContext;
    }
```

Then you can use `m_reactContext.UIDispatcher` to dispatch things to the UI thread in other native module calls.

**Comment by jicailiu1** [comment]
Thank you for the reply. I added suggested piece and updated code to 
```
    winrt::GraphicsCaptureItem item = nullptr;
    awaitable_event pickEvent;

    auto dispatcher1 = m_context.UIDispatcher();
    dispatcher1.Post([&item, &pickEvent]() -> winrt::IAsyncAction {
        auto picker = winrt::Windows::Graphics::Capture::GraphicsCapturePicker();
        item = co_await picker.PickSingleItemAsync();
        pickEvent.set();
        });

    co_await pickEvent;
```

But still having winrt::hresult_access_denied exception inside the callback, any other direction I could look into?
