### ISSUE TITLE
Support UnsupportedUriSchemeIdentified event in WebView

### ISSUE THREAD

**Issue by henningms** [Microsoft/react-native-windows#739]
In the app we're developing we're interacting with some webpages that uses different techniques for telling the app to close the webview. Redirecting to "close" or "about:blank" is some of them for instance. These URIs aren't handled in the OnNavigationCompleted or Failed but rather in the "UnsupportedUriSchemeIdentified" event in a WebView.

Would love for those events to be handled and passed to the LoadFinished event. 

https://msdn.microsoft.com/library/windows/apps/windows.ui.xaml.controls.webview.unsupportedurischemeidentified.aspx

**Comment by rozele** [comment]
@henningms please provide an update if this is still an issue, otherwise we'll close.
