### ISSUE TITLE
View Example Isn't Hit In visitAllPages e2e Test

### ISSUE THREAD

**Issue by AgneLukoseviciute** [microsoft/react-native-windows#7392]
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`: `5.0.1-alpha.1`
2. `npx react-native info`: `System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 15.48 GB / 31.59 GB
  Binaries:
    Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.17763.0, 10.0.18362.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.8.31019.35 (Visual Studio Enterprise 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found`

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Run `yarn windows --no-launch` followed by `yarn e2etest .\VisitAllPages.test.ts` in e2e-test-app directory
2. Notice how the View component page isn't actually opened

## Expected Results
visitAllPages should click on the View example button and actually enter the page as intended. I think this isn't happening, because when 'View' is entered in the search bar, View example button is not actually visible - because there are several other examples with "View" in the title, you have to scroll to see the View button even after searching. Adding some regex along with the example name(e.g. '\tView\t') in the e2etest navigation.ts file fixes this in that the search returns only the one example - but with this there was unexpected behavior in that when the tests run - sometimes the example wouldn't get clicked and the tests would time out. 

![view now e2e](https://user-images.githubusercontent.com/41223743/111218649-0088de80-85a5-11eb-8455-001806cf9457.PNG)
![view in e2e](https://user-images.githubusercontent.com/41223743/111218662-0383cf00-85a5-11eb-8200-d1f4829289b5.PNG)

**Comment by chrisglein** [comment]
@AgneLukoseviciute is the `\bView\b` functioning as a workaround?

Ideas for how to address more fundamentally:
- Enable the test to scroll and wait for items to realize
- Look up tests by a more unique identifier (give all tests a testid of some sort that's not just the string)
- Have a flag to force exact string matches instead of partial string matches

**Comment by AgneLukoseviciute** [comment]
I couldn't get \bView\b working entirely, there was some strange behavior where the test would not click on some of the components after search was complete and get stuck. I tried adding logic for it to wait until the search was complete before attempting to click on the button, but that didn't seem to fix it. 

The first thing I tried was scrolling the example button into view using [.scrollIntoView()](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) but it was throwing an error saying the method was not implemented, if there's a way to get this to work I think that would be the ideal solution.

**Comment by AgneLukoseviciute** [comment]
Closing. Running .\VisitAllPages.test.ts today & this is no longer an issue. Could be due to changes in jest or webdriver, don't think we changed anything with the footer in the e2e test app, but the test now scrolls to View and opens the example page.
