### ISSUE TITLE
Remove PFX files from repo

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#7400]
We should instead store the certificates as secrets on github.

We need to do the same for community modules we've added.

Also add .pfx to .gitignore.

**Comment by chrisglein** [comment]
@chiaramooney is working through how to do this for Gallery.
@asklar has some experience doing this for the XAML Islands samples and may be able to help form the right pattern here using github secrets.

**Comment by chrisglein** [comment]
Note: We also want to regenerate these under some non-personal account. Some of the existing ones (of about ~6?) need to be moved.

**Comment by chiaramooney** [comment]
All files removed from main. Now working on removing from other stable branches.
