### ISSUE TITLE
onScroll(Begin|End)Drag and onMomentumScroll(Begin|End) only emitted for first drag 

### ISSUE THREAD

**Issue by rozele** [microsoft/react-native-windows#7403]
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Open RNTester > ScrollView example
2. Find OnMomentumScroll example
3. Drag the ScrollViewer and "fling" to trigger inertial scrolling
4. Before the inertial scrolling comes to a stop, start dragging again
5. Notice that the `onMomentumScrollEnd` event doesn't fire until you've allowed the view port to come to rest.

## Expected Results

Each time I start dragging the ScrollView after inertial scrolling starts, I expect `onScrollBeginDrag` and `onMomentumScrollEnd`.

## Snack, code example, screenshot, or link to a repository:

https://user-images.githubusercontent.com/1106239/111371480-dbad6d80-866f-11eb-8b82-492bc8c4456f.mp4

**Comment by chrisglein** [comment]
Makes sense to me as expected behavior. @rozele , just to confirm does this match behavior in Android/iOS?

**Comment by rozele** [comment]
@chrisglein - actually no, turns out current RNW behavior matches iOS behavior. Closing for now.
