### ISSUE TITLE
Update doc that references IDesktopWindowXamlSourceNative interface

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#7408]
Filing task to update this once we have a doc page for the native IDesktopWindowXamlSourceNative interface

_Originally posted by @asklar in https://github.com/microsoft/react-native-windows/pull/7393#discussion_r595705690_

**Comment by chrisglein** [comment]
The only [existing doc](https://docs.microsoft.com/en-us/dotnet/api/microsoft.toolkit.win32.ui.xamlhost.idesktopwindowxamlsourcenative?view=win-comm-toolkit-dotnet-6.1) is for the toolkit. AKA not what we need to link to from our API docs.

**Comment by chrisglein** [comment]
Tracking issue on adding correct docs: https://github.com/MicrosoftDocs/winrt-api/issues/1503

**Comment by jonthysell** [comment]
I don't think we need to track this here any more.
