### ISSUE TITLE
Fix XamlUIService APIs that assume a single view for React app

### ISSUE THREAD

**Issue by vmoroz** [microsoft/react-native-windows#7411]
There a number of new API's that were recently added to the `XamlUIService` that assume that React native application uses a single root view. They associate window handlers and other properties with the React instance instead of `ReactRootView`.
The APIs in question are:
- SetXamlRoot
- SetAccessibleRoot
- GetXamlRoot
- GetAccessibleRoot
- GetIslandWindowHandle
- SetIslandWindowHandle

These APIs are first added in 0.64 and it would be nice to fix them in 0.64 until they get a broader use.

**Comment by chrisglein** [comment]
> it would be nice to fix them in 0.64 until they get a broader use.

I assume that would be a breaking API change? If so we wouldn't be able to take for a 0.64.x release. Let me know if that's wrong and it wouldn't be breaking. Otherwise I'm assuming we'll fix in 0.65.

**Comment by vmoroz** [comment]
We will discuss it with @asklar. I perceived it as an issue while working on the documentation in the IDL files.

**Comment by vmoroz** [comment]
> @chrisglein, we will discuss it with @asklar. I perceived it as an issue while working on the documentation in the IDL files.

@chrisglein, @asklar, I believe we can address this issue without breaking API, and thus making it part of 0.64: we just need to add a new IReactPropertyBag to the ReactRootView. This way we can make these XamlUIService APIs to be React root view specific, while keeping exactly the same XamlUIService API shape.
There will be only the behavioral changes and how these APIs are used.

**Comment by chrisglein** [comment]
@vmoroz @asklar This issue is from a couple releases ago in March. The immediacy of fixing within 0.64 seems clearly passed. Moving to backlog.

**Comment by rozele** [comment]
> we just need to add a new IReactPropertyBag to the ReactRootView

@vmoroz would love to hear more about your thoughts on this. My thought would be that the main IReactPropertyBag might just hold a map from root tag to XamlRoot, AccessibleRoot, IslandWindowHandle, etc., but are you suggesting that we should instead have a per root IReactPropertyBag where these are stored? And perhaps a XamlUIService API for `GetPropertiesForRootTag(context, tag)`?
