### ISSUE TITLE
Externalize WinUI and SDK version

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#7414]
Currently Microsoft.ReactNative and others import WinUI.props from node_modules, and set the SDK version within those projects.
WinUI 2.6 has a dependency on the 19041 SDK
This means that apps that want to consume WinUI 2.6 (and have M.RN use 2.6) end up having to touch up props files in node_modules

We should instead default to grab these properties from the solution folder, and if that doesn't exist we can import them from the node_modules location

**Comment by chrisglein** [comment]
We intend to update to 2.6 as soon as that ships (currently in preview), I'll open an issue on that. But there will always be a disconnect for teams that want to take on previews.

**Comment by chrisglein** [comment]
@asklar Was there any doc changes to show how to use ExperimentalFeatures.props to change this?

**Comment by chrisglein** [comment]
We've had some questions given recent news about how consumers of RNW can get the latest WinUI version (2.6). We have a change prepped to update the default (#7425), but perhaps we can provide more detail about how apps can opt into that today (or in the future, for when there's another WinUI version that people are excited about). @chiaramooney @asklar Any opinions on how we should document this?
