### ISSUE TITLE
Upgrade RNW 0.65 to use WinUI 2.6 by default (when available)

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#7425]
RNW currently pulls in 2.5 ([as of this change](https://github.com/microsoft/react-native-windows/issues/6182))

2.6 is coming. We'll want to start pointing to that once it's available.

A current preview here:
https://www.nuget.org/packages/Microsoft.UI.Xaml/2.6.0-prerelease.210217002

**Comment by chrisglein** [comment]
Related issue on making WinUI version more externally customizable: #7414

**Comment by chiaramooney** [comment]
Bugs in WinUI2.6 which would cause non-negligible issues for RNW:

https://github.com/microsoft/microsoft-ui-xaml/issues/5277
https://github.com/microsoft/microsoft-ui-xaml/issues/5299
https://github.com/microsoft/microsoft-ui-xaml/issues/5298

We should wait for these to be resolved before migrating 0.65 to WinUI2.6
