### ISSUE TITLE
Sync CLI Arg documentation for react-native-windows-init

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#7426]
The version on the docs site has the flag for `--useWinui3` , but it is not included in the package.json README.

Neither the docs site or README has documentation for the `--useHermes` flag.

**Comment by asklar** [comment]
See also #7442

**Comment by chrisglein** [comment]
Note missing [here](https://microsoft.github.io/react-native-windows/docs/getting-started#install-the-windows-extension) in the docs.

**Comment by imrishabh18** [comment]
@NickGerleman Can I take up this issue? Also, I am to this. Might need help

**Comment by chrisglein** [comment]
> @NickGerleman Nick Gerleman FTE Can I take up this issue? Also, I am to this. Might need help

@imrishabh18 Of course! We'd happily accept a fix for this.

**Comment by imrishabh18** [comment]
@chrisglein As I am new to this, Can you please guide me what are the things that you want to resolve this issue?

**Comment by chrisglein** [comment]
> @chrisglein As I am new to this, Can you please guide me what are the things that you want to resolve this issue?

There's a link [above](https://microsoft.github.io/react-native-windows/docs/getting-started#install-the-windows-extension) to the page in question.
The general information on how to update the website is [here](https://github.com/microsoft/react-native-windows-samples/tree/master/website).
I believe that same page's source is [here](https://github.com/microsoft/react-native-windows-samples/blob/master/docs/getting-started.md).
The package readme is [here](https://github.com/microsoft/react-native-windows/tree/master/packages/%40react-native-windows/cli)
@NickGerleman, respond if I missed anything. But I think the idea was to add `useHermes` to the docs and the readme, and to add `useWinUI3` to the readme.

**Comment by dannyvv** [comment]
Many thanks to @imrishabh18 for picking this up and fixing for us!

**Comment by dannyvv** [comment]
See also [PR #438@react-native-windows-samples](https://github.com/microsoft/react-native-windows-samples/pull/438)
