### ISSUE TITLE
Fix links in ExperimentalFeatures.props

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#7427]
The file references links like [https://microsoft.github.io/react-native-windows/docs/0.64/hermes](), but even after publish, links with an explicit 0.64 don't seem to work. Need to fix these, and see if we can create a permalink.

**Comment by chrisglein** [comment]
That's pretty annoying :(. Will Docusaurus v2 maybe help with this? We should check out whether we can do better permalinks once we update to that.
