### ISSUE TITLE
Simplify project creation flags

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#7442]
Today we have a couple of flags in ExperimentalFeatures.props: UseWinUI3 and UseHermes.
We also have flags in the init CLI to pre-seed the app with values for these properties, and different content in other files (packages.config, project files, etc.)
Finally, we also have autolinking which is now able to modify projects and packages.config on-the-fly to point to the right WinUI package flavor.

## Proposal
Simplify the app templates and init CLI, have it just write to ExperimentalFeatures.props (or react-native.config.js).
Then run autolinking before init finishes.
This ensures that project creation and autolinking results in the same contents, and removes complexity from the project init codepath.

**Comment by jonthysell** [comment]
No longer necessary.
