### ISSUE TITLE
configuring certificates in visual studio for windows app not working

### ISSUE THREAD

**Issue by kandabior** [microsoft/react-native-windows#7445]
## The Problem
In order to get an image from a camera using secured URL and the ```Image``` component I'm trying to configure certificates in visual studio, using the file Package.appxmanifest. In the "Decleration" tab I Added new certificate and installed it in the certificate store. 
After those steps, I still could not get the image while in the browser, with ```--ignore-certificate-errors``` flag, I could see the image.

My question is:
1. Is there any other way to configure the certificates for the react native windows app?
2. alternately, Is there any way to ignore the certificates errors and get the data without configuring the SSL certificates?

## Environment
Run the following in your terminal and copy the results here.
1.  
``` 
react-native-cli: 2.0.1
react-native: 0.63.4
```
2.
```
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
    Memory: 5.46 GB / 15.81 GB
  Binaries:
    Node: 15.5.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 7.3.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.17763.0, 10.0.18362.0
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    Visual Studio: 16.8.30907.101 (Visual Studio Community 2019)
  Languages:
    Java: 15.0.1
    Python: 2.7.18
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
    react-native-windows: ^0.63.0-0 => 0.63.23
  npmGlobalPackages:
    *react-native*: Not Found
```

![image](https://user-images.githubusercontent.com/48620177/111998312-8f0cdb00-8b24-11eb-992b-b8232d9dd8e0.png)

**Comment by asklar** [comment]
@kandabior 
> I still could not get the image while in the browser, with --ignore-certificate-errors flag, I could see the image

Can you clarify what this means? what browser are you referring to? and what are you passing `--ignore-certificate-errors` to?

**Comment by kandabior** [comment]
@asklar 
> Can you clarify what this means? what browser are you referring to? and what are you passing `--ignore-certificate-errors` to?

In chrome browser there is an option to open https pages with the flag ```--ignore-certificate-errors``` in order to load unknown https pages. I mentioned that to clarify that the image can be loaded in the browser, but whenever I try to load the image in react native using the Image component there is a white screen.
I wonder if there is an option to ignore ssl errors in react native.

**Comment by asklar** [comment]
The websocket API has a way to ignore cert errors, see e.g. [here](https://github.com/microsoft/react-native-windows/blob/9d552eb866c88910ac2e629c2430ce00bd36970c/vnext/Shared/WinRTWebSocketResource.cpp#L96-L101).
However this is not exposed to ImageSource's Source property or [BitmapImage ctor](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.imaging.bitmapimage.-ctor?view=winrt-19041#Windows_UI_Xaml_Media_Imaging_BitmapImage__ctor_Windows_Foundation_Uri_)

**Comment by chrisglein** [comment]
> I wonder if there is an option to ignore ssl errors in react native.

I think the answer to this is no, currently. The underlying XAML platform doesn't support this, so React Native for Windows can't.

If this a developer scenario you can install the cert to workaround this.

**Comment by kandabior** [comment]
So in case that there is not option to ignore the certification errors, The main question is how can I configure SSL certificate in react native project?

**Comment by asklar** [comment]
That's more of a question for either the XAML project or UWP platform. It's unclear whether the code that the BitmapSource(Uri) constructor uses would use a certificate embedded into the package like this, or if it is a missing feature. Can you file a bug in the XAML repo instead? 
https://github.com/microsoft/microsoft-ui-xaml/issues/
