### ISSUE TITLE
Scheduled publish for stable builds not running

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#7446]
The ADO scheduler is not picking up that 0.64-stable needs to publish.

**Comment by NickGerleman** [comment]
@jonthysell is this something we will need for 0.65? (Or maybe just to hardcode the branch.

**Comment by jonthysell** [comment]
I haven't been able to get the Microsoft ADO to pick up anything but master. I imagine I'll be kicking off the publish for 65 manually for a while too.
