### ISSUE TITLE
react-native-windows run via command line not working with VS 2019 Enterprise msbuild - "No public VS release found"

### ISSUE THREAD

**Issue by SBS-FPATE-RINALDI** [microsoft/react-native-windows#7448]
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`: 5.0.1-alpha.2
2. `npx react-native info`:  
System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
    Memory: 7.03 GB / 15.61 GB
  Binaries:
    Node: 14.15.5 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      Versions: 10.0.18362.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.8.30907.101 (Visual Studio Enterprise 2019)
  Languages:
    Java: 11.0.10 - C:\Program Files\AdoptOpenJDK\jdk-11.0.10.9-hotspot\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.0 => 0.64.0
    react-native-windows: ^0.64.0-0 => 0.64.0
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Follow guide [here](https://microsoft.github.io/react-native-windows/docs/getting-started) to get setup
2. Run the command npx react-native run-windows --logging

## Expected Results
Project is able to be built via command line

## Actual Results
says that valid msbuild tools cannot be found even though they exist on the system. Seems it is looking for community edition? 
`npx react-native run-windows --logging`:

 i Verbose: ON
- Auto-linking...
Parsing project...
Found Windows app project, config:
{
  folder: 'C:\\Users\\fpate-rinaldi\\OneDrive - Danaher\\Documents\\React-Native Testing\\Orca',
  sourceDir: 'windows',
  solutionFile: 'orca.sln',
  project: {
    projectFile: 'orca\\orca.vcxproj',
    projectName: 'orca',
    projectLang: 'cpp',
    projectGuid: '{97902121-2110-405e-9819-d577adcdfd53}'
  }
}
Parsing dependencies...
Calculating AutolinkedNativeModules.g.cpp...
Reading AutolinkedNativeModules.g.cpp...
No changes to AutolinkedNativeModules.g.cpp.
Calculating AutolinkedNativeModules.g.props...
Reading AutolinkedNativeModules.g.props...
No changes to AutolinkedNativeModules.g.props.
Calculating AutolinkedNativeModules.g.targets...
Reading AutolinkedNativeModules.g.targets...
No changes to AutolinkedNativeModules.g.targets.
Calculating orca.sln changes...
 √ Auto-linking...
Success: No auto-linking changes necessary. (132ms)
**Looking for vswhere at: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe
 ‼ No public VS release found
 i Trying pre-release VS
Looking for vswhere at: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe
 × Could not find MSBuild with VCTools for Visual Studio 16.7 or later. Make sure all required components have been installed**

`vswhere results`:
Visual Studio Locator version 2.7.1+180c706d56 [query version 2.7.3111.17308]
Copyright (C) Microsoft Corporation. All rights reserved.

instanceId: 21e1f90e
installDate: 1/20/2021 10:21:22 AM
installationName: VisualStudio/16.8.4+30907.101
installationPath: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
installationVersion: 16.8.30907.101
productId: Microsoft.VisualStudio.Product.Enterprise
productPath: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\devenv.exe
state: 4294967295
isComplete: 1
isLaunchable: 1
isPrerelease: 0
isRebootRequired: 0
displayName: Visual Studio Enterprise 2019
description: Scalable, end-to-end solution for teams of any size
channelId: VisualStudio.16.Release
channelUri: https://aka.ms/vs/16/release/channel
enginePath: C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service
releaseNotes: https://go.microsoft.com/fwlink/?LinkId=660893#16.8.4
thirdPartyNotices: https://go.microsoft.com/fwlink/?LinkId=660909
updateDate: 2021-01-20T18:21:22.014463Z
catalog_buildBranch: d16.8
catalog_buildVersion: 16.8.30907.101
catalog_id: VisualStudio/16.8.4+30907.101
catalog_localBuild: build-lab
catalog_manifestName: VisualStudio
catalog_manifestType: installer
catalog_productDisplayVersion: 16.8.4
catalog_productLine: Dev16
catalog_productLineVersion: 2019
catalog_productMilestone: RTW
catalog_productMilestoneIsPreRelease: False
catalog_productName: Visual Studio
catalog_productPatchVersion: 4
catalog_productPreReleaseMilestoneSuffix: 1.0
catalog_productSemanticVersion: 16.8.4+30907.101
catalog_requiredEngineVersion: 2.8.3267.30329
properties_campaignId:
properties_channelManifestId: VisualStudio.16.Release/16.8.4+30907.101
properties_nickname:
properties_setupEngineFilePath: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installershell.exe

**Comment by SBS-FPATE-RINALDI** [comment]
Figured out that my Visual Studio did not have the C++ development tools installed causing the issue...recommend to list this as a dependency on the website or mention it in the error output. I personally didn't know that VCtools meant the C++ dev tools.

**Comment by asklar** [comment]
@SBS-FPATE-RINALDI curious where the VCtools mention came from? If you ran the rnw-dependencies script mentioned on the instructions, it should have installed the C++ tools too.
https://microsoft.github.io/react-native-windows/docs/rnw-dependencies

**Comment by SBS-FPATE-RINALDI** [comment]
@asklar Sorry for the late reply. the VCTools mention came from the error produced above. You can see it mentioned in the section I have bolded.

I did run the rnw-dependencies script a couple of times, and it did have a missing dependency found with msbuild and Visual Studio. When I agreed to have it fix these dependencies, it looks like it did something but I would run the script again and it would still say the dependency is missing. It didn't throw any errors but it never seemed to actually install the C++ tools, and I would still get the error above when trying to run my project.
