### ISSUE TITLE
Remove deprecated APIs in 0.65

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#7486]
The content here reflects what is in the code repo master branch. The work to remove these APIs has not been done. I don't believe we have bugs tracking it but we should.

_Originally posted by @asklar in https://github.com/microsoft/react-native-windows-samples/pull/421#discussion_r602517801_

**Comment by NickGerleman** [comment]
Marking this as something we want to fix for 0.65.

That could just mean fixing the documentation for now.

**Comment by NickGerleman** [comment]
@asklar were there places other than the highlighted example in ReactInstanceSettings that were documented to be removed in 0.65?

@vmoroz are these APIs going to be removed shortly?

In the future we should maybe just say "removed in a future release" to give ourselves some more flex.

**Comment by NickGerleman** [comment]
Talked to Vlad offline. We can do this change after cutting the branch, so long as it is before release. Vlad said he will try to remove them before the end of the month.

**Comment by asklar** [comment]
yes I believe the WinRT JSI APIs are in the list of things that we wanted to remove in 0.65, I'm not sure if we have a full list of them

**Comment by NickGerleman** [comment]
Did we document that the WinRT JSI transport is going away in 0.65? It is used internally for the current ABI-safe JSI/C++ TurboModule implementation. That will all presumably be NAPI eventually, but I did not think that would be happening in the very short term.

**Comment by chrisglein** [comment]
Tagging @vmoroz @asklar @NickGerleman. We had wanted to remove these for 0.65, but after cutting the stable branch. That's the window we're in now. Who's taking the next steps on this?

**Comment by NickGerleman** [comment]
Some were removed in https://github.com/microsoft/react-native-windows/commit/f122f5a60209e668e6875f5fa71ec2755b8a9b26

Looks like there are some more left. https://github.com/search?q=65+repo%3Amicrosoft%2Freact-native-windows+extension%3Aidl&type=Code&ref=advsearch&l=&l=

@vmoroz had indicated this is work he wanted to do. I do not think this is properly blocking though, if we delay removal. Would probably just want to update the docs to no longer specify the version of removal.
