### ISSUE TITLE
C# apps/modules cannot use JSI

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#7487]
We currently have 2 JSI APIs:
- WinRT API, usable from C++ and C#. See e.g. [IJsiHostObject](https://microsoft.github.io/react-native-windows/docs/next/IJsiHostObject). However, this API is going away
- facebook::jsi API, and associated Microsoft.ReactNative.Cxx APIs. These are not ABI-safe and are C++ only.

Filing this issue to track the fact that we need a solution for C# too.

**Comment by chrisglein** [comment]
Does this affect when `IJsiHostObject` can go away? Sounds like we have no solution for C# here. @vmoroz did you have any thoughts on how this should be addressed?

**Comment by vmoroz** [comment]
@chrisglein , @asklar , yes, this what I am working on lately: I am implementing C-based NAPI from Node.js for our JS engines and to be used by native modules. These APIs can be  wrapped by .Net code. The goal is to make NAPI to be the ABI-safe APIs and then have C++ NAPI wrappers and JSI to be two choices for C++ developers, and to create .Net wrapper classes for C# developers. Ideally no one should use the NAPI directly in a language with exceptions.
I am also considering to add WinRT API on top of NAPI, but it may come later.

**Comment by jonthysell** [comment]
@vmoroz I think this issue can be closed, yeah?
