### ISSUE TITLE
onKeyDownCapture/onKeyUpCapture events are missing 

### ISSUE THREAD

**Issue by rectified95** [microsoft/react-native-windows#7500]
As specified here - https://github.com/microsoft/react-native-windows/blob/master/vnext/proposals/active/keyboard-reconcile-desktop.md - we should be firing both onKeydown and onKeyDownCapture events (corresponding to KeyDown and PreviewKeyDown XAML events).

Currently, we only fire onKeydown/onKeyUp (the bubbling events), **and we do it in the capture phase** (in the Preview handlers)

**UPDATE**
 This is a non-issue and our spec needs to be adjusted.

**Comment by chrisglein** [comment]
There's some question about whether RN handles this for us through its own event system. May already be handled. Add a test that validates this?

**Comment by rectified95** [comment]
Indeed, React Native has its own event handling system with the bubbling and capturing phases implemented. Therefore, we shouldn't be firing `xxxCapture` events, as our spec now says. We have examples of this usage, although only for the custom Win32 View.

Suggested action items:
- copy the Win32 example and make it into a Windows page to show it works there too
- amend the keyboarding spec to remove incorrect aspirational usage
