### ISSUE TITLE
Press events broken for nested Text 

### ISSUE THREAD

**Issue by rectified95** [microsoft/react-native-windows#7504]
https://github.com/microsoft/react-native-windows/pull/5125 introduced a mechanism to fire press events for nested Text elements. It didn't handle the case where eg. a Hyperlink was a child element of Text, which https://github.com/microsoft/react-native-windows/pull/6692 fixed. In doing so, it broke the original functionality of nested press events, though.

**Comment by rectified95** [comment]
This is happening because #6692 tests if elements are instances of FrameworkElements to prevent erroneous retrieval of Tag eg. from Hyperlink. However, this ends up aborting the entire iteration over TextBlock's set of Inline elements, since they're not FE either.

**Comment by chrisglein** [comment]
@rectified95 I think you have a PR for this. Can you link it?

**Comment by rectified95** [comment]
Closing as fixed.
