### ISSUE TITLE
Developing for HoloLens 2

### ISSUE THREAD

**Issue by sparmar-atheer** [microsoft/react-native-windows#7519]
Can I use Microsoft React Native framework to develop app for HoloLens 2?

**Comment by asklar** [comment]
Our team hasn't done it directly, but it has been done by folks working on VR :) You can reach out on the [Babylon](https://github.com/BabylonJS/BabylonReactNative) repo. @chrisfromwork fyi.

**Comment by chrisfromwork** [comment]
BabylonReactNative is definitely the best place to ask questions related to hololens 2 react-native-windows support.

fwiw, theres still a lot of work to be done around stereo rendering/performance improvements. But with babylon.js/babylonreactnative you can enter into an immersive xr experience on hololens today.
