### ISSUE TITLE
Linux support and current stability

### ISSUE THREAD

**Issue by Stevemoretz** [microsoft/react-native-windows#7527]
Hi I want to know if normal codes in react native like using View and other components are exactly the same here?

So custom libraries will work on this too.

Also now that you've added support for macos, will you add support for Linux later?

**Comment by asklar** [comment]
There is no plan to add support for linux (#4823 covers this too).
Custom libraries that don't depend on native controls (i.e. JS only) would work. Libraries that require the native platform need a Windows-specific implementation. You can find out whether a library has added Windows support here: [Supported community modules](https://microsoft.github.io/react-native-windows/docs/supported-community-modules)
