### ISSUE TITLE
Nodejs support

### ISSUE THREAD

**Issue by Stevemoretz** [microsoft/react-native-windows#7529]
I used electron before and I've used react native before, electron let's you just nodejs functions and everything and react native doesn't.Because well on Android and ios why would you need it anyways.

But since this is macos+windows implementation it would be great to bring life to nodejs environment and use its incredible functions and support.

Is it possible right now?
Or will it ever be possible?

**Comment by chrisglein** [comment]
I don't believe we have anything on the roadmap here. Although I know @vmoroz has mentioned a couple of times (see #4552 and #7487). Vladimir is there anything here we support now or expect to be able to in the future?

@Stevemoretz It would be helpful to know what your scenarios are and what functions you'd expect to use.

**Comment by vmoroz** [comment]
Sorry, I closed it by accident...

**Comment by vmoroz** [comment]
> I don't believe we have anything on the roadmap here. Although I know @vmoroz Vladimir Morozov (REDMOND) FTE has mentioned a couple of times (see #4552 and #7487). Vladimir is there anything here we support now or expect to be able to in the future?
> 
> @Stevemoretz It would be helpful to know what your scenarios are and what functions you'd expect to use.

I am working on implementing the NAPI support for RNW modules. We want to make it the main ABI-safe API used by native modules and TurboModules. It could be possible that the same binary module that uses NAPI can work in Node.js, Electron, and RNW. But, it is not the true Node.js support with all its libraries and modules.

@Stevemoretz , are you looking for an embedded Node.js like Electron does?

**Comment by Stevemoretz** [comment]
Hi thanks for the reply,
Sorry I searched for nodejs in issues and didn't find those.

An embedded nodejs would be pretty nice it provides a lot of nice features which you don't have to make for your own implementation.I have nothing especially in mind, but I just wanted to throw this idea out here.It would be a whole new world of features and possibilities with that added.

Anyways I found this a while ago :
https://github.com/janeasystems/nodejs-mobile-react-native

Maybe not useful because you want to use advanced stuff like Turbo Modules but it's nice to know it's done before kind of.

**Comment by asklar** [comment]
Note that many of the libraries available to nodejs won't work in RNW even when we add napi support, because of restrictions that the UWP appmodel imposes on things like filesystem access, launching processes, etc. 
It sounds like the original question is answered, so closing this issue :)
