### ISSUE TITLE
I can't use Navigation on RNW

### ISSUE THREAD

**Issue by yancarm** [microsoft/react-native-windows#7550]
When I want to use reactnavigation in RNW, I get an error like "folly :: toJson: JSON object value was a NaN or INF" How can I overcome this error or what do I have to do to switch pages. I could not find a project using navigation in any of the sample projects shared on the Internet.

**Comment by asklar** [comment]
can you please clarify what version of RN/RNW are you using, and what part/API of the react-navigation library are you referring to?

**Comment by yancarm** [comment]
**If you are using latest version:**

1. npx react-native --version:  4.14.0
2. npx react-native run-windows --info: 
      System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx
    Memory: 2.12 GB / 5.88 GB
  Binaries:
    Node: 14.13.1 - C:\Program Files\nodejs\node.EXE
    npm: 7.7.5 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 16.13.1 => 16.13.1
    react-native: 0.63.0 => 0.63.0
    react-native-windows: ^0.63.0-0 => 0.63.26
  Installed UWP SDKs:
    10.0.17763.0
    10.0.18362.0
    10.0.19041.0


**Otherwise if --info doesn't exist:**

1. react-native -v: react-native-cli: 2.0.1
                             react-native: 0.63.0
2. npm ls rnpm-plugin-windows: utestunidesktop@0.0.1 C:\Users\yancar\Desktop\UtestUniDesktop
                                                     `-- (empty)
3. npm ls react-native-windows: utestunidesktop@0.0.1 C:\Users\yancar\Desktop\UtestUniDesktop
                                                    +-- native-base@2.15.2
                                                    `-- @react-native-community/datetimepicker@3.4.3
                                                    `-- react-native-windows@0.63.26 deduped
                                                    `-- react-native-windows@0.63.26
4. node -v: v14.13.1
5. npm -v: 7.7.5
6. yarn --version: Not Found


 **npm list --depth=0**

+-- @babel/core@7.13.14
+-- @babel/runtime@7.13.10
+-- @react-native-community/eslint-config@1.1.0
+-- @react-navigation/bottom-tabs@5.11.9
+-- @react-navigation/drawer@5.12.5
+-- @react-navigation/material-bottom-tabs@5.3.15
+-- @react-navigation/material-top-tabs@5.3.15
+-- @react-navigation/native@5.9.4
+-- @react-navigation/stack@5.14.4
+-- babel-jest@25.5.1
+-- eslint-plugin-prettier@3.1.2
+-- eslint@6.8.0
+-- jest@25.5.4
+-- metro-react-native-babel-preset@0.59.0
+-- native-base@2.15.2
+-- prettier@1.19.1
+-- react-native-elements@3.3.2
+-- react-native-gesture-handler@1.10.3
+-- react-native-paper@4.7.2
+-- react-native-screens@3.0.0
+-- react-native-tab-view@2.16.0
+-- react-native-vector-icons@8.1.0
+-- react-native-windows@0.63.26
+-- react-native@0.63.0
+-- react-test-renderer@16.13.1
`-- react@16.13.1

**Comment by yancarm** [comment]
> can you please clarify what version of RN/RNW are you using, and what part/API of the react-navigation library are you referring to?
+-- @react-navigation/native@5.9.4
+-- @react-navigation/stack@5.14.4

**the piece of code that gave the error**


<NavigationContainer>
     <Stack.Navigator>
         <Stack.Screen name="Admin" component={Admin}/>
    </Stack.Navigator>
</NavigationContainer>

**Comment by yancarm** [comment]
With my research, I learned that RNW has not yet received navigation support. It is said that support will come in 2021. Sad :(
Thank you to all who answered and interested.

**Comment by asklar** [comment]
If I remember correctly, we did add support for Windows but there may be gotchas; full discussion is here: #3884
@chrisglein / @stmoy FYI

**Comment by chrisglein** [comment]
> With my research, I learned that RNW has not yet received navigation support. It is said that support will come in 2021. Sad :(
Thank you to all who answered and interested.

react-navigation should support RNW. It was implemented last year, tracked by #3884

**Comment by asklar** [comment]
Duplicate of #7565 
@qmatteoq ran into this too in 7565. This seems like a bug we should fix.

**Comment by asklar** [comment]
Duplicate of #7565
