### ISSUE TITLE
Sticky headers don't work in ScrollView

### ISSUE THREAD

**Issue by rectified95** [microsoft/react-native-windows#7554]
As in the title. Can be observed on pages: `SectionList stickySectionHeadersEnabled` or `ScrollView`

**Comment by chrisglein** [comment]
Claim is that these never worked in Windows. 
Related to #4085.

**Comment by NickGerleman** [comment]
Original sticky header NYI issue is https://github.com/microsoft/react-native-windows/issues/3070

That one has a bit more context, so closing this as dupe.
