### ISSUE TITLE
FlatList.onEndReached partially broken  

### ISSUE THREAD

**Issue by rectified95** [microsoft/react-native-windows#7555]
Scenario:
1. Go to page `FlatList onEndReached`
2. Scroll to the bottom (by hand, or with the 'Test' button on that page.
3. Observe no change in the horizontal, grey bar above the list - it's supposed to contain the string `onEndReached`
4. Maximize the app window - observe the string appear.

My guess is this could be somehow related to another issue, which is that the last list element is only partially visible: https://github.com/microsoft/react-native-windows/issues/7556

**Comment by jonthysell** [comment]
Not sure if this is still a problem?

**Comment by jonthysell** [comment]
This no longer repros.
