### ISSUE TITLE
Audit Accessibility API completion

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#7559]
This project board is out of date: https://github.com/microsoft/react-native-windows/projects/21
We need to know where we stand without waiting for apps to get an accessibility grade. This issue tracks going over the accessibility APIs and making sure we have issues tracking any gaps (and add them to that project board). This issue does not track fixing all those issues.

**Comment by AgneLukoseviciute** [comment]
Project board now up to date: https://github.com/microsoft/react-native-windows/projects/21. Closing.
