### ISSUE TITLE
Consider Reverting to Pinned `nuget.exe` CLI Binary

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#7567]
0.62-0.63 runs NuGet restore via a pined `nuget-exe` binary published by our repo. 0.64 Moved to instead use the MSBuild built-in version of NuGet. This was done for sake of trying to keep compatibility with latest build tools.

A Visual Studio update recently broke NuGet restore for all 0.64 CLI users. This shows a new risk we adopted, of NuGet MSBuild breaking changes.

We should monitor the situation, and consider moving back to pinned exes if latest MSBuild restore is too unstable.

**Comment by NickGerleman** [comment]
FYI @dannyvv @asklar who have some stake in this.

I think it might be possible to revert the original commit moving us this direction, then resolve a couple conflicts.

**Comment by NickGerleman** [comment]
Wanting to bring this to 0.64, since there's been wide reports of failure to build.

**Comment by asklar** [comment]
I think it's still not 100% clear, but the current theory is that the issue wasn't with the nuget client, but with a config change on the agents where they pushed a nuget.config that did not have nuget.org

**Comment by NickGerleman** [comment]
I think all of the issues I saw referenced 0.64, which is when we made the switch. Would be worth double checking though. If 0.63 and lower are unaffected, the NuGet change is a major difference between branches.

**Comment by NickGerleman** [comment]
This issue was some reports of 0.64 NuGet specific CLI failure. Some of the bits in this issue seem to suggest failure to sign appx's though. https://github.com/microsoft/react-native-windows/issues/7436

**Comment by NickGerleman** [comment]
PR pipeline for 0.63 seem to be passing as of four days ago, but I didn't look back to check whether there were prior failures.

**Comment by chrisglein** [comment]
This is still pretty fresh and we're trying to figure out how widespread it is (see linked issue). This may be an option if it seems like getting nuget from VS is too much of an additional variable. As is this is a maybe.

**Comment by NickGerleman** [comment]
Closing since the NuGet issue should be solved.
