### ISSUE TITLE
Text highlight does not get updated as text changes

### ISSUE THREAD

**Issue by rozele** [microsoft/react-native-windows#7569]
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Clone RNTester example: https://github.com/rozele/react-native-windows/tree/pressableTextRepro
2. Open Text component example
3. Scroll to "Pressable edge cases" example
4. On the line that says "Disabling pressables is okay too.", click "Click to disable".
5. Observe that the text highlighting is *not* removed for the "Click here." text and the highlighting is not updated for the "Click to enable." text.

## Expected Results
Text highlighting updates with changes to nested text.

## Snack, code example, screenshot, or link to a repository:
RNTester example: https://github.com/rozele/react-native-windows/tree/pressableTextRepro

https://user-images.githubusercontent.com/1106239/114274278-a3d5e380-99eb-11eb-8981-ca435c2f962a.mp4

**Comment by rozele** [comment]
FYI @koljaka - I believe you have a fix for this.

**Comment by rectified95** [comment]
@rozele @koljaka Let me know if you have a fix already, so I can assign the issue to you. If you don't, I'll fix it.

**Comment by koljaka** [comment]
@rectified95 It appears that my fix does not work in all cases, so it'd be better if you fix it. Thanks!
