### ISSUE TITLE
PlatformColors are cached and not recalculated on theme changes

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#7578]
The Color/Brush conversion helpers keep a cache (map of names to Brushes) that are used by the code implementing PlatformColor.
When the app/system theme changes, these caches are not updated or cleared, so apps will not re-draw with the right colors under these conditions.

**Comment by chrisglein** [comment]
If this is hooked up to a Brush it probably works because the Brush will self change, but not if you use a Color. Will need to listen for theme changes and invalidate.

**Comment by asklar** [comment]
Verified that using a brush name and changing the system theme does _not_ cause the app to use the new color, so this is a bug that should be fixed.

**Comment by rectified95** [comment]
@asklar Should this be closed since #7640 got merged?
