### ISSUE TITLE
Init 0.64 Project not building when adding react-native-fs native module

### ISSUE THREAD

**Issue by creambyemute** [microsoft/react-native-windows#7585]
I wanted to upgrade our Project to 0.64  and failed.
I then tried it with a fresh 0.64 init project and it miserably failed as well.

## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`: 5.0.1-alpha.2
2. `npx react-native info`: 
```
System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 24.86 GB / 31.95 GB
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 29.0.0, 29.0.1, 29.0.2, 29.0.3, 30.0.0, 30.0.1, 30.0.2, 30.0.3
      System Images: android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7042882
    Visual Studio: 16.9.31025.194 (Visual Studio Community 2019)
  Languages:
    Java: 1.8.0_282 - C:\Program Files\OpenJDK\openjdk-8u282-b08\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.0 => 0.64.0
    react-native-windows: ^0.64.0-0 => 0.64.3
  npmGlobalPackages:
    *react-native*: Not Found
```

What SDK version are you building for? Choose from 10.0.15063, 10.0.16299, 10.0.18362, etc.
- Target Platform Version(s): Latest
What device(s) are you targeting? Choose any from Desktop, Xbox, Hololens)
- Target Device(s):  Desktop
Which version of Visual Studio are you using? Specify Visual Studio 2017 or Visual Studio 2019
- Visual Studio Version: 2019
Which build configuration are you running? Choose from Debug, DebugBundle, Release, ReleaseBundle 
- Build Configuration: Release

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. `npx react-native init RN064Init --template react-native-template-typescript`
2. `npx react-native-windows-init --overwrite`
3. `yarn add <someNativePackage>` (I added `"react-native-fs": "https://github.com/wwimmo/react-native-fs.git"`, to package.json) and ran yarn

## Expected Results
Autolinking to happen, Build to happen

## Actual Results
Build in VS2019 Aborts with: 
`Error: Error: Auto-Linking changes were necessary but --check was specified`
`Error: Auto-Linking changes were necessary but --check was specified`
`The command npx react-native autolink-windows --check --sln <pathToSln> exited with code 1`

## Troubleshooting
  If you see build failure on `react-native run-windows`, please try again with 'react-native run-windows --logging' and provide the output.

Relevant Output (sorry for the german output...):
```
 8>C:\Users\thoma\dev\react\RN064Init\node_modules\react-native-windows\Microsoft.ReactNative.Cxx\JSI\JsiApiContext.cpp(9,40): error C4430: Fehlender Typspezifizierer - int wird angenommen. Hinweis: "default-int" wird von C++ nicht unterstützt. [C:\Users\thoma\dev\react\RN064Init\node_modules\react-native-fs\windows\RNFS\RNFS.vcxproj]
     8>C:\Users\thoma\dev\react\RN064Init\node_modules\react-native-windows\Microsoft.ReactNative.Cxx\JSI\JsiApiContext.cpp(9,29): error C2146: Syntaxfehler: Fehlendes ";" vor Bezeichner "__ImageBase" [C:\Users\thoma\dev\react\RN064Init\node_modules\react-native-fs\windows\RNFS\RNFS.vcxproj]
     8>C:\Users\thoma\dev\react\RN064Init\node_modules\react-native-windows\Microsoft.ReactNative.Cxx\JSI\JsiApiContext.cpp(34,5): error C2065: "HMODULE": nichtdeklarierter Bezeichner [C:\Users\thoma\dev\react\RN064Init\node_modules\react-native-fs\windows\RNFS\RNFS.vcxproj]
     8>C:\Users\thoma\dev\react\RN064Init\node_modules\react-native-windows\Microsoft.ReactNative.Cxx\JSI\JsiApiContext.cpp(34,13): error C2146: Syntaxfehler: Fehlendes ";" vor Bezeichner "currentDllHanlde" [C:\Users\thoma\dev\react\RN064Init\node_modules\react-native-fs\windows\RNFS\RNFS.vcxproj]
     8>C:\Users\thoma\dev\react\RN064Init\node_modules\react-native-windows\Microsoft.ReactNative.Cxx\JSI\JsiApiContext.cpp(34,13): error C2065: "currentDllHanlde": nichtdeklarierter Bezeichner [C:\Users\thoma\dev\react\RN064Init\node_modules\react-native-fs\windows\RNFS\RNFS.vcxproj]
     8>C:\Users\thoma\dev\react\RN064Init\node_modules\react-native-windows\Microsoft.ReactNative.Cxx\JSI\JsiApiContext.cpp(34,49): error C2061: Syntaxfehler: Bezeichner "HMODULE" [C:\Users\thoma\dev\react\RN064Init\node_modules\react-native-fs\windows\RNFS\RNFS.vcxproj]
     8>C:\Users\thoma\dev\react\RN064Init\node_modules\react-native-windows\Microsoft.ReactNative.Cxx\JSI\JsiApiContext.cpp(35,101): error C2065: "currentDllHanlde": nichtdeklarierter Bezeichner [C:\Users\thoma\dev\react\RN064Init\node_modules\react-native-fs\windows\RNFS\RNFS.vcxproj]
     8>C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets(482,5): error MSB4181: Die Aufgabe "CompileXaml" hat FALSE zurückgegeben, jedoch keinen Fehler protokolliert. [C:\Users\thoma\dev\react\RN064Init\node_modules\react-native-fs\windows\RNFS\RNFS.vcxproj]
     8>Die Erstellung des Projekts "C:\Users\thoma\dev\react\RN064Init\node_modules\react-native-fs\windows\RNFS\RNFS.vcxproj" ist abgeschlossen (Standardziele) -- FEHLER.
     7>Die Erstellung des Projekts "C:\Users\thoma\dev\react\RN064Init\windows\rn064init\rn064init.vcxproj" ist abgeschlossen (Standardziele) -- FEHLER.
     9>Die Erstellung des Projekts "C:\Users\thoma\dev\react\RN064Init\windows\rn064init\rn064init.vcxproj.metaproj" ist abgeschlossen (Standardziele) -- FEHLER.
     1>Die Erstellung des Projekts "C:\Users\thoma\dev\react\RN064Init\windows\rn064init.sln" ist abgeschlossen (Standardziele) -- FEHLER.

```

**Comment by asklar** [comment]
After adding a module, you must run either a CLI build, or an autolinking pass (when building in VS, autolinking does not run). You can run autolinking by running `npx react-native autolink-windows`
The build error seems unrelated though, it's as if it isn't finding Windows headers (IMAGE_DOS_HEADER for example). Just to confirm, do you have all the dependencies installed? you can check here: https://aka.ms/rnw-deps

**Comment by creambyemute** [comment]
I do have all the dependencies installed, running either a fresh 0.64/0.63 init or our not upgraded Project@0.63 works.
I posted the `CLI Build` output above, shouldn't that have run linking?

I tested some more native modules now (`DateTimePicker` which requires manual linking, `react-native-sketch-canvas` and `react-native-device-info` which autolinked) and those seem to work, build and run.

As soon as I add&link `react-native-fs` the build breaks again with the above `npx react-native run-windows --logging` output.
iOS and Android do not seem to have a problem with it on 0.64 though.

I guess the windows implementation/setup/structure of react-native-fs has to be adapted?

**Comment by chrisglein** [comment]
May be a new incompatibility between `react-native-fs` and 0.64. I don't believe we've had that one positive confirmed yet. We still have an issue open on supporting it in the first place actually: #2829. Long thread there I haven't had a chance to absorb. What version are you pulling in? (there were active PRs that haven't been merged)

**Comment by creambyemute** [comment]
I'm using a fork which includes avmoroz Windows 10 Support PR: `https://github.com/wwimmo/react-native-fs` and tested it quite a bit in 0.63 in our Project.

**Comment by asklar** [comment]
@creambyemute I've looked into this; the RNFS project is missing a `#include <windows.h>` in its pch.h

**Comment by creambyemute** [comment]
I temporarily added that to check if the 0.64 upgrade worked out and that worked and I was able to start and test the 0.64 upgraded App.

I think we can close this one here and continue it in its appropriate place. @asklar
