### ISSUE TITLE
DisplayNone test is testing the wrong ui element

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#7586]
> > > Question: from this snapshot and inspecting component properties from VS, it seems like the visibility remains as "visibile," despite the behavior changing as if it was collapsing(and from setting breakpoints in FrameworkElementViewManager I can see that the right code is getting hit and the Visibility value gets set to "Collapsed" - but I never see this in XAML) - any idea what's going on?
> > 
> > 
> > if the tree dump says it's not collapsed then it's probably not collapsed : ) (and something else may be re-setting the property?)
> > Do you see the collapsed element in the UI? What does the Live Visual Tree and Property panes say?
> 
> The "collapsed" element is no longer seen in the UI, but the Live Visual Tree and accompanying properties do not seem to change when display:none is toggled. If I undo the code change I added, same thing happens - component goes out of view when display is set to none, but you are still able to tab into those components - when I add the change back in, I'm no longer able to tab into components which are set to display:none, but according to the properties the visibility is still "visible"...

Final comment before merging: Confirmed the elements are getting collapsed through Live Visual Tree and Property panes however the snapshot tests do not reflect this. Might require filing an issue - and if/when this gets fixed this test will fail and will just need updated snapshots to go through. 

Additionally, I had to hard code the width for the view containing 2 Text and 2 Switch components as there was a weird width mismatch from running locally vs in the CI checks. To confirm the display:none property change was not the cause, I made sure update property for display was not getting hit when the prop was not used and commit a2ea3df confirmed the view width issue persists even when display:none is not used.

_Originally posted by @AgneLukoseviciute in https://github.com/microsoft/react-native-windows/issues/7363#issuecomment-819685337_

**Comment by NickGerleman** [comment]
The snapshots use the JSON dump from xaml tree dump library code, so likely a bug there.

**Comment by NickGerleman** [comment]
We should really consider bringing the code to this repo instead of a personal one, so it can get code reviewed and people working on the infrastructure can make fixes.

**Comment by chrisglein** [comment]
> We should really consider bringing the code to this repo instead of a personal one, so it can get code reviewed and people working on the infrastructure can make fixes.

This is being used by more than RN. Sounds like there's more discussion needed to figure out what changes are viable there.

**Comment by asklar** [comment]
This is *not* a bug in the tree dump library (in fact there are tests in the TDL for exactly this scenario). 
This is a bug in the test. The tree dump is happening on the wrong element (the test ID should be set on the parent of the view it is set on in the test).

I've asked @AgneLukoseviciute to fix the test.
