### ISSUE TITLE
Visual tests: Width value for some elements differs in CI vs. locally

### ISSUE THREAD

**Issue by AgneLukoseviciute** [microsoft/react-native-windows#7589]
This issue emerged from PR #7363 & explained in [final comment.](https://github.com/microsoft/react-native-windows/pull/7363#issuecomment-819685337):

>>>>Question: from this snapshot and inspecting component properties from VS, it seems like the visibility remains as "visibile," despite the behavior changing as if it was collapsing(and from setting breakpoints in FrameworkElementViewManager I can see that the right code is getting hit and the Visibility value gets set to "Collapsed" - but I never see this in XAML) - any idea what's going on?
>>>
>>>
>>>if the tree dump says it's not collapsed then it's probably not collapsed : ) (and something else may be re-setting the property?)
>>>Do you see the collapsed element in the UI? What does the Live Visual Tree and Property panes say?
>>
>>
>>The "collapsed" element is no longer seen in the UI, but the Live Visual Tree and accompanying properties do not seem to change when display:none is toggled. If I undo the code change I added, same thing happens - component goes out of view when display is set to none, but you are still able to tab into those components - when I add the change back in, I'm no longer able to tab into components which are set to display:none, but according to the properties the visibility is still "visible"...
>
>
>Final comment before merging: Confirmed the elements are getting collapsed through Live Visual Tree and Property panes however the snapshot tests do not reflect this. Might require filing an issue - and if/when this gets fixed this test will fail and will just need updated snapshots to go through.
>
>Additionally, I had to hard code the width for the view containing 2 Text and 2 Switch components as there was a weird width mismatch from running locally vs in the CI checks. To confirm the display:none property change was not the cause, I made sure update property for display was not getting hit when the prop was not used and commit a2ea3df confirmed the view width issue persists even when display:none is not used.

The issue only appears for the Text components and the View containing them - the width value for all 3 is narrower in CI (718) snapshots than in local build (1074). 
![image](https://user-images.githubusercontent.com/41223743/114767589-6e076680-9d2d-11eb-84a0-65a8d7a44fd7.png)

**Comment by NickGerleman** [comment]
Likely fixed by #7130. The rootview has a fixed height within the window, but not a fixed with, so window resize can affect test results.

**Comment by NickGerleman** [comment]
@AgneLukoseviciute would you be able to locally test this against latest master? That should let us know if the issue was related to the non-fixed rootview width vs a separate issue.

**Comment by NickGerleman** [comment]
I missed that we already are resizing to 800x600 on every app launch
https://github.com/microsoft/react-native-windows/blob/6d9a804a6782b40dfeee5de0bfc1bfe91ab962dd/packages/e2e-test-app/windows/ReactUWPTestApp/App.xaml.cs#L77

So I think the width difference may be due to a more legitimate rendering issue instead of mismatched width.

**Comment by AgneLukoseviciute** [comment]
> @AgneLukoseviciute would you be able to locally test this against latest master? That should let us know if the issue was related to the non-fixed rootview width vs a separate issue.

@NickGerleman Looks like it was related, #7683 did the trick. Local snapshot width got updated to match what CI was getting, thanks!
