### ISSUE TITLE
Remove fork of MapBufferBuilder.cpp

### ISSUE THREAD

**Issue by rectified95** [microsoft/react-native-windows#7591]
Build break coming from Core. PR to fix this: https://github.com/facebook/react-native/pull/31363

**Comment by chrisglein** [comment]
Is there a way we can get coverage for different warning levels on the nightly builds to catch this more in advance?

**Comment by rectified95** [comment]
This should have been removed in #7680 
Can be deleted any time now. Will most likely in the next ingestion from core.
