### ISSUE TITLE
Defork Yoga.cpp

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#7600]
There seem to be multiple functional changes between RN core's Yoga.cpp and our fork

**Comment by NickGerleman** [comment]
Duplicate of #3994

**Comment by NickGerleman** [comment]
There is a PR to Yoga which had the fixes from early last year, but the FB team owning it doesn't seem to be accepting contributions to the OSS version.

https://github.com/facebook/yoga/pull/995

**Comment by NickGerleman** [comment]
@rozele if the above PR something you might be able to submit FB-side?

**Comment by NickGerleman** [comment]
BTW @asklar you can see a diff of our patches if you run `npx react-native-platform-override diff path/to/Yoga.cpp`

**Comment by rozele** [comment]
@NickGerleman I just submitted a request to get this PR imported on Yoga.
