### ISSUE TITLE
Failed to pass tests before publish to windows store

### ISSUE THREAD

**Issue by dingbo8128** [microsoft/react-native-windows#7606]
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`: 5.0.1-alpha.2
2. `npx react-native info`:
```
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 7.42 GB / 15.84 GB
  Binaries:
    Node: 14.15.3 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.9 - D:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.8.30804.86 (Visual Studio Community 2019)
  Languages:
    Java: 15.0.1 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.0 => 0.64.0
    react-native-windows: ^0.64.0-0 => 0.64.3
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.  项目 - 发布 - 创建应用程序包 - 运行Windows App Certification Kit

## Expected Results
pass all tesets

## Snack, code example, screenshot, or link to a repository:

```
Windows 应用认证工具包 - 测试结果
应用名称:
锡安课程
应用发行者:
巴拿巴
应用版本:
0.1.0.0
应用体系结构:
x64
工具包版本:
10.0.18362.1
操作系统版本:
Microsoft Windows 10 家庭中文版 (10.0.19042.0)
OS 体系结构:
x64
报告时间:
2021/4/17 19:11:11

总体结果: 失败


支持的 API 测试

失败
支持的 API
发现错误: 支持的 API 测试检测到以下错误:
此应用程序类型不支持 vcruntime140_1_app.dll 中的 API __CxxFrameHandler4。zionappx.exe 调用此 API。
此应用程序类型不支持 vcruntime140_1_app.dll 中的 API __CxxFrameHandler4。ReactNativeVideoCPP.dll 调用此 API。
此应用程序类型不支持 api-ms-win-appmodel-runtime-l1-1-2.dll 中的 API AppPolicyGetWindowingModel。Microsoft.ReactNative.dll 调用此 API。
此应用程序类型不支持 vcruntime140_1_app.dll 中的 API __CxxFrameHandler4。Microsoft.ReactNative.dll 调用此 API。
未修复时会产生影响: 如果使用的 API 不属于 Microsoft Store 应用的 Windows SDK，则违反 Microsoft Store 认证要求。
如何修复: 查看错误消息以确定不属于适用于 Microsoft Store 应用的 Windows SDK 的 API。请注意，在调试配置中生成的应用或未根据需要启用 .NET Native 的应用可能无法通过此测试，因为这些环境可能拉入不支持的 API。请使用发布配置重新测试你的应用，并根据需要启用 .NET Native。 有关详细信息，请参阅下面的链接:
Microsoft Store 应用中的 Windows API 的替代选择。



应用清单资源测试

通过
应用资源

失败
品牌
发现错误: 品牌验证测试遇到以下错误:
映像文件 StoreLogo.png 是默认映像。
未修复时会产生影响: Microsoft Store 应用应该完整且功能齐全。如果应用使用默认图像，例如来自模板或 SDK 示例中的图像，则提供的用户体验较差，无法在 Microsoft Store 目录中轻松识别。
如何修复: 请使用更加鲜明且更具代表性的应用映像替换默认映像。



```

**Comment by chiaramooney** [comment]
Checkout #5737. Make sure that your copy of WACK is up to date.

**Comment by dingbo8128** [comment]
what's WACK ? 

> Checkout #5737. Make sure that your copy of WACK is up to date.

What's WACK ?

**Comment by dingbo8128** [comment]
Yes , I use newly installed WACK

**Comment by chrisglein** [comment]
Looks similar to #4475. Are you using a different JavaScript engine? (V8 or Hermes)

**Comment by dingbo8128** [comment]
> Looks similar to #4475. Are you using a different JavaScript engine? (V8 or Hermes)
I don't know how to not use V8, I have not change any default config.

**Comment by NickGerleman** [comment]
The end-user version of WACK often has out of date exemptions for allowed store APIs. So new code will be accepted, but WACK gives the wrong result.

This is a windows store dev experience issue in general.

**Comment by NickGerleman** [comment]
In the above example, one of the warnings flagged is for CxxFrameHandler4. This has usage starting with latest MSVC late last year. Seems like a false positive.

**Comment by NickGerleman** [comment]
@dingbo8128 It looks like you're running VS 16.8. Could you run "Visual Studio Installer" to update to latest?

You can also try to submit to the store despite the warnings, and it should be accepted.

**Comment by dingbo8128** [comment]
Thanks, i will try.
