### ISSUE TITLE
Support for EWDK

### ISSUE THREAD

**Issue by oldoldman** [microsoft/react-native-windows#7607]
I'm following this [doc](https://microsoft.github.io/react-native-windows/docs/getting-started) to go through the steps of running react-native-windows app. When running ```npx react-native run-windows``` in an EWDK build command window, I got stuck with following error
```
Looking for vswhere at: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe
 ‼ No public VS release found
 i Trying pre-release VS
Looking for vswhere at: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe
 × Unable to find vswhere at C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe
```
Is there some workaround of this ? Many thanks.

**Comment by asklar** [comment]
@oldoldman can you confirm whether you've installed the dependencies? the instructions can be found here: http://aka.ms/rnw-deps
You'll likely need to close the cmd/ps window after installing the dependencies and reopen a new one.

**Comment by oldoldman** [comment]
I've found a workaround , but it is not easy. I would like to suspend this issue. Thank you guys.

**Comment by josiext** [comment]
How did u solve it ?

**Comment by oldoldman** [comment]
Hack the build script which will detect the cl command line and call it later to compile the cpp files. The build system is complicated,so it is not a easy task.
