### ISSUE TITLE
Add Windows Support to RuntimeScheduler Module

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-windows#7610]
# Proposal: Add Windows Support to RuntimeScheduler Module
New module added by facebook in https://github.com/facebook/react-native/commit/eb13baf2a687b53dde04b9a336f18629d94f4b79. More commits have been made since to add additional functionality to the module.

**Comment by NickGerleman** [comment]
I don't think there is any work needed on our end for this.

**Comment by chrisglein** [comment]
Sounds like this may just work without action on RNW. Or likely it only affects Fabric, and the support there is already incomplete so we're not ready to track with individual items.
