### ISSUE TITLE
Rename "src" in RN Platforms to "patches"

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#7616]
The "src" directory contains a number of JS files that are added to the base copy of RN. It is not a complete source tree itself. Renaming to "patches" would increase clarity of intent, and follow OSS "patch-package" conventions.

**Comment by himanshu007-creator** [comment]
I would like to work on this issue. Please assign me this issue.

**Comment by Yash621** [comment]
@NickGerleman can I work on this ?

**Comment by chiaramooney** [comment]
No longer relevant. Dir now called src-win
