### ISSUE TITLE
Remove leakChecker.cpp fork once upstream PR complete 

### ISSUE THREAD

**Issue by acoates-ms** [microsoft/react-native-windows#7619]
Remove fork of ReactCommon\react\renderer\leakchecker\LeakChecker.cpp once https://github.com/facebook/react-native/pull/31399 is merged.

**Comment by chrisglein** [comment]
FYI @AgneLukoseviciute about the linked PR having some fixes for warning levels. Might be related to what you're looking into.

**Comment by acoates-ms** [comment]
Closing as we no longer need this fork now that we have fmt.  (#7635)
