### ISSUE TITLE
rnw-dependencies script missing VS component?

### ISSUE THREAD

**Issue by burtonrodman** [microsoft/react-native-windows#7644]
I am trying to create a custom Docker container to build my project in lieu of Azure DevOps hosted because the PCH files of my project and the included community modules are exceeding the 10GB limit of the hosted agents.  I have tried to pair down the PCH's but it's just not enough.  When I build my container I am using the following commands:

Dockerfile for base image with .net 4.8 and choco (to avoid reboot issues and choco rate limiting):
```
FROM mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-ltsc2019

SHELL [ "powershell", "-command"]

RUN [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; \
    iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'));
```

Dockerfile for build image copying WinRT vsix also because of download issue (maybe rate limiting):
```
FROM burtonrodman/windows-choco:latest

COPY Microsoft.Windows.CppWinRT.vsix /Users/ContainerAdministrator/AppData/Local/Temp/Microsoft.Windows.CppWinRT.vsix

COPY rnwscript.ps1 .
RUN .\rnwscript.ps1 -Install -NoPrompt -Enterprise -Tags @('buildLab')
```

After building the container, I clone my code, run yarn install (which has its own set of issues, but that's for another day), and then run msbuild and get this error:
```
msbuild /p:Configuration="Debug" /p:Platform="x86"
```

```
Folly.vcxproj(229,3): error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enter 
prise\MSBuild\Microsoft\VC\v160\Microsoft.Cpp.Default.props" was not found. Confirm that the expression in the Import declaration "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v1 
60\\Microsoft.Cpp.Default.props" is correct, and that the file exists on disk.
```

So it would seem that some component of VS/C++ is missing, but I can't seem to identify which.

For reference the above msbuild command works on my dev machine.

Any help would be appreciated.

**Comment by asklar** [comment]
We expect the `buildLab` profile to be used on AzDO/GitHub actions where some of the required VS workloads are already present. Can you try removing that?

**Comment by burtonrodman** [comment]
thanks for your response.  it seems I was hitting the 10GB default volume limit when installing VS, and it failed silently (or at least in a non-obvious way).  I have kicked my default volume size up and rebuilding now -- which seems to be going well.  still need to test, but i'll post back here asap.

**Comment by burtonrodman** [comment]
i'm closing this for now as it seems our builds started passing -- so maybe I was barking up the wrong track.  for anyone else who may be trying this, I added the following to my Docker Engine settings, deleted all containers and images and repulled all my images and it started giving me 40GB to work with while building.

```
  "storage-opts": [
    "size=40G"
  ]
```
