### ISSUE TITLE
Couldn't find any versions for "get-monorepo-packages" that matches "^1.2.0"

### ISSUE THREAD

**Issue by bokuns** [microsoft/react-native-windows#7649]
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`: 5.0.1-alpha.2
2. `npx react-native info`:
```
System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 AMD Ryzen 7 PRO 4750U with Radeon Graphics
    Memory: 21.12 GB / 29.73 GB
  Binaries:
    Node: 14.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 7.10.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 29, 30
      Build Tools: 29.0.2, 30.0.3
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7199119
    Visual Studio: 16.9.31205.134 (Visual Studio Community 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.0 => 0.64.0
    react-native-windows: ^0.64.0-0 => 0.64.4
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.
```
https://microsoft.github.io/react-native-windows/docs/getting-started
```
When running ```npx react-native-windows-init --overwrite```, it would show the error: 
```
Installing react-native-windows@^0.64.0-0...
warning Lockfile has incorrect entry for "get-monorepo-packages@^1.2.0". Ignoring it.
error Couldn't find any versions for "get-monorepo-packages" that matches "^1.2.0"
Command failed: yarn
...
```

## Expected Results
Describe what you expected to happen.
```npx react-native-windows-init --overwrite``` would be finished without errors.

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by NickGerleman** [comment]
The package seems to still be available on the npmjs registry https://www.npmjs.com/package/get-monorepo-packages/v/1.2.0. yarnpkg should mirror that.

It seems like this could be caused by intermitancy with either yarnpkg, or a separately configured npm mirror.

Would you be able to try again?

**Comment by bokuns** [comment]
Yes, it works after I switched the npm registry back to the original one. Before I was using taobao mirror, which is said to sync with the original one every 10 mins and this package was published...2yrs ago.
