### ISSUE TITLE
Where do I configure source bundle host/port, and open dev menu on Xbox?

### ISSUE THREAD

**Issue by marnusw** [microsoft/react-native-windows#7650]
When debugging on a remote device the app looks for the JS bundle at `localhost:8081` by default which doesn't exist.

It looks like #4582 raised this issue and that it was addressed #4979, but I couldn't find any documentation nor figure out where these developer settings can be configured. 

A related question is how to open the developer menu while debugging on an Xbox One?

If it would help I could contribute to the documentation on this topic once I understand it.

**Comment by NickGerleman** [comment]
You should be able to set `SourceBundleHost` on ReactInstanceSettings. https://microsoft.github.io/react-native-windows/docs/ReactInstanceSettings api

You should be able to assign th this in different places. InstanceSettings is part of ReactApplication, which is a XAML component that App.cpp implements.
 
You can also get the global application ReactNativeHost (think instance with attached views) from anywhere on the UI thread to assign settings. E.g. in MainPage.cpp  
 
The instance is IIRC started after the first root view is attached, so you will want to set any settings before the root view is attached.

**Comment by asklar** [comment]
You can connect a keyboard to the xbox and press Ctrl+Shift+D to bring up the Debug menu.
Let us know if you are still blocked!

**Comment by marnusw** [comment]
Thank you both for your quick responses. I was able to specify the host in App.cpp where the InstanceSettings are configured which works well.

It looks like the developer menu doesn't provide the option to change the bundle location like it does for iOS and Android, which means using ReactInstanceSettings is the only way to debug remotely right?

Could I send a PR with a few lines on this added to the Getting Started guide? This was the missing link for me to get going without reading through all the docs in its entirety (and I'm not sure I'd have found where to change this in any case not being a native UWP developer). It's pretty straight forward in hindsight though.

**Comment by asklar** [comment]
we are planning to add a "debugging your app" page to the docs which should contain this and other related information. Some examples of info we want here: 
- how to do direct debugging vs. web debugging
- attaching Visual Studio in "script mode"
- figuring out whether Flipper works for RNW apps or not
- debugging crash dumps
- using the debug menu and debug APIs

See microsoft/react-native-windows-samples#426
if you wanted to send a pr for a new page with [any portion of] that info that'd be great!

**Comment by acoates-ms** [comment]
The debug menu should allow you to change the bundle location like it does for iOS and Android.  The last item in the menu should be "Configure Bundler" which would allow you to specify the host / port for the bundle.

**Comment by marnusw** [comment]
Thanks @acoates-ms, I see the dev menu option is in v0.64. We've been using 0.63 since we're on `react-native-tvos` which hasn't realeased a port of RN 0.64 yet.

Thanks for outlining your plans for the docs @asklar. Most of those topics seem too specialised for my immediate knowledge and it seems v0.64 has already solved the root of the issue I had by adding the Configure Bundler option. As we make progress with our project I'll look at contributing documentation when I can in a meaningful way.

For now I'll close this. Thanks for all the help.
