### ISSUE TITLE
Experiment with pre-seeding virtualizedlist cell measurement cache when idle

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#7651]
Virtualizedlist keeps a full cache of measurements of all rendered items. This cache allows more accurate behaviors once the item is rendered.

Pre-seeding the cache would lead to correct behavior on the first (or early) interaction.

It comes at the cost of cpu/battery. Would need to throttle. Memory cost is not bad (100kb per thousand items)

**Comment by asklar** [comment]
@NickGerleman Is this something in Core rather than in Windows?

**Comment by NickGerleman** [comment]
This is in Core, but affects Windows. I thought about putting this in the core repo, but think it makes more sense here. Task-style work tracking for core is usually FB internal, so the OSS repo for react-native core is more related to user-issues. The RNW repo I think also has visibility to the folks who would be implementing this.

**Comment by asklar** [comment]
It might be worth to experiment with this, may not be the right default behavior.

**Comment by NickGerleman** [comment]
We can do this efficiently with #5800

**Comment by NickGerleman** [comment]
> Supporting the `collapsable` property might allow us to do efficient pre-measurement in VirtualizedList.
>
> Collapsable views have a shadownode and a yoga node, but do not need an associated native component. This allows us to efficiently keep a subset of components in a measure but no native render state.
>
> This will not work for self-measure components. I.e. we get efficient pre-measure for flexbox. No efficient pre-measure for Text (until maybe Fabric).

**Comment by NickGerleman** [comment]
JS would still render in this case. Which means we would do any async JS work per-item. Native side rendering costs are avoided though.
