### ISSUE TITLE
How can i update to V8 engine . Do we need to download any library or simply setting is enough instanceSettings.JSIEngineOverride = JSIEngine.V8;

### ISSUE THREAD

**Issue by sureshsvmx** [microsoft/react-native-windows#7660]

**Comment by NickGerleman** [comment]
V8 isn't something we fully support quite yet. E.g. we do not run tests with it, or ensure V8 builds are allowed in the app store. We should do a better job of making this clear in code (logged an issue on this).

In the meantime, we support Chakra by default, along with Hermes, which usually has better performance characteristics (with some limitations). Take a look here for how to enable that. https://microsoft.github.io/react-native-windows/docs/hermes

**Comment by sureshsvmx** [comment]
Thank @NickGerleman.
