### ISSUE TITLE
backgroundColor makes color stop working

### ISSUE THREAD

**Issue by ryfow** [microsoft/react-native-windows#7690]
If you create a text element like the following, it renders with black text on a black background instead of white text on a black background.:

`<Text style={{color: 'white', backgroundColor: 'black'}}>Hello!</Text>`

Additionally, there's some weirdness with reloading. Changing the backgroundColor requires an app restart for some reason.

## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`:
```
npx react-native --version
5.0.1-alpha.2
```
2. `npx react-native info`:
```
> npx react-native info
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19041
    CPU: (10) x64 Intel(R) Xeon(R) Gold 6226 CPU @ 2.70GHz
    Memory: 5.26 GB / 12.00 GB
  Binaries:
    Node: 14.8.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.7 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.15063.0, 10.0.16299.0, 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.9.31205.134 (Visual Studio Professional 2019)
  Languages:
    Java: 11.0.8 - C:\Program Files\Zulu\zulu-11\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.0 => 0.64.0
    react-native-windows: ^0.64.0-0 => 0.64.5
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. add `<Text style={{color: 'white', backgroundColor: 'black'}}>Hello!</Text>` to a rnw app
2. Notice that the text is not white

## Expected Results
style.color should work, even when backgroundColor is specified.

**Comment by rozele** [comment]
I believe @koljaka has run into this issue as well. I think the resolution was to set the foreground color on the TextHighlighter that's used for background color.

**Comment by asklar** [comment]
Assigning to Igor to take a look

**Comment by rozele** [comment]
The fix @koljaka had was to set Foreground here in addition to Background: https://github.com/microsoft/react-native-windows/blob/master/vnext/Microsoft.ReactNative/Views/TextViewManager.cpp#L108

**Comment by rectified95** [comment]
@ryfow Thanks for spotting this!
The fix is now in the master branch. I'll try to get it backported to 0.64 too.
