### ISSUE TITLE
Manually register folly and format to component goverenance

### ISSUE THREAD

**Issue by dannyvv** [microsoft/react-native-windows#7704]
We need to either:
* Update the msbuild logic that downloads folly and fmt to emit a [manifest file ](https://docs.opensource.microsoft.com/tools/cg/cgmanifest.html)that component governance would pick up...
* Add a manual registration in the [manifest file ](https://docs.opensource.microsoft.com/tools/cg/cgmanifest.html) for component governance

**Comment by asklar** [comment]
good catch

**Comment by NickGerleman** [comment]
Do we have Hermes/V8-JSI napping to Hermes and V8 CVEs? I remember we've hit "hemes-egine" NPM package CVE without the NuGet package triggering anything.

**Comment by NickGerleman** [comment]
Most vulnerabilities there affect untrusted JS code. That's fine for most RNW use-cases, but I'm wondering if we should advertise security behaviors/update cycle of current 3p JS engines.

**Comment by NickGerleman** [comment]
Moving this to 0.66, since 0.65 is approaching and this does not regress functionality added in 0.64.

**Comment by jonthysell** [comment]
I've added the items, but CG is complaining that it doesn't know what folly or fmt is, so following up on that with the CG team.
