### ISSUE TITLE
Error Installing Visual Studio Via RNW Dependencies Script (choco thinks VS is installed when it isn't)

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#7709]
After uninstalling visual studio
install script gives this error
![image](https://user-images.githubusercontent.com/18900210/116770157-6bae4780-aa63-11eb-994d-786f1744808f.png)

_Originally posted by @rendomnet in https://github.com/microsoft/react-native-windows/issues/7436#issuecomment-830511790_

**Comment by asklar** [comment]
if you uninstalled from the Windows add/remove programs UI in the Settings app then the script might be getting confused.
open an elevated cmd prompt, and run `choco list -l`. If VS is still there you can remove the registration by running `choco uninstall visualstudio2019community`

**Comment by chrisglein** [comment]
Belief is that using `choco` asymmetrically (to install but not to uninstall) may cause `choco` to be confused. @rendomnet are you personally unblocked using the workaround above?

The script will fall back to checking whether VS is installed but it is trusting the choco registry if choco says it's installed. Ideally the script would handle that case.

**Comment by rendomnet** [comment]
@asklar guys its getting ridiculous. Under Mac all went without problems. But under Windows so many  problems.
Yes `visualstudio2019community`  there I reinstalled it to run react-native-windows project. What should I do? Do you have uninstall script?
![image](https://user-images.githubusercontent.com/18900210/117546706-8e38f580-b04d-11eb-9431-bc5cd7deb1c4.png)

**Comment by rendomnet** [comment]
@asklar  @chrisglein Cant uninstall using choco
![image](https://user-images.githubusercontent.com/18900210/118385087-c338df80-b62d-11eb-8195-7b54bd51d195.png)

**Comment by rendomnet** [comment]
After uninstalling and reinstalling with choco

![image](https://user-images.githubusercontent.com/18900210/118386618-89baa100-b63a-11eb-8618-d8f558b45058.png)

**Comment by rendomnet** [comment]
okay I found the issue.
signintool was not in ENV PATH. after adding 'C:\Program Files (x86)\Microsoft SDKs\ClickOnce\SignTool' to enviroment  PATH
app started.
