### ISSUE TITLE
Failure to sign appx during deployment

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#7710]
and after installing visual studio manually and running install script again

`npx react-native run-windows --logging`

![image](https://user-images.githubusercontent.com/18900210/116773102-37dc1d80-aa75-11eb-80d9-b5924246a9ca.png)

_Originally posted by @rendomnet in https://github.com/microsoft/react-native-windows/issues/7436#issuecomment-830558863_

**Comment by NickGerleman** [comment]
Note that there were some cert logic changes in 0.64 with https://github.com/microsoft/react-native-windows/pull/6646

This is also likely using the new deployment mechanism

**Comment by asklar** [comment]
@rendomnet do you have KB4535996 installed? if so that could be the source of the issue. See https://developercommunity.visualstudio.com/t/failed-to-sign-appx/934749

Uninstalling that KB seems to have worked for folks.

**Comment by chrisglein** [comment]
We believe this is resolved by getting the right KBs (either uninstalling the above one and/or moving forward to the next). @rendomnet let us know if that doesn't unblock you.

**Comment by rendomnet** [comment]
@chrisglein @asachin96 
I don't have this update.
![image](https://user-images.githubusercontent.com/18900210/116956609-7fea8280-acb7-11eb-9485-402744a0c801.png)

**Comment by asklar** [comment]
Can you share the build log? (*.binlog file)

**Comment by rendomnet** [comment]
[msbuild.zip](https://github.com/microsoft/react-native-windows/files/6446190/msbuild.zip)

**Comment by asklar** [comment]
tagging @svetbonev and @srdjanjovcic to comment on this package signing failure

**Comment by SvetBonev** [comment]
@japarson FYI

@rendomnet Unfortunately, it seems signtool.exe didn't print a reason why it failed.
Would you be able to run signtool.exe manually to try to sign the .appx package and see if you could capture more details?
I would also suggest to pass /v on the command line for verbose output.

**Comment by rendomnet** [comment]
what should I do exactly ? 
![image](https://user-images.githubusercontent.com/18900210/118386674-06e61600-b63b-11eb-836f-8d0f67171880.png)

**Comment by rendomnet** [comment]
@SvetBonev what should I do exactly?
![image](https://user-images.githubusercontent.com/18900210/118386721-4f9dcf00-b63b-11eb-8e32-6f0d7eaaf82e.png)

**Comment by rendomnet** [comment]
okay I found the issue.
signintool was not in ENV PATH. after adding 'C:\Program Files (x86)\Microsoft SDKs\ClickOnce\SignTool' to enviroment  PATH
app started.

**Comment by asklar** [comment]
it's weird that signtool wouldn't be found by the project system (there should be another one that isn't in the ClickOnce directory too, afaik) so it would be interesting to understand why/how you got into this state. Any idea what could have happened @SvetBonev ?

**Comment by SvetBonev** [comment]
@rendomnet 
We expect to find signtool.exe at "\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x86\signtool.exe"

Does the binary exist in this location?
If not, could you repair the Windows 10 SDK version 10.0.19041.0?

**Comment by rendomnet** [comment]
@SvetBonev yes file exists in \Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x86\signtool.exe
