### ISSUE TITLE
Use Hermes-Windows 0.8.0

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#7711]
Facebook cut Hermes 0.8.0 for use with react-native 0.65. We should use the same version for RNW 0.65. We should update the Hermes-Windows NuGet package and use the new version in RNW.

**Comment by NickGerleman** [comment]
Marking as blocking 0.65 release, since it is needed to prevent Hermes from crashing on 0.65. @mganandraj will be the one to bring new payload into Hermes-Windows.

**Comment by mganandraj** [comment]
I'm on it.

**Comment by NickGerleman** [comment]
Anandraj published https://www.nuget.org/packages/ReactNative.Hermes.Windows/0.8.0-staging that we will use in the interim.

**Comment by NickGerleman** [comment]
Superceded by #7846
