### ISSUE TITLE
[E2E tests] visitAllPages.test.ts doesn't visit all pages

### ISSUE THREAD

**Issue by rectified95** [microsoft/react-native-windows#7726]
Seems like a bunch of pages have been added in RNTester (some examples simply moved out of the SectionList page), but we haven't included them in the test that opens all of them.

**Comment by asklar** [comment]
Ideally the test could discover the pages instead of relying on a hardcoded list

**Comment by NickGerleman** [comment]
I knew we had an issue for this before, but it looks like I accidentally closed it at some point with an unrelated PR 👀

https://github.com/microsoft/react-native-windows/issues/5775

**Comment by NickGerleman** [comment]
I played around with extracting names from source code but that approach did not work well.
