### ISSUE TITLE
Issues facing in react native windows upgrade to 0.64.5

### ISSUE THREAD

**Issue by sakthivel-servicemax** [microsoft/react-native-windows#7730]
We have upgraded to react native windows 0.64.5. 
I have three issues with the upgrade.
1) We have local Database. when we do db operation and react navigation together, application is crashing.
This was not happening before. I think, this threading logic is what causing the crash.  If we add some delay in navigation, we don't see the crash. but adding delay to entire project is not a good idea and customers will not like too.

2) OnLayout, we have done some resizing logic. This was working immediate before. But now, it takes some time. We see some delay in rendering.

3) Debugging is very slow now. This also was fine before. But Release bundle is fine with the upgrade. We see the slowness in debug mode only.

Do you have any solution for these?. Thanks in advance.

**Comment by asklar** [comment]
it will be hard to tell what the issues are caused by, without more information (call stack of the crash at the very least), or ideally a self-contained repro that we can look at.

**Comment by asklar** [comment]
Also, what version are you upgrading from?

**Comment by sakthivel-servicemax** [comment]
i am getting the exception 
**Exception thrown at 0x768BA6E2 in AppName.exe: Microsoft C++ exception: std::out_of_range at memory location 0x0987EFC4.
Debug Error!**

The version is getting upgraded from 0.63 to 0.64.5

**Comment by asklar** [comment]
@sakthivel-servicemax can you please provide a full call stack? that error message isn't very useful by itself

**Comment by tero-paananen** [comment]
I noticed also that my app (rn-w 0.64.7) is very slow when Chrome debugger is running...
