### ISSUE TITLE
requireNativeComponent: "RCTWebView" was not found in the UIManager.

### ISSUE THREAD

**Issue by dbm5858** [microsoft/react-native-windows#7758]
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`: 4.13.0
2. `npx react-native info`:
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 6.63 GB / 15.86 GB
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 30.0.2
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6858069
    Visual Studio: 16.9.31205.134 (Visual Studio Professional 2019)
  Languages:
    Java: javac 15 - C:\Users\MeilickD\dev\jdk-15\bin\javac.EXE
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-windows: ^0.63.28 => 0.63.28
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.  npm install react-native-webview
2.  npx react-native run-windows

## Expected Results
Describe what you expected to happen.
I included the following on one of my pages:

<WebView source={{uri: 'https://reactnative.dev/'}} />

I expect a webview with the react native web page displayed.  Instead, I get the "RCTWebView not found" error.

CLI auto-link says:

>npx react-native autolink-windows
 √ Auto-linking...
Success: No auto-linking changes necessary. (3601ms)

I'm not sure what else to do.  Very much lost, here.

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by jonthysell** [comment]
Can you run `npx react-native autolink-windows --logging` and post the result?

**Comment by jonthysell** [comment]
Which version of react-native-webview are you using? Autolinking is only available in 11.4.3 and above.

**Comment by dbm5858** [comment]
react-native-webview is 11.4.4.

**Comment by dbm5858** [comment]
C:\Users\MeilickD\dev\rnw\WebView>npx react-native autolink-windows --logging
⠋ Auto-linking...
Parsing project...
Found Windows app project, config:
{
  folder: 'C:\\Users\\MeilickD\\dev\\rnw\\WebView',
  sourceDir: 'windows',
  solutionFile: 'NavigationDemo.sln',
  project: {
    projectFile: 'NavigationDemo\\NavigationDemo.csproj',
    projectName: 'ProductConfigurationUtility',
    projectLang: 'cs',
    projectGuid: '{F2DB7379-DA36-4B7B-8543-D970CB080697}'
  }
}
Parsing dependencies...
react-native-sensitive-info has Windows implementation, config:
{
  folder: 'C:\\Users\\MeilickD\\dev\\rnw\\WebView\\node_modules\\react-native-sensitive-info',
  projects: [
    {
      projectFile: 'RNSensitiveInfoCPP\\RNSensitiveInfoCPP.vcxproj',
      projectName: 'RNSensitiveInfoCPP',
      projectLang: 'cpp',
      projectGuid: '{471024f1-cd6d-4f1e-a6c7-0037152c850e}',
      directDependency: true,
      cppHeaders: [Array],
      cppPackageProviders: [Array],
      csNamespaces: [Array],
      csPackageProviders: [Array]
    }
  ],
  solutionFile: null,
  nugetPackages: [],
  sourceDir: 'windows'
}
Adding react-native-sensitive-info.
react-native-webview has Windows implementation, config:
{
  folder: 'C:\\Users\\MeilickD\\dev\\rnw\\WebView\\node_modules\\react-native-webview',
  projects: [],
  solutionFile: 'ReactNativeWebView.sln',
  nugetPackages: [],
  sourceDir: 'windows'
}
Adding react-native-webview.
Calculating AutolinkedNativeModules.g.cs...
Reading AutolinkedNativeModules.g.cs...
No changes to AutolinkedNativeModules.g.cs.
Calculating AutolinkedNativeModules.g.props...
Reading AutolinkedNativeModules.g.props...
No changes to AutolinkedNativeModules.g.props.
Calculating AutolinkedNativeModules.g.targets...
Reading AutolinkedNativeModules.g.targets...
No changes to AutolinkedNativeModules.g.targets.
Calculating NavigationDemo.sln changes...
Processing RNSensitiveInfoCPP.vcxproj...
No changes to NavigationDemo.sln.
 √ Auto-linking...
Success: No auto-linking changes necessary. (7241ms)

**Comment by dbm5858** [comment]
My main Windows project is C# (UWP), not C++.  I'm beginning to wonder if it is related to that.

**Comment by jonthysell** [comment]
@chiaramooney You just added autolinking to react-native-webview with a new `react-native.config.js`, but it looks like the file isn't getting published in their npm package. It needs to be added to the files portion of their `package.json` file.

**Comment by chiaramooney** [comment]
On it! Will have a PR with the needed changes soon!
