### ISSUE TITLE
How to show 3d model/CAD file in react native windows application

### ISSUE THREAD

**Issue by navneetbagri** [microsoft/react-native-windows#7760]
# How to use `react-native-gl-model-view` on RNW

## Basic Info
- Module Repo URL: [link to repo](https://www.npmjs.com/package/react-native-gl-model-view)
- Target version: 0.63

## Which app/customer is requesting this module?

Those who want to show 3d model in react native windows application

**Comment by chrisglein** [comment]
Some links to other queries about GL/3D support and libraries/techniques: #2424 #6301

**Comment by chrisglein** [comment]
Closing this module request as not in plan. Not that this module _shouldn't_ receive a Windows implementation, but it makes more sense to track that request on the module's repo rather this repo.

**Comment by sisu2468** [comment]
Is there a feature to display CAD drawings in React Native?
