### ISSUE TITLE
Add support for detecting intention to open a context menu

### ISSUE THREAD

**Issue by rigdern** [microsoft/react-native-windows#777]
Forked from #774 which is about supporting right-click.

We need a way to detect the user's intention to open a context menu. Different types of input have different typical ways of triggering this:
- Mouse: right-click
- Touch: press and hold
- Keyboard: context menu key

As described in https://github.com/ReactWindows/react-native-windows/issues/688#issuecomment-253341636, we'll want the ability to detect these things independently (i.e. right-click vs press and hold vs context menu key) but we also might want a higher level event representing the intention of opening a context menu.

Prior art:
- Web has a [`contextmenu` event](https://developer.mozilla.org/en-US/docs/Web/Events/contextmenu)
- UWP ???

**Comment by rigdern** [comment]
> In https://github.com/ReactWindows/react-native-windows/issues/774#issuecomment-253347211 @rozele wrote:

> Well, there is a concept of a FlyoutMenu in UWP, but I don't think anything specific to trigger context menus. There's the RightTapped event, but I don't think we'll be using that. Keyboard is a whole other class of issues we'll need to create (i.e., I should be able to "tab" through the UI to focus on Controls, simulate onPress (potentially) using the return key when focused on a button, open a context menu, etc. But yeah, let's leave that for another time and keep this issue specific to just having the bare minimum option to recognize a right-click. Feel free to file an issue on context menus separately.

I think context menu and right-click are related enough that we should consider how to represent context menu in general before implementing right-click. Otherwise, later when we implement the rest of the context menu triggers, we might discover we made a poor choice for how to represent right-click.

I brought up UWP mostly as an example to look at for API design ideas. You mentioned UWP has a `RightTapped` event. Is that exposed on a particular UIElement subclass? Is that fired for multiple input types or just one? Are there other events?

**Comment by rozele** [comment]
RightTapped is available on all UIElements https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.xaml.uielement.righttapped.aspx

**Comment by rozele** [comment]
This is also something we can cross-post in react-native as an issue, I think we'll want to map a long-press to a context menu intent on any device.

**Comment by crutchcorn** [comment]
I apologize for bringing back an old issue, but I can't seem to find any resource or answer to this question anywhere else:

Does React Native Windows support handling of a right click on an "element"? If so, where can I find API docs?

**Comment by Hardikb19** [comment]
Hey is there any update on this, maybe any API doc which could be used to figure out how to detect a right click in React Native Windows?

**Comment by chrisglein** [comment]
You can ask questions in the Discussions tab: https://github.com/microsoft/react-native-windows/discussions
Were you unable to find what you were looking for in the documentation and samples? https://microsoft.github.io/react-native-windows/
It's helpful to know where you expected to find this information so we can enhance discoverability.

**Comment by IamJignesh** [comment]
Maybe this helps, we have been able to use the onTouchStart method on the <View> to detect the right click
![Image](https://github.com/user-attachments/assets/e99af089-de22-4adc-beae-2ad5aa9d85af)

**Comment by dngrhm** [comment]
> Maybe this helps, we have been able to use the onTouchStart method on the to detect the right click ![Image](https://github.com/user-attachments/assets/e99af089-de22-4adc-beae-2ad5aa9d85af)

Is this old arch? it doesn't appear to be working in 0.78.13 using fabric/new arch app

<img width="1365" height="521" alt="Image" src="https://github.com/user-attachments/assets/c1cca073-2a20-4150-a5b2-01d56abd7874" />
