### ISSUE TITLE
Hanging Visual Studio on Build

### ISSUE THREAD

**Issue by ryfow** [microsoft/react-native-windows#7778]
Something about [this example project's](https://github.com/ryfow/BackgroundBreaksForeground/tree/hang-vs-1
) dependencies makes it so when I try to build with Visual Studio, it hangs while compiling TurboModuleProvider.cpp. `yarn windows` works fine. 

## Environment

```
$ npx react-native --version
5.0.1-alpha.2


$ npx react-native info
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19041
    CPU: (10) x64 Intel(R) Xeon(R) Gold 6226 CPU @ 2.70GHz
    Memory: 4.45 GB / 12.00 GB
  Binaries:
    Node: 14.8.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.7 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.15063.0, 10.0.16299.0, 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.9.31229.75 (Visual Studio Professional 2019), 16.7.31229.181 (Visual Studio Enterprise 2019)
  Languages:
    Java: 11.0.8 - C:\Program Files\Zulu\zulu-11\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.64.1 => 0.64.1
    react-native-windows: 0.64.6 => 0.64.6
  npmGlobalPackages:
    *react-native*: Not Found
```

- Visual Studio Version: Tried 16.7.15 and 16.9.5

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Open BackgroundBreaksForeground.sln and click the play button
2. Wait
3. Watch the build get stuck/possibly run out of memory
4. Kill visual studio somehow
5. Start with `yarn windows`
6. Watch app start ok

## Expected Results
I expect the project to be able to build in visual studio.

## Snack, code example, screenshot, or link to a repository:

https://github.com/ryfow/BackgroundBreaksForeground/tree/hang-vs-1

I'll leave the branch hang-vs-1 in place and will try to trim down the deps in package.json but wanted to get this bug created because I don't know how long that'll take.

I built the repo to demonstrate another bug, disregard the repo name & javascript code.

**Comment by ryfow** [comment]
I did get a bunch of dependencies removed. It seems like some combination of react-native-device-info, react-native-permissions, react-native-sensitive-info and react-native-fs causes the issue. Last time I tried it, things stopped while compiling sensitive-info.

**Comment by chrisglein** [comment]
It's possible there's some duplicate building of Microsoft.ReactNative.dll. I'm curious if this can also be resolved by using the experimental nuget. @jonthysell how close are you to having steps that someone can follow for updating to the nuget when they also have module dependencies?

**Comment by ryfow** [comment]
In case anyone else runs into this, I found that reducing the number of parallel project builds seems to work around this problem.

<img width="359" alt="image" src="https://user-images.githubusercontent.com/717985/127242552-6606418e-a9b9-446a-9938-d235626cd88c.png">

**Comment by jonthysell** [comment]
I have checked out the provided repo and was able to build without a hang.

First I updated react-native-windows to 0.64.16 (since it was targeting an older verison): `yarn add react-native-windows@0.64.16`

Autolinking would cause the build to fail, but it was because of #8530. So I switched the solution file to CRLF, and ran autolinking once to make it happy: `npx react-native autolink-windows` (the resulting changes were just some minor reordering of the dependencies).

Then I opened the solution in VS and F5 on Debug x86. App built and launched without any hangs. For reference my machine info is:

```
npx react-native info
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 7.74 GB / 15.84 GB
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.31613.86 (Visual Studio Enterprise 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.64.1 => 0.64.1
    react-native-windows: ^0.64.16 => 0.64.16
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by ryfow** [comment]
I'm relatively confident that the problem I was having was due to some sort of race condition when trying to build with a lot of cores and unrestricted parallelism. I'm not arguing that this shouldn't be closed, I just want a note here in case someone else runs into the same problem. Thanks.
