### ISSUE TITLE
Images not showing in release build (code-push can't `require` assets, need to explicitly use ms-appx/ms-appdata and lose `require` benefits)

### ISSUE THREAD

**Issue by omdxp** [microsoft/react-native-windows#7780]
## Environment
1. `npx react-native --version`: 4.13.1
2. `npx react-native info`: 
```
System:
    OS: Windows 10 10.0.19592
    CPU: (4) x64 Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
    Memory: 3.01 GB / 15.88 GB
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3, 31.0.0
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7199119
    Visual Studio: 16.9.31112.23 (Visual Studio Professional 2019)
  Languages:
    Java: 1.8.0_242-release
    Python: 3.9.2
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
    react-native-windows: ^0.63.0-0 => 0.63.18
```

## Steps To Reproduce

1. In debug all images can be displayed.
2. When I try to build in release all images cannot be displayed.

## Expected Results
Images can be displayed in release build.

## Example code snippet
```javascript
<Image 
   source={require('./assets/images/logo.png')}
/>
```

**Comment by Omar-Belghaouti** [comment]
I have looked for this and what I found as a solution is to copy `logo.png` inside `Assets` folder of the UWP project and then to get the image from React Native you should type the following:
```js
<Image 
   source={{uri: 'ms-appx:///Assets/logo.png'}}
/>
```

**Comment by acoates-ms** [comment]
We should make sure that the default project is configured in a way that the normal import of an image works.  The image should be added to the appx and work in release. -- If it isn't, then that's something we will look into.

**Comment by aalbaharnah** [comment]
@Omar-Belghaouti @acoates-ms @chrisglein 

This is related to `react-native-code-push` and only happens with **release bundle if the root component is wrapped with codePush higher-order component**

I think it's because react native assets not being bundled in code push JS bundle

This issue might help
https://github.com/microsoft/react-native-code-push/issues/699

**Comment by Omar-Belghaouti** [comment]
@aalbaharnah Thanks for the remark, I did in fact use code push in this project. Never thought it's because of it. But nevertheless, I think code push must bundle all the assets!

**Comment by asklar** [comment]
CC @qmatteoq FYI - something to look out for

**Comment by asklar** [comment]
tagging to bring this back to triage

**Comment by Andriiklymiuk** [comment]
What is the status of that one?
Still happening on rn 0.65.1
