### ISSUE TITLE
How to run exe file in react-native-windows application?

### ISSUE THREAD

**Issue by rendomnet** [microsoft/react-native-windows#7781]
I'm coming from electron. And looking for functionality similar to `child_process`. https://nodejs.org/api/child_process.html
I need to run other applications from my rnw application.

**Comment by chrisglein** [comment]
There are going to be different restrictions for RNW as opposed to Electron. More information here: https://microsoft.github.io/react-native-windows/docs/native-code

Can you provide more context about what you want? You can launch files (Which would open the default app for that), you can launch uris. There are mechanisms, but they are not as open ended as "run this exe".

**Comment by rendomnet** [comment]
@chrisglein I'm making app launcher, specifically game launcher. 
I need a way to run different applications, sometimes with some additional launch commands. 
As I know **Windows Xbox App** is made in react native windows. 
So it should be possible?

**Comment by chrisglein** [comment]
I think what you're looking for is this: [Launch an app with a URI](https://docs.microsoft.com/th-th/windows/uwp/launch-resume/launch-app-with-uri).

**Comment by rendomnet** [comment]
@chrisglein again link to a native documentation. But how to do it in react-native-windows?

**Comment by chrisglein** [comment]
> @chrisglein Chris Glein FTE again link to a native documentation. But how to do it in react-native-windows?

See the link in my previous response: https://microsoft.github.io/react-native-windows/docs/native-code
