### ISSUE TITLE
Support react-native-registry

### ISSUE THREAD

**Issue by rendomnet** [microsoft/react-native-windows#7782]
# Support `react-native-registry` on RNW

## Basic Info
- Module Repo URL: https://www.npmjs.com/package/windows-native-registry
- Target version: 
- [ ] Issue exists on module repo (if so, [link]())

- [ ] Module has a Legacy/C# implementation (if so, [link]())

## In what scenarios will this module be used?
CRUD operations with windows registry

## Essential Features
CRUD operations with windows registry

**Comment by chrisglein** [comment]
This module is a Node module, not a React Native module. There is no direct support for node modules (see #7529). Note the module isn't called `react-native-registry`. You can see if there's something related in the RN space but the registry concept is pretty specific to Windows, additionally as that RNW apps are UWP apps and run in an app container... it's not going to work. For more information check out this article: https://microsoft.github.io/react-native-windows/docs/native-code

If you just want a key/value store for your app, the async storage module does support Windows.
