### ISSUE TITLE
Do not hardcode branch version for doc generation

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#7785]
for 0.64 this happens [here](https://github.com/microsoft/react-native-windows/commit/187a6be31f685a5ea6f5404a2024c926b9ad445a#diff-6a3fb2d860be9b6a806db5a541290fe9ee6587935cc508750d89e77d7a19c3ecR83)
for 0.65 you'd just add /apiVersion 0.65 to the command line

_Originally posted by @asklar in https://github.com/microsoft/react-native-windows/issues/7679#issuecomment-842655292_

**Comment by NickGerleman** [comment]
We have a few solutions for this. E.g. we have en variables in the PR pipeline for current package version, the branch name itself, and a script for modifying the project when branching for anything that does need to be hardcoded.

**Comment by asklar** [comment]
Duplicate of #7599
