### ISSUE TITLE
Sometimes Touchable* onPress event handlers don't fire

### ISSUE THREAD

**Issue by rigdern** [microsoft/react-native-windows#779]
### Repro Steps
1. Copy the code below into an app. Run it on a desktop or laptop (i.e. not phone or Xbox).
2. Click the "Click Me First" touchable. This moves focus into the text input.
3. Click the "Click Me Second (0)" touchable.

**Unexpected result:** The touch seems to be ignored. There isn't any feedback when touching the item and its counter remains at 0.

**Expected result:** The touchable shows feedback and its counter increases making its value "Click Me Second (1)".

``` javascript
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  TextInput,
  TouchableHighlight,
  ScrollView,
} from 'react-native';

class RNPlayground2 extends Component {
  constructor() {
    super();
    this.state = { counter: 0 };
  }
  _handlePress1() {
    this.refs.input.focus();
  }
  _handlePress2() {
    this.setState({ counter: this.state.counter + 1 });
  }
  render() {
    return (
      <View style={styles.container}>
        <TextInput ref="input" />
        <ScrollView>
          <TouchableHighlight onPress={this._handlePress1.bind(this)}>
            <Text>Click Me First</Text>
          </TouchableHighlight>
          <TouchableHighlight onPress={this._handlePress2.bind(this)}>
            <Text>Click Me Second ({this.state.counter})</Text>
          </TouchableHighlight>
        </ScrollView>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
});

AppRegistry.registerComponent('RNPlayground2', () => RNPlayground2);
```
### Cause

The bug repros when a text input has focus and you attempt to click a touchable which appears inside of a ScrollView. The problematic code appears in [scrollResponderHandleStartShouldSetResponderCapture in ScrollResponder.js](https://github.com/facebook/react-native/blob/a3868722f8377688ffc69b2d346837838f1904f4/Libraries/Components/ScrollResponder.js#L169-L189).

What's going on is that the ScrollView wants the input in this case so it prevents the touchable from receiving it. This code is trying to cover the scenario that you are on a phone, the on screen keyboard is on the screen, and you tap elsewhere on your screen to dismiss the keyboard. The code is designed to cause this action to dismiss the keyboard without causing any other UI elements to respond to the input.

The code assumes that if a text input has focus then the on screen keyboard must be on the screen. This heuristic might work fine for phones but it doesn't work well on a desktop/laptop that doesn't have an on screen keyboard. The heuristic is probably also broken in scenarios that you have an on screen keyboard but the on screen keyboard is in a mode such that moving focus out of a text input doesn't cause it to dismiss.
### Workaround

Set `keyboardShouldPersistTaps={true}` on the `ScrollView`.

**Comment by rozele** [comment]
@rigdern what happens if you set keyboardShouldPersistTaps={true} on the ScrollView?

**Comment by rigdern** [comment]
Thanks, that works around the bug.

For a proper fix, I think we'll want to let JavaScript know what kind of touch keyboard is being used. Something like:
  - `auto dismissal`: The kind of keyboard RN works with today. It dismisses when no text inputs have focus. With regards to the behavior this issue is about, we'll maintain the current behavior.
  - `manual dismissal`: The keyboard only dismisses when the user explicitly closes it. With regards to the behavior this issue is about, all `ScrollViews` will behave as though `keyboardShouldPersistTaps` is `true`.

**Comment by rozele** [comment]
@rigdern should we close this issue and open a new one against react-native?

**Comment by rigdern** [comment]
I think this bug requires work in both the `react-native` and `react-native-windows` repos:
  1. `react-native`: [This JS logic](https://github.com/facebook/react-native/blob/a3868722f8377688ffc69b2d346837838f1904f4/Libraries/Components/ScrollResponder.js#L169-L189) needs to be updated to support both auto and manual dismissing keyboards.
  2. `react-native-windows`: Needs to figure out what kind of keyboard is being shown and configure the ScrollResponder JS module appropriately.

I think we should keep this bug open to track (2). I opened facebook/react-native#10426 to track (1).
