### ISSUE TITLE
ReactEvent API changed? Now event data is in array.

### ISSUE THREAD

**Issue by tero-paananen** [microsoft/react-native-windows#7797]
I noticed that there is some changes in ReactEvent API on rn-windows 0.64.7. I previously used 0.62.22

If i send event from C# module like this

```
[ReactEvent("folderChangeEvent")]
public Action<JSValue> FolderChangeEvent { get; set; }
```

```
JSValueObject eventData = new JSValueObject() {{ "key", "value") }};
FolderChangeEvent?.Invoke(eventData);
```

Is event value in array of objects in javascript side. There was object in 0.62.x.

```
const myModuleEventEmitter = new NativeEventEmitter(NativeModules.MyCSharpModule);
myModuleEventEmitter.addListener('folderChangeEvent', (event)=>{
    const e = event[0]; // array on 0.64.7
    // const e = event; // object on 0.62.22
});
```

**Comment by asklar** [comment]
This sounds vaguely familiar... @vmoroz ?

**Comment by vmoroz** [comment]
@tero-paananen, @asklar  I had recently fixed this issue in the latest code for C++. Let me see what is going on with C# and fix it there too.

**Comment by tero-paananen** [comment]
> @tero-paananen, @asklar I had recently fixed this issue in the latest code for C++. Let me see what is going on with C# and fix it there too.

What commit or react native windows version? I hope that fix is coming also into 0.64.x

**Comment by asklar** [comment]
@tero-paananen I believe vmoroz meant #7732 - I see this was marked as backport to 0.64 requested but I don't see a PR for it.

**Comment by chrisglein** [comment]
Not going to make 0.65 release. Whether it's a backport candidate depends on how breaking the change is. Going to let @vmoroz comment on that.

**Comment by tero-paananen** [comment]
I tested that event argument is **still array** on react-native-windows **0.65.2**

I will test later again when i have moved into 0.66...

**Comment by chrisglein** [comment]
@vmoroz @asklar Did the PR for this make the 0.66 branch? Can we resolve this?

**Comment by vmoroz** [comment]
@tero-paananen, it seems that I did not implement the change for C#. I will do it next week.

**Comment by tero-paananen** [comment]
0.65.7 still has the issue, i will check 0.66 soon

**Comment by asklar** [comment]
Hey @vmoroz is this already in main / 0.66?

**Comment by vmoroz** [comment]
I would like to keep it open until we fix the previous stable branches.

**Comment by tero-paananen** [comment]
Now i have valid event also in `"react-native-windows": "0.65.9"`

**Comment by vmoroz** [comment]
> Now i have valid event also in `"react-native-windows": "0.65.9"`

Thank you for confirming it!
