### ISSUE TITLE
NativeModules.I18nManager is null when UseWebDebugger = false

### ISSUE THREAD

**Issue by tero-paananen** [microsoft/react-native-windows#7799]
```
import { NativeModules } from 'react-native';

const I18nManager = NativeModules.I18nManager;

const getDeviceLocale = (): string => {
  const locale = I18nManager.localeIdentifier;
  return locale.substr(0, 2); // en-EN to en
};

export default getDeviceLocale;
```

When setting `InstanceSettings.UseWebDebugger = true;` in App.xaml.cs module exists in Chrome debugger.

## Environment
"react-native-windows": "0.64.7",
"react-native": "0.64.1",
"react": "^17.0.1",

React Native CLI: 5.0.1-alpha.2

System:
    OS: Windows 10 10.0.19041
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 18.97 GB / 31.89 GB
  Binaries:
    Node: 12.9.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.14393.0, 10.0.16299.0, 10.0.18362.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.7.30621.155 (Visual Studio Community 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: 0.64.1 => 0.64.1
    react-native-windows: 0.64.7 => 0.64.7
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by tero-paananen** [comment]
Currently only React Native Windows module that does this. Others seems to work...

**Comment by tero-paananen** [comment]
I tested this also in "hello world" app

```
npx react-native init Hello064 --template react-native@0.64.7 
cd Hello064
npx react-native-windows-init --overwrite --language cs
```

and the result is the same. Module exists only when Chrome debugger is running.

**Comment by NickGerleman** [comment]
Do you see a similar result if importing I18NManager from RN directly instead of looking at the NativeModules object? E.g.

```js
import { I18nManager } from 'react-native';
```

**Comment by tero-paananen** [comment]
Yes, solution to get it work is to import it from react-native

```
import { I18nManager } from 'react-native';

const getDeviceLocale = (): string => {
  let locale = 'en';
  const constants = I18nManager.getConstants();
  if (constants.localeIdentifier) {
    locale = constants.localeIdentifier.substr(0, 2); // en-EN to en;
  }
  return locale;
};

export default getDeviceLocale;
```

There is then issue in `I18nManager.getConstants()` result. It seems that `localeIdentifier` is not typed in result but we can read it. Typing is missing maybe from `I18nManagerStatic` 

```
export interface I18nManagerStatic {
    getConstants: () => {
        isRTL: boolean;
        doLeftAndRightSwapInRTL: boolean;
    };
    allowRTL: (allowRTL: boolean) => void;
    forceRTL: (forceRTL: boolean) => void;
    swapLeftAndRightInRTL: (swapLeftAndRight: boolean) => void;
    isRTL: boolean;
    doLeftAndRightSwapInRTL: boolean;
}
```

**Comment by chrisglein** [comment]
> Yes, solution to get it work is to import it from react-native

Sounds like you're unblocked and importing this in the supported way. Yay! Closing this issue.
