### ISSUE TITLE
Return non-zero exit code on Node unhandled promise rejection in CI

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#7804]
An unhandled promise rejection usually signifies an exception in an async method, or a failure to handle an error. In Node <15, it results in a printed warning, often leading to termination without a non-zero exit code. This means scripts may fail in CI without creating signal by failing the task.

Default node settings can be set via the `NODE_OPTIONS` environment variable. E.g. `NODE_OPTIONS=--unhandled-rejections=strict`. We should set this with our other environment variables defined in YAML.

**Comment by Patil2099** [comment]
@chrisglein  I would love to work on this issue. Can you guide me a little on how to solve this issue?

**Comment by chrisglein** [comment]
@NickGerleman If you can provide a bit more jump-start information on this issue we may have some extra willing hands to help out.

**Comment by NickGerleman** [comment]
AZP seems to run internal tasks using Node 10 which does not support the options, so globally overriding Node behavior causes AZP task failures.

Probably just worth waiting until Node 16 is LTS, which should come soon, and set this as the default once we set that as the version our own scripts run.
