### ISSUE TITLE
Do not "yarn install" full monorepo during PR Setup Phase

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#7811]
PRs run a single initial job to run beachball and run a script to manipulate environment variables. It does a full `yarn install` to do this, pulling in a lot more dependencies than the single phase would need.

We can create a minimal set of package dependencies that we pull in for just setup, and could save a minute or two on latency for each PR.

**Comment by chrisglein** [comment]
Sounds like a good quality of life improvement, assuming we don't have to groom that minimal set very often.

**Comment by NickGerleman** [comment]
This does catch missing lockfile changes early, which is a convenience. Going to close for now.
