### ISSUE TITLE
Missing return data typing in I18nManager.getConstants()

### ISSUE THREAD

**Issue by tero-paananen** [microsoft/react-native-windows#7817]
Return value of ` I18nManager.getConstants()`  is not typed fully. There is missing `localeIdentifier`

```
import { I18nManager } from 'react-native';
const constants = I18nManager.getConstants();

// NOTE: missing typing of constants.localeIdentifier
const locale = constants.localeIdentifier.substr(0, 2); // en-EN to en;
```

This issue was mentioned also in https://github.com/microsoft/react-native-windows/issues/7799

## Environment
"react-native-windows": "0.64.7",
"react-native": "0.64.1",
"react": "^17.0.1",
React Native CLI: 5.0.1-alpha.2

**Comment by NickGerleman** [comment]
Thanks for creating a new issue for this and holding us accountable.

The above type is dictated by the "@types/react-native" package. Some of our team has made contributions to this package, but we don't actually maintain it.

I looked at the history of this. It looks like the API for this was undocumented/untyped until very recently. Of course it was still there either way 🙂. 

I would expect to see this in TypeScript typings in a newer RN version, but you should be able to suppress the TS warning until then.

**Comment by chrisglein** [comment]
@NickGerleman can you clarify if this has been fixed already? Definitely should be and is external to this repo, but wasn't sure whether the fix was already in or not.

**Comment by NickGerleman** [comment]
Looks like ACoates fixed the issue in a new version of community typings linked above. Updating to the newest version of @types/react-native should add the method.
