### ISSUE TITLE
TimeoutException when trying to deploy to Xbox

### ISSUE THREAD

**Issue by fasci** [microsoft/react-native-windows#7818]
_I'm aware that the following problem is probably more related to Visual Studio than react-native-windows itself, but any help on this issue would be highly appreciated._

I try to deploy (debug) a UWP app created with react-native-windows to an Xbox.

Windows 10 and thus Visual Studio (Community 2019, Version 16.9.6) is running in a virtual machine, but on the same network as the Xbox.

I can ping the Xbox from PowerShell, and VS is able to detect the device in the Remote Connections popup. So I can set the proper Machine Name in the Remote Machine config:
<img width="400" alt="Screenshot 2021-05-21 at 11 29 17" src="https://user-images.githubusercontent.com/2779613/119123082-8014ad00-ba2f-11eb-896b-d0b01b34c8d8.png">

Building the app works fine, but when it comes to deployment, I keep getting the following error message:
```
DEP0600: Deployment failed. DeviceException - DEP0001: Unexpected Error: TimeoutException - This operation returned because the timeout period expired. (Exception from HRESULT: 0x800705B4) [0x80131505] [0x80131500]
	Target.DeviceFamily = Windows.Xbox
	DeploymentSucceeded = False
	DeploymentError = Err_Deploy_FailedGeneric
	DeploymentHRESULT = 2148734208
	HasSharedCode = False
	Target.Id = 1024
	ProjectGuid = {9292a0d9-707e-4c78-ae46-dfd9efff3da8}
	Project.TargetPlatformVersion = 10.0.18362.0
	Project.TargetPlatformMinVersion = 10.0.16299.0
```

The network connection is stable. Deployment did work twice for me so far, but after a while, I kept (and keep) getting the timeout exception again, so the behavior is not deterministic.
I tried this now with three different WiFi access points, and am running out of options.

Is there any way to change the timeout threshold?
Any help would be much appreciated.

**Comment by asklar** [comment]
Sounds like there's probably some firewall rule that needs to be applied, but our team doesn't support VS or XBOX, can you please file a bug in the VS developercommunity site? (Help->Send Feedback)

**Comment by fasci** [comment]
Thanks for the reply, @asklar.
For future readers of this issue, the following workaround (found [here](https://answers.microsoft.com/en-us/xbox/forum/all/cant-deploy-app-to-xbox/b94a9a27-89af-43b8-9473-692ba89bf72b)) works for me:
- 'Remove all Visual Studio pairings' from Xbox in Dev Mode.
- Press 'Remote Machine' in VS to remotely debug your app.
- Enter new pairing pin when asked for.
- Deployment will fail.
- Again 'Remove all Visual Studio pairings' from Xbox in Dev Mode.
- Press 'Remote Machine' in VS to remotely debug your app.
- Deployment should now succeed.
