### ISSUE TITLE
HTTP Authorization Header is being modified in NetworkingModule

### ISSUE THREAD

**Issue by rs22** [Microsoft/react-native-windows#782]
I'm using the [Hawk HTTP authentication library](https://github.com/hueniverse/hawk) in my React Native app. When I'm making HTTP requests they have Authorization headers like this:

`Authorization: Hawk id="xxx", ts="1476364917", nonce="4YDs1Y", mac="Gs8i3GEpoCcFzSxm5I4NZdfREIHgBreSrq76biLsuQY="`

However, this is what is being sent over the network (note that some quotes disappeared):
`Authorization: Hawk id="xxx", ts=1476364917, nonce=4YDs1Y, mac="Gs8i3GEpoCcFzSxm5I4NZdfREIHgBreSrq76biLsuQY"`

The modification happens when the header value is being assigned to the HttpRequestHeaderCollection ([NetworkingModule:429](https://github.com/ReactWindows/react-native-windows/blob/master/ReactWindows/ReactNative/Modules/Network/NetworkingModule.cs#L429)), apparently some parsing happens in the background which creates a HttpCredentialsHeaderValue from the string.

As a workaround, I'm manually separating the Authorization scheme from the rest by splitting the string at the first space, in order to explicitly construct and assign a HttpCredentialsHeaderValue. This works well for my use case.

However, it might not be a good solution in the general case; I've looked into the System.Net.Http.HttpClient [code](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/Headers/AuthenticationHeaderValue.cs), and their parsing implementation looks more sophisticated.

**Comment by rozele** [comment]
Thanks for filing @rs22 I'm reaching out to see if there's any other work around.  I'm actually not sure why we went with the HttpClient from the Windows namespace instead of System.Net.Http...

**Comment by rozele** [comment]
Closed by #2041
