### ISSUE TITLE
How do I change RequiresPointerMode and SetDesiredBoundsMode in a RNW app?

### ISSUE THREAD

**Issue by marnusw** [microsoft/react-native-windows#7826]
I am trying to apply these best practice settings for an Xbox app:

1. https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/how-to-disable-mouse-mode
2. https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/disable-scaling
3. https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/turn-off-overscan

I was able to configure 2. successfully in `App.cpp` using:

```c++
ApplicationViewScaling::TrySetDisableLayoutScaling(true);
```

I tried to do 3. similarly with:

```c++
ApplicationView::GetForCurrentView().SetDesiredBoundsMode(ApplicationViewBoundsMode::UseCoreWindow);
```

There is no syntax error, but it throws an exception at start-up, and I think it's becuase `GetForCurrentView` isn't working right where I'm calling it in `App.cpp`. (Right now my app doesn't go to the edge of the screen on the TV, and from what I can tell this setting should fix that so it covers the entire screen.)

Lastly, I haven't been able to figure out at all where to do something along the lines of:

```c++
public App() {
        this.InitializeComponent();
        this.RequiresPointerMode = Windows.UI.Xaml.ApplicationRequiresPointerMode.WhenRequested;
        this.Suspending += OnSuspending;
}
```

Your help will be greatly appreciated.

**Comment by chrisglein** [comment]
You likely need to call this later than the `App` constructor. Page navigation is a natural choice (and by default you only have one page with the RNW default app template). So if you add your hook to `MainPage.cpp`/`MainPage.cs` to its constructor or override `OnLoaded` that _should_ do the trick. Let us know if not?

**Comment by marnusw** [comment]
Thanks for the reply @chrisglein. I got it working. Here is the solution for future reference:

In `pch.h` add:

```c++
#include <winrt/Windows.UI.ViewManagement.h>
```

In `App.cpp` add:

```c++
// After the other namespace imports
using namespace winrt::Windows::UI::ViewManagement;

// In the constructor, AFTER the InitializeComponent() call
Application::Current().RequiresPointerMode(ApplicationRequiresPointerMode::WhenRequested);

// In the OnLaunched override after the call to super::OnLaunched(e);
ApplicationViewScaling::TrySetDisableLayoutScaling(true);
ApplicationView::GetForCurrentView().SetDesiredBoundsMode(ApplicationViewBoundsMode::UseCoreWindow);
```

That covers all the Xbox best practices given [here](https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/tailoring-for-xbox).
