### ISSUE TITLE
Memory leak in JSValue

### ISSUE THREAD

**Issue by OleksandrDorosh** [microsoft/react-native-windows#7827]
## Environment
  "name": "react-native",  "version": "0.63.3"
  "name": "react-native-windows", "version": "0.63.4"

- Target Device(s): Desktop
- Visual Studio Version: Visual Studio 2019
- Build Configuration: Debug
- I checked memory consumption by Diagnostic Tool->Memory usage. I made memory dump before loop and after 10000 iterations, and compare them.
- Actually 2 memory leaks here. 1 = 120 bytes, 2 = 16 bytes. Stack call for both of them you can see on the screenshots. 

## Steps To Reproduce

 int i = 0;
 for (; i < 10000; ++i)
            {
                JSValueArray ar;
                JSValueObject v0{ {"X", 0} };
                JSValue val = JSValue(std::move(v0));
                ar.push_back(std::move(val));
                ar.push_back(JSValue("Test"));
            }

## Expected Results
No any memory leaks.

## Snack, code example, screenshot, or link to a repository:
![Screenshot (38)](https://user-images.githubusercontent.com/84740557/119399899-24257f00-bce2-11eb-8170-d84d2eae16a5.png)
![Leak1](https://user-images.githubusercontent.com/84740557/119399926-2d165080-bce2-11eb-879b-91e516cf6096.png)
![Leak2](https://user-images.githubusercontent.com/84740557/119399930-2e477d80-bce2-11eb-8c8d-1197d1c3d8b3.png)

**Comment by vmoroz** [comment]
@OleksandrDorosh, thank for finding and reporting the issue! I was able to repro and fix it. I will send a PR soon.
