### ISSUE TITLE
Implement `enableFocusRing` for <TextInput>

### ISSUE THREAD

**Issue by hossamnasser938** [microsoft/react-native-windows#7839]
![Screenshot 2021-05-25 173902](https://user-images.githubusercontent.com/27894818/119527559-b8462380-bd80-11eb-842d-396b0e98cb43.png)

**Comment by NickGerleman** [comment]
@rectified95 I remember you looked at “enableFocusRing” recently. Do you know if it is applicable here?

**Comment by chrisglein** [comment]
There should be a mechanism for this, but it might not be functioning. We'll investigate.

**Comment by chrisglein** [comment]
Also, it isn't a property on core. If we intend to support it then we also want to document it as well. Isn't today.

**Comment by NickGerleman** [comment]
`enableFocusRing` is the prop we use to control this on `<View>`. It is not supported across different components yet, do we do not think it will work against `<TextInput>`.

This issue should track the implementation of `enableFocusRing` against `<TextInput>`. We should ideally also add this to RN typings, so that TypeScript users can use the property.

**Comment by rectified95** [comment]
XAML TextInput is derived from Control, so this should work if I use the same function - `UseSystemFocusVisuals` - on it as well; will try it out in a few days

**Comment by rectified95** [comment]
@hossamnasser938 Would you mind posting your repro code? 
I've tried adding a border to a TextInput in one of our RNTester examples, and don't see your issue:
![image](https://user-images.githubusercontent.com/12816515/120708556-8f085000-c470-11eb-8f0a-8ee68f1e37ec.png)

vs without focus

![image](https://user-images.githubusercontent.com/12816515/120708992-279ed000-c471-11eb-90d2-2d8b3e17ad7d.png)

It's also the default behavior of the XAML to change the border color to blue (in light mode) when the TextBox receives focus.
@NickGerleman Should we allow people to overwrite this and deviate from platform behavior to align with iOS/Android, which don't do that?

**Comment by hossamnasser938** [comment]
@rectified95 I set borderColor to 'transparent' and it solved the issue. Thank you very much

**Comment by chrisglein** [comment]
> @rectified95 Igor Klemenski FTE I set borderColor to 'transparent' and it solved the issue. Thank you very much

Glad to hear you're unblocked! Closing out this issue.
