### ISSUE TITLE
WebAuthenticationBroker not opening the login dialog when invoked from a package (Native Module)

### ISSUE THREAD

**Issue by thedf** [microsoft/react-native-windows#7847]
I am trying to build a Native Module to have OpenID auth in windows along with other supported platforms. So I am trying to use the native WebAuthenticationBroker. I followed the steps in  **Steps To Reproduce** to have a Module that opens the Login dialog by WebAuthenticationBroker without success.
Expected to a window To login with the OpenID provider. However, I am getting absolutely nothing.
the function is correctly bind with react native as I get in my react native code the Something To return string, Also the library Windows::Security::Authentication::Web is correctly imported and working as the function `WebAuthenticationBroker::GetCurrentApplicationCallbackUri();` gives the correct result.
I tried to run the code : 

```[C++]
            Uri callbackUri = WebAuthenticationBroker::GetCurrentApplicationCallbackUri();

            winrt::hstring AuthURL= L"https://AnyOpenIDProvider/auth?clientid=....";

            WebAuthenticationBroker::AuthenticateAsync(WebAuthenticationOptions::None, Uri(AuthURL), callbackUri);
```
inside the MainApp.cpp of the app files instead of those of the package and they give the expected result. However, I don't have a way to invoke the function in MainApp.cpp from the package I'm developing nor am I capable of having the expected result straight from the package itself.

## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`:
5.0.1-alpha.2
2. `npx react-native info`:
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 19.72 GB / 31.90 GB
  Binaries:
    Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - C:\node-v12.18.3-win-x64\yarn.CMD
    npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.14393.0, 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.9.31129.286 (Visual Studio Professional 2019)
  Languages:
    Java: 1.8.0_232 - C:/Program Files/AdoptOpenJDK/jdk-8.0.232.09-openj9/bin/javac.exe
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: ^0.64.0-rc.1 => 0.64.0
    react-native-windows: ^0.64.0 => 0.64.2
  npmGlobalPackages:
    *react-native*: Not Found
3.  `npx react-native run-windows --info` : 

 System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 19.84 GB / 31.90 GB
  Binaries:
    Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - C:\node-v12.18.3-win-x64\yarn.CMD
    npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 16.13.1 => 16.13.1
    react-native: ^0.64.0-rc.1 => 0.64.0
    react-native-windows: ^0.64.0 => 0.64.2
  Installed UWP SDKs:
    10.0.14393.0
    10.0.18362.0
    10.0.19041.0

- Target Platform Version(s):
Windows Desktop
- Target Device(s):
 Visual Studio 2019
- Visual Studio Version:
Which build configuration are you running?  Debug

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.Start a sample react native windows project or use any that you have already.
2.Create a Native Modules from official instructions and bind it to your app.
3.Add imports for WebAuthenticationBroker which are : 
```[C++]
#include "winrt/Windows.Security.Authentication.Web.h"
using namespace winrt::Windows::Security::Authentication::Web;
using namespace winrt::Windows::Foundation;

```
4.Have a function like this :
```[C++]
        REACT_METHOD(Authorize, L"authorize")
        void Authorize(
            React::ReactPromise<std::string> result) noexcept
        {

            Uri callbackUri = WebAuthenticationBroker::GetCurrentApplicationCallbackUri();

            winrt::hstring AuthURL= L"https://AnyOpenIDProvider/auth?clientid=....";

            WebAuthenticationBroker::AuthenticateAsync(WebAuthenticationOptions::None, Uri(AuthURL), callbackUri);

            std::string statusString = "Something to return";

            result.Resolve(statusString);
        }
```
5.Invoke the function from react native.
2.In the root directory of the repository on your device, run yarn.
3.In the same directory run `npx react-native run-windows`.

## Expected Results
Expected to a window To login with the OpenID provider. 

## Snack, code example, screenshot, or link to a repository:
https://github.com/microsoft/react-native-gallery

**Comment by asklar** [comment]
@thedf it's possible / likely that the AuthenticateAsync api must be called from the UI thread (I don't actually know, this is a platform API that our team does not own, but just a guess), in which case you'd have to post a lambda to the UI thread by calling `reactContext.UIDispatcher().Post(...)`

**Comment by thedf** [comment]
Works like a charm, thanks  a lot @asklar !

**Comment by asklar** [comment]
Glad to hear it works! Tagging to look at triage still since we should understand the impact of having changed the threading model. Is there something we can do at the RN level to hint at the fact that we are not in the UI thread, when calling into the native platform?

**Comment by asklar** [comment]
@thedf also if you plan to make your module available to the community, let us know, we'd love to hear success stories :)

**Comment by chrisglein** [comment]
> Glad to hear it works! Tagging to look at triage still since we should understand the impact of having changed the threading model. Is there something we can do at the RN level to hint at the fact that we are not in the UI thread, when calling into the native platform?

There should be a standard HRESULT for invalid thread calls. If we can capture that as a standard error after everything explodes, that seems helpful. Write up a proposal issue for this @asklar?

**Comment by cjhines** [comment]
@thedf Is this module public anywhere? I would be very eager to see the final result

**Comment by thedf** [comment]
It's not public unfortunately.

**Comment by cjhines** [comment]
Oh well, was worth a shot :) Thanks for the quick response!
