### ISSUE TITLE
[CI Break] C3246 compiler error due to new VS update

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#7849]
> See `error C3246` at https://dev.azure.com/ms/react-native-windows/_build/results?buildId=169417&view=logs&j=ce6dbd70-21a8-576a-2d1e-b860511db24a&t=99422dc1-32ec-55ed-17e7-9f92b00603bf&l=7406
> 
> @dannyvv @NickGerleman Would you happen to know what this error is about?
> Else, do you know how to reproduce this (build `packages\integration-test-app\windows\integrationtest.sln`) locally?

Likely this is due to a new VS ingestion and unrelated to this change (but still needs to be fixed), can you upgrade your VS and try building locally to repro? it looks like some class is marked final when it shouldn't be.

(This goes to the earlier point about only ever supporting the latest VS :) )

_Originally posted by @asklar in https://github.com/microsoft/react-native-windows/issues/7779#issuecomment-848485172_

**Comment by asklar** [comment]
CC @AgneLukoseviciute

**Comment by chrisglein** [comment]
Update: This does not look related to VS, but platform SDK.
This should be considered blocking for this PR: https://github.com/microsoft/react-native-windows/pull/7779#issuecomment-848485172 (@JunielKatarn FYI)

**Comment by JunielKatarn** [comment]
Looking at other PRs, this issue does seem SDK-related and not VS-related.
Closing this issue, for the #7779 has not been merged and it will be resolved before doing so.
