### ISSUE TITLE
Unable to deploy to Hololens 2 from CLI

### ISSUE THREAD

**Issue by tayomadein** [microsoft/react-native-windows#7850]
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`: 5.0.1-alpha.2
2. `npx react-native info`:
System:
    OS: Windows 10 10.0.19043
    CPU: (24) x64 Intel(R) Core(TM) i9-7920X CPU @ 2.90GHz
    Memory: 37.56 GB / 63.73 GB
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 7.11.2 - ..\node_modules\.bin\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.16299.0, 10.0.17134.0, 10.0.17763.0, 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7199119
    Visual Studio: 16.9.31205.134 (Visual Studio Enterprise 2019)
  Languages:
    Java: 1.8.0_282 - C:\Program Files\OpenJDK\openjdk-8u282-b08\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.1 => 17.0.2
    react-native: ^0.64.0 => 0.64.0
    react-native-windows: ^0.64.1 => 0.64.3
  npmGlobalPackages:
    *react-native*: Not Found

What SDK version are you building for? Choose from 10.0.15063, 10.0.16299, 10.0.18362, etc.
- Target Platform Version(s): 10.0.19041.0
What device(s) are you targeting? Choose any from Desktop, Xbox, Hololens)
- Target Device(s): Hololens 2
Which version of Visual Studio are you using? Specify Visual Studio 2017 or Visual Studio 2019
- Visual Studio Version:  Visual Studio 2019
Which build configuration are you running? Choose from Debug, DebugBundle, Release, ReleaseBundle 
- Build Configuration:

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Connect Hololens 2 to computer.
2. Run either of these commands: 
```
	npx react-native run-windows --arch ARM64 --device
        npx react-native run-windows --arch ARM64 --target <GUID>
```
3  This is the output:
```
	√ Building Solution
 	   √ React-Native Server already started
 	   × Failed to deploy: No devices found
```

## Expected Results
An app deployed to hololens 2 from the CLI.
I am able to achieve this in Visual Studio 2019

## Snack, code example, screenshot, or link to a repository:
![image](https://user-images.githubusercontent.com/15232740/119713889-20b50380-be5a-11eb-9035-493532bc6fb2.png)
Build output

**Comment by chrisglein** [comment]
@tayomadein It sounds like you're unblocked by doing this through VS. How painful is it to do it that way and not use the CLI? Honestly on Windows we've had less focus on device deploy over CLI as there are fewer customers of that (although HoloLens is a great one). From a priority/resources perspective if you're able to make do with using VS here then we're not at the moment going to try to patch the CLI path.

**Comment by tayomadein** [comment]
@chrisglein my team is working to support for Babylon React Native and one of our goals is to have a workflow that allows developers do all their work with VS Code and the CLI without using another tool (Visual Studio) for deployments. While this is not a blocker for me right now, it could become a bottle neck for our users in a few weeks.

**Comment by tymlipari** [comment]
@tayomadein asked me to chime in here re: priority.

For our HoloLens developers, this is a scenario we'd love to have as we expect most of our developers to largely be working out of VSCode rather than VS proper, especially as Chakra debugging is broken on ARM64. Having the ability to deploy to device via the CLI would be great because we can easily integrate that into a VSCode inner loop workflow. 

That said, we _do_ have the "workaround" of just using VS, and we're still going to be in-development for a while, so it's not urgent that this be fixed immediately. Ideally we'd have this resolved by this fall/winter to keep with our schedule.
