### ISSUE TITLE
react-native-video works in debug but not release builds

### ISSUE THREAD

**Issue by ryfow** [microsoft/react-native-windows#7855]
react-native-video works in debug but not release builds

## Environment
```
PS C:\Projects\RNVProblem> npx react-native-version
npx: installed 51 in 5.957s
[RNV] Versioning Android...
[RNV] Android updated
[RNV] Versioning iOS...
[RNV] iOS updated
[RNV] Done
PS C:\Projects\RNVProblem> npx react-native info
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19041
    CPU: (10) x64 Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz
    Memory: 6.18 GB / 12.00 GB
  Binaries:
    Node: 14.8.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.7 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.15063.0, 10.0.16299.0, 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.9.31229.75 (Visual Studio Professional 2019), 16.7.31229.181 (Visual Studio Enterprise 2019)
  Languages:
    Java: 11.0.8 - C:\Program Files\Zulu\zulu-11\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.0 => 0.64.0
    react-native-windows: ^0.64.0-0 => 0.64.9
  npmGlobalPackages:
    *react-native*: Not Found
PS C:\Projects\RNVProblem>
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Try running a release build of https://github.com/ryfow/RNVProblem on Windows

## Expected Results
I expect a screen to render and some audio to play when the app runs.

Instead, I see a white screen, hear no audio, and see this exception in the debugger when all C++ exceptions break.

<img width="1730" alt="image" src="https://user-images.githubusercontent.com/717985/119736687-5696bf80-be3b-11eb-9ca0-5d3146c2b567.png">

## Snack, code example, screenshot, or link to a repository:
https://github.com/ryfow/RNVProblem

**Comment by asklar** [comment]
could be because the module is accessing ui stuff from the js thread?
cc @vmoroz

**Comment by chrisglein** [comment]
Error appears to be in JavaScript, so the native stack isn't as useful.

@jonthysell are there any known/unpublished issues with react-native-video here?

**Comment by chrisglein** [comment]
@ryfow Can you try running this in debug but while disabling web debugging? One hypothesis is that's the difference here, and you'd get more context in debug.

**Comment by ryfow** [comment]
I get this when the app reloads after turning debug off. Is there a way to start with debug off?

<img width="774" alt="image" src="https://user-images.githubusercontent.com/717985/119894565-fa46a500-bef9-11eb-8384-26b262d72d02.png">

**Comment by acoates-ms** [comment]
Yup, this is a bug in `react-native-video`.

https://github.com/react-native-video/react-native-video/blob/1eb11ce7b7619a04e65affedcb1ffff4f82f0af3/Video.js#L257
They should be importing `UIManager` from `react-native`, not accessing it from `NativeModules.UIManager`.

It looks like there is already a PR open to do this:
https://github.com/react-native-video/react-native-video/pull/2296

**Comment by ryfow** [comment]
That PR commit appears to have the same problem in Release build and gives me a new error in debug mode, slightly different depending on whether remote debugging in on.

Debugging on:
<img width="509" alt="image" src="https://user-images.githubusercontent.com/717985/119898323-ee111680-befe-11eb-8fc2-bf726a098b15.png">

Debugging off:
<img width="489" alt="image" src="https://user-images.githubusercontent.com/717985/119898388-04b76d80-beff-11eb-9055-5bc22919bda7.png">

**Comment by ryfow** [comment]
Oh, the other thing I noticed when staring at the VS debugger yesterday is that the call stack shows things are blowing up under JSIExecutor::callFunction where moduleId = "RCTEventEmitter" and methodId = "receiveTouches".

**Comment by KarkaLT** [comment]
I have exactly the same issue, have you found a workaround?

**Comment by ryfow** [comment]
I'm only using audio so I don't know if this would work for you, but I ended up hacking out the scaling stuff.

https://github.com/ryfow/react-native-video/commit/cb7573ff0dca10479d75977aa339a77fe1f39bed

**Comment by jonthysell** [comment]
Looking at their repo, react-native-video is looking for an active maintainer: https://github.com/react-native-video/react-native-video/issues/2343

**Comment by Yaxian** [comment]
> Yup, this is a bug in `react-native-video`.
> 
> https://github.com/react-native-video/react-native-video/blob/1eb11ce7b7619a04e65affedcb1ffff4f82f0af3/Video.js#L257 They should be importing `UIManager` from `react-native`, not accessing it from `NativeModules.UIManager`.
> 
> It looks like there is already a PR open to do this: [react-native-video/react-native-video#2296](https://github.com/react-native-video/react-native-video/pull/2296)

It works for me

**Comment by cjhines** [comment]
This is happening again for me again in `6.0.0-alpha.3`. Anyone else experiencing it?

**Comment by chiaramooney** [comment]
Please file issue on the react-native-video repository instead.
