### ISSUE TITLE
Errors using PNPM

### ISSUE THREAD

**Issue by br4in3x** [microsoft/react-native-windows#7888]
## Environment
1. `npx react-native --version`: `5.0.1-alpha.2`
2. `npx react-native info`:

```
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 3.54 GB / 15.79 GB
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      Versions: 10.0.16299.0, 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7199119
    Visual Studio: 16.9.31313.79 (Visual Studio Community 2019), 16.9.31313.79 (Visual Studio Enterprise 2019)
  Languages:
    Java: 15.0.1
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.64.1 => 0.64.1
    react-native-windows: 0.64.6 => 0.64.6
  npmGlobalPackages:
    *react-native*: Not Found
```

What SDK version are you building for? Choose from 10.0.15063, 10.0.16299, 10.0.18362, etc.
- Target Platform Version(s): `10.0.16299`
What device(s) are you targeting? Choose any from Desktop, Xbox, Hololens)
- Target Device(s): `Desktop`
Which version of Visual Studio are you using? Specify Visual Studio 2017 or Visual Studio 2019
- Visual Studio Version: `Visual Studio 2019`
Which build configuration are you running? Choose from Debug, DebugBundle, Release, ReleaseBundle 
- Build Configuration: `Debug`

## Steps To Reproduce
This issue is hard to reproduce because it's intermittent. It appeared several times on my system and is consistent on my colleague's system, but I'll provide as much info as I can.

I believe it is related to the long path support, and for some reason happens only sometimes. In our organization, we are using `@microsoft/rush` with `pnpm` as a package manager, the RN application is located in the `/apps` directory in the repo. When I'm trying to run the app, sometimes it gives errors like this:

```
C:\Program Files\dotnet\sdk\5.0.203\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(159,5): error MSB3491: Could not write lines to file "obj\x64\Debug\netcoreapp3.1\win-x64\Microsoft.ReactNative.Managed.CodeGen.AssemblyInfoInputs.cache". Could not find a part of the path 'C:\Users\Max\Code\HP\w2\common\temp\node_modules\.pnpm\@veneer+native@2.1.0_@babel+preset-env@7.13.15\node_modules\react-native-windows\Microsoft.ReactNative.Managed.CodeGen\obj\x64\Debug\netcoreapp3.1\win-x64\Microsoft.ReactNative.Managed.CodeGen.AssemblyInfoInputs.cache'.
```

The path is so long because `@microsoft/rush` creates symlinks. If I'm using `yarn`, this problem never appears because yarn doesn't create any symlinks, therefore the paths are shorter. But using `yarn` is hard with `@microsoft/rush` because it's experimental and sometimes doesn't work, and it's way slower than pnpm (takes about 10-15 minutes to finish installation for all packages in monorepo vs 2 minutes for pnpm).

Also, this issue is not happening if I move the whole repo to the root folder of the drive. And it's because the path of the place where the repo is located is not longer than 260 symbols. But when it's in my home directory, or for some reason the path is longer than 260 symbols, this error appears, because the path below is longer than 260 symbols (273 to be exact).
```
C:\Users\Max\Code\HP\w2\common\temp\node_modules\.pnpm\@veneer+native@2.1.0_@babel+preset-env@7.13.15\node_modules\react-native-windows\Microsoft.ReactNative.Managed.CodeGen\obj\x64\Debug\netcoreapp3.1\win-x64\Microsoft.ReactNative.Managed.CodeGen.AssemblyInfoInputs.cache
```

Long paths support is enabled on my system (output of [rnw-dependencies.ps1](https://github.com/microsoft/react-native-windows/blob/main/vnext/Scripts/rnw-dependencies.ps1) is below):
![image](https://user-images.githubusercontent.com/1525725/120047783-7668e780-bfe3-11eb-857f-2966cc0964e1.png)

## Expected Results
There are no issues related to the length of the path during VS builds.

Full build log:

https://gist.github.com/br4in3x/aaa8567d77938c787a073595020784d6

**Comment by asklar** [comment]
for a Windows program to work with long paths 2 things have to happen:
- system-wide setting is enabled (which it is, according to the screenshot you posted)
- the program must have an entry in its manifest saying that the app supports long paths

It sounds like msbuild is not manifested correctly. This sounds vaguely familiar, I believe @dannyvv had investigated this and found there was a bug in msbuild that had been fixed "the wrong way" but I forget if we ever founda way to work around it:
https://github.com/dotnet/msbuild/issues/53

**Comment by br4in3x** [comment]
Thank you @asklar, seems like https://github.com/dotnet/msbuild/issues/53#issuecomment-459062618 should be the solution. I'll try it out again when this issue appears, and reopen if it doesn't help.
