### ISSUE TITLE
Revert #7865 Before RNW 0.65 Release

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#7893]
https://github.com/microsoft/react-native-windows/pull/7865 patches over the community CLI to mitigate an issue that will be fixed in the upstream 0.65 RC. We should revert that PR once we are using an RC instead of current nightly build.

**Comment by asklar** [comment]
Currently using Nightly builds of RN as we were doing an experiment, should remove it before we ship 0.65 release.
