### ISSUE TITLE
Don't compile WinRTWebSocketResource in Release to save on disk footprint

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#7899]
@JunielKatarn is any of the WinRTWebSocketResource code used in Release? if not, we might want to `#ifdef DEBUG` it, in case the compiler can't statically decide that it won't be used in Release (and therefore we can get back some disk footprint)

_Originally posted by @asklar in https://github.com/microsoft/react-native-windows/issues/7892#issuecomment-850926370_

**Comment by NickGerleman** [comment]
"WinRTWebSocketResource" is the backend to the current production WebsocketModule. This allows websocket operations from RN application code in JS.

This is used in RN debug infrastructure, but also is regularly used in real-world applications if they rely on long-lived network connections to a service. (E.g. for real-time content updates).

**Comment by JunielKatarn** [comment]
> @JunielKatarn is any of the WinRTWebSocketResource code used in Release? if not, we might want to `#ifdef DEBUG` it, in case the compiler can't statically decide that it won't be used in Release (and therefore we can get back some disk footprint)
> 
> _Originally posted by @asklar in [#7892 (comment)](https://github.com/microsoft/react-native-windows/pull/7892#issuecomment-850926370)_

As @NickGerleman already explained, **YES, VERY MUCH**.
It's a fundamental component for React Native networking.

That said, both the "Resource" and the WebSocket module itself will go through some revisions and potential refinements to slim the classes down, which may impact positively the final object size.
If this happens, I will update this issue accordingly.
