### ISSUE TITLE
Implement ClippedSubviews for Performance Improvement

### ISSUE THREAD

**Issue by erikschlegel** [Microsoft/react-native-windows#79]
Implement the removeclippedsubviews  for the ReactViewManager so UWP apps can benefit from the same performance boost present for Android https://facebook.github.io/react-native/docs/view.html#removeclippedsubviews

**Comment by rozele** [comment]
Also look at #159 as a sub-task.

**Comment by rozele** [comment]
Closing - still should be investigated at some point, but as far as I can tell this is a reasonably buggy feature of react-native on Android.
