### ISSUE TITLE
Failing UTs after lockfile deduplication

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#7903]
It looks like reenabling JS UT parallelism leads to failiure of one of our tests. Going to leave fixing the test failure that slipped in for later.
```
ERR!  FAIL  src/test/sanitize.test.ts
ERR!   √ Sanitize message, no-op (2 ms)
ERR!   √ Sanitize message, project_dir (1 ms)
ERR!   √ Sanitize message, node_modules (1 ms)
ERR!   √ Sanitize message, other path
ERR!   √ Sanitize message, forward slashes (1 ms)
ERR!   √ Sanitize message, file share path
ERR!   √ Sanitize message, with cpu/thread id
ERR!   √ Error code (1 ms)
ERR!   √ Sanitize stack frame (1 ms)
ERR!   √ basic setup (2 ms)
ERR!   × thrown exception a->b, hello world (39 ms)
ERR!   √ throw exception with error code (19 ms)
ERR!   × thrown exception a->b, hello path (8 ms)
ERR!   √ trackEvent should not identify roleInstance (1 ms)
ERR!   √ No message (1 ms)
ERR! 
ERR!   ● thrown exception a->b, hello world
ERR! 
ERR!     expect(received).toBeTruthy()
ERR! 
ERR!     Received: false
ERR! 
ERR!       262 |   Telemetry.client!.flush();
ERR!       263 |
ERR!     > 264 |   expect(pass).toBeTruthy();
ERR!           |                ^
ERR!       265 |   Telemetry.client!.clearTelemetryProcessors();
ERR!       266 |   Telemetry.client!.addTelemetryProcessor(sanitizeEnvelope);
ERR!       267 |   done();
ERR! 
ERR!       at Object.<anonymous> (src/test/sanitize.test.ts:264:16)

```

_Originally posted by @NickGerleman in https://github.com/microsoft/react-native-windows/pull/7901#r642135462_

**Comment by NickGerleman** [comment]
Still seeing the failure after reverting the change. Possibly an appsinsights breaking change after yarn deduplication.

**Comment by NickGerleman** [comment]
Tests seem to pass again when I reverted to the pre-duplicated lockfile in https://github.com/microsoft/react-native-windows/pull/7901/commits/9bd1e4ac118bd77515c376dbf5cba8e6666667a7. Seems like we might need to dig deeper and assign a resolution.

**Comment by asklar** [comment]
The command to de-duplicate is `npx yarn-deduplicate`
The failing tests are telemetry tests that rely on the contents of a thrown exception's stack trace.

**Comment by jonthysell** [comment]
I don't think this will meet the bar for 0.66. Marking this as 0.67 just in case.
