### ISSUE TITLE
Following instructions to run playground-win32.sln doesn't launch Playground app

### ISSUE THREAD

**Issue by lyahdav** [microsoft/react-native-windows#7919]
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`: 5.0.1-alpha.2
2. `npx react-native info`:
```
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19041
    CPU: (40) x64 Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz
    Memory: 121.86 GB / 190.60 GB
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.0-20190429.1820 - C:\open\fbsource\xplat\third-party\yarn\yarn.BAT
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
    Watchman: 20210524.090203 - C:\tools\watchman\watchman.EXE
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.17763.0, 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.9.31229.75 (Visual Studio Professional 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- Visual Studio Version: Visual Studio 2019

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Clone repo
2. Follow steps [here](https://github.com/microsoft/react-native-windows/blob/main/docs/building-rnw.md#running-the-playground-app) in the Automatic section to run Playground app, except use playground-win32.sln.

## Expected Results
Expected: Metro and Playground app opens.
Actual: Only Metro opens. As a workaround I open the .sln in VS and run it afterwards. Here are the logs:
```
yarn run v1.17.0-20190429.1820
$ react-native run-windows --sln windows\playground-win32.sln
 √ Auto-linking...
Success: No auto-linking changes necessary. (4823ms)
 √ Found compatible MSBuild at C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin (16.9.31229.75)
 √ Found Solution: C:\Users\lyahdav\Documents\GitRepos\react-native-windows\packages\playground\windows\playground-win32.sln
 i Build configuration: Debug
 i Build platform: x86
 √ Building Solution
 √ Starting the React-Native Server
 √ Enabling Developer Mode
 √ Deploying C:\Users\lyahdav\Documents\GitRepos\react-native-windows\packages\playground\windows\Debug\playground\playground.build.appxrecipe
 √ Verifying loopbackExempt
 √ Starting the app
Done in 362.26s.
```

**Comment by asklar** [comment]
Talked offline, pasting here for posterity.
The instructions are for the "golden path" app type, which is the UWP project, as you've discovered :). The win32 project is not something we expect developers to use (outside of one-off 1:1 engagements like with FB :)) and so we haven't optimized for supporting xaml islands projects in the CLI or template projects (in fact we know the playground-win32 app doesn't do everything the right way wrt how islands are used).

It sounds like you are unblocked though, so putting this in the backlog for now.

**Comment by chiaramooney** [comment]
Closing issue as we migrate to the new architecture. Will not be tackled on Paper.
