### ISSUE TITLE
Add Text.onPressIn|Out

### ISSUE THREAD

**Issue by rectified95** [microsoft/react-native-windows#7954]
https://github.com/facebook/react-native/commit/1d924549cad75912191005c8f68dd73e15b07183 Adds 2 new events to `<Text>` - `onPressin/onPressOut`. We could add them too.

**Comment by rbrishabh** [comment]
hey! I can help with this one!

**Comment by chrisglein** [comment]
@rectified95 Can you confirm whether this is as simple as implementing these props in our view managers and where that code should go? As long as we don't need a native implementation for this it should be straightforward.

**Comment by sourabh112** [comment]
Hi @chrisglein and @rectified95, Can I work on this issue (if no one else is working on it)? And can you please point out the files where I need to make changes?

**Comment by rectified95** [comment]
@sourabh112 I'm assigning this issue to you.
The files that need to be changes would be the .windows.js forks of the Text files you can see in the original RN commit diff in the issue description. For reference, I previously added this to TextInput: https://github.com/microsoft/react-native-windows/pull/6754
One thing to note, though, is that I also added code firing JS events as a way of passing along the native XAML events there - I'm not sure if this is necessary, since there doesn't seem to be analogous code for iOS/Android: in short, you could check if the RN event routing system somehow invokes the in/out versions of Text.onPress, without us having to do that manually.

**Comment by rectified95** [comment]
@sourabh112 Have you made any progress? :)

**Comment by rectified95** [comment]
@rbrishabh Would you still be interested in taking this one over if the current assignee cannot complete the task?

**Comment by jonthysell** [comment]
@TatianaKapos Is this already complete? If not, will it make 0.69, or should it be moved to 0.70?

**Comment by rozele** [comment]
I think we get these "for free" no? Can this be closed?

**Comment by rozele** [comment]
https://github.com/facebook/react-native/pull/34944 will fix

**Comment by rozele** [comment]
It technically works today, but you must also set an `onPress` callback.

**Comment by TatianaKapos** [comment]
Closing as we get these already.
