### ISSUE TITLE
Suggestion: Create a Playground App in the Windows Store

### ISSUE THREAD

**Issue by joewood** [Microsoft/react-native-windows#796]
Similar to the TypeScript playground, or CodePen and JSFiddle - a playground app would:
- Provide an integrated code-editor and see the app running alongside
- Allow to quickly test features and concepts in ReactNative
- Use hot loading to see real-time changes in code
- Integrate File load/save from local disk
- Enhance the editor by embedding Monaco 
- Include a TypeScript mode running the TSServer in-process
- Enhance to include code sharing (like codepen) using a URL to reference uploaded code

**Comment by rozele** [comment]
Sounds similar to http://rnplay.org, which is something we've wanted to see for react-native-windows

**Comment by joewood** [comment]
Yes, exactly - only more reliable and with the option of a local mode. I could imagine something like an officially released Microsoft app but with community contribution.

**Comment by rozele** [comment]
Interesting, could probably be done pretty easily with a WebView pointing at a Gist editor.  Would it only need to support core modules (I think that's the case for RN Playground) or would it need to support third-party native modules?  If it's the latter, it gets difficult because we don't have `react-native link` for Windows yet...

**Comment by joewood** [comment]
Right, just core functionality. The binary container app would be installed from the windows store - so it couldn't be extended with `react-native link` (even if it was available). It would make sense to include a handful of trusted native components (like react-native-vector-icons). It could also serve as a showcase for UWP features.

For the editor - it _could_ be done with external webview. but I think it would be better with an internally hosted HTML resource - I'm sure it should be quite easy to host [Monaco](https://github.com/Microsoft/monaco-editor) in a webview in UWP (although I haven't tried). With that you could offer code completion etc..

It would then be simply a matter of patching in the contents of the local edited files into the JS engine. I could imagine the steps would be:
* Create a Playground UWP app using **react-windows**
* Modify the XAML in the main window so that the ReactWindows target sits alongside an editor window, which could be a TextBox to start with, eventually something like a WebView hosted Monaco.
* Take the output of a simple "Hello World" React bundle and load it as a resource into the UWP app
* Remove the "Hello World" class definition from the bundle, this will be loaded from the editor

When the user clicks "Render" (or on a timer):
* Take the contents of the editor window and apply a simple JSX transform. Eventually this could be a full Babel transform run locally in the UWP app, or a TypeScript transform.
* Patch the result into the Chakra JS context
* Force a re-render

The official UWP React-Native Playground app would be updated for each new release of react-native-windows.  It could become quite interesting with future features like multi-file support, URL based sharing, redux store visualization etc...

**Comment by rozele** [comment]
Alternative suggestion - get Expo working on UWP. Thanks for the suggestion, unfortunately this goes beyond the scope of this repo.
