### ISSUE TITLE
Support HTML printing on react-native-print

### ISSUE THREAD

**Issue by emanuelmartin** [microsoft/react-native-windows#7969]
# Proposal: Support HTML printing on react-native-print

## Summary
It should be great to print from HTML, not only for PDF, on react native windows.

## Motivation
It's crucial to support printing not only PDF, but HTML, since it's the way to print variable content in forms.

**Comment by asklar** [comment]
Duplicate of christopherdro/react-native-print#132

**Comment by asklar** [comment]
See also #7723

**Comment by chrisglein** [comment]
Closing this issue as we have the request covered through the issues above.
