### ISSUE TITLE
Is rn-fetch-blob supported by RNW ? (Confusing documentation)

### ISSUE THREAD

**Issue by thedf** [microsoft/react-native-windows#7970]
Hey there,

I want to know if the library rn-fetch-blob is yet supported by RNW, because in the [Community modules](https://microsoft.github.io/react-native-windows/docs/supported-community-modules#community-modules) section in the docs it says that this library is already supported but I couldn't find the implementation. 

Thanks in advance.

**Comment by thedf** [comment]
Thanks alot @asklar !

**Comment by thedf** [comment]
![Error](https://user-images.githubusercontent.com/30848421/121163875-6f49a100-c84f-11eb-8ade-a2ceb2f29f25.png)
 I am getting these errors when using both the code from the PR or the code from the repo you mentioned. Do you happen to know the source of these errors  or how to fix them?

**Comment by asklar** [comment]
looks like the error screenshot didn't work, can you paste the error text?

**Comment by thedf** [comment]
![Image](https://user-images.githubusercontent.com/30848421/121168659-7c688f00-c853-11eb-9f2f-8ba12fc42278.png)


``` 
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2065	'currentDllHanlde': undeclared identifier	RNFetchBlob	E:\react-native-desktop-gallery\node_modules\react-native-windows\Microsoft.ReactNative.Cxx\JSI\JsiApiContext.cpp	34	
Error	C2065	'currentDllHanlde': undeclared identifier	RNFetchBlob	E:\react-native-desktop-gallery\node_modules\react-native-windows\Microsoft.ReactNative.Cxx\JSI\JsiApiContext.cpp	35	
Error	C2065	'HMODULE': undeclared identifier	RNFetchBlob	E:\react-native-desktop-gallery\node_modules\react-native-windows\Microsoft.ReactNative.Cxx\JSI\JsiApiContext.cpp	34	
Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int	RNFetchBlob	E:\react-native-desktop-gallery\node_modules\react-native-windows\Microsoft.ReactNative.Cxx\JSI\JsiApiContext.cpp	9	
Error		PRI175: 0x80070002 - Processing Resources failed with error: The system cannot find the file specified.	bymegallery	E:\react-native-desktop-gallery\windows\bymegallery\GENERATEPROJECTPRIFILE	1	
Error		PRI252: 0xdef00071 - File E:\react-native-desktop-gallery\windows\Debug\RNFetchBlob\RNFetchBlob.pri not found.	bymegallery	E:\react-native-desktop-gallery\windows\bymegallery\GENERATEPROJECTPRIFILE	1	
Error	C2061	syntax error: identifier 'HMODULE'	RNFetchBlob	E:\react-native-desktop-gallery\node_modules\react-native-windows\Microsoft.ReactNative.Cxx\JSI\JsiApiContext.cpp	34	
Error	C2146	syntax error: missing ';' before identifier 'currentDllHanlde'	RNFetchBlob	E:\react-native-desktop-gallery\node_modules\react-native-windows\Microsoft.ReactNative.Cxx\JSI\JsiApiContext.cpp	34	
Error	C2146	syntax error: missing ';' before identifier '__ImageBase'	RNFetchBlob	E:\react-native-desktop-gallery\node_modules\react-native-windows\Microsoft.ReactNative.Cxx\JSI\JsiApiContext.cpp	9	

``` 

There seems to be a problem with my internet and github. here is the text version

**Comment by asklar** [comment]
please add a `#include <windows.h>` to your app's `pch.h`

**Comment by thedf** [comment]
I do have it already

**Comment by asklar** [comment]
make sure the module's pch.h has it too

**Comment by thedf** [comment]
including the library in pch.h of the module fixes the problem. Thanks a lot !
It should probably be added to the original repo and PR so it won't happen to other people.

**Comment by asklar** [comment]
filed https://github.com/RonRadtke/react-native-blob-util/issues/43

**Comment by thedf** [comment]
You are amazing @asklar !
