### ISSUE TITLE
backfaceVisibility style prop not functional for Image component

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-windows#8001]
# Proposal: backfaceVisibility style prop not functional for Image component

## Summary
backfaceVisibility is the property defines whether or not the back face of a rotated image should be visible. In RNW, if an image is rendered with 180 degree rotation in the y-axis and "hidden" as the value set for the backfaceVisibility prop, the image is still shown. Instead, the image should not render. 

## Motivation
Style prop API completion

**Comment by chrisglein** [comment]
Related to #3538
Does Image use the same view prop, or does it provide its own? From the documentation at least it may define its own. But the fix is probably the same. Good discussion to look at in the other issue.

**Comment by chrisglein** [comment]
Not something we plan to address on the Paper renderer as we move towards Fabric.
Fabric API completion for `Image` tracked here: https://github.com/microsoft/react-native-windows/issues/11144
This specific one should be fixed now for Fabric #11334
