### ISSUE TITLE
Add timestamp to onKeyUp / onKeyDown events

### ISSUE THREAD

**Issue by rozele** [microsoft/react-native-windows#8004]
# Proposal: Add timestamp to onKeyUp / onKeyDown events

## Summary
We have timestamps for `onTouch[Start|Move|End|Cancel]`, but we do not have any timestamps for keyboard events. We should add these.

## Motivation

We are capturing performance markers to detect the E2E latency from the time something is "pressed" to the time something renders. While we can achieve this using the native event `timestamp` for `onTouch*` events, we don't have anything analogous for keyboard events.

## Basic example

```js
<View onKeyDown={(e) => /* do something with e.nativeEvent.timestamp */ } />|
```

## Open Questions

For pointer events, we get the system uptime timestamp from `PointerRoutedEventArgs::GetCurrentPoint(...).Timestamp`. There isn't a native corollary for `KeyRoutedEventArgs`, so we'd have to create our own, which may be off slightly because the time XAML processes the event is slightly delayed from the time the key event occurred.

**Comment by chrisglein** [comment]
If `onTouch` events include this then having `onKeyUp` and friends contain the same makes sense. Is the set of args here documented on reactnative.dev at all?

**Comment by rozele** [comment]
@chrisglein This is the only documentation I'm aware of: https://reactnative.dev/docs/pressevent#timestamp
