### ISSUE TITLE
How to fire a ReactEvent without a directly call from JS side

### ISSUE THREAD

**Issue by Samuubs** [microsoft/react-native-windows#8005]
Hello, I'm trying to figure out how to call a `ReactEvent` from a static method in C#. Actually I have a ReactModule that have a `ReactEvent` called `handleLogging` and a method called `Debug`: 

```csharp
[ReactModule]
class LoggingModule
{
    [ReactEvent("handleLogging")]
    public Action<JSValue> HandleLogging { get; set; }

    [ReactMethod("debug")]
    public void Debug(string extension, string msg)
    {
      JSValueObject obj = GetLogData(extension, "DEBUG", msg);
      HandleLogging(obj);
    }
}
```
In the original docs for [ReactEvent](https://microsoft.github.io/react-native-windows/docs/native-modules#1-authoring-your-native-module-1), we need to have a call from [JS side first](https://microsoft.github.io/react-native-windows/docs/native-modules#1-authoring-your-native-module-1) to have a ReactEvent being fired. 

But, my case is little different. I need to call a ReactEvent without a directly  call from JS side. In first moment my RNW App will register into `handleLogging` event. And will call a function inside a second project used as reference in my main RNW APP. Like this: 

```csharp
[ReactModule("PolicyModule")]
class PolicyModule
{
     [ReactMethod("isEmbargo")]
     public async void IsEmbargo(int timeout, ReactPromise<JSValue> promise)
     {
         try
         {
            string token = EmbargoTokenGetter.Get();
            Logging.Logging.Debug("myHP", "testMSG");
            promise.Resolve(await PolicySDK.IsEmbargo(token, timeout));
         }
         catch (Exception e)
         {
           ReactModuleTools.Reject("PolicyModule.IsEmbargo error", e, promise);
         }
     }
 }
```

```ts
function onLoggingEventHandler(logData) {
  console.log(logData);
} 

const LoggingEventEmitter = new NativeEventEmitter(LoggingModule);
LoggingEventEmitter.addListener("handleLogging", onLoggingEventHandler);

useEffect(() => {
    isEmbargo(2)
      .then((res: boolean) => {
        setEmbargo(res);
      })
      .catch((err: string) => {
        setError(err);
      });
}, []);
```

So, this the method called in PolicyModule class. Basically, its just a call from a LoggingModule to fire the HandleLogging event as I said in first moment.
```csharp
public sealed class Logging
{
    private static LoggingModule loggingModule = new LoggingModule();

    public static void Debug (string extension, string msg)
    {
       loggingModule.Debug("myHP", "test");
    }
}
```

But, I am getting a NullReferenceException on handleLogging event: 
![image](https://user-images.githubusercontent.com/33751384/121579551-31d94500-ca02-11eb-9717-a4ee5da1b124.png)

How I can fix this? This is actually possible to do? There's another approach?
Thanks in advance :)

My react-native and react-native-windows versions:
"react-native-windows": "0.64.6",
"react-native": "0.64.1"

**Comment by asklar** [comment]
Just to confirm, is the LoggingModule marked with [ReactModule] etc?
I don't think it's legal to create a new instance of LoggingModule, which will be separate from the instance that React Native sees. This new instance will not have its ReactContext set, which is probably why you're getting a crash.

One idea would be to have the LoggingModule constructor set the singleton member. Even better, you should instead use the ReactPropertyBag to set the just-created LoggingModule as an object in the property bag. Then your singleton getter can grab the instance from the ReactContext's property bag.

**Comment by asklar** [comment]
See this doc about using `ReactContext`: https://microsoft.github.io/react-native-windows/docs/native-modules-advanced#c-native-modules-with-initializer-and-as-a-way-to-access-reactcontext

**Comment by Samuubs** [comment]
Thank you so much @asklar! This works very well! You are great :thumbsup:

Also, here is my solution: 

I created a ReactPropertyBag helper like I saw in [this issue](https://github.com/microsoft/react-native-windows/issues/6278):
```csharp
    class ReactPropertyBagLoggingHelper
    {
        private static IReactPropertyNamespace MyNamespace = ReactPropertyBagHelper.GetNamespace("LoggingModule");
        private static IReactPropertyName MetricsModuleName = ReactPropertyBagHelper.GetName(MyNamespace, "LoggingModule");

        public static void SetMetricsModule(IReactContext reactContext, LoggingModule myModule)
        {
            reactContext.Properties.Set(MetricsModuleName, myModule);
        }

        public static LoggingModule GetMetricsModule(IReactContext reactContext)
        {
            return (LoggingModule)reactContext.Properties.Get(MetricsModuleName);
        }
    }
```

And for LoggigModule I did the singleton idea like this:
```csharp
    [ReactModule]
    class LoggingModule
    {
        private static LoggingModule instance;
        private static ReactContext m_reactContext;

        [ReactInitializer]
        public void Initialize(ReactContext reactContext)
        {
            m_reactContext = reactContext;
            ReactPropertyBagLoggingHelper.SetMetricsModule(reactContext.Handle, this);
        }

        public static LoggingModule Instance
        {
            get
            {
                if (instance == null)
                {
                    instance = ReactPropertyBagLoggingHelper.GetMetricsModule(m_reactContext.Handle);
                }
                return instance;
            }
        }
    }
```
I'm closing this issue. 
Thank you again! Have a good day :smiley:

**Comment by SurajMDurgad** [comment]
> Thank you so much @asklar! This works very well! You are great 👍
> 
> Also, here is my solution:
> 
> I created a ReactPropertyBag helper like I saw in [this issue](https://github.com/microsoft/react-native-windows/issues/6278):
> 
> ```cs
>     class ReactPropertyBagLoggingHelper
>     {
>         private static IReactPropertyNamespace MyNamespace = ReactPropertyBagHelper.GetNamespace("LoggingModule");
>         private static IReactPropertyName MetricsModuleName = ReactPropertyBagHelper.GetName(MyNamespace, "LoggingModule");
> 
>         public static void SetMetricsModule(IReactContext reactContext, LoggingModule myModule)
>         {
>             reactContext.Properties.Set(MetricsModuleName, myModule);
>         }
> 
>         public static LoggingModule GetMetricsModule(IReactContext reactContext)
>         {
>             return (LoggingModule)reactContext.Properties.Get(MetricsModuleName);
>         }
>     }
> ```
> 
> And for LoggigModule I did the singleton idea like this:
> 
> ```cs
>     [ReactModule]
>     class LoggingModule
>     {
>         private static LoggingModule instance;
>         private static ReactContext m_reactContext;
> 
>         [ReactInitializer]
>         public void Initialize(ReactContext reactContext)
>         {
>             m_reactContext = reactContext;
>             ReactPropertyBagLoggingHelper.SetMetricsModule(reactContext.Handle, this);
>         }
> 
>         public static LoggingModule Instance
>         {
>             get
>             {
>                 if (instance == null)
>                 {
>                     instance = ReactPropertyBagLoggingHelper.GetMetricsModule(m_reactContext.Handle);
>                 }
>                 return instance;
>             }
>         }
>     }
> ```
> 
> I'm closing this issue.
> Thank you again! Have a good day 😃

How do you call the debug fuction? @Samuubs
