### ISSUE TITLE
TextInput autoCapitalize="characters" not working

### ISSUE THREAD

**Issue by kcfgl** [Microsoft/react-native-windows#801]
I'm hoping this is a simple one.  I'm trying to set the autoCapitalize on a text input to "characters" but it is not having any impact - on ARM device or on desktop.  I tried "words" as well, no impact.

Other props like keyboardType are working. 

Still on 0.32 but it looks like there haven't been any major changes (aside from new styles) to TextInput in the last couple months.

Thanks.

**Comment by rozele** [comment]
@kcfgl That prop is not exposed for the UWP TextBox unfortunately.  In UWP, the decision to autocapitalize the first word of the sentence is controlled by the InputScope, which also determines the keyboard type.  So, to get automatic capitalization of sentences, you have to have `autoCorrect` set to true and a keyboard associated with one of the InputScopes where this is supported: https://msdn.microsoft.com/en-us/library/windows/apps/mt280229.aspx

**Comment by kcfgl** [comment]
Ah, ok. Looking through the component source it looked like it was available for any. I'll take a look at the link. Thanks for the info!
