### ISSUE TITLE
backgroundColor Style prop for Image does not display background color

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-windows#8011]
# Proposal: backgroundColor Style prop for Image does not display background color

## Summary
The backgroundColor style prop should fill in the empty space of the Image view not occupied by the image itself with the specified color. For RNW, the empty space is left blank. 

## Motivation
Style Prop API Completion

**Comment by chrisglein** [comment]
Not something we plan to address on the Paper renderer as we move towards Fabric.
Fabric API completion for `Image` tracked here: https://github.com/microsoft/react-native-windows/issues/11144
I've confirmed that this functionality works on Fabric.
