### ISSUE TITLE
letterSpacing Text style prop is not functional

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-windows#8013]
# Proposal: letterSpacing Text style prop is not functional

## Summary
letterSpacing Test style prop should increase or decrease the spacing between characters. In RNW specifying with prop with any number results in no change in the rendered text. 

## Motivation
Text Style prop API Completion

**Comment by asklar** [comment]
If we are able to get an ITextRange, we should be able to implement this via `textRange.CharacterFormat.Spacing`. See https://docs.microsoft.com/en-us/uwp/api/windows.ui.text.itextcharacterformat.spacing?view=winrt-20348

**Comment by chrisglein** [comment]
If this is only supported for rich text we'd need some way to switch from plain ole text to rich text depending on which APIs you use.

**Comment by chrisglein** [comment]
Not something we plan to address on the Paper renderer as we move towards Fabric.
Fabric API completion for `Text` is tracked here: https://github.com/microsoft/react-native-windows/issues/11143
