### ISSUE TITLE
How to properly set up RNW app in a Packaging project?

### ISSUE THREAD

**Issue by br4in3x** [microsoft/react-native-windows#8014]
Environment info:

<details>
  <summary>npx react-native --version</summary>

   ```
   5.0.1
   ```
</details>

<details>
  <summary>npx react-native run-windows --info</summary>

   ```
   System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
    Memory: 17.87 GB / 31.88 GB
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 16.13.1 => 16.13.1
    react-native: 0.64.1 => 0.64.1
    react-native-windows: 0.64.6 => 0.64.6
  Installed UWP SDKs:
    10.0.14393.0
    10.0.16299.0
    10.0.17763.0
    10.0.18362.0
    10.0.19041.0
   ```
</details>

In our organization, we are building an RNW app with Win32 capabilities in order to access some hardware information, and registry keys, that are included with the operating system during manufacturing process.

In order to access Win32 APIs, we are using a Packaging Project, that consists of RNW app and a DesktopExtension project, which is a Win32 Windows Application that runs as a Full Trust process. RNW app communicates with this Win32 process via `AppServiceConnection` protocol.

Until recent time this scheme worked, however, something broke recently, and now some people on our team (including myself) are getting this error after the app is built and running:
```
System.IO.FileLoadException: 'Could not load file or assembly 'System.Collections.Concurrent, Version=4.0.14.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
```

![121606187-8977b080-ca02-11eb-88c2-475f261bb853](https://user-images.githubusercontent.com/1525725/121758794-cbbef180-cad7-11eb-8e8b-463b34ea0be7.png)

But, if `DesktopExtension` project is removed from the Packaging Project, the RNW app starts with no problems. After some digging, I think this may be related to mismatching versions of some libraries. Unfortunately, I can't tell what's really going wrong from here - my Windows / Visual Studio build process knowledge is still limited (learning every day!).

One small remark: originally we were getting another error related to `SolutionPath` resolving to `*Undefined*` in the `Autolink.props` file. Not sure if it's realted, but it seems to resolved after adding a Directory.Build.props file in the folder with RNW app solution file:
```xml
<Project>
 <PropertyGroup>
    <SolutionPath>$(MSBuildThisFileDirectory)</SolutionPath>
 </PropertyGroup>
</Project>
```

Could you please help us to resolve `System.Collections.Concurrent` problem?

**Comment by asklar** [comment]
@br4in3x can you please add your environment info?

FYI @dannyvv and @rainersigwald for the *Undefined* problem, since we saw this elsewhere (Danny did you get a chance to port the fix to 64/65/main?). We had another internal team that ran into this as well, so it seems something changed in vs16.10.

**Comment by br4in3x** [comment]
@asklar I updated the original post with the environment information.

**Comment by asklar** [comment]
Can you confirm:
- What version of VS ?
- What version of the UWP NuGet package your C# app is using
- Does the problem reproduce in Debug too (with .net native disabled)?

If the problem goes away when using Debug then that means the .net native targets are not using the right version. See:

- https://devblogs.microsoft.com/oldnewthing/20200615-00/?p=103868/
- https://docs.microsoft.com/en-us/windows/uwp/csharp-winrt/create-windows-runtime-component-cswinrt

**Comment by asklar** [comment]
If that's the case you probably need this PR: https://github.com/microsoft/react-native-windows/pull/7860
Try upgrading to the latest 0.64 which should have that fix.

**Comment by br4in3x** [comment]
@asklar, here is the additional info you asked for:

> What version of VS?
```
Microsoft Visual Studio Enterprise 2019
Version 16.10.0
VisualStudio.16.Release/16.10.0+31321.278
Microsoft .NET Framework
Version 4.8.03752
```

> What version of the UWP NuGet package your C# app is using?

Here are all NuGets installed into the C# app:
![image](https://user-images.githubusercontent.com/1525725/121748349-a58c5800-cabd-11eb-873e-7550a9cd43d7.png)

Seems like the version of UWP NuGet is 6.2.9

> Does the problem reproduce in Debug too (with .net native disabled)?

If you mean "Debug" configuration, then yes, I actually haven't tried running this app in the release mode.

**Comment by asklar** [comment]
@br4in3x can you upgrade the nuget to 6.2.12

**Comment by br4in3x** [comment]
@asklar done, the result is the same, unfortunately

![image](https://user-images.githubusercontent.com/1525725/121758734-7da9ee00-cad7-11eb-9273-cd8b71f2d018.png)

**Comment by asklar** [comment]
hm well that was worth a try :) 

We don't really have the ability to support custom projects (like win32/packaging projects) at the moment so my suggestion would be to file an issue through Visual Studio in the Developer Community forum and get it through the VS pipeline.
@svetBonev fyi in case this rings a bell.

**Comment by br4in3x** [comment]
@asklar thanks anyway. In this case, closing this issue to file an issue on VS Developer Community forum.
