### ISSUE TITLE
Verify that accessibilityState prop in works in Slider

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-windows#8020]
# Proposal: Verify that accessibilityState prop in works in Slider, if not implement it

## Summary
Facebook added the accessibilityState prop for the Slider component to announce "selected" on accessibilityState = {selected: true}. https://github.com/facebook/react-native/commit/35dd86180ba730425b97592ef6e5c4d449caee06

## Motivation
Match functionality of react-native core.

**Comment by chrisglein** [comment]
I thought Slider was lean core'd out... but this is a recent change. So... let's figure out what's going on here?

**Comment by rectified95** [comment]
FB have been adding these props across the board incl. for Picker (which they actually still use). RNW never had a remotely functional Slider impl, we only have the comm. mod one.

**Comment by chrisglein** [comment]
Not something we plan to address on the Paper renderer as we move towards Fabric.
And on Slider there's no plan to implement this deprecated component on Fabric.
