### ISSUE TITLE
App that chooses Hermes still ends up loading Chakra too

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#8025]
Playground loads hermes.dll in addition to chakra.dll, which is wasteful (8 MB for x64).
This is because it seems M.RN is not delayloading chakra

**Comment by NickGerleman** [comment]
I remember @tudorms hitting something similar in the win32 dll, and moving Chakra to be delay loaded there. Commits there might give a Jumpstart on any flags or props files.

**Comment by NickGerleman** [comment]
@mganandraj  fixed this.

**Comment by mganandraj** [comment]
This was the PR : https://github.com/microsoft/react-native-windows/commit/69486c0001ddd7a653dc4a600099fa2c5e0cb1fb#diff-cfd11ac11d71667e52b109b130c5952f30c3b9855372c54c0ed7c39bec7fb1c9

It didn't make it into 65
