### ISSUE TITLE
Support FlatList numColumns 

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#8037]
It looks like we don't currently support FlatList's numColumns property. This property could be used to create grid-like layouts.

**Comment by chrisglein** [comment]
Documentation: https://reactnative.dev/docs/flatlist#numcolumns
Given how much FlatList is cross-platform JS, why doesn't this work on Windows? That'd be the first level of investigation.

**Comment by asklar** [comment]
nevermind, this seems to work, the example in RNTester is called FlatList MultiColumn
