### ISSUE TITLE
Add Accessibility Actions on Core Components

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-windows#8043]
# Proposal: Add Accessibility Actions on Core Components

## Summary
Facebook made a recent change to add accessiblity actions on core components (Button, TextInput, Text, and Picker). 
https://github.com/facebook/react-native/commit/44717152cadb18c7aff74e9465fdb70efdb1bf81

We should check if additional configuration needs to be done on the Windows end of things for these new props to be functional. Javascript side may be good to go through overrides; may need native changes to Accessibility module. 
## Motivation

Accessibility API Completion

**Comment by chrisglein** [comment]
Documentation on accessibility actions (previously only on View): https://reactnative.dev/docs/accessibility#accessibility-actions

**Comment by chrisglein** [comment]
Related: #3122

**Comment by chrisglein** [comment]
Not something we plan to address on the Paper renderer as we move towards Fabric.
Fabric API completion for accessibility is tracked here: https://github.com/microsoft/react-native-windows/issues/11898
