### ISSUE TITLE
How to get an installer to react-native-windows app?

### ISSUE THREAD

**Issue by hossamnasser938** [microsoft/react-native-windows#8045]
For 2 days, I'v been searching for how to generate an installer for my react-native-windows app, but unfortunately, I cannot find any resources touching this topic. Instead, I've tried to consider my react-native-windows app as a native windows app, created a setup project inside my react-native-windows app and successfully got an installer to my application. But, the problem is that on installing the app, it runs and it waits for the development server to respond. I tried to bundle JS and then generate the installer again but with no gain. Anyone can guide me on generating something I could send to the client to test my react-native-windows app?

Thanks in advance

**Comment by asklar** [comment]
hey @hossamnasser938 - RNW apps are UWP apps so the installer work is done for you : ) When you build with the CLI, an .appx file is produced which is the installable package. If you want to distribute through the Microsoft Store, you can submit your app. See more info here: https://microsoft.github.io/react-native-windows/docs/native-code#packaging

**Comment by hossamnasser938** [comment]
Thank you @asklar 
Where can I find that .appx file? And can I use this file to install the app on any other machine?

**Comment by hossamnasser938** [comment]
@asklar I’ve tried creat app packages but when I install and run the app, it still expects the metro bundler to be running

**Comment by acoates-ms** [comment]
Debug builds will by default attempt to connect to metro.  Release should build and include the bundle as part of the appx.

**Comment by hossamnasser938** [comment]
thank you @acoates-ms

**Comment by chrisglein** [comment]
Sounds like the main questions have been answered here. Closing this issue.
