### ISSUE TITLE
Older modules cannot be autolinked (e.g. Clipboard, DateTimePicker, Slider)

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-windows#8047]
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`: 5.0.1-alpha.2
2. `npx react-native info`:

info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Memory: 45.79 GB / 63.84 GB
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.3
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7199119
    Visual Studio: 16.9.31328.270 (Visual Studio Enterprise 2019)
  Languages:
    Java: 1.8.0_282
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.0.0-7e05480cc => 0.0.0-7e05480cc
    react-native-windows: 0.65.0-preview.1 => 0.65.0-preview.1
  npmGlobalPackages:
    *react-native*: Not Found

- Target Platform Version(s): 10.0.19041
- Target Device(s): Desktop
- Visual Studio Version: 2019
- Build Configuration: All

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create an RNW app. Issue should repro on any RNW >= 0.63
2. Add the clipboard, datetimepicker, and react-native-picker modules to the app.
3. Run `npx react-native autolink-windows --logging`.
4. Observe that the autolinking script finds all three projects and states that it is adding them to the application.
5. Open AutolinkedNativeModules.g.cpp.  Observe that the three modules are not included in this file. 
6. Edit App.js to use the components from these modules. 
7. Run your app. Observe that the app will throw errors because it is unable to find the modules. 

## Expected Results
All three modules appear in AutolinkedNativeModules.g.cpp. No editing on native code is necessary to successfully use the components. 

## Snack, code example, screenshot, or link to a repository:
See React Native Gallery if you want to easily repro.

**Comment by asklar** [comment]
Those projects were built before we had the "native module" template so they don't have the hints to tell autolinking that they contain a project that is a native module (for cpp, they should have an import of `Microsoft.ReactNative.Uwp.CppLib.targets`).

Either we should update these modules, or we should relax the autolinking logic to allow older format projects.

**Comment by chrisglein** [comment]
How many of these modules do we have? If the number is low it seems better to update the module rather than having to adapt autolinking.

The linked PR attempts a best effort to find a project to link to. If that's not enough we'll need to go touch the modules.
