### ISSUE TITLE
How I can set the default window size?

### ISSUE THREAD

**Issue by Brouilles** [microsoft/react-native-windows#8069]
Hi,
How I can set the default window size? The minimum and maximum size?
Thanks!

**Comment by asklar** [comment]
You'd have to modify the native code of the app that the template generated. In app.xaml.cs / cpp, in the OnLaunched method, you can set the [`ApplicationView.PreferredLaunchViewSize`](https://docs.microsoft.com/en-us/uwp/api/windows.ui.viewmanagement.applicationview.preferredlaunchviewsize?view=winrt-20348) property.

**Comment by Brouilles** [comment]
Thanks. I try to modify the xaml but don't found a window tag. I don't know why but I have not thinking to modify directly with C# or C++.

**Comment by AstrOOnauta** [comment]
Hey, any solution here?
