### ISSUE TITLE
Compiler flags "throw" statements in JsiAbiApi.cpp as unreachable code in release builds

### ISSUE THREAD

**Issue by aschultz** [microsoft/react-native-windows#8087]
## Environment
react-native 0.64.2
react-native-windows 0.64.11
Visual Studio 2019 (16.10.2)
Build Architecture: x64
Build Configuration: Release

App configured with Warning Level 4 and TreatWarningsAsErrors.

## Issue
Many of the try/catch statements in `JsiAbiApp.cpp` look like:

```
catch(...)
{
    RethrowJsiError();
    throw;
}
```

In debug builds, the code as written compiles fine. In release, it fails with C4702 unreachable code on the "throw" line.

Removing the `throw;` statement fixes release builds, but causes debug builds to fail.

## Expected result
Debug and release builds issue no warnings for this code.

## Suggested Solution
Unfortunately disabling 4702 cannot be done at the statement level (i.e. wrapping just the catch code), so it either needs to be disabled across the whole file or for each function that triggers this.

**Comment by asklar** [comment]
CC @vmoroz

**Comment by dannyvv** [comment]
Since @vmoroz is out of office at the moment, I'll sign off and will send him a mail as a reminder. I think the fix is acceptable.
