### ISSUE TITLE
TextInput onSelectionChange event never suppressed

### ISSUE THREAD

**Issue by rozele** [microsoft/react-native-windows#8094]
There is a test to see if we're currently updating props to suppress events (e.g., onSelectionChange) from being emitted:
https://github.com/microsoft/react-native-windows/blob/93a7118960e7c2a9743580239c10efe9cfb8c731/vnext/Microsoft.ReactNative/Views/TextInputViewManager.cpp#L290

This test will always be false because `SelectionChanged` does not fire synchronously with setting SelectionStart, SelectionLength or calling the imperative Select method.

 ## Expected Results
When the selection change is a result of a prop change from JS, we should not emit an event.

**Comment by asklar** [comment]
CC @rectified95 is this on your radar?

**Comment by chrisglein** [comment]
Not something we plan to address on the Paper renderer as we move towards Fabric.
Fabric implementation has a different implementation of `TextInput` and will be evaluated fresh.
