### ISSUE TITLE
Use the same JavaScript engine in Debug and Release

### ISSUE THREAD

**Issue by jaimecbernardo** [microsoft/react-native-windows#8102]
When porting native modules to react-native-windows, one of the issues developers face is the differences between building for Debug and Release in an application's default configuration.

The fact that different engines are used these means that there is some JavaScript code that runs on iOS and Android and even Windows on Debug but then fails on Windows on Release.

Examples of issues:
- `Object.fromEntries` is not supported in ChakraCore: https://github.com/react-native-device-info/react-native-device-info/pull/1110
- react-native-windows 0.64 breaking previously working JavaScript code on Release: https://github.com/microsoft/react-native-windows/issues/7537
- Using the WebDebugger doesn't allow making synchronous native function calls, which some modules use.

From a development point of view, these changes are at their worse when a developer is developing an application in Debug and then tries out some Release builds closer to shipping and is met with a blank screen, which is hard to debug to pinpoint which code might be causing it. It'd be good if these cases were easier to debug as well.

**Comment by asklar** [comment]
Eventually RN will move away from web debugging and onto direct debugging by default, which should take care of the disparity between debug/release. This likely requires Hermes to be fully supported #6137

**Comment by chrisglein** [comment]
This is now the default experience in RNW 0.74, as we default to direct debugging and web debugging is deprecated.
@TatianaKapos @jonthysell FYI
