### ISSUE TITLE
Release builds of Reunion apps should bundle

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#8116]
We need to figure out how to embed the js bundle as a resource (build work) and use it via MRTCore (framework code) so that Release builds of Reunion apps can work properly.

**Comment by chrisglein** [comment]
Notes from planning poker

> No language differences, but yes differences from UWP to WinAppSDK (resources mechanism is different). What's in PR now only enables debug builds (you need to run the bundler). So this is how you get a release build for WinAppSDK. We can build the .bundle file, but how do we actually load it at startup? MRTCore is the new tech recommended for this (not classic Win32 resources). Needs to understand package vs. unpackaged if we support both. Will be changes in the framework, CLI, and build system. There are some buried assumptions about UWP that will time some time to unearth.
A fair number of unknowns here adding question on the 13-20 range.

**Comment by jonthysell** [comment]
@AgneLukoseviciute Is this already complete? If not, will it make 0.69, or should it be moved to 0.70?
