### ISSUE TITLE
Support for C++ WinAppSDK apps (CLI template)

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#8132]
Current plan is to start with C#, so filing this to add a C++/WinRT Reunion template in the future

**Comment by chrisglein** [comment]
We should start organizing this work into a project board so it's clear where to track progress on Windows App SDK support.

**Comment by chrisglein** [comment]
Notes from planning poker:

> Install WinAppSDK, open a new project, and get RNW loading into that. Then reverse engineer the project template from that. From learnings on doing this for C#, can be 1-2 weeks. Will need to navigate PackageReference. C# had breaks due to the preview versions that we won't have to deal with here. How many #ifWinUI3 checks to we have to keep and maintain? There are many of these in aggregate that add cost.

**Comment by jonthysell** [comment]
@AgneLukoseviciute Do you think this will make 0.69 or should it be moved to 0.70?

**Comment by AgneLukoseviciute** [comment]
update: since we're moving in the direction of using NuGets instead of source, we'll want to create and publish a cpp WinAppSDK nuget -- aka Microsoft.ReactNative build with USE_WINUI3 defined. Next step here is to get a working NuGet generated (test through sample app).

**Comment by chrisglein** [comment]
Back in late 2021 / early 2022 we started a WinAppSDK new app template based on understanding of WinAppSDK at the time. And then came [Fabric](https://github.com/microsoft/react-native-windows/issues/12042) and impact on our overall strategy for how to handle Win32/WinAppSDK. As such these original plans don't make as much sense and we'll be closing them as Not Planned. That's not in any way to say RNW isn't going to support WinAppSDK, we're just doing it differently! Track our [Fabric](https://github.com/microsoft/react-native-windows/issues/12042) progress for details on the new app template and how that'll be compatible with WinAppSDK.
