### ISSUE TITLE
Remove WinUI 3 preview support from UWP templates and CLI

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#8133]
Plan forward is to support UWP and Windows App SDK (and their corresponding app templates) so we can remove the UWP WinUI 3 template which Windows App SDK doesn't support yet.

**Comment by chrisglein** [comment]
There are some customers that may need the UWP WinUI3 preview support in the meantime. Let's give them some space to experiment with this option for awhile before we remove it. But long term we don't want to support these preview binaries and we'll want to move onto the ongoing Windows App SDK releases.
