### ISSUE TITLE
`npx react-native run-windows` is failing

### ISSUE THREAD

**Issue by itsarnavsingh** [microsoft/react-native-windows#8140]
## Environment

react-native version: 5.0.1

System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 7.99 GB / 15.85 GB
  Binaries:
    Node: 12.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      Versions: 10.0.17763.0, 10.0.19041.0
  IDEs:
    Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6626763
    Visual Studio: 16.10.31410.357 (Visual Studio Community 2019)
  Languages:
    Java: 1.8.0_275 - C:\Program Files\OpenJDK\openjdk-8u275-b01\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.2 => 0.64.2
    react-native-windows: ^0.64.0-0 => 0.64.12
  npmGlobalPackages:
    *react-native*: Not Found

- Target Platform Version(s): 10.0.16299

- Target Device(s): Desktop

- Visual Studio Version: 2019

## Expected Results
A running windows application

##Build Failure error 

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.Cpp.WindowsSDK.targets(46,5): error MSB8036: The Windows SDK 
 version 10.0.18362.0 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking  
the solution and selecting "Retarget solution". [A:\AllProjects\rnWinTesting\node_modules\react-native-windows\Common\Common.vcxproj]

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.Cpp.WindowsSDK.targets(46,5): error MSB8036: The Windows SDK 
 version 10.0.18362.0 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking  
the solution and selecting "Retarget solution". [A:\AllProjects\rnWinTesting\node_modules\react-native-windows\Folly\Folly.vcxproj]

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.Cpp.WindowsSDK.targets(46,5): error MSB8036: The Windows SDK
 version 10.0.18362.0 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking  
the solution and selecting "Retarget solution". [A:\AllProjects\rnWinTesting\node_modules\react-native-windows\JSI\Universal\JSI.Universal.vcxproj]

I even changed the SDK version from /windows/rnWinTesting.sln still it didn't work

**Comment by NickGerleman** [comment]
@itsarnavsingh could you open "Visual Studio Installer" and make sure the listed SDKs in the error message are installed?

**Comment by itsarnavsingh** [comment]
![image](https://user-images.githubusercontent.com/36072753/123840981-a716a680-d92c-11eb-8c47-f560626b48bd.png)

I have installed the latest version that was available: 10.0.17763.0

**Comment by NickGerleman** [comment]
Hmm, I'm not sure why Visual Studio is not listing later versions. Could you try installing the exact version listed in the error from this site? https://developer.microsoft.com/en-us/windows/downloads/sdk-archive/

**Comment by itsarnavsingh** [comment]
sure, but why does changing the SDK version from the solution file not affecting the build version being used.

**Comment by asklar** [comment]
Some RNW features require later SDKs (notably, animations). You can target an app to a lower OS release, but you still have to use a newer SDK to build it, so that the SDK headers can define the newer APIs (we will just not call them on older OSs).

It's super weird that VS isn't showing you any newer SDK versions though... @BenJKuhn @SvetBonev any idea why that might happen? Looks like @itsarnavsingh is running VS 16.10 Community.

@itsarnavsingh can you run the dependencies script described here: https://aka.ms/rnw-deps

**Comment by SvetBonev** [comment]
@asklar The screenshot shows the Visual Studio Build Tools edition, not any client editions (Community, Pro, Enterprise).

**Comment by asklar** [comment]
are the newer SDKs not available to be installed with build tools? I don't think we've tested or support using build tools (e.g. IDK if the right project system stuff is installed in this case).
It looks like vswhere did find Community installed from the info in the original post (see `Visual Studio: 16.10.31410.357 (Visual Studio Community 2019)`), so I'm not really sure what might be going on. It would be good to hear back from @itsarnavsingh and see if the dependencies script found any issues or resolved this.

**Comment by itsarnavsingh** [comment]
Thank you @NickGerleman it worked.

**Comment by itsarnavsingh** [comment]
> Some RNW features require later SDKs (notably, animations). You can target an app to a lower OS release, but you still have to use a newer SDK to build it, so that the SDK headers can define the newer APIs (we will just not call them on older OSs).
> 
> It's super weird that VS isn't showing you any newer SDK versions though... @BenJKuhn @SvetBonev any idea why that might happen? Looks like @itsarnavsingh is running VS 16.10 Community.
> 
> @itsarnavsingh can you run the dependencies script described here: https://aka.ms/rnw-deps

![image](https://user-images.githubusercontent.com/36072753/124140654-49a66500-daa6-11eb-859d-33c8acc6a0be.png)

**Comment by SvetBonev** [comment]
@asklar We do update the Build Tools with newer SDK. I am not sure what version of Build Tools is on the machine.
The Build Tools have no IDE components so no project system stuff is installed by this SKU.

**Comment by chrisglein** [comment]
> Thank you @NickGerleman Nick Gerleman FTE it worked.

Glad to hear you're unblocked!
There's potential to clean up the error reporting here as it's strange to have all the scripts and info reporting saying it's okay and then have it... not be okay. Let's wait and see if we get more hits on this.
