### ISSUE TITLE
Upgrade ProgressView to WinUI 2.6 Styling

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-windows#8141]
# Proposal: Upgrade ProgressView to WinUI 2.6 Styling

## Summary
ProgressView community module needs manual updates to reflect WinUI2.6 styling. Following adding ProgressView to an app running with WinUI 2.6, the ProgressView shows the wrong animation for its indeterminate state and has the wrong shape for its determinate state. 

## Motivation
Alignment with current WinUI styling. 

## Screenshots
Progress View Community Module
![image](https://user-images.githubusercontent.com/34109996/124192401-14841d80-da7a-11eb-827c-daee9c034dfb.png)

XAML ProgressBar
![image](https://user-images.githubusercontent.com/34109996/124192504-3ed5db00-da7a-11eb-882e-3534f0fca998.png)

**Comment by chrisglein** [comment]
@chiaramooney Can you provide a screenshot of the diff?

**Comment by chiaramooney** [comment]
Looks like we have a similar situation to the TextInput control here. The ProgressView control currently matches the styling of ProgressView for Android and iOS, but does not match the Windows styling. See photo here:

![image](https://user-images.githubusercontent.com/34109996/127914921-17b0fc67-447c-4521-aac4-d1b6fac76171.png)

Do we want to go with the same decision we went with for TextInput and rule that the design intention of this control is to be platform generic? Note that developers still have the opportunity to get the XAML ProgressBar through react-native-xaml.

**Comment by chiaramooney** [comment]
Following offline thread, looks like the next step here is to upgrade ProgressView to use MUX instead of system xaml's ProgressBar. Re-assigning this work to Tatiana; good fit as she worked with this repo last summer.
