### ISSUE TITLE
Upgrade TextInput to WinUI2.6 Styling

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-windows#8142]
# Proposal: Upgrade TextInput to WinUI2.6 Styling

## Summary
TextInput needs manual update to match WinUI2.6 styling. Currently when TextInput is used in an RNW app which consumes WinUI2.6, the component does not have the correct shape, shadows, or coloring. 

## Motivation

Align styling with WinUI2.6

## Screenshots
TextInput Core Component
![image](https://user-images.githubusercontent.com/34109996/124192627-6a58c580-da7a-11eb-973c-049af7fb6cbc.png)

TextBox XAML Component
![image](https://user-images.githubusercontent.com/34109996/124192697-8bb9b180-da7a-11eb-96b6-8b7663ae9645.png)

**Comment by chrisglein** [comment]
There's a question here about how close RN's TextInput should be to a XAML TextBox (which has a fair amount of chrome). Essentially, when making it "native", how much extra native details should it pick up?

For this we're looking at the diff from WinUI 2.5->2.6, so let's start by focusing on what the difference introduced there is. @chiaramooney can you provide some screenshots that show the differences? There's a `enableFocusRing` option that affects whether native visuals show up, which we should factor in.

**Comment by chrisglein** [comment]
Displaying a plain un-customized `TextInput`.

```
    <View style={styles.container}>
      <Text style={{borderBottomWidth: 1, borderColor: '#aaa'}}>⬇️ Below is a TextInput ⬇️</Text>
      <TextInput></TextInput>
      <Text style={{borderTopWidth: 1, borderColor: '#aaa'}}>⬆️ Above is a TextInput ️⬆️</Text>
    </View>
```
I put borders on there to make the control footprint more obvious, and then realized afterwards that it confused the presence/absence of box visuals and also is handled differently per platform. So... whoops.

But, you can see that most platforms do not display the extra level of Text _Box_ style chrome. Web is the closest in that it brings in more when focused.

| | Windows | Web | iOS | Android |
| --- | --- | --- | --- | --- |
| no content | ![image](https://user-images.githubusercontent.com/26607885/125872084-36c6974d-62f0-4156-a03f-52e5a79f7c97.png) | ![image](https://user-images.githubusercontent.com/26607885/125862946-c7ac860b-01b8-4091-97ed-eafbf3b96bd5.png) | ![image](https://user-images.githubusercontent.com/26607885/125863149-18b4bfb3-3c45-487f-befa-471fb707eaa8.png) | ![image](https://user-images.githubusercontent.com/26607885/125863511-44a88379-ec51-4465-be96-e4fb7849971b.png) |
| content | ![image](https://user-images.githubusercontent.com/26607885/125872106-3b305338-89b6-47a5-a77e-ff3b47f8327e.png) | ![image](https://user-images.githubusercontent.com/26607885/125862977-acdd7f84-b3e8-4286-a67a-ca1a9d583f58.png) | ![image](https://user-images.githubusercontent.com/26607885/125863330-41bfc4bf-321f-4cbb-9416-949a57562865.png) | ![image](https://user-images.githubusercontent.com/26607885/125863563-03867677-28b9-4370-812a-8771c958d1ce.png) |
| focused | ![image](https://user-images.githubusercontent.com/26607885/125872120-c9ad5e05-480f-4dec-8867-f9dc8566d83e.png) | ![image](https://user-images.githubusercontent.com/26607885/125863018-130c4b8f-9f2a-4965-815c-5a447e883b51.png) | ![image](https://user-images.githubusercontent.com/26607885/125863282-5c6ea6d7-8c14-43ad-b8d2-cac85092ec33.png) | ![image](https://user-images.githubusercontent.com/26607885/125863587-3b394d50-a7ee-4c8d-adca-df07a3331501.png) |

**Comment by chiaramooney** [comment]
Sounds good. It seems like the consensus then would be to leave the styling of the TextInput core control as is and if partners request the styled Windows TextBox we can refer them to react-native-xaml. Closing Issue.
