### ISSUE TITLE
Gradual slowdown when calling into a native method from js

### ISSUE THREAD

**Issue by edward-a** [microsoft/react-native-windows#8156]
We are experiencing a substantial slowdown after multiple calls into a native method from js. The more calls we make the slower it gets.

## Environment
1. `npx react-native --version`:
    5.0.1
2. `npx react-native info`:
 info Fetching system and libraries information...                                                                                                                      System:                                                                                                                                                                    OS: Windows 10 10.0.19043                                                                                                                                              CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz                                                                                                                Memory: 35.17 GB / 63.90 GB                                                                                                                                          Binaries:                                                                                                                                                                Node: 14.17.0 - C:\Program Files\nodejs\node.EXE                                                                                                                       Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD                                                                                                                npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD                                                                                                                         Watchman: Not Found                                                                                                                                                  SDKs:                                                                                                                                                                    Android SDK: Not Found                                                                                                                                                 Windows SDK:                                                                                                                                                             AllowDevelopmentWithoutDevLicense: Enabled                                                                                                                             AllowAllTrustedApps: Enabled                                                                                                                                           Versions: 10.0.17134.0, 10.0.17763.0, 10.0.18362.0, 10.0.19041.0, 10.0.20344.0                                                                                     IDEs:                                                                                                                                                                    Android Studio: Not Found                                                                                                                                              Visual Studio: 16.10.31321.278 (Visual Studio Professional 2019), 15.9.28307.1321 (Visual Studio Professional 2017), 16.10.31025.218 (Visual Studio Professional 2019)                                                                                                                                                                      Languages:                                                                                                                                                               Java: Not Found                                                                                                                                                      npmPackages:                                                                                                                                                             @react-native-community/cli: Not Found                                                                                                                                 react: 17.0.1 => 17.0.1                                                                                                                                                react-native: 0.64.0 => 0.64.0                                                                                                                                         react-native-windows: ^0.64.0-0 => 0.64.12                                                                                                                           npmGlobalPackages:                                                                                                                                                       *react-native*: Not Found          

## Steps To Reproduce
1. Create a React Native C# Visual Studio 2019 project:
    npx react-native init native_module_slowdown --template react-native@^0.64.0
    cd native_module_slowdown
    npx react-native-windows-init --language cs --overwrite
    npx react-native autolink-windows

2. Open native_module_slowdown.sln in Visual Studio 2019
3. Modify MainPage.xaml.cs to add the class below:
```csharp
namespace native_module_slowdown
{
  ...

  [ReactModule]
  class TestModule
  {
    [ReactMethod("test")]
    public void test(double r) {
      Debug.WriteLine($"test: {r}");
    }
  }
}
```

4. Modify ReactPackageProvider.cs as follows:
```csharp
namespace native_module_slowdown
{
  public partial class ReactPackageProvider : IReactPackageProvider
  {
    public void CreatePackage(IReactPackageBuilder packageBuilder) {
      packageBuilder.AddAttributedModules();
      CreatePackageImplementation(packageBuilder);
    }

    /// <summary>
    /// This method is implemented by the C# code generator
    /// </summary>
    partial void CreatePackageImplementation(IReactPackageBuilder packageBuilder);
  }
}
```

5. Replace the content of App.js with the code below:
```js
import React, { Component } from 'react';
import { View, Switch, NativeModules } from 'react-native';

class App extends Component {
  counter = 0;

  componentDidMount() {
    setInterval(function () {
      if (++this.counter < 1000)
        NativeModules.TestModule.test(Math.random());
    }.bind(this), 10);
  }

  componentWillUnmount() {
  }

  render() {
    return (
      <View>
        <Switch onValueChange={() => console.log("switch: " + Math.random())}/>
      </View>
    );
  }
};

export default App;
```
6. Run the server by executing the command below from the project's directory.
     yarn start
7. Compile x64/Debug configuration and run the app under Visual Studio 2019 debugger. You should be able to see a switch toggle in the left top corner.
8. The loop inside componentDidMount() will send random values to the native method for 1000 times which will be logged in the Visual Studio's Output window as follows: 
    ....
    test: 0.633033773705823
    test: 0.819914520830227
    test: 0.209848913516865
    test: 0.883959296199646
    test: 0.0663717719987089
    test: 0.373583039774186
    ....
9. Wait until the logging stops - all values have been sent/received.
10. Now open Developers Tools in Chrome/Edge and start clicking on the switch and see how long it takes for the value set by the switch to show up in Console:
   ...
   switch: 0.9707812927002095
   switch: 0.3081056968192988
   ...
11. Notice that the lag between you clicking on the switch and the value showing up in Console is about **1 seconds**.

## Expected Results
There should be no noticeable lag between clicking on the switch and the value showing up in the browser's Console. You can see that being the case by commenting out the content of componentDidMount() and restarting the app.
```csharp
  componentDidMount() {
    //setInterval(function () {
      //if (++this.counter < 1000)
        //NativeModules.TestModule.test(Math.random());
    //}.bind(this), 10);
  }
```

**Comment by acoates-ms** [comment]
It sounds like you are running the app with web/remote debugging.  Which is very different than a production environment.  Does this happen when running a release app, and running the JS inside the app instead of within chrome/edge?

**Comment by edward-a** [comment]
> 
> 
> It sounds like you are running the app with web/remote debugging. Which is very different than a production environment. Does this happen when running a release app, and running the JS inside the app instead of within chrome/edge?

No, it doesn't happen in release. But we need a way to test our code. Would appreciate any advice/workaround/fix.

**Comment by chrisglein** [comment]
The example above tries to stress the environment with a thousand messages. Were you seeing a scenario prior to this that prompted this example? As Andrew says above the web debugging path is going to have performance issues (you could try direct debugging?). Was this inhibiting your development?

**Comment by edward-a** [comment]
> 
> 
> The example above tries to stress the environment with a thousand messages. Were you seeing a scenario prior to this that prompted this example? As Andrew says above the web debugging path is going to have performance issues (you could try direct debugging?). Was this inhibiting your development?

I'd say this examples shows that the environment gets broken after thousands of messages. The actual test happens after those messages are sent/received, so there shouldn't be any bottleneck, although the substantial lag happens. This stress test clearly shows that there are underlying issues that make the framework unstable.

As for being impediment to our development, yes it actually makes React Native development for Windows with native components unbearable leading to a dead end. We are currently combing through the RN code trying to figure out whats going on. Hope RN team helps us and applies their expertise to sort this out.

**Comment by acoates-ms** [comment]
Is the app cross platform?  Does it happen in android/ios? Tracking down if its something windows specific or general to react-native will help isolate which parts of the platform we need to investigate.

**Comment by edward-a** [comment]
> 
> 
> Is the app cross platform? Does it happen in android/ios? Tracking down if its something windows specific or general to react-native will help isolate which parts of the platform we need to investigate.

It's a Windows app developed in Visual Studio (the description of issue). We are porting a UWP app to React Native in hopes to also port it to Linux in future. The business logic remains written in C#, while the presentation layer has been ported to JSX. There is a lot of communication happening between these layers and while it runs top notch in Release, the Debug version is what gives us a headache signficantly slowing down our development.

**Comment by chrisglein** [comment]
Sounds like next step here is to duplicate the repro and debug/profile through what's going on.
