### ISSUE TITLE
How to change cursor to pointer using styled components?

### ISSUE THREAD

**Issue by arnavzek** [microsoft/react-native-windows#8157]

**Comment by Arcalise08** [comment]
I'd actually be interested to know how to change cursor to pointer just in general. the following does nothing in windows view.

`cursor:"pointer"`

**Comment by asklar** [comment]
Looks like we don't support this today yet.

Work here would be:
- upon property set on a view, add a PointerEntered + PointerExited handler to change+save the prev pointer and restore it respectively. See example in [CoreCursor](https://docs.microsoft.com/uwp/api/Windows.UI.Core.CoreCursor).
- map the RN `cursor` values to [CoreCursorType](https://docs.microsoft.com/uwp/api/windows.ui.core.corecursortype).

**Comment by chrisglein** [comment]
There may be some implementations of this on macOS as well. This seems like a fair request to fill in for Windows.

**Comment by Qurishe** [comment]
> I'd actually be interested to know how to change cursor to pointer just in general. `cursor:"pointer"` does nothing in windows view.
> 
> Also gonna mention as a little dirty fix I created a C# method for changing cursor. Which works fine, although you have to invoke the method. itd be cleaner if the style prop worked.
> 
> I havent uploaded mine, But in my search for the solution i did find this [wrapper](https://github.com/bluejeans/react-native-windows-cursor) which does the same thing

Hi, can you provide an example of how to use this wrapper?
I installed it and imported Cursor from react-native-windows-cursor but when i call Cursor.setCursor("pointer") it gives me error of undefined.

**Comment by Qurishe** [comment]
> There may be some implementations of this on macOS as well. This seems like a fair request to fill in for Windows.

@chrisglein do you know anything about this library and how to use it?

**Comment by asklar** [comment]
@Qurishe that library was built for an earlier version of RNW, which was built on top of WPF. We rewrote RNW a few years ago (does not target WPF anymore) and so this library won't work on the re-written RNW.

**Comment by Qurishe** [comment]
> @Qurishe that library was built for an earlier version of RNW, which was built on top of WPF. We rewrote RNW a few years ago (does not target WPF anymore) and so this library won't work on the re-written RNW.

Ohh, so is there any library or work around?

**Comment by asklar** [comment]
you could use [react-native-winrt](https://github.com/microsoft/react-native-winrt/) to call the native cursor APIs from your JS. there isn't anything that is more ready-made as far as I know.

**Comment by Qurishe** [comment]
> you could use [react-native-winrt](https://github.com/microsoft/react-native-winrt/) to call the native cursor APIs from your JS. there isn't anything that is more ready-made as far as I know.

Thank u for helping me😃.
I setup the react native WinRT but when try to build it gives me error of "compiler is out of heap space" i tried lots of solutions from stackoverflow but still didn't solve it.
my machine has:
SSD
12GB of RAM

**Comment by paperbackdragon** [comment]
We're definitely interested in this feature on my team as well.

**Comment by shreyaspadhye3011** [comment]
+1. This would be super helpful in certain cases where we want to convey end users the possibility of clickable / actionable items.

**Comment by e-exchange** [comment]
@chrisglein i solved this issue by creating a native module and a component to change the cursor to pointer or any other type.

**Comment by imoris11** [comment]
> We're definitely interested in this feature on my team as well.

+1. Glad to see that you already left a comment here. We still need this.

**Comment by AlmTalal** [comment]
> @chrisglein i solved this issue by creating a native module and a component to change the cursor to pointer or any other type.



> @chrisglein i solved this issue by creating a native module and a component to change the cursor to pointer or any other type.

Hey, could you share the solution ?  Did you use [CoreCursor Contructor](https://learn.microsoft.com/en-us/uwp/api/windows.ui.core.corecursor.-ctor?view=winrt-22621)

**Comment by AlmTalal** [comment]
Hey @Qurishe thanks ! However im not that good in C#, I understand the logic of the code, but when trying to create the native module and rebuild the app like this: 

1. Create a file within the directory windows/projectname/, for example, MyModule.h.

2. Then, include #include "MyModule.h" within your ReactPackageProvider.cpp file.

(But with cs extension)

Im getting this error :

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2337	'ReactMethod': attribute not found (compiling source file ReactPackageProvider.cpp)	testpro	C:\Users\almta\OneDrive\Escritorio\M37\windows\testpro\cursorChanger.cs	1

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2447	'{': missing function header (old-style formal list?) (compiling source file ReactPackageProvider.cpp)	testpro	C:\Users\almta\OneDrive\Escritorio\M37\windows\testpro\cursorChanger.cs	3	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2059	syntax error: 'public' (compiling source file ReactPackageProvider.cpp)	testpro	C:\Users\almta\OneDrive\Escritorio\M37\windows\testpro\cursorChanger.cs	2	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2143	syntax error: missing ';' before '{' (compiling source file ReactPackageProvider.cpp)	testpro	C:\Users\almta\OneDrive\Escritorio\M37\windows\testpro\cursorChanger.cs	3	
	
Btw Im literally just copying your code, I don't know if I must have any headers or things like that. Should I have some ?

**Comment by Victor0814gui** [comment]
Give this a spin and let me know if it floats your boat
Here's the corrected C++ code for your scenario:

```cpp
#pragma once

#include "pch.h"
#include "NativeModules.h"

#include "winrt/Windows.UI.Core.h"
#include "winrt/Windows.Foundation.h"

namespace RN = winrt::Microsoft::ReactNative;

namespace MouseModuleNamespace {
    REACT_MODULE(MouseModule, L"MouseModule");
    struct MouseModule final {

        REACT_INIT(Initialize, L"init");
        void Initialize(RN::ReactContext const& reactContext) noexcept
        {
            m_reactContext = reactContext;
        }

        REACT_METHOD(CursorPointer, L"CursorPointer");
        void CursorPointer(hstring const& cursor, RN::ReactPromise<void> const& promise) noexcept
        {
            auto jsDispatcher = m_reactContext.JSDispatcher();
            m_reactContext.UIDispatcher().Post([cursor, promise, jsDispatcher] {
                if (cursor == L"pointer")
                {
                    winrt::Windows::UI::Core::CoreWindow::GetForCurrentThread().PointerCursor(
                        winrt::Windows::UI::Core::CoreCursor(winrt::Windows::UI::Core::CoreCursorType::Hand, 0));
                }
                else
                {
                    winrt::Windows::UI::Core::CoreWindow::GetForCurrentThread().PointerCursor(
                        winrt::Windows::UI::Core::CoreCursor(winrt::Windows::UI::Core::CoreCursorType::Arrow, 0));
                }
            });
        }
    };
}
```
Changes made:

- Added REACT_METHOD macro to declare the CursorPointer method as a React method.
- Changed the CursorPointer method signature to accept hstring const& cursor and RN::ReactPromise<void> const& promise as parameters.

**Comment by Qurishe** [comment]
@AlmTalal that's because the code i provided is just a method and not the React Module which u need to create and put the above code inside.

**Comment by AlmTalal** [comment]
> @AlmTalal that's because the code i provided is just a method and not the React Module which u need to create and put the above code inside.

@Qurishe Sorry if I'm bothering you too much, but could you provide the complete code, I'm just not able to get it done 😆. Thanks in advance

**Comment by AlmTalal** [comment]
> Give this a spin and let me know if it floats your boat Here's the corrected C++ code for your scenario:
> 
> ```c++
> #pragma once
> 
> #include "pch.h"
> #include "NativeModules.h"
> 
> #include "winrt/Windows.UI.Core.h"
> #include "winrt/Windows.Foundation.h"
> 
> namespace RN = winrt::Microsoft::ReactNative;
> 
> namespace MouseModuleNamespace {
>     REACT_MODULE(MouseModule, L"MouseModule");
>     struct MouseModule final {
> 
>         REACT_INIT(Initialize, L"init");
>         void Initialize(RN::ReactContext const& reactContext) noexcept
>         {
>             m_reactContext = reactContext;
>         }
> 
>         REACT_METHOD(CursorPointer, L"CursorPointer");
>         void CursorPointer(hstring const& cursor, RN::ReactPromise<void> const& promise) noexcept
>         {
>             auto jsDispatcher = m_reactContext.JSDispatcher();
>             m_reactContext.UIDispatcher().Post([cursor, promise, jsDispatcher] {
>                 if (cursor == L"pointer")
>                 {
>                     winrt::Windows::UI::Core::CoreWindow::GetForCurrentThread().PointerCursor(
>                         winrt::Windows::UI::Core::CoreCursor(winrt::Windows::UI::Core::CoreCursorType::Hand, 0));
>                 }
>                 else
>                 {
>                     winrt::Windows::UI::Core::CoreWindow::GetForCurrentThread().PointerCursor(
>                         winrt::Windows::UI::Core::CoreCursor(winrt::Windows::UI::Core::CoreCursorType::Arrow, 0));
>                 }
>             });
>         }
>     };
> }
> ```
> 
> Changes made:
> 
> * Added REACT_METHOD macro to declare the CursorPointer method as a React method.
> * Changed the CursorPointer method signature to accept hstring const& cursor and RN::ReactPromise const& promise as parameters.

Hey @Victor0814gui, you are always saving me jajajaja, but this time didn't work. I'm still getting some syntax problems

**Comment by josetr** [comment]
@AlmTalal 

I've fixed the compile errors:

```cpp

#pragma once

#include "pch.h"
#include "NativeModules.h"

#include "winrt/Windows.UI.Core.h"
#include "winrt/Windows.Foundation.h"

namespace RN = winrt::Microsoft::ReactNative;

namespace MouseModuleNamespace {
    REACT_MODULE(MouseModule, L"MouseModule");
    struct MouseModule final {
        REACT_INIT(Initialize, L"init");
        void Initialize(RN::ReactContext const& reactContext) noexcept
        {
            m_reactContext = reactContext;
        }

        REACT_METHOD(CursorPointer, L"CursorPointer");
        void CursorPointer(winrt::hstring const& cursor, RN::ReactPromise<void> const& promise) noexcept
        {
            auto jsDispatcher = m_reactContext.JSDispatcher();
            m_reactContext.UIDispatcher().Post([cursor, promise, jsDispatcher] {
                if (cursor == L"pointer")
                {
                    winrt::Windows::UI::Core::CoreWindow::GetForCurrentThread().PointerCursor(
                        winrt::Windows::UI::Core::CoreCursor(winrt::Windows::UI::Core::CoreCursorType::Hand, 0));
                }
                else
                {
                    winrt::Windows::UI::Core::CoreWindow::GetForCurrentThread().PointerCursor(
                        winrt::Windows::UI::Core::CoreCursor(winrt::Windows::UI::Core::CoreCursorType::Arrow, 0));
                }
                });
        }

    private:
        RN::ReactContext m_reactContext{ nullptr };
    };
}

```

**Comment by josetr** [comment]
React Bonus - wrapping native Pressable element

```ts
import { useEffect, useRef, forwardRef, ElementRef } from "react";
import { Pressable as NativePressable, Platform, PressableProps } from "react-native"
import { NativeModules } from "react-native";

const isPlatformSupported = Platform.OS === "windows"

type CursorType = "pointer" | ""

export const Pressable = !isPlatformSupported ? NativePressable :
  forwardRef<ElementRef<typeof NativePressable>, PressableProps>(({ onHoverIn, onHoverOut, onPress, ...props }, ref) => {
    const type = useRef<CursorType>("")

    const setType = (newType: CursorType) => {
      if (type.current === newType)
        return;

      type.current = newType;
      NativeModules.MouseModule.CursorPointer(newType);
    }

    useEffect(() => {
      return () => setType("")
    }, []);

    return <NativePressable
      onHoverIn={(e) => {
        if (onPress)
          setType("pointer");
        onHoverIn?.(e)
      }}
      onHoverOut={(e) => {
        setType("");
        onHoverOut?.(e)
      }}
      onPress={onPress}
      ref={ref}
      {...props} />
  })
```

**Comment by Victor0814gui** [comment]
@AlmTalal jajaja, this time I didn't test it thoroughly, but I've already resolved it and created a module that maps all the types of cursors available in UWP.

**Comment by Victor0814gui** [comment]
I'm thinking of releasing something like @rn-customize-window/cursor, @rn-customize-window/window, @rn-customize-window/titlebar. Any ideas for better names?

**Comment by AlmTalal** [comment]
> I'm thinking of releasing something like @rn-customize-window/cursor, @rn-customize-window/window, @rn-customize-window/titlebar. Any ideas for better names?

Hey! that would be great, maybe it could be called rnw/cursor ?

**Comment by AlmTalal** [comment]
> React Bonus - wrapping native Pressable element
> 
> ```ts
> import { useEffect, useRef, forwardRef, ElementRef } from "react";
> import { Pressable as NativePressable, Platform, PressableProps } from "react-native"
> import { NativeModules } from "react-native";
> 
> const hasNativeModule = Boolean(NativeModules.MouseModule)
> type CursorType = "pointer" | ""
> 
> export const Pressable = !hasNativeModule ? NativePressable :
>   forwardRef<ElementRef<typeof NativePressable>, PressableProps>(({ onHoverIn, onHoverOut, onPress, ...props }, ref) => {
>     const type = useRef<CursorType>("")
> 
>     const setType = (newType: CursorType) => {
>       if (type.current === newType)
>         return;
> 
>       type.current = newType;
>       NativeModules.MouseModule.CursorPointer(newType);
>     }
> 
>     useEffect(() => {
>       return () => setType("")
>     }, []);
> 
>     return <NativePressable
>       onHoverIn={(e) => {
>         if (onPress)
>           setType("pointer");
>         onHoverIn?.(e)
>       }}
>       onHoverOut={(e) => {
>         setType("");
>         onHoverOut?.(e)
>       }}
>       onPress={onPress}
>       ref={ref}
>       {...props} />
>   })
> ```

Thanks josetr! I will try it

**Comment by kentng201** [comment]
Any plan to do this, we will need this feature

**Comment by Saadnajmi** [comment]
I believe RNW with fabric supports the new cursor style prop.

**Comment by mentalitydark** [comment]
I'll share the way I implemented it using `TurboModule` in case anyone is interested.  

### File: `windows/<APP_NAME>/Cursor.h`  
```cpp
#pragma once

#include "pch.h"
#include "NativeModules.h"

#include "winrt/Windows.UI.Core.h"
#include "winrt/Windows.Foundation.h"
#include <unordered_map>

namespace RN = winrt::Microsoft::ReactNative;

namespace MyModule
{
    REACT_MODULE(MouseModule, L"MouseModule");
    struct MouseModule final {
        REACT_INIT(Initialize, L"init");
        void Initialize(RN::ReactContext const& reactContext) noexcept
        {
            m_reactContext = reactContext;
        }

        REACT_METHOD(CursorPointer, L"CoreCursor");
        void CursorPointer(winrt::hstring const& cursor) noexcept
        {
            static const std::unordered_map<std::wstring, winrt::Windows::UI::Core::CoreCursorType> cursorMap = {
                { L"Arrow", winrt::Windows::UI::Core::CoreCursorType::Arrow },
                { L"Cross", winrt::Windows::UI::Core::CoreCursorType::Cross },
                { L"Custom", winrt::Windows::UI::Core::CoreCursorType::Custom },
                { L"Hand", winrt::Windows::UI::Core::CoreCursorType::Hand },
                { L"Help", winrt::Windows::UI::Core::CoreCursorType::Help },
                { L"IBeam", winrt::Windows::UI::Core::CoreCursorType::IBeam },
                { L"SizeAll", winrt::Windows::UI::Core::CoreCursorType::SizeAll },
                { L"SizeNortheastSouthwest", winrt::Windows::UI::Core::CoreCursorType::SizeNortheastSouthwest },
                { L"SizeNorthSouth", winrt::Windows::UI::Core::CoreCursorType::SizeNorthSouth },
                { L"SizeNorthwestSoutheast", winrt::Windows::UI::Core::CoreCursorType::SizeNorthwestSoutheast },
                { L"SizeWestEast", winrt::Windows::UI::Core::CoreCursorType::SizeWestEast },
                { L"UniversalNo", winrt::Windows::UI::Core::CoreCursorType::UniversalNo },
                { L"UpArrow", winrt::Windows::UI::Core::CoreCursorType::UpArrow },
                { L"Wait", winrt::Windows::UI::Core::CoreCursorType::Wait },
                { L"Pin", winrt::Windows::UI::Core::CoreCursorType::Pin },
                { L"Person", winrt::Windows::UI::Core::CoreCursorType::Person }
            };

            winrt::Windows::UI::Core::CoreCursorType cursorType = winrt::Windows::UI::Core::CoreCursorType::Arrow;
            auto it = cursorMap.find(cursor.c_str());
            if (it != cursorMap.end()) {
                cursorType = it->second;
            }

            auto jsDispatcher = m_reactContext.JSDispatcher();
            m_reactContext.UIDispatcher().Post([cursorType] {
                winrt::Windows::UI::Core::CoreWindow::GetForCurrentThread().PointerCursor(
                    winrt::Windows::UI::Core::CoreCursor(cursorType, 0));
                });
        }

    private:
        RN::ReactContext m_reactContext{ nullptr };
    };
}
```

### File: `windows/<APP_NAME>/ReactPackageProvider.cpp`  
Just add `#include "Cursor.h"`

### File: `src/modules/Cursor.ts`  
```ts
import type {TurboModule} from 'react-native/Libraries/TurboModule/RCTExport';
import {TurboModuleRegistry} from 'react-native';
import { CoreCursorType } from 'enums';

export interface Spec extends TurboModule {
  CoreCursor: (cursor: CoreCursorType) => void;
}

const Cursor = TurboModuleRegistry.get<Spec>('MouseModule') as Spec | null;

export {Cursor};
```

### File: `src/enums/CoreCursorType.ts`  
```ts
export enum CoreCursorType {
    Arrow = 'Arrow',
    Cross = 'Cross',
    Custom = 'Custom',
    Hand = 'Hand',
    Help = 'Help',
    IBeam = 'IBeam',
    SizeAll = 'SizeAll',
    SizeNortheastSouthwest = 'SizeNortheastSouthwest',
    SizeNorthSouth = 'SizeNorthSouth',
    SizeNorthwestSoutheast = 'SizeNorthwestSoutheast',
    SizeWestEast = 'SizeWestEast',
    UniversalNo = 'UniversalNo',
    UpArrow = 'UpArrow',
    Wait = 'Wait',
    Pin = 'Pin',
    Person = 'Person',
}
```

### File: `package.json`  
```json
  "codegenConfig": {
    "name": "APP_NAME",
    "type": "modules",
    "jsSrcsDir": "src",
    "windows": {
      "namespace": "APP_NAME"
    }
  }
```

Run the command `npm run windows`, and everything will be generated automatically.  

To use it, simply call `Cursor` from `Cursor.ts`.  
I built my component this way so I can set it on any element, but you can use it however you prefer.  
The important part is `NativeCursor?.CoreCursor(type);`  

```ts
import React, { PropsWithChildren, useEffect } from 'react';
import { Pressable } from 'react-native-windows';

import { CoreCursorType } from 'enums';
import { Cursor as NativeCursor } from 'modules';
import { CursorProps } from './Cursor.types';

export function Cursor({ type, children }: PropsWithChildren<CursorProps>) {
  const mouseIn = () => {
    NativeCursor?.CoreCursor(type);
  };

  const mouseOut = () => {
    NativeCursor?.CoreCursor(CoreCursorType.Arrow);
  };

  useEffect(() => {
    return () => NativeCursor?.CoreCursor(CoreCursorType.Arrow);
  }, []);

  return (
    <Pressable
      onHoverIn={mouseIn}
      onHoverOut={mouseOut}
    >
      {children}
    </Pressable>
  );
}
```
