### ISSUE TITLE
StyleYogaNode hijacks lots of properties

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#8158]
After we call a view manager's `UpdateProperties`, we do another pass where the ui manager will call `StyleYogaNode` to update style properties (e.g. `margin`). However it doesn't require that these properties live inside a `style` object. This means that there is a large set of property names that can never be declared/overridden by view managers.

In other words, this is legal, but seems like it shouldn't be?
```jsx
<Text margin={20}>Foo</Text>
```

where I'd expect the right syntax to be:
```jsx
<Text style={{margin: 20}}>Foo</Text>
```

**Comment by NickGerleman** [comment]
This is also a problem in upstream RN (Android and iOS), where style properties are past as top level props.

**Comment by asklar** [comment]
Can we fix it?

**Comment by chrisglein** [comment]
This would be a breaking change in core across all platforms. Totally makes sense that it'd be better this way, but we'd need buyoff on the break from changing this. Candidate to raise on [discussions-and-proposals](https://github.com/react-native-community/discussions-and-proposals/issues/)? This is actually a React issue, not just a React Native issue.
