### ISSUE TITLE
Community view managers cannot get certain RN core properties applied to them

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#8165]
Community view managers will be wrapped by an `ABIViewManager`. This class inherits from `FrameworkElementViewManager`, so when a property is updated, it gives it to the community VM, and then passes it up the chain, to the FEVM.
However there is functionality like `borderRadius` that is implemented in other VMs in the hierarchy, that `ABIViewManager` does not have access to. This means that even if the VM returns a XAML `Control`, an app won't be able to use the `borderRadius` or any other property that isn't in `FrameworkElementViewManager`.

I think the fix is either:
- `ABIViewManager` needs to inherit from something lower down, and all the parent view managers need to do a best-effort (i.e. don't assume that the view is a Control in ControlViewManager, check it - IOW, change `view.as<Control>()` to `view.try_as<Control>()`)
- Have `ABIViewManager` manually delegate to other VMs if the view matches the XAML type that the VM represents
- Move the logic for these other VMs to a central, non-VM location, that can be called by `ABIViewManager` as well as the other VMs.

**Comment by chrisglein** [comment]
View managers can implement these themselves, but can't ride the standard behavior that exists for other Control based view managers. Can we have them get that? Can we provide an API for them to get the same behavior? Do we need to mark certain properties as "handled" so the handoff is clear here?

What we have here is the current design, but there seem to be some gaps that need answering as to how view managers should approach this.

**Comment by jonthysell** [comment]
The current internal structure of our View Managers is a class inheritance hierarchy mirroring the hierarchy of XAML, for the benefit of the built-in view managers RN needs to support. When designed, the expectation was that no one would ever need to create view managers for anything that wasn't a framework element, and most of the "common" logic is in the framework element viewmanager.

The ControlViewManager correspondingly, is targeted toward the requirements of the built-in View Managers that map to XAML Controls.

Requirements may have changed, and we could meet that by refactoring our view managers internally to instead expose this logic in a non-class-inheritance way. But I do not think we should do something like automatically apply the logic in ControlViewManager to all XAML Controls used by external View Managers,. At best it would "get certain RN core properties" applied to them, but more likely it would just be a breaking change in behavior.

Any refactor should include some mechanism for allowing viewmanagers (internal or external) for reporting _which_ properties it intends to handle, and then not allowing other viewmanagers from also handling those properties. So there can be a default behavior if you don't handle a property, but if you _do_ handle it, don't let the framework override you.

**Comment by jonthysell** [comment]
Still a good part of the "how should we design the ViewManager ABI" discussion.

**Comment by chiaramooney** [comment]
Not something we plan to address on the Paper renderer as we move towards Fabric.
Not sure if this behavior is still applicable on the Fabric renderer. If so, we'd want a fresh analysis.
