### ISSUE TITLE
Move C++ projects to use PackageReference 

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#8171]
Apparently PackageReference will work in C++ projects now. We should try it and see if there are any gaps, and if acceptable then remove the packages.config stuff as it complicates things.

----

@asklar As it turns out, PackageReference support in C++ projects works _today_. You will need to do the following:

1. Add `<ProjectCapability Include="PackageReferences" />` to an item group in your vcxproj file or a targets file included by it.
2. Add a Directory.Build.props file or above the project’s directory, and add an Import element to it with the following value: `$(MSBuildProjectExtensionsPath)$(MSBuildProjectFile).*.props`. (You can technically add this anywhere that MSBuild will see it, but I find that putting it in Directory.Build.props ensures that it is both included at the correct place, and is also easily shared between all the projects in your solution.)
3. Add a Directory.Build.targets file in the same location, and add an Import element to it with this value: `$(MSBuildProjectExtensionsPath)$(MSBuildProjectFile).*.targets`.
4. Unload and reload your C++ project(s).

After that, not only will NuGet packages auto-restore like with csproj, but the NuGet Package Manager UI will also add and remove PackageReference elements from the project instead of creating a packages.config file. (If this doesn’t seem to work, you may need to use the VS 16.11 beta; that’s what I’m using, and it works great for me.) Note that vcxproj will require you to run File > Save All before changes made in the NuGet UI will persist to the project file, as with any other changes to a vcxproj made using the GUI. Hope this helps!

_Originally posted by @wjk in https://github.com/dotnet/project-system/issues/2491#issuecomment-874924412_

## References
- https://developercommunity.visualstudio.com/t/use-packagereference-in-vcxproj/351636
- https://github.com/jlaanstra/CppWinRT-PackageReference

**Comment by JunielKatarn** [comment]
I think @dannyvv tried this before, only native projects still rely on traditional NuGet locations (meaning, packages will still be stored in the `packages` relative folder).

This is definitely useful, however, as it reduces the possibility of version mismatches.

**Comment by wjk** [comment]
@JunielKatarn Not necessarily. I have used vcxproj PackageReference with both the global (per-user) NuGet package cache, and a local package cache set via the `nuget.config` file, and have never ran into any such problems. Keep in mind that either way, the packages will all be unpacked as siblings of the same directory (either the per-user cache, or the path set in the `nuget.config` file), just as with packages.config. IMHO, if a NuGet package requires a specific restore layout to function properly, that is a bug in that package that should be corrected. (All paths in props/targets files in NuGet packages should be relative to `$(MSBuildThisFileDirectory)`.) What packages do you expect will give problems?

**Comment by JunielKatarn** [comment]
@wjk none specifically. Maybe I was misinformed?
If a Native C++ project can load the packages from the NuGet package cache instead of requiring an explicit location (usually relative to the VCXPROJ file), that would be a huge gain for us, because we wouldn't need to copy the packages for each local git clone.

Did I understand this correctly?

**Comment by wjk** [comment]
That’s correct! 🚀

**Comment by JunielKatarn** [comment]
> That’s correct! 🚀

🤯
I guess I'll be submitting this enhancement for this project... TODAY, then.

One last question. Does this `PackageReference` mechanism work with plain NuGet.exe, or does it require some VS magic?

**Comment by wjk** [comment]
As it turns out, PackageReferences uses neither! Just run `MSBuild.exe /t:Restore` to download all needed packages, just as you would do with csproj (or run `MSBuild.exe /restore` to do so and then build the project).

**Comment by JunielKatarn** [comment]
Pretty much, pure modern MSBuild APIs, then.
Awesome.

**Comment by asklar** [comment]
Yeah I'm excited about the opportunity for simplification this brings!
If it requires a specific min version of VS, then that'd be important to know.

**Comment by wjk** [comment]
@asklar Support for C++ PackageReference in the VS GUI requires at least 16.9 per https://github.com/dotnet/project-system/pull/6629, which was the last PR needed to implement this feature. Support for restoring C++ PackageReferences via the command line goes back much, much further.

**Comment by mingkuang-Chuyu** [comment]
Haha, you only discovered this secret now. How long have I been using it.

Here is a more comprehensive configuration that allows vcxproj to support PackageReference.

## Directory.Build.props
```xml
<?xml version="1.0" encoding="utf-8"?>
<!--
为Cpp工程强制开启 PackageReferences 支持

Visual Studio 2017使用以后只能让MSBuild以及nuget.exe支持包还原。

Visual Studio 2019 16.8或者更高版本可以直接让Visual Studio NuGet插件支持包管理。

使用方法：将此文件复制到 sln 或者 vcxproj同级目录。


作者：mingkuang
最后修订：2021-06-21

-->
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup Condition="'$(MSBuildProjectExtension)' == '.vcxproj'">
    <!--强制引入PackageReferences-->
    <ProjectCapability Include="PackageReferences" />
  </ItemGroup>
  <PropertyGroup Condition="'$(MSBuildProjectExtension)' == '.vcxproj'">
    <!--指定自己的体系为native-->
    <NuGetTargetMoniker Condition="'$(NuGetTargetMoniker)' == ''">native,Version=v0.0</NuGetTargetMoniker>
    <!--如果不指定这一行，那么arm64平台会找不到RID而失败-->
    <RuntimeIdentifiers Condition="'$(RuntimeIdentifiers)' == ''">win;win-x86;win-x64;win-arm;win-arm64</RuntimeIdentifiers>
  </PropertyGroup>
  
  <!--从兼容性考虑，继续向上搜索 Directory.Build.props-->
  <PropertyGroup>
    <DirectoryBuildPropsPath>$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))</DirectoryBuildPropsPath>
  </PropertyGroup>
  <Import Project="$(DirectoryBuildPropsPath)" Condition="'$(DirectoryBuildPropsPath)' != ''"/>
</Project>
```

**Comment by davidhunter22** [comment]
I am wondering if this is meant to work for C++/CLI projects.
I create a .NET Core C++/CLI project using VS 2022 Preview 2.1 which I think has .NET SDK 6 preivew 6.
I followed the above instructions and when I tried to build a "HelloWorld" before adding any package references got

`1>C:\Users\david\source\repos\ClassLibrary4\Directory.Build.targets(2,5): warning MSB4011: "C:\Users\XXX\source\repos\ClassLibrary4\ClassLibrary4\obj\ClassLibrary4.vcxproj.nuget.g.targets" cannot be imported again. It was already imported at "C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64\Microsoft.Common.Targets (128,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\Users\david\source\repos\ClassLibrary4\ClassLibrary4\ClassLibrary4.vcxproj]
>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Microsoft\NuGet\17.0\Microsoft.NuGet.targets(198,5): error : Your project does not reference "native,Version=v0.0" framework. Add a reference to "native,Version=v0.0" in the "TargetFrameworks" property of your project file and then re-run NuGet restore.
1>Done building project "ClassLibrary4.vcxproj" -- FAILED.`

Is this only for native C++ projects?

**Comment by asklar** [comment]
@davidhunter22 React Native for Windows does not support C++/CLI. If you have questions about msbuild or VS support, please file them through VS feedback.
