### ISSUE TITLE
Backport Temporary Compositor Fix

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#8175]
> This change reduced time spent in dcomp by 200% (overall, we were spending 11% of time on this call in the app scenario and removing this line brings it down to 0%).

👀

_Originally posted by @NickGerleman in https://github.com/microsoft/react-native-windows/issues/8146#issuecomment-872427178_

**Comment by NickGerleman** [comment]
This is XAML Islands only, so the broad utility of the fix may be slightly limited

**Comment by chrisglein** [comment]
Looking for a customer who needs this to be backported. By default we can ship in next release 0.66.

**Comment by NickGerleman** [comment]
Going to close this since there is not a current plan to action on the issue, and it will exist by default in the milestone of 0.66.
