### ISSUE TITLE
Add TouchableWithoutFeedback accessibilityRole

### ISSUE THREAD

**Issue by AgneLukoseviciute** [microsoft/react-native-windows#8187]
https://facebook.github.io/react-native/docs/touchablewithoutfeedback#accessibilityrole
Partial
Works with View child only (via FEVM, but requires DAP)

**Comment by chrisglein** [comment]
Not something we plan to address on the Paper renderer as we move towards Fabric.
Fabric API completion for accessibility is tracked here: https://github.com/microsoft/react-native-windows/issues/11898
