### ISSUE TITLE
Add Text accessibilityState and accessibilityRole

### ISSUE THREAD

**Issue by AgneLukoseviciute** [microsoft/react-native-windows#8191]
https://reactnative.dev/docs/text#accessibilitystate
https://reactnative.dev/docs/text#accessibilityrole
https://reactnative.dev/docs/accessibility#accessibilityrole

Partial
Via FEVM, but requires DAP

**Comment by chrisglein** [comment]
Not something we plan to address on the Paper renderer as we move towards Fabric.
Fabric API completion for accessibility is tracked here: https://github.com/microsoft/react-native-windows/issues/11898
