### ISSUE TITLE
Add TouchableWithoutFeedback accessibilityActions and onAccessibilityAction

### ISSUE THREAD

**Issue by AgneLukoseviciute** [microsoft/react-native-windows#8192]
https://reactnative.dev/docs/touchablewithoutfeedback#onaccessibilityaction

https://reactnative.dev/docs/touchablewithoutfeedback#accessibilityactions

**Comment by chrisglein** [comment]
Not something we plan to address on the Paper renderer as we move towards Fabric.
Fabric API completion for accessibility is tracked here: https://github.com/microsoft/react-native-windows/issues/11898
