### ISSUE TITLE
Add React Children To Native UI Component

### ISSUE THREAD

**Issue by Arcalise08** [microsoft/react-native-windows#8199]
I'm trying to figure out how to pass react children to native ui components. I havent seen anyone really doing it so I'm not sure its actually possible. In react we could pass children as a prop and use `{children}` in the return. 

I'm attempting to create a container that can implement some native code when you interact with it or its children. If this isnt possible the alternative would be to implement the templating in a react component that triggers functions from a native module. But i would rather create a native UI component and pass react children to it.

**Comment by chrisglein** [comment]
I believe what you're looking for is [AddView](https://microsoft.github.io/react-native-windows/docs/IViewManagerWithChildren#addview). You'll need to implement that. Let us know if you have any questions.

**Comment by Arcalise08** [comment]
> I believe what you're looking for is [AddView](https://microsoft.github.io/react-native-windows/docs/IViewManagerWithChildren#addview). You'll need to implement that. Let us know if you have any questions.

Yes, this looks like what I need. its the same breakpoint i seem to hit saying the same thing. Do you happen to know of any basic examples of how to implement AddView in C#? I dont really see much on it.

**Comment by chrisglein** [comment]
> > I believe what you're looking for is [AddView](https://microsoft.github.io/react-native-windows/docs/IViewManagerWithChildren#addview). You'll need to implement that. Let us know if you have any questions.
> 
> Yes, this looks like what I need. its the same breakpoint i seem to hit saying the same thing. Do you happen to know of any basic examples of how to implement AddView in C#? I dont really see much on it.

Here's one example: [CircleViewManagerCS.cs](https://github.com/microsoft/react-native-windows/blob/003602b90aeda1b2a43702c6a9307c0f01010e59/packages/sample-apps/windows/SampleLibraryCS/CircleViewManagerCS.cs)
