### ISSUE TITLE
useHermes flag should be turned on while building binary distribution projects

### ISSUE THREAD

**Issue by mganandraj** [microsoft/react-native-windows#8201]
This issue was realized while making hermes nuget package work with C# applications generated from template, which uses the binary distribution of Microsoft.ReactNative libraries. As the libraries are not built with useHermes turned on, the applications end up falling back to ChakraCore.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. npx react-native-windows-init --overwrite --language cs --experimentalNuGetDependency --useHermes
2. npx react-native run-windows 

## Expected Results
Application uses Hermes engine.

## Actual Results
Application uses Chakra engine.

To be more concrete, we need to make sure that
1. Every apps/solutions have ExperimentalFeatures.props
2. All relevant project files have reference to the ExperimentalFeatures.props

Or equivalent,

**Comment by chrisglein** [comment]
We should ensure that the Hermes binaries aren't included in the app if the app doesn't end up using Hermes. It sounds like the intent here is to have things "Hermes ready" by default, not to have to pay for a javascript engine that isn't used.

Also assuming there's not a substantial cost in additional build time for this.

All that said, definitely want nuget-based apps to be able to Hermes.

**Comment by NickGerleman** [comment]
I believe this was resolved by https://github.com/microsoft/react-native-windows/pull/8225
