### ISSUE TITLE
React native consuming WCF service

### ISSUE THREAD

**Issue by DiogoSimaoMadeira** [microsoft/react-native-windows#8208]
Hi,

I am a beginer guy in WCF and React Native. I only have experience with react.js. But i like to know if it's possible to bind both  tools (wcf services+react native).
If is it possible, please let me know a little more about that. 
Many ThankS
Diogo

**Comment by asklar** [comment]
Hey @DiogoSimaoMadeira ! 

If I understand correctly WCF will take a web service description / metadata, and produce code-behind, that your client app can then use to call into the web service "as if" it were a local client API. 

Is your expectation to be able to take a WCF service description and use it from JS in a RN app? I don't believe we have that yet, but it should possible to generate bindings from it:
- read the WCF service description and parse it
- produce a RNW native module that exposes the described APIs, and implements them using the WinRT APIs

Here are some resources for calling into a WCF service from WinRT:
- https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/accessing-wcf-services-with-a-windows-store-client-app

**Comment by chrisglein** [comment]
Let us know if this answers your question. If so, we can close this.
