### ISSUE TITLE
Yoga does not consider Styles when computing Width/Height of a XAML control

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#8213]
See asklar/react-native-xaml#96

The default width for `<AppBarButton>` is coming from a `Style`. However, Yoga will just ask the control for its width who just gives back the "actual size", for example, 17px. However, AppBarButton has a default Style with a width of 68px.

## In a C# UWP XAML app:

![image](https://user-images.githubusercontent.com/22989529/125183497-c97daf00-e1cb-11eb-8e71-f161393378fa.png)

![image](https://user-images.githubusercontent.com/22989529/125183487-bff44700-e1cb-11eb-8f34-303febf532e0.png)

---

## In a RNW app:

![image](https://user-images.githubusercontent.com/22989529/125183509-d8646180-e1cb-11eb-8326-2a5ad0728ee8.png)

![image](https://user-images.githubusercontent.com/22989529/125183475-b074fe00-e1cb-11eb-88d4-5471e8f4698e.png)

**Comment by chrisglein** [comment]
The XAML Style is being clobbered by Yoga. This is part of a larger class of issues with the way the two layout systems are overlapping. See linked areas by label Area: Layout.

**Comment by chiaramooney** [comment]
Not something we plan to address on the Paper renderer as we move towards Fabric.
Fabric will not use XAML for the fundamentals of accessibility here, so this isn't applicable.
