### ISSUE TITLE
auto link not happening for the package in react native windows

### ISSUE THREAD

**Issue by ArunVenkat1994** [microsoft/react-native-windows#8227]
I have converted one package (react-native-fs) from older version into include few of my requirements.

When I include the package using package builder, it is linking properly.

    using Microsoft.ReactNative;
    using Microsoft.ReactNative.Managed;
    using System.Linq;
    using System.Reflection;

    namespace Test
    {
    public partial class ReactPackageProvider : IReactPackageProvider
    {
      public void CreatePackage(IReactPackageBuilder packageBuilder)
      {                      
        CreatePackageImplementation(packageBuilder);
        packageBuilder.AddViewManagers();
        packageBuilder.AddAttributedModules();
        packageBuilder.AddAttributedModules(Assembly.Load("RNFS"));
       }

       /// <summary>
      /// This method is implemented by the C# code generator
    /// </summary>
    partial void CreatePackageImplementation(IReactPackageBuilder packageBuilder);

    private Assembly GetAssemblyByName(string name)
    {
        var assemblies = Assembly.GetEntryAssembly().GetReferencedAssemblies();
        var assemblyName = assemblies.FirstOrDefault(i => i.Name == name);
        var assembly = Assembly.Load(assemblyName);
        return assembly;
      }
     }
     }
But I try to auto link the package, it is not happening.

can anyone suggest an approach for this?

react-native autolink is not helping.

**Comment by ArunVenkat1994** [comment]
Hi @asklar, 

The module is not newly created, we have taken older version of npm package - react-native-fs and converted. 
Followed the steps like we have for native module development. 
So it is more like an npm package. Right? 
I guessed, auto linking should work for this.

**Comment by asklar** [comment]
I think the easiest would be to create a new module just so that it writes out the right project files (.vcxproj if C++, .csproj if C#), and then copy those over to your project, match the name to your module, etc.
@jonthysell fyi

**Comment by chrisglein** [comment]
> The module is not newly created, we have taken older version of npm package - react-native-fs and converted.

react-native-fs has an old windows implementation, the updated one is [in PR](https://github.com/itinance/react-native-fs/pull/952). So that's likely a bad place to start with. Create it fresh and then you should be able to get autolinking. Let us know how that works out.
