### ISSUE TITLE
Unit other than px, while using styled-components crashes the application.

### ISSUE THREAD

**Issue by itsarnavsingh** [microsoft/react-native-windows#8237]
The problem is that it crashes without any error.

**Comment by asklar** [comment]
Could you please use the issue template and provide a repro so we can better understand what you are hitting?

**Comment by asklar** [comment]
See #6217 for more details

**Comment by itsarnavsingh** [comment]
React Native Version: 5.0.1

System:
OS: Windows 10 10.0.18363
CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Memory: 7.66 GB / 15.85 GB
Binaries:
Node: 12.18.0 - C:\Program Files\nodejs\node.EXE
Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
Watchman: Not Found
SDKs:
Android SDK:
API Levels: 29, 30
Build Tools: 28.0.3, 29.0.2, 30.0.3
System Images: android-30 | Google Play Intel x86 Atom
Android NDK: Not Found
Windows SDK:
AllowDevelopmentWithoutDevLicense: Enabled
AllowAllTrustedApps: Enabled
Versions: 10.0.17763.0, 10.0.18362.0, 10.0.19041.0
IDEs:
Android Studio: Version 4.0.0.0 AI-193.6911.18.40.6626763
Visual Studio: 16.10.31410.357 (Visual Studio Community 2019)
Languages:
Java: 1.8.0_275 - C:\Program Files\OpenJDK\openjdk-8u275-b01\bin\javac.EXE
npmPackages:
@react-native-community/cli: Not Found
react: 17.0.1 => 17.0.1
react-native: 0.64.2 => 0.64.2
react-native-windows: ^0.64.0-0 => 0.64.12
npmGlobalPackages:
react-native: Not Found

Target Device: Desktop
Visual Studio version: 2019

**Comment by asklar** [comment]
Fixed in 0.65 by #6837

**Comment by chrisglein** [comment]
With 0.65 releasing very soon, I think we're covered here. You can try the preview or wait for the official release or work around.
