### ISSUE TITLE
Error when building Playground solution: "type already exists"

### ISSUE THREAD

**Issue by lyahdav** [microsoft/react-native-windows#8244]
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`: `6.0.0-rc.0`
2. `npx react-native info`:
```
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19043
    CPU: (40) x64 Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz
    Memory: 168.31 GB / 190.60 GB
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.0-20190429.1820 - C:\open\fbsource\xplat\third-party\yarn\yarn.BAT
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
    Watchman: 20210712.090025 - C:\tools\watchman\watchman.EXE
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.17763.0, 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.10.31424.327 (Visual Studio Professional 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
info React Native v0.60.0 is now available (your project is running on v0.0.0-0d32aef3a).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.60.0.
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.0.0-0d32aef3a.
info To upgrade, run "react-native upgrade".
```

- What SDK version are you building for? 10.0.19041
- Target Platform Version(s): Windows 10 19043.928
What device(s) are you targeting? Choose any from Desktop, Xbox, Hololens)
- Target Device(s): Desktop
- Visual Studio Version: Visual Studio 2019
- Build Configuration: Debug x64

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Clone repo to commit 776c134cd601b819dcbd9b53e15bb42b461329eb.
2. Follow steps [here](https://github.com/microsoft/react-native-windows/blob/main/docs/building-rnw.md#running-the-playground-app) to run playground.sln

## Expected Results
App builds and runs. Instead I get build error with code MDM2009 from MDMERGE:
> Duplicate type Windows.Foundation.Metadata.NoExceptionAttribute found processing metadata file C:\Program Files (x86)\Windows Kits\10\References\10.0.19041.0\Windows.Foundation.FoundationContract\4.0.0.0\Windows.Foundation.FoundationContract.winmd, type already exists in file C:\Users\lyahdav\Documents\GitRepos\react-native-windows\vnext\target\x64\Debug\Microsoft.ReactNative\Windows.Foundation.winmd.

I thought maybe this was the same issue as https://github.com/microsoft/react-native-windows/issues/7226 but I still get the error if I build again.

## Snack, code example, screenshot, or link to a repository:
![Screen Shot 2021-07-13 at 3 57 05 PM](https://user-images.githubusercontent.com/359157/125536325-d5523903-9e7d-488b-881e-55418a70f630.png)

**Comment by asklar** [comment]
Known issue in the mdmerge tool. Workaround is to try again 🙃

**Comment by lyahdav** [comment]
I had tried that before but it didn't help. What did fix it was to do a "Clean Solution" first, and then it worked.
