### ISSUE TITLE
Add interface to pass root tag to IViewManager

### ISSUE THREAD

**Issue by rozele** [microsoft/react-native-windows#8250]
# Proposal: Add interface to pass root tag to IViewManager

## Summary
The UIManager module sends the `rootTag` to the `createView` native method. For view managers like `FlyoutViewManager`, we could use this `rootTag` value to look up the appropriate XamlRoot when creating XamlRoot dependent views like flyouts.

We might want to add something like `NativeUIManager::tryGetXamlRoot(int rootTag)` as well.

## Motivation

Currently, FlyoutViewManager gets the XamlRoot for the first root view created with a XamlRoot. This is error prone in multi-window apps, where we need to set the correct XamlRoot for views like flyouts.

**Comment by asklar** [comment]
Luckily, there's already a `CreateViewWithProperties` which would work for this :)

**Comment by asklar** [comment]
Another possibility: is the root tag associated with the react context 1:1? if so, we have [IViewManagerWithReactContext](https://microsoft.github.io/react-native-windows/docs/IViewManagerWithReactContext)

**Comment by chrisglein** [comment]
Problem with using `CreateViewWithProperties` is that `rootTag` would become a reserved word as this is going in alongside the JS properties.

Needs some design here. Eric's suggestion above may be just fine.

**Comment by rozele** [comment]
Re-opening, while #8327 is good progress, it does not yet solve the problem for ABI view managers. For that, we'll need to extend XamlUIService to support multiple root tags as well.
