### ISSUE TITLE
Prevent window focus stealing for auto focus scenarios

### ISSUE THREAD

**Issue by rozele** [microsoft/react-native-windows#8251]
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create a react-native-windows app on XAML islands that creates multiple windows on a single UI thread
2. Trigger auto focus for any of the following scenarios:
  a. FlyoutViewManager FlyoutBase instance Closing callback
  b. Call `View.focus()` imperatively from React Native JS
  c. Render a TextInput on a non-foregrounded window with autoFocus={true}

## Expected Results

It's not always clear what the expected results should be. For example, scenario 2a above can be incredibly annoying when the flyout closes when you switch windows (the focus immediately returns to the window you were trying to focus away from).

Scenario 2b and 2c are a bit less clear. Perhaps you want the window to focus when you imperatively focus a control in 2b. I doubt we'd ever want autoFocus to take focus the wrong window for TextInput autoFocus in 2c.

However, I think the developer needs to be afforded the opportunity to decide if they want the window to get focus. For example, if you want to imperatively focus a control on a non-foreground window, you should likely focus the window first, then the control. If we leave things the way they are, then the developer is always forced to focus the window simultaneously with the control.

**Comment by chrisglein** [comment]
Auto focus behavior is... weird. We've had some discussion on this in the past: #3372. We tabled it due to lack of specific need. Sounds like we may need to revisit that?
Win32 has a different approach here with more explicit focus rules: [see here](https://github.com/microsoft/react-native-windows/blob/main/packages/%40office-iss/react-native-win32/src/Libraries/Utilities/FocusManager.win32.js)

**Comment by rozele** [comment]
@chrisglein - I have a PR that solves this in general through a quirk setting, but the win32 "polite vs. aggressive" focus options is intriguing. Can you share a pointer to where that is implemented for win32?

**Comment by chrisglein** [comment]
> @chrisglein Chris Glein FTE - I have a PR that solves this in general through a quirk setting, but the win32 "polite vs. aggressive" focus options is intriguing. Can you share a pointer to where that is implemented for win32? My approach does not support an "aggressive" focus.

I believe it was @acoates-ms that pointed out the different focus handling. Andrew, can you point Eric at the interesting bits?
