### ISSUE TITLE
Move additional unit tests to Shared

### ISSUE THREAD

**Issue by matthargett** [Microsoft/react-native-windows#826]
Some classes were moved to Shared, but their tests weren't moved to Shared.Tests (NativeModuleBaseTests, PromiseTests, etc). Do a pass through the existing Tests and move things to Shared.Tests where reasonable.

**Comment by GantMan** [comment]
on this, btw.  If you want to assign :D

**Comment by GantMan** [comment]
https://github.com/ReactWindows/react-native-windows/pull/837

Let's discuss later

**Comment by rozele** [comment]
Closing - we'll eventually move to .NET Standard in which case we can "unshare" the tests.
