### ISSUE TITLE
Allow us to disable back button behavior upfront

### ISSUE THREAD

**Issue by namrog84** [microsoft/react-native-windows#8262]
https://github.com/microsoft/react-native-windows/blob/0f90f13dd3da3b01ba0c3d4e8b077638cd0bb341/vnext/Microsoft.ReactNative/ReactRootView.cpp#L354

In some situations, it appears like the back button from RNW is reacting to back buttons when we don't want it too.

Allow us to disable RNW's registering of backbutton via a RN config at app launch. (and/or toggle-able at runtime)

I don't see a way to currently disable this GoBack behavior thru RNW. Please add feature flag.

**Comment by acoates-ms** [comment]
Core does some pretty gross things, where the event always goes to JS.  Then if none of the JS handlers mark the event as handled, then JS sends an command back to native to trigger a back navigation.  There doesn't appear to be a way for windows apps to trigger a back command manually.  

We might be able to achieve this will synchronous methods, where we can fire the JS event and find out if it handles the event or not immediately.  Not sure what we'd do while web debugging in the mean time.  -- Also not sure we want to introduce that behavior.

In the meantime, adding an opt out flag seems a reasonable workaround.

**Comment by chrisglein** [comment]
Might be some hooks to coordinate with react-navigation? Worth considering into whatever mechanism we decide on here to opt out.
