### ISSUE TITLE
Remove Picker Component from React Native Windows

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-windows#8264]
# Proposal: Remove Picker Component from React Native Windows

## Summary
All other ejected components have been removed or have a PR in progress to remove them. Creating issue to track work item of ultimately removing Picker and remainder of PickerWindows code from React Native Windows. 

## Motivation
Finish out Lean Core work. #4454

**Comment by NickGerleman** [comment]
There has been an open PR out for a while to remove PickerWindows, and the Windows specific version of DatePicker. https://github.com/microsoft/react-native-windows/pull/7685

**Comment by NickGerleman** [comment]
We may not rant to remove the raw Picker just yet, because it is still provided on Android/iOS. So xplat projects might assume we still provide it as well.

**Comment by chrisglein** [comment]
In the past we found that [it was still there](https://github.com/microsoft/react-native-windows/issues/4611#issuecomment-673056967). Used for internal tests and such. When Facebook removes it we definitely want to remove it too... but we need to make sure it's gone. And... not spotting it now so it does seem like we can remove it! (assuming _we_ have no remaining dependencies on it)
