### ISSUE TITLE
AppTheme.removeListener should not be marked as deprecated

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#8269]
Some AppTheme functionality that overlapped with Appearance was deprecated, then removed. High contrast functionality still exists in AppTheme though, as it does not yet have a documented alternative (though maybe we could push folks towards PlatformColor?).

The pattern of registering and removing high contrast listeners shows that removing a listener for any event is deprecated, while adding a listener is not. This is very visible in VS Code, which can create confusion.

![image](https://user-images.githubusercontent.com/835219/126195261-eb931088-be04-46b1-bbba-1bafe4053bc9.png)

**Comment by chrisglein** [comment]
Side note: This is all that's left on `AppTheme` at this point. Is the right place for these events? This predated `PlatformColor` and the `Appearance` module. Seems like there would be better places and then `AppTheme` can be required.

Does this report all high contrast theme information (Do seem to work via #8200, but is the right information carried through)?

**Comment by chrisglein** [comment]
@NickGerleman Seems like the example may just need to be updated. Link to that here and close out.

**Comment by NickGerleman** [comment]
Yeah, `removeListener` is deprecated on the emitter in general, but we have broken typings for removing the event subscription. Will fix that in a separate PR.
