### ISSUE TITLE
move more classes to Shared

### ISSUE THREAD

**Issue by matthargett** [Microsoft/react-native-windows#827]
Several classes that seemed impossible to move to Shared before now have all their former dependencies in Shared. Do a pass through and move the next wave of low-hanging fruit (and their tests, when possible) to Shared (e.g. ReactInstance, NativeModuleRegistry, etc).

**Comment by rozele** [comment]
@matthargett can you create a specific label or milestone to tag these with?

**Comment by rozele** [comment]
Closing - the goal is to move things to .NET Standard over time rather than more shared code.
