### ISSUE TITLE
react-native-windows-init fails following the GetStarted page instructions

### ISSUE THREAD

**Issue by aarongomez1** [microsoft/react-native-windows#8274]
Followed the instructions from: 
[https://microsoft.github.io/react-native-windows/docs/getting-started]

Run: **_react-native-windows-init --overwrite_**

I get the following output.

_Reading project name from package.json...
Reading react-native version from node_modules...
Error: No version of react-native-windows@latest found
NoLatestReactNativeWindows: Error: No version of react-native-windows@latest found
    at getLatestRNWVersion (C:\Users\gomezaa\AppData\Local\npm-cache\_npx\966c6a96be6f5a32\node_modules\react-native-windows-init\src\Cli.ts:249:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at C:\Users\gomezaa\AppData\Local\npm-cache\_npx\966c6a96be6f5a32\node_modules\react-native-windows-init\src\Cli.ts:404:36 {
  data: undefined
}_

How do I get it to work?

**Comment by aarongomez1** [comment]
I just got it to work.  I tried adding logging statements to get more details and saw that when it was getting back E_NOTFOUND when calling on registry.npmjs.org to find 'react-native-windows@latest'.

After some trial and error I tried passing the --version flag to pass the latest version and then it was able to run successfully.

There should probably be a  change somewhere so that the default instructions on the react native windows website work.

**Comment by NickGerleman** [comment]
The npmjs registry can sometimes be a bit flakey, which I'm guessing is what happened here. I tried to replicate the error by running the command the CLI does (`npm info react-native-windows@latest version --json`) and I do seem to get the correct result. Going to close this out as external service flakiness, but we should reopen if others hit this.
