### ISSUE TITLE
Missing Mechanism to Expose Right Click

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#8275]
@kikisaints @NickGerleman Kicking this. There needs to be a mechanism to surface right-click (and other mouse buttons). Right now Garrison is hacking overrides into RNW to undo #4878 so that onPress continues to fire for all buttons (we then use the event args to determine the button that was pressed).

I'm ok with "onPress" being strictly equivalent to web's "click" event (meaning it only fires for left mouse button). But we need an equivalent to web's "[auxclick](https://developer.mozilla.org/en-US/docs/Web/API/Element/auxclick_event)". 

onPointerDown/onPointerUp should also be added (and fire for all pointer buttons), but I don't know if onPointerUp is strictly equivalent to click/auxclick in.

_Originally posted by @aschultz in https://github.com/microsoft/react-native-windows/issues/6299#issuecomment-882911330_

**Comment by NickGerleman** [comment]
Related to what @aschultz proposed, we should check to see what react-native-web/react-native-win32 is doing.

**Comment by chrisglein** [comment]
@rectified95 and @stmoy FYI
This is remaining fallout from the mouse proposal doc that wasn't finished and is impacting some partners.

**Comment by aschultz** [comment]
@chrisglein @NickGerleman Any word on this?

**Comment by chrisglein** [comment]
> @chrisglein @NickGerleman Any word on this?

This is something we are tracking on our 2022 Jan-May schedule. Returning now in the new year we'll be vetting that and getting more specific on timelines.

**Comment by rozele** [comment]
For what it's worth, we also removed #4878 in Messenger.

**Comment by rozele** [comment]
One discussion @necolas (react-native-web) and I had a few months back is that it would be great for the pointer APIs in React Native to better align with the W3C Pointer APIs spec: https://www.w3.org/TR/pointerevents/

**Comment by rozele** [comment]
Perhaps with some of the elements of the MouseEvent API (e.g., `details`): https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent

If we're solving for right-click, which is likely to require some changes to core APIs, e.g., Pressability, we may want to also solve for double click, triple click. Currently the only way to implement double click is to read a Windows config through a native module and track time delta in JS, which leads to issues like needing to persist click events.

**Comment by chrisglein** [comment]
Notes from planning poker:
> The goal is whatever we do here should be forward compatible, but does _not_ block on the entire unification of the mouse story across mac/web/etc.. We can choose one of 3 payload mechanisms that already exist - need to plumb the onclick. If both onclick and onpress are used at the same time there's complexity. Expect that there's a lot of time aligning/communicating with partners (PM time yes, but also dev time).
This used to work and was disabled - can we not just revert to the previous behavior? Was that a specific partner and can we request they fork instead of everyone that needs a right click fork? Given the back and forth on design, is there an above average amount of tests + docs needed for this? (don't document what deviates from the norm, but may need additional partner interaction to clarify the new plan)
> Consensus: a couple of days to close on the approach. If revert, very fast. If not, and we need to build out some onclick, it's more.
