### ISSUE TITLE
How to use react-native-windows to support multiple screens to display different contents

### ISSUE THREAD

**Issue by Dean-Qian** [microsoft/react-native-windows#8309]
How to use react-native-windows to create an application that supports multiple displays (for example, we are developing an application for the POS  in the supermarket, which has two screens to display different contents. **We want to support the display of different contents on different screens in one application at the same time**.)

**Comment by chrisglein** [comment]
At the end of the day, React Native for Windows relies on the infrastructure of the Universal Windows Platform (UWP) to create apps. So another way to phrase this question is "How to create a UWP application that supports multiple displays." You might find some helpful information there with some searches (a quick one got me [this](https://stackoverflow.com/questions/48618937/multi-window-full-screen-apps-in-uwp) for example). But I believe the short is you can use ApplicationView to set up different windows for different monitors and render to each. Currently nothing in React Native for Windows is going to make that easier for you, however. You'll need to drop into native UWP code to set that up.

There is one React Native solution here that might be useful as a reference for you, if nothing else: https://github.com/microsoft/react-native-dualscreen/. This library was built specifically for devices like the Surface Duo that has identically sized screens, and where you want help handling rotation scenarios and such. I believe done with one window that spans both screens. That might not be your scenario.

Hopefully that's helpful? If you let us know more details about your scenario we might be able to help more. Let us know.

**Comment by Dean-Qian** [comment]
> At the end of the day, React Native for Windows relies on the infrastructure of the Universal Windows Platform (UWP) to create apps. So another way to phrase this question is "How to create a UWP application that supports multiple displays." You might find some helpful information there with some searches (a quick one got me [this](https://stackoverflow.com/questions/48618937/multi-window-full-screen-apps-in-uwp) for example). But I believe the short is you can use ApplicationView to set up different windows for different monitors and render to each. Currently nothing in React Native for Windows is going to make that easier for you, however. You'll need to drop into native UWP code to set that up.
> 
> There is one React Native solution here that might be useful as a reference for you, if nothing else: https://github.com/microsoft/react-native-dualscreen/. This library was built specifically for devices like the Surface Duo that has identically sized screens, and where you want help handling rotation scenarios and such. I believe done with one window that spans both screens. That might not be your scenario.
> 
> Hopefully that's helpful? If you let us know more details about your scenario we might be able to help more. Let us know.

Thanks！I will try。
