### ISSUE TITLE
Transform prop not applied

### ISSUE THREAD

**Issue by hailey822** [microsoft/react-native-windows#8330]
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`: 5.0.1
2. `npx react-native info`:

> System:
    OS: Windows 10 10.0.17763
    CPU: (2) x64 Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
    Memory: 441.86 MB / 4.00 GB
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.16299.0, 10.0.17134.0, 10.0.17763.0, 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.7.30413.136 (Visual Studio Enterprise 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.0 => 0.64.0
    react-native-windows: ^0.64.0-0 => 0.64.14
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.
1. Installed sample app following [RNW docs](https://microsoft.github.io/react-native-windows/docs/getting-started)
2. Inserted styling for view `<View
          style={{
            transform: [{rotate: '-90deg'}],
          }}>`

## Expected Results
Component to be rotated. 
Other stylings are applied properly, but transform property is not applied. 

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by NickGerleman** [comment]
@hailey822 the transform prop is not supported on versions of Windows 10 before 1903 (May 2019). Are you able to update to a newer version of Windows?

See this table for reference https://microsoft.github.io/react-native-windows/docs/win10-compat
