### ISSUE TITLE
Does RNW support libraries to do these tasks?

### ISSUE THREAD

**Issue by nguyenctu** [microsoft/react-native-windows#8334]
Hello, currently I'm working on a desktop application project using RNW. After a huge amount of time to search and test libraries. Now I think I should ask you guys directly for quick answer. I wonder if RNW support libraries to do:
1. Document picker (currently I'm unable to use [react-native-document-picker](https://github.com/rnmods/react-native-document-picker) because of the build errror after installing it, as I report the issue in [8322](https://github.com/microsoft/react-native-windows/issues/8322))
2. Read csv/excel file (get sheet, column, row,.etc...).
3. Barcode (code128) generating.
If there are libraries to do tasks above please let me know their name. Or if currently there're no library that support RNW to do these tasks please let me know too.
Thank you so much!

**Comment by chrisglein** [comment]
Your best option to answer "does RNW support X" is the [React Native Directory](https://reactnative.directory/?windows=true). You can look at what modules support Windows. If there's one that meets your needs but doesn't support Windows you can log an issue on that repo, and one here using the issue template (which is mainly used for tracking - we don't have bandwidth to implement new module support). Implementing these will generally be a matter of answering how to accomplish whatever it is using the Universal Windows Platform (UWP) APIs, or Win32 APIs if your app is running in a XAML Island (not the golden path, but is doable). For that you'll have to poke around with some searches. I don't know of anything for bringing in CSV/Excel in the RNW catalog, or for barcode generating (as for reading I'm pretty sure the camera module that supports RNW does do that - you can poke into the module implementation to see if what is uses to read could also do writing).

Hopefully that's helpful!
