### ISSUE TITLE
RN Integration Schedule

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#8353]
This issue tracks the schedule for integrations from https://github.com/facebook/react-native/ to https://github.com/microsoft/react-native-windows. The goal is that RNW's main doesn't lag further behind RN's main by more than a week. Integrators will do 1 integration per week.

Contributions to improve automation of the process are welcome, although at this point the process is pretty well automated so there are likely diminishing returns.

[Integration Process](https://github.com/microsoft/react-native-windows/wiki/Integration-Process)

Integrators not on duty for the current rotation are expected to help out with PR reviews.

| Month | Integrator |
| --- | --- |
| August 2021 | @NickGerleman |
| September 2021 | @rectified95  / @chiaramooney |
| October 2021 | @NickGerleman |
| November 2021 | @rectified95  / @chiaramooney |
| December 2021 | @NickGerleman |
| January 2022 | @chiaramooney |
| February 2022 | @chiaramooney / @TatianaKapos  |
| March 2022 | @chiaramooney  / @TatianaKapos |
| April 2022 | @chiaramooney  / @TatianaKapos |

**Comment by chrisglein** [comment]
@NickGerleman Can you copy the process that's currently covered in PR comments to the wiki [here](https://github.com/microsoft/react-native-windows/wiki/Integration-Process)? (@rectified95 / @chiaramooney, if you have any of that copied somewhere else or have other tips please add that to the wiki page)

**Comment by chiaramooney** [comment]
Updated Wiki page with steps for integration.

**Comment by chiaramooney** [comment]
Going to close this issue now, since the integration hand off is handled within the WinDev RNW team
