### ISSUE TITLE
Problem with LaunchFolderAsync

### ISSUE THREAD

**Issue by hondek** [microsoft/react-native-windows#8390]
Hi,

When i try launch folder in explorer like this:
`co_await Windows::System::Launcher::LaunchFolderAsync(Windows::Storage::KnownFolders::VideosLibrary());`

It work on RNW 0.63.0-0
But on RNW 0.64.0-0 i always getting error from native module: 

`A method was called at an unexpected time.`

please help ;)

**Comment by chrisglein** [comment]
Our guess is that you're calling this from the wrong thread. This needs to be invoked from the UI thread, not the JS thread. Between 0.63 and 0.64 there was a change in the default threading behavior, which explains the change you're seeing. Dispatch and you should be good to go.
