### ISSUE TITLE
TextHighlighter is not removed when backgroundColor prop is removed

### ISSUE THREAD

**Issue by rozele** [microsoft/react-native-windows#8407]
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create an example that removes sets and removes `backgroundColor` from nested text. E.g.:
```js
  const [backgroundColor, setBackgroundColor] = useState();
  ...
  <Text onPress={() => setBackgroundColor(backgroundColor ? undefined : 'yellow'}>
     <Text style={{backgroundColor}}>
        This
      </Text>
      text {backgroundColor ? 'should' : 'shouldn't' be highlighted.
   </Text>
```
2. 

## Expected Results
When backgroundColor prop is removed, TextHighlighter should be removed.

## Snack, code example, screenshot, or link to a repository:

https://user-images.githubusercontent.com/1106239/129052237-d7d168fb-92ac-43a3-a786-b9a780d1557e.mp4

## Notes

This is likely related to #7569

**Comment by chrisglein** [comment]
@chiaramooney another issue with backgroundColor not being applied, FYI
