### ISSUE TITLE
Test run hangs after executing a WebSocketModule test

### ISSUE THREAD

**Issue by pre10der89** [Microsoft/react-native-windows#841]
Have observed the test run hanging after executing one of the WebSocketModule tests... Have seen this happen immediately after the WebSocketModule_OpenClosedEvent test passes (test icon changes to green checkmark).  The unit test application does not close.

Have also seen this on WebSocketModule_DataEvent

**Comment by matthargett** [comment]
I can reproduce this when randomizing the order of tests run. Looks like some global mutable state or event gets messed up by another integration-level test? Almost never happens in the debugger, so I'm having difficulty nailing it down.

**Comment by rozele** [comment]
No repro + inactivity = closing for now.
