### ISSUE TITLE
[0.64] ScrollViewManager is missing handler for 'focusable' prop

### ISSUE THREAD

**Issue by aschultz** [microsoft/react-native-windows#8423]
The `focusable` prop is used to toggle the IsTabStop property on a component. This prop is exposed on ScrollViewProps (by way of inheriting from ViewProps) and supported by ViewViewManager, but appears to be missing from the ScrollViewManager inheritance chain.

The effect is that there's no way to mark a ScrollView as focusable. This is needed if a ScrollView has no focusable children (say, only text) in order to provide a target to tab to and then use other keys to scroll.

I suggest adding a handler to ControlViewManager since it's the parent class that already has a handler for tabIndex.

**Comment by chrisglein** [comment]
Scenario here is a big block of non-interactive content (like a wall of text) so the only thing to put focus on is the scroller itself?
(I assume this stops working as well as soon as there is one element that takes focus inside the scroller)

**Comment by aschultz** [comment]
Yep, this specifically affects ScrollView when it has no focusable children. The ScrollView itself needs to be made a tab stop so it can be navigated to and then other keys (PageUp/Down, Arrow Keys) will work on it.

If there *is* a focusable child, you can tab to that child and once it has focus the other keys will bubble, so there's less need for making the ScrollView itself focusable.

**Comment by Brouilles** [comment]
I can't find out which version the commit is in. Because it does not seem to be implemented in version 0.65.2
