### ISSUE TITLE
[0.64] Crash in NativeUIManager when dropping a TextInput that has yet to be processed by DoLayout

### ISSUE THREAD

**Issue by aschultz** [microsoft/react-native-windows#8441]
When `NativeUIManager::CreateView` processes a component that requires forced layout (ShadowNode.NeedsForceLayout), such as TextInput, it adds the node's tag to `m_extraLayoutNodes`.

That list is then processed during the next run of `NativeUIManager::DoLayout`, which retrieves the shadow node corresponding to the ID, calls UpdateLayout on it, and then clears the list.

If the component is removed from the tree before DoLayout is called, it is *not* removed from `m_extraLayoutNodes`. DoLayout performs a lookup on the node using `GetShadowNodeForTag`, which throws an exception because the tag is not in the map. 

### Expected Results
The removed node is ignored and the app does not crash.

### Potential Solutions
A) Use `FindShadowNodeForTag` within DoLayout instead, which will return nullptr if the node has been removed. Work on the node can then be skipped.

B) Add code to RemoveView that removes tags from `m_extraLayoutNodes`.

(A) should be more performant, as it only requires swapping out the existing lookup operation for one of equal complexity. (B) requires iterating the entire `m_extraLayoutNodes` list every time any node is removed and selectively removing specific values.

**Comment by NickGerleman** [comment]
Sounds like there is a well defined solution here. PRs are definitely welcome 🙂.
