### ISSUE TITLE
How can i add react-native-fs module to the react-native-windows project ?

### ISSUE THREAD

**Issue by mrityunjay-1** [microsoft/react-native-windows#8442]
Documentation says that we have to add "RNFS.csproj" to the project solution. I may do it in a wrong way that's why my build is always failed build exeecuted with status code 1 and says  "Building Solution returned error code 1. Check your build configuration". Please help !

**Comment by asklar** [comment]
@mrityunjay-1 The Windows support hasn't been merged to react-native-fs yet, it's still pending in this PR: https://github.com/itinance/react-native-fs/pull/952

The existing Windows implementation in the react-native-fs repo won't work with recent React Native for Windows versions.

**Comment by chrisglein** [comment]
Yep, still pending. Here's the issue tracking this: #2829.

**Comment by exotexot** [comment]
However, the referenced PR is working just fine!
