### ISSUE TITLE
Add mechanism to synchronize community module and application Windows SDKs

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#8443]
Users need to manually install Windows SDKs, either through the VS installer, dependencies script, or website. We bumped our own version to the current version provided by VS, but community modules currently hardcode their own version to rely upon (10.0.16299.0 for most of the ecosystem). WinMD format between SDKs does not seem to always be perfectly backwards compatible, but having multiple SDKs is a DevX pain as well.

**Comment by chrisglein** [comment]
This was cleaned up through ExperimentalFeatures in #7414. If all the modules are using the import it'd be fine. Is the fix here to update the modules to the modern templates? How much work needs to be done to patch each module?
Info on the website here: [Customizing SDK Versions](https://microsoft.github.io/react-native-windows/docs/next/customizing-sdk-versions)

@jonthysell you have a PR that didn't make 0.65.0 to update the templates. Can you link here? That's the template version we need, correct?

**Comment by chrisglein** [comment]
Meta commentary: The file is named ExperimentalFeatures but we have a mix of versioning information and experimental stuff in there.

**Comment by NickGerleman** [comment]
Not sure how much appetite there was to contribute further fixes to this when we discussed it.

I have an idea for a potential clean solution to this. Going to PR later today.
