### ISSUE TITLE
Changing the color of the Switch component doesn't work till mouse hovers over/away from component

### ISSUE THREAD

**Issue by paperbackdragon** [microsoft/react-native-windows#8476]
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`: 4.14.0
2. `npx react-native info`:
```
System:
    OS: Windows 10 10.0.22000
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Memory: 42.87 GB / 63.93 GB
  Binaries:
    Node: 12.22.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.17763.0, 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7042882
    Visual Studio: 16.10.31424.327 (Visual Studio Enterprise 2019)
  Languages:
    Java: Not Found
    Python: 3.9.4 - C:\Python39\python.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
    react-native-windows: 0.63.35 => 0.63.35
  npmGlobalPackages:
    *react-native*: Not Found
```
What device(s) are you targeting? Choose any from Desktop, Xbox, Hololens)
- Target Device(s): Desktop

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create a Switch component that changes color, either when it's toggled or by an external event such as a button press
2. Try changing the color (toggle the Switch or trigger the change another way)
3. Sometimes colors are not changed until your mouse has moved away or back to the Switch component itself

## Expected Results
Colors should change as they are programmed to.

## Snack, code example, screenshot, or link to a repository:
https://snack.expo.dev/@heatherhb/switch-color-issue

In this example, notice that:
* When toggling the switch, the thumbColor doesn't change until the mouse moves away.
* After clicking the "Change colors" button, the track _and_ thumb colors don't change until the mouse moves on top of the Switch itself.

Note that this does not repro in the "Web" section of the snack.expo.dev website, it needs to be loaded into an RN app and run on windows.

**Comment by AgneLukoseviciute** [comment]
@rectified95

**Comment by AgneLukoseviciute** [comment]
@rectified95
