### ISSUE TITLE
Logic to choose between WinUI2 and WinUI3 should be in targets, not C# app template

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#8486]
Starting in 0.65 we added the following logic into the C# app template:

```xml
<Choose>
    <When Condition="'$(UseWinUI3)'!='true'">
      <ItemGroup>
        <PackageReference Include="Microsoft.UI.Xaml" >
          <Version>$(WinUI2xVersion)</Version>
        </PackageReference>
      </ItemGroup>
    </When>
    <Otherwise>
      <ItemGroup>
        <PackageReference Include="Microsoft.WinUI">
          <Version>$(WinUI3Version)</Version>
        </PackageReference>
      </ItemGroup>
    </Otherwise>
  </Choose>
```

This logic should really have been in the target files and not added to the template. It'll now be a breaking change to remove but I think it'll be necessary to support the work for PackageReference and community modules building off the nugets.

**Comment by chrisglein** [comment]
Will want to consolidate alongside other template breaking changes such as #8195.
Question exists about what happens if you end up with both (the app has the PackageReference _and_ the targets have the reference). If that doesn't break, then we can do this earlier. @JunielKatarn do you happen to know what happens with redundant PackageReferences?

**Comment by chrisglein** [comment]
Assuming we're not backporting the recent addition of PackageReference back to 0.67 (it went in after the snap, right?), then this would be for 0.68. @jonthysell to confirm.

**Comment by jonthysell** [comment]
Yes, this should be part of 0.68.

**Comment by jonthysell** [comment]
Nevermind, there's a bunch of stuff that could be cleaned up and normalized thanks to the PackageReference changes.

**Comment by jonthysell** [comment]
PR is currently blocked

**Comment by JunielKatarn** [comment]
> PR is currently blocked

A current workaround is building from the command line (MSBuild.exe).
