### ISSUE TITLE
Missing behaviors for "pointerEvents" prop

### ISSUE THREAD

**Issue by rozele** [microsoft/react-native-windows#8496]
There are a couple issues with `pointerEvents`:
1. `pointerEvents` should be applicable to any RN component that derives from View (e.g., Image, Text, etc.)
2. `pointerEvents` is not implemented for `"box-none"` and `"box-only"`.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

For the former issue, add an example to RNTester like:
```js
  <Text onPress={() => console.log('Pressed')} pointerEvents="none">
    Absolutely not pressable text.
  </Text>
```
If you click on the Text, you should not get a `console.log`, but you still do in the current state of react-native-windows.

For the latter issue of missing implementations for `"box-none"` and `"box-only"`, you can repro from RNTester:
1. Run the Pointer Events example in RNTester
2. Scroll down to the `"box-none"` and `"box-only"` examples, try to click grayed out views that should not respond to events and observe that events still fire.

## Expected Results

Pointer events should work on arbitrary view types that expect View props, and the behaviors for `"box-none"` and `"box-only"` should match iOS and Android.

## Snack, code example, screenshot, or link to a repository:

Here's a video repro of the non-`<View />` `pointerEvents` being ignored:

https://user-images.githubusercontent.com/1106239/131182075-cf8195d1-ca94-4e30-8c4b-c88ae0cf2ba0.mp4

Here's a video repro of the `"box-none"` and `"box-only"` issues:

https://user-images.githubusercontent.com/1106239/131181259-6867ee36-0ee5-42d7-9c54-642f84f0a398.mp4

**Comment by chrisglein** [comment]
@rozele you didn't link #8500 to this. Is it intended to address any of these issues?
