### ISSUE TITLE
Cannot run command "react-native run-windows"

### ISSUE THREAD

**Issue by NetSpud** [microsoft/react-native-windows#8502]
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`:
`6.0.0`
2. `npx react-native info`:
```
System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 AMD Ryzen 7 3800X 8-Core Processor
    Memory: 10.27 GB / 15.95 GB
  Binaries:
    Node: 14.15.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.20.6 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7199119
    Visual Studio: 16.10.31515.178 (Visual Studio Community 2019)
  Languages:
    Java: 1.8.0_211 - C:\Program Files\Java\jdk1.8.0_211\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.65.0 => 0.65.0
    react-native-windows: 0.65.0 => 0.65.0
  npmGlobalPackages:
    *react-native*: Not Found
```
Running on a Windows 10 x64 machine
Using default config
Have run the powershell command from https://microsoft.github.io/react-native-windows/docs/rnw-dependencies with no problems

## Steps To Reproduce

Follow the steps provided by the docs: https://microsoft.github.io/react-native-windows/docs/getting-started 
I am following the `Without Using Visual Studio` path.
When I reach the stage of running the command `npx react-native run-windows` I get this error:
```
error listen EACCES: permission denied 0.0.0.0:8081.
Error: listen EACCES: permission denied 0.0.0.0:8081
    at Server.setupListenHandle [as _listen2] (net.js:1301:21)
    at listenInCluster (net.js:1366:12)
    at Server.listen (net.js:1452:7)
    at D:\Downloads\test\test\node_modules\metro\src\index.js:164:16
    at new Promise (<anonymous>)
    at Object.exports.runServer (D:\Downloads\test\test\node_modules\metro\src\index.js:163:10)
    at Object.runServer [as func] (D:\Downloads\test\test\node_modules\@react-native-community\cli\build\commands\start\runServer.js:113:26)
    at Command.handleAction (D:\Downloads\test\test\node_modules\@react-native-community\cli\build\index.js:186:9)
info Run CLI with --verbose flag for more details.
```
I've tried running with elevated permissions, but the same result occures.
It does work when adding `--ignore-existing` to the `npx react-native init` command though.
## Expected Results
To be able to run the application

## Snack, code example, screenshot, or link to a repository:

![image](https://user-images.githubusercontent.com/56541762/131225838-8bf95451-ca30-465a-a705-e6157b9f0b5b.png)

**Comment by chrisglein** [comment]
> It does work when adding --ignore-existing to the npx react-native init command though.

That's curious. That command is used to skip over previously existing global installations. Do you maybe have some previous installs of RN or its dependencies that it was picking up?

You can see what's globally installed using this command:
`npm list -g`

The error itself looks like it's coming from metro. Curious about which version you're getting.

Based on your comment above about `ignore-existing`, does everything work fine from that point on?

**Comment by NetSpud** [comment]
> Based on your comment above about ignore-existing, does everything work fine from that point on?

Yes, once I use that, everything else works as expected.

My global installations looks like this:

```
+-- @react-native-community/cli@5.0.1
+-- androidjs-builder@2.2.4
+-- cordova@10.0.0
+-- eas-cli@0.23.0
+-- electron@11.2.3
+-- eslint@7.28.0
+-- expo-cli@4.3.2
+-- express-generator@4.16.1
+-- nativefier@42.2.1
+-- nativescript@8.0.1
+-- node-dev@6.7.0
+-- nodemon@2.0.9
+-- npm-dts@1.3.9
+-- npm-windows-upgrade@6.0.1
+-- npm@7.20.6
+-- postcss-cli@8.3.1
+-- sails@1.4.0
+-- sass@1.32.11
+-- serve@11.3.2
+-- tsc-node@0.0.3
+-- vercel@23.0.1
`-- yarn@1.22.10
```
I don't seem to have metro installed within my `package.json` or globally, so how would I find the version for that? 
Sorry!

**Comment by acoates-ms** [comment]
Yeah, you should remove `@react-native-community/cli` from your global install.  The version of `@react-native-community/cli` should come from the version of `react-native` being used.  In this case `@react-native-community/cli@5.0.1` is not compatible with `react-native@0.65`
