### ISSUE TITLE
NuGet.config is vulnerable to supply chain attack

### ISSUE THREAD

**Issue by qmatteoq** [microsoft/react-native-windows#8529]
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`: 6.0.0
2. `npx react-native info`:

```
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 3.41 GB / 15.60 GB
  Binaries:
    Node: 14.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.14393.0, 10.0.15063.0, 10.0.17134.0, 10.0.17763.0, 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.31624.102 (Visual Studio Enterprise 2019), 17.0.31612.314 (Visual Studio Enterprise 2022), 16.11.31624.102 (Visual Studio Enterprise 2019)
  Languages:
    Java: 11.0.10 - C:\Program Files\Microsoft\jdk-11.0.10.9-hotspot\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.65.1 => 0.65.1
    react-native-windows: 0.65.1 => 0.65.1
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create a new React Native project
2. Add Windows support
3. Open the NuGet.config file included in the windows folder.

## Expected Results
The NuGet.config file should contain only a single feed source, to mitigate supply chain attacks. Instead, it contains two feeds: one for the public NuGet feed and one for an Azure Artifact feed.
This configuration makes impossible to create a CI/CD pipeline on Azure Pipelines to build a RNW app, since the NuGet Security Analysis build task which is automatically injected will detect this configuration as a vulnerability and it will prevent the pipeline to continue.

**Comment by chrisglein** [comment]
The Azure Artifact feed is used for daily builds, which aren't signed. Otherwise we could just use the public NuGet feed and discard the other. We may need to introduce new guidance for those who want to get daily canary builds. Alternatively we could sign the daily builds and push those to NuGet.

**Comment by NickGerleman** [comment]
@qmatteoq for your builds you should be able to remove the non-NuGet.org line and everything should just work we think.
