### ISSUE TITLE
`tabbar` AccessibilityRole

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#8536]
https://github.com/facebook/react-native/commit/11f8d9c7cd4bae0b1a5e880ea9b2da7447ad76c2 adds a new `tabbar` AccessibilityRole. There does not seem to be a directly corresponding [AutomationControlType](https://docs.microsoft.com/en-us/dotnet/api/system.windows.automation.peers.automationcontroltype?view=net-5.0). Need investigation on what our implementation should look like, or if we should implement this.

_Originally posted by @NickGerleman in https://github.com/microsoft/react-native-windows/issues/8535#issuecomment-911477553_

**Comment by chrisglein** [comment]
Not sure what this maps to on Windows. Need to look at what `tabbar` is and whether that maps to NavigationView's tabs or Pivot or TabView control or whatever.

**Comment by AgneLukoseviciute** [comment]
Closest thing to the [iOS Tab Bar ](https://developer.apple.com/design/human-interface-guidelines/ios/bars/tab-bars/) is probably the [Tab Control](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.tabcontrol?view=net-5.0). I think we could just handle this in DynamicAutomationPeer to return AutomationControlType::Tab when "tabbar" is specified as the role.
