### ISSUE TITLE
Update to Hermes 0.9

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#8537]
FB cut Hermes 0.9 to use with RN 0.66, containing about four months of changes since 0.8. 0.8 is still compatible with 0.66 from an interface perspective, but we will want to align with the newer Hermes version before we release.

**Comment by mganandraj** [comment]
https://github.com/microsoft/react-native-windows/commit/2afad93679990d06cec763bd6c12ce44efef0c4a
