### ISSUE TITLE
Multipart file upload header problem

### ISSUE THREAD

**Issue by MarcinNowak-codes** [microsoft/react-native-windows#8547]
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`: 5.0.1
2. `npx react-native info`: 

```
System:
    OS: Windows 10 10.0.19042
    CPU: (24) x64 Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz
    Memory: 47.09 GB / 63.96 GB
  Binaries:
    Node: 14.17.5 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.14 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7621141
    Visual Studio: 16.11.31624.102 (Visual Studio Community 2019)
  Languages:
    Java: 1.8.0_171 - C:\Program Files\Java\jdk1.8.0_171\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.0 => 0.64.0
    react-native-windows: 0.64.16 => 0.64.16
  npmGlobalPackages:
    *react-native*: Not Found
```

What SDK version are you building for? Choose from 10.0.15063, 10.0.16299, 10.0.19041, etc.
- Target Platform Version(s): 10.0.18362.0, 10.0.19041.0
What device(s) are you targeting? Choose any from Desktop, Xbox, Hololens)
- Target Device(s): Desktop
Which version of Visual Studio are you using? Specify Visual Studio 2017 or Visual Studio 2019
- Visual Studio Version: Microsoft Visual Studio Community 2019, Version 16.11.2
Which build configuration are you running? Choose from Debug, DebugBundle, Release, ReleaseBundle 
- Build Configuration: Debug x64, 

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Http post request with multipart form with code example below.
2. When executed code exception is thrown in `myApp\node_modules\react-native-windows\Shared\Modules\NetworkingModule.cpp` in function `AttachMultipartHeaders` line 247 in the second iteration of for loop     https://github.com/microsoft/react-native-windows/blob/3d7d5ff5c79390c38f8f0dcad70d15ae64c367b1/vnext/Shared/Modules/NetworkingModule.cpp#L247

## Expected Results
The post HTTP request with multipart form is sent. This issue is similar to https://github.com/microsoft/react-native-windows/issues/6046 but different place. JavaScript code is working in React Native for iOS and Android without any problem.

## Snack, code example, screenshot, or link to a repository:
```
        const formData = new FormData()

        formData.append("user", {
            string: JSON.stringify({"name": "Marcin", "family": "Nowak"}),
            type: "application/json",
        })

        const config = {
            headers: {
                "Content-Type": "multipart/form-data",
            }
        }


        const response = await fetch(
            'https://example.com/api/user/b52a6886-d02f-4121-95e3-48e3c7420081',
            {
              body: formData,
              method: "POST",
              headers: {
                'Content-Type': 'multipart/form-data',
                'Authorization': 'Bearer ' + "123"
              }
            }
          )
```

**Comment by JunielKatarn** [comment]
Attempting to reproduce.

**Comment by JunielKatarn** [comment]
Formatting repro sample for readability:
```JavaScript
const formData = new FormData();

formData.append('user', {
  string: JSON.stringify({name: 'Marcin', family: 'Nowak'}),
  type: 'application/json',
});

const config = {
  headers: {
    'Content-Type': 'multipart/form-data',
  },
};

const response = await fetch(
  'https://example.com/api/user/b52a6886-d02f-4121-95e3-48e3c7420081',
  {
    body: formData,
    method: 'POST',
    headers: {
      'Content-Type': 'multipart/form-data',
      Authorization: 'Bearer ' + '123',
    },
  },
);
```

**Comment by MarcinNowak-codes** [comment]
Thank you. I will try with next release of RNW.
