### ISSUE TITLE
Build failed with message Building Solution returned error code 1. Check your build configuration

### ISSUE THREAD

**Issue by VladKnyaz** [microsoft/react-native-windows#8577]
I'm getting this error when try to run following command
npx react-native run-windows

Environment
"react": "17.0.2",
"react-native": "0.65.1",
"react-native-windows": "0.65.1"

Visual Studio: 2019

I followed environment setup steps from following site
https://microsoft.github.io/react-native-windows/docs/rnw-dependencies

![image](https://user-images.githubusercontent.com/69315057/132136978-933fd1bf-6f0d-4ec5-847a-b9721ac4ceb7.png)

**Comment by tero-paananen** [comment]
Try call `npx react-native run-windows --logging` and read what failed

**Comment by tero-paananen** [comment]
or try `npx react-native run-windows --arch x64`
