### ISSUE TITLE
Update to prettier 2

### ISSUE THREAD

**Issue by acoates-ms** [microsoft/react-native-windows#8584]
#8572 had to work around an issue with prettier v1

**Comment by NickGerleman** [comment]
RN is stuck on Prettier 1.x, and Prettier 2.x introduces formatting changes. I think I fixed hoisting everywhere so that Prettier version should be per-project, but it would need to be verified that it works correctly for things like VS Code auto-format in different packages.

**Comment by NickGerleman** [comment]
react-native-windows-init already has a similar hack to the above PR.

**Comment by chrisglein** [comment]
We'll match when the core repo updates I imagine. And we'll see that when it does, so I don't think we need to track this with an issue.
