### ISSUE TITLE
Fast Refresh Broken on 0.66-preview.2

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-windows#8608]
Something might be broken on my personal inner dev loop, but filing issue so someone can hopefully test and confirm if issue is real. 

## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`: 6.0.0
2. `npx react-native info`:

```
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Memory: 37.46 GB / 63.84 GB
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.3
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7199119
    Visual Studio: 16.9.31529.145 (Visual Studio Enterprise 2019)
  Languages:
    Java: 1.8.0_282 - C:\Program Files\OpenJDK\openjdk-8u282-b08\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.66.0-rc.1 => 0.66.0-rc.1
    react-native-windows: 0.66.0-preview.2 => 0.66.0-preview.2
  npmGlobalPackages:
    *react-native*: Not Found

- Target Platform Version(s): 10.0.19041
- Target Device(s): Desktop
- Visual Studio Version: 2019
- Build Configuration: Debug
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create a fresh RNW app with react-native version 0.66.0-rc.1 and react-native-windows version 0.66.0-preview.2
2. Open App.js and make any change to the JS which should update upon saving the JS source code via Fast Refresh. 
3. Updates cannot be seen.

## Expected Results
Should see changes to JS appear in app upon save.

**Comment by chrisglein** [comment]
Things to investigate first:
- Is Metro picking up the changed file?
- Is it telling the app it should reload?
- Are there issues with the reload with the app

**Comment by chiaramooney** [comment]
Found commit which breaks Fast Refresh (https://github.com/microsoft/react-native-windows/commit/996ed985784ed75a06deb1e85f0e8fc99f9af8e6). It's the integration from core for changes up to 8/25 which was used as the base of 0.66-stable. 

When updates made to JS, metro is unresponsive and does not log that updates to the file have been made.

**Comment by acoates-ms** [comment]
This one looks potentially related: https://github.com/facebook/react-native/commit/f085e09be5a148065d286ba3950324dc9e44b7f6
