### ISSUE TITLE
How to build a standalone exe?

### ISSUE THREAD

**Issue by jimchanlite** [microsoft/react-native-windows#8614]
I used the command "npx react-native run-windows --release" to build the x86 exe file which will build the exe under "ProjectFolder\windows\Release\ProjectName\ProjectName.exe".

However, when I launch the exe file it shows the following errors:

- The code execution cannot proceed because MSVCP140_APP.dll was not found. Reinstalling the program may fix this problem.

- The code execution cannot proceed because VCRUNTIME140_APP.dll was not found. Reinstalling the program may fix this problem.

Is there a way to build the standalone exe without the DLL errors so that we can deliver it to clients?

**Comment by chrisglein** [comment]
Universal Windows Platform apps don't produce an exe that is launched from the file system like classic Win32 apps. React Native for Windows app are UWP apps by default. You can find more detail on this (and the tradeoffs involved in that) in our documentation: https://microsoft.github.io/react-native-windows/docs/native-code. But the short of it is that UWP apps are packaged and so you'll distribute the appx and have your clients sideload that package (or get it from the Microsoft Store).

If you want a more classic standalone EXE you can create a Win32 app and have your RNW content in a XAML island, but it remains a bit more of an advanced topic. There are some details on the website linked above.

You also may be able to find more resources by searching around the internet in general about UWP packaging.

Hope that's helpful!
