### ISSUE TITLE
Execute Command Line "react-native start" Error!

### ISSUE THREAD

**Issue by 527395632** [microsoft/react-native-windows#8623]
Computer environment：
    Version：Windows 10 Professional Edition
    Version number： 20H2
    Operating system build：19042.1165
    Images: 
![image](https://user-images.githubusercontent.com/20411721/133207790-515f545c-170e-439c-a40f-c6904b8bd2fc.png)

Development Environment: VisualStudio 2019 Enterprise

My steps：
1：download 'nodejs' from 'nodejs.org', 'https://nodejs.org/dist/v14.17.6/node-v14.17.6-x64.msi'
2：npm install -g react-native-cli
3：react-native init Sample --version 0.59.10
4：cd Sample
5：npm install --save-dev rnpm-plugin-windows
6：react-native windows
The above steps operate normally, However, I reported an error when I performed the following steps
“react-native start” or "react-native run-windows"
execute command line "react-native start" error message: 
error Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class. Run CLI with --verbose flag for more details.

images: 
![image](https://user-images.githubusercontent.com/20411721/133208437-ac036f82-734f-4971-a6b8-f20cbe467cc8.png)

execute command line "react-native run-windows" error message: 
![image](https://user-images.githubusercontent.com/20411721/133208541-39a495ee-b4d7-44d3-a1cb-ff9d933e6315.png)

**Comment by NickGerleman** [comment]
Older versions of react-native have a bug, requiring Node 10 or below to work correctly.

There have been some other pretty drastic changes since RNW 0.59. You will want to update to a newer, supported version if you run into issues.
