### ISSUE TITLE
Consider adding tabIndex to Pressable

### ISSUE THREAD

**Issue by AgneLukoseviciute** [microsoft/react-native-windows#8643]
Not sure what the initial motivation was for adding tabIndex prop, but if it still holds it might make sense to add tabIndex to Pressable as well.

**Comment by chrisglein** [comment]
FYI currently tabindex [isn't documented](https://github.com/microsoft/react-native-windows-samples/issues/294). But if it's on View and Button and such it makes sense to have on Pressable.

**Comment by chrisglein** [comment]
Change went to PR but it seems like we maybe need to do more homework on the overall story for `tabIndex`. There was a meeting and spec about this, but that was ~2 years ago. @stmoy FYI.
