### ISSUE TITLE
Playground Win32 isn't documented

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#8649]
There's a [readme for Playground](https://github.com/microsoft/react-native-windows-samples/issues/540), but it doesn't acknowledge [Playground Win32](https://github.com/microsoft/react-native-windows/tree/bf9a13dfd1edecf07945c1666fb34d759e66d1a9/packages/playground/windows/playground-win32). Given that this app is useful as an example for unpackaged apps and Xaml Islands, it at least deserves some coverage in the folder readmes about how to run it. At least until we create a replacement ([see this issue](https://github.com/microsoft/react-native-windows-samples/issues/540))

**Comment by asklar** [comment]
To me this is by design, per discussion in  microsoft/react-native-windows-samples#267

**Comment by chiaramooney** [comment]
Looks like my PR got closed from inactivity. @chrisglein @asklar do we have a final decision here on if we want this documentation or not? If yes, I'll reopen the PR. Otherwise, I'll go ahead and close this issue to wrap up this issue.

**Comment by chrisglein** [comment]
Yep, we talked about it in October-ish. You can reopen the PR.

**Comment by chiaramooney** [comment]
Will do. @asklar @chrisglein PR reopened now. Currently it's flagged with 'changes requested', so it'll need those removed before I can merge.

**Comment by chrisglein** [comment]
> Will do. @asklar Alexander Sklar FTE @chrisglein Chris Glein FTE PR reopened now. Currently it's flagged with 'changes requested', so it'll need those removed before I can merge.

@asklar Can you refresh you review state?
