### ISSUE TITLE
Wasteful string copies is napi RNW code

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#8650]
1. `CreateStringUtf8` will call into napi which will copy the string (this ends up calling [this](https://sourcegraph.com/github.com/nodejs/node@f182b9b29f6cdf0594498d4bd5b6efe562fc9ea6/-/blob/deps/v8/src/heap/factory.cc?L737))
2. `SerializeScript` calls `vector::assign` with the 2nd overload, which copies the string

The VectorBuffer ctor does a move so that one is ok.

_Originally posted by @asklar in https://github.com/microsoft/react-native-windows/pull/8617#discussion_r709718821_

**Comment by vmoroz** [comment]
There is no wasteful string copies: (1) creates the internal V8 string value for the V8 engine to parse the input, while (2) copies the resulting compiled string from the internal representation to the result buffer.

**Comment by vmoroz** [comment]
To triage I recommend to close this issue.

**Comment by JunielKatarn** [comment]
I have confirmed the buffer created `CreateStringUtf8` is the *raw source* input for `SerializeScript`, which results in the *prepared script* (V8's equivalent for *bytecode*), both which can be assumed to be always different.

See `napi_ext_serialize_script`:
```cpp
...
  if (v8::ScriptCompiler::CompileUnboundScript(context->GetIsolate(), &script_source).ToLocal(&script)) {
    v8::ScriptCompiler::CachedData *code_cache = v8::ScriptCompiler::CreateCodeCache(script);

    buffer_cb(env, code_cache->data, code_cache->length, buffer_hint);
  }
```

Then `NapiJsiRuntime::SerializeScript`:
```cpp
  auto getBuffer = [](napi_env /*env*/, uint8_t const *buffer, size_t bufferLength, void *bufferHint) 
  {
    auto data = reinterpret_cast<vector<uint8_t> *>(bufferHint);
    data->assign(buffer, buffer + bufferLength);
  };
```

The "internal buffer" @vmoroz mentioned is `code_cache`, which is clearly meant to be copied (I see no way to return it or pass it by reference) into the  out buffer pointer `buffer_hint`, represented by `result` in `SerializeScript`.

Closing this issue, @asklar.
Feel free to reopen if we missed something.
