### ISSUE TITLE
Create and validate new VS2022-based ADO agents/images/pools

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#8740]
Now there is a Windows Server 2022 agent image, with VS2022 installed. We should start migrating / ensuring that RNW can be built in 2022 

Task list:
- [x] Try creating a new image for the test pool
- [x] Try running PRs against it, fix issues (tracked by #8750)

**Comment by chrisglein** [comment]
We use custom images these days, so we'd need to update the custom images to be derived from these.

We want to get in front of this so we catch any compat issues before it all rolls out (currently they're on preview 4). Opinions on the right time to move to this @dannyvv?

Goal here is less to use the standard images than to catch breaks from 2022.

**Comment by jonthysell** [comment]
This is getting closer, leaving on 0.69 for now but this may move to 0.70.

**Comment by jonthysell** [comment]
0.69 is getting too close for a sudden toolchain change, moving to 0.70.

**Comment by jonthysell** [comment]
This is a priority for 0.71.

**Comment by jonthysell** [comment]
The `rnw-img-test` has been successfully updated to Windows Server 2022 with Visual Studio 2022. PR #9916 is currently running against those images.

**Comment by jonthysell** [comment]
The `rnw-img-vs2022` image has been created and validated.
