### ISSUE TITLE
Update react-native-platform-override for new nightly version pattern

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#8753]
RN nightlies now encode more than just the commit hash into the prerelease segment. E.g. 0.0.0-2d2de744b-20210929-2246.

We need to update integration tooling to properly extract just the commit hash from this.

**Comment by chrisglein** [comment]
Nick believes the fix here will likely just be to a regex. We will be broken on integration tooling until this is fixed, but should be an easy fix.
