### ISSUE TITLE
Autolinking doesn't work well with yarn link

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#8755]
1. add a module to an app, autolink it. sln and project files get pointed at the copy under node_modules
2. clone the module repo, yarn link it, link it into the app. 

expected: autolink is not needed
actual: autolink is needed because it thinks myapp\node_modules\mymodule is different than C:\mymodule_clone\...
in other words, autolinking is using the real ("target") filesystem path, which breaks the symlink abstraction

**Comment by chrisglein** [comment]
Paths are the targets of symlinks, not the symlinks itself. Logic there needs to be tidied up.
@jonthysell if you have ideas on how this should work, copy them in here.

**Comment by jonthysell** [comment]
The path to the dependency dir (under `node_modules`) is determined by the RN core CLI's `react-native config` command, and is passed to us fully resolved. By the time we get it, we can't possibly know that the path was gotten through a symlink without re-searching for the depdendency.

However, starting in [v9.0.0-alpha.5 of the RN CLI](https://github.com/react-native-community/cli/releases/tag/v9.0.0-alpha.5), the dependecy dir logic has been updated to _not_ automatically resolve the symlink by default (see [findPackageDependencyDir.ts](https://github.com/react-native-community/cli/blob/v9.0.0-alpha.5/packages/cli-tools/src/findPackageDependencyDir.ts#L68)).

So starting in RN 0.70 (where the 9.0 series CLI will be consumed) this problem should fix itself. So putting on 0.70.
