### ISSUE TITLE
Project templates should mention what version they used to be created with

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#8760]
It would be useful when going into an unfamiliar module/app, to be able to look at the project file and see what version of the CLI template was used to create it

**Comment by chrisglein** [comment]
@asklar @jonthysell Ideas about how in the project file that would be represented? Is there a clear place to put this kind of informational metadata?

**Comment by asklar** [comment]
at the very least, a comment in the project file. We could also include what command line options were used:

```xml
<!-- 
This project was created with react-native-windows-init 0.65.3 with the following command line:
npx react-native-windows-init --overwrite --language csharp
-->

**Comment by NickGerleman** [comment]
It might be worthwhile to also leave it in an MSBuild or config prop somewhere. Making it machine readable could let it be included in telemetry, for example.

**Comment by TatianaKapos** [comment]
@asklar Looping in @jonthysell, we had a meeting offline and discussed that adding in the command line options may expose private customer information such as the namespace. Wondering people's thoughts on this?

**Comment by asklar** [comment]
this issue is looking to track RNW version info (e.g. the string "0.65" stored as an msbuild property) in the template so that tooling can reason over it, there's no customer information such as the namespace being collected anywhere.

**Comment by jonthysell** [comment]
> this issue is looking to track RNW version info (e.g. the string "0.65" stored as an msbuild property) in the template so that tooling can reason over it, there's no customer information such as the namespace being collected anywhere.

I'm confused, I thought the purpose of this was to stamp RNW version in a comment within a template file. Something we could check on manually, say while debugging a customer-submitted codebase, not something tooling would reason over.
