### ISSUE TITLE
Create abstraction for getting/setting local configuration options

### ISSUE THREAD

**Issue by pre10der89** [Microsoft/react-native-windows#878]
An abstraction should be developed for getting / setting configuration options to the platform specific local store... The way local settings are stored is different between UWP and WPF... The abstraction would allow for a common interface to be used anywhere in the core code that needs to get or set a local configuration.

**Comment by rozele** [comment]
As things move towards .NET Standard its likely that some of this stuff will move to dependency injection, for now it seems like overkill for the limited usage of app local settings in core.
