### ISSUE TITLE
Support react-native-tcp-socket

### ISSUE THREAD

**Issue by enverbisevac** [microsoft/react-native-windows#8803]
### Module

react-native-tcp-socket

### Module repo url

https://github.com/Rapsssito/react-native-tcp-socket

### Existing issue url

https://github.com/Rapsssito/react-native-tcp-socket/issues/123

### Existing windows implementation?

- [ ] Legacy/C# implementation

**Comment by NguyenHuynhHuuTai** [comment]
I had the same problem when I couldn't create a TCP client

**Comment by chrisglein** [comment]
> I had the same problem when I couldn't create a TCP client

The module hasn't been implemented. Were you trying to use the module (in which case it's not supported on Windows), or something else?

**Comment by NguyenHuynhHuuTai** [comment]
> > I had the same problem when I couldn't create a TCP client
> 
> The module hasn't been implemented. Were you trying to use the module (in which case it's not supported on Windows), or something else?

Yes
I'm trying to use the module (in which case it's not supported on Windows)
