### ISSUE TITLE
Automatically Loosen RN Peer Dependency When Promoting From Preview to Latest

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#8810]
We want to allow using RNW with patch updates to RN. This means having a peerDependency that allows multiple versions of RN, e.g. `^0.66.0`. Our scripts leave us with too strict a dependency when we release, unless manually updated. Once we integrate a non-prelease version of RN into a branch (once there can be no more breaking changes), we should loosen the constraint.

**Comment by asklar** [comment]
Would be nice to get in 67, feel free to move to backlog if needed
