### ISSUE TITLE
Tests failing for x86 release with Hermes

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#8849]
### Problem Description

The latest main CI run passes all flavors except x86 hermes, where the tests timeout because they can't find the app.

### Steps To Reproduce

See CI integration test logs: https://dev.azure.com/ms/react-native-windows/_build/results?buildId=231768&view=logs&j=beb7dd8e-709a-58c9-01a4-da51a4b09277&t=dc2979bd-4d46-5ce8-318a-903e04150f70&l=964

See CI e2e test logs: https://dev.azure.com/ms/react-native-windows/_build/results?buildId=231768&view=logs&j=14709c39-390e-5691-22b3-9990e447bc08&t=b740a390-f27d-567e-c981-16687edca571&l=777

### CLI version

canary 400

### Environment

```markdown
ADO build machines
```

**Comment by NickGerleman** [comment]
Honestly it's probably worth just packing the binary at this point.
