### ISSUE TITLE
Run more checks Against stable branch PRs

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#8851]
We run some tests in PR, but more in nightly runs per branch. This can allow regressions to slip in. This is not too severe in main branch, but we can probably run more in stable builds where regressions are worse.

**Comment by jonthysell** [comment]
I will try to look at this again for 0.68 milestone.

**Comment by jonthysell** [comment]
I think this is possible in 0.69, the only question is: How many more configurations and how far back to go.

Then we should update the [promotion to latest steps](https://github.com/microsoft/react-native-windows/wiki/How-to-promote-a-release) to include this for new stable releases, upfront.
