### ISSUE TITLE
autolink won't add transitive project dependencies

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#8920]
in react-native-webview there are two projects: ReactNativeWebView (RNWV) and WebViewBridge (WVB)
RNWV depends on WVB

autolinking only adds RNWV to the project dependencies (autolinkedNativeModules.g.targets)
this works fine for msbuild.exe invocations, but VS has its own build ordering logic (it will rely on explicit project references)
this results in app builds failing because the dependency on WVB isn't explicitly declared

See https://docs.microsoft.com/en-us/visualstudio/msbuild/visual-studio-integration-msbuild?view=vs-2019#build-solutions

> Within Visual Studio, the solution file and project build ordering are controlled by Visual Studio itself. When building a solution with msbuild.exe on the command line, MSBuild parses the solution file and orders the project builds. In both cases the projects are built individually in dependency order, and project to project references are not traversed. In contrast, when individual projects are built with msbuild.exe, project to project references are traversed.

**Comment by jonthysell** [comment]
What exactly is missing here? If you specify RNWV as `directDependency: true` and WVB as `directDependency: false`, then both projects get added to the solution and a `PackageReferecen` to RNWV is added to the app project (via the generated autolink target).

**Comment by jonthysell** [comment]
The difference linked to in the VS docs is that for building a project directly with msbuild, the dependencies are not traversed. However we explicitly require everyone to build via the solution file anyways.
