### ISSUE TITLE
App registered component is remounted again

### ISSUE THREAD

**Issue by tero-paananen** [microsoft/react-native-windows#8930]
### Problem Description

Application's registered component` App` in index.js `AppRegistry.registerComponent(appName, () => App);` is remounted again when user tries open multiple instances of the same app on Windows 10 in **React Native Windows 0.65.x**. Tested with Welcome to React Native app. Main component remount **was not done in 0.63.x**.

Currently this causes issues in our app because main component remount did not happend on previous React Native versions. 

Is this bug in React Native or bug in our app that it not managed to pass main component remount?

https://www.digitalcitizen.life/how-quickly-open-multiple-windows-same-application/

### Steps To Reproduce

- Create Welcome to React Native app
```
npx react-native init Hello065 --template react-native@0.65.2
cd Hello065
yarn install
npx react-native-windows-init --overwrite --language cs
npx react-native autolink-windows
```

Add following code into App.js to show warning on component remount.
```
useEffect(() => {
    console.warn('componentDidMount');
  }, []);
```

- Run Hello065
- Right-click Hello065 icon in taskbar and select Hello065 icon and applications main component is remounted

### Expected Results

No remount done. Running Hello65 app is only activated again.

### CLI version

6.0.0

### Environment

```markdown
System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 23.02 GB / 31.90 GB
  Binaries:
    Node: 12.22.5 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.14 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.14393.0, 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.31624.102 (Visual Studio Community 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.65.1 => 0.65.1
    react-native-windows: 0.65.4 => 0.65.4
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Platform Version

10.0.18362.0

**Comment by asklar** [comment]
It makes sense to not re-navigate to the main page if the app is already running.
