### ISSUE TITLE
Theme changes at runtime do not update in XAML Island CommandBarFlyout 

### ISSUE THREAD

**Issue by rozele** [microsoft/react-native-windows#8948]
### Problem Description

If the theme of the app changes at runtime, the TextCommandBarFlyout (which is now a MUX control) does not update accordingly.

### Steps To Reproduce

1. Run RNTester in playground-win32
2. Open the TextInput example
3. Open the context menu on any TextBox
4. Change the app theme
5. Open the context menu for the same TextBox

The text for the ContextMenu will be using the previous theme still.

### Expected Results

The theme should update.

### CLI version

npx react-native --version

### Environment

```markdown
npx react-native info
```

**Comment by rozele** [comment]
> @rozele I believe you said #8949 doesn't fix this issue? I thought that PR just fixes the issue when the target that renders the CommandBarFlyout is in dark mode before the flyout appears, unrelated to theme changes afterwards.

Assuming the theme change is propagated from the window message queue to the XamlRoot, #8949 also fixes theme changes.

**Comment by asklar** [comment]
@rozele @lyahdav please confirm whether this needs to be reopened/revisited or not.
