### ISSUE TITLE
Expose onHoverIn/onHoverOut on Pressable

### ISSUE THREAD

**Issue by Saadnajmi** [microsoft/react-native-windows#8972]
### Summary

With https://github.com/facebook/react-native/pull/32405 , The Stock Pressable component now exposes onHoverIn/onHoverOut as the way to support mouse events. We should align our desktop ports (rn-macos/windows/win32) to take advantage of this.

### Motivation

This issue is motivated by my want to use the RN Stock Pressable component in FluentUI React Native, which currently has a local copy of Pressable internally. Using the upstream component would mean less custom code and smaller bundle size for FluentUI React Native. It also will help push Pressable as "the" cross platform component for handling mouse / keyboard focus / press events.

**Comment by rectified95** [comment]
This is going to be pulled in as part of the next RN integration we do. We are currently at Oct 21st, and the change in question was merged on Oct 23rd. @NickGerleman is probably going to pull this in within a week or so.

**Comment by NickGerleman** [comment]
@rectified95 you and @chiaramooney are on rotation for November 🙂.

**Comment by rectified95** [comment]
That is very true :D

**Comment by Saadnajmi** [comment]
If I read the updates to this bug properly, the upstream change will be merged in ~ next week, and will land with RN 0.68? 
Is there any chance we can back port it to RN 0.64? I would like to get the same change in RN-macOS so FURN (which should soon move to RN 0.64) could potentially use it across macOS/windows/win32

**Comment by acoates-ms** [comment]
Very unlikely, FB generally doesn't backport features to older versions.

**Comment by Saadnajmi** [comment]
> Very unlikely, FB generally doesn't backport features to older versions.

Sorry, I meant RN-Windows 0.64, not RN Core
