### ISSUE TITLE
doc: REACT_INIT doc says should pass `IReactContext`, but the actual param is `ReactContext`

### ISSUE THREAD

**Issue by roxk** [microsoft/react-native-windows#9010]
### Problem Description

From [REACT_INIT's doc](https://github.com/microsoft/react-native-windows/blob/eaf932469678b8b67b0b2b17fd2bcdda1ed4e358/vnext/Microsoft.ReactNative.Cxx/NativeModules.h#L38), it says:

> // REACT_INIT annotates a method that is called when a native module is initialized.
// **It must have 'IReactContext const &' parameter.** (emphasis mine)

But the [actual type](https://github.com/microsoft/react-native-windows/blob/eaf932469678b8b67b0b2b17fd2bcdda1ed4e358/vnext/Microsoft.ReactNative.Cxx/NativeModules.h#L420) used is `ReactContext`.

### Steps To Reproduce

t is a doc problem so no steps required.

### Expected Results

Doc says `ReactContext` is required.

### CLI version

npx react-native --version 4.14.0

### Environment

```markdown
npx react-native info
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
    Memory: 8.75 GB / 15.92 GB
  Binaries:
    Node: 14.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 27, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      Android NDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.16299.0, 10.0.17763.0, 10.0.18362.0, 10.0.19041.0, 10.0.22000.0
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6858069
    Visual Studio: 16.11.31729.503 (Visual Studio Community 2019), 17.0.31410.414 (Visual Studio Community 2022)
  Languages:
    Java: 1.8.0_262 - C:\Program Files\AdoptOpenJDK\jdk-8.0.262.10-hotspot\bin\javac.EXE
    Python: 3.7.3 - C:\Users\Name\AppData\Local\Programs\Python\Python37\python.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
    react-native-windows: 0.63.41 => 0.63.41
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Platform Version

10.0.16299

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2019

**Comment by asklar** [comment]
thanks @roxk !
