### ISSUE TITLE
Integration Test App X64WebDebug Failing

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#9015]
Screenshots show that the app hangs on start when running the tests. This is showing up in all pipelines, but x64 release, and x86 web debug do not seem affected.

**Comment by NickGerleman** [comment]
Will try to locally repro, but disabling the test for now.

**Comment by NickGerleman** [comment]
The issue locally reproes, running `yarn windows` on an x64 machine with web debugging. 
![image](https://user-images.githubusercontent.com/835219/139528592-1b5361e0-d38f-4511-b6ca-d9b73212bff4.png)

**Comment by NickGerleman** [comment]
Hmm, RNTesterApp x64 web debug works fine... 
![image](https://user-images.githubusercontent.com/835219/139528885-d46d3a32-c069-4ed4-9846-8872da8d7ff8.png)

**Comment by NickGerleman** [comment]
Okay tried again and I do not repo locally. Think I might have had a browser session set to pause on caught exceptions? 
![image](https://user-images.githubusercontent.com/835219/139529125-66b6e4cf-752d-439f-ae26-5fad37445f18.png)

**Comment by NickGerleman** [comment]
screenshot from CI machine: 
![before-test](https://user-images.githubusercontent.com/835219/139529193-7dbf270f-4916-42f6-99f0-14ed31ff9129.png)

**Comment by asklar** [comment]
looks like it's an issue in the CI machine but works locally?
