### ISSUE TITLE
Dumps not present for e2e-test-app crashes

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#9037]
Set to collect dumps for RNTesterApp.exe but they do not seem to show up on crash. Needs verification that the exe name is correct.

**Comment by jonthysell** [comment]
Assigning to me, will see if I can get this working for 0.69. It looks like we may be missing the DumpCount reg key.

**Comment by jonthysell** [comment]
This appears to be a permissions issue on the ADO build agents, moving to 0.70.

**Comment by jonthysell** [comment]
This may actually be fixable going forward with the new Windows Server / Visual Studio 2022 images.
