### ISSUE TITLE
RNW 0.66.2: `Invariant Violation: 'new NativeEntEmitter()' requires a non=nill argument.` in jest environment

### ISSUE THREAD

**Issue by nichamp** [microsoft/react-native-windows#9042]
### Problem Description

Originally I reported this in #8887 for 0.66.1 and #8901 attempted to address it for 0.66.2. It added a mock/shim for NativeAppTheme to add a addListener wrapper to suppress a warning.

Now when I attempt to run tests in a jest environment it still has the same failure as before, with or without the mock for  NativeModules.RTCAppTheme I had added as a workaround for 0.66.1

![image](https://user-images.githubusercontent.com/46539320/139947048-4be2616c-a1fd-4d34-971a-8cef7e3951c1.png)

I suspect the issue is due to no longer passing the module to the base class constructor.

![image](https://user-images.githubusercontent.com/46539320/139947082-22cf6469-975d-4267-8c3c-23fb2726c9bb.png)

### Steps To Reproduce

Attempt to use AppTheme in a jest test.

### CLI version

6.1.0

### Environment

```markdown
"dependencies": {
    "react": "17.0.2",
    "react-native": "0.66.1",
    "react-native-windows": "0.66.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "@types/jest": "^26.0.23",
    "@types/react-native": "^0.65.0",
    "@types/react-test-renderer": "^17.0.1",
    "babel-jest": "^26.6.3",
    "eslint": "^7.14.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.66.2",
    "react-test-renderer": "17.0.2",
    "typescript": "^3.8.3",
    "metro-config": "^0.66.2"
  },
```

**Comment by NickGerleman** [comment]
Following up offline, but this looks to be happening because the Jest tests are configured to simulate iOS.

**Comment by nichamp** [comment]
Nick is right so I am closing this issue - apologies for the noise. However react-native-windows should itself configure jest correctly on project init (it leaves the jest config set by react-native init in package.json) without having to use custom workarounds like I am now doing or adding a dependency on rnx-kit/jest-preset. A separate issue should be filed for this gap.
