### ISSUE TITLE
Allow `onMouseEnter` / `onMouseLeave` on arbitrary views

### ISSUE THREAD

**Issue by rozele** [microsoft/react-native-windows#9054]
### Problem Description

Currently, `onMouseEnter` and `onMouseLeave` only works on vanilla `<View />` components. Ideally, this would work for arbitrary components, including virtual text.

### Steps To Reproduce

1. Add `onMouseEnter` / `onMouseLeave` to a `<Text>` component
2. Attempt to hover the text
3. See no callback is received

### Expected Results

Callback should be received.

### CLI version

npx react-native --version

### Environment

```markdown
npx react-native info
```

**Comment by asklar** [comment]
Makes sense : )
