### ISSUE TITLE
secureTextEntry voids keyboardType

### ISSUE THREAD

**Issue by runeb** [Microsoft/react-native-windows#906]
When setting `secureTextEntry` on `TextInput` the input reverts to default keyboard no matter what `keyboardType` is set to:

```jsx
          <TextInput
            keyboardType="numeric"
            multiline={false}
            secureTextEntry
            editable
          />
```
Keyboard will not be numeric is this example.

Versions

    "react": "^15.3.1",
    "react-native": "^0.35.0",
    "react-native-windows": "^0.35.0",

Tested on a Lumia 650 with Windows 10

**Comment by rozele** [comment]
Looks like only 'number-pad' is supported. https://github.com/ReactWindows/react-native-windows/blob/master/ReactWindows/ReactNative/Views/TextInput/InputScopeHelpers.cs#L36

**Comment by runeb** [comment]
@rozele To be clear, you mean in the context of a `secureTextEntry`? Because `numeric` is supported otherwise.

**Comment by rozele** [comment]
@runeb yes, in the context of PasswordBox (when secureTextEntry=true)
