### ISSUE TITLE
Allow --useWinUI3 and --experimentalNugetDependency to be used together in CLI

### ISSUE THREAD

**Issue by AgneLukoseviciute** [microsoft/react-native-windows#9112]
### Summary

See #9099. Once WinAppSDK support is added in, we'll want to allow using these two flags simultaneously. 

### Motivation

Revert https://github.com/microsoft/react-native-windows/pull/5297 once it's no longer applicable.

**Comment by AgneLukoseviciute** [comment]
> The latest version of the the CLI runs for _all_ new projects, even against older RNW versions. Even if you can use both flags now for new projects, I don't think it will be true for older RNW versions.

yes actually @jonthysell has a good point - we would have to do a version check or something in the CLI to only allow certain versions. Really the CLI should delegate project creation logic to some version-specific package/code (we have an issue filed about syncing command line options)

_Originally posted by @asklar in https://github.com/microsoft/react-native-windows/issues/9099#issuecomment-965744893_

**Comment by chrisglein** [comment]
One solution here may be that if you `useWinUI3` that you only use the nuget (AKA we don't have the ability to build by source while also targeting WinUI3).

**Comment by jonthysell** [comment]
@AgneLukoseviciute Is this still something that makes sense for 0.69 or should it be moved to 0.70?
