### ISSUE TITLE
Remove JSIEngineOverride::ChakraCore

### ISSUE THREAD

**Issue by JunielKatarn** [microsoft/react-native-windows#9117]
ChakraCore support has been dropped from React Native Windows 0.64 and forward.

We should give heads up about this change to any consumers still using that engine, then delete the corresponding enum entry.

>ChakraCore [](http://example.com/codeflow?start=32&length=10)

Should we remove ChakraCore from this enum then?

_Originally posted by @NikoAri in https://github.com/microsoft/react-native-windows/pull/9089#discussion_r747842986_

**Comment by jonthysell** [comment]
@JunielKatarn Is this still something that makes sense for 0.69 or should it be moved to 0.70? Or maybe the Backlog?

**Comment by JunielKatarn** [comment]
It can be done for 0.69.

I'll send a PR right away.
