### ISSUE TITLE
Clean up bifurcation based on old winui3 / islands code

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#9135]
currently the code reasons over UWP xaml, system xaml islands, winui3 uwp, and sometimes even winui3 islands.
We should clean this up and support:
- UWP xaml
- system xaml islands
- WinUI 3 Win32

in the future, once winui3 properly supports islands, we can add that support too.

**Comment by chrisglein** [comment]
Clean up of this code would mean deprecating the UWP path. The longer we support UWP and WinAppSDK in a parallel, the further out this work is.

**Comment by AgneLukoseviciute** [comment]
> Clean up of this code would mean deprecating the UWP path. The longer we support UWP and WinAppSDK in a parallel, the further out this work is.

@asklar is this correct? My understanding is that this would only entail removing the WinUI3 UWP option, not UWP entirely.

**Comment by asklar** [comment]
the code reasons over winui3 in both "winui3 uwp" and "winui3 islands" mode; the latter is similar but different to winui3 winappsdk (subtly different assumptions). So the work here is to a) remove the code related to winui3 uwp, and b) inspect code related to winui3 islands, and figure out how to make it working for winappsdk, and for upcoming winui3 islands (which might behave differently from winui 3 islands as they existed before winui3 was made part of winappsdk). it's confusing i know.
