### ISSUE TITLE
Trying to use modules/apps across UWP/WinAppSDK should provide a meaningful error message

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#9137]
UWP modules will likely not work in WinAppSDK apps and vice versa.
We should have a sane experience here rather than let things fail at build or runtime.
This includes identifying whether a module/app is using winui3, as well as probably autolinking changes to diagnose this as early as possible.

**Comment by AgneLukoseviciute** [comment]
Depends on https://github.com/microsoft/react-native-windows/issues/9136
