### ISSUE TITLE
Measure % of new apps using RNW+WinAppSDK

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#9141]

**Comment by chrisglein** [comment]
There may be some instrumentation in WinAppSDK itself that we can leverage. If that works for us, great. If not, this would go into the RNW CLI telemetry.

**Comment by asklar** [comment]
@chrisglein I believe the existing instrumentation is in VS for file->new project which wouldn't capture usage through since we don't use the winappsdk templates.

**Comment by chrisglein** [comment]
If this would only cover VS project creation and not CLI project creation, yes we need our own events for this.

**Comment by chrisglein** [comment]
Depends on #9165

**Comment by jonthysell** [comment]
Presuming we've gotten to the "CLI telemetry data is available and in reports" we can answer the question "What percentage of new RNW apps created with the CLI target WinAppSDK" rather easily.

**Comment by jonthysell** [comment]
Depends on #9380 and existing reports.

**Comment by chrisglein** [comment]
How .NET CLI telemetry handles their data: https://learn.microsoft.com/en-us/dotnet/core/tools/telemetry
