### ISSUE TITLE
Update usage docs to include creating winappsdk apps

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#9142]
Once we are ready for 1.0 we should update the docs, unhide the CLI flag, etc.

**Comment by chrisglein** [comment]
Note that this is not all the docs, just the steps so far (does not include #https://github.com/microsoft/react-native-windows/issues/9602).

This is the first step in docs, so creating the spot in the docs (alongside UWP, not replacing I assume) and having an article on how to create an app, referring to CLI and samples.
