### ISSUE TITLE
(Backport Request) React native windows 0.66 -> Some React native stuffs are not working

### ISSUE THREAD

**Issue by sakthivel-servicemax** [microsoft/react-native-windows#9155]
### Problem Description

Hi,
 I upgraded react native windows to 0.66.0. Some react native stuffs like 
    - useNativeDriver true for Animated.timing not working, 
    - InteractionManager.runAfterInteractions is not working, 
    - FlatList loads only 10 items on initial load.
All of these are working fine in react native windows 0.65.0.

Any solutions for these?

Thanks,
Sakthi.

### Steps To Reproduce

Just adding the above to the project, not working as expected.

### CLI version

npx react-native --version

### Environment

```markdown
npx react-native info
```

**Comment by chrisglein** [comment]
> - useNativeDriver true for Animated.timing not working,
- InteractionManager.runAfterInteractions is not working,

There was an issue with animations that was recently patched. #9157. Does that sound like what you were hitting?

> FlatList loads only 10 items on initial load.

That one sounds different. Can you elaborate at all or provide any code snippet that repros?

**Comment by NickGerleman** [comment]
@chrisglein I think the linked issue should fix the FlatList one as well. On first render, FlatList only renders the first [`initialNumToRender` (default 10)](https://reactnative.dev/docs/flatlist#initialnumtorender) children. It starts rendering more in batches, once the app is idle. It does this via an internal API called `Batchinator`, that I think indirectly uses, `InteractionManager.runAfterInteractions`

**Comment by NickGerleman** [comment]
It needs to be backported to 0.66 and 0.67 though.

**Comment by NickGerleman** [comment]
@rozele I think this regression came with another one the changes you brought to the repo (https://github.com/microsoft/react-native-windows/pull/8418). Would you be able to make a PR backporting your fix to the affected branches?

**Comment by chrisglein** [comment]
> Would you be able to make a PR backporting your fix to the affected branches?

@NickGerleman @rozele Does that mean we have a fix in main that needs to be backported or that we're still waiting on one and when we do it should be backported?

**Comment by NickGerleman** [comment]
Yes, the PR you linked needs to be backported.

**Comment by NickGerleman** [comment]
@rozele is backporting the fix on your radar?

**Comment by rozele** [comment]
Not currently 😬

**Comment by jbcullis** [comment]
This one stumped me for a minute too, we are in the process of making an existing iOS / android app work with react-native-macos and react-native-windows.
Already have the macOS going but we need to set useNativeDriver to false for the windows app to work.
I'll add the fix to our build and see if it resolves the issue.

**Comment by sakthivel-servicemax** [comment]
did these changes port to 0.66 also? we need this immediately for our upgrade. When can we expect this ported to 0.66
So we can  plan accordingly?

**Comment by NickGerleman** [comment]
@rozele have you backported a change before?

**Comment by ptripathi-svmx** [comment]
@rozele  Requesting porting of these changes to 0.66 .. We are on critical path for our product release and need to absorb 0.66 with this fix added in.. would really appreciate your help in this regard. Thanks

**Comment by jbcullis** [comment]
@ptripathi-svmx If it's urgent, you can easily make the changes in your own environment.
Path should be {Project Name}\node_modules\react-native-windows\Microsoft.ReactNative\Modules\Animated

I followed the change set found here - https://github.com/microsoft/react-native-windows/commit/7abcaf8c07da20f3e950e63fa3970174c41865f7 - and the animations started working.

**Comment by chrisglein** [comment]
Instructions for backporting are [here](https://github.com/microsoft/react-native-windows/blob/main/CONTRIBUTING.md#-backporting). We'd take a PRs to 0.66/0.67 to backport this. Otherwise this is already in the 0.68 payload (currently in preview and release pending soon).
