### ISSUE TITLE
Telemetry should capture certain msbuild props - WinUI2xVersion, WindowsTargetPlatformVersion, UseWinUI3

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#9165]
### Summary

Our telemetry needs to capture the values of certain msbuild props, including WinUI2xVersion, WindowsTargetPlatformVersion, and UseWinUI3.

We should add this to the schema and, ideally, get it using something like script proposed in https://github.com/microsoft/react-native-windows/pull/8734.

### Motivation

While we do capture certain versioning information based on the nuget packages (via PackageReference or entry in packages.config) that may differ from what was specified in ExperimentalFeatures.props.

**Comment by chrisglein** [comment]
PR is up for this but is in draft because of concerns on impact to execution time to `run-windows`. @jonthysell How do you think this will go? Find a way to cut down the time, accept it as a necessary cost, find a way to make the cost not blocking, or other?
