### ISSUE TITLE
onMouseLeave behavior should be consistent regardless of whether the pointer is inside the ReactRootView

### ISSUE THREAD

**Issue by rozele** [microsoft/react-native-windows#9171]
### Problem Description

The `onMouseLeave` event is fired on all views when `PointerExited` fires on the `ReactRootView`, even if the pointer is down.

This is inconsistent with how we currently suppress `onMouseEnter` / `onMouseLeave` while inside the bounds of the `ReactRootView`.

These two behaviors need to be consistent so we have a reliable contract for `onMouseEnter` / `onMouseLeave`.

### Steps To Reproduce

1. Open RNTester > Mouse Events example
2. Hold the pointer down over a view and drag the pointer outside the bounds of the ReactRootView.
3. When the mouse exits the ReactRootView - it should not fire `onMouseLeave` until the pointer is released.
4. Notice that `onMouseLeave` didn't fire while the pointer was down inside the `ReactRootView`, but it does once the pointer exits it's bounds.

### Expected Results

The `onMouseEnter` / `onMouseLeave` events should be consistent regardless of whether the pointer is inside the bounds of the `ReactRootView`, so either:
a) Always suppress `onMouseLeave` while pointer is down, or...
b) Do not suppress `onMouseLeave` at all while pointer is down.

### CLI version

npx react-native --version

### Environment

```markdown
npx react-native info
```

### Snack, code example, screenshot, or link to a repository

https://user-images.githubusercontent.com/1106239/142464151-f5e64831-ff1c-4230-bf9a-7fe9f69a5ee4.mp4

**Comment by chrisglein** [comment]
There's an expectation from the Windows control set that if you are holding the mouse button down while hovering off of a control that the hover state is still reported. This is a way to "abandon" a click on a Button, actually - move your mouse off while holding the click, then release the click while no longer hovered. Does your proposal affect the ability to meet that behavior?

**Comment by rozele** [comment]
@chrisglein - no, that behavior is broken today. The real problem here is the inconsistent treatment of `onMouseEnter` / `onMouseLeave` events for when the pointer is inside the root view and outside of it. I see now that this inconsistent treatment is a legacy of suppressing `onMouseEnter` / `onMouseLeave` events in `PointerMoved` when the pointer is down, as we wanted to differentiate between `onMouseMove` (no pointer down) and `onTouchMove` (pointer down), and `onMouseEnter` / `onMouseLeave` piggy backed on the logic for this.

I'm going to update the issue to instead suggest that we should make the behavior consistent (not necessarily one way or the other) and you all can decide which is right ;)

**Comment by rozele** [comment]
I think based on the feedback thus far from @chrisglein, @asklar, and @acoates-ms, we should merge #9173 to fix this, rather than #9172.

**Comment by chrisglein** [comment]
> I'm going to update the issue to instead suggest that we should make the behavior consistent (not necessarily one way or the other) and you all can decide which is right ;)

Adding @rectified95 to weigh in on this.
