### ISSUE TITLE
Add remaining and UWP-specific accessibility features

### ISSUE THREAD

**Issue by rozele** [Microsoft/react-native-windows#918]
UWP has a rich UI automation API which we should expose to react-native.  This may involve breaking out accessibility features as a module that is pulled in for the base View class.

**Comment by rigdern** [comment]
Here's the work that I believe is involved:
  - Implement custom AutomationPeers for the kinds of controls we want to expose to the accessibility tree (e.g. button, list). We can pick the appropriate custom AutomationPeer based on the value of a prop. We can consider reusing the `accessibilityTraits` prop (iOS) or the `accessibilityComponentType` prop (Android). Or maybe we should have a new prop for UWP?
  -  Allow XAML controls to get focus (Eric did a prototype in #1386)
  - Allow controling the tab order through XAML's `TabIndex` property
  - Expose keyboard events to JavaScript
  - Expose event when high contrast is toggled
  - Implement live region support (Android exposes this through the `accessibilityLiveRegion` prop)

**Comment by rozele** [comment]
@rigdern 
2. We still need to differentiate in JavaScript when to use a Control vs. a plain Canvas to keep a concise view hierarchy for performance (probably could do something similar to the fast text prototype #1256)
3. this is a trivial addition to #1386
4. #1386 includes `KeyUp` and `KeyDown` events per focused view, do you think you'll also need a global key listener?

**Comment by rozele** [comment]
This is a broad bit of work which has been addressed by a number of PRs recently. Closing in favor of more specific accessibility issues that may arise.
