### ISSUE TITLE
TextInput securetext is editable when editable is disabled

### ISSUE THREAD

**Issue by tero-paananen** [microsoft/react-native-windows#9182]
### Problem Description

Following `TextInput` should be not editable but it is editable. 

```
 <TextInput
          editable={false}
          secureTextEntry={true}
          style={{height: 50}}
          placeholder="type password - not editable"
```

It is not editable if `secureTextEntry={false}`

Tested on **react-native-windows 0.65.8**

### Steps To Reproduce

Code above

### Expected Results

TextInput is not editable

### CLI version

6.0.0

### Environment

```markdown
System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 19.94 GB / 31.90 GB
  Binaries:
    Node: 12.22.5 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.14 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.14393.0, 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.31829.152 (Visual Studio Community 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.65.1 => 0.65.1
    react-native-windows: 0.65.8 => 0.65.8
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by chrisglein** [comment]
When you set `secureTextEntry` it switches between 2 different underlying XAML controls. `PasswordBox` vs. `TextBox`. In the switch between those controls it's possible that something's not being copied over or property set order matters or something like that.

**Comment by TatianaKapos** [comment]
@chrisglein Looks like `editable` is only implemented for TextBox since TextBox has the property `isReadOnly` and PasswordBox does not. Looks like we might have missed documenting this?

Potientally the fix could be mapping `editable` to `isReadOnly` for TextBox and `isEnabled` for PasswordBox. The only issue with that is you would not be able to copy/paste from the PasswordBox

**Comment by chrisglein** [comment]
> Looks like `editable` is only implemented for TextBox since TextBox has the property `isReadOnly` and PasswordBox does not. Looks like we might have missed documenting this?
> 
> Potientally the fix could be mapping `editable` to `isReadOnly` for TextBox and `isEnabled` for PasswordBox. The only issue with that is you would not be able to copy/paste from the PasswordBox

Oh that's interesting. If there's no way to have a copy-able but not paste-able PasswordBox then we're limited by what XAML can do (without spectacular workarounds). However the scenario of copying from a PasswordBox is... well less of a thing. So your suggestion of mapping isReadOnly to disable paste _and_ seems like a reasonable workaround.
