### ISSUE TITLE
Upgrade Microsoft.NETCore.UniversalWindowsPlatform

### ISSUE THREAD

**Issue by AgneLukoseviciute** [microsoft/react-native-windows#9194]
We [upgraded to 6.2.9 in May, 2020](https://github.com/microsoft/react-native-windows/pull/4975) - might be a good idea to upgrade to 6.2.13 to get current. 

>unrelated but we probably want to upgrade this number now

_Originally posted by @asklar in https://github.com/microsoft/react-native-windows/pull/9177#discussion_r753518230_ in reference to the Upgrade Microsoft.NETCore.UniversalWindowsPlatform version.

**Comment by chrisglein** [comment]
@AgneLukoseviciute there likely are side effects with .NET Native and other things, right? Any idea how disruptive this will be? When should we tackle this?
