### ISSUE TITLE
Tracking animation nodes do not restart correctly

### ISSUE THREAD

**Issue by rozele** [microsoft/react-native-windows#9206]
### Problem Description

When attempting to start a tracking animation from an animation that is already running, the animation pauses at it's current value and does not restart.

### Steps To Reproduce

1. Open RNTester > Native Animated example
2. Scroll to the tracking animation example
3. Click the animation twice (once to start, then again to update while the animation is running).

### Expected Results

The animation behavior should match the JS driver, but the native animation gets stuck.

### CLI version

npx react-native --version

### Environment

```markdown
npx react-native info
```

### Snack, code example, screenshot, or link to a repository

https://user-images.githubusercontent.com/1106239/143905660-445fedb2-25b1-4635-9f6b-1b467b39f23d.mp4

**Comment by chrisglein** [comment]
Same as #8419?

**Comment by rozele** [comment]
Not quite - I fixed #8419 separately.

**Comment by rozele** [comment]
This seems to be a problem with the same animation ID being used multiple times for TrackingAnimatedNodes, which prevents the new animation from being set to the m_activeAnimations map in NativeAnimatedNodesManager. I'll have a PR shortly.

**Comment by rozele** [comment]
Rather than putting in a separate PR, I merged the necessary changes into #9190.
