### ISSUE TITLE
NativeAnimated RNTester example crashes for Release x64 builds

### ISSUE THREAD

**Issue by rozele** [microsoft/react-native-windows#9227]
### Problem Description

RNTester crashes on a Yoga assertion for Release builds when attempting to open NativeAnimated

### Steps To Reproduce

1. Clone latest
2. Build and run Playground Release x64
3. Load RNTester
4. Attempt to open NativeAnimated examples

### Expected Results

Playground should not crash.

### CLI version

npx react-native --version

### Environment

```markdown
npx react-native info
```

**Comment by chrisglein** [comment]
@rozele Happen to have the assertion information/callstack?
