### ISSUE TITLE
Community Modules missing ARM64 Support are incompatible with 0.67 Apps

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-windows#9232]
### Problem Description

The DateTimePicker, Picker, and WebView community modules do not support the ARM64 configuration. When these modules are added to an RNW app running on 0.67 they fail to load because the app solution file expects ARM64 to be a supported confiugration.

### Steps To Reproduce

1. Create 0.67 RNW app.
2. Add modules listed above as dependencies.
3. Open app solution.

### Expected Results

See all community module projects be able to load. 

### CLI version

6.0.0

### Environment

```markdown
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Memory: 52.74 GB / 63.84 GB
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7199119
    Visual Studio: 16.9.31828.109 (Visual Studio Enterprise 2019)
  Languages:
    Java: 1.8.0_282
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.67.0-rc.1 => 0.67.0-rc.1
    react-native-windows: 0.67.0-preview.4 => 0.67.0-preview.4
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2019

### Build Configuration

Debug

**Comment by creambyemute** [comment]
@chiaramooney DateTimePicker now supports ARM64! V 4.0.1 was released with my PR that added ARM64 support.

Cheers

**Comment by NickGerleman** [comment]
Picker 2.0 should also now support ARM64 with https://github.com/react-native-picker/picker/pull/311

**Comment by NickGerleman** [comment]
We've supported ARM64 for a while now though. Any idea why 0.67 would make things worse?

Could you include the error VS gives when loading the solution?

**Comment by chiaramooney** [comment]
Closing issue now resolved with version upgrades.
