### ISSUE TITLE
Unable to transfer/perform deep linking with more than 100Kb data using Linking.OpenUrl

### ISSUE THREAD

**Issue by rahman2835** [microsoft/react-native-windows#9240]
### Problem Description

Unable to perform deep linking using Linking.OpenUrl with more than 100 Kb json string data.

Below is the sample.

 Linking.openURL(url).catch(error => {
            dispatch(openActionSheet({ instanceId: referrer, errorType: 'APP_NOT_INSTALLED' }));
            logger.error(`App-to-App error', ${error}`);
 });

Params:
url : this url param will have more than 100 Kb json string data as a query params.

### Steps To Reproduce

1. Create a target uwp app with schema or protocol (test://) to perform deep linking.
2. From the sender app call below code.

const url = "test:\\data"; // here data is json string with more than 100 KB.
Linking.openURL(url).catch(error => {
            dispatch(openActionSheet({ instanceId: referrer, errorType: 'APP_NOT_INSTALLED' }));
            logger.error(`App-to-App error', ${error}`);
 });

### Expected Results

App should open the 3rd party app with huge data.

### CLI version

0.63

### Environment

```markdown
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19042
    CPU: (2) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 747.72 MB / 3.98 GB
  Binaries:
    Node: 12.9.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0
  IDEs:
    Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6626763
    Visual Studio: 16.4.29613.14 (Visual Studio Community 2019)
  Languages:
    Java: Not Found
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-windows: ^0.63.0-0 => 0.63.20
  npmGlobalPackages:
    *react-native*: Not Found
```

### Visual Studio Version

Visual Studio 2019

### Build Configuration

Release

**Comment by chrisglein** [comment]
Not sure where the failure is at first glance. This could be failing at the UWP layer where there are restrictions around how big a URL can be. In which case there's not much we can do. There's going to be some limit, not sure what that is. We should figure out where that limit is enforced.

Workaround would be to find some intermediate place to store that data and only pass the link to that.
