### ISSUE TITLE
react-native-platform-override README in npm is Blank

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-windows#9241]
### Problem Description

react-native-platform-override README in npm just contains the word "none" missing information it used to contain such as package purpose, command line options for the package, etc. 

### Steps To Reproduce

Follow link: https://www.npmjs.com/package/react-native-platform-override

### CLI version

N/A

### Environment

```markdown
N/A
```

**Comment by NickGerleman** [comment]
Not seeing this locally when I go to that link. 
![image](https://user-images.githubusercontent.com/835219/144900137-a68f5a98-e3ce-459d-866d-ee7711f42558.png)
