### ISSUE TITLE
NativeAnimated `getValue` returns incorrect result

### ISSUE THREAD

**Issue by rozele** [microsoft/react-native-windows#9250]
### Problem Description

When stopping animations on an animated value, you can supply a callback that provides the current value. Currently, this value always returns the initial value on the NativeAnimated module.

### Steps To Reproduce

1. Add example that stops an animation and shows the value supplied to the callback, e.g., in RNTester > Native Animated Example
2. Run animation and force it to stop
3. Observe that the value supplied to the `stopAnimation` callback is incorrect.

### Expected Results

The value supplied to the `stopAnimation` callback should reflect the current state of the animation.

### CLI version

npx react-native --version

### Environment

```markdown
npx react-native info
```

### Snack, code example, screenshot, or link to a repository

https://user-images.githubusercontent.com/1106239/145256453-bc9ba495-8725-4a70-a19c-fee20a071317.mp4

**Comment by rozele** [comment]
The example shown is actually not a good one. Re-reading through the code in core RN, it doesn't look like this would work for any platform. We should probably fix that bug in RN core, but detaching a props animated node also uses the `NativeAnimated.getValue` API, and since that would be called synchronously in the same batch as `StopAnimation`, it's likely to return the incorrect value.

**Comment by rozele** [comment]
Note - getting the correct value for AnimatedValue when calling `stopAnimation` was just added here: https://github.com/facebook/react-native/commit/8ba771c3ddc00b1499e95a2812b4cd5ac904c8df

**Comment by rozele** [comment]
Looks like this could be a dupe of #5958, cc @rectified95

**Comment by chrisglein** [comment]
> Looks like this could be a dupe of #5958, cc @rectified95 Igor Klemenski FTE

Agreed, that sounds like the same issue. Closing this one as a duplicate.
