### ISSUE TITLE
App crashes when reloading JS while animation active

### ISSUE THREAD

**Issue by rozele** [microsoft/react-native-windows#9257]
### Problem Description

While an animation is running and you attempt to reload JS, the app crashes. This can be reproduced easily by opening the RNTester > Native Animated Example and attempting to reload JS from there.

### Steps To Reproduce

1. Open RNTester > Native Animated Example
2. Press `Ctrl + Shift + D` to open the debug menu
3. Click "Reload Javascript" option in debug menu
4. App crashes

### Expected Results

App should not crash.

### CLI version

npx react-native --version

### Environment

```markdown
npx react-native info
```

**Comment by jonthysell** [comment]
This doesn't appear to repro in main, using playground. I am able to start an animation and reload the JS without any problems.

**Comment by jonthysell** [comment]
A stack trace or crash dump would be useful.

**Comment by rozele** [comment]
Actually just confirmed this is fixed in latest.
