### ISSUE TITLE
Best way to use vector assets?

### ISSUE THREAD

**Issue by nuthinking** [Microsoft/react-native-windows#928]
Having some issues with react-native-vector-icons: https://github.com/oblador/react-native-vector-icons/issues/357

Wondering when "native" SVG support might land so that third party libraries are not needed, or if there are other ways.

**Comment by rozele** [comment]
@nuthinking I think a native SVG module would be great!  It looks like this might be a good starting point: https://github.com/mntone/SvgForXaml.  Would make a very useful plugin for react-native-windows.

**Comment by nuthinking** [comment]
FYI: react-native-vector-icons seems to be working fine now (was my mistake).
