### ISSUE TITLE
TextInput onContentSizeChange fires on render.

### ISSUE THREAD

**Issue by jbcullis** [microsoft/react-native-windows#9295]
### Problem Description

TextInput onContentSizeChange fires on render, but not on next line.

### Steps To Reproduce

Create following element:
<TextInput style={{height: Math.max(40, TextInputHeight)}} onContentSizeChange={(event) => {
    console.warn(event.nativeEvent.contentSize.height);
}} multiline={true} />

### Expected Results

onContentSizeChange should change when new lines are added to a multiline text input.

### CLI version

npx react-native --version

### Environment

```markdown
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 21.85 GB / 31.73 GB
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.3 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0, 10.0.22000.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 17.0.31912.275 (Visual Studio Community 2022)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.66.0 => 0.66.0
    react-native-windows: 0.66.5 => 0.66.5
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Platform Version

10.0.19041

### Build Configuration

Debug

**Comment by chrisglein** [comment]
Probably a mismatch between the underlying method/timing XAML uses for measuring text and how this event plays out.

**Comment by chrisglein** [comment]
Not something we plan to address on the Paper renderer as we move towards Fabric.
Fabric will not use XAML for the fundamentals here, so this isn't necessarily applicable in the new `TextInput` implementation.
