### ISSUE TITLE
AllowAutoRedirect should be false

### ISSUE THREAD

**Issue by grahamlyus** [microsoft/react-native-windows#9310]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-windows@0.64.27` for the project I'm working on.

AllowAutoRedirect is true by default, and this causes network requests to fail without much information other than "Unhandled exception during request" . Using the debugger, I found this was due to 0x80072F88 - The HTTP redirect request must be confirmed by the user.

react-native on iOS/Android does not automatically follow redirects.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-windows/Shared/Modules/NetworkingModule.cpp b/node_modules/react-native-windows/Shared/Modules/NetworkingModule.cpp
index 09caeaf..1a846a2 100644
--- a/node_modules/react-native-windows/Shared/Modules/NetworkingModule.cpp
+++ b/node_modules/react-native-windows/Shared/Modules/NetworkingModule.cpp
@@ -8,6 +8,7 @@
 #include <winrt/Windows.Security.Cryptography.h>
 #include <winrt/Windows.Storage.Streams.h>
 #include <winrt/Windows.Web.Http.Headers.h>
+#include <winrt/Windows.Web.Http.Filters.h>
 #include <winrt/Windows.Web.Http.h>
 #include "NetworkingModule.h"
 
@@ -33,7 +34,9 @@ namespace Microsoft::React {
 //
 class NetworkingModule::NetworkingHelper : public std::enable_shared_from_this<NetworkingHelper> {
  public:
-  NetworkingHelper(NetworkingModule *parent) : m_parent(parent) {}
+  NetworkingHelper(NetworkingModule *parent) : m_httpClient(m_httpFilter), m_parent(parent) {
+      m_httpFilter.AllowAutoRedirect(false);
+  }
 
   void Disconnect() {
     m_parent = nullptr;
@@ -83,6 +86,7 @@ class NetworkingModule::NetworkingHelper : public std::enable_shared_from_this<N
  private:
   NetworkingModule *m_parent;
 
+  winrt::Windows::Web::Http::Filters::HttpBaseProtocolFilter m_httpFilter;
   winrt::Windows::Web::Http::HttpClient m_httpClient;
   std::unordered_map<
       int64_t,
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by chrisglein** [comment]
> Here is the diff that solved my problem

Thanks for finding this issue and digging in. Could you create a PR with the fix that you've come up with so we can review and test it?

**Comment by AgneLukoseviciute** [comment]
I don't think this should've closed out, reopening.

**Comment by TatianaKapos** [comment]
Is this issue not closed by https://github.com/microsoft/react-native-windows/pull/10534?
