### ISSUE TITLE
e2etestapp references boost nuget

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#9328]
https://github.com/microsoft/react-native-windows/blob/17861f726533cb7907d9ad0ff3fd2083125f2de6/packages/e2e-test-app/packages.config#L3

it looks like the e2e test app is referencing the boost nuget package (which is for C++ code), but the e2e test app is C#.
Moreover it isn't clear why we need a packages.config for a C# project, the project should be using PackageReference already anyway

**Comment by chrisglein** [comment]
Also boost takes up a lot of space :).
This seems like a mistake that needs to be cleaned up.
This test app may not even need the packages.config at all. Start by deleting it and seeing if it still works.

**Comment by NickGerleman** [comment]
This isn't a bug. Boost is required for the source build, which regardless of language, will also build Microsoft.ReactNative, including Folly.

**Comment by NickGerleman** [comment]
I think `PackageReference` worked in external projects though... @JunielKatarn can confirm. I remember there were some weirdness of a hybrid model when using community modules using packages.config, but that we had a path to allow it, since it was very common.

**Comment by NickGerleman** [comment]
The writeup on migration will be helpful here I think 🙂.

**Comment by JunielKatarn** [comment]
> The writeup on migration will be helpful here I think 🙂.

Opened #9351 for follow-up.

**Comment by JunielKatarn** [comment]
> Also boost takes up a lot of space :). This seems like a mistake that needs to be cleaned up. This test app may not even need the packages.config at all. Start by deleting it and seeing if it still works.

Any machine building MSRN from sources will have to get a copy of boost.
Using `PackageReference`-only projects, there will be only one copy in the developer's machine.

As Nick explained, the "extra" `packages.config` exists for hybrid scenarios because the classic NuGet mechanism almost hard-codes the extracted NuGet's location (usually `$(SolutionDir)packages`).
