### ISSUE TITLE
Eliminate or reduce unneeded dependency on boost

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#9329]
For the most part, we don't need much from boost:
- Office desktop code uses, can we isolate to that flavor?
- Folly uses it (does it need to?)
- RNW code uses it for trivial things like string::ends_with or starts_with. These should be available with std::latest or maybe even std::cpp23
- Some test code uses it, can trim down 

Rationale: boost is a large dependency - around 180 MB; trimming down its use or finding replacements in the STL would benefit everyone.

**Comment by chrisglein** [comment]
> Office desktop code uses, can we isolate to that flavor?
There's some clean up in progress here, with some old web socket code deleted this may be able to get clean.

> RNW code uses it for trivial things like string::ends_with or starts_with. These should be available with std::latest or maybe even std::cpp23
That seems like great clean up that we can do now.

> Some test code uses it, can trim down
Related #9328. Any others?

**Comment by NickGerleman** [comment]
> Folly uses it (does it need to?)

I think it is set up to require it in several areas. It would be a significant undertaking to move it away for internal folly code. Maybe RN could use a smaller subset of folly though.

> Rationale: boost is a large dependency - around 180 MB
FWIW the nupkg is 24MB, so we are not transferring so much over the wire. There's still a disk space hit though.
