### ISSUE TITLE
Hermes direct debugging doesn't work with VS Code React Native Extension

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#9359]
User feedback is that Hermes debugger in RNW doesn't seem to work with the VS code extension.

**Comment by chrisglein** [comment]
> User feedback is that Hermes debugger in RNW doesn't seem to work with the VS code extension.

Both of these are OSS. Is the problem with the extension? Is the problem within Hermes Windows? Or is it something in the RNW configuration (e.g. port settings)? @NickGerleman do you have any more detail here alongside the user feedback?

**Comment by chrisglein** [comment]
One suggested problem: the default port for Hermes may be different and causing a problem with the extension. I don't know if the default needs to change to match or if the tools should handle this.

**Comment by RedMickey** [comment]
Yep, I think if a Hermes application provides a non-standard debugging port, the extension should handle this. The extension has the special `port` parameter in debug configurations for this purpose. 
To attach to the app, the extension tries to fetch debuggable targets from `http://address:port/json/version` and `http://address:port/json/list`. We rely on these guides https://github.com/microsoft/react-native-windows/blob/main/docs/inspector.md, https://reactnative.dev/docs/hermes#debugging-js-on-hermes-using-google-chromes-devtools and use the `8081` port as default for Hermes debugger.
I found the [issue](https://github.com/microsoft/react-native-windows/issues/9407) that seems to be similar to our [question](https://github.com/microsoft/react-native-windows/discussions/9087). This could cause problems with finding targets for debugging.

**Comment by mganandraj** [comment]
Hermes inspector server runs on the same port as the metro bundler runs .. which is 8081 by default. Do we have issues connection when VSCode when metro/inspector runs on default port, 8081 ?

**Comment by RedMickey** [comment]
We haven't faced problems with connection to the metro/inspector default port in the RNT extension if Hermes inspector is enabled. We only encountered an attachment issue when the Hermes inspector wasn't activated.

**Comment by RedMickey** [comment]
We tried out React Native for Windows v0.67.1 and could debug it without problems in the RNT extension. Now Hermes inspector activates, and the extension can attach to the app properly. Thanks!

**Comment by acoates-ms** [comment]
Fixed by #9478, #9477, #9407
(Depending on which stable version you needed the fix in)
