### ISSUE TITLE
Build broken in VS 2019 (16.11.9) with Internal Compiler Error

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#9373]
### Problem Description

There seems to be some compiler errors with the latest VS 2019:

![image](https://user-images.githubusercontent.com/10852185/149239066-6c27bc11-3f81-462b-b222-cfe084117535.png)

### Steps To Reproduce

1. Sync repo main
2. Open Microsoft.ReactNative.sln
3. 3. Build Debug x86

### CLI version

npx react-native --version

### Environment

```markdown
npx react-native info
```

### Visual Studio Version

Visual Studio 2019

### Build Configuration

Debug

**Comment by jonthysell** [comment]
Tracking the issue with DevDiv here: https://developercommunity.visualstudio.com/t/internal-compliler-error-when-building-in-latest-v/1635900

**Comment by chrisglein** [comment]
@jonthysell has an open channel with that team going on. Assigning to him just because he has the most recent status.

**Comment by jonthysell** [comment]
The only machine I've seen this on had a bad stick of RAM. It doesn't appear to repro on any other machine. After removing the bad RAM, it no longer repros on the original machine.

Closing this, will reopen if it somehow reappears.
