### ISSUE TITLE
Add CLI usage telemetry to drive OKRs and data-based decision making

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#9380]
Spec [internal link](https://microsoft.sharepoint-df.com/:x:/t/ReactNativeMicrosoft/EYtBHzeMVvRFh4YCElQ9aMMBjng9T-ds2nxhWUykY6X9yQ?e=awNfYJ&isSPOFile=1)

https://github.com/microsoft/react-native-windows/issues/9380#tasklist-block-7862bf8f-0c14-4f4b-8eb1-b4a4040be2a1

**Comment by chrisglein** [comment]
Notes from planning poker

> Telemetry is enabled in main, but there is no actual endpoint. Need to set up a test endpoint and verify the data is coming through nicely, look through in Application Insights.
There may be additional things we want to capture (e.g. msbuild props). Then will switch from test instance to a real instance, and looking over data with PM (time needed for positive handoff here). Will be some issue to fill in missing fields, but this is mostly about getting Application Insights running in an official capacity.
There will be delays due to requests and waiting for red tape, finding right approvers, etc.

**Comment by jonthysell** [comment]
This is getting closer, leaving on 0.69 for now but this may move to 0.70.

**Comment by jonthysell** [comment]
As we explore 1DS onboarding, the details of this task may change slightly.

**Comment by TatianaKapos** [comment]
Is this something we want to think about to add to Fabric?

**Comment by chrisglein** [comment]
Need to clarify what this covers versus that actual switch to 1DS: https://github.com/microsoft/react-native-windows/issues/10473

**Comment by danielayala94** [comment]
This work needs to build a "simple" dashboard, while measures with threshold need to be placed in a Health Monitor dashboard.

**Comment by chrisglein** [comment]
Initial dashboard created, we're on to refinement now!
