### ISSUE TITLE
npx react-native run-windows fails on Getting Started guide for Windows development

### ISSUE THREAD

**Issue by mpconte** [microsoft/react-native-windows#9390]
### Problem Description

On following the getting started guide for running the demo react native application on Windows, on the **Running a React Native Windows App** step, the `npx react-native run-windows` commands fails:

- Auto-linking...
Parsing project...
Found Windows app project, config:
{
  folder: 'D:\\software\\react_native_demo',
  sourceDir: 'windows',
  solutionFile: 'react_native_demo.sln',
  project: {
    projectFile: 'react_native_demo\\react_native_demo.vcxproj',
    projectName: 'react_native_demo',
    projectLang: 'cpp',
    projectGuid: '{70e4f165-f77b-49e7-a3e3-5d316259bfe8}'
  },
  experimentalFeatures: {
    UseHermes: 'false',
    UseWinUI3: 'false',
    UseExperimentalNuget: 'false'
  }
}
Parsing dependencies...
Calculating AutolinkedNativeModules.g.cpp...
Reading AutolinkedNativeModules.g.cpp...
No changes to AutolinkedNativeModules.g.cpp.
Calculating AutolinkedNativeModules.g.props...
Reading AutolinkedNativeModules.g.props...
No changes to AutolinkedNativeModules.g.props.
Calculating AutolinkedNativeModules.g.targets...
Reading AutolinkedNativeModules.g.targets...
No changes to AutolinkedNativeModules.g.targets.
Calculating react_native_demo.sln changes...
 √ Auto-linking...
Success: No auto-linking changes necessary. (121ms)
Looking for vswhere at: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe
 √ Found compatible MSBuild at C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin (16.11.32002.261)
 √ Found Solution: D:\software\react_native_demo\windows\react_native_demo.sln
 i Build configuration: Debug
 i Build platform: x86
Running MSBuild with args /clp:NoSummary;NoItemAndPropertyList;Verbosity=normal /nologo /p:Configuration=Debug /p:Platform=x86 /p:AppxBundle=Never /bl /flp1:errorsonly;logfile=C:\Users\mconte\AppData\Local\Temp\msbuild_23996_build.err /flp2:warningsonly;logfile=C:\Users\mconte\AppData\Local\Temp\msbuild_23996_build.wrn /maxCpuCount /restore /p:RestorePackagesConfig=true /p:RunAutolinkCheck=false
 C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe /nologo /bl /clp:NoSummary;NoItemAndPropertyList;Verbosity=normal /flp1:errorsonly;logfile=C:\Users\mconte\AppData\Local\Temp\msbuild_23996_build.err /flp2:warningsonly;logfile=C:\Users\mconte\AppData\Local\Temp\msbuild_23996_build.wrn /maxCpuCount /p:Configuration=Debug /p:Platform=x86 /p:AppxBundle=Never /p:RestorePackagesConfig=true /p:RunAutolinkCheck=false /restore D:\software\react_native_demo\windows\react_native_demo.sln
Build started 1/18/2022 9:14:51 AM.
     1>Project "D:\software\react_native_demo\windows\react_native_demo.sln" on node 1 (Restore target(s)).
     1>ValidateSolutionConfiguration:
         Building solution configuration "Debug|x86".
     0>D:\software\react_native_demo\node_modules\react-native-windows\PropertySheets\JSEngine.props(4,3): warning MSB4011: "D:\soft
       ware\react_native_demo\windows\ExperimentalFeatures.props" cannot be imported again. It was already imported at "D:\software\
       react_native_demo\windows\react_native_demo\react_native_demo.vcxproj (3,3)". This is most likely a build authoring error. Th
       is subsequent import will be ignored.
       _GetAllRestoreProjectPathItems:
         Determining projects to restore...
     1>Done Building Project "D:\software\react_native_demo\windows\react_native_demo.sln" (Restore target(s)).
   1:2>Project "D:\software\react_native_demo\windows\react_native_demo.sln" on node 1 (default targets).
     1>ValidateSolutionConfiguration:
         Building solution configuration "Debug|x86".
   1:2>Project "D:\software\react_native_demo\windows\react_native_demo.sln" (1:2) is building "D:\software\react_native_demo\window
       s\react_native_demo\react_native_demo.vcxproj.metaproj" (8) on node 1 (default targets).
     8>Project "D:\software\react_native_demo\windows\react_native_demo\react_native_demo.vcxproj.metaproj" (8) is building "D:\soft
       ware\react_native_demo\node_modules\react-native-windows\Microsoft.ReactNative\Microsoft.ReactNative.vcxproj" (7:10) on node
       5 (default targets).
  7:10>Project "D:\software\react_native_demo\node_modules\react-native-windows\Microsoft.ReactNative\Microsoft.ReactNative.vcxproj"
        (7:10) is building "D:\software\react_native_demo\node_modules\react-native-windows\Common\Common.vcxproj" (3:8) on node 2 (
       default targets).
     3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(439,5): e
       rror MSB4018: The "VCMessage" task failed unexpectedly. [D:\software\react_native_demo\node_modules\react-native-windows\Comm
       on\Common.vcxproj]
       C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(439,5): e
       rror MSB4018: System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the
       argument list. [D:\software\react_native_demo\node_modules\react-native-windows\Common\Common.vcxproj]
       C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(439,5): e
       rror MSB4018:    at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args) [
       D:\software\react_native_demo\node_modules\react-native-windows\Common\Common.vcxproj]
       C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(439,5): e
       rror MSB4018:    at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args) [D:\software\react_
       native_demo\node_modules\react-native-windows\Common\Common.vcxproj]
       C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(439,5): e
       rror MSB4018:    at System.String.Format(IFormatProvider provider, String format, Object[] args) [D:\software\react_native_de
       mo\node_modules\react-native-windows\Common\Common.vcxproj]
       C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(439,5): e
       rror MSB4018:    at Microsoft.Build.Shared.ResourceUtilities.FormatString(String unformatted, Object[] args) [D:\software\rea
       ct_native_demo\node_modules\react-native-windows\Common\Common.vcxproj]
       C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(439,5): e
       rror MSB4018:    at Microsoft.Build.Utilities.TaskLoggingHelper.FormatString(String unformatted, Object[] args) [D:\software\
       react_native_demo\node_modules\react-native-windows\Common\Common.vcxproj]
       C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(439,5): e
       rror MSB4018:    at Microsoft.Build.Utilities.TaskLoggingHelper.FormatResourceString(String resourceName, Object[] args) [D:\
       software\react_native_demo\node_modules\react-native-windows\Common\Common.vcxproj]
       C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(439,5): e
       rror MSB4018:    at Microsoft.Build.Utilities.TaskLoggingHelper.LogErrorWithCodeFromResources(String messageResourceName, Obj
       ect[] messageArgs) [D:\software\react_native_demo\node_modules\react-native-windows\Common\Common.vcxproj]
       C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(439,5): e
       rror MSB4018:    at Microsoft.Build.CPPTasks.VCMessage.Execute() [D:\software\react_native_demo\node_modules\react-native-win
       dows\Common\Common.vcxproj]
       C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(439,5): e
       rror MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [D:\softwa
       re\react_native_demo\node_modules\react-native-windows\Common\Common.vcxproj]
       C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(439,5): e
       rror MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() [D:\software\react_native_d
       emo\node_modules\react-native-windows\Common\Common.vcxproj]
     3>Done Building Project "D:\software\react_native_demo\node_modules\react-native-windows\Common\Common.vcxproj" (default target
       s) -- FAILED.
   1:2>Project "D:\software\react_native_demo\windows\react_native_demo.sln" (1:2) is building "D:\software\react_native_demo\node_m
       odules\react-native-windows\ReactCommon\ReactCommon.vcxproj.metaproj" (9) on node 1 (default targets).
     9>Project "D:\software\react_native_demo\node_modules\react-native-windows\ReactCommon\ReactCommon.vcxproj.metaproj" (9) is bui
       lding "D:\software\react_native_demo\node_modules\react-native-windows\Folly\Folly.vcxproj" (5:10) on node 1 (default targets
       ).
  5:10>Project "D:\software\react_native_demo\node_modules\react-native-windows\Folly\Folly.vcxproj" (5:10) is building "D:\software
       \react_native_demo\node_modules\react-native-windows\Fmt\Fmt.vcxproj" (6:8) on node 4 (default targets).
     6>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(439,5): e
       rror MSB4018: The "VCMessage" task failed unexpectedly. [D:\software\react_native_demo\node_modules\react-native-windows\Fmt\
       Fmt.vcxproj]
       C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(439,5): e
       rror MSB4018: System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the
       argument list. [D:\software\react_native_demo\node_modules\react-native-windows\Fmt\Fmt.vcxproj]
       C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(439,5): e
       rror MSB4018:    at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args) [
       D:\software\react_native_demo\node_modules\react-native-windows\Fmt\Fmt.vcxproj]
       C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(439,5): e
       rror MSB4018:    at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args) [D:\software\react_
       native_demo\node_modules\react-native-windows\Fmt\Fmt.vcxproj]
       C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(439,5): e
       rror MSB4018:    at System.String.Format(IFormatProvider provider, String format, Object[] args) [D:\software\react_native_de
       mo\node_modules\react-native-windows\Fmt\Fmt.vcxproj]
       C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(439,5): e
       rror MSB4018:    at Microsoft.Build.Shared.ResourceUtilities.FormatString(String unformatted, Object[] args) [D:\software\rea
       ct_native_demo\node_modules\react-native-windows\Fmt\Fmt.vcxproj]
       C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(439,5): e
       rror MSB4018:    at Microsoft.Build.Utilities.TaskLoggingHelper.FormatString(String unformatted, Object[] args) [D:\software\
       react_native_demo\node_modules\react-native-windows\Fmt\Fmt.vcxproj]
       C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(439,5): e
       rror MSB4018:    at Microsoft.Build.Utilities.TaskLoggingHelper.FormatResourceString(String resourceName, Object[] args) [D:\
       software\react_native_demo\node_modules\react-native-windows\Fmt\Fmt.vcxproj]
       C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(439,5): e
       rror MSB4018:    at Microsoft.Build.Utilities.TaskLoggingHelper.LogErrorWithCodeFromResources(String messageResourceName, Obj
       ect[] messageArgs) [D:\software\react_native_demo\node_modules\react-native-windows\Fmt\Fmt.vcxproj]
       C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(439,5): e
       rror MSB4018:    at Microsoft.Build.CPPTasks.VCMessage.Execute() [D:\software\react_native_demo\node_modules\react-native-win
       dows\Fmt\Fmt.vcxproj]
       C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(439,5): e
       rror MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [D:\softwa
       re\react_native_demo\node_modules\react-native-windows\Fmt\Fmt.vcxproj]
       C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(439,5): e
       rror MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() [D:\software\react_native_d
       emo\node_modules\react-native-windows\Fmt\Fmt.vcxproj]
     6>Done Building Project "D:\software\react_native_demo\node_modules\react-native-windows\Fmt\Fmt.vcxproj" (default targets) --
       FAILED.
     5>Done Building Project "D:\software\react_native_demo\node_modules\react-native-windows\Folly\Folly.vcxproj" (default targets)
        -- FAILED.
     9>Done Building Project "D:\software\react_native_demo\node_modules\react-native-windows\ReactCommon\ReactCommon.vcxproj.metapr
       oj" (default targets) -- FAILED.
     7>Done Building Project "D:\software\react_native_demo\node_modules\react-native-windows\Microsoft.ReactNative\Microsoft.ReactN
       ative.vcxproj" (default targets) -- FAILED.
     8>Done Building Project "D:\software\react_native_demo\windows\react_native_demo\react_native_demo.vcxproj.metaproj" (default t
       argets) -- FAILED.
     1>Done Building Project "D:\software\react_native_demo\windows\react_native_demo.sln" (default targets) -- FAILED.

### Steps To Reproduce

1. Follow the steps [here](https://microsoft.github.io/react-native-windows/docs/getting-started`)
2. On **Running a React Native Windows App**, the `npx react-native run-windows` command fails

### Expected Results

According to the guide, "A new Command Prompt window will open with the React packager as well as a react-native-windows app."

### CLI version

6.3.1

### Environment

```markdown
System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 17.45 GB / 31.81 GB
  Binaries:
    Node: 16.13.2 - C:\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.1.2 - C:\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      Versions: 10.0.16299.0, 10.0.17134.0, 10.0.19041.0
  IDEs:
    Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7784292
    Visual Studio: 16.11.32002.261 (Visual Studio Enterprise 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.66.0 => 0.66.0
    react-native-windows: 0.66.7 => 0.66.7
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2019

### Build Configuration

Debug

**Comment by chrisglein** [comment]
> 3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(439,5): error MSB4018: The "VCMessage" task failed unexpectedly. [D:\software\react_native_demo\node_modules\react-native-windows\Comm
on\Common.vcxproj]

This looks like the same error that was hit here: #8817. You should be okay with the 19041 SDK, so perhaps the cause is different.
A possible mitigation is for you to upgrade to VS 2022. VS 2019 should work, but if you are blocked you might want to try that.

**Comment by asklar** [comment]
the build error being hit in Microsoft.CppBuild.targets is this line:

```xml
    <!-- Error if toolset not found -->
    <VCMessage Code="MSB8020" Type="Error" Arguments="$(_PlatformToolsetShortName);$(PlatformToolset)" Condition="'$(DesignTimeBuild)' != 'true' and '$(_ToolsetFound)' != 'true'" />
```

so something about the toolset is not being properly detected or installed

**Comment by Invius** [comment]
This worked for me, the start guide should be updated:
npx react-native run-windows --sln .\windows\lenastoregep3.sln --proj .\windows\lenastoregep3\lenastoregep3.vcxproj
