### ISSUE TITLE
RNW supports WinAppSDK – Phase 4 “Default” 

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#9394]
Building on top of [general support for WinAppSDK](https://github.com/microsoft/react-native-windows/issues/9393), this issue tracks the set of sub-issues that are required before RNW would change the _default_ from UWP to WinAppSDK.

It's expected that as part of this UWP support still exists in parallel, but is not the default option for new projects.

[Phase 0](https://github.com/microsoft/react-native-windows/issues/9599) | [Phase 1](https://github.com/microsoft/react-native-windows/issues/9600) | [Phase 2](https://github.com/microsoft/react-native-windows/issues/9601) | [Phase 3](https://github.com/microsoft/react-native-windows/issues/9393) | Phase 4

### Estimated Schedule
```mermaid
gantt
    section WinAppSDK
    Phase 0 "Prototype" :done, phase0, 2022-01-01, 2022-03-21
    Phase 1 "Experimental" :done, phase1, 2022-03-28, 53d
    Phase 2 "Preview": done, phase2, after phase1, 22d
    Phase 3 "Stable"  : done, phase3, after phase2, 40d
    Phase 4 "Default"  : active, phase4, after phase3, 26d
    9140 : phase4a, after phase3, 5d
    9138 : phase4b, after phase4a, 5d
    9590 : phase4c, after phase4b, 5d
    4305 : phase4e, after phase4c, 5d
    9197 : phase4f, after phase3, 5d
    9546 : phase4g, after phase4f, 5d
    9135 : phase4d, after phase4g, 5d
    9711 : phase4h, after phase4d, 5d
```

### Phase 4 "Default"
- [ ] #9140
- [x] #9138
- [x] #9590
- [ ] #4305
- [ ] #9197
- [ ] #9546
- [ ] #9135 (Engineering efficiency (internal-facing) to reduce our test matrix and make us more agile)
- [ ] #9711 

### Future (not yet in WinAppSDK roadmap)
- [ ] #9134
- [ ] #9133

**Comment by rtorr** [comment]
Is there still plans for this to move forward?

**Comment by chrisglein** [comment]
Back in late 2021 / early 2022 we started a WinAppSDK new app template based on understanding of WinAppSDK at the time. And then came [Fabric](https://github.com/microsoft/react-native-windows/issues/12042) and impact on our overall strategy for how to handle Win32/WinAppSDK. As such these original plans don't make as much sense and we'll be closing them as Not Planned. That's not in any way to say RNW isn't going to support WinAppSDK, we're just doing it differently! Track our [Fabric](https://github.com/microsoft/react-native-windows/issues/12042) progress for details on the new app template and how that'll be compatible with WinAppSDK.
