### ISSUE TITLE
Crash when double-removing items.

### ISSUE THREAD

**Issue by Pokute** [Microsoft/react-native-windows#940]
ReactNative app crashes when same item is removed twice.
The exception is thrown at NativeViewHierarchyManager.cs:230.

I have an application with lots of animations and nifty stuff, which makes things slow on ReactNativeWindows, even natively on desktop.

In this application I have a list of items, number of which can be controlled by a "number of items: [-] 15 [+]"  -control. Additionally each item has a remove button.

Each remove takes a bit less than as second, so with fast clicking I can fill the command queue with "decrease items" events. While the items are being decreased, I can still click the "remove" -button of an item and the exception is thrown when the queue reaches the "remove"- event for an item which has already been removed.

**Comment by rozele** [comment]
@Pokute which API are you calling to remove items from the list?  Do you have sample code?

**Comment by Pokute** [comment]
I'm not sure, but it looks like we just basically give less data for <TableView />

**Comment by Pokute** [comment]
It actually is a
`[-] 2 [+]

 +-table-+ +-removes-+
  | row1   |   | remove1 |
  | row2   |   | remove2 |
 +-------+ +---------+`

So when a remove-button will remove from both the table and the removes list. Reducing the amount of items also does both.

**Comment by rozele** [comment]
would it be possible to just isolate that component and send it as sample code?

**Comment by Pokute** [comment]
I forgot my laptop charger at work, so prolly not.

**Comment by Pokute** [comment]
TableView just distplays items based on rowCount, columnCount and data.

**Comment by rozele** [comment]
Makes sense, but it's tough to diagnose what's going on without a repro, I get the issue, but I'm not sure what component is causing it (animation, UIManager, etc.)

**Comment by Pokute** [comment]
It should be pretty obvious that EnqueueManageChildren will result in problems.
It enqueues **indices** of children. So if two remove operations for children of the same parent are in the queue in the same time, then after the first remove, the second remove might remove the wrong child.

**Comment by Pokute** [comment]
`NativeViewHierarchyOptimizer.NativeManageChildren `has following code:

`            // We operate on tagsToRemove instead of indicesToDelete because by
            // the time this method is called, these views have already been
            // removed from the shadow hierarchy and the indices are no longer
            // useful to operate on.
            for (var i = 0; i < tagsToRemove.Length; ++i)
            {
                var tagToRemove = tagsToRemove[i];
                var delete = tagsToDelete.Contains(tagToRemove);
                var nodeToRemove = _shadowNodeRegistry.GetNode(tagToRemove);
                RemoveNodeFromParent(nodeToRemove, delete);
            }
`

and `NativeViewHierarchyOptimizer.RemoveNodeFromParent` immediately converts them to indices.
`                var index = nativeNodeToRemoveFrom.GetIndexOfNativeChild(nodeToRemove);
`

**Comment by Pokute** [comment]
Tried to make a test case from scratch but getting it to crash similarly didn't succeed (at least easily).
I suspect now that Redux might be needed for the crash to manifest.

**Comment by Pokute** [comment]
... I can see some pretty obvious removal bugging pretty easily in our app (without the app crashing), but debugging it isn't easy. Adding a System.Diagnostics.Debug.Writeline() into one function I was interested in completely "fixes" the issue.

**Comment by rozele** [comment]
@Pokute do you have an option of sharing your app in a private repo? I could try to debug from there.  The Debug.WriteLine removes the double remove race condition because it takes a global lock.

**Comment by Pokute** [comment]
@rozele Working on isolating the code.

**Comment by Pokute** [comment]
I finally have a test case. Clone, run npm install and run with react-native run-windows.

Add a couple of items with [+] buttons.
First click to [-] button should remove the last row, **but also removes** the [remove]-button from another row.

This test case doesn't crash as readily as our product code with same problem, but I think the same issue is at play.

https://github.com/Pokute/RNWListCrashTest

**Comment by rozele** [comment]
This still feels like a bug in the app logic itself.  Did you make any progress on debugging this?

**Comment by sayar** [comment]
@Pokute were you able to resolve this issue?

**Comment by rozele** [comment]
Closing stale issue.
