### ISSUE TITLE
Update needed to support react native 0.67.0

### ISSUE THREAD

**Issue by queltalent** [microsoft/react-native-windows#9411]
### Problem Description

warning " > react-native-windows@0.66.7" has incorrect peer dependency "react-native@^0.66.0".
warning "react-native-windows > @react-native-windows/virtualized-list@0.66.0" has incorrect peer dependency "react-native@0.66.0"

### Steps To Reproduce

upgrade to react native 0.67.0. The warnings are expected.

### CLI version

6.4.0

### Environment

Binaries:
    Node: 14.15.3 - /usr/local/bin/node
    Yarn: 1.22.17 - ~/test/node_modules/.bin/yarn
    npm: 6.14.9 - /usr/local/bin/npm
  npmPackages:
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.0 => 0.67.0 
    react-native-windows: ^0.66.7 => 0.66.7
  Installed UWP SDKs:

**Comment by queltalent** [comment]
> This issue lacks the environment info requested in the bug template. Please edit your issue report to add this information.
> 
> If you are using latest version:
> 
> 1. `npx react-native --version`:
> 2. `npx react-native run-windows --info`:
> 
> Otherwise if `--info` doesn't exist:
> 
> 1. `react-native -v`:
> 2. `npm ls rnpm-plugin-windows`:
> 3. `npm ls react-native-windows`:
> 4. `node -v`:
> 5. `npm -v`:
> 6. `yarn --version`:

environment info added

**Comment by asklar** [comment]
react-native-windows 0.67 is now live 🥳
https://www.npmjs.com/package/react-native-windows/v/0.67.0
