### ISSUE TITLE
Can no longer autolink native modules of `OutputType` `Library` after upgrade to 0.66.7

### ISSUE THREAD

**Issue by jeanmaried** [microsoft/react-native-windows#9420]
### Problem Description

I am trying to ugrade RN from 0.64.23 to 0.66.7. I am running into an issue where I can no longer autolink certain custom native modules. 

The cause of this issue is that these librarie have an `OutputType` of `Library` in .csproj while now the only type of native modules allowed are of `OuputType` `winmdobj`:  https://github.com/microsoft/react-native-windows/blob/6dd9d8183c3dcf582684ae136a6fb771a213ed80/packages/%40react-native-windows/cli/src/config/dependencyConfig.ts#L280

I read through this issue https://github.com/microsoft/react-native-windows/issues/8072 and see this PR: https://github.com/microsoft/react-native-windows/pull/8099

I am not sure I understand the reasoning behind why we can only allow native modules that are `winmdobj`.

This puts us in a situation where we need to either refactor entire libraries to be of type `winmdobj` that previously worked fine or else create a patch to get around this restriction.

What are the potential drawbacks of allowing modules of type `Library`? Was this tightening of the types necessary? If so, please help me understand. Thank you.

### Steps To Reproduce

1. Create a Native Module of with an `OutputType` of `Library`
2. Install it in a windows enabled react-native app
3. Run `npx react-native autolink-windows`
4. Library is not autolinked and we get `Error: MyLibPath.csproj is type 'library'

### Expected Results

Native module should autolink even if OutputType is `Library`

### CLI version

6.4.0

### Environment

```markdown
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 6.44 GB / 15.69 GB
  Binaries:
    Node: 14.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      Versions: 10.0.17763.0, 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.32002.261 (Visual Studio Enterprise 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.66.4 => 0.66.4
    react-native-windows: 0.66.7 => 0.66.7
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Platform Version

10.0.16299

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2019

### Build Configuration

Debug

**Comment by tido64** [comment]
The original intention is to not link in projects that do not produce a library, i.e. apps. I think we simply missed the `library` type here. It should be added. @jeanmaried: Is this something you can do? I think it will be easier for you to verify as well.

**Comment by jeanmaried** [comment]
@tido64 I will open a PR this week.

**Comment by tido64** [comment]
Closing since #9427 was merged.
