### ISSUE TITLE
Unable to switch SampleApps.sln build platform in Visual Studio

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#9424]
### Problem Description

I'm trying to build SampleApps.sln, Debug x86, from main, in any VS supported version. By default when I open the solution, Debug ARM64 is chosen.

If I switch to x86, VS hangs forever:

![image](https://user-images.githubusercontent.com/10852185/150844516-0c84f5c6-70dc-4688-808e-5a6599de6750.png)

This does not repro with 0.67-stable. I believe this may be some kind of race condition with VS trying to restore the nuget packages because of the new PackageReference stuff.

### Steps To Reproduce

1. Clone, yarn install, yarn build repo
2. Open SampleApps.sln in VS 2019 or 2022
3. Change build platform to x86

### Expected Results

Solution changes platform so I can build it

### CLI version

npx react-native --version

### Environment

```markdown
npx react-native info
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

2019, 2022

### Build Configuration

Debug

**Comment by asklar** [comment]
@JunielKatarn Jon thinks this might be due to the PackageReference change, could you take a look?

**Comment by JunielKatarn** [comment]
I'll take a look today. Verifying this should be simple.

**Comment by JunielKatarn** [comment]
I have successfully reproduced the issue on the latest `main` commit as of today (`6dd9d8183c3dcf582684ae136a6fb771a213ed80`).

Environment:
- npx 8.2.0

However, this may not be inherent to the `PackageReference` feature.

- Commit `522f0c8f1eec1a4e52ea4105685b99a5f3ea96d9`: No repro\
  Last commit before introducing `PacageReference` for C++ projects.
- Commit `bcdf9ad68eeda2967062f5137bc0f248e2ce7897`: **No repro** either\
  Commit introducing the `PackageReference` for C++ feature.

I'll do a binary search to find the first commit that hits the issue consistently.

**Comment by JunielKatarn** [comment]
Bug confirmed also in Visual Studio 2022.

**Comment by JunielKatarn** [comment]
But introduced by commit `ff37d64c0d44623d9884e5df7f0f027e4371d53c` (#9401).
