### ISSUE TITLE
Unable to build playground.sln with VS 2019 in main

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#9436]
### Problem Description

Trying to build playground.sln in main fails with a bunch of errors.

![image](https://user-images.githubusercontent.com/10852185/151432976-c8d9873e-44bf-4a81-8543-9f9216d59735.png)

### Steps To Reproduce

1. Clone repo.
2. `yarn && yarn build`
3. Open playground.sln in VS 2019
4. Switch to x86
5. Build Solution

### Expected Results

Solution builds.

### CLI version

npx react-native --version

### Environment

```markdown
info Fetching system and libraries information...
error Unable to print environment info.
Error: Command failed: wmic os get Caption
'wmic' is not recognized as an internal or external command,
operable program or batch file.


info React Native v0.60.0 is now available (your project is running on v0.0.0-20220107-2008-ca5aaa766).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.60.0.
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.0.0-20220107-2008-ca5aaa766.
info To upgrade, run "react-native upgrade".
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2019

### Build Configuration

Debug

**Comment by JunielKatarn** [comment]
Confirmed bug.

The MSBuild `Restore` run form `packages.config` is not working as expected for the playground project:

```
msbuild.exe /t:Restore "/p:RestoreProjectStyle=PackagesConfig;RestorePackagesConfig=true" .\playground\Playground.vcxproj
```

(No packages are restored into `$(SolutionDir)packages\`.

**Comment by JunielKatarn** [comment]
Root cause found.

When building with Visual Studio and explicitly (but automatically) restoring using the `PackagesConfig` restore style, property `RestoreUseStaticGraphEvaluation` set to `true` makes the target fail.
