### ISSUE TITLE
An image paints wrong after resuming from sleep

### ISSUE THREAD

**Issue by burtonrodman** [microsoft/react-native-windows#9443]
### Problem Description

I have a logo image (png) in my app's Header component that 99% of the time paints perfectly fine.

However, occassionally when resuming from sleep, it will paint a completely different image:
![image](https://user-images.githubusercontent.com/7658657/151815870-8f9ab018-fbee-468d-a2dd-0576be0197ac.png)

I don't know where the 2 X shapes are coming from, but the red and blue bits are from a _completely different image_ within my project.

Here is the markup.  There is no other logic associated with this.
`
            <View style={styles.headerCenter}>
                <Image
                    source={require('./../../assets/logo-header.png')}
                    style={styles.imageLogo}
                    testID="logo-image"
                    onError={(e) => {
                        appContext.telemetry.logError(e.nativeEvent.error);
                    }}
                />
            </View>
`

### Steps To Reproduce

1. display Image using a require()
2. launch the app
3. image displays correctly 100% of the time.
3. let the computer go to sleep
4. resume
5. image displays incorrectly (maybe 50% of the time).

### Expected Results

always display correct image

### CLI version

5.0.1

### Environment

```markdown
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz  
    Memory: 13.55 GB / 31.59 GB
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE        
    Yarn: 1.22.15 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 17.0.32112.339 (Visual Studio Enterprise 2022), 17.1.32120.378 (Visual Studio Enterprise 2022)
  Languages:
    Java: 11.0.12 - C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.2 => 0.64.2
    react-native-windows: ~0.64.0 => 0.64.14
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2019

**Comment by jonthysell** [comment]
It looks like we're using composition for some images, which means we need to handle when the machine changes "device lost" (sleep, screen resolution changes, driver updates).

**Comment by burtonrodman** [comment]
@chrisglein ya, i've been trying to update to the latest version for the last few weeks and pulling my hair out with crashes, touch not working on webivew, more crashes, etc...

any chance we could somehow connect to work through these issues?

#superfrustrated #zeroproductivity

**Comment by chrisglein** [comment]
> @chrisglein ya, i've been trying to update to the latest version for the last few weeks and pulling my hair out with crashes, touch not working on webivew, more crashes, etc...

Somehow missed my GitHub notification on this one, yikes! Sorry you're having such a rough time. You're upgrading from 64 to 66, I assume? What method are you using to upgrade? Did you bump the version, regenerate the app template, or walk through upgrade helper? (info here: https://microsoft.github.io/react-native-windows/docs/upgrade-app)

**Comment by chrisglein** [comment]
> Here is the markup. There is no other logic associated with this.
<View style={styles.headerCenter}> <Image source={require('./../../assets/logo-header.png')} style={styles.imageLogo} testID="logo-image" onError={(e) => { appContext.telemetry.logError(e.nativeEvent.error); }} /> </View>

Can you share more of the styles that are applied to these elements, in case there's something in the configuration relevant to this repro? Best case is if you can get min repro in an [Expo Snack](https://snack.expo.dev/) (realizing that doesn't let you run the Windows part interactively, but it does help us understand the context related to Android/iOS/Web).

**Comment by burtonrodman** [comment]
i have finally been able to upgrade to 0.67.  I will report back if we see this issue again.
