### ISSUE TITLE
 Appearance Module and PlatformColor use App theme instead of the parent XAML element's ElementTheme

### ISSUE THREAD

**Issue by jechternach** [microsoft/react-native-windows#9448]
### Problem Description

The appearance module is using RequestedTheme(). We need the theme to be determined by the XAML element parent. If the app theme and parent elementsTheme are different then the theme resolves incorrectly and the PlatformColor uses the App Theme mode without checking if the parent element is using a different theme.

https://github.com/microsoft/react-native-windows/blob/77ebdd47cd2feead7885933ac351a045041bee2e/vnext/Microsoft.ReactNative/Modules/AppearanceModule.cpp

### Steps To Reproduce

1. Set the UWP's ApplicationTheme to Light by changing the Setting in System Settings or setting it in code
1. Set the RequestedTheme of the element containing the React Native Windows root control to Dark.
1. Observe that Appearance.getColorScheme() returns light instead of dark.
1. Observe that Text elements using PlatformColor("TextFillColorSecondaryBrush") (or equivalent) will render black text whereas one would expect white text in dark theme.

### CLI version

npx react-native --version

### Environment

```markdown
npx react-native info
```

**Comment by acoates-ms** [comment]
Appearance Module is global to the RN instance.  It's possible that you could have multiple ReactRootView's with different XAML parents and different themes, all running in the same instance.

As such the appearance module does not have enough context to provide you a per view theme information.

**Comment by asklar** [comment]
Like Andrew mentioned, the existing AppearanceModule is designed to work with the application's theme. There is no affordance today for notifying / using per-view theme (the core API just doesn't exist). 

Either you'd need to write a native module to expose this per-view functionality, or you'd need to set the application's theme so that the code can work with the existing AppearanceModule.

**Comment by asklar** [comment]
notes from sync: apps can't set RequestedTheme dynamically; the RNW code should probably use ActualTheme
In parallel we should figure out if there's a good way to just query the root element's ElementTheme, that doesn't tie up our hands in the future by requiring there be only 1 root view per RN instance

CC @acoates-ms @marlenecota

**Comment by jonthysell** [comment]
@marlenecota Do you think a switch to using ActualTheme will make 0.69 or should it be moved to 0.70?

**Comment by jonthysell** [comment]
@marlenecota 0.69 is almost here, moving to 0.70 for now, feel free to move it back if it'll make it.

**Comment by chiaramooney** [comment]
@marlenecota I don't believe there's an update here. Should this be moved to 71?
