### ISSUE TITLE
ReactCommon Files Forked Following Break from Upstream

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-windows#9451]
### Problem Description

Lots of changes made to MappBuffer code in ReactCommon in https://github.com/facebook/react-native/compare/ca5aaa766...20b9ed91c. Had to fork several files in order to restore Windows build.

TO-DO:
- [x] File a PR in react-native with the required changes to the MapBuffer files needed to not break Windows. See files in `vnext\ReactCommon\TEMP_UntilReactCommonUpdate` for source changes needed. 
- [ ] Remove TEMP_UntilReactCommonUpdate and its files from react-native-windows following merge of first todo.

**Comment by NickGerleman** [comment]
We should ideally be making these PRs at the same time as integrating. We otherwise pile on technical debt that tends to never get paid off.
