### ISSUE TITLE
Opening a solution in VS2022 breaks autolinking

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#9459]
Just opening a 2019 solution in vs2022 will do 2 things:
- add ARM
- rev the VS version
it looks like adding ARM is causing autolinking checks to fail

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/22989529/152268614-b026da91-f1a6-4874-bded-67295190fa3d.png">

**Comment by chrisglein** [comment]
Is the fact that VS is adding ARM to a project that didn't previously have ARM a VS bug?
Is it possible for autolinking to ignore ARM?
@asklar can we get the logs of what autolinking attempted?
What is the workaround? Does running linking again fix this? Supposedly there's a command in the error output that should fix this. Was it not reported? (that's a bug if so)

**Comment by chrisglein** [comment]
If we have persistent problems with VS2022 we should create a "known issues" pinned issue or something on the website. We need to trend towards that being supported and track the blocking issues before we can give it a firm 👍.
