### ISSUE TITLE
CLI tests use outdated project files

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#9500]
### Problem Description

We've made several template changes (specifically the new PackageReference work), but some of our CLI e2etests contain project files that were generated a while ago.

We should update the test assets so we can confirm that the CLI code is still being tested appropriately.

### Steps To Reproduce

yarn test

### CLI version

npx react-native --version

### Environment

```markdown
npx react-native info
```

**Comment by jonthysell** [comment]
One option is to update these tests to generate the project files and apply patches, rather than using checked in files that go out of date.

**Comment by chrisglein** [comment]
@jonthysell You had moved this up from targeting 69 to 68. Since we've had the snap of the stable branch, do you think this is trending to make the .0 release, or backport later, or leave for vnext? Is the reason for doing this now to time it alongside the PackageReference change?
