### ISSUE TITLE
Create a native module template set up to create custom ViewManagers

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#9506]
### Summary

Create a new lib template that includes XAML (correctly) and has a basic ViewManager example. Remove XAML dependencies from the basic lib template.

### Motivation

The default "lib" template sets up a native module that isn't creating UI, as such technically it doesn't need to depend on XAML libs. Adding that dependency just makes the build take longer.

However, if you do want to create a ViewManager, you'll not only want the template to include the right version of XAML (in sync with what the client app is using) but also have a basic example set up so devs have a better starting point.

**Comment by chiaramooney** [comment]
Not something we plan to address on the Paper renderer as we move towards Fabric.
This behavior should be different on the non-XAML Fabric renderer.
