### ISSUE TITLE
Support HTTP incremental updates

### ISSUE THREAD

**Issue by JunielKatarn** [microsoft/react-native-windows#9534]
### Summary

See #2460, #9510.

The `useIncrementalUpdates` argument is currently not used in the HTTP module implementation on Windows.

### Motivation

This feature is available in React Native for Apple platforms, therefore is expected behavior.

**Comment by NickGerleman** [comment]
Iirc there's another issue on this repo that may be about the same thing, since the lack of support broke axios.

**Comment by JunielKatarn** [comment]
> Iirc there's another issue on this repo that may be about the same thing, since the lack of support broke axios. 

That would be #2460, I think.
