### ISSUE TITLE
HTTP form data support

### ISSUE THREAD

**Issue by JunielKatarn** [microsoft/react-native-windows#9535]
### Summary

Current HTTP module implementation ignores form data to be sent as part of a request.

This is due to dropping `folly` APIs from `IHttpResource` so that the interface is forward-compatible with TurboModules.

This creates the need for conversion logic from a `folly::dynamic` object containing the form data to an either ABI safe or at least Standard Library-based object type.

### Motivation

Form data body types are supported in both Android and Apple variants of React Native.

**Comment by tero-paananen** [comment]
https://github.com/microsoft/react-native-windows/issues/10378
