### ISSUE TITLE
[0.64] E2ETest app depends on a private fork of webdriver package

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#9545]
### Problem Description

In 0.64 we have CG alerts for the package `validator`, and the reason we're on a bad version is because of a dependency on a range of webdriver-related packages with a specific, old version: 5.2.1.

More specifically, we're targeting a fork of that version: https://github.com/react-native-windows/webdriver

The latest v5 is 5.23.0.

We got rid of this private dependency when in RNW 0.65, when we upgraded to webdriver v6, so any fixes would only be for 0.64.

### Steps To Reproduce

Look at package.json resolutions.

### CLI version

npx react-native --version

### Environment

```markdown
npx react-native info
```

**Comment by jonthysell** [comment]
PR #9544 resolves the CG alert for validator, but still doesn't address the potential long-term serviceability of 0.64 with this fork. One proposed solution has been to "drop-in" replace the e2e-test-app from 0.65 which doesn't have this problem.

**Comment by chrisglein** [comment]
Probably okay to port the 0.65 change back to 0.64 as soon as we need to address this. But... at the moment we don't to? This is good documentation for what's the situation if we need to go back (if we have E2ETest issues - as that's all this affects). But as is I think 0.64 is enough out of support scope that we can default to Won't Fix this.
