### ISSUE TITLE
Using `flexWrap: "wrap-reverse"` on a View component makes the app crash

### ISSUE THREAD

**Issue by axelfratoniMS** [microsoft/react-native-windows#9569]
### Problem Description

Using a react-native-windows stylesheet with a `flexWrap: "wrap-reverse"` property on a View component makes the whole app crash and close.

### Steps To Reproduce

1. Create a react native windows project using Metro Bundler as server.
2. Create a View component with a `flexWrap: "wrap-reverse"` style property.
`<View style={{flexWrap: "wrap-reverse"}}>`
3. Load the app
4. The app crashes and closes.

### Expected Results

The app shouldn't close, and when resizing the view component, it's children (if any) should wrap placing the last ones from the row/column on top.

### CLI version

6.3.1

### Environment

```markdown
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Xeon(R) W-2235 CPU @ 3.80GHz
    Memory: 37.04 GB / 63.73 GB
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.32126.315 (Visual Studio Enterprise 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2019

### Build Configuration

Debug

**Comment by asklar** [comment]
Likely not implemented yet:
See https://github.com/microsoft/react-native-windows/blob/main/vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp#L452-L460
```cpp
    } else if (key == "flexWrap") {
      YGWrap wrap = YGWrapNoWrap;

      if (value == "nowrap" || value.IsNull())
        wrap = YGWrapNoWrap;
      else if (value == "wrap")
        wrap = YGWrapWrap;
      else
        assert(false);
```

This might be as simple as adding:
```cpp
else if (value == "wrap-reverse")
  wrap = YGWrapWrapReverse;
```
before the `else assert(false)`

**Comment by axelfratoniMS** [comment]
@asklar I've attached a debugger and confirmed that this is indeed the issue.
![image](https://user-images.githubusercontent.com/99926270/154769746-e6a3a9e2-d3d3-40c8-a238-0a3c92df1b5a.png)
I've added the missing line of code myself and was able to make the 'wrap-reverse' behave as expected.

**Comment by asklar** [comment]
spoke to Axel offline, he'll send a PR for this with the change I suggested above.
