### ISSUE TITLE
Move UsePackageReference logic from Directory.Build.props from cs lib/app template into a new prop sheet that is optional (behind a new flag)

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#9579]
### Problem Description

Directory.Build.props files only applies to projects within the same folder, of subfolders.

Due to the distributed nature of how RNW projects have the app project in a sub folder, with native modules in a completely different node in the filesystem, they won't get applied.

To fix this (and have this UsePackageReference project capability bit actually get applied) we should move UsePackageReference logic from Directory.Build.props from cs lib/app template into a new prop sheet that is optional (behind a new flag)
* Flag should default to true if not specified (let people turn it off)
* External CSharpLib and CppAppLib property sheet should consume it?

### Steps To Reproduce

Build a C# app with an autolinked C++ native module in node_modules that uses packages.config, an see that adding PackageRaference into the native module project won't cause the nuget to get restored

### CLI version

npx react-native --version

### Environment

```markdown
npx react-native info
```

**Comment by jonthysell** [comment]
Part of #7227

**Comment by jonthysell** [comment]
I think if PackageReference is going to be in 0.68, we should get this done *before* we snap 0.68.0, so that new 0.68 projects (fresh or upgrading) don't have theses files in their output conflicting with what we put in the targets.

@JunielKatarn FYI, because this involves PackageReference work.

**Comment by chrisglein** [comment]
Related to #9581 and #9580.
Similar sort of solution in this PR: #9372
