### ISSUE TITLE
M.RN PackageReferences should be specified within the external props/targets files and not directly in the template output (for apps and modules)

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#9580]
### Summary

M.RN PackageReferences should be specified within the external props/targets files and not directly in the template output (for apps and modules)

* Stop "hardcoding" the nuget package versions, use variable `$(ReactNativeWindowsVersion)`
* Condition on `UseExperimentalNuGet`
* Remove the injection into the app template

### Motivation

Community modules should follow the app's decision on whether to consume M.RN via source or nugets.

This can only be done by keying off the `UseExperimentalNuget` experimental features props file, and by consolidating the choice into the external property sheets, we can make sure that both the app project and every native module project all align on the same type (and version) of the dependency, rather than hardcoding that decision into the template files.

**Comment by jonthysell** [comment]
Part of #7227

**Comment by jonthysell** [comment]
I think if PackageReference is going to be in 0.68, we should get this done *before* we snap 0.68.0, so that new 0.68 projects (fresh or upgrading) don't have this in their template.

@JunielKatarn FYI, because this involves PackageReference work.

**Comment by NickGerleman** [comment]
0.68 was snapped a couple of weeks ago, originally targeting an end of March release. @JunielKatarn is still doing a little bit of fixup though.

Starting to cleanup `packages.config` related structures would be great. Community modules will all still be on `packages.config` for a while though. I think there are some things we can start to remove now, but others may need to wait until modules are caught up.
