### ISSUE TITLE
Hermes PackageReferences should be specified within the external props/targets files and not directly in the template output

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#9581]
### Summary

Your feature requestHermes PackageReferences should be specified within the external props/targets files and not directly in the template output

* Only include conditionally on UseHermes?
* Stop "hardcoding" the nuget package versions, use variable $(ReactNativeWindowsVersion)
* Remove the injection into the app template

### Motivation

Related to #9580, the decision to use Hermes (and how to consume it) needs to be by consolidating the choice into the external property sheets, we can make sure that both the app project and every native module project all align on the same type (and version) of the dependency, rather than hardcoding that decision into the template files.

### Open Questions

Does Hermes need to be installed even if it's never used? Can it actually be conditional now with PackageReferences?

**Comment by jonthysell** [comment]
Part of #7227

**Comment by chrisglein** [comment]
@jonthysell we've snapped 0.68 previews ~3 weeks ago (currently we're on [preview 3](https://github.com/microsoft/react-native-windows/releases/tag/react-native-windows_v0.68.0-preview.3)). I think what you're saying is we want to prioritize this before we release 0.68.0 (and not take for a dot release), is that correct?

**Comment by chrisglein** [comment]
I assume this is related to #9580, but for different projects?
