### ISSUE TITLE
Update usage docs for how to create modules for WinAppSDK

### ISSUE THREAD

**Issue by AgneLukoseviciute** [microsoft/react-native-windows#9602]
Before we "move" WinAppSDK support to Stable, we should update the docs to include instructions for WinAppSDK module creation.

**Comment by chrisglein** [comment]
Back in late 2021 / early 2022 we started a WinAppSDK new app template based on understanding of WinAppSDK at the time. And then came [Fabric](https://github.com/microsoft/react-native-windows/issues/12042) and impact on our overall strategy for how to handle Win32/WinAppSDK. As such these original plans don't make as much sense and we'll be closing them as Not Planned. That's not in any way to say RNW isn't going to support WinAppSDK, we're just doing it differently! Track our [Fabric](https://github.com/microsoft/react-native-windows/issues/12042) progress for details on the new app template and how that'll be compatible with WinAppSDK.
