### ISSUE TITLE
e.stopPropagation and e.preventDefault

### ISSUE THREAD

**Issue by jbcullis** [microsoft/react-native-windows#9614]
### Problem Description

e.stopPropagation and e.preventDefault do not stop the event bubbling onKeyDown in a TextInput element.

### Steps To Reproduce

Create the following element and type anything into it:

<TextInput value={this.state.txt} onKeyDown={(e) => {e.stopPropagation;e.preventDefault();}} onChangeText={(e) => {this.setState({txt: e});}}></TextInput>

### Expected Results

key should be cancelled preventing onChangeText from firing.

### CLI version

6.3.1

### Environment

```markdown
OS: Windows 10 10.0.22000
CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
Memory: 21.85 GB / 31.73 GB
Binaries:
Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
npm: 8.1.3 - C:\Program Files\nodejs\npm.CMD
Watchman: Not Found
SDKs:
Android SDK: Not Found
Windows SDK:
AllowDevelopmentWithoutDevLicense: Enabled
AllowAllTrustedApps: Enabled
Versions: 10.0.18362.0, 10.0.19041.0, 10.0.22000.0
IDEs:
Android Studio: Not Found
Visual Studio: 17.0.31912.275 (Visual Studio Community 2022)
Languages:
Java: Not Found
npmPackages:
@react-native-community/cli: Not Found
react: 17.0.2 => 17.0.2
react-native: 0.66.0 => 0.66.0
react-native-windows: 0.66.5 => 0.66.5
npmGlobalPackages:
react-native: Not Found
```

**Comment by chrisglein** [comment]
e.stopPropagation stops the JS propagation but not the native propagation. Can you clarify what the scenario is that you're trying to accomplish here? It sounds like you're trying to lock text input and set it to the previous value. Can you share more of the example?

**Comment by jbcullis** [comment]
@chrisglein underlying need is a masked input field.
We were trying to fix a cursor position issue and was exploring a way to cancel the keydown.
