### ISSUE TITLE
Stock C++ template should be buildable in 10s

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#9620]
Currently the C++ template app is a full-fledged UWP XAML app. This requires building IDL, running cppwinrt, compiling the many xaml cppwinrt headers, etc. This ends up taking a long time, even when using nuget (much more if you don't use nuget).

This template is useful for apps that need to customize a lot of the native app experience.
However, there will be many cases where 100% of the app logic lives purely in JS, and so having a bunch of native code that is slow to compile but doesn't do anything special, is wasteful.

I have a prototype where we can internalize the stock app scaffolding into M.RN, and then use a C++ app template that does very little.
This way the app can build in under 10s (when using nuget), which would provide a much better dev experience than we have today. Developers that need full control of their native app environment can fall back to the full app template (or host RNW as an island, for example)

**Comment by chrisglein** [comment]
> I have a prototype where we can internalize the stock app scaffolding into M.RN, and then use a C++ app template that does very little.

@asklar Can you reference your prototype and provide the list of changes that would need to happen for apps that don't have native code to benefit from this?

Scenario here seems to cover apps that have on custom view managers but can reference modules that do. Or put differently, if they don't have a XAML file, there are savings to be had. That's part of the cost, the other part is cpp/winrt (consuming APIs is enough), and as long as they are using react-native-winrt or WRL or whatever they don't need to pay that cost. Essentially, make the native build costs pay for play.

This is going to be a common scenario for a class of apps, would be great to have that fast and painless.

**Comment by NickGerleman** [comment]
Do we have a story for binary distribution and existing community modules yet? I think we know that it enables this sort of thing, but it has been blocked for the past years because there wasn't a story to update all the modules support was added to for the new format.

**Comment by NickGerleman** [comment]
Admittedly it sounds like that will happen with WinAppSDK anyway though 🤷‍♀️. If we are making a break or pushing for something where there will be limited compatibility, it would be best to do this sort of thing at the same time.
