### ISSUE TITLE
Playground app hangs on reload after breaking and continuing in direct debugger 

### ISSUE THREAD

**Issue by aeulitz** [microsoft/react-native-windows#9662]
### Problem Description

After a debugging session including a break and a continue operation, the RNW Playground app fails to render a new package. 

### Steps To Reproduce

1. start Metro bundler
2. start RNW playground app
3. in Playground app settings, enable "Direct Debugger" and select JS Engine "Hermes"
4. open a JS package (e.g. Samples/calculator)
5. in Chrome/Edge inspect page, select "inspect" link of "Hermes React Native" target
6. in Chrome/Edge inspector window, break and continue script execution
7. in Playground, attempt to open another JS package

Result:

Client area of Playground app indefinitely shows "Loading bundle" message and spinning wheel. 

In the above state, the GUI of the PG app responds to user input (e.g. main menu can be expanded/collapsed). Bundler console output indicates that it has served the bundle requested in step 7.

### Expected Results

Package selected in repro step 7 should get rendered and be debuggable.

### CLI version

7.0.3

### Environment

```markdown
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 Intel(R) Core(TM) i9-9900 CPU @ 3.10GHz
    Memory: 43.12 GB / 63.84 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.32126.315 (Visual Studio Enterprise 2019), 17.0.32126.317 (Visual Studio Enterprise 2022)
  Languages:
    Java: 11.0.12 - C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
info React Native v0.60.0 is now available (your project is running on v0.0.0-20220206-2010-113f8257c).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.60.0.
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.0.0-20220206-2010-113f8257c.
info To upgrade, run "react-native upgrade".
```

**Comment by jonthysell** [comment]
@aeulitz Was this fixed by #9827? Can this issue be closed?

**Comment by jonthysell** [comment]
@aeulitz Any updates on this?

**Comment by aeulitz** [comment]
Fixed in ReactCommon code per https://github.com/facebook/react-native/pull/34342. Fix currently gets patched into Hermes per https://github.com/microsoft/hermes-windows/pull/122. New hermes-windows getting pulled into RNW per https://github.com/microsoft/react-native-windows/pull/10368.

To not conflate this issue with more changes, I'll probably create a new issue to track the addition of a regression test to RNW.
