### ISSUE TITLE
error when running npx react-native-windows-init --overwrite it says  Cannot find module 'react-native/package.json'

### ISSUE THREAD

**Issue by sdhetarwal** [microsoft/react-native-windows#9666]
after running command npx react-native init projectName --template react-native@^0.67.0
and cd projectName
when i run command 
npx react-native-windows-init --overwrite
it shows error 

 The system cannot find the file specified.
Reading project name from package.json...
Reading react-native version from node_modules...
Cannot find module 'react-native/package.json'
Require stack:
- C:\Users\S DHETARWAL\AppData\Local\npm-cache\_npx\966c6a96be6f5a32\node_modules\react-native-windows-init\lib-commonjs\Cli.js
- C:\Users\S DHETARWAL\AppData\Local\npm-cache\_npx\966c6a96be6f5a32\node_modules\react-native-windows-init\bin.js
Error: Cannot find module 'react-native/package.json'
Require stack:
- C:\Users\S DHETARWAL\AppData\Local\npm-cache\_npx\966c6a96be6f5a32\node_modules\react-native-windows-init\lib-commonjs\Cli.js
- C:\Users\S DHETARWAL\AppData\Local\npm-cache\_npx\966c6a96be6f5a32\node_modules\react-native-windows-init\bin.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at getReactNativeVersion (C:\Users\S DHETARWAL\AppData\Local\npm-cache\_npx\966c6a96be6f5a32\node_modules\react-native-windows-init\src\Cli.ts:162:33)
    at Object.reactNativeWindowsInit (C:\Users\S DHETARmodules\react-native-windows-init\src\Cli.ts:520:27)   
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\S DHETARWAL\\AppData\\Local\\npm-cache\\_npx\\966c6a96be6f5a32\\node_modules\\react-native-windows-init\\lib-commonjs\\Cli.js',
    'C:\\Users\\S DHETARWAL\\AppData\\Local\\npm-cache\\_npx\\966c6a96be6f5a32\\node_modules\\react-native-windows-init\\bin.js'
  ]
}
Command failed. Re-run the command with --verbose for more information.

**Comment by CesariniFillipe** [comment]
Same here. If I run de command "npm install" before and then again "npx react-native-windows-init --overwrite", it shows the message:

Installing react-native-windows@0.67.3...
Cannot find module 'react-native-windows/package.json'
Require stack:
- C:\Users\Fillipe\AppData\Roaming\npm-cache\_npx\16564\node_modules\react-native-windows-init\lib-commonjs\Cli.js
- C:\Users\Fillipe\AppData\Roaming\npm-cache\_npx\16564\node_modules\react-native-windows-init\bin.js
Error: Cannot find module 'react-native-windows/package.json'

**Comment by chrisglein** [comment]
Other previous issues (all resolved one way or another) that could be helpful: #9271 #8718

**Comment by chrisglein** [comment]
This sounds like a bad state. Can you find the package.json in the file system? If it's not there, something failed to install. If it's there and it's not being found, that's another issue.
