### ISSUE TITLE
Having trouble building react-native-screens

### ISSUE THREAD

**Issue by AlenToma** [microsoft/react-native-windows#9667]
### Problem Description

Hi. So I am thinking of using `react-native-windows` for the first time.
After much googling, I was able to find the right version of react-navigation that will work with it which is version 5.x

After having installed the required component, I am unable to build it at all.

I am getting the following error.

```
 × Building Solution: Microsoft.ReactNative.Managed -> D:\Projects\TorrentStreamer\streamer\node_modules\react-na...
 × Build failed with message     10>D:\Projects\TorrentStreamer\streamer\node_modules\react-native-screens\windows\RNScreens\ScreenViewManager.h(12,42): error C2039: 'IViewManagerRequiresNativeLayout': is not a member of 'winrt::Microsoft::ReactNative' (compiling source file ScreenViewManager.cpp) [D:\Projects\TorrentStreamer\streamer\node_modules\react-native-screens\windows\RNScreens\RNScreens.vcxproj].

```

I am using this with C# and not C++

Here is my package dependencies

```json
  "dependencies": {
    "@alentoma/usestate": "^1.2.4",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-navigation/bottom-tabs": "^5.11.15",
    "@react-navigation/native": "^5.9.8",
    "react": "16.13.1",
    "react-native": "0.63.2",
    "react-native-reanimated": "^2.4.1",
    "react-native-safe-area-context": "^4.1.2",
    "react-native-screens": "^3.13.1",
    "react-native-windows": "0.63.41"
  },
  "devDependencies": {
    "@babel/core": "^7.8.4",
    "@babel/runtime": "^7.8.4",
    "@react-native-community/eslint-config": "^1.1.0",
    "@types/jest": "^27.4.1",
    "@types/react": "^17.0.39",
    "@types/react-native": "^0.67.2",
    "@types/react-test-renderer": "^17.0.1",
    "babel-jest": "^25.1.0",
    "eslint": "^6.5.1",
    "jest": "^25.1.0",
    "metro-react-native-babel-preset": "^0.59.0",
    "react-test-renderer": "16.13.1",
    "typescript": "^4.6.2"
  },

```

## Complete Output with --logging
Don't thing you need one but if required please do ask and I will upload it somewhere

### Steps To Reproduce

Follow the guide for https://reactnavigation.org/docs/5.x/getting-started and try to build the project

### Expected Results

The project should be build with no issue

### CLI version

4.14.0

### Environment

```markdown
npx react-native info
```

**Comment by chrisglein** [comment]
react-native-screens is used by the [react-native-gallery](https://github.com/microsoft/react-native-gallery) app. It has a different version specified in [its package.json](https://github.com/microsoft/react-native-gallery/blob/main/package.json). I'm not sure on the min supported version, but 0.63 may be too old.
