### ISSUE TITLE
Implement persistentScrollbar for ScrollView

### ISSUE THREAD

**Issue by CarpeDiEmma** [microsoft/react-native-windows#9673]
Creating an issue here per @acoates-ms to implement persistentScrollbar to allow for the scrollbar to remain visible outside of actively scrolling.

**Comment by chrisglein** [comment]
@CarpeDiEmma Do you have non-RNW native scroll bars you're forcing to show? If so, is that handled per instance or on a global app level.

As for this setting, yep it's a gap and should be implemented.
https://reactnative.dev/docs/virtualizedlist#persistentscrollbar

**Comment by CarpeDiEmma** [comment]
@chrisglein Not me in particular--I have been primarily working in RNW. From a quick glance around the xaml in the Xbox Shell Apps, the configuration is handled per instance. Also the "type" of scrollview also determines whether it is consistently shown or not--a right stick scroll bar scroll viewer will always have the scroll bar as persistent, whereas a left stick scroll bar scroll viewer may not.

**Comment by haightt** [comment]
Does this prop not work for any of the virtualized lists in RNW?

**Comment by chrisglein** [comment]
Not something we plan to address on the Paper renderer as we move towards Fabric.
Fabric API completion is tracked here: https://github.com/microsoft/react-native-windows/issues/11152
