### ISSUE TITLE
jsi::String::utf8 does not preserve embedded NULs when using Hermes

### ISSUE THREAD

**Issue by dunhor** [microsoft/react-native-windows#9681]
### Problem Description

If JavaScript code tries to invoke a function in a turbo module with a string that has an embedded NUL character in it (e.g. the string `'\0'`), then the string the application receives when it tries to read the value of the string via `jsi::String::utf8` will terminate before the NUL character.

Debugging, it seems that this is because the code seems to use some `IHermesString` (which seems absent from the `hermes.h` in the hermes repo; perhaps this is out of date? Or is this a forked file?). This type only has a `c_str` function, but lacks a `length`/`size` function, so when the application attempts to read the contents of the string, the `std::basic_string` constructor will only initialize with the contents up to the embedded NUL.

### Steps To Reproduce

Create a turbo module that has a function that accepts a string. In JavaScript, call that function with a string that contains an embedded NUL character. Compile the application to use Hermes. Observe that inside of the function that exists in the turbo module, the `std::string` that returned by `jsi::String::utf8` is a substring that contains all characters up to, but not including, the embedded NUL.

### Expected Results

Strings should be perfectly preserved, with all embedded NUL characters.

### CLI version

6.4.0

### Environment

```markdown
>npx react-native info
info Fetching system and libraries information...
error Unable to print environment info.
Error: Command failed: wmic os get Caption
'wmic' is not recognized as an internal or external command,
operable program or batch file.
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

Debug

**Comment by dunhor** [comment]
Neglected to mention that the version of Hermes that was auto-added to the project is `<package id="ReactNative.Hermes.Windows" version="0.10.0-ms.1" targetFramework="native" />`

**Comment by dunhor** [comment]
Investigating more, this only seems to happen when building Debug

**Comment by chrisglein** [comment]
> Debugging, it seems that this is because the code seems to use some `IHermesString` (which seems absent from the `hermes.h` in the hermes repo; perhaps this is out of date? Or is this a forked file?). 

Yeah, this doesn't seem to [be a thing on the hermes-windows](https://github.com/microsoft/hermes-windows/search?q=IHermesString) code, so it's coming from somewhere else?

@dunhor sounds like you're investigating, @vmoroz FYI in case there's something off in the Turbo Modules infrastructure here with handling the string.

**Comment by asklar** [comment]
`IHermesString` is [here](https://github.com/microsoft/hermes-windows/blob/main/API/hermes/hermes.h#L13) introduced in 0.8.1

**Comment by dunhor** [comment]
Filed the issue in that repo: https://github.com/microsoft/hermes-windows/issues/88

**Comment by dunhor** [comment]
> Sorry, forked repositories are not currently searchable.

Explains why neither of us found the code when searching :/
