### ISSUE TITLE
Can't call FolderPicker.PickSingleFolderAsync

### ISSUE THREAD

**Issue by dbm5858** [microsoft/react-native-windows#9694]
### Problem Description

Upgraded to RNW 0.67.3 from 0.63.5.  FolderPicker code now throws `Invalid window handle. (Exception from HRESULT: 0x80070578)` exception.  The code is directly from https://docs.microsoft.com/en-us/windows/uwp/files/quickstart-using-file-and-folder-pickers, and was working in RNW 0.63.5

```
var picker = new FolderPicker { SuggestedStartLocation = PickerLocationId.Downloads };
picker.FileTypeFilter.Add("*");

var folder = await picker.PickSingleFolderAsync();
```

### Steps To Reproduce

1. Create native method that calls the above code
2. Call the native method from a button in the RNW app

### Expected Results

Folder picker dialog should open

### CLI version

6.4.0

### Environment

```markdown
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 3.67 GB / 15.86 GB
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 30.0.2
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6858069
    Visual Studio: 16.9.31205.134 (Visual Studio Professional 2019)
  Languages:
    Java: javac 15 - C:\Users\MeilickD\dev\jdk-15\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: ^0.67.0 => 0.67.3
    react-native-windows: 0.67.3 => 0.67.3
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2019

### Build Configuration

Debug

### Snack, code example, screenshot, or link to a repository

var picker = new FolderPicker { SuggestedStartLocation = PickerLocationId.Downloads };
picker.FileTypeFilter.Add("*");

var folder = await picker.PickSingleFolderAsync();

**Comment by chrisglein** [comment]
What thread are you calling into `FolderPicker` from? That's going to need to be from the UI thread. There was a breaking change somewhere between 0.63 and 0.67 and you'll need to be mindful of the threading here (dispatching the call yourself). Let us know if that doesn't resolve your issue.

**Comment by dbm5858** [comment]
I'm not doing an thread management.  I just created a native method, and called it from the Javascript side.  Wouldn't that mean that it is on the UI thread?  Under 0.63 I believed it was on the UI thread, because if I didn't set the native methods up as async, the UI would block.

```
        [ReactMethod("pickDownloadDirectory")]
        public async void PickDownloadDirectory(IReactPromise<JSValue> promise)
        ...
        //  eventually calls the above code
```

If I do have to attach to the UI thread, how would I do that?

**Comment by dbm5858** [comment]
OK.  Found this:

https://microsoft.github.io/react-native-windows/docs/native-modules-async#executing-calls-to-api-on-the-ui-thread

Still digesting that.

**Comment by dbm5858** [comment]
That code works.  I'm now able to use the directory picker.  Life is good!

Thanks for the assist.
