### ISSUE TITLE
Rename / Rethink project creation flags for WinAppSDK

### ISSUE THREAD

**Issue by AgneLukoseviciute** [microsoft/react-native-windows#9711]
In the CLI, we currently distinguish between a UWP/WinUI2 app and WASDK/WinUI3 using the `--winui3` flag. As support for more WinAppSDK configurations lands, we'll need a way to specify the kind of app that should be built in the CLI (unpackaged, MSIX packaged, WAP packaged). Proposed approach:
________
we should likely rename / rethink this flag [--usewinui3]. I think we'll want something like:
`--projectTemplate` which takes a value of one of: `uwp`,  `winappsk-single`, `winappsdk-wap`, etc.

_Originally posted by @asklar in https://github.com/microsoft/react-native-windows/pull/9177#discussion_r827640833_
_________

**Comment by chrisglein** [comment]
Tricky aspect: This needs to work for all versions of RNW. So what we change it to needs to balance pre and post WinAppSDK.

**Comment by chrisglein** [comment]
Back in late 2021 / early 2022 we started a WinAppSDK new app template based on understanding of WinAppSDK at the time. And then came [Fabric](https://github.com/microsoft/react-native-windows/issues/12042) and impact on our overall strategy for how to handle Win32/WinAppSDK. As such these original plans don't make as much sense and we'll be closing them as Not Planned. That's not in any way to say RNW isn't going to support WinAppSDK, we're just doing it differently! Track our [Fabric](https://github.com/microsoft/react-native-windows/issues/12042) progress for details on the new app template and how that'll be compatible with WinAppSDK.
