### ISSUE TITLE
Display build/launch progress _somewhere_ when starting Debug via F5 in vscode

### ISSUE THREAD

**Issue by burtonrodman** [microsoft/react-native-windows#9716]
### Summary

when one uses `yarn run windows` there is a series of progress messages on build and launching events.

when one starts debugging in vscode by hitting F5, there no build progress to be seen and just a singular "Launching the application" message in the Debug console.

please display the same (or similar) information when launching via F5 as when launching via `yarn run windows`.

### Motivation

the app takes a long time to launch in development (which is a pain point unto itself).

frequent progress messages (including build log and useful failure details) assure the developer that their waiting is not in vain.

**Comment by chrisglein** [comment]
I don't believe this is something we can do here from the platform perspective (correct me if wrong), but there is a VSCode extension for RN and this could be a feature request for that. Can you open this up as a feature request [here](https://github.com/Microsoft/vscode-react-native)?

**Comment by burtonrodman** [comment]
I discovered while onboarding a new developer, that one CAN in fact see the verbose build output by selecting
`React Native: Run Windows` 
drop-down in the OUTPUT tab.
