### ISSUE TITLE
Move "platform-override-zero-permission-token" from Personal Identity to RNBot

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#9721]
https://github.com/microsoft/react-native-windows/blob/0498237784e3ab526bdd0a090ea401a999606543/.ado/windows-vs-pr.yml#L11

Anonymous API requests behind a NAT may be rate limited by GitHub, if other users within the NAT are doing the same. GitHub allows presenting an identity along with API requests, to be treated separately in terms of rate-limit quota. We do that today in our PRs using an OAuth token. Because it is run in a PR environment, this token is specially generated to have no permissions.

The token acts as an "identity" without permissions but is only revokable only by the owner of that identity.

I've discovered this identity is tied to my personal GitHub account. It should be updated to use RNBot as an identity instead.

**Comment by NickGerleman** [comment]
Let me know if it would make sense to revoke the token that's still associating with my personal account. It would interrupt PR/CI validation though.

**Comment by NickGerleman** [comment]
FYI that the token has been revoked.

**Comment by chrisglein** [comment]
@jonthysell @chiaramooney Addressed and safe to close this?

**Comment by chiaramooney** [comment]
Yes all done.
