### ISSUE TITLE
App using @react-navigation/drawer does not render in release build

### ISSUE THREAD

**Issue by dbm5858** [microsoft/react-native-windows#9732]
### Problem Description

Upgraded our app from RNW 0.63 to RNW 0.67.3.  Release build (`npx react-native run-windows --release`) now renders as a white page:

![image](https://user-images.githubusercontent.com/62263940/159718068-128078f0-7c0b-4d3a-9acc-2630821cbd3f.png)

Debug build renders and works as expected.

I've tried previous versions of `@react-navigation/drawer` and `react-native-screens`.  Can't find a working combination.

### Steps To Reproduce

1.  Create default C# RNW application
2.  Change .csproj to use native tool chain (required for Microsoft Store) (same behavior if not using native tool chain)
3.  Install `@react-navigation/native`, `@react-navigation/drawer`, and their dependencies
4.  Replace App.js with the code below
5.  `npx react-native run-windows --release`

### Expected Results

This screenshot is using the same code in a debug build (`npx react-native run-windows`):
![image](https://user-images.githubusercontent.com/62263940/159719888-f9ce119e-73a1-4d5f-923e-73ef22fa5e08.png)

### CLI version

6.4.0

### Environment

```markdown
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 3.83 GB / 15.86 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.5.4 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 30.0.2
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6858069
    Visual Studio: 16.9.31205.134 (Visual Studio Professional 2019)
  Languages:
    Java: javac 15 - C:\Users\MeilickD\dev\jdk-15\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Platform Version

10.0.16299

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2019

### Build Configuration

Release

### Snack, code example, screenshot, or link to a repository

```
import React from 'react';
import {Text} from 'react-native-windows';
import {NavigationContainer} from '@react-navigation/native';
import {createDrawerNavigator} from '@react-navigation/drawer';

const App: () => React$Node = () => {
    const DrawerNavigator = createDrawerNavigator();
    return (
        <NavigationContainer>
            <DrawerNavigator.Navigator initialRouteName="Hello">
                <DrawerNavigator.Screen name={'Hello'} component={Hello} />
            </DrawerNavigator.Navigator>
        </NavigationContainer>
    );
};

const Hello = () => <Text>Hello World!</Text>;

export default App;
```

**Comment by chrisglein** [comment]
Upgrading from 0.63 to 0.67 is a big jump, including changes to threading assumptions that affect modules. How did you perform the [upgrade](https://microsoft.github.io/react-native-windows/docs/upgrade-app)? Did you recreate the app from the CLI, use the upgrade helper and apply custom diffs, or increase the package version? What versions of react-navigation and screens are you using?

For an updated example of RNW using those modules, check out [react-native-gallery](https://github.com/microsoft/react-native-gallery).

**Comment by dbm5858** [comment]
@chrisglein : I recreated the app from scratch.  Then added our code back in.

But more to the point, the code for App.js above is a complete example of recreating the problem.  Create a new RNW app, replace App.js with the code above, do a release build, and the app will render only a white screen.

react-navigation version are the latest and greatest.  For the two components used above, that would be:
```
    "@react-navigation/drawer": "^6.3.1",
    "@react-navigation/native": "^6.0.8",
```
Sorry, I should have included that info.

**Comment by dbm5858** [comment]
I provided the requested feedback.  Why hasn't the "needs author feedback" label been removed?

**Comment by chiaramooney** [comment]
Currently the react-native-gallery app is running on 0.68 with react-navigation  "@react-navigation/drawer": "^5.9.0",
    "@react-navigation/native": "^5.7.3"" and is successfully building in release and rendering its contents as expected. Note gallery is a C++ RNW app and not C#. 

@jonthysell Is there something about the C# configuration that could affect this scenario?

**Comment by dbm5858** [comment]
@chiaramooney : 

I created a new application using RN 0.68 and RNW 0.68.

I installed the latest @react-navigation/native and /drawer, and the two required dependencies react-native-screens react-native-safe-area-context.  

I get the same behavior.  The App.js above renders as a blank page in a release build.  Debug build works correctly.

I uninstalled the react-navigation components and dependencies.  Then installed the versions that you mentioned above.  Same behavior.

Note that when I did that, I was using the latest react-native-screens and react-native-safe-area-context.  Maybe that is the problem?  What version of these components is the gallery app using?

**Comment by chiaramooney** [comment]
Ah that might be it. Currently the Windows implementation of screens has a bug that results in a blank screen when you return to a page you've previously visited. It's possible there are other actions that lead to that state as well. Currently gallery is using "react-native-safe-area-context": "^3.1.0",
"react-native-screens": "^2.9.0",
 
in order to compensate for this. @dbm5858

**Comment by dbm5858** [comment]
@chiaramooney 

Screens?  Why is it always screens?  ;-)

I tried installing those specific versions, but then ran into dependency errors for react-navigation.  So it apparently isn't as easy as just backing off those two components.  I'll keep trying, but progress is going to be slow here (the boss isn't paying me to work on this, and the team has already coded a quick-and-dirty replacement for the drawer.  But I'll keep trying).

Sidenote:  Shouldn't the Community Modules page also list which versions of the modules are valid?  I know that is a big ask.  And maybe not even useful, since it would then have to get into the whole dependency tree.  Arg.

On the other hand, is the package.json for the gallery app maybe a proxy for the validated versions?  Is there any time given to keeping that up to date, or is it just left alone once a particular component is up and working?

I guess my point is that someone starting off from scratch, with a new app, is going to follow all of the installation instructions, and then be sorely disappointed when things don't work.

This is a really messy problem.

**Comment by dbm5858** [comment]
@chiaramooney:  I can confirm that using the versions from the gallery app, the drawer works properly in a release build.
```
npx react-native init Drawer3 --template react-native@^0.68.0
cd Drawer3
npx react-native-windows-init --overwrite --language cs
npm install @react-navigation/native@5.7.3
npm install react-native-screens@2.9.0
npm install react-native-safe-area-context@3.1.0
npm install @react-navigation/drawer@5.9.0
npm install react-native-gesture-handler@JaneaSystems/react-native-gesture-handler#windows
npm install react-native-reanimated@1.10.0
```

The problem with this is that some of these are +really+ old.  And according to `npm audit`, there are 4 high severity vulnerabilities by using these versions.  So I'm not eager to use this set of components.

Found this https://github.com/react-navigation/react-navigation/issues/10264.  I'll the `useLegacyImplementation={false}` work-around suggested there.  Although it isn't a perfect match for what I'm experiencing.  But this and other tickets seem to point to react-native-reanimated as the culprit.

**Comment by dbm5858** [comment]
@chiaramooney :  I just did a release build using the latest version of all components except `react-native-reanimated`.  This build runs correct.  So it would seem that `reanimated` is the culprit.

```
  "dependencies": {
    "@react-navigation/drawer": "^6.4.1",
    "@react-navigation/native": "^6.0.10",
    "react": "17.0.2",
    "react-native": "0.68.0",
    "react-native-gesture-handler": "github:JaneaSystems/react-native-gesture-handler#windows",
    "react-native-reanimated": "^1.10.0",
    "react-native-safe-area-context": "^4.2.4",
    "react-native-screens": "^3.13.1",
    "react-native-windows": "0.68.0"
  },
```

I'll start testing with other version of RNA.  I see that they just released 2.6 4-days ago.  Dare I hope?

**Comment by chiaramooney** [comment]
Thanks for all this context @dbm5858! From time to time we update the versions of the packages in react-native-gallery depending on if there is a change we are specifically looking to take in, but it would probably be good practice to at least refresh these with each RNW release to catch problems occurring with more recent version. Glad to hear you found the culprit! I'll go ahead and close this issue now!

**Comment by taduyde** [comment]
@chiaramooney the same issue.

**Comment by chrisglein** [comment]
This issue was closed a few months ago. Which issue were you referring to? Did you want to open a new issue with fresh context/version information?
