### ISSUE TITLE
Support react-native-foo

### ISSUE THREAD

**Issue by VarunTwri** [microsoft/react-native-windows#9734]
### Module

react-native-viewmanager for windows native

### Module repo url

NA(Local implementation)

### Existing windows implementation?

- [ ] Legacy/C# implementation

### In what scenarios will this module be used?

**Unable to see Windows Native uwp component on integration with react-native:**
Things tried:
Implemented IViewManager and Microsoft.ReactNative.IViewManagerRequiresNativeLayout interface.
as suggested but still can't view component but able to use component.
override the CreateView also , but didn't helped.
please find the attached below images:
![image](https://user-images.githubusercontent.com/102298041/159911705-58cd0372-4d6a-4194-868d-3540cf150b57.png)
![image](https://user-images.githubusercontent.com/102298041/159912044-68c3e72a-d30b-4758-89cd-9afe020e6d5c.png)

### Essential Features

ViewManager Module to integrate uwp Application with react native.
Need to get react view for that component.

**Comment by chrisglein** [comment]
The issue form you used is for requests for Windows support to existing modules. I'm not able to find [react-native-viewmanager](https://reactnative.directory/?search=viewmanager) in the directory. Are you trying to create a new community module? Can you share some source for what you're trying to do that isn't working?

**Comment by VarunTwri** [comment]
@chrisglein 
I referenced and created from below link:

https://microsoft.github.io/react-native-windows/docs/view-managers

**Comment by chrisglein** [comment]
Can you include the source of what you tried so we can reproduce?

**Comment by VarunTwri** [comment]
We tried it with whatever code snippet were there in above link.
Also tried below repo but unable to run:
https://github.com/microsoft/react-native-windows/tree/main/packages/sample-apps
(Above repo is also given in previously given link)
