### ISSUE TITLE
Add Support for accessibilityLanguage

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-windows#9748]
### Summary

https://github.com/facebook/react-native/commit/7b05b091fd97f95b778369277ac2147730abc7b8 Tadded an `accessibilityLanguage` prop to all the available components. This props is currently working only on iOS and should follow the [guidelines of the relative configuration](https://developer.apple.com/documentation/objectivec/nsobject/1615192-accessibilitylanguage).

### Motivation

Maintain alignment with upstream.

**Comment by chrisglein** [comment]
Not hits searching https://reactnative.dev/ for this. I take it it's not in the docs yet?
With this being iOS only it's not yet universal for React Native. Is there a Windows feature that would map directly to this? (iOS description is "The language to use when speaking the accessibility element's label, value, and hint.") Is it in UIA if not in XAML?
@AgneLukoseviciute FYI
