### ISSUE TITLE
Hermes repeatable builds for NuGet packages

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#9772]
1) We don't currently keep good track of code that went into a certain Hermes NuGet release, e.g. there is a 0.9.0-ms branch, but that doesn't exactly match the code in the 0.9.0-ms.**4** package (we get mismatched source warnings in the debugger).
This is because the branch seems to track only the latest for a given version.
It's important we address this for compliance / security reasons as well as debuggability.

2) The Hermes symbols seem to only available in symweb; they should be available in the public Microsoft symbol server.

**Comment by asklar** [comment]
CC @tudorms @dedavis6797 @Khalef1

**Comment by chrisglein** [comment]
@Khalef1 Should we track this on https://github.com/microsoft/hermes-windows/issues? (can transfer if so). Doesn't look like new issues are getting triaged - happy to work together to set something up for that.

**Comment by Khalef1** [comment]
Chatted offline with @dedavis6797 . We will start triages in our weekly syncs. This issue should go to the Hermes repo IMO

**Comment by Khalef1** [comment]
Tracked in the Hermes-Windows repo - https://github.com/microsoft/hermes-windows/issues/91.
