### ISSUE TITLE
Back event handler probably doesn't work

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#9773]
Found this while investigating another issue, I think this is broken now:
![image](https://user-images.githubusercontent.com/22989529/161450021-56aca35c-49bd-4d8b-b060-208771fb7a90.png)

[RCTEventEmitter](https://github.com/facebook/react-native/blob/5dff920177220ae5f4e37c662c63c27ebf696c83/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js#L1080) does not have an `emit` method.

**Comment by NickGerleman** [comment]
How are you looking for the interface of `RCTEventEmitter`? From the interfaces below, the above example seems like it would be valid.

1. https://github.com/facebook/react-native/blob/main/Libraries/EventEmitter/RCTDeviceEventEmitter.js
2. https://github.com/facebook/react-native/blob/main/Libraries/vendor/emitter/EventEmitter.js

Do you have a repro where the functionality does not work as expected?
