### ISSUE TITLE
Fill Windows TS Gaps in react-native for Future Releases

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-windows#9817]
### Summary

Issue raised in RN Release Weekly Sync. Request to RNW dev to take on this effort for each release. 

Meta uses Flow for typing instead of TS, thus they don't care about the TS types for their libs which leads to situations where people from the community need to fill the gap to make the libraries usable with Typescript. For react-native, there's the same problem. The goal would be for the RNW teams to take ownership of doing these TS types updates  in @types/react-native when new releases come out.

@tido64 brought up that we have a tool [microsoft/flow2dts: Flow declarations to TypeScript declarations transpiler (github.com)](https://github.com/microsoft/flow2dts) that should help make that process faster/smoother because it relies on the pre-existing Flow typings in the source code to generate the TS stuff. 

The idea would be to use the tool -> gen TS types -> ensure that they are correct and working -> open a PR against this [DefinitelyTyped/index.d.ts at master · DefinitelyTyped/DefinitelyTyped (github.com)](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-native/index.d.ts).

### Motivation

We have a number of partners and React Native Gallery that are reliant on TS, so it seems it's in our interest to support this.

**Comment by jonthysell** [comment]
@chrisglein Are we able to take on maintaining TS types for RN core?
