### ISSUE TITLE
Auto-expanding TextInput broken as of #966

### ISSUE THREAD

**Issue by rozele** [Microsoft/react-native-windows#983]
Previously, the height was not explicitly set on the text box because it was "computed" by the text in the box.  This conflicts with the ability for the user to explicitly set the height.  We need a better solution that accomodates both.

**Comment by dlajarretie** [comment]
https://github.com/facebook/react-native/commit/481f560f64806ba3324cf722d6bf8c3f36ac74a5

According to this commit on RN, the preferred way of sizing the TextInput is by listening to the onChange event, and then setting the height explicitly.

I don't think the "auto grow" should be implemented natively, so I guess we need to have this onChange event returning some layout info.

**Comment by rozele** [comment]
Closing, this is basically a dupe of #272
