### ISSUE TITLE
Once we try to create a simple React windows application version 0.68 and tried to run the same facing below build failing issue

### ISSUE THREAD

**Issue by VarunTwri** [microsoft/react-native-windows#9836]
### Page url

https://reactnative.dev/blog/2022/03/30/version-068#highlights-of-068

### Problem Description

Once we try to create a simple React windows application version 0.68 and tried to run the same facing below build failing issue.
Also could you please help me to switch to new ReactNative architecture.
![image](https://user-images.githubusercontent.com/102298041/163119146-e4139146-92e0-4b39-ac5f-3bbc2f901dc8.png)

**Comment by jonthysell** [comment]
What steps did you follow to create the new app? Was this error after trying to use the "new architecture"? Note that RNW does not yet support the new architecture.

**Comment by NickGerleman** [comment]
Like Jon mentioned, the recent "new architecture" opt-in is meant for iOS/Android, though there has been a lot of work behind the scenes to eventually allow similar features to users of RNW. You can use C++ TurboModules with RNW today, but it does not have a fully fleshed out story for C++ interface code generation from TS interfaces. Most internally provided modules will already run as TurboModules in release builds as well. Fabric is further out though, I think.
