### ISSUE TITLE
Enabling "Break on First Line" in the Developer Menu (Ctrl+Shift+D) does not cause the app to break on the first line

### ISSUE THREAD

**Issue by GriffinSoliminiMSFT** [microsoft/react-native-windows#9859]
### Problem Description

Enabling "Break on First Line" in the Developer Menu (Ctrl+Shift+D) does not cause the app to break on the first line. 

### Steps To Reproduce

1. Create a new React Native Windows Sample app
2. Run: npx react-native run-windows
3. Open developer menu (Ctrl+Shift+D) while running the app
4. Activate "Break on First Line" option in developer menu
5. Observe that the app starts as normal, and does not break

### Expected Results

Expected the app to break on first line until a debugger was attached.

### CLI version

6.4.0

### Environment

```markdown
System:
    OS: Windows 10 10.0.19044
    CPU: (20) x64 Intel(R) Xeon(R) W-2255 CPU @ 3.70GHz
    Memory: 35.23 GB / 63.69 GB
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.32407.337 (Visual Studio Enterprise 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.67.3 => 0.67.3
    react-native-windows: 0.67.7 => 0.67.7
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2019

### Build Configuration

Debug

**Comment by jonthysell** [comment]
Which JS engine are you using? Chakra? Hermes?

And are you reloading the JS after setting the option?
