### ISSUE TITLE
Can't install/build  with RNW

### ISSUE THREAD

**Issue by NickLeippe** [microsoft/react-native-windows#9879]
### Problem Description

VS 2019

With neither npm install nor yarn add to a base RNW project the result will not build.
Tried updating  NuGet packages.
Tried numerous variations on order of install, settings changes.
Produces errors every time.

### Steps To Reproduce

npx react-native init abc --template react-native@^0.68.0 # installs 0.68.1
cd abc
npx react-native-windows-init --overwrite

either:
npm install react-native-webview
or:
yarn add react-native-webview --save

npx react-native autolink-windows

either build via VS 2019 gui or via cli with npx react-native run-windows results in voluminous errors.

### Expected Results

successfully builds and runs application.

### CLI version

7.0.3

### Environment

```markdown
npx react-native info
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19043
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 24.51 GB / 31.93 GB
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.16299.0, 10.0.17134.0, 10.0.17763.0, 10.0.18362.0, 10.0.19041.0, 10.0.22000.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.32413.511 (Visual Studio Community 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.1 => 0.68.1
    react-native-windows: 0.68.1 => 0.68.1
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2019

### Build Configuration

Debug

**Comment by asklar** [comment]
@chiaramooney fyi, I was able to repro the "can't build" in a fresh app too. Also tagging @JunielKatarn 
Looks like this might be a combination of the webview2 changes colliding with the PackageReference stuff.
Now that RNWebview uses winui 2.8.x, that's what gets restored. However the webview vcxproj references the 2.7 version of props/targets since it doesn't know which version will ultimately be restored.

**Comment by chiaramooney** [comment]
@asklar @NickLeippe When using react-native-webview within an RNW app that is 0.68+ specifying specifying WinUI2xVersion as 2.8.0-prerelease.210927001 in ExperimentalFeatures.props is necessary because the module depends on the WinUI WebView2 control which is only present in WinUI 2.8.0-prerelease.210927001 or higher. Currently RNW 0.68 uses WinUI 2.7, so we have to use the ExperimentalFeatures workaround to override the WinUI version for now.

**Comment by NickLeippe** [comment]
I tried that and it didn't fix it.

**Comment by asklar** [comment]
if you run `yarn windows --logging`, it will spew out a bunch of info, and it should show the errors in red.

I just tried this and I see there's another additional layer where this is failing: conflict between the global webview2 nuget that is fetched by PackageReference, and the packages.config one:

```
     2>F:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(1946,5): error APPX1112: Payload contains two or more files with the same destination path 'WebView2Loader.dll', but they have different content. Source files:  [F:\testWebView\windows\testwebview
       \testwebview.vcxproj]
F:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(1946,5): error APPX1112: C:\Users\asklar\.nuget\packages\microsoft.web.webview2\1.0.1018-prerelease\build\native\x64\WebView2Loader.dll [F:\testWebView\windows\testwebview\testwebview.vcxproj]
F:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(1946,5): error APPX1112: F:\testWebView\windows\packages\Microsoft.Web.WebView2.1.0.1020.30\build\native\x64\WebView2Loader.dll [F:\testWebView\windows\testwebview\testwebview.vcxproj]
```

@JunielKatarn  any ideas?

**Comment by chiaramooney** [comment]
Fix found. PR out now.

**Comment by JunielKatarn** [comment]
> if you run `yarn windows --logging`, it will spew out a bunch of info, and it should show the errors in red.
> 
> I just tried this and I see there's another additional layer where this is failing: conflict between the global webview2 nuget that is fetched by PackageReference, and the packages.config one:
> 
> ```
> error APPX1112: Payload contains two or more files with the same destination path 'WebView2Loader.dll', but they have different content. 
> 
> APPX1112: C:\Users\asklar\.nuget\packages\microsoft.web.webview2\1.0.1018-prerelease\build\native\x64\WebView2Loader.dll 
> APPX1112: F:\testWebView\windows\packages\Microsoft.Web.WebView2.1.0.1020.30\build\native\x64\WebView2Loader.dll 
> ```
> 
> @JunielKatarn any ideas?

I'll take a look at the bug and Chiara's PR.

**Comment by NickLeippe** [comment]
Okay, if you edit ExperimentalFeatures.props and add:
<WinUI2xVersion>2.8.0-prerelease.210927001</WinUI2xVersion>

It does successfully build.
Also, the sample in the docs fails to set width and height, without which it doesn't display anything.
