### ISSUE TITLE
Document the architecture

### ISSUE THREAD

**Issue by LifeIsStrange** [microsoft/react-native-windows#9920]
### Summary

What is the architecture of react native for windows?
In Android I believe you use the Skia 2D renderer (like flutter and chromium).
What rendering library do you use on windows?
To you do direct calls to GDI+/direct2D/directwrite?
To you internally leverage WPF/.NET ?
Beyond the 2D renderer, what is the high level architecture? Display lists? What operations (scrolling, inputs, etc) are off the main thread.
How does clipping works?
Caches, etc
Publishing rendering benchmarks would give credence to the project too.

### Motivation

Without this comparison with other GUIs is impossible. 

### Basic Example

.

### Open Questions

.

**Comment by chrisglein** [comment]
@LifeIsStrange That's a broad set of topics. Can you clarify what you'll be using this information for? RNW is built on top of UWP XAML and a lot of your questions will match what that UI framework is capable of. What isn't present in the docs (http://aka.ms/reactnative) that you would expect to see?

**Comment by asklar** [comment]
@LifeIsStrange, this repo is for the Windows endpoint of React Native. Other platforms are handled in their respective repos: 
- http://github.com/microsoft/react-native-macos (for macos)
- https://github.com/facebook/react-native (for ios and android)

Your app doesn't need to be limited to lowest common denominator, you can have platform specific code in your app or components.

In regard to which properties are not supported yet, you can check out the issues list for issues marked api completion: https://github.com/microsoft/react-native-windows/labels/API%3A%20Completion
