### ISSUE TITLE
Microsoft.ReactNative.winmd missing when updating a previously created project to use Experimental Nugget

### ISSUE THREAD

**Issue by Samuubs** [microsoft/react-native-windows#9937]
### Problem Description

I'm trying to add the experimental nugget to an existing project. But the following error is always happening.
`Metadata file 'C:\TestApp\node_modules\react-native-windows\Microsoft.ReactNative\target\Microsoft.ReactNative\Microsoft.ReactNative.winmd' could not be found	Microsoft.ReactNative.Managed`

I'm following all steps described here https://microsoft.github.io/react-native-windows/docs/NuGet.

The app project itself build successfully, but the error comes from the `Microsoft.ReactNative.Managed`. Where is missing the `Microsoft.ReactNative` reference.
![image](https://user-images.githubusercontent.com/33751384/167429685-76440ca3-1662-4e34-b476-f80d46532335.png)

Even if I try to run on the local machine with the error I get an "Invariant Violation Error" on the Javascript side. 

I already removed all the old react-native references, so I don't know why `Microsoft.ReactNative.Managed` is asking for this dependency. 
![image](https://user-images.githubusercontent.com/33751384/167430450-e3eaacc2-2070-4074-b3c5-9f7b07280c6a.png)

### Steps To Reproduce

1. npx react-native init TestApp --template react-native@^0.68.0
2. npx react-native-windows-init --overwrite --language cs
3. Edit the file windows\ExperimentalFeatures.props
`<UseExperimentalNuGet>true</UseExperimentalNuGet>`
4. Add a NuGet reference to Microsoft.ReactNative.Managed 
```
<ItemGroup>
  <PackageReference Include="Microsoft.ReactNative.Managed">
    <Version>0.68.3</Version>
  </PackageReference>
</ItemGroup>
```

### Expected Results

All projects should build successfully.

### CLI version

7.0.3

### Environment

```markdown
System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 9.50 GB / 23.88 GB
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      Versions: 10.0.17134.0, 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.31702.278 (Visual Studio Community 2019), 16.11.31702.278 (Visual Studio Enterprise 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.0 => 0.68.0
    react-native-windows: 0.68.3 => 0.68.3
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2019

### Build Configuration

Debug

**Comment by jonthysell** [comment]
If you're on RNW 0.68 you shouldn't need to modify your project files, but you **will** need to remove the projects from the solution file.

Note, it may be easier to run `react-native-windows-init` with the `--experimentalNuGetDependency` flag to get the right behavior in the generated build files.

**Comment by jonthysell** [comment]
@jonthysell  to update the docs.
