### ISSUE TITLE
Desktop requires nuget packages not available on NuGet.org

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#9997]
### Problem Description

In trying to bring us into compliance wrt. NuGet configurations, I tried to remove the `react-native-public` feed from our NuGet.config files.

Unfortunately, this broke the build, because several `ReactWindows.*` packages (`ReactWindows.OpenSSL.StdCall.Static` and `ReactNative.V8Jsi.Windows`) have not published their latest versions to NuGet.org, only to the internal feed.

```
vnext\Desktop.DLL\React.Windows.Desktop.DLL.vcxproj(0,0): Error NU1603: React.Windows.Desktop.DLL depends on ReactWindows.OpenSSL.StdCall.Static (>= 1.0.2-p.5) but ReactWindows.OpenSSL.StdCall.Static 1.0.2-p.5 was not found. An approximate best match of ReactWindows.OpenSSL.StdCall.Static 1.1.1-d.0 was resolved.
vnext\Desktop.ABITests\React.Windows.Desktop.ABITests.vcxproj(0,0): Error NU1603: React.Windows.Desktop.DLL depends on ReactWindows.OpenSSL.StdCall.Static (>= 1.0.2-p.5) but ReactWindows.OpenSSL.StdCall.Static 1.0.2-p.5 was not found. An approximate best match of ReactWindows.OpenSSL.StdCall.Static 1.1.1-d.0 was resolved.
vnext\Desktop.IntegrationTests\React.Windows.Desktop.IntegrationTests.vcxproj(0,0): Error NU1603: React.Windows.Desktop.IntegrationTests depends on ReactWindows.OpenSSL.StdCall.Static (>= 1.0.2-p.5) but ReactWindows.OpenSSL.StdCall.Static 1.0.2-p.5 was not found. An approximate best match of ReactWindows.OpenSSL.StdCall.Static 1.1.1-d.0 was resolved.
vnext\Desktop.ABITests\React.Windows.Desktop.ABITests.vcxproj(0,0): Error NU1102: Unable to find package ReactNative.V8Jsi.Windows with version (>= 0.65.11)
  - Found 26 version(s) in nuget.org [ Nearest version: 0.64.4 ]
 vnext\Desktop.IntegrationTests\React.Windows.Desktop.IntegrationTests.vcxproj(0,0): Error NU1102: Unable to find package ReactNative.V8Jsi.Windows with version (>= 0.65.11)
  - Found 26 version(s) in nuget.org [ Nearest version: 0.64.4 ]
 ```

### Steps To Reproduce

Remove `react-native` ADO feed from NuGet configuration.
Try to build Desktop

### CLI version

npx react-native --version

### Environment

```markdown
npx react-native info
```

**Comment by jonthysell** [comment]
@JunielKatarn Can we consume the newer OpenSSL package to resolve that?

@dannyvv Can we get the V8JSI package we need published to nuget.org?

Then we could remove this requirement on the react-native-public from our repos then it'll be much easier to meet the multifeed requirements.

**Comment by JunielKatarn** [comment]
> @JunielKatarn Can we consume the newer OpenSSL package to resolve that?
> 
> @dannyvv Can we get the V8JSI package we need published to nuget.org?
> 
> Then we could remove this requirement on the react-native-public from our repos then it'll be much easier to meet the multifeed requirements.

The package can be pushed to nugget.org too

**Comment by JunielKatarn** [comment]
I have pushed package `ReactWindows.OpenSSL.StdCall.Static`, version `1.0.2-p.5` to nuget.org.

It will be available shortly.

**Comment by jonthysell** [comment]
Ping @JunielKatarn / @dannyvv  on this? Is is possible to get `ReactNative.V8Jsi.Windows` regularly published to nuget.org?

**Comment by JunielKatarn** [comment]
@tudorms Can you please confirm whether this is possible?

**Comment by tudorms** [comment]
We removed the V8 package from NuGet over similar compliance requirements (multiple feeds) sometime last year. @dannyvv has more background. I believe it was something related to package naming, reservations and/or signing requirements.

**Comment by jonthysell** [comment]
Can we do the opposite, and just push all the packages Desktop needs to `react-native-public` instead?

| Package | Version |
| :- | -: |
| boost | 1.76.0.0 |
| Microsoft.Build.Tasks.Git | 1.0.0 |
| Microsoft.googletest.v140.windesktop.msvcstl.static.rt-dyn | 1.8.1 |
| Microsoft.SourceLink.Common | 1.0.0 |
| Microsoft.SourceLink.GitHub | 1.0.0 |
| Microsoft.Windows.CppWinRT | 2.0.211028.7 |
| ReactNative.Hermes.Windows | * |

**Comment by jonthysell** [comment]
I'm trying to resolve these issues in PR #10332
